### ISSUE TITLE
Column not found on orderBy

### ISSUE THREAD

**Issue by mprandot** [yajra/laravel-datatables#1000]
Hello!

I have a datatables with one OTF column (nome_razao_cliente).
This column not exists in any table.
To search in this column, i use filterColumn() method.
But when click on column header (to order),  datatables returns column not found SQL error.

``` SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nome_razao_cliente' in 'order clause'  ```

``` 
->filterColumn('nome_razao_cliente', function ($query, $keyword) {
    $query->whereRaw("pessoas.nome like ?", ["%{$keyword}%"]);
    ...
})
```
I've not found nothing about like "orderColumn.."Can help me?

- Operating System : Linux/Ubuntu
- PHP Version: 7
- Laravel Version: 5.1
- Laravel-Datatables Version : v6.24.4

**Comment by yajra** [comment]
See [orderColumn](https://yajrabox.com/docs/laravel-datatables/7.0/order-column) api for ref. Thanks!
