### ISSUE TITLE
Error when updating HTML

### ISSUE THREAD

**Issue by jim1506** [yajra/laravel-datatables#1001]
### Summary of problem or feature request

In the doucmentation you state:

composer require yajra/laravel-datatables-html:^1.0

However when I did this it placed 

"yajra/laravel-datatables-html": "1.0",

and so uninstalled 1.1 and replaced it with 1.0

I changed the line to

"yajra/laravel-datatables-html": "^1.0",

and it worked fine.

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
Compose added this `"yajra/laravel-datatables-html": "1.0",`? That would load the exact version 1.0 and `^1.0` is correct version constraint AFAIK.

**Comment by redalpha01** [comment]
Issue might be with some other requirements. Couldn't update the core from 7.0 to 7.1 because I was forcing symfony/css-selector and dom-crawler to 3.1 when it needed 3.2

**Comment by yajra** [comment]
Have made some change, can you please try updating to v7.2.1? Thanks!

**Comment by jim1506** [comment]
When I try php artisan datatables:make UsersDataTable I am getting no commands in the namespace.
