### ISSUE TITLE
Exception in Datatables.php line 52: No available engine for Illuminate\Database\Eloquent\Collection

### ISSUE THREAD

**Issue by Mostafa-kalantar** [yajra/laravel-datatables#1003]
Problem when getting data

I have updated laravel-datatables to 7.0 and I'm using laravel 5.4. The problem is i cant use my Models Directly and i have to use DB to return the query, If i use Model::ModelName, I get this error:
Exception in Datatables.php line 52: No available engine for Illuminate\Database\Eloquent\Collection

My Controller:
```
$var = ModelName::all();
return Datatables::of($var)
  ->make(true);
```
My View
```
var dt = '';
     $(document).ready(function () {

         dt = $('#table').DataTable({
             processing: true,
             serverSide: true,
             ajax: {
                 url: '{!! route('route') !!}',
                 type: 'POST'
             },
             columns: [
                 {data: 'data'},
             ]
         });
     });
```
I'm sure the Model works. I can dd the response but Whenever i use Model I get error and If i use DB like:
`$var = DB::table('table')->select('*')->whereNull('deleted_at');`  
Everything works!

- Operating System: Windows 8.1
- PHP Version: 5.6.30
- Laravel Version: 5.4
- Laravel-Datatables 7.0

**Comment by yajra** [comment]
Please update to the latest version or at least `^7.1`. Thanks!

**Comment by yajra** [comment]
And you may need to force publish the config.

```
php artisan vendor:publish --tag=datatables --force
```
