### ISSUE TITLE
Parameters not used

### ISSUE THREAD

**Issue by klausd** [yajra/laravel-datatables#1004]
Hi,

I have combined this plugin with vue-table-2 in Laravel 5.4. This works pretty good, but the parameters are not used so I just get the complete, unfiltered, list of records.

Obviously I'm overlooking something very stupid. 

I've tried debugging the ajax route directly with Datatable parameters. But it keeps sending the whole list. It's not using the parameters. 

Thank you in advance for pointing out my mistake.

```php
//ajax route
Route::get('/project-ajax/',['uses'=>'ProjectController@anyData', 'as' => 'project.data']);

//anyData() in controller
public function anyData(Request $request)
{
    $leads = Company::all(); 
    return Datatables::of($leads)->make(true);
}
```

**Comment by yajra** [comment]
I think it's because you are using collection. Try using query instead of all.

```php
public function anyData(Request $request)
{
    $leads = Company::query(); 
    return Datatables::of($leads)->make(true);
}
```

Also, make sure you don't use form names like `start, columns, search, draw, etc..` as it is reserved to dataTables script.
