### ISSUE TITLE
Using POST instead of GET parameters

### ISSUE THREAD

**Issue by szepeviktor** [yajra/laravel-datatables#1005]
Hello!
I am maintaining a Laravel project and there are 2-3 kB long request URI-s because of the amount of GET params.

Would it be possible to implement an option for the request method?
AFAIK jquery datatables supports POST.

**Comment by yajra** [comment]
Yes, see this [demo](https://datatables.yajrabox.com/eloquent/post-column-search) for some ref.

**Comment by szepeviktor** [comment]
Thank you for your support.
