### ISSUE TITLE
Can't see the buttons CSV PDF etc

### ISSUE THREAD

**Issue by reiter777** [yajra/laravel-datatables#1007]
hi @yajra i did what you post in the issue #481
```php
->parameters([
'dom' => 'Bfrtip',
'buttons' => ['csv', 'excel', 'pdf', 'print', 'reset', 'reload'],
]);
```
but still can not see the Buttons, and also the button of show entries is missing when i put those lines man, how can i fix this problem man? is this working for laravel 5.4?

- Windows
- php>7
- laravel 5.4
- datatables version 7

**Comment by yajra** [comment]
Try inspecting the web console first. There must be something wrong with your javascripts.

**Comment by reiter777** [comment]
I dont see any errors at the console man. 
![console](https://cloud.githubusercontent.com/assets/6207721/22981431/016bd188-f362-11e6-9be2-10aca1832a3b.png)

And here is the code where i put what you said.
![return](https://cloud.githubusercontent.com/assets/6207721/22981515/38c5e506-f362-11e6-8341-18b5d28c902d.png)

**Comment by reiter777** [comment]
i solved the problem im closing the issue thank you!

**Comment by 91Abdullah** [comment]
How did you resolved this?

**Comment by irvv17** [comment]
How did you resolved this?

**Comment by rommelandrea** [comment]
@reiter777 Can you post the solution?

**Comment by geekstek** [comment]
add 
```
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="/vendor/datatables/buttons.server-side.js"></script>
```
then buttom shown
