### ISSUE TITLE
In v3.0, sort doesn't work for cols with no name

### ISSUE THREAD

**Issue by Robarelli** [yajra/laravel-datatables#101]
Seems to be an issue that's not allowing column sorting to work. Line 664:
```php
} elseif (isset($columns[$order_col])) {
    $this->query->orderBy($columns[$order_col], $order_dir);
}
```
There is no local $columns var. When I change it to $this->columns to match the rest of the function it seems to work.

```php
} elseif (isset($this->columns[$order_col])) {
    $this->query->orderBy($this->columns[$order_col], $order_dir);
}
```

**Comment by yajra** [comment]
@Robarelli, I think this was already fixed. Try updating your package to latest which is v3.6.5.

**Comment by yajra** [comment]
@Robarelli, updating the package should fixed the issue. Closing this one. Thanks!
