### ISSUE TITLE
Id column problem with service datatable

### ISSUE THREAD

**Issue by alko79** [yajra/laravel-datatables#1011]
### Summary of problem or feature request

Problem appeared on service method only, same code is working on normal method

### Code snippet of problem
This is working as planned eltime parameter is the id of the table:
`$reading= CDTime::with('comm','cdtask','cdoperator')->get();
 return Datatables::of($reading)
                    ->editColumn('id', function($reading) {return  '<td><a class="btn btn-danger" href="http://1.111.1.111:81/cloud1/nov/cloud/public/eltime/'.$reading->id.'" role="button">Delete</a></td>';})`

But same code on service method instead is returning not the id but another column CDJob_id that is a referenced column for jobs table:
`public function query(){
       $reading = CDTime::query()->with('comm','cdtask','cdoperator');
       return $this->applyScopes($reading );
}`
`public function ajax(){
        return $this->datatables
               ->eloquent($this->query())
               ->editColumn('id', function($reading ) {return  '<td><a class="btn btn-danger" href="http://1.111.1.111:81/cloud1/nov/cloud/public/eltime/'.$reading->id.'" role="button">Delete</a></td>';})`

this is the times model:
`class CDTime extends Model
{
  protected $fillable = [
    'CDOperator_id',
    'CDTask_id',
    'CDJob_id',
...

];
protected $table = 'cdtimes';
public $timestamps = false;
//public function cdjob() { return $this->belongsTo('App\CDJob','CDJob_id');}
public function comm() { return $this->belongsTo('App\Comm','CDJob_id');}
public function cdtask() { return $this->belongsTo('App\CDTask','CDTask_id');}
public function cdoperator() { return $this->belongsTo('App\CDOperator','CDOperator_id');}
public function reg() { return $this->belongsTo('App\Reg','Reg_id');}
}`

when i ask on service method id of table cdtimes i got id from table comm that is stored in CDJob_id.
but on normal method all is ok, asking column id i got id from table cdtimes.

### System details

- Operating System Windows server
- PHP Version 5
- Laravel Version 5
- Laravel-Datatables Version 7

**Comment by yajra** [comment]
@alko79 you need to add `select('dttime.*')` on your query to avoid this issue as documented [here](https://datatables.yajrabox.com/eloquent/relationships). Thanks!

**Comment by alko79** [comment]
yes I was going to post that this occurs on clicking ordering specifically.
it takes the id of whichever column i click to order but on first loading the url is correct,once i click order by some column if changes
 i read and apply that solution you suggested that will solve surely.
 cannot we specify the own table in columns in the future?
like data =id name= cdtimes.id or something similar?

**Comment by alko79** [comment]
ok that worked.
my friend from batangas here thank you also :) 
case closed
