### ISSUE TITLE
[Question] Why Service Implementation is removed in version 7.0

### ISSUE THREAD

**Issue by sangnguyenplus** [yajra/laravel-datatables#1012]
Hi @yajra,
Thanks for your hard works. I'm using your package and happy with it. But I have stuck with version 6.0. 
You removed Service Implementation feature in version 7.0.
https://datatables.yajrabox.com/service
Can you bring it back? It is a good feature to use.
Thanks!

**Comment by amamarul** [comment]
Hello!
now is in a different package.
you must require that package and it works!!
https://github.com/yajra/laravel-datatables-buttons

See that https://yajrabox.com/docs/laravel-datatables/7.0/upgrade

**Comment by sangnguyenplus** [comment]
Thanks!

**Comment by amamarul** [comment]
your welcome
