### ISSUE TITLE
Displaying only HTML text code in Laravel 5.4

### ISSUE THREAD

**Issue by marioene** [yajra/laravel-datatables#1013]
### Summary of problem or feature request
HTML Code in Datatable in Laravel 5.4, not parsing code in webpage, in Laravel 5.3.* is working ok.
The same behavior on your demo page: [Eloquent DataTable with Array Response](http://dt54.yajrabox.com/eloquent/array) in Action column.

Environment: Laravel 5.4, Acacha\Adminlte

### Code snippet of problem

```
    public function data()
    {
        DB::statement(DB::raw('set @rownum=0'));
        $result = My_Model::select(array(
            DB::raw('@rownum  := @rownum  + 1 AS rownum'),
            'created_at',
            'name'));
            
        $datatables = Datatables::of($result)
            ->edit_Column('rownum', '<div style="text-align:center;"><a class="btn btn-primary btn-xs">{{ $rownum }}</a></div>')
            ->edit_Column('created_at','<div style="text-align:center;">{{ App\Functions::setDateTime($created_at) }}')
            ->edit_Column('name', '<div style="text-align:left;"><a class="btn btn-success btn-xs">{{ $name}}</a></div>');

        return $datatables->make(true);
    }
```
Result displayed in datatable in webpage, just this text, not a button with value 1:

```
<div style="text-align:center;"><a class="btn btn-primary btn-xs">1</a></div>

```

### System details

- Operating System: Windows 7 Professional
- PHP Version: 7.0.10 (Laragon 2.2.2)
- Laravel Version: 5.4.11
- Laravel-Datatables Version: 7.1.4 & 7.2.1

**Comment by marioene** [comment]
Solved with solution from: [#909](https://github.com/yajra/laravel-datatables/issues/909)

Adding: 

`$datatables = Datatables::of($result)->rawColumns(['rownum','created_at','name'])`

**Comment by bayodesegun** [comment]
I couldn't get `->rawColumns([])` to work though, after trying whole day :(. Had to resolve grudgingly to `escapeColumns([])`.

### System details:
- Operating System: Windows 10
- PHP Version: 7.0.10
- Laravel Version: 5.4.17
- Laravel-Datatables Version: 7.2.0

Any ideas why this might happen? Thanks.

**Comment by kaled-999** [comment]
What's the solution?




 public function datatab(User $user)
    {

        $users = $user->all();
        return Datatables::of($users)
            ->editColumn('name', function ($model) {
                return '<a href="'.url('/data/users/' . $model->id . '/edit').'">'.$model->name.'</a>';
            })
            ->make(true);

    }

**Comment by mailnike** [comment]
whats the solution for this? rawColumn doesn't work. and escapeColumn basically removes HTML tags and only displays the image address. When I use editColumn 
```

->editColumn('image', function ($product_brand) {
                return '<img src="'.$product_brand->image.'" style="height:30px; width:30px" />';
            })

```
it just shows the html code in the image column
`
<img src="https://randomuser.me/api/portraits/men/1.jpg" style="height:30px; width:30px" />

`
Please let me know the solution where I can display this image. 
:(

**Comment by parthkharecha** [comment]
same here @marioene

**Comment by SubinRabin** [comment]
->escapeColumns([]) its working
