### ISSUE TITLE
Accessing relationnship in added column view

### ISSUE THREAD

**Issue by legreco** [yajra/laravel-datatables#1016]
Hello.  I m using laravel 5.4 and lavarel-datatables version 7. How to acces a relationnship properties in a view based column?

**Comment by minedun6** [comment]
If I got you correctly, it's like this

    `$parent->relation->relation_attribute`

**Comment by legreco** [comment]
I have a user model that can have many roles . I want to display a users table. I have a "roles" column and i want to display all the users roles as a list.

My user controller index:

` public function index(Request $request)
    {

        if($request->wantsJson())
        {
          $query=User::with('roles');
            return Datatables::of($query)
                ->addColumn('status','users.datatables.status')
                ->addColumn('roles','users.datatables.roles')
                ->addColumn('actions','users.datatables.actions')
                ->rawColumns(['status','roles','actions'])
                ->make(true);
        }
        else {
            return view('users.index');
        }
    }
`

My roles.blade.php view:


![capture](https://cloud.githubusercontent.com/assets/12883609/23084171/0ef88d18-f52f-11e6-8e76-d8729ed410fb.PNG)


But its not working

**Comment by yajra** [comment]
Use closure when adding the column. See [docs](https://yajrabox.com/docs/laravel-datatables/7.0/add-column#closure) for ref.

**Comment by legreco** [comment]
IT WORKS NOW! Thanks a lot
My usercontroller index method
![capture1](https://cloud.githubusercontent.com/assets/12883609/23090023/d22c83fc-f561-11e6-9a28-3affc1174e87.PNG)

My roles.blade.php partial view
![capture2](https://cloud.githubusercontent.com/assets/12883609/23090024/de3efa08-f561-11e6-9a0c-ba631c0439ce.PNG)
