### ISSUE TITLE
Version 7 no artisan command

### ISSUE THREAD

**Issue by jim1506** [yajra/laravel-datatables#1018]
In the tutorial it is stated to run

php artisan datatables:make UsersDataTable

but running this results in artisan saying there is n namespace for datatables.

### System details

- Operating System - Windows 10 with IIS
- PHP Version - 7
- Laravel Version -5.4
- Laravel-Datatables Version - 7

**Comment by yajra** [comment]
Please see [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade). Thanks!

**Comment by jim1506** [comment]
Jim Elliott



I am following the tutorial for using it as a service

**Comment by yajra** [comment]
Have updated the tutorial and add some note for upgrade guide for Laravel 5.4.

Will try to make a new tutorial for Laravel 5.4 when I had the chance. Thanks!
