### ISSUE TITLE
Clear filters

### ISSUE THREAD

**Issue by minedun6** [yajra/laravel-datatables#1020]
Is there any way to clear custom filter eitheir using using your package or the dataTables.js way ?

**Comment by yajra** [comment]
I think you need to do it on the js level. Something like what I did on the reset button extension:

```js
    DataTable.ext.buttons.reset = {
        className: 'buttons-reset',

        text: function (dt) {
            return '<i class="fa fa-undo"></i> ' + dt.i18n('buttons.reset', 'Reset');
        },

        action: function (e, dt, button, config) {
            dt.search('').draw();
        }
    };
```

**Comment by minedun6** [comment]
didn't mean the search input that is there by deafault.
I meant any other custom filters.

**Comment by yajra** [comment]
You need to manually clear all other filters by extending the reset button as ref.
