### ISSUE TITLE
Documentation site is down.

### ISSUE THREAD

**Issue by umefarooq** [yajra/laravel-datatables#1025]
Hi, your documentation site is down, please make it live showing server not found

**Comment by tobiasz** [comment]
bump

**Comment by gkjpettet** [comment]
Bump. Still down.

**Comment by aghict** [comment]
Still down.

**Comment by yajra** [comment]
Up now, had some issues with billing and the server was suspended. ^_^ 👍

**Comment by 0ly** [comment]
bump. Down again

**Comment by annajeanine** [comment]
Still down.
