### ISSUE TITLE
filterColumn colsure never executed #question

### ISSUE THREAD

**Issue by rizerzero** [yajra/laravel-datatables#1027]
## Can't make the filterClumn work 

i want to add a custom filter, i added the HTML and the java-script event that trigger the draw method on change , it works fine but in the php side i can't make it work , i get the value of my input but the filterColumn does not work  
 ```php 
return Datatables::eloquent($model)
                ->filterColumn('category', function($query, $keyword) {
               //no matter what i white here , the code is never executed  , the filterColumn method ( in the        baseEngine ) is called but never runs what i put here 
                                    $sql=$query->where('category', '=', $request->get('category'));
                    $query->whereRaw($sql, ["%{$keyword}%"]);
                })
                ->make();
});
```
### if i take the query code outside like so the filter works 
 ```php 

 $query= User::all();
$dt = Datatables::eloquent($model);
                
        $query->where('category', '=', $request->get('category'));
             
        return $dt->make();
```

the thing that i don't understand is how does this method work
```php

 public function filterColumn($column, $method)
    {
        $params                             = func_get_args();
        $this->columnDef['filter'][$column] = ['method' => $method, 'parameters' => array_splice($params, 2)];
  
       return $this;
    }
```

#how does the call work , how does the code bring the $query, 

```php
filterColumn('category', function($query, $keyword) {
}
```
**_i know  it's just closures but i feel i'm missing something to understand how it all works , and i would love to know and be a better developer_** 
**Thank you !**
 
- windows 10
- Operating System
- PHP 5.6.16
- Laravel 5.3
- Laravel-Datatables 6.0

**Comment by yajra** [comment]
I think you are using collection and not eloquent?

```php
$query= User::all(); // -> Collection?
$dt = Datatables::eloquent($model); // ? $model?
```

Try using select instead:
```php
$query= User::select();
$dt = Datatables::eloquent($query);
```

**Comment by ethaizone** [comment]
I used filterColumn and it works well. Do you implement follow this page? https://datatables.net/examples/api/multi_filter.html
