### ISSUE TITLE
Cant access https://yajrabox.com/docs/laravel-datatables/7.0/upgrade

### ISSUE THREAD

**Issue by jackkitley** [yajra/laravel-datatables#1029]
### Summary of problem or feature request

Unable to access https://yajrabox.com/docs/laravel-datatables/7.0/upgrade. Times out.

**Comment by AdrienPoupa** [comment]
The website is currently down.

**Comment by annajeanine** [comment]
You can still access the website through web.archive.org

**Comment by AdrienPoupa** [comment]
Or google cache: http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fyajrabox.com%2Fdocs%2Flaravel-datatables%2F7.0%2Fupgrade&ie=utf-8&oe=utf-8&client=firefox-b-ab

**Comment by yajra** [comment]
It's up now, not sure why it went offline. Thanks!
