### ISSUE TITLE
Ordering doesn't work when using column alias

### ISSUE THREAD

**Issue by ArtbyArjan** [yajra/laravel-datatables#103]
I have the following code in my controller:

```php
$news = News::join(
'news_translation',
'news_translation.news_id','=','news.id'
)
->join(
'newstype',
'news.newstype_id','=','newstype.id'
)
->join(
'newstype_translation',
'newstype_translation.newstype_id','=','newstype.id'
)
->select(
'news.id',
 'news.isactive',
'news.publish_date',
'newstype_translation.title as newstype',
'news_translation.title')
->where('news_translation.language_id','=',config('app.locale_id') );

return Datatables::of( $news )
->edit_column('isactive', '{{ $isactive ? Lang::get("backend.global.yes") : Lang::get("backend.global.no") }}' )
->add_column('edit', '{!! "<a href=\"".route("admin.news.edit", $id)."\" class=\"btn-edit\"><span class=\"icn-pencil-2\"></span></a>" !!}')
->add_column('del', '{!! Form::delete( URL::route( "admin.news.destroy", $id, false ) ) !!}')
->make();
```
As you can see, I have two columns with the same name so I give newstype_translation.title an alias.
The initial loading of the datatable works, but when I try to order my results on that column, I get a QueryException error

```sql
Syntax error: 7 ERROR: syntax error at or near "as"
LINE 1: ..._id" = $1 order by "newstype_translation"."title" as "newsty...
^ (SQL: select 
"news"."id", 
"news"."isactive", 
"news"."publish_date", 
"newstype_translation"."title" as "newstype", 
"news_translation"."title" 
from "news" 
inner join "news_translation" on "news_translation"."news_id" = "news"."id" 
inner join "newstype" on "news"."newstype_id" = "newstype"."id" 
inner join "newstype_translation" on "newstype_translation"."newstype_id" = "newstype"."id" 
where "news"."deleted_at" is null 
and "news_translation"."language_id" = 10
order by "newstype_translation"."title" as "newstype" asc 
limit 10 
offset 0)
```
As you can see on the order by line, it tries to order by "newstype_translation"."title" as "newstype" instead of "newstype"
How can I still display both columns by using an alias?

**Comment by yajra** [comment]
Please see this demo for ref. http://datatables.yajrabox.com/eloquent/joins. Basically you need to declare your JS like below. `data` corresponds to `alias` while `name` will be the actual column name.

```js
$('#posts-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: 'http://datatables.yajrabox.com/eloquent/joins-data',
        columns: [
            {data: 'id', name: 'posts.id'},
            {data: 'title', name: 'posts.title'},
            {data: 'name', name: 'users.name'},
            {data: 'created_at', name: 'posts.created_at'},
            {data: 'updated_at', name: 'posts.updated_at'}
        ]
    });
```

**Comment by ArtbyArjan** [comment]
I forgot to add my JS function. 
```javascript
$(function(){
    var config = dataTableConfig({
        'aoColumns' : [
        { "sortable": true },
        { "sortable": true },
        { "sortable": true },
        { "sortable": true },
        { "sortable": true },
        { "sortable": false },
        { "sortable": false }
        ]
    });
    $('#datatable-product').dataTable( config );
});
```
Is your example the only way to use aliases and perform joins?

**Comment by yajra** [comment]
I think you should use `columns` instead of `aoColumns` and I suggest you follow the convention above to avoid errors. Other approach like the one you were using is not fully tested.

**Comment by ArtbyArjan** [comment]
Hmm ok, that means I'll have to re-arrange my project in order to get it working...
I'll see how far I can get. Thanks for the replies so far.

**Comment by karillon** [comment]
Hi, I have the same problem. It worked perfectly until v5.4.5 !

**Comment by yajra** [comment]
@karillon latest stable version is 5.5.4 or just a typo?

**Comment by yajra** [comment]
@karillon, @ArtbyArjan maybe try updating to the latest stable version of the package (v5.5.7 atm) and verify if the issue still exists. Can't reproduce this one. Thanks!

`composer update yajra/laravel-datatables-oracle`

**Comment by ArtbyArjan** [comment]
I have just updated to 5.5.7 but the problem still excists.
The reason you can't reproduce my error is probably because you're setup is different from mine.
When I try the setup from your example, I get the "Requested unknown parameter 'id' for row '0'" error.
With my setup I do get the initial list, but when I try to sort it on a renamed column ( 'newstype_translation.title as newstype' ) it gives an error.

This is the default config
```javascript
function dataTableConfig( myconfig, extraparams ){
    var config = {
        stateSave: true,
        fnStateSave: function (oSettings, oData) {
            localStorage.setItem( 'DataTables'+document.location.pathname, JSON.stringify(oData) );
        },
        fnStateLoad: function () {
            return JSON.parse( localStorage.getItem('DataTables'+document.location.pathname) );
        },
        dom: "<'row'<'small-6 columns'l><'small-6 columns'f>r>t<'row'<'small-6 columns'i><'small-6 columns'p>>",
        processing: true,
        serverSide: true,
        responsive: {
            breakpoints: [
                { name: 'mobile-l',   width: 480 }
            ]
        },
        pagingType: "simple_numbers",
        renderer: "foundation",
        ajax: document.location.href,

        language: {
            "sProcessing": "Bezig...",
            "sLengthMenu": "Resultaten weer te geven: _MENU_",
            "sZeroRecords": "Geen data om weer te geven",
            "sInfo": "Resulaten _START_ tot _END_ van _TOTAL_ weergegeven",
            "sInfoEmpty": "Geen data om weer te geven",
            "sInfoFiltered": " (gefilterd uit _MAX_ regels)",
            "sInfoPostFix": "",
            "sSearch": "Zoeken:",
            "sEmptyTable": "Geen gegevens aanwezig in de tabel",
            "sInfoThousands": ",",
            "sLoadingRecords": "Een moment geduld aub - bezig met laden...",
            "oPaginate": {
                "sFirst": "Eerste pagina",
                "sLast": "Laatste pagina",
                "sNext": "Volgende pagina",
                "sPrevious": "Vorige pagina"
            }
        }
    };

    if( extraparams ){
        config['fnServerParams'] = function ( aoData ) {
            for( var key in extraparams ){
                aoData.push({"name":key, "value":extraparams[key] });
            }
        };
    }
    
    config = $.extend(config, myconfig);

    return config;
}
```
This is the controller
```php
$news = News::join(
'news_translation',
'news_translation.news_id','=','news.id'
)
->join(
'newstype',
'news.newstype_id','=','newstype.id'
)
->join(
'newstype_translation',
'newstype_translation.newstype_id','=','newstype.id'
)
->select(
'news.id',
 'news.isactive',
'news.publish_date',
'newstype_translation.title as newstype',
'news_translation.title')
->where('news_translation.language_id','=',config('app.locale_id') );

return Datatables::of( $news )
->edit_column('isactive', '{{ $isactive ? Lang::get("backend.global.yes") : Lang::get("backend.global.no") }}' )
->add_column('edit', '{!! "<a href=\"".route("admin.news.edit", $id)."\" class=\"btn-edit\"><span class=\"icn-pencil-2\"></span></a>" !!}')
->add_column('del', '{!! Form::delete( URL::route( "admin.news.destroy", $id, false ) ) !!}')
->make();
```
And this is the init call on the page
```javascript
$(function(){
    var config = dataTableConfig({
        'aoColumns' : [
        { "sortable": true },
        { "sortable": true },
        { "sortable": true },
        { "sortable": true },
        { "sortable": true },
        { "sortable": false },
        { "sortable": false }
        ]
    });
    $('#datatable-news').dataTable( config );
});
```

**Comment by yajra** [comment]
Ok i think i found your issue. You also need to declare the name on your js because the ordering and searching depends on it. Your init call should be something like this. I think you upgrading from Bllim's version? One big difference on this package is that column name used are declared on js. 

```js
$(function(){
    var config = dataTableConfig({
        'aoColumns' : [
        { "sortable": true, "name": "news.id" },
        { "sortable": true, "name":"news.isactive" },
        { "sortable": true, "name":"news.publish_date" },
        { "sortable": true, "name":"newstype_translation.title" },
        { "sortable": true, "name":"news_translation.title" },
        { "sortable": false },
        { "sortable": false }
        ]
    });
    $('#datatable-news').dataTable( config );
});
```

In addition, I also suggest that you use `make(true)` to return an object data source and then bind the value on datatables by declaring `data: 'field'`. Lastly, I think you don't have to declare `sortable: true` because it is true by default.

```js
        {data: 'id' , "name": "news.id" },
```

**Comment by ArtbyArjan** [comment]
Awesome, it works!
Thanks a lot for clearing that up.

We have updated from Bllim's version indeed.

**Comment by yajra** [comment]
I think this is a database specific query issue? maybe on `lower(news.id)...`. You can override this default global search by using `filterColumn` like on Bllim's version.

**Comment by yajra** [comment]
I think your using pgsql and search fields should be casted as text? Will try to check this too.. maybe there is a bug on my casting. However, I am not so fluent on pgsql coz I haven't used it yet. Might take some time to figure this out.

**Comment by yajra** [comment]
Just tested pgsql on my homestead and casting is working fine. However, based on you error dump it is not casted. >.<

**Comment by ArtbyArjan** [comment]
@yajra Updating to the latest version (5.5.11) has also fixed the search error

**Comment by yajra** [comment]
@ArtbyArjan, that's great! So this issue is really fixed and no need to re-open? Thanks!

**Comment by ArtbyArjan** [comment]
It works perfectly for me.
The only thing that's "bothering" me is that the search is executed after every keystroke.
So when I have a list of records and I'm going to search for a five letter word (i.e. daily), it executes a search after every letter.
d => updates datatables
a => updates datatables
i => updates datatables
etc...

Is that something that needs fixing on my side?

**Comment by yajra** [comment]
yes, it's on your side. You can use DT's `fnFilterOnReturn` plugin for that. Here's a link for the plugins you can use. http://datatables.net/plug-ins/api/
