### ISSUE TITLE
setRowAttr(), setClassAttr() not working when use setTransformer()

### ISSUE THREAD

**Issue by JanKyselica** [yajra/laravel-datatables#1038]
### Summary of problem or feature request

When I use setTransformer() method any of `setRowAttr()`, `setRowData()`, `setClassAttr()`, `addRowAttr()`, `addRowData()` methods aren't working.

```php
return Datatables::of($topics)->setTransformer(new AuditTransformer)
            ->addRowData('auditor', function($topic) {
                return $topic->auditor_id;
            })->make(true);
```

Maybe this not bug but in the docs are missing information that these methods not working when you use `setTransformer()` method. There are only three methods mentioned in docs: `addColumn`, `editColumn`, `deleteColumn`.
Link to the docs where should been this information: [Docs](https://yajrabox.com/docs/laravel-datatables/7.0/response-fractal)

### System details
- Ubuntu 16.10
- PHP 7.1.2
- Laravel 5.4.13
- Datatables 7.3.0

**Comment by yajra** [comment]
@JanKyselica you are correct that this is the expected behavior. All response manipulation should be done via transformer if it was used. Will update the docs, thanks for the heads up! 👍
