### ISSUE TITLE
How to change the datatable pagination per page count?

### ISSUE THREAD

**Issue by yelnyaface** [yajra/laravel-datatables#1039]
### Summary of problem or feature request

hi, I would like to know how to change the pagination per page number?

**Comment by yajra** [comment]
Hmm, not sure if get this right but I think what you need are the pagination plugins. See DT official [docs](https://datatables.net/plug-ins/pagination/).

**Comment by shimadh** [comment]
add this to parameters array. i am using dataTable service implementation
`  ->parameters([
                'dom'     => 'Bfrtip',
                "bJQueryUI" => true,
                "sPaginationType" => "full_numbers",
                "sDom" => '<""l>t<"F"fp>',
                'order'   => [[0, 'asc']],
                "lengthMenu" => [[25, 50, 100, -1], [25, 50, 100, "All"]]
            ]);`

**Comment by piyushgupta09-laravel** [comment]
> add page lengthMenu option to parameters array. i am using dataTable service implementation
> ` ->parameters([ 'dom' => 'Bfrtip', "bJQueryUI" => true, "sPaginationType" => "full_numbers", "sDom" => '<""l>t<"F"fp>', 'order' => [[0, 'asc']], "lengthMenu" => [[25, 50, 100, -1], [25, 50, 100, "All"]] ]);`

hi shimaxu,
can you tell me from where to get the list of all possible parameters, 
thanks

**Comment by shimaxu** [comment]
> > add page lengthMenu option to parameters array. i am using dataTable service implementation
> > ` ->parameters([ 'dom' => 'Bfrtip', "bJQueryUI" => true, "sPaginationType" => "full_numbers", "sDom" => '<""l>t<"F"fp>', 'order' => [[0, 'asc']], "lengthMenu" => [[25, 50, 100, -1], [25, 50, 100, "All"]] ]);`
> 
> hi shimaxu,
> can you tell me from where to get the list of all possible parameters,
> thanks

https://datatables.net/reference/option/
