### ISSUE TITLE
pagination issue with serverSide=true

### ISSUE THREAD

**Issue by jaimingohel** [yajra/laravel-datatables#104]
my application is running fine with server side true..
it just have one issue

when i search in datatable it gives me perfect results but the value of recordsFiltered does not change.. because of that the pagination is created on the basis of total records..

i want pagination to be created on the basis of filtered records not all records..

like this one https://www.datatables.net/examples/data_sources/server_side.html

**Comment by yajra** [comment]
@jaimingohel filtered total records and pagination seems working fine with me. See this demo for example http://datatables.yajrabox.com/eloquent/basic-object. 

<img width="1006" alt="screen shot 2015-07-09 at 8 32 41 am" src="https://cloud.githubusercontent.com/assets/2687997/8585499/216f562e-2615-11e5-9a09-09c855632025.png">

**Comment by tarunhere** [comment]
@jaimingohel  may be you too need to update your package. I was facing same issue. Kindly update to version 5.5.5.
thanks

**Comment by yajra** [comment]
@jaimingohel, please update your package to latest version to fix this issue. You can update by executing `composer update yajra/laravel-datatables-oracle`.
