### ISSUE TITLE
all ticket for one user 

### ISSUE THREAD

**Issue by Mahdi-Sahib** [yajra/laravel-datatables#1041]
i know how to show ticket using yajra/laravel-datatables and relational thinge

but i looking for make table to  all ticket for one user 

any example ?

**Comment by yajra** [comment]
Assuming you have user -> hasMany -> tickets?

```php
$tickets = auth()->user()->tickets()->query();
return Datatables::eloquent($tickets)->make(true);
```

See [demo](https://datatables.yajrabox.com/eloquent/has-many) for some refs.

**Comment by Mahdi-Sahib** [comment]
good so if i need another thing like customer so i dont need to use auth() 

customer -> hasMany -> tickets?
```
$tickets = customer()->tickets()->query();
return Datatables::eloquent($tickets)->make(true);
```

is that ok ?

**Comment by Mahdi-Sahib** [comment]
4 days i cant solve this problem

**Comment by yajra** [comment]
Yes, that should work too as long as your customer model exists. Thanks!
