### ISSUE TITLE
Eloquent with relations - Another problem with ids

### ISSUE THREAD

**Issue by apsg** [yajra/laravel-datatables#1046]
This is somehow related to this problem:

[https://github.com/yajra/laravel-datatables/issues/1019](https://github.com/yajra/laravel-datatables/issues/1019)

I have a large table that uses eloquent with relations as a data source. 

```
 columns: [
            { data: 'id', name: 'id', searchable: true },
            ... several not important columns....
            { data: 'user.name', name: 'user.name' , searchable: true },
            ... other columns...
        ],
```
in my controller I use following as data source:
```
$model = \App\Form::with('user');

return Datatables::eloquent($model)->make()
```
(Of course this is simplified version, I add several raw columns and I have few more relations in my query)

I sort by ID by default. But when user clicks on sorting by the user.name column, then the first column changes and ids are being converted to user.id 

I really don't understand why the id of `Form` is suddenly being replaced with id of `User` while sorting by the `user.name` column.

Any ideas? When you look at this problem and at #1019 it seems that it has some problem with ids when it comes to eloquent relations

**Comment by blueminded** [comment]
yep, you can do:

`$model = \App\Form::with('user')->slect('forms.*');`

I don't know why sometimes it replace the main ID with relationship ID

**Comment by apsg** [comment]
@blueminded Wow, that works, thanks! It's getting even stranger, but works.

**Comment by yajra** [comment]
Adding `->slect('forms.*')` will indeed solve the issue as noted in this [docs](https://datatables.yajrabox.com/eloquent/relationships) and [this](http://dt54.yajrabox.com/eloquent).
