### ISSUE TITLE
Change the name of **Action**  Cloumn header 

### ISSUE THREAD

**Issue by 3a6ala** [yajra/laravel-datatables#1047]
### Summary of problem or feature request

 in fact i develop an application using Arabic language  so i need to change the name of ***Action*** column for example  **from** Action **To**   اﻻجراءات. 

### There is any way to achieve that with this Awesome package . Thanks 

- Operating System Ubuntu 16.4
- PHP Version 7.0
- Laravel Version 5.3
- Laravel-Datatables 6.0

**Comment by yajra** [comment]
Just add title attribute:

```php
->addAction(['title' => 'اﻻجراءات'])
```

**Comment by 3a6ala** [comment]
Awesome Thanks @yajra  for help .

**Comment by Meklad** [comment]
> Just add title attribute:
> 
> ```
> ->addAction(['title' => 'اﻻجراءات'])
> ```

Thanks ... its working
