### ISSUE TITLE
Searching more than 1 Column - Datatable 

### ISSUE THREAD

**Issue by rebootcode** [yajra/laravel-datatables#1048]
Currently there is only 1 search box. how can we search data for 2 column at a time.

For example "name" and "city" ( John , Newyork ) in data table list generated by scaffold generator.

Is it possible to have search box implemented below each column ?

- Operating System - Linux
- PHP Version   - 5.6
- Laravel Version  - 5.3
- Laravel-Datatables Version - 6.0

**Comment by yajra** [comment]
You can use `filter` api to handle this. See [docs](https://yajrabox.com/docs/laravel-datatables/6.0/manual-search) for ref.
