### ISSUE TITLE
Vendor button.js problem

### ISSUE THREAD

**Issue by halilcosdu** [yajra/laravel-datatables#1049]
### button.js

var _buildUrl = function (dt, action) {
        var url = dt.ajax.url() || '';
        var params = dt.ajax.params();
        params.action = action;

        if (url.indexOf("?")) {
            return url + '&' + $.param(params);
        }

        return url + '?' + $.param(params);
    };

Not working

 Maybe ?

   if (url.indexOf("?")>-1) {
            return url + '&' + $.param(params);
        }

- Operating System Nginx
- PHP Version 7 
- Laravel Version 5.4
- Laravel-Datatables Version 7

**Comment by yajra** [comment]
@halilcosdu you are correct, can you please submit a PR for the fix? Thanks!

**Comment by yajra** [comment]
The issue was due to this [PR](https://github.com/yajra/laravel-datatables-buttons/pull/7).

**Comment by yajra** [comment]
Fixed on buttons v1.1.2, thanks a lot for reporting!

**Comment by halilcosdu** [comment]
You're welcome.
Best.
