### ISSUE TITLE
Class datatables.html does not exist

### ISSUE THREAD

**Issue by marianobies** [yajra/laravel-datatables#1050]
### Class datatables.html does not exist

This error in new installation "Class datatables.html does not exist"

**Comment by yajra** [comment]
Html and buttons are now extracted to own plugin. If you are using the service approach, you need to install the [buttons plugin](https://yajrabox.com/docs/laravel-datatables/7.0/buttons-installation)

**Comment by tarunhere** [comment]
Buttons plugin is giving error of 404!!
