### ISSUE TITLE
Receive Forbidden - Error for export functions

### ISSUE THREAD

**Issue by ngsource** [yajra/laravel-datatables#1051]
I have installed all the dependencies correctly. When I click on the export button I receive Forbidden - Error. Below is my code.
![403 forbidden](https://cloud.githubusercontent.com/assets/8065628/23656537/255b1abe-0360-11e7-9e77-64df932da2ba.png)

`
namespace App\DataTables;

use App\User;
use Yajra\Datatables\Services\DataTable;

class UserDataTable extends DataTable
{

    /**
     * Display ajax response.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->make(true);
    }

    /**
     * Build DataTable class.
     *
     * @return \Yajra\Datatables\Engines\BaseEngine
     */
    public function dataTable()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', 'path.to.action.view');
    }

    /**
     * Get the query object to be processed by dataTables.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
        $query = User::query();
        return $this->applyScopes($query);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->parameters([
                'dom'          => 'Bfrtip',
                'buttons'      => ['export', 'print', 'reset', 'reload'],
            ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'id',
            'email',
            'name',
            'created_at',
            'updated_at',
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'userdatatable_' . time();
    }
}

return $dataTable->render('app.clients.index');

 {!! $dataTable->table() !!}

    @push('scripts')

        <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
        <script src="https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
        <script src=" {{asset('vendor/datatables/buttons.server-side.js')}}"></script>
        {!! $dataTable->scripts() !!}
    @endpush`

- Operating System : Ubunut 14.04
- PHP Version : 5.6
- Laravel Version : 5.4
- Laravel-Datatables Version :  7.0

**Comment by yajra** [comment]
Were you able to install dompdf: ~6.2.0 or laravel-snappy package?

**Comment by yajra** [comment]
Some docs for ref: https://yajrabox.com/docs/laravel-datatables/7.0/buttons-config#pdf-generator

**Comment by tad3j** [comment]
I'm having the same issue. I have these installed:

> "barryvdh/laravel-snappy": "^0.3.1",

> "dompdf/dompdf": "^0.7.0",

And under datatables-buttons.php I have this configuration:

> 'pdf_generator' => 'snappy',

I'm getting Forbidden on all exports, CSV, Excel and PDF.

Seems like the request is issued to wrong route, since I see that the URL in URL bar is:

> http://website.dev/&draw=1&columns%5B0%5D%5Bdata%5D=name . . . &action=excel

**Comment by yajra** [comment]
@tad3j yeah, there was a bug on buttons-server-side.js and was fixed on the latest release. Thanks!
