### ISSUE TITLE
Search Query - Eloquent

### ISSUE THREAD

**Issue by fahrenheitsql** [yajra/laravel-datatables#1052]
### Summary of problem or feature request
When search is used the resulting records are getting only top 10/25/50/100 records. Also, pagination is not working on search.

### Code snippet of problem
Sample of query that is getting executed
select count(*) as aggregate from (select * from `tblName` where `status` = '1' and (LOWER(`tblName`.`col1`) LIKE '%2017-01-04%' or LOWER(`tblName`.`col2`) LIKE '%2017-01-04%' or LOWER(`tblName`.`col3`) LIKE '%2017-01-04%') order by `id` desc **limit 10 offset 0**) count_row_table

### System details

- Operating System : Linux
- Laravel Version : 5.4
- Laravel-Datatables Version : 7.2

**Comment by yajra** [comment]
Can you please paste some code to reproduce the error?

**Comment by fahrenheitsql** [comment]
Hi, My bad. I had the controller wrongly setup. 
Had 
->skip($request->input('start'))
->take($request->input('length')) 
that was added the the eloquent. Once I took them out. the "Search" and the "Paginiation" on search became fine.
