### ISSUE TITLE
Searching on eager loaded value does not put database prefix in query

### ISSUE THREAD

**Issue by dasuchin** [yajra/laravel-datatables#1054]
I have a DataTable class created with column definitions. If I set the `name` value of one of the columns to be a relationship, it doesn't add the database prefix to the generated query.

Column def example:

```
'value' => [
     'visible' => true,
     'searchable' => true,
     'name' => 'related.value',
],
```

Generated query example:

```
select 
count(*) as aggregate from 
(
    select 
    '1' as `row_count` 
    from `prefix_tablename` 
    left join `prefix_tablename_related` on `prefix_tablename_related`.`tablename_id` = `prefix_tablename`.`id` 
    where LOWER(tablename_related.value) REGEXP ^200$ and 
    `prefix_tablename`.`deleted_at` is null and 
    `prefix_tablename`.`deleted_at` is null
) count_row_table;
```

I had to edit this code from what I have actually producing the error, but this should give you an idea of what I'm seeing.

**Comment by yajra** [comment]
Yes, I think I understand what's missing here and this is indeed for enhancement/bug. I guess a workaround for this might be using filterColumn or use join statements atm. Thanks!

**Comment by yajra** [comment]
Just made a patch, can you please check if it fixes this issue? Thanks!

**Comment by dasuchin** [comment]
Is there any possibility of fixing this on version 6? I'm still using Laravel 5.3 for the moment.

**Comment by yajra** [comment]
Hmm, seems odd. I just tested on v6 and db prefix using the demo code and seems to work well. Can you please paste code to reproduce the issue? Thanks!

**Comment by yajra** [comment]
Can't replicate the issue. Open a new ticket if still encountering it. Thanks!
