### ISSUE TITLE
Custom filter AJAX issue

### ISSUE THREAD

**Issue by ConnorPoultonOP** [yajra/laravel-datatables#1057]
I have (nearly) copied the code form the advanced filter example and am trying to create a simple drop down filter. The problem is that whenever I try to search the value returned to the PHP controller is always the first value of the dropdown list. I believe this is an AJAX issue as the incorrect URL is displayed by the browser. If somebody could explain how to properly make an AJAX request with data tables, I would be very grateful. PS I apologize for the poor formatting, but my code was being mangled when I tried to past it in, so I had to add it one line at a time.

Routes
`Route::get('/test', 'test@getAdvanceFilter');`
`Route::get('/test/filter', 'test@getAdvanceFilterData');`

Javascript
```js
<script>
    $(function() {
        var table = $('#myTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: '/test/filter',
                data: function (d) {
                    d.demo = $('select[name=selecter]').val();
                }
            },
            columns: [
                { data:'protocol'},
                { data:'domain'},
                { data:'path'},
            ]
        });
        $('#search-form').on('submit', function(e) {
            table.ajax.url('/test/filter').load();
            e.preventDefault();
        });
    });
</script>
```

**Comment by yajra** [comment]
Try to use draw instead of load.

```js
$('#search-form').on('submit', function(e) {
            table.draw();
            e.preventDefault();
        });
```

**Comment by ConnorPoultonOP** [comment]
draw() is what I had originally, but it does not work either :(
This is the URL that ends up in my browser: http://homestead.app/?search_group_filter=url
But this is what it should be: http://homestead.app/filter 
Whenever I try to get $request->get('demo') the default value of the drop down list is always returned

**Comment by ConnorPoultonOP** [comment]
anything else you can recommend I try?

**Comment by Erth0** [comment]
Same problem with me as well

**Comment by yajra** [comment]
Can you please inspect the ajax response to get a hint on what's causing the issue? Use chrome dev tools or firebug.

**Comment by yajra** [comment]
You can try enabling debug mode and inspect the input's used to processed the table. Also, double check the queries generated. You might be scoping the query on every request and it may not be what you wanted. Thanks!

**Comment by akramabdulrahman** [comment]
hi , filtering using this method is working fine but i've got an issue 
` 
 function mix(source, target) {
        $(source).each(function (i, v) {
            console.log(i, v);
            target[v['name']] = v['value'];
        })

    }

$('#dataTableBuilder')
        .on('preXhr.dt', function (e, settings, data) {
            mix($('#search-form').serializeArray(), data);
        })
        .dataTable({
            ajax: "data.json"
        });

    $('#search-form').on('submit', function (e) {
        window.LaravelDataTables.dataTableBuilder.draw();
        e.preventDefault();
    });`
the code injects the value after filter into the datatable and causes "cannot reinitialize datatable" warning 
i can ignore that for now
the main issue am having is with print button . since my approch doesnt really edit the datatable context directly. print doesnt catch my change and prints the initial data without applying the filter .

my question is how to make print aware of changes i applied to datatable .
