### ISSUE TITLE
Can't call `join on` in filterColum method function?

### ISSUE THREAD

**Issue by xiaohuilam** [yajra/laravel-datatables#1059]
Can't call `join on` in filterColum method function?

```php
<?php
Datatables::queryBulder(DB::table('a'))
->filterColumn('a.status', function($query, $keyword) {
    switch($keyword):
       case 1:
          $query->leftJoin('b', function($join){
               $join->on('b.rel_id', '=', 'a.id');
               $join->on('b.status', '=', DB::raw(1));
          });
          break;
      default:
          break;
})
->make(true);
```

and it returns debug info of queries, which NOT including join on table `b` in the SQL.

OS + ENV info:
- MacOS X 10.9
- PHP 7.0
- Laravel 5.2
- Laravel-Datatables 6.22.2

**Comment by yajra** [comment]
Filter column will only be executed when you perform search. Thus, initial loading of dataTable will skip this part.

**Comment by xiaohuilam** [comment]
Yes, i know it will be trigger only if submit a search request

I just wanna join on table b when search 1, and join on c when search 2.
but seems it doesn't work...

**Comment by yajra** [comment]
Does it pass to your switch statement? 

```php
switch($keyword):
       case 1:
```

**Comment by xiaohuilam** [comment]
no, it does not work.

**Comment by ethaizone** [comment]
Do you implement search by https://datatables.net/examples/api/multi_filter.html?

Can you capture header request from your browser?

<img width="233" alt="chrome_2017-04-12_09-17-10" src="https://cloud.githubusercontent.com/assets/1168777/24938384/ff0c44e2-1f60-11e7-8f47-09d569366d68.png">

You should found post content like this picture, this one can trigger filterColumn.
