### ISSUE TITLE
empty result sets gives JS error -  TypeError: data is undefined

### ISSUE THREAD

**Issue by tarunhere** [yajra/laravel-datatables#106]
I have successfully installed and initiated Datatables, Now, when I push my code on production, I was not having records for all the tables. 
There, I am getting this js error - `TypeError: data is undefined`
I realized that those tables are empty and so the editColumn/addColumn is throwing this error.

````
$ad = advt::visibleAdvertsForGrade()->get();

			if($ad->count() >= 1)
			{
				return Datatables::of($ad)
					->addColumn('actions', function($ad) {
						  return view('ads.action', compact('ad'))->render();
					})
					->removeColumn('ads_id')
				->make(true);
			}
			else
			{
				return \Response::json($ad);
			}	

````

to resolve this error I tried to count the recordSets, but this is also not working. 
Any thoughts how to deal with empty resultSets!?

**Comment by yajra** [comment]
it should work fine with empty records. I think your problem here in on your view. Maybe you should put some checker if `ad` variable is set. 

On the other hand, I think I see some improvements for the package here. `addColumn` and other methods should not be called when result is empty. Will also check that scenario. Thanks!

**Comment by yajra** [comment]
I just tested your approach in my app and everything is working fine on empty table. There must be something else that going on in your app that causes the issue. I guess improvement is irrelevant here.

BTW, `if($ad->count() >= 1)` is not needed. Most probably, that is what causing the errors.

**Comment by yajra** [comment]
@tarunhere, `if($ad->count() >= 1)` is not needed and is the cause of issue. Removing it should fix this. Thanks!

**Comment by jaimingohel** [comment]
hello @yajra i'm having the same issue..  it is giving undefined offset:0 ..

**Comment by yajra** [comment]
@jaimingohel , can you please paste your controller script. re-opening the issue.

**Comment by jaimingohel** [comment]
here is my controller code..
````                                      
return Datatables::of($notify)
					->addColumn('actions', function($notify) {
						  return view('notify.action', compact('notify'))->render();
					})
					->editColumn('user_member','@if($user_member == 1)
				                                Everyone
				                            @elseif($user_member == 2)
				                                Members Only
				                            @elseif($user_member == 3)
                          						Non-Members Only 
				                            @endif')
					->editColumn('push_text','@if($push_text == 1)
				                                Push
				                            @elseif($push_text == 2)
				                                SMS 
				                            @endif')
					->removeColumn('id')
				->make(true);

````

**Comment by yajra** [comment]
what is `$notify`? is it an eloquent or a collection?

**Comment by jaimingohel** [comment]
yes $notify is eloquent code goes like this..

````
$notify = notification::NotifyVisible()
						->select('id','message','user_member','push_text')
						->get();

````

**Comment by yajra** [comment]
ok.. I suggest you remove `get()` because it will become a collection and not Eloquent instance. I think the issue is an empty collection. Will check it later.

**Comment by yajra** [comment]
@tarunhere same goes for you, I suggest you use Eloquent be removing the `get()` method. Issuing get may cause you some performance issue specially if the dataset is large as it will load all the records.

**Comment by tarunhere** [comment]
sure, I'll give it a try.

**Comment by jaimingohel** [comment]
A big thankyou to you man @yajra . you saved me!

**Comment by tarunhere** [comment]
So... it is working @jaimingohel ?? ok.. Then I m closing this issue. Thanks yajra, again.
