### ISSUE TITLE
Search doesn't return results when query is in lowercase

### ISSUE THREAD

**Issue by s6joui** [yajra/laravel-datatables#1061]
### Summary of problem or feature request

Search doesn't return results when query is in lowercase. I'm searching for usernames.
For example "John" returns results but "john" doesn't

caseInsensitive in config.php is set to true

### System details

Using version 6.26

**Comment by yajra** [comment]
Can you please provide some codes to reproduce the issue?

**Comment by yajra** [comment]
@s6joui does smart search also set to true? Just make sure the config are set to something like below:

```php
    /**
     * DataTables search options.
     */
    'search'          => [
        /**
         * Smart search will enclose search keyword with wildcard string "%keyword%".
         * SQL: column LIKE "%keyword%"
         */
        'smart'            => true,

        /**
         * Case insensitive will search the keyword in lower case format.
         * SQL: LOWER(column) LIKE LOWER(keyword)
         */
        'case_insensitive' => true,

        /**
         * Wild card will add "%" in between every characters of the keyword.
         * SQL: column LIKE "%k%e%y%w%o%r%d%"
         */
        'use_wildcards'    => false,
    ],
```

Searching works fine as per demo. Thanks!
