### ISSUE TITLE
How to show datatable instead of json?

### ISSUE THREAD

**Issue by yelnyaface** [yajra/laravel-datatables#1063]
hi, sorry but I ma kind of new to the datatables

I have a function in a controller:

```
    // Show the Restaurant Working hours
    public function showResWorkingHours($id)
    {
        $restaurant = $this->restaurantRepository->findWithoutFail($id);

        $res_workingHours = $restaurant->workingHours()->get();


        if (empty($res_workingHours)) {
            Flash::error('Restaurant Do not have working hours');

            return redirect(route('restaurant.index'));
        }

        $test = Datatables::of($res_workingHours)
            ->addColumn('action', 'res_working_hours.datatables_actions')
            ->make();

        return $test->render('res_working_hours.index');

        // return view('res_working_hours.index')->with('resWorkingHour', $res_workingHours);
    }
```

to show the data in the Datatable, but instead I am getting the json:

`{"draw":0,"recordsTotal":7,"recordsFiltered":7,"data":[[1,1,1,"1100-1500,1800-2200","<form method=\"POST\" action=\"http:\/\/localhost\/fc_project_a\/public\/resWorkingHours\/1\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"dTgZPQrdxRuJyOPiUK469qRZpJQQL7Ny45v7NZcK\">\n<div class='btn-group'>\n    <a href=\"http:\/\/localhost\/fc_project_a\/public\/resWorkingHours\/1\" class='btn btn-default btn-xs'>\n        <i class=\"glyphicon glyphicon-eye-open\"><\/i>\n    <\/a>\n    <a href=\"http:\/\/localhost\/fc_project_a\/public\/resWorkingHours\/1\/edit\" class='btn btn-default btn-xs'>\n ....`

instead, what I did wrong in the implementation?

Thank You

**Comment by yajra** [comment]
You can add if condition to alter the response:

```php
if (request()->ajax()) {
$test = Datatables::of($res_workingHours)
            ->addColumn('action', 'res_working_hours.datatables_actions')
            ->make();
}

return view('res_working_hours.index');
```

**Comment by yehximin** [comment]
hi, I have added the `if (request()->ajax()) {`

but I am getting:

`Undefined variable: dataTable (View: C:\xampp\htdocs\fc_project_a\resources\views\res_working_hours\table.blade.php) (View: C:\xampp\htdocs\fc_project_a\resources\views\res_working_hours\table.blade.php)`

This is the view.blade.php:

```
@section('css')
    @include('layouts.datatables_css')
@endsection



{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection
```

**Comment by yehximin** [comment]
actually the function above is in a `restaurantController`:

```
class restaurantController extends AppBaseController
{

...

   // Restaurant Datatable List page
    public function index(restaurantDataTable $restaurantDataTable)
    {

        return $restaurantDataTable->render('restaurant.index');

    }


    // Show the Restaurant Working hours
    public function showResWorkingHours($id)
    {
        $restaurant = $this->restaurantRepository->findWithoutFail($id);

        $res_workingHours = $restaurant->workingHours()->get();


        if (empty($res_workingHours)) {
            Flash::error('Restaurant Do not have working hours');

            return redirect(route('restaurant.index'));
        }

        if (request()->ajax()) {

            $test = Datatables::of($res_workingHours)
                ->addColumn('action', 'res_working_hours.datatables_actions')
                ->make();

        }

        //return $test->render('res_working_hours.index');

        return view('res_working_hours.index');
    }


}
```

I have another datatable class called `restaurantDataTable`: 


```
class restaurantDataTable extends DataTable
{

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
    {

        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', 'restaurant.datatables_actions')
            ->make(true);
    }

...

}
```

but this `restaurantDataTable` only used for showing `restaurant list datatable page`, which when clicked the added action column will goto `edit restaurant info form page`

I am trying to create another `restaurant list datatable page`, tht when clicked the added action column will goto `restaurant working hours list datatable page`, which is another datatable list showing 7 rows (days) of working hours for that res_id.

I added the function `restaurantController@showResWorkingHours` into `restaurantController` to try achieve that, but it is returning the json instead of the datatable view.

another way I trying to do is clone `restaurantDataTable` & create:

```
class resWorkingHourDataTable extends DataTable
{

    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', 'restaurant.workinghours_datatables_actions')
            ->make(true);
    }


}
```

and add it into `restaurantController@showResWorkingHours` like:

```
class restaurantController extends AppBaseController
{

   // Restaurant Working Hour Datatable List page
    public function showResWorkingHours(resWorkingHourDataTable $resWorkingHourDataTable)
    {

        return $resWorkingHourDataTable->render('restaurant.index');

    }

}
```
the `view.blade.php` is expecting a `'dataTable'` object is there anyway I can return a `datatable object `with:

```
            $test = Datatables::of($res_workingHours)
                ->addColumn('action', 'res_working_hours.datatables_actions')
                ->make();
```

?
