### ISSUE TITLE
Compatible with yajra/laravel-oci8 ?

### ISSUE THREAD

**Issue by guilhermegonzaga** [yajra/laravel-datatables#1064]
I'm using Laravel version 5.4
This package is compatible with yajra/laravel-oci8 ?
I need make any change?

**Comment by yajra** [comment]
@guilhermegonzaga yes it's compatible. If you're upgrading from LDT v6 - v7, please see [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade).
