### ISSUE TITLE
Total over all pages for serverside datatable show currentpage only

### ISSUE THREAD

**Issue by Neha223** [yajra/laravel-datatables#1067]
i want to show sum of current page and total pages for my serverside datatable
i use sum plugin like this

$('#mytable').DataTable({
        processing: true,
        serverSide: true,
        stateSave: true,
        ajax: 'stock/data-json',
        "fnDrawCallback": function() {
        var api = this.api();

        // Total over all pages
        var total = api.column(4).data().sum();

        // Total over this page
        var pageTotal = api.column(4, {page:'current'}).data().sum();
        $(api.column(4).footer()).html(pageTotal + ' ( ' + total + ' total)');
    }
});
the sum total shows the current page
i know this is bacause it loads only the current page and it cannot see the other records
now how i can show the correct sum of all pages in the footer

**Comment by yajra** [comment]
You can additional data response. See [docs](https://yajrabox.com/docs/laravel-datatables/7.0/response-with) for ref.

**Comment by Neha223** [comment]
But how can i use that.I am totally new to laravel and also to datatables.Thanks for help in advance.

**Comment by yajra** [comment]
There are several duplicate issues like this. See this https://github.com/yajra/laravel-datatables/issues/277 for a start.
