### ISSUE TITLE
How to get full used query ? 

### ISSUE THREAD

**Issue by BogdanSchimbischi** [yajra/laravel-datatables#1068]
It is possible to get full query of Datatables on filter ? I want to make a custom csv export.  Something like $datatables->getQuery() ? 

- Operating System Mac OS
- PHP Version 5.6
- Laravel Version 5.4
- Laravel-Datatables Version 7.2

**Comment by yajra** [comment]
I think this not yet supported/possible. Will review the code and I guess this can be considered as enhancement. Thanks!

**Comment by DMeganoski** [comment]
Would just like to point out that you can get the most recent queries from laravel itself. And since version 5.0 (I think) this is disabled by default, so you can just do 
```php
\DB::enableQueryLog();
$table = Datatables::of($query) {
    // etc.
}
$log = \DB::getQueryLog();
```

**Comment by yajra** [comment]
Implemented on master branch and will be available on Laravel 5.5. But we can also implement on Laravel 5.4 version if needed.

```php
        $dataTable = $datatables->eloquent(App\User::query());
        $response  = $dataTable->make(true);
        $query = $dataTable->getQuery()->get();

        return $response;
```

**Comment by BogdanSchimbischi** [comment]
Thank you for this new feature. Can you please implement also on Laravel 5.4 ? I see that 5.5 is major release and my project is not tested yet for 5.5 

Thank you again.

**Comment by fricred** [comment]
@yajra can we have the last used query without the limit? , currently i get something like 
```php

 $query = $dataTable->getQuery()->toSql();
  Log::info($query);
  
//select distinct CONCAT(users.name,' ',IFNULL(users.surname, '')) as username,
//          `users`.`id`, `users`.`country`
//        , `users`.`email`
// from `users` 
// left join `registrants` on `users`.`id` = `registrants`.`users_id`
// limit 10 offset 10 
``` 
but i want to run without the `limit 10 offset 10` is for a `Select all` feature

**Comment by yajra** [comment]
@fricred maybe `->skipPaging()->getQuery()`?

**Comment by govindtotla** [comment]
I did try the same to get queries logged but no success.
My issue: when we search something, it get filtered results based on searchable colors, but there is a parent-child relationship in the same table so I need all the parent ids from the search result and then I wanted to make a data table.

but as default behavior, after all the custom processing we just pass the query builder to the data table and Datatables::of($posts) apply filter with in the method and draw the table.

Any help will be appriciable.
