### ISSUE TITLE
Sorting and search doesn't work

### ISSUE THREAD

**Issue by lpredova** [yajra/laravel-datatables#107]
I've implemented datatables and everything seems fine it populates table with data but when it comes to searching and sorting values in collumns it doesnt work.

Method in controller looks like this:

public function getData()
    {
        $users = $this->repository->all(array('id','name','username','email'));
        return Datatables::of($users)
            ->add_column('actions',
                '<button type="button" data-event="edit" class="btn btn-default btn-xs"><i class="fa fa-edit"></i> Uredi</button>&nbsp;&nbsp;<button type="button" data-event="delete" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Obriši</button>',false)
            ->add_column('oznaka','<input type="checkbox" data-event="select-row">',true)
            ->make(true);
    }

var rootNode = $('#group-datatable');
            var tableSetup = {
                "bProcessing": true,
                "bServerSide": true,
                "bSearchable": true,
                "sAjaxSource": "{{route('Admin.Users.Data')}}",
                "columns": [
                    {
                        "data": "oznaka",
                        "title": '<input type="checkbox" data-event="select-all"> Oznaka',
                        "width": "90px"
                    },
                    {"data": "name", "title": "Ime"},
                    {"data": "username", "title": "Korisnk"},
                    {"data": "email", "title": "Email"},
                    {"data": "actions", "title": "Akcije"}
                ],
                "createdRow": function (row, data, index) {
                    $(row).attr('data-key', data.id);
                },
                "footerCallback": function (row, data, start, end, display) {
                    $(this.api().column(1).footer()).html(
                            '<button type="button" data-event="new-row" class="btn btn-default btn-sm"><i class="fa fa-plus-square"></i> Dodaj novi</button>&nbsp;<button type="button" data-event="bulk-delete" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i> Obriši</button>'
                    )
                }
            };

Am I missing something? What should I do to make searching and sorting work ?

**Comment by yajra** [comment]
@lpredova, since your using `make(true)`, you need to add `name` on your js. See this demo for ref.
http://datatables.yajrabox.com/eloquent/basic-object

**Comment by lpredova** [comment]
I've updated code so it looks like this now:

"columns": [
                    {
                        "data": "oznaka",
                        "title": '<input type="checkbox" data-event="select-all"> Oznaka',
                        "width": "90px"
                    },
                    {"data": "name", "title": "Ime" , "name": 'name'},
                    {"data": "username", "title": "Korisničko ime" , "name": 'username'},
                    {"data": "email", "title": "Email" , "name": 'email'},
                    {"data": "actions", "title": "Akcije" , "name": 'actions'}
                ],

but still no luck.

Im using Laravel 5, and without 

"processing": true,
 "serverSide": true,

thing wont work but when I add it i can get data but no sort and search. 

Any more Ideas what could be the issue ?

**Comment by yajra** [comment]
actions should not be sortable and searchable. `{"data": "actions", "title": "Akcije" , "name": 'actions', searchable: false, orderable: false}`. And try inspecting the results using firebug or chrome dev tools to see the error. It will help you debug faster.

**Comment by yajra** [comment]
>Im using Laravel 5, and without
> "processing": true,
> "serverSide": true,

BTW, you need to use the latest approach for DataTable 1.10++ which at least requires three parameters. `processing`, `serverSide` and `columns` definition.

**Comment by lpredova** [comment]
I've tried to set actions not searchable but still no luck.

If I use it without serverSide or processing,and use standard json It wont even populate table and it reports :

Uncught type error :  Cannot use 'in' operator to search for 'length' in

**Comment by yajra** [comment]
can you please paste the actual error you're encountering? I do suggest that you follow the conventions as provided the link above. It seems like your updating your app from an older version so I suggest you also review the new ajax option of datatables.net for v1.10++. Below are some links for ref:
- https://datatables.net/reference/option/ajax
- https://datatables.net/examples/server_side/
- https://datatables.net/examples/ajax/index.html

**Comment by lpredova** [comment]
I've solved the issue, the thing was that I was using old version of datatable library, few months ago the patched this bug and now everything is OK.

Tnx for your help!
