### ISSUE TITLE
[Bug] Multiple Add Column rendering problem in ^7.2

### ISSUE THREAD

**Issue by pyaehein** [yajra/laravel-datatables#1073]
### Summary of problem or feature request

Multiple Add Column with view or HTML String is not rendering very well.
It's only show one of table file as button and other is show as string.

ps: It's work well with ~6.0 but not work with ^7.2

### Code snippet of problem

```php
$query = Role::all();
return Datatables::of($query)
            ->addColumn('firsttest', function ($role) {
                  return '<button>Test</button>';
            })
            ->addColumn('secondtest', function ($role) {
                  return '<button>Test Two</button>';
            })->make(true);
```

### System details

- Operating System : MACOS
- PHP Version : 7.1
- Laravel Version : 5.4
- Laravel-Datatables Version ^7.2

**Comment by yajra** [comment]
Expected behavior on v7. See [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade) for details. You need to use `rawColumns` to render html.

**Comment by pyaehein** [comment]
Thank, it's work
