### ISSUE TITLE
Value is truncated when using rawColumns

### ISSUE THREAD

**Issue by paguemaou** [yajra/laravel-datatables#1075]
### Summary of problem or feature request

First, many thanks for your awesome packadge !

The returned value (my table's id) is truncated when/without using rawColumns (see the sippets).

Maybe I use a wrong syntax ? 

### Code snippet of problem

 
```php
$uais = Test::select([
                        'numero_uai',
                        'patronyme_uai',
                        ])->where('numero_uai','=','0330060L');

/* 
returned value 
dd($uais->get()); 
...
#original: array:2 [▼
        "numero_uai" => "0330060L"
        "patronyme_uai" => "FLORA TRISTAN"
...
*/
        return Datatables::of($uais)
            //->editColumn('numero_uai', 'partial.datatables_editcolumn_uai')
            ->rawColumns(['numero_uai'])
            ->make(true); 
```
The Datatables command returns :
```php
{"draw":0,"recordsTotal":1,"recordsFiltered":1,"data":[{"numero_uai":"330060","patronyme_uai":"FLORA TRISTAN"}],"queries":[{"query":"select count(*) as aggregate from (select '1' as `row_count` from `uais` where `numero_uai` = ?) count_row_table","bindings":["0330060L"],"time":26.02},{"query":"select `numero_uai`, `patronyme_uai` from `uais` where `numero_uai` = ?","bindings":["0330060L"],"time":0.52}],"input":[]}
```
As you can see, numero_uai value is now **"330060"** instead of **'0330060L'**.
It's the same thing if I comment the rawColumns ligne.

The schema and the Model are standard. **The numero_id column is my table's primary key.**
```php
Schema::create('uais', function(Blueprint $table)  
        {
            $table->string('numero_uai',8)->unique()->primary();
            ...
            $table->timestamps();
        });

<?php 
namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Test extends Model
 {
 	protected $table = 'uais';
 	
 	protected $primaryKey = 'numero_uai';

 	protected $fillable = [
		'numero_uai',
         ...];

	public 		$timestamps = true;
 }
```
### System details

- Operating System Linux homestead 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- PHP Version 7.1.0
- Laravel Version "5.4.*"
- Laravel-Datatables Version "^7.2",

Thanks in advance

**Comment by redalpha01** [comment]
I don't see how this is happening, all that rawColumns does is preventing it from going through escapeRow($row)

**Comment by redalpha01** [comment]
This may not be a rawColumns issue, run it without it and confirm whether it gives you the same thing or not.

**Comment by redalpha01** [comment]
try replacing ::of() with ::eloquent() and see if that changes anything.

**Comment by yajra** [comment]
I think the problem here is in your model. Laravel automatically cast primary key to int which explains the output. Try setting your model to `$incrementing = false;`.

**Comment by paguemaou** [comment]
, I just add this in my model 
```php
public $incrementing = false; 
```
My app is an upgrade from Laravel 5.1.11. I ignored this new feature.

Thanks a lot !
