### ISSUE TITLE
Method 'of' not found in \Yajra\Datatables\Facades\Datatables

### ISSUE THREAD

**Issue by noikiy** [yajra/laravel-datatables#1077]
![image](https://cloud.githubusercontent.com/assets/977243/24179989/62429e64-0eed-11e7-82bd-ef3a77c5810f.png)

**Comment by Skintillion** [comment]
use Yajra\Datatables\Datatables;

??

**Comment by yajra** [comment]
@Skintillion answer is correct. You can import the class instead of the facade for better IDE support.
