### ISSUE TITLE
Large Data Set

### ISSUE THREAD

**Issue by minedun6** [yajra/laravel-datatables#1078]
The title says it all.

The problem is that I execute the same query on my sql editor by limiting the query result to 1000, it runs fairly good/fast, but when I bump this value to 10000, it starts loading but then keeps on loading forever until there is a timeout.

The problem seems to be in the first query the package runs as it counts everything to get the pages count.
The tables I'm working with are 30,000 rows each.
Here's the query 

    ```sql
           select 
		 products.designation, 
		 packages.created_at, 
		 products.id as product_id, 
		 receptions.reference, 
		 packages.id as packages_id, 
		 receptions.id as receptions_id,
		 receptions.status,
		 suppliers.name as supplier_name,
		 suppliers.id as supplier_id, 
		 clients.name as client_name,
		 clients.id as client_id,
		 packages.state,
		 package_product.qty,
		 package_product.subpackages_number,
		 (package_product.qty * package_product.subpackages_number) as quantities,
		 delivery_package.qty as delivery_qty
                 from package_product
                 left join packages on package_product.package_id = packages.id
                 left join products on package_product.product_id = products.id
                 left join receptions on packages.reception_id = receptions.id
                 left join companies as suppliers on receptions.supplier_id = suppliers.id
                 left join companies as clients on receptions.client_id = clients.id
                 left join delivery_package on delivery_package.package_product_id = package_product.id
                 left join deliveries on deliveries.id = delivery_package.delivery_id
                #limit 10000
    ```
product_package table have 30.000 rows
delivery_package table have 30.000 rows
packages table have 30.000 rows.

Is there a way I can imporve on this ?

**Comment by Skintillion** [comment]
I had the same problem until I did some reindexing.

Index your database properly and it should be WAY faster.

**Comment by terdelyi** [comment]
It shouldn't be a problem if Datatable's javascript definition is using a "serverSide" option: https://datatables.net/reference/option/serverSide
