### ISSUE TITLE
Pdf export Problem between pages.

### ISSUE THREAD

**Issue by minedun6** [yajra/laravel-datatables#1082]
This seems to be an odd problem when having multiple pages when exporting to pdf.
How can this be solved ?

[Problem Screenshot](http://www.hostingpics.net/viewer.php?id=603613Capturedcran4.png)

**Comment by yajra** [comment]
You're using snappy right? Maybe try adjusting the margins via snappy options.

**Comment by minedun6** [comment]
I am using snappy indeed.
But problem is, I don't know if you did check the screenshot in my post, but does it have something to do with margins ?
In that case, where can I edit these options, do I need to override a method or somehing maybe.

**Comment by yajra** [comment]
You can override the margins on the config file. You can also override `pdf()` method and adjust accordingly as suggested on [snappy](https://github.com/barryvdh/laravel-snappy) package.Thanks!
