### ISSUE TITLE
ERROR Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by rafaelg21** [yajra/laravel-datatables#1083]
### ERROR Failed to load resource: the server responded with a status of 401 (Unauthorized)
alert (DataTables warning: table id=myTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7)

### ROUTE

routes.php
```
Route::get('almacen/categoria',['uses'=>'CategoriaController@getIndex', 'as' => 'datatables']);
Route::get('almacen/categoria.data',['uses'=>'CategoriaController@anyData', 'as' => 'datatables.data']);
```

### CONTROLLER

```
 public function getIndex()
    {
        return view('almacen.categoria.index');
    }

public function anyData()
    {   //return Datatables::queryBuilder(DB::table('categoria'))->make(true);
        $categorias = DB::table('categoria')
        ->select('idcategoria','nombre','descripcion','condicion')
        ->where('condicion','=','1')
        ->orderBy('idcategoria','desc');
        return Datatables::of($categorias)->make(true);
    }
```
### VIEW
```
<table class="table table-striped table-bordered table-condensed table-hover" id="myTable">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Opciones</th>                            
                        </tr>
                    </thead>
                    <tbody>                   
                   </tbody>
                </table>
<script>

$(document).ready(function(){
    $('#myTable').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "{!! url('almacen/categoria.data') !!}",        
        "columns":[
            {data:'idcategoria'},
            {data:'nombre'},
            {data:'descripcion'},
            {data:'condicion'},
        ]        
    });    
});
</script>
```
### RETURN DATA  PERFECT
http://localhost:8000/almacen/categoria.data
`
{"draw":0,"recordsTotal":12,"recordsFiltered":12,"data":[{"idcategoria":12,"nombre":"prueba","descripcion":"descrip prueba","condicion":1},{"idcategoria":11,"nombre":"Articulos de Limpieza","descripcion":null,"condicion":1},{"idcategoria":10,"nombre":"Animales","descripcion":null,"condicion":1},{"idcategoria":9,"nombre":"Equipos deportivos","descripcion":"Todos los accesorios","condicion":1},{"idcategoria":8,"nombre":"Liquidos","descripcion":"Todo tipo de liquidos","condicion":1},{"idcategoria":7,"nombre":"Servicio","descripcion":null,"condicion":1},{"idcategoria":6,"nombre":"Vestimenta","descripcion":null,"condicion":1},{"idcategoria":5,"nombre":"Comida","descripcion":null,"condicion":1},{"idcategoria":4,"nombre":"Medicina","descripcion":null,"condicion":1},{"idcategoria":3,"nombre":"Limpieza","descripcion":null,"condicion":1},{"idcategoria":2,"nombre":"Utiles","descripcion":null,"condicion":1},{"idcategoria":1,"nombre":"Equipos de Tecnologia","descripcion":null,"condicion":1}],"queries":[{"query":"select count(*) as aggregate from (select `idcategoria`, `nombre`, `descripcion`, `condicion` from `categoria` where `condicion` = ? order by `idcategoria` desc) count_row_table","bindings":["1"],"time":0.59},{"query":"select `idcategoria`, `nombre`, `descripcion`, `condicion` from `categoria` where `condicion` = ? order by `idcategoria` desc","bindings":["1"],"time":0.54}],"input":[]}
`
 
### RETURN VIEW CATEGORIA ERROR 
http://localhost:8000/almacen/categoria

```
ALERT JS 
DataTables warning: table id=myTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

### System details

- Operating System
- PHP Version
- Laravel Version 5.2
- Laravel-Datatables Version 1.10.7

**Comment by yajra** [comment]
Are you using artisan serve? If yes, try using apache/nginx. There are a lot duplicate issues like this and mostly due to php artisan serve.

**Comment by rafaelg21** [comment]
Thank you very much for your response and congratulations for the project.

Yes the problem is $ php artisan serve

Not Work 
http://localhost:8000/almacen/categoria

If Work
http://localhost/sisVentas/public/ventas/venta
