### ISSUE TITLE
How to create a hidden column?

### ISSUE THREAD

**Issue by thomasmoors** [yajra/laravel-datatables#1084]
As per title: How can one create a hidden column to store data that should not be shown directly?

**Comment by gsc89** [comment]
Easy peasy:
```

  private function getColumns()
    {
        return [
            'store_id' => ['name' => 'store_id', 'data' => 'store_id', 'visible' => false],
        ];
    }
```

**Comment by redalpha01** [comment]
Unless ypu want to show that column later, itd be better to just put it as a row attribute using datatable defcolumns

**Comment by redalpha01** [comment]
I can give you an example when i get on my computer.

**Comment by redalpha01** [comment]
And then you just casually $([rowSelector]).attr('first-attribute); when you need what's inside

**Comment by yajra** [comment]
Thanks for the answers guys! I think this is resolved. 👍
