### ISSUE TITLE
Is the website down

### ISSUE THREAD

**Issue by l-lawliett** [yajra/laravel-datatables#1087]
not showing whats wrong plz asap
http://datatables.yajrabox.com/

**Comment by naysumyat** [comment]
still cannot access the website.

**Comment by i255979** [comment]
unknown host yajrabox.com

**Comment by msashawky** [comment]
The same

**Comment by alperyazgan** [comment]
Still ??

**Comment by sabival89** [comment]
The site was down, but I guess it has been resolved now.

**Comment by yajra** [comment]
Yes, had some issue with the hosting but it's up now. Thanks!

**Comment by waiylgeek** [comment]
Website still down
