### ISSUE TITLE
Add additional object keys value pairs to the json response 

### ISSUE THREAD

**Issue by sabival89** [yajra/laravel-datatables#1089]
I will like to add additional key value pairs to the json response (after a result has been fetched) like the ones listed on the image below.

eg:

```
recordsFiltered: 3,
recordsTotal: 3 ,
key: value
```

![1](https://cloud.githubusercontent.com/assets/2057169/24580584/3a5a6950-1702-11e7-99af-64633ca10215.PNG)

Any ideas how I can achieve this please?

**Comment by yajra** [comment]
You can use with api. See https://yajrabox.com/docs/laravel-datatables/7.0/response-with for ref.

**Comment by sabival89** [comment]
Awesome. It worked. Thank you.

**Comment by kylesean** [comment]
@sabival89 Could you tell me how to render the additional value in html?
