### ISSUE TITLE
Apply ordering to field that is merged with concat?

### ISSUE THREAD

**Issue by kylescousin** [yajra/laravel-datatables#109]
I have this field in a query which looks like this:
DB::raw("CONCAT(users.firstname, ' ', users.lastname) as user")

So in the columns array in JS:
{data: 'user', name: 'users.firstname', render: function(data) {
  return data ? data : '&mdash;';
}},

Search and order works like this, but only on the firstname.
Is there a way to do search on the concatenated field? Something to simulate name: 'users.firstname' + 'users.lastname' ?

**Comment by yajra** [comment]
@kylescousin, you can use `filterColumn` to override the default global search for specific fields.

**Comment by yajra** [comment]
see this demo for ref. I made use of concat here. http://datatables.yajrabox.com/eloquent/post-column-search

**Comment by kylescousin** [comment]
Great, thanks!
