### ISSUE TITLE
Columns escape except one in the array

### ISSUE THREAD

**Issue by sebastienheyd** [yajra/laravel-datatables#1091]
Hello,

I see in the changelog that you escape all columns by default after the version 7.0.0

I suggest to add something like an escapeColumnsExcept() method to escape all columns except the one in the array.

For example : 

```
return Datatables::of(User::select())
          ->escapeColumnsExcept(['link'])
          ->editColumn('created_at', function ($user) {
            return ucwords($user->created_at->formatLocalized('%A %d %B %Y'));
        })->editColumn('roles', function ($user) {
            return $user->getRolesList();
        })->editColumn('link', function ($user) {
            return '<a href="'.route('users.edit', $user).'">Edit</a>'
        })->make(true);
```

In this example, all columns are escaped except the link column.

I can do a PR, but I'm not sure about the name of the method, is that clear enough ?

**Comment by redalpha01** [comment]
isn't this a duplicate of all the rawColumns issues

**Comment by sebastienheyd** [comment]
@redalpha01 yep that's it ! #909

**Comment by sebastienheyd** [comment]
Insted it can be useful to add rawColumns to the documentation : https://yajrabox.com/docs/laravel-datatables/master/xss
