### ISSUE TITLE
Slow Search on Has Many

### ISSUE THREAD

**Issue by ambrooo** [yajra/laravel-datatables#1093]
### Summary of problem or feature request

Hi,
I have 5000+ clients table rows, each clients has many addresses. When I perform a search with addresses included in search, the query is very slow. When I remove addresses from search, the query is quite fast. 

If I use Join, the search by address goes well, but the problem is that for each client that has more then one address the client is duplicated depending on the number of the addresses.

Bellow my code:

```
class Client extends Model{
public function addresses()
    {
        return $this->hasMany('App\Address', 'client_id', 'id');
    }
}

public function ajax()
    {
        $company = Auth::user()->company->cif;
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('addresses', function (Client $client){
                return $client->addresses->map(function($address){
                    return $address->address;
                })->implode('<br>');
            })->addColumn('action',  /*some action*/)
            ->make(true);
    }

public function query()
    {
        $workstation_id = Auth::user()->activeWorkstation()->id;

        $clients = Client::where('clients.workstation_id', $workstation_id)
            ->with('addresses')
            ->select('clients.*');

        return $this->applyScopes($clients);
    }
```
-->

### System details
- Laravel Version 5.2

**Comment by yajra** [comment]
Try indexing the columns that are used on searching.

**Comment by redalpha01** [comment]
Did laravel scout exist in 5.2? If so try using that with the mysql driver plugin

**Comment by redalpha01** [comment]
Packagee* also idk why im expecting you to have mysql butt there are different drivers out there if you canto have algolia

**Comment by ambrooo** [comment]
@yajra Can you give me a clue how to do that?

**Comment by redalpha01** [comment]
First of all I would suggest having your ajax call the index route of your ClientController for it to be more RESTful   
```
public function index(Request $request) // or ClientRequest if you have a custom request object
{
    If( $request->expectsJson() ) {
        //Datatable response 
    } else { //or else if( $request->expectsHtml())
        //View Response
    }
}
```
Secondly, it's going to be slow if you don't eager load and have to look for the addresses for each client one at a time so rather than have your query, try this and tell me if it helps
```
// in ClientController
$company = Auth::user()->company->cif; // Is this even used anywhere??

/*
 * This is considering that you have a use statement at the top, otherwise
 * use app/Client::with('adresses');
 */
$clients = Client::with('adresses');

return Datatables::eloquent($clients)
->addColumn(
    'addresses', function (Client $client) {
        return $client->addresses->map(
            function ($address) {
                return $address->address;
            }
        )->implode('<br>');
    }
)->make(true);

// in Client model
$company = Auth::user()->company->cif; // Is this even used anywhere??

/*
 * This is considering that you have a use statement at the top, otherwise
 * use app/Client::with('adresses');
 */
$clients = $this::with('adresses');

return Datatables::eloquent($clients)
->addColumn(
    //Seems silly to call Client inside the Client
    'addresses', function (Client $client) {
        return $client->addresses->map(
            function ($address) {
                return $address->address;
            }
        )->implode('<br>');
    }
)->make(true);
```

**Comment by ambrooo** [comment]
Thank you all for your responses. Any solution given didn't work for me. I went for the join method because the speed of search is more important on this instance then the disadvantage of duplicating clients that have more then one address.
Anyway, great plugin, it helped me a lot speeding this project.
