### ISSUE TITLE
Adding Editor buttons

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables#1095]
Hi, 
I am trying to add editor buttons as following.

	protected function getBuilderParameters()
	{
		return [
			'order'        => [[0, 'desc']],
			'dom'          => 'Bfrtip',
			'buttons'      => [
                                            'export', 
                                            'print', 
                                            'reset', 
                                            'reload', 
                                            ['extend' => 'create', 'editor' => 'editor'], 
                                            ['extend' => 'edit', 'editor' => 'editor'], 
                                            ['extend' => 'remove', 'editor' => 'editor']
                                      ],
			'select'       => true,
			'responsive'   => true,
		];
	}

I am expecting `['extend' => 'edit', 'editor' => 'editor']` to turn into `{"extend":"edit",editor:editor}` but I an getting it as `{"extend":"edit","editor":"editor"}` (Same issue with create and remove buttons)

The double quotes around "editor" is not allowing it to refer to editor instance defined in javascript. What is the best way to do it.

I did preg_replace just before the return statement in `vendor/yajra/laravel-datatables-oracle/src/Html/Builder.php` in `parameterize` function as following.

    public function parameterize($attributes = [])
    {
        $parameters = (new Parameters($attributes))->toArray();

        $values = [];
        $replacements = [];
        foreach($parameters as $key => &$value){
            if (!is_array($value)) {
                if (strpos($value, '$.') === 0)
                {
                    // Store function string.
                    $values[] = $value;
                    // Replace function string in $foo with a 'unique' special key.
                    $value = '%' . $key . '%';
                    // Later on, we'll look for the value, and replace it.
                    $replacements[] = '"' . $value . '"';
                }
            }
        }

        list($ajaxDataFunction, $parameters) = $this->encodeAjaxDataFunction($parameters);
        list($columnFunctions, $parameters) = $this->encodeColumnFunctions($parameters);
        list($callbackFunctions, $parameters) = $this->encodeCallbackFunctions($parameters);

        $json = json_encode($parameters);

        $json = str_replace($replacements, $values, $json);

        $json = $this->decodeAjaxDataFunction($ajaxDataFunction, $json);
        $json = $this->decodeColumnFunctions($columnFunctions, $json);
        $json = $this->decodeCallbackFunctions($callbackFunctions, $json);
        //For Editor Button
	    $json = preg_replace('/"(editor)"/','$1',$json);

	    return $json;
    }

But I really do not want to Modify vendor files.

**Comment by karmendra** [comment]
Anyone, any comment or direction?

**Comment by yajra** [comment]
I haven't personally tested editor with the builder so I guess it's not yet supported. Please submit a PR for a possible fix. Thanks!

**Comment by karmendra** [comment]
I would love to submit a PR, but I have never done that in past on Github, Can you point me somewhere I can follow step to submit PR that concur with your coding standards.

**Comment by karmendra** [comment]
Figured out, `Fork a project`, `make the changes in forked project`, `submit a PR from forked project` :).
I made the changes and submitted the PR.

**Comment by yajra** [comment]
Glad you sorted it out. On v7, builder was extracted to own plugin repo https://github.com/yajra/laravel-datatables-html.

**Comment by yajra** [comment]
PR merged and should fix this issue. Thanks!
