### ISSUE TITLE
Use datatables  , Array to string conversion , any ideas?

### ISSUE THREAD

**Issue by 1147832740** [yajra/laravel-datatables#1097]
### Use datatables  , Array to string conversion , any ideas?
Hi, ererybody 
User::with('role')  , i want it order by sum(the money of role) ,  when i click the money column , it got the error : Array to string conversion , any ideas? The relation of user and role : belongsToMany . The money is a column of role table .  Thanks.
### System details
- PHP Version 5.6.28
- Laravel Version  5.3.*
- Laravel-Datatables Version  v6.27.0

**Comment by yajra** [comment]
Can you please paste more snippets and the error dump? Or any steps to reproduce the issue? Thanks!

**Comment by 1147832740** [comment]
It solved, I used the join statement, it likes:
