### ISSUE TITLE
Enchancement: Make filterColumn and orderColumn return Eloquent builder.

### ISSUE THREAD

**Issue by ethaizone** [yajra/laravel-datatables#1099]
I used these two methods with eloquent query and found it return simple query builder so I cannot call scope or get model from it. It like pain in my ass. LOL

Do you think these two should get update or not?

**Comment by ethaizone** [comment]
This suggestion is not critical because we can use `filter` but `order` method return simple query builder.

https://github.com/yajra/laravel-datatables/blob/7.0/src/Engines/QueryBuilderEngine.php#L630

So right now I use `filterColumn` and `orderColumn` for call as **disable these actions** and create sort or search before send it to datatable class.

**Comment by yajra** [comment]
Good point. I think we can return Eloquent\Builder but not sure yet if this would be a breaking change. Or maybe override the whole method on EloquentEngine to make sure it only affect eloquent instances?

**Comment by yajra** [comment]
@ethaizone am reviewing this suggestion and it seems like this request is invalid since `filterColumn` is being used inside the `where($closure)` syntax, thus base query builder is needed for it to work properly. Thanks!
