### ISSUE TITLE
About Relationship 

### ISSUE THREAD

**Issue by Mahdi-Sahib** [yajra/laravel-datatables#1100]
when try to get all comment for one Article 
i use `article = Article::fine($id);` 
every thing is ok

 I need also the name of user  how write the # Comment

`{ data: 'user',      name: 'user'}`

Article Controller
```
public function commentsForOneArticle($id){
        article = Article::fine($id);
        return Datatables::of(Comment::where('article_id', $article->id))->make(true);
}
```

Article model

```
 public function commentsArticle() {
     return $this->hasMany('App\Comment');
 }
```

Comments model
```
    public function usersName() {
        return $this->belongsTo('App\User');
    }
```

### System details

- MAC OS 10
- php 7.1
- Laravel 5.4
- Laravel-Datatables Version 7.x

**Comment by yajra** [comment]
See belongsTo [demo](http://dt54.yajrabox.com/eloquent/belongs-to) for ref.
