### ISSUE TITLE
how to implement a sort without a default column id

### ISSUE THREAD

**Issue by oyw827** [yajra/laravel-datatables#1102]
hi yajra, 

since i don't have a cloumn named id in my database as the primary key , instead, the primary key is user_id, in my query, i certainly know how to get myself's sort with orderColumn, but the plugin sort by id by default, can i get any idea to avoid sorting by id by default?

thanks for your advice in advance;

**Comment by 1147832740** [comment]
The setting of datatables : sorting: [[ 1, "asc" ]]

**Comment by yajra** [comment]
@1147832740 answer should be able to help you setting the default sorting. Thanks!
