### ISSUE TITLE
The documentation is down

### ISSUE THREAD

**Issue by gperedor** [yajra/laravel-datatables#1103]
The documentation at https://datatables.yajrabox.com is not accessible at the moment. In fact, the website doesn't resolve to an IP address.

Where would we find the same documentation? It was more complete than what you can find on the wiki.

**Comment by kgengler** [comment]
Same issue here, I was able to pull up a snapshot on archive.org if that helps anyone else looking for the docs. https://web-beta.archive.org/web/20160624095606/http://datatables.yajrabox.com:80/

**Comment by yajra** [comment]
Was on vacation and was not able to check but I think the site is up now. Thanks!

**Comment by gilbert1995** [comment]
Can you made this doc availible on github? Thanks

**Comment by yajra** [comment]
Yes it is available on github @ https://github.com/yajra/laravel-datatables-docs

**Comment by gilbert1995** [comment]
Yes but it not full demo with HTML/CSS/PHP ;)

**Comment by yajra** [comment]
Yes, I have the doc parser on my site like how laravel docs works. It would be harder to maintain to have the html on github too :)

**Comment by gilbert1995** [comment]
What parser do you use?

**Comment by yajra** [comment]
It's a markdown parser package plus the styles from laravel docs.

`"erusev/parsedown-extra": "^0.7.1",`

**Comment by yajra** [comment]
BTW for the demo, you can setup a local copy if you like. 

[Laravel 5.0 - 5.1](https://github.com/yajra/laravel-datatables-demo).
[Laravel 5.4](https://github.com/yajra/dt54)
