### ISSUE TITLE
How to use this plugin to sort by convert(field using GBK)?

### ISSUE THREAD

**Issue by 1147832740** [yajra/laravel-datatables#1104]
### First of all , thank for this plugin!
How to use this plugin to sort by convert(field using GBK)?

### System details
- PHP Version   5.6.28
- Laravel Version  5.3.*
- Laravel-Datatables Version  6.27.0

**Comment by yajra** [comment]
You can use [orderColumn](https://yajrabox.com/docs/laravel-datatables/7.0/order-column) api for advance ordering sql.

**Comment by 1147832740** [comment]
Oh, it worked, thank you very much!@yajra
