### ISSUE TITLE
Unable to use OOP on Relationships to access the property.

### ISSUE THREAD

**Issue by BirdyUK** [yajra/laravel-datatables#1106]
### The following query returns several relationships in one fair sized object, In the object is nested relationships arrays, like so:

```
        $query = $this->model->with('quotes.provider')->with(['details.address', 'details.contacts' => function ($q) {
            $q->where('rel_type', global_config('rel_types', 'project'));
        }])->get();

         return $this->datatables
                        ->of($query)
            ->make(true);
```

Returns:

```
[0]	
id	44
project_id	2943875171
user_id	55
project_status	2
  -- details	
    id	1
    project_id	2943875171
    progress_from_status	1
    progress	"75"
       -- address
             id	1
             building	1
             street    main street
[1] ........

```

### If i try and return the value for anything that is in the nested details object so and example would be:
```
$project->details->address->building
```
### That will fail however this following example will work..
```
$project->details->address['building']
```

### And if i access a property on the details object like so:   

``` $project->details->progress ```  

### It seems my error comes when accessing propertys that are nested or past the first object layer... The error i get is...

```
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Trying to get property of non-object
```
<!--
If applicable, please include a copy of your code
which triggers the suspected bug.

You may use the markdown php code tags to format your paste:

### System details

- Operating System:  Ubuntu nginx
- PHP Version:   7.01
- Laravel Version:  5.4
- Laravel-Datatables Version:  7.6 i believe

**Comment by BirdyUK** [comment]
Solved!! - Turns out there was 1 column with a null value causing the whole table to fail.

**Comment by yajra** [comment]
Glad you were able to solve this. Thanks!
