### ISSUE TITLE
Smart Search Documentation Issue

### ISSUE THREAD

**Issue by apreiml** [yajra/laravel-datatables#1109]
### Summary of problem or feature request

The Documentation says that smart search enables the Datatables smart search feature, but in this project it is understood differently. The Datatables documentation says that smart search splits the string into individual words and searches for each of them. This project on the other hand just wraps the string with '%' chars.

See BaseEngine::setupKeywords

What would it take to implement this feature properly? Can I somehow help?

This may also be the problem for #881 .

**Comment by apreiml** [comment]
Seems like https://github.com/yajra/laravel-datatables/pull/998 is trying to achieve this.

**Comment by yajra** [comment]
@apreiml yes, the smart search implemented atm are just a wildcard database search. If you can test PR #998 on popular databases then if would really be a big help. We should try to support as much database as possible. Thanks!

**Comment by yajra** [comment]
Fixed on v7.4.0. Thanks!
