### ISSUE TITLE
Composer installs datatables in the wrong dir.

### ISSUE THREAD

**Issue by kylescousin** [yajra/laravel-datatables#111]
In my local environment, this problem does not occur. On a webserver I get this:

ReflectionException in Container.php line 736:
Class datatables does not exist

I did update composer and checked /vendor/ - DT seems to be installed here:
vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Datatables.php

is this path correct?
This is how the DT is called: return yajra\Datatables\Datatables::of($selection) - why does it not find the Datatables class on the web server and does find it locally?

The installation of laravel on the server is ~/laravel/ and the public files are in ~/public_html/ (the paths in autoload.php are adjusted)

Any idea?

**Comment by jrsalunga** [comment]
i have same problem.. how did you solve it? thanks!

**Comment by ahmadbadpey** [comment]
i have same problem But how can i solve that?

**Comment by ahmadbadpey** [comment]
I found the solution after hours of googling and try different ways :

1.first rename my project to a new name.
2.use composer update
3.run php artisan config:cache
4.and run php artisan cache:clear

and try your Code again.

**Comment by melisozmen** [comment]
I overlook the line below; after this everything works well..

php artisan vendor:publish
