### ISSUE TITLE
Undocumented auto-included wildcard columns

### ISSUE THREAD

**Issue by syphernl** [yajra/laravel-datatables#1116]
### Summary of problem or feature request

I'm selecting a few specific columns (`id`, `name`, `email`) using Eloquent, but for some reason DataTables adds in an additional `users.*` definition which means the rest of the table is also included in the result. However, in order to keep the data-set small, I'd like to limit this to the mentioned columns.

I haven't found anything in the documentation describing this behavior and whether it can be disabled somehow. 

### Code snippet of problem
```php
$data = User::select(['id','name','email']);
return Datatables::of($data)->make();       
```

This results in query:
```sql
select `id`, `name`, `email`, `users`.* from `users` desc limit 25 offset 0
```

I don't want it to include the `users.*` part.

### System details
- Operating System: Ubuntu
- PHP Version: 7.0.18
- Laravel Version: 5.4.19
- Laravel-Datatables Version: 7.3

**Comment by yajra** [comment]
Seems like it's working fine as per this [demo](http://dt54.yajrabox.com/eloquent/array)?

**Comment by syphernl** [comment]
@yajra Odd, the query of that particular demo doesn't contain the whole table indeed:
```json
      "query": "select `id`, `name`, `email`, `created_at`, `updated_at` from `users` where `users`.`deleted_at` is null order by `id` asc limit 10 offset 0",
```

**Comment by syphernl** [comment]
Hmm for some reason the [WithJoinTrait](https://github.com/sleeping-owl/with-join) causes this issue. If I disable it, it works just fine.

**Comment by yajra** [comment]
I see, add select was added on this line: https://github.com/sleeping-owl/with-join/blob/master/src/SleepingOwl/WithJoin/WithJoinEloquentBuilder.php#L161

The problem is on that package.
