### ISSUE TITLE
Making sure attributes with getMutators are mutated before being sent to the Datatable

### ISSUE THREAD

**Issue by fdvmarkus** [yajra/laravel-datatables#1119]
Hi,
I have several fields in the database that I want to store as decimal, but I want to display them as text in all views, including datatables. To achieve this, I use a mutator that checks if a field is defined as a decimal and changes the value to the appropriate value for the view. However, datatables does not access 

After digging through the code for datatables, I found that there are a few ways to make sure that the mutator is applied to the value before it is sent to the datatable.

1. Edit the column that contains the value I want and just return the value from the inline function.
2. Add a change in Processors/DataProcessor.php to add functionality to mutate attributes that *does* but has not been mutated already.

I don't like the first way, because it means that I have to be explicit about which fields are to be stored as decimals and presented as strings in several (very different) locations.

I don't like the second way, because it means that we have to check this package into the repository, instead of composer handling all third party packages.

Now I have two questions:

1. Is there a third way, different from the two I already mentioned, that will make sure all attributes that has a mutator gets the mutator applied to them before being sent to the datatable?

or

2. Should I submit a PR for the functionality described in the second way and just hope or wait until it makes it into the next release of Laravel-Datatables? I'm a little anxious about this, as it might break functionality if somebody is relying on datatables *not* applying mutators to attributes, but this might just be me overthinking it.

### System details

- PHP-Version 7.0
- Laravel Version 5.4
- Laravel-Datatables Version 7.3.0

**Comment by fdvmarkus** [comment]
After looking through the code again this morning, I found a way that makes this issue irrelevant for me. The issue stems from Datatables using Model::toArray(), which does not utilize mutators (laravel/framework#153).

The solution I settled on was, as mentioned in laravel/framework#153, was to overwrite toArray() (in the trait that is used) on the model.

I think this behavior (not utilizing mutators) should be documented, as the plugin was doing the opposite of what I expected and I had to dig pretty deep into the code to get an understanding about why it wasn't doing what I expected it to do. I'm not sure where in the documentation it should be added so I'm hesitant to go ahead and edit the wiki myself.

**Comment by yajra** [comment]
@fdvmarkus thanks for the findings. I was not aware of the mutators until this issue. If you can, would you please submit a PR for the mutators? I also think it would be nice to have mutation done before passing to dataTables. Thanks!

**Comment by nico-sorice** [comment]
A bit late to be honest, but might help someone googling...

I think the actual issue is that it wont execute mutators that dont share an attribute name, for example (asuming model has only 'date' attribute) $model->date_formatted wont be there when you serialize it or call toArray(), but it will have an effect if your accesor is actually called just like an existing field example $model->date.

To have your mutators that dont share name with an existant model attribute available when you use toArray, you can create an abstract class, call it something like BaseModel, and make the models you want to have this behaviour extends from this class.

Then, you can overwrite attributesToArray to something like this, so that it will execute mutators and it will respect $hidden and $visible expected behaviour

`public function attributesToArray()
        {
            $attributes = parent::attributesToArray();

            foreach ($this->getMutatedAttributes() as $key)
            {
                if ($this->hidden)
                {
                    if (in_array($key, $this->hidden)) continue;
                }

                if($this->visible)
                {
                    if (!in_array($key, $this->visible)) continue;
                }

                if (!array_key_exists($key, $attributes))
                {
                    $attributes[$key] = $this->mutateAttribute($key, null);
                }
            }

            return $attributes;
        }`

**Comment by safarovitch** [comment]
Thank you @nico-sorice. Solution still valid on laravel 8.*

**Comment by nico-sorice** [comment]
@safarovitch Hey there, (and anyone googling) there's a simpler way that doesn't require overriding that method anymore.

You can add the attribute name to the model's `$appends` attribute.

```php
//In your eloquent model
public $appends = [
   'date_formatted',
];
    
public function getDateFormattedAttribute(){...}
```
