### ISSUE TITLE
Help for laravel users not used to datatables

### ISSUE THREAD

**Issue by basementjack** [yajra/laravel-datatables#112]
Hi Arjay, this package looks awesome and I really appreciate the demo app!

Would you consider adding to the Quick Start documentation, to help a user understand what other things are needed for this to work?

I followed the quick start, but my demo output is just this:
```text
Id	Name	Email	Created At	Updated At 
$(function() { 
$('#users-table').DataTable({ 
processing: true, serverSide: true, ajax: 'http://laravel5s/demo/data', 
columns: [
{data: 'id', name: 'id'}, 
{data: 'name', name: 'name'}, 
{data: 'email', name: 'email'}, 
{data: 'created_at', name: 'created_at'}, 
{data: 'updated_at', name: 'updated_at'} ] });
 });
```
After looking at the demo app, it looks like I also need to include some styles/javascript from the datatables project, but your demo project has so much css/javascript (Even some links to google ads and analytics!) that it's taking a really long time just to get started with the demo example.

Thanks!

**Comment by yajra** [comment]
@basementjack, yes, I am planning to make a Laravel 5.1 version of the demo app to show some of the new approach I've been using and to make a better documentation. BTW, the demo app is open source and open to contribution. https://github.com/yajra/laravel-datatables-demo.

Lastly, I just removed the ads script. Analytics will be retained as I'm trying to learn analytics too.

**Comment by yajra** [comment]
just published a quick starter tuts. Hopefully it helps (not good at writing/teaching). http://datatables.yajrabox.com/starter

**Comment by basementjack** [comment]
Arjay, the Quickstart looks AWESOME now!
