### ISSUE TITLE
Export CSV or Excel return JSON query result when using AJAX instead of downloading the files

### ISSUE THREAD

**Issue by razril** [yajra/laravel-datatables#1120]
Hi,

First of all, thanks a lot for this amazing package. 

basically I was using the basic usage of the Laravel-datatables but then we need to add export to csv and excel functionality so I added the `"yajra/laravel-datatables-buttons": "^1.1",` to my composer.json and following the example from https://yajrabox.com/docs/laravel-datatables/master/buttons-starter

but then I have some issue when exporting CSV or Excel.it will returning JSON query result instead of downloading the files. the issue only occur when I added Ajax('url-to-ajax') within HTML() function . 

note that all the export functionality is working fine when I remove the Ajax('url-to-ajax') from the HTML() function.

### System details

- Operating System : using laravel Homestead (Ubuntu 16)
- PHP Version : 7.1
- Laravel Version : 5.4
- Laravel-Datatables Version : 7.2

### here is what I am doing

created InventoryDataTable files using datatable console command :
`php artisan datatable:make Inventory`

### then here is my InventoryDataTable Class
```php
public function dataTable()
{
        return $this->datatables
            ->collection($this->query());
}

public function html()
{
return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('inventory-datatable')
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['pageLength','csv','excel' ],                      
                        'initComplete' => 'function() { $(\'#inventory-table tbody tr:eq(0)\').click();  }',
                    ]);
}
```

### here is my web route files 
```php
Route::get('/inventory-datatable','InventoryController@data');
```

### here is my Inventory Controller
```php
public function index(InventoryDataTable $datatable)
    {
    	return $datatable->render('inventory.index');
    }

    public function data()
    {
    	$collection = Inventory::getFromAPI();
    	return Datatables::of($collection)->make(true);
    }
```

then when every time I hit the excel or css button, then the browser will returning the JSON query result from "inventory-datatable" route, instead of downloading the files.

but when I am removing the Ajax() part from the HTML() function like this :
### then here is HTML() function in InventoryDataTable Class
```php

public function html()
{
return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('')
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['pageLength','csv','excel' ],                      
                        'initComplete' => 'function() { $(\'#inventory-table tbody tr:eq(0)\').click();  }',
                    ]);
}
```
then all the functionality is working fine... which is make me wonder what is wrong with the AJAX request. the url in the browser will looks like this when using Ajax() function and it will return the JSON result rather than the CSV or EXCEL files :
`http://laravel.local/inventory-datatable?draw=1&columns%5B0%5D%5Bdata%5D=vendor&columns%5B0%5D%5Bname%5D=vendor&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=aproduct&columns%5B1%5D%5Bname%5D=aproduct&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=version&columns%5B2%5D%5Bname%5D=version&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&action=csv`

do you guys know what causing the issue? also note that when I added Ajax url to the options the buildExcelFile() is not called, tried to dd() something there but it is always returning the JSON query string result.

Is there any difference when using Ajax() and not using Ajax() function (sorry for the newbie question) ? as I am using Collection engine i encounter an issue when trying to load the data that having more than 500 records if not using the Ajax('url') function, but when I use the Ajax('url') function then the data will be loaded normally. That is why I am asking this question.

Many Thanks,
Rangga

**Comment by yajra** [comment]
I think something is wrong on your controller/flow:

```php
public function index(InventoryDataTable $datatable)
    {
    	return $datatable->render('inventory.index');
    }

    // this method is not needed.
    public function data()
    {
    	$collection = Inventory::getFromAPI();
    	return Datatables::of($collection)->make(true);
    }
```

On your class, set ajax to same url as index:

```php
public function html()
{
return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('')
...
```

**Comment by razril** [comment]
Hi Arjay, thanks for the response... 
the initial use of the data function in controller is when using the datatable in basic usage (not using it as Service). in basic usage you have to defined the ajax options to pointed to the data function in your controller.
yes removing the ajax() function will make export works. i just confused on the word ajax here... since we are not set any ajax at all, does we make the datatable to work in the Ajax way?

Many Thanks,
Rangga

**Comment by yajra** [comment]
Setting empty ajax means the current url will be used to fetch the request. This way, you can reuse your dataTable class in any route you desired as it will inherit the current url as the handler for all the request. Thanks!
