### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by myaot** [yajra/laravel-datatables#1122]
### Summary of problem or feature request

In my MainInventoryDatatable, I need to display two database tables and I used UNION SQL operator but search not working properly. 

### Code snippet of problem

These are the datatable codes:
![inventorydatatable-ajax-and-query](https://cloud.githubusercontent.com/assets/13942505/25423183/4c681456-2a96-11e7-8ac1-39d3a34f9e7f.png)
![inventorydatatable-getcolumns](https://cloud.githubusercontent.com/assets/13942505/25423191/5550c7a2-2a96-11e7-869b-01b9b92e29b7.png)

Here's my controller code:
![controller](https://cloud.githubusercontent.com/assets/13942505/25423202/5f264d60-2a96-11e7-8af8-317bb3b441f4.png)

Here's my datatable table search result sample:
![search-result](https://cloud.githubusercontent.com/assets/13942505/25423222/70e5343a-2a96-11e7-8c28-888e87da25a7.png)

### System details

- Operating System
    Windows 8.1
- PHP Version
    7.0.15
- Laravel Version
    5.1
- Laravel-Datatables Version
  ^6.6.0

**Comment by yajra** [comment]
Hi, I suggest you inspect the ajax response to get a better hint of what's causing the issue. Most probably, the generated SQL have some errors. From there, we can further dig on to do next. Please paste the error dump too. Thanks!

**Comment by myaot** [comment]
Thanks. Btw, I just disabled search for other columns except Store #. It's working now.
