### ISSUE TITLE
Upgrade guide from 6.17.0 to 6.28.1

### ISSUE THREAD

**Issue by mansouralex** [yajra/laravel-datatables#1130]
Hello @yajra 

Is there any breaking changes when upgrading from the noted versions?

As I have upgraded recently and it seems the filterColumn custom DB column names is not working as expected.

**Comment by yajra** [comment]
Yes there are. Please see http://yajrabox.com/docs/laravel-datatables/7.0/upgrade for details. Thanks!

**Comment by yajra** [comment]
Oh my bad, it's v6..  Reviewing...

**Comment by yajra** [comment]
AFAIK, I think there was a recent drop on dompdf dependency that may have cause a breaking change..

Found the thread: https://github.com/yajra/laravel-datatables/pull/1026

Aside from this, I think there is no breaking change added.

**Comment by yajra** [comment]
Looking at merge PR's and seems fine with me: https://github.com/yajra/laravel-datatables/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20%5B6.0%5D

**Comment by mansouralex** [comment]
@yajra Thanks for the details. What do you suggest to get the custom column naming and filter work again in the newer version?  

BTW, How we can downgrade to 6.17.0?

**Comment by yajra** [comment]
To downgrade, I think you can just specify `6.17.0` on composer and do an update.

For filterColumn, just use the same `name` you used on javascript.
