### ISSUE TITLE
Change DataTable object name in Service approach

### ISSUE THREAD

**Issue by kamrava** [yajra/laravel-datatables#1133]
When I'm using Yajra DataTables as Service it automatically specifies a object name to it:
```javascript
window.LaravelDataTables.dataTableBuilder
```
How can I manually set a name for that?

For instance I want something like this:

```javascript
window.LaravelDataTables.MyCustomName
```

Any help would be great appreciated.

**Comment by yajra** [comment]
While rendering the table, pass the id attribute.

```blade
{!! $dataTable->table(['id' => 'my-table']) !!}
```

**Comment by kamrava** [comment]
@yajra Thank You.

```
{!! $dataTable->table(['id' => 'UsersTableList']) !!}
```

And then we can use that like this:
```javascript
LaravelDataTables["UsersTableList"].draw();
```

Cheers
