### ISSUE TITLE
Export not working when I apply filters!

### ISSUE THREAD

**Issue by kamrava** [yajra/laravel-datatables#1135]
I'm using DataTables as-Service approach.

> Laravel 5.4
> Yajra DataTables v7.4.0

Datatables works fine when I export all data (without any filters). But when I apply a filter(for example `gender=male` )and export it as Excel or CSV it downloads the file but file is empty!

Any ideas?

P.S:
If you need my code to answer to my question feel free to ask me and I will attach the code.

**Comment by kamrava** [comment]
Sorry this problem occurred because of my Download Manager.

Everything works fine.

**Comment by yajra** [comment]
Thanks for the feedback. Not really sure how DM works so I may not be able to answer your question.
