### ISSUE TITLE
DataTables rendering always 6 columns but I defining only one

### ISSUE THREAD

**Issue by vertisan** [yajra/laravel-datatables#1136]
### Summary of problem or feature request

I'm using DataTables by services. Now I want to render only selected columns so I defined it but in rendered table I have always 6 < td> marks - why?

### Code snippet of problem

```php
class FaqsDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @return \Yajra\Datatables\Engines\BaseEngine
     */
    public function dataTable()
    {
        return $this->datatables
            ->eloquent($this->query());
    }

    /**
     * Get the query object to be processed by dataTables.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
        $query = Faq::select(['question']);

        return $this->applyScopes($query);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('');
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'question'
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'faqsdatatable_' . time();
    }
}

```

### System details

- Operating System **Windows 10 PRO**
- PHP Version **5.6/7.1**
- Laravel Version **5.4**
- Laravel-Datatables Version **7**

**Comment by DMeganoski** [comment]
Could you also post you JS initialization of the table, please?

**Comment by vertisan** [comment]
Sure, here is JS what's is initialized by blade snippet $dataTable->scripts()
```javascript
(function(window, $) {
    window.LaravelDataTables = window.LaravelDataTables || {};
    window.LaravelDataTables["dataTableBuilder"] = $("#dataTableBuilder").DataTable({
        "serverSide": true,
        "processing": true,
        "ajax": "",
        "columns": [{
            "name": "id",
            "data": "id",
            "title": "Id",
            "orderable": true,
            "searchable": true,
            "attributes": []
        }, {
            "name": "name",
            "data": "name",
            "title": "Name",
            "orderable": true,
            "searchable": true,
            "attributes": []
        }, {
            "defaultContent": "",
            "data": "action",
            "name": "action",
            "title": "Action",
            "render": null,
            "orderable": false,
            "searchable": false,
            "width": "80px",
            "attributes": []
        }],
        "order": [
            [0, "desc"]
        ],
        "buttons": ["create", "export", "print", "reset", "reload"]
    });
})(window, jQuery);
```

**Comment by DMeganoski** [comment]
Ah, right. Haven't tried using the scripts function yet, so I'm not exactly familiar, but I've seen this happen before when you define the column in js but not in the data.

It would seem that it's generating js that contains 3 columns. 'id', 'name', and 'action'. From what I can see, your code looks valid. I suspect this may be a bug, though I can't find where these 3 columns are defined in the package...

If this is holding you back, you can simply copy and modify the js and omit the `$dataTable->scripts()` call. It will always only display the columns defined in the javascript, even if php provides more. 

This should work, unless you wanted the columns defined dynamically, which would be a bit more difficult. (at least until it gets fixed)

**Comment by yajra** [comment]
I think there are some inconsistency in the issue? You said 6 td are displayed but then you have 3 columns defined on your script? I think the provided snippets are invalid in some ways.

Did you use `$dataTable->table()` to generate the table html?

Anyways, can't replicate the issue. Can you provide the view snippets your using if possible? Thanks!
