### ISSUE TITLE
duplicate query when use filter()

### ISSUE THREAD

**Issue by eness** [yajra/laravel-datatables#1140]
### Summary of problem or feature request

I use datatables with filter() method on the controller side. And when I enable this filter() method, it duplicates the first query sent to database, but if I disable that filter() feature, the query below is being sent once :

```
select count(*) as aggregate from (select '1' as `row_count` from `purchase_offers` where `purchase_offers`.`deleted_at` is null and `purchase_offers`.`deleted_at` is null) count_row_table;
```

Screenshot from duplicated query  : 

![image](https://cloud.githubusercontent.com/assets/2032225/25854146/b5c72572-34d7-11e7-8240-50c28b9dedc9.png)

### Code snippet of problem

```php
<?php
            $offers = PurchaseOffer::with('purchase');

            $now = new Carbon;

            return \Datatables::of($offers)
                ->filter(function ($query) use ($request) {
                    
                    // filter: search in item name
                    if ($request->has('search.value')) {
                        $query->where('item_name', 'like', '%'.$request->input('search.value').'%');
                        $query->orWhere('bidder_name', 'like', '%'.$request->input('search.value').'%');
                    }

                })
                ->addColumn('id', function ($offer) {

                    return $offer->id;
                })
                ->addColumn('status', function ($offer) {

                    return $offer->colored_field('status', true);
                })
                ->rawColumns(['status'])
                ->make(true);
```

### System details

- Ubuntu
- PHP 7.0
- Laravel 5.4
- Laravel-Datatables 7.3.0

**Comment by yajra** [comment]
It is the expected behavior. First count is for the `totalRecords` while the 2nd count is for `filteredRecords`. Thanks!

**Comment by azamrizki** [comment]
it happened the same as my case, thanks for the explanation
