### ISSUE TITLE
Transform then order the collection

### ISSUE THREAD

**Issue by twocngdagz** [yajra/laravel-datatables#1142]
### Summary of problem or feature request

I am using transformer to add additional computed columns, now I wanted to make this columns sortable. But my problem is, orderRecords is being called first before transforming, so there is no way for me to sort the columns I added on my transformer.

Is there a way for me to do achieve this?

Thanks

**Comment by yajra** [comment]
Good point. Currently, there is no way to achieve this afaik. Tagging for enhancement. Thanks!

**Comment by twocngdagz** [comment]
Thanks, looking forward for this enhancement.

**Comment by yajra** [comment]
I just submitted a PR to support this request. Can you please verify if it fixes this issue? Thanks!

**Comment by twocngdagz** [comment]
Yes, I will
