### ISSUE TITLE
How to render HTML in column 

### ISSUE THREAD

**Issue by nu1ww** [yajra/laravel-datatables#1143]
How to render HTML in column ?? only action column render as HTML

**Comment by DMeganoski** [comment]
https://yajrabox.com/docs/laravel-datatables/7.0/raw-columns

**Comment by nu1ww** [comment]
Thankuu :)

**Comment by mkcircles** [comment]
Hello @yajra i have this challenge. How do i render HTML code in datatables
![screen shot 2018-10-06 at 3 42 01 pm](https://user-images.githubusercontent.com/7066665/46571497-a10f5900-c97e-11e8-80ae-792c0efd4172.png)

**Comment by vipertecpro** [comment]
->rawColumns([
                    'Hits'
                ])

Just add this you're good to go

**Comment by chiragshahphp** [comment]
Just need to add **->escapeColumns([])** like as below ``
```
return Datatables::of($posts)
	->editColumn('address1', function ($user) {
	     return $user->address1 .'<br>'.$user->city_name .'<br>'.$user->state_name .'<br>'.$user->pin_code;
	})
	->escapeColumns([])
	->make(true);
```
```

**Comment by chiragshahphp** [comment]
Just need to add **->escapeColumns([])** like as below ``
```
return Datatables::of($posts)
	->editColumn('address1', function ($user) {
	     return $user->address1 .'<br>'.$user->city_name .'<br>'.$user->state_name .'<br>'.$user->pin_code;
	})
	->escapeColumns([])
	->make(true);
```
```

**Comment by MrSenhaji** [comment]
> Just need to add **->escapeColumns([])** like as below ``
> 
> ```
> return Datatables::of($posts)
> 	->editColumn('address1', function ($user) {
> 	     return $user->address1 .'<br>'.$user->city_name .'<br>'.$user->state_name .'<br>'.$user->pin_code;
> 	})
> 	->escapeColumns([])
> 	->make(true);
> ```

This work perfectly for me, thx

**Comment by parmarvishal21** [comment]
> Just need to add **->escapeColumns([])** like as below ``
> 
> ```
> return Datatables::of($posts)
> 	->editColumn('address1', function ($user) {
> 	     return $user->address1 .'<br>'.$user->city_name .'<br>'.$user->state_name .'<br>'.$user->pin_code;
> 	})
> 	->escapeColumns([])
> 	->make(true);
> ```

thank you
