### ISSUE TITLE
Suggestion: add config options for default xss exceptions

### ISSUE THREAD

**Issue by DMeganoski** [yajra/laravel-datatables#1144]
It would be nice if you could edit the default exceptions for the xss protection. I typically use the term 'actions' not 'action' and also would like to add a few other fields such as 'status' (usually an integer in the db).

You may also want to add the option to disable the xss protection. It's always better to have the safe way as default and be forced to disable it than to have the unsafe way default and forget to implement it, but there are those who may want to do their own escaping.

If you could throw those in it would be much appreciated. :)

- Win 7 / Xubuntu VM
- PHP 7.0
- Laravel 5.4 (Recently upgraded from 5.3)
- Laravel-Datatables 7.4

**Comment by yajra** [comment]
Good points. Will try to implement this when I had the chance. Thanks for the great idea.

**Comment by yajra** [comment]
@DMeganoski PR added as suggested. Can you please check if it's acceptable on your side? Feedbacks/suggestions appreciated. Thanks!

**Comment by DMeganoski** [comment]
Awesome, thanks. :smile: Close. Just one issue. You need to use a recursive merge [here](https://github.com/yajra/laravel-datatables/commit/07e56b2259556bef8e57559b3fcbd386386620c8#diff-e6741cb67824605796a581758f3accd1R686) otherwise, the config values for each of the excess, escape, raw, etc. columns will be overridden, not merged, if defined in the config. 

Be wary though, I have had issues with [array_merge_recursive()](http://php.net/manual/en/function.array-merge-recursive.php) when the array contains numeric keys. I don't see this being a problem here, just a heads-up.

Other than that, seems to be perfect. I was actually going to suggest adding options for those other arrays, I don't need them at the moment but could be useful in the future. Much appreciated.

**Comment by yajra** [comment]
Have updated the PR and use recursive. Thanks for the feedback! Released on v7.8.0 🚀
