### ISSUE TITLE
on local(windows) working fine but on server(ubuntu 16.04) errors?

### ISSUE THREAD

**Issue by vipin733** [yajra/laravel-datatables#1145]
i just install this package its working fine on  my local server but when i deploy my code its giving me errors 
" production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Datatables\DataTableBase' not found in"
i dont know why i double checked namespace is fine i deploy my code via git local to production(ssh)
thanks

**Comment by vipin733** [comment]
![2_teacher](https://cloud.githubusercontent.com/assets/10106412/26036789/624bc9b4-3902-11e7-93ea-6c0a0723ac98.PNG)
and my DataTableBase

`<?php

namespace App\DataTables;

use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Query\Builder;
use Yajra\Datatables\Datatables;
use Yajra\Datatables\Engines\BaseEngine;
use Yajra\Datatables\Services\DataTable;

class DataTableBase extends DataTable
{
  /*
    * The reason why this class exists is that Yajra/Datatables requires this service class for export methods to work
    * properly.
    */

   /** @var Builder The query that will be used to get the data from the db. */
   private $mQuery;

   /** @var array An array of columns */
   private $mColumns;

   /** @var BaseEngine The DataTable */
   private $mDataTable;

   /**
    * @param            $query
    * @param BaseEngine $dataTable
    * @param array      $columns
    */
   public function __construct($query, BaseEngine $dataTable, $columns) {
       parent::__construct(app(Datatables::class), app(Factory::class));

       $this->mQuery = $query;
       $this->mColumns = $columns;
       $this->mDataTable = $dataTable;
   }
    /**
     * Display ajax response.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
    {
      return $this->mDataTable->make(true);

    }

    /**
     * Get the query object to be processed by dataTables.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
      return $this->mQuery;
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
         return $this->builder()->columns($this->mColumns);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    // protected function getColumns()
    // {
    //     return [
    //         'id',
    //         // add your columns
    //         'created_at',
    //         'updated_at',
    //     ];
    // }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'datatablebases_' . time();
    }
}
`

**Comment by DMeganoski** [comment]
`namespace App\DataTables;`

`'App\Datatables\DataTableBase' not found`

Check your namespace capitalization.

**Comment by vipin733** [comment]
i just double checked everything is fine even on my mac i tested it working but when its goes live throwing errors

**Comment by vipin733** [comment]
here this is the filestrucutre on my server
![2](https://cloud.githubusercontent.com/assets/10106412/26062359/37adc616-39a8-11e7-970d-91826318c665.PNG)
![4](https://cloud.githubusercontent.com/assets/10106412/26062358/37aa943c-39a8-11e7-84fb-f2db875137a5.PNG)
![5](https://cloud.githubusercontent.com/assets/10106412/26062360/37bae3dc-39a8-11e7-8625-d68f87bddde2.PNG)

**Comment by DMeganoski** [comment]
you are declaring `DataTableBase` in the the `App\DataTables\DataTableBase` namespace but referencing `App\Datatables\DataTableBase` Notice, `Datatables` vs `DataTables`

**Comment by vipin733** [comment]
thanks , problem fixed
