### ISSUE TITLE
How to render a column in Mysql Json type ?

### ISSUE THREAD

**Issue by t-prod** [yajra/laravel-datatables#1148]
Hi,

Thanks for your awesome package. I try to display a mysql json field in the datatables.
I try to do this below

Example :

```php
$html = $builder->columns([
            ['data' => 'id', 'name' => 'id', 'title' => 'Id'],
            ['data' => 'position', 'name' => 'Position', 'title' => 'Position'],
            ['data' => 'title', 'name' => 'title->'.config('app.locale'), 'title' => 'Title'],
            ['data' => 'created_at', 'name' => 'created_at', 'title' => 'Created At'],
            ['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Updated At'],
 ]);
```
How can I do ?

Thanks again for your help

- PHP 7.0
- Laravel 5.4
- Laravel-Datatables 7.0

Regards

**Comment by DMeganoski** [comment]
I've not tried working with json data types, and I'm not sure how Laravel would go about handling that column. I typically just store serialized arrays in text fields.

If you are trying to translate your models, I would suggest using [Polyglot](https://github.com/Anahkiasen/polyglot) or [Laravel-Translatable](https://github.com/dimsav/laravel-translatable) to manage the translations.

**Comment by yajra** [comment]
I think you can cast the column to array? You can then access the data by using the key.

```
['data' => 'title.en', 'name' => 'title->'.config('app.locale'), 'title' => 'Title'],
```
