### ISSUE TITLE
Escaping data, new version.

### ISSUE THREAD

**Issue by Miguel-Frazao** [yajra/laravel-datatables#1153]
I had a functionality to make buttons (view, edit, delete etc...) on each row, with escaping html that doesn't work, doesn't give me an error but instead of the button it just outputs the raw html for the buttons, ex:

`<a title="View details" href="http://localhost:8000/...." class="actionButton btn btn-default btn-sm"><span class="fa fa-eye"></span></a>`

Is there any param I can pass into the method `$datatable->addColumn( ...)` so it doesn't escape and the espected output become correct (the button itself)?

**Comment by oriceon** [comment]
See rawcolumns() in documentation.
