### ISSUE TITLE
Help with buttons plugin 

### ISSUE THREAD

**Issue by rafailml** [yajra/laravel-datatables#1154]
### but table does not show any data.

My code:
Controller
```php
<?php
namespace Examples\Http\Controllers;

use Examples\DataTables\UsersDT;
use Illuminate\Http\Request;
use Examples\Http\Controllers\Controller;

class dt54Controller extends Controller
{
    public function index(UsersDT $dataTable)
    {
        return $dataTable->render('datatables/dt54');
    }

    public function create()
    {
        return view('buttons.eloquent.create');
    }
}
```

DataTable class:
```php
<?php
namespace Examples\DataTables;

use Examples\User;
use Yajra\Datatables\Services\DataTable;

class UsersDT extends DataTable
{

    public function dataTable()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', 'eloquent.tables.users-action');
    }

    public function query()
    {
        $query = User::query();

        return $this->applyScopes($query);
    }

    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->ajax('')
            ->addAction(['width' => '80px'])
            ->parameters($this->getBuilderParameters());
    }

    protected function getColumns()
    {
        return [
            'id',
            'name',
            'email',
            'created_at',
            'updated_at',
        ];
    }

}
```

My view:
```php
@extends('layout')

@section('content')
    {!! $dataTable->table() !!}
@endsection

@push('scripts')
    {!! $dataTable->scripts() !!}
@endpush
```

The result is that I have table head <thead> but no data. No single row.
From my investigation only html() method is executed from DataTable class.

Can someone helps me to get data?

And another question where is table() method?

### System details

- Operating System - MAMP Pro on Mac
- PHP Version - 7.0.15
- Laravel Version - 5.4
- Laravel-Datatables Version -

**Comment by yajra** [comment]
I think there is typo?

```php
return $dataTable->render('datatables/dt54');
// to
return $dataTable->render('datatables.dt54');
```

Is there any error logs on your developer console?

**Comment by rafailml** [comment]
^ changed to 
```php
return $dataTable->render('datatables.dt54');
```
but result is the same. 

I have no errors in my php log, apache log, debugbar and laravel.log
Is this what you mean by "developer console"?

**Comment by yajra** [comment]
Oh, I mean web developer console. Try inspecting the ajax response using chrome dev tools or firebug.

**Comment by rafailml** [comment]
oh yes, there is JS error:

TypeError: $("#dataTableBuilder").DataTable is not a function. (In '$("#dataTableBuilder").DataTable', '$("#dataTableBuilder").DataTable' is undefined)
(anonymous function) — dt45:64:188

**Comment by yajra** [comment]
Just make sure you have every js dependencies added on your view to fix this issue.

1. jQuery.js
2. datatables.js -> from datatables.net
3. datatables.buttons.js -> from datatables.net
4. buttons.server-side.js -> included in the package

**Comment by rafailml** [comment]
Thanks yajra!
Now it shows data but no buttons (create, print, etc.)
Pagination buttons are there, search and show are there too.

**Comment by rafailml** [comment]
And no errors in console :)

**Comment by yajra** [comment]
You might be missing the `B` buttons on your dom? Try implementing this method on your class.

```php
    protected function getBuilderParameters()
    {
        return [
            'dom'     => 'Bfrtip',
            'order'   => [[0, 'desc']],
            'buttons' => [
                'create',
                'export',
                'print',
                'reset',
                'reload',
            ],
        ];
    }
```

**Comment by rafailml** [comment]
Works!
Thanks yajra!
