### ISSUE TITLE
Ajax not executing function Laravel 5.4

### ISSUE THREAD

**Issue by monkjuice** [yajra/laravel-datatables#1159]
https://stackoverflow.com/questions/44191578/yajra-datatables-ajax-not-executing-function-laravel-5-4

In my controller I tried these 2 methods:
```

 public function getData(Datatables $datatables)
{
    Log::info('inside getData');
    $userList = User::select(['id','name','email','role']);
    return Datatables::of($userList)->make(true);
}

```
and

```
public function index(Request $request, User $user)
{
    if ($request->ajax()) {
        Log::info('inside ajax');
        return Datatables::of(User::all())->make(true);
    }
    return View('userlist');
}
```

Log info does not Log in neither of the methods.

If I manually go to the route 'userlist/data' on my navbar, It prints a correct JSON.

web.php:

```
Route::get('userlist', 'UserListController@index')->name('userlist')->middleware('checkrole');

Route::get('userlist/data',['uses'=>'UserListController@getData', 'as' => 'userlist/data']);

```
and finally my view:

```
@extends('layouts.app')

@section('content')
<div class="container">
    <table class="table table-bordered" id="users-table">
        <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>email</th>
            <th>role</th>
        </tr>
        </thead>
    </table>
</div>
@endsection

@push('script')
<script type="text/javascript">
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax:  '{!! route('userlist/data') !!}',
        columns: [
            {data: 'id'},
            {data: 'name'},
            {data: 'email'},
            {data: 'role'},
        ]
    });
</script>
@endpush

```
Yes, I declared the scripts on my app.blade.php and through NET, I can see they are loading correctly; the view /userlist loads correctly, but with the datatable empty.

I have no errors in laravel.log, or firebug

Thanks in advance.

**Comment by yajra** [comment]
Can you try inspecting the ajax response too? Does dataTable alert some error after the response?

Try adding this snippet to enable DT alert on error.
```js
$.fn.dataTable.ext.errMode = 'alert';
```

**Comment by monkjuice** [comment]
Thanks for the quick response, you're godlike..

If I'm not wrong the error should log in my firebug console; nothing here.
Im going to try with homestead now,  I was using the default php artisan serve; weird thing is that no errors are shown

**Comment by yajra** [comment]
Just to be sure, are you using the latest stable v7.5.2? If yes, you can configure dataTables to `throw` an exception instead of catching it. See https://yajrabox.com/docs/laravel-datatables/7.0/error-handler for all possible config.

The reason no error appears is might be because the exception was being catch by the package.
Also make sure you avoid using `php artisan serve` as it is known buggy with the package. Thanks!
