### ISSUE TITLE
Column  sorting / ordering doesn't work. 

### ISSUE THREAD

**Issue by racl101** [yajra/laravel-datatables#116]
I've scoured the closed issues for this same topic and even though the threads end with 'issue fixed' I still can't seem to get column sorting to work when the data source is a server side script querying the database. In other words, I click on the table column headers (the arrows) and though an Ajax request is sent (as far as I can see on the browser inspector) no sorting appears to be occurring.  I'm using laravel version 5.1.7 and laravel-datatables-oracle version 5.5.10    . Any help would be greatly appreciated. Please and thanks.

Here's my code:

Controller method(s):

```
...

  public function getAjaxLogfilesData() {
    $items =        AmazonS3Object::select(['id', 'key', 'bucket', 'folder'])
                    ->where('object_type', 'logfile')
                    ->orderBy('id', 'asc');
                    
    return Datatables::of($items)->make(true);
  }

...

```
`routes.php` file

```

...

Route::get('/s3-objects/ajax-get-logfiles', 'S3ObjectsController@getAjaxLogfilesData');

...

```

config file `config/datatables.php`: 

```
<?php

return [

    'search' => [
        'case_insensitive' => true,
        'use_wildcards'    => false,
    ]

];

```

and view file:

```

@extends('layouts.dashboard-layout')
@section('footer-inline-javascripts')
  <script type="text/javascript" language="javascript">

$(document).ready(function() {
  
  $('table#logfiles').dataTable({
    "processing": true,
    "serverSide": true,
    ajax: '{{ url("/s3-objects/ajax-get-logfiles") }}',
    columns: [
      { data: 'id', name: 'id', orderable: true  },
      { data: 'key', name: 'key', orderable: true},
      { data: 'bucket', name: 'bucket', orderable: true},
      { data: 'folder', name: 'folder', orderable: true}

    ],
    "pageLength": 50,
    "pagingType": "full_numbers",
  });
  
} );

  </script>
@stop
@section('content')

<h1>Logfiles</h1>

<table id="logfiles" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>ID</th>
      <th>Key</th>
      <th>Bucket</th>
      <th>Folder</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>ID</th>
      <th>Key</th>
      <th>Bucket</th>
      <th>Folder</th>
    </tr>
  </tfoot>
  
</table>


@stop


```

**Comment by yajra** [comment]
@racl101, I think ordering does not work for you because you already specify the order on your query. You need to remove ` ->orderBy('id', 'asc');` and let `datatables` do the work.

```php
 $items  =  AmazonS3Object::select(['id', 'key', 'bucket', 'folder'])
                    ->where('object_type', 'logfile')
                    ->orderBy('id', 'asc');
```

**Comment by yajra** [comment]
Suggestions above should fix the issue. Thanks!

**Comment by racl101** [comment]
Yeah that worked. Thank you.

**Comment by racl101** [comment]
Another question, should database queries have `->get()` added to them like so:

```
 $items  =  AmazonS3Object::select(['id', 'key', 'bucket', 'folder'])
                    ->where('object_type', 'logfile')
                    ->get();
```

or not? Like so:

```
 $items  =  AmazonS3Object::select(['id', 'key', 'bucket', 'folder'])
                    ->where('object_type', 'logfile');
```

Is there a difference to the the Laravel Datatables library how you created `$items`?

**Comment by yajra** [comment]
I suggest you use without `get()`. Using get will return all records and use collection instead of eloquent. When your data becomes big then chances are slower response from your server. Using eloquent, data will be paginated on DB server and not on PHP's memory.

**Comment by racl101** [comment]
Thanks for the response @yajra  . Thanks for this awesome library as well. This is a really cool, quality package.

**Comment by revaldopratama** [comment]
help sir @yajra 



if($request->ajax()) {
            DB::statement(DB::raw('set @rownum=0'));
            $queryAgent = $this->queryAgentPerformance($selectedStartDateString, $selectedEndDateString);
            $agent = $queryAgent->select(DB::raw('@rownum  := @rownum  + 1 AS rownum'), 'name', 'email', 'id')
                ->where('question')
                ->orderBy('id', 'asc')->get();

            return Datatables::of($agent)->make(true);
        }

        $html = $htmlBuilder
           ->addColumn(['data' => 'rownum', 'name' => 'rownum', 'title' => 'No.'])
           ->addColumn(['data' => 'email', 'name' => 'email', 'title' => 'Agent\'s Email'])
           ->addColumn(['data' => 'total_question.0.question', 'name' => 'question', 'title' => 'Assigned Questions'])
           ->addColumn(['data' => 'total_answered.0.answered', 'name' => 'answered', 'title' => 'Answered Questions'])
           ->addColumn(['data' => 'total_unanswered.0.unanswered', 'name' => 'unanswered', 'title' => 'Unanswered Questions'])
           ->addColumn(['data' => 'total_escalated.0.escalated', 'name' => 'escalated', 'title' => 'Escalated Questions'])
           ->addColumn(['data' => 'total_spam.0.spam', 'name' => 'spam', 'title' => 'Spam Marked Questions'])
           ->addColumn(['data' => 'average_response.0.average', 'name' => 'average', 'title' => 'Avg Response Time']);
