### ISSUE TITLE
DataTables warning: table id=tableId - Exception Message:

### ISSUE THREAD

**Issue by oriceon** [yajra/laravel-datatables#1160]
DataTables warning: table id=tableId - Exception Message:

htmlspecialchars() expects parameter 1 to be string, array given

Hello, i get this message alert after updating to the latest version.
Any ideea what could be?

I using it with Eloquent.

`Hall::with(['One', 'Two'])->select(['table.column'])..` and with
`Hall::select(['table.*'])..` will return that alert.

With `Hall::select(['table.column'])..` will work..

**Comment by yajra** [comment]
Yes, I recently released an update https://github.com/yajra/laravel-datatables/pull/1131 that throws the exception on alert instead of error dump on console. 

Can you please paste some snippets to reproduce the issue? Just to be sure what version are you using as displayed on `composer show`? Sorry for the inconvenience.

**Comment by oriceon** [comment]
I`m using v7.5.1 with laravel 5.4.

I don`t have a simple snippet (my code is complex than simple query i`ve pasted) but you could try exactly same query from comment. Should return that alert.

Thank you for your greate work!

**Comment by yajra** [comment]
@oriceon I think this is somehow related to MySQL version. It's working fine on MySQL 5.7++ but was able to reproduce the issue on MySQL v5.5.x.

Will dig further and hopefully create a patch to fix this. Thanks for reporting.

**Comment by oriceon** [comment]
My MySQL version is: mysql  Ver 14.14 Distrib 5.7.18, for Win64 (x86_64)

**Comment by yajra** [comment]
My initial findings is wrong. It seems like `array_dot` helper is not flattening the array and still returns an empty array values. Releasing a patch in a minute.

**Comment by yajra** [comment]
@oriceon can you please verify if issue was fixed on v7.5.2? thanks!

**Comment by oriceon** [comment]
Sure, i tested and you fixed! Thank you again.
