### ISSUE TITLE
Need several help for my problem

### ISSUE THREAD

**Issue by pb141510017** [yajra/laravel-datatables#1165]
Hello, I am a little bit new in Yajra Datatables and Laravel. I have several issues about it. Well, at first im sorry if i am asking for help for more than one problem in a thread. But, I think this is the most efficient way to ask it rather than creating many thread at once. This is the list of my question : 

1. How to add number in the tables? 
2. I have a foreign key (as an ID, lets said it Item_ID), how to display it as Item_name ?
3. What i need to do to get print button, excel, and others button?

### This is my line of code for my datatables (item_ID)

- In Controller

```
public function getDataTable(Request $request)
    {
      $data = harga::orderBy('id')->get();
      $data2 = paket::orderBy('id')->get();
      return \Datatables::of($data)
      ->addColumn('nomor', function($data){
      })
      ->addColumn('action', function ($data){
        return '<a href="hapusharga/'.$data->id.'" class="btn btn-xs btn-warning"><i class="fa fa-trash"></i></a>
        <a href="harga/'.$data->id.'/edit" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i></a>';
      })
      ->editColumn('tanggal_efektif', function($data) {
        return $data->tanggal_efektif ? with(new Carbon($data->tanggal_efektif))->format('d/m/Y') : '';
      })
      ->editColumn('created_at', function ($data) {
        return $data->created_at ? with(new Carbon($data->created_at))->format('d/m/Y h:m:s') : '';
      })
      ->editColumn('updated_at', function ($data) {
        return $data->updated_at ? with(new Carbon($data->updated_at))->format('d/m/Y h:m:s') : '';;
      })
      ->filterColumn('tanggal_efektif', function ($query, $keyword) {
          $query->whereRaw("DATE_FORMAT(created_at,'%d/%m/%Y') like ?", ["%$keyword%"]);
      })
      ->filterColumn('created_at', function ($query, $keyword) {
          $query->whereRaw("DATE_FORMAT(created_at,'%d/%m/%Y') like ?", ["%$keyword%"]);
      })
      ->filterColumn('updated_at', function ($query, $keyword) {
          $query->whereRaw("DATE_FORMAT(updated_at,'%d/%m/%Y') like ?", ["%$keyword%"]);
      })
      ->make(true);
    }
```

- My Datatables's Javascript in view
```
jQuery(document).ready(function() {
    var table = $('#table_id');
    var fixedHeaderOffset = 0;
    var oTable = table.dataTable({
      "processing": true,
      "responsive": true,
      "serverSide": true,
      "ajax": {
          "url": "/projectname/public/admin/getdatatableharga",
          // "url": "/projectname/public/admin/getdatatableuser",
          "type": "POST",
          "headers": {"X-CSRF-TOKEN": "{{ csrf_token() }}"}
      },
      "columns": [
        { data: 'nomor', name: 'nomor', searchable: false, orderable: false, className: 'bg-info text-center', width: '5%'},
        { data: 'paket_id', name: 'paket_id', className: 'text-center', width: '20%'},
        { data: 'harga', name: 'harga', className: 'text-left', width: '20%'},
        { data: 'tanggal_efektif', name: 'tanggal_efektif' ,className: 'text-center', dateFormat: 'dd/mm/yy', width: '15%'},
        { data: 'created_at', searchable: false, name: 'created_at', className: 'text-center', width: '15%'},
        { data: 'updated_at', searchable: false, name: 'updated_at', className: 'text-center', width: '15%'},
        { data: 'action', searchable: false, orderable: false, name: 'action', className: 'text-center', width: '5%'},
      ],
    });
});
```

### System details

- Windows 10
- PHP version: 5.6.28
- Laravel 5.4
- Laravel-Datatables Version : sorry i doesnt remember it, but i download the latest one from composer a week ago.

Thanks

**Comment by yajra** [comment]
> How to add number in the tables?
You mean like an index? Try using [`->addIndexColumn()`](https://yajrabox.com/docs/laravel-datatables/7.0/index-column)

> I have a foreign key (as an ID, lets said it Item_ID), how to display it as Item_name ?
You can use [join statements](https://datatables.yajrabox.com/eloquent/joins) or via [eager loading](https://datatables.yajrabox.com/relation/belongs-to)

> What i need to do to get print button, excel, and others button?
You can checkout this [tutorial](https://datatables.yajrabox.com/service) for some ref. It's for v6.x but the idea still applies on v7.x except for the installation part.

**Comment by pb141510017** [comment]
Sorry Yajra, i just can test this night, i will inform you in here later.
Thanks

**Comment by pb141510017** [comment]
@yajra Hi Yajra, sorrry for late respond.  
I'am already tried ur suggestion, and this is the answer : 

1.  I'am try that addIndexColumn() , and this is my code : 
   In my controller : 
   `public function getDataTable(Request $request)
    {
      $data = harga::orderBy('id')->get();
      return \Datatables::of($data)
      ->addIndexColumn('nomor', function($data){
      })`

And the view just like before, the result is error in `DataTables warning: table id=table_id - Requested unknown parameter 'nomor' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4`
this is how the table looks : http://prntscr.com/feoim3  

2. Sorry can u give me an example or simple way of it based on my controller and view? I kinda dont understand how its work, both join or eager loading.

**Comment by pb141510017** [comment]
Everything Solved. Thanks.  
Take me days to can understand all the suggestion gave to me.
