### ISSUE TITLE
editColumn escaping HTML

### ISSUE THREAD

**Issue by RyanPriceDotCa** [yajra/laravel-datatables#1167]
### Summary of problem or feature request

I'm looking to edit a column to include a link.  It's working, except the HTML is being escaped therefore rendered as text instead of HTML.

Not sure what I am missing to have the HTML not be escaped.  I have passing a template as the second argument and placing the HTML::linkRoute call in the template file, but same result.

### Code snippet of problem

```php
return Datatables::of($people)
    ->editColumn('firstname', '{!! HTML::linkRoute("person.show", $firstname, $userid) !!}')
    ->make(true);
```

And it returns:
```
firstname: "&lt;a href=&quot;http://myurl.localhost/person/516073&quot;&gt;SomeFirstName&lt;/a&gt;"
```

### System details

- Debian 8
- 7+
- 5.4
- 7.2

**Comment by RyanPriceDotCa** [comment]
Answering my own question.  Solution was using the well documented raw columns.

```php
return Datatables::of($people)
    ->editColumn('firstname', '{!! HTML::linkRoute("person.show", $firstname, $userid) !!}')
    ->rawColumns(['firstname'])
    ->make(true);
```

**Comment by robiparvez** [comment]
for versions above 8, u have to go to config/datatables.php file....and add your column name in ....raw => ['name_of your_column']

**Comment by stefanuscc** [comment]
How to resolve this in Datatables 6.0?
Somehow, i need this on Laravel 5.1. 

Thanks
