### ISSUE TITLE
Search causing data to overwrite

### ISSUE THREAD

**Issue by oceanapplications** [yajra/laravel-datatables#1168]
### Summary of problem or feature request
I have one database table "Accounts"  with a column named "type" and a related database table "Statuses" which also has a column named "type" that I eager load:

```php
 return Datatables::of(Account::with('status'))
            ->editColumn('account', function($account){ //type hinting Account doesn't help
                return ucwords($account->first_name." ".$account->last_name).'<br><small><i class="fa '.$account->typeIcon().'"></i>&nbsp;'.$account->type.'</small>';
            })
            ->rawColumns(['account'])
            ->make(true);
```

This works fine with no issues until I search on the column from the related table.   Searching causes the two tables to merge into the Accounts model which overwrites the Account's type column with the Status's type column. 

Thanks

### System details

- Ubuntu 16.04
- PHP 7.0
- Laravel 5.4.23
- Laravel-Datatables 7.5.2

**Comment by yajra** [comment]
I think this is related on the framework behavior. As advised on this [doc](https://datatables.yajrabox.com/eloquent/relationships), I suggest you add a select on the main table.

```php
return Datatables::of(Account::with('status')->select('accounts.*'))...
````

**Comment by oceanapplications** [comment]
Thanks that worked perfectly.
