### ISSUE TITLE
Facade bug in the 4.* version.  Accessor name is wrong.

### ISSUE THREAD

**Issue by Aner-Git** [yajra/laravel-datatables#117]
Hey,

The Facade loading  is not working since: 

Your return 'Datatables'   in the facade (note the First Upper case)
Datatables/Facade/Datatables.php [line 14]

But, you register the ServiceProvider with lowercase 'datatables' 
Datatables/DatatablesServiceProvider.php [line 31]

You owe me 2 hours :)  Ahh. 

After fix, you can also change the Installation to point to the facade class in 4.*
'Datatables' => 'yajra\Datatables\Datatables',           /// CAN be changed to point to facade class

Thanks!

**Comment by yajra** [comment]
@Aner-Git, thanks for taking your time for reporting and fixing this. It would be great if you can submit a PR on L4 branch so you can be added to contributors list ^_^.

**Comment by yajra** [comment]
fixed on v3.6.7.
