### ISSUE TITLE
Displaying search results in Datatables

### ISSUE THREAD

**Issue by nfunwigabga** [yajra/laravel-datatables#1172]
How do I display results from a search page in datatables using this extension? See my SO issue [here:](https://stackoverflow.com/questions/44270208/laravel-datatables-displaying-search-results)

**Comment by yajra** [comment]
Try following this [demo](https://datatables.yajrabox.com/eloquent/custom-filter)

**Comment by nfunwigabga** [comment]
Thanks, this is very helpful. I will close this now.
