### ISSUE TITLE
There are no commands defined in the "datatables" namespace

### ISSUE THREAD

**Issue by prabukarana** [yajra/laravel-datatables#1174]
### Summary of problem or feature request
I try to make button export in yajra. So, i read in tutorial, i must creating datatable.
But when i running "php artisan datatables:make EmployeeDataTable" show that error. 

im already install button-datatable. but still same.
and I try to running "php artisan Datatables:make EmployeeDataTable" same error.

### Code snippet of problem
php artisan datatables:make EmployeeDataTable

php artisan Datatables:make EmployeeDataTable

### System details

- Operating System
- PHP Version 7
- Laravel Version 5.4
- Laravel-Datatables Version 7.5

**Comment by yajra** [comment]
Did you install the buttons plugin? See [docs](https://yajrabox.com/docs/laravel-datatables/7.0/buttons-installation) for ref.

**Comment by prabukarana** [comment]
sorry forget to add button in provider. Now its running well. thanks bro...
