### ISSUE TITLE
Does search work on editColumn

### ISSUE THREAD

**Issue by openqubit** [yajra/laravel-datatables#1178]
I am trying to replicate this functionality https://datatables.yajrabox.com/collection/custom-filter and https://github.com/yajra/laravel-datatables-demo/blob/master/resources/views/datatables/collection/custom-filter.blade.php

but i just cannot be able to get it right.

This is the controller

    public function monitor(Request $request)
        {
          $id = Auth::id();
          $agent = new Agent();
          $now = new DateTime();
          $page = 'Monitor';
          $monitor = new Monitoring;
          $users_full_names = Auth::user()->users_full_names;
          $country = 'default';
          $device = 'n/a';
          $platform = $agent->platform();
          $browser = $agent->browser();
          $date = $now->format('Y-m-d H:i:s');
          $time = time();
          $ip = $request->ip();
    
          $data = compact('users_full_names','id','page','country','time','date','monitor','device', 'platform', 'browser', 'ip');
    
          Event::fire('simpleEvent',[$data]);
    
          $users = Monitoring::select(['id','monitoring_user_names','monitoring_page_visited','monitoring_ip','monitoring_date_of_visit','monitoring_time_of_visit','monitoring_country','updated_at'])->orderBy('updated_at', 'desc')->get();
    
            return Datatables::of($users)
                ->filter(function ($instance) use ($request) {
                    if ($request->has('monitoring_user_names')) {
                        $instance->collection = $instance->collection->filter(function ($row) use ($request) {
                            return Str::contains($row['monitoring_user_names'], $request->get('monitoring_user_names')) ? true : false;
                        });
                    }
    
                    if ($request->has('monitoring_page_visited')) {
                        $instance->collection = $instance->collection->filter(function ($row) use ($request) {
                            return Str::contains($row['monitoring_page_visited'], $request->get('monitoring_page_visited')) ? true : false;
                        });
                    }
                })->make(true);
        }

and this is the view

    @extends('layouts.master')
    @section('title')
        Create Post
    @endsection
    @section('page-script')
    <script type="text/javascript">
    $(document).ready(function() {
        $.noConflict();
        $('#outbox-1').datetimepicker();
        $('#outbox-2').datetimepicker();
    
        var oTable = $('#users-table').DataTable({
            dom: "<'row'<'col-xs-12'<'col-xs-6'l><'col-xs-6'p>>r>"+
            "<'row'<'col-xs-12't>>"+
            "<'row'<'col-xs-12'<'col-xs-6'i><'col-xs-6'p>>>",
            processing: true,
            serverSide: true,
            ajax: {
                url: '{!! route('datatable.monitoring') !!}',
                data: function (d) {
                    d.monitoring_user_names = $('input[name=name]').val();
                    d.monitoring_page_visited = $('input[name=email]').val();
                }
            },
            columns: [
            { data: 'id', name: 'id'},
            { data: 'monitoring_user_names', name: 'monitoring_user_names'},
            { data: 'monitoring_page_visited', name: 'monitoring_page_visited'},
            { data: 'monitoring_ip', name: 'monitoring_ip'},
            { data: 'updated_at', name: 'updated_at'},
            { data: 'monitoring_country', name: 'monitoring_country'}
            ]
        });
    
        $('#search-form').on('submit', function(e) {
            oTable.draw();
            e.preventDefault();
        });
    });
    </script>
    @endsection
    
    @section('content')
    
                <section class="col-md-12" id="content">
                    <section class="vbox">
                        <section class="scrollable padder">
                            <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
                                <li><a href="{{ URL::asset('textify/home'); ?>"><i class="fa fa-home"></i> Home</a></li>
                                <li class="active">User Tracking</li>
                            </ul>
                            <div class="m-b-md">
                                <h3 class="m-b-none">User Tracking</h3> <small>Monitor All User Activities</small> </div>
                            <div class="row">
                                <div class="col-md-9">
                                    <section class="panel panel-primary">
                                        <header class="panel-heading font-bold">User Monitoring</header>
                                        <div class="panel-body">
                                        <form method="POST" id="search-form" class="form-inline" role="form">
    
                <div class="form-group">
                    <label for="name">Names</label>
                    <input type="text" class="form-control" name="monitoring_user_names" id="name" placeholder="Names">
                </div>
                <div class="form-group">
                    <label for="email">Page Visited</label>
                    <input type="text" class="form-control" name="monitoring_page_visited" id="email" placeholder="Page Visited">
                </div>
    
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            <hr/>
                                        <table class="table table-striped">
                                            <thead>
                                              <tr>
                                                <th>Option</th>
                                                <th>Start Date</th>
                                                <th>End Date</th>
                                                <th>Action</th>
                                              </tr>
                                            </thead>
                                            <tbody>
                                            <tr><td><select name="track_users" class="form-control"><option>Track Users</option></select></td>
    
                                                <td><div class="form-group">
                    <div class='input-group date' id='outbox-1'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                </div></td>
                                                <td><div class="form-group">
                    <div class='input-group date' id='outbox-2'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div></td>
    
                                                <td><button type="button" class="btn btn-primary">Sony</button></td>
                                              </tr>
                                            </tbody>
                                          </table>
                                            
    
    
    
        <table class="table table-bordered" id="users-table">
            <thead>
                <tr>
                  <th>Id</th>
                    <th>Names</th>
                     <th>Action</th>
                      <th>Ip Address</th>
                       <th>Last Seen</th>
                        <th>Country</th>
    
    
                </tr>
            </thead>
        </table>
    
                                </div>
                                    </section>
                                </div>
                                <div class="col-md-3">
                                    <section class="panel panel-primary">
                                        <header class="panel-heading font-bold">Statistics</header>
                                        <div class="panel-body">
                                        <p>Statistics...</p>
                                        </div>
                                    </section>
                                </div>
    
                            </div>
                        </section>
    
                    </section>
    
                    <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen, open" data-target="#nav,html"></a>
                </section>
                @endsection

I have checked the form fields names and looked at the controler, the ajax fetching the data and i cannot spot where the search is not connecting.

I have no js error on the developer toolbar but the code above cannot return search results. What could be the problem with my code?.

**Comment by jelena-mio** [comment]
@openqubit Did you ever figure this out?
