### ISSUE TITLE
Datatable 7.5 not have datatables:make?

### ISSUE THREAD

**Issue by ssheduardo** [yajra/laravel-datatables#1180]
### The version 7.0 not have command datatables:make

Hi, 
I install the version 7.5 of datatables with laravel 5.4, and my surprise is that not have command for create datatables as services.
Now how create datatable as services?

### System details

- Ubuntu
- PHP Version 7
- Laravel Version 5.4
- Laravel-Datatables 7.5

**Comment by yajra** [comment]
@ssheduardo service buttons are now [extracted to own plugin](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade) to make it optional. See [installation](https://yajrabox.com/docs/laravel-datatables/7.0/buttons-installation) guide for ref.

**Comment by ssheduardo** [comment]
Thanks you.
