### ISSUE TITLE
DataTables warning: table id=datatable1 - Ajax error In Laravel

### ISSUE THREAD

**Issue by webindians001** [yajra/laravel-datatables#1181]
Hi, I have error on my  laravel app while loading  Yajra Datatable plugin can anyone help me please ?

DataTables warning: table id=datatable1 - Ajax error In Laravel

### System details

- Operating System = Ubantu 14.04
- PHP Version = 7.1.2
- Laravel Version = 5.4
- Laravel-Datatables Version = 7.2

**Comment by yajra** [comment]
Try inspecting the ajax response to get a hint of what's causing the error. Use browsers developer tools and inspect the network tab.
