### ISSUE TITLE
FatalThrowableError JsonResponse::make

### ISSUE THREAD

**Issue by ssheduardo** [yajra/laravel-datatables#1182]
### FatalThrowableError JsonResponse::make
When used the command php artisan datatables:make, create all skeleton but one method called dataTable, if execute in the navigator, show error JsonResponse::make

Added image

![datatables-services-1](https://cloud.githubusercontent.com/assets/1160138/26676510/5a7de22a-46c8-11e7-8399-787a53f53bd1.png)

![datatables-services-2](https://cloud.githubusercontent.com/assets/1160138/26676521/61088c80-46c8-11e7-962e-1f2660127e5f.png)

But if change the name dataTable by ajax, all  is done.

![datatables-services-3](https://cloud.githubusercontent.com/assets/1160138/26676559/78880dc2-46c8-11e7-8089-666bb015525f.png)

![datatables-services-4](https://cloud.githubusercontent.com/assets/1160138/26676562/7b63d2b0-46c8-11e7-9bf1-4a68a46a3e3d.png)

- Operating System
- PHP 7.1
- Laravel 5.4
- Laravel-Datatables 7.5

**Comment by yajra** [comment]
You should remove `->make()` on `dataTable()` method. See [docs](https://yajrabox.com/docs/laravel-datatables/7.0/buttons-extended) for ref.

FYI: `ajax()` is the older way to create a service class but would still work.

**Comment by ssheduardo** [comment]
OK
