### ISSUE TITLE
Filter Error when serach by 00

### ISSUE THREAD

**Issue by praveenpatel95** [yajra/laravel-datatables#1184]
Hello Yajra,
In my table store Patient ID as 00001, 00002
when i type 00 its showing error
![image](https://cloud.githubusercontent.com/assets/25205217/26689823/a8c8bef4-4714-11e7-830e-3e756beaa809.png)

**Comment by oceanapplications** [comment]
Ajax error means the server error returned an error.  Use your browser's dev tool/inspect element->network tab to see what the server error is.

**Comment by praveenpatel95** [comment]
Its working dfine, but only when i type 00 or 0 it showing this error

**Comment by mansouralex** [comment]
@praveenpatel95 If you are using FilterColumn method then the `$keyword = $request->get('search')['value'])` will always return false when you enter 0 or 00. To solve the issue change the condition:

`if (($keyword = $request->get('search')['value']) || $request->get('search')['value'] == 0){}`

**Comment by praveenpatel95** [comment]
Thank you so much mansouralex , its working fine
