### ISSUE TITLE
Use datatables service show blank

### ISSUE THREAD

**Issue by prabukarana** [yajra/laravel-datatables#1185]
### Summary of problem or feature request
I am following along with this documentation: https://datatables.yajrabox.com/service
the problem is when i use datatable services show blank, and i've got error. 304 not modified in firebug.

### Code snippet of problem
in Datatables class

    public function ajax()

    {
    return $this->datatables
    ->eloquent($this->query())
    ->make(true)
    }

    public function query()
    {
    $query = employee::select();
     return $this->applyScopes($query);
    }

    public function html()
    {
            return $this->builder()
                    ->columns($this->getColumns())
					->ajax('{{ url("Employee/index3") }}')
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['export', 'print', 'reset', 'reload'],
                        'initComplete' => "function () {
                            this.api().columns().every(function () {
                                var column = this;
                                var input = document.createElement(\"input\");
                                $(input).appendTo($(column.footer()).empty())
                                .on('change', function () {
                                    column.search($(this).val(), false, false, true).draw();
                                });
                            });
                        }",
                    ]);
    }

    protected function getColumns()
    {
        return [
            'ID',
			'cNip',
			'vName',
			'vBankbranch',
            
           
        ];
     }

    protected function filename()
    {
        return 'employeedatatables_' . time();
    }

in Controller

    public function index3(EmployeeDataTable $dataTable)
    {
        return $dataTable->render('employee.users');
     }

in view

    @extends('layouts.app')
    @section('content')	
    <div class="col-md-8 col-md-offset-2">
    <h3>test</h3>	
	
    {!! $dataTable->table() !!}
    </div>
    @endsection

    {!! $dataTable->scripts() !!}

### System details

- Operating System
- PHP Version 7
- Laravel Version 5.4
- Laravel-Datatables Version 7.5

**Comment by yajra** [comment]
Seems like you have an issue on your view? Does the script appended on the response?

```php
{!! $dataTable->scripts() !!}
```
