### ISSUE TITLE
issue for rawColumns

### ISSUE THREAD

**Issue by maple9991** [yajra/laravel-datatables#1188]
### Summary of problem or feature request
Hello,
I'm going to add my custom button on the datatable and this is my code.

![image](https://cloud.githubusercontent.com/assets/25544960/26767118/55965486-49cf-11e7-86df-4831059cb812.png)

As  you can see, I've added column with rawColumns.

But it doesn't work on my view, route doesn't work in my blade.

![image](https://cloud.githubusercontent.com/assets/25544960/26767158/c9e41a08-49cf-11e7-96eb-67454786d3de.png)

What can I do instead of it?
How can I add custom button on my view?

**Comment by yajra** [comment]
You have syntax error. Use something like below:

```php
->addColumn('connection', function($info) {
    return "<a href=". {{route('connect', $info)}} . "></a>";
})

**Comment by yajra** [comment]
You may also `rawColumns` to display it as html. See https://yajrabox.com/docs/laravel-datatables/7.0/xss#raw for details.
