### ISSUE TITLE
using groupby then Rownnum is not working correct

### ISSUE THREAD

**Issue by praveenpatel95** [yajra/laravel-datatables#1193]
When i am using groupby then Rownnum is not working correct

``` php
DB::statement(DB::raw('set @rownum=0'));
$data = DB::table('patients')
    ->leftjoin('patient_logs', 'patients.id', '=', 'patient_logs.patient_id')
    ->select([
        DB::raw('@rownum := @rownum + 1 AS rownum'),
        DB::raw("CONCAT(patients.name,' ',patients.sir_name) as fname"),
        'patient_logs.created_at',
        'patients.patient_no',
        'patients.mobile_no'
    ])->groupBy('patient_logs.patient_id');
```

result
6
10

**Comment by ChaosPower** [comment]
what do you mean by result the result? can you please give us your expected json output and the json output you are currently getting.

**Comment by praveenpatel95** [comment]
Hello ChaosPower ,
Result means output of rownum is not like 1, 2, 3, 4.....
its giving 6, 10.....

**Comment by yajra** [comment]
@praveenpatel95 can you try running the sql manually? I guess there is something wrong with SQL generated itself which explains why the output is like that. Thanks!
