### ISSUE TITLE
addColumn problem

### ISSUE THREAD

**Issue by dezashibi** [yajra/laravel-datatables#1197]
### Summary of problem or feature request

There are 2 issues :
1. I want to have 2 column but it doesn't work it only shows the action column
2. even if I delete all codes for addColumn syntaxes it still shows empty action column

### Code snippet of problem

```php
   public function dataTable()
    {
        return $this->datatables
                    ->eloquent($this->query())
                    ->addColumn('revisions', function($row){
                        return $row->revisionHistory->count();
                    })
                    ->addColumn('action', function($row) {
                        $var = route('clientbase');
                        return view('basedata::general.buttons', compact('row', 'var'))->render();
                    });
    }
```

### System details

- Centos
- PHP 7.1
- Laravel 5.4
- Laravel-Datatables 7.5

**Comment by ChaosPower** [comment]
Can you provide the json response? thanks!

**Comment by lk77** [comment]
I think you need to add you column to the html too.

`->addColumn([
                        'defaultContent' => '',
                        'data'             => 'revisions',
                        'name'           => 'revisions',
                        'title'              => 'Revisions'
                    ])`
