### ISSUE TITLE
$this->getDataForExport() 500 error

### ISSUE THREAD

**Issue by quantumwebco** [yajra/laravel-datatables#1198]
Hi there

I've just taken over a Laravel project using your package and one issue I can't resolve is when attempting a file export we get a 500 server error. I have traced it to the function call getDataForExport() but I am unable to seems to debug any further. I would really appreciate a point in the right direction. 

```    /**
     * Build excel file and prepare for export.
     *
     * @return \Maatwebsite\Excel\Writers\LaravelExcelWriter
     */
    protected function buildExcelFile()
    {
        /** @var \Maatwebsite\Excel\Excel $excel */
        $excel = app('excel');

        return $excel->create("filename", function ($excel) {
            $excel->sheet('exported-data', function ($sheet) {
                $data = $this->getDataForExport(); // THIS CAUSES 500 ERROR
                foreach($data as $key => $val){
                    $tmp = str_replace('£', '', $val);
                    $tmp = str_replace('N/A', '', $tmp);
                    $data[$key] = $tmp;
                }
                $data[count($data) + 2] = array(
                    'Issued' => '',
                    'Name' => '',
                    'Description/ Partnumber' => '',
                    'Quantity' => '',
                    'PO' => '',
                    'Cost Unit Price' => '=SUM(E1:E'.count($data).')',
                    'Cost Total Price' => '=SUM(F1:F'.count($data).')',
                );
                $sheet->rows($data);
            });
        });
    }
```

**Comment by ChaosPower** [comment]
what's the exact error? Error 500 is internal server error. Currently it's too general. Probably you have missing package or binary if it's the excel plugin.

**Comment by quantumwebco** [comment]
All packages etc are fine. It works from other pages from what I can tell. It's just the getDataForExport() function that causes a problem.

**Comment by ChaosPower** [comment]
@quantumwebco can you figure out what class is ```$this``` probably method does not exists error from line `$data = $this->getDataForExport(); // THIS CAUSES 500 ERROR`
