### ISSUE TITLE
Handle 3100 records problem

### ISSUE THREAD

**Issue by migas5000** [yajra/laravel-datatables#1203]
Hi. I have a table with about 3100 records and I'm having lots of trouble with it.
I must handle the data before pass it to the datatables because there are too many nested relations.   
When I test the controller it doesn't break the results into pages. It returns all the 3100 records and hangs.  
Here is my controller: 

` 
public function getGoals() {

        $goals = Goal::query()->with('shop', 'shop.chain', 'family')->get();

        $goals = Goal::getGoalsWithRate($goals);

        
        
        function generateTable($goals){
            
            $allgoals =[];
            foreach ($goals as $goal){
            
            
            if(Carbon::now()->between(Carbon::parse($goal->start_date) , Carbon::parse($goal->end_date)))
            {
                 $status = 'Em curso';
             } 
             elseif(Carbon::now()->lt(Carbon::parse($goal->start_date)))
             {
                 
                 $status = 'Próximo';
             } else
             {
                 $status ='Terminado';
             }
            
            
            $goal = array(
            'id' => $goal->id,
            'chain'=>$goal->shop->chain->name,
            'shop'=>$goal->shop->name,
            'family'=>$goal->family->name,
            'start_date'=>$goal->start_date,
            'end_date'=>$goal->end_date,
            'rate'=>$goal->achievement_rate,
            'week'=> Carbon::parse($goal->end_date)->weekOfYear,
            'status'=>$status
                
                
                
                    );
                    array_push($allgoals, $goal);
                                           
        }
        return $allgoals;
        }
        

        
    return Datatables::collection(generateTable($goals))->make(TRUE);
       

    }`

here is the script 

`  <script>
    
    $(document).ready(function() {
        
    $('#GoalsGlobalTable').DataTable( {
        
        "processing": true,
        "serverSide": true,
        
        "paging":true,
        "pageLength": 10,
        
        ajax: {
            url: '{{url('admin/api/goals')}}',
            type:'GET'
            
        },
        "columns" :[
            { data: 'id'},
            { data: 'chain' },
            { data: 'shop' },
            { data: 'family' },
            { data: 'start_date' },
            { data: 'end_date' },
            { data: 'rate'},
            { data: 'week'},
            { data: 'status'}
            
            
        ]
    } );
} );
    
    </script>`

Should I paginate the results in the query before passing to the datatable? I'm lost here. Please help me to solve this. Thanks 

### System details

- Operating System
- PHP Version 7
- Laravel Version 5.4
- Laravel-Datatables Version

**Comment by yajra** [comment]
You are using collection. Use a builder by removing `get()` and then utilize `addColumn, editColumn` to display the relations.

```php
$goals = Goal::query()->with('shop', 'shop.chain', 'family');

return Datatables::eloqeunt($goals)
    ->addColumn('shop_name', function(Goal $goal) { return $goal->shop->name })
    ....
    ->make(TRUE);
```
