### ISSUE TITLE
Searching doesn't work with multiple select (union)

### ISSUE THREAD

**Issue by ruggierileo** [yajra/laravel-datatables#1204]
Hi, when I search in my datatable only add the "like" to the last query
Why does not it  add the command "like" into the second select too?

Version
-----------------
laravel/framework": "5.4.24"
yajra/laravel-datatables-oracle": "7.0"

My Javascript code:
----------------------

tableBs.grid = tableBs.DataTable({
		responsive: true,
		processing: true,
		serverSide: true,
		ordering: false,
		ajax: {
			url: gridRoute,
			type: "POST",
			data: function (data) {
				data._token = tableBs.token;
			}
		},
		columns: [
                {data: 'name', name: 'tableB.name'},
                {data: 'username', name: 'tableA.username'},               
                {data: 'action', name: 'action', orderable: false, "searchable": false}
            ],
			

this is my Laravel code:
----------------------------

			
public function grid()
    {
        $userId = Auth::user()->id;			
			
		$query1 = DB::table('tableD AS tableA')
            ->join('tableC AS tableB', 'tableB.id', '=', 'tableA.tableB_id')
            ->where('tableA.user_id', '=', $userId)
            ->select(['tableA.tableB_id as id', 'tableB.name as name', 'tableA.username as username', 'tableA.created_at as created_at']);

        $query2 = DB::table('tableA')
            ->join('tableB', 'tableB.id', '=', 'tableA.tableB_id')
            ->where('tableA.user_id', '=', $userId)
            ->select(['tableA.tableB_id as id','tableB.name as name', 'tableA.username as username', 'tableA.created_at as created_at'])
            ->union($query1)
            ->orderBy('name', 'asc');			

        return Datatables::of($query2) ->make(true);
}

The query created when I search:
-----------------------------------

select "tableA"."tableB_id" as "id", "tableB"."name" as "name", "tableA"."username" as "username", "tableA"."created_at" as "created_at" 
from "tableA" 
inner join "tableB" on "tableB"."id" = "tableA"."tableB_id" 
where "tableA"."user_id" = 1 
and (LOWER(CAST("tableB"."name" as TEXT)) LIKE "%goo%" or LOWER(CAST("tableA"."username" as TEXT)) LIKE "%goo%") 

union 

select "tableA"."tableB_id" as "id", "tableB"."name" as "name", "tableA"."username" as "username", "tableA"."created_at" as "created_at" 
from "tableD" as "tableA" 
inner join "tableC" as "tableB" on "tableB"."id" = "tableA"."tableB_id" 
where "tableA"."user_id" = 1 
order by "name" asc

Can please someboy healp me?
Thank very much

**Comment by timothyrowan** [comment]
in the same boat

**Comment by ruggierileo** [comment]
Yes, the query works manually.

**Comment by yajra** [comment]
I think I see the issue here now, you need to create a 3rd sql that uses the union sql as single table. See demo for details: https://datatables.yajrabox.com/fluent/union

**Comment by weidmaster** [comment]
I tried the demo but it loses all relationship made by Eloquent, making the solution not good when we need to edit columns or show the relationships in datatables. Here is my current setup:

```
 $faturasFiscais = Faturamento::whereNotNull('crt_id')
                ->with('cliente')
                ->with('moeda')
                ->with('crt')
                ->select('id','created_at','crt_id','cliente_id','moeda_id','total','total_usd',DB::raw('"fiscal" as tipo'));
                
        $faturasNaoFiscais = FaturamentoLivre::whereNotNull('crt_id')
                ->with('cliente')
                ->with('moeda')
                ->with('crt')
                ->select('id','created_at','crt_id','cliente_id','moeda_id','total','total_usd',DB::raw('"livre" as tipo'));
        
        $faturas = $faturasFiscais->union($faturasNaoFiscais);

 return Datatables::of($query)
                ->editColumn('created_at', function ($fatura) {
                    return $fatura->created_at->format('d/m/Y');
                })
                ->filterColumn('created_at', function ($query, $keyword) {
                    $query->whereRaw("DATE_FORMAT(created_at,'%d/%m/%Y') like ?", ["%$keyword%"]);
                })
                ->editColumn('total', function ($fatura) {
                    return number_format($fatura->total,$fatura->moeda->casas_decimais,',','.');
                })
                ->editColumn('total_usd', function ($fatura) {
                    return number_format($fatura->total_usd,2,',','.');
                })
                ->addColumn('action', function ($fatura) {
                    $actions = '';
                    if($fatura->tipo == 'fiscal') {
                        $actions .= '<a href="/admin/financeiro-matriz/faturamentos/imprimir/'.$fatura->id.'" class="btn btn-xs btn-primary" target="_blank"><i class="fa fa-print"></i> Imprimir</a>';
                    } else {
                            $actions .= '<a href="/admin/financeiro-matriz/faturamentos-livres/imprimir/'.$fatura->id.'" class="btn btn-xs btn-primary" target="_blank"><i class="fa fa-print"></i> Imprimir</a>';
                    }
                     return $actions;
                 })
                ->make(true);
```

With that setup the datatable shows the information but as the topic says, the search only works for the first eloquent query. Here is the search query for comparison:

```
"(select `id`, `created_at`, `crt_id`, `cliente_id`, `moeda_id`, `total`, `total_usd`, "fiscal" as tipo from `faturamentos` where `crt_id` is not null and ((DATE_FORMAT(created_at,'%d/%m/%Y') like ?) or LOWER(`faturamentos`.`id`) LIKE ? or (select count(1) from `crts` where `faturamentos`.`crt_id` = `crts`.`id` and LOWER(`crts`.`number`) LIKE ?) >= 1 or (select count(1) from `partners` where `faturamentos`.`cliente_id` = `partners`.`id` and LOWER(`partners`.`client`) LIKE ?) >= 1)) union (select `id`, `created_at`, `crt_id`, `cliente_id`, `moeda_id`, `total`, `total_usd`, "livre" as tipo from `faturamentos_livres` where `crt_id` is not null) order by `id` desc limit 10 offset 0"

```
Then I tried the demo, but then I lose all Eloquent goodness when using like that:

```
$query = DB::table(DB::raw("({$faturas->toSql()}) as x"))
        ->select('id','created_at','crt_id','cliente_id','moeda_id','total','total_usd','tipo');
```

The very first complain of Laravel after doing that is:

```
Call to a member function format() on string
```
That is refering to the created_at->format part.

The fix should be to make the union query gets the where statements as the first query, but I couldn't make it work at all. Please take a look at this issue.
