### ISSUE TITLE
error: "Unauthenticated."

### ISSUE THREAD

**Issue by monkhsaikhan** [yajra/laravel-datatables#1205]
**I use laravel 5.4. But i have a problem.** 

![error](https://user-images.githubusercontent.com/6801431/27120718-a67a15a2-511f-11e7-9599-83d96e3641c8.PNG)
**My view**

![view](https://user-images.githubusercontent.com/6801431/27120762-cf802c5c-511f-11e7-8136-8f398450c796.PNG)

JS

```
$(function() {
    $('#orders-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '/fcs/api/orders',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'id', name: 'id' },
            { data: 'id', name: 'id' },
            { data: 'id', name: 'id' },
            { data: 'id', name: 'id' },
            { data: 'id', name: 'id' },
            { data: 'id', name: 'id' },
            { data: 'created_at', name: 'created_at' },
            { data: 'updated_at', name: 'updated_at' }
        ]
    });
});
```

Controller function 

```
public function index(Request $request)
    {
        if($request->ajax())
        {
            return Datatables::of(Order::query())->make(true);
        }
    }
```

**Pagination, order, search not working! How to fix this problem**

**Comment by yajra** [comment]
You might be using artisan serve? https://github.com/yajra/laravel-datatables#php-artisan-serve-bug

If yes, then convert to valet or something else. Thanks!

**Comment by yajra** [comment]
You might also experiencing a long url if your table has many columns. In that case, you can follow this [blog](https://yajrabox.com/blog/datatables-and-long-url) to shorten dataTables url. Thanks!
