### ISSUE TITLE
How to exclude a column from export

### ISSUE THREAD

**Issue by kamrava** [yajra/laravel-datatables#1206]
I'm using Laravel 5.4 + Yajra-dataTables 7.7 as Service.

How can I exclude a column from export? (eg. excel)

**Comment by yajra** [comment]
On your columns declaration, try setting `exportable => false`:

```php
protected getColumns() {
  return [
    'id' => [
      'exportable' => false
    ]
  ]
}
```

**Comment by kamrava** [comment]
Solved.
Thanks

**Comment by anandabayu** [comment]
@yajra hai, how to set exportable dynamically from javascript? because I need to visible or hidden some column and export it only for visible column
