### ISSUE TITLE
Quickly typing in search box causing Ajax Error Alert Dialog server 500 error

### ISSUE THREAD

**Issue by awebartisan** [yajra/laravel-datatables#1209]
I Have used Yajra DataTables in my project, everything working good except when I quickly type in search and quickly remove something from Search Box it's giving Ajax Error which is caused by **Server 500 error**.  I am not using a Service, I have just added a `public action in my controller` like below: 

    public function getBasicData()
    {

        
        $project = Project::with('user')
                        ->with('category')
                        ->select(['projects.id' ,  'projects.name' , 'projects.title' , 'projects.sales_offer_url' , 'projects.user_id' , 'projects.category_id' , 'projects.status' , 'projects.completed_at' , 'projects.created_at']);

        return Datatables::eloquent($project)
                          ->addColumn('action' , function($project){

                            return view('actions' , compact('project'))->render();

                          })
                          ->make(true);

    }

My Javascript looks like this:

                         var table = $('#projectsDataTable').DataTable({
                        "processing" : true,
                        "serverSide" : true,
                        ajax : {

                        url : "{{ route('projects.basic') }}",
                        complete : function(data){

                            showDeleteModal();

                        }

                    },
                    "columns" : [

                        { "data" : "name"},
                        { "data" : "title"},
                        { "data" : "sales_offer_url"},
                        { "data" : "user.name" , "name" : "user.name"},
                        { "data" : "category.name" , "name" : "category.name" , "searchable" : false},
                        { "data" : "status" , "searchable" : false},
                        { "data" : "completed_at" , "searchable" : false},
                        { "data" : "created_at" , "searchable" : false},
                        { "data": "action", "name ": "action", "orderable": false, "searchable": false},

                    ],
                    search : {
                        "regex" : true
                    }

Everything is working fine except this search issue... I can see in demo that when I quickly type anything in Search Box its not causing any issue , no server side 500 error. 
Is it with my local server that it can't handle so many requests in such short time? or my code needs optimization?
### System details

- I am on Windows 10 x64
- PHP 5.6.30
- Laravel 5.4
-XAMPP
-"yajra/laravel-datatables-oracle": "7.5"

**Comment by yajra** [comment]
Try inspecting the ajax request and see the error dump. There must be some error when generating the sql.

**Comment by awebartisan** [comment]
Yes, Errors are unexpected...
1st Error is about is : Access denied for user forge to connect with localhost, ( NOTE: I Have properly configured database and application is working.
2nd Error is about Application Key  : The only supported ciphers are AES-128-CBC and AES-256-CBC
I can see these errors in logs when this alert appears!

I am guessing that my server (XAMPP) Is not able to request so much requests, what do you think of these errors? they are not making any sense to me so far.

**Comment by jryd** [comment]
I am getting this error too.

I'm using a global search box in the front end to search 3 datatables.

It would appear when I type quickly, this error is caused. The error in my laravel.log looks like this:

> [2017-11-06 00:10:57] production.ERROR: No application encryption key has been specified.

Just to be clear, the encryption key is definitely set!

Interestingly, I am using XAMPP too...

**Comment by FilipQL** [comment]
If the encryption key is definitely set - then try running `php artisan config:cache` to cache configuration. I had the same problem (I'm using XAMPP) and after caching configuration there are no those weird errors (for now).

https://stackoverflow.com/a/47365230/4437206
