### ISSUE TITLE
UTF-8 problem with printing table to PDF

### ISSUE THREAD

**Issue by AdrianKuriata** [yajra/laravel-datatables#1211]
### Summary of problem or feature request

Hi, i have a problem with printing data table to `PDF`. With `Excel` and `CSV` everything working perfectly. When i try save data to PDF, i don't see special chars, mean polish chars like "`ł, ś, ź, ż, ó, ą, ę`" etc. I tried set `UTF-8` in vendor `print.blade.php` file and changed font for it, but this not helped.

Here is a picture, should be: "`zł`", but is "`zB`", this is bad...
[Example Picture](http://i.imgur.com/jAEOfq2.png)
### Code snippet of problem

```
<html lang="pl">
    <head>
        <title>Print Table</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name=description content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <style>
            body {
                margin: 20px;
                font-family: Arial, sans-serif;
            }
        </style>
    </head>
```
### System details

- Operating System - Fedora 24
- PHP Version - PHP 7.0.8-2 (working with Homestead)
- Laravel Version - 5.4.27
- Laravel-Datatables Version - 7.7.0 (Installation is clear, i never had Laravel DataTables.)

**Comment by yajra** [comment]
Are you using [snappy](https://github.com/barryvdh/laravel-snappy) or [dompdf](https://github.com/Maatwebsite/Laravel-Excel) to generate the pdf? Maybe we can ask help on those main repo.

**Comment by AdrianKuriata** [comment]
Im using probably dompdf, im not changed anything, i just saw it was maatweeb excel is used for generate everything.

**Comment by yajra** [comment]
On `config/datatables.php` there is a key `'pdf_generator'`. If you are using `excel` then adjusting `print.blade.php` won't change anything because it will use Laravel-Excel.

`print.blade.php` is only used with `snappy`. I also suggest that you use `snappy` instead on `excel` because I find `dompdf` to be buggy and slow.

**Comment by AdrianKuriata** [comment]
@yajra I will try do what you said, i give you response how it works.

**Comment by AdrianKuriata** [comment]
@yajra Hi, i tried to test you suggestion, but i don't know why i don't see now PDF and Excel buttons. Im really confused, i mean i don't see it on the excel and snappy module.

This is my parameters, do you have any suggestion why i don't see pdf and excel buttons?

```
->parameters([
                'language' => [
                	'url' => asset('js/Polish.json'),
	                'buttons' => [
	                	'copy' => 'Do schowka',
	                	'copyTitle' => 'Skopiowano do schowka',
	                	'copySuccess' => [
		                	'1' => "Skopiowano jeden wiersz do schowka",
		                	'_' => "Skopiowano %d wierszy do schowka"
	                	],
	                ],
                ],
                'searching' => false,
                'dom' => '<"pull-right"B>lfrtip',
                'buttons' => [
	                [
	                	'copyHtml5'
                	],
	                [
	                	'extend' => 'pdf',
	                	'text' => 'Do PDF',
	                ],
	                [
	                	'extend' => 'excel',
	                	'text' => 'Do EXCEL',
	                ],
	                [
	                	'extend' => 'csv',
	                	'text' => 'Do CSV',
	                ]
                ],
                'lengthMenu' => [
                	[
                		10,
                		25,
                		50,
                		100,
                		150,
                		1000
                	],
                	[
                		10,
                		25,
                		50,
                		100,
                		150,
                		1000
                	],
                ],
                'order' => [
                	[
                		2,
                		'desc'
                	]
                ]
            ]);
```

**Comment by AdrianKuriata** [comment]
Thank you for your time.
