### ISSUE TITLE
Override search function

### ISSUE THREAD

**Issue by Waguilar33** [yajra/laravel-datatables#1212]
First of all, thank you for all your work. What an amazing package.

I have done DataTables as a Service Implementation. Consulting information across data bases works amazing, no problem there.

However, the problem I have is with searching. I read here [#956](https://github.com/yajra/laravel-datatables/issues/956) that search across multiple database is not supported. But, is there a way to override the search functionality? I want to do something like  [DataTable Search](https://datatables.net/examples/api/regex.html)

Any guidance will be greatly appreciated.

- Laragon 3.0 on Windows 10
- PHP Version: 7.1.5
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.7.0

**Comment by yajra** [comment]
Yes, you can write you custom query using `filter` api. See https://datatables.yajrabox.com/eloquent/custom-filter for some ref. You can also use `filterColumn` to write a custom query for a specific field. Thanks!
