### ISSUE TITLE
Starting Datatable with Blank data

### ISSUE THREAD

**Issue by grafikkaos** [yajra/laravel-datatables#1213]
### Summary of problem or feature request

Hi guys,  I have a quick question that I hope someone can help me with.  I am build a search feature and fetching the data from a table that about 1 million plus records.  Is there a way I can prevent the datatable from initiating on load?

### System details
- Windows 10
- PHP Version: 7.1.4
- Laravel Version: 5.3
- Laravel-Datatables Version: 6.9.4

**Comment by pb141510017** [comment]
Do u use "server side" in your data tables?

**Comment by yajra** [comment]
Yes, you can do this on the js level. Just initialize you dataTable script when the submit button was clicked. See datatables.net docs for more js related stuffs. Thanks!
