### ISSUE TITLE
Unable to filter column  of 3 words by entering the first and last words

### ISSUE THREAD

**Issue by mansouralex** [yajra/laravel-datatables#1215]
Hi @yajra Is it possible to filter "Dr. Garett Reichel" by typing "Dr. Reichel" ? Example in reference: https://datatables.yajrabox.com/eloquent/multi-filter-select

**Comment by yajra** [comment]
Yes, it's possible now but only for Laravel 5.4 version. LDT v7.x.

See http://dt54.yajrabox.com/eloquent/object for demo. Thanks!

**Comment by mansouralex** [comment]
@yajra Ah Cool. Can you direct me to it's implementation ? I may need to add it to Laravel 5.2 project. Thanks.

**Comment by yajra** [comment]
This is the PR https://github.com/yajra/laravel-datatables/pull/1113 where it is added. 👍

**Comment by mansouralex** [comment]
@yajra Upgraded now. But not able to get it working. Is there special configuration or filterColumn setup?

`$dataTable->filterColumn('customers.customer_name', 'whereRaw', "CONCAT(customers.first_name,' ',customers.last_name) like ? ", ["%$keyword%"]);`

**Comment by yajra** [comment]
@mansouralex upgraded to what version? Please note that on v8, I removed the support for filterColumn magic method or whatever it is called and sticked to using closure. New syntax should be:

```php
$dataTable->filterColumn('customers.customer_name', function($query, $keyword) {
    $query->whereRaw("CONCAT(customers.first_name,' ',customers.last_name) like ? ", ["%$keyword%"]);
});
```

**Comment by mansouralex** [comment]
@yajra Yes, I'm aware of that. Our upgrade was to v7 so far and as you noted above this feature is supported.
