### ISSUE TITLE
How to display related items in datatable?

### ISSUE THREAD

**Issue by Chinese1904** [yajra/laravel-datatables#1217]
### Summary of problem or feature request

Hi yajra, 

first off, thanks for this amazing package!

I just reached a roadblock and I was wondering if someone here could help. I currently display all restaurants in a datatable, but restaurants can also have branches/franchises, so I am trying to display these as well in the same table.

At the moment I display them as follows:

```php
if ($request->ajax()) {
    $restaurant = Restaurant::query()->with('user');

    return Datatables::of($restaurant)
        ->editColumn('name', function ($restaurant) {
            return $restaurant->name;
        })
        ->editColumn('user.name', function ($restaurant) { // Owner
            return $restaurant->user->name;
        })
        ->editColumn('total_orders', function ($restaurant) {
            return $restaurant->total_orders;
        })
        ->make(true);
}
```
My relationship is that Restaurant `hasMany(Branch::class);` and Branch `belongsTo(Restaurant::class);`

Also note that I want to display the owner name which is this relationship for User `hasMany(Branch::class);` and `hasOne(Restaurant::class);`

I fail to think of a solution, but probably my skillset is not good enough :(

Any help and hints would be great!

**Comment by yajra** [comment]
Maybe try following this [has many demo](http://dt54.yajrabox.com/eloquent/has-many). You can also eager load hasMany relations but since it returns a collection, you then need to loop on it to display it properly to the user.
