### ISSUE TITLE
I wonder ? Big Data one call ?

### ISSUE THREAD

**Issue by ROKAISAKKON** [yajra/laravel-datatables#122]
example

Datatables::of( User::all())->make(true);

and user have 10,000,000 record.

It is very slow ?

**Comment by yajra** [comment]
Yes, because that is a ton of records. As some people says, **"ALL is bad"**. You should avoid using `all()` as much as possible and use pagination instead. Better use something like below and paginate the records.

```php
Datatables::of( User::select('*'))->make(true);
```

**Comment by ROKAISAKKON** [comment]
Thank you very much.
