### ISSUE TITLE
Service Implementation error - instance of Bllim\Datatables\Datatables given

### ISSUE THREAD

**Issue by dimidev** [yajra/laravel-datatables#1220]
### Summary of problem or feature request

I followed the DataTables as a Service Implementation tutorial, but i have this error on my Controller
`Argument 1 passed to Yajra\Datatables\Services\DataTable::__construct() must be an instance of Yajra\Datatables\Datatables, instance of Bllim\Datatables\Datatables given`

I dont know why i have this problem, i followed all instruction that is available.

Help Please!!

### Code snippet of problem
My Controller
```php
namespace App\Http\Controllers;

use App\DataTables\UsersDatatable;
use Illuminate\Http\Request;

class UsersController extends Controller{
    public function index(UsersDatatable $dataTable){
        return $dataTable->render('users.index');
    }
}
```

And this is my Datatable Service file

```php
namespace App\DataTables;

use App\User;
use Yajra\Datatables\Services\DataTable;

class UsersDatatable extends DataTable
{

    public function dataTable()
    {
        return $this->datatables
            ->eloquent($this->query())->make(true);
    }

    public function query()
    {
        $users = User::select(); 
      
        return $this->applyScopes($users);
    }
    
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->parameters();
    }
    
    protected function getColumns()
    {
        return [
            'id',
            'name',
            'lastname'
            ];
    }
    
    protected function filename()
    {
        return 'usersdatatables_' . time();
    }
}
```

### System details

- Operating System - Windows 10.2
- PHP Version - 5.6
- Laravel Version - 5.4
- Laravel-Datatables Version 7.0

**Comment by yajra** [comment]
Maybe try to uninstall `Bllim\Datatables\Datatables` package first. It's conflicting with this package. Thanks!

**Comment by dimidev** [comment]
thx ... it works fine now.. 
old datatable package was used by another package 'Tracker'
