### ISSUE TITLE
excelHtml5 with laravel-datatables

### ISSUE THREAD

**Issue by oriceon** [yajra/laravel-datatables#1222]
Hello, i`m using latest laravel-datatables and want to add excelHtml5 function but with no succes.
When open saved xlsx i get: "... file format or file extension is not valid ..."

(i`m not using laravel-datatables-buttons, just a original excelHtml5 script)

Any ideea why it happened?

I tested on a dummy datatables.html and with generated HTML it`s worked ok.

Thanks.

**Comment by yajra** [comment]
I think the right place to ask that question is on https://github.com/DataTables/Buttons since it out of the package scope. Thanks!
