### ISSUE TITLE
Leading 0 in serach box throws error Happens in demo site Example too

### ISSUE THREAD

**Issue by ruchisheth** [yajra/laravel-datatables#1223]
### Summary of problem or feature request
I have joined multiple tables in my controller method. It returns data as desired but when I type into search box '0' it throws an error. 

It only happen when single zero(0) is there in search box. '00' or 't0102' works fine.

only single '0' as search value throws an error.

Happens on the demo site to
https://datatables.yajrabox.com/eloquent/row-num
try to search for 0(zero) only and it will throw back you an error.

After spending couple of hours I came to the conclusion the it is because in MySql query LIKE %0% is not adding inverted commas('') around 0(zero)
It should be **LIKE '%0%'** instead **LIKE %0%**.

### Code snippet of problem

Syntax error or access violation: 1583 Incorrect parameters in the call to native function 'LOWER' (SQL: select count(*) as aggregate from (select `a`.`id` as `assignment_id`, `a`.`fieldrep_id`, `a`.`deadline_date`, `a`.`is_reported`, `a`.`is_partial`, `a`.`is_approved`, `c`.`client_logo`, `p`.`id` as `project_id`, `p`.`project_name`, `r`.`id` as `round_id`, `r`.`round_name`, `s`.`site_code`, `s`.`site_name`, `s`.`city`, `s`.`state`, `s`.`zipcode`, `su`.`id` as `survey_id`, `su`.`status`, `su`.`service_code`, `t`.`template_name`, CONCAT(IFNULL( DATE_FORMAT(a.schedule_date,'%e/%c/%Y'), DATE_FORMAT(r.schedule_date,'%e/%c/%Y')), ' ' , IFNULL(a.start_time, r.start_time)) as assignment_scheduled, CONCAT(IFNULL( DATE_FORMAT(a.schedule_date,'%d %b %Y'), DATE_FORMAT(r.schedule_date,'%d %b %Y')), ' ' , IFNULL(a.start_time, r.start_time)) as assignment_scheduled_date, CONCAT(DATE_FORMAT(a.start_date,'%d %b %Y'),' ',a.start_time) as assignment_starts, CONCAT(f.first_name," ",f.last_name) as schedule_to from `surveys` as `su` left join `assignments` as `a` on `su`.`assignment_id` = `a`.`id` left join `rounds` as `r` on `a`.`round_id` = `r`.`id` left join `projects` as `p` on `r`.`project_id` = `p`.`id` left join `sites` as `s` on `a`.`site_id` = `s`.`id` left join `fieldreps` as `f` on `a`.`fieldrep_id` = `f`.`id` left join `chains` as `ch` on `p`.`chain_id` = `ch`.`id` left join `clients` as `c` on `ch`.`client_id` = `c`.`id` left join `surveys_templates` as `t` on `su`.`template_id` = `t`.`id` where (`a`.`is_reported` = 1 or `a`.`is_partial` = 1 or `a`.`is_approved` = 1) and (LOWER(`s`.`site_code`) LIKE %0% or LOWER(`su`.`service_code`) LIKE %0% or LOWER(`p`.`project_name`) LIKE %0% or LOWER(`r`.`round_name`) LIKE %0% or LOWER(`s`.`city`) LIKE %0% or LOWER(`surveys` as `su.assignment_scheduled`) LIKE %0% or LOWER(`t`.`template_name`) LIKE %0% or LOWER(`surveys` as `su.schedule_to`) LIKE %0%) order by lpad(s.site_code, 10, 0) desc) count_row_table)'

**Comment by yajra** [comment]
@ruchisheth thanks for reporting. Will try to fix this as soon as I can.

**Comment by ruchisheth** [comment]
Did you find the solution for this?

**Comment by yajra** [comment]
Sorry, but haven't had the chance to look at this yet. If you can, please do not hesitate to submit a PR. Thanks!

**Comment by ruchisheth** [comment]
![laravel datatables mysql rownum demo](https://user-images.githubusercontent.com/20935380/27630846-42a5492a-5c14-11e7-9c7d-f6ca29f0f771.png)

If you search for 0(zero) then, the following condition in EloquentController.php retrun false as 0 consider as false. and it won't call **filterColumn** function.
 if ($keyword = $request->get('search')['value']) {
            $datatables->filterColumn('rownum', 'whereRaw', '@rownum  + 1 like ?', ["%{$keyword}%"]);
}

Not getting why condition is there? instead you can simply assign search value to $keyword variable

$keyword = $request->get('search')['value'];

and then,

 $datatables->filterColumn('rownum', 'whereRaw', '@rownum  + 1 like ?', ["%{$keyword}%"]);


Will it impact current functionality if I remove condition form there?

**Comment by yajra** [comment]
Yes, I think the if condition is not needed and should be removed.

**Comment by ruchisheth** [comment]
But https://datatables.yajrabox.com/fluent/advance-filter this works fine even if the condition is there. How?

**Comment by yajra** [comment]
It's because the condition fails when value is zero. `if (0) == if (false)`,

```php
if ($keyword = $request->get('search')['value']) {
  // not reached when keyword is zero.
}
```
