### ISSUE TITLE
Sorting Creates Duplicates in Datatable That Are Not in DB - Eager Loaded Relationship

### ISSUE THREAD

**Issue by madsem** [yajra/laravel-datatables#1224]
Hey,

thanks for this awesome package, it's been going great so far. But I stumbled on a problem that I can't seem to figure out now.

I'm eager loading a relationship and when I'm sorting the datatable in my view, the Datatable all of a sudden has duplicate rows that aren't in the database. It has something to do with the amount of relationships but I can't figure out what.

```php
/**
     * Process dataTable ajax response.
     *
     * @param \Yajra\Datatables\Datatables $datatables
     * @return \Illuminate\Http\JsonResponse
     */
    public function dataTable()
    {
        $landers = Lander::with('tags')
                         ->select('landers.id', 'landers.lander_label', 'landers.lander_domain', 'landers.lander_path_uuid', 'landers.created_at');

        return Datatables::of($landers)
                         ->addColumn('tags', function (Lander $lander) {
                             return $lander->tags->map(function ($tags) {
                                 return $tags->tag_label;
                             })->implode(',');
                         })
                         ->addColumn('preview', function ($data) {
                             $preview = $data->lander_domain . '?lp_preview=' . $data->lander_path_uuid;

                             return view('landers.datatables.preview', compact('preview'));
                         })
                         ->addColumn('action', function ($id) {
                             return view('partials.datatables.checkbox', $id);
                         })
                         ->rawColumns(['action', 'preview'])
                         ->blacklist(['action', 'preview'])
                         ->make(true);
    }
```

```javascript
$(function () {
        $('.datatable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('api.landers') }}',
            "order": [],
            columns: [
                @can('delete_landers')
                {data: 'action', name: 'action', orderable: false, searchable: false},
                @endcan
                {data: 'lander_label', name: 'landers.lander_label'},
                {data: 'lander_domain', name: 'landers.lander_domain'},
                {data: 'tags', name: 'tags.tag_label'},
                {data: 'created_at', name: 'landers.created_at'},
                {data: 'preview', name: 'preview', orderable: false, searchable: false},
            ],
            "pagingType": "full_numbers"
        });
    });
```

```sql
select `tags`.*, `lander_tag`.`lander_id` as `pivot_lander_id`, `lander_tag`.`tag_id` as `pivot_tag_id` from `tags` inner join `lander_tag` on `tags`.`id` = `lander_tag`.`tag_id` where `lander_tag`.`lander_id` in ('1', '2', '5', '8', '11', '14', '17', '18', '21')
```

the actual pivot table for lander_tag:
![screen shot 2017-06-24 at 4 17 20 pm](https://user-images.githubusercontent.com/3166991/27509293-780ae520-58f9-11e7-82df-2137b7301b5e.png)

This is the resulting table:
(As you can see the row with ID 21 is listed three times, exactly as many times as there are tags relationships.

![screen shot 2017-06-24 at 4 23 52 pm](https://user-images.githubusercontent.com/3166991/27509300-994fcbce-58f9-11e7-94a3-ac3cf57ba9b2.png)

Expected result:
The table sorted by tags, with just one table row for ID 21.

- PHP 7.1
- Laravel 5.4
- Datatables v7.8.0

**Comment by madsem** [comment]
Ok so I've investigated further, this does not happen on the original query when datatable is first build, it only happens on column sort of a belongs to many column.

This works, and displays the table correct with the tags that belong to the Lander model, in the same row
```php
$landers = Lander::select('landers.id', 'landers.lander_label', 'landers.lander_domain', 'landers.lander_path_uuid',
            'landers.created_at')->with('tags')->distinct();

        return Datatables::of($landers)
                  ->editColumn('tags', function (Lander $lander) {
                      return $lander->tags->pluck('tag_label')->implode(',');
                  })
                  ->addColumn('preview', function ($data) {
                      $preview = $data->lander_domain . '?lp_preview=' . $data->lander_path_uuid;

                      return view('landers.datatables.preview', compact('preview'));
                  })
                  ->addColumn('action', function ($id) {
                      return view('partials.datatables.checkbox', $id);
                  })
                  ->rawColumns(['action', 'preview'])
                  ->blacklist(['action', 'preview'])
                  ->make(true);
```


![screen shot 2017-06-25 at 10 47 04 am](https://user-images.githubusercontent.com/3166991/27514734-ab10605e-5993-11e7-88d4-7d3e0b5735fc.png)


But when I order the Tag column, it creates new duplicate rows:
![screen shot 2017-06-25 at 10 48 29 am](https://user-images.githubusercontent.com/3166991/27514739-db6ce128-5993-11e7-99d3-2802298cf7c2.png)

**Comment by yajra** [comment]
@madsem I think this is the default behavior on the SQL LEVEL. I usually disable sorting on has many relations.

**Comment by madsem** [comment]
@yajra thanks, I figured it's probably something like that, still learning :)

It's also what I ended up doing, disabled ordering and left searchable because that works.

Can you explain off the top of your head why this happens in SQL? Just trying to understand it. When I run the query in sequel pro, I get two results (i expected that) I just thought the package would then loop over those and not also make a second row?

Why is this happening? Would be awesome if you had an explanation so I can get it through my head ;) Thanks again!

**Comment by yajra** [comment]
AFAIK, this is how it works. 

Given:
```
users
id | name 
1 | A 
2 | B

posts
id| user_id | title
1 | 1 | Post 1
2 | 1 | Post 2
3 | 2 | Post 3
```

### WITHOUT RELATION SORTING
When we load users, the usual query generated is:
```sql
select users.* from users order by id
```
Output:
```
1 | A | post 1 + post 2 (collection of posts)
2 | B | post 3
```
### WITH RELATION SORTING
But when we order by relation, we are then force to join the relation to be able to do so:
```sql
select users.* from users
left join posts on users.id = posts.user_id
order posts.title
```
Output:
```
1 | A | post 1
1 | A | post 2
2 | A | post 3
```

**Comment by Morinohtar** [comment]
Hi,

>  But since we are eager loading posts. The output will become:
> 
> 1 | A | post 1 + post 2
> 1 | A | post 1 + post 2
> 2 | B | post 3

I'm using the latest version and this is not happening to me.

Controller function that is called by the datatable:
```
    public function datatable(Request $request)
    {
        if ($request->expectsJson()) {
            $columns = ['ingredient_types.id', 'ingredient_types.published', 'ingredient_types.created_at'];
            $with = ['translations'];

            $builder = IngredientType::with($with)->select($columns);

            return Datatable::ingredientTypes($builder);
        }
    }
```

Helper function to create the datatable:
```
    public static function ingredientTypes($ingredientTypes)
    {
        return DataTables::eloquent($ingredientTypes)
            ->editColumn('name', function (IngredientType $ingredientType) {
                return $ingredientType->translations->map(function ($translation) {
                    return str_limit($translation->name, 30, '...');
                })->implode('<br>');
            })
            ->rawColumns(['name'])
            ->toJson();
    }
```

JS:
```
      $('#datatable').DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                pageLength: 25,
                orderClasses: true,
                order: [1, 'desc'],
                pagingType: "full_numbers",
                ajax: {
                    url: "{!! route('backend.ingredient-type.ajax.datatable') !!}",
                    type: 'POST',
                    dataType: 'json',
                    cache: false
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'translations.name'}
                ]
        });
```

Output:
![datatable](https://user-images.githubusercontent.com/5765516/32107934-fdb64026-bb27-11e7-83e3-33edb6842539.PNG)


How do i just show one row per ID? This only happens when the sorting is applied in the relation column. If the sorting is applied tn the ID it shows correctly. But i looked in your examples and this doesnt occur... what am i missing here? Thanks.
