### ISSUE TITLE
PHP Built-in server and 404

### ISSUE THREAD

**Issue by isometriq** [yajra/laravel-datatables#1225]
I know that the issue of the built-in webserver is know ..but I am on a quest for a workaround.
It is what is used internally by the `php artisan serve` command and many IDE.

The issue is indeed a problem with the PHP built-in server, for example when launched like this
php.exe -S 127.0.0.1:8008 -t /path/to/working/dir

There seems to be a limit either in the URL or the GET querystring
https://stackoverflow.com/questions/7724270/max-size-of-url-parameters-in-get

In my case, the limit, including host name, uri and querystring, it seems it's around 1190 chars. So the following URL works without 404 (i'm using a REST query tool and passing the laravel session cookies):
http://127.0.0.1:8008/admin/users?draw=11&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=id&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=name&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=email&columns%5B2%5D%5Bname%5D=email&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=is_super_user&columns%5B3%5D%5Bname%5D=is_super_user&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=created_at&columns%5B4%5D%5Bname%5D=created_at&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=updated_at&a=1&b=2&c=3

Adding a small param `d=4` or any more will start giving random 404 errors.

And this behavior is the same with or without authentication or csrf token protection middlewares.

**Comment by isometriq** [comment]
I've found a workaround that I'd like to share.

In the my datatable class, I configure the datatable to use POST requests
ps: I've stripped parts of the class, simply generated with `php artisan datatables:make`

```
class UsersDataTable extends DataTable
{
    // ...
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax(['url'=>url('admin/users'),'type'=>'POST']) // <--- HERE
                    ->addAction(['width' => '80px'])
                    ->parameters([
                        'dom'     => 'Bfrtip',
                        'order'   => [[0, 'desc']],
                        'buttons' => [
                            'create',
                            'export',
                            'print',
                            'reset',
                            'reload',
                        ],
                    ]);
    }
    //...
}
```

I had the route set like this
`Route::get('users', 'UsersController@index');`

So I changed it for
`Route::any('users', 'UsersController@index');`

..but it could be `::post` or even a different route url?

With these changes, datatables works fine without any 404 errors!

**Comment by isometriq** [comment]
http://php.net/manual/en/features.commandline.webserver.php
One thing I did not try was to check the default INI settings and see if they could be changed or tweak any relevant option...

I seems that this condition `php_sapi_name() == 'cli-server'`  could be used for automatic exceptions when using the built-in server.

**Comment by yajra** [comment]
@isometriq thanks for digging into this issue and I've been aware of the URL length issue but haven't figured out a way to work around with it until today. Thanks to this research, I got an AHA moments and have finally figured a solution to this long going issue. See PR https://github.com/yajra/laravel-datatables-html/pull/13 for ref.

**Comment by isometriq** [comment]
Glad to hear it! I will check this out
