### ISSUE TITLE
How to integrate vuejs with datatable?

### ISSUE THREAD

**Issue by ahmadalshugairi8** [yajra/laravel-datatables#1227]

**Comment by yajra** [comment]
I did try to experiment with vue and dataTable. See this vue component I made for ref. It's not fully tested but it does the job the last time I checked.

https://github.com/yajra/dt54/blob/master/resources/assets/js/components/DataTable.vue

```js
<data-table :columns="columns" :ajax="/"></data-table>

new Vue({
   data: {
      columns: [ {data: 'id'}, {data: 'name'} ] // your standard dt columns..
   }
})
```

**Comment by almas-alright** [comment]
this dose not works perfectly. is there any example  or working demo?

**Comment by nusendra** [comment]
i need this too

**Comment by RVP04** [comment]
Yes me too need

**Comment by nusendra** [comment]
really need this so hard :-)

**Comment by nwaweru** [comment]
Anyone with a tutorial for this?

**Comment by nusendra** [comment]
i prefer to build my table component by myself @nwaweru

**Comment by sstepanovvl** [comment]
> i prefer to build table component by myself @nwaweru

demo please...
