### ISSUE TITLE
Unexpected data found with Carbon

### ISSUE THREAD

**Issue by eComEvo** [yajra/laravel-datatables#123]
Using the `~3.0` version in Laravel 4.2 to create the following controller response to a jQuery DataTables AJAX request:

    public function getData()
    {
        $items = Item::select();

        return Datatables::of($items)
            ->addColumn('actions', function ($items) {
                return '<a href="{{{ URL::to(\'items/\'' . $items->id . '\'/edit\' ) }}}" class="iframe btn btn-default btn-xs" data-id="' . $items->id . '">{{{ Lang::get(\'button.view_edit\') }}}</a>';
            })
            ->make(true);
    }

The `Item` model has the standard Laravel timestamps `updated_at` and `created_at` in a MySQL database.

When I call that route, Carbon spits out the exception `Unexpected data found.`

Why is laravel-datatables creating an exception on these timestamps?

**Comment by yajra** [comment]
Carbon is working fine on my side. Are you using the latest v3.6.7 version? If not try updating by using `composer update yajra/laravel-datatables-oracle`. Thanks!

Btw, I think there is an error in your code. You need to specify some columns on your select.

```php
$items = Item::select(['columns']);
```

**Comment by eComEvo** [comment]
If the columns aren't specified, it just assumes `'*'` as the argument.

Regardless, problem solved in 3.6.7. Thanks!
