### ISSUE TITLE
UTF-8 problem in CSV Export

### ISSUE THREAD

**Issue by maple9991** [yajra/laravel-datatables#1230]
### Summary of problem or feature request
I've tried to export utf-8 encoded data to csv.
And I get data exactly when I open it in notepad. (UTF-8 encoded in notepad)
The point is I can't get data exactly with excel as shown image.

![image](https://user-images.githubusercontent.com/25544960/27605220-94fe9bf6-5bae-11e7-99b2-fb36cd41f7a0.png)

As you can see all data is broken in excel. 
What can I do to fix this issue?

Here is my code .
![image](https://user-images.githubusercontent.com/25544960/27605273-c3e6d078-5bae-11e7-9f35-f7d21e01164f.png)

PS. When I convert exported file to unicode format in notepad manually it works perfect in excel.

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
https://github.com/Maatwebsite/Laravel-Excel is the package we are using to export to csv, excel. I think this question would be answered better on that repo. Thanks!
