### ISSUE TITLE
Is there a way to build the query (with filtering and sorting) but without execute it?

### ISSUE THREAD

**Issue by abel888** [yajra/laravel-datatables#1234]
### Summary of problem or feature request

I want to chunk all DB results and export it to a CSV. At this moment, I'm getting the query parameters in the request, but I can't access to the query builder without executing the query.

### Code snippet of problem
```php

$modelQuery = Model::select(['id', 'name']);

// Something like this would be great:

Datatables::eloquent($modelQuery)->chunk(500, function ($elements){
               // export
});

```

**Comment by yajra** [comment]
Sorry, but AFAIK, there is no way to achieve this atm.

**Comment by yajra** [comment]
Implemented a quick solution on v8. Still experimenting but this is how I see it.

```php
$dataTable = Datatables::eloquent($modelQuery);

if ($export) {
   $query = $dataTable->getFilteredQuery()->chunk(500)...;
}

return $dataTable->make();
```

**Comment by yajra** [comment]
Fixed on v8.
