### ISSUE TITLE
Sorting empty value with DataTables as a Service Implementation

### ISSUE THREAD

**Issue by Arkhas** [yajra/laravel-datatables#1236]
### Summary of problem or feature request

When using DataTables as a Service Implementation, sorting a column do this : 

• Asc :

[empty] 
[empty] 
[empty]
A 
B 
C 
D 
E 
 
• Desc : 

E
D
C
B
A
[empty] 
[empty] 
[empty] 

Is there a way to sort it to have : 

• asc :
A 
B 
C 
D 
E 
[empty] 
[empty] 
[empty] 

• desc : 

E
D
C
B
A
[empty] 
[empty] 
[empty] 

### System details

Mac OSX
PHP Version 7.1
Laravel Version 5.4
Laravel-Datatables Version 7.9.1

Thank you

**Comment by yajra** [comment]
You can use [orderByNullsLast](https://yajrabox.com/docs/laravel-datatables/7.0/order-by-nulls-last). But you may have to adjust depending on your database.

**Comment by Arkhas** [comment]
Thanks, that work when doing : 

```
return $this->datatables
            ->of($this->query())
            ->orderByNullsLast();
```
but it is not when using custom column with custom parameters, I would like to do this sorting when $this->query() return a collection, so after the mysql query is executed.

Do you know if this is possible ?

**Comment by yajra** [comment]
@Arkhas sorry but nulls last sorting on collection is not supported. We have implement very minimal functionalities on collection.

You may however submit a PR if you can implement it. Thanks!
