### ISSUE TITLE
multiple column sorting with collection engine

### ISSUE THREAD

**Issue by jond64** [yajra/laravel-datatables#1237]
I've found that if DataTables requests sorting by multiple columns, the returned data is only sorted by the last orderable column when using the collection engine.

Based on this discussion regarding sorting a collection by multiple columns ...

https://stackoverflow.com/questions/25451019/what-is-the-syntax-for-sorting-an-eloquent-collection-by-multiple-columns

I tried replacing the foreach loop in the ordering() function with the code below, and that seems to correctly sort the collection by multiple columns.

```
        $criteria = $this->request->orderableColumns();
        if ($criteria)
        {
            $comparer = function ($first, $second) use ($criteria) {
            foreach ($criteria as $orderable) {
                $column = $this->getColumnName($orderable['column']);
                // normalize sort direction
                $direction = $orderable['direction'];
                if ($first[$column] < $second[$column]) {
                    return $direction === "asc" ? -1 : 1;
                } else if ($first[$column] > $second[$column]) {
                    return $direction === "asc" ? 1 : -1;
                }
            }
            // all elements were equal
            return 0;
            };
            $this->collection = $this->collection->sort($comparer);
        }
```

**Comment by yajra** [comment]
@jond64 good catch and thanks for linking to the solution. Can you please submit a PR on 7.0 branch for the fix?
