### ISSUE TITLE
Summary total in the footer column

### ISSUE THREAD

**Issue by yurik3zzz** [yajra/laravel-datatables#1239]
### Summary of problem or feature request

How make summary to footer column?

### Code snippet of problem

```php
        $dataTableQuery = Users::query()
            ->leftJoin('user_info', 'users.id', '=', 'user_info.id')
            ->select([
                'users.id',
                'users.username',
                'users.role_id',
                'user_info.first_name',
                'user_info.last_name',
                'user_info.email',
                'users.blocked',
                'users.balance',
                'users.created',
            ]);

$sums = [
            'sum_balance' => '0',
        ];

        $datatables = Datatables::of($dataTableQuery )
            ->escapeColumns(['first_name', 'last_name', 'email'])
            ->editColumn('created', function ($user) {
                return Carbon::createFromFormat('Y-m-d H:i:s', $user->created)->toDateString();
            })
            ->editColumn('blocked', function ($user) {
                return $user->blocked_label;
            })
            ->addColumn('actions', function ($user) {
                return $user->gamers_buttons;
            })
            ->filter(function ($query) use ($request) {
                if ($request->has('username')) {
                    $query->where('username', 'like', "%{$request->get('username')}%");
                }
            })
            ->addSum('sum_balance', DB::raw("sum(balance)")) <-- How do it?
            ->with('sums', $sums);
```
-->

### System details

- Operating System Windows 8.1
- PHP Version 5.6.29
- Laravel Version 5.4
- Laravel-Datatables Version 7

**Comment by yajra** [comment]
Use the same query passed on DT like:

```php
->addSum('sum_balance', $dataTableQuery->sum('balance'))
```

**Comment by yurik3zzz** [comment]
$dataTableQuery - This is passed without filtering and|or searching data. How get a parsed query with all binding params?

**Comment by prakash-pokhrel** [comment]
How to display this in blade ?

**Comment by yajra** [comment]
@yurik3zzz you can use [withQuery](https://yajrabox.com/docs/laravel-datatables/master/response-with#query-closure) api for that on the latest version.

@prakash-pokhrel you would need to handle the display via javascript by accessing the ajax response data. Something like: `LaravelDataTables["users-table"].ajax.json()`

**Comment by prakash-pokhrel** [comment]
@yajra I still didn't get it. Should I place this inside html() function of datatable or put directly in blade. Btw, I am using datatable as service

**Comment by yajra** [comment]
Try adding a script on drawCallback.

```js
$('#users-table').on('draw.dt', function() {
  $('#total').val( LaravelDataTables["users-table"].ajax.json().total )
})

**Comment by yajra** [comment]
If you are using the latest html package v4.0, you can do something like:

```php
public function html()
{
  ...
  ->ajax()
  ->drawCallback('function() { $('#total').val( LaravelDataTables["users-table"].ajax.json().total ) }')
  ...
```

**Comment by prakash-pokhrel** [comment]
Hi,
What does "#total" stands for in
 ->drawCallback('function() { $("#total").val( this.api().ajax.json().total ) }') 

Is this id inside table or in other html element ?

**Comment by yajra** [comment]
It's a jquery selector for an element using id.
