### ISSUE TITLE
Column filter doesn't work. I get zero rows ever

### ISSUE THREAD

**Issue by joanebrown** [yajra/laravel-datatables#124]
Hi! Some time ago I found a little bug in your awesome yajra datatables package (https://github.com/yajra/laravel-datatables/issues/49), and now I think I found another (although it could be my fault, really)

I have the next javascript code:

    $.fn.dataTableExt.oApi.fnFilterColumn = function (oSettings,i, val) {
       $.extend( oSettings.aoPreSearchCols[ i ], {
               "sSearch": val+""
       } );
    }

and I call the this as follow:

     // 3 is the number of the column, and $(this).val() retrieve (correctly, I checked that) the selected value of my select (the value is the ID of the column, the ID of the user):
     dataTable.fnFilterColumn(3, '^' + $(this).val());

Structure of my table:

       <th>ID</th>
       <th>DATE</th>
       <th>USER</th>

And this is my Laravel code:

     return Datatables::of( Auth::user()->pets()->select(array('id', 'date',  'user_id')))
            ->setRowId(function($pet) {
                return $pet->id;
            })
            ->editColumn('user_id', function($pet){
               return $pet->user->user_name;
            })
     ->make();

**Comment by yajra** [comment]
I just tried your script and seems like your `fnFilterColumn` plugin is not working. Try inspecting your script and searching is not being fired. 

I think you can use something like below to achieve the same results. 

```js
dataTable.columns(3).search('^' + $(this).val()).draw();
```

**Comment by joanebrown** [comment]
Thanks for your fast answer. I try right now your code, but doesn't work :(  

`dataTable.columns is not a function`

I don't understand why my `fnFilterColumn` doesn't work... This retrieve all the rows ever; but I see no error.

Could you help me with this problem, please? I can't find the solution...

Thanks for your amazing job.

**Comment by yajra** [comment]
@joanebrown, how did you initialize your dataTable? You should use the API version using `DataTable` and not `dataTable`.

```js
// this will return DataTable API
var dataTable = $('table').DataTable({options});

// this will bind to dom
var dataTable = $('table').dataTable({options});
```

**Comment by yajra** [comment]
Or you can use something like this to access all visible dataTable instance and then perform column search.

```js
var tables = $.fn.dataTable.tables(true);
$(tables).DataTable().columns(3).search('^' + $(this).val()).draw();
```

Ref: http://datatables.net/reference/api/%24.fn.dataTable.tables()

**Comment by joanebrown** [comment]
All works well... Thanks for your help :)

Regards!
