### ISSUE TITLE
DT_Index_Row not sorting accordingly in table

### ISSUE THREAD

**Issue by funkistz** [yajra/laravel-datatables#1243]
the index column not sorting accordingly on POST method when updating to new version
last working in v7.8.1

happen when using the addIndexColumn() function

### Code snippet of problem

```php
$datatables = Datatables::of($counselling)
             ->addIndexColumn()
             ->make(true);
             
```

### System details

- Windows 10
- 5.6.25
- 5.4
- 7.9.1

**Comment by yajra** [comment]
Can you please paste how did you get the `$counselling` var?

**Comment by funkistz** [comment]
Maybe my explanation was not clear.

[](url)
![capture](https://user-images.githubusercontent.com/24681851/27845662-b0ff1d98-6163-11e7-984c-df9439980c01.PNG)

As u can see above the DT_Row_Index was not display in order. But it display in order on 7.8.1 and below.
I already test this on several machine and OS including Machintosh.

The counselling is just a collection using eloquent.

`$counselling = Counselling::All();`

and i retrieve it like this

`columns: [
          { data:'DT_Row_Index' },
          { sTitle: 'Date', data: 'date' }
]`

**Comment by yajra** [comment]
I see, I think I know where the issue occurs. We are now processing / transforming all the response before doing search/sorting to allow searching of added & edited columns when using collection. But since index column is part of the transformation, the arrangement is now incorrect.

Will try to fix this as soon as I can. Thanks!

**Comment by funkistz** [comment]
Ok thanks for the fast reply. I'm happy to help you

**Comment by marcelogarbin** [comment]
I'm also having this column sorting problem. Following...

**Comment by yajra** [comment]
Fix on v7.9.3. Kindly update and confirm. Thanks!

**Comment by marcelogarbin** [comment]
@yajra Is correct now. Thank you =)

**Comment by saraswat19** [comment]
Now the table sorting is working but still, the index column is not sorting.

![image](https://user-images.githubusercontent.com/6272778/42363903-f773c7f0-8116-11e8-82d6-4aa3b11f7ce5.png)

**Comment by ndaday** [comment]
how to revert transformed? not work for me 9.0
