### ISSUE TITLE
Pdf and excel buttons is not visible

### ISSUE THREAD

**Issue by AdrianKuriata** [yajra/laravel-datatables#1244]
### Summary of problem or feature request

Hi, i have a problem. I don't see print and excel buttons for export data. I don't know why this won't work but this is really important. I tried use snappy but the same result. I don't get any error in console.

### Code snippet of problem

```
$doles = $builder->columns([
                [
	                'data' => 'dole_type', 
	                'name' => 'dole_type', 
	                'title' => 'Typ'
                ],
                [
	                'data' => 'dole_cash', 
	                'name' => 'dole_cash', 
	                'title' => 'Ofiara'
                ],
                [
	                'data' => 'dole_date',
	                'name' => 'dole_date', 
	                'title' => 'Data'
                ],
                [
                    'data' => 'floor.floor_name',
                    'name' => 'floor.floor_name',
                    'title' => 'Ulica'
                ]
            ])
    	    ->parameters([
                'language' => [
                	'url' => asset('js/Polish.json'),
	                'buttons' => [
	                	'copy' => 'Do schowka',
	                	'copyTitle' => 'Skopiowano do schowka',
	                	'copySuccess' => [
		                	'1' => "Skopiowano jeden wiersz do schowka",
		                	'_' => "Skopiowano %d wierszy do schowka"
	                	],
	                ],
                ],
                'searching' => false,
                'dom' => '<"pull-right"B>lfrtip',
                'buttons' => [
	                [
	                	'copy'
                	],
	                [
	                	'extend' => 'pdf',
	                	'text' => 'Do PDF',
	                ],
	                [
	                	'extend' => 'excel',
	                	'text' => 'Do EXCEL',
	                ],
	                [
	                	'extend' => 'csv',
	                	'text' => 'Do CSV',
	                ]
                ],
                'lengthMenu' => [
                	[
                		10,
                		25,
                		50,
                		100,
                		150,
                		1000
                	],
                	[
                		10,
                		25,
                		50,
                		100,
                		150,
                		1000
                	],
                ],
                'order' => [
                	[
                		2,
                		'desc'
                	]
                ]
            ]);
```

### System details

- Operating System Homestead
- PHP Version 7.0.8-2
- Laravel Version Newest
- Laravel-Datatables Version Newest

**Comment by yajra** [comment]
You need add `print` on `buttons` array to be able to use it. For excel, I don't see any issue on your code. Did you write any custom js to overwrite the `excel` button?

**Comment by AdrianKuriata** [comment]
Hi, i don't understand nothing.... Look, when i have `buttons.server-side.js` file added i can see EXCEL and PDF button but when i click on them i getting error in console:

`http://kartoteka.dev/doles?draw=1&columns%5B0%5D%5Bdata%5D=dole_type&columns%5B0%5D%5Bname%5D=dole_type&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=dole_cash&columns%5B1%5D%5Bname%5D=dole_cash&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=dole_date&columns%5B2%5D%5Bname%5D=dole_date&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=floor.floor_name&columns%5B3%5D%5Bname%5D=floor.floor_name&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=2&order%5B0%5D%5Bdir%5D=desc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&action=excel 404 (Not Found)`

Before i don't had this file loaded and EXCEL button worked properly, now when i don't have this file, i don't see EXCEL buttton. Im confused... PRINT button working ok, but i want use PDF and EXCEL button, this buttons not working with `buttons.server-side.js` file. I don't have modified JS code which could overwrite excel or PDF button.

**Comment by yajra** [comment]
404 (Not Found), must something wrong with your environment.

Anyways, I made a patch on latest release of html plugin. On your builder, try using `minifiedAjax()`.

```php
builder->columns([
                [
	                'data' => 'dole_type', 
	                'name' => 'dole_type', 
	                'title' => 'Typ'
                ],
                [
	                'data' => 'dole_cash', 
	                'name' => 'dole_cash', 
	                'title' => 'Ofiara'
                ],
                [
	                'data' => 'dole_date',
	                'name' => 'dole_date', 
	                'title' => 'Data'
                ],
                [
                    'data' => 'floor.floor_name',
                    'name' => 'floor.floor_name',
                    'title' => 'Ulica'
                ]
            ])
->minifiedAjax()
...
```

**Comment by AdrianKuriata** [comment]
@yajra This not helped, i don't see error in console, but in my browse URL i see url which i added before and i don't get PDF or EXCEL file with data...

**Comment by yajra** [comment]
Possibly yes on your resource. You should put server-side.js script as the last entry.

**Comment by AdrianKuriata** [comment]
I added file after resources but still not working... I have latest dataTables version, before this is worked properly without server-side.js file, now this is not working without and with this file, i don't know what i doing bad...

**Comment by AdrianKuriata** [comment]
@yajra I'm done, i don't have idea why this not working. I just use PRINT buttons and will be enough with csv i clipboard buttons, thank you for you time.
