### ISSUE TITLE
columns with html shows code

### ISSUE THREAD

**Issue by carlituxman** [yajra/laravel-datatables#1245]
### Summary of problem or feature request

I use addColumn to show a button but now is returning html code, it works before 7.9 version

### Code snippet of problem

->addColumn('status', function ($model) {
                    return "<a href='". route('control.status', [$model->id]) ."' class='btn btn-sm btn-icon icon-left'><i class='fa fa-icon'></i> Activate</a>";
                })

**Comment by Ammar777** [comment]
![5555555](https://user-images.githubusercontent.com/18471073/27840473-eb2edcea-6101-11e7-9a17-c7b372e15f14.JPG)

**Comment by Ammar777** [comment]
i have the same problem >_<

**Comment by ReckeDJ** [comment]
Same here! Back to 7.8.1 for now..

**Comment by yajra** [comment]
Thanks for reporting, I think this was fixed on 7.9.1. Please update to the latest version.

**Comment by yajra** [comment]
Did you use `rawColumns(['status'])` on your code?

**Comment by ReckeDJ** [comment]
@yajra Thanks! rawColumns did the trick.

**Comment by Ammar777** [comment]
@yajra thanks for you ,,
can you send an example !

**Comment by rubensrocha** [comment]
Just a help to anyone:

When use ->addColumn() and ->editColumn with html content, you need set ->rawColumns(['addcolum','editcolum']) to avoid addColumn return html and editColumn return data.

Example:
```
->addColumn('action', function ($dtt) {
                return '<a href="'.route('routename).'" class="btn btn-xs btn-primary""><i class="glyphicon glyphicon-edit"></i> '.trans('btn.edit').'</a>';
            })
->editColumn('status', function($dtt) {
            if($dtt->status == TRUE){
               return '<span class="label label-success">'.trans('admin.status.active').'</span>';
            }else{
                return '<span class="label label-danger">'.trans('admin.status.inactive').'</span>';
            }
        })
        ->rawColumns(['status','action'])
        ->make(true);
```

**Comment by dmz3010** [comment]
@rubensrocha thanks!   the only solution I found was to change the version of yajra to 6.6, but with this clarification, I can continue with version 8.0 of yajra
