### ISSUE TITLE
Create a drop down list to change Status of a row

### ISSUE THREAD

**Issue by templatecompany** [yajra/laravel-datatables#1247]
Hello,
I want to create a drop down list for each row in the datatable. In my case, I will change status of row data with options(finished, pending, etc.), and also save that in database when I click one of these options.

Many Thanks

**Comment by yajra** [comment]
Try following the concept done on this demos:

https://datatables.yajrabox.com/services/users-with-footer
https://datatables.yajrabox.com/collection/multi-filter-select

**Comment by templatecompany** [comment]
I don't  want to filter data, I want to Edit data with Dropdown select. So, if I select an option of Dropdown list, Finished or Pending, this change should be stored in the database in the respective column called "Status". The  question is how  can I create dropdown list for each row in order to edit data from selected dropdown list option and store to database. I'm using Ajax to display data on datatable.

**Comment by yajra** [comment]
Oic, didn't quite get the question :)...

Anyways, just add a custom html column then hook a js event on that select box that once changed, you fire an ajax request that updates the database.

```php
->addColumn('action', function() {
  return 'select box html';
})
```

Then add a jquery/vanilla scripts that handles any related action on select input. Google can help you on that.
