### ISSUE TITLE
clicking on paging number fired searh.dt event

### ISSUE THREAD

**Issue by ruchisheth** [yajra/laravel-datatables#1249]
### Summary of problem or feature request
clicking on paging number fired searh.dt event.

table.on('search.dt', function () {
      console.log('search event');
    });

the above function log 'search event' even when I click on page numbers at bottom of the table

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
I think that is the default behavior of `dataTables.js`. See https://datatables.net/reference/event/search for details.
