### ISSUE TITLE
QueryBuilderEngine Count does not work correctly for queries with SELECT DISTINCT

### ISSUE THREAD

**Issue by pauls6832** [yajra/laravel-datatables#125]
If a query has a SELECT DISTINCT then the QueryBuilderEngine count() method returns the wrong value. The problem is that it replaces "select count(*) as aggregate from (select distinct <columns>..." with a "select count(*) as aggregate from (select distinct '1'...." which always returns a row count of 1 instead of the correct number of rows. The count() method checks for UNION and HAVING before changing the query to '1', please add a check for DISTINCT as well.

**Comment by yajra** [comment]
Thanks for reporting. Added DISTINCT on ignored list. Should be fixed on v5.8.2.

**Comment by pearl1811** [comment]
How to overwrite your count function?  because  i have big data (aprox: 400000 records) so count taking more time. Please help.

**Comment by yajra** [comment]
@pearl1811, unfortunately, there is no way to overwrite the count function. On the other hand, I have a million records and does not have a problem on count. You might be using collection? Can you please provide some snippet of you DT?
