### ISSUE TITLE
Displaying model id when sorting by related models

### ISSUE THREAD

**Issue by apsg** [yajra/laravel-datatables#1250]
I'm constantly experiencing problems with proper displaying model id in datatables. 

I have 3 models: `Qr` model and two related models: `Place` and `Client`. In my datatables I display (via AJAX) following columns:

    columns: [
            { data: 'id', name: 'id', searchable: true },
            { data: 'client.name', name: 'client.name', searchable : true },
            { data: 'place.address', name: 'place.address', searchable:true },
            { data: 'deviceid', name: 'deviceid', searchable:true },
            ...

and in my controller I prepare data using `with` clause:

    $model = \App\Qr::where(...)->with('client', 'place');
    return Datatables::of($model)->make(true);

I have problems with displaying the `id` column. Initially it correctly shows id of `Qr` item. But if I try to sort by another column, it displays id of underlying column. For example, if I sort by `client.name` column, the `id` column shows ids of `Client` models, instead of `Qr`. If I sort by `place.address` column, it shows ids of `Place` model. 

How can I show properly (and still be able to search/order) the id of main model in datatables?

**Comment by yajra** [comment]
You need to add select on your query when using eager loading:
```
$model = \App\Qr::where(...)->with('client', 'place')->select('qr.*');
```

Related docs:
http://dt54.yajrabox.com/eloquent
https://datatables.yajrabox.com/eloquent/relationships

**Comment by apsg** [comment]
Great, thank you! now it works!
