### ISSUE TITLE
Adding column that's not in Database

### ISSUE THREAD

**Issue by ghost** [yajra/laravel-datatables#1252]
# Summary of problem or feature request

I am trying to add a custom collumn 'applications', what is not in my database, but it doesn't display because I have not added the name to 'collumns', how can I add it t my table?

### Code snippet of problem

        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('DT_RowId', function($jobs){
                return 'jobs-' . $jobs->id;
            })
            ->addColumn('status', function ($jobs) {
                if($jobs->status == 0){
                    return "
                        <span class='text-danger'>Pending Payment</span>
                        <a href='".route('payment.job.pay', [$jobs->id, 'job'])."' class='btn btn-default btn-xs'><i class='fa fa-gbp'></i></a>";
                }else{
                    return "<em class='text-success'>Live</em>";
                }
            })
            ->addColumn('applications', function ($jobs) {
                if(count(Apply::Job($jobs->id)->get()) > 0){
                    return "
                        <a href='".route('applications.show', $jobs->id)."'>
                            <span class='label label-info'>View ".count(Apply::Job($jobs->id)->get())." Applications</span>
                        </a>";
                }else{
                    return "<span class='label label-danger'>No one has applied</span>";
                }
            })
            ->addColumn('action', function($jobs) { 
                $objectId    = $jobs->id;
                $edit        = 'editJob';
                $identifier  = 'jobs';
                $delete_path = 'jobs.destroy';
                $show_path   = 'jobs.show';

                return view('partials.table-buttons', compact('objectId', 'edit', 'delete_path', 'show_path', 'identifier'))
                    ->render();
            })
            ->rawColumns(['status', 'applications', 'action']);
You may use the markdown php code tags to format your paste:

**Comment by yajra** [comment]
Add in table markup? Just set it on your builder columns?

```php
protected function getColumns() {
  return [
    'id',
    'applications'
    etc...
  ];
}
