### ISSUE TITLE
get only 10 records per request instead of all

### ISSUE THREAD

**Issue by abusalameh** [yajra/laravel-datatables#1256]
Hi There, I'm trying to retrieve about 300k records 
when I tried 

```php 
Activity::all();
```
the datatable cannot retrive the data.

I tried to use the Query
```php
Activity::query()->skip(($request->start ) * $request->length)->limit($request->length);
```
it came with a result but the paging is not working, the main problem is the ```$request->start``` is always set to ```0```

any help ?

**Comment by yajra** [comment]
Just use `Activity::query()` and do include the pagination part. The package will do that for you.

**Comment by abusalameh** [comment]
I did use that , but the pagination is not working ! any ideas ?
