### ISSUE TITLE
Add Column Action - Changing route() url

### ISSUE THREAD

**Issue by marcelogarbin** [yajra/laravel-datatables#1258]
Operating System Win10
PHP Version 7
Laravel Version 5.4
Laravel-Datatables Version 7.9.2

I call my tables via AJAX function, it's in the controller and I use the route ('name.route') method to call the buttons. Ex.: 
```
public function ajaxListarRegistrosCadastrados(Request $request)
    {
        if($request->ajax()) {
            $grupos = Role::select(['id', 'readable_name', 'name', 'created_at', 'updated_at']);

            return Datatables::of($grupos)
                ->addColumn('action', function ($grupo) {
                    return
                        '<div class="acao text-center">'.
                        // edit
                        '<a href="'. route('permissao.edit', $grupo->id) .'" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>'.
                        // delete
                        Form::open(['route' => ['permissao.destroy', $grupo->id], 'method' => 'DELETE', 'class' => 'form-inline']).
                        '<button type="submit" class="btn btn-sm btn-danger btn-lixeira" data-id="'.$grupo->id.'" data-toggle="tooltip" data-placement="top" title="Deletar"><i class="fa fa-trash-o" aria-hidden="true"></i></button>'.
                        Form::close().
                        '</div>';
                })
                ->escapeColumns(['action'])
                ->removeColumn('deleted_at')
                ->make();
        }else{
            return redirect()->route('login');
        }
    }
```

It turns out that when I use the  `route('permissao.edit', $grupo->id)`, it is not respecting the current URL. I do not know why, I would like to know how to adjust to work correctly.

Ex.: Using the `npm run watch`, when calling the view index the URL is correct, however when calling the method `ajaxListarRegistrosCadastrados()` the URL is changed.

This is the call to view, it is correct:
![image](https://user-images.githubusercontent.com/9335588/28080956-15940626-6644-11e7-91da-1b698bcfd655.png)

This is the datatables call, it has the URL changed:
![image](https://user-images.githubusercontent.com/9335588/28081024-46e481b0-6644-11e7-9f10-4996b44d8586.png)

With this, the call of the buttons are changed, the correct one would be: `http://localhost:3000/painel/permissao/18/editar` but returns me `http://admin.dev/painel/permissao/18/editar`. Being the url currently active as `http://localhost:3000`

How can I fix this?

**Comment by yajra** [comment]
Hmm this is a weird one. Have you tried clearing your view cache?

`php artisan view:clear`

**Comment by marcelogarbin** [comment]
@yajra Was the first thing I tried to do rsrs ... But the error continues, I do not know what it can be, do you suggest any tests? This only occurs when I add the button in the datatables.

**Comment by marcelogarbin** [comment]
Problem solved, I believe it is some problem with Laravel. To solve the problem of changing the address of routes, I used the solution quoted in this post: https://github.com/laravel/framework/issues/2554#issuecomment-246645265

`RouteServiceProvider.php`:
```
public function boot()
    {
        parent::boot();
        /** @var \Illuminate\Routing\UrlGenerator $url */
        $url = $this->app['url'];
        // Force the application URL
        $url->forceRootUrl(config('app.url'));

    }
```

In this way the routes and url behave as they should, by the constant set in the .env file.

You can close this issue.
