### ISSUE TITLE
DataTables Laravel 5.4 Undefined Index with Ajax Request

### ISSUE THREAD

**Issue by pirmax** [yajra/laravel-datatables#1260]
I use **DataTables** and **yajra/laravel-datatables-oracle** package for **Laravel 5.4**. I want display **screen_name** in column **screen_name**. **screen_name** is in JSON object (*JSON result*).

##Ajax script code:##

    $(document).ready(function() {
        $('#logs-table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: 'api/ajax-file',
            columns: [
                { data: 'credentials.screen_name', name: 'credentials.screen_name' }
            ],
            aoColumns: [
                {
                    aTargets: [0],
                    mData: 'credentials.screen_name',
                    mRender: function (data, type, full) {
                        return '<strong>' + data + '</strong>';
                    }
                }
            ]
        });
    });

##HTML code:##

    <table class="table table-hover table-striped" id="logs-table">
        <thead>
    	    <tr>
    	        <th>User</th>
    	    </tr>
        </thead>
    </table>

##JSON result:##

    {
    	"draw":0,
    	"recordsTotal":208,
    	"recordsFiltered":208,
    	"data": [{
    		"_id":"5960e2f59f9d5158f7129d82",
    		"credentials":{
    			"id":"1",
    			"id_str":"1",
    			"name":"User 1",
    			"screen_name":"user1"
    		},
            ...
    	}]
    }

##Yajra Query:##

    public function ajax(Request $request)
    {
        $users = User::all();
        return Datatables::of($users)->make(true);
    }

##I have this error:##

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/wSwLn.png

**Comment by yajra** [comment]
I think the issue here is on js? Maybe try something like:

```js
$(document).ready(function() {
    $('#logs-table').DataTable({
        processing: true,
        serverSide: true,
        stateSave: true,
        ajax: 'api/ajax-file',
        columns: [
            { 
              data: 'credentials.screen_name', 
              name: 'credentials.screen_name', 
              render: function (data, type, full) { 
                return '<strong>' + data + '</strong>';
              }
            }
        ]
    });
});
```

**Comment by pirmax** [comment]
The request give me:

`{"draw":1,"recordsTotal":2,"recordsFiltered":0,"data":[],"error":"Exception Message:\n\nUndefined index: credentials.screen_name"}`

The real request is:

```
$logs = $twitter->logs()->where('user_id', $this->user->id)->take(2)->get();
        return Datatables::of($logs)->make(true);
```

I have already the same issue...

**Comment by yajra** [comment]
It seems like your using collection and I think nested array sorting is not yet supported. Is this working before or just a new code? 

If it's previously working then I guess this PR #1238 might have broke it. But afaik, I haven't tested nested array for sorting/searching on collection. Thanks!

**Comment by yajra** [comment]
I think you work around this by transforming your collection before passing it to dataTables.

```php
$logs = $twitter->logs()->where('user_id', $this->user->id)->take(2)->get();
$logs->transform(function ($data) {
    return array_dot($data);
});
return Datatables::of($logs)->make(true);
```

**Comment by pirmax** [comment]
It give me this result, it doesn't works.

`{"draw":0,"recordsTotal":1,"recordsFiltered":1,"data":[{"incrementing":"1","exists":"1","wasRecentlyCreated":false,"timestamps":"1"}],"input":[]}`

**Comment by yajra** [comment]
Not sure how mongodb driver does this. But the trick is to flatten your nested array using dot notation.

This is how I tested it on a normal collection:

```php
$collection = collect([
    [
        '_id'         => '5960e2f59f9d5158f7129d82',
        'credentials' => [
            'id'          => 1,
            'name'        => 'Yajra',
            'screen_name' => 'Yajra',
        ],
    ],
    [
        '_id'         => '5960e2f59f9d5158f7129d8a2',
        'credentials' => [
            'id'          => 2,
            'name'        => 'Gerger',
            'screen_name' => 'Gerger',
        ],
    ],
])->transform(function ($data) {
    return array_dot($data);
});

return $datatables->collection($collection)->make(true);
```

**Comment by abhishekjain-itsme** [comment]
I also get the same issues. Can you check it once?

**API Call** - 
$residencies = Residency::get();
return datatables()->of($residencies)->toJson();

**My Ajax** -
url = "{{ url('admin/residencies-data') }}";

    var table = $('#table1').dataTable({
        processing: true,
        serverSide: true,
        dom: 'Bfrtip',
        buttons: [],
        pageLength: 10,
        lengthMenu: [ 10, 25, 50, 100],
        ajax: { "url": url, "type": "GET"},
        columns: [
                    { data: function(data){
                                    return '<img src="'+ asset +'/'+ data.logo +'" width="75px" class="uploaded-img">';
                                }
                    },
                    { data: function(data){
                                    return data.name + '(' + data.unique_id + ')';
                                }
                    },
                    { data: function(data){
                                    return data.address + ', ' + data.city + ' - ' + data.pin;
                                }
                    },
                    { data: 'phone'},
                    { data: function(data){
                                    return '<img src="'+ asset +'/'+ data.photo +'" width="75px" class="uploaded-img">';
                                }
                    },
                    { data: function(data){
                                    if(data.status == 1)
                                        return 'Active';
                                    else
                                        return 'Inactive';
                                }
                    },
                    { data: function(data){
                                    return '<a href="javascript:void(0)" class="btn btn-success btn-sm edit_data" data-id="'+ data.id +'">Edit</a>' +
                                            '<a href="javascript:void(0)" class="btn btn-danger btn-sm delete_data delete_data" data-id="'+ data.id +'">Delete</a>';
                                }
                    },
                ],
    });

**Get this issue** -
![Screenshot (68)](https://user-images.githubusercontent.com/24824276/71185075-c5fc9d00-22a0-11ea-8cdc-b7dcbe979dfb.png)
![Screenshot (69)](https://user-images.githubusercontent.com/24824276/71185078-c5fc9d00-22a0-11ea-847f-c1d2866dd22c.png)
