### ISSUE TITLE
How Column Search on render datatable with serverside

### ISSUE THREAD

**Issue by muhrizkiakbar** [yajra/laravel-datatables#1261]
I dont know hot to add column search on rendering datatable

i need the server side because i want to export the data into pdf and excel

thankyou

### this is my server side datatable

public function dataTable()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->editColumn('persentase','{{$persentase}} %');
    }

    /**
     * Get the query object to be processed by dataTables.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
//
        $query = masterabsensi::with('instansi');
        return $this->applyScopes($query);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('')
                    ->parameters([
                        'dom'          => 'fBrtip',
                        'buttons'      => ['pdf','excel'],
                    ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'NIK'=>['name'=>'masterabsensis.NIK','data'=>'NIK','title'=>'NIP'],
            'nama'=>['name'=>'masterabsensis.nama','data'=>'nama','title'=>'Nama'],
            'normal'=>['name'=>'masterabsensis.normal','data'=>'normal','title'=>'K'],
            'riil'=>['name'=>'masterabsensis.riil','data'=>'riil','title'=>'M'],
            'late'=>['name'=>'masterabsensis.late','data'=>'late','title'=>'T'],
            'absent'=>['name'=>'masterabsensis.absent','data'=>'absent','title'=>'A'],
            'Bleave'=>['name'=>'masterabsensis.Bleave','data'=>'Bleave','title'=>'TL'],
            'tb'=>['name'=>'masterabsensis.tb','data'=>'tb','title'=>'TB'],
            'sakit'=>['name'=>'masterabsensis.sakit','data'=>'sakit','title'=>'S'],
            'ijin'=>['name'=>'masterabsensis.ijin','data'=>'ijin','title'=>'I'],
            'cuti'=>['name'=>'masterabsensis.cuti','data'=>'cuti','title'=>'C'],
            'persentase'=>['name'=>'masterabsensis.persentase','data'=>'persentase','title'=>'P'],
            'periode'=>['name'=>'masterabsensis.periode','data'=>'periode','title'=>'PER'],
            'namaInstasi'=>['name'=>'instansi.namaInstansi','data'=>'instansi.namaInstansi','title'=>'instansi']

        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'absensidatatable_' . time();
    }

### System details

- Operating System
- PHP Version 5.6.4
- Laravel Version 5.4
- Laravel-Datatables Version 7.0

**Comment by yajra** [comment]
Please see this [demo](https://datatables.yajrabox.com/services/users-with-footer) for ref. Thanks!
