### ISSUE TITLE
website down and bugged https://yajrabox.com/

### ISSUE THREAD

**Issue by hsali** [yajra/laravel-datatables#1262]
### Summary of problem or feature request

![image](https://user-images.githubusercontent.com/6765330/28174094-e9af5eee-6809-11e7-847f-8f1c2e0d82cc.png)

### System details

it is website error . I didn't find any other resouce to tell it. kindly fix it. I want to read the documentation for laraval datable.

**Comment by luiz-brandao** [comment]
You can find some documentation here: https://datatables.yajrabox.com/

**Comment by grafxflow** [comment]
Also getting the same on that server at the bottom of the page. Plus getting error popup because of broken json data feeds.

**Comment by yajra** [comment]
Thanks for reporting. It seems like my server's storage is full. Will try to fix it asap.

**Comment by yajra** [comment]
Sadly, automated backup eats up all the server's storage :(. Fixed! Thanks..
