### ISSUE TITLE
DataTables warning: table id=product-table - Ajax error

### ISSUE THREAD

**Issue by conangithub** [yajra/laravel-datatables#1267]
### Summary of problem or feature request
Hello. I always get error "DataTables warning: table id=product-table - Ajax error" while try to load the product table data using ajax. Any suggestion for me to fix this error? This is my code.

### Code snippet of problem

**ProductController.php**

```
public function index(Datatables $datatables)
    {
        $dt = $datatables->eloquent(Product::query())
            ->editColumn('id', function($item) {
                return view('admin.datatable-link', ['href' => "/admin/products/{$item->id}/edit", 'link' => $item->id]);
            })
            ->rawColumns(['id'])
            ->make(true);

        return $dt;
    }

```
**product.blade.php**

```
@section('scripts')
  @parent
  <script>
    $(function() {
      $('#product-table').DataTable({
        processing: true,
        serverSide: true,
        pageLength: 10,
        ajax: '{{ route('products.index') }}',
        columns: [
          {data: 'id', title: 'Id'},
          {data: 'code', title: 'Code'},
          {data: 'name', title: 'Name'},
          {data: 'owner', title: 'Owner'},
          {data: 'formulation', title: 'Formulation'},
          {data: 'size', title: 'Size'},
          {data: 'unit', title: 'Unit'},
          {data: 'type', title: 'Type'},
          {data: 'quantity', title: 'Quantity'},
        ]
      });
    });
  </script>
@endsection
```
**route.php**
```
Route::resource('products', 'Admin\ProductController', [
            'only' => ['index', 'create', 'edit', 'store', 'update']
        ]);
```

### System details
I am using :
- OS : Win 10 64-bit
- PHP : 7.0.9
- Laravel : 5.4
- yajra/laravel-datatables-html : 2.0.5
- yajra/laravel-datatables-oracle : 7.9.3
- yajra/laravel-datatables-buttons : 2.0.2

###Additional informations
- The error sometimes appear sometimes not.
- I have checked XHR on Firefox's Developer -> Network, the error is 401 Unauthorized.
- If I reload this page, it will ask me to login again.

**Comment by yajra** [comment]
Based on additional informations, it seems like you are using `php artisan serve` and this is known to be buggy when using the package. Please use valet, homestead or any apache2 stack. Thanks!

**Comment by conangithub** [comment]
Is it also because I am use it in Windows? If I using it in Machitosh, no problem appear.

**Comment by abdhannan** [comment]
I have same issue,
i use vallet in windows 10.

**Comment by conangithub** [comment]
I change to Apache and don't get problem anymore.
