### ISSUE TITLE
rawColumns() no longer works for collection key names

### ISSUE THREAD

**Issue by jond64** [yajra/laravel-datatables#1268]
It looks like with the changes in v7.9.0, specifying rawColumns by key name for a collection no longer works.  It worked with v7.8.1.

This is also impacting PR #1238 and causing "Undefined index" errors.  Below is an example of the object that gets passed to the ordering function in v7.9.0.

```
[2017-07-14 16:34:58] production.INFO: Yajra\Datatables\Engines\CollectionEngine::__set_state(array(
   'collection' => 
  Illuminate\Support\Collection::__set_state(array(
     'items' => 
    array (
      0 => 
      array (
        0 => '1',
        1 => '1T',
        2 => 'Street R',
      ),
      1 => 
      array (
        0 => '2',
        1 => '2T',
        2 => 'Street R',
      ),
    ),
  )),
   'original_collection' => 
  Illuminate\Support\Collection::__set_state(array(
     'items' => 
    array (
      66 => 
      array (
        'rank' => '',
        'position' => '1T',
        'group' => 'Street R',
      ),
      67 => 
      array (
        'rank' => '',
        'position' => '2T',
        'group' => 'Street R',
      ),
    ),
  )),
```

**Comment by yajra** [comment]
Maybe this is due to transforming the collection first [PR](https://github.com/yajra/laravel-datatables/pull/1232)? Will review further when I got the chance. Thanks!

**Comment by oriceon** [comment]
Have same problem with last build ! :(

**Comment by yajra** [comment]
@oriceon I have released a patch for a possible fix. Can you please verify if v7.9.7 fixes the issue? Thanks!

**Comment by oriceon** [comment]
@yajra , yes now is working as expected. Thank you for quick patch.
