### ISSUE TITLE
Cannot search zero value in column search

### ISSUE THREAD

**Issue by mifas** [yajra/laravel-datatables#127]
Hi, I have added column search option (ref: https://datatables.net/examples/api/multi_filter.html)
But I have several records that contains `0` values. When I tried to search it was returned all the records. 

So I digged into core file. in `doColumnSearch` function I replaced this line no 449 into 

``if ($columns[$i]['searchable'] == "true" and  ( !empty($columns[$i]['search']['value']) || $columns[$i]['search']['value'] == 0 ) and ! empty($columns[$i]['name'])) {``

then only its working. Is there any alternative options out there?

**Comment by yajra** [comment]
@mifas, what version are you using? Try updating to latest version by running `composer update yajra/laravel-datatables-oracle` and test again. I think this issue was already fixed and `doColumnSearch` was already replaced as `columnSearch`.

**Comment by yajra** [comment]
Fixed on v3.6.8.
