### ISSUE TITLE
Question: Service Implementation when not using HTML builder

### ISSUE THREAD

**Issue by Waguilar33** [yajra/laravel-datatables#1272]
### Summary of problem or feature request

I have used this package following this guide [DataTables as a Service Implementation](https://datatables.yajrabox.com/service) and it seems that with version 7+ HTML builder and Button plugins go hand and hand. 

I have the following datatable design to filter
![image](https://user-images.githubusercontent.com/21320293/28287515-34357b50-6af9-11e7-8291-65058eff026d.png) 

I have been searching the entire documentation and all I could found is this tutorial [Advance Filtering](https://datatables.yajrabox.com/eloquent/advance-filter) but I'm pretty sure it is not service implementation. **Buttons functionality is a must for my project.** and advance filtering too.

Anyway I can accomplish both using service implementation? Or what should I do. any help will be greatly appreciated.

### System details

- Operating System
- PHP Version: 7.1
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.9.3

**Comment by yajra** [comment]
The same code on demo can be used on `dataTable()` method on service implementation for advance filter.

For buttons, just add the server-side js script.

**Comment by Waguilar33** [comment]
thanks for the answer @yajra so i really don't need the html builder and buttons plugins then? only the main DataTable package?
