### ISSUE TITLE
How to use setRowData to change row values with conditions?

### ISSUE THREAD

**Issue by rubensrocha** [yajra/laravel-datatables#1273]
How can I override the value of a row based on the value received from the database.

Example:
$data->status = bool

How to replace the status value of each line with a text (eg active, inactive, on, off, etc)?

That is, transform a line like this:
Id | Contact Us | Status | Action
---------------------------------
1 | Product 1 | 1 | Action Buttons
2 | Product 2 | 0 | Action Buttons

For this:
Id | Contact Us | Status | Action
---------------------------------
1 | Product 1 | Active | Action Buttons
2 | Product 2 | Inactive | Action Buttons

I've tried it, but it does not work.
->setRowData([
            'status' => function($data){
                return ($data->status == 1) ? trans('status.active'): trans('status.inactive');
            }
        ])->make(true);

**Comment by yajra** [comment]
You should use [editColumn](https://yajrabox.com/docs/laravel-datatables/7.0/edit-column) and not rowData.

```php
->editColumn('status', function($data) {
  return ($data->status == 1) ? trans('status.active'): trans('status.inactive');
})
```

**Comment by rubensrocha** [comment]
@yajra Thanks man, now it worked.
