### ISSUE TITLE
Question : how to use Select columns (colvis)

### ISSUE THREAD

**Issue by Orbscope** [yajra/laravel-datatables#1274]
### Summary of problem or feature request

Example : https://datatables.net/extensions/buttons/examples/column_visibility/columns.html 
Reference  : https://datatables.net/reference/button/colvis

**Comment by yajra** [comment]
I think you just need to include the necessary assets and this should work out of the box. Haven't tried the plugin yet but I think it would work.

**Comment by andrechalom** [comment]
I can confirm that this works out of the box. You only need to include the right js. If you're including datatables.net-buttons in your `resources/assets/js/app.js`, for instance, just add the colvis include:

```js
    require('datatables.net-buttons'); // this should already be there
    require('datatables.net-buttons/js/buttons.colVis.js')(); // add this
```
