### ISSUE TITLE
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'objective' in 'where clause' 

### ISSUE THREAD

**Issue by Kyosfonica** [yajra/laravel-datatables#1275]
I use datatables as Service

In my current project I need to create some columns based on information on the database but mixed or transformed. I use SQL for that but it seems that when filtering datatables is unable to find those new columns I create via SQL.
This is the most basic example of what I am trying to do.

Code:

    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', function($row) {
                return view('admin.externaloffers._actions', compact('row'))->render();
            })
            ->filterColumn('objectives', function ($query, $keyword) {
                $query->whereRaw(
                    "objectives  like ?",
                    [
                        "%{$keyword}%",
                    ]
                );
            })
            ->make(true);
    }

    public function query()
    {
        $query = Externaloffer::select([
            DB::raw('externaloffers.*, CASE WHEN user_type = \'patient\'  THEN \'Paciente\' ELSE \'Clinica\' END AS objectives')
        ]);
        return $this->applyScopes($query);
    }

The information is correctly displayed in the view but any attemp of search ends up with an
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'objective' in 'where clause' 

I looked examples, read the documentation but I do not find the issue.

### System details
- Operating System Ubuntu 16.04
- PHP Version 7.1
- Laravel Version 5.2
- Laravel-Datatables Version 6.29.0

**Comment by Kyosfonica** [comment]
By the way, sorting works as expected out of the box.
The same SQL run from the database creates these columns:
id |name |description |url |code |user_type |published |created_at |updated_at |deleted_at |objectives |

**Comment by yajra** [comment]
Your query is invalid as the error stated. AFAIK, searching on column alias is not allowed but sorting is supported thus it works. You need to update your query builder appropriately. Try using query builder when statements.

**Comment by Kyosfonica** [comment]
Query builder doesn't work either.
I will figure out another way to filter that column.

Thanks.

**Comment by gslongo** [comment]
Hi !

I think this might be related to the issue i'm facing to : https://github.com/yajra/laravel-datatables/issues/1648

Did you found a solution ?

Thanks !
