### ISSUE TITLE
XSS filtering

### ISSUE THREAD

**Issue by apreiml** [yajra/laravel-datatables#128]
Hi,

I'm currently implementing xss filtering like so:

```
return Datatables::of('table')
    ->editColumn('surname', '{{ $surname }}')
    ->editColumn('forename', '{{ $forename }}')
...
```

But for larger tables and if used often this becomes quite cumbersome and also easy to overlook some of the columns. Is there a better way to do this? Is it possible to filter column data on default?

**Comment by yajra** [comment]
hi @apreiml, sorry didn't quite get what you mean by xss filtering. Does it mean like you want to display a column data but filter on another fields? You can always add a `visible: false` column to add them on filters like:

```js
// javascript
{
columns: [
  // will display surname but will search and sort using begins_at
  { data: 'surname', name: 'begins_at' }, 
  // will search on surname but is not visible to the user.
  { data: 'surname' name: 'surname', visible: false }, 
]
}

**Comment by apreiml** [comment]
XSS: Cross-site scripting is a common vulnerability in web applications. That means if someone writes 
```<script>alert('hello');</script>``` into one of your database entries it will get executed if it is shown without escaping. For example if it's stored in $surname. With this you can do really nasty stuff, like stealing sessions.

But blade will "escape" such a content if it's printed out using the '{{ }}' operators. That means the code will be displayed as a string. Hence I need to manually escape all of the fields.

See here https://en.wikipedia.org/wiki/Cross-site_scripting or here https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29 for more information.

PS: If edited the names of the columns at the previous comment.

**Comment by yajra** [comment]
I see, I got confused on the the different field names and it was a typo. Will think over this and let you know what I may find. Currently, we just display what is stored on our DB.

**Comment by yajra** [comment]
Btw, just sharing, what I did to prevent XSS records on my DB is by adding a global input sanitizer using `[Purifier](https://github.com/mewebstudio/Purifier)` package. You may also want to look at it.

**Comment by yajra** [comment]
This http://usman.it/xss-filter-laravel/ link is what I used in conjunction with Purifier. In case your interested. Just create a middleware that utilizes both scripts depending on your needs.

**Comment by yajra** [comment]
@apreiml, I just added a new feature for XSS filtering on v5.9.0. You can now escape column values using `escapeColumns` method.

```php
// escape selected fields
return $datatables
    ->eloquent(Role::select())
    ->escapeColumns(['name'])
    ->make(true);

// escape all output
return $datatables
    ->eloquent(Role::select())
    ->escapeColumns()
    ->make(true);

// escape by output index
return $datatables
    ->eloquent(Role::select())
    ->escapeColumns([0])
    ->make();
```
