### ISSUE TITLE
Bug --- Repetition of queries when transformer implementation requires an object

### ISSUE THREAD

**Issue by geoalex89** [yajra/laravel-datatables#1280]
As of version 7.9.1 when the transformer inplementation requires an object, the queries repeat it, because call method results() re-launche the queries
`class BaseEngine
if ($parameter->getClass()) {
            $resource = new Collection($this->results(), $this->createTransformer());`

**Comment by yajra** [comment]
Fix on v7.9.5, kindly update and confirm. Thanks!
