### ISSUE TITLE
Cannot set width column/resize column Yajra Datatables

### ISSUE THREAD

**Issue by axelsoedarsono** [yajra/laravel-datatables#1285]
### Summary of problem or feature request

Hi sir Arjay, so its me again, yeah i'm having problem with my datatables, looks like i cant resize or set desire size of column in datatables yajra, already try searching and still got nothing, so im trying to hardcode it with inline style still not work, can you explain the best practice to do set column width / height ?? thank you very much !

- Operating System : Ubuntu 14.04 LTS
- PHP Version : 5.6
- Laravel Version : 5.4
- Laravel-Datatables Version : 2.*~

**Comment by yajra** [comment]
Not sure if it's best practice but I also inline the width on my columns if needed. There are lot of examples on https://datatables.net/examples/index. You might a better answer there. Thanks!

**Comment by axelsoedarsono** [comment]
okay thank you Sir Yajra (y)
