### ISSUE TITLE
You're datatable with another language

### ISSUE THREAD

**Issue by Katerou22** [yajra/laravel-datatables#1288]
Hey there, i edited some of you're codes and return it to another language, can you support it please?

https://github.com/Katerou22/Datatables-Persian

**Comment by lk77** [comment]
all languages are already supported by default.
in getBuilderParameter : 
`'language' => Lang::trans('datatable'),`
and create a datatable.php file on resources/lang/{your_lang}/

**Comment by Katerou22** [comment]
Thank you i didn't know

**Comment by ChaosPower** [comment]
Closing issue. Please open a new one if you have any.
