### ISSUE TITLE
overwriting the keyword from search text

### ISSUE THREAD

**Issue by shiroamada** [yajra/laravel-datatables#1291]
My database status column store 3 statuses:-
0 - Pending
1 - Active
2- Inactive

When I display out for the user, I use Pending, Active and Inactive showing the DataTables. However, how do I let my user search via Pending, Active or Inactive and filter the status result?

Below is my code, but it is not working.

```php
if ($keyword = request()->get('search')['value']) {

$datatables->filterColumn('textstatus', function($query, $keyword) {
                $keyword = strtolower($keyword);

                if($keyword == 'pending')
                    $keyword = '0';
                elseif($keyword == 'active')
                    $keyword = '1';
                elseif($keyword == 'inactive')
                    $keyword = '2';

                $sql = "business.status = ?";
                $query->whereRaw($sql, ["{$keyword}"]);
            });
}
```

### System details

- Operating System: MacOS
- PHP Version: 7.0.11
- Laravel Version: 5.1.40
- Laravel-Datatables Version: 6.0

**Comment by yajra** [comment]
Try using condition query on Laravel. See https://laravel.com/docs/5.4/queries#conditional-clauses for details.

**Comment by shiroamada** [comment]
Possible show how to tweak the question I ask?
am I still using $datatables->filterColumn?
