### ISSUE TITLE
Support for custom engines (eg for mongodb)

### ISSUE THREAD

**Issue by pimlie** [yajra/laravel-datatables#1294]
For my project I am using mongodb through [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb/). Unfortunately I couldnt get laravel-datatables to work with mongodb, as laravel-mongodb requires different syntax in the QueryBuilderEngine as it does not use sql.

To still use mongodb I've written a rough [mongodb engine](https://github.com/pimlie/laravel-datatables-mongodb/) for datatables. But as it seems at the moment there is no easy way of adding a custom engine to datatables, I had to completely exend the laravel-datatables project and e.g. overwrite all methods where configuration settings are pulled.

As this implementation is very ugly and difficult to maintain, do you have any recommendations how to better add a custom engine for mongodb?

**Comment by yajra** [comment]
On version 8, I am also trying to create an engine for Laravel Scout. See https://github.com/yajra/laravel-datatables-scout for reference for possible implementation.

**Comment by pimlie** [comment]
Will you be changing the general engine interface in v8 as well, like removing the `eloquent` and `queryBuilder` methods in `Datatables.php`? From a code perspective I think it would be best to keep the interfaces for built-in engines and custom engines as much the same as possible.

One way to keep the interface more uniform would be by adding a magic __call method like the following pseudo code:
```php
// Datatables.php
public function __call($method, $parameters)
{
  $engines = $config->get('datatables.engines');
  if (!isset($engines[$method])) {
    throw new BadMethodCallException("Method {$method} does not exist.");
  }

  return $engines[$method]::getInstance($parameters);
}
```

Then you would only need to add your engine to the config.engines (and builder) array and you could just do `return Datatables::scout($model);` and/or `return Datatables::of($scoutModel);`.

Only difficulty with this solution i see currently is that e.g. jenssegers/mongodb extends the Eloquent classes, so the `of` method in `Datatables.php` would probably return an Eloquent engine and not a Moloquent engine. Either people should be instructed to add their custom engines definition _before_ the eloquent definition (in `config/datatables.php`) or we should add a check for these kind of inheritances between engines on startup.

**Comment by yajra** [comment]
> Will you be changing the general engine interface in v8 as well, like removing the eloquent and queryBuilder methods in Datatables.php?

The interface would remain the same. The only major breaking change is the namespace and class name being updated from `Datatables` to `DataTables`. 

I was also thinking on how to implement `return Datatables::scout($model);` assuming that scout is on a separate package. Will try your suggestion when I got the chance. Thanks!
