### ISSUE TITLE
Set pagination type on server side

### ISSUE THREAD

**Issue by quantumwebco** [yajra/laravel-datatables#1296]
How to set the pagination type in the server side script, not in the javascript? So when 
{!! $dataTable->scripts() !!}
is called in the blade template it uses the specified pagination type.

Can we do something like 

return $this->datatables
           ->pagingType("extStyle")

Or how do we set the option?

Thanks

**Comment by yajra** [comment]
On html builder, just set the parameters.

```php
->parameters([
    'pagingType' => 'bootstrap',
    ...
])
```

**Comment by quantumwebco** [comment]
Great! Thanks a lot!
