### ISSUE TITLE
custom filters edit datatable state to print filtered results

### ISSUE THREAD

**Issue by akramabdulrahman** [yajra/laravel-datatables#1297]
hi , filtering using request and editing the query to filter results is working fine but i've got an issue 
 ```javascript
function mix(source, target) {
        $(source).each(function (i, v) {
            console.log(i, v);
            target[v['name']] = v['value'];
        })

    }

$('#dataTableBuilder')
        .on('preXhr.dt', function (e, settings, data) {
            mix($('#search-form').serializeArray(), data);
        })
        .dataTable({
            ajax: "data.json"
        });

    $('#search-form').on('submit', function (e) {
        window.LaravelDataTables.dataTableBuilder.draw();
        e.preventDefault();
    });
```

the code injects the value after filter into the datatable and causes "cannot reinitialize datatable" warning 
i can ignore that for now
the main issue am having is with print button . since my approch doesnt really edit the datatable context directly. print doesnt catch my change and prints the initial data without applying the filter .

my question is how to make print aware of changes i applied to datatable .

**Comment by yajra** [comment]
You should include that script on html builder on the server side script.

```php
->ajax([
   'url' => 'data.json',
   'data' => 'function(data) { mix($('#search-form').serializeArray(), data);  }'
])
```

**Comment by yajra** [comment]
Also, I think this is an issue on the js library. `preXhr.dt` hook is not really called on initial load as far as I know.

The reinitialize warning was also due to this script:

```js
.dataTable({
           ajax: "data.json"
       });
```
