### ISSUE TITLE
Maintain previous (latest visited) dataTable page when Navigation between web page

### ISSUE THREAD

**Issue by thomas-tewelde** [yajra/laravel-datatables#1299]
### I need to get the pagination of a datatable as i move to another page and then press back to previous page on the browser

on my datatable i have actions like edit, view, and so on. So forexample when i click it view a raw it takes me to another page to view details about that raw. Lets say that raw was on pagination 3. once i am done viewing that raw on another page and I want to go back to the datatables, on pressing back on browser i get back to pagination 1 instead of pagination 2. 

### System details

- Operating System: macOS Sierra 
- PHP Version: 5.6.29
- Laravel Version: 5.2.31
- Laravel-Datatables Version: ^6.11

**Comment by yajra** [comment]
Use dataTables stateSave option.
