### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by jmilagroso** [yajra/laravel-datatables#130]
How can I cache the data passed to the Datatable:of() ?

        $rows = MyModel::select('id',  'name', 'remarks', 'created_at')->from('my_table');

        return Datatables::of($rows)->make(true);

Thanks

**Comment by yajra** [comment]
ATM, there is no caching inside the Datatables class. You have to perform your caching queries first before passing it to datatables. I guess googling **laravel eloquent cache** may lead you in the right way.

Some links for Caching: 
- https://laracasts.com/lessons/caching-essentials
- http://datatables.yajrabox.com/collection/github

**Comment by standaniels** [comment]
Are there any plans to support caching? Maybe the entire query could be cached? (see [Laravel doc](http://laravel.com/docs/4.2/queries#caching-queries))

**Comment by yajra** [comment]
I think NO, Caching queries were removed on Laravel 5.x. It's only available on L4.2 and below. But if you can propose a nice solution/flow then I can reconsider implementing this if possible. Thanks!

**Comment by standaniels** [comment]
Alright, I'll look into it. Thanks.
