### ISSUE TITLE
Doctrine support

### ISSUE THREAD

**Issue by rodrigotavio91** [yajra/laravel-datatables#1300]
Is there some way to use it with Doctrine instead of Eloquent?

Thanks.

**Comment by yajra** [comment]
Not really sure on this one as I haven't personally used Doctrine yet. Thanks!

**Comment by rafaelucena** [comment]
There is a way.

Yajra crashes when it comes to converting the connected objects to array by recursion.

If you use the Query Builder from Doctrine and extract only the fields you want to use on the DataTable, it should be able to work.

I just configured mine. :)

**Comment by Gegeenmedia** [comment]
> There is a way.
> 
> Yajra crashes when it comes to converting the connected objects to array by recursion.
> 
> If you use the Query Builder from Doctrine and extract only the fields you want to use on the DataTable, it should be able to work.
> 
> I just configured mine. :)

@rafaelucena, do you have example?

**Comment by rafaelucena** [comment]
> > There is a way.
> > Yajra crashes when it comes to converting the connected objects to array by recursion.
> > If you use the Query Builder from Doctrine and extract only the fields you want to use on the DataTable, it should be able to work.
> > I just configured mine. :)
> 
> @rafaelucena, do you have example?

Sure, I did it here, line 59: https://github.com/rafaelucena/dedoduro/blob/master/app/Http/Controllers/Admin/BlogsController.php

**Comment by Gegeenmedia** [comment]
> > > There is a way.
> > > Yajra crashes when it comes to converting the connected objects to array by recursion.
> > > If you use the Query Builder from Doctrine and extract only the fields you want to use on the DataTable, it should be able to work.
> > > I just configured mine. :)
> > 
> > 
> > @rafaelucena, do you have example?
> 
> Sure, I did it here, line 59: https://github.com/rafaelucena/dedoduro/blob/master/app/Http/Controllers/Admin/BlogsController.php

Thank you @rafaelucena . I do it for my project. But its response just array. Did you do any other configurations?

Here is my response
{"draw":0,"recordsTotal":12,"recordsFiltered":12,"data":[{"id":"1","title":"Test product"},{"id":"6","title":"New product title"},{"id":"8","title":"No details Product"},{"id":"11","title":"No details Product 2"},{"id":"12","title":"new product"},{"id":"21","title":"last"},{"id":"22","title":"lp3"},{"id":"23","title":"product title"},{"id":"24","title":"New product title"},{"id":"25","title":"3 New product title"},{"id":"26","title":"3 New product title"},{"id":"27","title":"laast"}],"input":[]}

**Comment by rafaelucena** [comment]
No, I did what you see in my code.

I am getting an array from Doctrine also, which is how I'm using it into the lines 81, 84 of the same file.
It's all there man. :)

It's been a while since I don't work in this project so I can't give you any more information than this.
What I know is that it works...

If possible, use less information into the Datatables and check if it works with two columns or so.
