### ISSUE TITLE
HTML Escaping

### ISSUE THREAD

**Issue by ozanakman** [yajra/laravel-datatables#1301]
### Summary of problem or feature request

After updating to latest version which is called **7.9.6**,
**HTML contents** from modifyColumn and addColumn methods, **replaced with escaped characters**. 
I don't know if you did it on purpose but I have a lot tables those contain HTML content and therefore I have to downgrade to 7.9.5 version.

**Comment by mohrwurm** [comment]
Same problem here.

I think this commit is the reason
https://github.com/yajra/laravel-datatables/pull/1293/commits/5b4fe248bf2a9020486dff0e886335b0d69ed167

When you set rawColumns it has no impact
`Datatables::of($collection)->rawColumns(['columnname'])->make(true);`

It always wins what is set in the config file (datatables.columns.raw).

Please revert this commit.

**Comment by yajra** [comment]
I think this was due to the last PR. I made some patch and use recursive merge. Can you please verify if it fixes the issue? Thanks!

**Comment by mohrwurm** [comment]
yes.. works for me.. thx 👍

**Comment by ozanakman** [comment]
It's fixed, thanks!
