### ISSUE TITLE
EscapeColumns doesn't work in latest version -- v7.9.7

### ISSUE THREAD

**Issue by true-gler** [yajra/laravel-datatables#1304]
### Summary of problem or feature request

In the latest version, escapeColumns does not escape columns any more. 

Maybe related to issue #1302...

**Comment by AbuHamdah** [comment]
I have the same problem , rawColumns and escapeColumns not working , the  html returned as a text ,
![dara](https://user-images.githubusercontent.com/17378609/28770441-da566370-75e7-11e7-9d82-5a5e21d250bc.PNG)
![dara2](https://user-images.githubusercontent.com/17378609/28770442-db05908e-75e7-11e7-8efd-8138c126f1ec.PNG)

Please what a solution and thanks alot

**Comment by lk77** [comment]
it's not a bug, it's normal, escapeColumns is used to escape.

**Comment by true-gler** [comment]
There is a different bug with this. I will report shortly...
