### ISSUE TITLE
datatables laravel returned html element as a text

### ISSUE THREAD

**Issue by AbuHamdah** [yajra/laravel-datatables#1305]
The laravel datatables return an HTML as a text I used a rawColumns and escapeColumns but not working

Please what a solution and thank you

Please find a below pictures
![dara](https://user-images.githubusercontent.com/17378609/28770955-b81689be-75e9-11e7-877a-cf0eacd9fd13.PNG)
![dara2](https://user-images.githubusercontent.com/17378609/28770956-b81c70f4-75e9-11e7-93f5-cf5ddedb9b01.PNG)

### System details

- Operating System
- PHP Version 
- Laravel Version 5.3
- Laravel-Datatables Version 7.9

**Comment by lk77** [comment]
Hello, 

it's normal, escapeColumn is for escaping columns, so it's escaped.
change by 
`->escapeColumns(['id', 'username']`

**Comment by AbuHamdah** [comment]
But, what I should do, to return HTML element? 
Thank you for your response

**Comment by lk77** [comment]
you can use rawColumns(['link'])

**Comment by AbuHamdah** [comment]
I used it, this same problem appeared

**Comment by lk77** [comment]
try to use version 7.9.5, it's working for me, perhaps it's a recent bug.

**Comment by AbuHamdah** [comment]
I used the last version of datatables  laravel, 
I tried also ['link' => true] but not working ,
Must i upgrade laravel version to 5.4 ?

**Comment by lk77** [comment]
i don't think it will solve your issue

**Comment by AbuHamdah** [comment]
What should I do in your opinion?

**Comment by lk77** [comment]
you tried escapeColumns(['link' => true) of rawColumns(['link' => true]) ?

**Comment by AbuHamdah** [comment]
Yes, it is.

**Comment by lk77** [comment]
i mean which one you tested ?

**Comment by AbuHamdah** [comment]
I tested them both

**Comment by lk77** [comment]
escapeColumns([]) should disable escaping on all columns as a workaround

**Comment by AbuHamdah** [comment]
I tried all solutions but nothing be changed

**Comment by lk77** [comment]
and escapeColumns(null) ?

**Comment by AbuHamdah** [comment]
Same problem,
I have question, why the action column return HTML  but the link not?

**Comment by lk77** [comment]
it should work i don't understand.
you removed all the escapeColumns calls ?

**Comment by AbuHamdah** [comment]
How can i remove all escapeColumns calls? and why?

**Comment by lk77** [comment]
inside your code i mean,
because if your doing rawColumns
and next do the opposite with espaceColumns or something.

**Comment by AbuHamdah** [comment]
My code now is
 return Datatables::of($row)
          ->addColumn('link', '<a href="#">Html Column
        </a>')
        ->addColumn('action', '<a href="#">Html Column
        </a>')
          ->escapeColumns(null)
            ->make(true);

**Comment by lk77** [comment]
try ->escapeColumns('') instead

**Comment by AbuHamdah** [comment]
Same problem, I also don't understand why the action work probably but the link no

**Comment by lk77** [comment]
the action work because it's not escaped by default

**Comment by AbuHamdah** [comment]
Thank you for your effort,

**Comment by AbuHamdah** [comment]
There is any way to find a solution ?

**Comment by yajra** [comment]
Have released a patch v7.9.8. Can you please verify if it fixes the issue? Thanks and sorry for the inconvenience.

**Comment by AbuHamdah** [comment]
How I can upgrade to the last release?

**Comment by lk77** [comment]
i think you should try :
```
[
    'link' => 'link'
];
```

**Comment by AbuHamdah** [comment]
How i can update my version to 7.9.8

**Comment by lk77** [comment]
you can change your composer.json and set yajra/laravel-datatables to 7.9.8

**Comment by AbuHamdah** [comment]
Ok, I'll try it
Thank you

**Comment by AbuHamdah** [comment]
Finally, it works,
Thank you Yajre and IK77
i used escapeColumn['link'] in last version it working probably

**Comment by robiparvez** [comment]
for versions above 8, u have to go to config/datatables.php file....and add your column name in ....raw => ['name_of your_column']
