### ISSUE TITLE
escapeColumns does not escape columns (XSS) 

### ISSUE THREAD

**Issue by true-gler** [yajra/laravel-datatables#1307]
### Summary of problem

Escaping with escapeColumns does not work as related in:

[Yajrabox Documentation](https://yajrabox.com/docs/laravel-datatables/master/xss#none)

At first glance I thought escapeColumns is not working, but then I took a closer look to the escapeColumns function in the `DataProcessor`:

```php
protected function escapeColumns(array $output)
    {
        return array_map(function ($row) {
            if ($this->escapeColumns == '*') {
                $row = $this->escapeRow($row);
            } elseif (is_array($this->escapeColumns)) {
                $columns = array_diff_key($this->escapeColumns, $this->rawColumns);
                foreach ($columns as $key) {
                    array_set($row, $key, e(array_get($row, $key)));
                }
            }

            return $row;
        }, $output);
    }

```
Here, the `$columns = array_diff_key($this->escapeColumns, $this->rawColumns);` is the cause that the column that is declared as the first element in the array, to escape the columns, is removed ...

`rawColumns` contains the default action with index 0 

![image](https://user-images.githubusercontent.com/11291277/28774532-21c78c7e-75ee-11e7-89b9-a2c2c4350651.png)

and the `escapeColumns` further columns to escape...
So `array_diff_key` takes `action` and the `first item of escapeColumns` and doesn't add them to `$columns`. As a result the first column is **_not_** escaped.

Any suggestions?

post scriptum:
At version 7.9.7 rawColumns contains for some reason two action items:

![image](https://user-images.githubusercontent.com/11291277/28774115-64a69384-75ec-11e7-944b-93e51b0b733e.png)
 
so the first two are removed...

### System details
- Operating System: Ubuntu 16.04
- PHP Version: PHP 7.0.18
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.9.*

**Comment by lk77** [comment]
i made a pr for this.

**Comment by true-gler** [comment]
thanks :+1:

**Comment by yajra** [comment]
Have released a patch v7.9.8. Can you please verify if it fixes the issue? Thanks and sorry for the inconvenience.

**Comment by lk77** [comment]
the problem still exists

**Comment by yajra** [comment]
Patch v7.9.9 released. Please check and verify if it fixes the issue. Thanks!

**Comment by lk77** [comment]
it's working :+1: 

_escapeColumns_
```
array:2 [
  0 => "nb_client"
  1 => "action"
]
```
_rawColumns_
```
array:1 [
  0 => "action"
]
```
_result_
```
array:1 [
  0 => "nb_client"
]
```
