### ISSUE TITLE
Laravel 5 model custom Carbon dates are not working

### ISSUE THREAD

**Issue by saqueib** [yajra/laravel-datatables#131]
I have a User model in L 5 and added a `last_login` field and made it Carbon instance by adding it to Models `$dates['loast_login']`, but its not working in Datatables editColumn method, its treated as a literal string, not as Carbon date instance.

**User Model**

```php
class User extends Model {
   protected $dates = ['last_login'];
   ...
```

**Controller**

```php
->editColumn('last_login', '{!! $last_login->diffForHumans() !!}')
```

Its giving me 

    Call to a member function diffForHumans() on a non-object

Its working when I am converting it to Carbon in a closer like this

```php
->editColumn('last_login', function($user) {
                    return $user->last_login ? Carbon::createFromTimestamp(strtotime($user->last_login))->diffForHumans() : 'Never';})
```

**Comment by yajra** [comment]
@saqueib, it's working on my side. Most probably, your `last_login` field has `null` values which makes the code fail. You should catch null values too. 

```php
->editColumn('last_login', '{{ $last_login ? $last_login->diffForHumans() : "no data" }}')
```

**Comment by saqueib** [comment]
You are right @yajra, I completely forgot the `null` values. 

Thanks its working now, you have done amazing job on this Package, its awesome and well documented :+1: :yum:

**Comment by yajra** [comment]
:+1:
