### ISSUE TITLE
ERR_INVALID_RESPONSE from PDF button

### ISSUE THREAD

**Issue by quantumwebco** [yajra/laravel-datatables#1313]
### Summary of problem or feature request

Exporting a PDF shows a page with an error ERR_INVALID_RESPONSE
Exporting other formats is fine

I have asked about a 500 error too before but was told I needed to provide more info but it's impossible to debug there is no feedback from datatables about the errors. It would be good if it returned the info from the whoops page if it errors.

Why would the getDataForExport() function return a 500 error when on the page it loads fine and all it's doing is the same thig but putting it into a xls/pdf right??

Also so now why would it give an ERR_INVALID_RESPONSE for the PDF but works fine for XLS?

- Operating System Windows/Linux
- PHP Version 5.6/7
- Laravel Version 5.2
- Laravel-Datatables Version

**Comment by yajra** [comment]
What driver are you using for the pdf? `snappy` or `excel`? I suggest you use snappy as I found dompdf to be buggy.

**Comment by quantumwebco** [comment]
OK yeah I think it's using dompdf. Will take a look at snappy. Thanks.

**Comment by RayhanYulanda** [comment]
I have the same problem. Just try it in linux environment
https://github.com/yajra/laravel-datatables/issues/718#issuecomment-244589857
