### ISSUE TITLE
How to add Custom Button with action with Yajra Buttons Plugin

### ISSUE THREAD

**Issue by 123bistami** [yajra/laravel-datatables#1314]
Hi guys,

I will add Custom Button like pre defined Print, Excel Button with Custom Action, I implement service like in the documentation of use the Button Plugin, But its not work.

get every time js error "Uncaught Unknown button type: test"

my Service implementation:

class UsersQueryBuilderDataTable extends DataTable
{

    protected $actions = ['print', 'csv', 'excel', 'pdf', 'test'];

    /**
     * Build DataTable class.
     *
     * @return \Yajra\Datatables\Engines\BaseEngine
     */
    public function dataTable()
    {
        return $this->datatables
            ->queryBuilder($this->query())
            ->addColumn('action', 'eloquent.tables.users-action');
    }

    /**
     * Get the query object to be processed by dataTables.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
        $query = DB::table('users');

        return $this->applyScopes($query);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('')
                    ->addAction(['width' => '80px'])
                    ->parameters([
                        'dom'          => 'iBftlp',
                        'buttons'      => ['print', 'excel','pdf', 'test' ]
                    ]);
    }

    public function test(){
    	return 'test';
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'id',
            'name',
            'email',
            'created_at',
            'updated_at',
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'users_' . time();
    }
}

**Comment by 123bistami** [comment]
I think this error occurs becouse the pdf excel buttons are pre defined by datatables.js how can i extend this i use the scripts() method of htmlbuilder.

**Comment by Waguilar33** [comment]
I´m also trying to figure out how to implement this feature but haven't been able to. Any help will be greatly appreciated.

**Comment by yajra** [comment]
Sorry for late response. You need to add an `action=test` on your query params or the request payload on your buttons script for it to be triggered.

**Comment by Trexology** [comment]
I figured out the missing part:
for the "custom action" UI to render we need to added a new DataTable.ext.buttons.test published at /public/vendor/datatables/buttons.server-side.js

For my case I'm doing a deleteSelected custom button, my code are as followed:

`    DataTable.ext.buttons.deleteSelected = {
        className: 'buttons-delete',

        text: function (dt) {
            return '<i class="fa fa-minus"></i> ' + dt.i18n('buttons.deleteSelected', 'Delete');
        },

        action: function (e, dt, button, config) {
            window.location = window.location.href.replace(/\/+$/, "") + '?action=deleteSelected';
        }
    };`


Someone may want to include this part in the tutorial https://yajrabox.com/docs/laravel-datatables/master/buttons-custom.

This was not mentioned there

**Comment by shanitiwari01** [comment]
Some Additional Feature Here  like addColumn and search a specific column 

https://medium.com/@tiwarishani/how-to-install-yajra-on-laravel-with-a-specific-column-search-and-addcolumn-rowcolumn-b18270fafa07?sk=2ce1aeaebc7f188f1ef9e2748c427555

**Comment by HemanthThallam1993** [comment]
> Sorry for late response. You need to add an `action=test` on your query params or the request payload on your buttons script for it to be triggered.

I have followed `[https://yajrabox.com/docs/laravel-datatables/master/buttons-custom](https://yajrabox.com/docs/laravel-datatables/master/buttons-custom)`
Can we add 
 DataTable.ext.buttons.customButton = {
        className: 'buttons-csv',
    
        text: function (dt) {
            return '<i class="fa fa-download"></i> ' + dt.i18n('buttons.test', 'My button');
        },
    
        action: function (e, dt, button, config) {
            var url = _buildUrl(dt, 'customButton');
            window.location = url;
        }
    }; 
to /public/vendor/datatables/buttons.server-side.js to create custom button it is working for me actually
whi
or is there any suggestion for error Uncaught Unknown button type: customButton

**Comment by camilafaiza26** [comment]
`  ->parameters([
                        "processing" => true,
                        "autoWidth" => true,
                        "serverSide" => true,
                        
                        "buttons" => 
                        [
                            ['custom'=>'deleteSelected', 'className' => 'btn btn-danger  btn-icon', 'text' => '<span><i class="fa fa-trash"></i>&nbsp Deleted Selected</span>'],
                            ['extend'=>'csv', 'className' => 'btn btn-primary btn-icon', 'text' => '<span><i class="fa fa-file-csv"></i>&nbsp Download CSV</span>'],
                            ['extend'=>'pdf', 'className' => 'btn btn-primary btn-icon', 'text' => '<span><i class="fa fa-file-pdf"></i>&nbsp Download PDF</span>'],
                            ['extend'=>'print', 'className' => 'btn btn-primary btn-icon', 'text' => '<span><i class="fa fa-print"></i>&nbsp Print</span>'],
                            ['extend'=>'reload', 'className' => 'btn btn-primary btn-icon', 'text' => '<span><i class="fa fa-refresh"></i>&nbsp Reload</span>'],
                                    
                        ],
                        j
                        `
                        just add in parameters

**Comment by ndungudedan** [comment]
This setup works superbly for me:    
    
```
    public function html(): HtmlBuilder
    {
        return $this->builder()
            ->setTableId('your-table')
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->dom('Bfrtip')
            ->orderBy(1)
            ->selectStyleSingle()
            ->buttons([
                [
                    'text' => '<i class="fa fa-info"></i>Manual Resolve',
                    'action' => "function ( e, dt, node, config ) {
                        alert( 'Button activated' );
                    }"
                ],
                Button::make('excel'),
                Button::make('reset'),
                Button::make('reload')
            ]);
    }
```
