### ISSUE TITLE
Total of column in serverSide

### ISSUE THREAD

**Issue by dlouvard** [yajra/laravel-datatables#1315]
### Summary of problem or feature request
Example, i have columns TTC,HT, and after searching, i would like add up each column (TTC,HT) to show the total in html
Can you help me ?

### System details

- Operating System
- PHP Version 7.0
- Laravel Version 5.4
- Laravel-Datatables Version ^7.4

**Comment by yajra** [comment]
See some duplicate issues for ref. Thanks!
https://github.com/yajra/laravel-datatables/issues/809
https://github.com/yajra/laravel-datatables/issues/648

**Comment by dlouvard** [comment]
Thanks for your answer :-). It's help me
