### ISSUE TITLE
rawColumns is being ignored 

### ISSUE THREAD

**Issue by akramabdulrahman** [yajra/laravel-datatables#1316]
hello , so this code was working fine until i tried to deploy and did a composer install , 
```php
<?php
    public function dataTable()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addIndexColumn()
            ->editColumn('name', function ($project) {

                return view('link',
                    ['route' => route('endusers.org.projects.show', $project->id),
                        'label' => $project->name]);
            })
            ->editColumn('action', function ($row) {
                $modelRoute = 'endusers.org.projects';
                $id = $row->id;
                return view('endusers.layout.datatables_actions', compact('modelRoute', 'id'));
            })
            ->escapeColumns([]);
    }
```
after update it went crazy : http://imgur.com/a/Q2UAE
so i googled and found that i have to use rawColumns 
```php
<?php
    public function dataTable()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addIndexColumn()
            ->editColumn('name', function ($project) {

                return view('link',
                    ['route' => route('endusers.org.projects.show', $project->id),
                        'label' => $project->name]);
            })
            ->editColumn('action', function ($row) {
                $modelRoute = 'endusers.org.projects';
                $id = $row->id;
                return view('endusers.layout.datatables_actions', compact('modelRoute', 'id'));
            })
            ->rawColumns(['name','action']);
            ->escapeColumns([]);
    }
```
and the result stayed the same rawColumns was being ignored although $datatables->make(true) was used in the original dataTable Class so it wasnt a problem where datatables couldn't see the indices 
so i tracked the code to a specific merging area 
in Yajra\Datatables\Engines\BaseEngine 
in a function called  getColumnsDefinition

```php
<?php
 /**
     * Get columns definition.
     *
     * @return array
     */
    protected function getColumnsDefinition()
    {
        $config  = config('datatables.columns');
        $allowed = ['excess', 'escape', 'raw', 'blacklist', 'whitelist'];

        return array_merge($this->columnDef, array_only($config, $allowed));
    }
```
array_merge here is overriding $this-columnDef using values it gets from config , 
so no matter what i pass to  rawColumns the result will get it value from config and default to only ['action'] which is in convenient 

I've changed this line temporarily , to 
```php
<?php
//from
// return array_merge($this->columnDef, array_only($config, $allowed));
//to
  return array_merge_recursive($this->columnDef, array_only($config, $allowed));
```
i don't know what implication this could have , and i you could help me with a solution where i don't have to tinker with the main package . 

old me would make a local package that overrides the original package functions .
but treatments are bad , cure is awesome .

thanks in advance you're awesome 👍 
- Operating System windows 10
- PHP Version 7
- Laravel Version 5.4.30
- Laravel-Datatables Version 7.4

**Comment by yajra** [comment]
Can you please try updating again? The was a recent bug on rawColumns and I think you are using the buggy version. Sorry for the inconvenience. Thanks!

**Comment by yajra** [comment]
Latest version is 7.9.9, you can check your current version using `composer show`.

**Comment by akramabdulrahman** [comment]
yeah , it was 7.9.6 , problem is fixed 👍  
thanks 👍
