### ISSUE TITLE
how to show image in datatable column

### ISSUE THREAD

**Issue by apoorvv1** [yajra/laravel-datatables#1318]
hi sir i am try to show image in one column
like this 
`->addColumn('product_brand_logo', function ($product_brand) {
            return '<img src="{{ URL::to('uploads/users')'.$image->image.'}}" border="0" width="40" class="img-rounded" align="center" />';`

in out put it will show like this ==>{{URL::to('uploads/users')imagename.png}}

### System details

- windows 10
- PHP Version 7
- 5.3
- Laravel-Datatables Version 6.0

**Comment by royduin** [comment]
You've to make the `product_brand_logo` column raw with: `rawColumns(['product_brand_logo'])`

**Comment by apoorvv1** [comment]
thanks sir my problem solved

**Comment by thedudetechnologies** [comment]
> thanks sir my problem solved

Please Update demo here
