### ISSUE TITLE
withCount() not working with search

### ISSUE THREAD

**Issue by royduin** [yajra/laravel-datatables#1319]
Probably related to: https://github.com/yajra/laravel-datatables-buttons/issues/32

When I'm using this:
```
$products = Product::withCount(['productCategories', 'shops'])->with(['supplier' => function ($query) {
    $query->withTrashed();
}]);

return Datatables::of($products)->make(true);
```

It looks fine, but when I use the search I'm getting a SQL error:
```
{"draw":10,"recordsTotal":70,"recordsFiltered":0,"data":[],"error":"Exception Message:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'products.product_categories_count' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `products` where (LOWER(`products`.`sku`) LIKE App\\ProductCategory or LOWER(`products`.`name`) LIKE App\\Shop or LOWER(`products`.`stock`) LIKE %a% or LOWER(`products`.`product_categories_count`) LIKE %a% or LOWER(`products`.`shops_count`) LIKE %a% or (select count(1) from `suppliers` where `products`.`supplier_id` = `suppliers`.`id` and LOWER(`suppliers`.`name`) LIKE %a% and `suppliers`.`deleted_at` is null) >= 1 or LOWER(`products`.`price`) LIKE %a% or LOWER(`products`.`points`) LIKE %a%) and `products`.`deleted_at` is null and `products`.`deleted_at` is null) count_row_table)"}
```

For now, I've disabled search for those columns:
```
{ data: 'product_categories_count', searchable: false },
{ data: 'shops_count', searchable: false },
```

**Comment by yajra** [comment]
@royduin withCount is indeed not searchable atm as native SQL does not allow searching on column aliases AFAIK but sorting works. Setting it to searchable false would be an answer for the issue.

However, if you want it to be searchable, I think you have to manually write the query for it using [filterColumn](https://yajrabox.com/docs/laravel-datatables/7.0/filter-column) api.

**Comment by royduin** [comment]
Hi @yajra, thank you for the tip! I'm going to try it. Any thoughts on https://github.com/yajra/laravel-datatables-buttons/issues/32 so I can move everything out of my controller?
