### ISSUE TITLE
[Question] Multiple datatables on one view

### ISSUE THREAD

**Issue by darragh3277** [yajra/laravel-datatables#1320]
I want to display multiple datatables on the one view. The datatables are unrelated to each other.

I was hoping to setup a route for my datatables 

```
Route::resource('dashboard', 'DashboardController');
Route::prefix('datatables')->group(function(){
    Route::get('products', 'datatables\ProductController');
    Route::get('users', 'datatables\ProductController');
});
```

Then when I go to my dashboard controller I would be able to pass my datatables to my view that would use the datatables routes to fetch the data. So my dashboard controller would look something like this

```
public function index(ProductsDataTable $productDatatable, UsersDataTable $userDatatable)
{    
    $user = Auth::user();

    $products = $user->products;

    return view('admin.dashboard', compact('products', 'user', 'productDatatable', 'userDatatable'));
}
```

Obviously this isn't working but is there a way to achieve something similar or how can I get two unrelated datatables on the one page.

Is there a way of achieving something like this?

- Homestead
- php 7
- laravel 5.4
- Laravel-Datatables 7

**Comment by yajra** [comment]
Unfortunately, DataTable service class is designed to handle single instance. However, I think we can make a workaround for it by adding additional query param in our request for us to identify which class is being requested to handle the request. 

Maybe something like below:

```php
public function index(ProductsDataTable $productDatatable, UsersDataTable $userDatatable)
{    
    if (request()->has('product') {
        return $productDatatable->render('view');
    }

    if (request()->has('user') {
        return $productDatatable->render('view');
    }

    $user = Auth::user();

    $products = $user->products;

    return view('admin.dashboard', compact('products', 'user', 'productDatatable', 'userDatatable'));
}
```
