### ISSUE TITLE
datatable query from 3 tables

### ISSUE THREAD

**Issue by mramirghafari** [yajra/laravel-datatables#1321]
Hi

How can i use html tags in editColumn or addColumn?

**Comment by aliworkshop** [comment]
https://yajrabox.com/docs/laravel-datatables/master/edit-column

    return Datatables::eloquent($model)
                ->editColumn('name', 'Hi <p>{{$name}}</p>!')
                ->make(true);

**Comment by yajra** [comment]
You can render html tags by using [rawColumns](https://yajrabox.com/docs/laravel-datatables/7.0/raw-columns) api.
