### ISSUE TITLE
one simple question

### ISSUE THREAD

**Issue by ali2535** [yajra/laravel-datatables#1323]
hi yajra . 
i have a question . your datatable package is suitable for huge data ?
i have 1 milion records to show . i want show this by paginate . is your package suitable for me?
Thank you

**Comment by ali2535** [comment]
@yajra .
Jquery datatable for huge data not working. i have 1 milion record to show.

**Comment by yajra** [comment]
Yes, this package is designed specifically for this. Just make sure you are using a query and not a collection. And make sure you have the indexes and other DB stuffs in place to fine tune your SQL.
