### ISSUE TITLE
Add column with Html view

### ISSUE THREAD

**Issue by NidhiDesai11** [yajra/laravel-datatables#1326]
I am trying to add a column with html view but not getting the proper result. It shows html text in view. I need solutions

```
return Datatables::of($suppliers)
             ->add_column('name', function($suppliers){
                   return  
                  '<a  href="'.route('suppliers.view',Helper::encrypt($suppliers->id)).'"> '.$suppliers->name.'</a>' ;
            })
```

and as a result i got this...

`<a href="#"> test</a>`

**Comment by aliworkshop** [comment]
use link_to(route('suppliers.view',Helper::encrypt($suppliers->id)),$suppliers->name);

**Comment by aliworkshop** [comment]
return Datatables::of($suppliers)
             ->addColumn('name', function($supplier){
                   return link_to(route('suppliers.view',Helper::encrypt($supplier->id)),$supplier->name);
            })

**Comment by NidhiDesai11** [comment]
Solved .. thanks @aliworkshop
