### ISSUE TITLE
[7.5] Transform a model to filter guarded data with related models

### ISSUE THREAD

**Issue by pet1330** [yajra/laravel-datatables#1327]
### Summary of problem or feature request

Is it possible to filter specific columns when loading related models rather than just loading all of the models fields and eager loaded relations and their fields.

For example, if we look at the [has-many demo](http://dt54.yajrabox.com/eloquent/has-many), this is a snippet of the data it returns once the page is loaded:

```json
...

data: [{id: "1", name: "Mateo Beatty V", email: "gleichner.dorian@rolfson.com",…},…]
    0: {id: "1", name: "Mateo Beatty V", email: "gleichner.dorian@rolfson.com",…}
        created_at: "2015-07-30 08:33:32"
        deleted_at: null
        email: "gleichner.dorian@rolfson.com"
        id: "1"
        name: "Mateo Beatty V"
        posts:
            0:{id: "1", user_id: "1",…}
            created_at: "2015-07-30 08:34:15"
            id: "1"
            title: "Officia velit laboriosam expedita voluptates. Doloremque eligendi perspiciatis officiis eum repudiandae.     Corrupti odit sequi omnis quas totam sit. Quis ex similique itaque. Voluptatum fugiat qui velit et."    
            updated_at: "2016-10-18 13:56:41"
            user_id: "1"
        title: "Officia velit laboriosam exped...&lt;br&gt;Expedita quam reprehenderit mo..."
        updated_at :"2015-07-30 08:33:32"
...
```

It shows the model, as it appears in the database, but if I didn't want the server to return the created_at, deleted_at or updated_at fields, how could I remove them and still return the information I needed, including related models? i.e. 

```json
...

data: [{name: "Mateo Beatty V", email: "gleichner.dorian@rolfson.com",…},…]
    0: { name: "Mateo Beatty V", email: "gleichner.dorian@rolfson.com",…}
        email: "gleichner.dorian@rolfson.com"
        name: "Mateo Beatty V"
        posts:
            0:{,…}
            title: "Officia velit laboriosam expedita voluptates. Doloremque eligendi perspiciatis officiis eum repudiandae.     Corrupti odit sequi omnis quas totam sit. Quis ex similique itaque. Voluptatum fugiat qui velit et."    
        title: "Officia velit laboriosam exped...&lt;br&gt;Expedita quam reprehenderit mo..."
...
```

I took a look at the Transformer method of retrieving data, but I could not get this to work with a models relations. Is it possible a Transformer a model which has a `belongsTo` relationship that is also needed? (I'm basically trying to replicate the Guarded property on eloquent).

Thanks in advance! 

### System details
- Operating System: Ubuntu 14.04
- PHP Version: 7.1
- Laravel Version 5.4.33
- Laravel-Datatables Version: 7.5

**Comment by yajra** [comment]
> Is it possible to filter specific columns when loading related models rather than just loading all of the models fields and eager loaded relations and their fields.

Yes it's possible. Just make sure you select the necessary related columns that laravel uses to fetch the relation.

> It shows the model, as it appears in the database, but if I didn't want the server to return the created_at, deleted_at or updated_at fields, how could I remove them and still return the information I needed, including related models? i.e.

I think you can try using the `$hidden` attribute of the model. Just set the columns that you don't want to be returned on the response. 

You can also use [removeColumn](https://yajrabox.com/docs/laravel-datatables/7.0/remove-column) api to force dataTable to remove the columns from response.

**Comment by pet1330** [comment]
Fantastic! Thank you! I'd forgotten about hidden property on Models. Can I use the removeColumn on related models that are eager loaded? For example, can I remove the post created_at by doing something like:

```php
->removeColumn('posts.created_at')
```

Or would this have to be removed using the hidden proprieties on the eloquent model?
