### ISSUE TITLE
sorting not working in server side datatables

### ISSUE THREAD

**Issue by NidhiDesai11** [yajra/laravel-datatables#1328]
I m using yajra datatables with ajax and server side script. My search works okay but when i click on sort button nothing will happen.

**My controller**
```php
$suppliers = DB::table("suppliers")
						->select(
							'suppliers.id', 
							'suppliers.created_at', 
							'suppliers.email',
							'suppliers.status', 
							'companies.id as company_id',
							'companies.name', 
							'company_categories.title',
						 	DB::raw('
						 		(select COUNT(promotions.company_id) FROM promotions WHERE promotions.status = "pending" AND promotions.company_id = companies.id) as total')
						)
						->leftJoin('companies','companies.supplier_id','=','suppliers.id')
						->leftJoin('company_sub_categories','company_sub_categories.id','=','companies.sub_category_id')
						->leftJoin('company_categories','company_categories.id','=','company_sub_categories.company_category_id')
						->groupBy('suppliers.id', 'suppliers.created_at', 'suppliers.first_name','suppliers.last_name', 
							'suppliers.phone','suppliers.email','suppliers.status','suppliers.image_path','companies.name','companies.id','companies.name','company_categories.title')
						->orderBy('suppliers.id','DESC');

		return Datatables::of($suppliers)
            ->add_column('next_payment_date', function($suppliers){
                return date(config('constant.DATE_FORMAT'), strtotime($suppliers->created_at));
            })
           
            ->filter(function ($query) use ($request) {
            	if (@$request->search['value']) {

            		$query->where('suppliers.email', 'like', "%{$request->search['value']}%")
            		->orWhere('companies.name', 'like', "%{$request->search['value']}%")
            		->orWhere('company_categories.title', 'like', "%{$request->search['value']}%")
            		->orWhere('suppliers.id', 'like', "%{$request->search['value']}%");
            	}                
            })
         
			->make(true);


```

**my js**
```js
$(function() {
    
  oTable = $('#supplier').DataTable({
        "processing": true,
        serverSide: true,
        "pageLength": 25,
        ordering: true,
        searching: true,
        "sDom":"tpr",
        "dom": 'difrtp',
        ajax: '{!! route('get-supplier') !!}',
        columns: [
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'title', name: 'title' },
            { data: 'created_at', name: 'created_at' },
            { data: 'status', name: 'first_name' },
            { data: 'next_payment_date', name: 'next_payment_date' },
            { data: 'action', name: 'action' }
        ]
    });
}
```

**Comment by ChaosPower** [comment]
You have an order by command. It will override all sorting functions. Try removing that and comment your result.

```
->orderBy('suppliers.id','DESC');
```

**Comment by revaldopratama** [comment]
help sir ?

if($request->ajax()) {
            DB::statement(DB::raw('set @rownum=0'));
            $queryAgent = $this->queryAgentPerformance($selectedStartDateString, $selectedEndDateString);
            $agent = $queryAgent->select(DB::raw('@rownum  := @rownum  + 1 AS rownum'), 'name', 'email', 'id')
                ->where('question')
                ->orderBy('id', 'asc')->get();

            return Datatables::of($agent)->make(true);
        }

        $html = $htmlBuilder
           ->addColumn(['data' => 'rownum', 'name' => 'rownum', 'title' => 'No.'])
           ->addColumn(['data' => 'email', 'name' => 'email', 'title' => 'Agent\'s Email'])
           ->addColumn(['data' => 'total_question.0.question', 'name' => 'question', 'title' => 'Assigned Questions'])
           ->addColumn(['data' => 'total_answered.0.answered', 'name' => 'answered', 'title' => 'Answered Questions'])
           ->addColumn(['data' => 'total_unanswered.0.unanswered', 'name' => 'unanswered', 'title' => 'Unanswered Questions'])
           ->addColumn(['data' => 'total_escalated.0.escalated', 'name' => 'escalated', 'title' => 'Escalated Questions'])
           ->addColumn(['data' => 'total_spam.0.spam', 'name' => 'spam', 'title' => 'Spam Marked Questions'])
           ->addColumn(['data' => 'average_response.0.average', 'name' => 'average', 'title' => 'Avg Response Time']);

**Comment by revaldopratama** [comment]
if($request->ajax()) {
            DB::statement(DB::raw('set @rownum=0'));
            $queryAgent = $this->queryAgentPerformance($selectedStartDateString, $selectedEndDateString);
            $agent = $queryAgent->select(DB::raw('@rownum  := @rownum  + 1 AS rownum'), 'name', 'email', 'id')
                ->where('question')
                ->orderBy('id', 'asc')->get();

            return Datatables::of($agent)->make(true);
        }

        $html = $htmlBuilder
           ->addColumn(['data' => 'rownum', 'name' => 'rownum', 'title' => 'No.'])
           ->addColumn(['data' => 'email', 'name' => 'email', 'title' => 'Agent\'s Email'])
           ->addColumn(['data' => 'total_question.0.question', 'name' => 'question', 'title' => 'Assigned Questions'])
           ->addColumn(['data' => 'total_answered.0.answered', 'name' => 'answered', 'title' => 'Answered Questions'])
           ->addColumn(['data' => 'total_unanswered.0.unanswered', 'name' => 'unanswered', 'title' => 'Unanswered Questions'])
           ->addColumn(['data' => 'total_escalated.0.escalated', 'name' => 'escalated', 'title' => 'Escalated Questions'])
           ->addColumn(['data' => 'total_spam.0.spam', 'name' => 'spam', 'title' => 'Spam Marked Questions'])
           ->addColumn(['data' => 'average_response.0.average', 'name' => 'average', 'title' => 'Avg Response Time']);

**Comment by dogukanakkaya** [comment]
I was having the same problem with this query:
```
return self::select($select)
            ->where('language', app()->getLocale())
            ->leftJoin('content_translations', 'content_translations.content_id', 'contents.id')
            ->latest();
```
I changed my by adding the get() function at the end, this solved my problem also.
```
return self::select($select)
            ->where('language', app()->getLocale())
            ->leftJoin('content_translations', 'content_translations.content_id', 'contents.id')
            ->latest()
            ->get();
```
