### ISSUE TITLE
Cannot click wiki's Usage / API 

### ISSUE THREAD

**Issue by mifas** [yajra/laravel-datatables#133]
Hey, its so horrible, Please fix the links 

https://github.com/yajra/laravel-datatables/wiki

Usage / API links are redirect to wiki page

**Comment by yajra** [comment]
@mifas, WIKI page is not updated and consists of old documentations derived from the original repo (bllims version). Don't have time to update it yet and the table of contents was a planned prototype but not yet done.

**Comment by yajra** [comment]
I may not be able to find a time to update the WIKI but it's open for contribution if someone is interested.  But will try to create a better documentation sometime in the future. Thanks!
