### ISSUE TITLE
Getting request data from checkboxes fails.

### ISSUE THREAD

**Issue by nfunwigabga** [yajra/laravel-datatables#1334]
Hi,
I am trying to build advanced custom filters and so far, it is good until where I have to deal with checkboxes as shown below:

```html
<label>
    <input name="ecozones[]" type="checkbox" value ="122"> Zone 1
</label>
<label>
    <input name="ecozones[]" type="checkbox" value ="123"> Zone 2
</label>
```

and my Datatables call

```javascript
    ajax: {
            url: "{!! route('search.results') !!}",
            data: function (d) {
                var selectedEcozones = [];
                $('input:checkbox:checked.ecozones').each(function() {
                       selectedEcozones.push($(this).val());
                 });
            }
       },
   columns: [
       ....
   ]

   ....
   $('.search-form').on('submit', function(e) {
            oTable.draw();
            e.preventDefault();
     });
```

So this fails and when in inspect my query parameters, I see:
```
ecozones[]:122
ecozones[]:23
```
What am I possibly doing wrong?

### System details
I am developing on Windows 7 with WampServer

- Operating System
- PHP Version 5.6.4
- Laravel Version 5.4
- Laravel-Datatables Version 7.0

**Comment by yajra** [comment]
This is how I usually deals with advance search with forms. A more general approach that targets all the input and select box.

```js
    ajax: {
            url: "{!! route('search.results') !!}",
            data: function (d) {
                var formData = $("#form").find("input, select").serializeArray();
                $.each(formData, function(i, data){
                    d[data.name] = data.value;
                });
            }
       },
```

**Comment by yajra** [comment]
BTW, you also need to bind `selectedEcozones` back to `d` object on your script. That maybe causes your issue.

**Comment by nfunwigabga** [comment]
Thanks for the response. Yes I did bind `selectedEcozones` back to `d`...just omitted it in the code.

Also the proposed method to get all `formData` from inputs and selects strangely does not find any input with type `checkbox`. It works for `select` and `input type="text"` but not for checkboxes

**Comment by nfunwigabga** [comment]
ok I got this to work...crooked i know but it does the job :)

```javascript
var selectedEcozones = [];
$("input[name='ecozones[]']:checked").each(function(){
          selectedEcozones.push(parseInt($(this).val()));
 })
....
d.ecozones = selectedEcozones
```
