### ISSUE TITLE
Laravel Eloquent Accessor

### ISSUE THREAD

**Issue by arnoldjp57** [yajra/laravel-datatables#1341]
I have a server side datatable that uses dot notation to access eager loaded referenced model attributes .... All 99.9%. BUT, it does not "see" an accessor defined in the model. Single attributes work.
This Accessor works on blade .... $patn->full_name ....

Models
```
class Visi extends Model {
 
public function visi_patn()
  {
    return $this->hasOne('App\Patn','id','patn');
  }
}
class Patn extends Model {
 
public function getFullNameAttribute()
  {
    return $this->name . ', ' . $this->init . ' ' . $this->patn_titl->desc;
  }
 
  public function patn_titl()
  {
      return $this->hasOne('App\Base','id','titl');
  }
}
```
jQuery
```
$('#visis-table_a').DataTable({
    "serverSide":     true,
    "deferRender":    true,
    "scroller":       true,
"ajax": { "type": "POST",
      "url": '{!! url('datatables_visis') !!}',
      "data": function (d) {
        d._token = '{{csrf_token()}}';
      }
    },
columns: [
 { data: 'visi_patn.full_name', name: 'visi_patn.full_name' },
]
});
```
Controller
```
return Datatables::of( Visi::with(['visi_patn']))->make(true); 
```
Error Thrown
```
DataTables warning: table id=visis-table_a - Requested unknown parameter
```
System details

- Ubuntu16.04LTS
- PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4
- Laravel Framework 5.4.33
- dataTables-1.10.13

**Comment by yajra** [comment]
I think you need to specify it on your model via `$append` property for it to be available on response. But do note that searching/sorting will not work on if by default. You will need to use `filterColumn` api to add a custom search for full_path.

```php
class Visi extends Model {
    $appends = ['full_name']
}
```

Another workaround is to do the sorting/searching on the name column only by declaring you js like:
```js
$('#visis-table_a').DataTable({
    "serverSide":     true,
    "deferRender":    true,
    "scroller":       true,
"ajax": { "type": "POST",
      "url": '{!! url('datatables_visis') !!}',
      "data": function (d) {
        d._token = '{{csrf_token()}}';
      }
    },
columns: [
 { data: 'visi_patn.full_name', name: 'visi_patn.name' },
]
});
```

**Comment by arnoldjp57** [comment]
Hi Yajra ...
Thank you .... Works 100%
Thank you for a great product
Take Care
Arnold

**Comment by guicara** [comment]
Hello,

Thank you. But the order on the fullname column doesn't work.

`Exception Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'visi_patn.full_name' in 'order clause'`

**Comment by Artistan** [comment]
@guicara - you need to have the `name` be the actual sortable data column and `data` be the accessor attribute.
