### ISSUE TITLE
Search based on URL http://localhost/maintenance/public/admin/maintenancedamage?name=test

### ISSUE THREAD

**Issue by constantinosergiou** [yajra/laravel-datatables#1342]
### Summary of problem or feature request

Hello @yajra  is it possible to create search based on url path ?  e.g

http://localhost/maintenance/public/admin/maintenancedamage?name=test 

### System details

- Operating System
- PHP Version  >=5.6.4
- Laravel Version 5.4
- Laravel-Datatables Version ^7.3

**Comment by yajra** [comment]
Yes, just use the `filter` api like on this [demo](https://datatables.yajrabox.com/eloquent/advance-filter).

**Comment by constantinosergiou** [comment]
thank you @yajra  for the answer

you mean https://datatables.yajrabox.com/eloquent/advance-filter?name=Estrella  like that? cause it seems not working

**Comment by yajra** [comment]
What I mean is you can add a custom filter that handles additional query:

```php
->filter(function($query) {
    if (request('name') {
        $query->where('name', 'like', request('name'));
    }
}, true)
