### ISSUE TITLE
Modal open to click edit column

### ISSUE THREAD

**Issue by jsiddik** [yajra/laravel-datatables#1343]
How to display pop-up modal to click edit column to the datatables.
i use, javascript to the view file to the id of the action column.but not working.
how to pass id to the javascript and open modal .

**Comment by yajra** [comment]
You can use `drawCallback` then hook the js for your modal.

**Comment by marcelogarbin** [comment]
The post is a bit old, but I want to know how to use modal with this package, for example, I have an action button to view the register, I want that when this button is clicked open a modal with all the information of the registry.

Could you give any tips? (show some sample code...) @jsiddik @yajra 

Thank's
