### ISSUE TITLE
How to Pass Model Data Into Laravel Blade

### ISSUE THREAD

**Issue by thincmedia** [yajra/laravel-datatables#1348]
### Summary of problem or feature request

Hi there. Firstly, a million thanks for the great laravel datatables framework Yajra

I have been digging around for a solution to manipulate $posts model data in the row.details.blade.php view 

I'm still fresh on Laravel particularly datatables and I figured that yajrabox is the best datatables approach for a database driven app.

The objective is pretty straight forward but I'm struggling to get it right in the yajrabox datatables context:

Here is what I need to do.

 I have a column in model (table) storing data this way NO|YES|NO|YES

So on the  row.details.blade.php I need to explode that data and for example display icons based on whether the exploded array item is a YES or NO.

Take note that I  need to apply this on the details-template and not on the main table or row. 

I have tried to find out how to explode {{variable}} with no success. 

I have also tried parsing Posts model data to view using with, withModel and compact with no success.

Here is what I have currently:

The Eloquent Controller

```php


public function getRowDetails()
    {
            
   return view('datatables.eloquent.row-details');
    }

    public function getRowDetailsData()
    {
        $user_id=Auth::id();
        $posts = Post::select(['id', 'title', 'country', 'region', 'datatoexplode']) ->where('user_id', '=', $user_id);

        return Datatables::of($posts)->make(true);
    }




```

The Details template in blade

```html
<script id="details-template" type="text/x-handlebars-template">
    <table class="table">
        <tr>
            <td>Title:</td>
            <td>{{title}}</td>
        </tr>
        <tr>
            <td>Region:</td>
            <td>{{region}}</td>
        </tr>
        <tr>
            <td>Features:</td>
            <td>{{datatoexplode}}</td>
        </tr>
    </table>
</script>
```

My aim is to explode the {{datatoexplode}} variable so I can access the |YES|NO|YES|YES| items and iterate them and format before rendering the html output. If I can get that in PHP that would be great.

Any help will be much appreciated.

System details

- Operating System :  Mac Captein
- PHP Version: 7.
- Laravel Version 5.1.46 (LTS)
- Laravel-Datatables Version : Laravel Datatables Demo App

**Comment by lk77** [comment]
why not using addColumn method ?
like this :
```
           ->addColumn('datatoexplode', function($post){

                return view('app.post._datatoexplode', compact('post'));
            })
```
or directly exploding without returning a view if you want :
```
           ->addColumn('datatoexplode', function($post){

                return explode($post->datatoexplode, '|');
            })
```

**Comment by thincmedia** [comment]
Thanks a lot for the quick responses much appreciated. 

I see ->addColumn would be  a great option if I were implementing this on the parent row. Remember I'm implementing the explode on a variable that will go to the details row (Unless if that can still work for the child row as well) as exemplified in the code below:

```
<script id="details-template" type="text/x-handlebars-template">
    <table class="table">
        <tr>
            <td>Title:</td>
            <td>{{title}}</td>
        </tr>
        <tr>
            <td>Region:</td>
            <td>{{region}}</td>
        </tr>
        <tr>
            <td>Features:</td>
            <td>{{datatoexplode}}</td>
        </tr>
    </table>
</script>

```

I am exploring rawColumns and enum options as well. Links to any relevant resources would be immensely appreciated. 

Thanks again. I must mention that this is my first major attempt at Laravel and Datatables.

**Comment by yajra** [comment]
I think this [demo](https://datatables.yajrabox.com/eloquent/master) is what you need for ref?

**Comment by thincmedia** [comment]
Thanks again Yajra for  a lighting fast response. However instead of using the master and details tables I'm using the Row Details demo.  The one this url [Link](https://datatables.yajrabox.com/eloquent/row-details)

So it's essentially working with data from the same table and row for example: fetching user details and showing name and surname on the parent row and then showing Email and Telephone and datatoexplode  variables of the same user on the child row. And in my case I want to explode the datatoexplode variables and cast raw html for formatting. Thanks again.

**Comment by lk77** [comment]
i see, you do not want to explode the data in a more readable format but in one column, but you want to explode in multiple columns ?

**Comment by capricorn05** [comment]
hi,
is there any easy way to do something like attached.  I
![hebe app functionality 1](https://user-images.githubusercontent.com/35541677/35520193-40aa4afa-050e-11e8-9048-2199ebd4c7b8.png)
 have look at examples but cannot see anything
