### ISSUE TITLE
Order, search, pagination doesn't work

### ISSUE THREAD

**Issue by vedmant** [yajra/laravel-datatables#135]
I've installed this package on Laravel 5.1 with datatables.js version 1.10.7, but order, search, pagination don't work, it just shows first set of rows.
I checked code and see it searches for $request->get('order'), but datatables doen't pass this type of data, it passes data like iSortCol_0:0 ; sSortDir_0:desc ; iSortingCols:1 . So I can't get why this package searches for 'order' param...

Here is my code

        $('#datatable-users')
            .DataTable({
               bProcessing: true,
               bServerSide: true,
               sAjaxSource: '{{ URL::current() }}',
               order: [[0, "desc"]]
            });

Controller:

        if($request->ajax()) {

            $users = User::select(['id', 'email', 'contact_name', 'created_at']);
            return \Datatables::of($users)
                ->make();
        }

        return view('+admin.user.index');

I think it have to be some simple option or so but I thought It have to work out of the box with latest packages.

Thanks!

**Comment by yajra** [comment]
You need to use the latest API of DataTables. Your js should look something like this.

```js
$('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ URL::current() }}',
    });
```

**Comment by vedmant** [comment]
Oh, I see, thank you! It's allways simple things take too much time, didn't know that it has two apis.
