### ISSUE TITLE
Trouble With Service Implementation After Upgrading to 8.x

### ISSUE THREAD

**Issue by jvb187** [yajra/laravel-datatables#1352]
### Summary of problem or feature request

I successfully upgraded to DataTables 8.x following the upgrade guide. Now I receive a 500 Internal Server Error and the following exception when trying to display my DataTable that worked properly under 7.x:

`Type error: Argument 2 passed to App\DataTables\ManagedRouterDataTable::dataTable() must be an instance of Yajra\DataTables\DataTables, instance of Illuminate\Database\Eloquent\Builder given`

I am using the button service implementation, and followed the DataTables Buttons Changes in the upgrade guide to inject the factory using method injection...

### Code snippet of problem

```php
<?php

namespace App\DataTables;

use App\Model;
use Yajra\DataTables\DataTables;
use Yajra\DataTables\Services\DataTable;

class ModelDataTable extends DataTable
{
    public function dataTable($query, DataTables $dataTables)
    {
        return $dataTables->eloquent($query);
    }

    public function query()
    {
        return Model::query();
    }
}
```

### System details

- Operating System - Ubuntu 16.04
- PHP Version - 7.1.8
- Laravel Version - 5.4.36
- Laravel-Datatables Version - 8.0

**Comment by yajra** [comment]
Will review this one. Atm, maybe try something like:

## via datatables() helper.
```php
return datatables()->eloquent($query);
```

## via Eloquent instance.
```php
return tap(new EloquentDataTable($query))->addColumn(...)
```

**Comment by yajra** [comment]
@jvb187 were you able to force publish the config?

**Comment by yajra** [comment]
It seems like on Laravel 5.5, you need to inject first before the query.

```php
public function dataTable(DataTables $dataTables, $query) {
    ...
}
```

Will update the docs too. Thanks!

**Comment by jvb187** [comment]
Ahh yes! That works.

Thank you!

**Comment by yajra** [comment]
Docs updated. Thanks!
