### ISSUE TITLE
Using having in filterColumn callback ?

### ISSUE THREAD

**Issue by lk77** [yajra/laravel-datatables#1354]
Hello,

i have a group_concat column and i want to search on it with having clause, 
but it will not work because we are using nested where query.

how can i do ?

does it need an alternative globalSearch with only having clause instead of where clause or this is already possible somehow ?

thanks.

**Comment by yajra** [comment]
Yes, you are correct that `having` query will not work because we are using a nested query.

I think you can this manually outside the dataTables scope. Something like:

```php
$query = User::query()....;

if (request('something')) {
   $query->having(...)
}
```

**Comment by lk77** [comment]
yes, but i think it's better to do a whereIn with an having subquery.

thanks

**Comment by lk77** [comment]
here is my working solution :
```
->filterColumn('tag', function (Builder $query, $keyword) {

                $query->whereIn('collection_clip.id', $this->query()->having(\DB::raw('GROUP_CONCAT(tag.label)'), 'LIKE', ["%%$keyword%%"])->get()->pluck('id'));
            })
```
