### ISSUE TITLE
Support for Laravel 5.5

### ISSUE THREAD

**Issue by sadhakbj** [yajra/laravel-datatables#1356]
### Support for laravel 5.5

I am trying to upgrade my current system to Laravel 5.5 and I found Yajra data table is not supported for Laravel 5.5. Please add support for the latest version of the laravel.

**Comment by lk77** [comment]
hello,

it's not tagged yet, but it's supported.

**Comment by yajra** [comment]
v8 is already tagged and released. Just make sure you check the https://yajrabox.com/docs/laravel-datatables/master/upgrade for changes.

**Comment by yajra** [comment]
Might be related to this https://github.com/yajra/datatables/issues/1. 

Quick solution is to update composer.json until collective html stable version is released.

```
    "minimum-stability": "dev",
    "prefer-stable": true
```

**Comment by yajra** [comment]
Related to https://github.com/LaravelCollective/html/issues/411

**Comment by yajra** [comment]
Collective html is now released and should fix this issue.
