### ISSUE TITLE
Handling Null relationships when used as service

### ISSUE THREAD

**Issue by longestdrive** [yajra/laravel-datatables#1358]
Hi
I'm using this as a service. I can get it working for basic tables but now experimenting with relationships.

I've successfully displayed the name of a relationship but I get errors where the relationship is empty as it's expecting a value to exist.

I'm not sure how to handle this - should I modify the column? should I modify the query - confused!

Here is the query and column definition:

It works fine when a relationship exists as the data contains the relation `parent_category` and I can then access the child object. 

When the relationship does not exist I get this datatables error: `equested unknown parameter 'parent_category.name' for row 7, column 1.`

````php
public function query()
    {
        $categories = categories::query()->with('parent_category');

        return $this->applyScopes($categories);
    }

private function getColumns()
    {
        return [
            'name' => ['name' => 'name', 'data' => 'name'],
            'Parent' => ['name' => 'parent_category.name', 'data' => 'parent_category.name'],
            'rule' => ['name' => 'rule', 'data' => 'rule']
        ];
    }
````
I have tried modifying the ajax call to this but the added column makes not difference - even if I remove the 'Parent' column in the `getColumns()` function above.

````php
public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('Parent', function (categories $category) {
                return $category->parent_category ? str_limit($category->parent_category->name, 30, '...') : 'null';
            })
            ->addColumn('action', 'categories.datatables_actions')
            ->make(true);
    }
````

### System details

Laravel 5.4 using homestead VM
Using version 6 of laravel-datatables to maintain compatibility with another package InfyOm Labs laravel-generator

- Homestead 3
- PHP Version: 7
- Laravel Version: 5.4
- Laravel-Datatables Version: 6

**Comment by lk77** [comment]
i think you should use a left join instead,
this way you will get empty values.

**Comment by yajra** [comment]
I think the problem here on the scripts. You are calling the data from `parent_category.name` and should be `Parent`.

```php
private function getColumns()
    {
        return [
            'name' => ['name' => 'name', 'data' => 'name'],
            'Parent' => ['name' => 'parent_category.name'],
            'rule' => ['name' => 'rule', 'data' => 'rule']
        ];
    }
```
