### ISSUE TITLE
To many Eager Loadings

### ISSUE THREAD

**Issue by rudashi** [yajra/laravel-datatables#1359]
### Summary of problem or feature request

If I use to many eager loadings, get error below.

![Screenshot](https://pasteboard.co/images/GIkTTAA.jpg/load)

### Code snippet of problem

```php
User::query()->with(['metadata', 'roles', 'assets', 'departments', 'managers.param'])->select('users.*')
```

### System details
Windows 10 Home,
PHP 7.0.10
Laravel 5.4
LDT: 8.0

**Comment by rudashi** [comment]
Update:
The problem is not too many relationships, but with the function 
**convertToArray($row)** in file **Helper.php** line 156

It have problem with convert object from json: 
`{"doors": {"1": "1", "9": "9", "20": "20", "25": "25", "26": "26", "27": "27", "28": "28", "31": "31", "33": "33", "36": "36", "40": "40", "41": "41", "45": "45"}}`

**Comment by yajra** [comment]
@rudashi thanks for digging this further. If possible, can you please submit a PR for the patch? Thanks!

**Comment by rudashi** [comment]
Currently I have no idea how to fix it properly.

**Comment by rudashi** [comment]
More research:
First dump is for `$data` in line 159
Second for `$key` in the same line.

If we try too check `$data[$key]` everything will crash. 
When I try to check `isset( $data[$key])` I get `false`.

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/5038647/30529810-b29d5246-9c41-11e7-9504-427b2aaf89a1.JPG)
