### ISSUE TITLE
[8.x] Composer error: can't find helper.php

### ISSUE THREAD

**Issue by spinapsejt** [yajra/laravel-datatables#1361]
### Summary of problem or feature request

We're upgrading to Laravel 5.5, so I followed the upgrade guide to install Datatables 8.x. The installation worked on my local machine, but when I try to do the build on our remote server,  I get an error saying that the file "helper.php" can't be found. The remote server is similar to Heroku, so I can't access it directly, but the build happens from scratch using Composer and outputs the results to Terminal (details below).

Any ideas on how to fix the problem? Also, as a quick fix, would it be possible to remove the postInstall call that tries to load helper.php? I'm not sure if the file is needed, but if it's not, I could temporarily remove the postInstall line from the composer.json file.

Thanks for any tips.

### Code snippet of problem

The build error includes this trace:

```
Generating optimized autoload files
       > IlluminateFoundationComposerScripts::postInstall
       PHP Warning:  Uncaught ErrorException: require(/tmp/build/vendor/composer/../yajra/laravel-datatables-oracle/src/helper.php): failed to open stream: No such file or directory in /tmp/build/vendor/composer/autoload_real.php:66
       Stack trace:
       #0 /tmp/build/vendor/composer/autoload_real.php(66): ComposerUtilErrorHandler::handle(2, 'require(/tmp/bu...', '/tmp/build/vend...', 66, Array)
       #1 /tmp/build/vendor/composer/autoload_real.php(66): require()
       #2 /tmp/build/vendor/composer/autoload_real.php(56): composerRequireef6a737e6df4a66cfb4a89261a9d08a0('0b47d6d4a00ca91...', '/tmp/build/vend...')
       #3 /tmp/build/vendor/autoload.php(7): ComposerAutoloaderInitef6a737e6df4a66cfb4a89261a9d08a0::getLoader()
       #4 /tmp/build/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(17): require_once('/tmp/build/vend...')
       #5 phar:///tmp/build/.heroku/php/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): IlluminateFoundationComposerScripts::postInstall(Object(ComposerScriptEvent))
       #6 phar:///tmp/build/.heroku/ph in /tmp/build/vendor/composer/autoload_real.php on line 66
```

### System details

- Operating System: nginx 1.8.1
- PHP Version: 7.1.8
- Laravel Version: 5.5
- Laravel-Datatables Version: 8.0.1
- Composer version: 1.4.2

**Comment by spinapsejt** [comment]
I tracked this down to a problem with SourceTree. When a file changes case, SourceTree doesn't detect and track the change on the Mac. Maybe helper.php used to be called Helper.php? Anyway, the solution was:

- Delete helper.php.
- Commit.
- Add helper.php again.
- Commit.

**Comment by toilaai** [comment]
@spinapsejt 😊
I found that version 9.17 do not have this issue.
But version 9.18 still have.
