### ISSUE TITLE
"No available engine for Yajra\DataTables\DataTables"

### ISSUE THREAD

**Issue by zerocooldeveloper** [yajra/laravel-datatables#1362]
I have version 8 and laravel 5.5 I do not understand that it should be simple but it is complicating me

**Comment by artoodetoo** [comment]
Pay attention to the version. For example in v7 of this package all files and classes contain "Datatables" when v8 is "DataTables" — do you see the difference?

**Comment by yajra** [comment]
Please follow the [upgrade](https://yajrabox.com/docs/laravel-datatables/master/upgrade). It's a major bump because there are breaking changes. Thanks!
