### ISSUE TITLE
Class 'Yajra\Datatables\Engines\EloquentEngine' not found

### ISSUE THREAD

**Issue by jericopulvera** [yajra/laravel-datatables#1363]
After upgrading to 8.0

**Comment by mix5003** [comment]
please check  ```config/datatables.php``` in your project, if it exists delete it.

and if you need to config it, you may run this again
```php artisan vendor:publish --provider=Yajra\DataTables\DataTablesServiceProvider```

**Comment by u01jmg3** [comment]
You may also need to run `php artisan config:cache` to pull in the new DataTables config
