### ISSUE TITLE
Sorting, Searching, Pagination not working after other ajax request?

### ISSUE THREAD

**Issue by irfanwv** [yajra/laravel-datatables#1365]
I am using yajrabox successfully, But when we are edit record on popup and save by ajax. After that searching,sorting and pagination now working, It is returning html of the page in ajax response.
Now what should need to do?

**Comment by yajra** [comment]
When you ajax completed, you can call dataTables draw method to refresh the table.

```php
var oTable = $('#xxx').DataTable();

... ajax
success: function(response) {
   oTable.draw();
}
```
