### ISSUE TITLE
I have version 8 and laravel 5.5 I do not understand what is the problem

### ISSUE THREAD

**Issue by stojankukrika** [yajra/laravel-datatables#1366]
Hi,
Am add this in laravel 5.5 application admin layout:
```js
    <script type="text/javascript">
        var oTable;
        $(document).ready(function () {
            oTable = $('#data').DataTable({
                "processing": true,
                "serverSide": true,
                "order": [],
                "ajax": "{{ url($type) }}" + ((typeof $('#data').attr('data-id') != "undefined") ? "/" + $('#id').val() + "/" + $('#data').attr('data-id') : "/data"),
                "pagingType": "full_numbers",
            });
        });
    </script>
```
and in specific page that extends that layout:
```
 <table class="table table-hover" id="data">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Link</th>
                    <th>Actions</th>
                </tr>
                </thead>
            </table>
```
and my backend Laravel method for get data in controller looks like this:
```
 public function data()
    {
        $pages = $this->pageRepository->getAll()
            ->get()
            ->map(function ($page) {
                return [
                    'id' => $page->id,
                    'title' => $page->title,
                    'link' => $page->link,
                ];
            });
        return Datatables::make($pages)
            ->addColumn('actions', function ($page) {
                return '<a href="'.url('admin/pages/' . $page['id'] . '/edit' ).'" class="btn btn-success btn-sm" >
                                            <i class="fa fa-pencil-square-o "></i> '.trans("table.edit").'</a>
                                    <a href="'.url('admin/pages/' . $page['id'] . '/delete' ). '" class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i> '.trans("table.delete") .'</a>';
            })
            ->make();
    }
```

I don't see what is the problem but when I run it it's give me an error:
```
DataTables warning: table id=data - Requested unknown parameter '0' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4
```
But in table he shows two rows and other data is filled up but now a table rows, they don't have data but have correct number of rows like this in photo:
![pages](https://user-images.githubusercontent.com/10199584/30051255-9a713cac-9221-11e7-9320-6087e4e5ca65.png)

Please can you tell me what am doing wrong?

System details

Windows 10
PHP 7.1.7
Composer 1.5.1
Laravel 5.5
Laravel Datatables 8.*

**Comment by yajra** [comment]
Can you please inspect the ajax request and dump the error message? Also please use `->make(false);` since true is now the default value for v8. https://github.com/yajra/laravel-datatables/blob/8.0/CHANGELOG.md

**Comment by stojankukrika** [comment]
WOHOOO! That is the solution! Fast and works! TNX bro!

Can  you tell me how to add buttons for export data to csv, excel... or have some example because I didn't understand user manual about that part?

**Comment by yajra** [comment]
Here's a [demo](http://dt54.yajrabox.com/buttons/eloquent) for buttons. But I don't have demo for v8 yet.
