### ISSUE TITLE
Returns empty data while using limit and offset

### ISSUE THREAD

**Issue by jagroop** [yajra/laravel-datatables#1369]
Returns empty data while using ```limit``` and ```offset``` , even if i pass records.

```php
$project = Project::find(1);
$start = (int) request('start');
$length = (int) request('length');
$total = $project->domains()->Firstscope()->count();
if($length < 0)
{
 $length = $total;
}
$domains =$project->domains()->Firstscope()->get(); 
DataTables::of($domains)->make(true); // Working Fine

// But ..

$domains = $project->domains()->Firstscope()->limit($length)->offset($start)->get(); // have 10 records
DataTables::of($domains)->setTotalRecords($total)->make(true); // Returns empty data 
```

### System details

- Operating System : ubuntu 14..04
- PHP Version : 7.0
- Laravel Version : 5.4.34
- Laravel-Datatables Version : v8.0.1

**Comment by yajra** [comment]
Some points:

1. Do you really need to limit the query? Why not let package do the job?
2. I suggest you use query instead of collection?

```php
$project = Project::find(1);
$domains = $project->domains()->Firstscope(); 

DataTables::of($domains)->toJson(); 
```

**Comment by jagroop** [comment]
hey @yajra thanks for replying 

yes I really need limit in the query, Actually, I want to check ```domains availability``` using ```GoDaddy API``` before I serve the data in the view if I don't use limit, Bulk records will make API work ```slow``` so that's why I want to use ```limit```

```php
$project = Project::find(1);
$domains = $project->domains()->Firstscope()->limit(10)->offset(10)->get(); 
$domains = Godaddy::ins()->checkAvail($domains); // Filter through domains and get only that are available to purchase.
DataTables::of($domains)->toJson();
```

Thanks !!

**Comment by jagroop** [comment]
@yajra  any updates ??

**Comment by vanushwashere** [comment]
Same issue

**Comment by vanushwashere** [comment]
I've found a workaround, you just need to use skipPaging() method
