### ISSUE TITLE
Documentation page throwing exception

### ISSUE THREAD

**Issue by digitalredefned** [yajra/laravel-datatables#1374]
Wasn't sure how else to message you but am trying to go to the documentation page (https://yajrabox.com/docs/laravel-datatables/master) and getting the "Whoops, looks like something went wrong." message.  Thanks!

**Comment by yajra** [comment]
Upgraded to Laravel 5.5 and fixed.. Thanks!

**Comment by amir751020** [comment]
@yajra 

http://yajrabox.com/docs/laravel-datatables/master/export-columns

http://yajrabox.com/docs/laravel-datatables/master/print-columns

getting the "Whoops, looks like something went wrong." message.
Tnx bro.

**Comment by yajra** [comment]
@amir751020 where did you get that link? It might be outdated, maybe see https://yajrabox.com/docs/laravel-datatables/master/buttons-export.
