### ISSUE TITLE
Fetal Exception: Syntax error, unexpected '?'

### ISSUE THREAD

**Issue by Chintan7027** [yajra/laravel-datatables#1375]
File Name: laravel-datatables/src/DataTableAbstract.php

**Ternary condition error in Line : 602**

protected function transform($results, $processed)
    {
        if (isset($this->transformer) && class_exists('Yajra\\DataTables\\Transformers\\FractalTransformer')) {
            return resolve('datatables.transformer')->transform(
                $results,
                $this->transformer,
                **$this->serializer ?? null**
            );
        }
        return Helper::transform($processed);
    }

- Mac OS x Lion
- 7.0.0
- 5.4
- 8

**Comment by yajra** [comment]
I think is a php version error. Make sure you are using PHP 7.0++. Thanks!

**Comment by Chintan7027** [comment]
Thanks @yajra Yes i found that after upgrading php version, it's working.
