### ISSUE TITLE
how to escape the value but not the entire column?

### ISSUE THREAD

**Issue by harimayco** [yajra/laravel-datatables#1376]
I want to escape user input (data from database) then I want to edit them as html format with addColumn or editColumn.

example

```php
$datatables->addColumn('name', function ($row){
 	/* 
         $row->name has value "telkom<br />sel" 
         and I want to escape this as "telkom&lt;br /&gt;sel"
         */
 	return "<a href='" .e($row->link). "'>" .e($row->name). "</a>";
});

$datatables->rawColumns(['name']);
...
```

as you can see I'm trying to escape the value  but not the column

### Expected Result
![screenshot_20170909_150606](https://user-images.githubusercontent.com/5478980/30238435-d2c997fe-9571-11e7-83c7-96ed32523ed3.jpg)

### Actual Result
![screenshot_20170909_150809](https://user-images.githubusercontent.com/5478980/30238441-051f79f8-9572-11e7-9d71-5449fa64843b.jpg)

### Json Result
```json
data": [{
	"id": "2",
	"name": "<a href='#'>telkom<br \/>sel<\/a>",
...
```

As you can see, the rawColumns makes the entire column as html again I don't want this.
could you please help?
Thank you

**Comment by robiparvez** [comment]
for versions above 8, u have to go to config/datatables.php file....and add your column name in ....raw => ['name_of your_column']
