### ISSUE TITLE
Export Button 414 (Request-URI Too Large)

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables#1378]
### Summary
When I was getting **414 (Request-URI Too Large)** on datatable load/draw. I add the data table option `'sServerMethod' => 'POST',` and it started working. After that Search and ordering started working too.

But when I try to do export CSV/EXCEL/PDF I get **414 (Request-URI Too Large)**. I even tried to add method in ajax call `->ajax(['url'=>route($this->route),'method'=>'post'])` But still export uses `get` method.
 
Btw I am using DatatablesServiceProvider

### System details

- Ubuntu 14
- PHP 7.1
- Laravel 5.1
- Laravel-Datatables 6

**Comment by yajra** [comment]
Follow the steps I posted on this [blog](https://yajrabox.com/blog/datatables-and-long-url) to shorten the url. If you are using buttons plugin v2.0, you can use `minifiedAjax()` which basically uses the same technique on the blog.

**Comment by karmendra** [comment]
Thanks for this, one thing I noted is when I copied the script in blog my column search and ordering stopped working. for this I changed the code a bit,

       function minifiedAjax(data) {
            for (var i = 0, len = data.columns.length; i < len; i++) {
                if (! data.columns[i].search.value) delete data.columns[i].search;
                if (data.columns[i].searchable === true && (data.columns[i].search === undefined || data.columns[i].search === "")) delete data.columns[i].searchable;
                if (data.columns[i].orderable === false) delete data.columns[i].orderable;
                if (data.columns[i].data === data.columns[i].name) delete data.columns[i].name;
            }
            delete data.search.regex;
        }

I am using `yajra/laravel-datatables-oracle ^6.0`
Regards,

**Comment by poovarasudev** [comment]
@yajra I'm also facing this same issue in Export option. Look the blog link you have shared was now available now - getting 404 error. Could you please help me to fix this issue?

@karmendra Kindly let me know how did you fixed this issue

**Comment by mikesocorecc** [comment]
@poovarasudev  I have the same problem, have you found any solution?

**Comment by yajra** [comment]
@mikesocorecc Try using `postExcel` or `postCsv` button instead
