### ISSUE TITLE
Search on edited column not working properly

### ISSUE THREAD

**Issue by sinandomeng** [yajra/laravel-datatables#1379]
### Edited column of status not working on search

I have status field on my users table. 1 => enabled, 2 => disabled
I don't wanted to display 1 on my table if the user is enabled or 2 if not
I created a Helper (setter and getter)

### Code snippet of problem
```php
return Datatables::of($salary_data)
    ->editColumn('status', function ($data) { return Helper::get_status($data->status); })
    ->make(true);
```
where the get_proper_data returns string
```php
public static function set_status()
{
    return array(
        1 => 'Enabled',
        2 => 'Disabled'
    );
}
```
on my table I have now Enabled and Disabled but once I search using 'Enabled' or 'Disabled', it returns nothing..

### System details

- Operating System -Linux Hosting
- PHP Version - 7.0
- Laravel Version - 5.3
- Laravel-Datatables Version - 6.x

**Comment by yajra** [comment]
You also need to transform the search on the query level. Try using [filterColumn](https://yajrabox.com/docs/laravel-datatables/master/filter-column) to modify how the package will search on the edited column.

**Comment by smplyjr** [comment]
I only have integer value on my table how could I concatenate it to be able to get the proper data? I try to use sql query replace but it did not work..
