### ISSUE TITLE
Redraw datatable if viewed lines is updated

### ISSUE THREAD

**Issue by legreco** [yajra/laravel-datatables#1384]
Hi, my problem is simple. 
Let say we have a server paginated list of employees displayed in a datatable. In the current page we have employees with id 5 to id 10. Someone else update employee with id 9. I fire the event EmployeeWasUpdated that i broadcast on a channel called 'employee_updates'. On the view (containing list of employees) I listen to this channel and and i receive the updated employe. Now what i want is
if the updated employee is actually displayed in the datatable redraw it, if not do nothing.

PS My English is bad, 

### System details

- Operating System Windows 10
- PHP Version 5.6
- Laravel Version 5.4
- Laravel-Datatables Version 7.9

### Other infos
- Pusher
- Vue js 2
- Laravel Echo

**Comment by yajra** [comment]
Just use `oTable.draw(false)` when the condition passes to retain the current page.

**Comment by legreco** [comment]
Hi I solved this this way.
in my controller i set the RowId
`
  ->setRowId(function ($movement) {
                    return $movement->id;
                })
`
in my view i listen for the event MovementCompleted
event data come this way:
`
{
  "movement": {
    "id": "3c3f66b0-97e7-11e7-84b9-534c7ed61dff",
    "movement_type_id": "CONTRACT_RENEWAL",
    "movement_status_id": "COMPLETED",
    "employee_id": "f54890c0-97c9-11e7-9bd1-f90f92aa5d7d"
}
}
`
`
  Echo.channel('movements')
                        .listen('.App.Events.movements.MovementCompleted', (e) => {
                         
 instance.table.rows().every( function ( rowIdx, tableLoop, rowLoop ) {
//Loop to search if the completed movement is currently displayed in the actuel page
                                var data = this.data();

                                if(data.DT_RowId==e.movement.id)
                                {
                                    alert('The completed movement is currently displayed');
                                    instance.table.draw();
                                }


                            } );


                        });
                },
`
