### ISSUE TITLE
Error 500 in GET

### ISSUE THREAD

**Issue by vitormicillo** [yajra/laravel-datatables#1385]
Hi Yajra

After update my laravel to 5.5 and you laravel-datatable to version 8
my listings do not work anymore.
The error I can identify is that provided by the console

![image](https://user-images.githubusercontent.com/1921806/30371968-88f23858-987c-11e7-919f-ac78b4c804bb.png)

Before updating everything worked normally

- Operating System: Linux
- PHP Version: 7.0.20
- Laravel Version: 5.5
- Laravel-Datatables Version: 8

**Comment by yajra** [comment]
Were you able to follow the [upgrade guide](https://yajrabox.com/docs/laravel-datatables/master/upgrade)? There are breaking changes on v8 so please check. Thanks!

**Comment by faazlila** [comment]
hi yajra , i have some problem search , some times i have search field i have error, ajax error datatables\tn 7.i inspect on my browser chrome.  and result like image and above: 
![image](https://user-images.githubusercontent.com/31990500/30484408-80655010-9a54-11e7-8f1f-51b4c46ac632.png)
my project on laravel 5.2, and a tried to php keygenerate, and clear config but error sometimes.
please solution, thnks
