### ISSUE TITLE
  [Symfony\Component\Debug\Exception\FatalErrorException]   Class 'Yajra\DataTables\DataTablesServiceProvider' not found

### ISSUE THREAD

**Issue by subodhrawat3344** [yajra/laravel-datatables#1387]
i am using laravel 5.3 
i have occur this problem when i publish vendor , please help .

**Comment by yajra** [comment]
Please follow this [documentation](https://yajrabox.com/docs/laravel-datatables/7.0) for Laravel 5.3.

`Yajra\DataTables\DataTablesServiceProvider` is for Laravel 5.4++ version.

`Yajra\Datatables\DatatablesServiceProvider` is 5.3 and below. The diff is on the namespace and spelling. Thanks!
