### ISSUE TITLE
Method setTransformer does not exist.

### ISSUE THREAD

**Issue by slion0725** [yajra/laravel-datatables#1388]
```php
        $model = User::query();
        return DataTables::eloquent($model)
        ->setTransformer(new UserTransformer)
        ->toJson();
```
Method setTransformer does not exist.

- Operating System
- PHP Version 7.1.8
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
Were you able to install [laravel-datatables-fractal](https://github.com/yajra/laravel-datatables-fractal)? It is now extracted to own plugin.

**Comment by slion0725** [comment]
Thanks, You done my job
