### ISSUE TITLE
Searchable merge columns

### ISSUE THREAD

**Issue by ninoypaninoy** [yajra/laravel-datatables#1389]
I have this code below but it can only search for last_name.
I want to search for first_name, middle_name, and name_extension also, how can I do that?
Thanks!

```js
{
         `// column definitions`
         `mData: 'last_name',`
         `"aTargets": [ 1 ],`
         `mRender:function ( data, type, row ) {`
             `// concatenate name`                        
             `return row.last_name+' '+row.name_extension+', '+row.first_name+' '+row.middle_name;`
         `},`
         `searchable: true,`
         `sortable: true,`
         `visible: true,`  
},
```

**Comment by yajra** [comment]
Try this trick, add a hidden column `first_name` on your columns and it will be included in search.

```js
columns: [
{data: first_name, visible: false},
{data: last_name},
]
```

**Comment by ninoypaninoy** [comment]
Thanks for your reply but still can't search for first_name.

**Comment by ninoypaninoy** [comment]
It's working! I changed my `aoColumnDefs: []` to `columns: []` and `mData` to `data` and follow the that trick. Thanks!
