### ISSUE TITLE
Class 'Yajra\Datatables\Services\DataTable' not found

### ISSUE THREAD

**Issue by mirnasamaan** [yajra/laravel-datatables#1390]
### System details

- Operating System: Windows 10
- PHP Version: 5.6.4
- Laravel Version: 5.4.*
- Laravel-Datatables Version: 1.0

**Comment by the94air** [comment]
Try Yajra\DataTables\Services\DataTable
---------------^

**Comment by waleedyounis** [comment]
Still not working

**Comment by the94air** [comment]
What version are you using?

**Comment by yajra** [comment]
@waleedyounis were you able to install the buttons plugin? 
https://github.com/yajra/laravel-datatables-buttons
https://yajrabox.com/docs/laravel-datatables/master/buttons-installation

**Comment by waleedyounis** [comment]
Yes. I re-installed the plugin along with the buttons plugin and now it's working.
Thanks a lot for the help

**Comment by Hamzeh-Jamalon** [comment]
@the94air Thanks. your the best.

**Comment by the94air** [comment]
I am glad it helped.

**Comment by khaleo** [comment]
I'm having a  same problem when using Yajra datatables with laravel 5.6. project. It gives me an error "Class 'Yajra\Datatables\Services\DataTable' not found"
System details
Operating System: Windows 10
PHP Version: 7.2.4
Laravel Version: 5.6.*

following the guide upgrade I have this other error in my terminal
"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yajra/laravel-datatables-oracle 7.0 -> satisfiable by yajra/laravel-datatables-oracle[v7.0.0].
    - Conclusion: remove laravel/framework v5.6.38
    - Conclusion: don't install laravel/framework v5.6.38
    - yajra/laravel-datatables-oracle v7.0.0 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9]  "

how to resolve it ????

**Comment by the94air** [comment]
The package name space is not correct
`Yajra\Data(t)ables\` to `Yajra\Data(T)ables\`
Checkout my answer [above](https://github.com/yajra/laravel-datatables/issues/1390#issuecomment-329571230).

**Comment by khaleo** [comment]
thk u but i don't understand.Explain plz what i have to do in my laravel project (laravel 5.6)

**Comment by shah1827** [comment]
same error 
ubuntu 16.04 version

**Comment by SavanThakkar** [comment]
> Try `Yajra\DataTables\Services\DataTable`
> ----------------^
> `Datatables` to `DataTables`
> See the [upgrade guide](https://yajrabox.com/docs/laravel-datatables/master/upgrade)

Link doesn't seems to be accessible. Can you please check it?
