### ISSUE TITLE
Datatables version 8 install issue

### ISSUE THREAD

**Issue by julianscreawn** [yajra/laravel-datatables#1391]
Hi I am running Laravel 5.4 , and I upgraded to datatables V 7 successfully.  I tried to upgrade from datatables 7 to datatables 8 but get the following error:

> Problem 1
>     - yajra/laravel-datatables-html v1.4.1 requires yajra/laravel-datatables-oracle 7.* -> satisfiable by yajra/laravel-datatables-oracle[7.0.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.1.4, v7.10.0, v7.10.1, v7.2.0, v7.2.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2, v7.9.3, v7.9.4, v7.9.5, v7.9.6, v7.9.7, v7.9.8, v7.9.9] but these conflict with your requirements or minimum-stability.
>     - yajra/laravel-datatables-html v1.4.1 requires yajra/laravel-datatables-oracle 7.* -> satisfiable by yajra/laravel-datatables-oracle[7.0.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.1.4, v7.10.0, v7.10.1, v7.2.0, v7.2.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2, v7.9.3, v7.9.4, v7.9.5, v7.9.6, v7.9.7, v7.9.8, v7.9.9] but these conflict with your requirements or minimum-stability.
>     - yajra/laravel-datatables-html v1.4.1 requires yajra/laravel-datatables-oracle 7.* -> satisfiable by yajra/laravel-datatables-oracle[7.0.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.1.4, v7.10.0, v7.10.1, v7.2.0, v7.2.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2, v7.9.3, v7.9.4, v7.9.5, v7.9.6, v7.9.7, v7.9.8, v7.9.9] but these conflict with your requirements or minimum-stability.
>     - Installation request for yajra/laravel-datatables-html (locked at v1.4.1, required as ^1.0) -> satisfiable by yajra/laravel-datatables-html[v1.4.1].

When I run composer show, it shows I have version 7 of datatables installed:
yajra/laravel-datatables-html       v1.4.1  Laravel DataTables HTML builder plugin for Laravel 5.4+.
yajra/laravel-datatables-oracle     v7.10.1 jQuery DataTables API for Laravel 4|5

Thanks

**Comment by yajra** [comment]
Please see the [upgrade guide](https://yajrabox.com/docs/laravel-datatables/master/upgrade).

Or remove all datatables package on your composer and install [`laravel-datatables:^1.0`](https://github.com/yajra/datatables)
