### ISSUE TITLE
There are no commands defined in the "datatables" namespace.

### ISSUE THREAD

**Issue by esilan** [yajra/laravel-datatables#1392]
I face the error 

**"[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "datatables" namespace."** 

when trying to run this command 

**php artisan datatables:make User**

I follow the instruction written here
@http://yajrabox.com/docs/laravel-datatables/master/buttons-config

### System details

- Window 10
- PHP Version 7.0.10
- Laravel Version 5.4

**Comment by yajra** [comment]
You need to install the buttons plugin first @http://yajrabox.com/docs/laravel-datatables/master/buttons-installation.

**Comment by kiranajudiya** [comment]
@yajra still getting error after publishing and ButtonsServiceProvider add to provider.

- Window 10
- PHP Version 7.3.20
- Laravel Version 7.22.2

![Yajra Table Error](https://user-images.githubusercontent.com/17902344/89715764-caa7ca00-d9c5-11ea-9c4c-a1c165c0a11c.png)

**Comment by awalawashington** [comment]
Root composer.json requires yajra/laravel-datatables-buttons 4.0 -> satisfiable by yajra/laravel-datatables-buttons[v4.0.0].
