### ISSUE TITLE
dynamic use variable

### ISSUE THREAD

**Issue by caturseptian** [yajra/laravel-datatables#1393]
### Summary of problem or feature request

How to do so the data return dynamic?

### Code snippet of problem

        $administrations = Administration::all();
        $balance = 0;

        return Datatables::of($administrations)
            ->addColumn('balance', function ($administration) use ($balance) {
                if ($administration->status == 'Debit') {
                    $balance = $balance + $administration->amount;
                } else {
                    $balance = $balance - $administration->amount;
                }
                return $balance;
            })
            ->make(true);`

*******************

balance is not totaled or reduced because value of balance is 0, so return data obtained from amount

### System details

- Operating System: Mac
- PHP Version: 7
- Laravel Version: 5.5
- Laravel-Datatables Version: 8.0

Please, help me...
Thanks before

**Comment by yajra** [comment]
You need to pass balance variable by reference.

```php
    $administrations = Administration::all();
    $balance = 0;

    return Datatables::of($administrations)
        ->addColumn('balance', function ($administration) use (&$balance) {
            if ($administration->status == 'Debit') {
                $balance = $balance + $administration->amount;
            } else {
                $balance = $balance - $administration->amount;
            }
            return $balance;
        })
        ->make(true);`
```

**Comment by caturseptian** [comment]
work, but returned wrong answer
![image](https://user-images.githubusercontent.com/13551379/30547809-967ac746-9cba-11e7-8d1b-276096b7dae7.png)

**Comment by yajra** [comment]
@caturseptian I think this would be done better on the `SQL` level. Try using subqueries.
