### ISSUE TITLE
Server Side Buttons Excel Export very slow

### ISSUE THREAD

**Issue by andrasgalli** [yajra/laravel-datatables#1397]
Hi Yajra!

I have the following problem: I'm using a mysql stored procedure to display the results for datatables. Everything works fine, until I hit the Export/Excel button. With 4-5000 records it took 20-25 sec to get the file. But with 14.000 records it does not work, i suffer from php timeot (max execution time is 180 sec)
The Stored procedure itself runs and gives back the results within 1.2 sec...

```php
public function query() {
//.....
//setting up filters...
//.....
$sql = 'CALL `proc_reservation_list`(' . 
            $this->language_id . ', \'' . $filter_reservation_date . '\', ' . $filter_room_id . ', 
            ' . $filter_payment_id . ', \'' . $filter_contact_name . '\', ' . $filter_reservation_id . ', 
            \'' . $filter_contact_email . '\', \'' . $filter_contact_phone . '\', \'' . $order_field . '\', \'' . $order_direction . '\', 
            \'"active", "inprogress", "completed"\', ' . $location_id . ')';
        Log::debug($sql);
        
        $result = collect(\DB::select($sql));
        return $result;
}

public function ajax() {
  $result = $this->datatables
            ->of($this->query());
  return $result->make(true);
}
```

- Operating System: Windows 10
- PHP Version: 7.1.5
- Laravel Version: 5.3
- Laravel-Datatables Version: 6.24.4

**Comment by yajra** [comment]
You can override the `excel` method and maybe use chunk when exporting large recordset. Or better ask `laravel-excel` repo for a better response on how to handle large records? Thanks!
