### ISSUE TITLE
Overriding Limit

### ISSUE THREAD

**Issue by valluminarias** [yajra/laravel-datatables#1398]
### Summary of problem or feature request

Is there any way to override or customize the query limit just like editing columns?

### Code snippet of problem
Like:
```
$dt = DataTables::of($query)
         ->limit(function($query) {
               return return $query->skip(10)->take(100);
         });
```

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
I think this PR https://github.com/yajra/laravel-datatables/pull/1338 is what you need? Thanks!
