### ISSUE TITLE
withTrashed() does not exist on upgrading to V8.0

### ISSUE THREAD

**Issue by chaitalipatil** [yajra/laravel-datatables#1400]
### Summary of problem
On upgrading laravel5.5 and laravel-datatable 8.0 I am facing issues in withTrashed() method.
It was mention on upgrade guide that  'withTrashed' and 'onlyTrashed' api are removed.

So now how to use SoftDelete().

Please give a demo example.

### System details

- Operating System  Win 10
- PHP Version  V7.0.0
- Laravel Version V5.5
- Laravel-Datatables Version V8.0

**Comment by rollercontainer** [comment]
Got stuck there too. I just removed the "->withTrashed()" after "Datatables::eloquent($model)". 

`
$model = Product::withTrashed();
return Datatables::eloquent($model)
            ->editColumn(`

**Comment by emilas44** [comment]
Same problem...
```
            $model = $this->model::query()->withTrashed();

            return DataTables::eloquent($model)
                ->withTrashed()
                ->make(true);
```
throws this error message:
```
exception: "ErrorException"
file: "/var/www/html/projects/...php"
line: 41
message: "Non-static method Yajra\DataTables\DataTables::eloquent() should not be called statically"
```
