### ISSUE TITLE
Documentation website not accessible

### ISSUE THREAD

**Issue by seilide** [yajra/laravel-datatables#1403]
Documentation website not accessible. Perhaps the documentation pages can be uploaded to github or some alternative where it is not dependent on yajrabox.com being up.

**Comment by the94air** [comment]
Good Idea. GitHub pages usually never goes down.

**Comment by yajra** [comment]
The docs are already on github but rendered on my site for a cleaner view. See https://github.com/yajra/laravel-datatables-docs.

Anyways, my hosting server just got suspended which causes the downtime. Will try to resolve it the soonest possible time. Thanks!

**Comment by thiagomagero** [comment]
@yajra , If you need help, please contact us. Your documentation is very useful to all of us. What is the problem with your server? Too many hits? Financially, is there anything that can be done? When bandwidth do you need?

**Comment by seilide** [comment]
Sorry I missed your laravel-datatables-docs repo. I looked but did not see. Excellent work, by the way.

**Comment by yajra** [comment]
Thank you! Please see #2223.
