### ISSUE TITLE
Malformed UTF-8 characters

### ISSUE THREAD

**Issue by mikerockett** [yajra/laravel-datatables#1405]
### Summary of problem or feature request

I'm receiving the following error when JSON is being compiled for my model:

> Exception Message: Malformed UTF-8 characters, possibly incorrectly encoded

If I remove `rawColumns`, it works, but HTML is no longer formatted as it is escaped. So far as I can tell, my modifications are correct. If I remove the modifications, the error persists. Could this be a bug with `rawColumns`?

### Code snippet of problem

```php
return datatables()->of($model)
    ->editColumn('n', function ($model) {
        return "<a href=\"/m/v/{$model->id}\">{$model->n}</a>";
    })
    ->editColumn('t', function ($model) {
        return (!$model->t && $model->m)
            ? $model->m
            : $model->t;
    })
    ->editColumn('e', function ($model) {
        if (!$model->e) {
            return '-';
        }
        $cn= $model->ca ?? $model->n;
        return "<a href=\"mailto:{$cn} <{$model->e}>\">{$model->e}</a>";
    })
    ->rawColumns(['n', 'e'])
    ->make(true); // or toJson()
```

### System details

- Windows 10
- PHP 7.1
- Laravel 5.5
- Laravel Datatables Oracle 8.0
- Datatables 1.10.16 (not that it matters, because the error is server-side)

**Comment by mikerockett** [comment]
I've decided to let the browser handle this kind of rendering, which is quite logical anyway. With that said, please look into this nonetheless.

**Comment by yajra** [comment]
Have you tried adjusting the json response options? Below is the default config we have.

```php
    'json'           => [
        'header'  => [],
        'options' => 0,
    ],
```

**Comment by mikerockett** [comment]
Sorry, I somehow missed this...

I'd need to revert my code to test it out, which isn't an option at the moment due to a large front-end codebase and pressure for time. But I'll try on a blank install to see if it persists.

**Comment by arun07as** [comment]
Setting 
```
'json'           => [
    'header'  => [],
    'options' => JSON_INVALID_UTF8_IGNORE,
],
```
in `config\datatables.php` fixed the issue for me
