### ISSUE TITLE
HTML code is not displayed in Laravel 5.5 

### ISSUE THREAD

**Issue by kaled-999** [yajra/laravel-datatables#1406]
### Summary of problem or feature request
The code works fine, but HTML code is displayed as text

### Code snippet of problem

> 

> 

```php
public function datatab(User $user)
    {

        $users = $user->all();
        return Datatables::of($users)
            ->editColumn('name', function ($model) {
                return '<a href="'.url('/data/users/' . $model->id . '/edit').'">'.$model->name.'</a>';
            })
            ->make(true);

    }
```

### System details

Windows 10 - Operating System
7.1.8 - PHP Version
5.5 - Laravel Version
8.0 - Laravel-Datatables Version

**Comment by yajra** [comment]
You need to use `->rawColumns(['name', 'etc'])`.

**Comment by waltersgp** [comment]
**CONTROLLER**

`return Datatables::of($contas)
            ->addColumn('edit', function ($contas) {
            return '<div class="text-center">
        				<a href="'.route('receber.editar', $contas->id).'" class="btn btn-primary" data-toggle="tooltip" title="Editar a Conta!">Editar</a>
            		</div>';
            })            
            ->addColumn('action', function ($contas) {
            return '<div class="text-center">
	            		<form method="POST" action="'.route('receber.conta', $contas->id).'">
						'. method_field('PUT') .' '. csrf_field() .'
						<input type="hidden" name="id" value="'. $contas->id .'">
						<input class="form-control" type="date" pickdate name="pagamento">
	            		<button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Receber</button>
	            		</form>
            		</div>';
            })            
        	->rawColumns(['edit', 'action'])
            ->editColumn('emissao', function ($contas) {
                return $contas->emissao ? with(new Carbon($contas->emissao))->format('d/m/Y') : '';
            })
            ->editColumn('vencimento', function ($contas) {
                return $contas->vencimento ? with(new Carbon($contas->vencimento))->format('d/m/Y') : '';;
            })
            ->make(true);    	`

**BLADE TEMPLATE** 

`columns: [
            { data: 'raw', name: 'raw' }, //<<<< I do not know what to put here.
            // { data: 'action', name: 'action', orderable: false, searchable: true }
        ],`

I have this code above, I can not include it in the table of the blade template, could you tell me how to include the two columns in the same row.

**thank you.**
