### ISSUE TITLE
Multi Datatable with using only one model

### ISSUE THREAD

**Issue by jamesriady** [yajra/laravel-datatables#1409]
This is My controller

```php
        $languages = Language::where('IsActive', 1)->get();
        if($request->ajax()) {  
                $post = Post::where('LanguageID', $request->input('LanguageID')));
            return Datatables::of($post)
            ->addColumn('action', function($post){
                return '<a id="edit" class="btn btn-info" 
                                     href="post/' . $post->id . '/edit">
                                        <i class="glyphicon glyphicon-edit icon-white"></i>
                                        Edit
                                    </a>
                                    <button type="button" class="btn btn-danger"
                                     onclick="checkDelete('.$post->id.', this);" 
                                     data-token="{{ csrf_token() }}">
                                        <i class="glyphicon glyphicon-trash icon-white"></i>
                                        Delete
                                    </button>';
                                })
            ->make(true);
        } 
        return view('pages.back-end.lists.post')->with('languages', $languages);  
```

This is my view
[https://i.stack.imgur.com/TbMHv.png](https://i.stack.imgur.com/TbMHv.png)

This is my yajra
```js
  $('.tabPost').each(function(){
    var lang_id = $(this).attr('id');
    console.log(lang_id);
    var oTable = $("#data-post" + lang_id).DataTable({
      processing: true,
      serverSide: true,
      ajax:{
        url: "{{ url("post") }}",
        data: function(d) {
          d.LanguageID = lang_id
        }
      },
      columns: [
          { data: 'PostDate', name: 'PostDate'},
          { data: 'PostTitle', name: 'PostTitle' },
          { data: 'PostSlug', name: 'PostTitle' },
          { data: 'action', name: 'action'}
      ]
    });

    $('#'+lang_id).on('click', function(e){
      oTable.draw();
      e.preventDefault();
    });

  }); 
```
I want to make my table has tab panel.. So, if I choose tab with language id 1, then display all data with language id 1, if I choose tab with language id 2, then display all data with language 2. Can I do like that in Yajra?
### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
I think your code is fine and just need a little tweak. Try something like:

```php
if ($request->ajax()) {  
    $post = Post::where('LanguageID', request('languageid'));
    
    return Datatables::of($post)
        ->addColumn('action', function($post){
            return '<a id="edit" class="btn btn-info" 
                                 href="post/' . $post->id . '/edit">
                                    <i class="glyphicon glyphicon-edit icon-white"></i>
                                    Edit
                                </a>
                                <button type="button" class="btn btn-danger"
                                 onclick="checkDelete('.$post->id.', this);" 
                                 data-token="{{ csrf_token() }}">
                                    <i class="glyphicon glyphicon-trash icon-white"></i>
                                    Delete
                                </button>';
                            })
        ->make(true);
} 

return view('pages.back-end.lists.post')->with('languages', $languages); 
```

The trick is to just include the languageid and use it to filter the results.

**Comment by jamesriady** [comment]
`$post = Post::where('LanguageID', request('languageid')); //does not work`
So, I am using the way like this `$post = Post::where('LanguageID', $request->has('LanguageID'));`
But, when i click Indonesia, it shows all data where LanguageID = Indonesia, But when I click the other language, it does not show anything.. why? @yajra

**Comment by yajra** [comment]
Maybe the languageid is not changing on your script? Try dumping the inputs to see the url query params. Also, try using this script:

```js
ajax:{
                 url: "{{ url("post") }}",
                 data: function(d) {
d.languageid = languageid;
etc...
}

           },
```

**Comment by jamesriady** [comment]
Still get the same result.. how can I do dump in ajax(yajra datatable)

**Comment by yajra** [comment]
Inspect the ajax request using chrome dev tools or firebug. Enable APP_DEBUG, and all inputs and queries will be included in the ajax response.

**Comment by jamesriady** [comment]
![abc](https://user-images.githubusercontent.com/20609442/30945444-90a2e93c-a428-11e7-8a75-dd13640ef227.png)

I got result like this.. my data only show in Indonesia tab

**Comment by yajra** [comment]
Did you create a separate script for each tab? There should be 2 ajax request. 1 for Indonesia & 1 for mandarin where languageid is diff.

**Comment by yajra** [comment]
Does the languageid changes on each tab? The issue here is on your script. There should be two ajax request to fetch the data for each language

**Comment by jamesriady** [comment]
The languageid on tab headerchanged when you click.. but, in tab panel, I don't know how to check if the languageid changes or not

**Comment by yajra** [comment]
You need to redraw the table too when you click the tab panel to reload the data with proper language id.

**Comment by jamesriady** [comment]
![zzz](https://user-images.githubusercontent.com/20609442/30945865-d18aa8a2-a42a-11e7-880e-88f05a5e4363.png)

There is id = Lang-1 and Lang 3, but the content is different

**Comment by jamesriady** [comment]
how to redraw the table? can you give me a sample?

**Comment by yajra** [comment]
```js
$(function(languageid){
    var oTable = $("#data-post").DataTable({
      processing: true,
      serverSide: true,
      ajax:{
                 url: "{{ url("post") }}",
                 data:{ _token: "{{csrf_token()}}", languageid: languageid}

           },
      columns: [
          { data: 'PostDate', name: 'PostDate'},
          { data: 'PostTitle', name: 'PostTitle' },
          { data: 'PostSlug', name: 'PostTitle' },
          { data: 'action', name: 'action'}
      ]
    });
  }); 
```

```js
// onclick tab
oTable.draw();
```

**Comment by jamesriady** [comment]
I change my tab without using onclick.. so, where should I put the oTable.draw();?

**Comment by jamesriady** [comment]
I am sure that maybe the problem is in my script.. but I don't know how to fix it.. I have used `oTable.draw();` on my onclick tab, but It only sends ajax request on tab 1, and it does not work on the other tab

**Comment by yajra** [comment]
In my opinion this would be easier if you use 2 scripts for both table than listening on tab click event.

```js
$("#indonesia").DataTable({
      processing: true,
      serverSide: true,
      ajax:{
                 url: "{{ url("post") }}",
                 data:{ languageid: 1}

           },
      columns: [
          { data: 'PostDate', name: 'PostDate'},
          { data: 'PostTitle', name: 'PostTitle' },
          { data: 'PostSlug', name: 'PostTitle' },
          { data: 'action', name: 'action'}
      ]
    });

$("#mandarin").DataTable({
      processing: true,
      serverSide: true,
      ajax:{
                 url: "{{ url("post") }}",
                 data:{ languageid: 2}
           },
      columns: [
          { data: 'PostDate', name: 'PostDate'},
          { data: 'PostTitle', name: 'PostTitle' },
          { data: 'PostSlug', name: 'PostTitle' },
          { data: 'action', name: 'action'}
      ]
    });
```

**Comment by jamesriady** [comment]
I have just tried them but I think that will make my datatable not dynamic.. how if I have more than 2 languages.. and I tried the way like you give me... but two of my table show the data with language id = 1.. I think that the problem is in controller 
`$post = Post::where('LanguageID', $request->has('LanguageID')); //this is the problem`
It always return LanguageID = Indonesia...

**Comment by jamesriady** [comment]
I know now why I only get Indonesia data.. because `$request->has('LanguageID');` will return boolean.. so I only get 1..

**Comment by jamesriady** [comment]
I have found what I need and I have posted the answer.. I hope my issue can help for others
