### ISSUE TITLE
Adding fixed secondary column sort to prevent pagination issues

### ISSUE THREAD

**Issue by trevorgehman** [yajra/laravel-datatables#141]
I have a unique issue regarding sorting and pagination. I have a large dummy dataset sorting on a DATETIME column where most rows have the same exact value. 

What I've discovered is that for this case, the data coming from the database is in a nearly random order each time the query is run. The result is that pagination is unreliable, since the order is not maintained while cycling pages.

I believe this can be fixed/prevented by supplying a permanent secondary sort based on the row ID. I tried adding it to the query using `$query->orderBy('id','DESC');` but this merely overwrites the sorting. Is there an easy way to add a secondary sort to the query?

**Comment by yajra** [comment]
ATM, there is no way of adding a secondary column sort on server side as far as I know. But have you tried using DT's `orderFixed` option? http://datatables.net/reference/option/orderFixed. Haven't tried this yet but I think it may work.

On the other hand, I think we can add a new feature like `addOrder` to add nth ordering. Will check this possibility on my free time. Thanks!

**Comment by trevorgehman** [comment]
Thank you, @yajra. Yes, I looked into that feature, but unfortunately this would require a column be fixed as a post sort, which won't work since all the visible columns in the table I need to be able to adjust the sort direction. 

It would be nice to have an `addOrder` function, so I could do this all invisibly on the backend.

**Comment by yajra** [comment]
@trevorgehman, you can still add a duplicate hidden column and set it as post sort as a workaround till we are done with `addOrder` feature. This is also the same trick I am using if i want to search on some fields but did not want it visible. 

```js
columns: [
  { name: 'id', data: 'id', visible: false },
  { name: 'id', data: 'id' }
]

```

**Comment by trevorgehman** [comment]
Thanks @yajra, that's what I will do for a temporary fix. Thanks for all your work!
