### ISSUE TITLE
Eager loading and filtered columns (record-counts)

### ISSUE THREAD

**Issue by mikerockett** [yajra/laravel-datatables#1411]
### Summary of problem

I think this may be somewhat similar to #333, though the context is slightly different in that I'm filtering on a per column basis, and not using standard pagination (rather using the scroller plugin).

When filtering by an eager-loaded column to get related data, the total record count and the filtered record count are the same, which leaves a huge wad of empty scrollable space in my table.

### Controller code

```php
$model = M::with(
    'related_a:id,name',
    'related_b:id,name,tag',
    'related_c:id,name',
    'related_d:id,name,long_name'
)->select([
    'id',
    'f_ref',
    'i_serial',
    'amount_value',
    'created_at',
    'related_a_id',
    'related_b_id',
    'related_c_id',
    'related_d_id',
]);

$dt = datatables()->eloquent($model)
    ->orderColumn('i_serial', 'id $1')
    ->editColumn('i_serial', function ($m) { ... })
    ->editColumn('...', function ($m) { ... })
    ->filterColumn('related_a_id', function ($query, $keyword) { ... })
    ->filterColumn('related_b_id', function ($query, $keyword) {
        $query->whereHas('related_b', function ($query) use ($keyword) {
            $query->whereTag($keyword);
        });
    })
    ->filterColumn('related_c_id', function ($query, $keyword) { ... })
    ->filterColumn('related_d_id', function ($query, $keyword) { ... });

// ...

return $dt->toJson($options);
```

### Resulting JSON

When filtering by column `related_b`, for example, I receive the following result:

```
// collapsed data tree (inspector)
{draw: 22, recordsTotal: 8897, recordsFiltered: 8897,…}
```

Meanwhile, there are only two records, as an example, in the `data` response after the filter is effected.

Below are the applicable input parameters from DT:

```
[0]
data: "related_b.name"
name: "related_b_id"
orderable: "true"
search: {value: "MV", regex: "false"}
searchable: "true"
```

Perhaps I'm doing this all wrong?

### System details

- Operating System: Windows 10
- PHP Version: 7.1.8
- Laravel Version: 5.5.13
- Laravel Datatables Version: Oracle 8.0.3

**Comment by mikerockett** [comment]
Oh, it's worth noting that this doesn't occur when filtering non eager-loaded columns (`f_ref`), for example.

**Comment by rudashi** [comment]
I have simillar problem, but when I filtering (searching column) the eager-loaded column I got always **recordsFiltered = 0**

**Comment by nateetk** [comment]
i found that adding the following fixes the filter totals

`->filter(function(){},true)`

for example:

`Datatables::of($initQuery)->filter(function(){},true);`
