### ISSUE TITLE
Question: server side request policy

### ISSUE THREAD

**Issue by linaspasv** [yajra/laravel-datatables#1412]
Hello @yajra , I could not find much of the information regards the subject and not sure if it's somehow covered already in your plugin.

I have a very large database. In order, to protect the server from ddos, I would like to be able to apply some strict rules for an incoming datatable requests on the server side by overriding the ones coming from the client side e.g. define what columns should be allowed for filtering or sorting, the maximum limit of the results, etc..

Please advice. Thanks.

**Comment by yajra** [comment]
For sorting & searching protection, you can use [blacklist](https://yajrabox.com/docs/laravel-datatables/master/blacklist) api. However, for max results, i think you can add a middleware that forces the length to a max. Maybe something like:

```php
namespace App\Http\Middleware;

use Closure;

class LimitLength
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (request('length') > 1000) {
            request()->merge(['length' => '1000']);
        }
        
        return $next($request);
    }
}
```

**Comment by yajra** [comment]
Btw, there is also a [whitelist](https://yajrabox.com/docs/laravel-datatables/master/whitelist) api that you can use.

**Comment by linaspasv** [comment]
@yajra I did somehow miss whitelist and blacklist api calls.

Do you think something like a single policy object would be nice to have?

```php
$guard = new Policy;
$guard->allowSearchableColumns(['name', 'email']);
$guard->allowOrderableColumns(['name']);
$guard->setMaxPageLength(1000);

DataTables::eloquent($model)
       ->policy($guard)
       ->toJson()
```

This would allow to add more rules or extend with more restrictions in the future. If you do agree with the concept I might write a PR.
