### ISSUE TITLE
[Question] How to insert columns when using Ajax URL

### ISSUE THREAD

**Issue by huuloc4193** [yajra/laravel-datatables#1417]
Hello yajra,
I'm using this your package with laravel 5.5. It's best Datatables's package.
I want to insert columns with AJAX url.
Please kindly help me !!
Thank you so much.

### System details

- Operating System: CentOS 7
- PHP Version : 7.1
- Laravel Version: 5.5
- Laravel-Datatables Version: 5.5

**Comment by yajra** [comment]
Can you please provide some snippet on what you are trying to achieve?
