### ISSUE TITLE
Eloquent relationship not working in search

### ISSUE THREAD

**Issue by jamesriady** [yajra/laravel-datatables#1419]
Hello yajra, I want to ask about search and sorting in Eloquent relationship.. I saw the issue before that you will add the search and sorting in  Eloquent relationship. is it work now?

- Operating System
- PHP Version 7.1.4
- Laravel Version 5.4
- Laravel-Datatables Version 7.2

**Comment by yajra** [comment]
@jamesriady yes it's working now. There are some edge cases though that might not be supported. One known issue is when using a SELF join relationships.
