### ISSUE TITLE
addRowAttr gets encoded, resulting in errors on the frontend

### ISSUE THREAD

**Issue by kife-design** [yajra/laravel-datatables#1423]
### Summary of problem or feature request

I updated to version 8 of the component and i'm having problems with the addRowAttr

Inside the addRowAttr closure i have the following code (param is changed for simplicity)

```php
return 'customers.editCustomer("test")';
```
So i'm passing the param "test" to the javascript function, but when this gets rendered on the page it returns:

```html
<tr onclick="customers.editCustomer(&amp;quot;test&amp;quot;)" role="row" class="odd">
```
As you can see, the parameter gets encoded, which is giving errors when i click on the row. This wasnt getting incoded in version 6

### Code snippet of problem

```php
return $this->datatables
            ->of($contacts)
            ->addRowAttr(
                'onclick',
                function ($contact) {
                    return 'customers.editCustomer("' . id($contact->id) . '")';
                }
            );
```

### System details

- 7.1
- laravel 5.5
- Laravel-Datatables Version 8

**Comment by yajra** [comment]
Since version 7, all results were encoded by default to protect us from XSS attacks. Will check if we can allow rowAttr to be less secure.

**Comment by kife-design** [comment]
That would be awesome. Keep us updated please.

**Comment by kife-design** [comment]
Any updates on this?

**Comment by kife-design** [comment]
Hello, could you give a status of this issue?
