### ISSUE TITLE
Ambiguous column name 'id', in pagination

### ISSUE THREAD

**Issue by ebardier** [yajra/laravel-datatables#1424]
### Summary of problem or feature request

In Datatables Service implementation, I have a join between two tables. Although I identify the fields in the form table.field, when I change page, I get the error: 

Next Illuminate\Database\QueryException: SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Ambiguous column name 'id'. (SQL: select * from (select [empresas].[id], [empresas].[nombre], [cat_empresas].[nombre] as [cat_nombre], [empresas].[rut], row_number() over (order by [id] desc) as row_num from [empresas] left join [cat_empresas] on [empresas].[cat_empresa_id] = [cat_empresas].[id] where [empresas].[deleted_at] is null) as temp_table where row_num between 11 and 20) 

### Code snippet of problem
```php

    public function dataTable($query)
    {
         $dataTable = new EloquentDataTable($query);

         return $dataTable->addColumn('action', function ($empresa) {               
                return '<a onClick="modalEditTriger(' . $empresa->id . ')" class="btn btn-primary"><i class="fa fa-pencil"></i></a>'
                        .' <a onClick="modalDeleteTrigger(' . $empresa->id . ')" class="btn btn-danger"><i class="fa fa-close"></i></a>';
             }) ;
    }

   public function query(Empresa $model)
    {           
          $query = $model::query()->select(['empresas.id', 'empresas.nombre','cat_empresas.nombre as cat_nombre', 'empresas.rut'])
                     ->leftJoin('cat_empresas', 'empresas.cat_empresa_id', '=', 'cat_empresas.id');

          return $query;        
    }

protected function getColumns()
    {
            return [
                'Nro. Id' => ['name' => 'empresas.id', 'data' => 'id'],
                'nombre' => ['name' => 'empresas.nombre', 'data' => 'nombre'],
                'rut' => ['name' => 'rut', 'data' => 'rut'],
                'categoria' => ['name' => 'cat_empresa.nombre', 'data' => 'cat_nombre','searchable' => true]    
            ];
    }
```

### System details

- Operating System Win 7/ SQL Server
- PHP Version 7.1.7
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by thiagodeluca** [comment]
Same problem here.

**Comment by Afatkharrofiqi** [comment]
just try adding all the columns to the model as follows "table.column"

```
class Guru extends Model
{
    protected $columns = array(
        "gurus.id",
        "gurus.user_id"
   );
}
```
