### ISSUE TITLE
Pagination not working version 8.0.3

### ISSUE THREAD

**Issue by markvdputten** [yajra/laravel-datatables#1426]
### Summary of problem or feature request

Hi,

I am having a fresh install of Laravel 5.5.14 and the package on version 8.03.
All the table functionality works as expected, except for the pagination.
Clicking on the next page, or a page number does not do anything.

I have searched for a while what this could be, but I really have no idea.
Would you have any pointers?

Thanks in advance!

### Code snippet of problem

```javascript
$('#players').DataTable({
	processing: true,
	serverSide: true,
	ajax: '/targeting/data',
	columns: [
		{data: 'user', name: 'user'},
		{data: 'spins_allowed', name: 'spins_allowed'},
		{data: 'spins_frequency', name: 'spins_frequency'},
		{data: 'spins_frequency_amount', name: 'spins_frequency_amount'},
		{data: 'expires', name: 'expires'},
		{data: 'prize_id', name: 'prize_id'},
		{data: 'actions', name: 'actions', orderable: false, searchable: false}
	],
});
```

```php
// Fetch data
$players = PlayerLimit::where('campaign_id', session('currentCampaign'));

// Return Datatable
return datatables()->of($players)
    ->addColumn('actions', function ($target) {
        return Button::delete('targeting', $target->id);
    })
    ->toJson();
```

### System details

- Operating System
- PHP Version 7.1.8
- Laravel Version 5.5.14
- Laravel-Datatables Version 8.03

**Comment by yajra** [comment]
Maybe by the name of the model itself `PlayerLimit`, you might be using a global scope that limits the result by default? If yes, you need to remove any scopes related to pagination.

**Comment by markvdputten** [comment]
Hi,

Thanks for getting back to me, much appreciated!

Here is the code of the model, very simple without any scopes

```javascript
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PlayerLimit extends Model
{
    protected $table = 'player_limits';
    protected $fillable = ['campaign_id', 'whid', 'spins_allowed', 'spins_frequency', 'spins_frequency_amount', 'expires', 'prize_id'];
}
```

Thanks again!

**Comment by markvdputten** [comment]
Hi again,

I have now noticed that this only happens when using the DataTables Bootstrap 3 integration. Once I comment this out the pagination works fine.

So there seems to be something related to using this Bootstrap integration which makes it break.

**Comment by mnelsonCASE** [comment]
This is still present with Bootstrap4 as well; I would like to leverage the Bootstrap styling with this library, any suggestions?

**Comment by yajra** [comment]
@mnelsonCASE I think the bootstrap styling should be raised on datatables.net or https://github.com/DataTables/DataTables repo instead. Styling is a bit out of scope of the package. Thanks!

**Comment by narbehmovsesian** [comment]
@markvdputten where you able to solve this issue. I am having the same problem and would appreciate any help
