### ISSUE TITLE
Model Methods are not working In datatables as Service

### ISSUE THREAD

**Issue by sandipsapkota1** [yajra/laravel-datatables#1427]
### Summary of problem or feature request

Hi, I am using Datatables as Service Latest version 8.0.

In UserDatataTable.php  file:

I have roles() method inside my Model but i cannot access it in my added column.
### Code snippet of problem

public function dataTable($query)
    {
        return datatables($query)
            ->addColumn('role', function ($query) {
                return ($query->roles[0]->display_name);
//This above method has issue
            })
            ->addColumn('action', 'datatables.action')
//            ->addColumn('role','eloquent/details-data/')
            ->addColumn('details', "");
    }

### System details

- OS Linux / MacOs / Apache
- Php Version 7.1
- Laravel Version 5.5
- Laravel-Datatables Version v8.0

**Comment by ElfSundae** [comment]
`roles()` is a method, but you access it using `$query->roles[0]` as an attribute?

**Comment by sandipsapkota1** [comment]
Yes, roles is a method that returns array of roles,  How can i access that roles of particular user?

**Comment by ElfSundae** [comment]
How about adding `()` before `[0]` ?
```php
return $query->roles()[0]->display_name;
```

**Comment by sandipsapkota1** [comment]
It still shows this error 
<img width="496" alt="screen shot 2017-10-06 at 5 34 29 pm" src="https://user-images.githubusercontent.com/17892319/31276640-b09c61f6-aabc-11e7-92de-b03cdd30a360.png">

**Comment by sandipsapkota1** [comment]
thanks , i got it

**Comment by ElfSundae** [comment]
Is `roles()` public?  
Your model is `App\User`?

It seems not a datatables issue, can you access this roles anywhere without using dataTables?

```php
Route::get('test', function () {
    $user = \App\User::first();
    dd($user->roles(), $user->roles);
});
```

**Comment by ElfSundae** [comment]
OK
