### ISSUE TITLE
Column data is changed when upgrading from 7.* to 8.*

### ISSUE THREAD

**Issue by rumaviio** [yajra/laravel-datatables#1429]
### Summary of problem or feature request

The indexes of the column data in 7.* and 8.* are different.
In 7.* the data is array of arrays, while in 8.* the data is array of objects.
I don't want to access the columns by property name, I want to do it by index.
How can I do such thing?

### Code snippet of problem

7.* :
```
"data":[
    [
        "1",
        "foo",
        "foo foo"
    ],
    [
        "2",
        "bar",
        "foo bar"
    ],
    [
        "3",
        "baz",
        "foo baz"
    ]
```

8.* :
```
"data":[
    {
        "id":"1",
        "name":"foo",
        "description":"foo foo"
    },
    {
        "id":"2",
        "name":"bar",
        "description":"foo bar"
    },
    {
        "id":"3",
        "name":"baz",
        "description":"foo baz"
    }
```

**Comment by AnubisTheory** [comment]
I'm experiencing the same issue, any insight into this would be greatly appreciated.

**Comment by AnubisTheory** [comment]
@rumaviio - try this:

->make(**false**);

Solved my issue (which was the same as yours).

**Comment by rumaviio** [comment]
It's working! Thanks for the help @AnubisTheory
