### ISSUE TITLE
Error not found when load datatables

### ISSUE THREAD

**Issue by SangAntking** [yajra/laravel-datatables#143]
Sometimes it has 404 error, but when i click to direct link, it's work. I don't know why it say 404 error in console.
![screenshot 1](https://cloud.githubusercontent.com/assets/12997556/9149425/76ad93aa-3dd3-11e5-96a0-f04417e1c743.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/12997556/9149426/76b57958-3dd3-11e5-8ff1-b871107ed250.png)
 
I'm working on Laravel 4 and yajra/laravel-datatables ~3.0

**Comment by SangAntking** [comment]
I dont know why it has this error on localhost. When i run it on real server, it's work. I think it has error because we have port 8000 on localhost, please help me fix it :)

**Comment by yajra** [comment]
@SangAntking, I think this is a random apache 404 issue and an environment issue. I am using homestead and not encountering this kind of issue. Maybe try using homestead and try using virtual hosting on your apache to avoid port 8000.

**Comment by SangAntking** [comment]
Thanks @yajra, it's working on homestead but sometime i dont want to use homestead. 
Thanks for your support.

**Comment by marijnhur** [comment]
I'm experiencing the same problem while running from the built in PHP server. I get a 404 _route not found_ around 50% of the time, while using the Datatables plugin and while visiting the API endpoint manually. I am running on the built in server of PHP 7. 

The only thing I can think of is that this is related to the long request URL. Any ideas?

Using Laravel v5.2.31, PHP 7.0.6RC1, Laravel Datatables v6.10.1

**Comment by jackleblack** [comment]
Same problem, the problem occurs 50% of the time, I'm on localhost:8000 ...

**Comment by PrakharSambhav** [comment]
Please resolve this , i am using artisan serve and get same error about 50% of times

**Comment by andreaschrist27** [comment]
same problem, please :(

**Comment by PrakharSambhav** [comment]
using a virtual host resolves the issue but still i want to use it on php artisan serve

**Comment by andreaschrist27** [comment]
using a virtual host resolves the issue but still i want to use it on php artisan serve (2) :(

**Comment by Aasif001** [comment]
Does anyone has solution?
