### ISSUE TITLE
Is it possible instead of using raw collumns to just allow a line break

### ISSUE THREAD

**Issue by ghost** [yajra/laravel-datatables#1430]
### Summary of problem or feature request

So, I have a column, with a name and a data, I am separating them via a line break like so:

            ->addColumn('title', function($product){
                return 
                    $product->title . '</br>' . 
                    $product->created_at->diffForHumans();
            })

Now, my problem is, if I add that collumn to the 

`rawColumns` array like so:

    rawColumns(['title'])

All the HTML goes through, and the ->title is user defined so he could input <script></script> etc... Is there any way for me to just allow a line break I define?

**Comment by ElfSundae** [comment]
You can use `e()` helper to escape user content:

```diff
 ->addColumn('title', function($product){
     return 
-        $product->title . '</br>' . 
+        e($product->title) . '</br>' . 
         $product->created_at->diffForHumans();
 })
 ->rawColumns(['title'])
```

Or using Blade format:
```php
->addColumn('title', '{{ $title }} <br> {{ $created_at->diffForHumans() }}')
->rawColumns(['title'])
```
