### ISSUE TITLE
how to know if it's the initial load

### ISSUE THREAD

**Issue by anchetaWern** [yajra/laravel-datatables#1431]
I need to load data randomly the first time the results are loaded. Is there any way to determine the first time the data is loaded?

**Comment by ChaosPower** [comment]
With database flags or without?

**Comment by anchetaWern** [comment]
@ChaosPower not really sure what you mean by database flags. But I'm just performing a plain query with `WHERE` clauses. I just need that on the first load the results (10 rows) are randomly selected from a table of 10k rows. When the user paginates, search, sort or do something else it's just going to load the data in their default order. It doesn't matter if any of the rows selected on first page load gets selected again when the user does so

Here's my code:

```php
$products_data = DB::table('products')
  ->where('qty', '>', 0)
  ->where('verification_status', 1)
  ->select('id', 'SKU', 'title', 'filter_category', 'BIN_Price', 'qty', 'image1');
  ->inRandomOrder(); // this messes up the pagination so I just need to implement this on first page load only
```
.

**Comment by ChaosPower** [comment]
@anchetaWern below are the links similar to what you want.

https://datatables.net/forums/discussion/1224/random-rows

If you want to randomly order. Please refer to https://yajrabox.com/docs/laravel-datatables/master/manual-order.

The pagination link when clicked, is from [Datatables](http://www.datatables.net/) (JS).

If you turn on server side processing, each time you click pagination of [Datatables](http://www.datatables.net/) (JS) it will send a command to Laravel Datatables Package then respond with new data.

I think what you were saying is to do not refresh the result of random $products_data or to retain the state of results from your query. This is a problem with server side processing. Each time you issue a request to the HTTP Server the PHP module will recompile and load.

If I where to do this, I would use [Laravel Cache](https://laravel.com/docs/5.5/cache) and and then paginate from the stored results.

And remove cache if [Laravel Session](https://laravel.com/docs/5.5/session) is not current viewing the current page or route.

**Comment by anchetaWern** [comment]
Thank you for the idea! I ended up using sessions.

So when the products page is accessed, I put in a session:

```
session()->put('randomize_products', true);
```

And in the function that returns the data:

```
if(session()->has('randomize_products')){
   $products_data->inRandomOrder();
   session()->forget('randomize_products');
}
```

This effectively orders the data in random when the user refreshes the page. But when another query is made, it now follows the default order since the session has been unset.
