### ISSUE TITLE
How to use Row-Details in Yajra DataTables Service Implementation

### ISSUE THREAD

**Issue by kamrava** [yajra/laravel-datatables#1432]
I checked out some demos about [row-details](https://datatables.yajrabox.com/eloquent/row-details) and [master-details](https://datatables.yajrabox.com/eloquent/master) and few threads related to this question.

**Question:**

How to pass data from DataTables Class (for example UsersDataTable) to the template(Handlebars).
I'm confusing because in Service Implementation all we have are these:

```php
{!! $dataTable->table(['id'=>'UsersList') !!}
AND
{!! $dataTable->scripts() !!}
```
Any help would be great apprectiated.

- Fedora 26
- PHP 7.1
- Laravel 5.4
- Laravel-Datatables 7.10 Service Implementation

**Comment by lk77** [comment]
Hello,
there is a generateJson method,  i think you will need to use it when you initialize a handlebar generated datatable.

**Comment by RayhanYulanda** [comment]
I got the answer from this https://github.com/yajra/laravel-datatables/issues/38#issuecomment-546725878
