### ISSUE TITLE
"Call to a member function diffForHumans() on string"

### ISSUE THREAD

**Issue by filtration** [yajra/laravel-datatables#1434]
So I am using cast for my dates like so:

	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = [
	    'created_at',
	    'updated_at',
	    'deleted_at'
	];

Inside my datatable I am selecting the created_at row

    protected function getColumns()
    {
        return [
            'id',
            'name', 
            'address',
            'description',
            'created_at',
        ];
    }

and trying to use it inside my builder like so:

            ->addColumn('name', '{{ $name }} <br> {{ $created_at->diffForHumans() }}')

Which thrown an error:

> "Call to a member function diffForHumans() on string"

But when I echo it without diff it returns the date like so:

    2017-10-05 20:06:12

All my created_at dates seem to be set:

<img src="https://i.imgur.com/VgymgoK.png">

Any idea how to fix this?

**Comment by yajra** [comment]
All attributes were converted to array when doing a blade string syntax for security purposes. You need to use closure if you want to access the Carbon date.


```php
->addColumn('name', function($model) {
    return $model->name . '<br>' . $model->created_at->diffForHumans();
})
```
