### ISSUE TITLE
OrderColumn not working

### ISSUE THREAD

**Issue by asivaneswaran** [yajra/laravel-datatables#1435]
### Summary of problem or feature request

I am trying to order my table using the orderColumn but that column is not being ordered. It's always the first column from the left.

### Code snippet of problem
```
$divisions = Division::select('*');
$list       = $this->dataTables->eloquent($divisions)
						->addColumn('actions', 'admin.table._actions')
						 ->rawColumns(['actions'])
						 ->orderColumn('level', 'level $1')
						->toJson();
```

### System details

- Operating System Homestead
- PHP Version 7.1
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
Working well on my side. Maybe try inspecting the generated SQL to get a hint on what may have cause the issue?
