### ISSUE TITLE
PDF Export error

### ISSUE THREAD

**Issue by buyzer** [yajra/laravel-datatables#1436]
Hi,
basically i'm new on laravel . I'm looking Datatables library for laravel and found this package as awesome library. but ' i got error at this page https://datatables.yajrabox.com/services/scope.
please click export button especially PDF export , 
i got this error 
![image](https://user-images.githubusercontent.com/13073021/31373564-c24bb2ac-adc4-11e7-897e-b5df0dc1214f.png)

i think the server error , but same error happened on my local server.  . 
thanks

**Comment by yajra** [comment]
What generator are you using? Snappy or DomPDF? See [docs](https://yajrabox.com/docs/laravel-datatables/master/buttons-config#pdf-generator) for ref.

**Comment by yajra** [comment]
Oh didn't notice it was on the demo server. Need to check the config too. :)

**Comment by buyzer** [comment]
Ok , thanks

**Comment by RayhanYulanda** [comment]
Where should i change "change the export.pdf.driver config setting accordingly"??
