### ISSUE TITLE
Does not work with queryBuilder and selectRaw

### ISSUE THREAD

**Issue by maxgalbu** [yajra/laravel-datatables#1441]
### Summary of problem or feature request

Using `queryBuilder->selectRaw` and then passing the queryBuilder to DataTables throws an exception of `Illegal offset type in isset or empty`, because $column is a laravel class (Expression) instead of a string.

### Code snippet of problem

```php
$queryBuilder = DB::table("table");
$columns = [
    "IFNULL(table.id, joined_table.id) AS id",
    "IFNULL(table.vendor, joined_table.vendor) as vendor"
];
$queryBuilder->selectRaw(implode(",", $columns));
$queryBuilder->rightJoin("joined_table", function(JoinClause $join) {
    $join->on("joined_table.vendor", '=', "table.vendor");
    $join->on("joined_table.id", '=', "table.id");
});
Datatables::queryBuilder($query)->make(false);
```

This returns the following JSON:
```json
{
"draw":4,
"recordsTotal":355,
"recordsFiltered":0,
"data":[],
"error":"Exception Message:\n\nIllegal offset type in isset or empty"
}
```

due to the code on [this line](https://github.com/yajra/laravel-datatables/blob/72cd1fdb3340b787c3bd71ca03228c09d1046de9/src/QueryDataTable.php#L587) for datatables 8.x and [this line](https://github.com/yajra/laravel-datatables/blob/8e217bf1be307c8e7e52fa6a5071b985568bc04c/src/Engines/QueryBuilderEngine.php#L714) for datatables 7.x.

`get_class($column) == 'Expression'` while DataTables expect a string

### System details

- Operating System: Ubuntu 16.04 (homestead)
- PHP Version: PHP 7.1
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.10.1 / 8.1.0

**Comment by yajra** [comment]
Thanks for the hints. If you can, please do not hesitate to submit a PR for a fix.
