### ISSUE TITLE
Cannot use setTotalRecords with jenssegers mongodb

### ISSUE THREAD

**Issue by orkunab** [yajra/laravel-datatables#1442]
### Summary of problem or feature request
``
Expected limit option to have type "integer" but found "string"
``
I got this message when i try run the code below

### Code snippet of problem
`$options =Option::query();
return \Yajra\Datatables\Datatables::of($options)->setTotalRecords(100)->make(true);`

### System details

- Centos 7
- PHP 5.4.6
- Laravel 5.4
- Laravel-Datatables 7.0
- jenssegers/mongodb 3.2

**Comment by yajra** [comment]
Will try to check this if I can. Honestly, I haven't used mongodb yet :).

**Comment by orkunab** [comment]
Solved the problem changing: `Yajra\Datatables\Engine\QueryBuilderEngine`
```
public function paging()
    {
        $limit = (int) $this->request->input('length') > 0 ? intval($this->request->input('length')) : 10;
        $skip = (int) $this->request->input('start') >= 0 ? intval($this->request->input('start')) : 0;
        $this->query->skip($skip)->take($limit);
    }
```

However, I am getting an error when i try the use datatables's search box. I used laravel scout instead.

Now this is the working code:

```
public function ajaxOptions(){
        $options = Option::query();
        $search = isset($_GET['ara']) ? $_GET['ara'] : null;
        if(!empty($search))
        {
            $options = Option::search($search)->get();
        }
        return Datatables::of($options)->setTotalRecords($options->count())->make(true);
    }
```

Thank you for your quick answer, and I'm sorry for my English.

**Comment by cbloss** [comment]
Hey @orkunab 

Were you able to figure it out? I was trying to extend Datatables instead of overriding vendor files and I'm not having any luck.
