### ISSUE TITLE
Hide the Actions Column in PrintPreview

### ISSUE THREAD

**Issue by BashirRezaiee** [yajra/laravel-datatables#1443]
how could I hide the Actions column of the DataTable in print preview?
![screenshot 1](https://user-images.githubusercontent.com/18642056/31496142-6b54d3be-af6f-11e7-938d-c7f58b48d960.png)

**Comment by yajra** [comment]
You are using buttons plugins right? You can set the attribute `'printable' => false` and I think it should be hidden on print.

**Comment by BashirRezaiee** [comment]
thanks, it worked.

**Comment by zorrigas** [comment]
How add on a Column with view?
` $dataTable->addColumn('action', 'pagos.datatables_actions');`

**Comment by irvv17** [comment]
yeah

**Comment by javidjan** [comment]
Hello dear @yajra how we can print issue for this line code
columns: [
                        { data: 'name', name:  'name' },
                        { data: 'phone', name: 'phone' },
                        { data: 'office', name: 'office' },
                        { data: 'date', name: 'date' },
                        { data: 'time', name: 'time' },
                    ],

**Comment by javidjan** [comment]
@yajra 
please inform me how to hide whole column

**Comment by thusithawijethunga** [comment]
I use this way.
`
protected function getColumns() {
        return [
            __('#') => ['data' => 'DT_RowIndex', 'orderable' => false, 'searchable' => false],
            Column::computed('action', __('app.action'))->exportable(false)->printable(false)
        ];
    }
`
