### ISSUE TITLE
Make Table responsive

### ISSUE THREAD

**Issue by lmatab** [yajra/laravel-datatables#145]
This  package works  just great!,

Although  when   you view it in  a cellphone the  table  is not quite proporcional. is it  possible to make it  responsable, so it can be adapted to any screen?

Thanks

**Comment by yajra** [comment]
@lmatab, try using this plugin https://datatables.net/extensions/responsive/. On my case, what I use is just the bootstrap `table-responsive` css class.

```html
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

**Comment by kamov** [comment]
How to enable responsive via Service (via php)?

@yajra
