### ISSUE TITLE
What do you think about implementing laravel-echo for realtime updates?

### ISSUE THREAD

**Issue by COLABORATI** [yajra/laravel-datatables#1452]
Hi, what do you think about implementing [Laravel Echo](https://laravel.com/docs/5.4/broadcasting#installing-laravel-echo) and [Laravel Broadcasating](https://laravel.com/docs/5.5/broadcasting) with datatables for (near) real-time updates or tables? (I am not sure if it is even possible with datatables api).

Thank you very much for your very interesting project and your attention!

**Comment by yajra** [comment]
I think this is doable using dataTables row attributes/id. Just broadcast the model id that was updated, track dataTables data and then update the necessary matching rowId. Haven't tried this yet though but I think it may work.

**Comment by legreco** [comment]
see this https://github.com/yajra/laravel-datatables/issues/1384
