### ISSUE TITLE
Searching for Multiple Row Selection Capabilities

### ISSUE THREAD

**Issue by sandman06** [yajra/laravel-datatables#1455]
### Summary of problem or feature request

I'd like the ability to select multiple records as provided in datatables:
https://datatables.net/examples/server_side/select_rows.html

Maybe I'm really missing something.  If it is available, please point me in the correct direction for laravel datatables as a service.

### System details

- Operating System: Currently Windows, but will be switching to Ubuntu.
- PHP Version: 5.6.17
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.28.1

**Comment by yajra** [comment]
Maybe this [doc](https://yajrabox.com/docs/laravel-datatables/master/html-builder-callbacks) can help. However, not really sure if it was supported on v6. I suggest you upgrade to v7 if possible. Thanks!

**Comment by EgyptianM** [comment]
Same question
How to make rows selectable?
The above link doesn't provide a clear way or guide on how to do it or examples or even the code used to do it?
So how to do it?
