### ISSUE TITLE
setTotalRecords Error

### ISSUE THREAD

**Issue by nimeshc64** [yajra/laravel-datatables#1457]
### Summary of problem or feature request

i added following   ->setTotalRecords(100) to my code the show error **_Call to undefined method Yajra\Datatables\Engines\BaseEngine::settotalrecords()_**
```
return $this->datatables
            ->of($this->query())
            ->setTotalRecords(100)
            ->make(true);
```

### System details

- Operating System -  windows 10 
- PHP Version - 5.6
- Laravel Version 5.2
- Laravel-Datatables Version 6.0

**Comment by yajra** [comment]
Sorry! But I think `->setTotalRecords(100)` is only available on v7++. Please upgrade if you need that feature. Thanks!
