### ISSUE TITLE
Any way to get QueryBuilder object?

### ISSUE THREAD

**Issue by underdpt** [yajra/laravel-datatables#1463]
Hi,

After reviewing #1068, if I understand it correctly, it will return the full query _after_ executing it. Now take a look at this scenario: a "Delete" button, which when pressed would delete all the rows on the table (filtered and searched).
Getting que query after executing it would be a waste of resources. In this scenario, I would like to get the QueryBuilder object before it's exectuted, to transform it onto a delete query (if that's possible) or modify it to only return the ids, then delete those ids. 

I've been diving onto the source, but didn't find a way to get the QueryBuilder object (i'm now getting the raw data from the `$response` object and extracting the `ids` for deletion).

**Comment by yajra** [comment]
See [changelog](https://github.com/yajra/laravel-datatables/blob/8.0/CHANGELOG.md#added) for details. I think it's not yet documented.

> Add `getQuery` api to get the query used by dataTable.
> Add `getFilteredQuery` api to get the prepared (filtered, ordered & paginated) query.

**Comment by underdpt** [comment]
Thanks! I'll take a look at it, and send a PR to the docs as soon as I can.
