### ISSUE TITLE
[8.1.x] Fractal transformer includes not working

### ISSUE THREAD

**Issue by trinvh** [yajra/laravel-datatables#1464]
### Summary of problem or feature request
Response does not include child items when use fractal transformer.

### Code snippet of problem

```shop = Shop::where('uuid', $uuid)->firstOrFail();
        return DataTables::eloquent($shop->orders()->with(['items', 'shipping', 'billing']))
            ->setTransformer(new OrderTransformer)
            ->toJson();

class OrderTransformer extends TransformerAbstract {

    protected $availableIncludes = ['billing'];

    public function transform(Order $order) { }
    public function includeBilling(Order $order) { return ... }
```
### System details

- Operating System: Windows 10
- PHP Version: 7.1.7
- Laravel Version: 5.4
- Laravel-Datatables Version: 8.1.1 (master)

**Comment by yajra** [comment]
If I recall this correctly, you should use `include` key on your request params.

```php
laravel.dev/url?include=billing
```

Or I think you should use `$defaultIncludes` if you want it added by default. Check with [fractal](https://fractal.thephpleague.com/transformers/) official docs.
