### ISSUE TITLE
globalSearch not working for 0

### ISSUE THREAD

**Issue by lrtr** [yajra/laravel-datatables#1466]
### Summary of problem or feature request

When using the global search and entering 0 no results are returned. The search works when the 0 from the database is a string, but in my case it is an integer or float. I also tested if 0 as a string in the database but the bug occured again.

### Code snippet of problem

```php
/**
     * Perform global search for the given keyword.
     *
     * @param string $keyword
     */
    protected function globalSearch($keyword)
    {
        $columns = $this->request->columns();
        $keyword = $this->config->isCaseInsensitive() ? Str::lower($keyword) : $keyword;
        $this->collection = $this->collection->filter(function ($row) use ($columns, $keyword) {
            $this->isFilterApplied = true;
            $data = $this->serialize($row);
            foreach ($this->request->searchableColumnIndex() as $index) {
                $column = $this->getColumnName($index);
                $value  = Arr::get($data, $column);
                if (!$value || is_array($value)) {
                    continue;
                }
                $value = $this->config->isCaseInsensitive() ? Str::lower($value) : $value;
                if (Str::contains($value, $keyword)) {
                    return true;
                }
            }
            return false;
        });
    }
```

The problem is the comparison in CollectionDataTable.php

```php
if (!$value || is_array($value)) {
                    continue;
 }
```
Numbers and numeric strings get interpreted as false and will not be searched.
http://php.net/manual/en/types.comparisons.php

### System details

- Operating System: Windows 10 Pro (1709) / Ubuntu 16.04
- PHP Version: 7.1.8 / 7.0.24
- Laravel Version: 5.4 / 5.5
- Laravel-Datatables Version: 8.1.1

**Comment by yajra** [comment]
Your PR was merged. Thanks!
