### ISSUE TITLE
nothing to publish

### ISSUE THREAD

**Issue by BartReymenants** [yajra/laravel-datatables#147]
the command
***php artisan vendor:publish --provider="yajra\Datatables\DatatablesServiceProvider"***

does return:
***Nothing to publish for tag [].***

is this ok?

**Comment by vluzrmos** [comment]
The service provider only has the tag "config", so, you need to specify that:
`php artisan vendor:publish --provider="yajra\Datatables\DatatablesServiceProvider" --tag=config`

**Comment by yajra** [comment]
@BartReymenants, I think it's ok and it means that you have already published the config file for datatables. To make sure, check your `config` directory and `datatables.php` must exists. You can also append `--tag=config` on command as suggested by @vluzrmos. Thanks!
