### ISSUE TITLE
Illegal operator and value combination after upgrading to 8.x

### ISSUE THREAD

**Issue by curtisweeks** [yajra/laravel-datatables#1474]
### Summary of problem or feature request

Illegal operator and value combination after upgrading to 8.x (Solved)
Update QueryBuilder Custom Filter Documentation (Suggested)

### Code snippet of problem

https://datatables.yajrabox.com/fluent/custom-filter

```php
if ($request->has('name')) {
    $query->where('name', 'like', "%{$request->get('name')}%");
}
```

Should now be

```php
if ($request->filled('name')) {
    $query->where('name', 'like', "%{$request->get('name')}%");
}
```

https://laravel.com/docs/5.5/requests

### System details

- PHP Version 7.1.x
- Laravel Version 5.5.x
- Laravel-Datatables Version 8.x

**Comment by yajra** [comment]
Thanks for the suggestion, will try to create a new documentation for v8 when I got the chance. I'm just too occupied atm.
