### ISSUE TITLE
Getting json but cannot render view

### ISSUE THREAD

**Issue by stumped101** [yajra/laravel-datatables#148]
HI,

Can you show me what I am doing wrong here. The following is the json response I get from an original datatable with checkboxes ticked. I am trying to develope another datable from these results.:
```php
Array
(
    [0] => 1
    [1] => 2
)
{"sEcho":0,"iTotalRecords":2,"iTotalDisplayRecords":2,"aaData":[{"id":1,"p_id":2,"Genus":"Abelia","species":"Edward","variety":"Goucher ","htmin":0,"htmax":0,"pmin":5,"pmax":0,"root":"","girthmin":0,"girthmax":0,"minprice":"\u20ac1.60","maxprice":"\u20ac1.60","created_at":"2014-11-30 22:17:12","updated_at":"2014-11-30 22:17:12"},{"id":2,"p_id":1,"Genus":"Abelia","species":"Edward","variety":"Goucher ","htmin":25,"htmax":30,"pmin":2,"pmax":0,"root":"","girthmin":0,"girthmax":0,"minprice":"\u20ac3.65","maxprice":"\u20ac4.00","created_at":"2014-11-30 22:17:12","updated_at":"2014-11-30 22:17:12"}],"sColumns":["id","p_id","Genus","species","variety","htmin","htmax","pmin","pmax","root","girthmin","girthmax","minprice","maxprice","created_at","updated_at"],"aQueries":[{"query":"select count(*) as aggregate from (select '1' as row_count from `prices` where `id` in (?, ?)) count_row_table","bindings":["1","2"],"time":1},{"query":"select count(*) as aggregate from (select '1' as row_count from `prices` where `id` in (?, ?)) count_row_table","bindings":["1","2"],"time":1},{"query":"select * from `prices` where `id` in (?, ?) limit 10 offset 0","bindings":["1","2"],"time":1},{"query":"select * from `prices` where `id` in (?, ?) limit 1 offset 0","bindings":["1","2"],"time":1}]}
```

My route is:
```php
	Route::get('chosenPlants2/data', 'DisplayController2@anyData');
	Route::resource('chosenPlants2', 'DisplayController2');
```
Thanks in advance

**Comment by yajra** [comment]
You need a view and to display this json response. See this link for ref: http://datatables.net/examples/data_sources/server_side.html. Note that this package should be used side by side DataTables jQuery plugin.

On the other hand, I think you are using an older version of DataTables. I suggest you upgrade it to v1.10.7++ as the support for older version of DT on this package was dropped on latest/future releases. Thanks!

**Comment by stumped101** [comment]
Thanks for your response. I have the first datatables working with the following code:
View:{{Form::open(array('url' => 'plants/chosenPlants2', 'method' => 'get','name' => 'f1'))}}
    <table class="table table-responsive table-bordered table-striped table-hover" id="users-table">
        <thead>
            <tr>
           		<th>Plant Name</th>
                <th>Common Name</th>
                <th>Height</th>
                <th>Max.Ht</th>
                <th>Min.Pot</th>
				<th>Max.Pot</th>
				<th>Root</th>
				<th>Girth</th>
				<th>Max.Girth</th>
				<th>Price(Y/N)</th>
            </tr>
        </thead>
    </table>
    {{Form::submit('Price', array( 'class'=>
		'form-group btn btn-success'))}} 
    {{ Form::close() }}
@stop

@push('scripts')
<script>
$(function() {
    $('#users-table').dataTable({
        processing: true,
        serverSide: true,
//         ajax: '{{url("datatables")}}',
        ajax: '{{{URL::to('datatables')}}}',
        columns: [
            { data: 'Plant_name', name: 'Plant_name' },
            { data: 'Common_name', name: 'Common_name' },
            { data: 'Htmin', name: 'Htmin' },
            { data: 'Htmax', name: 'Htmax' },
            { data: 'Pmin', name: 'Pmin' },
            { data: 'Pmax', name: 'Pmax' },
            { data: 'root', name: 'root' },
            { data: 'girthmin', name: 'girthmin' },
            { data: 'girthmax', name: 'girthmax' },
            { data: 'price_cb', orderable : false, searchable:false, name:'price_cb'  }
        ],

etc.
Routes:
Route::get('datatables', 'DatatablesController@anyData');
Route::resource('datatables/data', 'DatatablesController');

The problem exists when I submit the form with the checkbox array to another controller. The route to second controller receives the input as shown with print_r(Input::get("id"));
but when I try to use it in the second controller method as follows I get either json returned(as in my first post to you) or else I get datatables rendering but with no data when there definitely should be data:

public function anyData()
	{
 		$cps = Input::get("id");
		$result =  Price::select(["Genus","species","variety","htmin","htmax","pmin","pmax","root","girthmin",
				"girthmax","maxprice"])->whereIn('p_id', $cps);
		return Datatables::of($result)
		->make(true);
	}

Any idea how I pass form input from one datatable to render another second datatable with the results of the data passed from the first datatable?

Many Thanks in advance.

**Comment by stumped101** [comment]
Thanks for your response. I have the first datatables working with the following code:
View:{{Form::open(array('url' => 'plants/chosenPlants2', 'method' => 'get','name' => 'f1'))}}

What I need to know is how to pass data from one datatable (used as a form with checkboxes containing unique id's) to a route and onto another controller which renders a SECOND datatable with the results of the first datatable form input i.e. Input::get("id");.  Currently I can render valid json with the correct results or by altering the route render the second datatable as a view coorectly but unpopulated where clearly it should have been populated.

Any ideas on how to fix this?

Many Thanks in advance.

**Comment by yajra** [comment]
Correct me if i'm wrong, so you are trying to create something like master-details datatable? Where the details will depend on the master table and some of the form inputs? Maybe try using the approach here to get you started. 
- http://datatables.yajrabox.com/eloquent/row-details. 
- http://datatables.yajrabox.com/eloquent/advance-filter

**Comment by stumped101** [comment]
Some very interesting examples there thank you. My problem is slightly different in that I would like to pass a subset of the values in the main details datatable using checkboxes with a unique  id value in them to an eloquent query which queries the foreign table of another database table and use this to populate a second datatable.

**Comment by yajra** [comment]
@stumped101 , it's possible to pass data from one table to another but you would have to drill down datatables.net api for it to work. I have same scenarios like you and you would definitely need a bunch of javascripts for it to work. Better check the plugins api http://datatables.net/reference/api/ and other docs. It a little hard to explain here and is not covered by the package since it's a client side issue. Thanks!

Maybe try starting on reading the rows data then parse it to your own needs.

**Comment by stumped101** [comment]
Thanks for that - I am getting a json response from the above code for the SECOND datatable (which has read the imput values from the FIRST datatable correctly) as follows:
{"sEcho":0,"iTotalRecords":2,"iTotalDisplayRecords":2,"aaData":[{"Genus":"Abelia","species":"Edward","variety":"Goucher ","htmin":25,"htmax":30,"pmin":2,"pmax":0,"root":"","girthmin":0,"girthmax":0,"maxprice":"\u20ac4.00"},{"Genus":"Abelia","species":"Edward","variety":"Goucher ","htmin":0,"htmax":0,"pmin":5,"pmax":0,"root":"","girthmin":0,"girthmax":0,"maxprice":"\u20ac1.60"}],"sColumns":["Genus","species","variety","htmin","htmax","pmin","pmax","root","girthmin","girthmax","maxprice"],"aQueries":[{"query":"select count(*) as aggregate from (select '1' as row_count from `prices` where `p_id` in (?, ?)) count_row_table","bindings":["1","2"],"time":1},{"query":"select count(*) as aggregate from (select '1' as row_count from `prices` where `p_id` in (?, ?)) count_row_table","bindings":["1","2"],"time":1},{"query":"select `Genus`, `species`, `variety`, `htmin`, `htmax`, `pmin`, `pmax`, `root`, `girthmin`, `girthmax`, `maxprice` from `prices` where `p_id` in (?, ?) limit 10 offset 0","bindings":["1","2"],"time":1},{"query":"select `Genus`, `species`, `variety`, `htmin`, `htmax`, `pmin`, `pmax`, `root`, `girthmin`, `girthmax`, `maxprice` from `prices` where `p_id` in (?, ?) limit 1 offset 0","bindings":["1","2"],"time":1}]}


My problem lies in rendering the view. Any ideas how to render this view?
Thanks in advance

**Comment by yajra** [comment]
What I use is handlebars and add an init table function to render the 2nd table. Follow the code convention on this example: http://datatables.yajrabox.com/eloquent/row-details.

**Comment by yajra** [comment]
I just added a master-details table on demo site for your reference. It's just a simple demo just to guide developers on how to implement it. http://datatables.yajrabox.com/eloquent/master
