### ISSUE TITLE
syntax error, unexpected '?'

### ISSUE THREAD

**Issue by Osaidx** [yajra/laravel-datatables#1490]
(1/1) FatalErrorExceptionsyntax error, unexpected '?'
--
in DataTableAbstract.php (line 624)

**Comment by yajra** [comment]
I think this is php error. Make sure you are using at least PHP 7.

**Comment by alfenfebral** [comment]
Check in DataTableAbscract.php in line 624
Change this line
$this->serializer ?? null
to
isset($this->serializer) ? $this->serializer : null;

Work in PHP 5.6

**Comment by amarjitbh** [comment]
thank for helping @alfenfebral

**Comment by raikodok** [comment]
> Check in DataTableAbscract.php in line 624
> Change this line
> $this->serializer ?? null
> to
> isset($this->serializer) ? $this->serializer : null
> 
> Work in PHP 5.6

thank you,
