### ISSUE TITLE
Filtering two columns that represent that same model but two different relationships

### ISSUE THREAD

**Issue by Sitethief** [yajra/laravel-datatables#1491]
### Summary of problem or feature request

I have a problem with using filter columns when both columns represent a different relationship to the same Model. The search will not create a query where it joins twice to the same table.

I have tickets that have both a reporter relationship and an assignee relationship. Both are of the User model. I have two filter columns where I want to be able to filter on tickets that are created by one user but assigned to a different user. I can filter on one column, but not on a second. Filtering on other columns, for example reporting user + title of ticket works perfectly.

### Code snippet of problem

My query in the controller
```php
            $tickets = Ticket::with(['reporter', 'assignee', 'municipality', 'status'])->select('tickets.*');
            return $datatables->eloquent($tickets)->make(true);
```

My datatables build up. (all columns can be filterd via an input in the tfooter)
```javascript

var ticketTable = $('#tickets-list').DataTable({
            serverSide: true,
            processing: true,
            order: [[ 6, "desc" ]],
            ajax: '/tickets/data',
            rowId: 'id',
            columns: [
                {data: 'title'},
                {data: 'reporter.name'},
                {data: 'assignee.name'},
                {data: 'municipality.name'},
                {data: 'status.name'},
                {
                    data: 'created_at',
                    render: function(d){
                        return moment(d).format("YYYY-MM-DD HH:mm");
                    }
                },
                {
                    data: 'updated_at',
                    render: function(d){
                        return moment(d).format("YYYY-MM-DD HH:mm");
                    }
                }
            ]
        })
```

The query that is used in the end. Even though I filtered both reporter and assignee. It refuses to join for assignee_user_id.
```SQL
select `tickets`.* from `tickets` left join `users` on `tickets`.`reporter_user_id` = `users`.`id` where LOWER(`users`.`name`) LIKE '%%user%%' and LOWER(`users`.`name`) LIKE '%%admin%%' and `tickets`.`deleted_at` is null order by `updated_at` desc 
```
I wrote my own query that works when performed on the database:
```SQL
select `tickets`.* 
from `tickets` 
left join `users` `reporter` on `tickets`.`reporter_user_id` = `reporter`.`id` 
left join `users` `assignee` on `tickets`.`assignee_user_id` = `assignee`.`id` 
where 
	LOWER(`reporter`.`name`) LIKE '%%user%%' 
	and LOWER(`assignee`.`name`) LIKE '%%admin%%' 
	and `tickets`.`deleted_at` is null order by `updated_at` desc 
```
But I don't really get how to get Laravel-datatables to use it that way.

### System details

- Operating System: MacOS Sierra 10.12.6
- PHP Version: 7.1.10
- Laravel Version: 5.5.*
- Laravel-Datatables Version:  8.3.1  
- Datatables Version: 1.10.16

**Comment by yajra** [comment]
There is a known issue when using same table joins when using eager loading. In this regard, I suggest you use the join statement you created and just convert it to Laravel query format.

See https://datatables.yajrabox.com/eloquent/joins for ref.
