### ISSUE TITLE
Problem sorting table given a specified role, first order the "manager" type and then the rest

### ISSUE THREAD

**Issue by otipip90** [yajra/laravel-datatables#1494]
### Summary of problem or feature request

Hello, I have a list that returns a list of users with their roles as I order so that in the datatable I will show first those of type "manager" and then the rest, I have been searching for a while and can not find anything, if they could help me, Thank you

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
On your javascript, set the orderFixed value like:

```
$(..).DataTable({
    ...
    orderFixed: [0, 'asc'] // 0 is the index of manager.
})

**Comment by yajra** [comment]
On php side, I think you can just include `->orderBy('manager')` on your main query.

**Comment by otipip90** [comment]
Thank you very much for your time and response Yajra, believe me I appreciate your dedication to the guild, thank you really greetings from Cuba
