### ISSUE TITLE
how to do the multiple selection edit with tabs ?

### ISSUE THREAD

**Issue by tjnapster555** [yajra/laravel-datatables#1495]
I want to know that how we can implement the multiple selection edit when click on edit button the bootstrap model with tabs show in which we can edit all the select user data one by one 

- Operating System  windows 10
- PHP Version            7.1  
- Laravel Version        5.5
- Laravel-Datatables Version  6.0

**Comment by yajra** [comment]
Yes it's doable. I've done something like that years ago using jquery-ui tabs. But it's more on a javascript side so I suggest you browse boostrap, datatables & jquery library api.

**Comment by yajra** [comment]
You can also use datatables select extension / plugin for the select part.
