### ISSUE TITLE
addColumn sorting/searching

### ISSUE THREAD

**Issue by neuronetio** [yajra/laravel-datatables#1497]
there is a way to sort columns that are added with `addColumn` ?
can we sort this columns? or search ?

**Comment by yajra** [comment]
By default added column are not sortable searchable. You need to use `filterColumn` api and attach a handler for search and `orderColumn` for ordering.

Or another workaround is to do the column name trick:

```js
columns:[
    {data: 'addedColumn', name: 'column_name_to_search_sort'}
]
```

**Comment by grappetite-tahir** [comment]
@yajra Can you please let us know if the column name is coming from belongsToMany relationship how do we will put the name here column_name_to_search_sort
`columns:[
    {data: 'addedColumn', name: 'column_name_to_search_sort'}
]`

**Comment by grappetite-tahir** [comment]
@tnorthcutt yes exactly, I'm also willing to know how to

**Comment by yajra** [comment]
For the "column name trick" example, just remember that the `name` attribute is being used by package when performing sort / search.

```php
// js
columns:[ {data: 'fullname', name: 'last_name'} ]

// php
->addColumn('fullname', "{{ $lastname . ', ' . $firstname }}"
```

Given the snippet above, fullname is an added column but sorting and searching will be performed using the `last_name` column.

**Comment by xanxTV** [comment]
Sorry to bring up an old issue, however, I still have a burning question in regards to this.
What would I do in order to sort by edited variables? Say for example I get a variable of Smith from the column last_name.
I then processed this variable to somehow come up with returning the name John Smith, not from any column, just a function I coded. How do I then sort the column by "John Smith" instead of just "Smith" without using the last_name column?

@yajra

**Comment by tahirafridi** [comment]
> For the "column name trick" example, just remember that the `name` attribute is being used by package when performing sort / search.
> 
> ```
> // js
> columns:[ {data: 'fullname', name: 'last_name'} ]
> 
> // php
> ->addColumn('fullname', "{{ $last_name . ', ' . $first_name }}"
> ```
> 
> Given the snippet above, fullname is an added column but sorting and searching will be performed using the `last_name` column.

I understand what you are saying, I've a question if the last_name is from another table that is relative table. for example 
// js
columns:[ {data: 'fullname', name: 'employee.last_name'} ]

can we do it or there is any other way?

**Comment by emilas44** [comment]
I have the same problem... so this is what I have concluded from all of the posts before...
If you add a column with` ->addColumn('fullname', "{{ $last_name . ', ' . $first_name }}"`  function in PHP
 - it's not searchable
 - it's not sortable

To make it 'sortable' you can set the name of SOME OTHER COLUMN and it will sort it by that column with this code
`columns:[ {data: 'fullname', name: 'last_name'} ]`
and NOT by data in that column which you clicked to sort:
