### ISSUE TITLE
[Question] Filtering column that has multiple values

### ISSUE THREAD

**Issue by mleppala** [yajra/laravel-datatables#1498]
I have been trying to get a roles column to filter when it contains more than one roles but without any luck. I was wondering if anyone has successfully done this and would not mind assisting me with this issue.

 BTW, I am using Spatie Laravel-Permission package the builds the relationship between the users and roles. 

- Operating System
- PHP Version 7.1
- Laravel Version 5.4
- Laravel-Datatables Version 7.7

**Comment by yajra** [comment]
Not sure with the spatie permission db structure but using my own [acl](https://github.com/yajra/laravel-acl), this how I did it.

## PHP
```php
$query = User::with('roles')->select('users.*');

return datatables($query)
    ->editColumn('roles', '... edited value with styles')
    ->toJson();
```

## JS
```
columns: [
    ...
    {data: 'email', name: 'email}
    {data: 'roles', name: 'roles.name', orderable: false}
    ...
]
```

**Comment by mleppala** [comment]
Yajra, thanks for the reply. Spatie permission creates a pivot table between the users and roles. My users can have more than one roles, e.g. Registered User and Moderator.  I have a selection box filter that I would like to use to display all user in a particular role. So I need to filter the pivot table and then get the  user information from each of the user ids in the pivot table. This is where I cannot figure out how this should work. I do have other filters like the for the active state of the user, last visit date, etc., which the data is located in the user table.

The roles table contains an id and name columns.
The pivot table has user_id and role_id columns.

My query looks like:

```
$users = User::with('roles')->select(
   'users.id', DB::raw("CONCAT(users.firstName, ' ', users.lastName) AS full_name"),
      'users.firstName',
      'users.lastName',
      'users.username',
      'users.blockUser',  <--has a filter
      'users.activation',  <--has a filter
      'users.email',
      'users.lastVisitDate',  <--has a filter
      'users.created_at'
);
```

my filter for the roles is:
```
$r = Datatables::of($users)->filter(function ($query) use ($request){
     if ($request->has('group') && $request->get('group')){`
          $query->Where('roles.id', $request->get('group'));`
     }
})->make(true);
```

When I use the filter for the roles I get this error message

![image](https://user-images.githubusercontent.com/24446339/32584616-50ca8044-c4c7-11e7-86d3-035133f93ab3.png)

Which is telling my that I cannot filter the id of the selected role. So do you have any suggestions on how can I get this query to work with the pivot table and filter properly?

**Comment by mleppala** [comment]
I managed to figure out the issue with filtering the user based on the roles. I know that I am no expert when it comes to Laravel but being a good problem solver, I realized that I need to look at this issue in a different way. I decided to look at the problem from the top down view to see if the way of filtering the users by the roles was the correct path. Looking from the top down I found two things. 

The first thing I found was that I do not see how I would be able to filter the user based on the roles using the User query even with roles attached. With still learning the facets of Laravel I could be wrong and it would not be the first time I have worked with new software and I find myself hitting a wall and I look for a way around the wall.  If I do not have to go around the wall and someone knows that way then please let me know. 

The second thing I found was that all I really is the user ids that belong to a single group. By getting all these user ids then I could use them to filter the User query. So, for anyone else that might find this useful for them here is how I got the group filter to work.


User query:
```
$users = User::select(
            'users.id',
            DB::raw("CONCAT(users.firstName, ' ', users.lastName) AS full_name"),
            'users.firstName',
            'users.lastName',
            'users.username',
            'users.blockUser',
            'users.activation',
            'users.email',
            'users.lastVisitDate',
            'users.created_at'
        );
```
Group filter
```
     if ($request->has('group') && $request->get('group')){
          $userIds = DB::table('user_has_roles')->select('user_id')->where("role_id",$request->get('group'))->pluck('user_id');
                    $query->whereIn('id', $userIds);
     }

Thanks again yajra  for your reply
