### ISSUE TITLE
[Question] how to add form action, method patch, and csrf field in my return on addcolumn ?

### ISSUE THREAD

**Issue by ndar0430** [yajra/laravel-datatables#1499]
since i dont need to input anything on my update. i just want to click the Claim button and it updates.
when i do that it just redirects me on a blank page with the id url 
ex(asfdf.com/employee/1?)

` return <a href="' . route("readderauditing.update", $readderauditing_table->re_auditID) . '"  class="btn btn-xs btn-danger"><i class="fa fa-plus-circle" aria-hidden="true"></i>Claim</a>`

**Comment by yajra** [comment]
Try using ajax instead with some jquery click events?

```js
    $(function(){
        $('body').on('click', 'a.claim', function() {
            $.ajax({
                ...
            })
        })
    });
```

**Comment by blok-0** [comment]
I had this error but i tried whit this code:

In controller:
`return '<a href="Inventario/'.$producto['producto_id'].'/edit" class="btn btn-info btn-xs pull-left right15" rel="tooltip" data-animate="animated bounce" data-toggle="tooltip" data-original-title="Editar registro" data-placement="top"><i class="fa fa-pencil" ></i></a>
              <button class="btn btn-xs btn-danger pull-left right15 btn-delete" data-remote="Inventario/'.$producto['producto_id'].'">x</button> ';})->make(true);`

View
`$('#tabla').DataTable().on('click', '.btn-delete[data-remote]' ,function (e) {
          e.preventDefault();
          var url = $(this).data('remote');
          if(confirm("¿Seguro que deseas eliminar?")){
            $.ajax({
                url: url,
                type: 'DELETE',
                dataType: 'json',
                data: {method: '_DELETE'},
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
            }).always(function (data) {
                $('#tabla').DataTable().draw(false);
            });
          }
      });`

I did not find another easier way.
If you find it tell me how. Sorry for my english
