### ISSUE TITLE
Non-searchable column causing AJAX errors

### ISSUE THREAD

**Issue by judgej** [yajra/laravel-datatables#150]
I have use `addColumn()` to create a custom column that comes from a calculation performed outside of the database; it is just derived from an arbitrary closure. The table appears fine, the pager works, and ordering by other columns works.

Now, when I try to search on the table, I get a 500 AJAX error from from the server. I'm guessing it is trying to search on that column. How do I tell the back-end not to search on that custom column, since it is not a column in the database?

I was hoping it would be something simple like the `'searchable': false` flag on the front end, but I cannot see anything like that.

**Comment by judgej** [comment]
Oh, I've just made the problem go away by replacing the data query object with an eloquent object. I did have this in my query controller:

    $records = Datatables::of(Transaction::withTrashed()->select('*'));
    $records->addColumn(...);
    return $records->make(true);
    // Returns yajra\Datatables\Engines\EloquentEngine

Now I'm starting with this instead, only replacing `select('*')` with `get()`:

    $records = Datatables::of(Transaction::withTrashed()->get());
    $records->addColumn(...);
    return $records->make(true);
    // Returns yajra\Datatables\Engines\CollectionEngine

I'm selecting trashed records just to test a few things.

**Comment by yajra** [comment]
@judgej, `searchable: false, orderable: false` for `addColumn` should fixed the searching issue. Can you paste some snippets on ajax error? There might be something else that is breaking your code.

You can indeed use collection engine approach to fix your issue on `addColumn` being searchable, however, please note that it may cause some performance issues when your db becomes large as it will load all records at once.

**Comment by judgej** [comment]
Of course - don't know what I was thinking there. `get()` do the fetch, then `Datatables` filters those results *after* they are fetched from the database.

So setting what is searchable at the front end (in the browser) presumably means the AJAX backend will blindly search for whatever it has been asked to search. There aren't any risks of a malicious party injecting other stuff in here, is there, such as secure fields that they should never be able to look at? I realise the "*" could be replaced with field names in the `select()` part, but it's just a thought I have whenever I see something like this controlled at the front end and not mirrored at the back end.

Back to my original problem, it turns out the error may have been another column.

I have a database column "transaction_type". On the table at the front end I want to label it "Type" (`<th>Type</th>`). In my `columns` list I have this entry for it:

    { data: 'transaction_type', name: 'type' }

The `data` attribute matches the data coming from the server through the AJAX call. The `name` attribute then matches that data against the correct column in the table, and it displays fine.

However, when I do a search, the search is sent to the server against the `type` database column, which does not exist, rather than the `transaction_type` column. The back end just says, "yeah, whatever I'll put that into the query" and so we get this error:

> Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as row_count from `transactions` where (LOWER(`id`) LIKE %a% ... or *LOWER(`type`) LIKE %a%* ...

**Comment by judgej** [comment]
Finding how to set up that front end correctly in the documentation is really hard, as there are too many different places where this project is documented, all completed to different levels.

**Comment by yajra** [comment]
@judgej, basically this is how the package interprets Datatables ajax call column parameters. On js columns attributes:
```js
columns: [
  {
  data: 'key used in json response',
  name: 'column name to be used in searching and ordering query',
  searchable: 'flag to check if the package will search this field using the name as column',
  orderable: 'flag to check if the package will order this field using the name as column'
  }
]
``` 

In addition, the package will only search on fields you specified on `columns` array attributes. So even if you issued a `select('*')` on server side, the package will not search on protected columns unless specified.

**Comment by yajra** [comment]
Back to your issue. `{ data: 'transaction_type', name: 'type' }` needs to be updated to `{ data: 'transaction_type', name: 'transaction_type', title: 'type' }` for it to work properly on search.

**Comment by judgej** [comment]
Thank you, that's a great help.

**Comment by judgej** [comment]
I'll close this for now, as the front-end settings (Datatable "options") work for now, and I have a way forward to limit which columns are fetched at the back end. I feel like I have be revisiting some of this again, but that's for another day :smile:

Thanks for your help.
