### ISSUE TITLE
Order column doesn´t work in 8.*

### ISSUE THREAD

**Issue by vanrijs** [yajra/laravel-datatables#1500]
Hi,

We upgraded today to 8.3 but our order doesn't work anymore. 
We did no further changes to the code, just followed the upgrade guide. 
When i select a column to order, i get the order data in the console. But response is the same. 

Any ideas?

**Comment by yajra** [comment]
Can you please provide some snippets to reproduce the issue? Will check this as soon as I can. Thanks!

**Comment by vanrijs** [comment]
Hi Yajra,

Dont know if is ok but i also send you a screencast! 
Here is my code:

```
            <script type="text/javascript">
                $(document).ready(function() {

                    var oTable = $('#datatable').dataTable({
                        processing: true,
                        serverSide: true,
                        iDisplayLength: 20,
                        stateSave: true,
                        lengthMenu: [[10, 20, 50, 100, 250], [10, 20, 50, 100, 250]],
                        ajax: {
                            url: "{{ route( 'backend.lead.datatables' ) }}",
                            data: function (d) {
                                d.status = '{{ isset($status) ? $status : '' }}';
                                d.status_id = $("select#status option:selected").val();
                                d.user = '{{ isset($user) ? $user->id : '' }}';
                            }
                        },
                        columns: [
                            { data: 'label', searchable: false, orderable: false },
                            { data: 'name', orderable: false},
                            { data: 'address', orderable: false},
                            { data: 'intermediair', orderable: false, searchable: true},
                            { data: 'created_at', name: 'created_at', orderable: true },
                            { data: 'follow_up_at', name: 'follow_up_at' },
                            { data: 'updated_at', name: 'updated_at' },
                            { data: 'products', searchable: false, orderable: false },
                            { data: 'status', orderable: false, searchable: false },
                            { data: 'action', name: 'action', orderable: false, searchable: false }
                        ],
                        order: [[5, 'asc']],
                        drawCallback : function() {
                            OnloadFunction();
                        }
                    }
                    );
```

I downloaded also the newest bootstrap files( <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>) 

This is exactly the same code as yesterday (when it worked). I just followed the upgrade guide. I checked also other pages with datatables and there is the sort option also broken.

**Comment by vanrijs** [comment]
I think it has something to do with a date format. We use: "dd-mm-YYY H:i" 
I just tried to order an increment ID and that is working fine.

**Comment by vanrijs** [comment]
Some new findings: live i used 7.5.2. A really specific version. I just remembered i have seen this issue earlier. I tried local to downgrade to 7.* (7.10) and there i got the same issue. I can't sort on a date anymore. 
There is something wrong anywhere in the code after v7.5.2 (of maybe a version later).
Hope you can find out what!

**Comment by marcelogarbin** [comment]
@vanrijs I have the date format in pt_br (21/11/2017 13:55:00), I tried to use the filterColumn(), but I didn't succeed.

```
->filterColumn('data_hora', function ($query, $keyword) {
                    $query->whereRaw("DATE_FORMAT(data_hora,'%d/%m/%Y %H:%i:%s') like ?", ["%$keyword%"]);
                })
```

My version is: v7.10.1

Did you get this to work?

Thank's

**Comment by vanrijs** [comment]
Any updates on this one?
I just upgraded again to 8.3 to try to fix this one.
I thought: maybe it is my formatted date so i made a numeric number from is:
`            ->addColumn('updated_at', function ($contract) {
                return ($contract->updated_at) ? $contract->updated_at->format('dmYHi') : '';
            })
`

A date without - or /. Still no result :(

**Comment by vanrijs** [comment]
Ok i get it. Must be edit in the core of datatables ;)

I join other tables in my query. In my old situation it was:
`                            { data: 'updated_at', name : 'updated_at'},`

Just updated it to: 
`                            { data: 'updated_at', name : 'contracts.updated_at'},`
