### ISSUE TITLE
SetRowId with FixedColumns

### ISSUE THREAD

**Issue by legreco** [yajra/laravel-datatables#1501]
### Summary of problem or feature request

Normally when you use setRowId On server side, each tr have a id. It works fine. But when i add fixed column on client side the id is removed.

### System details

- Operating System: Windows 10
- PHP Version: 7.x
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.9.x

**Comment by yajra** [comment]
I think this is a issue on the javascript level and is out of scope of the project. Maybe try asking on the main js library forum at datatables.net. Thanks!
