### ISSUE TITLE
getting errors on AZURE(yajra please reply)

### ISSUE THREAD

**Issue by ndar0430** [yajra/laravel-datatables#1502]
### Summary of problem or feature request

i'm encountering an error on my datatables on columns  IN AZURE even though i uploaded the exact local file on my homestead which is working into azure through git.

![1x](https://user-images.githubusercontent.com/21249443/32612323-f10c3c4c-c5a2-11e7-9534-51191fd9f422.jpg)
![2x](https://user-images.githubusercontent.com/21249443/32612324-f188fe80-c5a2-11e7-88e4-abe0abd19d46.jpg)

**Comment by yajra** [comment]
This must a server config issue. What error is returned on the console?

**Comment by yajra** [comment]
I haven't used azure but maybe this would help: https://datatables.net/forums/discussion/41274/upload-and-view-files-from-azure

**Comment by ndar0430** [comment]
I don't think thats the right solution for my problem but look at this.

![image](https://user-images.githubusercontent.com/21249443/32690560-b2775f88-c733-11e7-9c5a-1d7c4a9c09a4.png)

![image](https://user-images.githubusercontent.com/21249443/32690590-10851f34-c734-11e7-82c6-8481d051a74f.png)
