### ISSUE TITLE
Modify column search text values

### ISSUE THREAD

**Issue by alr2413** [yajra/laravel-datatables#1504]
### Summary of problem or feature request

Hi Yajra, 
Thanks for this awesome package.
As you might know in Persian/Arabic language, there is some letters with the same sound but different keyboard layout notation. This difference cause problem in filtering since when someone tries to type on a keyboard with Persian layout it writes "ی" as a character and on a Arabic layout keyboard it writes "ي". So if a person searches for 'بازی' the query won't find 'بازي' as the result.
To solve the problem of inserting data to database, I wrote a simple trait to replace all these characters; and thus all of the stored data has the Persian (or Arabic) letters.

Now my problem is that when someone types in the header/footer text-boxes of column search of my table, if those unwanted characters are not replaced before the execution of search query, then no result is returned.
I want to solve this problem globally for all of my datatables used in my project. I found that in QueryDataTable class there is some method like "columnSearch() at line 215" that extract search keywords from the request. Temporarily, I can make change on this method but I'm looking for better way like overriding it on my custom datatable class.
I also found that there is an "engines" option in datatables.php config file that we can register our builder, but I don't know how to do that.

Thanks a lot.

### System details

- Operating System: MacOS High Sierra
- PHP Version: 7.1
- Laravel Version: ^5.5
- Laravel-Datatables Version: ^8

**Comment by yajra** [comment]
I think you can work this around using a middleware and convert all inputs as necessary. Maybe something like:

> Note: This code is not tested. Adjust it to your needs.

```php

namespace App\Http\Middleware;

use Closure;

class InputConverter
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        collect($request->all())->each(function($value, $key) {
            $value = convert($value);
            $request->merge([$key => $value]);
        });

        return $next($request);
    }
}
```

**Comment by alr2413** [comment]
Thanks a lot.
 As you mentioned, my problem is solved by using the below middleware:

namespace App\Http\Middleware;

use Closure;

class PersianInputConverter
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        collect($request->all())->each(function ($value, $key) use ($request) {
            $value = replaceKeyboardChars($value);
            $value = replacePersianNumbers($value);
            $request->merge([$key => $value]);
        });
        return $next($request);
    }
}
