### ISSUE TITLE
Datatables not loading the config file

### ISSUE THREAD

**Issue by pesovski** [yajra/laravel-datatables#1505]
### Summary of problem or feature request

I'm running Laravel 5.4 and Datatables 7.10.1

I have issue that the engines and builders in Datatables are empty and I cannot use Datatables as a result of that. I'm referring to this:

(vendor\yajra\laravel-datatables-oracle\src\Datatables.php
```php
49: $config     = app('config');
50: $engines    = $config->get('datatables.engines');
51: $builders   = $config->get('datatables.builders');
```
Both $engines and $builders are null

The exact issue that I get is: 
_Invalid argument supplied for foreach() in Datatables.php (line 57)_
and that is the following code:
```php
57: foreach ($builders as $class => $engine) {
58:            if ($source instanceof $class) {
59:                $class = $engines[$engine];
60:
61:                return new $class($source, $datatables->getRequest());
62:            }
63:        }
```

### System details

- Operating System : Linux
- PHP Version: 7
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.10.1

**Comment by ElfSundae** [comment]
`1.10.11` ?

**Comment by pesovski** [comment]
Sorry, it's v7.10.1, my bad.

**Comment by ElfSundae** [comment]
Did you register the service provider? 

```php
Yajra\Datatables\DatatablesServiceProvider::class
```

**Comment by pesovski** [comment]
Yes, I added the service provider to providers array and added alias in the aliases array in app.php.
I run 'php artisan vendor:publish'
I run 'composer dump-autoload'

**Comment by ElfSundae** [comment]
Did you change something in your `config/datatables.php` before? If not, you can delete this file, then run your application.
If this does not help, sorry I don't know how it happened, maybe you could try reinstalling packages:

```sh
rm -rf vendor
composer update # or composer install
```

**Comment by pesovski** [comment]
I don't have a datatables.php file in the config/ folder.

I did remove the vendor now and run composer install, but I still get the same error .

**Comment by pesovski** [comment]
Fixed it by removing bootstrap/config.php

For some reason `php artisan cache:clear` wouldn't clear the cache and the Datatables service provider was never registered.
