### ISSUE TITLE
$(...).DataTable is not a function

### ISSUE THREAD

**Issue by msbir** [yajra/laravel-datatables#1506]
I installed the package, for some reason, it always gets me the error
$(...).DataTable is not a function

**Loading the scripts that way on my main layout -** 

    <script src="//code.jquery.com/jquery.js"></script>
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    @stack('scripts')

**on the specific view -**

    @push('scripts')
    <script>
        $(function() {
            $('#products-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('categories.index') !!}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'name', name: 'name' },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'updated_at', name: 'updated_at' }
                ]
            });
        });
    </script>
    @endpush

- Operating System - macOS
- PHP Version - 7.0.24
- Laravel Version - 5.5
- Laravel-Datatables Version - 8.0

**Comment by yajra** [comment]
I think the issue here is on the arrangement of you scripts. Better check the source code on the browser and check that it is loaded on the correct order.
