### ISSUE TITLE
blacklist array do not applies

### ISSUE THREAD

**Issue by lgt** [yajra/laravel-datatables#1507]
having created datatables config and including more fields to blacklist array does not work, I see further the fileds in the json response
`
'blacklist' => ['password', 'remember_token', 'passwort', 'account_pwd'],`

adding directly to the DataTable object `->blacklist('passwort')` does not work either

cleared cache, view

My working datatables version

`"yajra/laravel-datatables-oracle": "8.0.3",`

am I missing something?

**Comment by yajra** [comment]
I think what you need is excess columns or `removeColumn('password', 'remember_token', 'passwort', 'account_pwd')`. Blacklist only disables searching/sorting functionality.

See https://yajrabox.com/docs/laravel-datatables/master/blacklist for ref.
