### ISSUE TITLE
Redis Caching Search

### ISSUE THREAD

**Issue by seivad** [yajra/laravel-datatables#1509]
### Summary of problem or feature request

Caching using Redis issues, receiving ```You cannot serialize or unserialize PDO instances``` after trying multiple combinations / versions. Is there anyway to actually cache the results, if you could provide an example that would be good as Google didn't return much to solve this issue. I tried ->get(), ->select('*'), ->query() etc...

### Code snippet of problem

*Truncated...*
```
$projects = Cache::remember('projects', $this->cacheTime, function () {
            return Project::with('representative', 'company', 'builder', 'files', 'users', 'tags', 'notes', 'location')->select('projects.*');
        });

        return DataTables::eloquent($projects)->toJson();
```

### System details

- OSX
- 7.1
- 5.5
- master

**Comment by yajra** [comment]
I think this is an issue with the framework and is out of scope of the project. 

Anyways, as the error indicated, PDO cannot be serialized hence you need to use collection instead. But using collection may hit a performance issue. Thanks!
