### ISSUE TITLE
Only getting json returned - no datatable displayed

### ISSUE THREAD

**Issue by sivon12** [yajra/laravel-datatables#151]
Hello Arjay, I have been trying to get a variation of your example working in Laravel 5, which I am new to, but I only ever get json returned to ...datatables/data and I can't see what is wrong

My view looks like this
![image](https://cloud.githubusercontent.com/assets/13921982/9425763/43dc974e-4915-11e5-99d8-8ea0f5c7f40e.png)

![image](https://cloud.githubusercontent.com/assets/13921982/9425772/fea20726-4915-11e5-908e-77beba214b58.png)
![image](https://cloud.githubusercontent.com/assets/13921982/9425774/0372a1fc-4916-11e5-9017-60369b104434.png)

Routes:
![image](https://cloud.githubusercontent.com/assets/13921982/9425788/a0fe8c38-4916-11e5-94e4-82d51252dd50.png)

The json I get back from datatables/data is
{"draw":0,"recordsTotal":2,"recordsFiltered":2,"data":[{"distno":211,"distname":"BOLTON"},{"distno":072,"distname":"GLOUCESTERSHIRE"}],"queries":[{"query":"select count(*) as aggregate from (select '1' as row_count from `districts`) count_row_table","bindings":[],"time":3},{"query":"select * from `districts`","bindings":[],"time":1}],"input":[]}

But I always get no contents in the table. Any idea what is wrong? Controller seems fine, and as I am getting json out I am guessing it is the view or javascript that is wrong, but as I'm a newbie and I've spent hours on this I could really do with some pointers.
Many thanks

**Comment by yajra** [comment]
@sivon12 , your code seems fine. Are you sure you have data on `districts` table? `select * from districts` query was executed as per response json. One way to test your query is to just return your model directly from your controller like:
```php
function anyData(){
  return District::all();
}
```

**Comment by yajra** [comment]
I just noticed that you have a response data `[{"distno":211,"distname":"BOLTON"},{"distno":072,"distname":"GLOUCESTERSHIRE"}]`. Maybe there are some js scripts error that is causing it not to display. Better inspect your page using dev tools.

**Comment by sivon12** [comment]
Many thanks Arjay - you were right, it was a js error. I had missed the closing ] on the end of the columns data within the Datatables javascript. Working fine now - thanks so much for pointing me in the right direction.

**Comment by yajra** [comment]
Your welcome! Closing the issue.
