### ISSUE TITLE
Class Yajra\Datatables\Html\Builder does not exist

### ISSUE THREAD

**Issue by vijaysebastian** [yajra/laravel-datatables#1513]
### Summary of problem or feature request

I have installed 

```
"yajra/laravel-datatables-oracle": "~8.0",
"yajra/laravel-datatables-html":"^3.0",
```
When I try to render the table, I am getting `Class Yajra\Datatables\Html\Builder does not exist`

### System details

- Operating System
- PHP Version 7.0
- Laravel Version 5.5
- Laravel-Datatables Version "yajra/laravel-datatables-oracle": "~8.0",

**Comment by ElfSundae** [comment]
Namespace updated, see https://yajrabox.com/docs/laravel-datatables/master/upgrade
