### ISSUE TITLE
[Proposal] Prevent withCount bug when searching

### ISSUE THREAD

**Issue by carusogabriel** [yajra/laravel-datatables#1520]
Recently, I've tried to use `Laravel Datatables` and `Eloquent` method `withCount`. Everything worked fine until I tried to search. I receive an error:
```php
[13:11:30] LOG.error: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'courses.periods_count' in where clause.
```

I resolve this issue by simply adding `searchable: false` in the `periods_count` initialization.

Should we add this to all `{relation}_count` field to prevent this errors in other people projects?

**Comment by yajra** [comment]
withCount is indeed not searchable so the correct solution is to set it as searchable false.

Not sure though on adding exception on `{relation}_count`. There might be some users that designs their DB to have a column like that and populate it on save. I have something similar where total are being computed when saving a record. So I guess that might be true for counts?

**Comment by gabriel-caruso** [comment]
Is there a way to figure out if the relation [`withCount`](https://laravel.com/docs/5.5/eloquent-relationships#counting-related-models) was set? Then we could automatically set `searchable` to `false`.
