### ISSUE TITLE
[Feat.Req / Question] set stateSave: true in config\datatables.php file

### ISSUE THREAD

**Issue by bhaumik-sassyinfotech** [yajra/laravel-datatables#1521]
Is there a way by which we can configure in file `config\datatables.php` so that is set `stateSave: true` for all the instances of yajratables in the application.
FYI: I am using Laravel 5.5.

currently It's working fine with:

$.extend(true, jQuery.fn.dataTable.defaults, {
    "stateSave": true,
});
but it would be great if would get this setting out of the box.

**Comment by yajra** [comment]
If you are using this main package, then I guess using extended defaults via js is the correct solution for this.

However, is you are using the buttons or html plugin, then the are some config and script stub that you can adjust to your needs.

**Comment by sagarpatel9697** [comment]
@yajra Can you please show us some example like how we config it in datatable-html.php or datatable-button.php configuration file?
