### ISSUE TITLE
Column sorting - filterColumn is not working

### ISSUE THREAD

**Issue by garbinmarcelo** [yajra/laravel-datatables#1522]
### Summary of problem or feature request
Column sorting is not working as expected when you have a formatted date.
![test](https://user-images.githubusercontent.com/9335588/33172410-2715b220-d037-11e7-8b69-18a3eed7a619.gif)

### Code snippet of problem
```php
->filterColumn('data_hora', function ($query, $keyword) {
   $query->whereRaw("to_char(data_hora,'DD/MM/YYYY HH:MI:SS') like ?", ["%$keyword%"]);
})
```

Complete Code:
```php
public function ajaxListarRegistrosCadastrados(Request $request)
    {
        if($request->ajax()) {
            $registros = Noticia::select(['id', 'titulo', 'data_hora', 'data_hora_agendamento', 'updated_at', 'fixa', 'status', 'visualizacoes']);

            return Datatables::of($registros)
                ->addColumn('categoria', function($registro){
                    $categoria = (isset(Noticia::withTrashed()->find($registro->id)->categoria))? Noticia::withTrashed()->find($registro->id)->categoria->nome : null;
                    if($categoria)
                        return $categoria;
                    else
                        return '-';
                }, 2)
                ->addColumn('action', function ($registro) {
                    $edit   = null;
                    $delete = null;
                    if(Auth::user()->hasPermission($this->rota.'.edit')){
                        $edit   = '<a href="'. route($this->rota.'.edit', Hashids::encode($registro->id)) .'" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>';
                    }
                    if(Auth::user()->hasPermission($this->rota.'.destroy')){
                        $delete =  Form::open(['route' => [$this->rota.'.destroy', Hashids::encode($registro->id)], 'method' => 'DELETE', 'class' => 'form-inline']).
                            '<button type="submit" class="btn btn-sm btn-danger btn-lixeira" data-id="'.$registro->id.'" data-toggle="tooltip" data-placement="top" title="Deletar"><i class="fa fa-trash-o" aria-hidden="true"></i></button>'.
                            Form::close();
                    }

                    if(!isset($edit) && !isset($delete)){
                        $acao = '<span data-toggle="tooltip" title="Você não possui permissão para executar ações neste módulo!"><i class="fa fa-info-circle" aria-hidden="true"></i></span>';
                    }else{
                        $acao = $edit.$delete;
                    }

                    return '<div class="acao text-center">'.$acao.'</div>';
                })
                ->editColumn('data_hora_agendamento', function($registro){
                    if($registro->data_hora_agendamento)
                        return $registro->data_hora_agendamento;
                    else
                        return '-';
                })
                ->filterColumn('data_hora', function ($query, $keyword) {
                    $query->whereRaw("to_char(data_hora,'DD/MM/YYYY HH:MI:SS') like ?", ["%$keyword%"]);
                })
                ->escapeColumns(['action'])
                ->removeColumn('deleted_at')
                // regra que verifica se o status existe e se é inativo, adiciona class alert-danger
                ->setRowClass(function($registro){
                    return (isset($registro->status) && $registro->status == 'Inativo')? 'alert-danger' : null;
                })
                ->make();
        }else{
            return redirect()->route('login');
        }
    }
```

I also use the following mutator:
```php
public static function FormataDataHoraPadrao($data){
 return Carbon::parse($data)->format('d/m/Y H:i:s');
}
```

### System details
- Operating System: homestead
- PHP Version: 7.1
- Laravel Version: 5.4.36
- Laravel-Datatables Version: 7.10.1

**Comment by mleppala** [comment]
I believe what you are looking for is columns.render option. The [columns.render](https://datatables.net/reference/option/columns.render) option will allow you to to have different formats for display, sort and filtering. So you can use the sort parameter to use timestamp and the display parameter to a date/datetime formatted how you need it.

```
<script>
oTable = $('#users-table').DataTable({
    columns: [
        {
            data: 'data_hora',
            name: 'data_hora',
            type: 'num',
            render: { _: 'display', sort: 'timestamp'}
        }]
});
</script>
```

and on your Datatables controller
```
public function ajaxListarRegistrosCadastrados(Request $request)
    {
        if($request->ajax()) {
            $registros = Noticia::select(['id', 'titulo', 'data_hora', 'data_hora_agendamento', 'updated_at', 'fixa', 'status', 'visualizacoes']);

            return Datatables::of($registros)
            ...
               ->editColumn('data_hora', function($registro) {
                        return [
                            'display' => e($registro->data_hora ? FormataDataHoraPadrao($registro->data_hora) : 'None'),
                            'timestamp' => $registro->data_hora->timestamp
                        ];
                })
        ...
}

```

**Comment by marcelogarbin** [comment]
I still can not make it work... =/

**Comment by mleppala** [comment]
Maybe I should have started off with what your are expecting to see and what you are seeing? I know that you put up that little time loop video but it is to hard to see what your are having issues with without more details.  

Why do you think the issue with filter for data_hora?

**Comment by marcelogarbin** [comment]
@mleppala The column is not being sorted. Example I passed, I have date with year of 2017 in November, but he does not order if you notice. The first column where it says Data.

The reason is maybe I was using a formatted date, as I'm using calls via AJAX, I do not know how to put the attributes for example in the row in the table, in the case of timestamp, I believe that sorting by timestamp works.

Would you have any tips?

I try to use:
```php
->editColumn('data_hora', function($registro) {
                        return [
                            'display' => e($registro->data_hora ? FormataDataHoraPadrao($registro->data_hora) : 'None'),
                            'timestamp' => $registro->data_hora->timestamp
                        ];
                })
```

return:
DataTables warning: table id=table0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

What does this "e($registro->data_hora ? FormataDataHoraPadrao($registro->data_hora) : 'None')," operator do? ... `e()` I do not know in php yet ..So I notice it's a ternary if.. right?

**Comment by yajra** [comment]
@marcelogarbin can you dump the ajax response error after performing the sort function? Must be some error on generated SQL.

**Comment by marcelogarbin** [comment]
@yajra was some ajax error same, I adjusted,
I used the following for testing:
```php
->editColumn('data_hora', function($registro) {
                    return [
                        'display'        => 'test',
                        'timestamp' => 00
                    ];
                })
```

but the following appears to me:
![data](https://user-images.githubusercontent.com/9335588/33261145-0897f67c-d349-11e7-823b-5e7dfc4f6666.png)

**Comment by marcelogarbin** [comment]
@yajra For example, how do I use HTML5's datatables in this package?
In this case I could use the attribute, data-order: `<td data-order="1303689600">Mon 25th Apr 11</td>`

https://www.datatables.net/examples/advanced_init/html5-data-attributes.html

**Comment by marcelogarbin** [comment]
@mleppala I use js code for several tables in the same view, so far it works fine.

JS Code: https://jsfiddle.net/marcelo_garbin/n2Lxjewj/

I don't do individual JS code for each table because I use AJAX. I think it would not make sense and it would be a hard job for every table.

I didn't know "method-e", thanks

**Comment by yajra** [comment]
>@yajra For example, how do I use HTML5's datatables in this package?
In this case I could use the attribute, data-order: <td data-order="1303689600">Mon 25th Apr 11</td>
> https://www.datatables.net/examples/advanced_init/html5-data-attributes.html

@marcelogarbin afaik, data-* attributes is only applicable on the client side implementation and not on the server-side.

With regard to column sorting, you can also use [orderColumn](https://yajrabox.com/docs/laravel-datatables/master/order-column).

**Comment by mleppala** [comment]
@marcelogarbin with your JS code I was able to display the date in your format and sort. I removed code that I needed. I had to use the mRender options in aoColumnDefs options to get it display the formatted date and sort by the timestamp. 

```
	aoColumnDefs: [{
		'bSortable': false,
		'aTargets': [0]
	},
	{
		'aTargets': [1],
		mRender: function(data,type, row){
			if(type==='sort'){
				return row.data_hora.timestamp;
			}
			else {
				return row.data_hora.display;
			}
		}
	}],
```
however, in the JS code I did not see an aoColumn options and it was giving me an error.
```
DataTables warning: table id=table0 - Requested unknown parameter '0' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4
```
so I added the aoColumns options
```
     aoColumns: [
         {data:'name',name:'name'},
         {
             data: 'data_hora', name: 'data_hora',
         }
     ],
```
along with the Laravel-Datatables code
```
	return Datatables::of($users)
		->editColumn('data_hora', function($user) {
		return [
			'display'   => Carbon::parse($user->data_hora)->format('d/m/Y H:i:s'),
			'timestamp' => $user->data_hora->timestamp
		];
	})
```
I am not sure this will work for you as I wrote it but it might help you to resolving the issue. I also see that you are using legacy options. You might want to look at change these options to the current ones. you can click the link below to take you the DataTables site for converting the legacy options.

[https://datatables.net/upgrade/1.10-convert](https://datatables.net/upgrade/1.10-convert)

**Comment by marcelogarbin** [comment]
@mleppala Why use?
```
   aoColumns: [
         {data:'name',name:'name'},
         {
             data: 'data_hora', name: 'data_hora',
         }
     ],
```

Where does this fit into my code since I use multiple tables dynamically?

I still do not understand and could not make the order work properly.

**Comment by marcelogarbin** [comment]
I think it's some problem with my Controller. I just did it this way:
```php
 $registros = Noticia::select(['id', 'titulo', 'data_hora', 'data_hora_agendamento', 'updated_at', 'fixa', 'status', 'visualizacoes']);
return Datatables::of($registros)->make();
```

And it worked as expected, I'll give it a revision in the encoding, strange that I do not see anything wrong, because the rest works normally.

**Comment by marcelogarbin** [comment]
Ordination is already lost when I make this form:
```php
return Datatables::of($registros)
                ->addColumn('categoria', function($registro){
                    $categoria = (isset(Noticia::withTrashed()->find($registro->id)->categoria))? Noticia::withTrashed()->find($registro->id)->categoria->nome : null;
                    if($categoria)
                        return $categoria;
                    else
                        return '-';
                }, 2)
                ->make();
```

@yajra Any suggestions for fixing this?

**Comment by mleppala** [comment]
@marcelogarbin As i stated that it might not work as I figured that your tables would not have the same layout and that it might lead you the in the the direction that might narrow down the the solution.

**Comment by marcelogarbin** [comment]
In place of "addColumn" I wrote "editColumn", changing the function to:
```php
->editColumn('id_categoria', function($registro){
                    $categoria = (isset(NoticiaCategoria::withTrashed()->find($registro->id_categoria)->nome))? NoticiaCategoria::withTrashed()->find($registro->id_categoria)->nome : null;
                    if($categoria)
                        return $categoria;
                    else
                        return '-';
                })
```
That way the ordering worked correctly. But if I use the same function for "addColumn" it is as in the 1st post I did, in the case not functional.

Would this be a bug?

**Comment by yajra** [comment]
@marcelogarbin good point. `addColumn` disables/adds the column on blacklist while `editColumn` does not. It is an expected behavior but might not be documented well. Sorry for that.

**Comment by marcelogarbin** [comment]
@yajra I believe I understood, in the "`addColumn`" case, it would only serve columns that do not require sorting, right? If yes, you can close this issue =)

Thank's
