### ISSUE TITLE
how share a search

### ISSUE THREAD

**Issue by mromero91** [yajra/laravel-datatables#1524]
How can share a result ?

**Comment by yajra** [comment]
Just an idea but haven't tried this yet:

1. Create a button that appends the search value on the current url. User can use this as the share button? Or update the current url every time a search was made?

2. When loading the page, check first if the search query param is set. If yes, set dataTables search value then trigger draw to load the appropriate data.

Will also try to do this too when I got the chance. Thanks!

**Comment by RohanSakhale** [comment]
1. Quick easy way, using GET URL parameters (request parameters) for doing search filters
2. Integrate any URL shortener and shorten the URL with search Parameters
3. Share the shortened URL easily
