### ISSUE TITLE
[Question] Hiding pagination when there is only one page when filtering

### ISSUE THREAD

**Issue by mleppala** [yajra/laravel-datatables#1527]
Is there a way to hide the pagination controls when there is only one page that display after you filter the table with and filtering, like text search, column filter and page length? 

- Operating System Win10
- PHP Version 7.1
- Laravel Version 5.4
- Laravel-Datatables Version 7.7

**Comment by yajra** [comment]
I think you would need to create your own pagination plugin for this. See https://datatables.net/plug-ins/pagination/ for ref.

**Comment by mleppala** [comment]
@yajra thanks! that was what I needed.
