### ISSUE TITLE
Filters in a dedicated row

### ISSUE THREAD

**Issue by samuelecarpene** [yajra/laravel-datatables#1529]
### I want to place filters in a dedicated row under header

After some search in the code i found the method
```
public function table(array $attributes = [], $drawFooter = false, $drawSearch = false)
```
and saw that ther is a drawSearch  parameter.
Can someone tell me how to use this new row? Any example that i can see?

If i use this 
```
{!! $dataTable->table([], false,true) !!}
```
datatable render 2 rows in thead but the second that i want to use for filters is always used for sorting (so i'm not able to use search with filters).
How can i move sorting in the first header row?

**Comment by yajra** [comment]
See this https://github.com/yajra/laravel-datatables-html/pull/23/files for details.

Using the buttons plugin, I think this is how it's done. Just set the search attribute on the column declaration.

```php
public function getColumns() {
    return [
        'id' => ['search' => '<input />']
    ]
}
```

**Comment by samuelecarpene** [comment]
I used it in this manner but the datatables insert sorting in the celll where is rendred the input, so the input is deleted and the cell is used for sorting.

**Comment by lk77** [comment]
Hello,

you will need to use `"orderCellsTop" => true` in the datatable configuration to prevent the sorting behaviour on the second row.
