### ISSUE TITLE
Class 'Yajra\DataTables\DataTablesServiceProvider' not found

### ISSUE THREAD

**Issue by cse111** [yajra/laravel-datatables#1531]
### Summary of problem or feature request

I have installed package version 5 but it says Class 'Yajra\DataTables\DataTablesServiceProvider' not found. 

### System details

- Operating System:Windows 7
- PHP Version: 5.6.4
- Laravel Version: 5.3.*
- Laravel-Datatables Version: ~5.0

**Comment by RohanSakhale** [comment]
Try using the latest version of Laravel and DataTables.

With the new feature called auto-discover in Laravel 5.5, this issue is avoided.

**Comment by yajra** [comment]
Use `Datatables` on versions lower than v8 or check the branch that corresponds to the version like https://github.com/yajra/laravel-datatables/tree/5.0 for a more accurate documentation. Thanks!
