### ISSUE TITLE
Why is https://datatables.yajrabox.com/ down?

### ISSUE THREAD

**Issue by bhaumik-sassyinfotech** [yajra/laravel-datatables#1533]
currently I am including css and JS for yajratable which is included from source https://datatables.yajrabox.com/ but it seems to be down. 
Any alternatives?

**Comment by indigitalit** [comment]
Use DataTables CDN - https://cdn.datatables.net/

**Comment by RohanSakhale** [comment]
Use DataTables CDN - https://cdn.datatables.net/

**Comment by cenob8** [comment]
Unfortunately the entire docs library is now down as well since this was hosted on  https://yajrabox.com/docs/laravel-datatables

**Comment by yajra** [comment]
Sorry for the inconvenience. It seems like our DigitalOcean droplet got corrupted and all sites were deleted! Anyways, it is now restored. Thanks!

P.S. The docs are also available on https://github.com/yajra/laravel-datatables-docs in case you guys need it.
