### ISSUE TITLE
How to use HasManyThrough Relation

### ISSUE THREAD

**Issue by mpmanwar** [yajra/laravel-datatables#1535]
I have three tables i am able to use relation between 2 tables easily. But when i am trying to access values from third table i mean trying to use hasManyThrough relation it is showing me always error. Do you have any idea how i can get value of third table column using middle table relation with first and last table.

### System details

- Linux
- PHP 7
- Laravel 5.3
- Laravel-Datatables Latest Version

**Comment by yajra** [comment]
I think I haven't tried HasManyThrough yet so not really sure if the package is working on it. See https://github.com/yajra/laravel-datatables/issues/1526 as it may be a duplicate on it.
