### ISSUE TITLE
eloquent query for datatable not working 

### ISSUE THREAD

**Issue by bhattaxay** [yajra/laravel-datatables#1537]
Hello,

I am using laravel 5.4 and yajra/datatable 7. When i writing code as below to get data:
`public function datatablecountry(){`
		
		$query = Country::select(['countryname','countrystatus']);
				
					
		return Datatables::of($query)->make(true);
		
	}`
than it throws 
```
Unknown column 'Country' in 'order clause' (SQL: select `countryname`, `countrystatus` from country order by `Country` asc limit 10 offset 0)
``` 
But i am not using `Country` column in my table so from where it will be loaded?

**Comment by yajra** [comment]
How did you declare your js columns? Make sure the correct column name was used.

```php
columns: [
  {data: 'countryname'},
  {data: 'countrystatus'},
]

**Comment by revaldopratama** [comment]
Hello,

I am using laravel 5.5 and yajra/datatable 7. When i writing code as below to get data:
public function index(Request $request, Builder $htmlBuilder)
{

if($request->ajax()) {
            DB::statement(DB::raw('set @rownum=0'));
            $queryAgent = $this->queryAgentPerformance($selectedStartDateString, $selectedEndDateString);
            $agent = $queryAgent->select(DB::raw('@rownum  := @rownum  + 1 AS rownum'), 'name', 'email', 'id')
                ->get();

            return Datatables::of($agent)
                    ->make(true);
        }

        $html = $htmlBuilder
           ->addColumn(['data' => 'rownum', 'name' => 'rownum', 'title' => 'No.'])
           ->addColumn(['data' => 'email', 'name' => 'email', 'title' => 'Agent\'s Email'])
           ->addColumn(['data' => 'total_question.0.question', 'name' => 'question', 'title' => 'Assigned Questions'])
           ->addColumn(['data' => 'total_answered.0.answered', 'name' => 'answered', 'title' => 'Answered Questions'])
           ->addColumn(['data' => 'total_unanswered.0.unanswered', 'name' => 'unanswered', 'title' => 'Unanswered Questions'])
           ->addColumn(['data' => 'total_escalated.0.escalated', 'name' => 'escalated', 'title' => 'Escalated Questions'])
           ->addColumn(['data' => 'total_spam.0.spam', 'name' => 'spam', 'title' => 'Spam Marked Questions'])
           ->addColumn(['data' => 'average_response.0.average', 'name' => 'average', 'title' => 'Avg Response Time']);

private function queryAgentPerformance($selectedStartDateString, $selectedEndDateString)
   {
       return User::with([
        'totalQuestion' => function ($query) use ($selectedStartDateString, $selectedEndDateString) {
            $query->whereBetween('assigned_at', [$selectedStartDateString, $selectedEndDateString]);
        }, 'totalAnswered' => function ($query) use ($selectedStartDateString, $selectedEndDateString) {
            $query->whereBetween('answered_at', [$selectedStartDateString, $selectedEndDateString]);
        }, 'totalUnanswered' => function ($query) use ($selectedStartDateString, $selectedEndDateString) {
            $query->whereBetween('assigned_at', [$selectedStartDateString, $selectedEndDateString]);
        }, 'totalEscalated' => function ($query) use ($selectedStartDateString, $selectedEndDateString) {
            $query->whereBetween('escalated_at', [$selectedStartDateString, $selectedEndDateString]);
        }, 'totalSpam' => function ($query) use ($selectedStartDateString, $selectedEndDateString) {
            $query->whereBetween('spam_at', [$selectedStartDateString, $selectedEndDateString]);
        }, 'averageResponse' => function ($query) use ($selectedStartDateString, $selectedEndDateString) {
            $query->whereBetween('answered_at', [$selectedStartDateString, $selectedEndDateString]);
        }])
        ->where('user_type', '!=', 'admin');
   }

}
