### ISSUE TITLE
[Question] Anchor tag not parsing correctly 

### ISSUE THREAD

**Issue by gabbydgab** [yajra/laravel-datatables#1538]
### Summary of problem or feature request
See sample here:
https://screenshots.firefox.com/0icGOVNwrgKcSxVZ/erp-3rm.local

### Code snippet of problem
I've followed the sample code here: https://datatables.yajrabox.com/collection/dt-row#edit-1

```php
return Datatables::of(Collection::make(new TireCollection(new TireResource($tires))))
                ->addColumn('actions', function ($tire) {
                    return '<a href="'.$tire['sku'].'" class="btn btn-xs btn-primary">'
                            . '<i class="fa fa-plus"></i>'
                            . '</a>';
                })
                ->make(true);
```

### System details

- PHP Version 7.1
- Laravel Version 5.5
- Laravel-Datatables Version 8.x

**Comment by yajra** [comment]
Please use [rawColumns](https://yajrabox.com/docs/laravel-datatables/7.0/xss#raw).

**Comment by gabbydgab** [comment]
Thanks @yajra!
