### ISSUE TITLE
my issues and solve(undefined index)

### ISSUE THREAD

**Issue by openvast** [yajra/laravel-datatables#154]
Edit files : 
1.vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Request.php
2.vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Engines/QueryBuilderEngine.php
![image](https://cloud.githubusercontent.com/assets/9793122/9543354/da7f8500-4daa-11e5-896a-6ddb495a43c2.png)
![image](https://cloud.githubusercontent.com/assets/9793122/9543366/f3912ea4-4daa-11e5-8843-7fad8bcef89f.png)
![image](https://cloud.githubusercontent.com/assets/9793122/9543409/338084e2-4dab-11e5-8f8d-1655de87252a.png)
![image](https://cloud.githubusercontent.com/assets/9793122/9543324/bb0a2270-4daa-11e5-87f9-0166e720ccb6.png)

**Comment by openvast** [comment]
english bad , and images can upload,sad...

**Comment by openvast** [comment]
my 	suggestion can solve issue。the function （filtering、columnSearch、setupColumnName）...

if i add select raw ("select('id', 'name', 'display_name', 'description', 'sort')") and （”->removeColumn('id')“）。and problem isn‘t exist。

what time to update and solve。

**Comment by openvast** [comment]
![image](https://cloud.githubusercontent.com/assets/9793122/9543309/9ddaa8a0-4daa-11e5-990a-181f97cb3fc4.png)

**Comment by yajra** [comment]
@openvast, YES, you basically need to set `orderable: false, searchable: false` on js options for columns added via `addColumn` method. Setting this option will tell the package not to search and do ordering for that specific column. Glad you sorted it out!
