### ISSUE TITLE
Can not use "customize" in excel button with DataTables as a Service.

### ISSUE THREAD

**Issue by wiiwilasinee** [yajra/laravel-datatables#1541]
### Summary of problem or feature request

I can't use "customize" in excel button with DataTables as a Service.
It always show this Error: "buttons.html5.min.js:23 Uncaught TypeError: b.customize is not a function" in console log but it work fine when use with out DataTables as a Service.

Thanks for your help :)

![image](https://user-images.githubusercontent.com/22979416/33697084-cca80732-db37-11e7-912e-487e107ec988.png)

- Window 10
- PHP Version : 7.0
- Laravel Version : 5.2

**Comment by yajra** [comment]
I think customize is not yet supported by the html builder plugin. Please submit a new ticket at https://github.com/yajra/laravel-datatables-html for feature request. Thanks!
