### ISSUE TITLE
Unable to search  Many to Many relationship with custom search

### ISSUE THREAD

**Issue by jkoech** [yajra/laravel-datatables#1544]
I have a Brand and Category model, with a many to many relationship. In my Brand Model, I have the following relation:
```
public function categories()
{
    return $this->belongsToMany(Category::class);
 }
```
And in my Category model, I have:
```
public function brands()
{
    return $this->belongsToMany(Brand::class);
}
```

Everything is working fine, I can search any field in the Brand Model except I haven't been able to search the Category. Below is my code, please help:
```
$brands = Brand::with('categories')->select('brands.*');

return Datatables::of($brands)
    ->filter(function ($query) use ($request) {

        if ($request->has('brand')) {
            $query->where('brand', 'like', "%{$request->get('brand')}%");
        }

    if ($request->has('category')) {
            $query->whereHas('categories', function ($q) use ($request) {
                $q->where('categories.slug', $request->category);
            });
        }

      
    })->make(true);
```

**Comment by yajra** [comment]
What version are you using please? I think eager loading does not work properly on version lower than v8 when using the `filter` api because it uses the `Base` query which invalidates any relationship in the model.

**Comment by jkoech** [comment]
HI Yajra, I'm using version 8. I managed to sort it out though. Even in version 8, it seems you can't filter a many to many relationship.  I had to use a ```whereHas``` callback as below:

```
$brands = Brand::with('categories')
    ->select('brands.*')
    ->whereHas('categories', function ($q) use ($request) {
    if ($request->has('categories') && $request->get('categories') != null ) {
         $categories = array_filter($request->categories);
        if(count($categories) > 0) {
            $q->whereIn('categories.slug', $request->get('categories'));
        }  
    }               
});
```
