### ISSUE TITLE
error in render method in datatables

### ISSUE THREAD

**Issue by MMagde** [yajra/laravel-datatables#1545]
### Summary of problem or feature request
there is an error in render method in datatables for new modules 
i solved it by commenting it and uncomment the code in  langcol file :D 
![image](https://user-images.githubusercontent.com/22965555/33789430-f8ec700e-dc80-11e7-9f9f-46f670fec3e4.png)

![image](https://user-images.githubusercontent.com/22965555/33789419-e63195d4-dc80-11e7-9c09-d7383b499dcd.png)

**Comment by yajra** [comment]
I think the function on render string is already added by default. Try setting the return value script like:

```php
'render' => "JSON.parse(this.name).".getCurrentLang();
```
