### ISSUE TITLE
serverSide ajax call for each page problem.

### ISSUE THREAD

**Issue by cakesforfree** [yajra/laravel-datatables#1546]
Laravel 5.3
"yajra/laravel-datatables-oracle": "6.0"
----------------------
Route:
![image](https://user-images.githubusercontent.com/13759233/33802648-157b70f6-dd41-11e7-8725-dc55fc03aa6c.png)

Controller:
`public function obtener_fragmentos (Request $request)
    {

        $id_documento = Request::input('id_documento');
        $fragmentos = DB::table('documentos_fragmentos')
            ->join('esquemas', 'documentos_fragmentos.id_esquema', '=', 'esquemas.id')
            ->select('documentos_fragmentos.*','documentos_fragmentos.id as identi','esquemas.descripcion as esquema','documentos_fragmentos.nomenclatura as nomenclatura','documentos_fragmentos.titulo as titulo')
            ->where('id_documento',$id_documento)
            ->orderBy('documentos_fragmentos.id_esquema','ASC')
            ->orderBy('documentos_fragmentos.nomenclatura','ASC');

        return Datatables::of($fragmentos)->addColumn('action', function ($fragmentos) {
                return '<input class="form-check-input nuevo_fragmento_padre" type="radio" name="nuevo_fragmento_padre"  value="'.$fragmentos->id.'" required>';
            })->make(true);
    }`

Script:
`$('#tabla-mover-fragmento').DataTable({
        "pageLength": 10,
        "order": [[ 0, "desc" ]],
        "destroy": true,
        "ajax": {
          "url": '/obtener_fragmentos',
          "data": {
            "id_documento": id_documento
          },
          "dataSrc": 'data'
        },
        "columns": [{
            data: 'identi'
          },
          {
            data: 'esquema'
          },
          {
            data: 'nomenclatura_real'
          },
          {
            data: 'titulo'
          },
          {
            data: 'action',
            orderable: false,
            searchable: false
          }
        ],
        "language": {
                "lengthMenu": "Mostrar _MENU_ registros",
                "zeroRecords": "No hay registros que mostrar",
                "info": "Mostrando página _PAGE_ of _PAGES_",
                "infoEmpty": "No hay registros",
                "infoFiltered": "(filtered from _MAX_ total records)",
                "search":         "Búscar:",
                "paginate": {
                    "first":      "Primero",
                    "last":       "Ultimo",
                    "next":       "Siguiente",
                    "previous":   "Anterior"
                },
            }

      });
    `});`

so far this code calls all the registres at once via ajax, but i need to make an ajax call for each page the table displays.

But when i add these two options:
"processing": true,
"serverSide": true,

it gives me an error 
![image](https://user-images.githubusercontent.com/13759233/33792464-cfa8985a-dc65-11e7-815d-56f9c39d669f.png)

![image](https://user-images.githubusercontent.com/13759233/33792472-35dce3e2-dc66-11e7-8210-fcc30cb2b7c6.png)

**Comment by cakesforfree** [comment]
![image](https://user-images.githubusercontent.com/13759233/33793380-b07c5662-dc7c-11e7-9f7c-466e5795702f.png)

I even try using requesting via PosT and adding the csrf, but still I am getting the 500 error:
![image](https://user-images.githubusercontent.com/13759233/33793387-d4a08536-dc7c-11e7-8806-d12a8a726029.png)

**Comment by mleppala** [comment]
Can you lease post your routes too?

**Comment by cakesforfree** [comment]
This is the route I am using.

![image](https://user-images.githubusercontent.com/13759233/33802620-9100169c-dd40-11e7-9bfd-e0678e554bff.png)

**Comment by mleppala** [comment]
Sorry for the delay work is a mad house try to get a release out before the end of the year. Are you still getting this issue?  Thank you for posting your route,  Can you share the error 500 information?  This is typical misspelled controller name but the return error message can show what is going on.

If you not sure how to get this then please click on the link in console. This will take you to the Network table. In the name column click on the the one in red. when the page comes up click on the Preview and screenshot it and post.
