### ISSUE TITLE
Quantity of columns are limited!!

### ISSUE THREAD

**Issue by cdiazr** [yajra/laravel-datatables#1547]
### Summary of problem or feature request

I've noticed that only 8 columns I can list. I spent lot of time guessing why I was getting an "Ajax error" when the rest of the sections are working perfectly with the same syntax. 

I delete a column into the view and it is working. 

I would like to know where can I change that limitation.

Thank you

- Windows 10
- PHP 7.0
- Laravel 5.5
- Laravel-Datatables 8

**Comment by Konafets** [comment]
I currently use 15 columns, so I doubt there is a hardcoded limit of how many cols you can see.

**Comment by yajra** [comment]
This might be a browser issue specifically IE. Try using `POST` on your ajax request.
