### ISSUE TITLE
Another editor.datatables.net support

### ISSUE THREAD

**Issue by bellwood** [yajra/laravel-datatables#1548]
http://datatables.codetoweb.com/ looks to be unmaintained for the last 2 years so this is no longer viable.

If I donated a paid license to this project, would you add support for it?

Presumably, so long as you don't distribute the licensed version, you'd be find - just add in your docs instructions to download the licensed version from datatables.net and how to integrate it.

If you are interested and have a datatables.net account, I can reach out to them about attaching a paid license to your account to make it simple/easy.

**Comment by bellwood** [comment]
Based on:

https://editor.datatables.net/purchase/index

Theres only two files needed to upgrade the trial, that makes distribution a cinch, just leave those two files out and you're golden =)

**Comment by yajra** [comment]
@bellwood thanks for the offer and I'm interested on your proposal. However, I cannot commit yet on the implementation timeline as I'm a bit occupied atm. Maybe I can spare some time starting January next year. My account on datatables.net is **yajra** too.

**Comment by bellwood** [comment]
@yajra I've reached out to datatables to see if what I proposed is indeed possible.

No worries on the immediate timeline, it's the end of the year.

I'll be using your library shortly for a grid project that requires no editing however following that I do have an inline edit grid project that would greatly benefit from native support hence why I'd love to donate the license to help spur the development.

Thank you for the response =)

**Comment by bellwood** [comment]
@yajra I've heard back from Datatables... They've GENEROUSLY donated a license to the project 👍

**Comment by yajra** [comment]
@bellwood thanks for initiating this. I got the license from @DataTables and I'm a bit excited now to experiment with it. :)

**Comment by yajra** [comment]
@bellwood I got excited and went ahead implementing an Editor handler. See https://github.com/yajra/laravel-datatables-editor. Still a WIP but works 90% of the time as of this moment. It's a bit easier to implement than I expected. You would just need to create a simple class to handle all Editors request and your done. :)

**Comment by bellwood** [comment]
I will give this a go next week time permitting... Thank you =)

**Comment by yajra** [comment]
Almost done with plugin. Just need to document it as I find it stable now with all the crud functions. :)

**Comment by yajra** [comment]
[Package](https://github.com/yajra/laravel-datatables-editor) is now released as v1.0. 🍻
