### ISSUE TITLE
Error with laravel 5.2.

### ISSUE THREAD

**Issue by guancarlos** [yajra/laravel-datatables#1549]
### Summary of problem or feature request
hi 
i'm trying installing with : 
`composer require yajra/laravel-datatables-oracle`
 or with: 
`composer require yajra/laravel-datatables-oracle:"~8.0"`
and i get this error 
### Code snippet of problem
`Problem 1

    - Conclusion: remove laravel/framework v5.2.45

    - Conclusion: don't install laravel/framework v5.2.45

    - yajra/laravel-datatables-oracle v8.3.0 requires illuminate/database 5.4.*|5.5.* -> satisfiable by illuminate/database[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].

    - yajra/laravel-datatables-oracle v8.3.1 requires illuminate/database 5.4.*|5.5.* -> satisfiable by illuminate/database[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].

    - yajra/laravel-datatables-oracle v8.3.2 requires illuminate/database 5.4.*|5.5.* -> satisfiable by illuminate/database[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].

    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.4.13|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.4.17|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.4.19|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.4.27|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.4.36|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.4.9|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.5.0|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.5.16|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.5.17|don't install laravel/framework v5.2.45

    - don't install illuminate/database v5.5.2|don't install laravel/framework v5.2.45

    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

    - Installation request for yajra/laravel-datatables-oracle ^8.3 -> satisfiable by yajra/laravel-datatables-oracle[v8.3.0, v8.3.1, v8.3.2].`

### System details
fedora 24
PHP 7.1.11
laravel 5.2

**Comment by yajra** [comment]
Please use v7.0 for Laravel 5.2. Thanks!
