### ISSUE TITLE
Relationship Table Name Issue.

### ISSUE THREAD

**Issue by erenergul** [yajra/laravel-datatables#1550]
### Summary of problem or feature request

Hi I have a problem with relationship. I try lots of method but I coulnd't bring id->name on my table.

Actually It is simple table.  Let me share and If you can help. I will be glad. 

### Code snippet of problem
This is my APIController. 

`  public function getAlinis()
    {

        $alinislar = Alinis::all();

        $turlar = Tur::with('turlar')->select('turlar.*');

        return Datatables::of($alinislar, $turlar)
            ->addColumn('action', function ($alinislar) {
                return
                    '<a href="tur/' . $alinislar->alinis_id . '/edit" class="btn btn-primary" style="margin-right: 10px;">Düzenle</a>' .
                    '<a href="tur/destroy/' . $alinislar->alinis_id . '" class="btn btn-danger" >Sil</a>';
            })
            ->make(true);
    }`

Its my js code. I try to add relationship name with 100 different variable. Now its just id. But How can i bring name from tur_id table. I install yajra demo and try to figure out but it looks very complicated. I didn't understand which controller for which view. 

`  <script type="text/javascript" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>

    <script src="{{asset('adminsrc/global/vendor/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>

    <script type="text/javascript">

        $(document).ready(function () {
            $('#dataTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Turkish.json"
                },
                processing: true,
                serverSide: true,
                ajax: '{{ route('alinis.getir')}}',
                columns: [
                    {data: "alinis_adi", name: "alinis_adi"},
                    {data: "tur_id", name: ""},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]

            });
        });

    </script>`

Please If you share your idea. I will be appreciative.

### System details

- Operating System
- PHP Version 7.2
- Laravel 5.5
- Laravel-Datatables Latest Version

**Comment by yajra** [comment]
I think you have used the api incorrectly:

```php
return Datatables::of($alinislar, $turlar) // is invalid.
```

Also see this [eager loading demo](https://datatables.yajrabox.com/eloquent/relationships) for ref.

**Comment by erenergul** [comment]
Hi , Arjay. I checked eager loading demo and install it but I couldn't understand. Which way should I follow. Just imagine. Alinislar -> Post and Turlar -> Categories for post. I watch more then 10 video for datatables. Nobody explain relationship. I am not good with ajax and js thats why I couldnt figure out..

**Comment by yajra** [comment]
On columns do something like this below. The name value represents the `table name + column name`

```
columns: [
                {data: "alinis_adi", name: "alinislar.alinis_adi"},
                {data: "tur_id", name: "alinislar.tur_id"},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
```

On your query maybe something like:

```php
    $alinislar = Alinis::with('tur.turlar')->select('alinislar.*');

    return Datatables::of($alinislar)...
```
