### ISSUE TITLE
filteredRecords count - custom filtering and pagination

### ISSUE THREAD

**Issue by tania-pets** [yajra/laravel-datatables#1551]
### Summary of problem or feature request

We have implemented a custom filtering and use pagination 10 per page (server side).
We tried 2 ways for the custom filtering one using overrideGlobalSearch() and one with filter() function.

The problem is on the filteredRecords that ends up equal to page's size.

At the BaseEngine, filterRecords method:
### Code snippet of problem
```php
$this->filteredRecords = $this->isFilterApplied ? $this->count() : $this->totalRecords;
```
Seems we cannot set $this->isFilterApplied to false (overrideGlobalSearch() and filter() set it true) and we cannot force filteredRecords like we do with setTotalRecords().

So, how could this work?

### System details

- PHP 7.0
- Laravel Version 5.2
- Laravel-Datatables 6.0

Thanks.

**Comment by yajra** [comment]
I am not using 6.0 anymore. Can you please send a PR for possible fix? I may not be able check anytime soon. Thanks!
