### ISSUE TITLE
Problem trying to include datatable in other view

### ISSUE THREAD

**Issue by ecampoBS** [yajra/laravel-datatables#1552]
First of all, I would like to thank you the great work you do to mantain this wonderful plugin ;)

I have a view where I edit some info of one of my models, but I'm creating a tab like form to fulfill the info in a more confortable way. The thing is that I would like to include the datatable inside a view that is used for editing the model, and I don't know how could I return the datatable from the controller without its custom view and route.

In a common situation I would return the view including the datatable in the controller:

```php
public function index(TareasDataTable $dataTable)
    {
        return $dataTable->render('tareas.listar');
    }
```

But in my case I'm already returning the edit view:

```php
$tarea = Tarea::find($id);

        if(is_null($tarea))
        {
            return redirect()->back()->withErrors(['error' => __('tareas.not_found')]);
        }

        $data = [
            "tarea" => $tarea
        ];

        return view('tareas.tarea',$data);
```

How could I acomplish this? Is there any way or what I'm trying it's not posible?

- Operating System: Windows 10
- PHP Version:  PHP 5.6
- Laravel Version: 5.4
- Laravel-Datatables Version 7.0

**Comment by yajra** [comment]
Do you mean that forms (create/edit) are already included in the index page? In this cases, I usually process all forms request via ajax since you are aiming for single page admin panel if I get this correctly.
