### ISSUE TITLE
How to make the database primaryKey returned according to the natural number

### ISSUE THREAD

**Issue by kylesean** [yajra/laravel-datatables#1555]
First of all, I would like to thank you the great work you do to mantain this wonderful plugin ;)

Usually,we return the id in table like:

ID | NAME
--- | ---
1 | Jack
3 | Mike
9 | Jordan

```
$('#xxx').dataTable({
    serverSide: true,
    processing: true,
    ajax: {
        url: 'xxx/xxx',
    },
    columns: [
       {data: 'id', name: 'id'},
       {data: 'name', name: 'name'}
    ]
});
```

however,I want to sort by natural number like:

ID | NAME
--- | ---
1|Jack
2|Mike
3|Jordan

I tried to use the laravel getAttribute model method,but it can't work well.

How could I acomplish this? 

- Operating System: Windows 10
- PHP Version: PHP 5.6
- Laravel Version: 5.4
- Laravel-Datatables Version 7.0

Looking forward to your reply,thanks.

**Comment by yajra** [comment]
I think what you need is [indexColumn](https://yajrabox.com/docs/laravel-datatables/master/index-column) for the display but sorted using the actual id?

```js
$('#xxx').dataTable({
    serverSide: true,
    processing: true,
    ajax: {
        url: 'xxx/xxx',
    },
    columns: [
       {data: 'DT_Row_Index', name: 'id'},
       {data: 'name', name: 'name'}
    ]
});
```

**Comment by kylesean** [comment]
Wow,thank you very much.

Sorry, I blame myself not carefully read the document ;)
