### ISSUE TITLE
Only redraw table when returning from server-side

### ISSUE THREAD

**Issue by mleppala** [yajra/laravel-datatables#1559]
I am looking for a way to only redraw the datatable on the return back from the controller not the entire page.

I have a array of buttons that are passed the view. These buttons resides outside the form tag. Here is an example of creating the button data from the server-side.
```
 private function activateButton(DynamicButton $buttonSet){
        return $buttonSet
            ->createButton('Active')
            ->setType('submit')
            ->name('action')
            ->addClass(['btn','btn-small'])
            ->value('active')
            ->attr(['onclick'=>"if ($('[name=\'boxchecked\']').val()==0){
                    alert('Please first make a selection from the list.');}else{ submitbutton('active', 'userForm')};  
                "]);
    } 
```
When one or more users are selected and button above is clicked. the submitbutton function is called. This function gets the form by the supplied form name. It will then add the action and a submit button. After the button is created inside the form the button is clicked. The button above will route to the active function on the server-side and process the information then gets redirect back to the users page. as shown below.

```
    public function active(Request $request){
        $this->setUserActivation($request->selected_users);
        return redirect()->back();
    }
```

However, this will reload the page and I just need to just reload the datatable. If I did a post ajax call I could use the datatable draw method.

```
oTable.draw(false);
```
Does anyone have any idea on how to do this from server-side?

- Operating System Win10
- PHP Version 7.1
- Laravel Version 5.4
- Laravel-Datatables Version 7.7

**Comment by yajra** [comment]
For my workflow, I usually do this kind of activation stuffs via ajax action button. When successful, just redraw the table instance.

```js
$('table').on('click', 'button.activate', function() {
  $.ajax({
    ...
    success: function(response) {
      oTable.draw(false);
    }
  })
})

**Comment by mleppala** [comment]
Yea , I was going to do use ajax but after thinking about how many buttons that would be dynamically created it would be too many ajax to maintain. But if there is no way to just the redraw the table instance on the return then I will have to look at the adding ajax in the mix.

**Comment by mleppala** [comment]
I ended up created a jQuery function to do a ajax call based on the button was pressed.

**Comment by acharyajay007** [comment]
How to get instance of object when there is more then two table and using service method $datatable->scripts()?

**Comment by bungnewbie** [comment]
> How to get instance of table when there are more then two table and using service method $datatable->scripts()?

How to get it?

**Comment by zeshan77** [comment]
> How to get instance of table when there are more then two table and using service method $datatable->scripts()?

Can someone guide here, please? I'm also stuck on the same.
Thanks

**Comment by yajra** [comment]
Use the global js namespace.

```js
var oTable = LaravelDataTables['customers-table'];
```

You can set the table id when defining the builder.

```php
    public function html()
    {
        return $this->builder()
            ->setTableId('customers-table')
...
```
