### ISSUE TITLE
Problems in Schedule Task

### ISSUE THREAD

**Issue by rikuhen** [yajra/laravel-datatables#156]
I have this problem, i developed a method, it finds users and  send email everyday but when i run the command its response is following:

![image](https://cloud.githubusercontent.com/assets/5169412/9556574/554ecef4-4d9b-11e5-8e50-eadc1228dbac.png)

I tried with others connections (mysql driver) and nothing wrong. 
Thanks and sorry my English.

**Comment by yajra** [comment]
I think you posted on the wrong repo. Anyways, are you using oracle as your DB driver? Please note that php cli config is different on you php web config. Please make sure that your php.ini on CLI loads `oci8` php extension.

**Comment by yajra** [comment]
Btw, please create a new issue on https://github.com/yajra/laravel-oci8/issues and lets continue the discussion there. Thanks!
