### ISSUE TITLE
Problem with join

### ISSUE THREAD

**Issue by Carlos123211** [yajra/laravel-datatables#1560]
`<?php

namespace App\DataTables;

use App\Models\Provincia;
use Form;
use Yajra\Datatables\Services\DataTable;
use App\Models\Departamento;

class ProvinciaDataTable extends DataTable
{

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', 'provincias.datatables_actions')
            ->make(true);
    }

    /**
     * Get the query object to be processed by datatables.
     *
     * @return \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder
     */
    public function query()
    {
        $provincias = Provincia::query()->join('departamentos','provincias.depart_id','=','departamentos.id')->select(['provincias.nomProv','departamentos.nombreDep']);

        return $this->applyScopes($provincias);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->addAction(['width' => '10%'])
            ->ajax('')
            ->parameters([
                'dom' => 'Bfrtip',
                'scrollX' => false,
                'buttons' => [
                    'print',
                    'reset',
                    'reload',
                    [
                         'extend'  => 'collection',
                         'text'    => '<i class="fa fa-download"></i> Export',
                         'buttons' => [
                             'csv',
                             'excel',
                             'pdf',
                         ],
                    ],
                    'colvis'
                ]
            ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    private function getColumns()
    {
        return [
            
            'nomProv' => ['name' => 'nomProv', 'data' => 'nomProv'],
            'depart_id' => ['name' => 'departamentos.nombreDep', 'data' => 'nombreDep']
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'provincias';
    }
}
`
What I'm trying to do is sending the Json to show in my index view, but i'm getting this error message:
DataTables warning: table id=dataTableBuilder -Exception Meesage:
Undefined variable:id(View:C:xampp\htdocs\v10\resourcers\views\provincias\datatables_actions.blade.php)

**Comment by yajra** [comment]
It's because id is not included on your select statement:

```php
->select(['provincias.nomProv','departamentos.nombreDep'])
```

**Comment by Carlos123211** [comment]
Thanks it worked.
