### ISSUE TITLE
fractal transformer and action buttons

### ISSUE THREAD

**Issue by swash13** [yajra/laravel-datatables#1562]
### how to use fractal transformer and ->addColumn('action', 'admin.categories.datatables_actions'); together ?

```php
$dataTable = new EloquentDataTable($query);

        return $dataTable
            ->setTransformer(new CategoryTransformer())
            ->addColumn('action', 'admin.categories.datatables_actions');
```

If i user this - action buttons do not display. How to include them with the transformer ?

**Comment by yajra** [comment]
As per this [doc](https://yajrabox.com/docs/laravel-datatables/master/response-fractal), you should avoid `addColumn` and instead use the transformer for adding the action column.

```php
$dataTable = new EloquentDataTable($query);

return $dataTable->setTransformer(new CategoryTransformer());

// transformer

return [
   'id' => $model->id,
   ...
   'action' => view('admin.categories.datatables_actions', compact('model')),
]
```

**Comment by swash13** [comment]
i did like you suggest, it's not working. It's like an object. Weird.
My transformer:
```php
/**
     * Category Transformer.
     *
     * @param Category $category
     * @return array
     */
    public function transform(Category $category)
    {
        return [
            'action' => view('admin.categories.datatables_actions', compact('category')),
            'id'         => (int)$category->id,
            'name'       => $category->name
        ];
    }
```

And the result:
![1514297681323](https://user-images.githubusercontent.com/14277100/34358492-e559d82a-ea58-11e7-9c56-f82bc3014222.jpg)

What am i doing wrong ?

**Comment by yajra** [comment]
Try adding the render on view.

```php
'action' => view('admin.categories.datatables_actions', compact('category'))->render(),
```

**Comment by swash13** [comment]
thanks, that worked. Nice to mention this in docs.
