### ISSUE TITLE
Package not working with large data

### ISSUE THREAD

**Issue by LeeGarden** [yajra/laravel-datatables#1565]
I have a large data with > 50.000 record
I have any issue 

> `{`
   ` "message": "Maximum execution time of 30 seconds exceeded",`
    `"exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",`
    `"file": "/var/www/lms_admin/vendor/laravel/framework/src/Illuminate/Support/Collection.php",`
   ` "line": 1210,`
    `"trace": []`
`}`

My code in Controller 

> `public function listDataJson(Request $request)`
   ` {      `
        `$limit = intval($request->input('length'));`
       ` $listCandidate = LMSNayoseCandidate::with('checkCandidate')`
                               `             ->with('SFAIntegrate')`
                                  `          ->get();`
    `    $data = [];`
      `  foreach ($listCandidate as $item) {`
         `   $nestedData['sfa_id']          = $item->sfa_id;`
          `  $nestedData['sfa_name']        = $item->SFAIntegrate->SFAKind->sfa_name;`
          `  $nestedData['company_name']    = $item->SFAIntegrate->company_name;`
           ` $nestedData['office_name']     = $item->SFAIntegrate->office_name;`
           ` $nestedData['count_candidate'] = count($item->checkCandidate);`
           `$nestedData['max_point']       = $item->getMaxPoint($item->checkCandidate);`
            `$nestedData['created_at']      = $item->created_at;`
           ` $nestedData['action']          = route('admin.detail-candidate', $item->sfa_id);`
           ` $data[] = $nestedData;`
      `  }`
       ` return datatables()->of($data)->toJson();`
   ` }`

**Comment by yajra** [comment]
Don't use collection by removing `->get();` on your query.

**Comment by LeeGarden** [comment]
If I don't use  `->get();`  data return is null

> `{"draw":1,"recordsTotal":0,"recordsFiltered":0,"data":[],}`

Pls, help me

**Comment by yajra** [comment]
What database are you using? If it only works on collection then the only solution here is to upgrade your server specs.

**Comment by yajra** [comment]
BTW, use editColumn instead of looping on each data. 

```php
public function listDataJson(Request $request)
{
  $listCandidate = LMSNayoseCandidate::with('checkCandidate')
  ->with('SFAIntegrate')->select('candidates.*');

  return datatables()->of($listCandidate)
  ->editColumn(...)
  ->editColumn(...)
  ->toJson();
}
```

**Comment by LeeGarden** [comment]
tks you, I will try again

**Comment by MohamedMounir00** [comment]
thank you yajra
