### ISSUE TITLE
Error when remove package

### ISSUE THREAD

**Issue by mprandot** [yajra/laravel-datatables#1566]
Hello

i remove the package from a application and this has broke the project.

The package have some "log" dependency?? I cannot understand what is happening :\

After removing:
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in 
/var/www/html/siscomv2/vendor/laravel/framework/src/Illuminate/Container/Container.php:741

dep: "yajra/laravel-datatables-oracle": "^6.0",
Laravel 5.1
Ubuntu 17.10
PHP7.1
Apache2

**Comment by yajra** [comment]
Can't recall much but v6.0 indeed has so many dependencies on it but I think log is not one of them.

**Comment by mprandot** [comment]
I searched too and find nothing...
I can't remove the package, and really don't know why...

**Comment by mprandot** [comment]
Found the issue;

After the `vendor:publish` the package created a file `excel.php` in `config/` folder... just delete the file... my fault, sorry :D
