### ISSUE TITLE
why not set the php function foreach continue the addColumn orderBy

### ISSUE THREAD

**Issue by openvast** [yajra/laravel-datatables#157]
the issue url
https://github.com/yajra/laravel-datatables/issues/154

**Comment by yajra** [comment]
When using `Collection` as data source, added column via `addColumn` method is possible to be search and arranged. This will vary on your use case. But generally, you should set false on added columns because it's not part of the query.

**Comment by openvast** [comment]
you are right ，but the Developer should solve any bug for use 。isn‘t it ? 
addColumn for search("foreach ($this->request->searchableColumnIndex() as $index)") and order("foreach ($this->request->orderableColumns() as $orderable)")  $index should be litte the database sql select column.

**Comment by yajra** [comment]
Yes, and the right way to fix this on my opinion is by properly setting the correct options set by the api. For your case, the proper way to fix it is by setting the option `searchable` and `orderable` to `false` to tell the package not to search and sort by it. If you have a better idea on how we can magically fix it then I am willing to accept a pull request ^_^.

**Comment by openvast** [comment]
how to  request a pull request. like this ? 
![image](https://cloud.githubusercontent.com/assets/9793122/9561018/a95f5a24-4e66-11e5-92fa-3cc58e77a1e3.png)

**Comment by yajra** [comment]
Let's continue the discussion on https://github.com/yajra/laravel-datatables/pull/158
