### ISSUE TITLE
No results with has many relationship, as a service with model class

### ISSUE THREAD

**Issue by eugeniregi** [yajra/laravel-datatables#1570]
### Hello! 
I get no results in the ajax response with a relation query passing my Person model in the query method.

My schema is an m-n relation to self table and i use  a pivot table.
_table persons_
-- id, name,surname1,surname2,email

_table relation_
-- IDStudent, IDRelative, relation

I have a class called FamiliaresDatatable with the methods query, dataTable, html and getColumns()

### My FamilyDatatables class
   ```
class FamiliarsDatatables extends DataTable
{
public function dataTable($query)
    {        
        return datatables($query));          
    }   
     /**
     * Get query source of dataTable.
     *
     * @param \App\User $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(Person $model)
    {
          return $model->relationsFamily()->select(['persons.id','persons.DNI','persons.name','persons.surname1','persons.surname2','persons.email','relation.relation']);              
    }
    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->addAction(['width' => '80px'])
                    ->parameters($this->getBuilderParameters());
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
                ['data' => 'persons.id', 'name' => 'persons.id', 'title' => 'Id'],
                ['data' => 'persons.email', 'name' => 'persons.email', 'title' => 'Email'],
                [ 'data'=> 'persons.DNI', 'name'=> 'persons.DNI','title'=>"DNI" ],
                [ 'data'=> 'persons.name', 'name'=> 'persons.name' ,'title'=>"Nom" ],
                [ 'data'=> 'persons.surname1', 'name'=> 'persons.surname1','title'=>'Cognom1' ],
                [ 'data'=> 'persons.surname2', 'name'=> 'persons.surname2','title'=>'Cognom2' ],
                [ 'data'=> 'pivot_relation', 'name'=> 'pivot_relation','title'=>'Parentiu' ],
                
        ];
    }
}
```
### My model Person Class
```

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
	public $table="persons";
    public function relationsFamily()
    {
    	return $this->belongsToMany('App\Person','relation','IDStudent','IDRelative')->withPivot('relation');
    }
}

```

The problem is that when in the controller i make
`$datatable->query($client)`
_the $client contains the Person model that I want get their relatives_
it gets the correct rows and executes the query (i can see in debugbar), but not in the table view. 
And when i make only 
` return $datatable->render('clients.edit',array('client'=>$client));`
not gets rows and no executes the query
.
It seems that when executes the render method does not includes de person model in the query method..

I have some questions:
Have I to use scopes ? In order to use them (scopes) have I to create them as a new Class.. ( with php artisan datatables:scope)? 

Have I to override ajax method?

PD: I have tried with applyscopes() method like this
 ```
public function query(Person $model)
    {                   
          return $this->applyScopes($model->relationsFamily()->select(['persons.id','persons.DNI','persons.name','persons.surname1','persons.surname2','persons.email','relation.relation']));
        
    }
```
But without success....

I Hope you can resolve it!
Thanks!

### System details

- Operating System homestead 7
- PHP Version 7
- Laravel Version 5.5
- Laravel-Datatables Version 8.3.2

**Comment by yajra** [comment]
Yes, I think you need to use scope in this case. Also you don't need to add `applyScopes` since it's automatically done on the background.

## Create the scope

```bash
php artisan datatables:scope ClientScope
```

## Add constructor and accept the client

```php
<?php

namespace App\DataTables\Scopes;

use Yajra\DataTables\Contracts\DataTableScope;

class ClientScope implements DataTableScope
{
    private $client;

    public function __construct($client)
    {
        $this->client = $client;
    }

    public function apply($query)
    {
         return $query->where('client_id', $this->client->id);
    }
}
```

## Apply the scope on controller

```php
return $datatable->applyScope(new ClientScope($client))->render('clients.edit',array('client'=>$client))
```

**Comment by eugeniregi** [comment]
Thanks for the answer!!

Now I get another problem...
In the ClientScoope Class If I make a where, it gets no records with the sql:
`select `persons`.`id`, `persons`.`DNI`, `persons`.`name`, `persons`.`surname1`, `persons`.`surname2`, `persons`.`email`, `relation`.`relation`, `relation`.`IDStudent` as `pivot_IDStudent`, `relation`.`IDRelative` as `pivot_IDRelative`, `relation`.`relation` as `pivot_relation` from `persons` inner join `relation` on `persons`.`id` = `relation`.`IDRelative` where `relation`.`IDStudent` is null and `relation`.`idStudent` = ?"`

The scope is working but, not get records because it queries for null id

I think, the problem is the parameter (Person $model) i get in the query method in ClientDatatable.
not have attributes, because when i try to get id is null (and that is the null in the sql query).

Is there a way to pass the correct object to the query method???

**Comment by yajra** [comment]
You can pass a variable on the dataTables class using with api. See https://yajrabox.com/docs/laravel-datatables/master/buttons-with for ref.

**Comment by eugeniregi** [comment]
Thanks!
It's working now!
