### ISSUE TITLE
large data issue

### ISSUE THREAD

**Issue by emaspc93** [yajra/laravel-datatables#1573]
### Summary of problem or feature request

hello excuse me, I have taken some time to ask you a brief question, I am starting in laravel and using this good package, however I am having problems when it comes to paging to the last records of my database, I count with 95 thousand records and when I go from page 1 to 9500 the browser is saturated and my query is delayed, sometimes it fails. 

### Code snippet of problem

```
public function apiIndex(){
        return Datatables::of(Index::query())
        ->addColumn('action', function($index) {
            return  "<div class='btn-group col-md-offset-3'>
            <a class='btn btn-info btn-sm show-index' n='1' href='".route('indexes.show', $index->id)."' data-toggle='tooltip' data-placement='top' title='Ver registros'><span class='fa fa-eye'></span></a>
            <a class='btn bg-yellow btn-sm edit-index' n='2' update='".route('indexes.update', $index->id)."' href='".route('indexes.edit', $index->id)."' data-toggle='tooltip' data-placement='top' title='Editar registros'><span class='glyphicon glyphicon-edit'></span></a>
            <a class='btn btn-sm btn-danger destroy-index' href='".route('indexes.destroy', $index->id)."''  data-toggle='tooltip' data-placement='top' title='Eliminar registros'><span class='glyphicon glyphicon-trash'></span></a></div>";
        })
        ->make(true);
    }

```

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
Your code looks fine. Are you using `php artisan serve`?

**Comment by emaspc93** [comment]
hello yajra thank you for responding, yes, I'm using php artisan serve to run the project and the problem persists using this command or running only in xampp, I do not know what may be happening, I attach a part of my script:


![script](https://user-images.githubusercontent.com/19209041/34831573-bd3aef20-f6bd-11e7-8b63-fef6855635f6.png)
![2](https://user-images.githubusercontent.com/19209041/34831643-e3094148-f6bd-11e7-8931-4ac5500460e2.png)
![prob](https://user-images.githubusercontent.com/19209041/34831752-3323f24a-f6be-11e7-9d83-fa4360c75d8d.png)

delayed 2 o 3 minutes to 9500 pages.

**Comment by yajra** [comment]
First, please avoid using artisan serve if possible as it is known buggy with the package. 

Have you tried inspecting the ajax request with `APP_DEBUG=true`? It should give you a hint on what queries are executed when processing the request.

**Comment by mohammadsalmani28** [comment]
my problem is like this issue ...
and absolutely i run "php artisan serve" on my application!
i have 100k user in my database.
