### ISSUE TITLE
pagination not work in filterColumn search

### ISSUE THREAD

**Issue by aliworkshop** [yajra/laravel-datatables#1574]
### Summary of problem or feature request

hello dear @yajra 
i'm using column search for search in laravel nested relations and it's work excellently
but a problem is exists still

when i'm use filterColumn , the total record count and the filtered record count are the same
i think that was for that in filterColumn function you dont set     $this->isFilterApplied as true

this function should be as this

```php
    public function filterColumn($column, callable $callback)
    {
        $this->columnDef['filter'][$column] = ['method' => $callback];
        $this->isFilterApplied = true;
        return $this;
    }

```

my code is as this
```php
            ->filterColumn('title',function ($query,$keyword){
                $query->whereHas('translate', function ($q) use ($keyword){
                    $q->where('title','like',"%$keyword%");
                });
            })

```

### System details

- Operating System
- PHP Version7.1
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
@aliworkshop thanks for reporting. Can you please submit a PR on the solution you made. Will try to replicate this as soon as I can.
