### ISSUE TITLE
Method filterColumn does not exist.

### ISSUE THREAD

**Issue by hironate** [yajra/laravel-datatables#1576]
In Version 8.0 filterColumn does not exist, so how to deal with filtering columns.

**Comment by yajra** [comment]
You might be using collection? If yes, then I think it is indeed non-existent. Filer column is only available on Query / Eloquent implementation.

**Comment by ultrono** [comment]
Getting the same error, tried loads of variations.  Apparently it should work as per https://yajrabox.com/docs/laravel-datatables/master/filter-column

**Comment by LazyPurushottam** [comment]
"Method Yajra\DataTables\CollectionDataTable::where does not exist."
I am getting this type of error can you help me out from this

**Comment by nguyenhychan** [comment]
Got same issue here. I got the problem when running the following code:

```
$datatables->filter(
    function ($query) use ($ranges) {
        foreach ($ranges as $range) {
            if (isset($range['from']) && $range['from'] !== "") {
                $query->where($range['column'], '>=', $range['from']);
            }
            if (isset($range['to']) && $range['to'] !== "") {
                $query->where($range['column'], '<=', $range['to']);
            }
        }
    }
);
```
