### ISSUE TITLE
count() issue in PHP 7.2

### ISSUE THREAD

**Issue by MikeMather** [yajra/laravel-datatables#1579]
### Summary of problem or feature request

I'm having a problem with DataTables in PHP 7.2.
It was working fine with PHP 7.1 but I now get this error when making the table:

**PHP Warning: count(): Parameter must be an array or an object that implements Countable in ~yajra/laravel-datatables-oracle/src/Engines/CollectionEngine on line 218**

I know this is a problem with PHP but I'm wondering if there's any workaround for this issue?

### System details

- Operating System Windows 10
- PHP Version 7.2
- Laravel Version 5.6
- Laravel-Datatables Version 8.3.3

**Comment by yajra** [comment]
Will try to add support for php 7.2 when I got the chance. Thanks for reporting.

**Comment by yajra** [comment]
I just realized, you are not using v8, `CollectionEngine` is for v7 below. Please use dev-master for Laravel 5.6.

**Comment by MRoym** [comment]
Thanks. I followed your update guide for v8 and changed everything from Datatables to DataTables and everything looks good. Also had to change the engines array in the config\datatables.php file.

**Comment by yajra** [comment]
@Shariaty can you please paste the full error stack? Or some snippets to reproduce the issue?

**Comment by Shariaty** [comment]
Sorry, It was my bad i use count() in filter function in a wrong way for php 7.2 and i thought it might be Datatable issue. Problem has been resolved.
