### ISSUE TITLE
removeColumn('id') method ordering does not work

### ISSUE THREAD

**Issue by garbinmarcelo** [yajra/laravel-datatables#1583]
### Summary of problem or feature request
When I use the "removeColumn('id')" method the sort order not works fine.

What can it be?

### Code snippet of problem

```php
return Datatables::of($registros)
                ->removeColumn('id')
                ->make();
```
-->

### System details
- Operating System: Win10
- PHP Version: 7.1
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.10.1

**Comment by yajra** [comment]
How did you build the `$registros`? Is it a collection or a query?

**Comment by marcelogarbin** [comment]
@yajra 

```php
$registros = Publicacao::select(['id', 'numero', 'titulo', 'data_hora_abertura', 'data_hora_encerramento', 'updated_at']);
```
