### ISSUE TITLE
AJAX: Dynamic columns

### ISSUE THREAD

**Issue by garbinmarcelo** [yajra/laravel-datatables#1585]
Hello, 
I know that some issues have been dealt with on this subject. But I would like to know if you have any means of not having to set the Javascript columns of a particular table at all times.

Would anyone have a more dynamic alternative to creating tables just by passing the link via AJAX and the HTML structure?

Ex.:
```html
<table class="table table-bordered table-striped table-hover dataTable" data-url='{{ route('datatable.ajaxLaravel') }}' data-sort='[0, "desc"]'>
    <thead>
    <tr>
        <th width="8%" class="text-center">#</th>
        <th>Name</th>
        <th>Role</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th class="nosort no-print text-center">Action</th>
    </tr>
    </thead>
</table>
```

I already use something like this, but it seems that with Laravel-Datatables v8 my code stopped working and I went to check it and the error precisely because I do not pass the columns in the javascript code, in v7 it is working normally, however v7 I believe it has some sort of bug in sorts when using the "removeColumn()" method.

**Comment by yajra** [comment]
See https://github.com/DataTables/DataTables/issues/273 for something similar. I think this is not yet supported on the main js library.

**Comment by lk77** [comment]
You could show and hide columns as you need i think or delete the datatable and redraw it completly.
