### ISSUE TITLE
FormBuilder dependebcy problem in Html\Bulder

### ISSUE THREAD

**Issue by anfrantic** [yajra/laravel-datatables#159]
```
Unresolvable dependency resolving [Parameter #2 [ <required> $csrfToken ]] in class Collective\Html\FormBuilder
```

Laravel Form Builder Requires $csrfToken to be passed in constructor
laravel 5.1

**Comment by r0bdiabl0** [comment]
Did you resolve this?

**Comment by anfrantic** [comment]
It wasn't actually an issue? my bad :smile: i was using illuminate/html by mistake and there is no pisble way to fix dep injection in there ((

**Comment by r0bdiabl0** [comment]
I was wondering because I am having the same issue. However, I am not using illuminate/html anywhere that I can think of.

**Comment by anfrantic** [comment]
Do you have this
```
Collective\Html\HtmlServiceProvider::class,
```
in your in your app service providers?

**Comment by andreiculda** [comment]
This seems to have fixed the issue for me @anfrantic .Thanks.

**Comment by alihossein** [comment]
thanks a lot @anfrantic .
my problem is solve.
