### ISSUE TITLE
{QUESTION BUTTONS] Configuration to work with ajax

### ISSUE THREAD

**Issue by garbinmarcelo** [yajra/laravel-datatables#1590]
Hi,

Is it possible to configure the buttons to work with the ajax code? 
No need to use the example command: `php artisan datatables:make User`

When I click the PDF button, it returns me the ajax code. But I would like it when I clicked the button it would return the file in PDF.
![datatables](https://user-images.githubusercontent.com/9335588/35245861-c88b556c-ffab-11e7-9177-5261776884c3.gif)

**Comment by yajra** [comment]
Unfortunately, you have to write your own script to generate the pdf if you don't want to use the DataTable service.

TIP: The button script passes an action parameter `action=pdf` that you can use as a flag to switch type of export / request to be processed.

```php
if (request('action') == 'pdf') {
// do export
}

return datatables(...)->toJson();
```

**Comment by marcelogarbin** [comment]
I will try to assemble the data, create a function to print the PDF and other actions of the buttons.

Would you have any tips add, or something already functional about?

Thank you!
