### ISSUE TITLE
Error 500 (Internal Server Error) when filtering records

### ISSUE THREAD

**Issue by NanoDev777** [yajra/laravel-datatables#1593]
I'm experiencing a rather strange error, at the moment everything works very well, but I've noticed the following problem: when I try to search for a record in the search field, I sometimes receive the error: **500 (Internal Server Error).** this happens at the time of writing a filter quickly, I know it sounds weird but that's what happens, it also happens to me to erase the word completely, I understand that when I am writing the word to filter an ajax request is being made, I imagine that there lies the problem, in addition to receiving this error 500 in the console, I receive this annoying alert from javascript: **DataTables warning: table id = example - Ajax error. For more information about this error, please see http://datatables.net/tn/7.** Is there a way to control this?

**Comment by yajra** [comment]
You can remove the alert error by setting `$.fn.dataTable.ext.errMode = 'none';`

On the other hand, better check on laravel logs on what causes the 500 error.

**Comment by narachamus** [comment]
Hello yajra, and thank you so much for this datatables! The same thing happens to me, everything works fine, but if I filter text too fast it shows a 500 error.

**Comment by narachamus** [comment]
The Log message:

[2020-06-21 10:15:28] production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at D:\\laragon\\www\\exlibris\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:44)
[stacktrace]

I don't understand :/
