### ISSUE TITLE
Datatables is getting all records

### ISSUE THREAD

**Issue by josedejesusjaime** [yajra/laravel-datatables#1595]
Hi im getting an curious issue. My datatable is rendering all records from the db. I already check the queries with the developer console, i figured out the query doesnt add the pagination "limit 10 offset 0", it happens in my production server,'cause this part exists in the local developement.  Laravel 5.4 ,datatables 7.x
Here`s the code im using:

`namespace App\DataTables;

use App\Models\Utilities;
use App\Models\Venta;
use Form;
use Yajra\Datatables\Services\DataTable;
use DB;
use App\Models\VentaProducto;

class VentaDataTable extends DataTable
{

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', 'ventas.datatables_actions')
            ->rawColumns(["action", "status"])
            ->editColumn('total', function ($data) {
                return number_format($data->total, 2);
            })
            ->editColumn('status', function ($data) {

                switch ($data->status) {
                    case 'vigente':
                        return "<span class='badge badge-success'>" . $data->status . "</span>";

                        break;
                    case 'reservacion':
                        return "<span class='badge badge-primary'>" . $data->status . "</span>";

                        break;
                    case 'cancelada':
                        return "<span class='badge badge-danger'>" . $data->status . "</span>";

                        break;
                }

            })
            ->make(true);
    }

    /**
     * Get the query object to be processed by datatables.
     *
     * @return \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder
     */
    public function query()
    {
        $from = $this->request()->get('from');
        $to = $this->request()->get('to');
        $sucursal = $this->request()->get('sucursal');
        $status = $this->request()->get('status');
        $cliente = $this->request()->get('cliente');

        $ventas = VentaProducto::select(
            'venta.id_venta',
            'venta.status',
            'folio',
            'cliente.nombre as cliente',
            'sucursal_habitacion.habitacion',
            'usuario_sucursal.nombre as vendedor',
            'producto.nombre as producto',
            'venta_producto.cantidad',
            'venta.fecha as fechaVenta',
            'fecha_pickup',
            'hora_pickup',
            'venta_lugar.lugar',
            'proveedor.razon_social as proveedor',
            'nota',
            'venta_producto.descuento',
            'venta_producto.total',
            'venta_producto.comision'
        )
            ->join("venta", "venta.id_venta", "venta_producto.id_venta")
            ->join("usuario_sucursal", "usuario_sucursal.id_usuario_sucursal", "venta.id_usuario_sucursal")
            ->join("sucursal", "sucursal.id_sucursal", "usuario_sucursal.id_sucursal")
            ->join("venta_lugar", "venta.id_venta_lugar", "venta_lugar.id_venta_lugar")
            ->join("cliente", "venta.id_cliente", "cliente.id_cliente")
            ->join("sucursal_habitacion", "sucursal_habitacion.id_sucursal_habitacion", "venta.id_sucursal_habitacion")
            ->join("proveedor_producto", "proveedor_producto.id_proveedor_producto", "venta_producto.id_proveedor_producto")
            ->join("producto", "producto.id_producto", "proveedor_producto.id_producto")
            ->join("proveedor", "proveedor.id_proveedor", "proveedor_producto.id_proveedor");

        if (\Auth::user()->rol->rol != 'Super Administrador') {
            $ventas->where("venta.id_usuario_sucursal", "=", \Auth::user()->id_usuario_sucursal);
        }
        if (!empty($cliente)) {
            $ventas->where('venta.id_cliente', '=', $cliente);
        }

        if (!empty($from) && !empty($to)) {
            $ventas->whereBetween(DB::raw('DATE_FORMAT(fecha,"%Y-%m-%d")'), [$from, $to]);

        }
        if (!empty($sucursal)) {
            $ventas->where(DB::raw('sucursal.id_sucursal'), '=', $sucursal);
        }

        if (!empty($status)) {
            $ventas->where(DB::raw('venta.status'), '=', $status);
        }

        return $this->applyScopes($ventas);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->addAction(['width' => '20%'])
            ->ajax('')
            ->parameters([
                'language' => [
                    'url' => url('vendor\datatables\lang\es.json')
                ],
                'order' => [2, 'asc'],
                "lengthMenu" => [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Todos"]],
                'dom' => 'lBfrtip',
                'scrollX' => true,
                'buttons' => [
                    ["extend" => "reload", "text" => "<i class='fa fa-refresh'></i> Recargar"],
                    ["extend" => "print", "text" => "<i class='fa fa-print'></i> Imprimir"],
                    [
                        'extend' => 'collection',
                        'text' => '<i class="fa fa-download"></i> Exportar',
                        'buttons' => [
                            'csv',
                            'excel',
                            'pdf',
                        ],
                    ],
                    ["extend" => "colvis", "text" => "<i class='fa fa-list-alt'></i> Seleccionar columnas"],
                ]
            ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    private function getColumns()
    {
        return [
            'status' => ['name' => 'venta.status', 'data' => 'status'],
            'folio' => ['name' => 'venta.folio', 'data' => 'folio'],
            'cliente' => ['name' => 'cliente.nombre', 'data' => 'cliente'],
            'habitacion' => ['name' => 'sucursal_habitacion.habitacion', 'data' => 'habitacion'],
            'vendedor' => ['name' => 'usuario_sucursal.nombre', 'data' => 'vendedor'],
            'producto' => ['name' => 'producto.nombre', 'data' => 'producto'],
            'no_pax' => ['name' => 'venta_producto.cantidad', 'data' => 'cantidad'],
            'fecha_venta' => ['name' => 'venta.fecha', 'data' => 'fechaVenta'],
            'fecha_pickup' => ['name' => 'venta.fecha_pickup', 'data' => 'fecha_pickup'],
            'hora_pickup' => ['name' => 'venta.hora_pickup', 'data' => 'hora_pickup'],
            'lugar' => ['name' => 'venta_lugar.lugar', 'data' => 'lugar'],
            'proveedor' => ['name' => 'proveedor.razon_social', 'data' => 'proveedor'],
            'observaciones' => ['name' => 'venta.nota', 'data' => 'nota'],
            'descuento' => ['name' => 'venta_producto.descuento', 'data' => 'descuento'],
            'total' => ['name' => 'venta_producto.total', 'data' => 'total'],
            'comision' => ['name' => 'venta_producto.comision', 'data' => 'comision'],
            
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'ventas';
    }
}`

**Comment by yajra** [comment]
Your code looks fine, maybe try inspecting if the correct request parameters are being sent properly on the server?

**Comment by TomMeijnaerts** [comment]
check my problem @ https://github.com/yajra/laravel-datatables/issues/2016
maybe it is related
