### ISSUE TITLE
Search not working on relationship

### ISSUE THREAD

**Issue by prakash-pokhrel** [yajra/laravel-datatables#1596]
The sorting throws error on instrument, entity and counterparty wherever it is called from relationship.
 
/**
     * Build DataTable class.
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable($query)
    {
        return datatables($query)
            -> addColumn('action', function ($mmDeal) {
                return $this -> actionPermission($mmDeal);
            })
    }

    /**
     * Get query source of dataTable.
     * @param MmDeal $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(MmDeal $model)
    {
        return $model -> newQuery() -> select(
            'id', 'currency_id', 'customer_reference', 'notional_currency_amount', 
     'trade_date','maturity_date',
            'entity_id', 'counterparty_id', 'instrument_id', 'portfolio_id') -> with('counterparty')
            -> with('entity') -> with('instrument') -> with('currency') -> with('portfolio');
    }

    /**
     * Optional method if you want to use html builder.
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this -> builder()
            -> columns($this -> getColumns())
            -> minifiedAjax()
            -> addAction(['width' => '80px'])
            -> parameters([
                'dom' => 'Bfrtip',
                'buttons' => ['excel', 'csv', 'print', 'copy','pageLength'],
                'pageLength' => 25,
                'aLengthMenu' => [25, 50, 100, 200, 500]
            ]);
    }

    /**
     * Get columns.
     * @return array
     */
    protected function getColumns()
    {
        return [
            'id',
            'customer_reference',
            'portfolio_id' => ['data' => 'portfolio.name', 'name' => 'portfolio.name', 'title' => 'Portfolio'],
            'entity_id' => ['data' => 'entity.short_name', 'name' => 'entity.short_name', 'title' => 'Entity'],
            'counterparty_id' => ['data' => 'counterparty.short_name', 'name' => 'counterparty.short_name', 'title' => 'Counterparty'],
            'instrument_id' => ['data' => 'instrument.instrument_name', 'name' => 'instrument.instrument_name', 'title' => 'Instrument'],
            'currency_id' => ['title' => 'Currency'],
            'trade_date',
            'maturity_date'

        ];
    }

    /**
     * Get filename for export.
     * @return string
     */
    protected function filename()
    {
        return 'MmDeal_' . date('YmdHis');
    }

**Comment by yajra** [comment]
What does the error states? I assume it's an sql generated error. Better check the error logs to get some hints on what's causing the issue.

**Comment by prakash-pokhrel** [comment]
I have the encrypted data so I guess that is the problem. Is there any way that I can override the sorting function with the custom function. Same is the case for searching. I can't search the data since it is encrypted in the database.
I can't find the exact error.

**Comment by foxer2010** [comment]
I have same Error
```
<?php

namespace App\DataTables;

use App\Applicants\applicant;
use Yajra\DataTables\Services\DataTable;

class applicantDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable($query)
    {
        return datatables($query)
            ->addColumn('action', function ($applicant) {
                return '<a href="' . route('app.edit', $applicant->id) . '" class="btn btn-success btn-sm">تعديل</a>
            <a target="_blank" href="' . route('app.print', $applicant->id) . '" class="btn btn-success btn-sm">طباعة</a>
            <a target="_blank" href="' . route('app.download', $applicant->id) . '" class="btn btn-success btn-sm">تحميل</a>';
            })
            ->editColumn('b_date', function ($applicant) {
                return $applicant->b_date ? round((time() - strtotime($applicant->b_date)) / 31536000) : '';
            });
    }

    /**
     * Get query source of dataTable.
     *
     * @param \App\User $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(applicant $model)
    {
        return applicant::with('inArea')->select('id', 'name', 'area', 'b_date');;
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->addAction(['title' => 'العمليات', 'width' => '17%']);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'id'           => ['title' => '#'],
            'name'         => ['title' => 'الأسم'],
            'in_area.name' => ['title' => 'المنطقة'],
            'b_date'       => ['title' => 'العمر'],
        ];
    }
}
```
every thing work perfect but when use 
```
            'in_area.name' => ['title' => 'المنطقة'],
```
I get this error
```
Column not found: 1054 Unknown column 'in_area.name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `applicants` where (LOWER(`applicants`.`id`) LIKE %das% or LOWER(`applicants`.`name`) LIKE %das% or LOWER(`in_area`.`name`) LIKE %das% or LOWER(`applicants`.`b_date`) LIKE %das%)) count_row_table)
```
hint::
"in_area" is a relationship
