### ISSUE TITLE
L4 Sorting

### ISSUE THREAD

**Issue by terratoss** [yajra/laravel-datatables#160]
Greating Community,

i am still using L4 and have some troubles since bllim datatables.

Right now i try to use yajra 3.6.9 but sorting is not working at all. Ive seen in past some issues like that but some one else expecting same issue maybe?

here is example of code :

$return = $this->select(
                array(
                    self::SQL_TABLE_NAME . '.' . $this->getFieldNameByFieldId(self::FIELD_ID),
                    self::SQL_TABLE_NAME . '.' . $this->getFieldNameByFieldId(self::FIELD_NAME),
                )
        );
return Datatables::of($return, true)
                        ->add_column('active', $arr)
                        ->make(true);

loadView: function () {
            table = $("#preset-index").DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/getAllDataPresets",
                "order": [[1, 'desc']],
                "createdRow": function (row, data, index) {
                    if (data.active) {
                        for (var i = 0; i < $(data.active).length; i++) {
                            if (data.active[i] == data.id) {
                                $(row).addClass('success');
                            }
                        }

                    }
                },
                "columnDefs": [
                    {//this prevents errors if the data is null
                        "targets": "_all",
                        "defaultContent": "",
                    }],
                "columns": [
...
                ]
            });

Paul

**Comment by yajra** [comment]
@terratoss, One main difference of bllim's  version to this one is that I specifically use the column name attribute for searching and sorting fields. You would need to defined your columns as follows:

```js
columns: [
{
  data: 'key of object data response',
  name: 'table.field' // this will be the field name to be used when searching and ordering the column
  orderable: 'flag to check if will order this field',
  searchable: 'flag to check if the field will be included on global search'
}
]
```

**Comment by terratoss** [comment]
Hi Yajra,

that was it. name property was missing for sorting. Thank you for the support.

Best Regards
Paul

**Comment by yajra** [comment]
Your welcome! ^_^
