### ISSUE TITLE
Duplicate sql on eager load

### ISSUE THREAD

**Issue by maganius** [yajra/laravel-datatables#1602]
I am not sure that I am doing the right way, but I will try detail my problem.

I have 3 related tables:

* - Item
* - Category
* - Subcategory

The datatable works correctly but I think it makes extra queries, I leave an example here:

https://i.imgur.com/AZGQohO.jpg

```mysql

select `item`.`id`, `item`.`subcategoria_id`, `item`.`nombre`, `item`.`precio` from `item` left join `subcategoria` on `item`.`subcategoria_id` = `subcategoria`.`id` order by `subcategoria`.`nombre` asc limit 10 offset 0;

#extra, no needed
select * from `subcategoria` where `subcategoria`.`id` in ('1', '2')
select * from `category` where `category`.`id` in ('1', '2')
```

As you will see in the red box, two extra queries are being made to the relational tables, which I think is enough with the first sql.

The sql that I am using is this:

```php

return DataTables::of(Item::with(['subcategoria', 'subcategoria.categoria'])
 ->select(['item.id', 'item.subcategoria_id', 'item.nombre', 'item.precio']))
                        ->addColumn('categoria', function($item){
                            return $item->subcategoria->categoria->nombre;
                        })->addColumn('subcategoria', function($item){
                            return $item->subcategoria->nombre;
                        })
                    ->toJson();
```
I am doing something wrong? or it is not possible to avoid it.

**Comment by yajra** [comment]
The extra query is from the eager loading and it's needed to function well. If you don't need it, just remove `with` relation call:

```php
Item::select()..
```

**Comment by maganius** [comment]
Hello yajra

Thanks for reply, If I delete the with relation I can't order or filter for the relation tables.
