### ISSUE TITLE
Json encode float issue

### ISSUE THREAD

**Issue by ToujouAya** [yajra/laravel-datatables#1604]
### Summary of problem or feature request

json encode float issue on php 7.1
I tried to set 
`serialize_precision = -1`
but the data from database is not correct 

### Code snippet of problem

```php
$data = $this->model->join('parts as p', 'p.id', '=', 'production_plans.part_id')
            ->join('countries as c', 'c.id', '=', 'p.country_id')
            ->join('classification_materials as cm', 'cm.id', '=', 'p.classification_material_id')
            ->select(
                'production_plans.part_id',
                **DB::raw('SUM(production_plans.weight) as weight_plans')**,
                DB::raw('GROUP_CONCAT(production_plans.order_id) as orderIds'),
                'p.code as material_classification_code',
                'p.name as material_part_name',
                'cm.name as material_original_name',
                'c.name as material_country_name',
                'production_plans.type',
                'production_plans.production_date'
            )->where('production_plans.type', 0)// 
            ->where('production_plans.part_id', 7)
            ->where('production_plans.production_date', '<=', $tomorrow)
            ->groupBy('production_plans.part_id');

        return $data;
```

The **weight_plans** was caculated from mysql 

Excerpt from multidimensional array (before):

```
array:9 [
    "part_id" => 7
    "weight_plans" => 2.9
    "orderIds" => "1698,1731,1733,1732,1734,1739"
    "material_classification_code" => "00301"
    "material_part_name" => "肩ﾛｰｽ"
    "material_original_name" => "牛"
    "material_country_name" => "輸入"
    "type" => 0
    "production_date" => "2018-01-31"
  ]
```

after json encode

`{"part_id":7,"weight_plans":2.9000000000000004,"orderIds":"1698,1731,1733,1732,1734,1739","material_classification_code":"00301","material_part_name":"\u80a9\uff9b\uff70\uff7d","material_original_name":"\u725b","material_country_name":"\u8f38\u5165","type":0,"production_date":"2018-01-31"}`

### System details

- Operating System Ubuntu Server 16.04
- PHP Version 7.1.2
- Laravel Version 5.4
- Laravel-Datatables Version 7.0

Does anybody have any idea ?

**Comment by yajra** [comment]
I think you just need to set some json parameter via config appropriately to your needs. This how the response being built:

```php
        return new JsonResponse(
            $output,
            200,
            config('datatables.json.header', []),
            config('datatables.json.options', 0)
        );
```

Based on this, you can override the json header and options as needed.
