### ISSUE TITLE
Method with does not exist. Datatable as a Service.

### ISSUE THREAD

**Issue by Drakota** [yajra/laravel-datatables#1605]
### Summary of problem or feature request

Hi, I have a view which needs a ticket before displaying, the problem is that when the table loads I have this message `DataTables warning: table id=dataTableBuilder - Ajax error. For more information about this error, please see http://datatables.net/tn/7`, I check in the request and I have this error `Method with does not exist.`. The problem is that this works the view is correctly displayed with the `$ticket`, it's just the table that doesn't display properly.

### Code snippet of problem

```php
public function show(Ticket $ticket, TicketsDataTable $dataTable)
{
        return $dataTable->render('tickets.edit')->with('ticket', $ticket);
}
```

### System details

- Operating System Windows 10
- PHP Version 7.1.12
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
You need to call with first before the render method.

```php
$dataTable->with('ticket', $ticket)->render('tickets.edit');
```

If you want to send data on the view, use compact instead.

```php
$dataTable->render('tickets.edit', compact('ticket'));
```

**Comment by Drakota** [comment]
`$dataTable->with('ticket', $ticket)->render('tickets.edit');`
Doesn't seems to work, but with `compact` it works as expected.
