### ISSUE TITLE
Error after publish, Class Yajra Not Found

### ISSUE THREAD

**Issue by passasooz** [yajra/laravel-datatables#1610]
### Summary of problem or feature request
I cannot use datatables plugin

I try to install yajra/laravel-datatables-oracle:"~7.0" and I have this problem
Problem 1
    - Installation request for yajra/laravel-datatables-oracle 7.0 -> satisfiable by yajra/laravel-datatables-oracle[v7.0.0].
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - yajra/laravel-datatables-oracle v7.0.0 requires illuminate/view 5.4.* -> satisfiable by illuminate/view[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/view v5.4.0|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.13|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.17|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.19|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.27|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.36|don't install laravel/framework v5.2.45
    - don't install illuminate/view v5.4.9|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

so I try to install yajra/laravel-datatables-oracle:"~6.0" and its work but when I try to doing publish cli return : Class 'Yajra\Datatables\DatatablesServiceProvider' not found

I putted this on app.php (config) 
providers: 
        Yajra\DataTables\DataTablesServiceProvider::class,

aliases: 
        'DataTables' => Yajra\DataTables\Facades\DataTables::class,

So now I don't know what I can do to work with this plugin.

- OSX
- 7
- 5.2
- 6.* / 7.0

**Comment by yajra** [comment]
Please see the old documentation on https://yajrabox.com/docs/laravel-datatables/6.0/installation.

For version 6, `Datatables` uses small `t` on tables, thus provider should be:

```
Yajra\Datatables\DatatablesServiceProvider::class,
```

**Comment by passasooz** [comment]
thanks but I resolved days ago the problem was that I cannot found the
correct version of your plugin because the pages of your website was in
down with 500 eorror

2018-02-13 4:58 GMT+01:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
Good to hear that you resolved it, the docs site went down for a few days but fixed now. Thanks!
