### ISSUE TITLE
Datatable "Internal Server Error" on large data sets

### ISSUE THREAD

**Issue by aliihaidar** [yajra/laravel-datatables#1613]
### Summary of problem or feature request

I've been using yajra-datatables for quite some time and everything's working fine, until I worked with a table that contains 350,000 records. The tables gives an error and when I inspect the console, it shows 500 Internal Server Error.

I called the route from the URL and it shows a blank page, tried the same query on a table of 1,000 records, worked like a charm. Can you please check what's causing this issue??

### Code snippet of problem

This is the function body that I am using

$citizens = Citizen::select(['citizen.*', DB::raw('CONCAT(first_name, " ", last_name) AS full_name')])
		->get();

		return Datatables::of($citizens)
		->addColumn('action', function ($citizen) {

			$buttons = '<a href="'.url("cms/citizens/$citizen->id", [], env('APP_SECURE')).'" class="btn btn-sm btn-icon btn-pure btn-default on-default edit-row waves-effect waves-classic blue-500 padding-5"><i class="icon md-info" aria-hidden="true"></i></a>';
			$buttons .= '<a href="'.url("cms/citizens/delete/$citizen->id", [], env('APP_SECURE')).'" onclick="return confirmDelete(event, $(this).attr(\'href\'));" class="red-500 padding-5 btn btn-sm btn-icon btn-pure btn-default on-default remove-row waves-effect waves-classic" data-toggle="tooltip" data-original-title="Delete"><i class="icon md-delete" aria-hidden="true"></i></a>';
			return $buttons;
		})
		->editColumn('activated', function ($citizen) {
			if($citizen->activated == 1)
				$status = "<span class='text-success'>Active &nbsp;<i class='md-portable-wifi'></i></span>";
			else
				$status = "<span class='text-danger'>Inactive &nbsp;<i class='md-portable-wifi-off'></i></span>";
			return $status;
		})
		->make(true);

### System details

- Operating System
- PHP Version PHP 7.1.7
- Laravel Version 5.1
- Laravel-Datatables Version "yajra/laravel-datatables-oracle": "~5.1"

**Comment by yajra** [comment]
Don't use collection for large datasets. Remove the get on your query.

```php
$citizens = Citizen::select(['citizen.*', DB::raw('CONCAT(first_name, " ", last_name) AS full_name')])
->get();
```

TO

```php
$citizens = Citizen::select(['citizen.*', DB::raw('CONCAT(first_name, " ", last_name) AS full_name')]);
```

**Comment by jishnuvp** [comment]
Hi i have similar issue but with data export functionality.. i could export  upto about 3k data. But when exporting  a large dataset internal server error occurs..
