### ISSUE TITLE
Problem with buttons and Select extension

### ISSUE THREAD

**Issue by ecampoBS** [yajra/laravel-datatables#1614]
### Summary of problem or feature request

So I have implemented the datatables buttons in a Laravel 5.4 environment and it was working fine. The issue I have encountered is when I try to include the Select extension of datatables with my actual setup.

The extension does not seem to work with the default "/vendor/datatables/buttons.server-side.js" file that the documentation instructs to include in the blade template. I have to include the file "https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" for select extension to work, but doing so, the buttons part of the implementation stops working.

I have recently upgraded to Laravel datatables 8 to see if that resolved the issue, but I keep geting the same problem.

The scripts I have included in my blade are the following:

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="/vendor/datatables/buttons.server-side.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script> //If I remove this line the select plugin doesn't work at all
    <link rel="stylesheet" href="https://cdn.datatables.net/select/1.2.5/css/select.dataTables.min.css">
    <script src="{{asset('js/dataTables.select.min.js')}}"></script>

- Operating System: Windows 10 ultimate
- PHP Version: 7.0
- Laravel Version: 5.4
- Laravel-Datatables Version: 8.0

**Comment by yajra** [comment]
I think `buttons.server-side.js` is indeed not fully compatible with the select plugin because it is mostly used on the `client side` implementation. Have you tried following the server side implementation of select plugin? https://datatables.net/examples/server_side/select_rows.html.
