### ISSUE TITLE
yajrabox.com is down

### ISSUE THREAD

**Issue by bellwood** [yajra/laravel-datatables#1615]
yajrabox.com is down  :(

**Comment by cromartie1984** [comment]
:(

**Comment by AGhasemzadeh** [comment]
Hello,
It work well for me.

**Comment by yajra** [comment]
Thanks for reporting, I think we had a ddos attack or something which causes 450% cpu usage. Anyways, I think the server is up now.

**Comment by hussainabuhajjaj** [comment]
still yajrabox not working why ?!

**Comment by apapazisis** [comment]
not working fix please...

**Comment by zorrigas** [comment]
down for me

**Comment by janainadcacaca** [comment]
still yajrabox not working why ?!

**Comment by rzdev** [comment]
yep, down for me too

**Comment by rezapiryghadim** [comment]
Down!
:sob:
:sob:
:sob:
:sob:
