### ISSUE TITLE
Search by column

### ISSUE THREAD

**Issue by danilodorgam** [yajra/laravel-datatables#1616]
### Summary of problem or feature request

I want to know if there is a way when I specify the column I want to search, the backend does not search the word in any column.
https://prntscr.com/ibvpr7

### FrontEnd
Today when I do the research I specify the column to search like this.
draw:1
columns[0][data]:nm_visitante
columns[0][name]:
columns[0][searchable]:true
...
order[0][column]:0
order[0][dir]:asc
start:0
length:10
search[value][nr_registro_geral]:dorgam
search[value][nr_registro_geral]:dorgam
search[regex]:false

### Backend

```        
return datatables()->of(VisitantModel::select('a','b'))->make(true);
```

The result of this is that it returns data when in fact it should not find anything.

### System details

- Operating System: Ubuntu
- PHP Version: 7.2
- Laravel Version: 5.4
- Laravel-Datatables Version

**Comment by deanlaw** [comment]
I do believe that the searchable attribute is true by default, so you need to specify searchable: false for the columns that you don't want to be searched.

**Comment by danilodorgam** [comment]
But if it has two columns, I don’t think it would work.
I wanted to search filter A in column A and filter B in column B.

Currently he searches for Filter A in column A and B

**Comment by tiipiik** [comment]
If I'm right, you also need to use the filter method on your datatable object, like this

```php
            return datatables()->of(VisitantModel::select('a','b'))
            ->filter(function ($query) use ($request) {
                if (isset($request->search['value'])) {
                    $query->where('your_table.your_field', 'like', "%{$request->search['value']}%")
                        ->orWhere('your_table.your_field', 'like', "%{$request->search['value']}%")
                }
            })->make(true);
```

**Comment by danilodorgam** [comment]
I found a solution on the frontend.
```
vm.dtInstance.DataTable
            .column(3).search(vm.filtro.nm_setor)
            .draw();
```

But I'm going to test the @tiipiik  solution

Font: [Datatables AngularJS](https://github.com/l-lin/angular-datatables/issues/473)
