### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by AGhasemzadeh** [yajra/laravel-datatables#1617]
Hello,
We need this package for laravel 5.6

**Comment by runepiper** [comment]
I use the `dev-master` version and it works seamlessly with Laravel 5.6 😉

**Comment by yajra** [comment]
v8.4.0 released with 5.6 support. Thanks!

**Comment by maxram** [comment]
8.4.1 not work with Laravel 5.6

**Comment by Skintillion** [comment]
maxram, you aren't giving any details.

Did you try fresh repo first? Error messages? What doesn't work? Others are saying it works fine.
