### ISSUE TITLE
http://datatables.yajrabox.com/ is down

### ISSUE THREAD

**Issue by tobiekruger** [yajra/laravel-datatables#1619]
### Summary of problem or feature request

Hi, it looks like http://datatables.yajrabox.com/ is down, is there another place I can acces documentation?

**Comment by bellwood** [comment]
Use google cache-view:

https://webcache.googleusercontent.com/search?q=cache:pmghcCyvq8QJ:https://datatables.yajrabox.com/eloquent/order-column+&cd=1&hl=en&ct=clnk&gl=us

**Comment by adw-cr** [comment]
+1

**Comment by yajra** [comment]
Having some issue with the server due to a virus or ddos attack. Working on a fix for it. Sorry for inconvenience.

**Comment by tobiekruger** [comment]
No worries, using google cache has been working great

**Comment by yajra** [comment]
Site was fixed! thanks

**Comment by bellwood** [comment]
Thank you =)

**Comment by RashidAliAnsari** [comment]
Hey....! 
This site again not accessible for 2 days...
And CDN files also not going to connect.. whats the solution plz anyone?
