### ISSUE TITLE
no error, but data not shown, stuck in processing

### ISSUE THREAD

**Issue by radzzii** [yajra/laravel-datatables#1623]
hallo yajra, thank you for your amazing work.
have been using your work for many projects, but this is the first time i really got stuck.

no error, the ajax response is good, but data not shown and processing box keeps showing.

req:
- yajra 8
- laravel 5.5 (homestead)
- vagrant box

routes:
![routes](https://user-images.githubusercontent.com/5517785/36143190-fe719ad2-10dc-11e8-87db-a073b616af80.png)

controller:
![controller](https://user-images.githubusercontent.com/5517785/36143192-feca3192-10dc-11e8-9c42-dbfd25f0baf2.png)

view:
![view](https://user-images.githubusercontent.com/5517785/36143193-ff00cc16-10dc-11e8-9af0-af265cb9371f.png)

ajax response:
![ajax response](https://user-images.githubusercontent.com/5517785/36143195-ff31fdea-10dc-11e8-8ccf-97ce32a41bc3.png)

stuck processing:
![stuck processing](https://user-images.githubusercontent.com/5517785/36143196-ff9fd040-10dc-11e8-9238-0680af8dae2b.png)

thank you very much for your response

**Comment by yajra** [comment]
Hmm, your code looks fine. Maybe try json linting the results? Some issue like this are due to invalid json response? I usually validate the response on https://jsonlint.com/ for some weird issues.

**Comment by radzzii** [comment]
wow, what a fast response.
ive tried to linting the response, but the result is a valid json.

i tried to console.log the datatable, and still it shows the good result
![screen shot 2018-02-13 at 5 08 40 pm](https://user-images.githubusercontent.com/5517785/36144427-911a6046-10e0-11e8-8a91-3a4519b408bc.png)

**Comment by yajra** [comment]
Is there any js error on the console log? Are you hooking any other scripts or any callbacks scripts?

**Comment by radzzii** [comment]
i really appreciate your response, its really a big thanks to you 😄 

there is no error in my console log.
and i dont hook it to other script, just this script to load the data to my table.
and no callbacks script.

**Comment by radzzii** [comment]
has been fixed.
the problem is me, not your work.

i (somehow), load the javascript twice.
first is from me, to load jquery (in app layout).
second is default from laravel (in below of the layout blaed).
after i remove the laravel default src, it work perfectly.

thanks you very much for your support arjay!
