### ISSUE TITLE
Eloquent eager loading causes SQL error when sorting and models returned do not have relationship

### ISSUE THREAD

**Issue by paulMDA** [yajra/laravel-datatables#163]
Using Laravel 5.1.12 and Laravel Datatables 5.11.6, attempting to use an Eloquent model retrieval as the source where there are no related models returned in the subset of records, results in invalid SQL:

```php
$devices = Device::with('assigned_user',
    'completed_by_user')
    ->select('*');
```

Results in the following SQL when attempting to sort by assigned user name:

```sql
select top 10 * from [prefix_devices] order by [name] asc
```

The SQL above does not join in the necessary table for the sort, using the requisite [alias].[column] convention considering the user model is being related twice.

**Comment by yajra** [comment]
Are you trying to sort on eager loaded model column? If yes, it's currently not supported. You can only sort relations using join statement.

**Comment by paulMDA** [comment]
Yes, correct. Thanks for the clarification. Once I switched to fluent with left joins, I was able to do accomplish what I was trying to do.
