### ISSUE TITLE
Ordering/Searching related model - WRONG DB TABLE

### ISSUE THREAD

**Issue by FilipQL** [yajra/laravel-datatables#1630]
### Summary of problem (with code snippets of problem)

I have `User` model which has the following relationship with the `SupportLevel` model:

```
    public function activeSupportLevel()
    {
        return $this->belongsTo(SupportLevel::class, 'support_level_id');
    }
```

In `SupportLevel` model I have specified DB table name and relationship with the `User` model:

```
protected $table = 'support_levels';

...

    public function users()
    {
        return $this->hasMany(User::class, 'support_level_id');
    }
```

In jQuery Datatables setup (in blade view) there is:

```
                columns: [
                    . . .
                    { data: 'active_support_level.name', name: 'active_support_level.name', responsivePriority: 1},
                    . . .
                ],
```

Finally, there is `UserController@process`: 

```
    public function process()
    {
        $users = User::select('users.*')->with(['activeSupportLevel', 'status', 'market']);

        return Datatables::of($users)
            ->editColumn('username', function ($user) {
                return "<a target='_blank' href='/users/{$user->id}'>{$user->username}</a>";
            })
            ->editColumn('created_at', function ($user) {
                return format_datetime($user->created_at);
            })
            ->rawColumns(['username'])
            ->make(true);
    }
```

Everything is loaded and displayed OK, without any errors but when I try to "order" by the "Active Support Level" column - I am getting the following error:

![error](https://user-images.githubusercontent.com/18264428/36322027-2b2762e8-134c-11e8-9222-f7dc2fd79182.png)

As you can see - it tries to order by `active_support_level.name`, but that table does not exists. The table should be `support_levels` as it is specified in the `SupportLevel` model:
```
protected $table = 'support_levels';
```
... but it is ignored.

### System details
- Operating System: Ubuntu 16.04 (Laravel Homestead)
- PHP Version PHP 7.1 (Laravel Homestead)
- Laravel Version 5.4
- Laravel-Datatables Version 8.4.1

**Comment by yajra** [comment]
I think on columns, you should use the function name of the relation.

```php
 { data: 'active_support_level.name', name: 'activeSupportLevel.name', responsivePriority: 1},
```
