### ISSUE TITLE
filterColumn and $query->having() or $query->havingRaw not parsed in SQL query

### ISSUE THREAD

**Issue by eelco2k** [yajra/laravel-datatables#1633]
### When defining a filterColumn it's not possible to use having or havingRaw in $query.

$query = DB::table('flights')
                     ->select(
                    DB::raw("CONCAT_WS(',', GROUP_CONCAT(DISTINCT flighttype.shortname ORDER BY flighttype.shortname ASC )) AS type"),
                    )
                    ->groupBy('flight.id')

return DataTables::of($query)
->filterColumn('type', function($query, $keyword) {
                    $query->having('type', 'LIKE', '%'.$keyword . '%');
                    //or
                    // $query->havingRaw("type LIKE '%".$keyword.'%");
                })->toJson();

ps. the query is much complexer with joins but for this example this should be sufficient.  

When i debug the query with ($query->toSql()) it just doesn't parse the having in the query. 

### System details
- Debian 8
- PHP 7.0
- Laravel 5.5
- Laravel-Datatables 8.*

**Comment by fikrimi23** [comment]
same problem on, php 7.1, Laravel 5.4, Laravel-Datatables-Oracle 7.*

**Comment by yajra** [comment]
I think this is because `having` sql does not work on nested where clause afaik. A workaround for this is to include the clause before passing it to dataTable.

```php
$query = DB::table('flights')
->select(
DB::raw("CONCAT_WS(',', GROUP_CONCAT(DISTINCT flighttype.shortname ORDER BY flighttype.shortname ASC )) AS type"),
)
->having('type', 'LIKE', '%'.$keyword . '%');
->groupBy('flight.id')

return DataTables::of($query)
->filterColumn('type', function($query, $keyword) {
})->toJson();
```

**Comment by hhummell81** [comment]
In service implementation, how can I access to $keyword variable inside the query method?

Thanks!

**Comment by yajra** [comment]
@hhummell81  you can always use the request helper of laravel. Something like `request('search.value')`.

**Comment by hhummell81** [comment]
That makes sense, thanks a lot!

**Comment by hhummell81** [comment]
By the way, is this workaraound works, and "can't have havingraw in nested queries" is an issue of Laravel, shouldn't this issue be closed? :)

**Comment by benyaminl** [comment]
> I think this is because `having` sql does not work on nested where clause afaik. A workaround for this is to include the clause before passing it to dataTable.
> 
> ```
> $query = DB::table('flights')
> ->select(
> DB::raw("CONCAT_WS(',', GROUP_CONCAT(DISTINCT flighttype.shortname ORDER BY flighttype.shortname ASC )) AS type"),
> )
> ->having('type', 'LIKE', '%'.$keyword . '%');
> ->groupBy('flight.id')
> 
> return DataTables::of($query)
> ->filterColumn('type', function($query, $keyword) {
> })->toJson();
> ```

Can we add it into documentation on https://yajrabox.com/docs/laravel-datatables/master/filter-column? How to contribute on writting this? Thank you.

**Comment by yajra** [comment]
@benyaminl docs can be updated on this repo https://github.com/yajra/laravel-datatables-docs/blob/master/filter-column.md.

When my laravel queries doesn't work, I usually write it as plain SQL first. If it works, I then convert it to Laravel query builder. You can also inspect the generated SQL on ajax response for debugging.

**Comment by yajra** [comment]
Closing as suggested by @hhummell81 since this is more of a framework behavior. Thanks!

**Comment by m33ts4k0z** [comment]
Hello,

I believe this no longer works. Is there another way of doing it @yajra ?
