### ISSUE TITLE
Datatable 5.4 to 6 upgrade

### ISSUE THREAD

**Issue by jestinas** [yajra/laravel-datatables#1636]
### Summary of problem or feature request

I've upgraded laravel 5.2 to 5.3 and started getting this error. 

> 'ErrorException in BaseEngine.php line 844:
> array_map(): Argument #2 should be an array'

So, I had to upgrade datatable 5.4 to 6. Now, I need the query object, input and columns from datatable. But Datatables::of($builder) doesn't return Datatable class object and I will not get query object, input and columns from  Datatables::of($builder).

### Code snippet of problem

```
$this->instance = Datatables::of($builder);
$this->query = $this->instance->query;
/* All the Get/ Post Parameters from datatable  in client/browser site */
$this->input = $this->instance->input;
/* Query Type: Eloquent, QueryBuilder, Collection */
$this->query_type = $this->instance->query_type;
$this->columns = $this->instance->columns;
```

### System details

- Operating System : Windows 10
- PHP Version : 7.1
- Laravel Version : 5.3
- Laravel-Datatables Version : 6.*

**Comment by yajra** [comment]
Please see upgrade guide docs for ref: https://yajrabox.com/docs/laravel-datatables/master/upgrade
