### ISSUE TITLE
Use laravel-datatables with external data

### ISSUE THREAD

**Issue by kasperdeboerdev** [yajra/laravel-datatables#1637]
Hello,

Is it possible to load datatables with external data?

**Comment by danilodorgam** [comment]
would not it be better to use the datatables directly from the front?

**Comment by Skintillion** [comment]
What do you mean "External Data"?

Like, from another website?

**Comment by Drillyus** [comment]
Hi,
 I have the same question , in my case , i want to use it to show a datatable with list of email get via imap.
Best regards

**Comment by Skintillion** [comment]
Just setup Laravel to connect to the information you want using the proper connector.

Nothing specific enough in this thread to elaborate any further than that.

**Comment by Drillyus** [comment]
I don't undestrand, what do you mean by "Just setup Laravel to connect the information".
Actually I have an Array with my messages and i put this like that :+1: 
`public function inbox(EmailsDataTable $dataTable)
	{
		return $dataTable->with(['folder' => 'Inbox','msgs' => $this->getInboxMsgs(true)])->render('webmail');
	}`
But i don't see how use the msgs array in my Datatable

**Comment by yajra** [comment]
@Drillyus you also need to pass the with on dataTable instance.

This code passes the data to the DataTable service class:
```
$dataTable->with(['folder' => 'Inbox','msgs' => $this->getInboxMsgs(true)])
```

To include the data on json response, use something like:
```
function dataTable($query) {
  return dataTable($query)->with('folder' => $this->folder])->toJson()
}
```

See https://yajrabox.com/docs/laravel-datatables/master/response-with for ref.
