### ISSUE TITLE
Need dropdown filler example

### ISSUE THREAD

**Issue by hohuuhau** [yajra/laravel-datatables#1639]
Hello,
I'm try to use create dropdown list (country and region) with filler in footer but i don't see any example.
I'm newbie php, so you can send me example for dropdown list?

Thanks you.

- Operating System: Windows 10
- PHP Version: 7.1.11
- Laravel Version: 5.4
- Laravel-Datatables Version: laravel-datatables-oracle": "~8.0"

**Comment by Skintillion** [comment]
A drop down list?

```
<select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
```

What you are asking isn't very clear though. Please elaborate and I don't know what this has to do with datatables.

**Comment by hohuuhau** [comment]
@Skintillion Thanks for reply.
I have two table (country and region). I want use filter in footer with select option. Select country -> select region. I found this (https://datatables.net/examples/api/multi_filter_select.html) use with datatables, but i don't know how to use with laravel-datatables.

**Comment by Skintillion** [comment]
https://datatables.yajrabox.com/eloquent/post-column-search

Just make these drop downs instead.

**Comment by hohuuhau** [comment]
Thanks you, i will try again.
