### ISSUE TITLE
Using Eloquent models as the source with escapeColumns() set attempts to apply htmlentities() to an array

### ISSUE THREAD

**Issue by paulMDA** [yajra/laravel-datatables#164]
Using Laravel 5.1.12 and Laravel Datatables 5.11.6, when using an Eloquent model retrieval as the source and applying the escapeColumns() method, the following error is returned:

```php
$devices = Device::with('assigned_user',
    'completed_by_user')
    ->escapeColumns()
    ->select('*');
```

ErrorException in <path>/vendor/laravel/framework/src/Illuminate/Support/helpers.php line 454:
htmlentities() expects parameter 1 to be string, array given

**Comment by yajra** [comment]
@paulMDA thanks for reporting. Fixed on v5.11.7. In addition, you can now optionally escape eager loaded columns by declaring like `escapeColumns(['id', 'assigned_user.name'])`. Use array dot notation for eager loaded models. Thanks!
