### ISSUE TITLE
Custom filter in initComplete on a separate blade file

### ISSUE THREAD

**Issue by manelsanz** [yajra/laravel-datatables#1640]
### Summary of problem or feature request

Hello everyone, specially @yajra for this awesome work you have done with DataTables on Laravel.

I'm trying to put the code of function 'initComplete' to a separate blade file, but with no luck. The error I'm getting is from JS console: 

`b.fn.apply is not a function`

But I supose that is happening here is basically that new blade file is not found by DataTable plugin.

### Code snippet of problem

What I'm doing:

Partial of file EmployeesDataTable.php:

```php
    public function html()
    {
        return $this->builder()
        ->columns($this->getColumns())
        ->minifiedAjax()
        ->parameters([
            'order'   => [[0, 'asc']],
            'initComplete' => 'employees.filters',
        ]);
    }
```

File /resources/views/employees/filters.blade.php:

```php
function () {
    $(".dataTables_filter label input").attr("placeholder", "Search all employees").removeClass("form-control-sm");

    var filters =
    `<form class="form-row align-items-center ml-4">

    <span class="mr-1" title="Filters"><i class="fas fa-filter"></i></span>

    <div class="col-auto d-inline">

    <select class="form-control" id="exampleFormControlSelect1">
        <option>Type</option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
    </select>

    </div>

    <button type="submit" class="btn btn-secondary ml-1"><i class="fas fa-filter"></i> Filter</button>

    </form>`; $("#filters").append(filters);  }
```

- Operating System: Windows 10
- PHP Version: 7.1
- Laravel Version: 5.5
- Laravel-Datatables Version: 8

**Comment by Skintillion** [comment]
I already said, you can't just do "employee.filters"

You have to include it using a blade function so it is processed and added into the script.

@include('employee.filters')

**Comment by manelsanz** [comment]
@Skintillion I answer by this thread, because the other was closed. The proposed '@include' don't works. Now I have no one JS error, and the datatable is working but the filters are not added in DOM. 
I followed this thread: [https://github.com/yajra/laravel-datatables/issues/422](url)

But this don't work. And I need it to multiple reasons: 
- Better organization of code
- Control if is Admin or not to show more or less filters

Thanks for the replies.

**Comment by Skintillion** [comment]
I could not find reference to that anywhere. 

Is it being properly included in your script?

What does the source show in Chrome?

**Comment by manelsanz** [comment]
I found the way to do this, at the end.
It's as easy as that:

```php
'initComplete' => view('employees.filters'),
```
I hope this helps anyone, and please, consider adding it at the docs. 
Thanks @Skintillion for the answers.

**Comment by Skintillion** [comment]
Ah, I meant that when I said @include. I was thinking blade by accident.
