### ISSUE TITLE
How to show and search metadata of any object. 

### ISSUE THREAD

**Issue by a1iraxa** [yajra/laravel-datatables#1641]
Hi everyone! 

I have a `patient's` model with a `one-to-many` relationship to `patient-meta` (columns: id, patient_id, key, value). There are a number of keys and values paired saved against one patient e.g: (1, 2, DOB, '12-28-1992');

Patient Model:
```
class Patient extends Model
{
    /**
     * Get the patient-metas associated with the patient.
     */
    public function metas()
    {
        return $this->hasMany(PatientMeta::class);
    }
    /*
     *Get patient meta by key or set default
     */
    public function getPatientMeta($key = '', $defaut = '') {
        
        $key = trim($key);
        
        if( '' == $key ){
            return $defaut;
        }
        
        $metas = $this->metas->filter(function ($metas) use ($key) {
            return $metas->key === $key;
        });

        if ($metas->count() > 0) {
            return $metas->first()->value;
        }
        
        return $defaut;
    }
    

}
```

PatientMeta Model:
```
class PatientMeta extends Model
{
    /**
     * Get the patient that owns the this meta.
     */
    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }
}
```
I have gone through official doucmentation [Has Many Demo](https://datatables.yajrabox.com/relation/has-many). But its not working ffor me.

I want to list patient data with its metadata like this:

| Name | Gender `(from meta-table)` |  Phone `(from meta-table)` | Address `(from meta-table)` | email  `(from meta-table)`| status | 
| -------------| ------------- | ------------- | ------------- | ------------- | ------------- |
| Foobar| Male  | 999999999  | This is dummy address | foo@bar.com | active |
| Baz | Female | 888888888  | This is dummy address2 | baz@new.com | inactive |

What I have done so far: 
```
    /**
     * Get patients
     */
    public function getPatients()
    {
        $query = Patient::with('metas')->select('patients.*');
        return Datatables::eloquent($query)
                ->addColumn('gender', function (Patient $patient) {
                    return $patient->getPatientMeta('gender');
                })
                ->addColumn('mobile_number', function (Patient $patient) {
                    return $patient->getPatientMeta('mobile_number');
                })
                ->addColumn('address', function (Patient $patient) {
                    return (string) getAddressLink( $patient->getPatientMeta('address') );
                })
                ->addColumn('email', function (Patient $patient) {
                    return (string) $patient->getPatientMeta('email') ;
                })
                ->addColumn('status', function (Patient $patient) {
                    return (string) $patient->getPatientMeta('status') 
                })
                ->make(true);
    }
```
```
$('#patients-data-table').DataTable({
	processing: true,
	serverSide: true,
	ajax: "{!! route('datatable.get.patients') !!}",
	columns: [
		{data: 'first_name', name: 'patients.first_name'},
		{data: 'gender', name: 'metas.key'},
		{data: 'mobile_number', name: 'metas.key'},
		{data: 'address', name: 'metas.key'},
		{data: 'email', name: 'metas.key'},
		{data: 'status', name: 'patients.status'},
	]
});
```

Everything is working fine, except sorting and de-sorting on meta values. 
I received following error on sroting meta values column. 
`local.ERROR: BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::getForeignKey() in /home/ubuntu/workspace/hvgp-crm/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2445`

### System details

- Operating System:  Ubuntu on C9 IDE
- PHP Version 7.0.1
- Laravel Version 5.4.*
- Laravel-Datatables Version ^6.0

**Comment by Skintillion** [comment]
Make them attributes instead.

**Comment by a1iraxa** [comment]
I didn't get you. what do you mean by 

> Make them attributes instead.

**Comment by Skintillion** [comment]
https://laravel.com/docs/5.6/eloquent-mutators

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    /**
     * Get the user's first name.
     *
     * @param  string  $value
     * @return string
     */
    public function getFirstNameAttribute($value)
    {
        return ucfirst($value);
    }
}
```

**Comment by a1iraxa** [comment]
no, no. you are getting it wrong. Actually, I have a patient with multiple meta-data (just like wp post-meta and user-meta). and I am getting patient meta just filtering meta objects by key.
 patient-meta-table structure is:

| id | patient_id `(from patient-table)` |  key | value | 
| ------| ----- | ---- | -----|
| 1 | 10  | gender | male |
| 2 | 10  | dob| 28-12-1991|
| 3 | 10  | address | this is dummy address |
| 4 | 10  | phone| 8879878979 |
| 5 | 10  | email | foo@bar.com |
| 6 | 15  | gender | female |
| 7 | 15  | dob| 28-12-1991|
| 8 | 15  | address | this is dummy address too |
| 9 | 15  | phone| 4345435435 |
| 10 | 15  | email | baz@new.com |

I want to list patient data with its metadata like this:

| Name | Gender `(from meta-table)` |  Phone `(from meta-table)` | Address `(from meta-table)` | email  `(from meta-table)`| status | 
| -------------| ------------- | ------------- | ------------- | ------------- | ------------- |
| Foobar| Male  | 999999999  | This is dummy address | foo@bar.com | active |
| Baz | Female | 888888888  | This is dummy address2 | baz@new.com | inactive |



```
public function getPatientMeta($key = '', $defaut = '') {
        
        $key = trim($key);
        
        if( '' == $key ){
            return $defaut;
        }
        
        $metas = $this->metas->filter(function ($metas) use ($key) {
            return $metas->key === $key;
        });

        if ($metas->count() > 0) {
            return $metas->first()->value;
        }
        
        return $defaut;
    }
```

**Comment by Skintillion** [comment]
Yes, and if you make it an attribute, you can search it.

The problem is you are trying to search your model on columns that aren't part of your model. If you make them attributes, you solve that problem.

**Comment by a1iraxa** [comment]
Yes, by making them attributes issue will be fixed. But I have a number of fields which are being saved in meta-table, some of them are optional, so I can not make patient model rushy by creating too many columns with optional values. 

Listing and search in data-table are working fine, just sorting column with meta-data are creating the issue.

**Comment by Skintillion** [comment]
From what I can see, your choices are to create the attributes, or not use a meta table and include the details as part of the patient record. You can't search something that doesn't exist.

**Comment by dhcmega** [comment]
Hi @Skintillion , this will be the case also in regular any one-to-many relation? Let's say a user has many phone numbers, would it be posible to show them comma separated as if they were a regular one to one relation? thanks!
