### ISSUE TITLE
data-tooltip-color not working

### ISSUE THREAD

**Issue by BAKTETE** [yajra/laravel-datatables#1644]
### Summary of problem or feature request

data-tooltip-color not working 

### Code snippet of problem
this is my `drawCallback`
```
$('[data-provide="tooltip"]').tooltip();
```

this is what  `addColumn` have
```
->addColumn('action', function ($membre) {

      return '<nav class="nav gap-1 fs-16">
                  <a class="nav-link disabled hover-warning" data-provide="tooltip" data-tooltip-color="warning" data-original-title="Modifier" href="'. route('membre.edit', $membre->id) .'"><i class="ti-pencil"></i></a>
                     
                                    
       <form method="POST" action="'. action('MembreController@destroy', ['id' => $membre->id]) .'" class="delete_form">
             <input type="hidden" name="_token" value="'.csrf_token().'">
             <input type="hidden" name="_method" value="DELETE">
             <a class="nav-link disabled hover-danger delete-btn" data-provide="tooltip" data-tooltip-color="danger" data-original-title="Supprimer" href="#">
             <i class="ti-trash"></i>
              </a>
        </form>


        </nav>';
 })
       
->rawColumns(['action'])`
```
PS if i use partials the response become slow if i include some permission check like `@can @endcan`
the response become even slower 20 seconds +
```
->addColumn('action', function ($membre) {
      return view('partials.membre.action', compact('membre))->render();
 })
```

### System details

- Operating System Ubuntu 17.10
- PHP 7.2.2
- Laravel 5.6
- Laravel-Datatables 8.4

**Comment by Skintillion** [comment]
Are you trying to apply a class as a color?

**Comment by BAKTETE** [comment]
in a file called **app.min.js**
`a('[data-provide~="tooltip"]').each(function(){var b="";a(this).hasDataAttr("tooltip-color")&&(b=" tooltip-"+a(this).data("tooltip-color")),a(this).tooltip({container:"body",trigger:"hover",template:'<div class="tooltip'+b+'" role="tooltip"><div class="arrow"></div><div class="tooltip-inner"></div></div>'})})`
in **app.min.css**
`.tooltip-warning.bs-tooltip-bottom .arrow::before{border-bottom-color:#faa64b}.tooltip-warning.bs-tooltip-top .arrow::before{border-top-color:#faa64b}.tooltip-warning.bs-tooltip-right .arrow::before{border-right-color:#faa64b}.tooltip-warning.bs-tooltip-left .arrow::before{border-left-color:#faa64b}.tooltip-warning`

**Comment by BAKTETE** [comment]
I've found a solution in case someone come across this situation 
in the `drawCallback ` function add this lines

`$('[data-provide~="tooltip"]').each(function(){var b="";$(this).hasDataAttr("tooltip-color")&&(b=" tooltip-"+$(this).data("tooltip-color")),$(this).tooltip({container:"body",trigger:"hover",template:'<div class="tooltip'+b+'" role="tooltip"><div class="arrow"></div><div class="tooltip-inner"></div></div>'})});`

**Comment by Skintillion** [comment]
I think you're going about this the wrong way, but glad you found a solution that works for you.
