### ISSUE TITLE
Print button display raw HTML in safari

### ISSUE THREAD

**Issue by Arkhas** [yajra/laravel-datatables#1646]
### Summary of problem or feature request

when using the print button, at least in safari 11.0.3 and 11.0.1 the generated blob is not render, but raw HTML is render instead

### System details

- Operating System
Debian wheezy
- PHP Version
PHP 7.1.8
- Laravel Version
Laravel Framework 5.5.19
- Laravel-Datatables Version

```
yajra/laravel-datatables-buttons      v3.1.0             Laravel DataTables Buttons Plugin.
yajra/laravel-datatables-html         v3.2.1             Laravel DataTables HTML builder plugin for Laravel 5.4+.
yajra/laravel-datatables-oracle       v8.3.2             jQuery DataTables API for Laravel 4|5
```

**Comment by Skintillion** [comment]
You have no code sample or anything. How can we help?

My guess is you forgot this:

https://yajrabox.com/docs/laravel-datatables/master/raw-columns

**Comment by Arkhas** [comment]
Yeah I should have precise, that it work well in chrome and firefox and what I meant by raw html was this : 

<img width="1231" alt="capture d ecran 2018-03-06 a 11 30 35" src="https://user-images.githubusercontent.com/5020806/37027532-de49daac-2131-11e8-8504-8f734f004caa.png">

on safari and this 

<img width="743" alt="capture d ecran 2018-03-06 a 11 31 59" src="https://user-images.githubusercontent.com/5020806/37027591-16053036-2132-11e8-9c2e-205f0bd7b1a5.png">

on chrome

Not that the content INSIDE the columns where display on raw html

**Comment by Skintillion** [comment]
What does the source show?

**Comment by Arkhas** [comment]
it is the source direclty printed in the browser, not interpreted at all.

The inspector show this : 

<img width="646" alt="capture d ecran 2018-03-07 a 11 06 51" src="https://user-images.githubusercontent.com/5020806/37086360-ae039e34-21f7-11e8-927a-72b771594f1a.png">

**Comment by Skintillion** [comment]
Strange it's wrapping everything in a pre tag.

**Comment by deanlaw** [comment]
I found a stackoverflow question regarding this type of behavior in Chrome being caused by an incorrect content type header. https://stackoverflow.com/questions/27914693/why-is-chrome-loading-my-html-in-a-pre-tag. Could this be a similar situation?

**Comment by Skintillion** [comment]
No, the output is wrapped in a <PRE> tag, which is causing it to not read the html properly.

**Comment by FabienLucini** [comment]
Hi,
I don't know if it is a deliberate behaviour of Safari, but since it always wrap the content of the blob when printing, I decided to go with another solution : submit a form, instead of creating a blob

So, in buttons.server-side.js : 
```
DataTable.ext.buttons.postPrint = {
    className: 'buttons-print',

    text: function (dt) {
        return '<i class="fa fa-file-pdf-o"></i> ' + dt.i18n('buttons.print', 'Print');
    },

    action: function (e, dt, button, config) {
        var url = dt.ajax.url() || window.location.href;
        var params = _buildParams(dt, 'print');
        
        params = decodeURIComponent($.param(params)).split('&');
        var form = '';
        $.each(params, function (key, value) {
            var fieldParams = value.split('=');
            form += '<input type="hidden" name="' + fieldParams[0] + '" value="' + fieldParams[1] + '">';
        });
        $('<form action="' + url + '" method="POST">' + form + '</form>').appendTo('body').submit();

    }
};
```
