### ISSUE TITLE
Searchable columns with selectSub (Sub query)

### ISSUE THREAD

**Issue by SGarridoDev** [yajra/laravel-datatables#1647]
### Summary of problem or feature request
Hi,
I've a datatable (service implementation with server side) with Laravel. 
This datatable get some columns using a selectSub (sub query), and this columns getting an error when I do a search with the search box input. 
To avoid  the error I marked that columns with **"searchable: false, orderable: false"** but I need to search for these columns too.

Can I search by column **Tags** using **filterColumn** api? And how?
Any suggestions?
Thanks in advance.

### Code snippet of problem
Columns:
```php
$columns = [['name' => 'u.id', 'data' => 'id', 'title' => __('ID')],
['name' => 'u.name', 'data' => 'name', 'title' => __('Name')],
['name' => 'u.email', 'data' => 'email', 'title' => __('eMail')],
['name' => 'tags', 'data' => 'tags', 'title' => __('Tags')]];
```
Query:
```php
$query = \DB::table('users as u')->select('u.id', 'u.name', 'u.email');

//tags (obtain tags list, separated by comma, in one column)
$subQueryTags = DB::table('tags as t')
          ->whereColumn('t.user_id', 'u.id')
          ->selectRaw("GROUP_CONCAT(DISTINCT t.tag ORDER BY t.tag SEPARATOR ', ')");
$query->selectSub($subQueryTags, 'tags');
//end tags

$query->where('manager_id', \Auth::user()->id);
```
DataTable:
```php
$datatable = $this->datatables->of($query)
->editColumn('name', function ($data) {
      return '<a href="'.url('users/edit/'.$data->id).'">'.$data->name.'</a>';
})
->setTotalRecords($query->count())
->rawColumns(['name'])
->make(true);
```

### Tests
I've tried with **filterColumn** without success:
```
// Global search function
if ($keyword = $this->input['search']['value']) {
   $datatable->filterColumn('tags', 'whereRaw', "GROUP_CONCAT(DISTINCT t.tag ORDER BY t.tag SEPARATOR ', ') like ? ", ["%$keyword%"]);
}
```

### System details
- PHP 5.6.4
- Laravel Version 5.4
- Laravel-Datatables Version 7.0

**Comment by Skintillion** [comment]
Here is my datatables filter trait

```
<?php

namespace App\Traits;

trait DatatablesFilterTrait
{
  public function applyFilters($model)
  {
    if($this->request()->has('filters')){
      //For each filter add query options.
      foreach($this->request()->get('filters') as $column => $filter){   
        if($filter['type'] == 'numeric'){
          $model->where($column, $filter['context'], $filter['value']);
        }
        if($filter['type'] == 'relation') {
          //For relationships we include null values for whereNotIn to retain extras. Will need an option to choose "Not null" as well in the future
          if($filter['context'] == 'in') {
            $model->whereIn($column, is_array($filter['value']) ? $filter['value'] : [$filter['value']]);
          } else {
            $model->where(function ($query) use ($column,$filter) {
              return $query
              ->whereNotIn($column, is_array($filter['value']) ? $filter['value'] : [$filter['value']])
              ->orWhereNull($column);
            });
          }
        }
        if($filter['type'] == 'string') {
          $model->where($column, $filter['context'], $filter['context'] == 'like' ? '%'.$filter['value'].'%' : $filter['value']);
        }
        if($filter['type'] == 'range') {
          $model->whereBetween($column, explode(";",$filter['value']));
        }
        if($filter['type'] == 'date') {
          if ($filter['context'] == 'between')
          {
            $model->whereBetween($column, [$filter['value'],$filter['secondvalue']]);
          } else {
                      //dd($filter['context']);
            $model->where($column,$filter['context'], $filter['value']);
          }

        }
      }
    }
  }
}
```

**Comment by Skintillion** [comment]
Here is part of my datatabase filters trait dealing with relationships

          //For relationships we include null values for whereNotIn to retain extras. Will need an option to choose "Not null" as well in the future
          if($filter['context'] == 'in') {
            $model->whereIn($column, is_array($filter['value']) ? $filter['value'] : [$filter['value']]);
          } else {
            $model->where(function ($query) use ($column,$filter) {
              return $query
              ->whereNotIn($column, is_array($filter['value']) ? $filter['value'] : [$filter['value']])
              ->orWhereNull($column);
            });
          }

**Comment by Skintillion** [comment]
You might have to filter instead of search if you want to do this. It works much better for linked tables you want to search without adding them as attributes.

**Comment by Skintillion** [comment]
Why are you doing it raw instead of using eloquent?

**Comment by SGarridoDev** [comment]
Hi @Skintillion,
The problem is not whether I use raw queries or eloquent methods, I could use eloquent without problem. Really the problem exists at the subquery that get the user tags.
How I can search by this subquery(column)?

Thanks for you reply.

**Comment by Skintillion** [comment]
Use a scope?

**Comment by SGarridoDev** [comment]
I don't need to use scope, but if I used scope I would have the same problem, I think. As I indicated above, the problem is when I filter by tags column because this column is a subquery into select of parent query.

**My query:**
```
$query = \DB::table('users as u')->select('u.id', 'u.name', 'u.email');

//tags (obtain tags list, separated by comma, in one column)
$subQueryTags = DB::table('tags as t')
          ->whereColumn('t.user_id', 'u.id')
          ->selectRaw("GROUP_CONCAT(DISTINCT t.tag ORDER BY t.tag SEPARATOR ', ')");
$query->selectSub($subQueryTags, 'tags');
//end tags

$query->where('manager_id', \Auth::user()->id);
```
**Datatable columns**:
```
$columns = [['name' => 'u.id', 'data' => 'id', 'title' => __('ID')],
['name' => 'u.name', 'data' => 'name', 'title' => __('Name')],
['name' => 'u.email', 'data' => 'email', 'title' => __('eMail')],
['name' => 'tags', 'data' => 'tags', 'title' => __('Tags')]];
```
In the datatable columns, **data** is equivalent to the column alias and **name** is equivalent to the column name. In my query the **alias** is "**tags**", but what is the column name? 

This would be the column name?
``` GROUP_CONCAT(DISTINCT t.tag ORDER BY t.tag SEPARATOR ', ') ```

If I put "**tags**" in name of tags column the datatable works fine but the search is not works because tags isn't the column name, "tags" is a subquery.

I hope explained me well.

Thanks for all replies

**Comment by yajra** [comment]
@SGarridoDev I think using [filterColumn](https://yajrabox.com/docs/laravel-datatables/master/filter-column) can be a workaround for this.

```php
dataTable()->filterColumn('tags', function($query, $keyword) {
   // perform subquery search.
})
```

**Comment by SGarridoDev** [comment]
Hi @yajra, thank you for you reply. 
Please, can you write the filter column with my subquery?

**Comment by yajra** [comment]
Code not tested but this is how I see to write it:

```php
dataTables()->filterColumn('tags', function($query, $keyword) {
  $query->whereRaw('GROUP_CONCAT(DISTINCT t.tag ORDER BY t.tag SEPARATOR ', ') like ?', [$keyword]);
})

**Comment by SGarridoDev** [comment]
Hi @yajra, thanks for you reply.

I've tested with your code and firstly I get an error because is not possible **GROUP_CONCAT** in where sentences.

The 'tags' column is a subquery in the select of  the primary query, for this, I need change your ``` $query->whereRaw``` by ```$query->havingRaw``` for searching by alias and not by column name, but if I change  **whereRaw** to **havingRaw** the **filterColumn** method remove my query with '**havingRaw**'. 

The filterColumn method only works with where sentences?

**Comment by SGarridoDev** [comment]
Hi @yajra,
At the end I've solved this issue. I explain you:

I've disabled the search in all columns with:
``` searchable: false```
I've picked columns with method **getColumns** from service provider.
And make my custom search using **having like** instead **where like** if I received the search input by Post.

Not is the best solution, but works fine for me.
Thanks for all.
Regards

**Comment by yajra** [comment]
I agree with your solution, I also use that approach for complex queries and it gives me much control on which field I should search on.
