### ISSUE TITLE
Searching / filtering with Query Builder, InnerJoin and aliases

### ISSUE THREAD

**Issue by gslongo** [yajra/laravel-datatables#1648]
Hi ! 

I'm facing to an issue regarding search filtering on a particular QueryBuilder with innerjoin

### Summary of problem or feature request

When searching/filtering. Datatables throws this error :

> DataTables warning: table id=mybrokers-table - Exception Message:
> 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'instruments.asset_class_name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `instruments` inner join `currencies` on `instruments`.`currencies_id` = `currencies`.`id` inner join `assets_classes` on `instruments`.`assets_class_id` = `assets_classes`.`id` inner join `markets` on `instruments`.`markets_id` = `markets`.`id` where (LOWER(`instruments`.`ticker`) LIKE %a% or LOWER(`instruments`.`name`) LIKE %a% or LOWER(`instruments`.`asset_class_name`) LIKE %a% or LOWER(`instruments`.`market`) LIKE %a%)) count_row_table)

Because of **instruments.asset_class_name** is not a column but an alias in the select statement

### Code snippet of problem

Here is the select statement with the datatable call :

```php
                    $instruments_paginator = DB::table("instruments")
                      ->join('currencies', 'instruments.currencies_id', 'currencies.id')
                      ->join('assets_classes', 'instruments.assets_class_id', 'assets_classes.id')
                      ->join('markets', 'instruments.markets_id', 'markets.id')
                      ->select('instruments.id',
                               'instruments.ticker',
                               'instruments.name',
                               'instruments.tick_size',
                               'instruments.tick_value',
                               'markets.name as market',
                               'currencies.ticker as currency',
                               'assets_classes.name as asset_class_name'
                      );

                      return datatables()->query($instruments_paginator)
                          ->addColumn('action', function ($table_data) {
                                //return '<a href="#edit-'.$table_data['name'].'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
                                $data = '<button type="button" id="" title="'.__('Edit').'" class="btn btn-xs btn-primary" data-uuid="'. $table_data->id .'" data-toggle="modal" data-target="#editModal"><i class="glyphicon glyphicon-edit"></i></button>';
                                return $data;

                            })
                          ->rawColumns(['action'])->toJson();
```

Here is the JavaScript columns def

```js
          columns: [
              { data: 'ticker', name: 'ticker' },
              { data: 'name', name: 'name' },
              { data: 'currency', name: 'currency', searchable: false },
              { data: 'asset_class_name', name: 'asset_class_name' },
              { data: 'market', name: 'market' },
              { data: 'tick_size', name: 'tick_size', searchable: false },
              { data: 'tick_value', name: 'tick_value', searchable: false },
              { data: 'action', name: 'action', orderable: false, searchable: false },
          ]
```

I can't find how to solve this in documentation.. Any idea ?
Thanks !

### System details

- Operating System : Debian 9
- PHP Version : PHP 7.0.27-0+deb9u1
- Laravel Version : v5.5.36
- Laravel-Datatables Version:  v8.4.1

Thanks !

**Comment by Skintillion** [comment]
Have you tried to DD your query and see what its actually doing?

**Comment by gslongo** [comment]
Hi!

Non, but we see in the error message what is done 

What information are you looking for?

Thanks !

**Comment by yajra** [comment]
When using join, you need to specify the fully qualified column name. See https://datatables.yajrabox.com/fluent/joins for ref.

**Comment by gslongo** [comment]
Yes, had to adjust a bit but it works now. Thanks !

**Comment by nyarachm** [comment]
@yajra Alternatively, in scenarios where a datediff() as elapsed_days entry exists in the query select, the solution above will fail and produce the same error. In this case:

Unknown column 'instruments.elapsed_days ' in 'where clause'

...which cannot be assigned a name matching the query 

Should these functions be reserved for the addColumn function?
