### ISSUE TITLE
help needed (newbie)

### ISSUE THREAD

**Issue by robertnicjoo** [yajra/laravel-datatables#1649]
I just installed this package and I have my function below,

```php
public function index()
    {
        $products = Product::orderby('id', 'desc')->paginate(10);
        $statuses = Status::all();
        return view('admin.products.index', compact('products', 'statuses'));
    }
```

> **I would like to know how can I use this package in my function?**

Thank you.

**Comment by Skintillion** [comment]
Read the documentation it shows how to do everything.

**Comment by robertnicjoo** [comment]
I removed this package already and used datatables `css` `js` files itself.

and changed my code to 

```php
        $products = Product::orderby('id', 'desc')->get();
```

works perfectly.
