### ISSUE TITLE
have question in performace 

### ISSUE THREAD

**Issue by webineh** [yajra/laravel-datatables#1651]
i have 100K record in users table how i can set limit for increase speed fetch data

``return  Datatables::of(DB::select('select * from users'))->make(true);``

- Operating System
- PHP Version 7
- Laravel Version 5.5
- Laravel-Datatables Version

**Comment by Skintillion** [comment]
Why are you selecting using raw?

**Comment by Skintillion** [comment]
https://laravel.com/docs/5.6/pagination

**Comment by vahidalvandi** [comment]
ok how i can post limit start , end in query ? from yaja ajax ??

``return Datatables::of(DB::select('select * from users',['from'=>0 , 'to'=>15]))->make(true);``

i need from , to in query ??

**Comment by yajra** [comment]
@vahidalvandi use something like:

```php
return Datatables::of(DB::table('users'))->make(true);
```

**Comment by vahidalvandi** [comment]
do i automatically fetch query  with paginate ??

**Comment by yajra** [comment]
@vahidalvandi yes, pagination is automatically applied.

**Comment by vahidalvandi** [comment]
do this create query builder ?

`invoice::where('invoice_type','sale_in')->select('id','user_id','invoice_amount')->orderBy('id', 'desc')->get()`

because if i remove  **get()**  search and order in table not Work

**Comment by yajra** [comment]
You need to remove `->orderBy('id', 'desc')->get()` for order to work and create a builder. Inspect the ajax request to debug further if it fails.

**Comment by vahidalvandi** [comment]
i need order by desc !!

**Comment by yajra** [comment]
Then sorting will not work since it's fixed on id desc.

**Comment by vahidalvandi** [comment]
thank you
