### ISSUE TITLE
Repository not downloadable by composer with Laravel 5.6

### ISSUE THREAD

**Issue by DenimaMab** [yajra/laravel-datatables#1656]
The I tried to install this repo with laravel 5.6 and it doesn't work ...

**Comment by Skintillion** [comment]
You know an error message or something would help?

**Comment by DenimaMab** [comment]
@Skintillion It's says that I have to uninstall Laravel 5.6. 

Found solution in another [ticket](https://github.com/yajra/laravel-datatables/issues/1568) but you've to check it again because Laravel 5.6 is stable now. 

Thanks.
