### ISSUE TITLE
Search queries on non existing database columns

### ISSUE THREAD

**Issue by NModern** [yajra/laravel-datatables#1657]
### Summary of problem or feature request

If somebody modifies column name in query to non existing column name, mysql returns "Unknown column" error. Adding whitelist not helps, because it whitelists only order clauses. 

### Code snippet of problem
Example request
draw=1&columns[0][data]=id&columns[0][name]=NON_EXISTING_COLUMN_NAME&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=3&columns[0][search][regex]=false&columns[1][data]=title&columns[1][name]=title&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=3&columns[1][search][regex]=false&columns[2][data]=cat_name&columns[2][name]=categories.cat_name&columns[2][searchable]=true&columns[2][orderable]=true&columns[2][search][value]=3&columns[2][search][regex]=false&columns[3][data]=lang&columns[3][name]=lang&columns[3][searchable]=true&columns[3][orderable]=true&columns[3][search][value]=3&columns[3][search][regex]=false&columns[4][data]=path&columns[4][name]=path&columns[4][searchable]=true&columns[4][orderable]=true&columns[4][search][value]=3&columns[4][search][regex]=false&columns[5][data]=created_at&columns[5][name]=created_at&columns[5][searchable]=true&columns[5][orderable]=true&columns[5][search][value]=3&columns[5][search][regex]=false

### System details

- Linux, Windows
- PHP 7.2, 7.1
- Laravel 5.5
- Laravel-Datatables Version 8.4.1

**Comment by yajra** [comment]
Yes, this is the expected behavior since we have to make sure that all column are existing in the database. However, I have to review this your note on whitelist.

>  Adding whitelist not helps, because it whitelists only order clauses.

AFAIK, it should handle both sorting and searching. Thanks!

**Comment by NModern** [comment]
Thank you for your reply. Yes I figured out that this is expected behavior. But I think this error messages should be shown only if debug of Laravel is turned on.  Because this is information leakage, and by bruteforcing column names somebody can get our database structure.

**Comment by NModern** [comment]
Or get information from columns that I don't want information to be gotten.

**Comment by yajra** [comment]
OIC, there is another config that handles this exception. You can set something on env like:

```php
DATATABLES_ERROR="Unable to process request."
```

See https://yajrabox.com/docs/laravel-datatables/master/error-handler for ref.
