### ISSUE TITLE
Documentation on how to use with jenssegers/laravel-mongodb

### ISSUE THREAD

**Issue by anushanw** [yajra/laravel-datatables#1662]
I have tried to scavenge the information distributed on a number of posts to get this to work with jenssegers/laravel-mongodb, but haven't been successful. Can you please provide a step-by-step guide to use jenssegers/laravel-mongodb with yajra/laravel-datatables please.

**Comment by yajra** [comment]
Sorry, but I haven't personally use mongodb yet. There are issues similar, try browsing it. Thanks!

**Comment by lalithhakari** [comment]
@anushanw did you find a solution for this?

**Comment by anushanw** [comment]
@lalithhakari I wasn’t 100% successful on this. I was able to get them to work together but the problem I had was that all regards were loading from DB and pagination wasn’t working properly. I tried to work around a bit and then gave up. 

I ended up  building a plug-in / connector to use datatables.net, mongodb and laravel pagination. I can share the repo link if you need

**Comment by lalithhakari** [comment]
@anushanw Please share link.

**Comment by anushanw** [comment]
@lalithhakari This is the package: https://packagist.org/packages/flatorb/moldssp

Note that this was mainly done to achieve what I wanted for my project. Might need some tweaks based on your project. Let me know on there if you need any assistance or changes with it.
