### ISSUE TITLE
Can I use 'full_name' in column definition instead of 'last_name'?

### ISSUE THREAD

**Issue by ivansammartino** [yajra/laravel-datatables#1664]
### Summary of problem or feature request

Can I have the fields `last_name` and `first_name` both in one column, order by `last_name` but have only `full_name` in `data` and `name` column parameters?

### Code snippet of problem
Ok, this is maybe a dumb question (or a VERY dumb one...): I have both `last_name` and `first_name` in one column (I sort by `last_name`)
```
...
->editColumn('last_name', function($record) {
    return "{$record->last_name} {$record->first_name}";
})
...
```
```
protected function getColumns()
{
    $columns = [
       ...
       [
            'data' => 'last_name',
            'name' => 'last_name',
            'title' => 'Full Name'
        ],
        ...
    ]
}
```
So far so good, but since I'm not displaying only a `last_name` but a `full_name`, is there a way I can use `full_name` in my column definition? Like this sort of "transformation":
```
...
->editColumn('full_name', function($record) {
    return "{$record->last_name} {$record->first_name}";
})
...
```
```
protected function getColumns()
{
    $columns = [
       ...
       [
            'data' => 'full_name',
            'name' => 'full_name',
            'title' => 'Full Name'
        ],
        ...
    ]
}
```
Thank you
### System details
- Operating System: Windows 10 / Laragon
- PHP Version: 7.1
- Laravel Version: 5.5
- Laravel-Datatables Version: "yajra/laravel-datatables": "1.0"

**Comment by yajra** [comment]
Yes you can, however, you need to set the name value to `last_name`. The name attribute is the one being used for sorting and searching.

```php
protected function getColumns()
{
    $columns = [
       ...
       [
            'data' => 'full_name',
            'name' => 'last_name',
            'title' => 'Full Name'
        ],
        ...
    ]
}
```

**Comment by zohaibhassan156** [comment]
What if I have to search and sort from both first_name and last_name, how I can set a compound name of Datatable column using eloquent and query builder and Transformer on the other hand.

I have to use it on an app with big data that's why I can't leave using eloquent (query builder) and Transformers.

**Comment by yajra** [comment]
@zohaibhassan156 You can add a hidden column and it will be included on search.

```php
$columns = [
       ...
       [
            'data' => 'full_name',
            'name' => 'last_name',
            'title' => 'Full Name'
        ],
       [
            'data' => 'first_name',
            'name' => 'first_name',
            'visible' => 'false'
        ],
        ...
    ]
````
