### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Class 'Yajra\DaTatables\Services\DataTable' not found"  Stacktrace: #0 Symfony\Component\Debug\Exception\FatalErrorException in C:\Users\achraf\Desktop\laravel-5-boilerplate\app\Http\Controllers\Backend\Employees\DataTables\EmployeeDataTable.php:8

### ISSUE THREAD

**Issue by aajiboo** [yajra/laravel-datatables#1665]
### Code snippet of problem
"Class 'Yajra\DaTatables\Services\DataTable' not found"

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
Please make sure that you are using the latest version of the package. Older version uses `Yajra\Datatables\Services\DataTable`. Also make sure you have the buttons plugin installed. See https://yajrabox.com/docs/laravel-datatables/master/buttons-installation for ref.
