### ISSUE TITLE
Call to a member function getQuery() on array

### ISSUE THREAD

**Issue by shifoodew** [yajra/laravel-datatables#1666]
### Summary of problem or feature request

I want to pass a variable from ajax to controller then return the query results back to Ajax. And I encountered this error Call to a member function getQuery() on array. and I don't know how to solve or fix this.  Hope you can help me fix this problem.

### Code snippet of problem

This is my ajax

    //GENERAL
    var $i=0;
    var level_id = '{{ @$level->id }}';
    var level = '{{ @$_level }}';

    var viewStudent
    function view_students($this){
        viewStudent
        if ($('#viewStudent-div').is(':hidden')) {
            $(".sidebar .menus").removeClass("active");
            $($this).addClass("active");

            $('#viewStudent-div').siblings().hide('slow/400/fast', function() {
                $('#viewStudent-div').show('slow/400/fast');
            });
        }
    }

    $(function(){
        viewStudent = $('#viewStudent-table').DataTable({
            order: [[ 0, "asc" ]],
            Language: {
                sLoadingRecords:"<img src='{{asset('assets/images/load.gif')}}' style='max-height:30px;'/> Fetching data...",
                sEmptyTable: "No data available"
            },
            ajax:{
                url:'{{ route("json_product_user") }}',
                data: function (d) {
                    d.level_id = level_id;
                    d.level = level;
                }
            },
            columnDefs: [
                {
                    targets: 0,
                    searchable:false,
                    orderable:false,
                },
            ],
            columns:[
                {
                    data: "full_name",
                    render: function(data, type, row){
                        return data;
                    }
                },
                {
                    data: "product_name",
                    render: function(data, type, row){
                        var html = '';
                        html += '<p style="">'+data+'</p>';
                        return html;
                    }
                },
                {
                    data: "level",
                    render: function(data, type, row){
                        return data;
                    }
                },
                {
                    data: "date_purchase",
                    render: function(data, type, row){
                    var html = '';
                    html += '<p style="text-align: center">'+moment(data).format('MMM-DD-YYYY')+'</p>';
                        return html;
                    }
                }
            ]
        });
    });

controller

    public function viewStudents(Request $request)
    {
        $org_id= \App\School::find($request->level_id)->organization_id;

        if( $request->has('level_id') ){
            if($request->level == 'school') {
                $query = DB::table('product_user')
                    ->leftJoin('products', 'product_user.product_id', '=', 'products.id')
                    ->leftJoin('school_products', 'product_user.product_id', '=', 'school_products.product_id')
                    ->leftJoin('users', 'product_user.user_id', '=', 'users.id')
                    ->whereRaw("school_products.school_id = " . $request->level_id . " OR products.organization_id = ".$org_id)
                    ->select('products.name as product_name', DB::raw('CONCAT(users.last_name, ", ", users.first_name ) AS  full_name'), 'product_user.created_at', 'products.level as level')
                    ->get();
            }
            else{
                $query= DB::table('product_user')
                    ->leftJoin('products', 'product_user.product_id', '=', 'products.id')
                    ->leftJoin('school_products', 'product_user.product_id', '=', 'school_products.product_id')
                    ->leftJoin('users', 'product_user.user_id', '=', 'users.id')
                    ->whereRaw("products.level = 'organization' AND products.organization_id = ".$request->level_id)
                    ->select('products.name as product_name', DB::raw('CONCAT(users.last_name, ", ", users.first_name ) AS  full_name'), 'product_user.created_at', 'products.level as level')
                    ->get();

            }
        }
        return  Datatables::of($query)->make(true);
    }

### System details

- Operating System
- PHP Version 7
- Laravel Version 5.2
- Laravel-Datatables Version ^6.21

**Comment by yajra** [comment]
Try using query instead of collection by removing `->get()` on your code.

```php
$query= DB::table('product_user')
                ->leftJoin('products', 'product_user.product_id', '=', 'products.id')
                ->leftJoin('school_products', 'product_user.product_id', '=', 'school_products.product_id')
                ->leftJoin('users', 'product_user.user_id', '=', 'users.id')
                ->whereRaw("products.level = 'organization' AND products.organization_id = ".$request->level_id)
                ->select('products.name as product_name', DB::raw('CONCAT(users.last_name, ", ", users.first_name ) AS  full_name'), 'product_user.created_at', 'products.level as level')
```

**Comment by phpguru** [comment]
If you used the generator (`php artisan datatables:make <name>`) to create your instance of `DataTables` class, by default, the following is written to your `DataTables` class' `ajax( )` method:

        return $this->datatables
              ->eloquent($this->query())
              ->addColumn('action', 'path.to.action.view')
              ->make(true);

If, in your `query( )` method you're not using an Eloquent model to produce the object DataTables needs, but instead using Query Builder, change the `ajax( )` method to 

        return $this->datatables
            ->queryBuilder($this->query())
            ->make(true);

This is what I found out and it makes perfect sense now. `Eloquent::getQuery( )` method exists, but it's not the same for a QueryBuilder object. 

        "laravel/framework": ">=5.5",
        "yajra/laravel-datatables-oracle": "^6.0",
