### ISSUE TITLE
sort by a column in all the pages following the order

### ISSUE THREAD

**Issue by nbrusquetti** [yajra/laravel-datatables#1667]
How to sort my results by the date column in all the pages?
I can only sort by page and when I change pages I lose the order.

**Comment by yajra** [comment]
You can use the `stateSave = true` option of dataTables to retain the last order state.

**Comment by nbrusquetti** [comment]
lo intente pero no funciona
`$('#consultas').DataTable(
{  
  processing: true,
  serverside:true,
  stateSave: true,
  ajax: '{{route('consulta_medica.datatable')}}',
  columns: [
  { data: 'paciente.documento'},  
  { data: 'paciente.nombre'},
  { data: 'paciente.apellido'},
  { data: 'created_at'}, 
  { data: 'opciones', orderable:false ,searchable:false}

  ],

  "language": {
    "url":"{{asset('template/js/spanish.json')}}"
    }
});`

**Comment by nbrusquetti** [comment]
My controller

public function datatable(Request $request)
	{

		if(!$request->ajax())
		{
			abort('404');
		}
		else{

			$consulta = ConsultaMedica::where('medico_id',Auth::user()->id_persona)->with('paciente')            
			->get();
			return Datatables::of($consulta)
			->addColumn('opciones','consultas_medicas.datatable.botones')
			 ->editColumn('created_at', function ($consulta) {
                return $consulta->created_at->format('d/m/Y');
            })
			->rawColumns(['opciones'])   
            
			->make(true);
		}
	}
