### ISSUE TITLE
laravel 5.5 datatables 6.0 - dataTables 8.0 issues

### ISSUE THREAD

**Issue by mck776775** [yajra/laravel-datatables#1671]
before Im using datatables 6.0 just last day I upgrade to datatables 8.0, now the system can show the data on datatable 
 <table id="tblLists" class="table table-bordered table-hover table-condensed DataTable" >
                        <thead style="font-size:12px; font-weight:bolder ">
                        <tr >
                            <th>EQUIPMENTS</th>
                            <th>BRAND</th>
                            <th>SERIAL NUMBER</th>
                            <th>DATE ACQUIRED</th>
                            <th>ACTION</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>

.. but if i use/access the route thru url ex http://myweb.site/equipment.data  there is a result the data is showing as query
{"draw":0,"recordsTotal":4557,"recordsFiltered":4557,"data":[{"............

please give me some example for datatables 8.0

- Operating System : win 10
- PHP Version : 7.
- Laravel Version : 5.5
- Laravel-Datatables Version : 8.0

**Comment by yajra** [comment]
Please see upgrade guide https://yajrabox.com/docs/laravel-datatables/master/upgrade for ref. Thanks!

**Comment by skys215** [comment]
yajrabox.com is not available
