### ISSUE TITLE
Vue components (delete and disconnect) not rendering with datatable

### ISSUE THREAD

**Issue by avanisolanki** [yajra/laravel-datatables#1672]
Hello, 
I am using (yajra/laravel-datatables-oracle": "^8.4) for listing data and There is problem of vue component rendering. 

![selection_013](https://user-images.githubusercontent.com/37375055/37814657-1ba4b8ce-2e91-11e8-97ff-019588c94176.png)

My controller code is:
public function getUsers() : JsonResponse
    {   
        $companyobj = app('App\Models\Company\Company');
        
        return \DataTables::of($companyobj->getCompanyUsers())->addColumn('action',function($user) {
                return view('client.company.user.listaction', compact('user'))->render();
            }
        )->make(true);
    }
listaction.blade.php code is :

<a href="{!! route('company.manage.users.edit', [$user->getKey()]) !!}"><i class="fa fa-pencil"></i></a>
<delete
    url="{!! route('company.manage.users.delete', [$user->getKey()]) !!}"
    remove="#user_{{ $user->getKey() }}">
</delete>
<disconnect url="{!! route('acp.user.disconnect', [$user->getKey()]) !!}"></disconnect>

datatable js code is as : 
$(document).ready(function() {
        $(function() {
            var dataTable = $('#members-table').dataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{!! route('company.manage.users.getusers') !!}",
                "columns": [
                    {data: 'id', name: 'id'},
                    {data: 'deptName', name: 'deptName'},
                    {data: 'teamName', name: 'teamName'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]   
            });
        });
    });

Can anyone please help me?

**Comment by deanlaw** [comment]
I do believe that you need to define your action column as a raw column.

https://yajrabox.com/docs/laravel-datatables/master/raw-columns

**Comment by avanisolanki** [comment]
How can initialize vue object in initComplete of datatable?
