### ISSUE TITLE
Search and OrderBy with AppendedAttribute

### ISSUE THREAD

**Issue by Drakota** [yajra/laravel-datatables#1678]
### Summary of problem or feature request

Hi, I'd like to know what would be the best way to accomplish what I'm trying to do. I have a table called tickets with a client_id, the table clients has a name column. I want to display the client_name inside my datatable. 

```php
protected $appends = ['client_name'];

public function getClientNameAttribute()
{
    return $this->client->name;  
}
```

This is what I did to display the client_name on the table and it works fine I have a column with the client_name attribute, but now I want to be able to search and orderBy with this column. How can I do this?

### System details

- Operating System: Windows 10
- PHP Version: 7.1
- Laravel Version: 5.5
- Laravel-Datatables Version: 8.4.1

**Comment by yajra** [comment]
Since it seems like client name is on a relationship, you can try using eager loading. See https://datatables.yajrabox.com/relation/belongs-to for ref.
