### ISSUE TITLE
Data loads fine but upon typing in search box, nothing happens. Sorting also broken.

### ISSUE THREAD

**Issue by brendenclerget** [yajra/laravel-datatables#1680]
### Summary of problem or feature request
Using Laravel 5.6, newest 8.0 Yajra release and HTML Builder. Local machine on Valet.

The data seems to be loading fine from the server side call to my controller. The table shows up with the records, styling gets applied, and table is generated.

 However, when I type a character into the search box for the datatable, nothing occurs. It doesn't make a call anywhere to search, and the table does not filter. Also, clicking a column heading doesn't do anything.

There are no JS errors in the console, and I see no search ajax call in the network tab upon search, only the original call to get the table (even with preserve log clicked)

### Code snippet of problem
Inside DataTable controller

```
 public function getCompanies()
    {
        $company = Company::query();
        return \DataTables::eloquent($company)
            ->toJson();
    }
```

Route

`Route::get('datatable/getdata/company', 'DataTableController@getCompanies')->name('dt.companies.view');`

I'm using HTML builder to output the javascript into the page, and that seems to be working fine because the table loads.

JavaScript that HTML Builder is outputting

```
(function(window, $) {
    window.LaravelDataTables = window.LaravelDataTables || {};
    window.LaravelDataTables["dataTableBuilder"] = $("#dataTableBuilder").DataTable({
        "serverSide": true,
        "processing": true,
        "ajax": {
            "url": "http:\/\/ls3.test\/datatable\/getdata\/company",
            "class": "table-responsive"
        },
        "columns": [{
            "name": "id",
            "data": "id",
            "title": "CID",
            "orderable": true,
            "searchable": true
        }, {
            "name": "name",
            "data": "name",
            "title": "Name",
            "orderable": true,
            "searchable": true
        }, {
            "name": "permissions",
            "data": "permissions",
            "title": "Permissions",
            "orderable": true,
            "searchable": true
        }, {
            "name": "created_at",
            "data": "created_at",
            "title": "Created",
            "orderable": true,
            "searchable": true
        }]
    });
})(window, jQuery);
```

Anybody have any clue why it seems all functionality is broken, but I see no errors?

**Comment by brendenclerget** [comment]
I expect there was an issue with one of the CDNs for jQuery or DataTables because now it appears to work and the code hasn't changed.

**Comment by jajack36** [comment]
I have the same sort problem, and you can add filterColumn to solve the search problem.

**Comment by yajra** [comment]
Looks like this is already resolved. Thanks!
