### ISSUE TITLE
Additional data in response using "with" is not updating on column search. 

### ISSUE THREAD

**Issue by tarunranka** [yajra/laravel-datatables#1681]
Additional data in response using "with" is not updating on column search.

**Comment by yajra** [comment]
Can you please provide some snippet to reproduce the issue? Thanks!

**Comment by tarunranka** [comment]
I have column filter called "status" which is a drop down with new, processed, completed option. On the page load I am calculating the total cost using "with".
If i change the status dropdown to select any one option, the total cost is not updating.
