### ISSUE TITLE
Using select inputs for filtering data does not include all expected values

### ISSUE THREAD

**Issue by ivansammartino** [yajra/laravel-datatables#1682]
### Summary of problem or feature request
When using [select inputs](https://datatables.net/examples/api/multi_filter_select.html) for filtering data, the select input shows only the unique items that are in the first screen, ignoring other values that can be in next pages

### Code snippet of problem
Let's suppose I have 50 records, with a field "status" that can be "on" or "off".
The first 48 records have status "on", the last 2 have status "off".
I have 10 records per page.
The select box shows only the "on" status due to the `LIMIT 10` feature of SQL query, ignoring that on the last page (`LIMIT 10 OFFSET 40`) there would be an "off" value to include in the select box.

Is there a workaround for this? (i.e. retrieving all data at once via SQL, thus removing LIMIT, and let javascript paginate)
Thank you :-)

### System details
- Operating System: Windows 10
- PHP Version: 7.2.2
- Laravel Version: 5.5
- Laravel-Datatables Version: "yajra/laravel-datatables": "1.0"

**Comment by yajra** [comment]
The demo only works on client-side implementation. Similar to https://github.com/yajra/laravel-datatables/issues/1690, please see my propose workaround there. Thanks!
