### ISSUE TITLE
Server Side Export 200000 records

### ISSUE THREAD

**Issue by jay-shah-rushiinfotech** [yajra/laravel-datatables#1684]
### Summary of problem or feature request

When 200000 records how to export data. When I export data **"Allowed memory size of 134217728 bytes exhausted "** this exception thrown.

**What other options are to export large amount of data in yajra/datatable.**

Please provide a different way to export large amount of data.

**We have limited amount of ram on server.**

### Code snippet of problem

```
public function showData(ServiceDataTable $dataTable)
    {
        return $dataTable
            ->render('dataTable.renderDataTable');
    }
```
### System details

- Operating System : Ubuntu 16.04
- PHP Version: 7.0.0
- Laravel Version: 5.5
- Laravel-Datatables Version: 8.0
- Laravel-Datatables Buttons Version: 3.1

**Comment by yajra** [comment]
You need to implement your own excel file builder to handle this bulk request. On your ServiceDataTable class, you can override `protected function buildExcelFile()` method and maybe do some chunk, etc. See laravel-excel docs for more info.

```php
    /**
     * Build excel file and prepare for export.
     *
     * @return \Maatwebsite\Excel\Writers\LaravelExcelWriter
     */
    protected function buildExcelFile()
    {
        /** @var \Maatwebsite\Excel\Excel $excel */
        $excel = app('excel');

        return $excel->create($this->getFilename(), function (LaravelExcelWriter $excel) {
            $excel->sheet('exported-data', function (LaravelExcelWorksheet $sheet) {
                $sheet->fromArray($this->getDataForExport());
            });
        });
    }
```

**Comment by karmendra** [comment]
If we are able to put this onto queue, we should be also able to save it to a folder on server and then provide the link to user to download it.

**Comment by jay-shah-rushiinfotech** [comment]
Thanking you for response.

I am using it in JQuery Datatable or yajra datatable and want to export from server side.

I think it's not feasible to save into folder on server, there are many issues that will generate problem.

I need streaming of data.

Amount of data is of size 20MB in response or larger.

**Comment by jay-shah-rushiinfotech** [comment]
I have issue with serverside proccessing which consumes large amount of ram and default script memory allocation size is 60MB.
Look at memory_limit in php.ini
Execution time limit `max_execution_time` is 60.
After increasing value you were able to make request using serverside export.

**Comment by karmendra** [comment]
I modified the excel function to do store the file instead of download, it is storing the file in storage/exports/ folder.

    public function excel()
    {
        $this->buildExcelFile()->store('xls');
    }

currently I am not having large amount of data in my development env, can you make above change in you setup and see if it is able to create the excel in that folder without hitting the memory cap?

Another thing to note is I am using Laravel 5.1 thus maatwebsite/excel version 2.1

**Comment by OzanKurt** [comment]
So any updates about this?

**Comment by JasonZsl6** [comment]
So any updates about this?

**Comment by TheGeekyM** [comment]
If anyone uses Laravel Excel 3.0+ the upper solution won't work. so you should override `buildExcelFile()` by using ["Queued Export"](https://docs.laravel-excel.com/3.1/exports/queued.html).

Or I did something else by using chunking also but by creating my trait and use CSV to do my work and this an [example](https://gist.github.com/TheGeekyM/5df229a24026c6ca643dc6b7e3b4ea3b)

**Comment by ahmedsafadii** [comment]
any updates ?

**Comment by singhofmarco** [comment]
Starting with Laravel 6 you can use LazyCollections to load only one item at a time in memory. This fixes the issue of running out of memory.

**Only need to extend DataTable class and write an adapted DataTablesExportHandler.**

Override the buildExcelFile() method in your class that extends DataTable
` protected function buildExcelFile()
    {
        $source = app()->call([$this, 'query']);
        $source = $this->applyScopes($source);

        $dataTable = app()->call([$this, 'dataTable'], compact('source'));
        $dataTable->skipPaging();
        $query = $dataTable->getFilteredQuery();

        $dataForExport = $query->cursor();

        return new $this->exportClass($dataForExport);
    }`

Create LazyDataTablesExportHandler class that accepts LazyCollection.
`namespace App\DataTables;

use Illuminate\Support\LazyCollection;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class LazyDataTablesExportHandler implements FromCollection, WithHeadings
{
    use Exportable;

    /**
     * @var LazyCollection
     */
    protected $collection;

    /**
     * LazyDataTablesExportHandler constructor.
     *
     * @param LazyCollection $collection
     */
    public function __construct(LazyCollection $collection)
    {
        $this->collection = $collection;
    }

    /**
     * @return LazyCollection
     */
    public function collection()
    {
        return $this->collection;
    }

    /**
     * @return array
     */
    public function headings(): array
    {
        $first = $this->collection->first();
        if ($first) {
            return array_keys($first->toArray());
        }

        return [];
    }`

Set newly created export class
` protected $exportClass = LazyDataTablesExportHandler::class;` 

Enjoy!

**Comment by ahmedsafadii** [comment]
@singhofmarco Can you make example?

**Comment by yajra** [comment]
@singhofmarco I agree, have started a [v10 project](https://github.com/yajra/laravel-datatables/projects/2) last year that will utilize LazyCollections but can't continue it atm.

**Comment by ameenross** [comment]
I went a different route. I've overridden the csv function, calling DataTables with one page of data each time, effectively chunking. Using `fputcsv` on the result rows until the file is complete, then just return the file content in a Laravel Response.

**Comment by karmendra** [comment]
@ameenross if possible can you share your code please.

**Comment by ameenross** [comment]
@karmendra I'd rather not, as it's for an older version of Yajra Datatables. But basically what I'm doing is I'm merging some page&length values in the request, call the code that normally returns a page of data for AJAX (`$this->ajax()->getData(true)['data']` in my case). I have a base class for datatables which extends the Yajra Datatable class, with a function `getCsv`. This goes in a loop until there are no more pages left.

**Comment by karmendra** [comment]
@ameenross Thanks that is helpful. I will give this a try.

**Comment by lcabre** [comment]
Laravel Datatable:: v1.5.0
Here is my solution based on @TheGeekyM comment, i leave it in case it helps someone else.
I created a ChunkedDatatableExportHandler class that implements FromQuery and then override the buildExcelFile method in my ServiceDataTables to use it.

``` PHP
<?php

namespace App\DataTables;

use Yajra\DataTables\Services\DataTable;

class ServiceDataTable extends DataTable
{
  protected $exportClass = ChunkedDatatableExportHandler::class;
  
  protected function buildExcelFile()
  {
      $query = app()->call([$this, 'query']);
      $query = $this->applyScopes($query);

      $dataTable = app()->call([$this, 'dataTable'], compact('query'));
      $dataTable->skipPaging();
      $data_query = $dataTable->getFilteredQuery();

      return new $this->exportClass($data_query);
  }
}
```
``` PHP
<?php
namespace App\DataTables;

use Illuminate\Database\Query\Builder;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithHeadings;

class ChunkedDatatableExportHandler implements FromQuery, WithHeadings
{
    use Exportable;

    /**
     * @var Builder 
     */
    protected $query;

    /**
     * ChunkDatatablesExportHandler constructor.
     * @param Builder $query
     */
    public function __construct(Builder $query)
    {
        $this->query = $query;
    }

    /**
     * @return array
     */
    public function headings(): array
    {
        $first = $this->query()->first();
        
        if ($first) {
            return array_keys((array)$first);
        }

        return [];
    }

    /**
     * @return Builder
     */
    public function query()
    {
        return $this->query;
    }
}
```

**Comment by yajra** [comment]
Made several improvements with export, hope it helps:

1. Exporting via fast-excel https://github.com/yajra/laravel-datatables-buttons/pull/124
2. Better export with Laravel-Excel https://github.com/yajra/laravel-datatables-buttons/pull/122
3. Used Lazy Collection for better memory / performance.

For bulk export, I suggest to use option 1 but compromised formatting. I only tested with 20k records and was a success unlike before where it fails with around 5-7k records at max.

Please check and feedbacks appreciated. Thanks!

**Comment by yajra** [comment]
Also planning to use query / cursor with Laravel-Excel like what @lcabre have provided but it might be a breaking change.
