### ISSUE TITLE
DataTables warning: table id=not_issued - Ajax error

### ISSUE THREAD

**Issue by wiselh** [yajra/laravel-datatables#1685]
> ### DataTables warning: table id=my-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Code works fine sometimes i don't know why, i keep refreshing the page and getting the error again until it works but when i try to type any key for searching it showing up this error over again.
In dev tool showing the request : 404 page not found

### System details

- Operating System Win 10
- PHP Version 7
- Laravel Version 5.4
- Laravel-Datatables Version ~8.

#### My JS
```
jQuery('#my-table').dataTable({
        columnDefs: [],
        pageLength: 5,
        lengthMenu: [[5, 8, 15, 20], [5, 8, 15, 20]],
        autoWidth: false,
        processing: true,
        serverSide: true,
        searching: true,
        ordering: true,
        ajax: "http://127.0.0.1:8000/statistics/datatableCommandes",
        columns: [
            {data: 'commande_num', name: 'commande_num'},
            {data: 'id_client', name: 'id_client'},
            {data: 'commande_quantity', name: 'commande_quantity'},
            {data: 'commande_montant', name: 'commande_montant'},
            {data: 'commande_date', name: 'commande_date'},
            {data: 'commande_date_retrait', name: 'commande_date_retrait'},
            {data: 'commande_paid', name: 'commande_paid'}
        ]
    }); 
```
#### my HTML
`<table id="my-table" class="table table-bordered table-striped table-vcenter ">
   <thead>
          <tr>
            <th class="text-center" style="width: 10%;">NO°</th>
            <th class="d-none d-sm-table-cell text-center" style="width:10%;">Client</th>
            <th class="d-none d-sm-table-cell text-center">Quantity</th>
            <th class="d-none d-sm-table-cell text-center">Montant Total</th>
            <th class="d-none d-sm-table-cell text-center">Date de Facture</th>
            <th class="d-none d-sm-table-cell text-center">Date de Retrait</th>
            <th class="d-none d-sm-table-cell text-center">Paiments</th>
          </tr>
    </thead>
</table>`

### laravel controller

```
public function tableCommandes(){
            return Datatables::of(Commande::all())->make();
}
```
### Route.php
`Route::get('/statistics/datatableCommandes', 'StatisticController@tableCommandes');`

**Comment by wiselh** [comment]
I Solved the error :)

**Comment by rcasanova27** [comment]
Hi Wiselh, sorry as you solved it?
