### ISSUE TITLE
How to use the applyScopes?

### ISSUE THREAD

**Issue by ivansammartino** [yajra/laravel-datatables#1687]
Hello, I needed to use a Global Scope for one of my queries and I found about `applyScopes()` in the docs. Indeed, there's no mention of `applyScopes()` in the `query()` method when I create a datatable with artisan: `php artisan datatables:make DummyDataTable`:

```
public function query(User $model)
{
    return $model->newQuery()->select('id', 'add-your-columns-here', 'created_at', 'updated_at');
}
```
and [applying a Global Scope in the Laravel way](https://laravel.com/docs/5.5/eloquent#global-scopes) still works fine in datatable.

So, what's the matter of `applyScopes()`? is it an old implementation? How do I use in the `query()` method created with artisan command?

Thanks

- Operating System: Windows 10
- PHP Version: 7.2
- Laravel Version: 5.5.*
- Laravel-Datatables Version: "yajra/laravel-datatables": "1.0"

**Comment by yajra** [comment]
Sorry, docs is not up to date. You can still use scopes via controller when using the service class like:

```php
public function index(UsersDT $dt) {
  return $dt->addScope(new DTQueryScope())->render('path.to.view');
}

**Comment by ivansammartino** [comment]
Thanks for the answerr! :-) is it the same as using Scopes straight on Models? Or has it some advantages?

**Comment by yajra** [comment]
It's almost the same as eloquent scope. However, I think the advantage here is the reusability of the scope and the dataTable class. For instance, as I recall on one of my project, I have a `OwnedScope` that applies a `table.user_id = current_user_id`. I can then apply this same scope on any dataTable class where I want to limit the results. I also used this on a multi-tenant app like `CompanyOwnedScope`.

**Comment by ivansammartino** [comment]
Perfect, thanks, it makes sense! 👍

**Comment by Fionajeremychik** [comment]
I want to show the users inside dataTable based on table.user_id = Auth()->id()
How can I use OwnedScope

public function query(User $model)
{
    return $model->newQuery()
}
