### ISSUE TITLE
Please Upgrade the maatwebsite/excel package to v3

### ISSUE THREAD

**Issue by alr2413** [yajra/laravel-datatables#1689]
Hi Yajra,
Thanks for this awesome package.
Please release a new stable sub-version of your package with the latest version of the Maatwebsite spreadsheet package.
Here is a link:
[https://github.com/Maatwebsite/Laravel-Excel](https://github.com/Maatwebsite/Laravel-Excel)

**Comment by drbyte** [comment]
Work in progress. 
It would be helpful if you test it and give feedback:
https://github.com/yajra/laravel-datatables-buttons/issues/61
