### ISSUE TITLE
CSRF Token Error When Using HTML Builder

### ISSUE THREAD

**Issue by r0bdiabl0** [yajra/laravel-datatables#169]
I am using the latest stable releases of Laravel 5.1 and laravel-datatables. I am following the HTML Builder example provided in the wiki exactly using dependecy injection option. However, when I render the page, I get this error:

`BindingResolutionException in Container.php line 823: Unresolvable dependency resolving [Parameter #2 [ <required> $csrfToken ]] in class Collective\Html\FormBuilder`

Is this a bug?

My code: 
```
namespace sass\Http\Controllers;

use Illuminate\Http\Request;
use sass\User;
use yajra\Datatables\Datatables;
use yajra\Datatables\Html\Builder;

class DatatableController {
	protected $htmlBuilder;
	protected $request;
	protected $user;

	public function __construct(Builder $htmlBuilder) {
		$this->htmlBuilder = $htmlBuilder;
	}

	public function getUsers(Request $request) {
		if ($request->ajax()) {
			return Datatables::of($this->user)
				->showColumns('id', 'username', 'email')
				->addColumn('actions', function ($array) {
					return '<a href="users/edit/' . $array->id . '" class="btn">Edit</a>';
				})
				->searchColumns('id', 'username', 'email')
				->orderColumns('id', 'username', 'email')
				->make();
		}

		$html = $this->htmlBuilder
			->addColumn(['data' => 'id', 'name' => 'id', 'title' => 'Id'])
			->addColumn(['data' => 'username', 'name' => 'username', 'title' => 'Username'])
			->addColumn(['data' => 'email', 'name' => 'email', 'title' => 'Email'])
			->addColumn(['data' => 'actions', 'name' => 'actions', 'title' => 'Actions']);

		return view('users.index', compact('html'));
	}

}

**Comment by rogierborst** [comment]
I have the same problem. Did you manage to solve it, @r0bdiabl0? And if so, how?

**Comment by yajra** [comment]
Not sure, but I think this was due to `illuminate/html`? The proper package to use is `laravelcollective/html`.

**Comment by rogierborst** [comment]
Right, I had to register its ServiceProvider and Facades in config/app to get it to work. Thanks for pointing me in the right direction, @yajra!
