### ISSUE TITLE
SoftDeletes seem to be ignored in paging?

### ISSUE THREAD

**Issue by IchFloque** [yajra/laravel-datatables#1692]
### Summary of problem or feature request

I have a model with soft deletes and I get the data with ::query()->withTrashed().
All data seems to be there when I view 100 rows, but when it is limited to 10 per page it is cut off at the end. Pages seems to only handle the not-deleted rows. Am I missing something here?

### Code snippet of problem

```php
$model = \App\Model::query()->withTrashed();
return datatables()->eloquent($model)>toJson();
```

### System details

- PHP Version: 7.1
- Laravel Version: 5.5
- Laravel-Datatables Version: 8.4

**Comment by yajra** [comment]
Thanks for reporting, will try replicate this on my side when I got the chance.
