### ISSUE TITLE
Done Exit with code 1 due to network error

### ISSUE THREAD

**Issue by ElHombreSinNombre** [yajra/laravel-datatables#1695]
In Laravel i use [Laravel datatable service](https://datatables.yajrabox.com/service) to create a table with some custom elements. In this datatable i have Excel and PDF export buttons. Excel button work and export correctly but when i push PDF button to export return

> The exit status code '1' says something went wrong: stderr: "Loading pages (1/6) [> ] 0% [======> ] 10% [===================> ] 32% [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [==============================> ] Page 1 of 2 [============================================================] Page 2 of 2 Done Exit with code 1 due to network error: HostNotFoundError " stdout: "" command: "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --lowquality --margin-bottom "10mm" --margin-left "0" --margin-right "0" --margin-top "10mm" --orientation "landscape" --no-outline --encoding "UTF-8" --footer-center "Página [page] de [toPage]" --footer-font-size "8" "C:\WINDOWS\TEMP\knp_snappy5ac5ce7f86ae68.54708623.html" "C:\WINDOWS\TEMP\knp_snappy5ac5ce7f899d54.74117266.pdf".

All css and js elements are in local. I create a simple template with 'hello world' and can export so i do´t know why i can´t export datatable data to pdf.  Snappy config binary has

>  'binary' => '"C:\wkhtmltopdf\bin\wkhtmltoimage.exe"',

- Windows 10 with XAMPP
- PHP 7.0
- Datatable 8.0
- Snappy 0.4.1

¿Any help?

**Comment by yajra** [comment]
This error usually occurs due to invalid WKHTMLTOPDF installation. Try running the generated script manually if it works: Also, I advise that you use the QT-patch version.

```
C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --lowquality --margin-bottom "10mm" --margin-left "0" --margin-right "0" --margin-top "10mm" --orientation "landscape" --no-outline --encoding "UTF-8" --footer-center "Página [page] de [toPage]" --footer-font-size "8" 
```
