### ISSUE TITLE
Order by column data instead of database data

### ISSUE THREAD

**Issue by nassiem3dc** [yajra/laravel-datatables#1696]
I have some columns that get their value from a function that returns a status and I am unable to store these values in the database because it is generated each time based on other states.

Is there a way to exclude a column from using the query and instead use the data already in the table to order them?

**Comment by yajra** [comment]
Yes, this is possible using collection instead of query. However, collection is not advisable specially if the table has large records. 

On the other hand, using both query and data is not possible.
