### ISSUE TITLE
open new tab for printing when print button clicked

### ISSUE THREAD

**Issue by saqueib** [yajra/laravel-datatables#1698]
How can I open a new tab for printing when print button clicked, something like `target="_blank"`, currently it opens in same tab which causes to loose back my apps navigation.

- Operating System: Mac OS 10.12.6
- PHP Version: 7.2
- Laravel Version: 5.6
- Laravel-Datatables Version: "yajra/laravel-datatables": "^1.0"

**Comment by yajra** [comment]
Maybe try to override the default print button script to open new window instead of change the current location? Here is snippet of print button.

```js
    DataTable.ext.buttons.print = {
        className: 'buttons-print',

        text: function (dt) {
            return  '<i class="fa fa-print"></i> ' + dt.i18n('buttons.print', 'Print');
        },

        action: function (e, dt, button, config) {
            var url = _buildUrl(dt, 'print');
            window.location = url;
        }
    };
```

**Comment by saqueib** [comment]
Done

**Comment by afiqhamzah-wisb** [comment]
Hi I'm sorry for re-opening this issue, I'd try to look everywhere... is there any way to open new tab when clicking the export button using the PHP only? 

I'd studied the codes on 
- vendor/yajra/laravel-datatables-html/src/Html/Button.php
- vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php

And I'd try to change the button tag to anchor tag with target=''_blank" using function tag of previous mentioned, Button.php. It change the tag and everything but when I click the button still redirect to the same page. I think that, there is some js that overrides the behaviour of the anchor tag thats why it didn't work

**Comment by yajra** [comment]
@afiqhamzah-wisb  Here's snippet on how to create a raw button via html builder. Adjust it to fit your needs:

```php
Button::raw()
  ->text('My Button')
  ->className('btn btn-primary')
  ->action("function() { alert('test'); }"),
```
