### ISSUE TITLE
I need to sort on custom sorting query

### ISSUE THREAD

**Issue by yatin13490** [yajra/laravel-datatables#1699]
I have one table which has the data column "Featured" default this field value is set to 0 and then can change at any number(also set same priority number to multiple records)
when I search on this column in data tables the 0 record as shows first but my requirement is I need to show 0 value recorded in last in any sorting order in SQL I can achive the result by this:

**order by case `featured_order` when 0 then 2 else 1 end, `featured_order`**

but how can I set this with data tables, how can I pass this query as name?

### System details

- Operating System: Ubuntu
- PHP Version: 7.0
- Laravel Version: 5.4
-  "yajra/laravel-datatables": "^1.0",
     "yajra/laravel-datatables-oracle": "~8.0"

**Comment by yajra** [comment]
See https://yajrabox.com/docs/laravel-datatables/master/order-column for ref. You can do your custom order sql with that API.
