### ISSUE TITLE
Search/Sort by child keys on Eloquent 

### ISSUE THREAD

**Issue by ajnatural** [yajra/laravel-datatables#170]
I was wondering what the best way to allow searching/sorting on child keys of Eloquent models would be. For example the name and email columns here: http://datatables.yajrabox.com/eloquent/has-many

**Comment by yajra** [comment]
@ajnatural, search/sort by child key/eager loaded models is not yet supported on eloquent. The best way is still to use join statements atm.

**Comment by yajra** [comment]
Or maybe try using master-details approach? http://datatables.yajrabox.com/eloquent/master.
