### ISSUE TITLE
How to pass extra parameter with other default parameter

### ISSUE THREAD

**Issue by jatinbphp** [yajra/laravel-datatables#1700]
### Summary of problem or feature request

Hello,

I want to pass one extra parameter with other default parameter which are passing it self on ajax request.
I want to pass variable which is not part of data/field which are displaying on tables.
Basically i want to add one filter which is not part of currently displaying columns.How i can pass it ?

**Comment by yajra** [comment]
On minified ajax, you can append an array of parameters that will be included by default on request. Maybe this is what you need? See docs https://yajrabox.com/docs/laravel-datatables/master/html-builder-minified-ajax for ref.

**Comment by Surrendra** [comment]
@jatinbphp  do youmean like this ?
    public function userSkpDataTable($pes) #datatale di menu skp peserta
    {
        $skp = skp::isAktif($pes,1);
        return Datatables::of($skp)
            ->addColumn('action', function($user)use($pes) {
                return '<a href="'.route('peserta.skp.edit',[$pes,$user->skp_kode]).'" class="btn btn-success btn-xs"><i class="fa fa-edit"></i> Edit</a>';                
            })->make(true);
    }

**Comment by Surrendra** [comment]
@jatinbphp  do you mean like this ?
    public function userSkpDataTable($pes) #datatale di menu skp peserta
    {
        $skp = skp::isAktif($pes,1);
        return Datatables::of($skp)
            ->addColumn('action', function($user)use($pes) {
                return '<a href="'.route('peserta.skp.edit',[$pes,$user->skp_kode]).'" class="btn btn-success btn-xs"><i class="fa fa-edit"></i> Link with 2 parameter</a>';                
            })->make(true);
    }

**Comment by Surrendra** [comment]
@jatinbphp do you mean like this ?
    public function userSkpDataTable($pes) 
    {
        $skp = skp::isAktif($pes,1);
        return Datatables::of($skp)
            ->addColumn('action', function($user)use($pes) {
                return '<a href="'.route('peserta.skp.edit',[$pes,$user->skp_kode]).'" class="btn btn-success btn-xs"><i class="fa fa-edit"></i> link with 2 paramter</a>';                
            })->make(true);
    }

**Comment by yajra** [comment]
Are you using the html builder or writing your own script?

Anyways, try this js:

```js
$('#..').DataTable({
    ajax: {
        url: '',
        data: function(data) { data.key = value; } 
    },
    ...
})

**Comment by laurence702** [comment]
Hello Yajra, im trying to pass extra parameter from controller to view when using Yajra, so I get something like total amount made from the time range filter. see screenshot below of my controller.
In my view I cant do this {{cashMade}}  

I get Errr: Use of undefined constant cashMade - assumed 'cashMade'

<img width="917" alt="yaj" src="https://user-images.githubusercontent.com/30216553/76171841-f8c37c80-618f-11ea-91ed-08ce834ea64c.PNG">

**Comment by yajra** [comment]
@laurence702 you can use [with](https://yajrabox.com/docs/laravel-datatables/master/response-with#key-value) api to append data on response.

```php
Route::get('user-data', function() {
    $model = App\User::query();

    return DataTables::eloquent($model)
                ->with('posts', 100)
                ->with('comments', 20)
                ->toJson();
});
```

**Comment by UmeshKrRana** [comment]
I have passed the extra parameter with the datatable like this-

```
->with([
   "cities" => app(\App\Http\Controllers\HelperController::class)->cityListing(),
  "leadCounters" =>  $this->leadCounters
])
->make(true);
```

But, how can I get these extra parameters in the response of Yajra Datatable?

**Comment by FerBiani** [comment]
@UmeshKrRana do as follows:

Save the initialization of the DataTable in a variable:

`var table = $('.vehicles-report-table').DataTable({...})`

Then access the data via the drawCallback function:

`drawCallback: function(settings) {
        console.log(table.ajax.json())
}`

**Comment by MilanUnjiya4149** [comment]
> Are you using the html builder or writing your own script?
> 
> Anyways, try this js:
> 
> ```js
> $('#..').DataTable({
>     ajax: {
>         url: '',
>         data: function(data) { data.key = value; } 
>     },
>     ...
> })
> ```

return $this->builder()
            ->setTableId('table')
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->ajax([
                'data' => 'function(d) { 
                    d.range = $("#range").val();
                    d.period_from = $("#period_from").val();
                    d.period_to = $("#period_to").val();
                }'
            ]));
