### ISSUE TITLE
How can I know my datatable version on command line and uninstall old version?

### ISSUE THREAD

**Issue by robinnpca** [yajra/laravel-datatables#1706]
Can I  know my datatable version on command line on windows artisan command?
and how do  I do to uninstall old version by the composer?

D:\appserv\www\comefourPS>composer require yajra/laravel-datatables-oracle
Using version ^8.4 for yajra/laravel-datatables-oracle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing yajra/laravel-datatables-oracle (v8.4.3): Loading from cache
yajra/laravel-datatables-oracle suggests installing yajra/laravel-datatables-buttons (Plugin for server-side exporting of dataTable.)
yajra/laravel-datatables-oracle suggests installing yajra/laravel-datatables-html (Plugin for server-side HTML builder of dataTable.)
yajra/laravel-datatables-oracle suggests installing yajra/laravel-datatables-fractal (Plugin for server-side response using Fractal.)
yajra/laravel-datatables-oracle suggests installing yajra/laravel-datatables-editor (Plugin to use Datatables Editor (requires a license).)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: appstract/laravel-blade-directives
Discovered Package: appstract/laravel-bootstrap-components
Discovered Package: yajra/laravel-datatables-oracle
Package manifest generated successfully.
D:\appserv\www\comefourPS>
![image](https://user-images.githubusercontent.com/34333522/38856146-378a2f08-4258-11e8-8b64-ffce5738923b.png)

**Comment by BlackCaptainTR** [comment]
Firstly I think this is not right place to ask this. This is not about this package, its about using command line and composer. You could do a quick google search [composer learn package version](https://www.google.com/search?q=composer+learn+package+version) or look at [Composer's docs](https://getcomposer.org/doc/03-cli.md#show).

Anyways you can use `show` command to learn details of a package. For example for this package you can use
```sh
$ composer show yajra/laravel-datatables-oracle
```
to get its details. You can filter it by using `grep` pipe as
```sh
$ composer show yajra/laravel-datatables-oracle | grep "versions"
```
which gives only the version not other details.
