### ISSUE TITLE
Problem Large Dataset with DataTables Serverside

### ISSUE THREAD

**Issue by alemodis** [yajra/laravel-datatables#1715]
### Summary of problem or feature request

I have a laravel app that displays a table with Datatables, the data are fetched from the database and then I parse them and I construct the json. I use serverSide Datatables, the dataset has 30.000 rows and it's really slow it takes about 13s to fully load.

Every time I do something with the table (order, nextpage etc) it takes 13s.

### Code snippet of problem

Datatables Script:
`<script>
			$('.datatable').DataTable( {
               "ordering": true,
                "searching": false,
				"processing": true,
                "serverSide": true,
				"ajax": {
					"url":"/serverSide/{!! $store->EUI!!}",
					"dataType":"json",
                    "type":"POST",
                    "data":{"_token":"<?= csrf_token() ?>",},
                },
				"columns":[
					{"data":"id"},
					{"data":"eui"},
                    {"data":"ts"},
                    {"data":"hum"},
                    {"data":"temp"},
                    @if ( $type == '10')
                    {"data":"hcho"},
                    @endif
                    {"data":"pm25"}
				]
			} );
</script>
`

Controller:
public function ajax(Request $request){
        
        $eui=$request->eui;
        
        $store = DB::table('stores')->where('EUI', $eui)->first();
  
        $datas = DB::table('messages_rx')->where('eui', $eui)->orderBy('ts', 'desc')->get();
        $id = $store->id;
        $category = DB::table('category_store')->where('store_id', $id )->first();
        $type = $category->category_id; 
        
        switch($type) {
            case 9:
                $data = parseGlobalSat($datas,$eui);  
                break;
            case 10:
                $data = parseArduino($datas);
                break;
            default:
        } 
        return Datatables::of($data)->make(true);;
   
    }

### System details

- Operating System : Windows 10
- PHP Version 7.0.4
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
I think you are using collection as you data source. In this regard, I suggest you use `query` by removing `get()` on your code.
