### ISSUE TITLE
laravel datatable Having clause not working on column alias

### ISSUE THREAD

**Issue by amit772000** [yajra/laravel-datatables#1716]
### Summary of problem or feature request

I am trying to build query for laravel data table but having clause not working on two columns as i tried below.

### Code snippet of problem
 $row = DB::table('composite_inventories as u')->select([
                'u.id',
                'u.purchase_item_name',
                'u.sales_item_name',
                DB::raw('GROUP_CONCAT(p.itemcode) as purchase_items'),
                DB::raw('GROUP_CONCAT(s.itemcode) as sales_items')
            ])->leftJoin('composite_has_inventories as us', 'u.id', '=', 'us.composite_inventory_id')
                ->leftJoin('inventories as s', function($join)
                     {
                        $join->on('US.inventory_id', '=', 's.id');
                        $join->on('us.type','=',DB::raw("'sale'"));
                     })
                ->leftJoin('inventories as p', function($join)
                     {
                        $join->on('US.inventory_id', '=', 'p.id');
                        $join->on('us.type','=',DB::raw("'purchase'"));
                     })
            ->groupBy('u.id', 'u.purchase_item_name','u.sales_item_name');

$datatable = app('datatables')->of($row);

if($keyword=$request->get('search')['value'])
{
$datatable->filterColumn('purchase_items',function($row,$keyword){

$row->having('purchase_items','LIKE','%$keyword%')

});

$datatable->filterColumn('sales_items',function($row,$keyword){

$row->having('sales_items','LIKE','%$keyword%')

});

}

return $datatable->make(true);
please have a look above query I am having two aliases purchase_items and sales_items. when i enter something in search filter of datatable it is not able to provide me matched records.it needs to check value in either purchase_items or sales_items. if i put having clause in main query then it works.

see the below image of output of query before applying filter 
![before output](https://user-images.githubusercontent.com/38563250/39056019-30842024-44d3-11e8-9086-89eb4363ff91.png)

if i search 'A123' in datatable search filter then output should as below but my filter column not working like that 

![after output](https://user-images.githubusercontent.com/38563250/39056059-469c84be-44d3-11e8-8f4b-dced3b669e8b.png)

### System details

- laravel 5.5
- Yajra Datatable laravel plugin

**Comment by yajra** [comment]
Filter column is added inside a nested where clause and afaik, having query is indeed not working on this type of query. I suggest you put the having clause with query before passing it to dataTables.

```php
if($keyword=$request->get('search')['value']) {
  $row->having('purchase_items','LIKE','%$keyword%')
}

$datatable = app('datatables')->of($row);
```

**Comment by amit772000** [comment]
thank you for your reply.

i have try to set solution like this and it is working good now.


$row = DB::table('inventories')->select('inventories.*','contacts.name',DB::raw('SUM(inventory_has_warehouses.starting_balance) as total'))
            ->leftJoin('contacts', 'inventories.supplier', '=', 'contacts.id')
            ->leftJoin('inventory_has_warehouses', 'inventories.id', '=', 'inventory_has_warehouses.inventory_id')
            ->where('inventories.subscriber_id',$id)
            ->groupBy('inventory_has_warehouses.inventory_id');




          if ($keyword = $request->get('search')['value']) {
            $row->having(DB::raw('SUM(inventory_has_warehouses.starting_balance)'), 'like', '%'.$keyword.'%');
            $row->orHaving('inventories.itemcode', 'like', '%'.$keyword.'%');
            $row->orHaving('inventories.purchasedescription', 'like', '%'.$keyword.'%');
            $row->orHaving('contacts.name', 'like', '%'.$keyword.'%');
          }
        
       

        if ($request->has('status')) {
            $row->where('inventories.status', $request->get('status'));
        }

        $datatable = DataTables::of($row);
