### ISSUE TITLE
[question] Dynamic Columns

### ISSUE THREAD

**Issue by vankaiser** [yajra/laravel-datatables#1717]
Hi sir Arjay, I'm trying to implement multiple eager relationships using your datatable library but I can't get the search and filters to work for the dynamic column values. 

Table structure
tbl_module
-id
-by_user

tbl_module_columns
-id
-tbl_columns_id
-tbl_module_id
-column_value

tbl_columns
-id
-column_name

Expected datatable output (this can stretch up to 30 or more dynamic columns):
Module ID, User ID, Column 1 column_value, Column 2 column_value, Column 3 column_value,..,...,....

btw, I am a fan of your work.

Thanks,
Riel

**Comment by yajra** [comment]
Hey Riel, your requirements is a bit complex and I haven't tried working on a dataTable like that. Will try to replicate this when I got the chance but until then I may not be able to help you on this.

If you found a solution, kindly share too. Thanks!

**Comment by vankaiser** [comment]
Thank you for replying, I ended up using Schema class( for adding and removing dynamic columns ) and having the model to have dynamic $fillable for the dynamic columns so I can fetch it in one table, now ordering and search works and it's fast too.
