### ISSUE TITLE
 frequently shows error code on the same right code : DataTables warning: table id=users-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by robinnpca** [yajra/laravel-datatables#1720]
I alwasys got this message irregular time on the same code.
The code is easiest basic demo. I don't add other code to it! 
Sometimes It work well to show the datatable as I need, sometimes it shows this error.
When I reload, research, or resort, the error message comes irregular times for the right code.
I don't know why it is so unstable?

I work on
System details
Operating System Windows 7
PHP Version 7.1.1
Laravel Version 5.5
Laravel-Datatables Version 8.4.3

**Comment by yajra** [comment]
You must be using `php artisan serve`? If yes, this is known issue of the package that occurs when using serve. Solution: don't use artisan serve and use apache, etc instead. :) 

See https://github.com/yajra/laravel-datatables#php-artisan-serve-bug for ref.
