### ISSUE TITLE
DataTables warning: table id=users-table - Exception Message:

### ISSUE THREAD

**Issue by dflow** [yajra/laravel-datatables#1722]
### Summary of problem or feature request
Not sure why I am getting this error
DataTables warning: table id=users-table - Exception Message:

Undefined index: campaign_job_id

Undefined index: campaign_job_id in /home/vagrant/Projects/vms/vendor/yajra/laravel-datatables-oracle/src/Engines/CollectionEngine.php:134
### Code snippet of problem
##php
'$campaign_job_totals = DB::table("campaign_jobs")
                ->select(
                    'campaign_jobs.id as campaign_job_id'
                )
                ->join('campaign_results','campaign_results.campaign_job_id','=', 'campaign_jobs.id')
                 ->where('campaign_jobs.id','=', $campaign_job->id)
->first();'

'<script>
    $(function() {
        $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('datatables.data') !!}',
                columns: [
            { data: 'campaign_job_id', name: 'campaign_job_id' }
        ]
    });
    });'

</script>

### System details

- Operating System
- PHP Version 7.2
- Laravel Version 5.4.36
- Laravel-Datatables Version 7.3

**Comment by yajra** [comment]
Maybe try removing `->first();'` on your query?
