### ISSUE TITLE
Parameters in request

### ISSUE THREAD

**Issue by butoibogdan** [yajra/laravel-datatables#173]
Hello
Please can you help me with a solutions to send a parameter wich i get in controller.
I need a solutions if exists in ajax to  - ajax: {url:"link/{id}"} or
a solutions to get the parameter from url.
Now if i try to get from url with request:segment(n) the respose is from route to datatables data
Thank you very much
Best regards

**Comment by yajra** [comment]
@butoibogdan, try checking this example where it passes custom parameters and how to capture it. http://datatables.yajrabox.com/eloquent/advance-filter. Just use the `Request` object of laravel to get the parameters. For the segment, Laravel automatically passes the variable to your `Controller@method`. Check controller's docs on Laravel for more info.

**Comment by butoibogdan** [comment]
Thank you very much and have a nice day
