### ISSUE TITLE
Unable to fetch the custom parameters using 'with'

### ISSUE THREAD

**Issue by NitishKumarPatra** [yajra/laravel-datatables#1731]
I have already implemented datatables as a service and it works fine without any issue.

What I want to achieve is, let's say there is a table with 1000 records, and I don't want to show all of them at once say on index.php, on the load I want to show only the current month's records. The same index.php page contains a date range and a form submit button which reloads the page by passing the date range into the controller@index.

On the initial load, as the user cannot pass any date, so in the controller, I set the dates dynamically based on the month and returns the view with datatable

Now, if the user wants to view the previous month data, he has to choose the date range and click on filter.

The request goes to the same controller@index function, as it has parameters, the from and to dates are set from the request.

Now going down to the return of index function ie.
return $dataTable->with(['filterFromDate'=>$filterFromDate,'filterToDate'=>$filterToDate])->render(....)

the 'filterFromDate' and 'filterToDate' takes the month's 1st day and the last day as if the request didn't have any parameters. As a matter of fact, the dates are properly passing into the index function, but not to the datatables.

Please help with the issue

    public function index(BookDataTable $dataTable, Request $request){
        if($request->from_date && $request->to_date){
            $filterFromDate = date_format(new \DateTime($request->from_date),"Y-m-d");
            $filterToDate = date_format(new \DateTime($request->to_date),"Y-m-d");
        }else{
            $filterFromDate = date('Y-m-01');
            $filterToDate = date('Y-m-t');
             //These values always gets passed into the BookDataTable 
        }
      .
      .
      .
      <!-- I am not altering the $filterFromDate and $filterToDate values in between>
      .
      .
      return $dataTable->with(['filterFromDate'=>$filterFromDate,'filterToDate'=>$filterToDate])->render('books.datatable-index', compact('leads','filterFromDate','filterToDate'));
}

**Comment by yajra** [comment]
`$dataTable->with(['filterFromDate'=>$filterFromDate,'filterToDate'=>$filterToDate])` on assigns a property on your `BooksDataTable` class. You still need to set this on your query filters manually.

Something like: 

```php
class BooksDataTable extends ... {
  function query(Model $model) {
    return $model->newQuery()->whereBetween('date', [ $this->filterFromDate, $this->filterToDate ])...;
  }
}

**Comment by NitishKumarPatra** [comment]
I am already passing it into the query, but it seems that the datatable service is somehow caching the initial request made with the dates passed by the else block, that is why it doesn't consider the subsequent requests dates.

What i did as a workaround is by storing the dates for every request in session and overriding the constructor like this - 


    public function index(BookDataTable $dataTable, Request $request){
        session()->put('from_date',$filterFromDate);
        session()->put('to_date',$filterToDate);
        \\Adding into session after the if else block
    }


class BooksDataTable extends Datatable 
{
    protected $fromDate ='';
    protected $toDate = '';

    function __construct(Datatables $datatables, Factory $viewFactory)
    {
        $this->fromDate = session('from_date');
        $this->toDate = session('to_date');  
        
        parent::__construct($datatables, $viewFactory);   
    }
}

Now the search on filters are working fine, but if i use the search box to filter the results, it doesn't search from the already filtered results, rather it does from all the records.

**Comment by NitishKumarPatra** [comment]
I had another workaround to deal with it, for every search in the search box, it again makes a call, so i had to deal it in the index function


        if(!empty($request->from_date) && !empty($request->to_date)){
            $filterFromDate = date_format(new \DateTime($request->from_date),"Y-m-d");
            $filterToDate = date_format(new \DateTime($request->to_date),"Y-m-d");
        }else if(!empty(session('from_date')) && !empty(session('to_date'))){
            $filterFromDate = session('from_date');
            $filterToDate = session('to_date');
        }else{
            $filterFromDate = date('Y-m-01');
            $filterToDate = date('Y-m-t');            
        }



This works properly on-
Normal load(triggers else block)
Filtered load(triggers if block)
Searched load(triggers else if block) of the Datatable as a service

I am good as of now, but frankly speaking, i wanted it to pass using 'with' api with variables and not via session data, may be because of caching or first initialization of Datatable instance in index function ,or may be due to some othe reason that i may be unaware of , this api is not behaving properly. Let me know if you can somehow reproduce the same issue and get the 'with' api working.
