### ISSUE TITLE
Limit() or Take() on server side on Working

### ISSUE THREAD

**Issue by rijans** [yajra/laravel-datatables#1732]
### Summary of problem or feature request

 When I try to Limit the records, I get following error:

```
BadMethodCallException in Builder.php line 2405:
Call to undefined method Illuminate\Database\Query\Builder::getQuery()
```

### Code snippet of problem:

```
$query = DB::table('sales_invoices')
            ->where('client_id', $clientId)
            ->where('payment_status', '!=', 3)
            ->where('is_recurring_setting', 0)
            ->OrderBy('id', 'ASC')->take(2)->select();
```

### System details

- Operating System: Linux
- PHP Version: 7.1
- Laravel Version: 5.2
- Laravel-Datatables Version: 6

**Comment by yajra** [comment]
Limit should be done on the client side by setting the page length and the package will handle it for you dynamically. On the other hand, if you are only going to display 2 records, you can use collection instead.

```php
$query = DB::table('sales_invoices')
            ->where('client_id', $clientId)
            ->where('payment_status', '!=', 3)
            ->where('is_recurring_setting', 0)
            ->OrderBy('id', 'ASC')->take(2)->select()->get();
```

**Comment by rijans** [comment]
Hi, thanks. I actually needed to limit from server side, to show only specific records.

Thanks again.

**Comment by vipertecpro** [comment]
I am using DataTable as server, how do i put record limit here
i have 2-3 million records and i want to test it with few records first but i can't do, please help asap @yajra 

    /**
     * Get query source of dataTable.
     *
     * @param User $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(User $model)
    {
        return $model->select(['id', 'name'])->limit(10); // Why i can't use this ?????????????
        // OR
        // return $model->select(['id', 'name'])->take(10); // OR  this ?????????????
    }

**Comment by yajra** [comment]
@vipertecpro try adding a where clause to limit the data.


```php
return $model->select(['id', 'name'])-where('id', '<', 200_000);
```

**Comment by vipertecpro** [comment]
> @vipertecpro try adding a where clause to limit the data.
> 
> ```
> return $model->select(['id', 'name'])-where('id', '<', 200_000);
> ```

Yes that works correctly. Thank you so much
