### ISSUE TITLE
Searching / filtering with Query Builder, InnerJoin and aliases

### ISSUE THREAD

**Issue by AliSultanKhan** [yajra/laravel-datatables#1734]
### Summary of problem or feature request

Hi !

I'm facing to an issue regarding search filtering on a particular QueryBuilder with innerjoin
Summary of problem or feature request

When searching/filtering. Datatables throws this error :

![captussre](https://user-images.githubusercontent.com/33395254/39880375-0ca7f8b4-5497-11e8-91a3-a5eb45eed85a.PNG)

### Code snippet of problem
Here is the select statement with the datatable call :
![capturse](https://user-images.githubusercontent.com/33395254/39880431-36d498ae-5497-11e8-8243-a7888e6cb71a.PNG)
Here is the JavaScript columns def
![captssure](https://user-images.githubusercontent.com/33395254/39880521-7aa9f420-5497-11e8-8e92-6c13aa2fb1df.PNG)

I can't find how to solve this.. Any idea ?
Thanks !

### System details

- Operating System - Windows 10
- PHP Version 7.1.16
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by cromartie1984** [comment]
got the same issue somewhat :+1: 
![screenshot from 2018-05-27 18-49-49](https://user-images.githubusercontent.com/22010858/40588527-de8627f8-61de-11e8-8efe-1dda84a21513.png)

**Comment by nyarachm** [comment]
Also facing the same issue but with searching table data. 

Matching the datatable name to the database in js does the trick until you have a subquery or aggregate function where these do not have table names.

Still searching for a fix, else Collection based (as opposed to query based) may be the best option though much slower
