### ISSUE TITLE
Exporting a data table that is filtered using query parameters?

### ISSUE THREAD

**Issue by mseymour** [yajra/laravel-datatables#1735]
I am attempting to export a data table to CSV, but when I use query parameters to filter by a set of lookup tables (example: status, classification, using query parameters `s` and `c` respectively) and click on the export button, it will only export whatever is currently being searched (or not), and not what is currently shown in the data table, as the query parameters are not passed into the CSV export button.

What is the best way to get around this, since I need to have this multiple filtering functionality that can be exported?

**Comment by yajra** [comment]
I think your `ajax` url value should also include your query params for this to work.

**Comment by mseymour** [comment]
How would I update that? I've been looking through the documentation for both the package and DataTables.net and nothing has stood out for me so far.

**Comment by yajra** [comment]
Something like:

```php
->minifiedAjax(route('index', ['foo' => 'bar']))
```

**Comment by Alucard55555** [comment]
hi, i have a problem with this post, when i try to export all data the code return me only the filtering rows. but my data table is a service, can help me pls

**Comment by yajra** [comment]
@Alucard55555 I think that is the expected behavior. Exporting should apply any filters applied in the request. If you want to export all records that ignores the filters, you have to make your own custom action buttons that will do the job. See https://yajrabox.com/docs/laravel-datatables/master/buttons-custom for ref.

**Comment by Alucard55555** [comment]
@yajra 
thanks, I use the custom button but instead of the custom action, just add an if in the getAjaxResponseData method and add the support for my action in the render method, by the way in https://yajrabox.com/docs/laravel- datatables / master / buttons-custom does not mention the part in js for the custom action.

my code:
`public function render($view, $data = [], $mergeData = []){

        if ($this->request()->ajax() && $this->request()->wantsJson()) {
            return app()->call([$this, 'ajax']);
        }

        if ($action = $this->request()->get('action') and in_array($action, $this->actions)) {
            if ($action == 'print' || $action == 'MyPrint') {
                return app()->call([$this, 'printPreview']);
            }
            return app()->call([$this, $action]);
        }

        return view($view, $data, $mergeData)->with($this->dataTableVariable, $this->getHtmlBuilder());

    }
    protected function getAjaxResponseData(){
        $this->request()->merge(['length' => -1]);
        if($action = $this->request()->get('action')=='MyPrint'){
            $this->request()->merge(['search' => '']);
        }
        $response = app()->call([$this, 'ajax']);

        $data     = $response->getData(true);

        return $data['data'];
    }`
    and the js
`(function ($,DataTable){
    var _buildUrl = function(dt, action) {
        var url = dt.ajax.url() || '';
        var params = dt.ajax.params();
        params.action = action;

        if (url.indexOf('?') > -1) {
            return url + '&' + $.param(params);
        }

        return url + '?' + $.param(params);
    };

    DataTable.ext.buttons.MyPrint = {
        className: 'buttons-print',

        text: function (dt) {
            return  '<i class="fa fa-print"></i> Imprimir todo'; //+ dt.i18n('buttons.print', 'Print');
        },

        action: function (e, dt, button, config) {
            var url = _buildUrl(dt, 'MyPrint');
            window.location = url;
        }
    };
})(jQuery, jQuery.fn.dataTable);`

**Comment by agamyrat301** [comment]
I accomplished this saving filtered data id  to sessions. when want to export data read ids from sessions. every time data is filtered update the existing session.

**Comment by agamyrat301** [comment]
$person_query = null;
        $card_type = null;
        $person_status = null;

        if($request->has('person_query')){
            $person_query = $request->get('person_query');
        }

        if($request->has('card_type_filter')){
            $card_type = $request->get('card_type_filter');
        }
        if($request->has('person_status')){
            $person_status = $request->get('person_status');
        }

        if($request->ajax())
        {
            $data = Person::when($person_query, function ($query, $person_query){
                return $query->where(function ($q) use ($person_query){
                    return $q->where('name','LIKE',"%$person_query%")
                    ->orWhere('surname', 'LIKE', "%$person_query%")
                    ->orWhere('card_number','LIKE', "%$person_query%")
                    ->orWhere('passport_number','LIKE', "%$person_query%")
                    ->orWhereHas('embassy', function($query) use ($person_query){
                        return $query->where('name','LIKE', "%$person_query%");
                    })
                    ->orWhereHas('position', function($query) use ($person_query){
                        return $query->where('name','LIKE',"%$person_query%");
                    });


                });
            })->when($card_type, function ($query, $card_type){
                return $query->where('card_type',$card_type);
            })
                ->when($person_status, function ($query, $person_status){
                    if($person_status == "main"){
                        return $query->whereHas('companions');
                    } else if($person_status == "dependent"){
                        return $query->doesntHave('companions');
                    }
                })->whereNull('departure_date_tm')->get();


                $archive = $data->pluck('id')->toArray();
                session()->put('currently_available', $archive); // HERE I SAVE FILTERED DATA TO SESSIONS


            return DataTables::of($data)
                ->editColumn('fullname', function ($person) {
                    return $person->name.' '.$person->surname;
                })
                ->editColumn('embassy_name', function ($person) {
                    return $person->embassy->name;
                })
                ->editColumn('position', function ($person) {
                    return $person->position->name;
                })
                ->editColumn('card_type', function ($person) {
                    return trans('general.'.$person->card_type);
                })
                ->addColumn('action', function ($person)
                {
                    return view('people.currently_available_column', compact('person'));
                })
                ->addIndexColumn()
                ->toJson();
        }
    }



AND WHEN EXPORT BUTTON CLICKED 




  $archive = session()->get('currently_available');
                
        $export_data = $archive->map(function ($person) {
            return [
                'Имя Фамилия:' => $person->name . ' ' . $person->surname,
                'Дата рождения' => $person->birthday ? date('d/m/Y', strtotime($person->birthday)) : '',
                'Место рождения:' => $person->place_of_birth ? $person->place_of_birth : '',
                'Гражданство:' => $person->nationality,
                'Семейное положение:' => trans('general.' . $person->marital_status),
                'Тип паспорта:' => trans('general.' . $person->passport_type),
                 ..........
            ]
       })->toArray();

return Excel::download(new PeopleExport($export_data), 'Currentlu_available.xlsx');
