### ISSUE TITLE
Order by nulls last produces sql error under postgres

### ISSUE THREAD

**Issue by BARNZ** [yajra/laravel-datatables#1738]
### Summary of problem or feature request

When `orderByNullsLast` is used is appears as though column identifiers are not escaped properly.

For example a user table that has a column named `order` and trying to do the following results in the column `order` not being escaped and a sql error when sorting by this `order` column

```
return datatables(User::query())
            ->orderByNullsLast()
            ->make(true);
```

Removing `orderByNullsLast` makes the query work as expected.

### System details

- Operating System - `Windows 10`
- PHP Version - `7.2`
- Laravel Version - `5.6`
- Laravel-Datatables Version - `8.5.1`
- Database - `PostgreSQL 10`

**Comment by yajra** [comment]
Working fine for me on `mysql`. Maybe try updating `datatables.php` config to fit your need?

```
'nulls_last_sql' => '%s %s NULLS LAST',
```
