### ISSUE TITLE
Problem with many to many join statements.

### ISSUE THREAD

**Issue by dogrocker** [yajra/laravel-datatables#174]
Hello, I try to select last row for each group with many to many table by using join statements.

Because I want to use Column search. 

This is my schema.

```
table vehicles
id
1
2
```

```
table regis_history
vehicle_id     regis_id     created_at
1                      1             yesterday
1                      2             today
```

```
table regis
id
1
2
```

Now I use this query to select all vehicle with have regis or not have regis.
And if it have regis I try to select the last row of regis that group by vehicle_id.

```
$vehicle = Vehicle::leftJoin('registration_history AS rh', 'vehicles.id', '=', 'rh.vehicle_id')
            ->leftJoin('registrations AS r', 'rh.registration_id', '=', 'r.id')
            ->select(*)
            ->groupBy('rh.vehicle_id')
            ->orderBy('rh.created_at', 'desc')
            ->get();
```

But It alway select the `yesterday` row.

How to get the `today` row ?

Thank you for help.

**Comment by dogrocker** [comment]
I tried to use.

```
->addColumn('regis', function ($vehicles) {
                $regis = $vehicles->registrations()->orderBy('registration_history.id', 'desc')->first();
                if ($regis) {
                    return $regis;
                } else {
                    $regis['registration_number'] = '-';
                    return $regis;
                }
            })
```

It work but I can't use the search function so now I try to use `leftjoin` but can't get the last row.

**Comment by yajra** [comment]
I think this issue is not related to datatables. Anyways, you have to check your SQL first if it does display the correct output to verify that you are passing correct data on datatables. Below is an example SQL which I think you can use. Convert it to Eloquent ^_^.

```sql
select vehicles.id, vehicles.name, max(vehicle_histories.created_at) last_registration
from vehicles 
left join vehicle_histories on vehicle_histories.id = vehicles.id
group by vehicles.id, vehicles.name
```
