### ISSUE TITLE
Need help with some RAW SQL

### ISSUE THREAD

**Issue by arieltoledo** [yajra/laravel-datatables#1744]
### BadMethodCallException Call to undefined method Illuminate\Database\Query\Builder::getQuery()

Hi everyone, im using datatables as service in my project. I got this IntermediateDataTable.php file where I have the next query:
```php
$sql = 'select intermediates.* from intermediates join goals on goals.id = intermediates.goal_id where goals.jurisdiction_id = 9';
$test = DB::table(DB::raw("($sql) as my"));
$this->applyScopes($test);
```
But I get the error described above. I been reading other issues with no luck yet; I try adding ```->get()``` but it returns **Method getQuery does not exist.** 

Thanks a lot!

**Comment by yajra** [comment]
I think the query can be achieved using the builder, why not use it instead of raw sql?

```php
$query = DB::table('intermediates')->join(..)->select('intermediates.*');
```

Anyways, the raw sql looks fine. I suspect there must be some other things that causes an issue. I suggest you inspect the ajax request and enable the debug to true to see the generated SQL. From there, we can identify which query fails.

**Comment by arieltoledo** [comment]
Hi @yajra, well I made some testing, changing the query to 
```
  $test = DB::table('goals')
    ->join('intermediates', 'goals.id', '=', 'intermediates.goal_id')
    ->where('goals.jurisdiction_id', '=', 9);
    return $this->applyScopes($test);
```
inside the query() function and it returns 
###BadMethodCallException Call to undefined method Illuminate\Database\Query\Builder::getQuery()

So I change my code by adding 
###use Yajra\Datatables\Datatables;
and inside dataTable() function
```
test = DB::table('goals')
            ->join('intermediates', 'goals.id', '=', 'intermediates.goal_id')
            ->where('goals.jurisdiction_id', '=', 9)
            ->select('intermediates.*', 'goals.*')
            ->get();
return Datatables::of($test)
    ->addColumn('action', 'intermediate.datatables_actions')
    ->editColumn('title', function($intermediate){
        $intermediate_id = $intermediate->id;
        $title = $intermediate->title;
        return "<a style='text-decoration: none; color:#000' href='/goals-intermediate/" . $intermediate_id . "/edit'>" . $title . "</a>"; })
    ->rawColumns(['action', 'title']);
    ```
    
 And it kinda work, but I read somewhere that we shouldn't use Datatables::of.

**Comment by yajra** [comment]
What database are you using? I think this getQuery issue occurs when using mongodb.
