### ISSUE TITLE
Get error information

### ISSUE THREAD

**Issue by jajack36** [yajra/laravel-datatables#1745]
## sample code:
$users = user::with('info');

return $datatables->eloquent($users )
-> addColumn('id', function($db){
          return $db->id;
    })
-> toJson();
## question
why this id always get info id?

**Comment by yajra** [comment]
You need to include a select statement when using eager loading. See https://datatables.yajrabox.com/eloquent/relationships for ref.

```
$users = user::with('info')->select('users.*');
```
