### ISSUE TITLE
DataTables warning: table id=myTableId - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by ujjual** [yajra/laravel-datatables#1746]
DataTables warning: table id=myTableSort - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Datatable works for some time then starts alerting this error .

- Database: PostgreSQL
- Operating System: Windows 10
- PHP Version:7.0
- Laravel Version:5.4
- Laravel-Datatables Version

**Comment by yajra** [comment]
> Datatable works for some time then starts alerting this error .

You must be using `artisan serve`. Please use apache/nginx as this is a know issue with the package. See https://github.com/yajra/laravel-datatables#php-artisan-serve-bug for ref.
