### ISSUE TITLE
Eloquent DataTables casts all attributes to string

### ISSUE THREAD

**Issue by peyobr** [yajra/laravel-datatables#1747]
### Eloquent DataTables casts all attributes to string

Eloquent DataTables casts all attributes to string, even int ids, even if explicit eloquent model $casts is set.

### System details

- Linux Mint 18.3
- PHP 7.0.30-0ubuntu0.16.04.1
- Laravel Version 5.5.40
- Laravel-Datatables Version 8.6.0
- Mysql 5.5.72-ubuntu0.16.04.1

**Comment by BARNZ** [comment]
I encountered this problem today as well. Wondering why this would be happening?

What I'm getting:

![image](https://user-images.githubusercontent.com/2202345/45399988-5f043780-b69e-11e8-9a23-588df7775455.png)

What I expect:

![image](https://user-images.githubusercontent.com/2202345/45399969-4eec5800-b69e-11e8-8145-550b4638dd2e.png)

**Comment by yajra** [comment]
Found the related issue/pr: https://github.com/yajra/laravel-datatables-buttons/pull/67.

ATM, I think you need to use fractal integration for proper API response but I also agree that we can improve the package not to casts all data to string and let the eloquent casting handle it. 

Can't check this further though but will definitely implement this when I got the chance. If any of you can, please do not hesitate to submit a PR. Thanks!

**Comment by ridaamirini** [comment]
@yajra I added a PR

**Comment by yajra** [comment]
Fixed on v8.13.2, thanks to @ridaamirini!

**Comment by jovpet** [comment]
What have happened with that? It seems it has been reverted in version 9! `DataProcessor.php`
It seems this PR from @ridaamirini has been discarded. @yajra ?
`
protected function escapeColumns(array $output)
    {
        return array_map(function ($row) {
            if ($this->escapeColumns == '*') {
                $row = $this->escapeRow($row);
            } elseif (is_array($this->escapeColumns)) {
                $columns = array_diff($this->escapeColumns, $this->rawColumns);
                foreach ($columns as $key) {
                    Arr::set($row, $key, e(Arr::get($row, $key)));
                }
            }

            return $row;
        }, $output);
    }
`

**Comment by yajra** [comment]
It was reverted due to a breaking change and still unresolved. https://github.com/yajra/laravel-datatables/issues/1951. Will try to have a look at this again when I got the chance.

**Comment by rilwanmsm** [comment]
Any updates?

**Comment by fayaz668** [comment]
> It was reverted due to a breaking change and still unresolved. #1951. Will try to have a look at this again when I got the chance.

any updates??

**Comment by ridaamirini** [comment]
@rilwanmsm @fayaz668 I don't think this will be fixed...

**Comment by yajra** [comment]
Can't check this further atm. Maybe you guys can provide some tests / feedbacks on https://github.com/yajra/laravel-datatables/issues/1951?

**Comment by fayaz668** [comment]
@yajra , @ridaamirini below methods works for me 

  ```
  return \DataTables::eloquent(Users::where('isActive',1))
        ->rawColumns(['id'])
        ->make(true);
```
