### ISSUE TITLE
Sort language UTF-8 

### ISSUE THREAD

**Issue by tranthanhtuan269** [yajra/laravel-datatables#1748]
I select in database, return is true. But put data to datatable then it false. Please help to me!

$sql = "SELECT categories.id as id, categories.name as name, users.name as updater FROM translate.categories JOIN users on users.id = categories.updated_by order by categories.name";
        
        $query = \DB::select($sql);
        // out put : A   Á   B

        return datatables()->of($query)
                ->addColumn('action', function ($category) {
                    return $category['id'];
                })
                ->addColumn('all', function ($category) {
                    return $category['id'];
                })
                ->removeColumn('id')->make(true);
        // output A    B   Á

**Comment by yajra** [comment]
`\DB::select($sql);` uses collection. I suggest you use query builder instead. See https://datatables.yajrabox.com/fluent/joins for ref.

**Comment by tranthanhtuan269** [comment]
Thank you so much!
