### ISSUE TITLE
Class 'Yajra\DataTables\Facades\Datatables' not found

### ISSUE THREAD

**Issue by Pashamahardika** [yajra/laravel-datatables#1754]
### This is my config/app.php
Provider : 
Yajra\DataTables\DataTablesServiceProvider::class,
Facade: 
'DataTables' => Yajra\DataTables\Facades\DataTables::class,

### System details

- Operating System : Ubuntu 16.04
- PHP Version : 7.2.5
- Laravel Version : 5.5.40
- Laravel-Datatables Version : 8.6.0

**Comment by yajra** [comment]
`Datatables` was updated to `DataTables`, notice the the capital T. See https://yajrabox.com/docs/laravel-datatables/master/upgrade for details. Thanks!

**Comment by LendisFabri** [comment]
thanks @yajra
