### ISSUE TITLE
I want to add two columns each containing HTML

### ISSUE THREAD

**Issue by kamhawy4** [yajra/laravel-datatables#1756]
Picture of the problem
![ssssssssssss](https://user-images.githubusercontent.com/25951080/40783176-f454b99a-64e1-11e8-9897-21aa4f83916f.PNG)

I want to add two columns each containing HTML

=> this Controller

public function getPosts()
    {
    	$users = DB::table('demo_posts')->select('*');
             return Datatables::of($users)->addColumn('action', function ($users) {
               return    view('admin.datatable.buttons',compact('users'))->render();

              })->addColumn('option', function ($users) {
               return    view('admin.datatable.option',compact('users'))->render();
           })->make(true);
    }

=> this ajax

<script type="text/javascript">
$(document).ready(function() {
    oTable = $('#users').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "{{ route('datatable.getposts') }}",
        "columns": [
            {data: 'action', orderable: false, searchable: false},
            {data: 'id', name: 'id'},
            {data: 'title', name: 'title'},
            {data: 'category', name: 'category'},
            {data: 'tag', name: 'tag'},
            {data: 'option', orderable: false, searchable: false},
        ]
    });
});
</script>

- Operating System  : windows 10
- PHP Version : 7.0.0
- Laravel Version : 5.5
- Laravel-Datatables Version : 8.6

**Comment by yajra** [comment]
You need to use raw columns for cell that have html content. See https://yajrabox.com/docs/laravel-datatables/master/raw-columns for ref.

**Comment by kamhawy4** [comment]
Done :: Thank You Very much

**Comment by PiyushNagwani** [comment]
thank you  so much you save my lot of time
