### ISSUE TITLE
Collection Demo using Github API as data source

### ISSUE THREAD

**Issue by wattsie** [yajra/laravel-datatables#1760]
Hi,
  Reviewing "https://datatables.yajrabox.com/collection/github"

  I noticed the demo only present 30 items.

  If you manually go to "https://api.github.com/search/repositories?q=laravel" you will see there is over 117,439 given as a total count within the JSON response.

  To get the next page of results from the GitHub API, one would call "https://api.github.com/search/repositories?q=laravel&page=2&per_page=30"

  How would one modify the example "CollectionController.php" to pass either the current "page" parameter or optionally the "per_page" parameter when selecting the various pages (not as a search query) and reload the next lot of data into the table?

  Many thanks in advance.

Cheers.

**Comment by yajra** [comment]
Hi,

Thanks for the question and this got my attention :). Reviewing the code, here is how to implement it on the latest version of the package with proper pagination.

```php
$search       = request('search');
$keyword      = $search['value'] ?: 'laravel';
$client       = new \GuzzleHttp\Client();
$per_page     = (int) request('length');
$page         = ceil(request('start') / $per_page) + 1;
$response     = $client->get('https://api.github.com/search/repositories', [
    'query' => [
        'q'        => $keyword,
        'page'     => $page,
        'per_page' => $per_page,
    ],
]);
$repositories = json_decode($response->getBody()->getContents(), true);

return datatables()
    ->collection(collect($repositories['items']))
    ->filter(function (){})
    ->setTotalRecords($repositories['total_count'])
    ->setFilteredRecords($repositories['total_count'])
    ->skipPaging();
```

**Comment by wattsie** [comment]
Hi,
  Thanks for your update. I will check it out.

  It might be worth updating the "yajrabox" example for others to see as well.

Cheers.

**Comment by wattsie** [comment]
Hi,
  Just tested this out locally. Found some weird issues.

  When the table goes to load, I get the following:
`DataTables warning: table id=datatable - Invalid JSON response. For more information about this error`

  So looked into the `getGitHubData` function and found when the response is passed to "json_decode", it returns an invalid response .
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

  Viewing the raw data that is returned I see the following.
> HTTP/1.0 200 OK
> Cache-Control: no-cache, private
> Content-Type:  application/json
> Date:          Wed, 06 Jun 2018 23:25:31 GMT
> 
> {"draw":1,"recordsTotal":117716,"recordsFiltered":117716,"data":..........................

The ajax call that is being made is to the url
`/github-data?draw=1&columns[0][data]=stargazers_count&columns[0][name]=stargazers_count&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=full_name&columns[1][name]=full_name&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=owner.login&columns[2][name]=owner.login&columns[2][searchable]=false&columns[2][orderable]=false&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=description&columns[3][name]=description&columns[3][searchable]=true&columns[3][orderable]=true&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=private&columns[4][name]=private&columns[4][searchable]=true&columns[4][orderable]=true&columns[4][search][value]=&columns[4][search][regex]=false&order[0][column]=0&order[0][dir]=desc&start=0&length=-1&search[value]=&search[regex]=false&_=1528325530050`

  PS: Using guzzlehttp/guzzle - 6.3.2

  One this that is interesting, if you do a "dump" on the `$response->getBody()->getContents()` before the `json_decode`, there are quotes and \n characters being printed.

  Ill dig deeper tomorrow, but if you have any suggestions, please let me know.

Cheers.

**Comment by wattsie** [comment]
Hi, 
  Found a solution that works for me.

  Looks like the `datatables()` needs a `->make(true)` call..

ie, change
```
return datatables()
    ->collection($repositories['items'])
    ->filter(function (){})
    ->setTotalRecords($repositories['total_count'])
    ->setFilteredRecords($repositories['total_count'])
    ->skipPaging();
```

to:
```
return datatables()
    ->collection($repositories['items'])
    ->filter(function (){})
    ->setTotalRecords($repositories['total_count'])
    ->setFilteredRecords($repositories['total_count'])
    ->skipPaging()
    ->make(true);
```

Now the tables are rendering correctly...

Many thanks.

**Comment by wattsie** [comment]
Hi,
  Sorry for the hassles, I hope this is my last issue.

  I have found that github search has a rate limit, ie. if you do to many requests the guzzle get response is a 403 forbidden.   _(this may also be true for other api call issues, such as connection timeout, dns issues, remote api authentication issees and so on)_

  Of course, the 403 error causes the Controller to return an `error 500` and guzzle exception, which in turn causes the browser to popup a `DataTables warning: table id=datatable - Ajax error. For more information about this error, please see http://datatables.net/tn/7`.

  What is the best way to return a more appropriate notice or message when the table renders, instead of the default error.

  As en example, I modified the Controller to do the following.

  Please let me know if there is a more elegant way of doing this. 

```
public function getGithubData(Request $request) {
        $search   = request('search');
        $keyword  = $search['value'] ?: 'laravel';
        $client   = new \GuzzleHttp\Client(['http_errors' => false]); // Force Guzzle to not through exceptions
        $per_page = (int) request('length');
        $page     = ceil(request('start') / $per_page) + 1;
        $response = $client->get('https://api.github.com/search/repositories', [
            'query' => [
                'q'        => $keyword,
                'page'     => $page,
                'per_page' => $per_page,
            ],
        ]);
        // Check if the response code is 200
        if ($response->getStatusCode() == 200) {
            $repositories = json_decode($response->getBody()->getContents(), true);
            return datatables()
                            ->collection($repositories['items'])
                            ->filter(function () {
                                
                            })
                            ->setTotalRecords($repositories['total_count'])
                            ->setFilteredRecords($repositories['total_count'])
                            ->skipPaging()
                            ->make(true)
            ;
        } else {
            // On error, return an empty datatable with error message
            return datatables()
                            ->collection(array ())
                            ->setTotalRecords(0)
                            ->setFilteredRecords(0)
                            ->skipPaging()
                            ->with([
                                'error' => 'Error ' . $response->getStatusCode() . ': ' . $response->getReasonPhrase() . '.'
                            ])
                            ->make(true)
            ;
        }
    }
```

**Comment by yajra** [comment]
Hi, 

I was using the service approach which is the reason I forgot to include `->make(true)` or `toJson()`. Glad you figure this out.

On the other hand, I think you should use Github SDK to make the request instead of using guzzle. Using github SDK with proper authorization will give you more api request limit than a public request afaik.

**Comment by wattsie** [comment]
Hi,
  Thanks.

  I am thinking more along the line of if there are errors generated from any API calls, how would one best handle them.

  ie. I focused on your example which uses GitHub, whereas my back-end uses a SOAP API to a 3rd party web-service.

  I can easily handle all the back-end code, and if I get an error, I am trying to work out how the best way is to have the datatable display the error.

  I don't really want to simply return an empty array, I would rather be able to pass back some type of error string for a popup.

  Thanks heaps, muchly appreciated.

Cheers.
