### ISSUE TITLE
How to hide pagination block if few rows

### ISSUE THREAD

**Issue by sergeynilov** [yajra/laravel-datatables#1761]
### Code snippet of problem

Hello,
Using Datatables I want to hide pagination block, when there are too few rows in result set, in other words when pagination has only 1 link...
Is there is such option?

Or maybe event when data are retrieved, get number of read rows and to hide pagination block using jquery?

Thanks!

### System details

"yajra/laravel-datatables-oracle": "^8.6"
Laravel Framework : 5.5.40
php 7.1

**Comment by yajra** [comment]
I think this can be achieved on the javascript & css level. Listen on the drawCallback then count the results. Hide the pagination block using CSS.

**Comment by sergeynilov** [comment]
Thanks! Could you also point how to read property rows_number per 1 page ?
I do not need Show selection  entries...

**Comment by yajra** [comment]
The are options that you can also use to hide some features. See official docs https://datatables.net/reference/option/ for ref. I think what you need is `lengthChange`.
