### ISSUE TITLE
Display Datatable of 2 variable

### ISSUE THREAD

**Issue by Mravatech** [yajra/laravel-datatables#1762]
i have `$reservations` and `room_categories` and i want to to display both hem on a table
having error

> ErrorException (E_WARNING)
> Illegal offset type

```
$datatable = Datatables::of($reservations)
            ->with ($room_categories));
             return $datatable->make(true);
```

**Comment by yajra** [comment]
Please see https://datatables.yajrabox.com/eloquent/relationships for ref.
