### ISSUE TITLE
How to custom buttons all in one

### ISSUE THREAD

**Issue by bocanhcam** [yajra/laravel-datatables#1763]
Hi, I was searching around but not found anything. Can you give me a hand. I just want to know how to custom all buttons append to one div. So I can customize that div and do the dropdown UI. Thank you so much.

My code is exactly same in the document https://yajrabox.com/docs/laravel-datatables/7.0/buttons-starter.

- PHP Version 7.
- Laravel Version 5.4
- Laravel-Datatables Version ^7.0

**Comment by yajra** [comment]
I think what you need is buttons collection. See https://datatables.net/extensions/buttons/examples/initialisation/collections for ref.
