### ISSUE TITLE
error trying to use datatables on a collection of models BadMethodCallException with message 'Method Illuminate\Database\Query\Builder::getLogTextAttribute does not exist.'

### ISSUE THREAD

**Issue by jarloyz** [yajra/laravel-datatables#1766]
### Summary of problem or feature request
Hello everyone, i am trying to make a datatable of a model but went i try i got this error, i am using laravel 5.6.

### Code snippet of problem
Psy Shell v0.8.18 (PHP 7.2.5-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> use DataTables
>>> $resp= Datatables::collection(User::all())->make(true);
[!] Aliasing 'User' to 'App\User' for this Tinker session.
BadMethodCallException with message 'Method Illuminate\Database\Query\Builder::getLogTextAttribute does not exist.'
>>> 

### System details

- Operating System ubuntu 16.04 64 bit
- PHP Version 7.2
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
You may have some mutators / appends on your user model that does not have a proper value. Try disabling the mutators first and check again?

**Comment by yajra** [comment]
Tried the same code on my local machine with output:

```php
Psy Shell v0.9.6 (PHP 7.1.8 — cli) by Justin Hileman
>>> datatables(App\User::all())->toJson()
=> Illuminate\Http\JsonResponse {#4299
     +headers: Symfony\Component\HttpFoundation\ResponseHeaderBag {#4301},
     +original: [
       "draw" => 0,
       "recordsTotal" => 6,
       "recordsFiltered" => 6,
       "data" => [
         [
           "id" => "1",
           "email" => "admin@example.com",
...
```

**Comment by jarloyz** [comment]
thanks for you repply the problem is that i need some like this 
SELECT U.id,
    last_log.created_at
FROM users AS U
    LEFT JOIN
        (
            SELECT id,
                MAX(created_at) AS created_at
            FROM login_logs
            GROUP BY id
        ) AS last_log
    ON  last_log.id = U.id;

but i cant get the query

**Comment by jarloyz** [comment]
it worked i modify my user model and now work. Thanks
