### ISSUE TITLE
How to make for any row several buttons

### ISSUE THREAD

**Issue by sergeynilov** [yajra/laravel-datatables#1768]
### Summary of problem or feature request

Hello,
I get this example
https://datatables.yajrabox.com/eloquent/add-edit-remove-column
to make for any row in datatable several buttons, like:
```
        get())

            ->editColumn('action', '<a href="/admin/articles/edit/{{$id}}"><i class="voyager-edit"></i></a>')
            ->editColumn('action_delete', '<a href="#" onclick="javascript:deleteArticle()"><i class="voyager-trash"></i></a>')

        ->make(true);
```

and in template :

```
                columns: [
                ...
                    { data: 'action', name: 'action', orderable: false, searchable: false },
                    { data: 'action_delete', name: 'action_delete', orderable: false, searchable: false }
```

But I see the second column as a text:
https://imgur.com/a/Ru1HC2l

Which is the right way? I need to add several buttons of similar type...

Thanks!

### System details
- Operating System
- PHP 7.1
- Laravel 5.6
- Laravel-Datatables "yajra/laravel-datatables-oracle": "^8.6":

**Comment by yajra** [comment]
Hi @sergeynilov,

On latest version, you need to specify columns with html using:

```php
->rawColumns(['action', 'action_delete'])
```

`action` is escaped by default but if multiple columns have html, you need to redeclare it on the array.

**Comment by Artistan** [comment]
seems to be an issue through other areas
https://github.com/yajra/laravel-datatables/issues/1898
