### ISSUE TITLE
Cant edit checkbox datatables

### ISSUE THREAD

**Issue by MusicGindos** [yajra/laravel-datatables#1769]
### Summary of problem or feature request

When i add checkbox on Datatables, i cant make it edit them.
Radio working, text working but when i press done, the column does not getting update.
What can i do?

### Code snippet of problem
{
                label: "Banks:",
                name: "banks",
                type: "checkbox",
                options: [
                    {label: "bank1", value: "10"},
                    {label: "bank2", value: "11,17"},
                    {label: "bank3", value: "12"},
                    {label: "bank4", value: "13"},
                    {label: "bank5", value: "20"},
                    {label: "bank6", value: "31,52,14,46"}
                ]
            },

### System details

- Operating System windows
- PHP Version 7.2.5
- Laravel Version 5.5.40
- Laravel-Datatables Version 1.0

**Comment by yajra** [comment]
After the edit, trigger a table redraw function? 

```
// do edit
oTable.draw()
```
