### ISSUE TITLE
Sum values on a column with numbers

### ISSUE THREAD

**Issue by marioene** [yajra/laravel-datatables#177]
Do you have an example with a total sum on a column with numbers?

**Comment by yajra** [comment]
I think i don't have one for sum but the concept is likely the same on this example: http://datatables.yajrabox.com/eloquent/count

**Comment by naude** [comment]
Yajra - thanks for a great package.
I managed to get the sum of columns working.
Eloquent simply returns the amount in a column - no sum in eloquent required.
In the blade table def add class to the heading
< th class="sum1">Amount</ th>
< th class="sum2">Days</ th>
And the <tfoot> you do as follows
< th></ th>........ the jscript outputs the total in the right column footer for you.
Then in the $('#table').DataTable{ function add this 
 "initComplete": function (settings, json) {
                    this.api().columns('.sum1').every(function () {
                        var column = this;
                        var sum1 = column
                                .data()
                                .reduce(function (a, b) {
                                    return parseInt(a, 10) + parseInt(b, 10);
                                });
                        $(column.footer()).html(sum1);
                    });
                    this.api().columns('.sum2').every(function () {
                        var column = this;
                        var sum2 = column
                                .data()
                                .reduce(function (a, b) {
                                    return parseInt(a, 10) + parseInt(b, 10);
                                });
                        $(column.footer()).html(sum2);
                    });
                },

Thanks to http://stackoverflow.com/users/3549014/gyrocode-com for the jsfiddle
