### ISSUE TITLE
filters not working in production server.

### ISSUE THREAD

**Issue by chamindar2002** [yajra/laravel-datatables#1770]
#Data table filters not working on production server

We have 3 enviorenments namely dev, qa and prod. The datatables filters just works fine on dev and qa enviorenments. But on production the filters does not work as expected. For example the search return all the records without filtering the records searched. The only difference to the production environment to that of dev and qa is that production server has a ssl and hence use https. 

When i observe the request I see that the input[] array is empty.

### System details

- Operating System
- PHP 7
- Laravel Version 5.5
- Laravel-Datatables Version 1

**Comment by yajra** [comment]
I think this is on apache/nginx config where ajax url are being encoded twice?.. have a similar closed issue but can't remember the name. The hint here is the input being empty array.

**Comment by yajra** [comment]
Found it! https://github.com/yajra/laravel-datatables/issues/1210

**Comment by yajra** [comment]
See this too:

https://github.com/yajra/laravel-datatables/issues/1086
https://github.com/yajra/laravel-datatables/issues/142

**Comment by chamindar2002** [comment]
I have tried setting the cgi.fix_pathinfo=0 but still the same. Also mcrypt is enabled. see the screen below.
![screenshot-admin lyceum zuluerp com-2018 06 15-09-10-17](https://user-images.githubusercontent.com/12139703/41449028-2fc76b80-707c-11e8-86c3-3164014b9414.png)

**Comment by yajra** [comment]
Im not so knowledgable on server config but this issue is indeed related to your server setup. I suggest you consult a server administrator to help you with this. Thanks!
