### ISSUE TITLE
Eloquent Relationships and Versioning

### ISSUE THREAD

**Issue by jemoreno** [yajra/laravel-datatables#1771]
### Summary of problem or feature request

I am currently using [ProAI Eloquent-Versioning](https://github.com/ProAI/eloquent-versioning) for a few models to track changes.  I have no problems loading the initial view with the relations, but when I search it errors out because it doesn't know how to associate the versioned table column against the relation.  

Is there a way to force the relation and then query against the returned model to properly display datatables info.

### Code snippet of problem
public function campaign(){
    return $this->belongsTo(Campaigns::class,'campaign_id');
  }

$model = Segments::select('segments.*')->with('campaign');
return DataTables::of($model)->make(true);

### System details

Mac OS X 10.13.5  - Operating System
7.1.16                       - PHP Version
5.5.x                        - Laravel Version
8.7.0                        - Laravel-Datatables Version

**Comment by yajra** [comment]
I think the solution on https://github.com/yajra/laravel-datatables/issues/1772 would be applicable here too.

**Comment by yajra** [comment]
Also this demo https://datatables.yajrabox.com/relation/belongs-to seems relevant.

**Comment by jemoreno** [comment]
Yajra, thanks for the reply.  I did, in fact, try both of those solutions but the issue I'm having is that the column in question that I am trying to filter against is derived from a left join on the campaigns_version table which happens on the relation model of the campaign class.  When I try to filter using the techniques shown before I get a column not found error in SQL each time.  

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'campaigns_version.title' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `segments` inner join `segments_version` on `segments`.`id` = `segments_version`.`ref_id` and `segments_version`.`version` = `segments`.`latest_version` where `title` is not null and (LOWER(`segments_version`.`title`) LIKE %i% or LOWER(`campaigns_version`.`title`) LIKE %i%) and `segments_version`.`deleted_at` is null) count_row_table)
```

**Comment by jemoreno** [comment]
I decided not to go with the eloquent method and just do a series of joins to get the information I was looking for
