### ISSUE TITLE
datatables language not working

### ISSUE THREAD

**Issue by maxdiable** [yajra/laravel-datatables#1777]
hi,
i put this cose on my javascript:

$('#table-log').DataTable({
"language": {
"url": "//cdn.datatables.net/plug-ins/1.10.18/i18n/Italian.json"
},
});

but chrome show this error:

Failed to load http://cdn.datatables.net/plug-ins/1.10.18/i18n/Italian.json: Request header field X-CSRF-TOKEN is not allowed by Access-Control-Allow-Headers in preflight response.

br
Max

**Comment by Timfr89** [comment]
Just upload the file to you own public folder and use this:
```
                language: {
                    url: '/localisation/Dutch.json'
                },
```

**Comment by rafaelgus** [comment]
#I think you need to use array on the language param like:

```
public function html()
    {
        return $this->builder()
            ->columns([
                'id',
                'name',
                'actions',
            ])
            ->parameters([
                'dom' => 'Bfrtip',
                'order' => [ [0, 'desc'] ],
                'buttons' => ['csv', 'excel'],
                'language' => ['url => '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Italian.json']
            ]);
    }
```
`'language' => ['url' => '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json']`
