### ISSUE TITLE
Json returning with query strings

### ISSUE THREAD

**Issue by cagatayoncul** [yajra/laravel-datatables#178]
Hi, i dont want to return query strings with json data. How can i remove from results ?
Ex
```
"aQueries":[{"query":"select * from `users` where `users`.`id` = ? limit 1","bindings":[1],"time":0.74},
```

**Comment by yajra** [comment]
Just set `debug=false` on your env or config file for Laravel 4.

**Comment by cagatayoncul** [comment]
Omg :)) i am not tried on production server. I think datatables has own
configuration :) thank you
11 Eyl 2015 15:11 tarihinde "Arjay Angeles" <notifications@github.com>
yazdı:
