### ISSUE TITLE
Datatable addColumn variable results sharing issue

### ISSUE THREAD

**Issue by akhileshyolo** [yajra/laravel-datatables#1784]
Hi,
I am new to Yajra datatable . I am using datatable::of() and addColumn method to create json response.

I noticed that every addColumn has its own variable scope.
I was able to pass variables not declared in addColumn via use keyword.

But how do I share variables or results of one addColumn with other addColumn?

Moreover, chrome screen gets freezed for half second while retrieving new json data.

**Comment by yajra** [comment]
Share variable result? I think you just need to pass the variable by reference.

BTW, please paste some snippets for a better view of your issue. Thanks!

**Comment by arki7n** [comment]
1) How can I use variables/query results generated in 1 addColumn with other addColumn for same row?

2) Do I need to use Cache mechanism to store query results in one addColumn and call the cache data in other addColumn for same row data?

**Comment by arki7n** [comment]
3) How Do I block other columns other than manual addColumn by default?

4) Is there a way to block rest of column using remove Column via array of those column?

**Comment by arki7n** [comment]
3) Also let me know difference between yajra package and normal js plugin method

https://scotch.io/@neobk25/laravel-bootstrap-datatable-full-example

**Comment by DevHamx** [comment]
did you found any solution?

**Comment by pirex360** [comment]
Anybody knows the answer ? i need to a value from ->addColumn field.

**Comment by yajra** [comment]
Depends on your use case but one way is to encapsulate the logic inside your model?

```php
->addColumn('fullname', function($user) {
  return $user->fullname();
})
->addColumn('fullname2', function($user) {
  return $user->fulname(); // reuse the value from fullname?
})
```

**Comment by pirex360** [comment]
Thanks ;) It worked.
