### ISSUE TITLE
Class 'Yajra\DataTables\DataTables' not found

### ISSUE THREAD

**Issue by nishat-sayyed** [yajra/laravel-datatables#1786]
I always get this exception
**FatalThrowableError
Class 'Yajra\DataTables\DataTables' not found**

My composer.json is
"require": {
        "php": ">=5.6.4",
        "jenssegers/mongodb": "^3.2",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "yajra/laravel-datatables-oracle": "8.7.0"
    }

**My server has php version is 7.1.1**

I installed datatables as follows
**composer requrire yajra/laravel-datatables-oracle:8.7.0**

Please help

**Comment by ChinaSor** [comment]
This is my composer.json
```json
"yajra/laravel-datatables-buttons": "^3.2",
"yajra/laravel-datatables-html": "^3.7",
"yajra/laravel-datatables-oracle": "~8.0"
```
You can go to the directory to see if there is ?
path is  vendor\yajra\laravel-datatables-oracle\src\DataTables.php

**Comment by nishat0403** [comment]
@ChinaSor Thank you for the reply. 
Yes I can see the vendor\yajra\laravel-datatables-oracle\src\DataTables.php
But still getting the same error.

**Comment by ChinaSor** [comment]
If you can try `composer dump-autoload` effective?

**Comment by arki7n** [comment]
Use sudo command as well

**Comment by landongme** [comment]
add to \config\app.php
**Providers**
```
Yajra\DataTables\DataTablesServiceProvider::class,
Yajra\DataTables\ButtonsServiceProvider::class,
```
**aliases**
`'DataTables' => Yajra\DataTables\Facades\DataTables::class,`

use Yajra\DataTables\Services\DataTable;

reference =
[https://yajrabox.com/docs/laravel-datatables/master/installation](url)
[https://yajrabox.com/docs/laravel-datatables/master/buttons-installation](url)

i hope can help you :)

**Comment by Prince-254** [comment]
run the following command
`composer require yajra/laravel-datatables-buttons:^4.0 && php artisan vendor:publish --tag=datatables-buttons --force`
