### ISSUE TITLE
Row grouping server side

### ISSUE THREAD

**Issue by bluemountainteam** [yajra/laravel-datatables#1787]
### Summary of problem or feature request

Hi,
I would like use this feature "Row grouping":
https://datatables.net/examples/advanced_init/row_grouping.html
in serverside.
I don't find how can i develop it. Any idea ?

Thanks

### System details

- Operating System
- PHP Version 7.1
- Laravel Version 5.6
- Laravel-Datatables Version yajra/laravel-datatables-oracle ~8.0

**Comment by yajra** [comment]
Here is how I implemented it.

1. Add the row group assets.
2. Add a group column that will set as the group header
3. Set the group column in your javascript.

Also use this https://datatables.net/extensions/rowgroup/ as ref. The example provided is too complex.

**Comment by bluemountainteam** [comment]
Ok Yajra, thanks for your help

**Comment by yagrasdemonde** [comment]
It will be nice to have an example of integration of row grouping 😉
https://github.com/yajra/laravel-datatables/issues/1787#issuecomment-403114186

**Comment by Plasto13** [comment]
It may help someone.

With Builder

```php
public function index(Builder $builder)
    {
        $html = $builder->columns($this->checklog->getCollumns())
                        ->parameters([
                            'paging' => true,
                            'searching' => false,
                            'info' => false,
                            'searchDelay' => '500',
                            'language' => [
                            'url' => asset("modules/core/js/vendor/datatables/".locale().".json")
                                ],
                            'order'=> [[0, 'desc'],[4, 'asc']],
                            'rowGroup'=> [
                                'dataSrc' => ['created_at', 'point_id'],
                            ],
                        ])
                        ->ajax([
                            'url' => route('api.admin.patrol.checklogs.datatables'),
                            'type' => 'POST',
                        ]);
        $base = $this->base;
        
        return view('patrol::admin.checklogs.index', compact('base', 'html'));
    }
```

Ajax controller : 
```php
 return DataTables::of(CheckLog::query()->with(['point', 'patrolStatus', 'equipment.line.hall', 'files'])) 
                    ->editColumn('created_at', function(CheckLog $checklog){
                        return $checklog->created_at->tz(setting('base::timezone'))->format(setting('base::datetimeformat'));
                    }) 
                    ->editColumn('point_id', function(CheckLog $checklog){
                        if (!$checklog->point){
                            $d = Point::withTrashed()->find($checklog->point_id);
                            return $d->title;
                        }
                        return $checklog->point->title;
                    }) 
                    ->editColumn('user_id', function(CheckLog $checklog){
                        if (is_object($checklog->user)) {
                            return $checklog->user->first_name.' '.$checklog->user->last_name;
                        }
                    }) 
                    ->editColumn('photo', 'patrol::admin.checklogs.columns.image')
                    ->editColumn('action', function(CheckLog $checklog){
                        return view('patrol::admin.checklogs.columns.action', compact('checklog'));
                    })
                    ->rawColumns(['description', 'photo', 'action'])
                    ->filter(function ($query) use ($request) {
                        if ($request->get('planrepair')) {
                           $query->where('plan_repair', '=', 1);
                        }
                        if ($name = $request->get('check')) {
                            $query->where('check_id', '=', $name);
                        }
                        if ($name = $request->get('status')) {
                            $query->where('patrol_status_id', '=', $name);
                        }
                        if ($name = $request->get('hall')) {
                            $query->whereHas('equipment.line.hall', function ($q) use ($name) {
                                $q->where('equipment_name', 'like', "%$name%");
                            });
                        }
                        if ($name = $request->get('line')) {
                            $query->whereHas('equipment.line', function ($q) use ($name) {
                                $q->where('equipment_name', '=', $name);
                            });
                        }
                        if ($name = $request->get('equipment')) {
                            $query->whereHas('equipment', function ($q) use ($name) {
                                $q->where('equipment_name', 'like', "%$name%");
                            });
                        }
                        if ($name = $request->get('point')) {
                                $query->where('point_id', '=', $name);
                        }
                        if ($name = $request->get('user')) {
                            $query->whereHas('user', function ($q) use ($name) {
                                $sql = "CONCAT(users.first_name,' ',users.last_name)  like ?";
                                $q->whereRaw($sql, ["%{$name}%"]);
                            });
                        }
                    })
                    ->toJson();  
}
```
blade template
```html
@extends('layouts.master')

@if (isset($base['filters']))
@section('styles')
<link rel="stylesheet" href="{!! Module::asset('base:css/select2.css') !!}" />
<link rel="stylesheet" href="{!! Module::asset('base:css/select2-bootstrap-dick.css') !!}"/>
<link rel="stylesheet" href="https://cdn.datatables.net/rowgroup/1.1.0/css/rowGroup.dataTables.min.css"/>
@endsection

@section('content-header')
    <h1>
        {{ trans('patrol::checklogs.title.checklogs') }}
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fas fa-tachometer-alt"></i> {{ trans('core::core.breadcrumb.home') }}</a></li>
        <li class="active">{{ trans('patrol::checklogs.title.checklogs') }}</li>
    </ol>
@stop

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <div class="btn-group pull-right" style="margin: 0 15px 15px 0;">
                  
                </div>
            </div>
            <div class="box box-primary">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @if (isset($base['filters']))
                        @include('base::inc.filter')
                    @endif
                    <div class="table-responsive">
                        {!! $html->table(['class'=>'table table-bordered table-hover dataTable']) !!}
                        <!-- /.box-body -->
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>
    </div>
    @include('core::partials.delete-modal')

    <div id="photoModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body showimage">
                   
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
@stop

@section('footer')
    <a data-toggle="modal" data-target="#keyboardShortcutsModal"><i class="fa fa-keyboard-o"></i></a> &nbsp;
@stop
@section('shortcuts')
    <dl class="dl-horizontal">
        <dt><code>c</code></dt>
        <dd>{{ trans('patrol::checklogs.title.create checklog') }}</dd>
    </dl>
@stop

@push('js-stack')
<script src="https://nightly.datatables.net/rowgroup/js/dataTables.rowGroup.min.js" type="text/javascript"></script>
    {!! $html->scripts() !!}
@endpush
```

Result :
![datatables-groupBy](https://user-images.githubusercontent.com/19667328/57753517-a428af80-76ec-11e9-8d18-c5950fe691b4.png)

**Comment by angellee177** [comment]
hi, do yo

> It may help someone.
> 
> With Builder
> 
> ```
> public function index(Builder $builder)
>     {
>         $html = $builder->columns($this->checklog->getCollumns())
>                         ->parameters([
>                             'paging' => true,
>                             'searching' => false,
>                             'info' => false,
>                             'searchDelay' => '500',
>                             'language' => [
>                             'url' => asset("modules/core/js/vendor/datatables/".locale().".json")
>                                 ],
>                             'order'=> [[0, 'desc'],[4, 'asc']],
>                             'rowGroup'=> [
>                                 'dataSrc' => ['created_at', 'point_id'],
>                             ],
>                         ])
>                         ->ajax([
>                             'url' => route('api.admin.patrol.checklogs.datatables'),
>                             'type' => 'POST',
>                         ]);
>         $base = $this->base;
>         
>         return view('patrol::admin.checklogs.index', compact('base', 'html'));
>     }
> ```
> 
> Ajax controller :
> 
> ```
> public function datatables(Request $request) 
> {
>  return DataTables::of(CheckLog::query()->with(['point', 'patrolStatus', 'equipment.line.hall', 'files'])) 
>                     ->editColumn('created_at', function(CheckLog $checklog){
>                         return $checklog->created_at->tz(setting('base::timezone'))->format(setting('base::datetimeformat'));
>                     }) 
>                     ->editColumn('point_id', function(CheckLog $checklog){
>                         if (!$checklog->point){
>                             $d = Point::withTrashed()->find($checklog->point_id);
>                             return $d->title;
>                         }
>                         return $checklog->point->title;
>                     }) 
>                     ->editColumn('user_id', function(CheckLog $checklog){
>                         if (is_object($checklog->user)) {
>                             return $checklog->user->first_name.' '.$checklog->user->last_name;
>                         }
>                     }) 
>                     ->editColumn('photo', 'patrol::admin.checklogs.columns.image')
>                     ->editColumn('action', function(CheckLog $checklog){
>                         return view('patrol::admin.checklogs.columns.action', compact('checklog'));
>                     })
>                     ->rawColumns(['description', 'photo', 'action'])
>                     ->filter(function ($query) use ($request) {
>                         if ($request->get('planrepair')) {
>                            $query->where('plan_repair', '=', 1);
>                         }
>                         if ($name = $request->get('check')) {
>                             $query->where('check_id', '=', $name);
>                         }
>                         if ($name = $request->get('status')) {
>                             $query->where('patrol_status_id', '=', $name);
>                         }
>                         if ($name = $request->get('hall')) {
>                             $query->whereHas('equipment.line.hall', function ($q) use ($name) {
>                                 $q->where('equipment_name', 'like', "%$name%");
>                             });
>                         }
>                         if ($name = $request->get('line')) {
>                             $query->whereHas('equipment.line', function ($q) use ($name) {
>                                 $q->where('equipment_name', '=', $name);
>                             });
>                         }
>                         if ($name = $request->get('equipment')) {
>                             $query->whereHas('equipment', function ($q) use ($name) {
>                                 $q->where('equipment_name', 'like', "%$name%");
>                             });
>                         }
>                         if ($name = $request->get('point')) {
>                                 $query->where('point_id', '=', $name);
>                         }
>                         if ($name = $request->get('user')) {
>                             $query->whereHas('user', function ($q) use ($name) {
>                                 $sql = "CONCAT(users.first_name,' ',users.last_name)  like ?";
>                                 $q->whereRaw($sql, ["%{$name}%"]);
>                             });
>                         }
>                     })
>                     ->toJson();  
> }
> ```
> 
> blade template
> 
> ```
> @extends('layouts.master')
> 
> @if (isset($base['filters']))
> @section('styles')
> <link rel="stylesheet" href="{!! Module::asset('base:css/select2.css') !!}" />
> <link rel="stylesheet" href="{!! Module::asset('base:css/select2-bootstrap-dick.css') !!}"/>
> <link rel="stylesheet" href="https://cdn.datatables.net/rowgroup/1.1.0/css/rowGroup.dataTables.min.css"/>
> @endsection
> 
> @section('content-header')
>     <h1>
>         {{ trans('patrol::checklogs.title.checklogs') }}
>     </h1>
>     <ol class="breadcrumb">
>         <li><a href="{{ route('dashboard.index') }}"><i class="fas fa-tachometer-alt"></i> {{ trans('core::core.breadcrumb.home') }}</a></li>
>         <li class="active">{{ trans('patrol::checklogs.title.checklogs') }}</li>
>     </ol>
> @stop
> 
> @section('content')
>     <div class="row">
>         <div class="col-xs-12">
>             <div class="row">
>                 <div class="btn-group pull-right" style="margin: 0 15px 15px 0;">
>                   
>                 </div>
>             </div>
>             <div class="box box-primary">
>                 <div class="box-header">
>                 </div>
>                 
>                 <div class="box-body">
>                     @if (isset($base['filters']))
>                         @include('base::inc.filter')
>                     @endif
>                     <div class="table-responsive">
>                         {!! $html->table(['class'=>'table table-bordered table-hover dataTable']) !!}
>                         
>                     </div>
>                 </div>
>                 
>             </div>
>         </div>
>     </div>
>     @include('core::partials.delete-modal')
> 
>     <div id="photoModal" class="modal fade" role="dialog">
>         <div class="modal-dialog">
>             <div class="modal-content">
>                 <div class="modal-body showimage">
>                    
>                 </div>
>                 <div class="modal-footer">
>                     <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
>                 </div>
>             </div>
>         </div>
>     </div>
> @stop
> 
> @section('footer')
>     <a data-toggle="modal" data-target="#keyboardShortcutsModal"><i class="fa fa-keyboard-o"></i></a> &nbsp;
> @stop
> @section('shortcuts')
>     <dl class="dl-horizontal">
>         <dt><code>c</code></dt>
>         <dd>{{ trans('patrol::checklogs.title.create checklog') }}</dd>
>     </dl>
> @stop
> 
> @push('js-stack')
> <script src="https://nightly.datatables.net/rowgroup/js/dataTables.rowGroup.min.js" type="text/javascript"></script>
>     {!! $html->scripts() !!}
> @endpush
> ```
> 
> Result :
> ![datatables-groupBy](https://user-images.githubusercontent.com/19667328/57753517-a428af80-76ec-11e9-8d18-c5950fe691b4.png)

hi, do you have the example of data output? because i'm kind of confuse.

**Comment by angellee177** [comment]
> It may help someone.
> 
> With Builder
> 
> ```
> public function index(Builder $builder)
>     {
>         $html = $builder->columns($this->checklog->getCollumns())
>                         ->parameters([
>                             'paging' => true,
>                             'searching' => false,
>                             'info' => false,
>                             'searchDelay' => '500',
>                             'language' => [
>                             'url' => asset("modules/core/js/vendor/datatables/".locale().".json")
>                                 ],
>                             'order'=> [[0, 'desc'],[4, 'asc']],
>                             'rowGroup'=> [
>                                 'dataSrc' => ['created_at', 'point_id'],
>                             ],
>                         ])
>                         ->ajax([
>                             'url' => route('api.admin.patrol.checklogs.datatables'),
>                             'type' => 'POST',
>                         ]);
>         $base = $this->base;
>         
>         return view('patrol::admin.checklogs.index', compact('base', 'html'));
>     }
> ```
> 
> Ajax controller :
> 
> ```
> public function datatables(Request $request) 
> {
>  return DataTables::of(CheckLog::query()->with(['point', 'patrolStatus', 'equipment.line.hall', 'files'])) 
>                     ->editColumn('created_at', function(CheckLog $checklog){
>                         return $checklog->created_at->tz(setting('base::timezone'))->format(setting('base::datetimeformat'));
>                     }) 
>                     ->editColumn('point_id', function(CheckLog $checklog){
>                         if (!$checklog->point){
>                             $d = Point::withTrashed()->find($checklog->point_id);
>                             return $d->title;
>                         }
>                         return $checklog->point->title;
>                     }) 
>                     ->editColumn('user_id', function(CheckLog $checklog){
>                         if (is_object($checklog->user)) {
>                             return $checklog->user->first_name.' '.$checklog->user->last_name;
>                         }
>                     }) 
>                     ->editColumn('photo', 'patrol::admin.checklogs.columns.image')
>                     ->editColumn('action', function(CheckLog $checklog){
>                         return view('patrol::admin.checklogs.columns.action', compact('checklog'));
>                     })
>                     ->rawColumns(['description', 'photo', 'action'])
>                     ->filter(function ($query) use ($request) {
>                         if ($request->get('planrepair')) {
>                            $query->where('plan_repair', '=', 1);
>                         }
>                         if ($name = $request->get('check')) {
>                             $query->where('check_id', '=', $name);
>                         }
>                         if ($name = $request->get('status')) {
>                             $query->where('patrol_status_id', '=', $name);
>                         }
>                         if ($name = $request->get('hall')) {
>                             $query->whereHas('equipment.line.hall', function ($q) use ($name) {
>                                 $q->where('equipment_name', 'like', "%$name%");
>                             });
>                         }
>                         if ($name = $request->get('line')) {
>                             $query->whereHas('equipment.line', function ($q) use ($name) {
>                                 $q->where('equipment_name', '=', $name);
>                             });
>                         }
>                         if ($name = $request->get('equipment')) {
>                             $query->whereHas('equipment', function ($q) use ($name) {
>                                 $q->where('equipment_name', 'like', "%$name%");
>                             });
>                         }
>                         if ($name = $request->get('point')) {
>                                 $query->where('point_id', '=', $name);
>                         }
>                         if ($name = $request->get('user')) {
>                             $query->whereHas('user', function ($q) use ($name) {
>                                 $sql = "CONCAT(users.first_name,' ',users.last_name)  like ?";
>                                 $q->whereRaw($sql, ["%{$name}%"]);
>                             });
>                         }
>                     })
>                     ->toJson();  
> }
> ```
> 
> blade template
> 
> ```
> @extends('layouts.master')
> 
> @if (isset($base['filters']))
> @section('styles')
> <link rel="stylesheet" href="{!! Module::asset('base:css/select2.css') !!}" />
> <link rel="stylesheet" href="{!! Module::asset('base:css/select2-bootstrap-dick.css') !!}"/>
> <link rel="stylesheet" href="https://cdn.datatables.net/rowgroup/1.1.0/css/rowGroup.dataTables.min.css"/>
> @endsection
> 
> @section('content-header')
>     <h1>
>         {{ trans('patrol::checklogs.title.checklogs') }}
>     </h1>
>     <ol class="breadcrumb">
>         <li><a href="{{ route('dashboard.index') }}"><i class="fas fa-tachometer-alt"></i> {{ trans('core::core.breadcrumb.home') }}</a></li>
>         <li class="active">{{ trans('patrol::checklogs.title.checklogs') }}</li>
>     </ol>
> @stop
> 
> @section('content')
>     <div class="row">
>         <div class="col-xs-12">
>             <div class="row">
>                 <div class="btn-group pull-right" style="margin: 0 15px 15px 0;">
>                   
>                 </div>
>             </div>
>             <div class="box box-primary">
>                 <div class="box-header">
>                 </div>
>                 
>                 <div class="box-body">
>                     @if (isset($base['filters']))
>                         @include('base::inc.filter')
>                     @endif
>                     <div class="table-responsive">
>                         {!! $html->table(['class'=>'table table-bordered table-hover dataTable']) !!}
>                         
>                     </div>
>                 </div>
>                 
>             </div>
>         </div>
>     </div>
>     @include('core::partials.delete-modal')
> 
>     <div id="photoModal" class="modal fade" role="dialog">
>         <div class="modal-dialog">
>             <div class="modal-content">
>                 <div class="modal-body showimage">
>                    
>                 </div>
>                 <div class="modal-footer">
>                     <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
>                 </div>
>             </div>
>         </div>
>     </div>
> @stop
> 
> @section('footer')
>     <a data-toggle="modal" data-target="#keyboardShortcutsModal"><i class="fa fa-keyboard-o"></i></a> &nbsp;
> @stop
> @section('shortcuts')
>     <dl class="dl-horizontal">
>         <dt><code>c</code></dt>
>         <dd>{{ trans('patrol::checklogs.title.create checklog') }}</dd>
>     </dl>
> @stop
> 
> @push('js-stack')
> <script src="https://nightly.datatables.net/rowgroup/js/dataTables.rowGroup.min.js" type="text/javascript"></script>
>     {!! $html->scripts() !!}
> @endpush
> ```
> 
> Result :
> ![datatables-groupBy](https://user-images.githubusercontent.com/19667328/57753517-a428af80-76ec-11e9-8d18-c5950fe691b4.png)

hi, do you have the example of data output, because i'm kind of confuse when read your code.
