### ISSUE TITLE
search for alias not working

### ISSUE THREAD

**Issue by Raman16** [yajra/laravel-datatables#179]
Hai Yajra,search is not working for my alias names,please provide me a possible solution,i am new to datatables
my js

//Products datatables
$(function() {
    
     $('#admin-products-table').DataTable({
      processing: true,
        serverSide: true,
        ajax: '../admin/products/products-list',
        
        columns: [
               { data: 'id', name: 'products.id'},
               { data: 'cname', name: 'cname' },
               { data: 'ptypename', name: 'ptypename' },
               { data: 'name', name: 'products.name' },
               { data: 'price', name: 'products.price' },
               { data: 'description', name: 'products.description' },
               {data: 'action1', name: 'action1', orderable: false, searchable: false},
              
        ]
    });
    
});

my query is

 $productsList = DB::table('products') ->leftJoin('product_types', 'products.product_type_id', '=', 'product_types.id')
                                                           ->leftJoin('company', 'company.id', '=', 'products.company_id')
                                                           ->select(['products.id', 'products.name', 'products.price', 'products.description','products.active', 'product_types.name as ptypename','company.name as cname'])
                                                                    ->where('company.active','=',1);
                                                                return Datatables::of($productsList)

using DataTables 1.10.7 version....ofcourse sorting is working fine......

I have read #66 -->need to override the default global search on that column by using filterColumn function...how to do this..i dont want to search clicking on some button just need search on key type..pls give me the solution...

**Comment by yajra** [comment]
Just use the actual field name like `{ data: 'ptypename', name: 'product_types.name' }`.

**Comment by Raman16** [comment]
Thanks a lot for your reply,it fixed my issue.....
