### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded, when use uuid field 

### ISSUE THREAD

**Issue by bpartner** [yajra/laravel-datatables#1793]
### Summary of problem or feature request

Log:
InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in D:\OpenServer\domains\finkpi.local\vendor\laravel\framework\src\Illuminate\Http\JsonResponse.php:75 Stack trace: #0 D:\OpenServer\domains\finkpi.local\vendor\symfony\http-foundation\JsonResponse.php(50): Illuminate\Http\JsonResponse->setData(Array) #1 
..........

Ajax response
{"draw":1,"recordsTotal":1,"recordsFiltered":0,"data":[],"error":"Exception Message:\n\nMalformed UTF-8 characters, possibly incorrectly encoded"}
------------------------
id & user_id is BINARY, 

"id" => b"\x11Þü╩?¾$Éº[\x00 \x05(!>"
"user_id" => b"\x11Þü┼9¿ÃÈ¼\x01\x00 \x05(!>"

### Code snippet of problem

        $auth_user_id = Auth::user()->uuid_text;
        $models = Motivation::withUuid($auth_user_id,'user_id');
        $datatables = DataTables::eloquent($models)
                         ->setTransformer(new MotivationTransformer)
                         ->make();

Transformer

        return [
            'id' => $models->uuid_text,
            'name' => $models->name,
            'active' => $models->active ? '<span class="label bg-success-300" data-i18n="page.models.mm_table.active">Active</span>':'<span class="label bg-danger-300" data-i18n="page.models.mm_table.pending">Pending</span>',
            'created_at' => Carbon::parse($models->created_at)->format('d-m-Y'),
            'actions' =>
                '<button class="edit btn text-info-600 btn-flat btn-icon" data-id="'.$models->uuid_text.'">
                       <i class="icon-database-edit2"></i></button>
                 <button class="delete btn text-warning-600 btn-flat btn-icon" data-id=" '.$models->uuid_text.'">
                       <i class="icon-database-remove"></i></button>'
        ];

### System details

- Windows 10
- PHP 7.2
- Laravel 5.6
- Laravel-Datatables 8

Used https://github.com/spatie/laravel-binary-uuid

**Comment by bpartner** [comment]
Problem in method render in abstract class DataTableAbstract,
when the debugging mode is on 

protected function render(array $data)
    {
        $output = $this->attachAppends([
            'draw'            => (int) $this->request->input('draw'),
            'recordsTotal'    => $this->totalRecords,
            'recordsFiltered' => $this->filteredRecords,
            'data'            => $data,
        ]);

        if ($this->config->isDebugging()) {
            $output = $this->showDebugger($output);
        }
        return new JsonResponse(
            $output,
            200,
            $this->config->get('datatables.json.header', []),
            $this->config->get('datatables.json.options', 0)
        );
    }

**if ($this->config->isDebugging()) {
            $output = $this->showDebugger($output);
   }**

on production no problem

**Comment by drsdre** [comment]
I've ran into the same issue. Added a PR which UTF-8 encodes the debug output to prevent this issue.

**Comment by matthijs** [comment]
The PR is merged, but now I am getting the following error (first 10 lines of the stacktrace):
```php
[2019-06-09 11:49:52] testing.ERROR: ErrorException: utf8_encode() expects parameter 1 to be string, object given in /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php:730
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'utf8_encode() e...', '/home/matthijs/...', 730, Array)
#1 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(730): utf8_encode(Object(DateTime))
#2 [internal function]: Yajra\DataTables\QueryDataTable->Yajra\DataTables\{closure}(Object(DateTime), 2)
#3 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(731): array_walk_recursive(Array, Object(Closure))
#4 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php(744): Yajra\DataTables\QueryDataTable->showDebugger(Array)
#5 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(104): Yajra\DataTables\DataTableAbstract->render(Array)
#6 /home/matthijs/Projects/frontend/app/Http/Controllers/InvestmentportfolioController.php(102): Yajra\DataTables\QueryDataTable->make()
#7 [internal function]: App\Http\Controllers\InvestmentportfolioController->index(Object(Illuminate\Http\Request))
#8 /home/matthijs/Projects/frontend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /home/matthijs/Projects/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array)
#10 /home/matthijs/Projects/frontend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\InvestmentportfolioController), 'index')
```

**Comment by matthijs** [comment]
To be honest, this is very hard to fix. There is no way to reliably detect binary data.

In my opinion the best way to handle this, is to add an option which disables fetching of the querylog and add a warning that the query log is disabled (by the user).

Encoding the data with utf8_encode is not an option, I already described that here: https://github.com/yajra/laravel-datatables/pull/2088#issuecomment-500514459

**Comment by jmichaelterenin** [comment]
> The PR is merged, but now I am getting the following error (first 10 lines of the stacktrace):
> 
> ```
> [2019-06-09 11:49:52] testing.ERROR: ErrorException: utf8_encode() expects parameter 1 to be string, object given in /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php:730
> Stack trace:
> #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'utf8_encode() e...', '/home/matthijs/...', 730, Array)
> #1 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(730): utf8_encode(Object(DateTime))
> #2 [internal function]: Yajra\DataTables\QueryDataTable->Yajra\DataTables\{closure}(Object(DateTime), 2)
> #3 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(731): array_walk_recursive(Array, Object(Closure))
> #4 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php(744): Yajra\DataTables\QueryDataTable->showDebugger(Array)
> #5 /home/matthijs/Projects/frontend/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(104): Yajra\DataTables\DataTableAbstract->render(Array)
> #6 /home/matthijs/Projects/frontend/app/Http/Controllers/InvestmentportfolioController.php(102): Yajra\DataTables\QueryDataTable->make()
> #7 [internal function]: App\Http\Controllers\InvestmentportfolioController->index(Object(Illuminate\Http\Request))
> #8 /home/matthijs/Projects/frontend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
> #9 /home/matthijs/Projects/frontend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('index', Array)
> #10 /home/matthijs/Projects/frontend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\InvestmentportfolioController), 'index')
> ```

I just upgraded from 8.9 to 9.7.1 (for Laravel upgrade from 5.7 to 5.8) and I am getting this error, can you please explain how to resolve?

**Comment by kamleshwebtech** [comment]
> Problem in method render in abstract class DataTableAbstract,
> when the debugging mode is on
> 
> ```
> protected function render(array $data)
>     {
>         $output = $this->attachAppends([
>             'draw'            => (int) $this->request->input('draw'),
>             'recordsTotal'    => $this->totalRecords,
>             'recordsFiltered' => $this->filteredRecords,
>             'data'            => $data,
>         ]);
>         if ($this->config->isDebugging()) {
>             $output = $this->showDebugger($output);
>         }
>         return new JsonResponse(
>             $output,
>             200,
>             $this->config->get('datatables.json.header', []),
>             $this->config->get('datatables.json.options', 0)
>         );
>     }
> ```
> 
> **if ($this->config->isDebugging()) { $output = $this->showDebugger($output); }**
> 
> on production no problem

In Production mode - it returns error { "message": "Server Error" } in ajax response instead of "Malformed UTF-8 characters, possibly incorrectly encoded" error. Any other suggestion, please share. Thanks.

**Comment by yajra** [comment]
@kamleshwebtech Make sure you don't have any binary on your result set. I usually encounter this error when having a blob field in oracle. My solution was to include a select statement and exclude the binary field. Also, you should make the binary columns hidden so that it will not return when the model is converted to array response.

**Comment by desenvolvedorindie** [comment]
I had the some problem with normal columns, I was using substr in returned value, to resolve I replaced to mb_substr
