### ISSUE TITLE
Limit not working on eloquent basic

### ISSUE THREAD

**Issue by masbenx** [yajra/laravel-datatables#1794]
### Summary of problem or feature request

Hi.
I try to use this plugin with basic eloquent, but my ajax result always show all the data without limiting by the request.

I have search and try the solution, but I have really no idea. 

Thanks in advance

### Code snippet of problem

```php
public function ajaxList(Request $request) {
    $data = Province::select(['id', 'name', 'material_price_multiplier']);

    return Datatables::of($data)
        ->addColumn('action', function ($data) {
            return '<a href="'.url('province/update', [$data->id]).'" class="fa fa-edit"></a>';
        })
        ->make(true);
}
```

### System details

- Operating System MacOS High Sierra
- PHP Version 7.1.8
- Laravel Version 5.6
- Laravel-Datatables Version 8.7.1

**Comment by pujianto** [comment]
Hi,
Kindly take a look at Utilities/Request.php, there is a function named isPaginationable(). To apply limit on the database side, just make sure there is start & length variable in your request. 

### Example 
```
public function ajaxList(Request $request) {
    $data = Province::select(['id', 'name', 'material_price_multiplier']);
    if (!request()->input('length')) {
        request()->instance()->merge(['length' => 10]);
    }
    if (!request()->input('start')) {
        request()->instance()->merge(['start' => 0]);
    }
    return Datatables::of($data)
        ->addColumn('action', function ($data) {
            return '<a href="'.url('province/update', [$data->id]).'" class="fa fa-edit"></a>';
        })
        ->make(true);
}

**Comment by swati-clarion** [comment]
Thanks pujianto!

Above solution worked for me. But we are already get length and start as query params  for ajax request. So , to override them,

We can directly use this code:
   
        request()->instance()->merge(['length' => 1]);  //limit and length should be same 
        request()->instance()->merge(['start' => 0]);
    
Then $query->limit(1) gets only one result.
