### ISSUE TITLE
Column name updated automatically when filtering related column with same column name

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables#1795]
### Summary of problem

I have a User datatable where I also display the Role name assigned to the user, for ACL I use Laratrust.

key thing to note is user `name` and role `name` both are displayed in the table ans we have column filter setup on the same.

The problem is when I filter roles name column all names in my user.name column gets updated to filtered role name.

### Code snippet of problem

Following code is from `class UsersDataTable extends DataTable {`
Note that I use eager loading `->with('roles')` on related roles table.

```php

public function query(User $model)
	{
		$columns = [
			'users.id', 'users.name', 'users.email', 'users.verified', 'users.active', 'users.created_at',
			'users.updated_at',
		];
		$scope = $model->newQuery()->with('roles')->select($columns);
		if(!Laratrust::hasRole('superadmin')){
			return $scope->where('current_team_id', Auth::user()->currentTeam->id);
		}
		return $scope;
	}

```
and to show the roles name column 

```php
->editColumn('roles.name', function ($user) {
				return $user->roles->pluck('name')->implode(', ');
			})
```
### System details

- Operating System Ubuntu 16.04
- PHP Version 1.7
- Laravel Version 5.6
- Laravel-Datatables Version 8.7

### Screenshots
![image](https://user-images.githubusercontent.com/11293052/42448575-31b2dc54-839b-11e8-8e06-33efdbe7dea1.png)

After applying filter see the Name column
![image](https://user-images.githubusercontent.com/11293052/42448584-3578b28c-839b-11e8-89fd-1d3a5a6aedce.png)

**Comment by karmendra** [comment]
I added a filter on my roles.name column as following, and it seems to work now. Is there any better solution than this?

```
		->filterColumn('roles.name', function ($query, $keyword) {
			$query->whereHas('roles', function ($query) use ($keyword) {
				$query->where('name',$keyword);
			});
		})
```

**Comment by pr4xx** [comment]
I am experiencing the exact same problem. My master table `books` has a `title` column. The related table `categories` also has a column called `title`. As soon as I click to order the category column, all columns with the same name in the books table get overriden (even `id`).
I set up a new project with fresh dependencies. The same code works in an older version (Laravel 5.6, Laravel-Datatables 8.9.2).

**Comment by pr4xx** [comment]
Update: its fixed if I do this:

```php
return datatables()->eloquent(Book::select([
            'books.*',
        ])->with($with))->toJson();
```

**Comment by saskysamonte** [comment]
https://github.com/yajra/laravel-datatables/issues/1231
