### ISSUE TITLE
How are errors in the AJAX call handled?

### ISSUE THREAD

**Issue by judgej** [yajra/laravel-datatables#180]
The front end DataTables makes a call to the back end, and this package is able to provide the required data from an Eloquent query or other sources. That's fine when the query works.

What happens if the query or supporting code around it generates an exception? Is there a method built into this package that can or should be used to return "sorry an error occurred" to DataTables, presumably as a JSON result?

Or does this have to be done outside the scope of this package?

**Comment by yajra** [comment]
@judgej, there is no custom error handler for ajax response atm. When there is an error like on your query, normal laravel error exception will be thrown.

> Or does this have to be done outside the scope of this package?

Yes. But maybe we can add some error handler in a future releases.

**Comment by judgej** [comment]
I found this in SO:

http://stackoverflow.com/questions/15447155/datatable-error-for-empty-ajax-response

It suggests that this is returned in the event of some kind of server error:

~~~php
return '{
    "sEcho": 1,
    "iTotalRecords": "0",
    "iTotalDisplayRecords": "0",
    "aaData": []
}';
~~~

This produces a "no rows" message on the front end. Alternatively:

~~~php
return json_encode([
    "sEcho" => 1,
    "iTotalRecords" => "0",
    "iTotalDisplayRecords" => "0",
    "aaData" => []
]);
~~~

On the server, catching exceptions is fine, and the application's responsibility anyway. It was just knowing what to return that was the problem.

**Comment by judgej** [comment]
Just being able to return something like this would be great (maybe you can - I'll experiment):

    Datatables::empty()->make(true);

I'll do a bit more digging to see if a message can be passed too, without having to customise the front end to catch that message.

**Comment by judgej** [comment]
A message can be returned to the datatable like this:

~~~php
return json_encode([
    "error" => "Some sort of error occurred..."
    "sEcho" => 1,
    "iTotalRecords" => 0,
    "iTotalDisplayRecords" => 0,
    "aaData" => []
]);
~~~

You still need to provide the empty record counts and data otherwise the spinner doesn't stop. The message modal dialogue is prefixed like this:

> DataTables warning: table id=your-table-id - Some sort of error occurred...

But that can be fixed using the [fnServerData](http://datatables.net/usage/callbacks#fnServerData) callback on the client side. That is, of course, out of scope for this package, but everything is in-scope for us developers - so I'm posting this to help awareness.

**Comment by judgej** [comment]
Not sure if you want to close this? It depends on whether you feel there are any development actions on this.

I'm happy that I have a way of handling server-side exceptions for my admin pages, without generating AJAX errors. I'm happy that there are more advanced techniques that can be followed up if this was to go in from of end users (perhaps with messages appearing in a bootstrap dialog). So my immediate question has an answer.

**Comment by yajra** [comment]
Will keep this open and try to dig on this too on my free time. BTW, here is my snippet for expired sessions error handling that you may want? https://gist.github.com/yajra/ddb9a28dcc120d1a5d2c

**Comment by judgej** [comment]
I never even thought about the middleware - I was just thinking about the controller catching its own exceptions. There are errors that can happen even before execution gets to the controller. Good point.

**Comment by yajra** [comment]
@judgej, I think ajax error handling will highly depends on user requirements and thus I think this should be implemented on per project basis as required. Thanks!
