### ISSUE TITLE
Search return empty records

### ISSUE THREAD

**Issue by nubinter** [yajra/laravel-datatables#1802]
### Summary of problem or feature request

Hi I am using laravel-datatables-fractal to transform data for my datatable.
My problem is everytime I search for data will return empty records / no match found.
But if I am not using transformer the searching is fine.

### Code snippet of problem

Here is my controller

```
public function konsep_riwayat_json()
	{
		$daftar = RJft::where('status', 'konsep')->get();
		return DataTables::of($daftar)
			->setTransformer(new DaftarJftTransformers)
			->toJson();
	}
```

And here is the transformer

```
    public function transform(RJft $riwayat)
    {
		return [
				'id_rjft'      => (int) $riwayat['id_rjft'],
				'identitas'   => $riwayat['nama_pns'].' / '.$riwayat['nip'],
				'gol' => $riwayat['pangkat'].' / '.$riwayat['gol'].' / '.$riwayat['tmt_gol'] ,
				'jabatan_baru' => $riwayat['nama_jft'].' '.$riwayat['nama_jenjang_baru'].' / '.$riwayat['tmt_jabatan'],
				'ak' => $riwayat['angka_kredit'].'( '.$riwayat['terbilang'].' )',
				'no_sk' => $riwayat['no_sk'].' '.$riwayat['tanggal_sk'],
				'unor' => $riwayat['unor'],
				'jenis' => $riwayat['jenis'],
				'posisi' => Posisi::find($riwayat['posisi'])->nama_posisi.' '.$riwayat['keterangan'],
		];
    }
```
### System details

- Operating System Centos 6
- PHP Version 7
- Laravel Version 5.6
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
Thanks for reporting, haven't used fractal much. Will try to check this when I got the chance. If you can trace the issue, please do not hesitate to submit a PR.
