### ISSUE TITLE
Laravel 5.6.* Not Installing via Composer

### ISSUE THREAD

**Issue by tahir-grappetite** [yajra/laravel-datatables#1803]
### System details

- Operating System
- PHP Version 7.2.*
- Laravel Version 5.6.*
- Laravel-Datatables Version 8.0
here is the screenshot http://prntscr.com/k8uydr

**Comment by yajra** [comment]
That's odd, I am using 5.6 and it's working well for me. Maybe try deleting the vendor folder and try again? Also try removing the lock file too. Thanks!

**Comment by tahir-grappetite** [comment]
I have solved the issue. I tried it initially with 
`"yajra/laravel-datatables-oracle": "^8.0"`
but it was not working

Then I have changed the "^" to "~" its worked like this
`"yajra/laravel-datatables-oracle": "~8.0"`

Note: This is in composer.json file.

**Comment by yajra** [comment]
Oh yes, I think 5.6 support was added as a minor bump but it's weird why is not working on `^8.0` constraint. Anyways, glad you figured it out. Thanks!
