### ISSUE TITLE
DATATABLES_ERROR shouldn't be by default null

### ISSUE THREAD

**Issue by zeyad82** [yajra/laravel-datatables#1805]
### Summary of problem or feature request

DATATABLES_ERROR shouldn't be by default null, specially if APP_DEBUG is set to false.

The queries where explicit on production and the APP_DEBUG was set to false even though.
It doesn't make sense to make the default is to show everything, at least with a simple check if APP_DEBUG is set to false, `throw` can be set instead.

**Comment by yajra** [comment]
I think a similar concern was raised before but I haven't had the chance to check it. Can you please send a PR on your proposed solution? Thanks!

**Comment by yajra** [comment]
PR merged and released on v8.9.1 🚀 thanks and sorry for the delay. 🍻
