### ISSUE TITLE
Custom sort function for column with data as range not working

### ISSUE THREAD

**Issue by swati-clarion** [yajra/laravel-datatables#1806]
I am using yajrabox datatables with laravel 5.5. I have a page number column which has data as range like 1-10, 10-14, .... 1071-1888 etc. this page number column is added using addColumn in query. The usual sorting for this column was not working. So I added a custom jquery function for sorting. Still the sorting for this range column donot work. I have tried multiple solutions but nothing works.

Here is my code jquery datatable code:

    var oTable = $('.datatable').DataTable({			
		dom: "<'row'<'col-sm-9'l><'col-sm-3'f>>" +
		"<'row'<'col-sm-12'tr>>" +
		"<'row'<'col-sm-5'i><'col-sm-7'p>>",
		searching: false,
		processing: true,
		serverSide: true,
		ordering: true,
		stateSave: true,
		pageLength: 100,
		deferRender: true,			
		contentType: "application/json; charset=utf-8",
		order: [[ 3, "asc" ]], 
		ajax: {
			 url: '{{ route('legal/custom-filter-data') }}',
			data: function (d) {			
				d.srch_type     = $('#instrument_type').val();
				d.srch_date     = $('#datepicker').val();
				d.srch_qtr      = $('#quater').val();				
			} 
		},	   
		columns: [ 		
			{
				'data': 'reception_number',
				 'render': function(data, type, row, meta) {
					if (type === 'display'){

						data = "<a alt='View Detail' title='View Detail'><strong>" + data + "</strong></a>";
					}
					return data;
				 }
			}, 
			{data: 'grantor', name: 'grantor'},	
			{data: 'grantee', name: 'grantee'},				
			{data: 'instrument_type', name: 'instrument_type'},	
			{data: 'book', name: 'book'},
			{data: 'page',  name: 'page', type: 'page-range'},          
			},											
		]
	});	

Here is the custom jquery function for sorting:
//Custom function for page range column sorting
        
     jQuery.fn.dataTableExt.oSort['page-range-asc'] = function(x,y)  {
			x = x.split("-");
			y = y.split("-");
			x0 = parseInt(x[0]);
			y0 = parseInt(y[0]);
			return (x0 > y0) ? -1 : ((x0 < y0) ? 1 : 0);
    };
    jQuery.fn.dataTableExt.oSort['page-range-desc'] = function(x,y) {
			x = x.split("-");
			y = y.split("-");
			x0 = parseInt(x[0]);
			y0 = parseInt(y[0]);
			return (x0 < y0) ? -1 : ((x0 > y0) ? 1 : 0);
    };

- Operating System - Windows
- PHP Version 7
- Laravel version 5.5
- Laravel-Datatables Version 8.0

**Comment by swati-clarion** [comment]
I got to know sorting dont work with addColumn. Sorted it using orderColumn.

**Comment by yajra** [comment]
I think you need to implement the sorting on the server side too specifically on the QUERY LEVEL sorting. See https://yajrabox.com/docs/laravel-datatables/master/order-column for some ref.

**Comment by lherreranetlink** [comment]
@yajra your example in this point (orderColumn function) is non-understandable, also we'd like to pass some kind of closure to this method and maybe it's possible but you never documented that in your documentation.
