### ISSUE TITLE
DataTables warning: table id=student_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by Kertex17** [yajra/laravel-datatables#1807]
i got this problem and the data was not showing and the table is broken, and please help me T_T

`<body>
	@include('page.navbar')
		<table id="student_table" class="table table-bordered ">
		  <thead>
		    <tr>
		      <th scope="col">ID</th>
		      <th scope="col">First Name</th>
		      <th scope="col">Last Name</th>
		      <th scope="col">Age</th>
		      <th scope="col">Address</th>
		      <th scope="col">Grade Level</th>
		    </tr>
		  </thead>
		</table> 

		<script type="text/javascript">
			$(document).ready(function() {
				$('#student_table').DataTable({
					"processing" 	: true,
					"serverSide"	: true,
					"ajax"			: "{{route('ajaxdata.getdata')}}",
					"columns":[
						{"data": "id"},
						{"data": "first_name"},
						{"data": "last_name"},
						{"data": "Age"},
						{"data": "Address"},
						{"data": "Grade_Level"}
					]	
				});
			})
		</script>
</body>`

this is my view page with the jquery

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;
use Datatables;

class AjaxController extends Controller
{
    function index()
    {
    	
    	return view('student.ajaxdata');
    }

    function getdata()
    {

    	$students = Student::select('id', 'first_name', 'last_name', 'Age', 'Address', 'Grade_Level');
    	return Datatables::of($students)->make(true);
    }
}
`

and my controller

i dont know why im getting this error and its consuming meeeee!

**Comment by yajra** [comment]
Have you tried inspecting the ajax request to get a hint of what was causing the issue? I suspect there might be an issue on your query? Maybe an invalid field?
