### ISSUE TITLE
Eager loaded relationship breaks Datatables as Service

### ISSUE THREAD

**Issue by oranges13** [yajra/laravel-datatables#1808]
I am implementing the datatables as a service. Everything works until I include two columns which are eager loaded.

```php
class RegistrationDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @return \Yajra\Datatables\Engines\BaseEngine
     */
    public function ajax() {
        return $this->datatables
            ->eloquent($this->query())->make(true);
    }
    public function query()
    {
        $query = Registration::select('registrations.*')->with(['product','reg_type']);

        return $this->applyScopes($query);
    }
    public function html()
    {
        return $this->builder()
        ->columns($this->getColumns())
        ->ajax('')
        ->parameters([
            'dom'     => 'Bfrtip',
            // 'order'   => [[0, 'asc']],
            'select' => 'true',
            'buttons' => [
                'excel',
                'print',
                'reset',
                'reload',
            ]);
    }
    protected function getColumns()
    {
        return [
            'id' => ['visible' => false, 'exportable' => true],
            // When the following two rows are included, I receive a 404 or 401 error in my ajax
            "product.name" => ['data' => 'product', 'name' => 'product.name'],
            "reg_type.type" => ['data' => 'reg_type', 'name' => 'regType.name'],
            "alcohol",
            "status",
            "reg_date",
            "renew_date",
            'created_by' => ['visible' => false, 'exportable' => true],
            'edited_by' => ['visible' => false, 'exportable' => true],
        ];
    }
}
````
Suggestions would be appreciated

yajra/laravel-datatables-buttons v 2.0.0
"yajra/laravel-datatables-oracle": "7.*"

**Comment by yajra** [comment]
I think the issue here is on the reg type relation. I think it should match the relation function name instead of the table name?

Try changing:
```
'name' => 'regType.name'
```
to

```
'name' => 'reg_type.name'
```

Also, what does the error logs states?

**Comment by oranges13** [comment]
I've tried both. I settled on regType sure to other comments but I've given up on the buttons plugin all together.

It was also behaving oddly with `ajax` versus `minifiedAjax` which causes either a 401 on `artisan serve` or a 404 on production hardware.

I got some combination to work finally, but sorting doesn't work with minifiedAjax and exports don't work without it due to the length of the query string. I gave up on using the button plugin.

**Comment by yajra** [comment]
Sorry about that, it was a known issue of the package that it behaves strangely when using [artisan serve](https://github.com/yajra/laravel-datatables#php-artisan-serve-bug). And yes, it was indeed a issue for long query string. There is also a postAjax that you can use the avoid this issue.

**Comment by oranges13** [comment]
The 401 changed to a 404 on production hardware so that didn't fix it unfortunately. Due to laravel version, I don't believe I have the version with postAjax included. I'm on 5.4 using 7.0

Correct me if I'm wrong.
