### ISSUE TITLE
Search with "-" replace to "\\-"

### ISSUE THREAD

**Issue by dogrocker** [yajra/laravel-datatables#181]
Hello!, I've got a problem when I try to search with "-" it will replace with "\\-".

(This is about security right? But how can I handle these kind of data?)

My data is.

```
JF62E-0002682
```

This is json when datatable are searching. 

```
"search": {
"value": "JF62E\\-0002682",
"regex": "true"
}
```

-- Edit --
This problem only on 

multi-filter-select ref: http://datatables.yajrabox.com/eloquent/multi-filter-select

ref: https://github.com/yajra/laravel-datatables/blob/5f803548454491b1e1583442b294aed6ce066b27/src/yajra/Datatables/Engines/BaseEngine.php#L178

Thank you very much.

**Comment by yajra** [comment]
I think value was escape because of regex true? Can you try using regex false?

**Comment by dogrocker** [comment]
@yajra, OK. Now I change regex to false and it got the same.

```
"search": {
"value": "JF62E\\-0002682",
"regex": "false"
}
```

But I change.

```
var val = $.fn.dataTable.util.escapeRegex($(this).val());
```

to

```
var val = $(this).val();
```

and it work now.

Thanks.
