### ISSUE TITLE
v[7] -  Class 'Datatables' not found

### ISSUE THREAD

**Issue by hariskhan111** [yajra/laravel-datatables#1812]
I am using laravel 5.4 and php version is 5.6.

I am getting error "Class 'Datatables' not found". I am following standard procedure. I have installed datatable using composer by following command: 

composer require yajra/laravel-datatables-oracle:"~7.0"

I added these two lines in config->app file in service provider and aliases:

Yajra\DataTables\DataTablesServiceProvider::class,
'DataTables' => Yajra\DataTables\Facades\DataTables::class,

then publish package : 
php artisan vendor:publish --provider=Yajra\DataTables\DataTablesServiceProvider

I am using raw query here is my controller code : 
				 	function allvendor(){
	
$sql="my query";
$results=DB::table(DB::raw("($sql)"));
return Datatables::of($results)->make(true);
	}

- Operating System - windows
- PHP Version - 5.6
- Laravel Version - 5.4
- Laravel-Datatables Version -  7

**Comment by yajra** [comment]
You need to use `DataTables::of()`, notice the uppercase `T`. Thanks!

**Comment by hariskhan111** [comment]
I changed return DataTables::of($results)->make(true);  to return DataTables::of($results); but same error.

**Comment by hariskhan111** [comment]
I received error in alert (DataTables warning: table id=vendors - Ajax error. For more information about this error, please see http://datatables.net/tn/7). When I check in console it is giving me 500 internal error

**Comment by AbubakerxD59** [comment]
@hariskhan111 Bro, what was the solution to this query?
I've tried everything but the problem retains :(
