### ISSUE TITLE
View path for addcolumn in a laravel-modules hierarchy

### ISSUE THREAD

**Issue by pat-och** [yajra/laravel-datatables#1820]
### Summary of problem or feature request
Using NWirdart/Laravel-modules package, in a module context not under app folder, i'm stuck to implement the addcolumn with view like described below
https://yajrabox.com/docs/laravel-datatables/master/add-column#view

### Code snippet of problem

here my files hierarchy focus on views

```
app
....resources
............views
................foomodel
....................tables
........................foomodel-table-actions.blade.php
modules
.... mymodule
........resources
............views
................mymodelname
....................tables
........................mymodelname-table-actions.blade.php
```

here the ajax handler in my controller 

```
    /**
     * Populate the mymodelname datatable (Ajax handler).
     *
     * @return string
     */    
    public function publipostageTypeTable()
    {
        return DataTables::of($myModelName = $this->myModelName->all(['id', 'name']))
            ->addColumn('action', '?????i.tried.here.amazing.things.but.nothin.worked??????')
            ->rawColumns([
                'id',
                'name',
            ])
            ->toJson();
    }
```
**so, instead of my view, the text ?????i.tried.here.amazing.things.but.nothin.worked?????? is displayed in the column**

_I would point out that already perfectly work with some others foocontrollers, foomodels and their associated views in the classical app hierarchy, i introduce modules recently to organize the already big app_
	
	
### System details
windows 10 64bits
php 7.0.x
laravel 5.5.4
yajra/laravel-datatables-buttons": "^3.0
yajra/laravel-datatables-html": "^3.1
yajra/laravel-datatables-oracle": "~8.0

**Comment by yajra** [comment]
You need to use the module view namespace as path.

```php
->addColumn('action', 'module::path.to.view')
```
