### ISSUE TITLE
Smaller and greater than operations in filter row search.

### ISSUE THREAD

**Issue by mshd** [yajra/laravel-datatables#1821]
### Summary of problem or feature request
Maraming salamat, really appreciate your great plugin.
I would really like the possibility to advance the search for smaller than or greater than operations to simply type in the filter column box `<5` or `>10` or fetch an exact value with `=10`. Is there any way to achieve that?. I'm happy to contribute as well with a PR.

### System details

- Ubuntu 16.04
- PHP 7.2
- Laravel 5.6
- MySQL

**Comment by yajra** [comment]
You can use [filterColumn](https://yajrabox.com/docs/laravel-datatables/master/filter-column) for custom queries that you need. Thanks!
