### ISSUE TITLE
MySQL orderByNullsLast doesn't work for strings and just turns order for integers

### ISSUE THREAD

**Issue by mshd** [yajra/laravel-datatables#1822]
### Summary of problem or feature request

I'm using orderByNullsLast with the config setting  MySQL orderByNullsLast doesn't work for strings and for numbers and integers it will sort ascending like this 1,2,3,4,5,null,null,null, and descending like this null,null,nulll,5,4,3,2,1

Any idea idea how to fix that with MySQL?

### Code snippet of problem

config/DataTables.php
` 'nulls_last_sql' => '-%s %s',`

Controller.php
``` 
$return = Datatables::of(\DB::table($tablename));//nulls last
      foreach(...){
          $return = $return->orderColumn($name,$name."_int $1");
      }
      return $return->orderByNullsLast()->make(true);
```
-->

### System details

- Ubuntu 16.04
- PHP 7.2
- Laravel 5.6
- MySQL

**Comment by mshd** [comment]
I found a solution, would be great if you can add it in /src/QueryDataTable.php
```
    protected function getNullsLastSql($column, $direction)
    {
        if(config('database.default') == "mysql"){
          $sql = 'IF(ISNULL(%s),1,0),%s %s';
          return sprintf($sql, $column, $column, $direction);
        }
```

**Comment by yajra** [comment]
@mshd thanks! can you please submit a PR?
