### ISSUE TITLE
Order by encrypted datatable fields

### ISSUE THREAD

**Issue by nithinwilson** [yajra/laravel-datatables#1823]
### Summary of problem or feature request

How we will order a field which is encrypted by laravel encryption and stored in database

### System details

Ubuntu 14.04
PHP 7.2
Laravel 5.5
yajra/laravel-datatables-oracle": "~8.0

**Comment by yajra** [comment]
Maybe try using [orderColumn](https://yajrabox.com/docs/laravel-datatables/master/order-column)? You can also use https://yajrabox.com/docs/laravel-datatables/master/manual-order if it makes sense. Thanks!

**Comment by nw1923** [comment]
Manual Order - it is ordering by table field name. my data is encrypted and saving in the table. so ordering shows incorrect order

**Comment by yajra** [comment]
Oh, so you mean you need to decode the contents first before applying the sorting? If that's the case, you should write the decode process on the query level. If it's not possible on the query level. You can do the updates using **collection** with editColumn to decode the contents. However, note that collection has some performance overhead.
