### ISSUE TITLE
laravel 5.7 support

### ISSUE THREAD

**Issue by plindsay** [yajra/laravel-datatables#1824]
Hi there, is it possible to support Laravel 5.7?

**Comment by yajra** [comment]
I think 5.7 is not yet officially released? Anyways, sure will add initial support on master branch for 5.7.

**Comment by yajra** [comment]
Initial support added but it's not yet tested. Will try to check it when I got the chance. Please give feedbacks on how it works for you. Thanks!

**Comment by plindsay** [comment]
Great thanks :-) How is it best to test this with Laravel 5.7 via composer?

**Comment by yajra** [comment]
You can require it on composer using `dev-master` version and test the app as usual :)

**Comment by Rux77** [comment]
Laravel 5.7 has been officially released. 
Is it possible to support Laravel 5.7 on the official branch?

**Comment by hailwood** [comment]
@yajra the upgrade guide for 5.7 is out, reading through it, it appears there's nothing in there that would break with this package so testing is pretty good.

Could you please tag a new release?

**Comment by yajra** [comment]
@hailwood yes, Im in the process of testing Laravel 5.7 and updating my packages to support it. I started on my [oracle db](https://github.com/yajra/laravel-oci8) packages and going to review dataTables packages later today.

**Comment by yajra** [comment]
Support released on v8.8.0, thanks!

**Comment by Jimmy-JS** [comment]
hi, @yajra I can't use v8.8.0. even in my composer.json I directly use v.8.8.0 like this:
`"yajra/laravel-datatables-oracle": "8.8.0",`
I got this error
`The requested package yajra/laravel-datatables-oracle 8.8.0 exists as yajra/laravel-datatables-oracle[1.3.0, 4.0.10, 5.0.x-dev, 5.11.7, 6.0.x-dev, 7.0.x-dev, 8.0.x-dev, dev-L4, dev-L5-DT1.9, dev-master, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.5.0, v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.1.0, v2.2.0, v2.2.1, v2.2.2, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.1.0, v3.2.0, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.15.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2, v3.4.2.1, v3.4.3, v3.4.3.1, v3.4.3.2, v3.4.4, v3.4.5, v3.4.5.1, v3.4.6, v3.5.0, v3.5.1, v3.6.0, v3.6.1, v3.6.10, v3.6.11, v3.6.12, v3.6.13, v3.6.2, v3.6.3, v3.6.4, v3.6.5, v3.6.6, v3.6.7, v3.6.8, v3.6.9, v4.0.0, v4.0.1, v4.0.11, v4.0.12, v4.0.12.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.2, v4.1.2.1, v4.1.3, v4.1.3.1, v4.1.3.2, v4.1.4, v4.1.5, v4.1.5.1, v4.1.6, v4.2.0, v4.2.1, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v5.0.0, v5.0.0-beta, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.1.0, v5.1.1, v5.1.2, v5.10.0, v5.11.0, v5.11.1, v5.11.10, v5.11.11, v5.11.12, v5.11.13, v5.11.14, v5.11.2, v5.11.3, v5.11.4, v5.11.5, v5.11.6, v5.11.8, v5.11.9, v5.12.0, v5.12.1, v5.12.2, v5.12.3, v5.12.4, v5.12.5, v5.2.0, v5.2.1, v5.2.2, v5.3.0, v5.3.1, v5.3.2, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.2, v5.5.3, v5.5.4, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9, v5.6.0, v5.6.1, v5.7.0, v5.8.0, v5.8.1, v5.8.2, v5.8.3, v5.8.4, v5.8.5, v5.8.6, v5.9.0, v5.9.1, v5.9.2, v6.0.0, v6.0.0-RC1, v6.0.0-alpha, v6.0.0-beta, v6.1.0, v6.1.1, v6.1.2, v6.1.3, v6.10.0, v6.10.1, v6.11.0, v6.11.1, v6.11.2, v6.11.3, v6.11.4, v6.11.5, v6.11.6, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.15.2, v6.16.0, v6.16.1, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.19.0, v6.2.0, v6.2.1, v6.2.2, v6.2.3, v6.2.4, v6.20.0, v6.21.0, v6.21.1, v6.22.0, v6.22.1, v6.22.2, v6.22.3, v6.22.5, v6.22.6, v6.22.7, v6.22.8, v6.22.9, v6.23.0, v6.24.0, v6.24.1, v6.24.2, v6.24.3, v6.24.4, v6.25.0, v6.26.0, v6.27.0, v6.28.0, v6.28.1, v6.29.0, v6.29.1, v6.29.2, v6.29.3, v6.3.0, v6.3.1, v6.3.2, v6.4.0, v6.4.1, v6.4.2, v6.4.3, v6.4.4, v6.4.5, v6.5.0, v6.5.1, v6.6.0, v6.6.1, v6.7.0, v6.7.1, v6.7.2, v6.7.3, v6.8.0, v6.9.0, v6.9.1, v6.9.2, v6.9.3, v6.9.4, v7.0.0, v7.0.1, v7.0.2, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.1.4, v7.10.0, v7.10.1, v7.10.2, v7.2.0, v7.2.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2, v7.9.3, v7.9.4, v7.9.5, v7.9.6, v7.9.7, v7.9.8, v7.9.9, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.1.0, v8.1.1, v8.2.0, v8.3.0, v8.3.1, v8.3.2, v8.3.3, v8.4.0, v8.4.1, v8.4.2, v8.4.3, v8.4.4, v8.5.0, v8.5.1, v8.5.2, v8.6.0, v8.6.1, v8.7.0, v8.7.1] but these are rejected by your constraint.`

**Comment by mariapaulinar** [comment]
Not compatible with Laravel 5.7.9 :(

**Comment by hailwood** [comment]
@mariapaulinar the composer.json constraints should allow it, is there an actual issue stopping this?

**Comment by mariapaulinar** [comment]
Go to #1880, I've reported this problem right there.
