### ISSUE TITLE
Not working datatable render method for packages views

### ISSUE THREAD

**Issue by nyeyint** [yajra/laravel-datatables#1826]
Not working like that.
```
return $dataTable->render('packages::eloquent.index');
```
I'm using "nwidart/laravel-modules" laravel modules for modular structure.

laravel 5.6

**Comment by yajra** [comment]
Am using that package too and have tons of modules with dataTables so I'm sure that this is working with it. Just make sure you have the proper view namespace as registered on the module service provider.

**Comment by nyeyint** [comment]
Hi @yajra,

Thanks for your reply.I will double check that.

Thanks!
