### ISSUE TITLE
How-To Diacritics-neutralise in Datatable as a service Implementation

### ISSUE THREAD

**Issue by h2jose** [yajra/laravel-datatables#1827]
Can somebody explain me with a simple example how to implement Diacritics-neutralise in Datatable as a service Implementation. I couldn't find it from tutorials.

**Comment by yajra** [comment]
This is the first time I heard about Diacritics-neturalize but I think a plugin was already created for this. Maybe https://datatables.net/plug-ins/filtering/type-based/diacritics-neutralise is what you need?

**Comment by h2jose** [comment]
Hi, i am using it in spanish website, i use service implementation, but i did all about plug-ins ( diacritics-neutralise and accent-neutralise) but this not working , if i not use service implementation these work fine.

**Comment by Maixck** [comment]
The problem is that when the filtering is done server side, the plugin does nothing. And i'm not certain how does laravel-datatables implement searching from a query result. Is there a way to solve this?
