### ISSUE TITLE
Laravel datatables: hide url from javascript code to minimize my web app vulnerability

### ISSUE THREAD

**Issue by fatenfalfoul** [yajra/laravel-datatables#1828]
Good morning. 
I'm biginner on Laravel. I used Laravel Yajra library to process my database data. But when trying to show the web page's code the url is viewd clearly. However, this behaviour might not always be desirable when the first page of the table has already been preloaded in the HTML (which you might do to ensure accessibility or for performance reasons).
Can I use Datatables plugin without using a clear route in the ajax call??
Having, I tried to use a simple php file (on the public) but it deos not work correctly. 
Please I need your hel, and thanks a lot

**Comment by yajra** [comment]
I think what you need is post method on ajax call? See https://datatables.yajrabox.com/eloquent/post-column-search for some ref. Thanks!

**Comment by fatenfalfoul** [comment]
thanks for your reply :)

**Comment by lk77** [comment]
Hello,

the url will always be visible, not matter if post/get method is used,
you can always use the laravel signed route functionnality to generate temporary urls that will not work after some time. But if you are logged in and have a valid url, you can access it anyway.
