### ISSUE TITLE
Method Yajra\DataTables\EloquentDataTable::where does not exist.

### ISSUE THREAD

**Issue by jonathanx56** [yajra/laravel-datatables#1829]
Why am I getting this error???

Code:

`  $datatables =  app('datatables')->of($civil);

      // additional users.name search
      if ($nome = $datatables->request->get('nome')) {
          $datatables->where('civil.nome', 'like', "%$nome%");
      }`

In the previous version, it worked perfectly.

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
@jonathanx56 yes, this was removed on latest version. See https://yajrabox.com/docs/laravel-datatables/master/upgrade#removed for ref. Please use the query object instead of the dataTable instance.

**Comment by rebornishard** [comment]
sorry for comment in other issue @yajra ,
how to do advance filtering with new datatables : 
https://datatables.yajrabox.com/eloquent/advance-filter

**Comment by yajra** [comment]
@rebornishard thanks for pointing the old demo. This is how it should be done on the latest version:


## Users Query

```php
$users = User::select([
            DB::raw("CONCAT(users.id,'-',users.id) as id"),
            'users.name',
            'users.email',
            DB::raw('count(posts.user_id) AS count'),
            'users.created_at',
            'users.updated_at'
        ])->leftJoin('posts', 'posts.user_id', '=', 'users.id')
        ->groupBy('users.id');
```

## FROM

```php
        // having count search
        if ($post = $datatables->request->get('post')) {
            $datatables->having('count', $datatables->request->get('operator'), $post);
        }

        // additional users.name search
        if ($name = $datatables->request->get('name')) {
            $datatables->where('users.name', 'like', "$name%");
        }
```

## TO

```php
        // having count search
        if ($post = $datatables->request->get('post')) {
            $users->having('count', $datatables->request->get('operator'), $post);
        }

        // additional users.name search
        if ($name = $datatables->request->get('name')) {
            $users->where('users.name', 'like', "$name%");
        }
```

**Comment by rebornishard** [comment]
@yajra will u update in there, since many ppl still confused out there,

for temp i using 
https://yajrabox.com/docs/laravel-datatables/master/filter-column

thanks @yajra will implement this one

i want to ask something, when first load datatable it show 10 table,
it's limit 10 in query when requesting it ?

thanks a lot

**Comment by yajra** [comment]
Done on https://github.com/yajra/laravel-datatables-demo/pull/37. Thanks!
