### ISSUE TITLE
Filtering with Relationship

### ISSUE THREAD

**Issue by MatiasSW** [yajra/laravel-datatables#183]
I've noticed a similar question being asked before and while the usual suggestion points to using database.column in the data field, this doesnt seem to work for me. I can list the data just fine initially, its only when filtering that it seems to break down. 

I'm currently building my datatables with the following code (This is a short version)
```
$users = User::all()->with('ext');
$dt = Datatables::of($users)->make(true);
```

My JS looks a bit like this
```
	$(document).ready(function () {
		var dTable = $('#accountsList').DataTable({
			scrollY:        400,
			scrollCollapse: true,
			processing: true,
			serverSide: true,
			searching: true,
			lengthChange: true,
			deferRender: true,
			autoWidth: false,
			sorting: [],
			ajax: {
				'url': 'http://127.0.0.1/sfpr/public/users',
				'type': 'POST',
				'data':	function (d) {
					d._token = '{{ csrf_token() }}'
				}
			},
			columns: [
							{ 'data': 'options', 'name': 'options', 'searchable': 'false', 'sortable': 'false' },
							{ 'data': 'ext.displayname', 'name': 'ext.displayname', 'searchable': 'true', 'sortable': 'false' },
							{ 'data': 'userid', 'name': 'userid', 'searchable': 'true', 'sortable': 'true' },
							{ 'data': 'sex', 'name': 'sex', 'searchable': 'false', 'sortable': 'false' },
							{ 'data': 'group', 'name': 'group', 'searchable': 'false', 'sortable': 'false' },
						],			
		});	
				
	});
```
The error seems to be caused by the relationship not being loaded when filtering? As the query error doesnt show the 'ext' table being included in the query, although the ext.displayname field is being searched.

I know I am still a bit lost on how eager loading works, but if the intiial data load works I'd expect the same query to be used when searching?

I apologize if this has been answered before and I couldnt get my head right around it to understand the actual answer.

**Comment by yajra** [comment]
@MatiasSW, searching/sorting via eager loaded columns is not yet supported atm. You would need to use join statements for it to work or just use `'searchable': false, 'sortable': false`

**Comment by MatiasSW** [comment]
@yajra Ok, that settles I am still not clear on how eager loading works. Thanks a lot for your answer!
