### ISSUE TITLE
Serverside Export - Filename attachment cannot contain "/" characters

### ISSUE THREAD

**Issue by jay-shah-rushiinfotech** [yajra/laravel-datatables#1832]
### Summary of problem or feature request

When DataTable Calls were within Namespace 
Filename get generated by \ in old datatable 8.7.

After upgrading 8.8 exception thrown:
"The filename and the fallback cannot contain the "/" and "\" characters."

I use server-side export for datatable.
Before export Can filename remove special character and replace with "_" underscore ?
### System details

- Operating System - Ubuntu 16.04
- PHP Version - 7.2
- Laravel Version - 5.7
- Laravel-Datatables Version - 8.8

**Comment by yajra** [comment]
Not sure but this must be a limitation on Laravel Excel v3.0 since this is only the recent changes related to export. In this regard, I suggest you check https://github.com/Maatwebsite/Laravel-Excel to find a better solution.
