### ISSUE TITLE
BelongsTo returning null or 0 results in JS error

### ISSUE THREAD

**Issue by JurjenRoels** [yajra/laravel-datatables#1833]
I have used Infyom scaffolding to create tables, relations and datatables.

I have succesfully changed columns to lookup their value based upon their belongsTo in their respective model

For instance: 

'customer' => ['name' => 'customer_id', 'data' =>'customers.name'],

customer can be NULL or 0 and because of that datatable reports an error.

Could you give me some pointers on how to add a custom value like 'Not Set' is customer_id = NULL or 0

**Comment by yajra** [comment]
For nullable cases like this, the usual approach I do is via edit column or add column.

```php
->addColumn('customer_name', function ($model) {
  return $model->customer ? $model->customer->name : 'Not Set';
})

// columns
'customer' => ['name' => 'customer_id', 'data' =>'customer_name'],
```

**Comment by JurjenRoels** [comment]
Thank You.

Your example really helped me.
