### ISSUE TITLE
Comparison to freshbitsweb/laratables?

### ISSUE THREAD

**Issue by hailwood** [yajra/laravel-datatables#1835]
Hey @yajra,

https://github.com/freshbitsweb/laratables was just featured in Laravel News, which means people are going to be looking at it as an alternative.

It may be useful to write up a "comparison" section outlining how this package is different to how laratables functions :)

**Comment by yajra** [comment]
Will try but I can't promise :). 

Anyways, having a quick look on the package. It seems like it delegates all the custom searching and sorting onto the eloquent model which I think will make your model bloated? IMO, you will have more codes on your model that is only required for dataTables which I think should be extracted and implemented to own class and maybe via scope or implemented on the controller level (depends on your preference).

Also, do you really need to put the [extra data attributes](https://github.com/freshbitsweb/laratables#extra-data--datatables-attributes) in your model? What if you have different audience for your dataTables with same model but functions differently? I think it lacks the ability to provide a flexible solution for it? But I maybe wrong. 

Thanks for the heads up. I am following Laravel News but I think I missed that post.

**Comment by lk77** [comment]
Hello,

this package has only 17 stars, 39 commits and only 1 contributor,
it's not a mature package, perhaps in the future, but for now i don't think so.

i would not trust a package like that and put it in production.
