### ISSUE TITLE
CollectionDatatable throws an Exception when trying to sort an array type Datatable

### ISSUE THREAD

**Issue by trideout** [yajra/laravel-datatables#1839]
CollectionDatatable throws an Exception when trying to sort an array type Datatable

When returning an array type Datatable with `->make(false)` the getSorter method gets the wrong column names and throws an Exception.

```
$collection = collect([
['name' => 'item one', 'option' => 'foo'],
['name' => 'item two', 'option' => 'bar']
]); 

return (new CollectionDatatable($collection))->make(false);
```

Version Tested: Datatables 8.*

**Comment by cferrante** [comment]
Hello @trideout, I use the server side implementation, so I am not sure I could be of help. 

Perhaps if you post additional detail...maybe the Exception message?...perhaps someone else will recognize your issue.
