### ISSUE TITLE
Eloquent master details example

### ISSUE THREAD

**Issue by stumped101** [yajra/laravel-datatables#184]
Thanks for this example. I am trying to get it to work but I am getting undefined constant 'id' ..... error every time I run the following: <script id="details-template" type="text/x-handlebars-template">
        <table class="table details-table" id = "sup_{{id}}">
            <thead>
            <tr>
                <th>Id</th>
                <th>Company_name</th>
            </tr>
            </thead>
        </table>
</script>

Any ideas what might be causing this?

**Comment by yajra** [comment]
Not sure on this error. Try debugging using chrome dev tools or firebug. This is most probably a js issue.

**Comment by stumped101** [comment]
Thats now working - I used a file called details_template.blade.php. It should of course be details_template.php. A datatable within a datatable I like that.

Thanks for your help

**Comment by fanjavaid** [comment]
Hy stumped101, Can you explain in detail the solution? I have same problem. Thank you :)
