### ISSUE TITLE
Why this error occurs.: Call to a member function eloquent() on null at 

### ISSUE THREAD

**Issue by Rsl561292** [yajra/laravel-datatables#1843]
Hello. I wrote the following code.
Controller:
`use App\DataTables\Module\Profile\ArticlesDataTable;

class ArticleResource extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ArticlesDataTable $dataTable)
    {
        //

        return $dataTable->render('modules.profile.article.index');

    }
}
`
Code writed in file App\DataTables\Module\Profile\ArticlesDataTable :
`
use Yajra\DataTables\Services\DataTable;
use App\Article;

class ArticlesDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable()
    {
        return $this->datatables
        ->eloquent($this->query())
        ->addColumn('action', 'eloquent.tables.users-action');
    }

    /**
     * Get query source of dataTable.
     *
     * @param \App\'App\Article'\Module/Profile/Article $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query()
    {
        $query = Article::query();

        return $this->applyScopes($query);
        //return $model->newQuery()->select('id', 'title', 'updated_at', 'published_at', 'status');
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->addAction(['width' => '80px'])
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['export', 'print', 'reset', 'reload'],
                    ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'id',
            'title',
            'updated_at',
            'published_at',
            'status',
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'Articles_' . date('YmdHis');
    }
}
`
Html code page:
`

@section('content')
    {!! $dataTable->table(['id' => 'articles']) !!}
@endsection

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
@endpush

@push('scripts')
    
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
    <script src="/vendor/datatables/buttons.server-side.js"></script>
    {!! $dataTable->scripts() !!}
@endpush

`
The problem is that it issues an error of number 500 and the Laravel log writes an error: [2018-09-17 17:11:21] local.ERROR: Call to a member function eloquent() on null {"userId":3,"email":"ruslan.karpatu.2013@gmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function eloquent() on null at D:\\OSPanel\\domains\\laravelstudy.loc\\app\\DataTables\\Module\\Profile\\ArticlesDataTable.php:20)

Please help understand what I'm doing wrong, why this error occurs.

- PHP Version: 7.1
- Laravel 5.6
- Laravel-Datatables Version: i installed command composer require yajra/laravel-datatables:^1.0

**Comment by Rsl561292** [comment]
> Hello. I wrote the following code.
> Controller:
> `use App\DataTables\Module\Profile\ArticlesDataTable;
> 
> class ArticleResource extends Controller
> {
> /**
> * Display a listing of the resource.
> *
> * @return \Illuminate\Http\Response
> */
> public function index(ArticlesDataTable $dataTable)
> {
> //
> 
> ```
>     return $dataTable->render('modules.profile.article.index');
> 
> }
> ```
> }
> `Code writed in file App\DataTables\Module\Profile\ArticlesDataTable :`
> use Yajra\DataTables\Services\DataTable;
> use App\Article;
> 
> class ArticlesDataTable extends DataTable
> {
> /**
> * Build DataTable class.
> *
> * @param mixed $query Results from query() method.
> * @return \Yajra\DataTables\DataTableAbstract
> */
> public function dataTable()
> {
> return $this->datatables
> ->eloquent($this->query())
> ->addColumn('action', 'eloquent.tables.users-action');
> }
> 
> ```
> /**
>  * Get query source of dataTable.
>  *
>  * @param \App\'App\Article'\Module/Profile/Article $model
>  * @return \Illuminate\Database\Eloquent\Builder
>  */
> public function query()
> {
>     $query = Article::query();
> 
>     return $this->applyScopes($query);
>     //return $model->newQuery()->select('id', 'title', 'updated_at', 'published_at', 'status');
> }
> 
> /**
>  * Optional method if you want to use html builder.
>  *
>  * @return \Yajra\DataTables\Html\Builder
>  */
> public function html()
> {
>     return $this->builder()
>                 ->columns($this->getColumns())
>                 ->minifiedAjax()
>                 ->addAction(['width' => '80px'])
>                 ->parameters([
>                     'dom'          => 'Bfrtip',
>                     'buttons'      => ['export', 'print', 'reset', 'reload'],
>                 ]);
> }
> 
> /**
>  * Get columns.
>  *
>  * @return array
>  */
> protected function getColumns()
> {
>     return [
>         'id',
>         'title',
>         'updated_at',
>         'published_at',
>         'status',
>     ];
> }
> 
> /**
>  * Get filename for export.
>  *
>  * @return string
>  */
> protected function filename()
> {
>     return 'Articles_' . date('YmdHis');
> }
> ```
> }
> `Html code page:`
> 
> @Section('content')
> {!! $dataTable->table(['id' => 'articles']) !!}
> @endsection
> 
> @Push('css')
> 
> @endpush
> 
> @Push('scripts')
> 
> <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
> 
> <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
> <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
> <script src="/vendor/datatables/buttons.server-side.js"></script>
> {!! $dataTable->scripts() !!}
> @endpush
> 
> `
> The problem is that it issues an error of number 500 and the Laravel log writes an error: [2018-09-17 17:11:21] local.ERROR: Call to a member function eloquent() on null {"userId":3,"email":"[ruslan.karpatu.2013@gmail.com](mailto:ruslan.karpatu.2013@gmail.com)","exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): Call to a member function eloquent() on null at D:\OSPanel\domains\laravelstudy.loc\app\DataTables\Module\Profile\ArticlesDataTable.php:20)
> 
> Please help understand what I'm doing wrong, why this error occurs.
> 
> * PHP Version: 7.1
> * Laravel 5.6
> * Laravel-Datatables Version: i installed command composer require yajra/laravel-datatables:^1.0

**Comment by lk77** [comment]
https://github.com/yajra/laravel-datatables/issues/1845
