### ISSUE TITLE
Unable to sort by accessor column

### ISSUE THREAD

**Issue by miken32** [yajra/laravel-datatables#1844]
### Summary of problem or feature request

Errors are thrown when sorting by an accessor column. Using the below code I get this error:

>DataTables warning: table id=DataTables_Table_0 - Exception Message:
>
>SQLSTATE[42S22]: Column not found: 1054 Unknown column 'address' in 'order clause' (SQL: select * from `houses` where `user_id` = 12451 order by `address` asc limit 25 offset 0)

### Code snippet of problem

```php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class House extends Model
{
    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ["address"];

    public function getAddressAttribute()
    {
        return "$this->number $this->street\n$this->city $this->province  $this->postcode";
    }
}
```

```php
<?php
namespace App\Http\Controllers;

use App\House;
use DataTables;
use DB;

class HouseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            $houses = House::where("group_id", Auth::user()->group()->id)->with("user");
            return DataTables::of($houses)->make();
        }
        return view("houses.index");
    }
}
```

```js
$("table.datatable").DataTable({
    columns: [
        {data: "address"},
        {data: "user.name", defaultContent: "Unoccupied"},
        {data: "id"},
    ],
    ajax: "http://host.example.com/houses/",
    pageLength: 25,
    serverSide: true
});
```

### System details
- Operating System: MacOS
- PHP Version: 7.1
- Laravel Version: 5.6
- Laravel-Datatables Version: 8.0

**Comment by cytech** [comment]
I have the same issue using dataTables as a service

**Comment by yajra** [comment]
The package cannot sort on computed / accessor properties. You need to convert this to SQL level. Try using filterColumn. 

Refs:

https://datatables.yajrabox.com/eloquent/post-column-search 
https://yajrabox.com/docs/laravel-datatables/master/filter-column

**Comment by miken32** [comment]
That doesn't seem to work for me either. Now the controller has this code:

```php
        $concat = "CONCAT(number, ' ', street, '\n', city, ' ', province, '  ', postal_code)";
        $houses = House::select(["id", DB::raw("$concat AS address")])
            ->where("user_id", Auth::user()->id)
            ->with("user");
        return DataTables::of($houses)
            ->filterColumn("address", function($q, $k){return $q->whereRaw("$concat LIKE ?", ["%$k%"]);})
            ->make(true);
```

The query is built properly, according to debug returned in the JSON:

    select `id`, CONCAT(number, ' ', street, '\n', city, ' ', province, '  ', postal_code) AS address from `houses` where `user_id` = ? order by `address` asc limit 25 offset 0

I've put this into MySQL and it returns the expected values. But the JSON data returned has an empty string instead of the calculated value.

**Comment by miken32** [comment]
After some debugging, it appears that the data is lost in `Helper::convertToArray()` when the model's `toArray()` method is called. Any suggestions?

**Comment by yajra** [comment]
@miken32 can you please paste the error dump. Can't visualize the problem. Thanks!

**Comment by miken32** [comment]
Here is the complete response from the server:

    {"draw":1,"recordsTotal":25,"recordsFiltered":25,"data":[{"id":"4","address":"","user":null},{"id":"5","address":"","user":null},{"id":"6","address":"","user":null},{"id":"7","address":"","user":null},{"id":"8","address":"","user":null},{"id":"9","address":"","user":null},{"id":"10","address":"","user":null},{"id":"11","address":"","user":null},{"id":"12","address":"","user":{"id":"9","group_id":"1","house_id":"12","name":"Spiz Boots","disabled":0,"deleted_at":null,"created_at":"2018-09-06 20:03:39","updated_at":"2018-09-19 18:48:44"}},{"id":"13","address":"","user":null},{"id":"14","address":"","user":null},{"id":"15","address":"","user":null},{"id":"16","address":"","user":null},{"id":"17","address":"","user":null},{"id":"18","address":"","user":null},{"id":"19","address":"","user":null},{"id":"20","address":"","user":null},{"id":"21","address":"","user":null},{"id":"22","address":"","user":null},{"id":"23","address":"","user":null},{"id":"24","address":"","user":null},{"id":"25","address":"","user":null},{"id":"3","address":"","user":null},{"id":"2","address":"","user":null},{"id":"1","address":"","user":{"id":"1","group_id":"1","house_id":"1","name":"Mike A User 👨🏻‍💻","disabled":0,"deleted_at":null,"created_at":"2018-07-09 23:02:03","updated_at":"2018-09-19 18:49:06"}}],"queries":[{"query":"select count(*) as aggregate from (select '1' as `row_count` from `houses` where `houses`.`group_id` = ?) count_row_table","bindings":[1],"time":0.57},{"query":"select `id`, CONCAT(number, ' ', street, '\n', city, ' ', province, '  ', postal_code) AS address from `houses` where `group_id` = ? order by `address` asc limit 25 offset 0","bindings":[1],"time":2.42},{"query":"select * from `users` where `users`.`house_id` in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)","bindings":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],"time":1.4}],"input":{"draw":"1","columns":[{"data":"name","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}},{"data":"user.name","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}},{"data":"id","name":"","searchable":"true","orderable":"false","search":{"value":"","regex":"false"}}],"order":[{"column":"0","dir":"asc"}],"start":"0","length":"25","search":{"value":"","regex":"false"},"_":"1537458956998"}}

As you can see, the `address` field in each record is an empty string, but this is not the value that's returned from the database.

**Comment by miken32** [comment]
Ok, got it figured out. The problem was that I was using the same name (`address`) for both the constructed column and the accessor. When the model's `toArray()` method was called, the accessor must have been overwriting the constructed column.

This is not super intuitive, and it would be great if this library could somehow work transparently with accessors.

**Comment by yajra** [comment]
The accessor should still return the proper value. I suspect that you removed the street, address, etc on your query which is why it does compute the values properly.

**Comment by kablin** [comment]
I just add a fake field to my DB. And now a can use it in accessor and it show fine in DataTable
