### ISSUE TITLE
Raw columns

### ISSUE THREAD

**Issue by sharifzadesina** [yajra/laravel-datatables#1849]
By default blade strings/templates, should be considered as `rawColumn` cause we do the filtering inside of the blade string/template using `{{ }}` operator.

It is not robust to add also a `rawColumn` for each of your columns that use blade.

NOTE: this won't be a breaking-change or cause a security issue, as everyone uses `{{ }}` inside of the blade strings/templates.

**Comment by yajra** [comment]
The idea looks fine. Can you please send a PR as per your suggestion?

**Comment by sharifzadesina** [comment]
@yajra Sure, I'll do it today.
