### ISSUE TITLE
class="never" not working

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#185]
Hi, how can I use the class="never"  inorder to hide a certain column?

Thank you in advance.

**Comment by yajra** [comment]
class="never"? I think you are referring to `visible: false`?

**Comment by ezekel** [comment]
Thank you for the reply so visible:false is equivalent to class="never" ?

Datables has class control see https://datatables.net/extensions/responsive/examples/display-control/classes.html

**Comment by ezekel** [comment]
@yajra , how do I hide column ?

**Comment by yajra** [comment]
See api for more details. https://datatables.net/reference/option/columns.
