### ISSUE TITLE
Service implementation joins not working

### ISSUE THREAD

**Issue by RomkaLTU** [yajra/laravel-datatables#1850]
Can't figure out simple task: join 1 table and add column. There is no usefull documentation about service implementation. 

### Code snippet of problem

```php
public function query()
    {
        $query = Technika::query()
            ->join('manufacturers','technika.manufacturer_id','=','manufacturers.id')
            ->select($this->getColumns());

        return $this->applyScopes($query);
    }

protected function getColumns()
    {
        return [
            'manufacturers.id',
        ];
    }
```

This will trigger bizarre error

` Requested unknown parameter 'manufacturers.id' for row 0, column 0 `

Tried many variations like:

```
return [
    'id',
];
```

Above will trigger `Column 'id' in field list is ambiguous`

Another one was:

```
return [
  [
    'name' => 'id',
    'data' => 'id'
  ]
];
```

this will result in: `strtolower() expects parameter 1 to be string, array given`

And so on and so forth. Maybe some one jsut can give basic join example using Service implementation? 

### System details

- Operating System OSX
- PHP Version 7.2
- Laravel Version 5.5
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
You need to specify the table name with column name when using join. See https://datatables.yajrabox.com/eloquent/joins for ref. The only diff on demo with service implementation is that the  scripts/columns are declared on the php side. Hope it makes sense. Thanks!

**Comment by RomkaLTU** [comment]
Thanks for follow up @yajra but this was first thing I've tried and when I set up columns like this:

```
protected function getColumns()
    {
        return [
            'technika.id',
            'manufacturers.title'
        ];
    }
```

`Requested unknown parameter 'technika.id' for row 0, column 0`

However response data is correct (as I can see in XHR response) but table renders empty rows.

**Comment by RomkaLTU** [comment]
### Update

Solved problme by doing this:

```
protected function getColumns()
    {
        return [
            [ 'data' => 'id', 'name' => 'technika.id', 'title' => 'ID' ],
            [ 'data' => 'title', 'name' => 'manufacturers.title', 'title' => 'Manufacturer' ]
        ];
    }

public function query()
    {
        $query = Technika::query()
            ->join('manufacturers','technika.manufacturer_id','=','manufacturers.id')
            ->select( collect($this->getColumns())->pluck('name')->toArray() );

        return $this->applyScopes($query);
    }
```

getColumns method is used in query() and in html() and they both expect different type of array format.
