### ISSUE TITLE
rawColumns doesn't seem to work when changing the column index

### ISSUE THREAD

**Issue by cacholong** [yajra/laravel-datatables#1855]
### Summary of problem or feature request

We are trying to add the 'actions' to our rows. This is some html what should be displayed. Our convention is to add those buttons on last column. But when doing that, the plain html (escaped) is displayed instead of the buttons what we expected.

### Code snippet of problem

```php
$results = User::select(['id']);
return DataTables::make($results)
  ->addColumn('actions', '<button id="bla"></button>', 2)
  ->rawColumns(['actions'])
  ->make(false);
```

It works when we change the code snippet to:
```php
$results = User::select(['id']);
return DataTables::make($results)
  ->addColumn('actions', '<button id="bla"></button>', 0)
  ->rawColumns(['actions'])
  ->make(false);
```

It also works when we return the results as json objects.

### System details

- Operating system: Debian GNU/Linux
- PHP Version: 7.2.9
- Laravel Version: v5.7.5
- Laravel-Datatables Version: v8.8.0

**Comment by Artistan** [comment]
same issue, https://github.com/yajra/laravel-datatables/issues/1898

**Comment by Artistan** [comment]
you need make(true) otherwise it does not keep the column names when trying to apply the rawColumn definitions.

**Comment by yajra** [comment]
When using `make(false)`, you need to specify the row index and not the column name. But please note that [array response](https://yajrabox.com/docs/laravel-datatables/master/response-array) is not fully tested so I suggest you go with the [object response](https://yajrabox.com/docs/laravel-datatables/master/response-object) if possible.

```php
$results = User::select(['id']);
return DataTables::make($results)
  ->addColumn('actions', '<button id="bla"></button>', 2)
  ->rawColumns([1])
  ->make(false);
```

**Comment by Artistan** [comment]
right!  I am not a big fan of that unless you specify each column in the order you want the data returned.  This makes me claustrophobic. LOL 😆
