### ISSUE TITLE
Reply Slow 

### ISSUE THREAD

**Issue by lusho201515** [yajra/laravel-datatables#1857]
### Summary of problem or feature request

The reply o load datatable is very slow, betwen 3-5seg 

### Code snippet of problem
 Controller 

    public function list_user(){
        $users = User::all();
        $users->each(function ($users)
        {
            $users->role;
        });
        return datatables()->collection($users)->toJson();
    }

JS

    function activar_tabla_users() {
    $('#DataTableUser').DataTable({
        "processing" : true,
        "serverSide" : true,
        "searchDelay" : 500,
        "responsive": {
            orthogonal: 'responsive'
        },
        "language": {
            "url": '{!! asset('/plugins/datatables.net/latino.json') !!}'
        } ,
        "lengthMenu": [5,10, 25, 50, 75 ],
        "ajax":'{!! url('admin/list_user') !!}',
        columns: [
            {data: 'id' },
            {data: 'username'},
            {data: 'name',
                render: function (data, type, row, meta) {
                    return row.name + ' ' + row.lastname;
                } 
            },
            {data: 'email'},
            {data: 'role.name',
                render: function(data, type, row, meta) {
                var html = ''
                if ( row.role.name == 'Administrador' )
                {
                    html = '<span class="label label-danger" > <label style="width:80px;"> '+row.role.name+' </label></span>';
                            
                }else {
                    html = '<span class="label label-primary" > <label style="width:80px;"> '+row.role.name+' </label></span>';
                }
                return html;
                }
            },{
            "defaultContent" : " ",
            "searchable" : false,
            "orderable" : false,
            "render" : function(data, type, row, meta) {
                    var disabled = "", tooltip = 'data-toggle="tooltip"';
                    var html= '<span data-toggle="modal" data-target="#delete-user" data-userid="'+row.id+'"><a id="tooltip-ex" class="btn btn-danger btn-xs" onclick="conf_modal(this)" data-original-title="Eliminar" data-toggle="tooltip" data-placement="auto"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></span>';
                    html+='&nbsp;<span data-toggle="modal" data-target="#modal-EUsers"><a class="btn btn-warning btn-xs" onclick="Mostrar('+row.id+');" id="#updateUser'+row.id+'" data-original-title="Editar"  data-target="#modal-EUsers" data-toggle="tooltip"><i class="fas fa-wrench"></i></a></span>';
                    html+='&nbsp;<a class="btn btn-info btn-xs" onclick="openmodal(this)" id="#MeditPermissions'+row.id+'" data-original-title="Editar Permisos" data-toggle="tooltip"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span</a>'
  
                    return html;
            },
            }],

    });
    }
    activar_tabla_users(); 

model

```
<?php

    namespace App;

    use Illuminate\Notifications\Notifiable;
    use Illuminate\Contracts\Auth\MustVerifyEmail;
    use Illuminate\Foundation\Auth\User as Authenticatable;

    class User extends Authenticatable
    {
        use Notifiable;

        protected $table = "users";

        protected $fillable = [
            'id','role_id', 'username','name','lastname','email', 'password'
        ];

        protected $hidden = [
            'password', 'remember_token',
        ];
        public function role()
        {
            return $this->belongsTo('App\Role');
        }
        public function permission()
        {
            return $this->hasOne('App\Permission');
        }
    }

```
### Details
How can I optimize the data load?
when I did not use server inside it was much faster..
first of all, Thanks

**Comment by cacholong** [comment]
In your controller you are loading the complete collection (issueing a query like: SELECT * FROM user). Look at the basic example on https://datatables.yajrabox.com/eloquent/basic. When you give datatables a query it is able to add an offset and limit to your query. This will minimize the amount of processing serverside.
