### ISSUE TITLE
Sorting & Search dosen't work

### ISSUE THREAD

**Issue by abosami2000** [yajra/laravel-datatables#186]
Hi guys ,

I have laravel 4.1 and laravel-da tatables-oracle , it works fine.

but have some problem

I have 5 columns ( id(int) , name(string) , sales(int) ,mobile(int),phone(int) , when I want to search it works with integer only but string dosn't work.

also all columns can't sorting.

this is my query:
```php
 return Datatables::of( Persons::select(array('id_person','full_name_person','SegelID_person',DB::raw('(select COUNT(id_agd) from sales Where customer_id = prsn.id_person AND status != 0) as sales'),'mobile1_person'))->where('ty',2))
    ->editColumn('full_name_person',function($Person){
    	         return $Person->full_name_person;

     })
    ->addColumn('options',function($Person){
       return $Person->full_name_person;
     
    }) 
 
    ->make();
```

this is javascript:

```js
  $(document).ready(function() {
    var oTable = $('#example').DataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "{{URL::Route('GetCustomerJson')}}",
        
    
    } );
 } );
```

**Comment by yajra** [comment]
What is the error that dumped in your developer tools? 

On the other hand, I think it would be best to use Bllim's version for Laravel 4.1 as it was best maintained during that time. I fully integrated their new features starting Laravel 5 and some on Laravel 4.2 version.

**Comment by yajra** [comment]
@abosami2000, Sorry! forgot to mention that I already dropped support for 4.1. Currently supporting 4.2, 5.0 & 5.1. It is best to use Bllims version for 4.1. Regards!

**Comment by abosami2000** [comment]
thanks @yajra  , yes you'r right , it works with Bllims
