### ISSUE TITLE
How to search until at least 3 characters are entered?

### ISSUE THREAD

**Issue by uobando** [yajra/laravel-datatables#1861]
Hello.

I would like start the search only after 3 characters have been typed in the search box. 

The next code is an example for jQuery datatables 10, but it doesn't work with laravel-datatables.

```js
// Call datatables, and return the API to the variable for use in our code
// Binds datatables to all elements with a class of datatable
var dtable = $(".datatable").dataTable().api();

// Grab the datatables input box and alter how it is bound to events
$(".dataTables_filter input")
    .unbind() // Unbind previous default bindings
    .bind("input", function(e) { // Bind our desired behavior
        // If the length is 3 or more characters, or the user pressed ENTER, search
        if(this.value.length >= 3 || e.keyCode == 13) {
            // Call the API search function
            dtable.search(this.value).draw();
        }
        // Ensure we clear the search if they backspace far enough
        if(this.value == "") {
            dtable.search("").draw();
        }
        return;
    });
```

Can someone help me?

Thanks.

**Comment by yajra** [comment]
Your code looks fine. Maybe you should check the arrangement of your scripts? Make sure the plugin is loaded first before the table initialization.

**Comment by elevensquare** [comment]
i think you use this way 
 var dtable= $("table#pagination-2").DataTable({
        "processing": true,
        "serverSide": true,
        "order": [],
        "searchDelay":2000,
    
        "ajax": {
                "url": dataTableURL,
                "type": "POST"
            },
            "columnDefs": [{ 
                "targets": [0],
                "orderable": true
            }],
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1,-2,-3] /* 1st one, start by the right */
            }],
            
            "initComplete": function() 
            {
             $(".dataTables_filter input")
              .unbind() // Unbind previous default bindings
              .bind("input", function(e) { // Bind our desired behavior
                  // If the length is 3 or more characters, or the user pressed ENTER, search
                  if(this.value.length > 3 || e.keyCode == 13) {
                      // Call the API search function
                      dtable.search(this.value).draw();
                  }
                  // Ensure we clear the search if they backspace far enough
                  if(this.value == "") {
                      dtable.search("").draw();
                  }
                  return;
              });
              
            }
      })

**Comment by dreadkopp** [comment]
i'd do

```
...

 .bind("keyup", function(e) { // Bind our desired behavior
              // If the length is 3 or more characters, or the user pressed ENTER, search
              if(this.value.length > 2 || e.keyCode == 13) {
                  // Call the API search function
                  dtable.search(this.value).draw();
              }
              // Ensure we clear the search if they backspace far enough
              if(this.value == "") {
                  dtable.search("").draw();
              }
              return;
          });
...
```

though

**Comment by arce701** [comment]
how would it be if i'm using the plugins  HTML Builder and Buttons, helpme please
