### ISSUE TITLE
DataTables as Service and JSON column type, escaping problem

### ISSUE THREAD

**Issue by RomkaLTU** [yajra/laravel-datatables#1862]
Double quotes not removing when returning json value, for example in Mysql I have:

`"some_key": "Something and something more"`

But HTML is rendered like this:

`"Something and something more"` should be **Something and something more**

No quotes. I'm accessing this column trough columns method like this:

`[ 'data' => 'date', 'name' => 'metas->date AS date', 'title' => 'Data' ]`

Tried adding

`->rawColumns(['metas|metas->date|metas.date','action'])`

Also tried allowing everything in /config/datatables.php 'escape' => [] nothing helped.

Response is escaped. How to do it unescaped? Tried everything...

Response looks like this:

`{"draw":1,"recordsTotal":77,"recordsFiltered":77,"data":[{"id":43695,"nr":"18-036","date":"\"2018-09-17\""...`

As you can see I have additional quotes in response near date: 
Normally if I return same data from DB with ->toJson() there wouldn't be problem. There is something wrong with DataTables decoding.

**In QueryDataTable.php construct $this->query->get() returning same results with additional quotes and I don't know where to go next.** 

**UPDATE:**

**So it seams that problem is causing by ->select(['metas->date']) explicitly selecting fields produce output with 4x quotes. I have no idea why at the moment...**

**Comment by Artistan** [comment]
https://github.com/yajra/laravel-datatables/issues/1898
