### ISSUE TITLE
where 'status' = ?

### ISSUE THREAD

**Issue by rebornishard** [yajra/laravel-datatables#1867]
### Summary of problem or feature request

This happen when data not found
using where (int) become ? (question mark) not showing real number,
is this feature or to hide real number ?

#### Only status
```php
$members = Members::where('status',1);
		return Datatables::of($members)
			->addColumn('action', 'backend.pages.members.buttons')
			->rawColumns(['action'])
			->addIndexColumn()
			->make(true);
```
result
```javascript
{"draw":0,"recordsTotal":0,"recordsFiltered":0,"data":[],"queries":[{"query":"select count(*) as aggregate from (select '1' as `row_count` from `members` where `status` = ?) count_row_table","bindings":[1],"time":0.4},{"query":"select * from `members` where `status` = ?","bindings":[1],"time":0.3}],"input":[]}
```
#### add orderby hope it well
```php
$members = Members::where('status',1)->orderBy('name','ASC');
		return Datatables::of($members)
			->addColumn('action', 'backend.pages.members.buttons')
			->rawColumns(['action'])
			->addIndexColumn()
			->make(true);
```
result
```javascript
{"draw":0,"recordsTotal":0,"recordsFiltered":0,"data":[],"queries":[{"query":"select count(*) as aggregate from (select * from `members` where `status` = ? order by `name` asc) count_row_table","bindings":[1],"time":0.37},{"query":"select * from `members` where `status` = ? order by `name` asc","bindings":[1],"time":0.37}],"input":[]}
```
#### using DB
```php
$members = DB::table('members')
						->select('*')
						->where('status',1)
						->get();
```
result
```javascript
{"draw":0,"recordsTotal":0,"recordsFiltered":0,"data":[],"input":[]}
```

-->

### System details

- Operating System Ubuntu 16.04
- PHP Version 7.2.10
- Laravel Version 5.6
- Laravel-Datatables Version ~8.0

**Comment by rebornishard** [comment]
i forgot to write my question,  can result from eloquent become empty like this, if null / empty :
```javascript
{"draw":0,"recordsTotal":0,"recordsFiltered":0,"data":[],"input":[]}
```

**Comment by oranges13** [comment]
This is not an issue and should not be affecting your results. The ? is just a placeholder, but if you look in the `queries` data, you will also see `bindings` which is what is placed in the ? when it is run as SQL.

For example `{"query":"select * from `members` where `status` = ? order by `name` asc","bindings":[1]}` becomes `SELECT * FROM members where status = 1 order by name asc`

**Comment by yajra** [comment]
@oranges13 is correct, it's just a placeholder for query bindings which is basically a protection from an SQL Injection attacks.
