### ISSUE TITLE
Class datatables.html does not exist

### ISSUE THREAD

**Issue by QadeerQT** [yajra/laravel-datatables#1868]
### Problem or feature request
I'm unable to use yajra getting exception while using this. No Major code changes.
Anyone guide me to fix this. Thanks

### Installed Packages
       "yajra/laravel-datatables-buttons": "^3.0",
        "yajra/laravel-datatables-fractal": "1.*",
        "yajra/laravel-datatables-html": "3.*",
        "yajra/laravel-datatables-oracle": "~8.0"
        
        Yajra\DataTables\DataTablesServiceProvider::class,
         Yajra\DataTables\HtmlServiceProvider::class

### System details

- Ubuntu 16.04
- PHP 7.0
- Laravel 5.4
- Laravel-Datatables ~8.0

**Comment by yajra** [comment]
It's registered on the [html provider](https://github.com/yajra/laravel-datatables-html/blob/3.0/src/HtmlServiceProvider.php#L46).

Maybe try deleting your vendor folder and composer.lock file then re-install the packages?
