### ISSUE TITLE
Adding checkbox 

### ISSUE THREAD

**Issue by s1nc4pp** [yajra/laravel-datatables#187]
How can i add checkbox to the table and i want to to put checkbox's value current row's id

**Comment by johnhatch** [comment]
You can add a column to your table like so:

```php
->addColumn('check', '<input type="checkbox" id="selected_users[]" value="{{ $id }}">')
```

Example:
```php
$data = User::select('id','first_name','last_name');

return Datatables::of($data)
->addColumn('check', '<input type="checkbox" name="selected_users[]" value="{{ $id }}">')
->make(true);
```

More solutions at: https://github.com/yajra/laravel-datatables/issues/26#issuecomment-92690658

**Comment by s1nc4pp** [comment]
thanks man

**Comment by s1nc4pp** [comment]
Hi again, i added an email field in my table like you said way 
but when i click to email row to sort datas by email it takes sql error
```->addColumn('email', '<a href="mailto:{{ $email }}">{{ $email }}</a>')```

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* asc limit 10 offset 0' at line 1 (SQL: select `users`.*, `user_profiles`.`name`, `user_profiles`.`phone` from `users` inner join `user_profiles` on `user_profiles`.`user_id` = `users`.`id` where `users`.`deleted_at` is null order by `users`.* asc limit 10 offset 0)`

**Comment by johnhatch** [comment]
Hmm, looks like it's not finding a column to sort by:
```sql
order by users. asc
```
Should be like
```sql
order by users.email
```

What does your JS look like? The 'name' property of the table should point to the email column: 
```js
columns: [
	{data: 'email', name: 'users.email'}	
]
```

**Comment by s1nc4pp** [comment]
Hmm that wat just `email` and when i changed it to `users.email` it worked
Thanks again dude

**Comment by johnhatch** [comment]
I figured it would just work as just `email`, but seeing https://github.com/yajra/laravel-datatables/issues/58#issuecomment-104207654 it seems like when you left join you have to use the full path to the column for ordering/sorting. And no problem :)

**Comment by yudijohn** [comment]
@yajra, i have added checkbox on my server-side datatables, when i check a data at page 1, and i move to page 2, and return to page 1, the check is gone, how to make my check still there?

**Comment by Instabash** [comment]
> @yajra, i have added checkbox on my server-side datatables, when i check a data at page 1, and i move to page 2, and return to page 1, the check is gone, how to make my check still there?

Hey, have you figured out a solution to this?

**Comment by yajra** [comment]
@Instabash see https://datatables.net/examples/server_side/select_rows.html for refs. I can be achieved by adding some js and tracking the selected ids.
