### ISSUE TITLE
Suggested tweak

### ISSUE THREAD

**Issue by nettsite** [yajra/laravel-datatables#1870]
### Summary of problem or feature request

When a table is generated, all columns are created, including those which are not going to be visible. The "visible=>false" columns are then removed, which looks untidy.

I have inserted one line of code to fix this:

```php
if (array_key_exists('visible', $value) && FALSE == $value['visible']) continue;
```

### Original code with addition:

```php
/**
     * Set datatables columns from array definition.
     *
     * @param array $columns
     * @return $this
     */
    public function columns(array $columns)
    {
        $this->collection = new Collection;

        foreach ($columns as $key => $value) {
            if (! is_a($value, Column::class)) {
                if (is_array($value)) {

                  // Skip "invisible" columns:
                   if (array_key_exists('visible', $value) && FALSE == $value['visible']) continue;

                    $attributes = array_merge(
                        [
                            'name' => $value['name'] ?? $value['data'] ?? $key,
                            'data' => $value['data'] ?? $key,
                        ],
                        $this->setTitle($key, $value)
                    );
                } else {
                    $attributes = [
                        'name'  => $value,
                        'data'  => $value,
                        'title' => $this->getQualifiedTitle($value),
                    ];
                }

                $this->collection->push(new Column($attributes));
            } else {
                $this->collection->push($value);
            }
        }

        return $this;
    }
```
-->

### System details

- Operating System  Ubuntu 16.04
- PHP Version  7.3
- Laravel Version 5.7
- Laravel-Datatables Version

**Comment by yajra** [comment]
Thanks for the idea but it will break the installations specially this trick which I often used. I often add hidden column to enable searching on it. An example would be for the name. Having a column first & last name, we often display it as `full_name` and named as `first_name` but this limits the search to `first_name` column. To allow searching on `last_name`, we can then add a hidden column for it and it will be included in the search. 

```js
columns: [
  {data: 'full_name', name: 'first_name'},
  {data: 'last_name', name: 'last_name', visible: false},
]
```

**Comment by NettSite** [comment]
Ok, I see. Would it be possible to incorporate it as an option? I know that if I update the package, I will lose my tweak.
