### ISSUE TITLE
Jquery CDN Problem

### ISSUE THREAD

**Issue by dan3460** [yajra/laravel-datatables#1871]
### Summary of problem or feature request

I copied a table with server requests from one application to another. I got an error that h.ajax is not a function. Could figure out what the problem could be. At first look everything was the same.
After playing a little and googling around and no luck, decided to look at the templates to make sure that were the same, every thing was the same except for the Jquery CDN, on the application that works i have this: <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> on the one that doesn't work i have the cdn from JQuery : <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

Is this a problem?

### System details

- Operating System Window 10
- PHP Version 7.2.3
- Laravel Version 5.7.8
- Laravel-Datatables Version 8.8

**Comment by yajra** [comment]
Not sure on this one. Maybe try asking on the js library forum on https://datatables.net/forums/. Thanks!
