### ISSUE TITLE
Very slow performance with relationships

### ISSUE THREAD

**Issue by paulcanning** [yajra/laravel-datatables#1872]
I'm experiencing very slow performance when using chained relationships in my Eloquent data source.

My models are linked through a few relationships, for example:

A > B > C > D

By specifying a property in D, I can get A.

I am using `with()` in the query builder, to eager load the data, but it takes about 30s to load data when filter by a property at the end of the chain.

Is there anything I can do to speed this up, other then add new columns to table A to store the data being queried?

I've even added some foreign keys to linked A to B and B to C, but it doesn't seem to help.

**Comment by yajra** [comment]
I suggest you debug the queries generated and optimize it using indexes and DB optimization tricks. You can see the queries generated by setting `APP_DEBUG=true` and inspect the ajax response for queries result.

**Comment by paulcanning** [comment]
Looks like it was my dev environment being slow. Homestead with 1gb RAM, 1 CPU, XDebug etc = unhappy datatables.

Our remote testing environment is much much quicker.

**Comment by arieltoledo** [comment]
@paulcanning Laravel Eloquent is quite slow with this type of querys when you have large set of data. 
You should check doing the same with a raw query. This are old posts but they address the problem quite well. I found that using RAW SQL QUERY with long datasets (when you need the relationships) improves the time performance in a huge way. 
https://medium.com/@asked_io/optimizing-laravel-5-mysql-for-9m-rows-step-2-dcf4ceee1876
https://stackoverflow.com/questions/45323659/laravel-collection-with-relations-take-a-lot-of-time

**Comment by cuteaayushi** [comment]
I am Using datatable in laravel But it is loading very slow. It is taking 1min approx to fetch 100 records. Please tell me if any one know the reason why this is happening . I really need help to figure out this thing.

Here is my view File
$('document').ready(function () {
            var sellertable = null;

            var loadDatatables = function(params = null){
                
                var url = "http://dev-admin.gozappi.com/users/seller";

                if (params) {
                        // debugger;
                        url += url.indexOf('?') === -1 ? `?${params}` : `&${params}`;
                    }
                    
                    
                    if (sellertable) {
                        sellertable.destroy();
                    }


                    sellertable = $('#SellerTableDataTable').DataTable({
                        responsive: true,
                        "order": [[ 1, "desc" ]],
                        "language": {
                          processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span> ',
                          sLengthMenu: " _MENU_",
                      },
                      scrollX:        true,
                      colReorder:      true,
                      scrollCollapse: true,
                      fixedColumns:   {
                        leftColumns: 4,
                    },
                    fixedHeader: true,
                    pagingType: "simple",
                    "drawCallback" : function () {
                        $('[data-toggle="tooltip"]').tooltip({
                            container: 'body'
                        });
                    },
                    "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull) {

                        if(aData['status'] == '2'){
                         $(nRow).css('color', 'Red'); 
                     }
                     else{

                        if(aData['affiliate_status'] == '1'){
                          $(nRow).css('color', 'Green');
                      }
                      else if(aData['affiliate_status'] == '0') {
                        $(nRow).css('color', 'Red');
                    }
                    else if(aData['affiliate_status'] == '2') {
                        $(nRow).css('color', '#ff5500');
                    }
                    else if(aData['affiliate_status'] == '3') {
                        $(nRow).css('color', 'Blue');
                    }
                }     
            },
            "initComplete": function(){
                $("#pageLength").html('');
                $("#pagination").html('');
                $("#SellerTableDataTable_length").appendTo("#pageLength");
                $("#SellerTableDataTable_paginate").appendTo("#pagination");
            },
            "columns": [
            { "data": "id","orderable" : false},
            { "data": "created_at","orderable" : true },
            { "data": "status","orderable" : true},
            { "data": "trade_name","orderable" : false},
            { "data": "username","orderable" : true},
            { "data": "email","orderable" : true },
            { "data": "retainer_level","orderable" : true },
            { "data": "seller_level","orderable" : false },
            { "data": "subscription_name","orderable":false},
            { "data": "mobile_no" ,"orderable" : true},
            { "data": "country","orderable" : false },
            { "data": "gender","orderable" : true},
            { "data": "postcode" ,"orderable" : false},
            { "data": "industry","orderable" : false},
            { "data": "affiliate_status " ,"orderable" : true},
            { "data": "ytd_sold", "orderable" : false},
            { "data": "spend_this_week", "orderable" : false},
            { "data": "spend_this_month", "orderable" : false},
            { "data": "spend_this_year", "orderable" : false},
            { "data": "ytd_sold", "orderable" : false},
            { "data": "seller_followers", "orderable" : false},
            { "data": "no_of_offer","orderable" : false },
            { "data": "no_of_bundle","orderable" : false},
            { "data": "offer_refund", "orderable" : false  },
            { "data": "offer_wishlistes", "orderable" : false  },
            { "data": "id"},
            
            ],
            "columnDefs": [
            {
                "targets" : 0,
                "render" : function (data , type, full, meta){
                    let html = 
                    '<div class="select"><label><input type="checkbox" name="checkbox" value="'+full.id+'" data-name="'+full.username+'"></label></div>';

                    return html;
                }
            },
            {
                "targets" : 2,
                "render" : function (data , type, full, meta){
                    if(full.status == '1'){
                        return html ="Active";

                    }
                    else if(full.status == '0'){
                        return html ="Blocked";
                    }
                    else if(full.status == '2'){
                        return html ="Deleted";
                    }
                    else if(full.status == '3'){
                        return html ="Inactive";
                    }
                    else if(full.status == '4'){
                        return html ="Pending";
                    }
                    else {
                        return html ="N/A";
                    }

                    
                }
            },
            {
               "targets" : 11,
                "data" : "gender",
                "orderable" : true,
                "render" : function (data , type, full, meta){
                    var gender ='Male';
                    if(full.gender === '2'){
                        var gender ='Female';
                    }
                    return gender;
                }
            },
            {
                "targets" : 14,
                "render" : function (data , type, full, meta){
                    if(full.affiliate_status == '0'){
                        return html ="Blocked";

                    }
                    else if(full.affiliate_status == '1'){
                        return html ="Active";
                    }
                    else if(full.affiliate_status == '2'){
                        return html ="Paused";
                    }
                    else if(full.affiliate_status == '3'){
                        return html ="Pending Approval";
                    }
                    else{
                        return html ="N/A";
                    }

                    
                }
            }, 
            {
                "targets" : -1,
                "data" : null,
                "orderable": false,
                "className" : "text-center",
                

                "render" : function (data , type, full, meta){
                    var html = "";
                    if(full.status){
                        status = full.status;
                    }
                    else{
                        status = '';
                    }

                    if(full.affiliate_status){
                        affiliate = full.affiliate_status.toLowerCase();
                    }
                    else{
                        affiliate = '';
                    }
                    var handoverhtml;
                    if(full.created_by == '1'){
                        handoverhtml ='<option value="handover-'+full['id']+'-'+full['mobile']+'-'+full['email']+'">Handover</option>';
                    }

                    
                    html += '<select class="actionTable form-control"><option value="" id="--Select--">--Select--</option><option value="edit-'+full['id']+'" data-status="'+status+'" data-affiliate="'+affiliate+'">Edit</option><option value="view-'+full['id']+'">View</option><option value="copy-'+full['id']+'">Copy</option>'+handoverhtml+'';
                    return html;
                }
                
            }        
            ],
            "ordering": true,
            "dom": 'B<"top"flp>rt<"bottom"i><"clear">',
            "buttons": [
            {
                extend: 'csv',
                text: 'Export CSV',
                filename: 'seller'    ,
            },
            ],
            "processing": true,
            "serverSide": true,
           "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "All"] ],
            "ajax" :url
        });
        sellertable.buttons().container().appendTo('#export-csv');

        }

        loadDatatables();
