### ISSUE TITLE
Custom filters combined with default search?

### ISSUE THREAD

**Issue by paulcanning** [yajra/laravel-datatables#1874]
When I add my own filters and use `filter()` the default free text search box is disabled.

How can I combine the two easily?

**Comment by yajra** [comment]
You can pass `true` as 2nd argument to enable global search. See https://yajrabox.com/docs/laravel-datatables/master/manual-search for ref.

**Comment by paulcanning** [comment]
Ah. The documentation isn't the clearest ;)

I ended up just moving the sub queries out of the DataTables class.
