### ISSUE TITLE
How can I add custom drop-down-list on top of the datatable

### ISSUE THREAD

**Issue by computerzman** [yajra/laravel-datatables#1879]
Hi my friends
How can I add custom drop drop-down-list top of the datatable
when i choose item of it, it add custom where clause to the main query and redraw the datatable again ..
Thanks in advance

**Comment by oranges13** [comment]
I have an example of how I accomplished this here: https://gist.github.com/oranges13/759d8692693dbdb569c4ca542f1b1be2

At the core, you need to create a query (or queries) to populate your dropdown list(s) and add this data to the initial JSON response.
You then need to modify your javascript in the `initComplete` function to add the data from the JSON response to draw the dropdown filters and then filter when they're modified. See the gist for more details.
