### ISSUE TITLE
Eager loading related of related (nested eager loading) (sorting by the related of related doesn't work) 

### ISSUE THREAD

**Issue by FilipQL** [yajra/laravel-datatables#1883]
### Summary of problem or feature request

There are 3 Eloquent models with the following relations:

- `Post` _belongsTo_ `Thread`
- `Thread` _belongsTo_ `Forum`

I am using Datatables to display **posts**. I "_eager load_" **threads** (similarly to [your example](https://datatables.yajrabox.com/relation/belongs-to)):

```
        $posts = Post::select('posts.*')
            ->with(['thread' => function ($query) {
                $query->withTrashed();
            }]);
```

and then I have `'thread.title'` column. Everything works **OK** here - ordering by the _thread titles_, searching... BUT I've tried to "_eager load_" **forums** also (into **threads** that are already being eagerly loaded):

```
           ->with(['thread' => function ($query) {
                $query->withTrashed()->with(['forum' => function ($query) {
                    $query->withTrashed();
                }]);
            }])
```

and then I have `'thread.forum.name'` column. The forums names are displayed in the table, but when I try to order by the forum name - I'm getting the following error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'thread.forum.name' in 'order clause' (SQL: select `posts`.* from `posts` order by `thread`.`forum`.`name` asc limit 10 offset 0)

![1](https://user-images.githubusercontent.com/18264428/47388243-fe8efe00-d711-11e8-9d71-39c3c0935f61.png)

The question is - is this (**nested eager loading**) even **supported** by this package? :) 

### System details

- Operating System: Windows 7 64 bit
- PHP Version: 7.2 (XAMPP)
- Laravel Version: 5.6.39
- Laravel-Datatables Version: 8.9.1

**Comment by FilipQL** [comment]
@yajra Will there be any updates on this issue? :) I tested with the latest version 9.x (Laravel 6) and the same issue still exists.

**Comment by PeraMika** [comment]
I suggest to close this question (as it was asked in 2018 and no replies) and re-create the same one (with updated versions).
