### ISSUE TITLE
how detect current language ?

### ISSUE THREAD

**Issue by vahidalvandi** [yajra/laravel-datatables#1884]
### Summary of problem or feature request

hello , i have multi language system . how  datatable can detect current language automatically?

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
Not sure as I haven't tried developing on multiple language. Maybe try asking on https://datatables.net/manual/i18n forum?

On php side, I guess a basic if to conditionally load the [language](https://datatables.net/plug-ins/i18n/) file will do?

```php
if (Request::server('HTTP_ACCEPT_LANGUAGE') == 'en') {
    $parameters['language']['url'] = 'dataTables.english.lang';
}
