### ISSUE TITLE
Using Yajra datatables as service..but can't use Model accessor.

### ISSUE THREAD

**Issue by rohanshukla94** [yajra/laravel-datatables#1885]
### 
    protected $appends = ['unique_name'];
    public function getUniqueNameAttribute($value)
     {

        return $this->posts->name . sprintf('%02d', $this->authors->id) . date('Ym') . sprintf('%02d', $this->id);

     }

I followed this link while making the datatable: https://datatables.yajrabox.com/service
btw I got a completely different code than shown there, maybe cause of updates.
but anyways it works 100% when i select some fields from the database but I had a question or rather an issue

How can I use my accessor for displaying it on datatable
I'm trying to use it like this which obviously doesn't work

    public function query(Project $model)
    {
        return $model->newQuery()->select('id', 'project_title', 'unique_name', 'due_date');
    }

I know this is obviously not work but how can I use it?

### System details

- Operating System: Debian Stretch 
- PHP Version: 7.2.9
- Laravel Version: Laravel Framework 5.7.7
- Laravel-Datatables Version: "yajra/laravel-datatables": "^1.0"

**Comment by yajra** [comment]
You can use this undocumented PR https://github.com/yajra/laravel-datatables/pull/1416. Or manually add it using [addColumn](https://yajrabox.com/docs/laravel-datatables/master/add-column). Thanks!
