### ISSUE TITLE
Model timestamp, Exception Message: Trailing data

### ISSUE THREAD

**Issue by emiliosa** [yajra/laravel-datatables#1886]
### Vehicle class

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Vehicle extends Model
{
    const CREATED_AT = 'created_date';
    const UPDATED_AT = 'modified_date';

    protected $dates = ['created_date','modified_date'];
        
    public function getCreatedDateAttribute()
    {
        return Carbon::parse($this->attributes['created_date'])->format('d/m/Y H:i:s');
    }

    public function getModifiedDateAttribute()
    {
        return Carbon::parse($this->attributes['modified_date'])->format('d/m/Y H:i:s');
    }
}
```

### Vehicle controller

```
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Vehicle;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class VehiclesController extends Controller
{
    public function datatableIndex()
    {
        return view('vehicles.datatables.index');
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function datatableData()
    {
        return Datatables::of(Vehicle::query())->make(true);
    }
}
```

### index.blade.php

```
@extends('layouts.app')
@section('title', 'Vehicles')

@push('javascript')
    <script>
        $(function() {
            $('#vehicles-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('vehicles.datatable.data') !!}',
                columns: [
                    { data: 'created_date', name: 'created_date' },
                    { data: 'modified_date', name: 'modified_date' },
                ]
            });
        });
    </script>
@endpush

@section('content')

    <table class="table table-bordered" id="vehicles-table">
        <thead>
            <tr>
                <th>Created Date</th>
                <th>Modified Date</th>
            </tr>
        </thead>
    </table>
@endsection
```

### Error

- PHP Version: 7.2
- Laravel Version: 5.7
- Laravel-Datatables Version: 8.9

Help, thanks!

**Comment by yajra** [comment]
I think the issue here is not related to dataTables but on your model and maybe carbon. Checking the web for some relevant issue and [this](https://laracasts.com/discuss/channels/laravel/carbon-trailing-data-error?page=0) seems to fit your error.

To make sure, try returning the query data first to see if it works?

**Comment by emiliosa** [comment]
Hi, sorry for so late response from me, ive been very busy with another proyect, like most of us.

Well, i have read that article already, and i dont have that problem outside yajra/laravel-datatable package. 

![captura de pantalla de 2018-11-21 17-42-12](https://user-images.githubusercontent.com/7193597/48867398-ccc29300-edb4-11e8-95a4-3f87805d7417.png)

![captura de pantalla de 2018-11-21 17-47-19](https://user-images.githubusercontent.com/7193597/48867635-8883c280-edb5-11e8-975a-96f02d7c4a23.png)

Insteand, using datatables:

![captura de pantalla de 2018-11-21 17-44-59](https://user-images.githubusercontent.com/7193597/48867536-3773ce80-edb5-11e8-8529-acfac40960fe.png)

But! When i comment this lines on Vehicle model:
`
//const CREATED_AT;
//const UPDATED_AT;
`

![captura de pantalla de 2018-11-21 17-52-02](https://user-images.githubusercontent.com/7193597/48867973-cb926580-edb6-11e8-8c45-a27852254136.png)
![captura de pantalla de 2018-11-21 17-56-04](https://user-images.githubusercontent.com/7193597/48867974-cb926580-edb6-11e8-9bfd-1782642291cc.png)

Despite of Carbon exception, it throws when i call make() method from Datatable...
Any ideas?

Thanks again for your time.

**Comment by jhoanborges** [comment]
+1
