### ISSUE TITLE
Possibility of using package outside of Laravel

### ISSUE THREAD

**Issue by grafikkaos** [yajra/laravel-datatables#1887]
Is it possible to use this package outside of laravel?  I am currently working on an existing project where I have pulled down some illuminate components and got the application working.

It would however be nice to use this package outside of laravel itself as it's the best out there that generates datatables quite well.

While I have tried to instantiante the Yaira\Datatables\Datatables class, I am getting erroes where it says the datatables.request class has not been found.

If it's possible, I would appreciate any ideas.

Thanks

Manny

**Comment by yajra** [comment]
TBH, I haven't tried using the package outside of Laravel. But maybe it might work if you can emulate the bindings on `DataTablesServiceProvider`?

`datatables.request` is being pushed on the IoC that returns a new instance of Request class:

```php
        $this->app->singleton('datatables.request', function () {
            return new Request;
        });
```

Or maybe you can fake it by creating your own app helper that returns the required class to create a DataTable. Something like:

```php
class QueryDataTable extends DataTableAbstract {
...
public function __construct(Builder $builder) {
        $this->request    = app('datatables.request');
        $this->config     = app('datatables.config');
...

// helper.php
function app($key) {
    if ($key == 'datatables.request') return new Request;
}
```

**Comment by grafikkaos** [comment]
Hi, thanks for the reply...

I will see what I can come up with. 

Thank you :)
