### ISSUE TITLE
demo problem

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#189]
HI @yajra ,

Can I ask about your demo, I installed it on my local windows 8, but some of your examples have problem in loading the datatables. but it works fine in linux machine. is there something difference if we code to linux then we transfer it to windows ?.I have notice that if we use datatables on linux then we run it to windows ,the datatables will have problem in loading.

Thank you in advance.

**Comment by yajra** [comment]
@ezekel, not sure on windows and linux as I am using mac as my dev machine. But one thing is for sure that the php environments do differ on these OS. I suggest you use homestead if possible to avoid this environment issues that most of us developers encounter. But generally, it should should work on any LAMP stack.

**Comment by ezekel** [comment]
Ok thanks.
