### ISSUE TITLE
Laravel Datatables is not installing with Composer

### ISSUE THREAD

**Issue by nafeeur10** [yajra/laravel-datatables#1894]
### Hanging on installing Laravel DataTable

> Loading composer repositories with package information
> Updating dependencies (including require-dev)

### System details

- Operating System Windows
- PHP Version
- Laravel Version 5.7.1
- Laravel-Datatables Version 0.8

**Comment by hamzaubi** [comment]
that's totaly true i am stuck too cant install it

**Comment by hamzaubi** [comment]
Hey Yajra thanks for getting back so quick 
i found out that one of the packages that i am including in my project was preventing datatables from bein installed
