### ISSUE TITLE
Logging out the user randomly

### ISSUE THREAD

**Issue by wessodesigner** [yajra/laravel-datatables#19]
After I installed the package and started to use it, it works perfectly. But the issue is every time I open a page that displays a table (with thousands of records) being handled by this plugin, it logs me out and redirects me to the login page. It happens randomly.

I am using Laravel 5 on a windows machine and a google chrome browser. 

I am uploading my application to a production server to see if I get the same results. But for now this is my issue.

**Comment by yajra** [comment]
Hi, most probably a server time out is occurring due to volume of data being parsed. Maybe try adjusting your environment to a production level settings?

**Comment by wessodesigner** [comment]
Still not working. I am being logged out every time randomly. Sometime after the first refresh, sometimes after a few refreshes. What settings exactly do you think I should change?

**Comment by wessodesigner** [comment]
After some tests, I found out that I am being logged out only when I am causing the table to send an ajax request quickly a few times. For example, clicking on the sorting arrow 3 times very fast, when I switch back, I am logged out. So how can we solve this issue?

**Comment by illuminate3** [comment]
-- OSX 10.10.2, php 5.5, laravel 5, Chrome, calling with ajax and datatables 1.10.5, jquery 2.x
-- I am using joins on the controller side and several options on the view side.

I'm testing with 11k records and do not have this issue.
My local machine does take 249ms to reload my tables so clicking fast just shows me processing until I stop.

DataTables will crash your browser with 10K+ records but that  is not really this package's issue. I find this package just as fast as Chumper's on Laravel 4, however yajra's is simpler to setup and for now he still answers and helps :wink:

I can not see this package will log you out.

Is your code similar to what I posted in issue #12 ?
Would you mind showing some of your code?

I do think your issue is possibly:
More related to your php.ini settings or Apache/Nginx. It could be a memory issue.

**Comment by wessodesigner** [comment]
The weird thing is when I changed the request type from get to post in both my controller and my ajax request, it worked like magic. No more logging out, no more anything. It just works. o.O 

This is my code (after changed the method to post instead of get)

public function postCourses() {
        $courses = Course::join('categories', 'categories.id', '=', 'courses.category_id')
                    ->leftJoin('sub_categories', 'sub_categories.id', '=', 'courses.sub_category_id')
                    ->select(['courses.id', 'title_en', 'title_ar', 'categories.english_name as cat_name', 'sub_categories.english_name as subcat_name', 'city_id', 'start_date', 'duration', 'courses.user_id', 'courses.slug']);

        return Datatables::of($courses)
            ->addColumn('actions', '<a href="{{ url( \'admin/courses\', [$slug, \'edit\']) }}" class="btn btn-xs btn-info tooltipLink" data-toggle="tooltip" data-placement="top" title="Edit Course">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button class="btn btn-xs btn-danger tooltipLink delete" data-toggle="tooltip" data-target="tooltip" data-placement="top" title="Delete Course"><i class="fa fa-times"></i></button>')
            ->removeColumn('slug')
            ->make();
    }

**Comment by yajra** [comment]
Since post method seems to fix your issue then I guess that maybe the query string being generated is too large which may have caused apache/php to bug down your code. See this link for some details: http://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string

In addition, I also have an experience with this on our firewall blocking the ajax request due to it's length exceeding 2000 chars but does not logout like what you were experiencing.

**Comment by illuminate3** [comment]
I just crashed DataTables with 12,000 records ... not enough memory.

However!!! with Yajra's ajax call this is not an issue.

So, be careful with just straight DataTables and large number of collections.

**Comment by wessodesigner** [comment]
OK thank you very much for your efforts 

Just one last thing

Something weird is happening now. It worked well after changing the method from get to post. Now after leaving the project for 10 days, I am trying to run it now, and the following happens: 

I open the courses page (which contains the all the courses in the database in a form of ajax-filled datatables), and the first page of data is shown. After performing any action that supposed to changed the data in the view (sorting, filtering, changing the page, or changing the length per page), the data in the table stays the same. However, when I revert back to get requests, it works fine (But not if I filter or searched too quickly).

Here are my code snippets:

1- JS
```
var dTable = $('.table').dataTable({
            "sPaginationType": "full_numbers",
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": link,
                "type": "POST"
            },
            "columns": [
                        {courses: 'id', name: 'id'},
                        {courses: 'title_en', name: 'title_en'},
                        {courses: 'title_ar', name: 'title_ar'},
                        {courses: 'cat_name', name: 'cat_name'},
                        {courses: 'subcat_name', name: 'subcat_name'},
                        {courses: 'city_id', name: 'city_id'},
                        {courses: 'start_date', name: 'start_date'},
                        {courses: 'duration', name: 'duration'},
                        {courses: 'user_id', name: 'user_id'},
                        {courses: 'actions', name: 'actions', bSearchable: false}
                    ]
        });
```

2- Controller
```
public function postCatCourses($id) {
        $courses = Course::join('categories', 'categories.id', '=', 'courses.category_id')
            ->leftJoin('sub_categories', 'sub_categories.id', '=', 'courses.sub_category_id')
            ->where('categories.id', '=', $id)
            ->select(['courses.id', 'title_en', 'title_ar', 'categories.english_name as cat_name', 'sub_categories.english_name as subcat_name', 'city_id', 'start_date', 'duration', 'courses.user_id', 'courses.slug', 'categories.slug as cat_slug']);

        return Datatables::of($courses)
            ->addColumn('actions', '<a href="{{ url( \'admin/categories\', [$cat_slug, \'courses\' ,$slug]) }}" class="btn btn-xs btn-success tooltipLink" data-toggle="tooltip" data-placement="top" title="View Course">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{ url( \'admin/courses\', [$slug, \'edit\']) }}" class="btn btn-xs btn-info tooltipLink" data-toggle="tooltip" data-placement="top" title="Edit Course">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button class="btn btn-xs btn-danger tooltipLink delete" data-toggle="tooltip" data-target="tooltip" data-placement="top" title="Delete Course"><i class="fa fa-times"></i></button>')
            ->removeColumn('slug')
            ->removeColumn('cat_slug')
            ->make();
    }
```

**Comment by yajra** [comment]
There were several bug fix since this issue was created. Can you please checkout the latest version and test again? thanks!

**Comment by illuminate3** [comment]
I also think (not sure) if there is an issue with the way the columns are working. So, I just use long form to prevent issues.

```
			{
				data: 'id',
				name: 'id',
				searchable: false,
				visible: false
			},
			{
				data: 'name',
				name: 'name',
				orderable: true,
				searchable: true
			},
```

Notice that I have orderable and searchable declared for each item.

Also, I have been having problems with the ->removeColumn() command in the controller. Just make visible:false and it will do the same thing for you.

The reason I think it has a bug is because the ajax call is looking for data that in the original query or something like that. Or you can just use a select in your query and keep data limited that way.

These are work arounds but they are working for me!

**Comment by yajra** [comment]
Closing this one because can't reproduce the error and it's been a while and no one seems to be having the same issue.

**Comment by yajra** [comment]
@wessodesigner are you using "artisan serve"? #167 seems to prove that this issue was due to it. Feedback much appreciated. Thanks!

**Comment by wessodesigner** [comment]
Actually yes I always do

**Comment by yajra** [comment]
@wessodesigner, thanks for confirming. This ghost bug does indeed was due to artisan serve. Several users experiencing this issue also confirmed it that they were using `artisan serve`.

**Comment by gadius** [comment]
@mastrip2 Just nailed it; changed my initialization as follow.

var tableIndex=$('#tableIndex').DataTable({
"order": [[ 0, "asc" ]],
"aLengthMenu": [[5, 10, 25], [5, 10, 25]],
"iDisplayLength": 10,
"dateFormat": 'yyyy-mm-dd',
"processing": true,
"serverSide": true,
"ajax": {
'url': '{{route("clinics.api.laboratoryIndex")}}',
'type': 'POST',
'headers': {
'X-CSRF-TOKEN': '{{ csrf_token() }}'
}
},
"columns":[
{data: 'products', name: 'products'},

],
"columnDefs": [
{ "searchable": false, "bSortable": false, "targets": 0 }
],
language: {
"sProcessing": "Procesando...",
"sLengthMenu": "Mostrar MENU registros",
"sZeroRecords": "No se encontraron resultados",
"sEmptyTable": "Ningún dato disponible en esta tabla",
"sInfo": "Mostrando registros del START al END de un total de TOTAL registros",
"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
"sInfoFiltered": "(filtrado de un total de MAX registros)",
"sInfoPostFix": "",
"sSearch": "Buscar: ",
"sUrl": "",
"sInfoThousands": ",",
"sLoadingRecords": "Cargando...",
"oPaginate": {
"sFirst": "Primero",
"sLast": "Último",
"sNext": "Siguiente",
"sPrevious": "Anterior"
},
"oAria": {
"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
"sSortDescending": ": Activar para ordenar la columna de manera descendente"
}
}
});

Thank you fam
