### ISSUE TITLE
Disable Specific column Filter (No JS settings)

### ISSUE THREAD

**Issue by MatiasSW** [yajra/laravel-datatables#190]
Hello.

Is it possible to disable filtering of a specific column? 
I have a column which initially worked with eager loading (And then realized it doesnt work for filtering) so I wrote 2 separate Queries, one for the Specific column and another for everything else, the specific column query works fine and the "global" query works fine too, however the global search still tries to lookup the custom column.

I can't rely on filterColumn since I use two different databases (Unless you can actually issue a whole function into it?). 
So is it possible to remove a column from the global search without disabling it on the JS part of the initialization.

**Comment by yajra** [comment]
Hi,

Unfortunately, there is no way atm to remove a column from global search but I think you can use filterColumn as a workaround to remove it. Maybe something like this will do:

```php
->filterColum('remove_column', 'whereRaw', '1=1', [])
```

**Comment by MatiasSW** [comment]
Worked like a charm. Thank you again.

**Comment by armen9494** [comment]
Also this one works
`->filter(function () {})`
