### ISSUE TITLE
Yajra DataTable Is Not Installing on Laravel 5.7.*

### ISSUE THREAD

**Issue by adnanali1996** [yajra/laravel-datatables#1902]
### Summary of problem or feature request

Hello Developers!
I am facing problem while installing Yajra Datatable by using this Command " composer require yajra/laravel-datatables:^1.0 "on Powershell and i got errors. I have Uninstall Wampp and installed Xampp but problem still exists. Please Help me out to figure out why this is happening is any PHP version issue or something else. I am solving this issue from two days to since now but I failed.
 

### Code snippet of problem

  Problem 1
    - Installation request for yajra/laravel-datatables 1.0 -> satisfiable by yajra/laravel-datatables[v1.0.0].
    - Conclusion: remove laravel/framework v5.7.12
    - Conclusion: don't install laravel/framework v5.7.12
    - yajra/laravel-datatables v1.0.0 requires yajra/laravel-datatables-buttons 3.* -> satisfiable by yajra/laravel-datatables-buttons[3.0.x-dev, v3.0.0, v3.0.1, v3.0.2, v3.1.0, v3.1.1, v3.1.2, v3.2.0, v3.2.1, v3.2.2, v3.3.0].
    - yajra/laravel-datatables-buttons 3.0.x-dev requires illuminate/console 5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - yajra/laravel-datatables-buttons v3.0.0 requires illuminate/console 5.4.*|5.5.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - yajra/laravel-datatables-buttons v3.0.1 requires illuminate/console 5.4.*|5.5.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - yajra/laravel-datatables-buttons v3.0.2 requires illuminate/console 5.4.*|5.5.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - yajra/laravel-datatables-buttons v3.1.0 requires illuminate/console 5.4.*|5.5.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - yajra/laravel-datatables-buttons v3.1.1 requires illuminate/console 5.4.*|5.5.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - yajra/laravel-datatables-buttons v3.1.2 requires illuminate/console 5.4.*|5.5.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - yajra/laravel-datatables-buttons v3.2.0 requires illuminate/console 5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - yajra/laravel-datatables-buttons v3.2.1 requires illuminate/console 5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - yajra/laravel-datatables-buttons v3.2.2 requires illuminate/console 5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - yajra/laravel-datatables-buttons v3.3.0 requires illuminate/console 5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/console[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/console 5.6.x-dev|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.0|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.1|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.10|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.11|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.12|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.13|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.14|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.15|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.16|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.17|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.19|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.2|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.20|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.5.43|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.5.44|don't install laravel/framework v5.7.12
    - Installation request for laravel/framework (locked at v5.7.12, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.12].

### System details

- Operating System Window 10
- PHP 7.2.11
- Laravel Version 5.7.12
- Laravel-Datatables Version ^1.0

**Comment by yajra** [comment]
Try using `composer require yajra/laravel-datatables:^1.2`

**Comment by adnanali1996** [comment]
Thankssssssss So much sir it worked. Sir can i ask you that why it was not installing with composer require yajra/laravel-datatables:^1.0 is some package version compatibility issue or something else i want to know that and again Thankssssssss God Bless you.

**Comment by yajra** [comment]
Support for buttons package was added on v4.x. I think it was added on v1.2.

**Comment by adnanali1996** [comment]
Thanks for your support.

**Comment by harishankarsingh** [comment]
the same problem I'm also getting it is not installing in laravel 5.8

**Comment by akijweb** [comment]
just run `composer require yajra/laravel-datatables`  which is perfect for any version.. That is in my case.

**Comment by mvhk** [comment]
`composer require yajra/laravel-datatables-oracle:"~8.0"`
try this it's working

**Comment by fingersandmind** [comment]
What version of yajra does eager loading for relationship works? I'm using laravel 5.7

**Comment by baltun** [comment]
I had a problem with updating laravel from 5.7 to 5.8 with yajra/laravel-datatables-oracle in composer.json. I removed this package from composer.json, made laravel update with `composer update` and then made `composer require yajra/laravel-datatables-oracle`
