### ISSUE TITLE
Ordering problem, undefined index data

### ISSUE THREAD

**Issue by sansanbgl** [yajra/laravel-datatables#1904]
### Summary of problem or feature request
Ordering problem
Always Shows Exception regarding undefined index

### Code snippet of problem
Javascript
```
var tableMeeting = $('#table-meeting').DataTable({
                processing: true,
                serverSide: true,
                scrollX: true,
                ordering:true,
                order:[
                    [5,"DESC"]
                ],
                sAjaxSource: "{{url('/meeting/datatables')}}",
                columns: [
                    {data: 'id',render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }},
                    {data: 'student_name', name: 'student_name'},
                    {data: 'lecturer_name', name: 'lecturer_name'},
                    {data: 'date_held', name: 'date_held',orderable: true, searchable: false},
                    {data: 'room_name', name: 'room_name', orderable: false},
                    {data: 'updated_at', name: 'updated_at', orderable: true, searchable: false},
                    {data: 'action', name: 'action',orderable: false, searchable: false}
                ],
                "bLengthChange": false,
                "iDisplayLength": 10,
                "oTableTools": {
                    "sRowSelect": "single"
                },
            });
```

Error is 
Undefined index: data
/home/vagrant/Sites/simta/vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Datatables.php#429

### System details

- Operating System : Vagrant Ubuntu 18.04
- PHP Version: 5.6
- Laravel Version : 4.2
- Laravel-Datatables Version : 3.0

Summary

I was able to evade this error, this is there is no array key named 'data' when do Ordering method fired

I able to fix it with these

```
private function doOrdering()
	{
		if ( count($this->input['order'])>0 )
		{
			$columns = $this->cleanColumns( $this->last_columns );
			for ( $i=0, $c=count($this->input['order']); $i<$c ; $i++ )
			{
				$order_col = (int)$this->input['order'][$i]['column'];
				$order_dir = $this->input['order'][$i]['dir'];
				foreach ($this->input['columns'] as $k => $column) {
					if ($k == $order_col)
					{
						if ( $column['orderable'] == "true" )
							$this->query->orderBy($columns[$order_col],$order_dir);
					}
				}
			}
		}
	}
```

is it worth for pull request

**Comment by yajra** [comment]
BTW, can you also paste your server-side code? Might be some issue there and no need for a PR.

**Comment by sansanbgl** [comment]
Server side 
`$query = Meeting::join('final_projects', function ($on) {
            $on->on('meetings.final_project_id', '=', 'final_projects.id');
        })->leftJoin('lecturers', 'final_projects.lecturer_id', '=', 'lecturers.id')
            ->leftJoin('students', 'final_projects.student_id', '=', 'students.id')
            ->leftJoin('rooms', 'meetings.room_id', '=', 'rooms.id')
            ->where('meetings.approved', '=', 1);
        if (!Auth::user()->isAdmin()) {
            $query = $query->join('final_projects', 'meetings.final_project_id', '=', 'final_projects.id')->where('final_projects.lecturer_id', Auth::user()->person_id);
        }
        $query->select(['meetings.id', 'lecturers.name as lecturer_name', 'students.name as student_name', 'date_held', 'rooms.name as room_name', 'meetings.updated_at']);
        return Datatables::of($query)
            ->editColumn('date_held', function ($data) {return Carbon\Carbon::parse($data->date_held)->formatLocalized('%d %B %Y');})
            ->editColumn('updated_at', function ($data) {return $data->updated_at->diffForHumans();})
            ->addColumn('action', function ($item) {
                $links = '<a href=' . URL::to('meeting/update/' . $item->id) . ' class="btn btn-primary btn-xs" title="Edit Jadwal"><span class="glyphicon glyphicon-pencil"></span> Edit</a>' .
                '<a href="' . URL::to('meeting/detail/' . $item->id) . '" class="btn btn-primary btn-xs" title="Lihat rincian jadwal"><span class="glyphicon glyphicon-list-alt"></span> Lihat</a>';
                if (Auth::user()->isAdmin()) {
                    $links .= '<a href="' . URL::to('meeting/print_report/' . $item->id) . '" class="btn btn-success btn-xs" title="Cetak Laporan"><span class="glyphicon glyphicon-print"></span> Berita Acara</a>';
                }
                $links .= '<a href="' . URL::to('meeting/delete/' . $item->id) . '" class="btn btn-danger btn-xs" title="Hapus"><span class="glyphicon glyphicon-remove"></span>Hapus</a>';
                return $links;

            })
            ->make(true);`

**Comment by sansanbgl** [comment]
I'm dealing with some old code haha

**Comment by yajra** [comment]
I think you should set the name with `table.column` format since you are using join.

```php
{data: 'student_name', name: 'students.name'},
```

**Comment by sansanbgl** [comment]
problems still persists
![image](https://user-images.githubusercontent.com/3112367/48464988-f65b4780-e813-11e8-9312-b421a1ea9911.png)

doOrdering func
```
private function doOrdering()
	{
		if ( count($this->input['order'])>0 )
		{
			$columns = $this->cleanColumns( $this->last_columns );

			for ( $i=0, $c=count($this->input['order']); $i<$c ; $i++ )
			{
				$order_col = (int)$this->input['order'][$i]['column'];
				$order_dir = $this->input['order'][$i]['dir'];
				foreach ($this->input['columns'] as $column) {
					if ($column['data'] == $order_col)
					{
						if ( $column['orderable'] == "true" )
							$this->query->orderBy($columns[$order_col],$order_dir);
					}
				}
			}
		}
	}
```
I dump $this->input['columns'] there isn't 'data' as key
