### ISSUE TITLE
Use repository L5

### ISSUE THREAD

**Issue by macagoraga** [yajra/laravel-datatables#1905]
If I try to paginate the users result then there is an error.
How to paginate the users since at the moment return all rows the server side process?

Did I need to do this manually or is handle by custom request of your package?

Thanks

**Comment by macagoraga** [comment]
Seem work fine using query().

I try different way by using repository, I am using this: https://github.com/andersao/l5-repository

Is there a way to handle this?

**Comment by yajra** [comment]
@macagoraga I think the repository package is good for handling on API centric development. For the dataTables, I suggest you use a model or a [Query Object](https://laracasts.com/series/whip-monstrous-code-into-shape/episodes/17) for complex queries.

Anyways, if there is a way for the that package to get the `query()` instance, it should also work fine. Just note that pagination is already handled by the package thus `paginate()` should not be used.

**Comment by macagoraga** [comment]
Thanks!
