### ISSUE TITLE
addIndexColumn() Not working from recent update

### ISSUE THREAD

**Issue by reezdevs** [yajra/laravel-datatables#1907]
### Summary of problem or feature request

addIndexColumn not working from last update. It was working fine from today (12/11/2018) It gives 

Requested unknown parameter 'DT_Row_Index' for row 0 Error message

### System details

- Operating System Windows 10
- PHP Version 7.2
- Laravel Version 5.6
- Laravel-Datatables Version ~8.0

**Comment by yajra** [comment]
Sorry for the inconvenience, it was considered as bug with a possible breaking change to follow the dataTables standard naming. 

Anyways, `DT_Row_Index` was renamed to `DT_RowIndex`.

See https://github.com/yajra/laravel-datatables/pull/1882 for details.
