### ISSUE TITLE
Loading indicator when export PDF, Excel...

### ISSUE THREAD

**Issue by manelsanz** [yajra/laravel-datatables#1909]
### Summary of problem or feature request

I'm using Snappy and Laravel Excel with Yajra DataTables Buttons and is a extremely powerful combination, so thanks a lot @yajra!

Just one thing, I wonder if there is a way to show the same Processing/Loading indicator of DataTables when a PDF/Excel/CSV buttons are clicked. 
If not, there is some way to handle the request in Javascript in order to put additional GIF/FontAwesome loading icon and quit when it's done?

Thanks!

### System details

- Windows 10
- PHP 7.2
- Laravel 5.7
- Laravel-Datatables 8.0

**Comment by yajra** [comment]
Not sure if possible but you can try playing the `buttons.server-side.js` script and append some animation/loading scripts there.

If you achieve this, kindly share the solution :). Thanks!

**Comment by from2day** [comment]
Hi, 
To address similar issue I am adding toggle to the action button to prevent user making the same call again. 
Add something for your needs into suggested file `buttons.server-side.js` in  `_downloadFromUrl` method 
```
$(".buttons-" + params.action).prop('disabled', true);
```

something like this:
```
var _downloadFromUrl = function (url, params) {

        /* Disable the action button */
        $(".buttons-" + params.action).prop('disabled', true);

        var postUrl = url + '/export';
        var xhr = new XMLHttpRequest();
        xhr.open('POST', postUrl, true);
        xhr.responseType = 'arraybuffer';
        xhr.onload = function () {
            if (this.status === 200) {
                
                /* Enable the action button */
                $(".buttons-" + params.action).prop('disabled', false);

                var filename = "";
...the rest of the file..
```
