### ISSUE TITLE
Search with boolean doesn't work well

### ISSUE THREAD

**Issue by joanebrown** [yajra/laravel-datatables#191]
Hi,

I'm trying to search the first column of my dataTable (the active column), and I use this:

    table.DataTable().columns(0).search("0");

But instead of return all the rows with the active column = 0, this return me all rows...

It's weird, but if I use:

    table.DataTable().columns(0).search("1");

Works well, and I only see the active rows...

Maybe is a bug?

**Comment by yajra** [comment]
Are you using regex? Kindly check the queries generated on dev tools and verify if it's correct. There used to be a bug when searching zero value but this was fixed sometime ago as far as I remember.

**Comment by joanebrown** [comment]
No, I onle use this code... In the Dev Tools I see all well :S 

When I use:

    table.DataTable().columns(0).search("%0%");

All works well, Why?


**BTW**: How can I implement a search if my column is produced by editColumn? (my "product_id" but I edit this with the serial number of the product: product->serialNumber). So when I search... I don't found nothing, because datatables search by the ID... Sorry for my english T_T

**Comment by yajra** [comment]
I tried column search with zero value and it works well. Try executing the generated sql manually and check if it does work. Demo for column search http://datatables.yajrabox.com/eloquent/multi-filter-select seems to work well too.

For editColumn, searching on it's edited value may not work since we are using a database query and it's not the value stored on it. For your case, you should use join statements (I think you are using eager loading?). Searching on eager loaded models is not supported atm.

**Comment by joanebrown** [comment]
Hi Yajra,

I tried with the SQL directly, and works well...

    select * from products where active = '1';

But doesn't work with:

    table.DataTable().columns(0).search("1");
And "works" with:

    table.DataTable().columns(0).search("%0%");

I say "works" inside quotes because, if the column have the "01" value, i get this too, with the "0". (because % is a wildcard character...)

Why is happen that?

BTW, the next sentence:

    $.fn.dataTable.util.escapeRegex($(this).val());

return me the next error:

    Uncaught TypeError: Cannot read property 'escapeRegex' of undefined

**Comment by yajra** [comment]
Is that the sql generated on ajax request? Can you dump the ajax output please?

**Comment by joanebrown** [comment]
I use AJAX on my datatables, yes. Of course!
In the next ajax output, i try to search the element with id 7, but i get the id 17 too:

`"bindings":["%%7%%","%%%%","%%%%","%%%%","%%%%","%%%%"],"time":0.61},{"query":"select `elements`.`id`, `elements`.`name`, `elements`.`lastname`, `elements`.`active`  from `elements` order by `id` desc limit 25 offset 0" ...`

I don't know why i can't search a exact match in my datatable. When I use:

    // The eight column is for the "active" attribute (boolean) of the element
    dataTable.DataTable().columns(8).search("0").draw();

I get all the elements, active or inactive...

When I use:


    dataTable.DataTable().columns(8).search("1").draw();


I get only the active! (I don't know why it works here)

And if I use:

    dataTable.DataTable().columns(8).search("%0%").draw();

Works well, but only for boolean columns, being as I can't search the exact match (If i try to search the ID 7, i get the id 17 too)

Sorry I don't know how to explain my problem better... :(

---

BTW, I want to make a donation, but I only have paypal account, do you have paypal?

**Comment by yajra** [comment]
Hmm this is really odd. I did tried manually doing column on search on this demo and it does work.
http://datatables.app/eloquent/relationships
```js
$('#posts-table').DataTable().columns(0).search(0).draw();
```

Maybe it's on the version you are using? Are you using latest version of the package?

-----------

With regard to paypal, thank you in advance for the support on this project. I do have paypal and pledgie also accepts it. I just use [pledgie campaign](https://pledgie.com/campaigns/29515) so that supports will be tracked and is open to public for transparency. Thanks!

**Comment by joanebrown** [comment]
Hi Yajra,

Yes, it works! but not how I want. I will explain me better :), your code:

    $('#posts-table').DataTable().columns(0).search(0).draw();

Returns all the rows whose first column contain "0" (10, 100, 102, ...) But i Want only the column who contains only "0" (exact match)

I just make a donation, thanks for all your amazing job :)

**Comment by yajra** [comment]
@joanebrown, by default global search will filter all columns using wildcard like `%0%`. If you want the exact match then you need to override the search for that field by using `filterColumn` method. See this demo for ref: http://datatables.yajrabox.com/eloquent/post-column-search.

And thanks for the support! :+1:

**Comment by joanebrown** [comment]
Hi,

filterColumn doesn't work :S

    Call to undefined method yajra\Datatables\Datatables::filtercolumn()

And I have the latest version of yajra datatables...

Can you give me a simple example of `filterColumn` for a boolean column? Maybe I don't understand the example in your URL well...

Regards

**Comment by yajra** [comment]
```php
->filterColumn('user_id', 'whereRaw', "CONCAT(users.id,'-',users.id) like ?", ["$1"])
```

What this do is that it will override the default search on `user_id` field from `user_id like '%keyword%'` to `CONCAT(users.id,'-',users.id) like 'keyword'`. For your case, you can follow the same. For instance if you want to search on `published` boolean column.
```php
->filterColumn('published', 'whereRaw', "published = ?", ["$1"])
```

`$1` is a special variable where it will be replaced with the actual value being search.

**Comment by joanebrown** [comment]
Thanks for all your help, works well :)

Could I ask you another little question? When I write in my database a spanish word like "Camión" (with accute),  I see "Cami&oacute;n" in my database, and the search of datatables doesn't work if I use "Camión" or "camion". I only get results when I write "Cami".

Do you know why ?

Thank you very much :)

**Comment by yajra** [comment]
I think it's due to localization? Not an expert on database localization but I think it's connected to that.

Made a quick search and it seems like it's connected to character sets. http://stackoverflow.com/questions/3304464/mysql-diacritic-insensitive-search-spanish-accents.

Regards!

**Comment by luciantugui** [comment]
@yajra ->filterColumn('published', 'whereRaw', "published = ?", ["$1"]) still adds %% wildcard, how can I use exact match? thanks

**Comment by a2zbits** [comment]
@luciantugui  try removing , ["$1"] including comma.
I think ["$1"] is not necessary. when 4rth value into method will be missing then it'll populate the searched-value in place of '?'.
