### ISSUE TITLE
yajra datatable dos is down

### ISSUE THREAD

**Issue by Abdelraman** [yajra/laravel-datatables#1913]
yajra datatable docs is down ?

**Comment by DavitMK** [comment]
Yes (. I hope they will fix it asap.

**Comment by yajra** [comment]
Server is suspended, will try to process it earliest tomorrow. Sorry for the inconvenience.

**Comment by DavitMK** [comment]
Thanks a lot --Sent from Yandex.Mail for mobile22.11.2018, 07:10, "Arjay Angeles" <notifications@github.com>:Server is suspended, will try to process it earliest tomorrow. Sorry for the inconvenience.

**Comment by ChaosPower** [comment]
Hi all,

We are having difficulties paying for the server ATM. We are waiting for funds to come in. When we receive the money will pay for the server as soon as possible.

**Comment by erikcmcollective** [comment]
Okay! Any updates so far?

**Comment by pajinkyaprdxn** [comment]
When will this site work?

**Comment by hazaveh** [comment]
is the site opensourced? any repo we can refer to docs?

**Comment by yajra** [comment]
Still waiting for funds, $40/mo is a bit hard to maintain for free software. Please use the github docs atm at https://github.com/yajra/laravel-datatables-docs and the demo repo at http://github.com/yajra/laravel-datatables-demo.

**Comment by erikcmcollective** [comment]
Hello Yajra, just paid 30 USD. Thank you!

**Comment by yajra** [comment]
thanks @erikcmcollective, payment sent to digital ocean. Server is up! ❤️ 🍻

**Comment by erikcmcollective** [comment]
Same issue again??
