### ISSUE TITLE
rawColumns doesn`t work

### ISSUE THREAD

**Issue by oriceon** [yajra/laravel-datatables#1916]
@yajra what`s wrong on last version (v8.13.0) with rawColumns() because now it displays columns without escape.

**Comment by yajra** [comment]
@oriceon Nothing wrong at all. It's just for convenience as requested by @sharifzadesina to allow raw html when using strings values on add / edit column. Does it break your app?

**Comment by oriceon** [comment]
@yajra yes, does not escape html on some columns .. as it did untill now.

**Comment by yajra** [comment]
Did the value came from database? Can you please paste some snippet to produce it. Will test again on my side.

**Comment by vanushwashere** [comment]
Same issue :( , waiting for fix

**Comment by yajra** [comment]
Sorry for this, reverting the changes.

**Comment by oriceon** [comment]
It happens`. No worry. Thanks and don`t forget to push a release.

Thanks.

**Comment by yajra** [comment]
Reverted on v8.12.1, thanks for reporting.

**Comment by yajra** [comment]
My tagging messed up :(... Reverted on v8.13.1
