### ISSUE TITLE
Hello What is this wired error for me in response 

### ISSUE THREAD

**Issue by githubtagh** [yajra/laravel-datatables#1923]
### Summary of problem or feature request
DataTables warning: table id=mytable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

### Look at response start with letter W

w{"draw":1,"recordsTotal":500,"recordsFiltered":500,"data":[{"id":"500","name_en":"United States Minor Outlying Islands","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"499","name_en":"Nepal","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"498","name_en":"Greece","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"497","name_en":"Burundi","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"496","name_en":"Lesotho","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"495","name_en":"Angola","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"494","name_en":"Guatemala","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"493","name_en":"Czech Republic","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"492","name_en":"India","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null},{"id":"491","name_en":"Peru","name_ar":"\u0627\u0644\u0628\u0644\u062f \u0628\u0627\u0644\u0639\u0631\u0628\u0649","created_at":"2018-11-25 09:31:12","updated_at":"2018-11-25 09:31:12","deleted_at":null}],"queries":[{"query":"select count(*) as aggregate from (select '1' as `row_count` from `countries`) count_row_table","bindings":[],"time":10},{"query":"select * from `countries` order by `id` desc limit 10 offset 0","bindings":[],"time":3}],"input":{"draw":"1","columns":[{"data":"id","name":"id","searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"name_en","name":"name_en","searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"name_ar","name":"name_ar","searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}}],"order":[{"column":"0","dir":"desc"}],"start":"0","length":"10","search":{"value":null,"regex":"false"},"_":"1543138665057"}}

### System details

- Operating System Windows 7
- PHP Version 7.2
- Laravel Version 5.7
- Laravel-Datatables Version 8.x

**Comment by yajra** [comment]
Your vendor files might be accidentally edited? Try deleting the vendor folder then `composer install` again.
