### ISSUE TITLE
please show tut in ver 8

### ISSUE THREAD

**Issue by vahidalvandi** [yajra/laravel-datatables#1924]
### Summary of problem or feature request
hello , please update this tutorial in v8 

http://dt54.yajrabox.com/buttons/eloquent

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by MeduNeter93** [comment]
For  real it will be very helpful

**Comment by vahidalvandi** [comment]
thank you
