### ISSUE TITLE
Fluent Join approach question

### ISSUE THREAD

**Issue by SelimSalihovic** [yajra/laravel-datatables#193]
So this is the situation. I have a users table and a countries table. The users table has a country_id field to show their country. The countries table is populated with countries (iso code, name etc.). Now I need to have the table be filterable by the user names and country names.

So as in the fluent example I am doing this in the controller function  that handles the ajax requests
```
$users = DB::table('users')->join('countries', 'users.country_id', '=', 'countries.id')
    ->select(['users.id', 'users.name', 'users.surname', 'users.nickname', 'users.email', 'countries.name',      'countries.id']);

return Datatables::of($users)->make(true);
```

At the page bottom I have this script:

```
<script type="text/javascript">
        $(function() {
            $('#users').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ url("users/datatable") }}',
                columns: [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'surname', name: 'surname'},
                {data: 'nickname', name: 'nickname'},
                {data: 'email', name: 'email'},
                {data: 'name', name: 'countries.name'}
            ]
            });
        });
    </script>
```

The data gets loaded initially into the table, but once I search I get a 500 response with Laravel. This is the full error message:

![screen shot 2015-09-18 at 17 09 44](https://cloud.githubusercontent.com/assets/3939551/9962832/1dedb07c-5e28-11e5-9778-0f0f6b16c15a.png)

Did you have any similar cases? Is the problem that it does not know which id it should reference?

**Comment by yajra** [comment]
See this as ref: https://github.com/yajra/laravel-datatables/issues/7. Basically, you need to use `table.name` pattern on your js like `data: 'id', name:'users.id'`.
