### ISSUE TITLE
Parent model data is being overridden

### ISSUE THREAD

**Issue by amir751020** [yajra/laravel-datatables#1933]
### Summary of problem

I've been using this package for a while, and I've had multiple implementations of the datatable with similar codes. Until this scenario happened to me:

There are 3 models in here, CardTransfer, Center, User. A card transfer belongs to one center and one user.

### Code snippet of problem

This is the js columns:
```
            {data: 'center.name'},
            {data: 'user.name'},
            {data: 'price'},
            {data: 'transferred_at'},
            {data: 'src_card'},
            {data: 'dst_card'},
            {data: 'created_at', name:'created_at'},
            {data: 'apply', searchable: false, orderable: false}
```

And this is the backend code:
```
                return DataTables::of(CardTransfer::with(['user', 'center']))
                ->addColumn('apply', function ($transfer) {
                    return $transfer->confirmed_at ? 'اعمال شده' :
                        DataTable::anchorTag('#', 'اعمال',
                            ['class' => 'submit', 'data-id' => $transfer->id], '_self');
                })->editColumn('transferred_at', function ($transfer) {
                    return jdate($transfer->transferred_at)->toString();
                })->editColumn('created_at', function ($transfer) {
                    return jdate($transfer->created_at)->toString();
                })->rawColumns(['apply'])->toJson();
```

A screenshot of the debugging:
http://swifi.ir/d1.png

As you can see, center data and card_transfer data has been merged, and similar columns (id, created_at, updated_at, has been replaced by the center value)

But if I replace my code with this:
```
                return DataTables::collection(CardTransfer::with(['user', 'center'])->get())
                ->addColumn('apply', function ($transfer) {
                    return $transfer->confirmed_at ? 'اعمال شده' :
                        DataTable::anchorTag('#', 'اعمال',
                            ['class' => 'submit', 'data-id' => $transfer->id], '_self');
                })->editColumn('transferred_at', function ($transfer) {
                    return jdate($transfer->transferred_at)->toString();
                })->editColumn('created_at', function ($transfer) {
                    return jdate($transfer->created_at)->toString();
                })->rawColumns(['apply'])->toJson();
```
It will work just fine.
A little help would be appreciated here.

### System details

- Windows 10
- PHP 7.2.7
- Laravel 5.7.17
- Laravel-Datatables 8.13.1

**Comment by timurlan156** [comment]
> You need to add `CardTransfer::with(['user', 'center'])->select('card_transfers.*)` when using eager load to avoid this issue. See https://datatables.yajrabox.com/eloquent/relationships for some ref.

Unfortunately the DOC url **yajrabox.com no more available**. Pls fix it. Thank you very much!
