### ISSUE TITLE
Stuck at "processing" - Conflict with vuejs

### ISSUE THREAD

**Issue by sreenadh** [yajra/laravel-datatables#1937]
If I comment out the below line in app.js it works.
//window.Vue = require('vue');

laravel/framework                     v5.7.19     The Laravel Framework.
yajra/laravel-datatables-oracle       v8.13.1     jQuery DataTables API for Laravel 4|5

**Comment by yajra** [comment]
Hmm, not sure on this one. I am using vue along with dataTables just fine. Any errors on console?

**Comment by amaurycid** [comment]
Same happens to me! No errors in console.

**Comment by ricklambrechts** [comment]
Same problem.

After commenting all Vue stuff in app.js, it works.

**Comment by ricklambrechts** [comment]
After moving app js from head to body. I don't have any problem.
`    
    <script src="{{ asset('js/app.js') }}"></script>

    @stack('scripts')
</body>`
