### ISSUE TITLE
Collections: Sorting by raw field not edited column

### ISSUE THREAD

**Issue by timothymarois** [yajra/laravel-datatables#1941]
I bet this has been asked a lot,

but I can not **sort the columns based on the raw fields/values**, it always sorts based on the edited column which is bad in the sense you can throw a lot of garbage inside the output of edited columns, yet you do not want to sort that nonsense. Like Html. 

I am also talking about Collection sorting, not database sorting. 

Using `$table->order()` still just works with the edited columns.

**Comment by ridwantanjung** [comment]
why is it still no answer? did you find a solution @timothymarois ?

**Comment by ridwantanjung** [comment]
why is it still no answer? did you found a solution @timothymarois ?
