### ISSUE TITLE
Documentation links broken (http://www.yajrabox.com)

### ISSUE THREAD

**Issue by jayenn007** [yajra/laravel-datatables#1943]
### Summary of problem or feature request

http://www.yajrabox.com is down - is there a mirroe site?

Thanks,

Jay

**Comment by erikcmcollective** [comment]
Server down again I guess?

**Comment by timurlan156** [comment]
+1. Server's still down. Guess there's no mirror sites... Pls help.

**Comment by sstepanovvl** [comment]
+1

**Comment by gebaiwan** [comment]
https://webcache.googleusercontent.com/search?q=cache:a01NtrM2wFgJ:https://datatables.yajrabox.com/+&cd=3&hl=zh-CN&ct=clnk&gl=hk

**Comment by kinnedev** [comment]
Does anyone know if this project is no longer going to be maintained?

**Comment by timothymarois** [comment]
@kinnedev I would also like to know the answer to that as well. I've just implemented on one of my projects since there isn't anything else out there that has this functionality. (so far that I've seen). 

I know it been a holiday, so maybe the author is out. But in a month or so without response, have to decide if it needs to be forked.

**Comment by jayenn007** [comment]
> 
> 
> https://web.archive.org/web/20180317203838/http://yajrabox.com:80/docs/laravel-datatables/master

@endelson: thanks a lot, that link seems to be working and helps for now. 
@timothymarois: same here,I hope jayra comes back and continues the good work

**Comment by ridaamirini** [comment]
> @kinnedev I would also like to know the answer to that as well. I've just implemented on one of my projects since there isn't anything else out there that has this functionality. (so far that I've seen).
> 
> I know it been a holiday, so maybe the author is out. But in a month or so without response, have to decide if it needs to be forked.

Yes i am with u. There many of us that are using this.

**Comment by yajra** [comment]
Happy holidays! Having an issue with the server. Will try to fix this asap.

**Comment by kinnedev** [comment]
@yajra Happy Holidays! No worries, let us know if we can help in anyway. Thanks!

**Comment by yajra** [comment]
Server fixed. Special thanks to my friend @ChaosPower! 🍻

**Comment by ridaamirini** [comment]
@yajra what do u think about the idea of an offline docs or a GitHub Wiki?

**Comment by yajra** [comment]
It's already on github. https://github.com/yajra/laravel-datatables-docs

**Comment by ridaamirini** [comment]
@yajra ok sorry didn’t know that

**Comment by vahaash** [comment]
@yajra would you mind helping me out about the offline script of datatables

    <script src="https://datatables.yajrabox.com/js/jquery.min.js"></script>
    <script src="https://datatables.yajrabox.com/js/bootstrap.min.js"></script>
    <script src="https://datatables.yajrabox.com/js/jquery.dataTables.min.js"></script>
    <script src="https://datatables.yajrabox.com/js/datatables.bootstrap.js"></script>
    <script type="text/javascript">

**Comment by yajra** [comment]
@vahaash use the cdn at https://cdn.datatables.net/.

**Comment by vahaash** [comment]
Thanks @yajra!! Helped me a lot! More power 👍

**Comment by rogersantosferreira** [comment]
Hi @yajra! 
Is your domain yajrabox.com down?

Thx in advance...

**Comment by Bojoofu** [comment]
Yeah, seems to be down again.
