### ISSUE TITLE
Search on custom column created using raw query

### ISSUE THREAD

**Issue by harmanlgz** [yajra/laravel-datatables#1945]
### Summary of problem or feature request

Hi, I have added a custom column to my datatable using a raw query. I'm able to sort this column, however, I'm having trouble searching on it. I have tried using filterColumn() too, it still doesn't work probably because the query is complex. Please suggest a workaround to make the global search work on this column.

/************************************************************************************/

This is my PHP code snippet : 

    public function ordersList(ValidateOrdersListInputRequest $request){
        $orders = $this->_getOrdersTableQuery($request);
        $datatables = Datatables::of($orders)
                ->addColumn('type_label', function($order){
                    return $order->type_label;
                })
                ->addColumn('status_label', function($order){
                    return $order->status_label;
                })
                ->addColumn('pickup_time_label', function($order){
                    return $order->pickup_time_label;
                })
                ->addColumn('actions', function($order) {
                    return $order->action_buttons;
                })
                ->make(true);
        return $datatables;
    }
    
    private function _getOrdersTableQuery($request){
        return Order::whereIn('orders.status',config('constant.main_orders_list_status'))
                ->where(function($query)use($request){
                    if($request->has('startdate') && $request->has('enddate')){
                        $query->whereBetween('orders.created_at', [$request->start, $request->end]);
                    }
                })
                ->leftJoin('users', 'users.id', '=', 'orders.user_id')
                ->leftJoin('order_items', 'order_items.order_id', '=', 'orders.id')
                ->leftJoin('payment_adjustments', 'payment_adjustments.order_id', '=', 'orders.id')
                ->where('order_items.deleted_at', null)
                ->selectRaw('orders.*, users.name as user_name, users.phone as phone')
                ->selectRaw('ROUND((SUM(order_items.price) + SUM(order_items.service_fee) + SUM(order_items.shipping) + SUM(order_items.shipping_service_fee) + SUM(order_items.tax) + COALESCE(SUM(payment_adjustments.amount),0)),2) as summary_total')
                ->groupBy('orders.id');
    }

/************************************************************************************/

jQuery : 

            var table = $('#orders-table').DataTable({
                    processing: true,
                    serverSide: true,
                    pageLength: 800,
                    ajax: {
                        url: '{{ route("admin.orders.list") }}',
                        type: 'get',
                        data: function(d) {
                            d.startdate = $('#startdate').val();
                            d.enddate = $('#enddate').val();
                        },
                        error: function (err) {
                            sweetAlert('Oops...',getErrorMessage(err.responseJSON ? err.responseJSON : "Something went wrong." ));
                        }
                    },
                    columns: [
                        {data: 'uuid', name: 'uuid', sortable: false},
                        {data: 'user_name', name: 'users.name'},
                        {data: 'phone', name: 'users.phone', sortable: false},
                        {data: 'type_label', name: 'type', sortable: false},
                        {data: 'summary_total', name: 'summary_total'},
                        {data: 'status_label', name: 'status'},
                        {data: 'pickup_time_label', name: 'pickup_time'},
                        {data: 'created_at', name: 'created_at'},
                        {data: 'actions', sortable: false, searchable: false},
                    ],
                    "order": [[ 7, "desc" ]],
                    searchDelay: 500
            });

/************************************************************************************/

- Operating System : Ubuntu 16.04.5 LTS
- PHP Version : 7.1.23
- Laravel Version : 5.2
- Laravel-Datatables Version : 6.0

**Comment by yajra** [comment]
For complex queries, I usually test it first on SQL level. If it's doable on SQL level, you just then need to convert it to laravel way.

**Comment by hazem-taha** [comment]
@yajra 
Can you please clarify your answer, what do you mean by converting it to Laravel way ?

**Comment by yajra** [comment]
I mean something like a raw sql to builder form.

FROM:
```sql
select * from users where id=1;
```

TO:
```php
DB::table('users')->where('id', 1);
```
