### ISSUE TITLE
Requested unknown parameter 'DT_Row_Index' for row 0, column 1

### ISSUE THREAD

**Issue by phoenixrever** [yajra/laravel-datatables#1947]
### Summary of problem or feature request

Requested unknown parameter 'DT_Row_Index' for row 0, column 1

### Code snippet of problem

in laravel controller:

```
        return Datatables::of($users)
            ->addIndexColumn()
            .....
            ->make(true);
```
in js:
     `  {data: 'DT_Row_Index',name: 'DT_Row_Index', orderable: false, searchable: false},`

this worked before. don't konw how to fix it!

**Comment by JinalSomaiya** [comment]
@phoenixrever use `{data: 'DT_RowIndex', orderable: false, searchable: false}`.

**Comment by yajra** [comment]
@phoenixrever `DT_Row_Index` was renamed to `DT_RowIndex ` to follow the naming convention of DataTables. @JinalSomaiya answer should fix this.

**Comment by ubaidillahSriyudi** [comment]
> 
> 
> @phoenixrever `DT_Row_Index` was renamed to `DT_RowIndex ` to follow the naming convention of DataTables. @JinalSomaiya answer should fix this.

Thanks, it works
