### ISSUE TITLE
Can't Install it on Laravel 5.7.19

### ISSUE THREAD

**Issue by jeraldpunx** [yajra/laravel-datatables#1948]
I want to try this on Laravel v5.7.19, but it shows me this after I run the command
![image](https://user-images.githubusercontent.com/5249781/50547104-2fd5fe00-0c6e-11e9-83c8-8dd27662acf1.png)

**Comment by jeraldpunx** [comment]
also where should I follow?
https://github.com/yajra/laravel-datatables/blob/8.0/README.md

or 

https://yajrabox.com/docs/laravel-datatables/master/installation

**Comment by yajra** [comment]
Maybe try using `^8.13` version constraint.
