### ISSUE TITLE
[Help] v6.0 DataTables as Service

### ISSUE THREAD

**Issue by yajra** [yajra/laravel-datatables#195]
Hey Guys,

Need help on testing ~~v6.0.0-alpha~~ v6.0 version of datatables. This version will have the following features:

- Provides DataTable Service.
- Provides artisan command for creating a service. `php artisan datatables:make UsersDataTable`
- Provides artisan command for creating a DataTable scope. `php artisan datatables:scope ActiveUserScope`
- Provides built-in support for server-side buttons. (Formerly TableTools).
   - Available buttons are csv, excel, pdf, print.
   - Built-in support for exporting to CSV, EXCEL and PDF using Laravel-Excel.
   - Built-in printer friendly view or create your own by overriding printPreview() method.

I also created a [quick tutorial](http://datatables.yajrabox.com/service) on how to implement this new features. 

Feedbacks/suggestions are welcome.

Thanks in advance.

@yajra

**Comment by yajra** [comment]
For those interested to help. Please use `dev-develop` branch instead. Will keep pushing bug fixes/patches on that branch. Thanks!

**Comment by jwtoler** [comment]
How would we extend the buttons to create our own actions like the default JS allows? What about buttons for extending Editor?

**Comment by yajra** [comment]
For custom button actions, I think we just need to create a new `custom-buttons.js` file that will just extend the defaults. Just include the custom buttons after `buttons.server-side.js` and I guess it would register the custom as the default button action.

For editor, I don't have any idea on it atm as my trial copy already expired and haven't played with it at all. :(

**Comment by jwtoler** [comment]
Well I mean really wouldn't a function that accepted a JSON encoded variable work for editor actions? 
The create, edit,  remove is what would be really awesome.

https://editor.datatables.net/examples/extensions/exportButtons.html
or
allow the action function
https://datatables.net/extensions/buttons/custom

**Comment by yajra** [comment]
I kinda get what you mean. I was thinking of it too but one thing I can't figure out is how I can send a function from php/json to js. Currently, what I am doing is I create a js for the custom button and include it on the `html` builder function like:

```js
(function ($, DataTable) {
    "use strict";
    DataTable.ext.buttons.receive = {
        className: 'buttons-receive',

        text: function (dt) {
            return dt.i18n('buttons.receive', 'Received');
        },

        action: function (e, dt, button, config) {
            var rows = dt.rows({selected: true}).data().pluck('id');
            var selected = [];
            for (var i=0; i < dt.rows({selected: true}).count(); i++) {
                selected.push(rows[i]);
            }

            if (!confirm('Confirm?')) {
                return;
            }

            $.post('post-receive', {id: selected}, function(json) {
                dt.ajax.reload();
            });
        }
    };
})(jQuery, jQuery.fn.dataTable);
```

```php
public function html()
{
    return $this->builder()
        ->columns([
            'id',
            'name',
            'email',
            'created_at',
            'updated_at',
        ])
        ->parameters([
            'dom' => 'Bfrtip',
            'buttons' => [
                    [
                        'extend'  => 'collection',
                        'text'    => 'Export',
                        'buttons' => [
                            'csv',
                            'excel',
                            'pdf',
                            'print',
                        ],
                    ],
                    'reset',
                    'reload',
                    'release',
                ],
        ]);
}
```

If you have an editor, then just extend it as it is on js and convert to as a php array. I hope what I'm saying makes sense as I am still adopting on buttons and editor too. LOL.

**Comment by jwtoler** [comment]
Actually no I don't really get you mean extend on JS and send to php? Lol

- Justin Toler

**Comment by yajra** [comment]
Lol. Let me try to explain it using an example. ^_^

On js file, buttons parameters are set like below:
```js
buttons: [
            { extend: 'create', editor: editor },
            { extend: 'edit',   editor: editor },
            { extend: 'remove', editor: editor },
            {
                extend: 'collection',
                text: 'Export',
                buttons: [
                    'copy',
                    'excel',
                    'csv',
                    'pdf',
                    'print'
                ]
            }
        ]
```

We can convert this to php by using array.
```php
'buttons' => [
    [ 'extend' => 'create', 'editor' => 'editor' ],
    [ 'extend' => 'edit',   'editor' => 'editor' ],
    [ 'extend' => 'remove', 'editor' => 'editor' ],
    [
        'extend' => 'collection',
        'text' => 'Export',
        'buttons' => [
            'copy',
            'excel',
            'csv',
            'pdf',
            'print'
        ]
    ]
]
```

One thing though, I don't know how to passed a value on json response from php as an equivalent function to javascript. Like if we want to override the `action` function of button via server-side script.

```js
$.fn.dataTable.ext.buttons.reload = {
    text: 'Reload',
    action: function ( e, dt, node, config ) {
        dt.ajax.reload();
    }
};
```
To **PHP**?
```php
'buttons' => [
    'text' => 'Reload',
    'action' => function ( e, dt, node, config ) {
        dt.ajax.reload();
    }
]
```

**Comment by jwtoler** [comment]
This is what I ended up doing for now.
```
DataTable.ext.buttons.create = {
        action: function (e, dt, button, config) {
            dt.editor()
                .buttons([
                    'Create',
                    { label: 'Cancel', fn: function () { this.close(); } }
                ]).create();
        },
        text: function (dt) {
            return dt.i18n('buttons.create', 'Create');
        }
    };

    DataTable.ext.buttons.edit = {
        action: function (e, dt, button, config) {
            dt.editor()
                .buttons([
                    'Edit',
                    { label: 'Cancel', fn: function () { this.close(); } }
                ]).edit( dt.rows({ selected: true }));
        },
        text: function (dt) {
            return dt.i18n('buttons.edit', 'Edit');
        }
    };

    DataTable.ext.buttons.remove = {
        action: function (e, dt, button, config) {
            dt.editor()
                .buttons( 'Confirm delete' )
                .message( 'Are you sure you want to remove this row?' )
                .remove( dt.rows({ selected: true }));
        },
        text: function (dt) {
            return dt.i18n('buttons.remove', 'Remove');
        }
    };
```

```
'buttons' => [
                    [ 'create', 'edit', 'remove'],
                ]
```

**Comment by MatiasSW** [comment]
Awesome feature (Y)
Is it possible to access the Data Serices from a controller? Avoiding the usage of UsersDataTable class

**Comment by yajra** [comment]
Unfortunately, I think it's not possible not to use UsersDataTable class because all the magic are stored on `yajra\Datatables\Services\DataTable` class. That is also the main reason why I planned to release this as v6.x as the flow/style will significantly change from v5.x.

Yes, I will be using datatables scope and extract most of the functions that are previously done on Controller to DataTable class. This way, our controller's footprint will be as small as single line of code in a method.

Lastly, thanks for showing interest on this planned new features. ^_^

**Comment by rogierborst** [comment]
Is there a reason for returning the `queries` object in the Ajax call? I'm not too fond of giving away this much database info to the world.

**Comment by yajra** [comment]
@rogierborst, it's for debugging purposes. You can turn it off by setting `debug=false` or update your `.env` file.

**Comment by Evertt** [comment]
Hey I have a question with this new service thing. Is it possible for me to tell datatables to concatenate a few columns into one? I want to concatenate the columns `name`, `infix` and `surname` into one column called `artist`. How do I let the service know I want to do that?

**Comment by haakym** [comment]
@Evertt I hope I understood your question, I believe you can do this via the fractal transformer. Have you tried this yet?

**Comment by yajra** [comment]
All, 

FYI: I have created a [6.0 branch](https://github.com/yajra/laravel-datatables/tree/6.0) for this release. You can now use `"yajra/laravel-datatables-oracle": "6.*"` on your composer to directly download in that branch. Once a stable version is released, doing a composer update will automatically load the stable version. Thanks!

**Comment by eugenevdm** [comment]
I read this post with interest. I'm still new to DataTables and your API and I'm trying to understand buttons and front-end versus server side buttons.

I tried using the buttons *without* "DataTables as a Service Implementation" and I notice that both CSV and Excel gives JSON output instead of the real thing.

I am therefore correct in saying that should I wish to use to export to CSV and Excel using your API that I *must* use DataTables as a service?

Or can CSV and Excel buttons work without using the service?

**Comment by sandeepv** [comment]
Hi @yajra ,

I want to add Export button to data tables here is my code 

$('#users-table').DataTable({
            dom:'Bfrtip',
	        processing: true,
	        serverSide: true,
            crossDomain: true,
	        ajax: site_url+'/admin/roles-data',
	        columns: [
		        {data: 'id', name: 'id'},
		        {data: 'name', name: 'name'},
		        {data: 'display_name', name: 'display_name'},
		        {data: 'description', name: 'description'},
		        {data: 'created_at', name: 'created_at'},
		        {data: 'updated_at', name: 'updated_at'},
		        {data: 'action', name: 'action', orderable: false, searchable: false}
	    	],
            buttons: [
                {
                    extend: 'collection',
                    text: 'Export',
                    buttons: [
                        'copy',
                        'excel',
                        'csv',
                        'pdf',
                        'print'
                    ]
                }
            ]
	    });

Please help...! Thanks
