### ISSUE TITLE
Got error on Helper.php:197

### ISSUE THREAD

**Issue by aurelijussaldauskas** [yajra/laravel-datatables#1951]
### Summary of problem
After upgrading from version 8.13.1 to 8.13.2 datatables stopped working. 
I get error "ErrorException: Object of class stdClass could not be converted to string in C:\laragon\www\system\vendor\yajra\laravel-datatables-oracle\src\Utilities\Helper.php:197"

Stack trace: 
C:\laragon\www\system\vendor\yajra\laravel-datatables-oracle\src\Utilities\Helper.php(197): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Object of class...', 'C:\\laragon\\www\\...', 197, Array)
C:\laragon\www\system\vendor\yajra\laravel-datatables-oracle\src\Utilities\Helper.php(180): Yajra\DataTables\Utilities\Helper::transformRow(Array)
[internal function]: Yajra\DataTables\Utilities\Helper::Yajra\DataTables\Utilities\{closure}(Array)
C:\laragon\www\system\vendor\yajra\laravel-datatables-oracle\src\Utilities\Helper.php(179): array_map(Object(Closure), Array)
C:\laragon\www\system\vendor\yajra\laravel-datatables-oracle\src\DataTableAbstract.php(684): Yajra\DataTables\Utilities\Helper::transform(Array)
C:\laragon\www\system\vendor\yajra\laravel-datatables-oracle\src\QueryDataTable.php(95): Yajra\DataTables\DataTableAbstract->transform(Object(Illuminate\Database\Eloquent\Collection), Array)
C:\laragon\www\system\app\DataTables\FormDataTable.php(122): Yajra\DataTables\QueryDataTable->make(true)
[internal function]: App\DataTables\FormDataTable->ajax()

### Code snippet of problem

FormDataTable.php:122 code: 
```php
return $datatable->make(true);
```

### System details

- Windows
- PHP 7.3.0
- Laravel 5.6.39
- Laravel-Datatables 8.13.2

### Solution
Downgraded to version 8.13.1

**Comment by yajra** [comment]
Thanks for reporting, https://github.com/yajra/laravel-datatables/pull/1942 caused the issue. Checking..

**Comment by yajra** [comment]
Can you please test if reverting this line https://github.com/yajra/laravel-datatables/pull/1942/files#diff-95e51f0625379b2c727a4130e4d3c3edL158 will fix the issue?

**Comment by yajra** [comment]
Hmm, that's the only changed done on helper file. Can you please paste some snippet to reproduce the issue? Thanks!

**Comment by aurelijussaldauskas** [comment]
I tried to reverse #1942 commit and when I have reverted the line
```php
settype($arrayDot[$key], $dataType);
```
in src/Processors/DataProcessor.php file then datatables started working again.

**Comment by ridaamirini** [comment]
@aurelijussaldauskas Thats strange why this line would cause such an error.

Can u pls paste a snippet to reproduce this. Like @yajra said.

**Comment by yajra** [comment]
@ridaamirini reverting your PR for now until we found what causes this issue. @aurelijussaldauskas please provide some snippets to reproduce the issue and will try to add a tests for it along with casted attributes PR.

**Comment by aurelijussaldauskas** [comment]
I have upgraded to current version and problem no longer appears...

**Comment by ridaamirini** [comment]
@aurelijussaldauskas Can you pls post some code to reproduce?

**Comment by ridaamirini** [comment]
> Can you please test if reverting this line https://github.com/yajra/laravel-datatables/pull/1942/files#diff-95e51f0625379b2c727a4130e4d3c3edL158 will fix the issue?
> 
> ```
> $data = $row instanceof Arrayable ? $row->toArray() : (array) $row;
> ```

I test some cases out and the only line that causes the issue is this. But i can't be 100% sure if @aurelijussaldauskas  doesn't post a snippet

**Comment by alasdairgallacher** [comment]
Hey guys, spent about an hour trying to see there is any sort of fix.
@yajra after reading comment:

> Can you please test if reverting this line https://github.com/yajra/laravel-datatables/pull/1942/files#diff-95e51f0625379b2c727a4130e4d3c3edL158 will fix the issue?
> 
> ```
> $data = $row instanceof Arrayable ? $row->toArray() : (array) $row;
> ```

I wondered if it was actually and instance implementing Arrayable.
So I came across this article: https://stackoverflow.com/a/49760738/13174315

I've sadly not got enough time to go deep into this.
However, I hope this helps in some way :/

**Comment by fayaz668** [comment]
try this 
return \DataTables::eloquent(Users::where('isActive',1))
      ->rawColumns(['id'])
      ->make(true);
