### ISSUE TITLE
Way to disable ordering on column in EloquentDataTable

### ISSUE THREAD

**Issue by Mapteg34** [yajra/laravel-datatables#1953]
### Summary of problem or feature request

EloquentDataTable can create new columns with addColumn, and can disable ordering on it by send false in last param. But no way to disable ordering in exists column. ->orderColumn(id,false) no changes, editColumn has no params. How to fix it? 

Problem in json fields, they are not sortable on pgsql... But in interface they has sort function. When user try it - error created.

### Code snippet of problem

```php
$res = datatables()->eloquent(User::query);
/* need */
$res->disableOrder('json_field'); // or ['filed1', 'field2', ...]
return $res->make(true);
```

**Comment by yajra** [comment]
On your javascript, just set `{data: 'json_field', orderable => false}`.

**Comment by Mapteg34** [comment]
> On your javascript, just set `{data: 'json_field', orderable => false}`.

Yes, i can disable ordering on client side. By this ticket about server side. We can create field without ordering, but can't disable order on existing field.

**Comment by Mapteg34** [comment]
> I see, I think we have no feature like that atm. Maybe a workaround would be by using
> `->orderColumn('json_field', '')`?

This half solution. Yes, it resolve error, and order not working (tested). But on interface field has orderable, and can trigger order event by click.

Best solution may be add support FALSE orderColumn parameter value, that set FALSE on input.columns.<colid>.orderable parameter in json response.
