### ISSUE TITLE
Ordering on custom rows 

### ISSUE THREAD

**Issue by moda20** [yajra/laravel-datatables#1955]
### Summary of problem or feature request

I want to order custom added rows, if i do it the usual way i get an SQL error since the custom rows don't exist in the database. 

if it was not on serverside the sorting would be done by ordering the unsortable columns and sort the numeric or alphanumeric columns. 

### Code snippet of problem

i add columns based on ajax requests and others based on html templates

```php
->addColumn('payload', function ($customer){
                $response = $this-AjaxRequest($customer);
                $customer->payload = $response->payload;
                return $customer->payload;
            })
```

### System details

- Operating System linux ubuntu 18.04 LTS
- PHP Version 7.2
- Laravel Version 5.5
- Laravel-Datatables Version 6.0

**Comment by yajra** [comment]
Unfortunately, this may not be possible when using SQL. DataTables should be able to handle most cases as long as it's doable via SQL.

A work-around maybe is to use a collection. However, it is not advisable to use if you have a large dataset.
