### ISSUE TITLE
How to escase a string in laravel-datatables-oracle table?

### ISSUE THREAD

**Issue by OrlandoUllrich** [yajra/laravel-datatables#1956]
### Summary of problem or feature request

Hello,

In my laravel 5.7 app I use laravel-datatables-oracle": "^8.7"
and defining js function on confirmation of deletion I call ja function like
            ->editColumn('action_delete',
                '<a href="#" onclick="javascript:backendPageContent.deletePageContent({{$id}},\'{{$title}}\')"><i class="fa fa-remove a_link"></i></a>')
            ->rawColumns(['action', 'action_delete'])
It works ok, until in $title happen “'” char and it raise error.

Usually in my laravel/jquery apps I use method json_encode in such cases, but here i tried like
            ->editColumn('action_delete',
//                '<a href="#" onclick="javascript:backendPageContent.deletePageContent({{$id}},json_encode(\'{{$title}}\'))"><i class="fa fa-remove a_link"></i></a>')
                '<a href="#" onclick="javascript:backendPageContent.deletePageContent({{$id}},\'{{  json_encode($title)  }}\'))"><i class="fa fa-remove a_link"></i></a>')
            ->rawColumns(['action', 'action_delete'])

But in both cases I failed. Which is right way ?

Thanks!

### System details

- Operating System Kubuntu
- PHP Version  7.2
- Laravel Version 5.7
- Laravel-Datatables Version 8.7

**Comment by OrlandoUllrich** [comment]
Sorry, your answer is not clear. Could you please to give a small example or reference to such example ?

**Comment by yajra** [comment]
Something like:

```php
->addColumn('action__delete', '<button class="delete">Del</button>')
->rawColumns(['action_delete']);
...

// js
$('table').on('click', '.delete', function() {
    alert('test');
})
```
