### ISSUE TITLE
datatable button and excel problem

### ISSUE THREAD

**Issue by arbabi2010** [yajra/laravel-datatables#1958]
### Summary of problem or feature request

I want to use datatable as service on v7 for laravel 5.5 and that need to laravel button . and also i want to  use Maatwebsite\Excel version 3 . when i install datatable i get this error
 yajra/laravel-datatables-buttons v3.0.0 requires maatwebsite/excel ^2.0
how can i use datatable as service with button package and maatwebsite/excel 3 ?

### Code snippet of problem

- PHP Version 7
- Laravel Version 5.5
- Laravel-Datatables Version 7

**Comment by yajra** [comment]
You need to use v8 if you want to use excel v3.
