### ISSUE TITLE
Server Side Smart Filtering

### ISSUE THREAD

**Issue by Redshift-Web-Design** [yajra/laravel-datatables#196]
Hey guys.

Has anyone managed to pull this off yet?

http://www.datatables.net/forums/discussion/3343/server-side-processing-and-regex-search-filter/p1#Item_23

Being a bit of a rookie, I'm not comfortable trying to hack the vendor files to make this happen. Was hoping someone with more skills than I has done so before :-)

Thanks.

**Comment by yajra** [comment]
@Redshift-Web-Design, there was a recent PR for regex support. However, not all database is currently supported. See this PR for ref: https://github.com/yajra/laravel-datatables/pull/152
