### ISSUE TITLE
Service: Method App\DataTables\QuoteDataTable::render does not exist.

### ISSUE THREAD

**Issue by quantumwebco** [yajra/laravel-datatables#1962]
Upgrading from 6.0 to 8.0

Composer.json
```
"laravel/framework": "5.7.*",
 ...
"yajra/laravel-datatables": "^1.0",
"yajra/laravel-datatables-buttons": "4.*",
"yajra/laravel-datatables-html": "4.*"
```

In my controller
```
return $quoteDataTable->render('quotes.index', array(
            'companies' => $companies,
            'statuses' => $stautses,
            'contacts' => $contacts
        ));
```
In my datatable service class
```
use Yajra\DataTables\DataTables;

public function dataTable($query, DataTables $dataTables)
    {
        return $dataTables
            ->eloquent($query)
            ...
            ->make(true);
}
public function query($builder)
    {
        $quotes = Quote::select ...
        ...
        return $this->applyScopes($quotes);
    }
public function html()
    {
        return $this->builder();
}
```
I've tried naming the dataTable() method back to ajax() as in the demo app but no change.

Also, if I don't have the $builder variable passed to the query() method I get an error that the method isn't compatible with the overwritten method.

**Comment by yajra** [comment]
`App\DataTables\DataTable` is not a valid class. 

Import should be `use Yajra\DataTables\Services\DataTable;`

**Comment by quantumwebco** [comment]
App\DataTables\DataTable was just an example. It's actually App\DataTables\QuoteDataTable; 

In my controller is
```
use App\DataTables\QuoteDataTable;
class QuoteController extends AppBaseController
{
    public function index(QuoteDataTable $quoteDataTable)
    {
        try {
            $companies = Company::orderby('company_name', 'ASC')->get();
            $contacts = Contact::orderby('name', 'ASC')->get();
            $stautses = Status::orderby('status', 'ASC')->get();
            return $quoteDataTable->render('quotes.index', array(
                'companies' => $companies,
                'statuses' => $stautses,
                'contacts' => $contacts
            ));
        } catch (\Exception $e) {
            return $e->getMessage();
        }

    }
}
```

in QuouteDataTables is 
```
use Yajra\DataTables\DataTables;
use Yajra\DataTables\Services\DataTable;

class QuoteDataTable extends DataTable
{
public function ajax($query, DataTables $dataTables)
    {
        return $dataTables
            ->eloquent($query)
            ...
            ->make(true);
}
public function query($builder)
    {
        $quotes = Quote::select ...
        ...
        return $this->applyScopes($quotes);
    }
public function html()
    {
        return $this->builder();
}
```
But I get the error 
Declaration of App\DataTables\QuoteDataTable::ajax($query, Yajra\DataTables\Services\DataTable $dataTables) should be compatible with Yajra\DataTables\Services\DataTable::ajax() (0)

Because ajax doesn't take any arguments so how do you pass the query and DataTable class? 

If I change the function to datatable($query, DataTable $dataTables) it works but I get no content in my table and the error in the console says Uncaught TypeError: $(...).DataTable is not a function

Any ideas? Thanks

**Comment by quantumwebco** [comment]
I fixed the js error by moving the datatables.js front end scripts above @stack('scripts') instead of pushing them to it.

But then I got a 500 error **Too few arguments to function App\DataTables\QuoteDataTable::query(), 0 passed and exactly 1 expected**

So I changed it to **public function query($builder = false)** which sorted that issue

Then I get **Argument 2 passed to App\DataTables\QuoteDataTable::datatable() must be an instance of Yajra\DataTables\DataTables, instance of Illuminate\Database\Eloquent\Builder given**
```
public function ajax($query, DataTables $dataTables)
    {
        return $dataTables
            ->eloquent($query)
            ...
            ->make(true);
}
```

**Comment by quantumwebco** [comment]
Swapped the arguments round re: https://github.com/yajra/laravel-datatables/issues/1352

Now getting error **Method Illuminate\Http\JsonResponse::toJson does not exist.**

**Comment by quantumwebco** [comment]
Cloned the **ajax()** function into my QuoteDataTable class and replaced **return $dataTable->toJson();** with **return $dataTable;** which seems to have worked.
