### ISSUE TITLE
Laravel Datatables sometimes not working

### ISSUE THREAD

**Issue by arbnorsalihu** [yajra/laravel-datatables#1963]
### 
I'm using Laravel and Yajra Datatables, but sometimes working sometimes not. 
The only error displaying is DataTables warning: table id=invoices_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7. 
Console Error is : jquery.js:9600, xhr.send( options.hasContent && options.data || null );

But, sometimes it is working well and the data are being displayed.

### 
My blade:
```
             $('#invoices_table').dataTable( {
              processing: true,
            serverSide: true,
            ajax: '{{ route('invoices.getData') }}',
            columns: [
              {data: 'name', name: 'client_id'},
            {data: 'company', name: 'clients.company'},
            {data: 'invoiceDate', name: 'invoices.invoiceDate'},
            {data: 'dueDate', name: 'invoices.dueDate'},
            {data: 'total', name: 'invoices.total'},
            {data: 'status', name: 'invoices.status'}
            ]
      } );
```
My Controller
```
function getData()
    {

       $inv = DB::table('invoices')->join('clients', 'invoices.client_id', '=', 'clients.id')
            ->select(['invoices.id', 'clients.name', 'clients.company', 'invoices.invoiceDate', 'invoices.dueDate', 'invoices.total', 'invoices.status']);

        return Datatables::of($inv)
            ->editColumn('id', 'ID: {{$id}}')
            ->make(true);
    

    }
```
My Route:
Route::get('invoices/getData', 'InvoicesController@getData')->name('invoices.getData');

Thank you

### System details

- Operating System: Windows
- PHP Version: 7.2.10
- Laravel Version : 5.6
- Laravel-Datatables Version: ~8.0

**Comment by yajra** [comment]
You must be using `php artisan serve`. Please avoid using that. See https://github.com/yajra/laravel-datatables#php-artisan-serve-bug
