### ISSUE TITLE
Cant access https://yajrabox.com

### ISSUE THREAD

**Issue by ezani92** [yajra/laravel-datatables#1964]
### Summary of problem or feature request

https://yajrabox.com/docs/laravel-datatables/master/installation

is it your website down?

**Comment by dheiro** [comment]
i think website down (again)

**Comment by OskR219** [comment]
@yajra Hi yajra, Could I get the documentation offline?

**Comment by ksgush1** [comment]
@yajra Looking for your documentation. Please make this a priority.

**Comment by yajra** [comment]
My friend who provides me the hosting is currently out of town and cannot process the billing yet. Hopefully this will be fixed by weekend. Atm, access the docs at https://github.com/yajra/laravel-datatables-docs.

**Comment by roelofjan-elsinga** [comment]
> My friend who provides me the hosting is currently out of town and cannot process the billing yet. Hopefully this will be fixed by weekend. Atm, access the docs at https://github.com/yajra/laravel-datatables-docs.

I see all of your documentation is written in Markdown, excellent! That makes it very easy just to host everything on GitHub pages: https://guides.github.com/features/pages/

**Comment by ACvijic** [comment]
it's down again... :disappointed:

**Comment by nasrulhazim** [comment]
it's down at the moment.

**Comment by maungyehtunzaw** [comment]
it's down again... @yajra

**Comment by nasrulhazim** [comment]
Is it better to just use github page?

**Comment by RiccardoFrancescato** [comment]
The website returns 500 on all pages @yajra

**Comment by yah-ya** [comment]
Its down sir :(

**Comment by maguilarce** [comment]
We really need the yajrabox back very bad @yajra. Is this situation related to this error in my app?

```
$ composer require yajra/laravel-datatables

[Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl extensio
  n, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.
```

**Comment by rezapiryghadim** [comment]
it's down!
:sob::sob::sob:

**Comment by umituz** [comment]
No access to site right now

**Comment by ahmedshahawy** [comment]
I'm sorry, your website is down now please check

**Comment by atapatel** [comment]
Its Down again @yajra . :(

**Comment by a-hussalem** [comment]
Hello
I think the server is down :( 
@yajra

**Comment by vipertecpro** [comment]
I cleared all cache , checked every permission and then i read this threat now i know what to tell my client .

**Comment by andikurnia** [comment]
I think it's better to move your documentation page host into github. It's down again :(

**Comment by vipertecpro** [comment]
If you're having server/hosting problem use mine, i've linux hosting for 2 years, i'm working on freelancing projects and doing job, so lemme know if you need help.

**Comment by yajra** [comment]
Thank you all! Please see https://github.com/yajra/laravel-datatables/issues/2223.

@andikurnia github is not an option as the documentation requires database access and afaik github only allows static pages.

**Comment by tousifahmedah** [comment]
Its down again @yajra.

**Comment by ramsengar** [comment]
Website is down again. 
Any other alternate way to get the documentation?

**Comment by enniosousa** [comment]
Its down again @yajra .

**Comment by yahyaefendy** [comment]
its web for documentation down again @yajra

**Comment by bassem-shoukry** [comment]
Its down  :(

**Comment by blogtj** [comment]
its web for documentation down again @yajra

**Comment by muhammadnm** [comment]
@yajra Really bad time again, website down again .. Please please up and get that running.. we need that..

**Comment by atikbhatti** [comment]
Sir @yajra site down .. not working, please fix that ASAP

**Comment by yajra** [comment]
I will purchase a new 1 year subscription server within the week. Site will be up soon.

Donations are appreciated for those who are willing to help! Thanks 🍻
