### ISSUE TITLE
Update Laravel from 5.1 to 5.7 join, where, ... doesn't exist

### ISSUE THREAD

**Issue by madman99** [yajra/laravel-datatables#1965]
### Summary of problem or feature request

Hi all,
In Laravel 5.1 this snippet worked fine. I've upgradet to Laravel 5.7, I got only Laravel is currently processing. I think the problem is the join, but as the site is down, I don't know where to find information. The table is an ajax request returning the fiche_cam variables and the join. My question, how do I implement the join in Laravel 5.7?

### Code snippet of problem

return Datatables::of(Fiche_cam::select(

            'fiche_cam.user_id',
            'fiche_cam.start_service',
            'fiche_cam.stop_service',
            'fiche_cam.roulement',
            'fiche_cam.notes_sup',
            'fiche_cam.service_garage',
            'fiche_cam.attente_aps',
            'fiche_cam.id',
            'fiche_cam.camionnette',
            'fiche_cam.blocage',
            'fiche_cam.control',
            'users.id AS usersid',
            'users.name AS usersname'

        ))->join('users', 'fiche_cam.user_id', '=', 'users.id')->orderBy('fiche_cam.start_service', 'ASC')->make(true);

### System details

- Mac OS High Sierra and Linux Debian 9 Stretch (production)
- PHP Version: 7.2.10
- Laravel Version: 5.7
- Laravel-Datatables ~8.0

Thanks in advance,

Yves

**Comment by yajra** [comment]
Query proxy callback was removed on latest version. You should chain the join statement on the query clause.

```php
$query = Fiche_cam::select(
        'fiche_cam.user_id',
        'fiche_cam.start_service',
        'fiche_cam.stop_service',
        'fiche_cam.roulement',
        'fiche_cam.notes_sup',
        'fiche_cam.service_garage',
        'fiche_cam.attente_aps',
        'fiche_cam.id',
        'fiche_cam.camionnette',
        'fiche_cam.blocage',
        'fiche_cam.control',
        'users.id AS usersid',
        'users.name AS usersname'
    )
    ->join('users', 'fiche_cam.user_id', '=', 'users.id')
    ->orderBy('fiche_cam.start_service', 'ASC');

return Datatables::of($query)->make(true);
```

**Comment by madman99** [comment]
Thank you, works great ;)
