### ISSUE TITLE
When http://yajrabox.com will fix???

### ISSUE THREAD

**Issue by ravindra42** [yajra/laravel-datatables#1970]
When http://yajrabox.com will fix???

**Comment by armycoder** [comment]
Documentation is kinda important...

**Comment by igerslike** [comment]
Rofl, documentation is really important, not sure why the site remains offline and no one care about. Seems like the original repo owner doesnt care a lot about this project.

You may visit the documentation threw cached pages at  : http://web.archive.org/web/20180409204920/http://yajrabox.com:80/docs/laravel-datatables/master/

**Comment by armycoder** [comment]
yeah @igerslike thats how i'm using it. More info on the owner here. [https://github.com/yajra/laravel-datatables/issues/1964](url)

**Comment by Ravindra54** [comment]
Thank you @igerslike 😀😀

**Comment by yajra** [comment]
Thank you! Please see #2223.
