### ISSUE TITLE
Problem creating column with button

### ISSUE THREAD

**Issue by hestalella-apilogic** [yajra/laravel-datatables#1971]
In my API I have the following code to create my table

`Route::get('products', function () {
    return datatables()
            ->eloquent(App\Product::withTrashed()->with('subgroup'))
            ->addColumn('subgroup', function (App\Product $product) {
                return isset($product->subgroup) ? $product->subgroup->name : "";
            })
            ->addColumn('group', function (App\Product $product) {
                return isset($product->subgroup) ? $product->subgroup->group->name : '';
            })
            ->addColumn('state', function (App\Product $product){
                return ($product->trashed() ? 'INACTIVO' : '');
            })
            ->addColumn('actions', 'products.actions')
            ->rawColumns(['actions'])
            ->toJson();
});`

And my **actions.blade.php** view is

```
<td>
@can('products.edit')
<form method="get" action="{{route('products.edit', $id)}}" style="display: inline;">
    <button type="submit" class="btn btn-sm btn-primary">Editar</button>
</form>
@endcan
</td>
```

The problem is that it does not show the button (actually, it does not even print the form) even when the user has the permissions. Can you please help me?

**Comment by igerslike** [comment]
Why you are adding a <td> in your template? Did you try with a callback function instead ?

` 
->addColumn('actions', function (Foo $foo) {
    return view('actions.blade',['foo' => $foo]);
})`

**Comment by hestalella-apilogic** [comment]
Hi! I delete <td> tag, use a callback function, change can directive to auth()->user()->can with same results.  auth()->user() returns null, I do not understand why. Blade @can directive can be used, right?
