### ISSUE TITLE
Response is casting all attributes to string

### ISSUE THREAD

**Issue by D4ni3lr** [yajra/laravel-datatables#1975]
**Al attributes are being casts as String**

All attributes are being casts  to String, even when the `$casts` attribute is present in the model.

I've tried with

```
Datatables::of(Model::get())->toJson();
Datatables::of(Model::get())->make();
datatables()->of(Model::get())->toJson();
datatables()->of(Model::get())->make();
```
Same result.

When i return `Model::get();`  or  `Model::all();` the attribute types are returned as expected.

**System Details**

- Windows 10
- Apache 2.4
- PHP 7.1
- laravel/framework  v5.5.45
- yajra/laravel-datatables              v1.4.0  Laravel DataTables Complete Package.
- yajra/laravel-datatables-buttons      v4.5.0  Laravel DataTables Buttons Plugin.
- yajra/laravel-datatables-editor       v1.6.1  Laravel DataTables Editor plugin for Laravel 5.5+.
- yajra/laravel-datatables-fractal      v1.3.0  Laravel DataTables Fractal Plugin.
- yajra/laravel-datatables-html         v4.3.1  Laravel DataTables HTML builder plugin for Laravel 5.4+.
- yajra/laravel-datatables-oracle       v8.13.4 jQuery DataTables API for Laravel 4|5

**Comment by D4ni3lr** [comment]
Hi, the problem was introduced in this PR: #1952 in file DataProcessor.php inside the function escapeRow two lines where removed. 

```
// File: src/Processors/DataProcessor.php
...
if (! in_array($key, $this->rawColumns)) {
       $dataType       = gettype($value); 
       $arrayDot[$key] = e($value);
       settype($arrayDot[$key], $dataType);
 }
...
```

**Comment by Thijmen** [comment]
Really waiting for this one, any updates?

**Comment by artemsky** [comment]
any update?

**Comment by bendt-indonesia** [comment]
Same problem here, using PHP 7.2, Laravel 5.8, yajra/laravel-datatables-oracle 9.4.0

**Comment by bendt-indonesia** [comment]
> Hi, the problem was introduced in this PR: #1952 in file DataProcessor.php inside the function escapeRow two lines where removed.
> 
> ```
> // File: src/Processors/DataProcessor.php
> ...
> if (! in_array($key, $this->rawColumns)) {
>        $dataType       = gettype($value); 
>        $arrayDot[$key] = e($value);
>        settype($arrayDot[$key], $dataType);
>  }
> ...
> ```

This works, if i added the two rows back

**Comment by fayaz668** [comment]
Really waiting to fixe this issues, any updates?
