### ISSUE TITLE
I search method like setRowClass for any column

### ISSUE THREAD

**Issue by PetroGromovo** [yajra/laravel-datatables#1976]
### Summary of problem or feature request

Hi all,
In my laravel 5.7 application, using "yajra/laravel-datatables-oracle": "~8.0" library 
I search method like setRowClass, but setting class/style for any column. Are there such method? Can this functionality be implemented in some way ?

**Comment by yajra** [comment]
Maybe this is what you need https://yajrabox.com/docs/laravel-datatables/master/row-options#row-class?

**Comment by PetroGromovo** [comment]
That is just what I asked in my question, that setRowClass applies class for all rows.
I need to set some class for any separate td cell.
Can it be some css trick when setting css class to a whole row, it is applied only for some td columns, say first only?

**Comment by yajra** [comment]
I think that is how the API works (row level) in javascript. If you want to target specific cell then try using css selectors. Or try asking the forum on the main plugin site @ datatables.net.

```
->setRowClass('odd')

...


.odd:nth-child(2) {
  color: #fff
}
```
