### ISSUE TITLE
skipTotalRecords not working when no filtering is applied

### ISSUE THREAD

**Issue by gjm** [yajra/laravel-datatables#1984]
### Summary of problem or feature request

When using ```skipTotalRecords()```, if no filtering is applied, both ```recordsTotal``` and ```recordsFiltered``` fields return ```true``` to the client which causes misbehavior.
 
### Code snippet of problem
```php
class DataTablesController 
{
    // ...

    public function datatable (SomeModel $model) 
    {
        return DataTables::of($model)->skipTotalRecords()->toJson();
    } 
}
```

Here's a response snippet
```json
{
    draw: 3,
    recordsTotal: true,
    recordsFiltered: true,
    ....
}
```

Don't really know how datatables uses these fields to build the table but i get **0** as the filtered record count and **NaN** as the total record count.

_Showing 0 to 0 of 0 entries (filtered from NaN total entries)_

### System details

- Operating System: Ubuntu 18.10
- PHP Version: 7.2
- Laravel Version: 5.7
- Laravel-Datatables Version: 8.0

**Comment by yajra** [comment]
It returns `true` and not 0? Can you please provide the specific version you are using?

**Comment by gjm** [comment]
It's 8.13.3.

composer.lock:
        ...
        {
            "name": "yajra/laravel-datatables-oracle",
            "version": "v8.13.3",
            "source": {
                "type": "git",
                "url": "https://github.com/yajra/laravel-datatables.git",
                "reference": "387512371d3688f3fe1bf75e3e9e53b3d1426736"
            },
            "dist": {
                "type": "zip",
                "url": "
https://api.github.com/repos/yajra/laravel-datatables/zipball/387512371d3688f3fe1bf75e3e9e53b3d1426736
",
                "reference": "387512371d3688f3fe1bf75e3e9e53b3d1426736",
                "shasum": ""
            },
        ...


Gonçalo Marrafa

**Comment by benyaminl** [comment]
Hello. I also experience similliar problem
This's my code 
```php
// @see https://yajrabox.com/docs/laravel-datatables/master/engine-query
        $db = DB::table("mhcustomer", "c")
                ->select(["c.nomor", "kode_hokky", "nama", "telepon_hp", "s.point", "s.point_tier"])
                ->join(DB::raw("(select `s`.`nomormhcustomer`,
                    sum(s.jumlah) as point,
                    sum(s.jumlah_tier) as point_tier
                from
                    tsaldo_membership s
                group by s.nomormhcustomer) as `s`"), "s.nomormhcustomer", "=", "c.nomor");
                
        return DataTables::of($db)        
                ->skipTotalRecords()
                ->setTotalRecords(0)
                // see @https://datatables.yajrabox.com/eloquent/post-column-search
                // see @https://datatables.yajrabox.com/fluent/custom-filter untuk cata SULIT
                // terpaksa kalau kolomnya agregate kaya sum, count, iffnul, dll, tapi kalau ga, pakai get cukup
                // @see https://datatables.yajrabox.com/relation/has-one
                // Itu untuk Kasus Pakai Relationship nambah kolom, jadi ga perlu raw query
                ->setTransformer(function($item){

                    return [
                        'nomor'         => $item->nomor,
                        'kode_hokky'    => $item->kode_hokky,
                        'nama'          => $item->nama,
                        'telepon_hp'    => $item->telepon_hp,
                        'point'         => $item->point,
                        'point_tier'    => $item->point_tier,
                        'tier'          => ''
                    ];
                })
                ->make(true);
```

AND the respond still query aggregate
![image](https://user-images.githubusercontent.com/2817332/75002997-e7dcf080-5498-11ea-96a6-30a55b0c268b.png)

**Comment by hejingyuan199** [comment]
Yes. This is true. But I do not think there is an appropriate solution.
If we do not use skipTotalRecords(), it will set recordsTotal and recordsFiltered as 'true'.

In the file: QueryDataTable.php of folder "/vendor/yajra/laravel-datatables-oracle/src/"

     function: make($mDataSupport=true)
           ...
           $this->prepareQuery()  // This method calls totalCount() --- it will set totalRecords as true if skipTotalRecords() is used.
                                                 //  else, it will call count() to run the query (select count(*) ...)
           ...


     In function: prepareQuery(), after it calls totalCount(), it will call filterRecords().
     If there is not a filter applied, it will set totalRecords to filteredRecords. 
     So they both will be 'true' if skipTotalRecords() is used. 

That is what this happens.

In my case, it will take around 50 seconds to get the JSON data because my SQL statement is quite complex.
But if I used skipTotalRecords(), it will only take 25 seconds, much better. But the pagination will not show correctly because the page does not know how many records in total.

![image](https://user-images.githubusercontent.com/7050357/114820965-32d76700-9e03-11eb-8720-d3e3b4b3ce3f.png)

It has actually 20 entries, could be shown in 2 pages. But it has infinite pages.

If I do not use skipTotalRecords(), there is another way to get the count, which is:
    
    setTotalRecords(DataTables::of($model)->count())

But this is the same as the scenario that we do not use skipTotalRecords() because it will call function 'count()' like what prepareQuery() do.
 

Well, it seems there is not a win-win solution for me use only one query to get both data and totalcount.
