### ISSUE TITLE
No available engine for Illuminate\Database\Query\Expression

### ISSUE THREAD

**Issue by sunthree74** [yajra/laravel-datatables#1985]
### Summary of problem or feature request
No available engine for Illuminate\Database\Query\Expression apeared when i acces the db

### Code snippet of problem

\DB::raw('SELECT * FROM `v_transaksi`');

**Comment by yajra** [comment]
`DB::raw('SELECT * FROM `v_transaksi`')`? Use query builder or collection.

`DB::select('SELECT * FROM `v_transaksi`')`
`DB::table('v_transaksi')`

**Comment by sunthree74** [comment]
i wanna select data from a view
