### ISSUE TITLE
shorten query parameters??

### ISSUE THREAD

**Issue by michaelnguyen547** [yajra/laravel-datatables#1986]
### Summary of problem or feature request

Ajax request includes all column data which i dont want

`https://datatables.yajrabox.com/fluent/custom-filter-data?draw=3&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=id&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=name&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=email&columns%5B2%5D%5Bname%5D=email&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=created_at&columns%5B3%5D%5Bname%5D=created_at&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=updated_at&columns%5B4%5D%5Bname%5D=updated_at&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&name=&email=ad&_=1549932861825`

Ideally, it should look like this

`https://datatables.yajrabox.com/fluent/custom-filter-data?draw=3&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&name=&email=ad&_=1549932861825`

### Code snippet of problem

Example taken from the plugin @ https://datatables.yajrabox.com/fluent/custom-filter

**Comment by yajra** [comment]
It's the default of dataTables. However, you can try emulating the way [minifiedAjax](https://yajrabox.com/docs/laravel-datatables/master/html-builder-minified-ajax) was build. Dig the code to see how it's done. 

Alternatively, you may try using [post method](https://yajrabox.com/docs/laravel-datatables/master/html-builder-post-ajax).

**Comment by michaelnguyen547** [comment]
thanks, I used POST to clean up the query parameters.
