### ISSUE TITLE
DataTables::make(collection) returns empty array into data property

### ISSUE THREAD

**Issue by iam-mishgun** [yajra/laravel-datatables#1987]
### 
For some reason, this method began to return an empty array, although there is data.
Previously, it was the `of` method. If you replace it - it does not work either.

### Code snippet of problem

```php
    $res = new Collection;
    foreach ($data as $company) {
      $company = (object)$company;
      if (gettype($company->properties) === 'array') {
        $company->properties = (object)$company->properties;
      }
      $res->push([
        'id' => $company->id,
        'company_name' => property_exists($company->properties, 'company_name') ? $company->properties->company_name : '',
        'company_phone' => property_exists($company->properties, 'company_phone') ? $company->properties->company_phone : '',
      ]);
    }

    // Make sure that there is data in the $res.
    // dd($res);

    return DataTables::make($res)
      ->addColumn('action', function ($company) {
        return '<a href="' . route('company_edit', $company['id']) . '" class="btn btn-xs btn-primary">Edit</a>';
      })->toJson();
```

### System details
- Operating System Ubuntu 17.10
- PHP Version 7.1
- Laravel Version 5.7
- Laravel-Datatables Version 8.13.4

**Comment by yajra** [comment]
Just an empty array and no error on response? The code looks fine.

**Comment by thiagobrauer** [comment]
@GrimJacky same problem here, did you find a solution?

**Comment by Krato** [comment]
Same problem filtering a collection.

```php
$collection = Model::all();

//filter
$elements = $elements->filter(function ($appraisal) use ($column, $search) {
    if ($column == 'id') {
        return match (true) {
            ($search == 'vp') => $appraisal->video,
            str_contains('video', $search) => $appraisal->video,
            str_contains('extension', $search) => $appraisal->action->version > 1,
            default => str_contains($appraisal->id, $search),
        };
    }

    return false;
});


datatables()
    ->of($elements)...
```
Everything is working fine. 

But for some reason  when this line is fired `str_contains('extension', $search) => $appraisal->action->version > 1,`, the data return is an empty array.

But if I call `dd($elements)`. is giving me 25 items. And also ajax is retuning:

 `draw: 9, recordsTotal: 25, recordsFiltered: 0, data: []`

Don't know the reason but is not painting the table.

**Comment by sagar-celcius** [comment]
Is this issue solved for anyone? I am facing the same issue.

**Comment by urshar** [comment]
Is not clear why, but it solve my problem too

**Comment by heriher76** [comment]
> Is this issue solved for anyone? I am facing the same issue. I am using Redis and feeding data as Array after applying pagination manually. I am geeting data for first page but not for other pages.
> 
> My issue has been solved with 'skipPaging()'.

this is awesome

**Comment by yajra** [comment]
Since paging is being handled before being passed to dataTable, we need to use `skipPaging` to disable the internal paging function of the package. The package assumes that all data are loaded at once when using collection.
