### ISSUE TITLE
Problem with Sort and Search

### ISSUE THREAD

**Issue by Santeee** [yajra/laravel-datatables#1989]
Hi, the datatables worked fine but for some reason (i think when i updated the packages in my project) datatable sort and search with Ajax stop work.

### Code snippet of problem

I try in the **backend**, first with:
`return DataTables::of(Model::query()->orderByDesc('created_at'))
        ->editColumn('dateattribute', '{!! (new Carbon\Carbon($dateattribute))->format("d/m/Y") !!}')
        ->make(true);`

and second with:
`return datatables()->collection(Model::all())->toJson();`

In the **frontend**:

```
var table = $('#tabla_model').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('models.datos_datatable') }}",
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'dateattribute', name: 'dateattribute' },
                    { data: 'contenido', name: 'contenido' }
                ]
            });
```

I'm doing something wrong?
i didn't modify my code after packages updated.

The data of datatable load fine, but search and sort by column don't work.

### System details

- Operating System: Windows 7 64x SP1
- PHP Version: 7.2.6
- Laravel Version: 5.7
- Laravel-Datatables Version ^8.13.0

**Comment by yajra** [comment]
Sort will not work because you have a fixed order. `->orderByDesc('created_at')`. You need to remove it for sort to work. 

For search, please provide any errors on the console.

**Comment by Santeee** [comment]
Hi yajra.
I removed the `->orderByDesc(created_at)` and it still don't work.
The console don't show me errors. 
When i search (writing in the search field) or click in the colum for sort, part of the response that i have from backend is: 
queries[""0""].query = "select count(*) as aggregate from (select '1' as `row_count` from `models` where `models`.`deleted_at` is null) count_row_table"
it don't receive the text that i writed.

**Comment by Santeee** [comment]
Solved.

My error.

I needed to send the QueryString to the API that response with DataTableResource.

using Dingo:

`$this->client->get('v1/models?'.$request->getQueryString());`

The package works very fine!
