### ISSUE TITLE
Search data range

### ISSUE THREAD

**Issue by joanebrown** [yajra/laravel-datatables#199]
Hi Yajra,

You could help me with my problem? I use: 

    dataTable.DataTable().columns(0, '2015-09-24 ~ 2015-09-25 23:59:59');

to filter a date range, But I just get the dates `2015-09-24`

I'm doing something wrong? I must do something before?

Thank you very much.

> INFO: The zero column is a datetime

**Comment by yajra** [comment]
I think the proper syntax is something like below:
```js
dataTable.DataTable().columns(0).search('2015-09-24 ~ 2015-09-25 23:59:59').draw();
```

Then on server side, just split the search value to get the date range and apply the necessary sql.

**Comment by joanebrown** [comment]
Hi,

Oh, I see... I thought which `yajra Datatables` does it automatically. Do you have a little example to do that? I don't know how to do with your package. :(

Regards,

**Comment by yajra** [comment]
The package automates search by using a wildcard like search. Date range and other specific queries should be written as appropriate. Try using filterColumn like on this demo: http://datatables.yajrabox.com/eloquent/post-column-search.

For the search keyword, you can use datatables request object to easily get the column search value like: `$datatables->getRequest()->columnKeyword(0);`

**Comment by joanebrown** [comment]
Thanks, I will try the `filterColumn` but I get an error... I created a new issue: https://github.com/yajra/laravel-datatables/issues/202
