### ISSUE TITLE
support for Laravel Scout

### ISSUE THREAD

**Issue by michaelnguyen2021** [yajra/laravel-datatables#1992]
### Summary of problem or feature request
There was a ticket to request Laravel Scout support (#1042)  and there is also a package for it (https://github.com/yajra/laravel-datatables-scout). The issue is the package has been abandoned since July 2017. Please spend more time on laravel-datatables-scout package as you know that in large scale tables, mysql is not really a good solution.

Things to improve on laravel-datatables-scout
* more tutorials to get started so people can start using it and give more feedback
* respond to reported laravel-datatables-scout issues
* laravel-datatables-scout package should do whatever laravel-datatables can do atm

It's my opinion and I (and others) are really appreciate your great contribution. I believe laravel-datatables-scout will make laravel-datatables to the next level. 

Thank you

**Comment by meijdenmedia** [comment]
What needs to be done to implement this? Is it possible to create a project for the Laravel Scout support? When there's a clear vision in what needs to be done I, and most likely some other users of this repo, might be able to help.
