### ISSUE TITLE
Service Implementation on Array Object

### ISSUE THREAD

**Issue by developerabdan** [yajra/laravel-datatables#1994]
### Summary of problem or feature request
I am using Laravel Yajra Datatable service implementation for my array object but it's not working because it says that 
`Call to a member function getQuery() on array`
i try to use collect for collectiong the data array but it still gets some error. here is my code below

### Code snippet of problem

`<?php

namespace App\DataTables;

use App\DataSantri;
use App\PaymentList;
use App\PaymentAddon;
use Yajra\DataTables\Services\DataTable;
use Route;
use DB;
class VirtualAccountDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable()
    {
        return datatables()
            ->eloquent($this->query());
    }

    /**
     * Get query source of dataTable.
     *
     * @param \App\User $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query()
    {
       $santri = DataSantri::select('data_santri.*','id_vc')
                        ->join('vc','data_santri.id_user','=','vc.id_user')
                        ->whereIn('status_kegiatan',['ziyadah','mutqin','tahsin'])
                        ->get();
        foreach($santri as $row){
            $pl = PaymentList::where('is_active',1)
                               ->where('angkatan',$row->angkatan)
                               ->where('payment_list.payment_time','bulanan')
                               ->get();
            $totalPl = DB::table('payment_list')
                                    ->where('is_active',1)
                                    ->where('angkatan',$row->angkatan)
                                    ->where('payment_list.payment_time','bulanan')
                                    ->sum('payment_price');
            $pa = PaymentAddon::where('nis',$row->nis)->get();
            $totalPa = DB::table('payment_addon')
                                        ->where('nis',$row->nis)
                                        ->sum('payment_price');
            $data[] =  array(
                'nis' => $row->nis,
                'id_vc' => $row->id_vc,
                'nama_lengkap_santri' => $row->nama_lengkap_santri,
                'jk' => $row->jk_santri,
                'data_pembayaran_bulanan' => $pl,
                'data_pembayaran_tambahan' => $pa,
                'total' => $totalPl + $totalPa
            );
        }
        return $this->applyScopes($data);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('')
                    ->parameters([
                        'dom' => 'lBfrtip'
                    ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'nis',
            'id_vc',
            'nama_lengkap_santri',
            'jk',
            'data_pembayaran_bulanan' => [
                'payment_name',
                'payment_price'
            ],
            'data_pembayaran_tambahan' => [
                'payment_name',
                'payment_price'
            ],
            'total'
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'Virtual Account Semua Cabang' . date('Y-m-d');
    }
}`

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
You are using collection data but declaring it as eloquent. Use collection instead.

```php
->collection($this->query());
```
