### ISSUE TITLE
It's time to move forward. 

### ISSUE THREAD

**Issue by timothymarois** [yajra/laravel-datatables#1996]
**Enough with the server issues.** It is time to move this documentation into a public resource. 

https://readme.io/
They offer free service for open source projects. 

This is the second time I've tried to look up documentation within the last few months, and it's been down on both occasions. While I know, it was previously resolved. This is ongoing.

**Comment by Ghiffari** [comment]
agreed, atm it's downed again

**Comment by yajra** [comment]
Thank you! Please see #2223.
