### ISSUE TITLE
How to output a clickable delete button using laravel collectives in yajra datatables laravel 5.7

### ISSUE THREAD

**Issue by karlarnejo** [yajra/laravel-datatables#1997]
I wanted to output a clickable delete button using the laravel collectives. The problem is that it outputs a raw html text `{!! Form::open(["action" => ["UsersController@destroy",28], "method" => "POST", "class" => "pull-right"]) !!} {{ Form::hidden("_method", "DELETE") }} {{ Form::submit("Delete", ["class" => "btn btn-danger"]) }} {!! Form::close()!!}")` in the view instead of a clickable delete button. I can output regular html tags but I want to use the laravel collectives. I am confused why it isn't working even if I already added `rawColumns()` function.

Here is my controller:

    public function yajraDT()
    {
        $users = User::all();
        return Datatables::of($users)
        ->addColumn('delete', function ($users) {
                return '{!! Form::open(["action" => ["UsersController@destroy",'.$users->id.'], "method" => "POST", "class" => "pull-right"]) !!}
                {{ Form::hidden("_method", "DELETE") }}
                {{ Form::submit("Delete", ["class" => "btn btn-danger"]) }}
                {!! Form::close()!!}")';
        })
        ->rawColumns(['delete'])
        ->make(true);
    }

Here is my view:

    <script>
         $(function() {
               $('#tableDT').DataTable({
               processing: true,
               serverSide: true,
               ajax: '{{ url('users/yajraDT') }}',
               columns: [
                        { data: 'id', name: 'id', 
                            @if(Auth::check() && Auth::user()->type == "Admin")
                                render:function(data, type, row)
                                {
                                    return "<a href='/users/"+ row.id +"'>" + row.id + "</a>"
                                }
                            @endif},
                        { data: 'first_name', name: 'first_name' },
                        { data: 'last_name', name: 'last_name' },
                        { data: 'email', name: 'email' },
                        { data: 'gender', name: 'gender' },
                        {data: 'delete', name: 'delete'}
                     ]
            });
         });
    </script>

**Comment by gidaban** [comment]
I am not sure if you do it but i found solution :)

```
return Form::open(["route" => ["business.branch.destroy",$branches->id], "method" => "POST", "class" => "pull-right"]) .
                    Form::hidden("_method", "DELETE") .
                    Form::submit("Delete", ["class" => "btn btn-danger"]) .
                    Form::close();
```
