### ISSUE TITLE
Regex search with Postgres

### ISSUE THREAD

**Issue by aline-matos** [yajra/laravel-datatables#1998]
### Summary of problem or feature request

Hi @yajra! Any chance of regex searching suport Postgres?

https://yajrabox.com/docs/laravel-datatables/master/regex

### Code snippet of problem

`dataTable.column(2).search("^" + "P52 VN" + "$", true, true, false).draw();` not working with regex searching.

### System details

- Ubuntu 18.04.1 64-bit
- PHP 7.2.15
- PostgreSQL 10.7 (Ubuntu 10.7-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- Laravel 5.6
- DataTables 1.10.19

**Comment by yajra** [comment]
I am not using Postgres so I cannot promise to attend to this sooner. If you can, please do not hesitate to submit a PR. Thanks!
