### ISSUE TITLE
Support for Laravel 5.8 but for yajra/laravel-datatables package

### ISSUE THREAD

**Issue by asivaneswaran** [yajra/laravel-datatables#2006]
Hi,

I know the version 9.0 supports Laravel 5.8 but what `yajra/laravel-datatables`

I have this in composer file:

```
"yajra/laravel-datatables": "^1.0",
"yajra/laravel-datatables-oracle": "~9.0"
```

and the first one is not working.

**Comment by yajra** [comment]
Using "yajra/laravel-datatables": "^1.5" should be enough for 5.8.

**Comment by gjhuerte** [comment]
> Using "yajra/laravel-datatables": "^1.5" should be enough for 5.8.

Installation completed on mine. Thanks 👌
