### ISSUE TITLE
Actions column problem

### ISSUE THREAD

**Issue by Mastok1979** [yajra/laravel-datatables#201]
Hi, 

I write you again about this Issue: https://github.com/yajra/laravel-datatables/issues/88#issuecomment-120047971

I have a problem with the fact that i have to except the show route to render the view! 
Can you explain me what i do wrong ? I want to make the action button Show Edit Delete in this Datatable.

This dont works:
```
    Route::resource('users','Admin\AdminUsersController');
```
![routes1](https://cloud.githubusercontent.com/assets/5084676/10206051/225c77f0-67c5-11e5-886f-70d79f3e93cd.png)
This works:
```
    Route::resource('users','Admin\AdminUsersController',[
    'except' => ['show']
    ]);    
```
![routes2](https://cloud.githubusercontent.com/assets/5084676/10206038/19e70e5a-67c5-11e5-832e-3a4184678412.png)
************************************
AdminUsersController:
-------------------
```
	public function Data()
	{
		$users = User::select(array('users.id','users.username','users.email'));
		return Datatables::of($users)
            ->addColumn('actions', function($user) {
                return view('admin.users.actions', compact('user'))->render();
            })		
			->make(true);
	}
```
Route for this:
```
    Route::get('users/data', 'Admin\AdminUsersController@Data');
```
***********************************
Admin.users.index 
-----------------------
```
@section('content')
    <table class="table table-bordered" id="users-table">
        <thead>
            <tr>
                <th>{{ trans('users.id') }}</th>
                <th>{{ trans('users.username') }}</th>
                <th>{{ trans('users.email') }}</th>
                <th>{{ trans('app.actions') }}</th>
            </tr>
        </thead>
    </table>
@stop

@push('scripts')
<script>
$(function() {
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        
        ajax: "{{ URL::to('admin/users/data') }}",
        columns: [
            { data: 'id', name: 'id' },
            { data: 'username', name: 'username' },
            { data: 'email', name: 'email' },
            { data: 'actions', name: 'actions', orderable: false, searchable: false },
        ]
    });
});
</script>
@endpush
```
actions.blade.php
----------------------
```
<a href="{{ URL::to('admin/users/'.$user->id.'/edit') }}" class="btn btn-xs btn-warning">{{ trans('app.edit') }}</a>
```
or this
```
{!! link_to_route('admin.users.edit', trans('app.show'), [$user->id], ['class' => 'btn btn-xs btn-warning']) !!}
```

**Comment by yajra** [comment]
@Mastok1979, I think your code is fine. What error did you get when running the app?

**Comment by Mastok1979** [comment]
Here when it works (show is just named like this link dont work)
---------
![works](https://cloud.githubusercontent.com/assets/5084676/10262489/10d6ad0a-69ca-11e5-8c64-4a449d5e99e6.png)


Here error msg
-----------
![wnoorks](https://cloud.githubusercontent.com/assets/5084676/10262490/1468921c-69ca-11e5-8ff0-35a1db3e4d9b.png)

**Comment by Mastok1979** [comment]
When i make my buttons without the action.blade it works! But this is less nice!

**Comment by Mastok1979** [comment]
Has anyone a solution for me?

**Comment by yajra** [comment]
@Mastok1979, what version of Laravel & Datatables are you using? forgot to mention that view approach is only applicable on v5.x of datatables.

**Comment by Mastok1979** [comment]
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laravelcollective/html": "5.1.*",
        "bestmomo/filemanager": "1.*",
        "laracasts/flash": "~1.3",
        "orchestra/imagine": "~3.0",
        "yajra/laravel-datatables-oracle": "~5.0"                
    },

**Comment by yajra** [comment]
Hmm.. your version seems correct too. Can you please inspect the ajax response using chrome dev tools/firebug and dump the error message / response from the server?

**Comment by Mastok1979** [comment]
Halleluja! I found the problem with firebug!

Really crazy! The method show dont exist in my controller! but the same happens for the other routings... hmmm

![2015-10-08_15h14_09](https://cloud.githubusercontent.com/assets/5084676/10367221/794e3336-6dcf-11e5-8716-5e04b36289b8.png)

**Comment by Mastok1979** [comment]
But now it seems to bug on this show method! How do you declare this method? with a datatables without action column i have this error too!

**Comment by yajra** [comment]
Show method is part of resource controller. http://laravel.com/docs/5.1/controllers#restful-resource-controllers. The issue seems due to incomplete controller method implementation. And you are correct that writing a manual route may solve that issue.

**Comment by hashemireza** [comment]
sadfdasf
