### ISSUE TITLE
For large number of record, it is becoming too slow

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [yajra/laravel-datatables#2010]
### Summary of problem or feature request
It seems for a large number of records, it becomes pretty slow, I have around 8000+ records on some pages, I am using CollectionDataTable to prepare the data. It is taking around 5 minutes.

### Code snippet of problem
 ```
return (new CollectionDataTable($videos))
        ->filter(function ($instance) use ($request) {
            if ($request->has('category') && ! is_null($request->get('category'))) {
                $instance->collection = $instance->collection->filter(function ($row) use ($request) {
                    return $row['video_category'] == $request->get('category') ? true : false;
                });
            }

            if ($request->has('language') && ! is_null($request->get('language')) ) {
                $instance->collection = $instance->collection->filter(function ($row) use ($request) {
                    return $row['video_language'] == $request->get('language') ? true : false;
                });
            }
        })
        ->editColumn('created_at', function(Video $video){
            return $video->createdAt();
        })->toJson();
```

### System details

- Operating System: Windows 10 pro
- PHP Version: 7.2.10
- Laravel Version: 5.6.39
- Laravel-Datatables Version: 8.0

Is it because of Collection, am I bound to use the query to make it fast or there is any better option?

**Comment by yajra** [comment]
Yes, collection is prone to slow process for large datasets. It's better to use query for faster response. If query is not possible, the only solution is to upgrade your server resources to handle bulk data faster.
