### ISSUE TITLE
"composer require yajra/laravel-datatables" error on laravel 5.8

### ISSUE THREAD

**Issue by jalil1408** [yajra/laravel-datatables#2011]
I run "composer require yajra/laravel-datatables" on laravel 5.8 app

output:

Using version ^1.5 for yajra/laravel-datatables
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yajra/laravel-datatables ^1.5 -> satisfiable by yajra/laravel-datatables[v1.5.0].
    - Conclusion: remove laravel/framework v5.8.0
    - Conclusion: don't install laravel/framework v5.8.0
....

how should I fix this error?

**Comment by imansugirman** [comment]
Same for me. this need yajra/laravel-datatables-fractal requires yajra/laravel-datatables-oracle 8.* please update @yajra

**Comment by rendyyangasli** [comment]
just try to install version ^9.0 instead of ^8.0 for laravel 5.8 using this command
`composer require yajra/laravel-datatables-oracle:^9.0` 

it should fix your issue
@jalil1408 @imansugirman

**Comment by asivaneswaran** [comment]
> just try to install version ^9.0 instead of ^8.0 for laravel 5.8 using this command
> `composer require yajra/laravel-datatables-oracle:^9.0`
> 
> it should fix your issue
> @jalil1408 @imansugirman

Actually no. @imansugirman is right. The update process is blocked because of the fractal package.

**Comment by yajra** [comment]
Fractal package updated to support v9. Thanks!

**Comment by moazsns** [comment]
i useing laravel 6 and faceing the same problem
