### ISSUE TITLE
Class datatables.request does not exist 

### ISSUE THREAD

**Issue by Amarashdeh** [yajra/laravel-datatables#2012]
**Summary of problem or feature request**

_Class datatables.request does not exist_

--
 
in Container.php line 729 at ReflectionClass->__construct('datatables.request')
in Container.php line 729 at Container->build('datatables.request')
in Container.php line 608 at Container->resolve('datatables.request')
in Container.php line 575 at Container->make('datatables.request')
in Application.php line 728 at Application->make('datatables.request')
in helpers.php line 106 at app('datatables.request')
in QueryDataTable.php line 79

____

vendor/yajra directory already has laravel-datatables-html

Already tried;
"php artisan clear-compiled",
"composer dump-autoload",
"php artisan optimize",
"php artisan cache:clear",
"php artisan route:clear",
"php artisan view:clear"

_____

System details
MAC
PHP 7.1
Laravel 5.4.16
Datatables ~8.0

**Comment by yajra** [comment]
Not sure on this one. Maybe try reinstalling all your packages? Delete vendor folder and run `composer install` again.

**Comment by rmdwirizki** [comment]
Facing the same issue with Laravel 5.6 and Datatables ~8.0. Fixed it by using uppercase 'T'. From 'Datatables' to 'DataTables':

When using:
```php
use Yajra\DataTables\DataTables;
```

Change in `config/app.php`
```php
'providers' => [
    // ...
    // ...
    Yajra\DataTables\DataTablesServiceProvider::class
];

'aliases' => [
    // ...
    // ...
    'DataTables' => Yajra\DataTables\Facades\Datatables::class,
];
```
