### ISSUE TITLE
How to calculate a value from data in table

### ISSUE THREAD

**Issue by falahatiali** [yajra/laravel-datatables#2013]
hi 
I have a question.

assume I have a field in my table that its name is consume and this is boolean 

I wanna show in the table if consume==1 then 'YES'
and if consume ==0 then 'NO'

how I can do that?

**Comment by falahatiali** [comment]
@yajra

**Comment by pet1330** [comment]
```php
return Datatables::eloquent($records)
->editColumn('consume', '{{$consume ? "YES" : "NO" }}')
```
