### ISSUE TITLE
best way to show all table with less controller and view

### ISSUE THREAD

**Issue by cyrilmanuel** [yajra/laravel-datatables#2018]
### Summary of problem or feature request
hi, 
I have a simple question. I have 30 tables on my bdd. I should be created 30 controllers and 30 function crud to (edit, del, add, show) all tables and all object on this table. do you have a best practice to generate less controller and less view or use a factory or anything else ? 

my goal is simple, I don't want to create 30x the same code with different params.

### System details

- Operating System element os 5
- PHP Version 7.3.1
- Laravel Version 5.8
- Laravel-Datatables Version

**Comment by yajra** [comment]
Not sure on best practice but I usually create a DataTable and Controller for each table since most of the time, the use cases for each table differs. 

Just an idea for your case, maybe try creating a single dataTable class that will have a table and columns dynamically selected/picked from a config?

Played with this idea is this is what I came up. Just modify it as you see fit.

```php
// create tables config.
return [
    'users' => [
        'table' => 'users',
        'columns' => [
            'id',
            'created_at',
        ],
    ],
];

// append table on your request
Route::resource('tables/{table}', 'DynamicDataTablesController');

// controller
class DynamicDataTablesController extends Controller
{
    public function index(DynamicDataTable $dataTable, $table)
    {
        return $dataTable->with('table', $table)->render('index');
    }
}

// dataTable service class
class DynamicDataTable extends DataTable
{
    public function dataTable($query)
    {
        return datatables()
            ->query($query)
            ->addColumn('action', 'dynamic.action');
    }

    public function query()
    {
        return DB::table($this->table);
    }

    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->minifiedAjax();
    }

    protected function getColumns()
    {
        return config('tables.' . $this->table . '.columns');
    }
}
```

**Comment by cyrilmanuel** [comment]
Thank you very much for this approach, it's exactly what I needed. I think the solutions of using multiple controllers and views is ideal to optimize rendering. 

but this solution is perfect for me. Thank you very much. 

have a good day
