### ISSUE TITLE
Call to undefined filtercolumn()

### ISSUE THREAD

**Issue by joanebrown** [yajra/laravel-datatables#202]
Hi Yajra,

When I try to use `filterColumn()` I get the next error:

    Call to undefined method yajra\\Datatables\\Datatables::filtercolumn()

Why? I have the latest version of `yajra/laravel-datatables-oracle` I need something more?

**Comment by yajra** [comment]
You should use `filterColumn` after `->of($model)` in chain.

```php
return $datatables->of($model)->filterColumn(....)->make(true);
```

**Comment by joanebrown** [comment]
I use it in that way:

      return Datatables::of(MyModel::select(array('id', 'name', 'created_at', 'date')))
           ->setRowId(function($model) {
                   return $model->id;
           }) 
           ->filterColumn('id', 'whereRaw', "id = ?", ["$1"])
           ->make();

And, as I said, I always get:

    Call to undefined method yajra\\Datatables\\Datatables::filtercolumn()

Note that this error says filter**c**olumn() and not filter**C**olumn() (the name of the function) I'ts weird, not?

I don't know what is happening :S

**Comment by joanebrown** [comment]
Is an issue, Yajra? I still with the problem...

**Comment by MJRedcooL** [comment]
I have this problem too. Are there some patch for that issue?

I'm using `yajra/laravel-datatables-oracle 3.6.9` and `Laravel 4.2.17`

Please, I need this functionality: any help is welcome

---

Best regards,

  Michael J. R.

**Comment by MJRedcooL** [comment]
I think I can use the `filter()` method, but I don't *know* how to *know* the column in I'm searching for.

---

**Javascript:**

I want to search in the column number 0, the `100` value.

    dataTable.columns(0).search("100").draw();

**PHP:**

How can I know the `$HereTheValueOfColumnZeroSearch` and `$HereTheValueOfColumnOneSearch`:

    ->filter(function ($query)  {         
         // Can I know the value of each column search to apply a custom query for each one?

          // Column 0
          $query->where('id', '==',$HereTheValueOfColumnZeroSearch);

          // Column 1
          $query->where('name', '==',$HereTheValueOfColumnOneSearch);         
     })

**Comment by yajra** [comment]
Sorry for late response. `filterColumn` works fine on my side. Can I know your environment please? I am using homestead on Mac. thanks!

@MJRedcooL, the best approach for this is to use `filterColumn`. `filter` overrides global search but not the column search which causes your SQL issue.

**Comment by MJRedcooL** [comment]
Hi Yajra! Don't worries.

I can't find `filterColumn` in `Datatables.php` class.

I use Debian and:

-  My version of `yajra\Datatables`: **3.6.9**

-  My version of Laravel: **4.2.17**

Can you think of any solution for the issue of `filter` method?

Best regards,

**Comment by yajra** [comment]
@MJRedcooL, upon checking filterColumn is not yet available on my L4.2 version. @joanebrown are you  using L4.2 too? Will try to integrate `filterColumn` on L4.2 on my free time.

**Comment by joanebrown** [comment]
Yes i have this version too... Thanks for all your help yajra and MJRedcooL

I tried the solution of MJRedcooL and works well... but i have the issue of the `and LOWER(mydate) LIKE ?` too. 

Yajra you know how to solve this error until you implement `filterColumn` for L4.2?

Thanks :D

**Comment by yajra** [comment]
I think using v3.6.8 may solve the SQL issue. Can you give it a shot? v3.6.9 excludes columnSearch from global search which is causing the `and LOWER(mydate) LIKE ?` issue.

**Comment by joanebrown** [comment]
I can't use this version... (*because I use POST for my datatables, and I think remember with this version have a bug*) there are other way to exclude globa search into the `filter` method? I do not care if I need to modify the `filter` method.

Do you think it would take much to develop the `filterColumn` on L4.2?

**Comment by yajra** [comment]
The only changes from v3.6.8 to v3.6.9 was `columnSeach` was made independent from global search. This means that column search will always be triggered regardless if you override it using `filter` method.  The POST method issue was fixed on v3.6.8.

For the `filterColumn`, I made quick preview and it seems that it would take much time to integrate. I would have to fetch the logic from Bllims version because I almost have re-written the package on L5.1 version and the difference is huge. And I'm not using L4.2 anymore so I have to setup a test environment on 4.2 too. Sorry for this but it might take some time to implement this.

**Comment by joanebrown** [comment]
I understand, 

I will give a shot to the `v3.6.8`!  Could you tell my how to downgrade with composer? 


Thanks Yajra :)

**Comment by yajra** [comment]
on your composer.json update the package version to: `"yajra/laravel-datatables-oracle": "3.6.8"` then run `composer update yajra/laravel-datatables-oracle` on your terminal.

**Comment by joanebrown** [comment]
All works well.

I hope God (Or whoever) bless you. Amazing support. :)

**Comment by joanebrown** [comment]
I think is better to put this here... I have a littleee question.

I need to filter data wich there aren't in any column:

Can I send to `filter()` variables with values? I tried with the next code, but doesn't work:

    dataTable.DataTable().push( { "name": "more_data", "value": "my_value" } ); 
    dataTable.fnDraw(true);

I want this to make something like this:

     if($IHaveThisVariable){
               $query->where('columnWichNoAppearInDatatable, '=', $IHaveThisVariableValue);
      }

Sorry to be so heavy ...

**Comment by yajra** [comment]
Yes, its possible. Just make sure that the data are being sent to the server and just use the Input facade inside the filter method. 

Sent from Outlook using iPhone

    _____________________________

**Comment by yajra** [comment]
Sorry guys, I may not be able to do this enhancements anymore. But I am willing to accept a PR if someone is interested to implement this. Thanks!
