### ISSUE TITLE
How can I ordering XX/XXXX

### ISSUE THREAD

**Issue by marcelogarbin** [yajra/laravel-datatables#2020]
### Summary of problem or feature request

![image](https://user-images.githubusercontent.com/9335588/54300376-7d8ab300-459b-11e9-92a8-986f67bc4d9d.png)

Hello, 
how can I correct this ordering?

Using pure SQL code I can sort, but I was not able to sort in a satisfactory way using DataTables.
Code: `ORDER BY right(numero, 4) DESC, left(numero, 2)`

Thank's

### System details

- Operating System Win10
- PHP Version 7.3
- Laravel Version: 5.5
- Laravel-Datatables Version: 8.13.5

**Comment by yajra** [comment]
I think you can use orderColumn: https://yajrabox.com/docs/laravel-datatables/master/order-column

```php
->orderColumn('numero', 'right(numero, 4) $1, left(numero, 2')
```

**Comment by marcelogarbin** [comment]
Hello @yajra 
It worked fine, I had tried using this method, but I was sinning in the "$1" position, I had not understood where to put it.

Thank you for your help.
