### ISSUE TITLE
Limit and offset 

### ISSUE THREAD

**Issue by arshadasgar** [yajra/laravel-datatables#2022]
### Query log shows limit and offset is not automatically applied
I have enabled the QueryLog using **DB::enableQueryLog()** and executed this query 
```php
datatables(Line::all())->toJson();
```
The result of the query log was:
```php
[0] => Array
        (
            [query] => select * from `lines` where `lines`.`deleted_at` is null
            [bindings] => Array
                (
                )

            [time] => 1.43
        )
```

The query did not contain the limit and offset. Isn't the package supposed to do that? Or did I do anything wrong?
### System details

- Operating System : Ubuntu 18.04
- PHP Version : 7.2
- Laravel Version : 5.7
- Laravel-Datatables Version : 8

**Comment by yajra** [comment]
You are loading all data, thus paging is not applicable. 

`Line::all()`

Use query: `Line::query()` instead.
