### ISSUE TITLE
how to show sum value in nested column

### ISSUE THREAD

**Issue by imamhsn195** [yajra/laravel-datatables#2023]
### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by imamhsn195** [comment]
here is my code
 $users = Purchase::with('supplier','product','branch','users')
       ->groupBy('invoice_no')
       ->get();
       $users = $users->groupBy('invoice_no');
        foreach($users as $user){
            foreach($user as $u){
                $u['invoice_qty'] = $user->sum('quantity');
            }
        }
        // return $users;
        return Datatables::of($users)->make(true);
        // return Datatables::of(Purchase::query())->make(true);

**Comment by luzenggui** [comment]
Hi, do you finish the function of showing sum value in texted column? If you got it, can you teach me how to get it!  very thks
