### ISSUE TITLE
Edit header title by adding view html

### ISSUE THREAD

**Issue by kamov** [yajra/laravel-datatables#2026]
I have a header title with a dropdown html code which is very long.
I would like to put the html code inside a view and then load it as "title" of the column.

Something like for editColumns():

```php

            ->editColumn('customColumn', function(User $user) {
                return view('my-view', compact('user'));
            })

```

Thanks

**Comment by yajra** [comment]
You need to use raw columns too: `->rawColumns(['customColumn', ...])`. See https://yajrabox.com/docs/laravel-datatables/master/raw-columns for ref.

**Comment by kamov** [comment]
I understand how to add html inline using rawColumns.

But I would like to use separated "view" file for column
