### ISSUE TITLE
Does laravel-datatables work with the scroller extension for datatables

### ISSUE THREAD

**Issue by basementjack** [yajra/laravel-datatables#203]
Hi, I added the scroller extension to my project, but to really see it work I need to remove the paging, so added     "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]] to my javascript.

When I change to "view all" I get a 500 server error, and as far as I can tell, no response otherwise. (at least no visible ajax on screen when I looked in Chrome Dev Tools.

**Comment by yajra** [comment]
I just tested scroller plugin and seems to work on my side. Using this example as ref: https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html

```js
    $(document).ready(function() {
        $('#example').DataTable( {
            serverSide: true,
            ordering: false,
            buttons: false,
            searching: false,
            ajax: '',
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
            scrollY: 200,
            scroller: {
                loadingIndicator: true
            },
            columns: [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'}
            ]
        });
    });
```

Route:
```php
get('test', ['as' => 'test', function(Request $request, Datatables $datatables) {
    if ($request->ajax()) {
        return $datatables->of(\App\Models\User::query())->make(true);
    }
    return view('test');
}]);
```

Output:
![screen shot 2015-10-06 at 1 23 58 pm](https://cloud.githubusercontent.com/assets/2687997/10300786/b988a13c-6c2d-11e5-8c92-074423c8ddae.png)

**Comment by basementjack** [comment]
Thanks yajra!
I'll give give it a deeper look, I'm sure I just did something stupid!

**Comment by basementjack** [comment]
Also I just donated on your project page - I really appreciate your work on this and your support here on github!

**Comment by yajra** [comment]
@basementjack thanks for the contributions again ^_^. Will close this one since I have tested this and it works. Thanks!
