### ISSUE TITLE
Yajra DataTables website down

### ISSUE THREAD

**Issue by pututbawono** [yajra/laravel-datatables#2030]
I notice that Yajra DataTables website is down. Is there any alternative site for docs and tutorials?
And also, I'm using yajra/laravel-datatables v9.0 with Laravel 5.8, so I need those docs for this version.
Thanks.

**Comment by jnineja** [comment]
@yajra Please take note of this. I also need the documentation regarding datatable exports/downloads. Thanks!

**Comment by no4** [comment]
hold can help you.
https://web.archive.org/web/20181105174706/https://yajrabox.com/docs/laravel-datatables/master

**Comment by pututbawono** [comment]
@no4 thanks for the link, I'll look into it then.
By the way, @yajra, still no sign of when the actual site will be up again?

**Comment by TomEasterbrook** [comment]
> hold can help you.
> https://web.archive.org/web/20181105174706/https://yajrabox.com/docs/laravel-datatables/master

Thanks for this! Google Cache didn't work but this is just what I need

**Comment by TomEasterbrook** [comment]
This appears to be resolved!

**Comment by pututbawono** [comment]
Yes, I just notice that the site's up already. Thanks for everyone's help.

**Comment by nasrulhazim** [comment]
unable to access the site. is it down again?
