### ISSUE TITLE
unknown parameter in JSON column

### ISSUE THREAD

**Issue by kejodion** [yajra/laravel-datatables#2034]
I have a JSON column type called `data` with the following value:

	{"name": "tester", "email": "tester@example.com"}

I can utilize these values via `data->name` etc.

However, if I try to access an unknown parameter like `data->phone`, I get an `unknown parameter` error because that particular parameter does not exist.

Why are unknown parameters not defaulting to `null` and how do I fix this?

Here is an example of code that generates columns:

        foreach (company()->fields->where('tables', true) as $field) {
            $columns[] = ['title' => $field->label, 'data' => 'data.' . $field->name, 'name' => 'data->' . $field->name];
        }

**Comment by kjjdion** [comment]
I fixed it by adding: `'defaultContent' => ''`

**Comment by ricardovigatti** [comment]
Same here, fixed by adding` 'defaultContent' => ''` to columns definition:

eg:
`
protected function getColumns()
    {
        return [
            [
                'data' => 'id',
                'title' => '#',
            ],
            [
                'data' => 'name',
                'title' => 'Product',
            ],
            [
                'data' => 'manufacturer.name',
                'defaultContent' => '',
                'title' => 'Manufacturer',
            ],
        ];
    }
`
