### ISSUE TITLE
DataTables warning: table id=tableclient - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by armelkouassi** [yajra/laravel-datatables#2038]
### Summary of problem or feature request

Hello I have an error with yajra datatables, the error is : DataTables warning: table id=student_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7 with serverSide: true but when serverSide is false i ahve not error

### Code snippet of problem

-- My page client html : index.blade.php

<div class="table-responsive">
                                <table id="tableclient" class="display table" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>Numéro</th>
                                        <th>Sigle</th>
                                        <th>Raison sociale</th>
                                        <th>Localisation</th>
                                        <th>Contact</th>
                                        <th>Email</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
-- Script javascript : 

var oTable;
        $(document).ready(function () {

            /*Liste des clients*/
            oTable = $('#tableclient').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('client.getclient') !!}',
                columns: [
                    /*{data: 'check', orderable:false, searchtable:false},*/
                    {data: 'numero'},
                    {data: 'sigle'},
                    {data: 'raison_sociale'},
                    {data: 'localisation'},
                    {data: 'tel'},
                    {data: 'email'},
                    {data: 'action', orderable:false, searchtable:false},
                ],
                language: {
                    url: '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json'
                }
            });
});

-- Controller : ClientController.php

use App\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\DB;
use DataTables;

public function getClient(){

        /*$clients = Client::all();*/

        $clients = Client::all();

        return DataTables::of($clients)
            ->addColumn('action', function ($client){
                $sup = (auth()->user()->isAdmin == 1) ? '<a class="dropdown-item delClient" data-id="'.$client->id.'" href="#0" title="Supprimer"><span class="ti-trash c-rouge"></span> Supprimer</a>' : '';
                $div = (auth()->user()->isAdmin == 1) ? '<div class="diviseur"></div>' : '';
                return '<div class="dropdown" style="">
                            <button class="btn btn-sm btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="ti-menu"></span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="'.route('archive.index', ['id_client' => $client->id]).'"><span class="ti-folder c-vert"></span> Archives</a>
                                <a class="dropdown-item" href="'.route('archive.corbeille', ['id_client' => $client->id]).'"><i class="i-Folder-Trash c-vert"></i> Corbeille</a>
                                <div class="diviseur"></div>
                                <a class="dropdown-item" href="#0" onclick="formClient(\''.$client->id.'\',\''.$client->numero.'\',\''.$client->sigle.'\',\''.$client->raison_sociale.'\',\''.$client->localisation.'\',\''.$client->tel.'\',\''.$client->email.'\')" data-toggle="modal" data-target="#modalUpdateClient"><span class="ti-pencil c-bleu"></span> Modifier</a>
                                '.$div.'
                                '.$sup.'
                            </div>
                        </div>';
            })
            ->rawColumns(['action'])
            ->make(true);
    }

### System details

- Operating System : windows 10  64 bit
- PHP Version : 7.2.9
- Laravel Version 5.8
- Laravel-Datatables Version 9

**Comment by AhmedFatehy** [comment]
Me Too

**Comment by AhmedFatehy** [comment]
just add id in blade {!! $dataTable->table(['id'=> "any-id"]) !!}

**Comment by armelkouassi** [comment]
@AhmedFatehy I add that in my <thead> </ thead> or where precisely thank you

**Comment by Pak10** [comment]
@armelkouassi could u please clarify on this
