### ISSUE TITLE
Pagination - count - performance issue

### ISSUE THREAD

**Issue by MajkieS** [yajra/laravel-datatables#2044]
Hey there,

when having 0,5 million records in a database (everything optimized using query builder instead of collections, using indexes and so) table is blazing fast except during filtration.

When filtering through table records it counts on every request like so: select count(*) as aggregate from.

In file: QueryDataTable.php there is a method: public function count(). This should probably respect option skipTotalRecords and everything can be solved. 

To avoid showing 0 pages in pagination it should be:
if ($this->skipTotalRecords) return null;

Tested, works flawlessly after this small change.

Thanks for feedback.

**Comment by yajra** [comment]
hi @MajkieS, thanks for the inputs. Can you please submit a PR on your proposed solution so that we can check and verify it?

**Comment by MajkieS** [comment]
Hey @yajra, I'll submit a PR.

**Comment by MajkieS** [comment]
@yajra It's done. You can check it out :)

**Comment by karmendra** [comment]
Any update on this?
