### ISSUE TITLE
sorting doesn't work with DT_RowIndex , it searches for a column named DT_RowIndex when sorting button is pressed.

### ISSUE THREAD

**Issue by akilpatel** [yajra/laravel-datatables#2046]
![Screenshot 2019-04-09 at 6 36 39 PM](https://user-images.githubusercontent.com/49442775/55802740-78ffde80-5af6-11e9-9462-eafe1ce4695c.png)

### Sorting of the column with DT_RowIndex values. screenshot of error is attached.

```
columns: [
		      { data: 'id', name: 'id'},
		      { data: 'DT_RowIndex', name: 'DT_RowIndex', "orderable":true, "ordeing":true, "searchable":true, "className" : "my_class"},
		     {
    	                "className":'details-control',
    	                "orderable":false,
    	                "ordeing":false,
    	                "searchable":false,
    	                "data":null,
    	                "defaultContent":''
    	            },
```

### System details

- PHP Version 7.2
- Laravel Version 5.7

**Comment by yajra** [comment]
DT_RowIndex is a computed column, thus searching and sorting are expected not to work when using it. Unless the value was fetch from the database too.
