### ISSUE TITLE
I stored columnNames on array. How can I use editColumns. Can we use loop on editColumns?

### ISSUE THREAD

**Issue by zayazayazaya** [yajra/laravel-datatables#2047]
### Summary of problem or feature request

Can we use loop on editColumns?
### Code snippet of problem
$hyperLinkColumns = $data['hyperLinkColumns']; // Contains 10 values and it's dynamic

Datatables::of($query)->editColumn($hyperLinkColumns[0], function($user) {
     return $user->$hyperLinkColumns[0].'_URL';
  });
}

**Comment by yajra** [comment]
Yes, just use the proper syntax of closure and you're good to go :).

```php
$hyperLinkColumns = $data['hyperLinkColumns']; // Contains 10 values and it's dynamic

Datatables::of($query)
->editColumn($hyperLinkColumns[0], function($user) use(hyperLinkColumns) {
    return $user->$hyperLinkColumns[0].'_URL';
});
```

**Comment by zayazayazaya** [comment]
Well. Problem is I don't know how many elements are stored in $hyperLinkColumns It can be 10 or 20. 
Is there any way to use loop to edit columns?

**Comment by zayazayazaya** [comment]
$hyperLinkColumns is dynamic

**Comment by yajra** [comment]
I see, you can store dataTable is a variable then perform a loop? Something like:

```php
$dataTable = Datatables::of($query);
foreach(...) {
  $dataTable->->editColumn($hyperLinkColumns[0], function($user) use(hyperLinkColumns) {
      return $user->$hyperLinkColumns[0].'_URL';
  });
}
return $dataTable->toJson();
```
