### ISSUE TITLE
DataTable warning ajax error

### ISSUE THREAD

**Issue by muhghazaliakbar** [yajra/laravel-datatables#205]
Hi, i have error on my laravel app
![screenshot_195](https://cloud.githubusercontent.com/assets/8321936/10314844/912339b2-6c89-11e5-8af3-58bed130a9cb.png)

here my table:
![screenshot_196](https://cloud.githubusercontent.com/assets/8321936/10314934/f173683c-6c89-11e5-9d3b-28f6f10d6535.png)

and my script:
![screenshot_197](https://cloud.githubusercontent.com/assets/8321936/10314947/020182ec-6c8a-11e5-976b-411a63ff2bb8.png)

and here my controller:
![screenshot_198](https://cloud.githubusercontent.com/assets/8321936/10314983/26f21a08-6c8a-11e5-9dac-5d138ad87896.png)

everything looks good for me, but maybe something i have missing.

**Comment by johnhatch** [comment]
If you go to your browser's dev tools (<kbd>F12</kbd> in chrome), then look in either the network or console tab, you should be able to see the request sent for the datatable (highlighted in red due to returning an error). You can open that request in a new tab and see the specific error that laravel is throwing.

Glancing over your code I'm not sure I can see where the issue would be, perhaps something to do with `$this->transaksi` not being set in your controller.

**Comment by muhghazaliakbar** [comment]
i found this error on chrome
![screenshot_199](https://cloud.githubusercontent.com/assets/8321936/10326952/fedc90da-6cd3-11e5-9cb8-506bd8c0efae.png)

and about $this->transaksi
here my code
![screenshot_200](https://cloud.githubusercontent.com/assets/8321936/10326956/15a784a0-6cd4-11e5-9a50-3641d571469d.png)

**Comment by yajra** [comment]
Based on error, it seems like `route('transaki.allData')` is not yet defined on your routes. Double check your routes and route name declarations.

**Comment by muhghazaliakbar** [comment]
i have declared my route here
![screenshot_201](https://cloud.githubusercontent.com/assets/8321936/10327008/e7c72382-6cd4-11e5-97c3-9b77addd497c.png)

**Comment by sonuku** [comment]
Have, uh, you tried php artisan route:cache ?

**Comment by muhghazaliakbar** [comment]
yah.but not affect

**Comment by sonuku** [comment]
Might be completely off, 
But could it be your table id is "tabel_transaksi" and your jquery selector is "#table transaksi"

Missing an underscore?

**Comment by muhghazaliakbar** [comment]
![screenshot_202](https://cloud.githubusercontent.com/assets/8321936/10327470/21d76dfc-6cda-11e5-9072-e1504cba452e.png)
no

**Comment by yajra** [comment]
Can you try listing your routes and confirm that `transaki.allData` was registered by Laravel? `php artisan route:list`. Or try using `url()` instead of `route()`?

**Comment by sonuku** [comment]
Weird hey.

Try restarting your dev server / artisan serve.
Looks like something not related to datatables and more with the app.

**Comment by muhghazaliakbar** [comment]
here my list route
![screenshot_203](https://cloud.githubusercontent.com/assets/8321936/10327505/a0ef3e12-6cda-11e5-9309-c39ce1b6a7e9.png)

**Comment by sonuku** [comment]
Whats in your transaksi `select` repository method?
Maybe its got a redirect in there or something?

**Comment by muhghazaliakbar** [comment]
this?
```
$transaksi = $this->transaksi->select([
            'id',
            'tanggal',
            'nomor_nota',
            'tipe',
            'jumlah_uka',
            'kurs',
            'mata_uang',
            'jumlah_rupiah',
            'cabang'
        ]);
        
        return Datatables::of($transaksi)->make(true);
```

**Comment by sonuku** [comment]
`$this->transaksi->select`

**Comment by muhghazaliakbar** [comment]
where?

**Comment by sonuku** [comment]
Ok then, i assume `$this->transaksi` is just an instance of the model.

If you just go to http://localhost:8000/transaksi-dan-sipesat/alldata
What do you see?

**Comment by muhghazaliakbar** [comment]
completed json result from transaksi select

**Comment by yajra** [comment]
Are you using artisan serve? There were several weird issues that are coming up when using `artisan serve` and most of it were fixed when they migrated to apache/nginx. One most common weird bug is that Laravel will automatically/randomly destroy your session when making an ajax call.

**Comment by muhghazaliakbar** [comment]
yah i use artisan serve. so what can i do to fix this problem?

**Comment by yajra** [comment]
I suggest you use apache or homestead if possible.

**Comment by muhghazaliakbar** [comment]
aw right laravel destroy my session if i use artisan serve. 
why not report this bug?

big thanks to you ^_^
