### ISSUE TITLE
Datatables server side: Dropdown filter with all options?

### ISSUE THREAD

**Issue by FrazeColder** [yajra/laravel-datatables#2053]
### Summary of problem
I have implemented a datatable which operates server sided. However, I also want to make use of the dropdown select filter. The problem I am facing is that the filter shows only the values which are displayed at the current page. As you can see this is not very useful cause I want to have the possibility to filter the table by all data and not only the data which are shown.

I am using laravel and your package here: https://github.com/yajra/laravel-datatables.

You guys have any idea how to change solve this?

This is an example of my table operating server sided. You can see, you only have the shown values as option to filter:
https://jsfiddle.net/bpLtq3ec/

### Code snippet of problem
On jsfiddle (link above)

**Comment by yajra** [comment]
Here is a good example tuts that you can use as ref from LaravelDaily.   https://laraveldaily.teachable.com/courses/datatables-in-laravel/lectures/9677067
