### ISSUE TITLE
Error when using NestableTrait

### ISSUE THREAD

**Issue by josegus** [yajra/laravel-datatables#2059]
### Summary of problem or feature request

I recently installed https://github.com/atayahmet/laravel-nestable and added NestableTrait to my model "Categoria". This is causing an issue, returning "No available engine for App\\Categoria" message. I really need to use both (datatables and nestable). Any idea how can i make both work correctly?

I have not run "vendor publish" for datatables, since I don't need customization. I have other models (Producto, Cliente) working the same: ajax and using datatables() helper, but without NestableTrait.

### Code snippet of problem
I'm using ajax, so my code looks like:

```php
    // Ajax method
    public function list(Request $request)
    {
        $query = Categoria::select(['id', 'nombre']);

        return datatables($query)->toJson();
    }
```
And my Categoria model:

```php
class Categoria extends Model
{
    use NestableTrait;

    protected $table = 'categoria';

    protected $fillable = ['nombre', 'slug', 'icono', 'descripcion', 'categoria_id'];

    protected $hidden = ['created_at', 'updated_at'];
}

```

### System details

- Operating System: Ubuntu 16.04
- PHP Version: 7.2
- Laravel Version: 5.7
- Laravel-Datatables Version: 8.0

**Comment by yajra** [comment]
Self joins is not yet supported by the package. There is a PR that address this but it breaks on the soft deletes model and was reverted https://github.com/yajra/laravel-datatables/pull/2051.
