### ISSUE TITLE
Cannot read property 'style' of undefined (Laravel row detail)

### ISSUE THREAD

**Issue by muhghazaliakbar** [yajra/laravel-datatables#206]
Hi, i tried to use row details on http://datatables.yajrabox.com/eloquent/row-details but i get error ```Cannot read property 'style' of undefined``` 

i followed the instruction like on docs but i can't reach my mistake.

**Comment by yajra** [comment]
I think this is a javascript error. Please double check the number of columns on your datatables and make sure that it does match the number of `th` on your table header.

**Comment by muhghazaliakbar** [comment]
it's affect? if my query ```Datatable::of(Model::all())->make(true);``` Example:10 column, and i show just 7 column in my table ```<th>```.

**Comment by yajra** [comment]
No. What I mean is check your `table > thead > th` and make sure that it matches the number of columns defined on your datatables. Like below js should have 3 corresponding `th`.

```js
columns: [
{data: ..., name: ...},
{data: ..., name: ...},
{data: ..., name: ...},
]
```

```html
<table>
<thead>
<tr>
<th>Col1</th>
<th>Col2</th>
<th>Col3</th>
</tr>
</thead>
</table>
```

**Comment by muhghazaliakbar** [comment]
here my script:
```javascript
var table = $('#tabel_transaksi').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route('transaksi.allData') }}',
            columns: [
                { data: 'tanggal', name: 'tanggal' },
                { data: 'nomor_nota', name: 'nomor_nota' },
                { data: 'tipe', name: 'tipe' },
                { data: 'jumlah_uka', name: 'jumlah_uka' },
                { data: 'kurs', name: 'kurs' },
                { data: 'mata_uang', name: 'mata_uang' },
                { data: 'jumlah_rupiah', name: 'jumlah_rupiah' },
                { data: 'cabang.nama_cabang', name: 'cabang' },
                { data: 'action', name: 'action' }
            ]
        });
```

and here my table:
```
<table id="tabel_transaksi" class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Tanggal</th>
                        <th>Nomor Nota</th>
                        <th>Jual/Beli</th>
                        <th>Jumlah UKA</th>
                        <th>Rate/Kurs</th>
                        <th>Mata Uang</th>
                        <th>Jumlah Rupiah</th>
                        <th>Pusat/Cabang</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
```

**Comment by yajra** [comment]
If you want to add details, then you should add one more `th` before `<th>Tanggal</th>` then on your js.

```js
columns: [
  {
    "className":      'details-control',
    "orderable":      false,
    "data":           null,
    "defaultContent": ''
  },
  { data: 'tanggal', name: 'tanggal' },
  ...
]

**Comment by muhghazaliakbar** [comment]
how to fill row detail with data?

**Comment by yajra** [comment]
You would need some templating js like Handlebars to fill row details with data. Follow my demo http://datatables.yajrabox.com/eloquent/row-details to get some ideas. There are several ways to do it depending on your js knowledge.

**Comment by fabianscholz** [comment]
I found a Problem with Laravel. If you use [Handlebars](http://handlebarsjs.com/) like the example and a Laravel Blade template you need to mark the braces like:
```
Hello, @{{ name }}.
```
In this example, the @ symbol will be removed by Blade; however, {{ name }} expression will remain untouched by the Blade engine, allowing it to instead be rendered by your JavaScript framework.

Found here: http://laravel.com/docs/5.1/blade

That worked in my case.

Fabian

**Comment by yajra** [comment]
@fabianscholz, yeah good point on using `@{{ }}` on blade when using handlebars. I do have it on my actual demo code but I think forgot to put a note for it. Thanks!

**Comment by mohalabAldai** [comment]
@yajra 
Every things in my source code is Ok  , But the style has problems
 
See the attachment below


![datatable](https://user-images.githubusercontent.com/44842647/52343189-10c24d00-2a20-11e9-9f24-acb4ed4844f7.PNG)
