### ISSUE TITLE
Eloquent "filter" not working

### ISSUE THREAD

**Issue by Razorsheep** [yajra/laravel-datatables#207]
I am trying to do a simple eloquent limit to a selection and it I am getting a 500 (Internal Server Error).

This is the controller code:

```php
$plants = Plant::select(array('plants.id','plants.name','plants.created_at','plants.updated_at'));

    	return Datatables::of($plants)
      	->whereIn('id', [1,2,3,4])
        ->make(true);
```

The table:

```html

<div class="adv-table">
  <table class="display table table-bordered table-striped" id="dynamic-table">
    <thead>
      <tr>
        <th>Plant ID</th>
        <th>Plant Name</th>
        <th>Created At</th>
        <th>Updated At</th>
      </tr>
    </thead>
  </table>
</div>
```
And javascript:
```javascript
$(document).ready(function(){
            $('#dynamic-table').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": '{{ URL::Route('admin.servicetickets.custom_data') }}',
                "columns": [
                    {data: 'id', name: 'id', defaultContent:'n/a'},
                    {data: 'name', name: 'name', defaultContent:'n/a'},
                    {data: 'created_at', name: 'created_at', defaultContent:'n/a'},
                    {data: 'updated_at', name: 'updated_at', defaultContent:'n/a'}
                    ]
            });
          });
```

I am using Laravel 4.2. 

Do you have any clue what might be wrong?

**Comment by johnhatch** [comment]
Can you open the 500 request in a new tab and view the error directly? Perhaps:

- `->whereIn(...)` should be called on the $plants object, not the datatable. Also there's probably a syntax error with that extra `}` sitting around before the make function. Should look like:
```php
 return Datatables::of($plants->whereIn('id', [1,2,3,4]))
     ->make(true);
```
Personally I would move the `whereIn(...)` up to the variable, and since you're selecting from the plant model itself table prefix isn't necessary (not sure if that would cause an error, though, just personal preference here)
```php
$plants = Plant::select(['id','name','created_at','updated_at'])->whereIn('id', [1,2,3,4]);

return Datatables::of($plants)->make(true);
```

I think that should do it :)

**Comment by Razorsheep** [comment]
Just a quick reply before I try your suggestions.

I specifically made the above example as a copy of Yajra's own Usage example taken from [https://github.com/yajra/laravel-datatables/wiki/Usage] (https://github.com/yajra/laravel-datatables/wiki/Usage)


Datatables now extends Query Builder's functionality which means that you can directy filter results using the Datatables class.

```php
// Query Builder's extended function.
// See Laravel Query Builder docs for more details.
return Datatables::of($user)
    ->whereIn('id', [1,2,3])
    ->whereNull('id')
    ->make(true);
```

**Comment by muhghazaliakbar** [comment]
i have same problem with this.

**Comment by yajra** [comment]
@Razorsheep, @muhghazaliakbar sorry for misleading documentations. Most of the recent updates/features are only available on v5.x. Laravel 4.2 version has a very limited features which are derived from the original bllims version.

@johnhatch suggestion should fix your issue. thanks!

**Comment by yajra** [comment]
Added a [note](https://github.com/yajra/laravel-datatables#laravel-42--datatable-v19x-users) on read me for legacy code users. Sorry for the confusions.

**Comment by Razorsheep** [comment]
Thanks for clarifying. Especially the custom filtering functions were quite
a source of frustration.

Well another excuse to update to laravel 5... 😉

Thanks for the good work!
Den 09/10/2015 06.56 skrev "Arjay Angeles" <notifications@github.com>:
