### ISSUE TITLE
Column Filtering with Multiple Select (Many-to-Many relationship)

### ISSUE THREAD

**Issue by v10dynamite** [yajra/laravel-datatables#2071]
Hi Yajra, I have a problem when filtering data by using multiple select in belongs to many relationship

```php
if ($category = $request->get('category')) {
    if ($category == -1)
        $products = $products->leftJoin('category_product', function ($join) {
            $join->on('products.id', '=', 'category_product.product_id');
        })->whereNull('category_product.product_id');
    else {
        $categories = explode(',', $category); // Convert into Array

        $products = $products->whereHas('categories', function ($query) {
            $query->whereIn('categories.id', $categories); // Return 500 internal server error
        });


        $products = $products->whereHas('categories', function ($query) {
            $query->whereIn('categories.id', [2, 3]); // This works fine
        });
    }
}
```
I pass a string of categories id that the multiple select returned like "2, 3, .." to my Controller then convert it into an array [2, 3]
Then I use eloquent command for filtering but it returns Ajax Error (500 Internal Server Error) -> So I can't filter it
But when I hard-code the array then it works!

### System details

- PHP Version : 7.2.9
- Laravel Version : 5.8.7
- Laravel-Datatables Version : 9.x

**Comment by PrafullaKumarSahu** [comment]
Have you tried to check what you are getting for `$categories`, if you are not getting a one-dimensional array, I do not think it will work.

**Comment by v10dynamite** [comment]
Oh yes, I checked it
I switched to this way and it works
```php
$categories = explode(',', $category);
$products = $products->join('category_product', function ($join) {
                        $join->on('products.id', '=', 'category_product.product_id');
                    })->whereIn('category_product.category_id', $categories)->distinct('products.id');
```
But I don't understand why the old way doesn't work.

**Comment by pd2011** [comment]
> 
> 
> Oh yes, I checked it
> I switched to this way and it works
> 
> ```
> $categories = explode(',', $category);
> $products = $products->join('category_product', function ($join) {
>                         $join->on('products.id', '=', 'category_product.product_id');
>                     })->whereIn('category_product.category_id', $categories)->distinct('products.id');
> ```
> 
> But I don't understand why the way above doesn't work.

Hello, sorry to bother but you could send me all the code of this, please? I can't make it work :\
