### ISSUE TITLE
datatables with ajax

### ISSUE THREAD

**Issue by dily86** [yajra/laravel-datatables#2074]
Hi,
I use datatables in ajax. On a column I load the content of a many to many relationship. However, when I try to sort this column in ascending or descending order it doesn't work. This is a list of all the artists in a work. I put:
 "columns": [
                    { data:'id', name:'works.id' },
                    { data:'works', name:'works.title' },
                  { data:'artists', name: works.artists}, 
                ],
but it doesn't work.
Thank you in advance for your help.

### System details

- Operating System: Windows
- PHP Version : 7.1.3
- Laravel Version : 5.6
- Laravel-Datatables Version : ~8.0

**Comment by dily86** [comment]
?????????????????????????????

**Comment by yajra** [comment]
The code looks fine. Try inspecting the ajax response to get a hint of what was causing the issue.
