### ISSUE TITLE
aliases losts in order by

### ISSUE THREAD

**Issue by eriksape** [yajra/laravel-datatables#2075]
### Summary of problem or feature request

Problem with aliases in query on the order.

### Code snippet of problem

```php
public function datatable(Request $request)
{
    $report = ReportCourseUser::with(['user']);
    return DataTables::eloquent($report)->toJson();
}
```

I notice when i sort a column the query is the next

```sql
SELECT * 
FROM   "report_course_users" 
       LEFT JOIN "users" AS "users_0" 
              ON "report_course_users"."user_id" = "users_0"."id" 
WHERE  "users"."deleted_at" IS NULL 
       AND "report_course_users"."deleted_at" IS NULL 
ORDER  BY "users_0"."username" ASC 
LIMIT  10 offset 0 
```
in the line `WHERE  "users"."deleted_at" IS NULL ` users lost the alias 🤔 

### System details

- Operating System: debian
- PHP Version: 7.2.16
- Laravel Version: 5.8
- Laravel-Datatables Version: 9

**Comment by yajra** [comment]
You need to update to the latest version where https://github.com/yajra/laravel-datatables/pull/2051 was reverted. Self join is not yet supported.
