### ISSUE TITLE
Perform search on customized column using transformer via eloquent relationship

### ISSUE THREAD

**Issue by eternalBlast** [yajra/laravel-datatables#2077]
### Summary of problem or feature request

Hi, i have tried several way to do search on customized column but still have some problems. Cannot search if using name in transformer. Always got error message like undefined column when using customized column. See below for details.

### Code snippet of problem

This is the class 
MyProj/DataTable/DepositDataTable.php

```
public function query(DepositRequest $model)
    {
        return $model->newQuery()->with('deposit');
    }

protected function getColumns()
    {
        return [
            'id' => ['title' => 'Id'],
            'status' => ['title' => 'Status', 'name' => 'deposit.verify_status', 'data' => 'status'],
            'due_date' => ['title' => 'Due Date', 'name' => 'due_date', data' => 'due_date'],
        ];
    }
```
Inside the ```getColumns``` method, the ```deposit.verify_status``` column is an integer in the table structure. And deposit is a model that have relation with deposit request. I read the doc about datatable that the performing search is based on name. So, when i used the method above. I can search value with 0, 1 and so on, but cannot if the value has been updated using some hardcoded like in this DepositTransformer class.
MyProj/DataTable/DepositTransformer.php
```
public function transform(DepositRequest $depositRequest)
    {
         if ($depositRequest->deposit->verify_status == 1) {
            $status = "accepted";
         } else if ($depositRequest->deposit->verify_status == 2) {
            $status = "rejected";
         }
         $due_date = $depositRequest->deposit->created_at->addDay()->toDateTimeString();
         $transformedArray = [
               'id' => $depositRequest->id,
               'deposit_type_id' => $depositRequest->depositType->name,
               'status' => $status,
               'due_date' => $due_date,
         ];
    }
```
In my Controller, i render the deposit datatable on index method like this
```
public function index(Request $request, DepositDataTable $dataTable)
    {
        return $dataTable->render('deposit');
    }
```

 If checking the value and return string value like above for ```status``` and due_date is new column the based on calculation and not saved on the table, How can we perform search? I read some other doc and issue but can't get it right. I think for ```status```, we can use relation and make a master table for it. But, what if the conditions like above? Any help will be appreciated.
### System details

- Operating System => Mac OS High Sierra 10.13.4
- PHP Version => php v7.3.0
- Laravel Version => Laravel 5.5 LTS
- Laravel-Datatables Version -> yajra/laravel-datatables v1.5.0

**Comment by yajra** [comment]
Have you tried using filter column https://yajrabox.com/docs/laravel-datatables/master/filter-column? Just remember that you just have to make an SQL that works and it should work on dataTables too. Thanks!
