### ISSUE TITLE
How to add export buttons in controller?

### ISSUE THREAD

**Issue by Tarcisiofl** [yajra/laravel-datatables#2078]
### Summary of problem or feature request

I'm trying to add PDF and XLS export options to my users.
However, taking a look on the documentation I just found out the implementation when the class extends DataTable.
In my case, the controller is responsible for get the data and send it to the view, and it doesn't extends DataTable.

How can I add the export feature?

### Code snippet of problem

```php
class ShiftController extends Controller
{
    /**
     * @var \Yajra\Datatables\Datatables
     */
    private $dataTable;

    /**
     * ShiftController constructor.
     *
     * @param \Yajra\Datatables\Datatables $dataTable
     */
    public function __construct(Datatables $dataTable)
    {
        $this->dataTable = $dataTable;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return JsonResponse
     * @throws Exception
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $model = Shift::withTrashed()->select('shifts.*');
            return $this->dataTable
                ->eloquent($model)
                ->addColumn('deleted_at', function (Shift $shift) {
                    if($shift->trashed())
                        return '<span class="status--denied">INATIVO</span>';
                    return '<span class="status--process">ATIVO</span>';
                })
                ->addColumn('edit', function (Shift $shift) {
                    return '<div class="table-data-feature"><a href="'.route('shifts.edit', ['shift' => $shift]).'" class="item" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="zmdi zmdi-edit"></i></a></div>';
                })
                ->rawColumns(['deleted_at', 'edit'])
                ->make(true);
        }

        $shifts = Shift::withTrashed()->get();
        return view('shifts.index', ['shifts' => $shifts]);
    }
}
```

### System details

- Operating System Windows 10
- PHP Version 7.2
- Laravel Version 5.8
- Laravel-Datatables Version 9

**Comment by yajra** [comment]
You need to implement the service class approach if you want to have some buttons support. If not, you would have to write your own export handler for it to work. See https://datatables.yajrabox.com/services/basic for ref.

**Comment by tduffy-saf** [comment]
> You need to implement the service class approach if you want to have some buttons support. If not, you would have to write your own export handler for it to work. See https://datatables.yajrabox.com/services/basic for ref.

What exactly is the service class approach? I can't seem to load the documentation site.
