### ISSUE TITLE
How to delete a record with yajra/laravel datatables with ajax

### ISSUE THREAD

**Issue by adnanalidzinemedia** [yajra/laravel-datatables#2081]
### Summary of problem or feature request

hey i am using yajrabox in my project i want to delete and edit a record i have added a column and in column i have added a blade file which contains delete and edit buttons and i have assigned classes i want that if i click on the delete button it delete the corresponding record with ajax and same on clicking on the edit button.
` <script>
        $(document).ready(function(){
           
            drawCallback:$(function() {
                $('#myTable').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: '{!! route('get.users') !!}',
                    columns: [
                        { data: 'id', name: 'id' },
                        { data: 'name', name: 'name' },
                        { data: 'email', name: 'email' },
                        { data: 'action', name: 'action' }
                    ]
                });
            });

            $(".edit_user").click(function(){
                alert("The paragraph was clicked.");
              });
        });
           
      
    </script>`
and in my blade file i have 
`<a href="{{ route('delete.user', ['id' => $user->id]) }}"><button class="btn btn-danger btn-sm delete_user" value="{{$user->id}}">Delete</button></a>
<button class="btn btn-success btn-sm edit_user" value="{{$user->id}}">Edit</button>
`
![Capture](https://user-images.githubusercontent.com/49089888/57292258-c9a92e00-70da-11e9-9c72-7c4413540a4c.PNG)
`

**Comment by noogen** [comment]
Looks like you're using client-side code with laravel-datatables.  You can take a look at this example: https://stackoverflow.com/questions/38617157/removing-rows-from-datatables-from-a-ajax-call

Alternatively, you can do it in Vue with this example: https://github.com/niiknow/laratt-api/blob/master/resources/js/views/Contacts.vue#L99

Demo: http://laratt.niiknow.org/home/contacts
Using my vue wrapper component: https://github.com/niiknow/vue-datatables-net

**Comment by adnanalidzinemedia** [comment]
Thanks Dear noogen
