### ISSUE TITLE
glyphicons in pagination

### ISSUE THREAD

**Issue by frechina** [yajra/laravel-datatables#209]
When I load a datatable I see in pagination the following strings "First", "Last", "Next", "Previous" instead of glyphicons. How can I fix this?

**Comment by yajra** [comment]
There are several pagination plugins available for datatables. http://datatables.net/plug-ins/pagination/.
I just used some custom scripts on my demo page which makes it different.

**Comment by frechina** [comment]
that solved my problem, thank you!
