### ISSUE TITLE
Documentation (yajrabox.com) is down.

### ISSUE THREAD

**Issue by Shkeats** [yajra/laravel-datatables#2093]
yajrabox.com is down and we can't access the docs. Seems to impact the main site and subdomains like datatables.yajrabox.com.

Getting the DNS_PROBE_FINISHED_NXDOMAIN error. Checked with dns propagation tools and it looks like it's widespread and not specific to me or my DNS provider.

Hope this report helps.

**Comment by mohamedaitbella** [comment]
how can i access doc , the website is down till now

**Comment by yajra** [comment]
Having some billing issue with the server :). Atm, please access the docs repo https://github.com/yajra/laravel-datatables-docs.

**Comment by n588E** [comment]
Where can I get js files while your server is down? 

<script src="https://datatables.yajrabox.com/js/jquery.min.js"></script>
<script src="https://datatables.yajrabox.com/js/bootstrap.min.js"></script>
<script src="https://datatables.yajrabox.com/js/jquery.dataTables.min.js"></script>
<script src="https://datatables.yajrabox.com/js/datatables.bootstrap.js"></script>

**Comment by Yahav** [comment]
@yajra readthedocs.io  thank me later.

**Comment by rogerad** [comment]
how to we install the datatables library in our application so the program will operate when the website is down ?

**Comment by Shkeats** [comment]
Closing as the docs are now back online.

**Comment by SupunSam** [comment]
@yajra docs are offline again.

**Comment by zlanich** [comment]
The docs site is down again, lol. readthedocs.io? :D

**Comment by andikurnia** [comment]
And it's down again tonight :(

**Comment by Sohail-Ansari** [comment]
Your website is down again.
I will host your documentation and all for free. Because your billing issue becomes a really big issue for the people using it. Do let me know. I will do it with anything in return. Simple we are this much sick of your billing issue. Please consider this offer seriously and do let me know.

**Comment by kaloczikvn** [comment]
Still down...

**Comment by rollerdead** [comment]
> Still down...

still down..

**Comment by hafidluqman50** [comment]
still down :(

**Comment by yajra** [comment]
I just finished setting up the new server for http://yajrabox.com. Please check again. Demo app is still down though.
