### ISSUE TITLE
Documentation Page

### ISSUE THREAD

**Issue by esmaei1** [yajra/laravel-datatables#2097]
Documentation Page is down:
http://yajrabox.com/docs/laravel-datatables

**Comment by armadeas** [comment]
yes its down, can't access from indonesia

**Comment by AdrianKuriata** [comment]
@yajra Could you make something with that? Or add markdown with documentation on github? Or github pages? Or change server, 50% time in the year page is down?

**Comment by Yahav** [comment]
+1
