### ISSUE TITLE
Datatable from lumen api to laravel application not working

### ISSUE THREAD

**Issue by elmanti** [yajra/laravel-datatables#2099]
I want to send return Datatables::of(DB::table('ride'))->make(true); from lumen api to laravel application by Guzzle client, i can display data in laravel application but i can't sort or search : the request is going to API but nothing is happing. I thing the request sending by Guzzle client is not the same reveive in API Lumen :

API code :

```php
public function rides(Request $request){
        return Datatables::of(DB::table('ride'))->make(true);
    }
```

Laravel Application code :

```php
$resultat = $client_ppm->request('get', $url_, [
            'form_params' => $datafield_array,
            'headers' => [
                'Authorization' => 'Bearer ' . $token,
                'Content-type' => 'application/json',
                'Accept' => 'application/json',
                'from' => 'portail'
            ]
                ]
        );
        return $resultat->getBody()
```

**Comment by yajra** [comment]
Make sure that your data field array matches the convention that dataTable uses. You can check the package test suit for some reference.

**Comment by engineerknow** [comment]
how to fix it ?

i check in postman data is success 
but i see the json return draw = 0 i think this is a problem make not showing to datatable 

but i don't know how to fix it
