### ISSUE TITLE
How can I sum amount in footer ?

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#210]
Is it possible to sum the column amount in my footer ?
```
<table class="table table-striped table-condensed table-hover" width="100%" id="mytable">
                             <thead>
                             <tr>


                                 <th>id</th>
                                 <th>salary</th>
                                 <th>amount</th>

                             </tr>

                             <tfoot>
                             <tr>
                                 <th colspan="2" style="text-align:right">total amount:</th>
                                 <th></th>
                             </tr>
                             </tfoot>
                             </thead>
                         </table>
```

Thank you in advance.

**Comment by yajra** [comment]
If you want to add the total amount, then you can just eloquent to get the sum like `Salary::sum('amount')` or something.

Another way, is by hooking on datatables events like draw callback then sum your amount and display it. Haven't tried this yet but some js codes should do this. And you would also need to look on datatables jquery api docs on how to it. http://datatables.net/reference/api/

**Comment by ezekel** [comment]
@yajra , Thank you
