### ISSUE TITLE
Carbon 1 is deprecated and needs to be upgraded to Carbon 2

### ISSUE THREAD

**Issue by mureithimaina** [yajra/laravel-datatables#2104]
### Summary of problem or feature request

Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.

**Comment by yajra** [comment]
I think we don't have any carbon dependencies on this package. Might be related to other packages.
