### ISSUE TITLE
how can reload my datatable when i delete from function destroy

### ISSUE THREAD

**Issue by TranceDevCode** [yajra/laravel-datatables#2109]
### Code snippet of problem

If applicable, please include a copy of your code
which triggers the suspected bug.

You may use the markdown php code tags to format your paste:

```php
    public function getClientes(){
            return datatables()
	        ->eloquent(Clientes::query())            
            ->addColumn('btn','admin.clientes.partials.btn')
            ->rawColumns(['btn'])
            ->toJson(); 
        }
```
and this is my function destroy
```php
public function destroy($ID){
        $Clientes = Clientes::FindOrFail($ID);
        $result = $Clientes->delete();
        return Redirect::to('admin/clientes')->with(session()->flash('success', 'Registro eliminado exitosamente') );
  (here can reload my datatable) this because i want delete the return redirect::to xxxx 
    }
```

Thank you bro

- Operating System Dev mode is windows, production mode is linux
- PHP Version 7.0
- Laravel Version 5.5 
- Laravel-Datatables Version 8.8

**Comment by yajra** [comment]
You need to use ajax to delete the record. On success, just call `oTable.draw()`, where `oTable` is the variable you used for your dataTable.

**Comment by vigneshmersal** [comment]
To reload,
window.LaravelDataTables["user-table"].ajax.reload();
