### ISSUE TITLE
select all or All in controller

### ISSUE THREAD

**Issue by mohammad6006** [yajra/laravel-datatables#211]
in controller I use this code :
```
public function anyData()
    {
        return Datatables::of(User::select('*'))->make(true);
    }
```
and when I use search in datatable every character send a request and query to database

but when i use all() instead of select * , json replaced

which one should I use?

**Comment by yajra** [comment]
I suggest you use the query builder approach to avoid possible performance issues when your data becomes large. Using `User::select()` or `User::query()` should do the trick.

What do you mean by json replaced? Output data should be the same on query or all method.

**Comment by yajra** [comment]
> when I use search in datatable every character send a request and query to database.

You need to use a plugin like `fnFilterOnReturn` to trigger search upon submit and not on changed event.  See this demo for ref: http://datatables.yajrabox.com/collection/github
