### ISSUE TITLE
HTML BUILDER can not use Ajax

### ISSUE THREAD

**Issue by minhliem86** [yajra/laravel-datatables#2110]
### Summary of problem or feature request

HTML BUILDER ajax can not read data because JS return string not a JS function.

### Code snippet of problem

In Controller:
 $builder->columns(...)->ajax(
            [
                'data' => 'function(d) { d.name = "test" ;}'
            ]
        );

In View:
This is result when run {!! $html->scripts() !!}

$("#dataTableBuilder").DataTable({"serverSide":true,"processing":true,"ajax":{"data":"function(d) { d.name = \"test\" ;}"}.....

--> The problem is "function(d) { d.name = \"test\" ;}" is a string so Request can not get name as a query string.

--> IF I remove double quotation marks -->function(d) { d.name = "test" }. it work exactly as my expectation.

Sorry about my English.

### System details

- Operating System
- PHP Version
- Laravel Version: 5.4
- Laravel-Datatables Version: ^7.0

**Comment by yajra** [comment]
Not sure, but I think it's not yet supported on the version you are using (^7.0). I suggest you update to the latest version if possible.

**Comment by yajra** [comment]
I think a workaround here would be to use the [initComplete](https://datatables.net/reference/option/initComplete) callback and then append your data? Or something along the callbacks of dataTable. Can't recall how I do it in the past.
