### ISSUE TITLE
Get sum per row

### ISSUE THREAD

**Issue by donpedro0914** [yajra/laravel-datatables#2111]
### Summary of problem or feature request

How can i get the sum per row?. I have tried to replicate the footerCallback to rowCallback but still no luck.

### System details

- Operating System
- PHP Version : 7.2
- Laravel Version : 5.7
- Laravel-Datatables Version

**Comment by yajra** [comment]
Sum per row or per page? Anyways, you can try computing it on the backend and return it as additional data response. See https://yajrabox.com/docs/laravel-datatables/master/response-with for ref.

**Comment by yajra** [comment]
To access the data on front-end, just use `oTable.ajax.json()`.
