### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by 91Abdullah** [yajra/laravel-datatables#2112]
### Summary of problem or feature request

Calling DataTables::of for collection is leading to error 

"A non well formed numeric value encountered"

{"draw":1,"recordsTotal":21,"recordsFiltered":0,"data":[],"error":"Exception Message:\n\nA non well formed numeric value encountered"}

### Code snippet of problem

```
public function getReport(Request $request)
    {
        $start = Carbon::parse($request->start)->format('Y-m-d ');
        $end = Carbon::parse($request->end)->format('Y-m-d');

        $cdrs = Cdr::whereBetween(DB::raw('date(start)'), [$start, $end])->get(['src', 'dst', 'start', 'answer', 'end', 'duration', 'disposition', 'recordingfile']);

        //dd($cdrs);
        return DataTables::of($cdrs)->toJson();
    }

```
- Operating System Windows 10
- PHP Version 7.2
- Laravel Version 5.8
- Laravel-Datatables Version 9.0

**Comment by 91Abdullah** [comment]
Sorry to bother guys. I was doing a silly mistake! Calling get() to select columns.

**Comment by 91Abdullah** [comment]
Error is coming when I put serverSide: true

**Comment by yajra** [comment]
You should not use `start` on your variable name because DT uses this for pagination. Try changing the variable name.

```
$request->start --> $request->start_date
```

**Comment by amrikarisma** [comment]
> You should not use `start` on your variable name because DT uses this for pagination. Try changing the variable name.
> 
> ```
> $request->start --> $request->start_date
> ```

Wowww its work for me. Thank you
