### ISSUE TITLE
Data table rendering so much slow one record taking 5 seconds to load 

### ISSUE THREAD

**Issue by AliSultanKhan** [yajra/laravel-datatables#2116]
Data table rendering so much slow

### Client Side Code

![image](https://user-images.githubusercontent.com/33395254/59443045-c1988880-8e14-11e9-9a49-038c6385c00a.png)

### Server Side Code

![image](https://user-images.githubusercontent.com/33395254/59443302-2b189700-8e15-11e9-8498-ff803ada45c5.png)
### System details
- Operating System Windows10
- PHP Version 7.1.9
- Laravel Version 5.7

**Comment by yajra** [comment]
Maybe you have a binary data / image stored on your DB? If yes, please exclude it from the response.

**Comment by pirex360** [comment]
Any solution ?
