### ISSUE TITLE
Excel export filename is always set to current page's title

### ISSUE THREAD

**Issue by wassim** [yajra/laravel-datatables#2117]
### Summary of problem or feature request

When I use excel export, the downloaded file name is always set to current page's title (page-title.xlsx). Even when my model's DataTable class has a function to override the filename:

```php
    /**
    * Get filename for export.
    *
    * @return string
    */
    protected function filename()
    {
        return 'Users_' . date('YmdHis');
    }
```

Any ideas how I can fix this?

### System details

- Operating System: Windows
- PHP Version: 7.2.7
- Laravel Version: 5.8
- Laravel-Datatables Version: 9

**Comment by wassim** [comment]
Kindly bumping this out. Does anyone have the same problem?

**Comment by yajra** [comment]
Not sure on this one but maybe a browser issue? Can you please try on all browsers? Thanks!

**Comment by Slivicon** [comment]
I can confirm I'm experiencing this issue in latest version of Chrome, Edge and Internet Explorer.

I may try to use the dt export options for the buttons to try and control the filename in the interim: https://datatables.net/forums/discussion/32512/dynamically-change-filename-when-exporting

**Comment by Slivicon** [comment]
I am using the service option and the HTML builder. A workaround I've found is to set the filename in the parameters for the builder and call the Yajra datatable filename function:

```php
class AppDataTable extends DataTable
{

```
```php

return $this->builder()
    ->parameters([
        'buttons' =>  [
            [
                'extend' => 'collection',
                'text' => __('Export'),
                'buttons'   => [
                    [
                        'extend' => 'csvHtml5',
                        'text' => __('CSV'),
                        'filename' => $this->filename(),
                        'exportOptions' => ['modifier' => ['selected' => true]]
                    ],
                    [
                        'extend' => 'excelHtml5',
                        'text' => __('Excel'),
                        'filename' => $this->filename(),
                        'title' => '',
                        'exportOptions' => ['modifier' => ['selected' => true]]
                    ],
                ]
            ]
        ];

```
```php

}
```
