### ISSUE TITLE
I want to start Dt_RowIndex from 0?

### ISSUE THREAD

**Issue by abhaywani114** [yajra/laravel-datatables#2119]
### Summary of problem or feature request

I want to start Dt_RowIndex from 0? How can I modify the index addIndexColumn()?

### System details

- Operating System
- PHP Version 7.0
- Laravel Version 5.8

**Comment by yajra** [comment]
Not supported but I think a work around would be by adding a render function and just subtract 1 from the actual value?

```js
render: function(data) {
  return data - 1;
}
```
