### ISSUE TITLE
HTML Builder with custom javascript template and Html template

### ISSUE THREAD

**Issue by minkbear** [yajra/laravel-datatables#212]
First, Thanks for your effort for this package. It's saved my time much.
It's the best if there is blade template to be customize.
For example: https://github.com/Chumper/Datatable/tree/master/src/views

**Comment by yajra** [comment]
@minkbear, I think this is good addition to the package :+1: . Will try to add this on future releases. Currently occupied atm so it may take some time to be implemented. Thanks!

Btw, can you explain how the js template was used? Any proposed workflow how to add this? Haven't used Chumper yet.

**Comment by yajra** [comment]
Upcoming v6.0 would now allow the script to load from a template. Kindly check it out if you time. Thanks!

**Comment by minkbear** [comment]
@yajra thanks
