### ISSUE TITLE
How to receive Additional Data Response in footerCallback function?

### ISSUE THREAD

**Issue by fsuuaas** [yajra/laravel-datatables#2120]
### I'm trying to show sum of price all page (Server Side)

footerCallback function showing only current page sum amount. So i'm use Additional Data Response to get total sum amount of all page. 
`->with('gtotal', $orders->sum('grand_total'))`
But i'm unable to show this response in footer callback function or in blade file.
### Code snippet of problem
[Image 1](https://i.imgur.com/olxebwC.png)
[Image 2](https://i.imgur.com/HtAsWCS.png)

### System details

- Operating System : Windows 10
- PHP Version 7.1.28
- Laravel Version 5.6
- Laravel-Datatables Version 1.0

**Comment by yajra** [comment]
Just fetch the data from ajax json. 

```js
total = api.ajax.json().gtotal
```

**Comment by HashmatWaziri** [comment]
**Solution** based on above comment . Thanks @yajra 
JS:

       var oTable = $("#attendanceTable").DataTable({

            createdRow: function (row, data, dataIndex) {
                $(row).find('td:eq(0)').css('text-align', 'center');
            },
            "info": false,
            "paging": false,
            "serverSide": true,
            "processing": true,
            "scrollX": true,
            "searching": false,

            "ajax": {
                "url": "{{url('workplace/humanresource/attendance/'.$employee->id)}}",

                data: function (d) {
                    d.name = $('input[name=name]').val();
                    d.monthFilter = $("#monthFilter").val();
                    d.dateRange = $('input[name=datefilter]').val();
                    d.status = $("#status").val();
                    d.roles = $("#roles").val();
                }
            },
            "columns": [

                {data: 'date', name: 'date', 'visible': false},
                {data: 'dayandDate', name: 'dayandDate'},
                {data: 'insandouts', name: 'insandouts'},
                {data: 'action', name: 'action'},

            ],

        });

        oTable.on('draw.dt', function() {
            // alert(oTable.ajax.json().posts);
            $("tfoot>tr>th#twh").html( oTable.ajax.json().totalWorkingHours);
            $("tfoot>tr>th#trwh").html(oTable.ajax.json().totalRequiredWorkingHours);

            $('table#attendanceTable>tfoot').toggle();

        })

Controller:

             return \Yajra\DataTables\DataTables::of($daily_record)
                ->with('totalWorkingHours','<span style="background: #ff8664 " class="badge badge-info">'. $total_working_hours.' 
         Hours</span>')
                ->with('totalRequiredWorkingHours', '<span style="background: #57a7ff ; color: #fefefe; " class="badge badge-info">'. 
          $total_required_hours.' Hours</span>')
                ->rawColumns(['dayandDate', 'insandouts', 'action','totalWorkingHours','totalRequiredWorkingHours'])
                ->toJson();


![Capture 2021-02-02 at 0 23 58](https://user-images.githubusercontent.com/10204499/106486811-017e1900-64ed-11eb-896c-84b1e85e5956.png)

**Comment by sluxzer** [comment]
this answer just save my day
