### ISSUE TITLE
Separate whitelist blacklist for search and sort

### ISSUE THREAD

**Issue by liepumartins** [yajra/laravel-datatables#2121]
### Summary of problem or feature request
I have columns e.g. `name`, `sku`, `stock`, `price`. I would like to whitelist `name` and `sku` for search.
If this is done, other columns cease to be sortable. Desired behaviour would be to define sortable and searchable separately, same way like it is done on client side JS.

```
$datatables->whitelist('name', 'sku');
// `stock` and `price` no longer can used for sorting
```
Desired would be to create e.g.
```
$datatables->whitelistSearch('name', 'sku');
$datatables->whitelistSort('*');
```

### System details

- Operating System Linux
- PHP Version PHP 7.3.6-1+ubuntu18.04.1
- Laravel Version 5.8
- Laravel-Datatables Version 9.0

**Comment by yajra** [comment]
Not yet supported but I think we can do a workaround. Try something like below:

```php
$datatables->whitelist('name', 'sku')
  ->orderColumn('price', 'price $1')
  ->orderColumn('stock', 'stock $1');
```

**Comment by GregorVoelkl** [comment]
Are there any plans on implementing this? Would be a greate feature as client side javascript can be easily manipulated and sorting certain columns could trigger application errors.
