### ISSUE TITLE
Cannot get pivot object on eager load many to many relationship

### ISSUE THREAD

**Issue by handhikadj** [yajra/laravel-datatables#2122]
### Summary of problem or feature request
I don't know how to get the pivot object of the M2M relationship on this package.
show me an exhaustive tutorial how to get the pivot object as well as the related data on the model object

### Dumped Data
![image](https://user-images.githubusercontent.com/22522638/59767652-f0a77200-92cc-11e9-9784-31cffa2bb4bd.png)

### Code snippet of problem
   ```php
     $groupModelWith = GroupModel::with('groupmap')->select('group.*')->where('id', $gid);

        return datatables()->of($groupModelWith)
            ->addColumn('group-name', function ($groupModelMember) {
                // get groupmap->name
            })
            ->addColumn('group-number', function ($groupModelMember) {
                // get groupmap->created_at (for example)
            })
            ->addColumn('action', function ($groupModelMember) {
                // get pivot->id
            })
            ->addIndexColumn()
            ->make(true);
```

### System details

- Operating System: Windows 10
- PHP Version: v7.1.0
- Laravel Version: 5.6.39
- Laravel-Datatables Version: 1.2.0

**Comment by ihabhamad** [comment]
You Can Use foreach
$groupModelWith = GroupModel::with('groupmap')->select('group.*')->where('id', $gid);

     return datatables()->of($groupModelWith)
         ->addColumn('group-name', function ($groupModelMember) {
              $names = [];
                foreach ($groupModelMember->groupmap as $group) {
                    $names[] = sprintf('<span class="badge grey waves-effect waves-orange  white-text">%s</span>', $group->name);
                }
                return implode(' ', $names);
         })
         ->addColumn('group-number', function ($groupModelMember) {
             // get groupmap->created_at (for example)
         })
         ->addColumn('action', function ($groupModelMember) {
             // get pivot->id
         })
         ->addIndexColumn()
         ->make(true);

**Comment by ihabhamad** [comment]
@handhikadj on the front side still access them 
columns = [
data: 'groupmap', name: 'groupmap',
                       render: function ( data, type, row, meta ) {
                           return data[0].name;
                       }
]

**Comment by handhikadj** [comment]
what about the `pivot->id`?

**Comment by ihabhamad** [comment]
If you want to access thim on backend side still under foreach 

$groupmap->povit->id

On front end

data[0].povit.id

**Comment by handhikadj** [comment]
Thank you for your help. Gonna try it

**Comment by Karacraft** [comment]
How to search simple many to many relationship?
