### ISSUE TITLE
Searching not working on using join tables by backend builder

### ISSUE THREAD

**Issue by prasanthtippu** [yajra/laravel-datatables#2123]
### Searching not working

Search not working on using join tables by back-end builder.i am using backend builder

public function query(User $model){
 return DB::table('users')->join('departments', 'users.dept_id', '=', 'departments.id')
            ->select(['users.id', 'users.name as name', 'users.email', 'departments.name','users.sum','users.created_at', 'users.updated_at']);
    }
protected function getColumns()
    {
        return[
                ['data' => 'id', 'name' => 'id', 'title' => 'Id'],
                ['data' => 'name', 'name' => 'name', 'title' => 'Name'],
                ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
                ['data' => 'departments.name', 'name' => 'departments.name', 'title' => 'Department'],
                ['data' => 'sum', 'name' => 'sum', 'title' => 'Sum'],
                ['data' => 'created_at', 'name' => 'created_at', 'title' => 'Created At'],
                ['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Updated At'],
            ];
}

### System details

- Operating system - Linux mint 19
- PHP Version - 7.3
- Laravel Version - 5.7
- Laravel-Datatables Version - 8.0

**Comment by yajra** [comment]
I suggest you inspect the ajax request to be able to see the error response. I think there is an error on the generated SQL and you can debug it from there. Also when using join, you should include the table name too to avoid some SQL errors.

```php
return[
  ['data' => 'id', 'users.name' => 'id', 'title' => 'Id'],
  ['data' => 'name', 'name' => 'users.name', 'title' => 'Name'],
  ['data' => 'email', 'name' => 'users.email', 'title' => 'Email'],
  ['data' => 'departments.name', 'name' => 'departments.name', 'title' => 'Department'],
  ['data' => 'sum', 'name' => 'sum', 'title' => 'Sum'],
  ['data' => 'created_at', 'name' => 'users.created_at', 'title' => 'Created At'],
  ['data' => 'updated_at', 'name' => 'users.updated_at', 'title' => 'Updated At'],
];
```
