### ISSUE TITLE
WEBSITE IS STILL DOWN

### ISSUE THREAD

**Issue by verovexsler** [yajra/laravel-datatables#2124]
Website is still down, therefore data table is not working on my application.

Everything works fine except anything related to yajra.

- Operating System - Windows 10 Pro 1803
- PHP Version - 7.3.1
- Laravel Version - 5.7.28
- Laravel-Datatables Version- 7.0?

**Comment by ihabhamad** [comment]
Website is still down

**Comment by ifaniqbal** [comment]
https://github.com/yajra/laravel-datatables-docs

**Comment by verovexsler** [comment]
I need the javascript files. My entire project has been finished for a while, but the data table to show all the information is no longer appearing due to said files not being hosted on a server.

**Comment by iseus** [comment]
> I need the javascript files. My entire project has been finished for a while, but the data table to show all the information is no longer appearing due to said files not being hosted on a server.

You have several options to solve it.

1. Get an other CDN. Like unpkg.org. Or go to the datatables.net site and get the link from there.
2. Install it with NPM. If you use Mix/Webpack you can require() the js files and @import the css ones.

If you like CDN hosted versions, go with the first option, and embed it directly from datatables.net or from unpkg.
[https://datatables.net/download/](https://datatables.net/download/)

**Comment by verovexsler** [comment]
@iseus  yes thank you. I have done so already and everything works just fine. Also downloaded and backed up all css and js files just in case.
