### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by funkymonk91** [yajra/laravel-datatables#2126]
https://web.archive.org/web/20181105174706/https://yajrabox.com/docs/laravel-datatables/master
will do for now, but the documentation site for the package is down.

**Comment by alr2413** [comment]
The referred archive link contains the old documents. I'm recently upgraded the package from v8.9 to v9.4 and I wanna know the latest changes & upgrade guide, because it seems that the orderColumn & filterColumn do not work anymore (my application is based on the Service mode of DataTable).

**Comment by alr2413** [comment]
> I'm having the same problem.
> The referred archive link contains the old documents. I'm recently upgraded the package from v8.9 to v9.4 and I wanna know the latest changes & upgrade guide, because it seems that the orderColumn & filterColumn do not work anymore (my application is based on the Service mode of DataTable).

Sorry. That was my mistake, the name of columns in client and server side do not match with each other, so the callback functions filterColumn and orderColumn are never called.
Now my problem has been solved, and since the documentation website is now up, please close this issue.

**Comment by funkymonk91** [comment]
Site is live again :).
