### ISSUE TITLE
Html builder and buttons

### ISSUE THREAD

**Issue by gidaban** [yajra/laravel-datatables#2127]
### Summary of problem or feature request

Hello Guys, so far i am using HTMLbuiler for generate datatable however i want add edit and delete buttons 

### Code snippet of problem

```php
        if (request()->ajax()) {
            return DataTables::of(Role::all())->toJson();
        }
        $html = $builder->columns([
            ['data' => 'id', 'name' => 'id', 'title' => 'Id'],
            ['data' => 'name', 'name' => 'name', 'title' => 'Name'],
            ['data' => 'display_name', 'name' => 'Display Name', 'title' => 'Display Name'],
            ['data' => 'created_at', 'name' => 'created_at', 'title' => 'Created At'],
            ['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Updated At'],
            ['data'           => 'actions', 'name' => 'actions', 'title' => 'Actions', 'searchable' => false, 'orderable' => false,
             'defaultContent' => 'buttons'],

        ]);
```
-->

### System details

- Operating System win 8.1
- PHP Version 7.2
- Laravel Version 7.8^
- Laravel-Datatables Version 
"yajra/laravel-datatables": "^1.5",
        "yajra/laravel-datatables-oracle": "~9.0"

**Comment by alr2413** [comment]
Hello gidaban,

There are lots of examples on the Internet. Moreover, you can find some explanations about these subjects on [yajra docs](https://yajrabox.com/docs/laravel-datatables/master).
