### ISSUE TITLE
How to remowe / hidden row ?

### ISSUE THREAD

**Issue by gidaban** [yajra/laravel-datatables#2128]
### Summary of problem or feature request

Hello guys, any suggestions for remove row from datatable if i am using HTMLBuilder ?

If anybody have idea then maybe change of generate datatable ?

```php
->addColumn('actions', function ($role) {
                return
                    '<div class="button-group text-center">' .
                    Form::open(["route" => ["admin.role.destroy", $role->id], 'method' => 'DELETE']) .
                    '<a href="' . route('admin.role.show', $role->id) . '" class="btn btn-primary btn-sm btn-flat" data-toggle="tooltip" title="Preview"><i class="fa fa-image"></i></a> ' .
                    '<a href="' . route('admin.role.edit', $role->id) . '" class="btn btn-warning btn-sm btn-flat" data-toggle="tooltip" title="Edit"><i class="fa fa-edit"></i></a> ' .
                    Form::submit('DELETE', ['class' => 'btn btn-danger btn-sm btn-flat', 'data-toggle' => "tooltip", 'title' > 'DELETE']) .
                    Form::close() .
                    '</div>';
            })
```
Always i can use form and reload page, however i want to make more dynamically.

**Comment by alr2413** [comment]
Hi gidaban,

if you don't want to display a row (or rows) in your table, simply exclude them from your query. However, if you wanna remove the row by pressing the delete button, you should use an ajax call on your delete action, and then on the success response from the server, redraw the table again.
You should refer to [datatables page](https://datatables.net) for more details.
