### ISSUE TITLE
Unable to use multiple times the "withQuery" method

### ISSUE THREAD

**Issue by idmeneo** [yajra/laravel-datatables#2129]
### Summary of problem or feature request

Hi, I have a quite complex table for which I try to retrieve the sum of a column "rated power", filtered by a status "announced, operational, contracted".

After hours of searching, il looks like the method "withQuery" works great. But the fact is I cannot use it multiple times, like the query was modified by my request.

These three declarations work fine alone but not at the same time : 

### Code snippet of problem

```php
->withQuery('announced_rated_power', function($filteredQuery) {
    return $filteredQuery->whereHas('status', function($query) {
            $query->where('slug','LIKE','announced');
    })->sum('rated_power');
})
->withQuery('contracted_rated_power', function($filteredQuery) {
    return $filteredQuery->whereHas('status', function($query) {
            $query->where('slug','LIKE','contracted');
    })->sum('rated_power');
})
->withQuery('operational_rated_power', function($filteredQuery) {
        return $filteredQuery->whereHas('status', function($query) {
                $query->where('slug','LIKE','operational');
        })->sum('rated_power');
    })
->make(true);
```

I don't understand the logic behind the query keeping the filter I made...

Do you have any idea how to reset the query or to make the 3 methods work at the same time ?

Thank you,

- Operating System : Dedian 8
- PHP Version : 7.1
- Laravel Version : 5.7
- Laravel-Datatables Version : 1.5

**Comment by yajra** [comment]
I think the filteredQuery object might be mutable atm, may try cloning the model first before doing a query? Maybe something like:

```php
->withQuery('announced_rated_power', function($filteredQuery) {
    return (clone $filteredQuery)->whereHas('status', function($query) {
            $query->where('slug','LIKE','announced');
    })->sum('rated_power');
})

**Comment by yajra** [comment]
Might be a good candidate for enhancement and make the filteredQuery immutable.

**Comment by idmeneo** [comment]
Dear @yajra it works, thank you so much !
