### ISSUE TITLE
How to show repeating HTML table headers on each printed page On jquery datatable?

### ISSUE THREAD

**Issue by infoshahin** [yajra/laravel-datatables#213]
In my page.blade.php I have a jQuery Datatable. Now I need to Repeating table Header every pages when I print the report. I tried by Used this

~@media print { thead {display: table-header-group;} }~

But I can't? Please tell me how can I add this in my project every datatable reports? Now Table header showing on only top page (page one) when I print it, it doesn't showing other pages!!

**Comment by yajra** [comment]
Are you using table tools? If yes, then it will not work as it only works on client-side of datatables. You would have to create your own print preview page to accomplish this.

**Comment by infoshahin** [comment]
I used it something like that my code : 

{!! HTML::script('js/jquery.min.js') !!}  
{!! HTML::script('js/datatable.js') !!}
{!! HTML::script('js/tabletools.js') !!}
<script type="text/javascript">
$(document).ready(function() {
   oTable = $('.example').DataTable({
         // "dom": 'T<"clear">lfrtip',
         "fixedHeader": true,
                        "aaSorting": [],
                        "bPaginate": true,
                        "bLengthChange": true,
                        "bInfo": true,
                        "bAutoWidth": false,
                        'bFilter': true,
                        'iDisplayLength': 25,
                        "sDom": 'T<"clear">lfrtip',
                                   "oTableTools": {
                                       "aButtons": [
                                           "print",
                                           {
                                               "sExtends":    "collection",
                                               "sButtonText": "Save",
                                               "aButtons":    [ "csv", "xls"]
                                           }
                                       ]
                                   },
                        "tableTools": {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf"
                        },
        "processing": false,
        "serverSide": false,
    });
  });
</script>

Now I can't it?

**Comment by infoshahin** [comment]
```{!! HTML::script('js/jquery.min.js') !!}  
{!! HTML::script('js/datatable.js') !!}
{!! HTML::script('js/tabletools.js') !!}
<script type="text/javascript">
$(document).ready(function() {
   oTable = $('.example').DataTable({
         // "dom": 'T<"clear">lfrtip',
         "fixedHeader": true,
                        "aaSorting": [],
                        "bPaginate": true,
                        "bLengthChange": true,
                        "bInfo": true,
                        "bAutoWidth": false,
                        'bFilter': true,
                        'iDisplayLength': 25,
                        "sDom": 'T<"clear">lfrtip',
                                   "oTableTools": {
                                       "aButtons": [
                                           "print",
                                           {
                                               "sExtends":    "collection",
                                               "sButtonText": "Save",
                                               "aButtons":    [ "csv", "xls"]
                                           }
                                       ]
                                   },
                        "tableTools": {
                            "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf"
                        },
        "processing": false,
        "serverSide": false,
    });
  });
</script>```

**Comment by yajra** [comment]
You are indeed using table tools and unfortunately, it only works on client-side and not on server-side. One work around you can do is setting the length to -1 to display all records but that is not recommended at all since paging will be disabled and may cause performance issue when your db is too large. The best approach atm is to create a separate view for your print preview page.

**Comment by yajra** [comment]
On the other hand, I have a pending development for the server-side table tools support. The demo is http://datatables.yajrabox.com/buttons and a tutorial is available at http://datatables.yajrabox.com/service. Just note that this is under development and your coding style may changed. I am using this development branch on one of my production code though so using it have a little risk of breaking and it is backward compatible.

**Comment by infoshahin** [comment]
Ok, I got it. but now how can I add it on client-side datatable?

**Comment by yajra** [comment]
Just add a normal laravel link that points to a view where you will display a printer friendly version of your datatables.

**Comment by infoshahin** [comment]
I already add a page but don't show table headers on each printed page!!

**Comment by yajra** [comment]
It's a CSS issue and google is your friend.
http://stackoverflow.com/questions/274149/css-repeat-table-headers-in-print-mode

https://www.google.com.ph/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=html%20table%20header%20print%20on%20every%20page

**Comment by infoshahin** [comment]
Thank you for suggestion.
