### ISSUE TITLE
Documentation down.

### ISSUE THREAD

**Issue by Yahav** [yajra/laravel-datatables#2135]
Hey

It seems like the documentation website keeps going down every once in a while.
its pretty much impossible to use this package without documentation, perhaps you should upload the docs website code to github for such incidents...

**Comment by Darthmaul** [comment]
My question is why not upload the docs/demo app to something more stable the first few times this happened....I can almost count on the documentation to be Down more than Up

**Comment by turbo124** [comment]
Happy to provide a mirror for this when it comes back up online.

**Comment by kastoras** [comment]
Maybe this will help, from a archive web history website.

https://web.archive.org/web/20190713172523/https://datatables.yajrabox.com/starter

**Comment by yajra** [comment]
The docs is available on github via this repo https://github.com/yajra/laravel-datatables-docs. We'll try to resolve server issue the soonest possible. Thanks!

**Comment by Skintillion** [comment]
Anything we can do to help?

**Comment by luca-itro** [comment]
Hi Yajra! Please tell us anything we can do to help you.
Thank you so much for your work!

**Comment by vnetmx** [comment]
@yajra In case you need I can give you free hosting for your domain. So I can help to support this project in this way.

**Comment by samoldenburg** [comment]
@yajra 

Please allow others to help you with hosting your documentation for the package. By this point you've proven that you cannot reliably host your own documentation. Personally I feel like I have to make a backup of your documentation in order to use this package because I cannot rely on you to keep your website online.

**Comment by Skintillion** [comment]
Shots fired...

**Comment by Skintillion** [comment]
@yajra 

Hey, do you have a repo of the working demo app? I can host it for now until you get yours up and running.

**Comment by yajra** [comment]
Sorry for late response. Working on getting the server up now... 

Special thanks to a donator `conpor Dirk Opdenplatz e.K.` and @ChaosPower

**Comment by SupunSam** [comment]
@yajra Documentation is down again.

**Comment by Yahav** [comment]
@yajra  We all do really appreciate the hard work that went into this package development and maintenance. 
However, there was couple of offers here for hosting your docs, perhaps you should consider them.
It is really hard to relay on a package while you don't know whether the documentation will be available for you down the development road.

**Comment by turbo124** [comment]
@yajra hit me up, happy to help with robust hosting for this.

**Comment by ihabhamad** [comment]
hey @yajra we hIClass LTD, we offer to you or donate from our company dedicated server for free to host yajarbox site and your docs.
server os ubuntu 18 with Webmin, Virtualmin panels
server ram 8gb or 12gb or 16gb, what you want
CPU 4 core
and what you want for your specification
 to complete this offer send me an email: ihab@hiclass.ps

**Comment by yajra** [comment]
Thank you all! Please see #2223.
