### ISSUE TITLE
How to add scroll x to datatable that is generated by service?

### ISSUE THREAD

**Issue by SSEsmaeeli** [yajra/laravel-datatables#2136]
Hello, I'm using datatable as a service, so datatable will be initialized in view file once with default values.
how can I add more options to datatable default values?
e.g. I wanna add scrollX to true ... like this:
    $('#example').DataTable( {
        "scrollX": true
    } );

now we are not able to do something like this:
{!! $dataTable->scripts({  
"scrollX": true
}) !!}

Is there a way?
Thanks in advance.

**Comment by yajra** [comment]
There is an undocumented api that you use to can chain on the builder `->scrollX(true)`.

Or via `parameters(['scrollX' => true])`.
