### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by arminderk** [yajra/laravel-datatables#2138]
### Summary of problem or feature request

Documentation Site is Down!

### System details

- Operating System: Mac OS
- PHP Version: 7.0
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.29.3

**Comment by SSEsmaeeli** [comment]
The docs is available on github via this repo https://github.com/yajra/laravel-datatables-docs.

**Comment by Skintillion** [comment]
Not much on adding as a service on there.

**Comment by yajra** [comment]
#2135
