### ISSUE TITLE
Yajra laravel datatable package not working properly in laravel 5.0 with mongodb

### ISSUE THREAD

**Issue by haseenapa** [yajra/laravel-datatables#214]
I have installed yajra/laravel-datatables-oracle package 5.0  for supporting serverside datatables in laravel 5.0 with mongodb 3.3 as database. I have connected laravel 5.0 with mongodb through jenssegers-mongodb 2.1 package. It is connecting successfully , but datatable is not working properly.
Here is my js code,
```
$('#vendorDatatable').DataTable({
                "processing": true,
                "serverSide": true,
                "order": [[ 0, "desc" ]],
                "ajax": baseUrl+'/vendors/data',
                "columns": [
                    {"data": 'branch', "name": 'branch'}
            ],
            });
```

Error message,
```
FatalErrorException in Builder.php line 1309: Call to a member function compileSelect() on a non-object
```

**Comment by yajra** [comment]
Can you please paste your server-side script? Does the query works properly when being called without the datatables package?

**Comment by haseenapa** [comment]
Route

    Route::get('vendors/data','VendorsController@getList');

VendorsController

    public function getList(){
       $vendors = Vendors::select(['branch']);
return Datatables::of($vendors)->make();

    }

Error while accessing ../vendors/data

FatalErrorException in Builder.php line 1309: Call to a member function compileSel

**Comment by yajra** [comment]
Will try to setup a Laravel 5.0 with MongoDB and let you know what I may find.

Oddly, `compileSelect` is a built-in `Grammar` method of Laravel. It's weird why that error is being thrown.

**Comment by joel-james** [comment]
Just add `->get()` to the query in controller.

Change controller function to
```
public function getList(){
    $vendors = Vendors::select(['branch'])->get();
    return Datatables::of($vendors)->make();
}
```
This will fix the issue.

**Comment by haseenapa** [comment]
Thank You @joel-james . Issue has been fixed

**Comment by kamranahmedse** [comment]
Not a proper fix though. There should be a way to make it work with pagination. I mean, in case there is a small dataset, it would work properly but what if the collection is really huge. In that case getting all of the data at once doesn't seem like a good solution.

**Comment by joel-james** [comment]
@kamranahmedse Have you tried? This will work with huge dataset too. It will not retrieve entire data each time. Only the paginated set of data will be retrieved.
