### ISSUE TITLE
How can I merge two columns in just one?

### ISSUE THREAD

**Issue by piterog** [yajra/laravel-datatables#2140]
I'm using server side, and I have two fields, demand_number and demand_year, and I like to display this fields in one field like a demand_number / demand_year ( 001 / 2019 ) 

How can I do this?

- Operating System: Linux Mint
- PHP Version: 7.2
- Laravel Version: 5.7
- Laravel-Datatables Version: 9.4.1

**Comment by yagrasdemonde** [comment]
You can use accessor/mutator and add custom column

**Comment by connectmalves** [comment]
Try to create a custom column like "demand_info" in your frontend and your controller, edit the column, like:

``
$datatables->editColumn('demand_info', function ($eloquent) {
            return $eloquent->demand_number . '/' . $eloquent->demand_year;
});
``

If you need search by this fields, don't forget to filter the column, like:

``
$datatables->filterColumn('demand_info', function ($query, $keyword) {
            $query->where('demand_number', 'like', $keyword)->orWhere('demand_year', 'like', $keyword);
});
``

Warning: This codes was not tested.

**Comment by piterog** [comment]
Thanks @connectmalves works perfectly!
