### ISSUE TITLE
Custom search by model scope

### ISSUE THREAD

**Issue by connectmalves** [yajra/laravel-datatables#2141]
Hello, I want to create custom searches that will not filter by columns, but by a model scopes.

Example, I have some scopes that filter:

* Customers who spend more than x.
* Customers who made more than x purchases.
* Customers who have more than x years that not purchase in the store.

Where x is the search parameter.

For each scope I will create separate text fields in frontend to submit the search.

How can I achieve that?

**Comment by yajra** [comment]
You may need to include the scope outside the dataTables. Something like:

```php
if (request('search.value') > x) {
  $query->scopeHere();
}

return DataTables::of($query)->toJson();
```
