### ISSUE TITLE
Delete row by ajax request

### ISSUE THREAD

**Issue by gidaban** [yajra/laravel-datatables#2142]
### Summary of problem or feature request

Hello, i am trying to implement delete row by ajax request, i found one solution however it don`t work 
```
   LaravelDataTables.row($(this).parents("tr")).remove().draw();
```
But i got error:
```
Uncaught (in promise) TypeError: LaravelDataTables.row is not a function
```

Any idea how to fix it?

Many Thanks

**Comment by yajra** [comment]
It should be something like: `LaravelDataTables['table-id'].row`
