### ISSUE TITLE
How to send additional data to custom view column?

### ISSUE THREAD

**Issue by latbat58** [yajra/laravel-datatables#2144]
### Sending additional data to custom view column

I can use this inside the controller to add a view column to the table. It works fine right now:
`DataTables::of($model)->addcolumn('other','small.buttons')->rawColumns(['other'])->toJson();`

And inside that view i can access the model attributes:
`<a class="btn btn-info" role="button" href="{{ route( 'modeledit',['id'=>$id]) }}">edit</a>`

Is there way to send more data from controller to this view other than model attributes?

- Operating System Microsoft Windows [Version 6.1.7601] (win7 sp1)
- PHP Version 7.3.7
- Laravel Version 5.8.29
- Laravel-Datatables Version v9.4.1 i think.
 
Sorry for weird question. Thank you.

**Comment by yajra** [comment]
You need to use closure for that. See https://yajrabox.com/docs/laravel-datatables/master/add-column#closure for ref.

```php
DataTables::of($model)
  ->addcolumn('other', function($model) {
   return view('small.buttons', compact('model', 'other vars'))->render();
  })
  ->rawColumns(['other'])->toJson();
```

**Comment by latbat58** [comment]
Thank you!
