### ISSUE TITLE
Get DataTables Item Count after DataTable Ajax Reload

### ISSUE THREAD

**Issue by conangithub** [yajra/laravel-datatables#2146]
Hello. Does it has any event to count DataTables item after I reload DataTable successfully or any other way to do it?

Here is my DataTable script :
```
var table = $('#prizeitem-table').DataTable({
                            processing: true,
                            serverSide: false,
                            pageLength: 10,
                            ajax: '{{ route('prizeitems.index') }}',
                            columns: [
                                {data: 'id', title: 'Id'},
                                {data: 'code', title: 'Code'},
                                {data: 'name', title: 'Name'},
                            ],
                            order: [[0, 'desc']]
                        });
```

DataTable reload script :
```
table.ajax.reload();
```

DataTable count item script :
```
if (!table.data().any()) {
     alert('Data is empty');
}
```

I put this 2 script together like this :
```
table.ajax.reload();
if (!table.data().any()) {
     alert('Data is empty');
}
```

But the count item script was run before the DataTable finish reload the data. So, I got the result was an old data before the ajax reload.

Please help me.

**Comment by DanielGilB** [comment]
Hello, You can try this:

```php
var table = $('#example').DataTable();
 
var data = table.rows().data();
 
alert( 'The table has '+data.length+' records' );
```

If this not working to you, try use "initComplete" method to make a callback function after your datatable is ready!!


Let me know if it works 😄

**Comment by yajra** [comment]
Or access the ajax json response. 

```js
table.ajax.json().recordsTotal
```

**Comment by conangithub** [comment]
Sorry for replying lately.

I try @DanielGilB code and put inside initComplete and drawCallback function. Both of them successfully works.
initComplete
```
initComplete: function(settings, json) {
    alert(table.rows().data().length);
}
```
drawCallback
```
drawCallback: function(settings) {
    var api = this.api();
    alert(api.rows().data().length);
}
```

I also try Sir @yajra code and put inside initComplete function, it also successfully works. But when try inside drawCallback function like this
```
drawCallback: function(settings) {
    var api = this.api();
    alert(api.ajax.json().recordsTotal);
}
```
I got this error 
```
TypeError: api.ajax.json(...) is undefined
```

By the way, thank you to @DanielGilB and Sir @yajra have answered my question and helped me.

**Comment by lovecoding-git** [comment]
```
table= $('#example').DataTable();

$('#example').on('draw.dt', function() {
    console.log(table.ajax.json().recordsTotal);
});
```
