### ISSUE TITLE
having custom where clause in query

### ISSUE THREAD

**Issue by roxozur** [yajra/laravel-datatables#2148]
### Code snippet of problem
```
   $bottle= tbl_bottle::select(
                'name',
                'type',
                'location'            
            )->where('location','=','USA')->OrWhere('location','=',' ');
 return DataTables::of($bottle)->make(true);
```
so when the data is displayed it is correct 
but when i start searching : for example when i search 
bottle one: all the bottles with the name bottle one is displayed with the location marked as USA or the location is empty . the first couple of results would be correct but the rest the result will be nothing related to my search at all.

i have narrowed my problem down to when i have only one WHERE clause it works perfectly but when i have two where clauses it gives me all types of results

- Windows 10 
-  7.2.11
-5.8
- ~9.0

**Comment by yajra** [comment]
Maybe because you are using `orWhere`. Try reviewing the SQL generated.

**Comment by yajra** [comment]
Also, I think you are using a wrong chain of SQL. You should use where closure instead.

**Comment by roxozur** [comment]
@yajra  do you have any idea how my sql should be structured in this sense 
any help would be appreciated

**Comment by yajra** [comment]
It should be something like:

```php
$bottle= tbl_bottle::select(
  'name',
  'type',
  'location'            
)->where(function($query) {
  $query->where('location','=','USA')->OrWhere('location','=',' ')
});

return DataTables::of($bottle)->make(true);
```

**Comment by roxozur** [comment]
@yajra Thank you this worked <3
