### ISSUE TITLE
Sorting on extra column in datatables as a service

### ISSUE THREAD

**Issue by WimDeMeester** [yajra/laravel-datatables#2149]
### Summary of problem or feature request

I am using datatables as a service for my tables. One of the columns I add is a multiplication of the values in two other columns. 

In this case, it is impossible to sort on this new added column. Is there a solution for this?

### Code snippet of problem

In the ajax() method, I have the following:

```php
return datatables()
            ->eloquent($this->query())
            ->addColumn(
                'focalLength',
                function ($instrument) {
                    if ($instrument->fd) {
                        if (Auth::user()->showInches) {
                            return round($instrument->diameter * $instrument->fd / 25.4, 2) . ' ' . _i('inch');
                        } else {
                            return $instrument->diameter * $instrument->fd . ' ' . _i('mm');
                        }
                    } else {
                        return null;
                    }
                }
          )->make(true);
```

### System details

- Operating System: Homestead: Ubuntu 18.0.4.3
- PHP Version: 7.3.8
- Laravel Version: 5.8.31
- Laravel-Datatables Version: 9.4.1

**Comment by yajra** [comment]
@WimDeMeester you need to convert that computation to SQL query level. Try using https://laravel.com/docs/5.8/queries#conditional-clauses instead. Maybe something like:

```php
$query = $this->query();

$query->when(Auth::user()->showInches, function ($query) {
    return $query->addSelect(DB::raw('round(diameter * fd / 25.4, 2) as focalLength'));
}, function($query) {
    return $query->addSelect(DB::raw('round(diameter * fd)  as focalLength');
})
```

Afterwards, I think you can then use `focalLength` to sort the column.

Note: code is not tested.

**Comment by WimDeMeester** [comment]
Thanks! Should I put this in the ajax() method before I return the datatable?

**Comment by yajra** [comment]
Yes, you need to set the query first then return dataTables.

```php
$query = $this->query();

$query->when(Auth::user()->showInches, function ($query) {
    return $query->addSelect(DB::raw('round(diameter * fd / 25.4, 2) as focalLength'));
}, function($query) {
    return $query->addSelect(DB::raw('round(diameter * fd)  as focalLength');
});

return datatables()
            ->eloquent($query)
...
```

Or you can include it on `query()` method if you prefer.

**Comment by WimDeMeester** [comment]
Thanks a lot! I'm making progress, but still have a problem. When I only use

```
$query = $this->query();
```

I get all columns correctly, as is expected. 

However, if I also add the next line:
```
$query->when(Auth::user()->showInches, function ($query) {
    return $query->addSelect(DB::raw('round(diameter * fd / 25.4, 2) as focalLength'));
}, function($query) {
    return $query->addSelect(DB::raw('round(diameter * fd)  as focalLength');
})
```

I only get the column with the focalLength, all other columns are not longer known...

**Comment by WimDeMeester** [comment]
I found the solution. Before using the addSelect method, we need the select method, so the code becomes

```
return $query->select()->addSelect(DB::raw('round(diameter * fd)  as focalLength');
```

Thanks for the help!

**Comment by WimDeMeester** [comment]
Is this also the way to do things if I need to do some complicated calculations?
