### ISSUE TITLE
Can you include Unordered listing of data using <ul> tags instead of table display <table>.

### ISSUE THREAD

**Issue by razikallayi** [yajra/laravel-datatables#215]
### So we can also use grid styling and list styling methods.

**Comment by yajra** [comment]
Hmm. not sure on this one. Better check http://datatables.net/ and their forum if this is possible. As far as I know, we can only display data in table format.

**Comment by razikallayi** [comment]
Do you know any other plugins to using this method...?

**Comment by yajra** [comment]
@razikallayi, sorry, but there is no plugin for that method as far as I know.

**Comment by razikallayi** [comment]
Ok @yajra  Thank you!
