### ISSUE TITLE
ORA-00904 Invalid Indentifier

### ISSUE THREAD

**Issue by afifazfar4** [yajra/laravel-datatables#2151]
### Summary of problem or feature request

I try to display the specified data in a view page but it shows that there is error on the identifier. When i refer to error, it shows that the unique column selected by the query is "ID" instead of "VENDOR_REFNO". I tried to change the parameter passed at the controller but nothing seems to solve the issue. Is there anything i need to change and edit to solve this issue? Any guide and help would be much appreciated.

### Code snippet of problem

**Vendor Controller:**
public function show($vendor_refno){
     $vendors = Vendor::find($vendor_refno);
     return view('admin.view', compact('vendors));
}

**index.blade.php:**
<a href="{{action('VendorController@show', $data->vendor_refno)}}"

### System details

The i developed is to process the vendor registration. I already map the system to the existing company database that use Oracle 11g. 

- Operating System: Window 10
- PHP Version: 7.1.10
- Laravel Version: 5.8.27
- Laravel-Datatables Version

**Comment by yajra** [comment]
I this you just need set the model's primary key.

```php
class Vendor extends Model {
  protected $primaryKey = 'vendor_refno';
}
```

**Comment by afifazfar4** [comment]
That would be the answer. Thanks
