### ISSUE TITLE
How to filter datatable based on custom data using button onclick?

### ISSUE THREAD

**Issue by rgingingon** [yajra/laravel-datatables#2153]
I have a column render of textarea with multiple data. I wonder if we can filter column using data-bgcolor value.

For bgcolor values, I have "red" and "transparent".

So I was thinking if we can add a button to filter the bgcolor's value. When I click the button, it will filter the table and only show rows that have bgcolor equals to 'red'. Is that even possible to work?

For your information, I'm using server-side datatable.

**Here's my datatable column code**
```
var datatable = $('#datatable').DataTable(
{                
  processing: true,
  serverSide: true, 
  headers:
  {
    'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
  },
  ajax: "{{ route('api.posts.index') }}",                 
  columns: 
  [
    {   
      orderable: false, 
      checkboxes: 
      { 
        selectRow: true 
      }, 
      target: 0, 
      data: null,
      defaultContent: '',
    }, 
    {   
       orderable: false, 
       data: 'StockName'
    },
    {   
       orderable: false,                        
       data: 'ReorderLevel',                        
       render: function (data, type, row, meta) 
       {                        
         if((data == null) || (data == ".00000000"))
           return '<textarea rows="1" cols="3" name="reorderlvl" class="reorderlvl align-middle text-right" style="background-color:'+row.bgcolor+'" data-stockcode="'+row.StockCode+'" data-stockname="'+row.StockName+'"></textarea>';                                
         else
           return '<textarea rows="1" cols="3" name="reorderlvl" class="reorderlvl align-middle text-right" style="background-color:'+row.bgcolor+'" data-stockcode="'+row.StockCode+'" data-stockname="'+row.StockName+'" data-balance="'+row.CurrentBalance+'">'+parseFloat(data).toFixed(0)+'</textarea>';
      }
    }
  ],
  createdRow: function (row, data, dataIndex)
  {
    $('td', row).eq(2).attr('data-search', data.bgcolor);
  },
  dom: 'Bfrtip',
  buttons: 
  {
    dom: 
    {
      button: 
      {
        tag: 'button',
        className: ''
      }
    },
    buttons: 
    [
      {
        className: 'reorderlist btn btn-sm btn-info',
        text: 'Reorder List',
        action: function ( e, dt, node, config ) 
        { 
           datatable.column(2).search('red').draw();
        }
      }
    ]
  },
  order : [ [ 1 , 'asc' ] ]                                                
})
```

- Operating System
- PHP Version 5.6.32
- Laravel Version 5.4.36
- Laravel-Datatables Version 1.10.18

**Comment by DanielGilB** [comment]
Hello!

You have to use `filterColumn` (server side) to do that.

**Comment by rgingingon** [comment]
> Hello!
> 
> You have to use `filterColumn` (server side) to do that.
> 
> Apply to your datatable something like:
> 
> ```
> ->filterColumn('bgcolor', function ($query, $keyword) {
>    
>     if($keyword === 'red')
>         $query->where('bgcolor', ""HEXREDCOLOR"");
> 
>     if($keyword === 'transparent')
>         $query->where('bgcolor', ""HEXTRANSPAENTCOLOR"");
> 
>  })
> ```
> 
> But I dont think that searching for hardcoded color is a good option. You can create a select filter, checkboxes or similar with all your colors then users only have to click to apply filter.

@DanielGilB I have updated my question.  Please review back. Thanks
