### ISSUE TITLE
Export runs into memory exhausted error

### ISSUE THREAD

**Issue by rokde** [yajra/laravel-datatables#2154]
### Summary of problem or feature request

If you run a Datatable Export the export call results in a 500 server error, because the memory exceeds.

I did extend the datatable class to get the buildExcelFile() overriden, but it was not the cause of the error. The cause of the error is the QueryDataTable::results() method. I am not able to override the behaviour to get a chunked query result for using on the display view and on the export action in the same way.

I can not use only the query, because I have a lot of `editColumn` calls for the concrete DataTable to show the table results and i need the same results in export. But the export runs into memory leak on a table with 50.000 records.

### System details

- Operating System: Debian Linux
- PHP Version 7.2
- Laravel Version 5.7.24
- Laravel-Datatables Version 8.13.4

### Related issues (without any successful help)

- #1684
- #1572

**Comment by TheGeekyM** [comment]
[See this answer ](https://github.com/yajra/laravel-datatables/issues/1684#issuecomment-571878847)

**Comment by rafaelqm** [comment]
@rokde Did you succeeded in this workaround? Same problem here on a 70k lines

**Comment by rokde** [comment]
No, we dropped use of laravel-datatables in this case.

**Comment by yajra** [comment]
I just updated the package and supported `fast-excel` for heavy export. See https://github.com/yajra/laravel-datatables-buttons/pull/124 and give it a try. Feedbacks appreciated. Thanks!
