### ISSUE TITLE
yajra is down for one week

### ISSUE THREAD

**Issue by abidshah544** [yajra/laravel-datatables#2155]
http://yajrabox.com for one week please check it.

**Comment by warlof** [comment]
It's a duplicate from #2135

**Comment by damonbakker** [comment]
I think it is back up again. Been using the archive.org version all this time haha.

https://yajrabox.com/docs/laravel-datatables/6.0

**Comment by abidshah544** [comment]
Yeah it’s back again thanks

**Comment by atapatel** [comment]
Site is down again.
