### ISSUE TITLE
Upgrade to L6 ?

### ISSUE THREAD

**Issue by warlof** [yajra/laravel-datatables#2156]
### Summary of feature request

Hello there, as Laravel 6 has been released (and flagged as a new LTS), do you plan to upgrade packages to it? 

Would be greatly appreciated ☺️

**Comment by yajra** [comment]
Sure, when it's officially released.

**Comment by u01jmg3** [comment]
Released today: https://laravel-news.com/laravel-6

**Comment by baig772** [comment]
@yajra , Is this released? I am still having the issue in Laravel 6.0  #2202

**Comment by yajra** [comment]
Yes, already works on Laravel 6.
