### ISSUE TITLE
OrderCoumn with Closure

### ISSUE THREAD

**Issue by Arkhas** [yajra/laravel-datatables#2159]
### Summary of problem or feature request

We can only use raw sql in the orderColumn function, it would be nice if we would be able to something like : 

```
->orderColumn('name', function($query, $order){
      return $query->orderBy('name', $order);
});
```

that would allow more complexe ordering like : 

```
->orderColumn('user.name', function($query, $order){
      return $query->join('users', 'user_id', '=', 'users.id')
                             ->orderBy('users.name', $order);
});
```

**Comment by yajra** [comment]
A good proposal. Will try to look into it when I got the chance. If you can, please do not hesitate to submit a PR. thanks!

**Comment by yajra** [comment]
@Arkhas, sent a PR. Kindly review if you got some spare time. Thanks!
