### ISSUE TITLE
HalfSmartSearch

### ISSUE THREAD

**Issue by dhcmega** [yajra/laravel-datatables#2161]
Hi!
I think the smart search is very useful for searching. The problem is that starting the search string with % skips indexes.
I would like to have a second method, like this:

```
        if ($this->config->isSmartSearch()) {
            $keyword = "%$keyword%";
        }

        if ($this->config->isHalfSmartSearch()) {
            $keyword = "$keyword%";
        }
```

Is it possible without changing code? Will I have to override too many things?

**Comment by yajra** [comment]
The idea makes sense and is possible. Maybe not `halfSmartSearch` but `startsWithSearch` search?

Will try to implement this when I got the chance, but if you can, please do not hesitate to submit a PR. Thanks!

**Comment by yajra** [comment]
There, sent a PR. Kindly check and provide some feedbacks. Thanks!

**Comment by dhcmega** [comment]
Sure, thank you! I'm testing it and works perfectly.
I will keep testing during the day.
Thanks again.
