### ISSUE TITLE
How to sort and search on table with belongsTo in datatables as a service, using eager loading

### ISSUE THREAD

**Issue by WimDeMeester** [yajra/laravel-datatables#2162]
### Summary of problem or feature request

I have a table where I keep a list of locations. These locations also have a user. I can use datatables as a service to see the name of the users. For this, I add an extra table with the following code:

```php
return datatables()
            ->eloquent($query)->addColumn(
                'username',
                function ($location) {
                    return $location->user->name;
                }
```

However, I would like to sort and search on the user name, but this is not possible.
Is there an easy solution for me to solve this?

### System details

- Operating System: Homestead / Ubuntu Linux
- PHP Version: 7.3
- Laravel Version: 5.8
- Laravel-Datatables Version: v9.4.1

**Comment by dhcmega** [comment]
Hi
This is what I do:
1) add the relation to the query using "with" method.
Then at the columns call like like this:
2) 'username' => ['user.name' => 'name', 'data' => 'user.name', 'title' => 'Cuenta'],
This is php code because I use a package that generates de javascript.

If it's not working, use the chrome browser inspector and check the XHR calls, you will be able to check how the JSON is created and the relations, etc, so you can figure out how to access the data.
I hope this helps you.

**Comment by WimDeMeester** [comment]
I don't really understand step 1...

Should I do something like

```php
$query = $this->query();
$query->with('user_id');
```

But what sould I put in the with() method then?

**Comment by dhcmega** [comment]
@WilliamPeralta what's the name of your relation? If `Location` has one `User`, then the relation should be called `user` not `user_id`. `with` is telling Eloquent to "pre" load all the relations (eagerload), so they will be included in the JSON that is returned to the web page.

**Comment by WimDeMeester** [comment]
A User can have many locations, but a location has only one user. I will change the `user_id` to `user`. 
I guess I will need to use

```php
$query->with('user')
```

then?

**Comment by dhcmega** [comment]
Is the column showing up already? Have you added the column to the column list without using `addColumn` but listing it as any other `Location` column as I shown you above?

**Comment by WimDeMeester** [comment]
I have changed `user_id` to `user`. If I try to show the column, using 

```php
                'username' => ['user.name' => 'name', 'data' => 'user.name', 'title' => 'Cuenta'],
```

I get the following error: 
![image](https://user-images.githubusercontent.com/7261529/64116889-e1947400-cd93-11e9-8eda-06c04d377dfc.png)

**Comment by WimDeMeester** [comment]
I have the following method in User.php

```php
    public function locations()
    {
        return $this->hasMany('App\Location', 'user');
    }
```

and the following method in Location.php:

```php
    public function user()
    {
        return $this->belongsTo('App\User');
    }
```

**Comment by dhcmega** [comment]
Hi, please check my first message:
`If it's not working, use the chrome browser inspector and check the XHR calls, you will be able to check how the JSON is created and the relations, etc, so you can figure out how to access the data.`

Is user relation included in the JSON response?

**Comment by WimDeMeester** [comment]
I don't think so... This is what I get:

```php
http://localhost/location/admin?draw=1&columns%5B0%5D%5Bdata%5D=name&columns%5B1%5D%5Bdata%5D=country&columns%5B2%5D%5Bdata%5D=elevation&columns%5B3%5D%5Bdata%5D=limitingMagnitude&columns%5B4%5D%5Bdata%5D=skyBackground&columns%5B5%5D%5Bdata%5D=bortle&columns%5B6%5D%5Bdata%5D=observations&columns%5B7%5D%5Bdata%5D=delete&columns%5B7%5D%5Bsearchable%5D=false&columns%5B7%5D%5Borderable%5D=false&columns%5B8%5D%5Bdata%5D=user.name&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=desc&start=0&length=10&search%5Bvalue%5D=&_=1567430524276
```

**Comment by dhcmega** [comment]
Thanks the http request you make to the server, not the response.

**Comment by WimDeMeester** [comment]
The response starts with:

```
{"draw":1,"recordsTotal":1837,"recordsFiltered":1837,
"data":[{"id":"2071","name":"<a href=\"\/location\/2071\/edit\">\u00deingvellir<\/a>",
"longitude":"21.1167","latitude":"64.25","elevation":"0 m",
"country":"Iceland","timezone":"Atlantic\/Reykjavik","limitingMagnitude":"-0.14",
"skyBackground":null,"bortle":null,"user":null,
```

so, the user is null, while it should be the user with id 279 here...

**Comment by dhcmega** [comment]
Not really, it should be the whole user record.
That problem goes beyond the scope of this ticket area. You should ask this questions in a forum related to Laravel IMHO.

**Comment by WimDeMeester** [comment]
The problem is in the with(...) method. If I remove this method, I get the user id...

**Comment by yajra** [comment]
@WimDeMeester the problem is on null user for location. Maybe try adding withDefault to your relation:

```php
return $this->belongsTo('App\User')->withDefault();
```

**Comment by WimDeMeester** [comment]
> A User can have many locations, but a location has only one user. I will change the `user_id` to `user`.
> I guess I will need to use
> 
> ```
> $query->with('user')
> ```
> 
> then?

Since I changed user_id to user, I can no longer get the information of the user using 

```php
$location->user()
```

... The result is always null. I will try to fix this first.

**Comment by WimDeMeester** [comment]
I could fix the $location->user() problem. I can now get the names of the users (that is exactly what I want!) when I add:

`
        $query = $this->query();

        $model = Location::with('user');
`

The names are perfectly shown, but searching and sorting fails with the following error:

`
{
    "message": "Country \"\" not found.",
    "exception": "Yajra\\DataTables\\Exceptions\\Exception",
    "file": "/home/vagrant/code/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php",
    "line": 805,
    "trace": [
        {
            "file": "/home/vagrant/code/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php",
            "line": 106,
            "function": "errorResponse",
            "class": "Yajra\\DataTables\\DataTableAbstract",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/app/DataTables/LocationDataTable.php",
            "line": 118,
            "function": "make",
            "class": "Yajra\\DataTables\\QueryDataTable",
            "type": "->"
        },

`

I guess I need to use the query, together with the model... When I find out how to do this, I will document in this ticket how to fix my problem.

**Comment by dhcmega** [comment]
If you add the column using addColumn, sort and search will fail because the column might not exist. If you generate the column programmatically you have to set it as false for sort and search.

**Comment by WimDeMeester** [comment]
But setting sort and search to false will disable sort and search no? The ticket was all about being able to search and sort on the new column (the user name)

**Comment by WimDeMeester** [comment]
This is the solution:

1. First of all, make sure that there is a user() method in the App/Location.php class:

```php
    public function user()
    {
        return $this->belongsTo('App\User');
    }
```
For this to work, the locations table in the database needs to have a field named **user_id**, and the user_id should be a foreign key. So in the migration, the following is needed:

```php
$table->unsignedInteger('user_id');
$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
```

2. In the LocationDatatable.php file, in the ajax() method, add the following:

```php
$model = Location::with('user')->select('locations.*');
```

or if want only the locations for a certain user:

```php
$model = Location::where('user_id', auth()->user()->id)->with('user')->select('locations.*');
```

followed by

```php
return datatables()->eloquent($model);
```

Also add the column with the user name:

```php
['name' => 'user.name',
 'title' => _i('Observer'),
 'data' => 'user.name',
 'orderable' => true,
 'searchable' => true,
],
```
