### ISSUE TITLE
404 Error not found 

### ISSUE THREAD

**Issue by k3youmin** [yajra/laravel-datatables#2164]
http://127.0.0.1:8000/%7B%7B%20route('prccodes.index')%20%7D%7D?draw=1&columns%5B0%5D%5Bdata%5D=DT_RowIndex&columns%5B0%5D%5Bname%5D=DT_RowIndex&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=prc_code&columns%5B1%5D%5Bname%5D=prc_code&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=prc_description&columns%5B2%5D%5Bname%5D=prc_description&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=created_at&columns%5B3%5D%5Bname%5D=created_at&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=updated_at&columns%5B4%5D%5Bname%5D=updated_at&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=action&columns%5B5%5D%5Bname%5D=action&columns%5B5%5D%5Bsearchable%5D=false&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1567145961883

![image](https://user-images.githubusercontent.com/15870174/63997934-84e64e80-cb32-11e9-815b-cf02fbf10b55.png)

**Comment by yajra** [comment]
[Known issue](https://github.com/yajra/laravel-datatables#php-artisan-serve-bug) with `artisan serve`. Please use apache, nginx, etc.

> PHP ARTISAN SERVE BUG
Please avoid using php artisan serve when developing with the package. There are known bugs when using this where Laravel randomly returns a redirect and 401 (Unauthorized) if the route requires authentication and a 404 NotFoundHttpException on valid routes.

**Comment by k3youmin** [comment]
[image: image.png]

I used xampp for apache, but i got this error 403(forbidden) You don't have
permission to access the requested object. It is either read-protected or
not readable by the server.

**Comment by k3youmin** [comment]
I got error 404 found using homestead

[image: image.png]
[image: image.png]
[image: image.png]

**Comment by yajra** [comment]
#2166
