### ISSUE TITLE
Yajra datatable group by function not working

### ISSUE THREAD

**Issue by irfanjvd** [yajra/laravel-datatables#2165]
![error](https://user-images.githubusercontent.com/17895622/64075606-bd715e00-ccd3-11e9-8c8e-44d058b990b0.png)

**Comment by yajra** [comment]
As the error stated, you have an invalid SQL and is out of project scope. Anyways, try adding `select('vehicle_id')`. Or run the query on sequel pro or anything you uses to verify that your sql is correct.

**Comment by yajra** [comment]
If you have access on Laracasts, I suggest you watch this series/episode https://laracasts.com/series/mysql-database-design/episodes/6.
