### ISSUE TITLE
403 (Forbidden)

### ISSUE THREAD

**Issue by k3youmin** [yajra/laravel-datatables#2166]
I use xampp to run my laravel project.

![image](https://user-images.githubusercontent.com/15870174/64085993-4d60e780-cd68-11e9-9d3f-6e5b9ff53ad3.png)

**Comment by yajra** [comment]
Are you logged in when you did the request? Provide some codes to reproduce the issue.

**Comment by k3youmin** [comment]
I already solve my issue, thanks to your package.

**Comment by yajra** [comment]
If you don't mind, kindly share your solution? Thanks!

**Comment by k3youmin** [comment]
I have a master layout and child layout then in child layout I used push
and stacks in my scripts
[image: image.png]

**Comment by k3youmin** [comment]
Good day sir,
What is the possible cause of the request()->ajax() return false?
