### ISSUE TITLE
Rendering occurs before pagination or filtering

### ISSUE THREAD

**Issue by simonorono** [yajra/laravel-datatables#2169]
### Summary of problem or feature request

Using the Datatable for collections, columns get rendered **before** pagination occurs, leading to really slow request when using queries or the query builder is not an option.

### Code snippet of problem

Here's the problem: https://github.com/yajra/laravel-datatables/blob/9.0/src/CollectionDataTable.php#L157-L179

`processResults` occurs before any pagination or filtering, so it performs over the whole data, not just the one that's going to be returned.

**Comment by yajra** [comment]
I think that is the intended behaviour for collection because doing so will allow the package to search and sort on added/edited columns. Performance issue is indeed prone when using collections. So I advise to use it when you are sure that your dataset are not that large.
