### ISSUE TITLE
filterColumn 

### ISSUE THREAD

**Issue by luciantugui** [yajra/laravel-datatables#217]
can I filter data by exact match? it seems like filterColumn adds wildcard % all the time. Is it possible to disable wildcard when calling filterColumn?

this also adds the wildcard:
->filterColumn('price_gross', 'whereRaw', 'price_gross' = ?', ["$1"])

**Comment by yajra** [comment]
`filterColumn` uses wildcard search settings. If you want to do an exact match, then you would have to do it manually by using request object and get the search value. Using `$1` variable will yield to `%search%`. Try something like below:
```php
->filterColumn('price_gross', 'whereRaw', 'price_gross' = ?', [$request->get('search')['value']])
```

**Comment by SuperlativeEntity** [comment]
```
            $data = datatables()->of($members);

            $data->filterColumn('member_number', function ($query, $keyword)
            {
                $query->where('member_number', '=', $keyword);
            });

            return $data->toJson();
```
