### ISSUE TITLE
pageResize Not Showing Correct On First Page

### ISSUE THREAD

**Issue by swartjie** [yajra/laravel-datatables#2170]
### Summary of problem or feature request

When using pageResize plugin with datatables, the data does not pull correctly on the first page. It does pull correctly however after that if I browse to any other page.

Somehow when using the plugin it does not take that into account?

### Code snippet of problem

```php
 $(function () {
    
    var table = $('.dtable').DataTable({
        pageResize: true,
        processing: true,
        serverSide: true,
        paging: true,
        lengthChange: true,
        ajax: "{{ route('company.setups.JobTitles', [$company_id]) }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'code', name: 'code'},
            {data: 'value', name: 'value'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
    
  });
```

### System details
Running Laravel  5.5 using your datatables plugin, also included the resize plugin as stated here: https://datatables.net/blog/2015-04-10

- Operating System
- PHP Version: 7.2
- Laravel Version: 5.4
- Laravel-Datatables Version: 9.5 (I believe)

**Comment by yajra** [comment]
Can you please provide some snippets to reproduce the issue?

**Comment by swartjie** [comment]
HI,I added the code snippet in the original post. Not sure why it's not there... But basically I did 3 things:
1. Setup the datatables plugin according to your documents. And Setup the route to give the data back as the below snippet.
2. Setup the view with n empty table
3. Setup the JS with the pageResize plugin for datatables.

the first page load's with 10 records (most likely the default) once I use the pagination to go to page 2, the page starts resizing according to my browser size and pulls the correct amount of records then..

Very important note, When I don't load the records through the ajax request, and pre-populate the records, it shows as it should. Only when I load it with ajax using your plugin does the first page not resize with the correct amount of records... Hope that helps :)

The Route Code:
public function view_job_titles(Request $request, $company_id)
    {
        if ($request->ajax()) {
            $data = \App\CompanyPresets::where('company_id', $company_id)->where('type', 'Job Title')->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
   
                           $btn = '<a href="javascript:void(0)" class="edit btn btn-primary btn-sm">View</a>';
     
                            return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
      
        return view('users.company.setups.JobTitles')->with('company_id', $company_id);
    }

The JS:
<script type="text/javascript">
  $(function () {
    
    var table = $('.dtable').DataTable({
        pageResize: true,
        processing: true,
        serverSide: true,
        paging: true,
        lengthChange: true,
        ajax: "{{ route('company.setups.JobTitles', [$company_id]) }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'code', name: 'code'},
            {data: 'value', name: 'value'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
    });
    
  });
</script>

**Comment by yajra** [comment]
Not sure but I think this might be an asset arrangement issue. Try loading the pageResize script first before the DataTable script.

**Comment by yajra** [comment]
Okay, tried to played with it and I think the issue is with the plugin itself. I think it does not fully support serverSide processing. Better ask on https://datatables.net/forums/index to get a better support since this is a javascript issue.
