### ISSUE TITLE
Service?

### ISSUE THREAD

**Issue by phillipmadsen** [yajra/laravel-datatables#218]
Why do you have \Service\Datatables; in the imports header of UsersDataTable.php it is not doing anything but throwing errors

**Comment by yajra** [comment]
@phillipmadsen, You should `use yajra\Datatables\Services\DataTable;` and not  `\Service\Datatables;`. The service approach is still under development but it is working as intended. Have you seen this [tutorial](http://datatables.yajrabox.com/service) on how to use it?

**Comment by yajra** [comment]
Going thru the tutorial should fixed the issue.
