### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by der-ada** [yajra/laravel-datatables#2180]
### Summary of problem or feature request

I am facing a little problem with inline-editing. I have an upload-field for images in my table. If I change the image inline, which works very well, i can't persist this change.

So I tried to set it to SubmitOnBlur, like so:
https://datatables.net/forums/discussion/31895/editor-uncaught-typeerror-cannot-read-property-contents-of-undefined

But I can't change the line:

$('#example').DataTable(

to:

var table = $('#example').DataTable(

So, unless I am missing something, it's as of now not possible to change the upload file inline. Any solution?

### System details
- Operating System: debian stretch
- PHP Version: 7.3.9-1+0~20190902.44+debian9~1.gbpf8534c
- Laravel Version: 5.8.35
- Laravel-Datatables Version: newest as of Sep, 15th, 2019

**Comment by yajra** [comment]
Can you please provide the full snippets to reproduce the issue? Thanks!

**Comment by der-ada** [comment]
Hi!

Thank you very much for your answer.

The snippets to reproduce are right in the lin I included. The accepted solution says:

> var table = $('#example').DataTable(

I need to assign the variable "table" to the datatables object. I assume this needs to be done womehere in the HTML-Builder.

TIY & cu,
ada

**Comment by der-ada** [comment]
Hi!

I ran into this problem again. I need to assign a variable name to the DataTable.
Any Ideas?

TIA & cu,
ada

**Comment by der-ada** [comment]
I found it. It is: LaravelDataTables["id"]
