### ISSUE TITLE
Best practice of writing the script and using it inside a blade template

### ISSUE THREAD

**Issue by YouSif-97** [yajra/laravel-datatables#2186]
### Summary of problem or feature request

Is it Ok to use jQuery code within script tags inside a blade template, knowing that it is better if we avoid placing tags with side-effects in templates, such as <script>, as they will not be parsed.

**Comment by CPCoder** [comment]
Then why do you not use the `@push()` function in your blade templates to push a specific JS code (or external JS file) in the main layout template?

In the main layout template you use `@stack('scripts')` at the place where you want to have all your javascripts and in the sub-template you use then 
```
@push('scripts')
    <script src="path/to/external/jsfile.js'></script>
    <script>
        // Your plain javascript
    </script>
@endpush
```
