### ISSUE TITLE
Documentation Website is Down

### ISSUE THREAD

**Issue by amitmeghare** [yajra/laravel-datatables#2189]
Hello Yajra,

We really appreciate your efforts. But we are facing issue while accessing your documentation website. Is there any other way to get the complete documentation. We are waiting for your website to get live.

Thanks :)

**Comment by philspil66** [comment]
I've got round it for now using the archived version on archve.org

Example:
https://web.archive.org/web/20190131042815/http://yajrabox.com/docs/laravel-datatables/7.0

**Comment by amitmeghare** [comment]
Ohh!! Thank you so much @philspil66 :) It's really helpful.

**Comment by yajra** [comment]
Working on it, we just paid the server's $68 balance yesterday and just got short of $3. Will be up soon.

**Comment by amitmeghare** [comment]
It'll be really great. You are awesome @yajra :) Thank you so much.

**Comment by stefkes** [comment]
Still down. How much you need to host it for a year?

**Comment by yajra** [comment]
Thank you all! Please see #2223.
