### ISSUE TITLE
Need search datatable with column alias

### ISSUE THREAD

**Issue by sugengsuprayogi** [yajra/laravel-datatables#219]
My Data Control

    public function data()
    {
        $article = Article::join('languages', 'languages.id', '=', 'articles.language_id')
            ->join('article_categories', 'article_categories.id', '=', 'articles.article_category_id')
            ->select(array('articles.id','articles.title','article_categories.title as category', 'languages.name',
                'articles.created_at'));

        return Datatables::of($article)
            ->add_column('actions', '<a href="{{{ URL::to(\'admin/article/\' . $id . \'/edit\' ) }}}" class="btn btn-success btn-sm iframe" ><span class="glyphicon glyphicon-pencil"></span>  {{ trans("admin/modal.edit") }}</a>
                    <a href="{{{ URL::to(\'admin/article/\' . $id . \'/delete\' ) }}}" class="btn btn-sm btn-danger iframe"><span class="glyphicon glyphicon-trash"></span> {{ trans("admin/modal.delete") }}</a>
                    <input type="hidden" name="row" value="{{$id}}" id="row">')
            ->remove_column('id')

            ->make();

    }

When use search box

     SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as row_count from `articles` inner join `languages` on `languages`.`id` = `articles`.`language_id` inner join `article_categories` on `article_categories`.`id` = `articles`.`article_category_id` where `articles`.`deleted_at` is null and (LOWER(`articles`.`id`) LIKE %k% or LOWER(`articles`.`title`) LIKE %k% or LOWER(`category`) LIKE %k% or LOWER(`languages`.`name`) LIKE %k% or LOWER(`articles`.`created_at`) LIKE %k%)) count_row_table)

**Comment by yajra** [comment]
On your js, define your columns for category as something like below:

```js
columns: [
  { data: 'category', name: 'article_categories.title' }
]
```

**Comment by sugengsuprayogi** [comment]
Thank you very much

**Comment by yajra** [comment]
Welcome!

**Comment by sandeepv** [comment]
Im unable to find the this 
columns: [
  { data: 'category', name: 'article_categories.title' }
]

where to place this code .. pls help me to fix, this

**Comment by sandeepv** [comment]
@yajra 


Im unable to find the this
columns: [
{ data: 'category', name: 'article_categories.title' }
]

where to place this code .. pls help me to fix, this

**Comment by yajra** [comment]
@sandeepv, declare this on your javascript. See this demo for ref: http://datatables.yajrabox.com/eloquent/basic-object

**Comment by setiawans** [comment]
> On your js, define your columns for category as something like below:
> 
> ```js
> columns: [
>   { data: 'category', name: 'article_categories.title' }
> ]
> ```

@yajra 
sorry, is it possible to alias``` name: 'article_categories.title'``` to ```name: 'something.else' ```? 
but actually it still searches based on the actual table "article_categories.title".

**Comment by yajra** [comment]
@setiawans Yes, I think it's possible but you need to override the search function on the backend using `->filterColumn('something.else', ...)`. 

BTW, why do you need to change the name? It would still work as long as the relation is name method `something()` exists.

**Comment by maguilarce** [comment]
I'm having the same problem. Here's my column definition:



columns: [
                 { data: "id", name: "id" },
                 { data: 'date', name: 'date' },
                 { data: 'label', name: 'label' },
                 { data: 'semester', name: 'semester' },
                 { data: 'status', name: 'status' },
                 { data: 'availability', name: 'availability' },
                 { data: 'action_btns', name: 'action_btns'}
                 
                 
              ]

And  my controller:


public function listAllSessions()
    {
        $slip_sessions = SlipSession::query();
        return Datatables::of($slip_sessions)
            ->editColumn("action_btns", function ($slip_sessions) {
                return "<a class='btn btn-info session-edit' href='#' data-id='" . $slip_sessions->id . "'><i class='glyphicon glyphicon-pencil'></i> Edit</a> <a class='btn btn-danger session-delete' href='#' data-id='" . $slip_sessions->id . "'><i class='glyphicon glyphicon-trash'></i> Delete</a>";
            })
            ->rawColumns(["action_btns"])
            ->make(true);
    }

**Comment by yajra** [comment]
@maguilarce I think the issue here is on your `action_btns`. Try using addColumn.

```php
->addColumn("action_btns", ...
```

**Comment by maguilarce** [comment]
I fixed it by doing:

`
public function listAllSessions()
    {
        $slip_sessions_query = DB::table("slip_sessions")
            ->select("slip_sessions.*")
            ->where(["slip_sessions.status" => "active"])
            ->get();
        return Datatables::of($slip_sessions_query)
            ->editColumn("action_btns", function ($slip_sessions_query) {
                return "<a class='btn btn-info session-edit' href='#' data-id='" . $slip_sessions_query->id . "'><i class='glyphicon glyphicon-pencil'></i> Edit</a> <a class='btn btn-danger session-delete' href='#' data-id='" . $slip_sessions_query->id . "'><i class='glyphicon glyphicon-trash'></i> Delete</a>";
            })
            ->rawColumns(["action_btns"])
            ->make(true);
    }
`

**Comment by yajra** [comment]
@maguilarce yes that would also work. But do note of `->get();` uses collection and it might hit a performance issue once your DB becomes large.
