### ISSUE TITLE
RawColumns in version 6.x??

### ISSUE THREAD

**Issue by aroldanclicko** [yajra/laravel-datatables#2190]
### Summary of problem or feature request

Is there the RawColumns () function in version 6?

### System details

- Operating System: Debian
- PHP Version: 7.0
- Laravel Version: 5.1
- Laravel-Datatables Version: 6.x

**Comment by erlangp** [comment]
https://laravel.com/docs/6.x#server-requirements

>     PHP >= 7.2.0
>     BCMath PHP Extension
>     Ctype PHP Extension
>     JSON PHP Extension
>     Mbstring PHP Extension
>     OpenSSL PHP Extension
>     PDO PHP Extension
>     Tokenizer PHP Extension
>     XML PHP Extension

**Comment by yajra** [comment]
Sorry for late response. RawColumns is not available on v6.
