### ISSUE TITLE
yajrabox Server Down !!

### ISSUE THREAD

**Issue by a-hussalem** [yajra/laravel-datatables#2192]
Hello,
The yajrabox.com is down.
If there is any thing I could help you with so, i'm here

**Comment by Ans-dev** [comment]
I want to know how to use default search filter with out custom logic.???Please Help as documentation is not accessible.

**Comment by marcelogarbin** [comment]
+1

**Comment by Mghobadid** [comment]
until the server up again use the web archive 
[https://web.archive.org/web/20190713172523/https://datatables.yajrabox.com/starter](url)

**Comment by yajra** [comment]
#2189
