### ISSUE TITLE
Filtering fails when joins and aliases are used

### ISSUE THREAD

**Issue by jim1506** [yajra/laravel-datatables#2196]
### Summary of problem or feature request

While the initial table draws OK it seems that the search filter does not work with the join.

I have the following method in my controller
![01-10-2019 11-32-16](https://user-images.githubusercontent.com/123184/65955135-603a0b00-e43f-11e9-9903-bee945e2af17.png)

and the code in my view is

![01-10-2019 11-34-54](https://user-images.githubusercontent.com/123184/65955212-8d86b900-e43f-11e9-8ddf-3ff827d7dffb.png)

This is all OK until I use the search box when I get

![01-10-2019 11-35-49](https://user-images.githubusercontent.com/123184/65955283-b4dd8600-e43f-11e9-9852-ccc04b0acd23.png)

### System details

- Operating System - Windows 10 as localhost
- PHP Version - 7.1
- Laravel Version 5.8
- Laravel-Datatables Version - latest

**Comment by Karacraft** [comment]
Assuming your **users** table has **name** field as well, so a workaround is to change your 
`
**users.name as name**

with

**users.name as username**
`
Filter actually searches the table (it doesn't search your select statement) and when it finds name in both tables it throws error
