### ISSUE TITLE
Is there a recommended way to set and retrieve URL for specific state?

### ISSUE THREAD

**Issue by Slivicon** [yajra/laravel-datatables#2197]
I would like to set the URL whenever a specific state of the dataTable is set by the user (sort, columns, page, search, etc.) so that they can bookmark/share that URL. When the URL is accessed in another client browser session, the dataTable loads the state that was selected.

I have only found solutions like "keepConditions.js" (discontinued, could not get it to work with yajra laravel-datatables 9 as service), or deepLink.js (datatables plugin that does not set URL for state, only will set state if parameters in URL specify state settings; "half" solution).

**Comment by yajra** [comment]
I just tested keepConditions and it is working on hashing the state. However, it seem like it's not compatible yet on serverSide processing as per issue: https://github.com/jhyland87/DataTables-Keep-Conditions/issues/1.

To integrate, just add the parameters like below. And also, don't forget to include the scripts.

```php
            ->parameters([
                'keepConditions' => 'oplfvcs'
            ])
```

**Comment by yajra** [comment]
> Is there a recommended way to set and retrieve URL for specific state?

Can't answer this question as I haven't implemented a use case like this yet but it seems like keepConditions is a good way to go.

**Comment by yajra** [comment]
Found a fix for initializing the plugin. Just replace `init.dt` event with `preInit.dt`.

```js
    $(document).on('preInit.dt', function (e, dtSettings) {
        if (e.namespace !== 'dt') return;

        if (dtSettings.oInit.keepConditions !== undefined) new KeepConditions(dtSettings);
    });
```

However, the page number is still not persisted as stated in the issue I reference above. Other than the page, the plugin seems to work well.

**Comment by Slivicon** [comment]
Thank you, Yajra, I appreciate the feedback and insight.
