### ISSUE TITLE
serverside custom column order (orderData) 

### ISSUE THREAD

**Issue by fabianscholz** [yajra/laravel-datatables#220]
Hi,

I'm trying to order a column by a order database field.
I have a Table like this:

| id | shortname | order |
|----|----|----:|
|1|b|10
|2|a|20
|3|c|0

The user should see the shortname but if the user order this column, then sort by *order*-field.
Without serverSide i realized with columnDefs:
```
columnDefs: [
            { targets: 10, defaultContent: ""},
            { targets: 11, orderData:12},
            { targets: 12, visible: false}
        ],
```
i load a column *12* with the order number, hidden it and set the order target for column *11* to *12*, so if the user sort column *11* it sorted by column *12*. But with serverSide enabled it didn’t work.

**after sorting *shortname* it should look like this (but with not visible *order* column)**

| id | shortname | order |
|----|----|----:|
|3|c|0
|1|b|10
|2|a|20

It's posible to set a order by tag only if the the corresponding column should be sort?

Sorry for my bad english
Fabian

**Comment by yajra** [comment]
I just tested this on my demo app and it seems to work. Like example below will order by name when email was clicked.

```js
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url("eloquent/basic-object-data") }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email', orderData: 1},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'}
        ]
    });
```

**Comment by fabianscholz** [comment]
Hi yajra,

the option is very useful for my projects. And with your help it works just fine!
I forgot to a a *name* to data, so the server could not process the order.

My code before:

```
{ data: 'machines', name: 'machine', render: "[, ].shortname" },
{ data: 'authority.shortname', name: 'authority.shortname' },
{ data: 'status.name', name: 'staus.name', orderData: 3 },
{ data: 'status.order', type: 'num'}
```

and after:

```
{ data: 'machines', name: 'machine', render: "[, ].shortname" },
{ data: 'authority.shortname', name: 'authority.shortname' },
{ data: 'status.name', name: 'staus.name', orderData: 3 },
{ data: 'status.order', name:'status.order', type: 'num', visible: false}
```

Thanks alot
Fabian

**Comment by fanjavaid** [comment]
Hello i have same issue an apply your solution like this : 
```php
[
                    'title' => 'ID Paket',
                    'data' => 'id_paket',
                    'name' => 'id_paket',
                    'visible' => true,
                    'orderData' => 1
                ],
```

But it won't work
I have this data id as a big number **5250421** but in my sort just show **660169**
And my ID Paket column at the first one.

**Comment by KS-Kannu** [comment]
Hi yajra,

the option is very useful for my projects. And with your help it works just fine!
but can i use column name at the place of column id for shorting

$('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url("eloquent/basic-object-data") }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email', orderData: 'EmpName'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'}
        ]
    });
