### ISSUE TITLE
Datatable not showing data 

### ISSUE THREAD

**Issue by ElHombreSinNombre** [yajra/laravel-datatables#2200]
In **Laravel 6.0** I'm trying to use [this package][1] to show a data table. The data table appears but doesn't have any data. I use [datatables as service][2] like documentation says. My code is

**Routes**

    Route::match(['get', 'post'],'usuarios', 'UsuarioController@index')->name('usuarios.listado');

**Controller**

    use App\DataTables\UsuariosDataTable;
    
      public function index(UsuariosDataTable $dataTable)
        {
            return $dataTable->render('home');
        }

**Datatable Service**

    <?php
    
    namespace App\DataTables;
    
    use App\User;
    use Yajra\DataTables\Html\Button;
    use Yajra\DataTables\Html\Column;
    use Yajra\DataTables\Html\Editor\Editor;
    use Yajra\DataTables\Html\Editor\Fields;
    use Yajra\DataTables\Services\DataTable;
    
    //Facades
    use Carbon;
    
    class UsuariosDatatable extends DataTable
    {
        public function ajax($query)
        {
          dd('Hello') //Doesn´t work here
          return $this->datatables
          ->eloquent($this->query())
          ->make(true);
        }
    
        public function query(UsuariosDatatable $model)
        {
    
          $users = User::all();
          return $this->applyScopes($users);
        }
    
        public function html()
        {
          dd('hello') //dd works here
          return $this->builder()
               ->columns($this->getColumns())
               ->parameters([
                    'order'      => [[0, 'desc']],
                    'pagingType' => 'full_numbers',
                    'dom'        => "<'row'<'col-xs-12'<'col-xs-6'l>B>><'row'<'col-xs-12't>><'row'<'col-xs-12'<'col-xs-6'i> <'col-xs-6'p>>>",
                    'buttons'    => [
                         ['extend' => 'excel', 'text' => '<i class="fa fa-file-excel-o"></i> Exportar a Excel'],
                    ],               
                    'processing' => true,
                    'serverSide' => true,
                    'responsive' => true,
                    'searching'  => true,
                   ])
        }
    
    
        protected function getColumns()
        {
            return [
                 'name'     => ['title' => 'Nombre','name'=>'name'],
                 'email'    => ['title' => 'Email' ,'name'=>'email'],
            ];
        }
    
        protected function filename()
        {
            return 'Listado de usuarios del ' . Carbon:: now()->format('d/m/Y H:i:s');
        }
    }

**View**

    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Laravel DataTables Tutorial</title>
            <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
            <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
    
        </head>
        <body>
            <div class="container">
        
            {!! $dataTable->table() !!}
    
            </div>
    
            @push('scripts')
            <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
            <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
            <script src="/vendor/datatables/buttons.server-side.js"></script>
            {!! $dataTable->scripts() !!}
            @endpush
        </body>
    </html>

I used this package many times but i think something was changed in some update but don't know exactly what is.

Thr question is: Somebody see what´s is wrong? What is the right way to create a datatable with this package?

  [1]: https://datatables.yajrabox.com/eloquent/
  [2]: https://datatables.yajrabox.com/service

**Comment by shubham1397** [comment]
same issue

**Comment by yajra** [comment]
@ElHombreSinNombre some mistakes on your code:

You are using collection and parsing it as eloquent:

```php
public function query(UsuariosDatatable $model)
    {

      $users = User::all();
      return $this->applyScopes($users);
    }
```

Should be something like:

```php
public function query(User $model)
    {
      return $model->newQuery();
    }
```

If you want to use collection:

```php
return $this->datatables
      ->collection($this->query())
```

Lastly, it seems you are using the old version and upgrading to Laravel 6. Better check the upgrade guide https://yajrabox.com/docs/laravel-datatables/master/upgrade.

**Comment by ElHombreSinNombre** [comment]
The documentation explain how to update to 8.* but i use this packages

>   "yajra/laravel-datatables-buttons": "4.8",
>    "yajra/laravel-datatables-oracle": "^9.7"

I changed the code to this but table continue empty

```
<?php

namespace App\DataTables;

use App\User;
use Yajra\DataTables\Html\Button;
use Yajra\DataTables\Html\Column;
use Yajra\DataTables\Html\Editor\Editor;
use Yajra\DataTables\Html\Editor\Fields;
use Yajra\DataTables\Services\DataTable;


class UsersDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->make(true);
    }

    /**
     * Get query source of dataTable.
     *
     * @param \App\UsersDataTable $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(User $model)
    {
      return $model->newQuery();
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {


        return $this->builder()
                    ->columns($this->getColumns())
                    ->buttons(
                        Button::make('create'),
                        Button::make('export'),
                        Button::make('print'),
                        Button::make('reset'),
                        Button::make('reload')
                    );
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            ['data' => 'name', 'name' => 'name', 'title' => 'name'],

        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'Users_' . date('YmdHis');
    }
}
```

**Comment by ZAZmaster** [comment]
same issue
use "yajra/laravel-datatables": "v1.5.0" php 7.3.3 laravel 6.5.2

**Comment by ZAZmaster** [comment]
There will be news on this issue?

**Comment by Andile192** [comment]
Having the same issue any solution?

**Comment by avishkaME** [comment]
Having the same issue with v9 + laravel v8. any solution?

**Comment by samraskul** [comment]
Having the same issue with v9 + laravel v8. any solution?

**Comment by hunterbit** [comment]
I have same problem with v9 + laravel v8

**Comment by Jamshid2906** [comment]
I have same problem with laravel 8 
Is there solution this problem

**Comment by parsasamandi** [comment]
`use App\DataTables\AdminDataTable;`

// DataTable to blade
   ```
 public function list() {
        // dataTable
        $dataTable = new AdminDataTable();

        // Admin Table
        $vars['adminTable'] = $dataTable->html();

        return view('admin.adminList', $vars);
    }
```
I hope by adding this function, it works.
