### ISSUE TITLE
Cannot install package on Laravel v6.1

### ISSUE THREAD

**Issue by sambindas** [yajra/laravel-datatables#2201]
Im trying to install to my project using ```composer require yajra/laravel-datatables-oracle:^9.0```
But its returning the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yajra/laravel-datatables-oracle 9.0 -> satisfiable by yajra/laravel-datatables-oracle[v9.0.0].
    - Conclusion: remove laravel/framework v6.1.0
    - Conclusion: don't install laravel/framework v6.1.0
    - yajra/laravel-datatables-oracle v9.0.0 requires illuminate/view 5.8.* -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].

System details:
Windows 10
Php v7.2.5
Laravel v6.1
Laravel-Datatables v9.0

**Comment by marcelloinfoweb** [comment]
Some Problem, with plugin Buttons.

Laravel: 6.2
OS: Clear Linux
PHP v7.3
