### ISSUE TITLE
DataTables Retrieve Row Data

### ISSUE THREAD

**Issue by WGR7** [yajra/laravel-datatables#2207]
Hi,

I already populated my dataTable and a I need to know how to get all fields from a row in my dataTable. How can I get the values from the row number 3 and pass to a view, for example?

Best Regards

He I set id for some CRUD buttons equals to user id

            return $this->dataTable->eloquent($data)
                ->addColumn('action', function($data){                            
                    $button =  '<button type="button" name="view" id="'.$data->user_id.'" class="view btn btn-primary btn-sm">Exibir</button>';                       
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<button type="button" name="edit" id="'.$data->user_id.'" class="edit btn btn-warning btn-sm">Editar</button>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<button type="button" name="delete" id="'.$data->user_id.'" class="delete btn btn-danger btn-sm">Apagar</button>';
                    return $button;
                })
                ->rawColumns(['action'])
                ->make(true);

Here are my columns that I need to retrieve the row data

columns: [           

            {data: 'users.name', name: 'users.name'},
            {data: 'users.email', name: 'users.email'},  
            {data: 'users.email1',name: 'users.email1'},
            {data: 'name',name: 'name'},
            {data: 'bloco',name: 'bloco'},
            {data: 'action',name: 'action',orderable: false}
            ],

- Operating System : Linux Lite 4.6
- PHP Version: 7.2.19
- Laravel Version: 5.8
- Laravel-Datatables Version: 9.7.0

**Comment by Karacraft** [comment]
Do not use button, as they are usually used with forms or if you want to use javascript to show alert boxes etc.

User anchor tag and pass on your view route with row id to show it. Example below :

`
->addColumn('edit',function($data){
            return '<a href="'  .route('purchase.edit', ['id'=>$data->id ]) . '" class="btn btn-default btn-sm"   title="Edit #' . $data->id . '"><i class="fa fa-edit text-info"></i></a>';
})
`

However, if you really want to use button, then here is an example (You'll need javascript with this)

`->addColumn('cancel',function($data){
            return '<button type="button" 
            id="' .$data->id. '" 
            data-cancel="'  . route('purchase.cancel.po') . '/?id='  . $pos->id .'"
            class="btn btn-default btn-sm" title="Cancel #' . $pos->id . '" 
            onclick="cancelPO(this)"><i class="fa fa-trash text-danger"></i></button>';
        })`
