### ISSUE TITLE
Setting the number visible pages from the PHP service

### ISSUE THREAD

**Issue by simonorono** [yajra/laravel-datatables#2209]
### Summary of problem or feature request

Recently I found myself doing something not so nice in order to increase the number of pages displayed in the pager:

```php
  {!! $dataTable->scripts() !!}
  <script>
    $.fn.DataTable.ext.pager.numbers_length = 11;
  </script>
```

Is there a way of adding that option from the PHP service? I already tried this with no luck:

```php
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->parameters([
                'ext.pager.numbers_length' => 11
            ])
            ->minifiedAjax();
    }
```

**Comment by yajra** [comment]
Can you please provide the link on datatables.net on how it was implemented?

Anyways, I think you should convert it to array:

```php
->parameters([
'ext' => [
  'pager' => [
    'numbers_length' => 11
  ]
]
])
```

**Comment by simonorono** [comment]
Converting it to array didn't work; [here's the implementation from datatables.net](https://github.com/DataTables/DataTablesSrc/blob/ae01542c8fad109cdffa27308678a421189df3f0/js/ext/ext.paging.js).

**Comment by yajra** [comment]
Checking some related stuffs on forum and it seems like that feature is hidden and currently bugged. 

https://datatables.net/forums/discussion/comment/70543/#Comment_70543
https://datatables.net/forums/discussion/comment/68094/#Comment_68094

If the number is fixed, you can override the default script template `datatables/script.blade.php` and include the script you have `$.fn.DataTable.ext.pager.numbers_length = 11;`.
