### ISSUE TITLE
editcolumn and then order

### ISSUE THREAD

**Issue by dpapala** [yajra/laravel-datatables#2210]
### Summary of problem or feature request

Order by column that is first decrypted

### Code snippet of problem

I want to order my results by a specific column that i first need to edit because it is encrypted.

```
->editColumn('field', function($data) {
            if (!empty($data->field)) return Crypt::decrypt($data->field);
            else return "";
        })
```

I use serverside datatables.
Is there any way to do this?

**Comment by yajra** [comment]
Unfortunately, ordering on edited column value is not possible unless you convert the decryption to database / query level.
