### ISSUE TITLE
Help with using this plugin with lumen

### ISSUE THREAD

**Issue by Skilmen6** [yajra/laravel-datatables#2211]
I have just started learning and using lumen and I would like to use this plugin.
I have read the other posts about using this plugin in lumen and I have tried to make it work for myself, but I can't make it work. I was hoping someone could help me with this.

###System details

-Operating System: Windows
-PHP Version: 7.2.9
-Lumen Version: 6.x
-Laravel-Datatables Version: 9.0

**Comment by yajra** [comment]
Haven't tried using lumen, need help from the community on this one. Thanks!

**Comment by webkod3r** [comment]
Check this
https://github.com/yajra/laravel-datatables/issues/317#issuecomment-586804849
