### ISSUE TITLE
datatable look strange

### ISSUE THREAD

**Issue by senaacls** [yajra/laravel-datatables#2212]
i have some problem with datatable, I use laravel 5.7 version and datatable yajra 8.0..

my datatable is  not working in production
this is sample code in local 
```
var otable = $('#example').DataTable({
            processing: true,
            serverSide: true,
            **ajax: '/custtype',   // not work (production) but work in local
            sAjaxSource: '/custtype', // work in production** 
            columns: [
                { data: 'CustTypeCode', name: 'CustTypeCode' },
                { data: 'CustTypeName', name: 'CustTypeName' },
                { data: 'FgActive', name: 'FgActive' },
                { data: 'action', name: 'action' }
            ]
        });
```

thank you for attention

**Comment by yajra** [comment]
@senaacls this issue is indeed strange as this is the first time I think that received an issue like this. Anyways, I think this might be related to your production server configuration. See https://github.com/yajra/laravel-datatables/issues/1210 for some ref.
