### ISSUE TITLE
Hi I am using API Resource and it working great, until I have tried add another resource into it. like

### ISSUE THREAD

**Issue by shamsuljewel** [yajra/laravel-datatables#2213]
Hi I am using API Resource and it working great, until I have tried add another resource into it. like
`return [
			'id' => $this->id,
	        'name' => $this->name,
'users' => UserResource::collection($this->whenLoaded('getusers')),`

when I loaded getusers then it's not using the UserResoure, it's just return me back the resource from database!!

` "users": {
                "collects": "App\\Http\\Resources\\V1\\UserResource",
                "collection": [
                    {
                        "resource": {
                            "id": "141",
                            "email": "test.platform@doorhub.io",
                            "permissions": [],
                            "last_login": "2019-10-14 16:50:23",
                            "first_name": "Test",`

where as I expected id, userName, etc.

Is it supported? or I am doing wrong?

_Originally posted by @shamsuljewel in https://github.com/yajra/laravel-datatables/pull/1702#issuecomment-542288810_

**Comment by sanshan** [comment]
I confirm. There is a problem.

**Comment by benderoki** [comment]
@shamsuljewel 
Try use this. 
`
        $builder = User::with(['payment']);

        return DataTables::eloquent($builder)
            ->setTransformer(function ($item) {
                return UserResource::make($item)->resolve();
            })
            ->make();
`
**Note** package https://github.com/yajra/laravel-datatables-fractal required

**Comment by shamsuljewel** [comment]
@benderoki I found the solutions, yes I am now using what you have referred.
I confirm that it is working fine.

One problem might come if you use transformers like In my App I also expects the column fields returned with the same fields that I send using Resource. I am using a Bag class to convert back my db fields before using Datatables:.eloquent.
