### ISSUE TITLE
Error getting hasMany relationship when sorting by another relation column when doing datatables($builder)->make()

### ISSUE THREAD

**Issue by LimitTech** [yajra/laravel-datatables#2214]
### Summary of problem or feature request

Problem:
Error getting hasMany relationship when sorting by another relation column when doing datatables($builder)->make()

If the ordering column is "entitat" or "tipus" won't eager load _respostes_, but if sorting by respostes or any non-relation column it works.

Note below that when it filters incidencia_id (the foreign key of _respostes_) it binds the ids of _Entitats_, instead of incidencia. In this example I sorted by _Entitat_.

### Code snippet of problem

Incidencia hasMany respostes
Incidencia belongsTo Tipus
Tipus belongsTo Entitat

respostes = HasMany relationship
tipus = BelongsTo relationship
entitat = BelongsTo relationship of Tipus

```php
// Works but won't do pagination
     $builder = Incidencia::with('tipus.entitat', 'respostes', 'treballador');
     $builder = $builder->whereDate('dataihora', $request->dia);
     return datatables($builder->get())->make();

Query from debugbar:
select * from `tipus_incidencia` where `tipus_incidencia`.`id` in (17, 28)
select * from `entitats` where `entitats`.`id` in (**5, 6**) 
select * from `respostes` where `direccio` = 1 and `respostes`.`incidencia_id` in (**38, 39**)

----------------

// Doesn't work
     $builder = Incidencia::with('tipus.entitat', 'respostes', 'treballador');
     $builder = $builder->whereDate('dataihora', $request->dia);
     return datatables($builder)->make();

Query from debugbar:
select * from `tipus_incidencia` where `tipus_incidencia`.`id` in (17, 28) 
select * from `entitats` where `entitats`.`id` in (**5, 6)** 
select * from `respostes` where `direccio` = 1 and `respostes`.`incidencia_id` in (**5, 6**)

```

### System details

- Windows Xampp 
- PHP Version: 7.3
- Laravel Version 6.2
- Laravel-Datatables Version 9.7.0

**Comment by benyaminl** [comment]
I think because you tried to add all model to the DataTable class. I recommend you to use https://yajrabox.com/docs/laravel-datatables/master/response-fractal or https://yajrabox.com/docs/laravel-datatables/master/add-column if you need data from the table, because it's not possible I think to do that with DataTable Laravel. I always use fractal if I need the relationship or I do manual query, because it's not Laravel DataTable restriction, but by design.
