### ISSUE TITLE
Passing object to view and to datatable when using datatables as a service

### ISSUE THREAD

**Issue by WimDeMeester** [yajra/laravel-datatables#2215]
### Summary of problem or feature request

I'm using datatabes as a service and I'm trying to send some data to both the view and the datatable.

The following code sends the data to the datatable class, but not to the view

`return $dataTable->with('target', $target)->render('layout.target.show');`

Is there a way to do so?

**Comment by elraghifary** [comment]
You can pass variable to datatable like this :
```
// TargetController
public function index(TargetDataTable $dataTable, $target)
{
    return $dataTable->with('target', $target)->render('layout.target.show');
}
```
```
// TargetDataTable
public function query()
{
    $target = $this->target;
    // query
}
```

**Comment by WimDeMeester** [comment]
This indeed works to pass the variable to the datatable, but I also want to pass the variable to the blade file (layout/target/show.blade). It does not matter if I do this from the datatable or from the Controller...

**Comment by elraghifary** [comment]
Like this?
```
return $dataTable->with('target', $target)->render('layout.target.show', compact('some variable'));
```

**Comment by WimDeMeester** [comment]
That does indeed work! Thanks!

**Comment by vipulwalia** [comment]
> Well this doesn't work in case of **blade component**
> 
> Variables that i pass like this
> 
> ```
> public function index(UserDataTable  $dataTable)
>     {
>         $pageData = [
>             'pageTitle'     => 'User Listing',
>             'createUrl'     => url('/')
>         ];
>         return $dataTable->render('pages.users.index',$pageData);
>     }
> ```
> 
> is only avaiable in this
> 
> ```
> <x-base-layout>
>     <div class="card">
>         <div class="card-body pt-6">
>             @include('pages.users._table')
>         </div>
>     </div>
> </x-base-layout>
> ```
> 
> not anywhere apart from this blade, please help, thank you.

Never Mind i figure it out
This is my controller
   ```
 public function index(UserDataTable  $dataTable)
    {
        $pageData = [
            'pageTitle'     => 'User Listing',
            'createUrl'     => route('users.create')
        ];
        return $dataTable->render('pages.users.index',$pageData);
    }
```

By passing variables like this, i can send data to my parent or master blade template
```
<x-base-layout :pageTitle="$pageTitle" :createUrl="$createUrl">
    <div class="card">
        <div class="card-body">
            @include('pages.users._table')
        </div>
    </div>
</x-base-layout>
```
And can use it like this
  `  <title>{{ $attributes['pageTitle'] }}</title>
`
