### ISSUE TITLE
How to use render in the column with datatable as a service

### ISSUE THREAD

**Issue by nonowd** [yajra/laravel-datatables#2217]
Hey,

I use your very nice plugin for my website.

I use it as a service, and in the getColumns() function, I can choose the data I want to get.
But it will render it as it is in the database. I want to customize it.

Iv seen I can use "render" option, but I have seen any where how to use it.

This doesnt work:

`
protected function getColumns()  {

        return [
           Column::make('preparation_status')
                ->title('Status')
                ->render(function($data) {
                    return $data . " test";
                })
         ]
}`

Thanks for your help.

**Comment by NettSite** [comment]
I think that should be 
`render->(data + ' test')`

**Comment by nonowd** [comment]
> I think that should be
> `render->(data + ' test')`

Hey, thanks but it doesn't work

**Comment by NettSite** [comment]
See the question I posted - what does the final Javascript look like?

**Comment by nonowd** [comment]
It returns a general error.
But that's because the way the datatable service - as I understood - should allow you to construct your table only using php. That's what Im doing in my case, thats why it returns a general error.

So when I do that:, its all php

`protected function getColumns() { 
return [
       Column::make('preparation_status')
            ->title('Status')
            ->render(function($data) {
                return $data . " test";
            })
]`

I think it works differently if you construct your datatable using javascript. The render method seems to be fine.

But I can't make the render method works in my case, constructing the datatable as a service, only using php.

**Comment by egyangel** [comment]
it should be like this 
 Column::make('img','Immagine')->render(@"'<img src =\"'"."+data+'"."\"   >'"),

 Column::make('img','Immagine')->render("data +'test' "),

**Comment by yajra** [comment]
@egyangel solution should work, thanks!
