### ISSUE TITLE
Documentations website not working

### ISSUE THREAD

**Issue by kitro** [yajra/laravel-datatables#2218]
The documentations website not working:
http://yajrabox.com/docs/laravel-datatables

**Comment by samoldenburg** [comment]
@yajra 

This happens all the time, and we have asked you many times to take the community offers being given to you for others to host your documentation.

As was the case last time, it is clear that you do not have the time, or technical capability to maintain your own documentation website. This package is very difficult to use without documentation.

This time, I hope you actually take those offers. It is very frustrating for the people that use this package to have to complain on Github every time you fail to maintain your documentation website.

**Comment by yajra** [comment]
Thank you! Please see #2223.

**Comment by bm2ilabs** [comment]
i have hosted the doc in netlify if anyone need a quick browsing 
https://laravel-datatables-docs.netlify.com/
