### ISSUE TITLE
"render" seems to be enclosing twice?

### ISSUE THREAD

**Issue by NettSite** [yajra/laravel-datatables#2219]
When using the "render" functionality, DataTables encloses the value which is passed in a function, e.g. 
`render(data)`

should become 

`function(data,type,full,meta){return data}

in the final script passed to the browser. 

I am experiencing it "double enclosing", so that the passed value is out of scope and is "undefined".

### Code snippet of problem

`$column->render("(data + '').replace(/^(.)|\s+(.)/g, function ($1) {return $1.toUpperCase()})"");`

returns 

`"render":function(data,type,full,meta){return function(data,type,full,meta){return (data + '').replace(/^(.)|\s+(.)/g, function ($1) {return $1.toUpperCase()});};}`

The closure is enclosed in a closure, and 'undefined' is returned.

If I pass a string literal instead of the data variable, it works, so it is obviously the data variable in the inner closure which is not defined.

### System details

- Operating System
- PHP Version 7.3
- Laravel Version 6.3
- Laravel-Datatables Version "8.*|9.*" (Where can I find the version?)

I have recently upgraded, and it was working before that.

What could I be doing wrong?

**Comment by yajra** [comment]
The render implementation already adds the js for us cause I feel lazy when doing that feature thus, should be used like:

```php
->render('full.column_name')
```

**Comment by NettSite** [comment]
I am also lazy, I understand. However, that doesn't solve my problem. Here is another example:

I write

`render->('send_mail == 1 ? Yes : No')`

and the JS is added twice:

'"render":function(data,type,full,meta){    //  First JS
                 return function(data,type,full,meta){  // Second JS
                        return send_mail == 1 ? Yes : No;  // send_mail is not defined
		};
	};
`

**Comment by yajra** [comment]
I see, will review this. What version are you using?

**Comment by NettSite** [comment]
I am not sure of the version, but I have updated recently, and I think the problem started after the update.

My composer.json says 

`
"yajra/laravel-datatables-buttons": "^4.8",
 "yajra/laravel-datatables-editor": "^1.17",
 "yajra/laravel-datatables-html": "^4.18",
"yajra/laravel-datatables-oracle": "^9.6",
`

Where can I see the version of your scripts?

**Comment by NettSite** [comment]
Don't worry about this for a moment, I think I know why it is happening, and it is on my side.

I am using the "Column" class to generate the definitions, but I need an array and not an object to use in my form loop. Therefore, I take the Column attributes as an array and return that from get_columns() in the datatable. Clearly, the JS has been added at that point, and because it is getting an array and not an object, datatables adds it again when it generates the datatable JS.
