### ISSUE TITLE
editColumn is not being called

### ISSUE THREAD

**Issue by isbkch** [yajra/laravel-datatables#222]
I'm following the same example on http://datatables.yajrabox.com/eloquent/add-edit-remove-column#edit-9

but editColumn() is not being called, the column is not being changed, is there some kind of special case for it not to be called at all ?

I have no error in php or js, the editColumn() it's just not executed.

**Comment by yajra** [comment]
Can you please paste your php code?

**Comment by isbkch** [comment]
sure.

This works:
```
return Datatables::of(Spot::select('*'))
            ->editColumn('name', '<a href="spot/view/{{$id}}">{{$name}}</a>')
            ->make(true);
```
This doesn't works:
```
$results = Spot::select('*');
return Datatables::of($results)
            ->editColumn('name', '<a href="spot/view/{{$results->id}}">{{$results->name}}</a>')
            ->make(true);
```
I discovered later that I need to do it that way:
```
$results = Spot::select('*');
return Datatables::of($results)
            ->editColumn('name', '<a href="spot/view/{{id}}">{{$name}}</a>')
            ->make(true);
```

The second and third example are not mentioned in the docs, so I had to look at what of() first.
my bad.

**Comment by yajra** [comment]
Your second example has an error.You cannot reference `$result` instance on the blade string. All attributes of your model will be passed as a variables on blade.
**Error**
```php
->editColumn('name', '<a href="spot/view/{{$results->id}}">{{$results->name}}</a>')
```

**Correct**
```php
->editColumn('name', '<a href="spot/view/{{id}}">{{$name}}</a>')
```

In addition, you can also use a view or closure on `editColumn` like:
```php
->editColumn('name', 'path.to.view') // all model attributes will be passed as variables.
```
```php
->editColumn('name', function($model){
  return '<a href="spot/view/' . $model->id . '">' . $model->name . '</a>';
})
```
