### ISSUE TITLE
[Need Help] Documentation Upgrade Funds

### ISSUE THREAD

**Issue by yajra** [yajra/laravel-datatables#2223]
Ok, I know that the site has been down several times due to some billings issues of my friend who provides me with a free hosting since the beginning of the project. Would like to thank him for the support and for being my motivator and inspiring me to give back to open source community.

Moving forward,  I would like to seek help to generate funds and move the project documentation to its own server. There are several offers for hosting but I prefer it to be a server on my own account. I just need at least a year of hosting funds and can handle it from there. Also, I would like to include my friend's current server bill of $121.61 so that he can finally close his account.

## FUNDS NEEDED
- 1 year hosting at DO for $20/mo. (4gb at least)
- $121.61 dollar to settle the current server bill.

## ESTIMATED TOTAL FUNDS NEEDED: $361.61

Those who are willing to help can send their donations to my paypal account: https://www.paypal.me/yajra

I will try to bring the documentations up as soon as the funds are enough. Might also upgrade the documentation to Laravel 6 if supports generated are motivating.

**Comment by samoldenburg** [comment]
Why not just put some documentation somewhere that isn't going to go down, and is free, like GitHub pages?

Crowdsourcing funding to host your personal website on your own personal server is not necessary when you have community offers on the table to set you up with space on a server. This response to the criticism is frustrating at best for the people that use the package.

**Comment by yajra** [comment]
> Why not just put some documentation somewhere that isn't going to go down, and is free, like GitHub pages?

It's already on github https://github.com/yajra/laravel-datatables-docs.

> Crowdsourcing funding to host your personal website on your own personal server is not necessary when you have community offers on the table to set you up with space on a server. This response to the criticism is frustrating at best for the people that use the package.

I prefer that my codes are in my personal account for security purposes and that it can't be publicly shared without my permission.

**Comment by zero0n3** [comment]
hello
have you ever thought about using free services like heroku to store documentatio?

**Comment by bm2ilabs** [comment]
Hello , if anyone wants to browse the documentation check https://laravel-datatables-docs.netlify.com/

**Comment by zack6849** [comment]
@yajra wouldn't it be good to have the documentation as a github sites site with a domain pointed at it, or is that not doable with the current state of the documentation?

**Comment by HthSolid** [comment]
is there a site to see how much funding is needed and provided, like crowdfunding site?

**Comment by yajra** [comment]
@bm2ilabs thanks for that docs. I will update readme and point the docs there while I'm working to restoring my site.

@zack6849 Yes, for static docs. But for the demo that needs database access, I think it will not work.

@HthSolid  No crowdfunding site and no donations received yet. 

Closing this request and will personally fund my site next year.

**Comment by gidaban** [comment]
Hi,

msg me.

i can provide web hosting.
