### ISSUE TITLE
Total amount causing issue with paging

### ISSUE THREAD

**Issue by TheGeekyM** [yajra/laravel-datatables#2225]
### Summary of problem or feature request

When I get the sum of amount it works great but once I'm using the pagination the total amount gets 0.

Laravel/PHP Code
->withQuery('total', function ($filteredQuery) {
                return $filteredQuery->sum('Amount');
            })```

Js Code
table.on('draw.dt', function (e) {
            $('#total').text(LaravelDataTables["dataTableBuilder"].ajax.json().total)
        });

### System details

- Operating System unbntu 19.04
- PHP Version 7.1 
- Laravel Version 5.8
- Laravel-Datatables Version 9.0

**Comment by yajra** [comment]
Any error on the response? Maybe try cloning the `filteredQuery` cause it's currently mutable.

```php
->withQuery('total', function ($filteredQuery) {
    return (clone $filteredQuery)->sum('Amount');
})
```

**Comment by TheGeekyM** [comment]
I already tried it before but it didn't work, It works correctly only on the page the first page.

the query I get on the first page is:
`select sum([Amount]) as aggregate from [Transaction]`

and in other pages I got a query like this:
`select * from (select sum([Amount]) as aggregate , row_number() over (order by (select 0)) as row_num from [Transaction]) as temp_table where row_num between 101 and 150 order by row_num`

but can I listen to all events that are fired except paging? I think it will solve the problem if there is another one

**Comment by yajra** [comment]
I see, so the problem is paging are getting applied when doing the sum? Maybe try removing the paging applied on query before applying the sum? Is it possible to remove the limit applied on query? Will dig further when I got the chance.

**Comment by fatihmehmetkiris** [comment]
I have the same issue. Is there any solution for this after 2 years?

**Comment by tcagkansokmen** [comment]
any solve on that?

got same problem.

**Comment by DannyV90** [comment]
Any Update?? I got the same issue.

**Comment by mustafaarslan1** [comment]
@yajra did you got any chance to find solution. i have same problem

**Comment by salmansamkhan** [comment]
There is a work around you guys can do. May be helpful for someone.  Compare the start if its 0 then return else return static value and in front check that condition.
![image](https://user-images.githubusercontent.com/23137785/129442948-9625cdfd-8739-4ff3-a5ff-b6ba8c592b12.png)

`"fnDrawCallback": function( oSettings ) {
                if( oSettings.json.total != 'no' ) {
                    $('#total_donation').text(oSettings.json.total);
                }
            },`

**Comment by DannyV90** [comment]
> There is a work around you guys can do. May be helpful for someone. Compare the start if its 0 then return else return static value and in front check that condition.
> ![image](https://user-images.githubusercontent.com/23137785/129442948-9625cdfd-8739-4ff3-a5ff-b6ba8c592b12.png)
> 
> `"fnDrawCallback": function( oSettings ) { if( oSettings.json.total != 'no' ) { $('#total_donation').text(oSettings.json.total); } },`

This seems a great workaround! It works perfectly.
Really thanks man!!!!

 If someone is using datatables as service, in method dataTable has to use 
`$startNo = $this->request->input("start")`
because it's an inherited property.

**Comment by Jankec** [comment]
This works fine for me:
->withQuery('total', function ($filteredQuery) {
    return (clone $filteredQuery)->offset(0)->sum('Amount');
})

just add ->offset(0)
