### ISSUE TITLE
Laravel-datatables oracle database

### ISSUE THREAD

**Issue by 110010100** [yajra/laravel-datatables#2233]
### Summary of problem or feature request

Hello, 
I tried to use Laravel-Datatable with an Oracle database, but I have an error Datatables warning.

When I try with a mysql database, It's works !

But I want Oracle access ...

#### .env
    APP_NAME="Requêtes SIRH Test"
    APP_ENV=local
    APP_KEY=APP_KEY
    APP_DEBUG=true
    APP_URL=http://sirht.cd03.fr:8080/

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=127.0.0.1
    DB_PORT=3306
    DB_DATABASE=ads
    DB_USERNAME=root
    DB_PASSWORD=

    DB_CONNECTION_ADS=oracle_ADS
    DB_HOST_ADS=
    DB_PORT_ADS=myport
    DB_TNS_ADS="(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = myserver.local)(PORT = myport)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = myservicename) ) )"
    DB_DATABASE_ADS=DB_DATABASE
    DB_USERNAME_ADS=DB_USERNAME
    DB_PASSWORD_ADS=DB_PASSWORD

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_DRIVER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

#### config/oracle.php

    <?php

    return [
        'oracle_ADS' => [
            'driver'         => 'oracle',
            'tns'            => env('DB_TNS_ADS', ''),
            'host'           => env('DB_HOST_ADS', ''),
            'port'           => env('DB_PORT_ADS', ''),
            'database'       => env('DB_DATABASE_ADS', ''),
            'username'       => env('DB_USERNAME_ADS', ''),
            'password'       => env('DB_PASSWORD_ADS', ''),
            'charset'        => env('DB_CHARSET_ADS', 'AL32UTF8'),
            'prefix'         => env('DB_PREFIX_ADS', ''),
            'prefix_schema'  => env('DB_SCHEMA_PREFIX_ADS', ''),
            'edition'        => env('DB_EDITION_ADS', 'ora$base'),
            'server_version' => env('DB_SERVER_VERSION_ADS', '11g'),
        ],
    ];

####  Controller 

    <?php

    namespace App\Http\Controllers;

    use Datatables;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\DB;

    class UsersController extends Controller
    {
        public function index()
        {
            return view('users');
        }

        public function userslist()
        {

            // Permet d'obtenir les informations gobales des agents
            $info_agent_globales = DB::connection('oracle_ADS')
                ->table('AGENT_POSTE_R')
                ->join('AGENT', 'AGENT_POSTE_R.MATRICULE', '=', 'AGENT.MATRICULE')
                ->join('POSTE', 'AGENT_POSTE_R.CODE_POSTE', '=', 'POSTE.CODE_POSTE')
                ->select('AGENT_POSTE_R.MATRICULE_ETABLISSEMENT', 'AGENT_POSTE_R.ETABLISSEMENT', 'AGENT_POSTE_R.LIB_ETABLISSEMENT', 'AGENT.MATRICULE', 'AGENT.TITRE', 'AGENT.NOMPATRO', 'AGENT.NOMUSAGE', 'AGENT.PRENOM', 'AGENT.EMAIL', 'AGENT.DATE_NAISSANCE', 'AGENT.LOGON', 'AGENT_POSTE_R.CODE_EVENEMENT', 'AGENT_POSTE_R.LIB_EVENEMENT', 'AGENT_POSTE_R.DATE_EFFET', 'AGENT_POSTE_R.DATE_EFFET_FIN', 'AGENT_POSTE_R.CODE_POSITION_ADM', 'AGENT_POSTE_R.LIB_POSITION_ADM', 'AGENT_POSTE_R.CODE_QUALITE_EMPLOI', 'AGENT_POSTE_R.LIB_QUALITE_EMPLOI', 'AGENT_POSTE_R.CODE_FILIERE', 'AGENT_POSTE_R.LIB_FILIERE', 'AGENT_POSTE_R.CODE_CADRE_EMPLOI', 'AGENT_POSTE_R.LIB_CADRE_EMPLOI', 'AGENT_POSTE_R.CODE_GRADE', 'AGENT_POSTE_R.LIB_GRADE', 'AGENT_POSTE_R.CODE_ECHELON', 'AGENT_POSTE_R.LIB_ECHELON', 'AGENT_POSTE_R.CODE_ECHELLE', 'AGENT_POSTE_R.LIB_ECHELLE', 'AGENT_POSTE_R.CODE_DIRECTION_DG', 'AGENT_POSTE_R.LIB_DIRECTION_DG', 'AGENT_POSTE_R.CODE_DIRECTION_DGA', 'AGENT_POSTE_R.LIB_DIRECTION_DGA', 'AGENT_POSTE_R.CODE_DIRECTION', 'AGENT_POSTE_R.LIB_DIRECTION', 'AGENT_POSTE_R.LIB_COURT_DIRECTION', 'AGENT_POSTE_R.CODE_POLE', 'AGENT_POSTE_R.LIB_POLE', 'AGENT_POSTE_R.CODE_SERVICE', 'AGENT_POSTE_R.LIB_SERVICE', 'AGENT_POSTE_R.CODE_UNITE_COMPTABLE', 'AGENT_POSTE_R.LIB_UNITE_COMPTABLE', 'POSTE.CODE_POSTE', 'POSTE.LIB_POSTE', 'POSTE.ANCIEN_CODE_POSTE', 'AGENT_POSTE_R.CODE_LIEU_TRAVAIL', 'AGENT_POSTE_R.LIEU_TRAVAIL_ADR1', 'AGENT_POSTE_R.LIEU_TRAVAIL_ADR2', 'AGENT_POSTE_R.LIEU_TRAVAIL_ADR3', 'AGENT_POSTE_R.LIEU_TRAVAIL_ADR4', 'AGENT_POSTE_R.LIEU_TRAVAIL_CP', 'AGENT_POSTE_R.LIEU_TRAVAIL_VILLE', 'AGENT_POSTE_R.MATRICULE_HIERARCHIQUE', 'AGENT_POSTE_R.TITRE_HIERARCHIQUE', 'AGENT_POSTE_R.NOMUSAGE_HIERARCHIQUE', 'AGENT_POSTE_R.PRENOM_HIERARCHIQUE', 'AGENT_POSTE_R.CODE_POSTE_HIERARCHIQUE', 'AGENT_POSTE_R.LIB_POSTE_HIERARCHIQUE', 'AGENT_POSTE_R.ANCIEN_CODE_POSTE_HIERARCHIQUE', 'AGENT.TRAIN_PAIE', 'AGENT.LIB_TRAIN_PAIE', 'AGENT.TRAIN_CARRIERE', 'AGENT.LIB_TRAIN_CARRIERE', 'AGENT_POSTE_R.CODE_DUREE_TRAVAIL', 'AGENT_POSTE_R.LIB_DUREE_TRAVAIL', 'AGENT_POSTE_R.TAUX_EMPLOI', 'AGENT_POSTE_R.CODE_FONCTION_BONIFIANTE', 'AGENT_POSTE_R.LIB_FONCTION_BONIFIANTE', 'AGENT_POSTE_R.NBRE_POINT_NBI', 'AGENT_POSTE_R.DATE_ENTREE_COLLECTIVITE', 'AGENT_POSTE_R.DATE_ENTREE_FP', 'AGENT_POSTE_R.DATE_ENTREE_FILIERE', 'AGENT_POSTE_R.DATE_ENTREE_CADRE_EMPLOI', 'AGENT_POSTE_R.DATE_ENTREE_GRADE', 'AGENT_POSTE_R.DATE_ENTREE_ECHELON', 'AGENT_POSTE_R.DATE_STAGIAIRISATION', 'AGENT_POSTE_R.DATE_TITULARISATION', 'AGENT_POSTE_R.INDICE_BRUT', 'AGENT_POSTE_R.INDICE_REMUNERATION', 'AGENT_POSTE_R.INDICE_MAJORE', 'AGENT_POSTE_R.INDICE_HORS_ECHELLE', 'AGENT_POSTE_R.CODE_TRAIN_VISITE', 'AGENT_POSTE_R.LIB_TRAIN_VISITE', 'AGENT_POSTE_R.CODE_TYPE_OCCUP_POSTE', 'AGENT_POSTE_R.LIB_TYPE_OCCUP_POSTE', 'AGENT_POSTE_R.CODE_CATEGORIE', 'AGENT_POSTE_R.LIB_CATEGORIE');
            return datatables()->of($info_agent_globales)
                ->make(true);
        }
    }

####  View

    <!DOCTYPE html>

    <html lang="fr">
    <head>
    <title>Infos Agents</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">  
    <link  href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    </head>
      <body>
         <div class="container">
               <h2>Infos Agents</h2>
            <table class="table table-bordered" id="laravel_datatable">
               <thead>
                    <tr>
                        <th>MATRICULE_ETABLISSEMENT</th>
                        <th>ETABLISSEMENT</th>
                        <th>LIB_ETABLISSEMENT</th>
                        <th>MATRICULE</th>
                        <th>TITRE</th>
                        <th>NOMPATRO</th>
                        <th>NOMUSAGE</th>
                        <th>PRENOM</th>
                        <th>EMAIL</th>
                        <th>DATE_NAISSANCE</th>
                        <th>LOGON</th>
                        <th>CODE_EVENEMENT</th>
                        <th>LIB_EVENEMENT</th>
                        <th>DATE_EFFET</th>
                        <th>DATE_EFFET_FIN</th>
                        <th>CODE_POSITION_ADM</th>
                        <th>LIB_POSITION_ADM</th>
                        <th>CODE_QUALITE_EMPLOI</th>
                        <th>LIB_QUALITE_EMPLOI</th>
                        <th>CODE_FILIERE</th>
                        <th>LIB_FILIERE</th>
                        <th>CODE_CADRE_EMPLOI</th>
                        <th>LIB_CADRE_EMPLOI</th>
                        <th>CODE_GRADE</th>
                        <th>LIB_GRADE</th>
                        <th>CODE_ECHELON</th>
                        <th>LIB_ECHELON</th>
                        <th>CODE_ECHELLE</th>
                        <th>LIB_ECHELLE</th>
                        <th>CODE_DIRECTION_DG</th>
                        <th>LIB_DIRECTION_DG</th>
                        <th>CODE_DIRECTION_DGA</th>
                        <th>LIB_DIRECTION_DGA</th>
                        <th>CODE_DIRECTION</th>
                        <th>LIB_DIRECTION</th>
                        <th>LIB_COURT_DIRECTION</th>
                        <th>CODE_POLE</th>
                        <th>LIB_POLE</th>
                        <th>CODE_SERVICE</th>
                        <th>LIB_SERVICE</th>
                        <th>CODE_UNITE_COMPTABLE</th>
                        <th>LIB_UNITE_COMPTABLE</th>
                        <th>CODE_POSTE</th>
                        <th>LIB_POSTE</th>
                        <th>ANCIEN_CODE_POSTE</th>
                        <th>CODE_LIEU_TRAVAIL</th>
                        <th>LIEU_TRAVAIL_ADR1</th>
                        <th>LIEU_TRAVAIL_ADR2</th>
                        <th>LIEU_TRAVAIL_ADR3</th>
                        <th>LIEU_TRAVAIL_ADR4</th>
                        <th>LIEU_TRAVAIL_CP</th>
                        <th>LIEU_TRAVAIL_VILLE</th>
                        <th>MATRICULE_HIERARCHIQUE</th>
                        <th>TITRE_HIERARCHIQUE</th>
                        <th>NOMUSAGE_HIERARCHIQUE</th>
                        <th>PRENOM_HIERARCHIQUE</th>
                        <th>CODE_POSTE_HIERARCHIQUE</th>
                        <th>LIB_POSTE_HIERARCHIQUE</th>
                        <th>ANCIEN_CODE_POSTE_HIERARCHIQUE</th>
                        <th>TRAIN_PAIE</th>
                        <th>LIB_TRAIN_PAIE</th>
                        <th>TRAIN_CARRIERE</th>
                        <th>LIB_TRAIN_CARRIERE</th>
                        <th>CODE_DUREE_TRAVAIL</th>
                        <th>LIB_DUREE_TRAVAIL</th>
                        <th>TAUX_EMPLOI</th>
                        <th>CODE_FONCTION_BONIFIANTE</th>
                        <th>LIB_FONCTION_BONIFIANTE</th>
                        <th>NBRE_POINT_NBI</th>
                        <th>DATE_ENTREE_COLLECTIVITE</th>
                        <th>DATE_ENTREE_FP</th>
                        <th>DATE_ENTREE_FILIERE</th>
                        <th>DATE_ENTREE_CADRE_EMPLOI</th>
                        <th>DATE_ENTREE_GRADE</th>
                        <th>DATE_ENTREE_ECHELON</th>
                        <th>DATE_STAGIAIRISATION</th>
                        <th>DATE_TITULARISATION</th>
                        <th>INDICE_BRUT</th>
                        <th>INDICE_REMUNERATION</th>
                        <th>INDICE_MAJORE</th>
                        <th>INDICE_HORS_ECHELLE</th>
                        <th>CODE_TRAIN_VISITE</th>
                        <th>LIB_TRAIN_VISITE</th>
                        <th>CODE_TYPE_OCCUP_POSTE</th>
                        <th>LIB_TYPE_OCCUP_POSTE</th>
                        <th>CODE_CATEGORIE</th>
                        <th>LIB_CATEGORIE</th>
                    </tr>
               </thead>
            </table>
         </div>
        <script>
        $(document).ready( function () {
            $('#laravel_datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ url('users-list') }}",
                    type: 'POST',
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                },
                columns: [
                            { data: 'MATRICULE_ETABLISSEMENT', name: 'MATRICULE_ETABLISSEMENT' },
                            { data: 'ETABLISSEMENT', name: 'ETABLISSEMENT' },
                            { data: 'LIB_ETABLISSEMENT', name: 'LIB_ETABLISSEMENT' },
                            { data: 'MATRICULE', name: 'MATRICULE' },
                            { data: 'TITRE', name: 'TITRE' },
                            { data: 'NOMPATRO', name: 'NOMPATRO' },
                            { data: 'NOMUSAGE', name: 'NOMUSAGE' },
                            { data: 'PRENOM', name: 'PRENOM' },
                            { data: 'EMAIL', name: 'EMAIL' },
                            { data: 'DATE_NAISSANCE', name: 'DATE_NAISSANCE' },
                            { data: 'LOGON', name: 'LOGON' },
                            { data: 'CODE_EVENEMENT', name: 'CODE_EVENEMENT' },
                            { data: 'LIB_EVENEMENT', name: 'LIB_EVENEMENT' },
                            { data: 'DATE_EFFET', name: 'DATE_EFFET' },
                            { data: 'DATE_EFFET_FIN', name: 'DATE_EFFET_FIN' },
                            { data: 'CODE_POSITION_ADM', name: 'CODE_POSITION_ADM' },
                            { data: 'LIB_POSITION_ADM', name: 'LIB_POSITION_ADM' },
                            { data: 'CODE_QUALITE_EMPLOI', name: 'CODE_QUALITE_EMPLOI' },
                            { data: 'LIB_QUALITE_EMPLOI', name: 'LIB_QUALITE_EMPLOI' },
                            { data: 'CODE_FILIERE', name: 'CODE_FILIERE' },
                            { data: 'LIB_FILIERE', name: 'LIB_FILIERE' },
                            { data: 'CODE_CADRE_EMPLOI', name: 'CODE_CADRE_EMPLOI' },
                            { data: 'LIB_CADRE_EMPLOI', name: 'LIB_CADRE_EMPLOI' },
                            { data: 'CODE_GRADE', name: 'CODE_GRADE' },
                            { data: 'LIB_GRADE', name: 'LIB_GRADE' },
                            { data: 'CODE_ECHELON', name: 'CODE_ECHELON' },
                            { data: 'LIB_ECHELON', name: 'LIB_ECHELON' },
                            { data: 'CODE_ECHELLE', name: 'CODE_ECHELLE' },
                            { data: 'LIB_ECHELLE', name: 'LIB_ECHELLE' },
                            { data: 'CODE_DIRECTION_DG', name: 'CODE_DIRECTION_DG' },
                            { data: 'LIB_DIRECTION_DG', name: 'LIB_DIRECTION_DG' },
                            { data: 'CODE_DIRECTION_DGA', name: 'CODE_DIRECTION_DGA' },
                            { data: 'LIB_DIRECTION_DGA', name: 'LIB_DIRECTION_DGA' },
                            { data: 'CODE_DIRECTION', name: 'CODE_DIRECTION' },
                            { data: 'LIB_DIRECTION', name: 'LIB_DIRECTION' },
                            { data: 'LIB_COURT_DIRECTION', name: 'LIB_COURT_DIRECTION' },
                            { data: 'CODE_POLE', name: 'CODE_POLE' },
                            { data: 'LIB_POLE', name: 'LIB_POLE' },
                            { data: 'CODE_SERVICE', name: 'CODE_SERVICE' },
                            { data: 'LIB_SERVICE', name: 'LIB_SERVICE' },
                            { data: 'CODE_UNITE_COMPTABLE', name: 'CODE_UNITE_COMPTABLE' },
                            { data: 'LIB_UNITE_COMPTABLE', name: 'LIB_UNITE_COMPTABLE' },
                            { data: 'CODE_POSTE', name: 'CODE_POSTE' },
                            { data: 'LIB_POSTE', name: 'LIB_POSTE' },
                            { data: 'ANCIEN_CODE_POSTE', name: 'ANCIEN_CODE_POSTE' },
                            { data: 'CODE_LIEU_TRAVAIL', name: 'CODE_LIEU_TRAVAIL' },
                            { data: 'LIEU_TRAVAIL_ADR1', name: 'LIEU_TRAVAIL_ADR1' },
                            { data: 'LIEU_TRAVAIL_ADR2', name: 'LIEU_TRAVAIL_ADR2' },
                            { data: 'LIEU_TRAVAIL_ADR3', name: 'LIEU_TRAVAIL_ADR3' },
                            { data: 'LIEU_TRAVAIL_ADR4', name: 'LIEU_TRAVAIL_ADR4' },
                            { data: 'LIEU_TRAVAIL_CP', name: 'LIEU_TRAVAIL_CP' },
                            { data: 'LIEU_TRAVAIL_VILLE', name: 'LIEU_TRAVAIL_VILLE' },
                            { data: 'MATRICULE_HIERARCHIQUE', name: 'MATRICULE_HIERARCHIQUE' },
                            { data: 'TITRE_HIERARCHIQUE', name: 'TITRE_HIERARCHIQUE' },
                            { data: 'NOMUSAGE_HIERARCHIQUE', name: 'NOMUSAGE_HIERARCHIQUE' },
                            { data: 'PRENOM_HIERARCHIQUE', name: 'PRENOM_HIERARCHIQUE' },
                            { data: 'CODE_POSTE_HIERARCHIQUE', name: 'CODE_POSTE_HIERARCHIQUE' },
                            { data: 'LIB_POSTE_HIERARCHIQUE', name: 'LIB_POSTE_HIERARCHIQUE' },
                            { data: 'ANCIEN_CODE_POSTE_HIERARCHIQUE', name: 'ANCIEN_CODE_POSTE_HIERARCHIQUE' },
                            { data: 'TRAIN_PAIE', name: 'TRAIN_PAIE' },
                            { data: 'LIB_TRAIN_PAIE', name: 'LIB_TRAIN_PAIE' },
                            { data: 'TRAIN_CARRIERE', name: 'TRAIN_CARRIERE' },
                            { data: 'LIB_TRAIN_CARRIERE', name: 'LIB_TRAIN_CARRIERE' },
                            { data: 'CODE_DUREE_TRAVAIL', name: 'CODE_DUREE_TRAVAIL' },
                            { data: 'LIB_DUREE_TRAVAIL', name: 'LIB_DUREE_TRAVAIL' },
                            { data: 'TAUX_EMPLOI', name: 'TAUX_EMPLOI' },
                            { data: 'CODE_FONCTION_BONIFIANTE', name: 'CODE_FONCTION_BONIFIANTE' },
                            { data: 'LIB_FONCTION_BONIFIANTE', name: 'LIB_FONCTION_BONIFIANTE' },
                            { data: 'NBRE_POINT_NBI', name: 'NBRE_POINT_NBI' },
                            { data: 'DATE_ENTREE_COLLECTIVITE', name: 'DATE_ENTREE_COLLECTIVITE' },
                            { data: 'DATE_ENTREE_FP', name: 'DATE_ENTREE_FP' },
                            { data: 'DATE_ENTREE_FILIERE', name: 'DATE_ENTREE_FILIERE' },
                            { data: 'DATE_ENTREE_CADRE_EMPLOI', name: 'DATE_ENTREE_CADRE_EMPLOI' },
                            { data: 'DATE_ENTREE_GRADE', name: 'DATE_ENTREE_GRADE' },
                            { data: 'DATE_ENTREE_ECHELON', name: 'DATE_ENTREE_ECHELON' },
                            { data: 'DATE_STAGIAIRISATION', name: 'DATE_STAGIAIRISATION' },
                            { data: 'DATE_TITULARISATION', name: 'DATE_TITULARISATION' },
                            { data: 'INDICE_BRUT', name: 'INDICE_BRUT' },
                            { data: 'INDICE_REMUNERATION', name: 'INDICE_REMUNERATION' },
                            { data: 'INDICE_MAJORE', name: 'INDICE_MAJORE' },
                            { data: 'INDICE_HORS_ECHELLE', name: 'INDICE_HORS_ECHELLE' },
                            { data: 'CODE_TRAIN_VISITE', name: 'CODE_TRAIN_VISITE' },
                            { data: 'LIB_TRAIN_VISITE', name: 'LIB_TRAIN_VISITE' },
                            { data: 'CODE_TYPE_OCCUP_POSTE', name: 'CODE_TYPE_OCCUP_POSTE' },
                            { data: 'LIB_TYPE_OCCUP_POSTE', name: 'LIB_TYPE_OCCUP_POSTE' },
                            { data: 'CODE_CATEGORIE', name: 'CODE_CATEGORIE' },
                            { data: 'LIB_CATEGORIE', name: 'LIB_CATEGORIE' },
                            ]
            });
        });
    </script>
</body>
</html>

#### Route

    Route::get('/users',[
        'as' => 'users.index',
        'uses' => 'UsersController@index'
    ]);

    Route::post('/users-list',[
        'as' => 'users.userslist',
        'uses' => 'UsersController@userslist'
    ]);

### System details

- Operating System : Windows 10 Pro 1803
- PHP Version : 7.3.10
- Laravel Version : 6.4
- Laravel-Datatables Version : 9.7.1

Thanks for your help !

**Comment by yajra** [comment]
What does the warning / error states? Can you please provide the error log. Most of my projects are in Oracle too so I am pretty sure this would work.

**Comment by 110010100** [comment]
I found the problem ... it was a problem with the database ...
Sorry for the inconvenience ...

Now, in the view :

Instead of : 

> columns: [
>                         { data: 'MATRICULE_ETABLISSEMENT', name: 'MATRICULE_ETABLISSEMENT' },
>                         { data: 'ETABLISSEMENT', name: 'ETABLISSEMENT' },
>                         ......

I put :

> columns: [
>                          { data: 'matricule_etablissement', name: 'MATRICULE_ETABLISSEMENT' },
>                          { data: 'etablissement', name: 'ETABLISSEMENT' },
>                         ......

Thanks for your help
