### ISSUE TITLE
Unescaped unicode  is not working in response (even with config/Datatables.php done)

### ISSUE THREAD

**Issue by Benoit75** [yajra/laravel-datatables#2237]
### Summary of problem or feature request
Hello, 
Thank's for your work !

I'm having same trouble as this issue  [Unescaped unicode in response #1034](https://github.com/yajra/laravel-datatables/issues/1034)

My Json data are not in UTF8 char. 
(ex : it's  become it& #039;s)
Trouble is only with Databases classes (JSON utf8 work's fine in another class)

I try to config vendor\yajra\laravel-datatables-oracle\src\config\datatables.php

`    'json'           => [
         'header'  => ['Content-Type' => 'application/json;charset=utf8'],
        'options' => JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ,
    ],
`
or 
`     'header'  => ['Content-Type' => 'text/html; charset=UTF-8'],`

but no success (the header change but not the JSON

The workaround is to use ->rawColumns(). It's working but it's not very convenient :  i have to think about each column... 

Any thoughts ?

### Code snippet of problem
My Controler
`    $regie = Regie::select([
        'id', 
        'libelle',
        'web']);
       return Datatables::of($regie)->make(true);`

My workaround 
`return Datatables::of($regie)->rawColumns(['libelle'])->make(true);`

### System details
yajra/laravel-datatables-buttons            v4.8.0     
yajra/laravel-datatables-editor             v1.17.1    
yajra/laravel-datatables-html               v4.19.4   
yajra/laravel-datatables-oracle             v9.7.1
Editor 1.9.2
Database 1.10.20
Php 7.2.3
Laravel 6.5
Windows 10

**Comment by yajra** [comment]
Need help on this one as I haven't actually had the chance to work with non UTF8 char. But will try to check this further if I got the chance.
