### ISSUE TITLE
Sorting on added attributes of models

### ISSUE THREAD

**Issue by WimDeMeester** [yajra/laravel-datatables#2241]
### Summary of problem or feature request

I have a model and I want to add some columns. The calculations I need to do are complicated and it is impossible to add these columns by using database queries to add them. I can add the columns by calculating them using another php class and adding the columns as attributes. I know that the calculations can take some time, but that is not a problem here. When I do this, the new columns appear in my datatable (I'm using datatables as a service), but sorting does not work... Is there a way to make the sorting work?

### System details

- Operating System
Homestead (Ubuntu 18.04.3)
- PHP Version
7.3.9
- Laravel Version
6.5.0
- Laravel-Datatables Version
1.5.0 (latest version)

**Comment by yajra** [comment]
Unfortunately, it's not possible unless you convert the computations to query level.

On the other hand, you may try using collection but do note that it has performance issue when used in large datasets.

**Comment by WimDeMeester** [comment]
I will investigate the use of collections.
