### ISSUE TITLE
button plugin can't installed

### ISSUE THREAD

**Issue by marcelloinfoweb** [yajra/laravel-datatables#2242]
### Summary of problem or feature request

I can't install the button plugin, I started the project in laravel version 6.2, and yesterday I updated both the framework and the plugin, yet it shows me the same message, and I can't downgrade, I need to finish the company project.

### Code snippet of problem

```bash
 composer require yajra/laravel-datatables-buttons:^3.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.5.0
    - Conclusion: don't install laravel/framework v6.5.0

```

### System details

- Operating System Clear Linux
- PHP Version 7.3
- Laravel Version 6.5.0
- Laravel-Datatables Version 9.7

**Comment by yajra** [comment]
Please use `composer require yajra/laravel-datatables-buttons` to install the latest version available.

**Comment by M-H-Abdelfadeil** [comment]
@yajra 
Thank you very much the solution was to use  composer require yajra/laravel-datatables-buttons
