### ISSUE TITLE
Cannot go to other page when using response-resource.

### ISSUE THREAD

**Issue by oroalej** [yajra/laravel-datatables#2244]
### Summary of problem or feature request

Datatables cannot render the pagination when using [response-resource](https://yajrabox.com/docs/laravel-datatables/master/response-resource). It only get the first result and no way to go to another page.

### Code snippet of problem

```
$collections = SomeModel::paginate(10);

return Datatables::of(
  SomeResource::collection($collections)
)->toJson();
```

### System details

- Operating System All OS
- PHP Version 7.3.9
- Laravel Version: 5.5.45
- Laravel-Datatables Version: 8.13.5

**Comment by grafikkaos** [comment]
I would like to bump this as well.  I am also seeing the same issue.  Using the response-resource only returns the first 10 results and complete ignores everything else  and the pagination buttons are disabled.
