### ISSUE TITLE
Documentation links broken (http://www.yajrabox.com)

### ISSUE THREAD

**Issue by zero0n3** [yajra/laravel-datatables#2249]
### Summary of problem or feature request

http://www.yajrabox.com is down

**Comment by kitro** [comment]
https://github.com/yajra/laravel-datatables/issues/2218#issuecomment-544988948

**Comment by zero0n3** [comment]
FYI
Actually, you can surf documentation on github opening md files individually (without a graphical interface like yajrabox.com)  at https://github.com/yajra/laravel-datatables-docs
