### ISSUE TITLE
data table documents

### ISSUE THREAD

**Issue by kazemimorteza68** [yajra/laravel-datatables#2252]
Hi
Laravel data table document is unavailable.
where i can found laravel data table Documents?
below web site is damaged and can not be access.
http://yajrabox.com/docs/laravel-datatables
Thanks

**Comment by mush60** [comment]
u can see documentation in the following link bro 

https://github.com/yajra/laravel-datatables-docs

**Comment by mush60** [comment]
> Hi
> Laravel data table document is unavailable.
> where i can found laravel data table Documents?
> below web site is damaged and can not be access.
> http://yajrabox.com/docs/laravel-datatables
> Thanks
here :
https://github.com/yajra/laravel-datatables-docs

**Comment by mush60** [comment]
look here 
https://github.com/yajra/laravel-datatables-docs
this is the github page, the backs up of the documentation in .md file
