### ISSUE TITLE
Documentation site does not work

### ISSUE THREAD

**Issue by DmitrySur** [yajra/laravel-datatables#2257]
The site does not work with documentation and examples https://yajrabox.com, tell me where you can get it please

**Comment by federicogodan** [comment]
Im using wayback until they fix it:
https://web.archive.org/web/20190429144709/http://yajrabox.com/docs/laravel-datatables/master

**Comment by DmitrySur** [comment]
> 
> 
> Im using wayback until they fix it:
> https://web.archive.org/web/20190429144709/http://yajrabox.com/docs/laravel-datatables/master
> 
> Edit:
> you can visit the issue #2252

thx

**Comment by bahjaat** [comment]
See: https://github.com/yajra/laravel-datatables-docs

**Comment by yajra** [comment]
#2223 thanks!
