### ISSUE TITLE
How to check if dataTable service has records

### ISSUE THREAD

**Issue by thewebartisan7** [yajra/laravel-datatables#2259]
I would like to show a blank / empty page when datatable service has not records, instaed of the empty table.

How I can check before calling $dataTable->table(...) in my view? Or before $dataTable->render(...)

There is something like $dataTable->isEmpty() ?

Thanks

**Comment by yajra** [comment]
Unfortunately, something like this is not yet available. You would have to do a manual query to check if the table is empty.

**Comment by thewebartisan7** [comment]
Add it please. Thanks

**Comment by ajayfroiden** [comment]
Is this added?

**Comment by thewebartisan7** [comment]
I solve this with below code, is not perfect but works:

```js

            if($('.dataTables_empty').length) {
                $('.dataTables_paginate, .dataTables_length, .dataTables_info, .dataTable thead').hide();
            }

```
