### ISSUE TITLE
Columns created by addColumn are unsearchable and unsortable

### ISSUE THREAD

**Issue by chrisbeaver** [yajra/laravel-datatables#226]
return Datatables::of($services)
        ->addColumn('invoice_numbers', function($service) {
            $item = Link\Service::find($service->id);
            return $item->listInvoiceNumbers();
        })
       ->addColumn('payments', function($service) {
        	$item = Link\Service::find($service->id);
        	return $item->totalPayments();
        })
        ->addColumn('edit', function($service) {
        	return '&lt;a class="btn btn-default" href="/record/'.$service->id.'/edit"&gtEdit&lt;/a&gt;';
        })
        ->make(true);

I'm using DB:: calls so I can search and sort my relationships. However, two columns of the table use Model methods to create the data in the cells. I don't believe this data is filtered through the DataTables quick search filter because it's not returned from a SQL query, but rather built on the fly. Is there a way to make this data searchable in the DataTables quick search box?

**Comment by yajra** [comment]
Unfortunately, it's not possible atm to search/sort on added columns since it's not part of the query.

**Comment by chrisbeaver** [comment]
Would it be possible to add a callback function to the query that appends data to the query string?

**Comment by yajra** [comment]
Yes, it's possible using `addSelect` or `addSelectRaw` method of query builder. This way, you might be able to do search/sorting since it's now part of the query. You can add a sub-query too using `addSelect` that calculates the total payments like on your example. http://laravel.com/docs/5.1/queries#selects

**Comment by llioor** [comment]
ohh... Do you think it will be done sometimes?

**Comment by yajra** [comment]
Yes, `addSelect` methods are readily available and is built-in with Laravel. It's a more advance way of querying with Laravel so you may need to do some researching.

**Comment by llioor** [comment]
@chrisbeaver I think I have a solution for you...
Tell me, how are you selecting you "$services" parameter?

**Comment by chrisbeaver** [comment]
$services = DB::table('services')
    	->leftJoin('patients', 'patients.id','=','services.patient_id')
    	->leftJoin('surgical_assistants', 'surgical_assistants.id','=','services.surgical_assistant_id')
    	->leftJoin('hospitals', 'hospitals.id','=','services.hospital_id')
    	->leftJoin('specialties', 'specialties.id','=','services.specialty_id')
    	->leftJoin('insurance_providers', 'insurance_providers.id','=','services.insurance_provider_id')
    	// ->leftJoin('payments', 'billings_id','=','billings.id')
    	->leftJoin('physicians', 'physicians.id','=','services.physician_id')
    	->select(['services.id', 'services.service_date', 'patients.name as patient', 'surgical_assistants.name as surgical_assistant', 'hospitals.name as hospital', 'specialties.name as specialty', 'insurance_providers.name as insurance_provider',  'physicians.name as physician']);
    
    return Datatables::of($services)
        ->addColumn('invoice_numbers', function($service) {
            $item = Link\Service::find($service->id);
            return $item->listInvoiceNumbers();
        })
        ->addColumn('payments', function($service) {
        	$item = Link\Service::find($service->id);
        	return $item->totalPayments();
        })
        ->addColumn('edit', function($service) {
        	return '<a class="btn btn-default" href="/record/'.$service->id.'/edit">Edit</a>';
        })
        ->make(true);

**Comment by dasuchin** [comment]
@yajra if one of the columns is in the select, but I'm overriding how it returns with `addColumn`, is it still not able to sort? The documentation site is down so I can't look that much into it, but I assumed that if my `name` column is in the query select, even if I override what it returns with `addColumn` (doing that so I can some extra functionality to it) then it would still sort it?

**Comment by yajra** [comment]
Closing issue since addColumn are indeed unsearchable and unsortable since it's not part of the query. Thanks!
