### ISSUE TITLE
How to sort on a value store in a json field ?

### ISSUE THREAD

**Issue by invaders-xx** [yajra/laravel-datatables#2262]
### Summary of problem or feature request
Hello,

I will need some help in order to sort a datatable based on json field column. Is there any way to do this ?

Many thanks in advance,

David

- Operating System : Ubuntu
- PHP Version 7.3
- Laravel Version 5.7
- Laravel-Datatables Version 8

**Comment by yajra** [comment]
I haven't personally tried this but I think using `orderColumn` would do the trick. Maybe something like:

```php
->orderColumn('jsonKey', function($query, $dir) {
    $query->orderBy('json->key', $dir);
})
```

See https://github.com/yajra/laravel-datatables-docs/blob/master/order-column.md for ref.
