### ISSUE TITLE
https://yajrabox.com not accessible

### ISSUE THREAD

**Issue by SanaAsghar92** [yajra/laravel-datatables#2265]
https://yajrabox.com/docs/laravel-oci8/master/installation
is not accessible

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by ali997** [comment]
Any word on this? Still not accessible.

**Comment by zack6849** [comment]
See #2223 ,

https://github.com/yajra/laravel-datatables-docs
https://laravel-datatables-docs.netlify.com/
