### ISSUE TITLE
PhpStorm  Unhandled \Exception for "of"

### ISSUE THREAD

**Issue by asadi20** [yajra/laravel-datatables#2269]
Hi yajra
in Phpstorm when using 
return DataTables::of($posts)->some_code->make(true);
everything is work fine but phpstorm say Unhandled \Exception... for "of" 
please solve this
----------------------------------
![error_exception](https://user-images.githubusercontent.com/24497450/71396044-c8a71b80-262d-11ea-8686-0320240f6c20.png)
----------------------------------------
Phpstorm version 2018.3
Datatable 9.x
laravel 6.8

**Comment by yajra** [comment]
It is intended behavior when using the factory `::of`.  If you want that exception removed, you need to specify which builder you are going to use.

```php
DataTables::eloquent($posts)->some_code->make(true);
DataTables::collection($posts)->some_code->make(true);
DataTables::query($posts)->some_code->make(true);
```
