### ISSUE TITLE
Sorting Has One Relationship Column

### ISSUE THREAD

**Issue by gustavo9810** [yajra/laravel-datatables#2271]
### Summary of problem or feature request

**I'm using [this official example](https://github.com/yajra/laravel-datatables-demo/blob/master/resources/views/datatables/relation/has-one.blade.php). The problem is, when I try to sort the rows by the `onePost.title ` (has one relationship) column it doesn't work.**

### Code snippet of problem and my own example

I have a table called Orders, and another table called statuses, which contains every status of the related order. Ex:

    Order 01 has status 01 - 10/12/2019, status 02 - 12/12/2019, status 03 - 16/12/2019
    Order 02 has status 01 - 20/12/2019, status 02 - 21/12/2019, status 03 - 23/12/2019

I Want to get the orders data, and their respective latest status, which for both of them is status 03. To do this, I have the following code:

```
    public function statuses()
    {
        return $this->hasOne('App\Statutes', 'order_id')->latest($column = 'date');
    }
```

At my controller that feed the datatable I have:
``` 
        $model = Order::with('statuses');
        return DataTables::eloquent($model)
        ->addColumn('date', function (Order $order) {
            return $order->statuses? str_limit($order->statuses->date, 30, '...') : '';
        })
        ->make(true);
``` 

And at the JS:

``` 
$(document).ready(function() {
            var table = $('#orders').DataTable({
                processing: true,
                serverSide: true,
                searchDelay: 950,
                ajax: '{!! route('getorders') !!}',
                columns: [
                    { data: 'name', name: 'orders.name' },
                    { data: 'type', name: 'orders.type' },
                    { data: 'desc', name: 'orders.desc' },
                    { data: 'date', name: 'statuses.date' },
                ],
            });
            
        });   
``` 
This, just like the [official example][2], works perfeclty, and the statuses.date column is even searchable. But, I can't order it. **When** I write the code ```order: [[3, 'desc']]``` all the values of this column suddentlyn disappear, they are shown as they were empty. Also, IDK why, all the order records are shown 2, 3 and even 4 times each. The same happens **when** I try to order clicking the ordering button at the column header.

When I try to order another column, like orders.name, it works well, and the following queries are performed:
``` 
queries: [{,…},…]
    0: {,…}
        query: "select count(*) as aggregate from (select '1' as `row_count` from `orders`) count_row_table"
        bindings: []
        time: "0.56"
    1: {query: "select * from `orders` order by `orders`.`name` asc limit 10 offset 0", bindings: [],…}
        query: "select * from `orders` order by `orders`.`name` asc limit 10 offset 0"
        bindings: []
        time: "0.63"
    2: {,…}
        query: "select * from `statuses` where `statuses`.`order_id` in (14, 16, 19, 23, 24) order by `date` desc"
        bindings: []
        time: "0.76"
``` 
That works perfectly and show all the orders records ordered by the name column and the statuses.date value is also shown correctly.

When I try to order the statuses.date column, the following queries are performed:
``` 
queries: [{,…}, {,…}, {,…}]
    0: {,…}
        query: "select count(*) as aggregate from (select '1' as `row_count` from `orders`) count_row_table"
        bindings: []
        time: "0.4"
    1: {,…}
        query: "select * from `orders` left join `statuses` on `statuses`.`order_id` = `orders`.`id` order by `statuses`.`date` asc limit 10 offset 0"
        bindings: []
        time: "0.84"
    2: {,…}
        query: "select * from `statuses` where `statuses`.`order_id` in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10) order by `date` desc"
        bindings: []
        time: "0.66"
``` 
This shows a lot of duplicate records, and don't show any value for the statuses.date column, as it were empty. Also I noticed that the third query shows a lot of nonexistent ids (the only ones that exist are 14, 16, 19, 23, 24).
It's been a while since I've been trying to figure out this, and I still don't know how to make the column statuses.date orderable.

  [1]: https://github.com/yajra/laravel-datatables
  [2]: https://github.com/yajra/laravel-datatables-demo/blob/master/resources/views/datatables/relation/has-one.blade.php

### System details

- Operating System: Windows 10 (localhost)
- PHP Version: 7.3.1
- Laravel Version: 5.8
- Laravel-Datatables Version: v9.7.1

**Comment by yajra** [comment]
I think the issue here is that the actual relationship is hasMany and not hasOne. The package tries to generate a join statement based on your relationship. Given that orders has-many statuses, ordering by statuses date will indeed yield to duplicates records depending on how many statuses are recorded on your table.

Anyways, here are some possible solutions I can think of:

1. Use join query instead of depending on relationship. You need to force your query to load only the latest (max) date available.

2. Use `orderColumn` to override the default order functionality and apply the necessary filters to load only the latest status.
