### ISSUE TITLE
Upgrade guide not reachable

### ISSUE THREAD

**Issue by verstratenbram** [yajra/laravel-datatables#2272]
### Summary of problem or feature request

The upgrade guide from version 7.x to 8.x is not reachable.

URL: https://yajrabox.com/docs/laravel-datatables/master/upgrade

Error: `ERR_TIMED_OUT`

### System details

- Operating System: MacOS
- PHP Version: 7.2
- Laravel Version: 5.5
- Laravel-Datatables Version: 8.13

**Comment by yajra** [comment]
Please use github docs atm: https://github.com/yajra/laravel-datatables-docs/blob/master/upgrade.md.
