### ISSUE TITLE
Not Able to Convert Into CRUD Child DataTable

### ISSUE THREAD

**Issue by JeffreyDavidson** [yajra/laravel-datatables#2273]
### Summary of problem or feature request
I'm trying to refactor some controller code so that inside of my controller I only have to call one line of code so that it will send back my desired result in a json format. The code immediately below was the original and now I'm currently trying to refactor to the code further down.

The problem is I don't know what I need to call in my controller so that it calls the correct method in the file because I'm not sure I have the right methods defined in the child datatable file.

```
$query = Manager::with('employment');
$requestFilter->apply($query);

return $table->eloquent($query)
                ->addColumn('action', 'managers.partials.action-cell')
                ->filterColumn('name', function ($query, $keyword) {
                    $sql = "CONCAT(managers.first_name, ' ', managers.last_name)  like ?";
                    $query->whereRaw($sql, ["%{$keyword}%"]);
                })
                ->filterColumn('id', function ($query, $keyword) {
                    $query->where($query->qualifyColumn('id'), $keyword);
                })
                ->toJson();
```

### Code snippet of problem

```
public function index(ManagersDataTable $dataTable, ManagerFilters $requestFilter)
{
        $model = Manager::query();
        // dd($dataTable->eloquent($model)->toJson());

        // return $dataTable->eloquent($model)->toJson();
        return $dataTable->of(Manager::query())->toJson();
}
```

```
<?php

namespace App\DataTables;

use App\Models\Manager;
use App\Filters\ManagerFilters;
use Yajra\DataTables\DataTables;

class ManagersDataTable extends DataTables
{
    /** @var managerFilters */
    private $managerFilters;

    /**
     * ManagerDataTable constructor.
     *
     * @param ManagerFilters $managerFilters
     */
    public function __construct(ManagerFilters $managerFilters)
    {
        $this->managerFilters = $managerFilters;
    }

    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function render($query)
    {
        return datatables($query)
            ->editColumn('started_at', function (Manager $manager) {
                return $manager->currentEmployment->started_at->format('Y-m-d H:s');
            })
            ->editColumn('name', function (Manager $manager) {
                return $manager->full_name;
            })
            ->filterColumn('id', function ($query, $keyword) {
                $query->where($query->qualifyColumn('id'), $keyword);
            })
            ->filterColumn('name', function ($query, $keyword) {
                $sql = "CONCAT(managers.first_name, ' ', managers.last_name)  like ?";
                $query->whereRaw($sql, ["%{$keyword}%"]);
            })
            ->addColumn('action', 'managers.partials.action-cell');
    }

    /**
     * Get query source of dataTable.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query($builder)
    {
        $query = Manager::with('employment');

        $this->managerFilters->apply($query);

        return $query;
    }
}
```

### System details

- Operating System: MacOSX Catalina 10.15.2
- PHP Version: 7.3.8
- Laravel Version: 5.8.36
- Laravel-Datatables Version: ~9.0

**Comment by yajra** [comment]
Something is wrong on your ManagersDataTable class. You are trying to emulate the DataTable service class but you are extending the core DataTable class. For instance, you are using render method and expecting a `$query` argument but you are not injecting it anywhere in your code?

**Comment by JeffreyDavidson** [comment]
Which class should I be trying to emulate for this situation? 

Then when I inject my ManagersDataTable class on in my controller which method(s) should I be calling on the class? 

You had a page up that talked about child classes like this but the documentation has not been reachable.

**Comment by yajra** [comment]
Yes, my personal website is currently offline. Use https://github.com/yajra/laravel-datatables-docs atm if you need some docs.

Anyways, try using the generator and see the class structure of the generated DataTable service class.

```sh
php artisan datatables:make Test 
```

The extended class is `Yajra\DataTables\Services\DataTable;`.

**Comment by JeffreyDavidson** [comment]
@yajra I'll do that however in your examples I find I see calling a render() method off of the class. I just want to return the json. I can't call $managersDatatable->toJson() though.

**Comment by yajra** [comment]
Use `$managersDatatable->ajax()` method if you want to return the json.

**Comment by JeffreyDavidson** [comment]
@yajra So when I installed the package. ` "yajra/laravel-datatables-oracle": "~9.0"`. It doesn't include the Yajra\Datatables\Services directory so it doesn't include that Datatable file.

**Comment by yajra** [comment]
Oh, you need to install `yajra/laravel-datatables-buttons` packae too.

**Comment by JeffreyDavidson** [comment]
@yajra I was able to get everything straigtened out and all my tests passing. Thank you on your support.
