### ISSUE TITLE
Is there any way to search number (or date) range...?

### ISSUE THREAD

**Issue by KLA6** [yajra/laravel-datatables#2275]
### Summary of problem or feature request

When the search column need to search a number (or date) range, does laravel-datatables support any simple way for it...?

### Code snippet of problem

E.g. when I want to search [ from 1 to 9999 ] on id column, my current $_POST request is same as the below.

```
[columns] => Array
  (
    [0] => Array
      (
        [data] => id
        [name] => id
        [searchable] => true
        [orderable] => true
        [search] => Array
          (
            [value] => 1|9999 // Here, I expect [ from 1 to 9999 ] on the result.
            [regex] => false
          )
      )
  )
```

I expected the pipe "|" character may mean a range, but it is not working.

**Should I make the range search from Laravel Eloquent by myself, or does laravel-datatables support any simple way for it...?**

### System details

- Operating System : Linux
- PHP Version : 7.3
- Laravel Version : 6.x
- Laravel-Datatables Version

**Comment by yajra** [comment]
You need to range search manually. I think you can use `filterColumn` in this case.

**Comment by JayCasee** [comment]
Thank you so much for your quick response...!
