### ISSUE TITLE
->width('100%') does not work

### ISSUE THREAD

**Issue by Serokuz22** [yajra/laravel-datatables#2276]
Column::make('name')->title('Название')->width('100%')

```
Html generated:
<th title="Название" class="sorting" tabindex="0" aria-controls="referencetransactiontype-table" rowspan="1" colspan="1" style="width: 1399px;" aria-label="Название: activate to sort column ascending" width="100%">Название</th>
```

package.json
        "datatables.net-bs4": "^1.10.20",
        "datatables.net-buttons-bs4": "^1.6.1",

**Comment by yajra** [comment]
Seems like it's working as per generated html.

```html
<... style="width: 1399px;" ... width="100%">Название</th>
```

Maybe it has something to do with your js options like `autoWidth` I think which sets the width via style attribute.

**Comment by Serokuz22** [comment]
Thanks, -> autoWidth (false) helped.
