### ISSUE TITLE
Searching not working by using a related model on EloquentDataTable 

### ISSUE THREAD

**Issue by japc-74** [yajra/laravel-datatables#2277]
### The search feature doesn't work if I have a related model 

Hello guys, great contribution, I love the datatables for Laravel.
But, i'm facing some issues when I try to search on a related model.

Notice that ordering works fine, just searching doesn't

I have other datatables whitout related data and the search works fine.

I'm confused at this point, after looking for several pages and forums I couldn't resolve this issue.

Please help :)

### Code of datatable

```php
namespace App\DataTables;
use App\Models\MyModel;
use Yajra\DataTables\Services\DataTable;
use Yajra\DataTables\EloquentDataTable;

public function dataTable($query)
    {
        $dataTable = new EloquentDataTable($query);

        return $dataTable
                ->addColumn('action', 'test.datatables_actions')
                ->rawColumns(['date, 'destiny_id', 'driver_id', 'number_sp', 'trx_amount', 'action'])
                ->editColumn('date', function(MyModel $model){                    
                    return optional($model)->date->format('d-m-Y');
                })
                ->editColumn('Destiny.destiny_id', function(MyModel $model){                    
                    return optional($model->Destiny)->formated_data;
                })
                ->editColumn('Driver.driver_id', function(MyModel $model){                    
                    return optional($model->Driver)->formated_data;
                })
                ->editColumn('number_sp', function(MyModel $model){                    
                    return optional($model)->number_sp;
                })
                ->editColumn('trx_amount', function(MyModel $model){                    
                    return number_format(optional($model)->trx_amount, 0, ',','.');
                });
                
        //return $dataTable->addColumn('action', 'test.datatables_actions');
    }

public function query(MyModel $model)
    {

       return $model -> newQuery() -> select(
        'id', 'date', 'destiny_id', 'driver_id', 
        'number_sp', 'trx_amount') -> with('Destiny')
        -> with('Driver');

    }

public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->addAction(['width' => '80px', 'printable' => false, 'title' => 'Acción'])
            ->parameters([
                'lengthMenu' => [
                    [ 50, 100, 150, -1 ],
                    [ '50 registros', '100 registros', '150 registros', 'Todo' ]
                ], 
                'dom'       => 'Bfrtip',
                'stateSave' => true,
                'order'     => [[4, 'desc']],
                'buttons'   => [
                    ['extend' => 'create'],
                    ['extend' => 'export'],
                    ['extend' => 'print'],
                    ['extend' => 'reset'],
                    ['extend' => 'reload'],
                ],
                'language' => ['url' => '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json'],
            ]);

            
    }

protected function getColumns()
    {

        return
        [
            [
                'name' => 'date',
                'data' => 'date',
                'title' => 'Fecha',
                'defaultContent' => '',
                'width' => '150px',
            ],
            [
                'name' => 'destiny_id',
                'data' => 'Destiny.destiny_id',
                'title' => 'Destino',
                'defaultContent' => '',
            ],
            [
                'name' => 'driver_id',
                'data' => 'Driver.driver_id',
                'title' => 'Driver',
                'defaultContent' => '',
            ],
            [
                'name' => 'number_sp',
                'data' => 'number_sp',
                'title' => 'Nº SP',
                'defaultContent' => '',
            ],
            [
                'name' => 'trx_amount,
                'data' => 'trx_amount',
                'title' => 'Monto',
                'defaultContent' => '',
            ],
        ];

    }
```
-->

### System details

- Operating System: LINUX
- PHP Version 7.1
- Laravel Version 5.8
- Laravel-Datatables Version 9.5

**Comment by yajra** [comment]
I think you want to search on edited column values?

```php
->editColumn('Destiny.destiny_id', function(MyModel $model){                    
                    return optional($model->Destiny)->formated_data;
                })
```

If yes, you should also include the columns used in `formatted_data`. You can try adding a hidden column or use `filterColumn` and adjust how to proceed with searching.

```js
            [
                'name' => 'destiny_id',
                'data' => 'Destiny.destiny_id',
                'title' => 'Destino',
                'defaultContent' => '',
            ],
            [
                'data' => 'Destiny.name',
                'visible' => false,
            ],
```

**Comment by japc-74** [comment]
Thanks for your reply.
In formated_data is a concat of name and surname by using an accesor on the model Driver as is:

```php
    public function getFormateDataAttribute()
    {
        return $this->name . ' ' . $this->surname;
    }
```

,I'd added as you suggested, doesn't work.

```php
            [
                'data' => 'Driver.name',
                'visible' => false,
            ],
            [
                'data' => 'Driver.surname',
                'visible' => false,
            ],
```

also I tried changing the query as is

```php
return $model -> newQuery() -> select(
        'id', 'date', 'destiny_id', 'driver_id', 
        'number_sp','trx_amount', 'Driver.name','Driver.surname') -> with('Destiny')
        -> with('Driver');
```

Notice that I'm using the model instead tables, should I use the relation table name?

even I change this too..

```php
->editColumn('Driver.driver_id', function(MyModel $model){                    
                    return optional($model->Driver)->name. ' '. optional($model->Driver)->surname;
                })
```

nothing works... please guide me, is there any other approach?

**Comment by yajra** [comment]
Can you please dump the json response? Is it really `Driver` and not `driver` on lowercase?

**Comment by japc-74** [comment]
the model is Driver, the table name is drivers

this is the dump:


`

{"draw":1,"recordsTotal":11,"recordsFiltered":11,"data":[{"id":"10082","date":"27-12-2019","destiny_id":88,"driver_id":103,"number_sp":null,"trx_amount":"90.000","destiny":{"id":"88","created_at":"2019-10-30 16:48:21","updated_at":"2019-10-30 16:48:21","name_destiny":"PYG PRISUR TEMUCO","time":"09:00:00","client_id":"9","destiny_p_id":"16","deleted_at":null,"amount_pre":"90000","formated_data":"PYG PRISUR TEMUCO - H: 09:00 - $ 90.000","destiny_p_id":"PYG PRISUR TEMUCO"},"driver":{"id":"103","created_at":"2019-06-13 19:50:33","updated_at":"2019-11-05 13:02:04","deleted_at":null,"name":"YULIEXIS","surname":"TORRES\tGONZALEZ","rut":"23101367-9","email":null,"fdn":null,"foto":null,"foto_app":null,"bio":null,"user_id":"105","activo":"1","disponible":"1","driver_id":"YULIEXIS TORRES\tGONZALEZ"},"action":"<form method=\"POST\" action=\"http:\/\/localhost\/fbackend\/public\/expediciones\/10082\" accept-charset=\"UTF-8\"><input name=\"_method\" type=\"hidden\" value=\"DELETE\"><input name=\"_token\" type=\"hidden\" value=\"Mtyt1XrKQbTNqh2Ryl31RI1IGKAICcCaEWAky9zF\">\n<div class='btn-group'>\n    <a href=\"http:\/\/localhost\/fbackend\/public\/expediciones\/10082\" class='btn btn-ghost-success'>\n       <i class=\"fa fa-eye\"><\/i>\n    <\/a>\n    <a href=\"http:\/\/localhost\/fa-backend\/public\/expediciones\/10082\/edit\" class='btn btn-ghost-info'>\n       <i class=\"fa fa-edit\"><\/i>\n    <\/a>\n    <button type=\"submit\" class=\"btn btn-ghost-danger\" onclick=\"return confirm(&#039;\u00bfEsta seguro?&#039;)\"><i class=\"fa fa-trash\"><\/i><\/button>\n<\/div>\n<\/form>\n"}"}],"queries":[{"query":"select count(*) as aggregate from (select '1' as `row_count` from `expediciones` where `expediciones`.`deleted_at` is null) count_row_table","bindings":[],"time":"0.74"},{"query":"select `id`, `date`, `destiny_id`, `driver_id`, `number_sp`, `trx_amount` from `expediciones` where `expediciones`.`deleted_at` is null order by `trx_amount` desc limit 50 offset 0","bindings":[],"time":"0.68"},{"query":"select * from `destinies` where `destinies`.`id` in (18, 22, 24, 66, 71, 77, 85, 86, 88, 106) and `destinies`.`deleted_at` is null","bindings":[],"time":"2.42"},{"query":"select * from `drivers` where `drivers`.`id` in (4, 37, 103, 110) and `drivers`.`deleted_at` is null","bindings":[],"time":"2.14"}],"input":{"draw":"1","columns":[{"data":"date"},{"data":"destiny.destino_particular_id","name":"destiny_id"},{"data":"driver.driver_id","name":"driver_id"},{"data":"number_sp"},{"data":"trx_amount"},{"data":"action","searchable":"false","orderable":"false"}],"order":[{"column":"4","dir":"desc"}],"start":"0","length":"50","search":{"value":null},"_":"1578536090123"}}

`

**Comment by japc-74** [comment]
Hello, i finally did, as you mentioned the relationship name was lowercase, I just replaced in everywhere and works.

But, doesn't work with searching on an Accessor, neither on a manually concatenated  editColumn 

```php

->editColumn('Driver.driver_id', function(MyModel $model){                    
                    return optional($model->Driver)->name. ' '. optional($model->Driver)->surname;
                })

```

So i was obligated to do in separated columns, which is a little limitating. 

additionally i detected that id column is required in order to keep links to show, and edit views.

is there a way to hide the Id column? since using

```php
            [
                'data' => 'id',
                'visible' => false,
            ],
```

doesn't work, I'm using Yajra\DataTables\Services\DataTable; and that seems to be the reason. 
Please let me know if there is a way to use Accessor and hide the Id column.

Best

**Comment by yajra** [comment]
Instead of editing, I suggest you use addColumn. Editing an existing column like ID may cause some issue like what you stated when generating links and views.

```php
->addColumn('driver_info', function(MyModel $model){                    
    return optional($model->Driver)->name. ' '. optional($model->Driver)->surname;
})

... Columns

            [
                'data' => 'drive_info',
                'name' => 'driver.name',
            ],
            [
                'data' => 'driver.surname',
                'visible' => false,
            ],

```

In addition, try setting APP_DEBUG=true and inspect the queries generated on json response. That would give you a better where the query is failing.
