### ISSUE TITLE
Searchable and orderable custom column

### ISSUE THREAD

**Issue by thewebartisan7** [yajra/laravel-datatables#2278]
Everything works fine, except when I make a custom column searchable and orderable.

Then I get below error:

<img width="392" alt="Screenshot 2020-01-10 at 09 14 30" src="https://user-images.githubusercontent.com/57477934/72136758-cc56d400-3389-11ea-88f1-c2f01b852c8a.png">

The column is defined like so:

`  { data: { _: 'name', sort: 'name', search: 'name'}, className: 'align-middle' },`

It's rendered like so:

```
{
                    targets: 1,
                    render: function (data, type, row, meta) {

return `<a href="#${row.id}" class="tile tile-img mr-1">
                                    <img class="img-fluid" src="assets/images/dummy/img-${row.avatar}.jpg" alt="Card image cap">
                                  </a>
                                  <a href="#${row.id}">${row.name}</a>`;
                            
                    }
                }
```

Works fine except when I add:

```
           processing: true,
                serverSide: true,
```

Any idea how to make this work?

Thanks

**Comment by thewebartisan7** [comment]
I solved somehow differently

**Comment by markfs** [comment]
how did you solve this problem?

**Comment by thewebartisan7** [comment]
I don't remember exactly but check here how a column is defined:
https://yajrabox.com/docs/laravel-datatables/master/html-builder-column

As I remember you have to use `'data' => 'id',` or ` 'name' => 'id',` to let know which is the column used for searching and ordering, so that will be used even if you have custom content on it.
