### ISSUE TITLE
Add action not exist method

### ISSUE THREAD

**Issue by thewebartisan7** [yajra/laravel-datatables#2279]
About addAction explained here https://github.com/yajra/laravel-datatables-docs/blob/master/html-builder-action.md

I can't see a method addAction, but if I use addColumn('action', ...) or editColumn('action', ...) seem that it's used this customized column.

However, I am not able to change default options, for example "printable" is set to true, but when you print you don't want to see actions.

Same for addCheckbox.

I see that there is trait for this two method, but I am not sure how to add them in my Service datatable.

Thanks

**Comment by thewebartisan7** [comment]
I found! 

```php

        return $this->builder()
            ->columns($this->getColumns())
            ->addAction([
                'printable' => false,
                'exportable' => false
            ])

```

But is always printable and exportable.

My buttons definitions:

```php

            ->parameters([
                'buttons' => [
                    'copyHtml5' => ['extend' => 'print', 'autoPrint' => false]
                ],
```

**Comment by thewebartisan7** [comment]
Now seem works, adding also "title" to addAction()

**Comment by yajra** [comment]
What button are you using for export? `exportable` is only applicable for serverSide export and not on the client side.

**Comment by thewebartisan7** [comment]
I forgot about this issue. I was able to fix checking in datatable docs. For each button there is an option "exportOptions", so this works:

```
 'buttons' => [[
                    'extend' => 'copyHtml5',
                    'exportOptions' => [
                        'columns' => [ 1, 3, 4, 5 ]
                    ]
                ]
```

I am using buttons js of datatables. But only yesterday I saw your custom buttons JS. I didn't yet try them. So for now I am using only client side copyHtml5 and print.
