### ISSUE TITLE
orderColumns column name order 

### ISSUE THREAD

**Issue by quantumwebco** [yajra/laravel-datatables#2282]
I have a column in the database called order which is a reserved word in mysql. so doing

```->orderColumns(['code', 'starts_at', 'ends_at', 'order'], ':column $1')```

results in a sql error because it cant ```order by order``` it needs ```order by `order` ```

Is there any way to wrap the column name in quotes or backticks? I've tried things like ```'`order`'``` but no luck

Or maybe I should change the column name to ordering or something?

- Operating System windows 10
- PHP Version 7.3
- Laravel Version 6.x
- Laravel-Datatables Version 1.5

**Comment by yajra** [comment]
Maybe try this?

```php
->orderColumns(['code', 'starts_at', 'ends_at', 'order'], '`:column` $1')
```

**Comment by quantumwebco** [comment]
Oh yeah that works! Thanks a lot! I just changed the column name in the end tho lol. Thanks!
