### ISSUE TITLE
search overrides other filters

### ISSUE THREAD

**Issue by quantumwebco** [yajra/laravel-datatables#2283]
I'm sure I'm just doing something wrong but the following code seems to ignore other filters when search is present. So if you select a user id in the filter it filters by that user id but if you then type something in search it returns all records as if the user id wasn't there.

```
->filter(function ($query) {
    if (request()->has('search') && !empty(request()->search['value'])) {
        $query->where('first_name', 'like', "%" . request('search')['value'] . "%")
            ->orWhere('last_name', 'like', "%" . request('search')['value'] . "%")
            ->orWhere('email', 'like', "%" . request('search')['value'] . "%")
            ->orWhere('id', 'like', "%" . request('search')['value'] . "%")
            ->orWhereHas('user', function ($query) {
                $query->where('users.first_name', 'like', "%" . request('search')['value'] . "%");
                $query->orWhere('users.last_name', 'like', "%" . request('search')['value'] . "%");
            });
    }
    if (request()->has('userFilter') && !empty(request()->userFilter)) {
        $query->whereIn('user_id', request()->userFilter);
    }
})
```

Thanks for any help

**Comment by yajra** [comment]
I think you need the global search too. There is a 2nd param on filter method that would enable global search. It is disabled by default.

```php
->filter(fn($q) {}, true)
```

**Comment by quantumwebco** [comment]
I thought that could have been the problem so I disabled it. I usually always have it enabled. Behaviour is the same regardless if it's enabled or not. I thought it was to do with the order of the statements so I've tried it with the search queries at the bottom of the filter method too. I'm stumped lol

**Comment by quantumwebco** [comment]
@yajra This seems to be working fine now
