### ISSUE TITLE
skipTotalRecords for CollectionDataTable

### ISSUE THREAD

**Issue by titoshadow** [yajra/laravel-datatables#2285]
Couldn' t it be implemented for CollectionDataTable as well ?

Any other tips to improve performance on big datasets ?

Also, I'm currently using Laravel Cache in some controllers, and not sure how to make use of skipTotalRecords for that cases.

Code snippet of actually implemented:

Controller:
```
public function index(Request $request)
    {
        $items = cache()->remember('contactsList', now()->addMinutes(config('app.cache_minutes')), function () {
            return Contact::latest('updated_at')->get();
        });

        if ($request->ajax()) {
            return DataTables::of($items)
                ->editColumn('name', function($item){
                    return '<td><a href="'. route(ADMIN . '.contacts.edit', $item->id) . '">' . $item->name . '</a></td>';
                })
                ->rawColumns(['name'])
                ->toJson();
        }

        return view('admin.contacts.index', compact('items'));
    }
```

Blade:
```
<div class="bgc-white bd bdrs-3 p-10 mB-20">
        <table id="dataTable" class="table-hover table table-striped table-bordered contacts-table" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>{{ __('app.Name') }}</th>
                <th>{{ __('app.Phone') }}</th>
                <th>{{ __('app.Address') }}</th>
                <th>{{ __('app.Email') }}</th>
                <th>{{ __('app.ZIP_Code') }}</th>
                <th>{{ __('app.Charge') }}</th>
                <th>{{ __('app.Company') }}</th>
                <th>{{ __('app.Actions') }}</th>
            </tr>
            </thead>

            <tfoot>
            <tr>
                <th>{{ __('app.Name') }}</th>
                <th>{{ __('app.Phone') }}</th>
                <th>{{ __('app.Address') }}</th>
                <th>{{ __('app.Email') }}</th>
                <th>{{ __('app.ZIP_Code') }}</th>
                <th>{{ __('app.Charge') }}</th>
                <th>{{ __('app.Company') }}</th>
                <th>{{ __('app.Actions') }}</th>
            </tr>
            </tfoot>

            <tbody>
            @foreach ($items as $item)
            @endforeach
```

System:
Centos v7
Laravel v6.2
Laravel-datatables v1.5.0

**Comment by yajra** [comment]
Is it really needed to be a Collection? It is not advisable to use collection on large datasets. Only way to improve this afaik is by increasing your server resources.

**Comment by fsou** [comment]
Hi @yajra, currently facing similar problem.

I am getting data from an external service and using predefined offsets as suggested on #2083.

At the moment, I only get from external service, using it's own API, the chunk of data to be displayed.

The issue I'm having is I don't know how many records the query would return, not knowing that, I can't set the totalRecords with the correct value.

Without that, I can't make datatables to activate the "next page" button to request the next chunk of data.

I am using:
laravel-datatables-oracle v9.8.0
laravel-datatables-html v4.20.1

Thank you.
