### ISSUE TITLE
DataTables warning: table id=DataTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by Pak10** [yajra/laravel-datatables#2286]
### Summary of problem or feature request

I get the error above a some times like 8 out of 10 when searching the datatable or loading the page. On checking the xhr, i see the 500 internal server error on that request So this error may appear if i type very quickly. please help me out

### Code snippet of problem
------------------------------THIS IS MY CONTROLLER-------------------------------
   
        $Deposits = DB::table('deposits')->whereNull('deposits.deleted_at')
        ->join('users', 'deposits.User_ID', '=', 'users.id')
        ->join('deposit_charges', 'deposits.User_ID', '=', 'deposit_charges.User_ID')
       ->select('deposits.Deposit_ID','deposits.Payment_Date',
'deposit_charges.Deposit_Charge','deposits.Amount_Paid','users.name','deposits.Deposit','deposits.Month_For','deposits.Year_For', 'deposits.Charge_Paid')
        ->orderBy('deposits.Deposit_ID', 'DESC')
        ->get();  

        

            if(request()->ajax()){
                
                return Datatables::of($Deposits)->addColumn('action', function($data){
                    $button = '<button type = "button" name = "edit" id ="'.$data->Deposit_ID.'" class = "edit btn btn-primary btn-sm ">Edit</button>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<button type = "button" name = "delete" id ="'.$data->Deposit_ID.'" class = "delete btn btn-danger btn-sm">Delete</button>';
    
                    return $button;
                })->editColumn('Charge_Paid', function ($inquiry) {
                    if ($inquiry->Charge_Paid == 0) return 0;
                    if ($inquiry->Charge_Paid == 1) return $inquiry->Deposit_Charge;
                    return 'Cancel';
                })
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
    
              
            }

--------------------------------THIS IS MY SCRIPT ON THE BLADE---------------------------------
$(document).ready(function(){
var table = $('#DataTable').DataTable({
    processing: true,
    serverSide: true,
    searching: true,
    
    ajax:  "/ReturnSavings",
    columns:[
        {
          data: 'DT_RowIndex',
          name: 'DT_RowIndex'
        },
        {
            data: 'Payment_Date',
            name: 'Payment_Date',
            orderable: false
        },
        {
            data: 'name',
            name: 'name',
            orderable: false
            
        },
        {
            data: 'Amount_Paid',
            name: 'Amount_Paid'
           
        },
        {
            data: 'Deposit',
            name: 'Deposit'
           
        },
        {
            data: 'Month_For',
            data: 'Month_For'
        },
        {
            data: 'Year_For',
            name: 'Year_For',
            orderable: false
        },
        {
            data: 'Charge_Paid',
            name: 'Charge_Paid'
        },
        {
            data: 'action',
            name: 'action', 
            orderable: false
        },

    ]

});

});

-------------------------------------------------DETAILS-------------------------------------
- WINDOWS 10
- PHP 7.2
- Laravel Version 5.8.32
- Laravel-Datatables Version 9.8

**Comment by yajra** [comment]
Better inspect the ajax response and see the error dump. Enable APP_DEBUG=true to have more feedbacks from the request.

**Comment by adrian-lp** [comment]
Did you find a solution for this?
