### ISSUE TITLE
How to add link to column use route() function

### ISSUE THREAD

**Issue by chungtran4078** [yajra/laravel-datatables#2289]
I need sometthings like as:
```php
        Column::make('project_name')
                ->title(__('Project Name'))
                ->render(function($item) {
                    return '<a href="' . route('projects.detail', $item->id) . '">' . $item->project_name . '</a>';
                })
```

Here, I can use route() and pass parameter for it to generate link of project.

I had try:
```php
datatables()
            ->eloquent($query)
            ->addColumn('project_name', function ($item) {
                return '<a href="'.route('projects.detail', $item->id).'">'.$item->project_name.'</a>';
            });
```
then:
```php
 Column::computed('project_name')
                ->title(__('Project Name'))
```
It's work but cannot sort

**Comment by yajra** [comment]
Use `editColumn`.

```php
datatables()
            ->eloquent($query)
            ->editColumn('project_name', function ($item) {
                return '<a href="'.route('projects.detail', $item->id).'">'.$item->project_name.'</a>';
            });
```

**Comment by chungtran4078** [comment]
> Use `editColumn`.
> 
> ```
> datatables()
>             ->eloquent($query)
>             ->editColumn('project_name', function ($item) {
>                 return '<a href="'.route('projects.detail', $item->id).'">'.$item->project_name.'</a>';
>             });
> ```

Thanks for response.
I had can use `route()` function. But how can I show html instead of raw data as below
![image](https://user-images.githubusercontent.com/46410548/73140029-d4f81b80-40a6-11ea-8ff0-0bb370d29100.png)

This is not work:
```php
datatables()
            ->eloquent($query)
            ->editColumn('project_name', function ($item) {
                return '<a href="'.route('projects.detail', $item->id).'">'.$item->project_name.'</a>';
            })
            ->rawColumns(['action', 'time_passed'])
            ->escapeColumns(['project_name'])
```

**Comment by yajra** [comment]
Don't use escapeColumns with rawColumns.

```php
datatables()
            ->eloquent($query)
            ->editColumn('project_name', function ($item) {
                return '<a href="'.route('projects.detail', $item->id).'">'.$item->project_name.'</a>';
            })
            ->rawColumns(['action', 'time_passed', 'project_name']);
```

**Comment by chungtran4078** [comment]
It's work perfectly.
Thanks!

**Comment by kousar2334** [comment]
this is my addColumn method

`->addColumn('action', function ($donor) {
                return '<a href="'.route('admin.blood.donar.edit',$donor->id).'" class="btn btn-sm btn-info edit-info"><i class="fas fa-edit"></i></a> '; })
        ->rawColumns(['image', 'status', 'action'])->make(true);`

This is my route
`Route::get('/blood-donar-edit/{id}', 'BloodBankController@editBloodDonor')->name('admin.blood.donar.edit');`

But I got this error
Missing required parameters for [Route: admin.blood.donar.edit] [URI: admin/blood-donar-edit/{id}]. (View: /opt/lampp/htdocs/bogura/resources/views/admin/bloodBank/donor_list.blade.php)

**Comment by fazrisuhada007** [comment]
how show project name in view sir?

**Comment by kousar2334** [comment]
This is List url 
http://localhost/bogura/admin/blood-donar-list
