### ISSUE TITLE
Mutate search query

### ISSUE THREAD

**Issue by kryzz** [yajra/laravel-datatables#229]
First, thanks for this awesome datatable package.
I have a datatable and want to perform a column search (select) on a particularly column. My problem is, that I use editColumn for this column in my datatable, where I rename the column value.
```
->editColumn('ordered_at', function ($order_item) {
    	$ordered_at = Order::renameOrderedAt($order_item->ordered_at);
        eturn $ordered_at;
 })
```
So when I use column search and select an option, it couldn't find the data in the database because its renamed.  Any suggestions how to bypass this problem?

**Comment by yajra** [comment]
@kryzz, you can try using `filterColumn` method to apply a custom filtering that should match the mutated value like:

```php
return Datatables::of($users)
            ->filterColumn('user_id', 'whereRaw', "CONCAT(users.id,'-',users.id) like ?", ["$1"])
            ->make(true);
```

**Comment by kryzz** [comment]
@yajra that did the trick, thanks!
