### ISSUE TITLE
How to loop through columns for chaining editColumn or filterColumn?

### ISSUE THREAD

**Issue by Slivicon** [yajra/laravel-datatables#2290]
### Summary of problem or feature request

How to loop through columns for chaining editColumn? I did not see a "editColumns" function, only "editColumn", so I have to do:

```php
return datatables($query)
    ->editColumn('COLUMNA', function ($data) {
        return $this->getDisplay('COLUMNA', $data->COLUMNA);
    })
    ->editColumn('COLUMNB', function ($data) {
        return $this->getDisplay('COLUMNB', $data->COLUMNB);
    });
```

but I would like to do something like: 

```php
$datatable = datatables($query);
$editColumns = $this->getEditColumns();
foreach ($editColumns as $editColumn) {
    $datatable->editColumn($editColumn['name'], function ($data) use ($editColumn) {
        return $this->getDisplay($editColumn['name'], $data->{$editColumn['name']});
    });
}
return $datatable;
```

Similarly, for filterColumn, instead of having to call filterColumn chained for every column individually just to call the same callback.

Sorry if this is a php knowledge question instead of a yajra laravel-datatables question.

### System details

- Windows Server 2012
- PHP 7.3.3
- Laravel 5.8
- Laravel-Datatables 9.8

**Comment by yajra** [comment]
I think this can be better achieved using model accessor or model presenters.

```php
class Product extends Model
{
    public function getDisplayAttribute()
    {
        return 'Display Product: ' . $this->id;
    }
}

...

return datatables($query)
    ->addColumns(['display', 'other attributes via getter'])
    ...

```
