### ISSUE TITLE
Enable inline editing and row selection

### ISSUE THREAD

**Issue by cent89** [yajra/laravel-datatables#2294]
Hi, I have setup DataTables end Editor correctly; I can see the rows and a "new" button, that opens the editor to save a new record.
I can see also an "Edit" button, that is disabled.
How I can enable a row selection (that enable the Edit button) and the inline editor with a Laravel controller?
Thanks

**Comment by yajra** [comment]
You need to include the `select` extension for it to work (edit & delete).

**Comment by cent89** [comment]
Hi,
I have added a ->select() function to mu Controller and I works well.
How I can enable the inline editor? Some code:

**DataTable class:**

```
...
public function html()
  {
    return $this->builder()
    ->setTableId('resourceTable')
    ->columns($this->getColumns())
    ->minifiedAjax()
    ->select()
    ->dom('Bfrtip')
    ->orderBy(1)
    ->buttons(
      Button::make('create')->editor('editor'),
      Button::make('edit')->editor('editor')
      )
      ->editor(
        Editor::make()
        ->fields([
          Fields\Date::make('data_inserimento', 'data_inserimento'),
        ])
      );
    }
...
```

**index.blade.php**
```
<body>
<div>
{{$dataTable->table()}}
</div>
...
<script>
{{$dataTable->scripts()}}
</script>
</body>

```

Thanks

**Comment by cent89** [comment]
I have added some code to editor template (resource/view/vendor/datatables/editor.blade.php). In any row of my table I have an edit and remove button). Is this the best way?

```javascript
// Custom edit script
        $("#%1$s").on('click', 'button#editor_edit', function (e) {
          e.preventDefault();
          {{$editor->instance}}.edit( $(this).closest('tr'), {
            title: 'Modifica',
            buttons: 'Aggiorna'
          });
        });

        // Custom delete script
        $("#%1$s").on('click', 'button#editor_delete', function (e) {
          e.preventDefault();
          {{$editor->instance}}.remove( $(this).closest('tr'), {
            title: 'Cancella record',
            message: 'Sei sicuro di voler eliminare il record selezionato?',
            buttons: 'Cancella record'
          } );
        } );

        //Custom inline editor
        $("#%1$s").on('dblclick', 'tbody td', function (e) {
          {{$editor->instance}}.inline(this, {
            onBlur: 'submit',
            submit: 'allIfChanged'
          });
        });
```

**Comment by yajra** [comment]
Not sure if best, it depends on your prefs. I sometimes write the js on another file or within the view itself.

Another way is to optionally create a new template and use it so that the defaults are not altered. To use the new template chain `setTemplate('view.path')` as the last call in method chain.

```php
...
public function html()
{
    return $this->builder()
    ->setTableId('resourceTable')
    ->columns($this->getColumns())
    ->minifiedAjax()
    ->select()
    ->dom('Bfrtip')
    ->orderBy(1)
    ->buttons(
      Button::make('create')->editor('editor'),
      Button::make('edit')->editor('editor')
      )
    ->editor(
        Editor::make()
        ->fields([
          Fields\Date::make('data_inserimento', 'data_inserimento'),
        ])
    )
    ->setTemplate('view.path');
}
...
```

**Comment by cent89** [comment]
Hi,
setTemplate is a great solution. Thanks!

**Comment by salehliam** [comment]
Hi Guys, I‘ve been looking for the solution you were talking about in this post. However, I am not able to access $editor variable in blade view. I got a message that $editor doesn’t exist. 

Any help appreciated.

Michal
