### ISSUE TITLE
Search issue in Datatables with many-to-many relationship table

### ISSUE THREAD

**Issue by gwachhamit** [yajra/laravel-datatables#2296]
I am using laravel datatables, package provided by you. 
Everythings works fine for search if the table is one-to-one relation or one-to-many relationship by doing like:
`{name:"table.column"}`
the search is good.
The problem is when the table relation is many-to-many. how can we search for this?
It is impossible to write `{name:"table_name.column_name}` since, we have to run loop to preview the contents because the result is in array.

**Comment by yajra** [comment]
I think you need to use [filterColumn](https://yajrabox.com/docs/laravel-datatables/master/filter-column) and write your query manually.
