### ISSUE TITLE
How to use blade with Column::render()

### ISSUE THREAD

**Issue by cent89** [yajra/laravel-datatables#2297]
Hi, I have a question.
I have a Datatables with an editor; I would render a boolean value with a blade view. 
I have tried two options.
A) `addColumn('important', 'view.checkbox')`: It works well (in checkbox.blade.php I have a simple html string), I can see a rendered value. But if I edited the row with the editor, the new value isn't saved (but no errors in console).

B) `Column::make(important)->render('view.checkbox')`: The value isn't rendered and I have a javascript error: 'Requested unknown parameter 'important' for row 0, column 10'. But in the console I can see the 'important' field in json format.

How I can solve this issues?
Thanks!
Roberto

**Comment by yajra** [comment]
When using editor, you need to preserve the original column value. I usually handle this case by adding a new column.

```php
->addColumn('important_display', 'view.checkbox')

Column::make('important')->data('important_display')
```

**Comment by cent89** [comment]
Thanks!
