### ISSUE TITLE
How to use dataTableVariable

### ISSUE THREAD

**Issue by cent89** [yajra/laravel-datatables#2298]
Hi, 
I have this scenario: in one page I have a big table, with a button in each row. This button loads a detail in a small div below the main table.
Loading the frame with the second table, there is a lot of errors, due to the same {{ $dataTable }} variable name in blade template.
After some searching, I have found $dataTableVariable in Yajra\DataTables\Services\DataTable class. So, for example, I can change the table name in the constructor:

```
public function __construct(){
    $this->dataTableVariable = 'dataTable2';
  }
```

When I call `{{ $dataTable2->table() }}` in blade template, it works well. The problem is `{{ $dataTable2->scripts() }}`, that use the DataTable query of the first (main) table.
How I can force the script to initialize the second table?

Thanks!
Roberto

**Comment by yajra** [comment]
You need to set the variable as the html builder.

```php
$dataTable2 = $table2->html();
```

Then use it with table and scripts on blade.

```php
{{ $dataTable2->table() }}
...
{{ $dataTable2->scripts() }}
```

**Comment by cent89** [comment]
What is `$table2`? And where I can put the `$table2->html()`?

Thanks!

**Comment by yajra** [comment]
Something like: 

```php
fn index(UsersDT $table1, RolesDT $table2) 
{
  $dt1 = $table1->html();
  $dt2 = $table2->html();

  return view('view.tables', compact('dt1', 'dt2'))
}

{{ $dt1->table() }}
{{ $dt2->table() }}
...
{{ $dt1->scripts() }}
{{ $dt2->scripts() }}
```

**Comment by yajra** [comment]
Also, your issue might be on same table element id? If that is the case, you should set table2 id to something else.

```php
$this->builder()->setTableId('table2')...

// via blade

$dataTable2->table(['id' => 'table2')
```


------
> How to use dataTableVariable?

On your class, just override the property.

```php
class UsersDT extends DataTable 
{
  protected $dataTableVariable = 'myTable';
}

{{ $myTable->table() }}
...
{{ $myTable->scripts() }}
```

**Comment by cent89** [comment]
It doesn't works.
This is the scenario:
In the first class, I have this index() function:

```php
class FirstDataTable extends DataTable
{
public function index(LottiProduzioneDataTable $dataTable, Request $request)
  {    
      return $dataTable->render('lotto_produzione.index');
  }
}
```
```php
class LottiProduzioneDataTable extends DataTable
{
public function html(){
return $this->builder()->....->setTableId('resourceTable');
}
}
```
In my view lotto_produzione/index.blade.php, I have:
```
{{ $dataTable->table() }}
{{ $dataTable->scripts() }}
```
This works: I have a table with editor and some buttons; the id is 'resourceTable'. For each row I have a button that loads a second DataTable in a div. 

Function of the button:
```javascript
$("#my_div").load("{!! url('detail.index') !!}");
```

Second Class
```php
class DetailDataTable extends DataTable
{
public function index(FaseProduzioneDataTable $dataTable, Request $request)
  {    
      return $dataTable->render('fase_produzione.index');
  }
}
```
```php
class FaseProduzioneDataTable extends DataTable
{
  protected $dataTableVariable = 'dataTable2';
public function html(){
return $this->builder()->....->setTableId('fasiProduzioneTable');
}
}
```
In the child view fase_produzione/index.blade.php I have:
```
{{ $dataTable2->table() }}
{{ $dataTable2->scripts() }}
```
The table is rendered in the div with the right id (fasiProduzioneTable), but the script() function is of the first table, so I have a lot of errors.

**Comment by yajra** [comment]
I think you're mixing the controller and dataTable class. Maybe you should see the quick starter documentation first https://yajrabox.com/docs/laravel-datatables/master/quick-starter.

Also, it seems like you are doing some master-details table. See https://datatables.yajrabox.com/eloquent/master for ref too.

**Comment by cent89** [comment]
Update.
The scripts are rightly generated (in the javascript code, the table id is correcty fasiProduzioneTable). 
Php side, `html()` function is right (in blade I have two different tables) but the `dataTable()` and `query()` function called by the second table are relative to the first table.
There isn't a mixing in the controller and DataTable class...
Any ideas?

**Comment by cent89** [comment]
Some code, after some investigations.
This is the code generated by `{{ $dataTable->scripts() }}` is:

```javascript
window.LaravelDataTables["resourceTable"] = $("#resourceTable").DataTable(
    {"serverSide":true,
    "processing":true,
    "ajax":{
      "url":"",
      "type":"GET",
      "data":function(data) {
        for (var i = 0, len = data.columns.length; i < len; i++) {
          if (!data.columns[i].search.value) delete data.columns[i].search;
          if (data.columns[i].searchable === true) delete data.columns[i].searchable;
          if (data.columns[i].orderable === true) delete data.columns[i].orderable;
          if (data.columns[i].data === data.columns[i].name) delete data.columns[i].name;
        }
        delete data.search.regex;
      }
      },
      "columns":[...],"select":{"selector":"td:not(:last-child)","style":"os"},"dom":"Bfrtip","order":[[1,"desc"]],"buttons":[{"extend":"create","editor":editor,"className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-plus\"><\/i> Nuovo Lotto"},{"extend":"export","className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-download\"><\/i> Esporta"},{"extend":"print","className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-print\"><\/i> Stampa"},{"extend":"reset","className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-undo\"><\/i> Reset"}]}
    );
    })(window,jQuery);
```
The same code is generated by the second table, except for the `columns[]` array. The problem, I think, is in the `ajax` param, that is the same for the two tables.

**Comment by cent89** [comment]
> Some code, after some investigations.
> This is the code generated by `{{ $dataTable->scripts() }}` is:
> 
> ```js
> window.LaravelDataTables["resourceTable"] = $("#resourceTable").DataTable(
>     {"serverSide":true,
>     "processing":true,
>     "ajax":{
>       "url":"",
>       "type":"GET",
>       "data":function(data) {
>         for (var i = 0, len = data.columns.length; i < len; i++) {
>           if (!data.columns[i].search.value) delete data.columns[i].search;
>           if (data.columns[i].searchable === true) delete data.columns[i].searchable;
>           if (data.columns[i].orderable === true) delete data.columns[i].orderable;
>           if (data.columns[i].data === data.columns[i].name) delete data.columns[i].name;
>         }
>         delete data.search.regex;
>       }
>       },
>       "columns":[...],"select":{"selector":"td:not(:last-child)","style":"os"},"dom":"Bfrtip","order":[[1,"desc"]],"buttons":[{"extend":"create","editor":editor,"className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-plus\"><\/i> Nuovo Lotto"},{"extend":"export","className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-download\"><\/i> Esporta"},{"extend":"print","className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-print\"><\/i> Stampa"},{"extend":"reset","className":"btn btn-sm btn-primary","text":"<i class=\"fas fa-undo\"><\/i> Reset"}]}
>     );
>     })(window,jQuery);
> ```
> 
> The same code is generated by the second table, except for the `columns[]` array. The problem, I think, is in the `ajax` param, that is the same for the two tables.

Ok, the problem is the ajax url, that is defined as `url()->current()`. So, you can pass an url as first param of `minifiedAjax()` function, that in my case is the url of the detail table.
It works!
