### ISSUE TITLE
Search field - HTML element not rendered 

### ISSUE THREAD

**Issue by Caine85** [yajra/laravel-datatables#2299]
Hi everybody, I have a problem with the search field visualization. 

Sometimes in almost all browsers and practically always in Microsoft Internet Explorer and Microsoft Edge, the search field is not correctly rendered neither is the corresponding element added to the DOM.

Search element not present (Internet Explorer 11):
![search element not present](https://user-images.githubusercontent.com/5676445/72902675-31b4a880-3d2c-11ea-8fa7-8ebc8caa01c9.png)

Search element present (Apple Safari 13):
<img width="1522" alt="search element present" src="https://user-images.githubusercontent.com/5676445/72902700-3c6f3d80-3d2c-11ea-850b-b8d3b7ff6c25.png">

This is the getBuilderParameters () function that I use to add elements to the table:

```
protected function getBuilderParameters()
    {
        return [
            'dom' => '<"top d-md-flex justify-content-between"lB<"search">>rt<"bottom d-md-flex justify-content-between"ip><"clear">',
            'buttons' => [
                [
                    'extend' => 'print',
                    'text' => '<i class="fa fa-print"></i> ' . __('Print')
                ], 'csv', 'pdf'
            ],
            'lengthMenu' => [[10, 25, 50, -1], [10, 25, 50, __('All')]],
            'language' => [
                'url' => '/DataTables/language/it_IT.json',
                'select' => [
                    'rows' =>
                    [
                        "_" => "%d righe selezionate",
                        "0" => "Puoi selezionare una o più righe",
                        "1" => "1 riga selezionata"
                    ]
                ]
            ],
            'processing' => true,
            'scrollX' => true,
            'order' => [
                10, // here is the column number
                'desc'
            ]
        ];
    }
```

Is there any way to force the add of the search field within the DOM or to fix this issue?

Thank you so much!

- Operating System: Windows Server 2019, Windows 10, Mac OS X 10.15.2
- PHP Version: 7.2
- Laravel Version: 6.11
- Laravel-Datatables Version: 9.8.0

**Comment by yajra** [comment]
Not sure but It seems more like hidden instead of missing? Have you tried to scroll horizontally?

Anyways, I think this can be answered better if you try asking on datatables.net forum. More of a CSS and JS issue. Thanks!

**Comment by Caine85** [comment]
Hi, thank you very much for the quick response!

No, unfortunately it's not a problem related to CSS or to the fact that the element is hidden. The problem is that this block is missing in the DOM:
```
<div class="form-inline">
    <input class="form-control" type="text" placeholder="Search...">
    </input>
</div>
```

I will try to ask in the forum suggested by you, thank you again!
