### ISSUE TITLE
How to collapse cells Yajra Laravel Datatable ?

### ISSUE THREAD

**Issue by PhoeniX7s** [yajra/laravel-datatables#2302]
I need to collapse all blank cells to get one cell next to 4 cells like in the screenshot: :
https://imgur.com/a/Npi9yFT

- Operating System Windows 10
- PHP Version 7.1.3
- Laravel Version 5.8.35
- Laravel-Datatables Version 9.7.2

**Comment by yajra** [comment]
Can you elaborate, didn't quite get your issue? Or do you want something like grouping the cells?

**Comment by PhoeniX7s** [comment]
I need cells fusion so the 4 cells will display like one big cell.
