### ISSUE TITLE
Datatable  iTotalRecords doesnt work in Laravel

### ISSUE THREAD

**Issue by SyahirahWanMin** [yajra/laravel-datatables#2307]
Code below is the ajax for datatable that I used to solve above problems, but it doesnt work as what I wanted.

```
<script type="text/javascript">
  $(document).ready(function(){
      fill_datatable();

      function fill_datatable(age = '', ,carOwnership2='') 
    {
        var dataTable = $('#table_data').DataTable({
            processing: true,
            serverSide: true,
            fixedHeader: {
      header: true,
      "draw": 1
    });
```
Im pretty sure I've used the functions in a correct way. However, not sure why I got those errors in datatable. Anyone knows what I should do to fix my code?

**Comment by yajra** [comment]
Can you please paste the error dump? 

The script doesn't have `ajax` on it,  does it work?

**Comment by yajra** [comment]
Btw, I think you also need to include the columns definition.

**Comment by SyahirahWanMin** [comment]
Thanks now it works
