### ISSUE TITLE
Column search with constants from Model function

### ISSUE THREAD

**Issue by kautharhilmyz** [yajra/laravel-datatables#2308]
### Summary

Hi. I want to get status label from model where the status id is save in the database for each record. 
Meanwhile the status id and label is define in model.

Example: I want to search "Claimed" in the search box, and it will get the label from model and list the status in datatables. The following code can search all the column necessary except for status_label column because it not have relation in database. I want to try filterColumn but have no idea how to use it. 

Database Id: status_id = 6 (STATUS_CLAIMED)
Model Label: STATUS_CLAIMED = Claimed

How can achieve this. Thank you.

![image](https://user-images.githubusercontent.com/5203500/73613247-a7731b00-462e-11ea-8ac9-4152b6961222.png)

### Code snippet

```php
    /**======================*
     *         Model Claim                           *
     * ======================*/
    const STATUS_GENERATE               = 0;
    const STATUS_DRAFT                  = 1;
    const STATUS_PENDING_VERIFICATION   = 2;
    const STATUS_PENDING_DOCUMENT       = 3;
    const STATUS_VERIFIED               = 4;
    const STATUS_APPROVED               = 5;
    const STATUS_CLAIMED                = 6;

    /**
     * Return list of status codes and labels
     * @return array
     */
    public static function listStatus()
    {
        return [
            self::STATUS_GENERATE               => 'Generate',
            self::STATUS_DRAFT                  => 'Draft',
            self::STATUS_PENDING_VERIFICATION   => 'Pending Project Verification',
            self::STATUS_PENDING_DOCUMENT       => 'Pending Document',
            self::STATUS_VERIFIED               => 'Verified',
            self::STATUS_APPROVED               => 'Approved',
            self::STATUS_CLAIMED                => 'Claimed',
        ];
    }

    /**
     * Returns label of actual status
     * @param string
     * @return mixed|string
     */
    public static function statusLabel($status)
    {
        $list = self::listStatus();

        // little validation here just in case someone mess things
        // up and there's a ghost status saved in DB
        return isset($list[$status])
            ? $list[$status]
            : 'Invalid status: '. $status;
    }

    /**======================*
     *         Controller                               *
     * ======================*/
            $data = Claim::join('users', 'users.id', '=', 'claims.user_id')
                ->select(['users.name as user_name', 'claims.id', 'claims.reference_no', 'claims.selling_price', 'claims.created_at', 'claims.submitted_on', 'claims.status']);
            
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('status_label', function ($row) {
                    return Claim::statusLabel($row->status);
                })
                ->make(true);


    /**======================*
     *             Blade                                  *
     * ======================*/
                columns: [
                    {data: 'reference_no', name: 'claims.reference_no'},
                    {data: 'selling_price', name: 'claims.selling_price'},
                    {data: 'created_at', name: 'claims.created_at'},
                    {data: 'submitted_on', name: 'claims.submitted_on'},
                    {data: 'user_name', name: 'users.name'},
                    {data: 'status_label', name: 'status_label'}
               ]
```

### System details

- Operating System: Windows 10
- PHP Version: 7.2
- Laravel Version: 6.5.0
- Laravel-Datatables Version: v9.7.1

**Comment by RyanPriceDotCa** [comment]
Maybe something like the below.  Note the code isn't tested as I can't know what your model fully looks like.

First, expose the status in your Claim model by creating a [mutator](https://laravel.com/docs/master/eloquent-mutators#defining-a-mutator).  This might not be necessary if you are able to access the string version of the status some way through the model already:

```php
   //make sure to add it to the $appends array so it's available to be used...
   protected $appends = [
        'claim_status',
    ];

    public function getClaimStatusAttribute()
    {
        return $this->statusLabel($this->status);
    }
```

```php
return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('status_label', function ($row) {
                    return Claim::statusLabel($row->status);
                })
                ->filterColumn('status_label', function ($query, $keyword) {
                    $query->where('claim_status', 'like', '%' . $keyword . '%');
                })
                ->make(true);
```

Something along those lines should do the trick, hopefully it gets you pointed in the right direction.

**Comment by yajra** [comment]
I think what you need is a conditional query since the label is from constants. Maybe something like:

```php
->filterColumn('status_label', function ($query, $keyword) {
    $query->when($keyword == 'Claimed', function ($query) {
        return $query->where('status', Model::STATUS_CLAIMED);
    });
})
```

See official docs for ref: 

https://laravel.com/docs/6.x/queries#conditional-clauses
https://yajrabox.com/docs/laravel-datatables/master/filter-column

**Comment by kautharhilmyz** [comment]
@RyanPriceDotCa 
This code work, it append column claim_status with the label status
> ```
>    //make sure to add it to the $appends array so it's available to be used...
>    protected $appends = [
>         'claim_status',
>     ];
> 
>     public function getClaimStatusAttribute()
>     {
>         return $this->statusLabel($this->status);
>     }
> ```



Unfortunately code below doesn't work, an error like "Unknown column claim_status/claims.claim_status in where clause" will appear when try to search keyword.
> ```
> return DataTables::of($data)
>                 ->addIndexColumn()
>                 ->addColumn('status_label', function ($row) {
>                     return Claim::statusLabel($row->status);
>                 })
>                 ->filterColumn('status_label', function ($query, $keyword) {
>                     $query->where('claim_status', 'like', '%' . $keyword . '%');
>                 })
>                 ->make(true);
> ```

Is this code for blade in right sentence? ```{data: 'claim_status', name: 'claim_status'},```


> You can also setup a search in the footer to search per-column to make sure you're only searching that specific column. It will use the same code once it's showing up. See https://datatables.yajrabox.com/eloquent/multi-filter-select for more details.

At the moment client don't want this multi searching from individual column yet.

**Comment by kautharhilmyz** [comment]
@yajra Thanks for your respone.
> ```
> ->filterColumn('status_label', function ($query, $keyword) {
>     $query->when($keyword == 'Claimed', function ($query) {
>         return $query->where('status', Model::STATUS_CLAIMED);
>     });
> })
> ```

I changed the code as below:
```
$query->when($keyword == 'Claimed', function ($query) {
    return $query->where('claims.status', Claim::STATUS_CLAIMED);
});
$query->when($keyword == 'Approved', function ($query) {
    return $query->where('claims.status', Claim::STATUS_APPROVED);
});
$query->when($keyword == 'Pending Account Verification', function ($query) {
    return $query->where('claims.status', Claim::STATUS_PENDING_APPROVAL);
});
 ```
For the Claimed and Approved status can filter, but for the status "Pending Account Verification", the keywords just capture word "Pending" without the rest of the words. So it cant filter that status.

And this approach only filter if the word is exactly as the status not partial word like Eg: search 'cla' will return "Claimed".

**Comment by yajra** [comment]
The condition query executes if true, thus you just need to do some string manipulation like `Str::contains()`, etc if you want something like a fuzzy search.

**Comment by kautharhilmyz** [comment]
Ok. I need to get the full search value from request first. Then lowercase it and check contains.
```
->filterColumn('status_label', function ($query) {
    $searchKeyword = strtolower(request()->search['value']);

    if (Str::contains($searchKeyword, 'claimed')) {
        return $query->where('pipelines.status', Pipeline::STATUS_CLAIMED);
    };
    if (Str::contains($searchKeyword, 'approved')) {
        return $query->where('pipelines.status', Pipeline::STATUS_APPROVED);
    };
    if (Str::contains($searchKeyword, 'pending account verification')) {
        return $query->where('pipelines.status', Pipeline::STATUS_PENDING_APPROVAL);
    };
});
```

Currently for this method its working fine where I need to manually add condition for each status then and the value must have full status name.

I'm looking for a way where I can use ```$query->where('status_label', 'like', '%' . $searchKeyword. '%');``` from the idea that had mentioned by @RyanPriceDotCa because I have many model to use this kind of things. And each model have more than 10 statuses.

It is quite troublesome to make condition for each status in each model. Any suggestions that include changes to the model are welcomed.

**Comment by yajra** [comment]
I think it would be hard to implement since it's not part of the database. If you can create a lookup table and transfer all your constants there then this would be easily done with a belongsTo relationship.
