### ISSUE TITLE
Datatables Cache Query

### ISSUE THREAD

**Issue by andipahlevy** [yajra/laravel-datatables#2312]
How to cache query using yajra datatables?

**Comment by yajra** [comment]
Haven't tried caching because it's faulty the last time I tried. Maybe other users can help you on this.

**Comment by andipahlevy** [comment]
I have solve this issue. I added a few lines of code in QueryDataTable.php. Next i want to override this function to another class

`public function count()
    {
        $builder = $this->prepareCountQuery();
        $table   = $this->connection->raw('(' . $builder->toSql() . ') count_row_table');
		
		$cName = 'countdttbl_'.clean($builder->toSql()) . clean(json_encode($builder->getBindings()));
		
		if(config('cache.default') == 'redis'){
			$cek = Cache::tags(AccessRight::plants())->has($cName);
		}else{
			$cek = Cache::has($cName);
		}
		
		if ($cek){
			if(config('cache.default') == 'redis'){
				$value = Cache::tags(AccessRight::plants())->get($cName);
			}else{
				$value = Cache::get($cName);
			}
			
			$LOG = 'Ini data dari CACHE - datatables count()';
		} else {
			if(config('cache.default') == 'redis'){
				$value = Cache::tags(AccessRight::plants())->remember($cName, config('app.cache_query_time'), function () use($table, $builder) {
					return $this->connection->table($table)
									->setBindings($builder->getBindings())
									->count();
				});
			}else{
				$value = Cache::remember($cName, config('app.cache_query_time'), function () use($table, $builder) {
					return $this->connection->table($table)
									->setBindings($builder->getBindings())
									->count();
				});
				
				
			}
			
			$LOG = 'Ini data dari DATABASE - datatables count()';
		}	
		if(config('app.debug')){
			// \Log::info("CName: $cName");
			\Log::info($LOG);
        }
		return $value;
    }`

`public function results()
    {
		$cName = clean($this->query->toSql()) . clean(json_encode($this->query->getBindings()));
		
		if(config('cache.default') == 'redis'){
			$cek = Cache::tags(AccessRight::plants())->has($cName);
		}else{
			$cek = Cache::has($cName);
		}
		if ($cek){
			if(config('cache.default') == 'redis'){
				$value = Cache::tags(AccessRight::plants())->get($cName);
			}else{
				$value = Cache::get($cName);
			}
			
			$LOG = 'Ini data dari CACHE - datatables results()';
		} else {
			if(config('cache.default') == 'redis'){
				$value = Cache::tags(AccessRight::plants())->remember($cName, config('app.cache_query_time'), function () {
					return $this->query->get();
				});
			}else{
				$value = Cache::remember($cName, config('app.cache_query_time'), function () {
					return $this->query->get();
				});
			}
			
			$LOG = 'Ini data dari DATABASE - datatables results()';
		}	
		
		if(config('app.debug')){
			// \Log::info("CName: $cName");
			\Log::info($LOG);
        }
		return $value;
    }`
