### ISSUE TITLE
Response show Query 

### ISSUE THREAD

**Issue by salazar94** [yajra/laravel-datatables#2313]
### Response include queries  

![image](https://user-images.githubusercontent.com/16265756/73882563-832a6080-481f-11ea-9c9b-82324353f992.png)

how can i remove it?

### System details

- Laravel Version 6
- Laravel-Datatables Version 9

**Comment by KnightAR** [comment]
The queries output is only if debug is turned on in your app using the APP_DEBUG environment variable, turn off debug in production and it'll never show.
