### ISSUE TITLE
unable to get debug information for loading big number of records from datatable

### ISSUE THREAD

**Issue by andrewsky** [yajra/laravel-datatables#2316]
### Summary of problem or feature request

I wanted to display 78 columns of data from two different table. The column are simple string and numbers.  I had about 15000 records. When i limit the record retrieved to 8500, everything runs fine but when i retrieved the full 15000 records, occasionally i get "allowed memory size of xx bytes exhausted" or i get no debug message and it return a 500 server response error. I am not sure if the returned response hit maximum limit allowed by post response or it s something to do with datatable from server side. I am using pagination and server side processing for datatable but it doesn't solve the problem. Any help is appreciated.

The following is my code  

### Code snippet of problem
```php
$data = DB::select("select xxx,xx,xx.....from table1,table2 where table1.id = table2.foreignkey");
foreach($data as $item){
    ...do some cleaning of each column data
}

echo ("ok"); //this is always printed out..

 $dataDatatable = Datatables::of($data)
                ->setTotalRecords(count($data))          
                ->escapeColumns([])
               ->rawColumns(['name'])
                ->make(true);
echo("rendered ok"); //this is not printed out when number of records is above 8500
return $dataDatatable
-->


### System details
- Operating System :Xampp running in windows 10
- PHP Version : 7
- Laravel Version : 5.5
- Laravel-Datatables Version 1.10.20

**Comment by yajra** [comment]
I think this is more of an environment issue. Try increasing the execution timeout and other php settings for it to be able to handle large datasets in single request.
