### ISSUE TITLE
Search issue with accented characters

### ISSUE THREAD

**Issue by lparede** [yajra/laravel-datatables#2317]
### Summary of problem or feature request
I'm having problem with server side search and accented characters.

I have a table with the following test records:
- testã
- testá
- testà
- test ã
- test á
- test à

If I search for "test a", the datatable show the records:
- test ã
- test á
- test à

But if I search for "testa", it doesn't show me any results ("No matching records found"). But the records counter of the table shows me the info "Showing 1 to 3 of 3 entries (filtered from 6 total entries)".

While debugging the code, I noticed that the SQL returns the rights records, but when I build the datatable data, they disappear .

Is this a bug? Or am I doing something wrong?

Thank you for your help.

### Code snippet of problem

```
// Request table values
$start  = $request->start ?? 0;                 //Start is the offset
$length = $request->length ?? null;             //How many records to show
$column = $request->order[0]['column'] ?? 0;    //Column to orderBy
$dir    = $request->order[0]['dir'] ?? 'asc';   //Direction of orderBy
$search = $request->search['value'] ?? null;    //Search value

// Table columns
$columns = ['name', 'readable_name'];

// Data query
$data = PermissionGroup::select('id', 'name', 'readable_name');

// Total records
$totalRecords = $data->count();

// Search data
if ($search) {
	$search = htmlspecialchars($search, ENT_QUOTES, 'UTF-8');
	$search = explode(' ', $search);
	$search = implode('%', $search);

	$data = $data
		->where('name', 'LIKE', '%' . $search . '%')
		->orWhere('readable_name', 'LIKE', '%' . $search . '%');
}

// Filtered records
$filteredRecords = $data->count();

// Sort data
$orderColumn = $request->columns[$column]['data'] ?? null;

if ($orderColumn && in_array($orderColumn, $columns)) {
	$data = $data->orderBy($orderColumn, $dir);
}

// Chunk data
if ($length) {
	$data = $data->skip($start)->take($length);
}

// Get data
$data = $data->get();

// HERE $data ALWAYS HAVE RESULTS

// Build table data
$tableData = datatables($data)
	->editColumn('readable_name', function ($element) {
		return '<a href="' . route('permission-groups.show', $element->id) . '">'
			. $element->readable_name . '</a>';
	})
	->addColumn('action', function ($element) {
		$actions = '';

		if (auth()->user()->can('edit-permissions')) {
			$actions .= '<a title="' . __('Edit') . '" class="btn btn-info btn-xs" 
				href="' . route('permission-groups.edit', $element->id) . '" 
				role="button">' . __('Edit') . '</a>';
		}

		if (auth()->user()->can('delete-permissions')) {
			$actions .= '<a title="' . __('Delete') . '" class="btn btn-danger btn-xs" 
				href="javascript:SwalConfirm(\''. route('web-api.confirm-permission-group-destroy',
					[app()->getLocale(), $element->id]) . '\');" 
				role="button">' . __('Delete') . '</a>';
		}

		return $actions;
	})
	->rawColumns(['readable_name', 'action'])
	->setTotalRecords($totalRecords)
	->with('filtered', $filteredRecords)
	->skipPaging()
	->toJson();

// IN HERE $tableData DOES'T HAVE RESULTS

return $tableData;
```

### System details
- Operating System: Linux
- PHP Version: 7.3
- Laravel Version: 6.2
- Laravel-Datatables Version: 9.0

**Comment by yajra** [comment]
> If I search for "test a", the datatable show the records:

I think this is because of the package behavior where it will search on multi_term by default. Try setting `'multi_term'  => false` on config if the result would be the same?

On the other hand, not sure on accented characters but maybe try replacing the request search value before processing dataTable. Something like:

```php
// note: code is not tested and just an idea
request()->merge(['search.value' => htmlspecialchars(request('search.value'), ENT_QUOTES, 'UTF-8')]);
```

**Comment by lparede** [comment]
@yajra, thank you for your reply.

> I think this is because of the package behavior where it will search on multi_term by default. Try setting `'multi_term' => false` on config if the result would be the same?
> 

Where should I set this option? In here?

`
let dataTable = $("#users-datatable").DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                stateSave: true,
`

**Comment by lparede** [comment]
@yajra , forget my last post.

I set the 'multi_term' to false, but the problem remains...

**Comment by yajra** [comment]
Have you tried inspecting the generated SQL queries? It will give you more details on how to resolve your issue. 

For complex cases, I usually based my debugging on the queries generated and try to patch it on SQL level first and converting it to Laravel builder when all is working well. The idea is, if it works on SQL, it should work with the package. If not, then maybe a bug somewhere.

**Comment by lparede** [comment]
The SQL is OK. I have try it on phpMyAdmin.

On the code snippet, where I put "// HERE $data ALWAYS HAVE RESULTS", I have results on that stage. But as soon as the results are processed by datatables, It simply does not assume "testa" as "testã".

**Comment by lparede** [comment]
@yajra 

I made a debug, when searching for "testa", and this is what I get:

Before calling tabledata():
`lluminate\Database\Eloquent\Collection {#1015 ▼
  #items: array:1 [▼
    0 => Modules\User\Entities\User {#1016 ▼
      #table: "users"
      #fillable: array:4 []
      #hidden: array:2 []
      #casts: array:1 []
      #connection: "mysql"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:5 [▼
        "id" => 4
        "name" => "Testã"
        "email" => "mail@mail.com"
        "can_be_deleted" => 1
        "deleted_at" => null
      ]
      #original: array:5 []
      #changes: []
      #dates: array:1 []
      #dateFormat: null
      #appends: []
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 []
      #rememberTokenName: "remember_token"
      #forceDeleting: false
      -roleClass: null
      -permissionClass: null
    }
  ]
}`

After calling tabledata():
`{
   "draw":1,
   "recordsTotal":4,
   "recordsFiltered":0,
   "data":[

   ],
   "filtered":1,
   "input":{
      "draw":"1",
      "columns":[
         {
            "data":"name",
            "name":"name",
            "searchable":"true",
            "orderable":"true",
            "search":{
               "value":null,
               "regex":"false"
            }
         },
         {
            "data":"email",
            "name":"email",
            "searchable":"true",
            "orderable":"true",
            "search":{
               "value":null,
               "regex":"false"
            }
         },
         {
            "data":"roles",
            "name":"roles",
            "searchable":"true",
            "orderable":"false",
            "search":{
               "value":null,
               "regex":"false"
            }
         },
         {
            "data":"action",
            "name":"action",
            "searchable":"false",
            "orderable":"false",
            "search":{
               "value":null,
               "regex":"false"
            }
         }
      ],
      "order":[
         {
            "column":"0",
            "dir":"asc"
         }
      ],
      "start":"0",
      "length":"10",
      "search":{
         "value":"testa",
         "regex":"false"
      },
      "_token":"nhYOXOPhCdM7OHxWACCDijOJHVUHs7EgTcgENgoe",
      "filterDeleted":"hide",
      "filterRole":null,
      "_":"1582896382372"
   }
}`

As you can see, the field 'data' is empty.

**Comment by yajra** [comment]
Just realized that you are using collection and you are also performing a manual search before passing it to datatables. I think you just need to disable the search function of dataTable by using the `filter` api.

```php
$tableData = datatables($data)->filter(function() {})->.....
```

**Comment by lparede** [comment]
@yajra , it works!!!

I do has you have told me. I just added `->filter(function() {})->`, without any arguments and it work!

In previous attempts, I have tried to use the filter. The only problem was that I was adding arguments to filter the data and could not get the results that I wanted.

Thank you so much for your support! :)

You can close this thread.
