### ISSUE TITLE
Search box throwing error on Model::with('relationships') Laravel 5.7

### ISSUE THREAD

**Issue by fingersandmind** [yajra/laravel-datatables#2319]
### Search box is not working on tables that has a relationship on it.

If I use 
###Mode::with('relationships')->get()' 
it works but loading is slow.
If I use 
###Model::query()->with('relationships')
 loads fast but search box throws an error.

- Using yajra package ~8.0
- Laravel version 7.1

**Comment by yajra** [comment]
Better inspect the ajax request to get a hint on what was causing the error. 

See https://datatables.yajrabox.com/eloquent/relationships too for ref.
