### ISSUE TITLE
Orering don't work with relationship column

### ISSUE THREAD

**Issue by 3s777** [yajra/laravel-datatables#2320]
Sorry for my english
I'm make column Role for table Users. Role is relationship with table User.
Every columns is orderable and work fine, except column role. This column showing data of role, but don't work order. Error DataTables warning: table id=users-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

Search work fine.

My code

```
    public function dataTable($query)
    {
        return datatables()
            ->eloquent($query)
            ->addColumn('action', function($user){
                return view('users.includes.action', compact('user'));
            })
            ->addColumn('roles', function (User $user) {
                return $user->roles->map(function($role) {
                    return str_limit($role->name, 300, '...');
                })->implode('<br>');
            });
    }
```
`
$model->newQuery()->with('roles:id,name');`

```
    protected function getColumns()
    {
        return [
            Column::make('id'),
            Column::make('name')->title('Имя'),
            Column::make('email'),
            Column::make('created_at')->title('Добавлен')->width(60),
            Column::make('roles','roles.name')->title('Роль'),
            Column::computed('action')
                ->exportable(false)
                ->printable(false)
                ->width(300)
                ->addClass('text-center'),
        ];
    }
```

Thanks for help

- PHP Version 7.2.0
- Laravel Versionla 6.11.0
- Laravel-Datatables Version 1.5

**Comment by RyanPriceDotCa** [comment]
If you follow the diagnosis steps from https://datatables.net/manual/tech-notes/7 what is the response from the request?

Is your name column nullable?  I have had issues with ordering on relations if there are null values, in which case you can solve it by writing your own orderColumn() function for that column: 
https://yajrabox.com/docs/laravel-datatables/master/order-column

**Comment by 3s777** [comment]
Thanks, but for me it's doesn't work.
I tried use orderColumn but it's don't work too
Column is not nullable.
Data in table work, search work, sort by click on table header Role don't work.
In console error 500

**Comment by RyanPriceDotCa** [comment]
Console error 500 indicates there was something server-side that went wrong.  Take a look at your server logs (apache error logs, if it's apache) and see what is causing the 500 error.  Your issue will likely be clear from that.

**Comment by 3s777** [comment]
In log i have error
[18-Feb-2020 17:04:58 UTC] PHP Fatal error:  Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Missing required parameters for [Route: users.show] [URI: users/{user}]. (View: F:\Server\domains\dnk.loc\resources\views\users\includes\action.blade.php) in F:\Server\domains\dnk.loc\vendor\yajra\laravel-datatables-oracle\src\Utilities\Helper.php on line 0

i remove $user from action.blade.php

and now i have other error 
DataTables warning: table id=users-table - Requested unknown parameter 'id' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

Ordering after error is working, but table is empty.
Screen before ordering 
![image](https://user-images.githubusercontent.com/16633006/74760538-9f9cb300-528b-11ea-8461-d68b8496ec32.png)

Screen after ordering
![image](https://user-images.githubusercontent.com/16633006/74760595-b511dd00-528b-11ea-8d69-158dfdc80903.png)

**Comment by 3s777** [comment]
if i understand rightp, my User model after ordering is removing

**Comment by RyanPriceDotCa** [comment]
I would give orderColumn() a second try at this point.

Something along the lines of:

```php
    public function dataTable($query)
    {
        return datatables()
            ->eloquent($query)
            ->addColumn('action', function($user){
                return view('users.includes.action', compact('user'));
            })
            ->addColumn('roles', function (User $user) {
                return $user->roles->map(function($role) {
                    return str_limit($role->name, 300, '...');
                })->implode('<br>');
            })->orderColumn('roles', function ($query, $order) {
                    $query->orderBy('roles.name', $order);
            });
    }
```

Not sure if it will know roles.name column, you may need to do a join first.  Something like this...

```php
$query->join('roles', 'users.role_id', '=', 'roles.id')->orderBy('roles.name', $order);
```

**Comment by 3s777** [comment]
Thanks for help, but it still doesn't work. Same error. And with join too

**Comment by bumbummen99** [comment]
I have had a similar issue. I was using a base model with a related Entry that has a related User and a related Role, the DataTable can sort booth names. Problem is that if i do so the data in the addColumn method is not of type Entry in m case but of type User if i sort by user name or Role if i sort by role name. What happens is that it does get the atributes/row of these related models and does cast it into the model i used as type for the callback. This is because it is $row, not $model. This was my code.

```php
return DataTables::eloquent($adminconfig->entries()->with('user', 'serverGroup'))
                ->addColumn('name', function (AdminConfigEntry $entry) {
                    return view('admin.adminconfigs.parts.name', [
                        'user' => $entry->user,
                    ])->render();
                })
                ->addColumn('group', function (AdminConfigEntry $entry) {
                    return $entry->serverGroup->name;
                })
                ->addColumn('actions', function (AdminConfigEntry $entry) use ($adminconfig) {
                    return view('admin.adminconfigs.parts.actions', [
                        'adminConfig' => $adminconfig,
                        'entry' => $entry,
                    ])->render();
                })
                ->rawColumns(['name, 'actions'])
                ->make();
```

As mentioned in the docs, using `$adminconfig->entries()->select('admin_config_entries.*')` as the query, makes sure that you get the correct row data to be cast to a model. Make sure to select the correct data when working with relations and DataTables.
