### ISSUE TITLE
Null request value

### ISSUE THREAD

**Issue by ayman-elmalah** [yajra/laravel-datatables#2322]
### Summary of problem or feature request

I'm using yajra datatables class that generated using > php artisan datatables:make ClassDatatable
and in query when writing request('key') and this key is in query string it's return null 
It's just happen since 1 month

### Code snippet of problem

query = $competition->inClub();
        $query = request('date_from') ? $query->where('date_from', '>=', request('date_from')) : $query;
        $query = request('date_to') ? $query->where('date_to', '<=', request('date_to')) : $query;
        $query = $query->get();

### System details

- Operating System macos
- PHP Version 7.4
- Laravel Version 6.x
- Laravel-Datatables Version 
        "yajra/laravel-datatables": "^1.5",
        "yajra/laravel-datatables-oracle": "^9.7",

**Comment by yajra** [comment]
Thank you for reporting, it seems like the fix I made on https://github.com/yajra/laravel-datatables-html/commit/acf3aeb5c14038fa80163396d56f8794c596382f is the culprit. Applying a patch now.

**Comment by yajra** [comment]
Please update to html package v4.21.1. Thanks!

**Comment by ayman-elmalah** [comment]
Thank you for your fix  @yajra 

It sill have error when the page is secure, the request is sent in http and return this error

Mixed Content: The page at 'https://' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://'. This request has been blocked; the content must be served over HTTPS.

**Comment by AdrienPoupa** [comment]
I have the same error as @ayman-elmalah since the commit. Please revert @yajra
