### ISSUE TITLE
orderBy in Eloquent query.

### ISSUE THREAD

**Issue by SPQRBrutus** [yajra/laravel-datatables#2323]
Hello,

when I use Eloquent Data Source with selectRaw I must have orderBy in querry otherwise it crash on this error:

`Exception Message: sasql_query(): SQLAnywhere: [-143] Column 'agentura_kobchodnik' not found (SQL: select count(*) as aggregate from (select '1' as "row_count" from "hist_klient" where ("kobchodnik" = AdminIstrator or "hdalsi_zucast" like %AdminIstrator,% or "agentura_kobchodnik" = AdminIstrator or "klient_kobchodnik" = AdminIstrator)) count_row_table)`

So I can't use datatables sorting.

### Code snippet of problem

Select:
```php
$histClients = HistKlient::with("agency", "client")
            ->select(
                "histk_id",
                "hdd",
                "hrelod",
                "hkdlzka",
                "hakcia",
                "hsdd",
                "hsrelod",
                "hksdlzka",
                "hstav",
                "kobchodnik",
                "hvysledokc",
                "htyp",
                "hokruh",
                "hagentura_id",
                "hklient_id",
                "hdalsi_zucast",
                DB::raw("(SELECT IsNull(klienti.kobchodnik,'') FROM klienti WHERE hist_klient.hagentura_id = klienti.klient_id) agentura_kobchodnik"),
                DB::raw("(SELECT IsNull(klienti.kobchodnik,'') FROM klienti WHERE hist_klient.hklient_id = klienti.klient_id) klient_kobchodnik"),
                DB::raw("(SELECT klienti.knazov FROM klienti WHERE hist_klient.hagentura_id = klienti.klient_id) agentura"),
                DB::raw("(SELECT klienti.knazov FROM klienti WHERE hist_klient.hklient_id = klienti.klient_id) klient")
            )
            ->where("kobchodnik", auth()->user()->identify_name)
            ->orderBy("hdalsi_zucast");
```

Datatable:

```php
return Datatables::of($histClients)
                ->filterColumn('client', function($query, $keyword) {
                    $sql = "LOWER(klient) like ?";
                    $query->whereRaw($sql, ["%".strtolower($keyword)."%"]);
                })
                ->filterColumn('agency', function($query, $keyword) {
                    $sql = "LOWER(agentura) like ?";
                    $query->whereRaw($sql, ["%".strtolower($keyword)."%"]);
                })
                ->setRowClass(function(HistKlient $histClient) {
                    if($histClient->kobchodnik != auth()->user()->identify_name) {
                        return 'text-muted';
                    }
                })
                ->orderColumn("hdd", function($query, $order) {
                    $query->orderBy("hdd", $order)->orderBy("hrelod", $order);
                })
                ->orderColumn("hsdd", function($query, $order) {
                    $query->orderBy("hsdd", $order)->orderBy("hsrelod", $order);
                })
                ->rawColumns(["hdd", "hsdd", "action"])
                ->make(true);
```

### System details

- Operating System: Win 10
- PHP Version: 7.3.8
- Laravel Version: 6
- Laravel-Datatables Version: 9

**Comment by yajra** [comment]
I think you also included `agentura_kobchodnik` on your displayed columns but forgot to include `searchable: false`. agentura_kobchodnik is a computed column and search is not working afaik on that case.

```js
columns: [
    ...
    {data: 'agentura_kobchodnik', searchable: false}
]
```

**Comment by SPQRBrutus** [comment]
> 
> 
> I think you also included `agentura_kobchodnik` on your displayed columns but forgot to include `searchable: false`. agentura_kobchodnik is a computed column and search is not working afaik on that case.
> 
> ```js
> columns: [
>     ...
>     {data: 'agentura_kobchodnik', searchable: false}
> ]
> ```

Thanks for answer.

But no, I got it only where condition. If I don't have orderBy in query the count of rows query fails. When I moved this inline select to join and not using "as" in select it working. But can't do it in every case.
