### ISSUE TITLE
Question : Set Total Records, Skip Total Records, setFiltered records does it also work with DB?

### ISSUE THREAD

**Issue by benyaminl** [yajra/laravel-datatables#2326]
Reffered to #578 and #779

### Summary of problem or feature request

I use skipTotalRecords(), setTotalRecords(0), and setFilteredRecords(0) but the datatables class still query agregate to get the result count. Is there I'm missing here?
![image](https://user-images.githubusercontent.com/2817332/75003400-26bf7600-549a-11ea-81ed-01ed62e137dc.png)

But when I dd the datatables object 
![image](https://user-images.githubusercontent.com/2817332/75003691-44d9a600-549b-11ea-94c6-9441fdc4f990.png)
The skipTotalRecords are true and I think it should return the set record or even not doing anything at all on
https://github.com/yajra/laravel-datatables/blob/9.0/src/QueryDataTable.php#L158-L167
and https://github.com/yajra/laravel-datatables/blob/9.0/src/QueryDataTable.php#L158-L167
But seems it's not working instead still query the agregate that cause slow process of datatables. 
### Code snippet of problem

```php
// @see https://yajrabox.com/docs/laravel-datatables/master/engine-query
        $db = DB::table("mhcustomer", "c")
                ->select(["c.nomor", "kode_hokky", "nama", "telepon_hp", "s.point", "s.point_tier"])
                ->join(DB::raw("(select `s`.`nomormhcustomer`,
                    sum(s.jumlah) as point,
                    sum(s.jumlah_tier) as point_tier
                from
                    tsaldo_membership s
                group by s.nomormhcustomer) as `s`"), "s.nomormhcustomer", "=", "c.nomor");
                
        return DataTables::of($db)        
                ->skipTotalRecords()
                ->setTotalRecords(0)
                ->setFilteredRecords(0)
                // see @https://datatables.yajrabox.com/eloquent/post-column-search
                // see @https://datatables.yajrabox.com/fluent/custom-filter untuk cata SULIT
                // terpaksa kalau kolomnya agregate kaya sum, count, iffnul, dll, tapi kalau ga, pakai get cukup
                // @see https://datatables.yajrabox.com/relation/has-one
                // Itu untuk Kasus Pakai Relationship nambah kolom, jadi ga perlu raw query
                ->setTransformer(function($item){

                    return [
                        'nomor'         => $item->nomor,
                        'kode_hokky'    => $item->kode_hokky,
                        'nama'          => $item->nama,
                        'telepon_hp'    => $item->telepon_hp,
                        'point'         => $item->point,
                        'point_tier'    => $item->point_tier,
                        'tier'          => ''
                    ];
                })
                ->make(true);
```

### System details

- Operating System : Windows 10 1909
- PHP Version : php 7.4
- Laravel Version : 6.x
- Laravel-Datatables Version : 1.5.0 (9.8.0)

**Comment by benyaminl** [comment]
Seems the answer is the param of the skipTotalRecords should be bigger than 0 and the setFilteredRecords also should be bigger than zero.

**Comment by dhcmega** [comment]
@benyaminl hi! have you figured this out? I'm having the same problem. Thanks!
