### ISSUE TITLE
Latest version not working on https connection

### ISSUE THREAD

**Issue by ayman-elmalah** [yajra/laravel-datatables#2327]
### Summary of problem or feature request

I updated my version today and it have an issue on https connection it was worked before but after update this error showing to me

Mixed Content: The page at 'https://' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://'. This request has been blocked; the content must be served over HTTPS.

I'm using yajra datatables class that generated using > php artisan datatables:make ClassDatatable

### System details

- Operating System
- PHP Version 7.4
- Laravel Version 6.x
- Laravel-Datatables Version
"yajra/laravel-datatables": "^1.5",
"yajra/laravel-datatables-oracle": "^9.7",

**Comment by yajra** [comment]
I think this is an issue on the URL helper and can be fixed using `URL::forceScheme('https')` as per SO post https://stackoverflow.com/questions/24426423/laravel-generate-secure-https-url-from-route?

**Comment by yajra** [comment]
This might also help https://rtmccormick.com/2017/07/21/force-assets-to-use-https-laravel/.

**Comment by ayman-elmalah** [comment]
I already force https and it was working in https before this update
Now its not working after update

**Comment by ayman-elmalah** [comment]
Thanks, it's working

**Comment by devfelipereis** [comment]
If you are already forcing https, add this **$this->app['request']->server->set('HTTPS', true);** to the register method.

```
<?php

namespace App\Providers;

use Illuminate\Routing\UrlGenerator;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app['request']->server->set('HTTPS', true);
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(UrlGenerator $url)
    {
        if (config('app.force_https')) {
            $url->forceScheme('https');
        }
    }
}
```

**Comment by 27terminal** [comment]
Thanks, @devfelipereis It's working

**Comment by parthkharecha** [comment]
Thanks, @devfelipereis  It's working

**Comment by Nemachtilli** [comment]
It works in production, but in local it does not load the styles and launches the following in the console:

Invalid request (Unsupported SSL request)

`if (config('app.env') === 'production') {
        config('app.force_https');
        \URL::forceScheme('https');
    }`
 
I created a simpler conditional that works locally and in production

**Comment by rsee49** [comment]
Thanks, @devfelipereis It's working. After more then two years!!

**Comment by kkimerag** [comment]
Thank you @devfelipereis

**Comment by umair975** [comment]
having same issue but the URL is loading over http with port 443 thats suppose to be https

Mixed Content: The page at 'https://manager.anc.net/public/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://manager.abc.net:443/public/'. This request has been blocked; the content must be served over HTTPS.

**Comment by umair975** [comment]
after forcing https using headers. There is no more mixed content errors but data tables is still not loading any data over https

**Comment by umair975** [comment]
@yajra can u pls help with this.
