### ISSUE TITLE
How can one change the Font-family for the PDF export feature 

### ISSUE THREAD

**Issue by christonjones** [yajra/laravel-datatables#2329]
### How can one change font-family for all the PDF export for all tables

I am using the buttons 'copy', 'csv', 'excel', 'print', 'pdf' with my table. I have a monospaced font-family set for my datatable display to the screen but when I export to PDF the font family changes for the PDF and is no longer monospaced.  I need the have the PDF font monospaced so that each character or space takes up equal space to enable simple visual analysis of the column data when viewing the PDF. 

I have searched and tested different locations in many of the plugins/datatables css files but have not found the proper location to either change or override  the font-family. Where in the code is the proper location to change the setting of the font-family for all of the datatables PDF exports?

- Operating System - windows
- PHP Version - PHP 7.3
- Laravel Version - 5.8
- Laravel-Datatables Version - 9.7

**Comment by yajra** [comment]
The dataTable class has a printPreview prop which declares the view path that is being used to print and export to pdf. You override this prop to something else or you can override the actual view being used.

```php
abstract class DataTable implements DataTableButtons
{
    /**
     * DataTables print preview view.
     *
     * @var string
     */
    protected $printPreview = 'datatables::print';
```

See https://github.com/yajra/laravel-datatables-buttons/blob/4.0/src/resources/views/print.blade.php for the default view.

**Comment by christonjones** [comment]
Thanks!
