### ISSUE TITLE
Post column search

### ISSUE THREAD

**Issue by butoibogdan** [yajra/laravel-datatables#233]
Can I search on column via concatenate. In your example not working to search in column its working only in general search. 
Thank you very much.
http://datatables.yajrabox.com/eloquent/post-column-search

**Comment by yajra** [comment]
Column search is doing an exact match search on that example. If you wanted a wildcard search then I think you should do something like below instead. (Enclose `$1` with `%`).

```php
->filterColumn('user_id', 'whereRaw', "CONCAT(users.id,'-',users.id) like ?", ["%$1%"])
```
On the other hand, I think `$1` should use the same value as global search. Will review this specification as this may need an enhancement on the code. Thanks for reporting!

**Comment by yajra** [comment]
It's using an exact search because the demo uses `regex` flag as `true`. Use false on regex to enable wildcard search. Will update the demo too. Thanks!

```js
// wild card search
column.search(val ? val : '').draw();

// exact search... regex search
column.search(val ? val : '', true, false).draw();
```

**Comment by butoibogdan** [comment]
Thank you very much
Have a nice day.
