### ISSUE TITLE
Compound database primary key

### ISSUE THREAD

**Issue by cent89** [yajra/laravel-datatables#2330]
Hi, I have two models with a BelongsToMany relationship and a pivot value.
I can show the right table, with all fields, but I can't edit the pivot value. The problem, I think, is that the relation table has two primary key:

```
ricetta_id | ingrediente_id | qta
```
How I can define an array of rowId? Like here: https://editor.datatables.net/examples/advanced/compoundKey.html

Thanks!

**Comment by yajra** [comment]
Not supported and I think laravel doesn't support composite key too last time I checked. I suggest you add an incrementing column if possible. Thanks!

**Comment by backstageel** [comment]
Actually Laravel now supports Composite Primary Keys: https://laravel.com/docs/7.x/migrations

**Comment by yajra** [comment]
I think it's only on migration but not on Eloquent per se.
