### ISSUE TITLE
Laravel 7.0 Yajra datatables is not working

### ISSUE THREAD

**Issue by yashweb3** [yajra/laravel-datatables#2335]
### Code snippet of problem
![image](https://user-images.githubusercontent.com/48712509/75786048-b1518080-5d8a-11ea-92a5-3f9b9c01f43c.png)

### System details

- Operating System Windows
- PHP Version 7.2
- Laravel Version 7.0
- Laravel-Datatables Version latest (v9.8.0)

**Comment by adiletmaks** [comment]
Because, laravel 7 support has not been yet been added.

here PR https://github.com/yajra/laravel-datatables/pull/2332

**Comment by yashweb3** [comment]
> Because, laravel 7 support has not been yet been added.
> 
> here PR #2332

any idea when I can use Yajra datatable in Laravel 7.0

**Comment by adiletmaks** [comment]
> > Because, laravel 7 support has not been yet been added.
> > here PR #2332
> 
> any idea when I can use Yajra datatable in Laravel 7.0

Released on v9.9.0.
