### ISSUE TITLE
use Osearch to fill default value from other page

### ISSUE THREAD

**Issue by mbilal-12** [yajra/laravel-datatables#2340]
Basically I need to know how to fill search field automatically based on the data from other page.

Here is my search column 
![image](https://user-images.githubusercontent.com/59948166/76425908-dffbd680-63dc-11ea-95c8-f054efd4b439.png)

So the objective is after user click Store link, it will bring to datatable. Here is the screeenshoot :
![image](https://user-images.githubusercontent.com/59948166/76426103-2cdfad00-63dd-11ea-9cd2-62cb72736944.png)

nah I need to put search field with merchant id from my search column, so user only can see store that related to specific merchant id. is there any way to do it with laravel datatable?

i am using laravel 7 btw.

Thank you

**Comment by yajra** [comment]
I think you can use a js for this and trigger search on load.

Not tested but maybe something like:

```php
// on ready
oTable.search('{{ request('data_from_other_page') }}')
```
