### ISSUE TITLE
Modify generated $dataTable->scripts()

### ISSUE THREAD

**Issue by akilrezaputra** [yajra/laravel-datatables#2348]
Hi,

i have a problem, when i generate scripts using $dataTable->scripts(), the searchbox didnt show up. so i try to move the generated scripts to my master layout, but the problem still exist. then i try modifying
`<script type="text/javascript">
  (function(window, $) {
    window.LaravelDataTables = window.LaravelDataTables || {};
         ....
})(window, jQuery);
</script>`
on the begining of generated script, then changed it to :
`<script type="text/javascript">
$(document).ready(function () {
    window.LaravelDataTables = window.LaravelDataTables || {};
         ....
});
</script>`

can i modify the output of generated scripts like above?

**Comment by Nacoma** [comment]
Once you've published the view assets you will be able to edit the generated script template in `resources/views/vendor/datatables/script.blade.php`.

You may want to ensure that the global search box is enabled in the `dom` option: https://datatables.net/reference/option/dom

You should also be able to set global defaults without modifying the template to ensure that the `dom` options is set to what you want: https://editor.datatables.net/manual/options#Setting-defaults

**Comment by Vidagdha** [comment]
How to publish the view assets

**Comment by Nacoma** [comment]
As long as you have `yajra/laravel-datatables-html` installed and the service providers registered (automatic in later versions of laravel), run `php artisan vendor:publish --tag=datatables`
