### ISSUE TITLE
Rownum, missing or invalid option

### ISSUE THREAD

**Issue by TwinLight** [yajra/laravel-datatables#235]
Hello, here is my code,
![image](https://cloud.githubusercontent.com/assets/9023187/10932135/1258cc3c-8309-11e5-9f7a-d08398a5a579.png)

But i got an error about set @rownum=0 
![image](https://cloud.githubusercontent.com/assets/9023187/10932143/2e8edfae-8309-11e5-8192-670fafd9e412.png)

It is about my way of doing it was different than yours? Because on your tutorial it, you will grab the data from model its  but mine from DB model. And currently I'm using Oracle 11g R2 XE.

**Comment by yajra** [comment]
@TwinLight, that demo is only applicable on MySQL. For oracle, you can just select `rownum`.

**Comment by TwinLight** [comment]
Works like charm. Thnak you
