### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by saadaan** [yajra/laravel-datatables#2352]
Hi,

I have a not-too-big table with 100k entries. But when trying to pull it via your plugin, it is giving following error (I am just displaying on page, not exporting to excel):

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/aaaaa/vendor/yajra/laravel-datatables-oracle/src/Processors/DataProcessor.php on line 263
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/aaaaa/vendor/symfony/debug/Exception/FatalErrorException.php on line 1

Any solution for this please?

Many thanks,
Saad Omer

**Comment by yajra** [comment]
I just updated the package and added support for `fast-excel`. See https://github.com/yajra/laravel-datatables-buttons/pull/124 and give it a try if you can. I only tested using 20k rows while developing it.

Feedbacks appreciated. Thanks!

**Comment by farindra** [comment]
i had the same problem, i was using "yajra/laravel-datatables": "^9.0" php 8.0 and laravel 9, this problem didn't happen on "yajra/laravel-datatables-oracle": "^8.7" php 7.4, strangely this it only happens to some tables.

**Comment by maxLeet** [comment]
Has anyone tried lazy load?
