### ISSUE TITLE
Case When in Select not doing Else

### ISSUE THREAD

**Issue by mrkvici** [yajra/laravel-datatables#2357]
### Summary of problem or feature request

I'm doing a SELECT with the total value of a certain column but using a CASE for determining the equation to be use. My problem is when the total is render, it skips the ELSE statement but when I add GROUPBY(total) it shows that the case did work. Is the CASE function only does the check once and is there any other options for doing this check? By the way im using SQLite3.

### Code snippet of problem

```php
                return datatables()->of(Order::join('order_details', 'orders.id', '=', 'order_details.order_id')
                                ->join('menu_categories', 'menu_categories.id', '=', 'order_details.category_id')
                                ->select(DB::raw("description, sum(quantity) as qty, category_name,
                                (CASE WHEN order_details.senior_dc < 1 THEN sum((quantity*price*(1+($vat)))) ELSE sum(quantity*price-order_details.senior_dc) END) as total"))
                                ->whereDate("order_details.created_at", "=", date('Y-m-d', strtotime($d5)))
                                ->where('order_details.deleted_at', NULL)
                                ->where('status', 'Completed')
                                ->groupBy('product_id')
                                ->get())
                                ->make(true);
```
### System details

- Operating System: Windows 7
- PHP Version: 7.1.3
- Laravel Version: 5.8
- Laravel-Datatables Version: 9.0

**Comment by benyaminl** [comment]
> 
> ### Summary of problem or feature request
> 
> I'm doing a SELECT with the total value of a certain column but using a CASE for determining the equation to be use. My problem is when the total is render, it skips the ELSE statement but when I add GROUPBY(total) it shows that the case did work. Is the CASE function only does the check once and is there any other options for doing this check? By the way im using SQLite3.
> ### Code snippet of problem
> 
> ```
>                 return datatables()->of(Order::join('order_details', 'orders.id', '=', 'order_details.order_id')
>                                 ->join('menu_categories', 'menu_categories.id', '=', 'order_details.category_id')
>                                 ->select(DB::raw("description, sum(quantity) as qty, category_name,
>                                 (CASE WHEN order_details.senior_dc < 1 THEN sum((quantity*price*(1+($vat)))) ELSE sum(quantity*price-order_details.senior_dc) END) as total"))
>                                 ->whereDate("order_details.created_at", "=", date('Y-m-d', strtotime($d5)))
>                                 ->where('order_details.deleted_at', NULL)
>                                 ->where('status', 'Completed')
>                                 ->groupBy('product_id')
>                                 ->get())
>                                 ->make(true);
> ```
> 
> ### System details
> 
>     * Operating System: Windows 7
> 
>     * PHP Version: 7.1.3
> 
>     * Laravel Version: 5.8
> 
>     * Laravel-Datatables Version: 9.0

no that shouldn't. Try to 

```php
Order::join('order_details', 'orders.id', '=', 'order_details.order_id')
                                ->join('menu_categories', 'menu_categories.id', '=', 'order_details.category_id')
                                ->select(DB::raw("description, sum(quantity) as qty, category_name,
                                (CASE WHEN order_details.senior_dc < 1 THEN sum((quantity*price*(1+($vat)))) ELSE sum(quantity*price-order_details.senior_dc) END) as total")->toSql()
```

First and run on your database client and see if it's right query, I think this's not a DataTable issue
