### ISSUE TITLE
minifiedAjax and isColumnSearchable - column search doesn't work together

### ISSUE THREAD

**Issue by mgralikowski** [yajra/laravel-datatables#2359]
### Summary of problem

`minifiedAjax()` method remove `searchable` `true` flag from request, but this attribute is validated in method `isColumnSearchable` so we get incorrect result. I think we need to check for a true or not set attribute in `isColumnSearchable` method.

This method is used in column individual search functionality, I was forced to remove in my class.

### System details

- Operating System Win/Lin
- PHP Version 7.3
- Laravel Version 5.8
- Laravel-Datatables Version 9.0

**Comment by yajra** [comment]
If I remember correctly, we default to `true` if searchable flag is not set from request. Did we miss on `isColumnSearchable`?

**Comment by mgralikowski** [comment]
`$this->request->input("columns.$i.searchable", 'true') === 'true' || $this->request->input("columns.$i.searchable", 'true') === true`

Above condition doesn't take into consideration empty `searchable` input.
