### ISSUE TITLE
Recieving ajax error when loading JSON data

### ISSUE THREAD

**Issue by aleary06** [yajra/laravel-datatables#236]
Hi all,

On the site I'm working on, I wanted to use this package to run Datatables on one of my pages (it's a Laravel 5.1 site). To test out the implementation, I've been working with the Users table. Unfortunately, when I try to navigate to that page, I get the following error:

    DataTables warning: table id=user-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I've tried a couple of different things, but here's my current code:

DatatablesController:

```php
class DatatablesController extends Controller
{
    ...
  
    public function getUserData()
    {
        $users = User::select(['id', 'name', 'email', 'created_at', 'updated_at'])->get();
        return Datatables::of($users)->make(true);
    }
}
```
routes:
```php
...

Route::controllers([
    'datatables' => 'DatatablesController',
]);

// previous route:
Route::controller('datatables', 'DatatablesController', [
    'getUserData' => 'datatables.data',
    'getIndex' => 'datatables',
]);
```
master.blade:
```javascript
...

$(document).ready(function() {
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url("datatables/user-data") }}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'created_at', name: 'created_at' },
            { data: 'updated_at', name: 'updated_at' }
        ]
    });
});
```
and in Index:
```html
...

<table class="table table-bordered" id="users-table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Created At</th>
            <th>Updated At</th>
       </tr>
    </thead>
</table>
```
When I open the debugger in the browser, the call to datatables/user-data throws a 404 error. However for the sake of testing when I add a route to run the getUserData function when the root directory is navigated to (localhost/testSite/public/), the raw JSON data is output to the screen. This is the route that causes that to occur:
```php
Route::get('/', ['as' => 'userData', 'uses' => 'DataTablesController@getUserData']);
```
Does anyone see where the issue in my approach is? I believe it's in issue with the routes since the JSON string is being created properly in the controller, but even if I follow the quick start guide word for word, I can't get this table populated with the data from my users table. Any help that could be provided would be greatly appreciated.

Thanks!

**Comment by yajra** [comment]
@aleary06, I suggest you use firebug on chrome's dev tools and inspect the ajax response of Laravel so you can have a better view of what was causing the error. Or paste the error response here so we can evaluate further.

Also, were you able to import the `User` class on your controller? Something like `use App\User;`? You can also remove the `->get()` method on your query. And you misspelled `Datatables`. (Datatales)

```php
use App\User;
use Datatables;

class DatatablesController extends Controller
{
    ...

    public function getUserData()
    {
        $users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);
        return Datatables::of($users)->make(true);
    }
}
```

**Comment by aleary06** [comment]
Hi yajra, thanks for the response. 

I was importing the User class properly and I think Datatables was just accidentally misspelled when I was editing my post here, because it was correct in my code. I removed the `->get()` method from my query, but I'm still having the same issue. I don't think the issue is in my controller though, because I can get the raw JSON to output to the screen (see first attached image) which tells me that the getUserData() method is probably working as I'd expect it to. Alternatively, the second attached image shows what Firebug has to say about the call to `datatables/user-data`. As I mentioned in my initial post, it throws up a 404 error, but since I know that getUserData is generating the JSON string, my thinking is that the issue lies in how I have my route set up.

Thanks again!

![raw_json](https://cloud.githubusercontent.com/assets/11541037/10971657/58b0c622-83a3-11e5-9153-131b2e5f5a4f.PNG)

![firebug_output](https://cloud.githubusercontent.com/assets/11541037/10971663/647c106a-83a3-11e5-84a8-4ace240e8d48.PNG)

![error_message](https://cloud.githubusercontent.com/assets/11541037/10971670/6815a678-83a3-11e5-839f-3cf6b10aea73.PNG)

**Comment by aleary06** [comment]
On a side note, I set up the demo site this morning. After creating the following route:

```php
Route::get('/', 'CollectionController@getBasic');
```
I get the same Ajax error message:

![demo_site](https://cloud.githubusercontent.com/assets/11541037/10972968/8e8fb1f8-83a9-11e5-9d7e-6645d524769b.PNG)

**Comment by aleary06** [comment]
I was just able to find the solution, and it had nothing to do with the code I wrote. There was an issue in the web.config file that was causing issues with the URL routing (the `MapRequestHandler` error I was getting was what led me to figure it out). Anyway, looks like I'm all set for now. Thanks again yajra for taking the time to respond to me!

**Comment by luizpatrocinio** [comment]
Hello I'm the same problem above. And if you update several times works.
My js:
$(function() {
    $('#tabela').DataTable({
        "processing": true,
        "serverSide": true,
        "language": { "url": "/datatables/pt.br" },
        "ajax": "/audiencia/api/",

        "columns":
        [
        { data: "processo" },
        { data: "cliente" },
        { data: "tel" },
        { data: "cparte" },
        { data: "dtaudiencia" },
        { data: "hraudiencia" },
        { data: "local" },
        { data: "tipo" },
        { data: "action", name: "action", orderable: false, searchable: false }
        ]
    });
});


![error](https://cloud.githubusercontent.com/assets/16004201/16938641/1657d116-4d48-11e6-9e69-90b88d8997c1.jpg)

Tks Yajra.

**Comment by dibya325** [comment]
I have also same problem ... Please anybody  guide to fix it ... In advance Thanks

**Comment by NightravenJames** [comment]
aleary06 at least tell us what you did in the web.config file

**Comment by tcibikci** [comment]
Hi @aleary06 Can you share the solution to the problem? I have that same problem.

**Comment by redionallaraj** [comment]
hello

**Comment by redionallaraj** [comment]
i want to add 2buttons in each row of a datatable..how to do that plz?

**Comment by yunishawash** [comment]
Just change the ajax type from 'get' to 'post'

```
processing: true,
        serverSide: true,
        ajax: {
          url: 'localhost:8000/api/v1/cities',
          type: 'post',
```
