### ISSUE TITLE
Class App\DataTables\indiaDataTable does not exist

### ISSUE THREAD

**Issue by shivamIndian** [yajra/laravel-datatables#2360]
### Summary of problem or feature request

**I am having trouble loading up DataTable class that does exist in infyom laravel
![errordatatable1](https://user-images.githubusercontent.com/41446454/79051026-7d039680-7c4b-11ea-9627-472af77e953b.png)
![errordatatable2](https://user-images.githubusercontent.com/41446454/79051049-91479380-7c4b-11ea-8e55-27c9cf8aef7a.png)
![errordatatable3](https://user-images.githubusercontent.com/41446454/79051054-986ea180-7c4b-11ea-9b8f-75708cc2b52b.png)
![errordatatable4](https://user-images.githubusercontent.com/41446454/79051058-9c9abf00-7c4b-11ea-91a8-77ca56341b65.png)

**

I have tried

- composer dump-autoload
- 
- composer dump-autoload -o
- 
- php artisan cache:clear
- 
- php artisan config:clear
- 

- Renamed my project folder and ran
- 
- composer update
- 

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
Maybe a case sensitive filename issue?
