### ISSUE TITLE
Prevent show all data

### ISSUE THREAD

**Issue by yaelahan** [yajra/laravel-datatables#2363]
### How to prevent all data if base of endpoint hit (without query string) ?
as we know datatable will return data belongs to query string (limit, offset, etc) sends by ajax. how to prevent if someone access endpoint without query string ?

in code below, paging/limit will run if **Paginationable** and **not skipPaging**
[https://github.com/yajra/laravel-datatables/blob/9.0/src/DataTableAbstract.php#L712](https://github.com/yajra/laravel-datatables/blob/9.0/src/DataTableAbstract.php#L712)

**isPaginationable** will run if req->start != null & req->length != null & req->length != -1
[https://github.com/yajra/laravel-datatables/blob/9.0/src/Utilities/Request.php#L230](https://github.com/yajra/laravel-datatables/blob/9.0/src/Utilities/Request.php#L230)

if we hit endpoint without query string, controller doesn't receive query string, paging will not run and server will return all data. how to prevent this if we have a lot of data later ?

**Comment by yajra** [comment]
This is the default behavior atm. I think it can be prevented by altering the request as needed before returning dataTable. Maybe something like below.

```php
request()->merge(['length' => request('length', 1)])

return datatable($source)->toJson();
```

**Comment by quannetwork** [comment]
You should also check for the 'start' parameter.
