### ISSUE TITLE
"error":"Exception Message:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'DT_RowIndex' in 'order clause' (SQL: select `id`, `username`, `email`, `saldo` from `users` order by `DT_RowIndex` desc limit 10 offset 0)

### ISSUE THREAD

**Issue by captan3899** [yajra/laravel-datatables#2367]
### Summary of problem or feature request

this is first time i use yajra datatables 
can someone help me how to use addIndexColumn()
me already try tutorial in google but it not working

everytime i get this error 

"error":"Exception Message:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'DT_RowIndex' in 'order clause' (SQL: select `id`, `username`, `email`, `saldo` from `users` order by `DT_RowIndex` desc limit 10 offset 0)

### Code snippet of problem
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use DataTables;

class UserController extends Controller
{
    public function viewUser()
    {
        return view('user-index');
    }

    public function dataDatatableUser()
    {
        try
        {

            $users = User::select(['id','username','email','saldo']);
            return Datatables::of($users)->addIndexColumn()->make();

        } catch (\Exception $e) {

            dd($e->getMessage());

        }
    }
}
`

`<script>
$(function () {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    let oTable = $("#example1").DataTable({
        responsive: true,
        autoWidth: false,
        processing: true,
        serverSide: true,
        ajax: '{{ route("data.user.datatables") }}',
        columns: [
            { data: 'DT_RowIndex'},
            { data: 'username'},
            { data: 'email'},
            { data: 'saldo'}
        ],
        order:[[0,'desc']]
    });
  });
</script>`

### System details

- Operating System
- PHP Version = 7.3.2
- Laravel Version = 7.6.1
- Laravel-Datatables Version =composer require yajra/laravel-datatables:^1.5

**Comment by captan3899** [comment]
i found the solution i change the config/datatables.php

` /*
     * DataTables internal index id response column name.
     */
    'index_column'   => 'id',`

**Comment by yajra** [comment]
A better solution is to set searchable and orderable false on your js.

```js
{data: 'DT_RowIndex', searchable: false, orderable: false}
```

**Comment by captan3899** [comment]
thanks

**Comment by roshani3110** [comment]
Unknown column DT_RowIndex is not found

in controller,

$datatables = DataTables::eloquent($users)
->addIndexColumn()
->addColumn('roles', function (User $user) {
return $user->getRoleNames()->implode(',');
})

in js,

columns: [
{ data: 'DT_RowIndex', orderable: false, searchable: false },
...
]

still, this problem has occurred.
