### ISSUE TITLE
Add columns not working with service implementation

### ISSUE THREAD

**Issue by ayman-elmalah** [yajra/laravel-datatables#2374]
### Summary of problem or feature request
When i'm using service implementation i need to add columns but when i do this the search and sort is not working

### Code snippet of problem

return datatables()
            ->eloquent($query)
            ->escapeColumns([])
            ->addColumn('id', function ($q) {
                return '#' . $q->id;
            });

### System details

- Operating System
- PHP Version 7.2
- Laravel Version 7
- Laravel-Datatables Version 
         "yajra/laravel-datatables": "^1.5",
        "yajra/laravel-datatables-oracle": "^9.8"

**Comment by yajra** [comment]
Use editColumn

```php
->editColumn('id', function ($q) {
  return '#' . $q->id;
});
```

**Comment by ayman-elmalah** [comment]
Okay but i need to add columns that have no value like i have no since date i need to add it , when add columns it's not be searchable

**Comment by yajra** [comment]
Yes, see https://yajrabox.com/docs/laravel-datatables/master/add-column for ref.

> added columns are assumed to be computed columns and not part of the database. Thus, search/sort will be disabled on those columns. If you need them, use the editColumn api instead.

**Comment by bremg** [comment]
What if you have 100 columns all of the same custom object. You suggest we add 100 loops?

There is an addColumns but that has the same inefficient implementation. 

I'd like to seem something like 

->addColumns($model , function($model)
     $this->addColumn('name', $model->name),
     $this->addColumn('email', $model->email)
)

Or you could fix the relations so we can add them in the get columns.
