### ISSUE TITLE
Orthogonal sort and filter

### ISSUE THREAD

**Issue by dima-bzz** [yajra/laravel-datatables#2378]
### Summary of problem or feature request

```php
...
->editColumn('updated_at', function ($row) {
           return [
                    'display' => $row->getUpdatedAt(),
                    'timestamp' => $row->getUpdatedAtTimestamp(),
                ];
            })
...
```

How can I sort and search using Orthogonal data? Sorting works, but no search.

columns[2][data][_]: updated_at.display
columns[2][data][sort]: **updated_at.timestamp**
columns[2][data][filter]: **updated_at.display**
columns[2][name]: updated_at.timestamp
columns[2][searchable]: true
columns[2][orderable]: true
columns[2][search][value]
columns[2][search][regex]: false
### System details

- Operating System Ubuntu 18.04
- PHP Version 7.2.24
- Laravel Version 6.18.3
- Laravel-Datatables Version 9.7.2

**Comment by yajra** [comment]
On your js, set the `name: 'updated_at'`.

**Comment by dima-bzz** [comment]
@yajra  Does not work. Gives an error message **Undefined index: updated_at**. Here is my code in js.
```js
{'name': 'updated_at', 'data': { '_': 'updated_at.display', 'sort': 'updated_at.timestamp', 'filter': 'updated_at.display'}},
```
