### ISSUE TITLE
Example and documentation site down

### ISSUE THREAD

**Issue by ekandreas** [yajra/laravel-datatables#238]
Example and documentation site down, development discontinued?

**Comment by yajra** [comment]
Thanks for reporting. Will check later, must be a hosting issue.

Sent from Outlook using iPhone




On Wed, Nov 4, 2015 at 11:33 PM -0800, "Andreas Ek" <notifications@github.com> wrote:












Example and documentation site down, development discontinued?

**Comment by ekandreas** [comment]
Sounds great!

**Comment by yajra** [comment]
Demo site is up again. Thanks!
