### ISSUE TITLE
orderBy() not working with Display Row Number 

### ISSUE THREAD

**Issue by ramouspeppy** [yajra/laravel-datatables#2381]
### Summary of problem or feature request

I have a problem when I using Display Row Number with orderBy('created_at','DESC').
So, I have 200 data in my database. when I display to datatable. row number start from 200 to 400. 
it should start from 1 - 200 right?

please help, I've been working this for 1 month 

### Code snippet of problem
```php
 if ($request->ajax()) {
            DB::statement(DB::raw('set @rownum=0'));
            $testDrive = TestDrive::with('product')->select(['*', DB::raw('@rownum  := @rownum  + 1 AS rownum')])
                         ->orderBy('created_at','ASC');
            $datatables = DataTables::eloquent($testDrive);

            if ($keyword = $request->get('search')['value']) {
                $datatables->filterColumn('rownum',
                function($query, $keyword) {
                    $query->whereRaw("@rownum  + 1 like ?", ["%{$keyword}%"]);
                });
            }
            $datatables
            ->editColumn('tanggal', function($testDrive){
                return $testDrive->created_at_formated;
            });
            return $datatables->make();
        }

        $html = $builder

        ->addColumn(['data'=>'rownum','name'=>'rownum','title'=>'#','class' => 'fit text-center','searchable'=>false])
        ->addColumn(['data'=>'name','name'=>'name','title'=>'Nama'])
        ->addColumn(['data'=>'hp','name'=>'hp','title'=>'Handphone','class' => 'fit'])
        ->addColumn(['data'=>'address','name'=>'address','title'=>'Alamat'])
        ->addColumn(['data'=>'product.product','name'=>'product.product','title'=>'Product'])
        ->addColumn(['data'=>'tanggal','name'=>'tanggal','title'=>'Tanggal','class' => 'fit','searchable'=>false]);
        return view('backend.testDrives.index')->with(compact('html'));
    }
```

### System details

- Operating System Win 10 64 Bit
- PHP Version 7.2.19
- Laravel Version 5.8 
- Laravel-Datatables Version 1.5

**Comment by benyaminl** [comment]
> 
> ### Summary of problem or feature request
> 
> I have a problem when I using Display Row Number with orderBy('created_at','DESC').
> So, I have 200 data in my database. when I display to datatable. row number start from 200 to 400.
> it should start from 1 - 200 right?
> 
> please help, I've been working this for 1 month
> ### Code snippet of problem
> 
> ```
>  if ($request->ajax()) {
>             DB::statement(DB::raw('set @rownum=0'));
>             $testDrive = TestDrive::with('product')->select(['*', DB::raw('@rownum  := @rownum  + 1 AS rownum')])
>                          ->orderBy('created_at','ASC');
>             $datatables = DataTables::eloquent($testDrive);
> 
>             if ($keyword = $request->get('search')['value']) {
>                 $datatables->filterColumn('rownum',
>                 function($query, $keyword) {
>                     $query->whereRaw("@rownum  + 1 like ?", ["%{$keyword}%"]);
>                 });
>             }
>             $datatables
>             ->editColumn('tanggal', function($testDrive){
>                 return $testDrive->created_at_formated;
>             });
>             return $datatables->make();
>         }
> 
>         $html = $builder
> 
>         ->addColumn(['data'=>'rownum','name'=>'rownum','title'=>'#','class' => 'fit text-center','searchable'=>false])
>         ->addColumn(['data'=>'name','name'=>'name','title'=>'Nama'])
>         ->addColumn(['data'=>'hp','name'=>'hp','title'=>'Handphone','class' => 'fit'])
>         ->addColumn(['data'=>'address','name'=>'address','title'=>'Alamat'])
>         ->addColumn(['data'=>'product.product','name'=>'product.product','title'=>'Product'])
>         ->addColumn(['data'=>'tanggal','name'=>'tanggal','title'=>'Tanggal','class' => 'fit','searchable'=>false]);
>         return view('backend.testDrives.index')->with(compact('html'));
>     }
> ```
> 
> ### System details
> 
>     * Operating System Win 10 64 Bit
> 
>     * PHP Version 7.2.19
> 
>     * Laravel Version 5.8
> 
>     * Laravel-Datatables Version 1.5

do you use any variable from the js side, such as start and end? 
I'm also got this problem last time, and that's because I use start variable and sent it via ajax.
eg
```js

var table = $("#dataTable").dataTables({
....
ajax : {
          url: '{{ url("master/barang/foo") }}',
            data: function (d) {
                d.kategori = $('#kategori').val();
                // don't use d.start and don't use d.end!
                d.startHarga = $('#txtFrom').val();
                d.endHarga = $('#txtTo').val();
            }
}
....
});

```

maybe it helps with your problem?
