### ISSUE TITLE
Facing problem in datatable column sorting

### ISSUE THREAD

**Issue by santoshnextgeni** [yajra/laravel-datatables#2386]
Hi Team, I am facing problem in yajra datatable sorting. sorting is not working in my code. Please help

This ismy server side code function.

public function datatableRequest( Request $request ){

		$count = DBTable::count();
		$total_members =  $count; // get your total no of data;
		$datalog = DBTable::select("*");
		
		$draw = $request->get('draw');
        $start = $request->get('start');
        $length = $request->get('length');
		$filter = $request->get('search');
		$search = (isset($filter['value']))? $filter['value'] : false;
		$columns = $request->get('columns');
		foreach($columns as $column){
			if( isset($column['search']['value']) ){
				if(isset($column['name']) && $column['name'] == 'user_id' || $column['name'] == 'user_id' || $column['name'] == 'id') {
					$datalog = $datalog->where($column['data'], "=", $column['search']['value']);
				} else {
					$datalog = $datalog->where($column['data'], "Like", "%".$column['search']['value']."%");
				}
			}
		}	
		$total_members = $datalog->count();
		$result_logs = $datalog->skip($start)
        ->take($length)
		->orderBy('id', 'DESC')->get();
		
		
		
		$data = array(
            'draw' => $draw,
            'recordsTotal' => $total_members,
            'recordsFiltered' => $total_members,
            'data' => $result_logs,
        );
		
		echo json_encode($data);
		
	}

**Comment by yajra** [comment]
Not a team but just me ^_^

Anyways, I think you are not using the package at all in your code. Try this simple snippet instead.

```php
public function datatableRequest( Request $request ) {
    return datatables(DB::table('tableName')->select("*"))->toJson();
}
```
