### ISSUE TITLE
Can't install on laravel 7.10.0 - Doc error in Yajrabox

### ISSUE THREAD

**Issue by BRobertORT** [yajra/laravel-datatables#2387]
### Summary of problem or feature request
Hi, 
Using composer require yajra/laravel-datatables-oracle:^9.0  (as it says in the [doc ](https://yajrabox.com/docs/laravel-datatables/master/installation#installing-laravel-datatables)) on a fresh install of Laravel  and i'have got a "Your requirements could not be resolved to an installable set of packages." message : 

 Problem 1
    - Installation request for yajra/laravel-datatables-oracle 9.0 -> satisfiable by yajra/laravel-datatables-oracle[v9.0.0].
    - Conclusion: remove laravel/framework v7.10.0
    - Conclusion: don't install laravel/framework v7.10.0
    - yajra/laravel-datatables-oracle v9.0.0 requires illuminate/view 5.8.* -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/view 5.8.x-dev|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.0|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.11|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.12|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.14|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.15|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.17|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.18|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.19|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.2|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.20|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.22|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.24|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.27|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.28|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.29|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.3|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.30|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.31|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.32|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.33|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.34|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.35|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.36|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.4|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.8|don't install laravel/framework v7.10.0
    - don't install illuminate/view v5.8.9|don't install laravel/framework v7.10.0
    - Installation request for laravel/framework (locked at v7.10.0, required as ^7.0) -> satisfiable by laravel/framework[v7.10.0].

Installation failed, reverting ./composer.json to its original content.
### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by MGeurts** [comment]
Use :
composer require yajra/laravel-datatables-oracle:"~9.0"

**Comment by BRobertORT** [comment]
Thank's, 
it's working. 
So there is a typo in https://yajrabox.com/docs/laravel-datatables/master/installation#installing-laravel-datatables

Regards;
B.

**Comment by yajra** [comment]
Thanks, docs updated.
