### ISSUE TITLE
x-editable with select option

### ISSUE THREAD

**Issue by rimbaborne** [yajra/laravel-datatables#2388]
### Summary of problem or feature request
Bismillah,
I can't display select options from the x-editable module. I tried using the usual format, the result was no problem. but if I use the select format, the results don't come out according to the x-editable documentation.

I put it on drawCallback because it will work for all data with usual format x-editable.
I have no problems with the package. the script works well. just select option.

is there a configuration on this related yajra datatable ?

### Code snippet of problem

```php 
$.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
$('#tabel_biodata').DataTable({
        "scrollX": true,
        "processing": true,
        "serverSide": true,
        "ajax": "{{ route('admin.biodata.getdata') }}?produk={{ request('produk') }}",
        'columnDefs': [
     'targets': 0,
            'createdCell':  function (td, cellData, rowData, row, col) {
                $(td).attr('data-pk', rowData['id']).attr('data-type', 'text').attr('class', 'updateaktif').attr('data-value', rowData['aktif']);
                }
            },
        ],
"columns":[
            { "data": "aktif" },
        ],
        "drawCallback": function( settings ) {
            var api = this.api();

            $('.updateaktif', api.table().body()).editable({
                url: "{{route('admin.biodata.updatedata')}}",
                mode : 'inline',
                source: [
                    {value: 1, text: 'Active'},
                    {value: 2, text: 'Blocked'},
                    {value: 3, text: 'Deleted'}
                ]
            });

        }
});
```

### System details

- Operating System : mac
- PHP Version : 7.4
- Laravel Version : 5.8
- Laravel-Datatables Version : 9

**Comment by yajra** [comment]
This is more of a js and css issue and is out of scope of the project. I suggest you ask on datatables.net forum.

**Comment by rimbaborne** [comment]
ok. thank you
