### ISSUE TITLE
Datatables parse from sql script

### ISSUE THREAD

**Issue by butoibogdan** [yajra/laravel-datatables#239]
How can i use a sql script in datatables.
I have a complex sql script an i wont to use with datatables 
My code si $users=DB::select(DB::raw($sqlcript);
return Datatables::of($users)->make(true);
but i have an error Call to a member function getQuery() on array.
I saw that DB:select return an array.
Thank you very much

**Comment by yajra** [comment]
I think you should use `DB::table()` instead of `DB::select()`. `DB::select()` indeed returns an array but `DB::table()` returns a query builder.

**Comment by butoibogdan** [comment]
It's not working i test with a simple table DB::table(DB::raw('SELECT * FROM users')) and i got an error
 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT * FROM users) count_row_table' at line 1 (SQL: select count(*) as aggregate from (select '1' as row_count from SELECT * FROM users) count_row_table)

Thank you

**Comment by yajra** [comment]
You should an alias on table depending on your database. Use something like below:

```php
$sql = 'select * from users';
DB::table(DB::raw("($sql) as users"))->get();
```

**Comment by butoibogdan** [comment]
Thank for all now every thing is perfect :)

**Comment by konstantinkonstantinovbgo** [comment]
I run this code:

$sql = 'select * from users';
DB::table(DB::raw("($sql) as users"))->get();

[2017-11-15 16:00:17] local.ERROR: Method getQuery does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method getQuery does not exist.
