### ISSUE TITLE
Normal pageLength styling in buttons implemenation

### ISSUE THREAD

**Issue by bremg** [yajra/laravel-datatables#2392]
When I use the buttons implementation it removes the page lenght option and replaces it with the buttons. 

I can add the pageLenght as a button but i want the normal styling. 

```
	public function html()
	{
		return
			$this->builder()
				->addTableClass('table table-hover dataTable nowrap css_modal-datatable js_datatable')
				->responsive(true)
				->searching(true)
				->paging(true)
				->lengthChange(true)
				->pageLength(25)
				->setTableAttributes(['width="100%"'])
				->columns($this->getColumns())
				->minifiedAjax(route('language.datatables-index'))
				->dom('Bfrtip')
				->orderBy(0, 'desc')
				->buttons(['pageLength'])
			    ->drawCallback('function () { $(".dataTables_filter").hide(); }')
				->parameters([]);
	}
```

Is it possible to have no buttons (or some buttons) AND the normal pagination dropdown?

**Comment by yajra** [comment]
Afaik, pageLength is part of the default dom. Not sure on pageLength button. Can you link me to the js docs please? Haven't tried that button yet.
