### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by MGeurts** [yajra/laravel-datatables#2394]
This package is unnecessary hard to use.
The documentation is outdated and contradicting in so many places.
Examples are outdated and not consistent.
The documentation is unstructured and completely unusable for beginners.

**Comment by realtebo** [comment]
Sorry to say, I agree.

The documentation refers in part to another package. 

I also faced that 

```
>php artisan datatables:make InfoRequestList

                                                                
  There are no commands defined in the "datatables" namespace.  
```
                                                                
So probably the documentation need a good rewrite and update

**Comment by yajra** [comment]
Yes, I also agree with this and sorry for the outdated docs. I just can't find time to work on it yet. I even bought a [laravel-datatables.com](laravel-datatables.com) domain for a dedicated docs but it just doesn't kicked on me yet. 

Anyways, the docs are open to pull request via https://github.com/yajra/laravel-datatables-docs.
