### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by harendra21** [yajra/laravel-datatables#2395]
### I am facing this problem with datatable when I removed get() to use query instead of collection to make data tables fast 

```php
$quiz_data = User_quiz::select(['id','user_id',
            'quiz_id','transaction_status','reference_no','source','created_at']);
            return DataTables::of($quiz_data)
                ->addIndexColumn()
                ->addColumn('payment_status', function($row){
                    if(isset($row['transaction_status'])){
                        return $row['transaction_status'];
                    }else{
                        return '';
                    }
                })->addColumn('quiz', function($row){
                    $quiz = $row['quiz_id'];
                    $quiData = Quiz::where('id',$quiz)->select(['title','quiz_start_date_time'])->first();
                    return '<div><b>Title - </b>'.$quiData['title'].'</div><div><b>Date - </b>'.$quiData['quiz_start_date_time'].'</div>';
                    //return 'Quiz';
                })->addColumn('transaction_details', function($row){
                    $reference_no = $row['reference_no'];
                    $user_id = $row['user_id'];
                    $userData = User::where('id',$user_id)->select(['mobile_no','operator'])->first();
                    return '<div><b>Reference No. - </b>'.$reference_no.'</div><div><b>Mobile - </b>'.$userData['mobile_no'].'</div><div><b>Operator - </b>'.ucfirst($userData['operator']).'</div>';
                })
                ->editColumn('created_at', '{{ date("M d, Y H:i:s",strtotime($created_at)) }}')
                ->escapeColumns([])
                ->toJson();
```

### System details

- Operating System - Linux
- PHP Version - 7.2 
- Laravel Version - 5.8
- Laravel-Datatables Version - 9.6

**Comment by benyaminl** [comment]
> 
> ### I am facing this problem with datatable when I removed get() to use query instead of collection to make data tables fast
> 
> ```
> $quiz_data = User_quiz::select(['id','user_id',
>             'quiz_id','transaction_status','reference_no','source','created_at']);
>             return DataTables::of($quiz_data)
>                 ->addIndexColumn()
>                 ->addColumn('payment_status', function($row){
>                     if(isset($row['transaction_status'])){
>                         return $row['transaction_status'];
>                     }else{
>                         return '';
>                     }
>                 })->addColumn('quiz', function($row){
>                     $quiz = $row['quiz_id'];
>                     $quiData = Quiz::where('id',$quiz)->select(['title','quiz_start_date_time'])->first();
>                     return '<div><b>Title - </b>'.$quiData['title'].'</div><div><b>Date - </b>'.$quiData['quiz_start_date_time'].'</div>';
>                     //return 'Quiz';
>                 })->addColumn('transaction_details', function($row){
>                     $reference_no = $row['reference_no'];
>                     $user_id = $row['user_id'];
>                     $userData = User::where('id',$user_id)->select(['mobile_no','operator'])->first();
>                     return '<div><b>Reference No. - </b>'.$reference_no.'</div><div><b>Mobile - </b>'.$userData['mobile_no'].'</div><div><b>Operator - </b>'.ucfirst($userData['operator']).'</div>';
>                 })
>                 ->editColumn('created_at', '{{ date("M d, Y H:i:s",strtotime($created_at)) }}')
>                 ->escapeColumns([])
>                 ->toJson();
> ```
> 
> ### System details
> 
>     * Operating System - Linux
> 
>     * PHP Version - 7.2
> 
>     * Laravel Version - 5.8
> 
>     * Laravel-Datatables Version - 9.6

do you try to debug from the url? It's hard to measure or guess what you're up to and what the problem is if you don't post the error message.
