### ISSUE TITLE
Buttons default config overrides buttons

### ISSUE THREAD

**Issue by hgokturk** [yajra/laravel-datatables#2397]
First of all, thank you very much for this great tool. When I try to set the button defaults through html builder, class applied to the buttons but not the buttons I choose to create are created but the certain set of them are. Below are the before/after secreen shots.
![Screenshot_before](https://user-images.githubusercontent.com/1374240/82422281-eb2d4b80-9a8a-11ea-81c4-e76de96f0743.png)
![Screenshot_after](https://user-images.githubusercontent.com/1374240/82422289-ee283c00-9a8a-11ea-9da0-9630ab8a415d.png)

Thank you.

```php
public function html()
    {
        return $this->builder()
            ->setTableId('users-table')
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->dom("<'row'<'col-sm-12'B>><'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>><'row'<'col-sm-12'tr>><'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>")
            ->orderBy(1, 'asc')
            ->parameters([
                'orderClasses' => false,
                'pagingType' => 'first_last_numbers',
                // Buttons default class
                'buttons' => [
                    'dom' => [
                        'button' => [
                            'className' => 'btn btn-outline-primary',
                        ]
                    ]
                ]
            ])
            ->stripeClasses(['alert-info', 'alert-light'])
            ->buttons(
                Button::make('create')->text('Oluştur'),
                Button::make('export'),
                Button::make('print'),
                Button::make('reset'),
                Button::make('reload')
            );
    }
```

- Laravel Version - Latest
- Laravel-Datatables Version - Latest

**Comment by Sok-Hai** [comment]
@hgokturk  hi did you solve you problem?
I just face this problem also. I just solve it by using this code

```
/**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->setTableId('users-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->orderBy(1)
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => [
                            'buttons' => [
                                [
                                    'extend' => 'create',
                                    'text' => 'My Custom Name'
                                ], 
                                'print', 'excel'
                            ],
                            'dom' => [
                                'button' => [
                                    'className' => 'btn btn-light'
                                ]
                            ]
                        ],
                    ]);
    }

```

which we need to config buttons in side parameters method. this work for me. I spend 3 days to figure out and fixed it.

**Comment by yajra** [comment]
Wow, I personally haven't tried that options as I usually set the defaults in javascript. Thanks for sharing your solution.

**Comment by hgokturk** [comment]
@Sok-Hai I wish I shared my solution before :)

`public function html()
    {
        return $this->builder()
            ->setTableId('users-table')
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->dom("<'row'<'col-sm-12 mb-4'B>><'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>><'row'<'col-sm-12'tr>><'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>")
            ->orderBy(1, 'asc')
            ->parameters([
                'orderClasses' => false,
                'pagingType' => 'first_last_numbers',
                'renderer' => [
                    'header' => 'bootstrap4',
                    'pageButton' => 'bootstrap',
                ],
                'buttons' => [
                    'buttons' => [
                        [
                            'extend' => 'excel', 'text' => 'EXCEL'
                        ],
                        [
                            'extend' => 'print', 'text' => 'PRINT'
                        ],
                        [
                            'extend' => 'reload', 'text' => 'RELOAD'
                        ],
                        [
                            'extend' => 'reset', 'text' => 'RESET'
                        ],
                    ],
                    'dom' => [
                        'button' => [
                            'className' => 'btn btn-outline-primary btn-sm',
                        ]
                    ]
                ]
            ])
            ->stripeClasses(['alert-info', 'alert-light']);
    }`

This seems the way to do it.

**Comment by Sok-Hai** [comment]
@hgokturk  next time if you found solution and fixed it. please post so i can save my 3 days. haha

**Comment by hgokturk** [comment]
@Sok-Hai I'm really sorry :)

**Comment by Sok-Hai** [comment]
@hgokturk yeah. so issue should be close now.
