### ISSUE TITLE
Export Column endpoint not showing

### ISSUE THREAD

**Issue by oluwatosinolamilekan** [yajra/laravel-datatables#2398]
![image](https://user-images.githubusercontent.com/29930457/82529972-14ee7d00-9b34-11ea-8df6-2d9857c3de3b.png)

**Comment by yajra** [comment]
Correct link is without S https://yajrabox.com/docs/laravel-datatables/master/export-column

Might be a bad link somewhere, how did you get there?

**Comment by yajra** [comment]
Fixed via https://github.com/yajra/laravel-datatables-docs/pull/69.
