### ISSUE TITLE
Using livewire/livewire components in a yajra/laravel-datatables table

### ISSUE THREAD

**Issue by Namoshek** [yajra/laravel-datatables#2401]
**Note: This is not a bug report or an issue. Prior to trying it out myself, I searched for the keyword `livewire` in the issues and did not find what I was looking for. So I thought, I leave a hint for future readers with a similar question. This issue may be closed at any time.**

I always wanted to have dynamic components within my tables, but unfortunately with vuejs, the default option provided by Laravel, this isn't possible. The vuejs core parses the DOM once when loading the page and switches then to a virtual DOM which is unaware of changes in the actual DOM. Therefore, when returning vuejs components from a DataTable, they are not recognized by vuejs and are simply not _activated_. And the alternative, plain JavaScript, was never an option for me either.

When learning about [`livewire/livewire`](https://github.com/livewire/livewire), I thought it might be a suitable alternative for exactly this scenario. And it turns out, it is! (As long as you add a tiny but necessary configuration to your tables.)

The only thing's I had to add to my DataTables configuration are the following two options:
```js
{
    deferLoading: true,
    drawCallback: function(settings) {
        if (window.livewire) {
            window.livewire.rescan();
        }
    }
}
```

The `deferLoading` option was necessary for me because I'm also using a self-written logic to save and restore the state of my tables, especially the column search state. Without the option, my tables performed three draw cycles when loading a page, which seemed to break the livewire logic (it happened quite fast, maybe that's why). If you are not using custom logic in the `initComplete` callback, you most likely don't need this option.

The `drawCallback` is the actual sweetness needed to get things working. And it is straight forward as well. Whenever we finish drawing the table (which happens when loading new data, e.g. on search, sort or page change), we ask livewire to look for new components and initialize them. That's it. livewire will even make sure to subscribe to new Laravel Echo channels, if any of the newly recognized components listens for some events. Unfortunately though, it won't unsubscribe when components (i.e. table data) are replaced with new ones. For me, this isn't an issue though.

**Comment by yajra** [comment]
Thanks for sharing, I haven't tried livewire yet and surely will use this as a ref when I got the chance to play with it.

**Comment by fabioi** [comment]
Hello @Namoshek I am a bit new with LiveWire. I am trying to render a Livewire component on a custom 'actions' column but without success. I would like to have a livewire button component loaded in a custom datatable 'actions' column.

`/**
     * @throws Exception
     */
    public function get(): JsonResponse
    {
        $query = $this->userRepository->getIndexQuery();

        return DataTables::of($query)
            ->addColumn('roles', function (User $user) {
                             return $user->roles->implode('name', ', ');
                         })
            ->addColumn('actions', function (User $user) {
                            //return livre
                         })
            ->rawColumns(['actions'])
            ->make(true);
    }`


Do you have any hints maybe? thank you a lot

**Comment by Namoshek** [comment]
You just need to return the html which renders the livewire component from the closure, similar to what you would use in a view.

**Comment by fabioi** [comment]
Thanks for your reply! I tried this way but cannot make it work:

Note:
- the livewire component is working (tested in a separate view)
-  the JS  callback works (tried triggering a JS alert), no errors in the browser console

 I have the JS callback set up in the datatable:
'''JS
tableElement.DataTable({
          "serverSide"   : true,
          "order"        : {!! $order ?? "[]" !!},
          "lengthMenu"   : [[10, 50, 100, 200, -1], [10, 50, 100, 200, "Tutti"]],
          "searching"    : true,
          "deferRender"  : true,
          "ordering"     : true,
          "paging"       : true,
          "orderCellsTop": true,
          drawCallback   : function(settings) {
            if (window.livewire) {
              window.livewire.rescan();
            }
          },
'''

'''PHP
 $query = $this->userRepository->getIndexQuery();

        return DataTables::of($query)
                         ->addColumn('roles', function (User $user) {
                             return $user->roles->implode('name', ', ');
                         })
                         ->addColumn('actions', function (User $user) {
                             return view('livewire.block-user-button');
                         })
                         ->rawColumns(['actions'])
                         ->toJson();
'''
Tested also returning directly the HTML. 

'''PHP
$query = $this->userRepository->getIndexQuery();

        return DataTables::of($query)
                         ->addColumn('roles', function (User $user) {
                             return $user->roles->implode('name', ', ');
                         })
                         ->addColumn('actions', function (User $user) {
                         return <<<'HTML'
<div>
    <input wire:model="buttonText" wire:click="myAction" type="text">
</div>
HTML;

                         })
                         ->rawColumns(['actions'])
                         ->toJson();

'''
But unfortunately clicking the button does not trigger the component PHP function.

**Comment by Namoshek** [comment]
Your HTML is not a Livewire component, it's the template of the component. You need to return the call to the component, for example `<livewire:counter>` when we stick with the example component from [the quickstart guide](https://laravel-livewire.com/docs/2.x/quickstart).

**Comment by fabioi** [comment]
Thank your suggestion @Namoshek!. 

I have been able to make the Livewire component work in a Datatable column this way:

'''PHP
 $query = $this->userRepository->getIndexQuery();

        return DataTables::of($query)
                         ->addColumn('roles', function (User $user) {
                             return $user->roles->implode('name', ', ');
                         })
                         ->addColumn('actions', '<livewire:block-user-button>')
                         ->rawColumns(['actions'])
                         ->toJson();
'''

**Comment by yajra** [comment]
I was able to work with livewire now and the code suggestions here works great. I also added a new api on html builder to integrate with livewire as per suggestion of @Namoshek 🎊 

```php
    public function html()
    {
        return $this->builder()
                    ->setTableId('videos-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->drawCallbackWithLivewire() // enable livewire integration
...
```

Tried implementing this with `wire:poll` for automatic loading status from a job queue. Great work around for a realtime checking of row status with dataTables. ^_^

**Comment by Namoshek** [comment]
Cool stuff, thank you!

**Comment by fabioi** [comment]
super nice! Thank you @yajra :D

**Comment by jhourlad** [comment]
Hello, guys. It's still a blur on my side. Can anybody suggest how this issue is dealt with if we are doing livewire inside custom colums? Something similar to this code:

```
      const dt = table.DataTable( {
                columns: [
                    { data: 'id', render: (data, type, row, meta) => {
                        return `<div class="text-rightx"><a href="#" as="button" wire:click.prevent="test"><i class="fa fa-edit mr-1"></i></a> <a href="#" wire:click.prevent="test" class="text-danger"><i class="fa fa-trash"></i></a></div>`;
                    }},
                ],
```

Thanks!

**Comment by Namoshek** [comment]
@jhourlad If you use custom **JavaScript** render functions, the Blade component tags like `<livewire:counter />` are not parsed and rendered correctly.

See my [earlier comment](https://github.com/yajra/laravel-datatables/issues/2401#issuecomment-694971925) as how to render Livewire components. You need to use a [raw column](https://yajrabox.com/docs/laravel-datatables/master/raw-columns) which renders the Livewire component tag. And you need to add the new builder helper method yajra showed [here](https://github.com/yajra/laravel-datatables/issues/2401#issuecomment-727157794).

**Comment by kiotipot1** [comment]
can someone share the project? i badly need it, i'm new to both laraval and datatables.

**Comment by kiotipot1** [comment]
This is how i add my button but it is still don't work

![Uploading dataTables_button.PNG…]()

front datatable
![dataTable_front](https://user-images.githubusercontent.com/74756933/100884553-931cda80-34ec-11eb-90ed-3e4194950bbf.PNG)
 any suggestion on how that is the proper way of displaying the datables? by the way i'm a newbie in laravel i just only starting to study it this day i badly need your help

**Comment by fdelvals** [comment]
> Hello, guys. It's still a blur on my side. Can anybody suggest how this issue is dealt with if we are doing livewire inside custom colums? Something similar to this code:
> 
> ```
>       const dt = table.DataTable( {
>          columns: [
>            { data: 'id', render: (data, type, row, meta) => {
>              return `<a href="#" as="button" wire:click.prevent="edit(${data})">Edit</a>`;
>            }},
>          ],
>          ...
>       });
> ```
> 
> With that code, function `edit()` is not being called. Thanks!

I have been stuck with your same problem.
Does anyone have a working example? I can't figure it out with the guidelines given.

thank you

**Comment by AtefR** [comment]
was anyone able to make the livewire click work?

**Comment by Namoshek** [comment]
> was anyone able to make the livewire click work?

You mean a clickable button for example, like `<button wire:click="foo">`? Absolutely, it requires no special handling.

**Comment by AtefR** [comment]
> > was anyone able to make the livewire click work?
> 
> You mean a clickable button for example, like `<button wire:click="foo">`? Absolutely, it requires no special handling.

It doesn't work with me though,

View: 
```
<div>
    <button wire:click="increment">+</button>
    <h1>{{ $count }}</h1>
</div>
```
Component:
```
class Actions extends Component
{
    public $count = 0;

    public function increment()
    {
        $this->count++;
    }

    public function render()
    {
        return view('livewire.permission.actions');
    }
}
```

and scripts are like this on layout
```
@livewireScripts
<script src="{{ mix('js/app.js') }}"></script>
@stack('scripts')
</body>
</html>
```

**Comment by Namoshek** [comment]
How does the relevant part of your DataTable look like? Have you added the draw callback, [which Yajra added to the package](https://github.com/yajra/laravel-datatables/issues/2401#issuecomment-727157794)?

**Comment by AtefR** [comment]
> How does the relevant part of your DataTable look like? Have you added the draw callback, [which Yajra added to the package](https://github.com/yajra/laravel-datatables/issues/2401#issuecomment-727157794)?

yes, I did add it

```php
    public function dataTable($query)
    {
        return datatables()
            ->eloquent($query)
            ->editColumn('created_at', function ($data) {
                return $data->created_at->format('Y/m/d');
            })
            ->editColumn('action', function ($data) {
                return Livewire::mount('permission.actions', ['permission' => $data->id])->html();
            })
            ->rawColumns(['action']);
    }

    public function html()
    {
        return $this->builder()
            ->setTableId('permissions-table')
            ->columns($this->getColumns())
            ->drawCallbackWithLivewire()
            ->addAction(['width' => '80px'])
            ->orderBy(1);
    }
```

**Comment by Namoshek** [comment]
My code looks a bit different, but I swapped it for your style (didn't know the `Livewire::mount()->html()` yet) and it works as well.

Are you rendering the scripts for your DataTable? Or is this some manually written stuff?
```blade
<div>
    {{ $dataTable->table([], true) }}
</div>

@push('scripts')
    {!! $dataTable->scripts() !!}
@endpush
```

**Comment by AtefR** [comment]
> My code looks a bit different, but I swapped it for your style (didn't know the `Livewire::mount()->html()` yet) and it works as well.
> 
> Are you rendering the scripts for your DataTable? Or is this some manually written stuff?
> 
> ```
> <div>
>     {{ $dataTable->table([], true) }}
> </div>
> 
> @push('scripts')
>     {!! $dataTable->scripts() !!}
> @endpush
> ```

this is weird, this is how the view
```blade
<x-app-layout>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-sm-4">
                            @livewire('permission.create')
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div class="table-responsive">
                            {{ $dataTable->table(['class' =>'table table-centered table-striped dt-responsive nowrap w-100'], true) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        {!! $dataTable->scripts() !!}
    @endpush
</x-app-layout>
```
what's your livewire version might be some bug in the newer versions..

**Comment by Namoshek** [comment]
Latest, this is weird. I guess the browser is also not showing any click event handlers for the button?

**Comment by Namoshek** [comment]
I'm using `->editColumn('action', 'some.view.name')` in my DataTable and `<livewire:my.component :foo="$model" :bar="true" />` in the view for example. But as said, I tried your style and it works the same (and is definitely nicer 👍).

**Comment by mahendra2448** [comment]
> I was able to work with livewire now and the code suggestions here works great. I also added a new api on html builder to integrate with livewire as per suggestion of @Namoshek 🎊
> 
> ```
>     public function html()
>     {
>         return $this->builder()
>                     ->setTableId('videos-table')
>                     ->columns($this->getColumns())
>                     ->minifiedAjax()
>                     ->drawCallbackWithLivewire() // enable livewire integration
> ...
> ```
> 
> Tried implementing this with `wire:poll` for automatic loading of status from a job queue. Great work around for a realtime checking of row status with dataTables. ^_^

Hello, where you create this `html()` method? is it inside the component?

**Comment by Namoshek** [comment]
You'll need [`yajra/laravel-datatables-html`](https://github.com/yajra/laravel-datatables-html) for this. The usage is described in the [documentation](https://yajrabox.com/docs/laravel-datatables/master/quick-starter).
