### ISSUE TITLE
Accents Working in MySQL but not in Datatables

### ISSUE THREAD

**Issue by racerguy** [yajra/laravel-datatables#2402]
### Summary of problem or feature request

In MySQL I can use the below to find the name I am looking for

      SELECT * FROM `inventory_selections` WHERE `name` LIKE '%capi%'

which finds the full name Capítulo

However searching for "capi" in datatables yields no results.

### System details

- Mac OSX Mojave
- PHP 7.3
- Laravel 7
- Laravel-Datatables 9

**Comment by racerguy** [comment]
Also running it as a test, this code works in a separate controller

` $column = 'name';
        $keyword = "%capi%";
        $sql    = $column . ' LIKE ?';
        $select = InventorySelection::select('*')
        ->whereRaw($sql ,$keyword)
        ->get();`

**Comment by yajra** [comment]
You might be using collection? Make sure you don't have `->get()` when passing the query to dataTables.

**Comment by racerguy** [comment]
> You might be using collection? Make sure you don't have `->get()` when passing the query to dataTables.

It was a combination of that and manually setting a render column in JS. For some reason it kept pulling the data: null of the column and thinking it was part of the column filtering. Would get errors such as "inventory.  " column not found

**Comment by yajra** [comment]
Can you please provide snippets to reproduce the issue?

**Comment by jcarlos1985** [comment]
I need also a solution for this issue... I'll specify my case:

I have a column "nombre" with "Perez" and "Pérez" values.
When I search "pere", it founds only "Perez" results and I need to find also "Pérez". Like @racerguy said, if you do the sql query in mysql "select * from `alumnos` where `nombre` like '%pere%'" it finds both cases...

I've been trying to modify the query in datatable using filter function, but doesn't work..., it shows an error said "CollectionDatatable where doesn exist" this is my filter function:

->filter(function ($query) use ($request) {
    if ($request->has('search')) {
        $busqueda = $request->get('search');
        $query->where('name', 'like', "%{$busqueda['value']}%");
    }
})

@yajra Do you know any solution?

**Comment by racerguy** [comment]
@jcarlos1985 Can you send the entire snippet including the datatables function? I'll try to see if my fix works for you

**Comment by jcarlos1985** [comment]
Hi @racerguy this is the complete function:

$data = Alumno::latest()->get();
$grupos = Grupo::all();

$select_grupos = '';
foreach($grupos as $grupo)
    $select_grupos .= '<option value="' . $grupo->id . '">' . $grupo->nombre . '</option>';

return Datatables::of($data)
    ->filter(function ($query) use ($request) {
        if ($request->has('search')) {
            $busqueda = $request->get('search');
            $query->where('name', 'like', "%{$busqueda['value']}%");
        }
    })
    ->addColumn('nombre', function($row) { return $row->nombre; })
    ->make(true);


Thanks for reply!

**Comment by racerguy** [comment]
**First change** 

$data = Alumno::latest()->get(); 

**to** 

$data = Alumno::latest();

**Then change**  

return Datatables::of($data)

**to**

return Datatables::eloquent($data)

I'm assuming nombre is stored as name in the database?

If so, what i would do is delete the custom filter then just set name to title  "nombre"  in the datatables front end.

**Comment by jcarlos1985** [comment]
Hi!

Sorry about the mistake, in database is "nombre" not "name". This is the code now:

$data = Alumno::latest()->get();
return Datatables::eloquent($data)
->addColumn('nombre', function($row) { return $row->nombre; })
->make(true);

But this is the error it shows:
Non-static method Yajra\DataTables\DataTables::eloquent() should not be called statically

**Comment by racerguy** [comment]
```
$datatables = datatables()->eloquent($datas)...
return $datables;
```
This is how mine reads

try lower casing datatables()

**Comment by jcarlos1985** [comment]
Now is working!! Thanks @racerguy final code is:

return datatables()->eloquent($data)
	->filter(function ($query) use ($request) {
		if ($request->has('search')) {
			$busqueda = $request->get('search');
			$query->where('nombre', 'like', "%{$busqueda['value']}%");
		}
})

About addColumn, yes, I understand now, only it would be necessary in case modify the result in database or make some calc, isn't it?

Some interesting thing... I note is faster doing the query in database when use datatables()->eloquent() instead of Datatables::of() Is there any reason?

Thanks!

**Comment by jcarlos1985** [comment]
I realized now is not ordering columns... What could be the reason? :'(

**Comment by racerguy** [comment]
> Now is working!! Thanks @racerguy final code is:
> 
> return datatables()->eloquent($data)
> ->filter(function ($query) use ($request) {
> if ($request->has('search')) {
> $busqueda = $request->get('search');
> $query->where('nombre', 'like', "%{$busqueda['value']}%");
> }
> })
> 
> About addColumn, yes, I understand now, only it would be necessary in case modify the result in database or make some calc, isn't it?
> 
> Some interesting thing... I note is faster doing the query in database when use datatables()->eloquent() instead of Datatables::of() Is there any reason?
> 
> Thanks!

You are exactly right on the first question.

The second part may be a @yajra question as I'm not well versed in the difference. 

Could you go on chrome and open the debug window then record network calls?

click the reorder then see if API returns anything or if response is null if you can send the response you got
