### ISSUE TITLE
Render html on setRowData

### ISSUE THREAD

**Issue by lungu-catalin** [yajra/laravel-datatables#2403]
### Summary of problem or feature request

Hi, 
Is there any possibility to send html in setRowData? Something like this:

### Code snippet of problem

```php
 ->setRowData([
           'contact' => function ($contact) {
                 return "<li>$contact->name</li>";
            },               
     ])
```

### System details

- Operating System: Win10
- PHP Version: 7.4.5
- Laravel Version: 6.4
- Laravel-Datatables Version:  9.0

**Comment by yajra** [comment]
Not sure but maybe try using HtmlString.

```php
 ->setRowData([
           'contact' => function ($contact) {
                 return new HtmlString("<li>$contact->name</li>");
            },               
     ])
```
