### ISSUE TITLE
Eager Loading Relationships problem when Filter and Search using Multi-Database 

### ISSUE THREAD

**Issue by Siulacio** [yajra/laravel-datatables#2404]
### Summary of problem or feature request

Hi, I have problems when I try to use filters and searches on relationship that relates two diferents databases.

the extrange is that the relationship brings the data and show it in the column, it indicates that the way I related the tables and access to the data is fine, but when I write in the search box, datatables show me an error "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenant_db_name.municipios' doesn't exist".  **in this case, tenan_db_name = comercial_1065613976_3**

![image](https://user-images.githubusercontent.com/58397603/83098431-3b4e7400-a070-11ea-803a-97de78b025a8.png)

I have two databases, the first is the main database, where table municipios is located and the second database is a client database, where terceros table is located and this is related with municipios table. ***Datatables assumes that municipios table is located on comercial_1065613976_3 database, but it really locates on main database***

### Code snippet of problem

this is the municipios model
~~~
class Municipios extends Model
{    
    use SoftDeletes;
    
    protected $table='municipios';

    protected $fillable = [
        'codigo_municipio',
        'nombre_municipio',
        'codigo_dpto',
    ];  

    public static function municipio($id){
        return Municipios::where('codigo_dpto','=',$id)->get();
    }

}
~~~
---
this is the belongsTo relationship between terceros and municipios, it's defined on terceros model.
~~~ 
public function municipios(){
return $this->setConnection('mysql')->belongsTo('App\Municipios','municipio','codigo_municipio');
}
~~~

I must clarify that I use two conectors, "mysql" for stablish conection with the main database and "tenant" to stablish conection with the client db. ***in this case I use $this->setConnection('mysql') because the municipios table is on the main database***

---
Now, this is the controller function that serves the data:
~~~
    public function getData2(){
        if( request()->ajax() ){
            $terceros = Terceros::with('municipios')->select('terceros.*'); 
            return datatables()->of($terceros)
                ->addColumn('action', function($data){
                    $button ='<center>';
                    $button .= '<a href="'.asset('/sistema/terceros/editar/'.$data->id).'" data-remote="false" class="btn btn-warning btn-circle" title="Editar tercero"> <i class="fa fa-fw fa-pencil"></i> </a>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<a href="" data-toggle="modal" id="'.$data->id.'" data-remote="false" class="btn btn-danger btn-circle delete" title="Eliminar tercero"> <i class="fa fa-fw fa-trash"></i> </a>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<a href="" data-toggle="modal" id="'.$data->id.'" data-remote="false" class="btn btn-success btn-circle geo" title="Georeferencia"> <i class="fa fa-fw fa-map-marker"></i> </a>';
                    $button .='</center>';
                    return $button;
                })
                ->addColumn('dpto',function($data){
                    return $data->departamentos->nombre_dpto;
                })
                ->addColumn('nom',function($data){
                    return $data->nomTercero($data->id);
                })
                ->make(true);
        }
    }
~~~
---
this is the script that receives the data
~~~
    <script>
        $(document).ready(function(){
            $('#terceros_dt').DataTable({
                "processing":true,                
                "serverSide": true,
                "ajax":{
                    url:"{{ route('getData2')}}",
                },                
                "columns":[
                    {data: 'id'},
                    {data: 'nit'},
                    {data: 'nom', name:'nom'},
                    {data: 'dpto'},    
                    {data: 'municipios.nombre_municipio', name:'municipios.nombre_municipio'},
                    {data: 'tipo_tercero'},
                    {data: 'action', orderable:false},                    
                ]
            });
        });
    </script>
~~~
---

finally, I would like to know why the relationships is fine to show the data but I can't filter and search the same data.

thanks in advance for your help.
 

### System details

- Operating System: Windows 10
- PHP Version 7.3.5
- Laravel Version 6.0
- Laravel-Datatables Version 9.0

**Comment by yajra** [comment]
Using multi database connection is not supported unless you can set a database link or something similar that will let you join all those tables.

If you can make it work on SQL level, then in can be handled by the package.
