### ISSUE TITLE
Recommended way to pass/use parameters to DataTable class?

### ISSUE THREAD

**Issue by redbastie** [yajra/laravel-datatables#2405]
What is the recommended way to pass parameters to a class that extends `DataTable`?

For example, let's say I want to add where to the query.

Controller:

    public function index(UsersDataTable $dataTable)
    {
        return $dataTable->render('users.index');
    }

DataTable class:

    class UsersDataTable extends DataTable
    {
        public function dataTable($query)
        {
            return datatables()
                ->eloquent($query)
                ->addColumn('action', 'users.action');
        }

        public function query(User $model)
        {
            return $model->newQuery();
        }

Where would I add, say, `->where('role', 'Admin')` to the call inside the controller, and how do I implement it properly in the class?

**Comment by yajra** [comment]
Several ways:

If role is from request, I usually add it on the query.

```php
    public function query(User $model)
    {
        $query = $model->newQuery()
        if (request('role')) {
            $query->where('role',  request('role'));
        }
        
        return $query;
    }
```

If it's a fixed scope and you want the users dataTable to be reusable, you can use Scope class. See https://yajrabox.com/docs/laravel-datatables/master/buttons-console for ref but sorry since it's not updated but should work.

```php
public function index(UsersDataTable $dataTable)
{
    return $dataTable->addScope(new AdminRoleScope)->render('users.index');
}
```
