### ISSUE TITLE
How to use datatable class without DI?

### ISSUE THREAD

**Issue by redbastie** [yajra/laravel-datatables#2407]
I have this code that works:

    public function index(LeadDataTable $lead_data_table)
    {
        return $lead_data_table->render('admin.leads.index');
    }

How do I do this without DI? E.G:

    public function index()
    {
    	$lead_data_table = new LeadDataTable;

        return $lead_data_table->render('admin.leads.index');
    }

**Comment by yajra** [comment]
Your code should work. Any issues?

```php
public function index()
{
    $lead_data_table = new LeadDataTable;

    return $lead_data_table->render('admin.leads.index');
}
```
