### ISSUE TITLE
Maximum function nesting

### ISSUE THREAD

**Issue by lloricode** [yajra/laravel-datatables#2409]
### Summary of problem or feature request

Hi I am using this https://github.com/spatie/laravel-model-states verson 1.6.1
then the table give us 
```
Maximum function nesting level of '512' reached, aborting!
```
### Code snippet of problem

try to comment this line
https://github.com/spatie/laravel-model-states/blob/1.6.1/src/HasStates.php#L74
then it works, but the `spatie/laravel-model-states` is not not working because of commented events

### System details

- Operating System
- PHP Version: 7.2.30
- Laravel Version: v7.14.1
- Laravel-Datatables Version  v9.10.1 

Thanks, hope any solution or any idea what is a missing

**Comment by lloricode** [comment]
already found the problem, this is will cause infinite recursion

![Screenshot from 2020-06-04 16-55-03](https://user-images.githubusercontent.com/8251344/83736409-2c754c00-a684-11ea-84df-7cab26536fd2.png)

can we set ignore check on specific column?

**Comment by lloricode** [comment]
already fix added in model

```php
    protected $hidden = [
        'column_name',
    ];
```

but can we have hide only on datatable?

**Comment by yajra** [comment]
I think there is `->makeHidden(array)` api that you already use for this case.

**Comment by lloricode** [comment]
> I think there is `->makeHidden(...)` api that you can use for this case.
> 
> Found the docs: https://yajrabox.com/docs/laravel-datatables/master/make-hidden

@yajra will try this, thanks

**Comment by lloricode** [comment]
thanks already fixed

**Comment by yordivd** [comment]
makeHidden is not an option if the state object is nested somewhere i think. it's not working for my case.... also using laravel-model-states
