### ISSUE TITLE
Order Column API does not recognize column name when it has a dot '.' inside its name

### ISSUE THREAD

**Issue by quannetwork** [yajra/laravel-datatables#2411]
The tutorial on https://datatables.yajrabox.com/eloquent/order-column gave me the idea of replacing the sorted column with the other column. For example, the code below will make sure that when the `title` column is sorted, it will be sorted by `email` instead.

```
orderColumn('title', 'email $1')
```

But the other tutorial, searching with relationships, https://yajrabox.com/docs/laravel-datatables/master/relationships, suggested that the name of the column should be the `relation.column_name`, so the name of the column became `posts.title`.

Then I continued to update the column name in `orderColumn`, 

it became `orderColumn('posts.title', 'email $1')`, but it did not work, the column will be sorted by the title, not email.

I guess because the name of the column has the '.' inside its name.

So are there any workaround? Thanks in advance.

**Comment by yajra** [comment]
Maybe try using a name alias on js and use it instead?

```js
{data: 'posts.title', name: 'post_title'}
```

```php
->orderColumn('post_title', 'email $1')
```

**Comment by quannetwork** [comment]
Yeah, that would work, but it will make the search function raise errors because the generated SQL query will use the `post_title` as the column name, but `post_title` does not exist.

**Comment by quannetwork** [comment]
@yajra. I got the solution. This would work:

```
{data: 'relationship_function_name_declared_in_model.title', name: 'post_title'}

->orderColumn('real_table_name.title', 'email $1')
```
