### ISSUE TITLE
Display custom DateTime 

### ISSUE THREAD

**Issue by joaocarlos** [yajra/laravel-datatables#2415]
### Summary of problem or feature request

I need to display dates as dd-mm-yyyy in datatables. I need to apply this display to `data_admissao`, `created_at` and `updated_at`.

### Code snippet of problem

Here is the sniped of my ClassDataTable.php

```php
    protected function getColumns()
    {
        return [
            Column::make('siape')->addClass('text-center'),
            Column::make('nome'),
            Column::make('email'),
            Column::make('telefone'),
            Column::make('titulacao.nome')->title('Titulação')->addClass('text-center'),
            Column::make('grupo.nome')->title('Grupo'),
            Column::make('data_admissao'),
            Column::make('created_at'),
            Column::make('updated_at'),
        ];
    }
```

### System details

- Operating System
Ubuntu LTS 18.04
- PHP Version
PHP 7.4.6
- Laravel Version
Laravel Framework 7.14.1

**Comment by yajra** [comment]
Several ways, you can use Model mutator, js renderer or via editColumn.

```php
            ->editColumn('updated_at', function (Distribution $distribution) {
                return Carbon::parse($distribution->updated_at)->toDateTimeString();
            })
````

**Comment by joaocarlos** [comment]
> Several ways, you can use Model mutator, js renderer or via editColumn.
> 
> ```
>             ->editColumn('updated_at', function (Distribution $distribution) {
>                 return Carbon::parse($distribution->updated_at)->toDateTimeString();
>             })
> ```

Thanks for the answer, but where do I have to put the editColumn call? I am using the service implementation using the DataTables class.

**Comment by Barbait** [comment]
same question, it's not clear where to put the editColumn(). I've tried something like this:
`protected function getColumns()
    {
        return [
            Column::make('name'),
            Column::make('email'),
            Column::make('phone'),
            Column::make('created_at')
                ->editColumn('updated_at', function (Distribution $distribution) {
                return Carbon::parse($distribution->updated_at)->toDateTimeString();
                }),
            Column::make('updated_at'),
        ];
    }
`

Unfortunately without success. Every search done online does not use datatables as service and would be great to know how to transit from normal datatable to datatable as service.
