### ISSUE TITLE
Issue / Problem - [empty data] - Using Yajra/Datatables ^9.10  with Laravel 7.12.0

### ISSUE THREAD

**Issue by gc2lgno** [yajra/laravel-datatables#2416]
### Hi there, just a newbie right here trying to use this package. 

I followed the steps to install the package via composer, added the Service Provider and Alias.

**Here is my routes/api file:**
![image](https://user-images.githubusercontent.com/3009032/84425555-c80c3c80-abef-11ea-9662-0f35746b1f21.png)
(it works fine)

**Here is my Controllers\API\CompanyController:**
![image](https://user-images.githubusercontent.com/3009032/84425706-030e7000-abf0-11ea-8313-bb84a6b47027.png)

**Here is my view**

**The goal I am aiming is to Server-Side the displayed data via AJAX**
And this is the result of testing this with Postman:
![image](https://user-images.githubusercontent.com/3009032/84426882-f25ef980-abf1-11ea-9e25-a0ec88552632.png)
As you can see, there is no error besides the one on the JSON response.

When the right output shold look like this ->
![image](https://user-images.githubusercontent.com/3009032/84426854-e8d59180-abf1-11ea-8650-587d35b00e0c.png)

What am I doing wrong? There is something that I'm missing :(

PS: Sorry for my bad english.

PS#2: In case you're wondering, yes, there is data in Companies::all();
![image](https://user-images.githubusercontent.com/3009032/84433788-dc0a6b00-abfc-11ea-9f82-610de57bdbef.png)
(in the image above it's only displaying two fields)

**Comment by yajra** [comment]
I think you are missing `toJson()` on your chain.

```php
return datatables()->collection($companies)->toJson();
```

**Comment by gc2lgno** [comment]
> 
> 
> I think you are missing `toJson()` on your chain.
> 
> ```
> return datatables()->collection($companies)->toJson();
> ```

I realley apreciate your answer, but unfortunately I get the same error doing that.

![imagen](https://user-images.githubusercontent.com/3009032/84923857-c7632280-b095-11ea-8bf8-12ee9b298147.png)
![imagen](https://user-images.githubusercontent.com/3009032/84923874-ce8a3080-b095-11ea-852b-e05ca2e5b88e.png)

**Comment by yajra** [comment]
I just tried it and works well on my side:

```php
return datatables()->collection(User::all())->toJson();
```

You might have appends and some eager loading behind the scene that causes the error. Try reviewing the full error log to get a hint on what causes the issue.

**Comment by gc2lgno** [comment]
> 
> 
> I just tried it and works well on my side:
> 
> ```
> return datatables()->collection(User::all())->toJson();
> ```
> 
> ![image](https://user-images.githubusercontent.com/2687997/84968050-297c6000-b148-11ea-9d80-b8492e395d3e.png)
> 
> You might have appends and some eager loading behind the scene that causes the error. Try reviewing the full error log to get a hint on what causes the issue.

Well I certainly can't find the error. I know it is too much to ask, but if you just could take a look of it, this is the repo.

https://github.com/gc2lgno/Laravel-Junior-Test

Probably it is a minor thing, but I'd really apreciate your help even if you don't take a look of it.

**Comment by sazzadul4201** [comment]
same issue

**Comment by yajra** [comment]
@gc2lgno @sazzadul4201 might be because the call was done via postman. When using the js library, there are several input values that will be included in the request like search, columns, start, etc that are required for the package to work correctly.
