### ISSUE TITLE
On initial page load draw datatable rows on clicking a button only.

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables#2419]
### Summary of problem or feature request

On my page once the user fills a form with specific column filters an click submit, then I will trigger the ajax call and update the rows with filtered data. I am able to achieve this.

The issue I am facing is, on initial page load it is loading the rows without any filter. I want to disable the ajax that loads data on initial page load.

Because of this there is an unwanted DB call and as DB is huge it takes a lot of time for calculating the count of entire table. After applying filters this is much faster but then on initial page load user has to wait for the unfiltered ajax to complete.

### System details

- Operating System Ubuntu 18.04
- PHP Version 7.1
- Laravel Version 5.7
- Laravel-Datatables Version 8.13

**Comment by yajra** [comment]
If you to disable ajax on initial load then try using `->deferLoading(false)`.
