### ISSUE TITLE
Title shows html code as title when using checkbox

### ISSUE THREAD

**Issue by Peter-1969** [yajra/laravel-datatables#2421]
One (the first) of the columns i use in datatables is a checkbox. In the header i also use a checkbox so the users can select/deselect all of the records checkboxes at once. But when i hover over this checkbox a hint/title is shown with the html code of this checkbox. This is, of course, not what i want. Can i provide an alternative title for hovering or disable the title?

` 
$checkbox  = '&lt;div class="niceCheckbox"&gt;';
        $checkbox .= '&lt;input class="datatable-toggle-all-checkboxes" type="checkbox" id="toggle_check_all"&gt;';
        $checkbox .= '&lt;label for="toggle_check_all" class="custom-checkbox"&gt;&lt;/label&gt;';
        $checkbox .= '&lt;label for="toggle_check_all" class="checkbox-text-label"&gt;&lt;/label&gt;';
        $checkbox .= '&lt;/div&gt;';

        Column::make('select')
            ->title($checkbox)
            ->width(20)
            ->orderable(false)
            ->searchable(false);`

![afbeelding](https://user-images.githubusercontent.com/62602251/85514682-94bcab00-b5fc-11ea-834c-a119de3dcb53.png)

- PHP 7.3
- Laravel 6
- Yajra/laravel-datatables ^1.5

**Comment by ArkaitzUlibarri** [comment]
I have the same problem when I put bootstrap styles on the title:

   /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        //More colums here

        
        foreach ($this->answer_types as $answer_type_id => $answer_type) {
            $columns[] = [
                'name' => Str::slug($answer_type) . '_' . 'count',
                'data' => Str::slug($answer_type) . '_' . 'count',
                'title' => '<span class="badge bg-res_' . $answer_type . '">' . __('metrics.' . strtolower($answer_type)) . '</span>',
                'className' => 'text-center'
            ];
        }

        return $columns;
    }

- PHP ^7.2
- Laravel 6
- Yajra/laravel-datatables-buttons ^4.8
- Yajra/laravel-datatables-html ^4.20
- Yajra/laravel-datatables-buttons ~9.0

**Comment by ArkaitzUlibarri** [comment]
@yajra Can you please take a look on this

**Comment by yajra** [comment]
I think you need to use `'titleAttribute' => 'tooltip'`.

**Comment by ArkaitzUlibarri** [comment]
I have search in datatables.net your suggestion and I have found the solution for my case. It is the following:

`'titleAttr' => trans('metrics.' . strtolower($answer_type))`
