### ISSUE TITLE
[Docs] Error in pages "Export columns" & "Print columns" in official docs

### ISSUE THREAD

**Issue by livevasiliy** [yajra/laravel-datatables#2423]
### Summary of problem or feature request

Error open pages in official docs in section "Column Editing" next pages: "Export columns" and "Print columns". Which open this pages I give exception below I attach screenshots opening pages.

![изображение](https://user-images.githubusercontent.com/15705591/86002085-e744ff80-ba20-11ea-85aa-46d7f8da9c20.png)
![изображение](https://user-images.githubusercontent.com/15705591/86002119-f4fa8500-ba20-11ea-8c26-a52b3da125f5.png)

**Comment by yajra** [comment]
There is a mistake in URL. It should be:

https://yajrabox.com/docs/laravel-datatables/master/export-column
https://yajrabox.com/docs/laravel-datatables/master/print-column

Where did you get the link? Might be a typo somewhere in the docs. Also I think a similar issue like this was already raised.

**Comment by livevasiliy** [comment]
> There is a mistake in URL. It should be:
> 
> https://yajrabox.com/docs/laravel-datatables/master/export-column
> https://yajrabox.com/docs/laravel-datatables/master/print-column
> 
> Where did you get the link? Might be a typo somewhere in the docs. Also I think a similar issue like this was already raised.

I found, you have mistack in sidebar menu. In sidebar links ends with 's' 

![image](https://user-images.githubusercontent.com/15705591/86514111-bb5ebb00-be20-11ea-86a4-f35d83398f66.png)
