### ISSUE TITLE
sum of a column of all the pages of a filter

### ISSUE THREAD

**Issue by VConsulting** [yajra/laravel-datatables#2424]
I am looking for the sum of a column of all the pages of a filter, I managed to obtain the sum of the current page:

I manage to pass the sum of the total of the records of the table in JSON parameter without worries, but if I add a filter, for example by date, I cannot find how to recover the sum of the lines concerned by the filter ...
Datatable load page by page in AJAX therefore impossible to calculate in JS and on the server side it is the datatable which takes care of the filter ...
I can't figure out how to tell him to give me that filter sum ... has anyone ever done that?

I followed :
https://datatables.net/examples/advanced_init/footer_callback.html

But with :
// Total over all pages
                    total = api
                        .column (2, {filter: 'applied'})
                        .data ()
                        .reduce (function (a, b) {
                            return intVal (a) + intVal (b);
                        }, 0);

I don't have the sum of the total with the filter.

Server side:
-> with ('total', $ datas-> sum ('amount')) returns the total of all the rows in the table but not the current filter

```
return Datatables::of($datas)
            ->editColumn('created_at', function ($datas) {
                return $datas->created_at->format('d-m-Y');
            })
            ->filterColumn('created_at', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(created_at,'%d-%m-%Y') like ?", ["%$keyword%"]);
            })
            ->with('total', $datas->sum('montant'))
            ->make(true);
```
An idea ?

**Comment by yajra** [comment]
I think what you need is the `withQuery` api. See https://yajrabox.com/docs/laravel-datatables/master/response-with#query-closure for ref.

**Comment by Nadeem2462** [comment]
This code block may help you to did the trick
            ->with('total', function() use ($datas) {
                return $datas->sum('montant');
            })

**Comment by danielgzvludiant** [comment]
I have the same problem, I can show the value of the sum but if I do a search it does not update the value, I look for something like this in laravel: https://www.webslesson.info/2019/07/how-to-calculate-total-of-column-in-datatable-using-php-with-ajax.html but I have not been able to adapt it, any idea?
