### ISSUE TITLE
Encrypt ID column

### ISSUE THREAD

**Issue by johnwswar** [yajra/laravel-datatables#2425]
New to Laravel, but what is the most efficient way to encrypt the ID using Laravel 7 with this Datatable.  I have a following link to edit this field:

LINK:  #< href="javascript:void(0)" data-toggle="tooltip"  data-id="378" data-original-title="EDIT" class="btn btn-outline-danger btn-sm title="EDIT Record">EDIT</a>

If possible, I do not want the users to see the value of the data-id="378" so would like to encrypt this ID and I guess would need to decrypt on my controller.  

Thank you in advance.

**Comment by yajra** [comment]
I think your inquiry should go to Laracast or Laravel forum. This is more of a route / controller question and is out of scope of the package.

Anyways, I suggest you read: https://laravel.com/docs/7.x/urls#urls-for-named-routes
