### ISSUE TITLE
raw SQL queries to be passed as QueryBuilder - Clone from reference #638

### ISSUE THREAD

**Issue by BaelishLord** [yajra/laravel-datatables#2426]
Basically, i want to pass raw queries in to the Datatables so as to avoid sending complete results and want it to work server sid such that only the required data is extracted from the database and not all data.

```
$sql="SELECT brands_id,brand_name,brand_code FROM brands where brands_id = 2";
$results=\DB::table(\DB::raw("($sql)"));
return Datatables::of($results)->make(true);
```

using the above syntax but getting error as below

`error: "Exception Message:↵↵SQLSTATE[42000]: Syntax error or access violation: 1248 Every derived table must have its own alias (SQL: select count(*) as aggregate from (select '1' as row_count from (SELECT brands_id,brand_name,brand_code FROM brands where brands_id = 2)) count_row_table)"`

- Operating System - Linux
- PHP Version - 7.2
- Laravel Version - 6
- Laravel-Datatables Version - 9.0

**Comment by yajra** [comment]
Already replied on https://github.com/yajra/laravel-datatables/issues/638.
