### ISSUE TITLE
How to insert title in button::make

### ISSUE THREAD

**Issue by dtreis** [yajra/laravel-datatables#2427]
Hello!
Please, how to insert title in button::make?

> 
    public function html()
    {
        return $this->builder()
                    ->setTableId('data-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->dom('Bfrtip')
                    ->orderBy(1, 'desc')
                    ->buttons(
                        Button::make('postExcel')->text('<i class="fa fa-download" aria-hidden="true"></i> Excel')->title('Download planilha Excel'),
                        Button::make('postCsv')->text('<i class="fa fa-download" aria-hidden="true"></i> CSV'),
                        Button::make('reset')->text('Limpar'),
                    )
                    ->parameters([
                        "language" => [ 'url' => asset('/portuguese-brasil.json')]
                    ]);
    }

 **Button::make('postExcel')->text('<i class="fa fa-download" aria-hidden="true"></i> Excel')->title('Download planilha Excel'),**

Thanks!

- PHP Version: 7.4.3
- Laravel Version: 6.18.14
- Laravel-Datatables Version: 1.5.0

**Comment by yajra** [comment]
Title like for tooltip on the button? Try adding it in the text?

```php
Button::make('postExcel')->text('<span title="Download planilha Excel"><i class="fa fa-download" aria-hidden="true"></i> Excel</span>')
```

**Comment by dtreis** [comment]
Thank you so much, Yajra!
