### ISSUE TITLE
Passing parameters to computed column

### ISSUE THREAD

**Issue by redbastie** [yajra/laravel-datatables#2428]
How do I pass a parameter to a computed column?

In my controller I have:

    public function assignModal(LeadAssignDataTable $lead_assign_data_table, Lead $lead)
    {
        return $lead_assign_data_table->with('lead', $lead)->render('leads.assign');
    }

This passes the `lead` to my datatable class, used by the `html` function here:

    public function html()
    {
        return $this->builder()
            ->setTableId('lead-assign-table')
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->ajax(route('leads.assign', $this->lead))
            ->responsive()
            ->autoWidth(false)
            ->orderBy(0, 'asc');
    }

I also have a computed action column:

    public function dataTable($query)
    {
        return datatables()
            ->eloquent($query)
            ->addColumn('action', 'leads.assign_action');
    }

    protected function getColumns()
    {
        return [
            Column::make('name'),
            Column::computed('action')->title(''),
        ];
    }

I can currently access the `lead` from the `leads.assign_action` view using `request('lead')`. This feels kind of hacky to me, I'd like to use the `lead` as a variable instead.

Here is the view file:

    <form method="post" action="{{ route('leads.assign', request('lead')) }}" class="d-inline-block" data-ajax-form>
        @csrf
        <input type="hidden" name="salesperson_id" value="{{ $id }}">
        <button type="submit" class="btn btn-primary">
            Assign
        </button>
    </form>

I'm just wondering if there is a way to pass the `lead` as a variable into the computed view?

**Comment by parth2799** [comment]
@redbastie You got any solution ?

**Comment by redbastie** [comment]
I ended up just using callback:

            ->editColumn('action', function (User $user) {
                return view('assigns.create_action', [
                    'lead' => $this->lead,
                    'salesperson' => $user,
                ]);
            });

**Comment by yajra** [comment]
Yes, I also use callback for complex cases. Actually, most of the time. :)
