### ISSUE TITLE
HTML revealed in DataTable after Laravel 5.5 -> 5.6 update

### ISSUE THREAD

**Issue by hondaman900** [yajra/laravel-datatables#2429]
### Summary of problem or feature request

I upgraded my project from Laravel 5.5 to 5.6 and checkboxes in DataTables are now writing the HTML code for non-breaking space (`&nbsp;`) over the checkbox. [Here's a screenshot.](https://i.imgur.com/an38fEG.png)

This is not in the view blade, or can I find where this issue is originating. Is there some extra step I need to take to address this as part of the upgrade? Everything else is working fine. This was never apparent in Laravel 5.5.

### Code snippet of problem

[Here's a screenshot of the HTML generated when the table cell is inspected.](https://i.imgur.com/Kn1MPDY.png)

### System details

- Operating System: Win10 running Laragon
- PHP Version: 7.4.8
- Laravel Version: 5.6
- Laravel-Datatables Version: The Laravel 5.5->5.6 update pulled in yajra/laravel-datatables-oracle v8.13.5 => v8.13.7

**Comment by hondaman900** [comment]
Anyone...?

**Comment by hondaman900** [comment]
Nevermind. Finally after days of searching I found two instances of the `e` helper buried in  the `vendor\yajra\laravel-datatables-oracle\src\Processors\DataProcessor.php` file. Laravel 5.5->5.6 changes the `e` helper behavior to now double encode special characters by default, resulting in the revealing of special characters, such as the `&nbsp;`. Adding the "`false`" parameter to the helper fixed the issue. Now both lines read:
`array_set($row, $key, e(array_get($row, $key), **false**)); // Added "false" for L5.6`
and
`$arrayDot[$key] = e($value, **false**); // Added "false" for L5.6`

Hope this helps someone else not loose days off their project.

**Comment by yajra** [comment]
I think what you need is the rawColumns for latest version. See https://yajrabox.com/docs/laravel-datatables/master/raw-columns for reference.

**Comment by hondaman900** [comment]
Thank you, I'll try that as well. 

Incidentally, upgrading to `laravel-datatables ^9.0 `overwrote my correction in the `DataProcessor.php `file. For ongoing compliance with Laravel (see [https://laravel.com/docs/5.6/upgrade](https://laravel.com/docs/5.6/upgrade)  "`Helpers`") it might be good to edit those two lines accordingly.

Thank you for the great package! Very much appreciated.
