### ISSUE TITLE
Unknown column DT_RowIndex is not found

### ISSUE THREAD

**Issue by roshani3110** [yajra/laravel-datatables#2431]
Unknown column DT_RowIndex is not found

in controller,

$datatables = DataTables::eloquent($users)
                ->addIndexColumn()
                ->addColumn('roles', function (User $user) {
                    return $user->getRoleNames()->implode(',');
                })

in js,

columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false },
            ...
]

still, this problem is occurred.

**Comment by yajra** [comment]
You might be using a lower version? Inspect the ajax response. You might still be using the old key which is `DT_Row_Index`.

**Comment by roshani3110** [comment]
thank you.
