### ISSUE TITLE
Uneven result in Yajra DataTable of Laravel

### ISSUE THREAD

**Issue by afoysal** [yajra/laravel-datatables#2433]
I am working using Laravel [DataTables][1]. My code of Controller is like below

    return Datatables::of(Address::where('company_name', 'LIKE', $letter.'%')->get)  //return all records of table 
                    ->addIndexColumn()
                    ->addColumn('initial', function($row){
                        return '<div class="'.($row->assignee? 'consignee' : 'customer') .'" title="'.($row->assignee? 'Consignee' : 'Customer') .'">C</div>';
                    })
                    ->addColumn('action', function(){
                        return
                            '<a href="">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>
                            <a href="">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>';
                    })
                    ->rawColumns(['initial','action'])
                    ->make(true);

I am trying to fetch values started with certain character ($letter.'%'). The query (`Address::where('company_name', 'LIKE', $letter.'%')->get`) is working perfectly if I run it individually but DataTable returns all the records of the table.

How can I debug the whole situation ?

  [1]: https://yajrabox.com/docs/laravel-datatables/master

**Comment by yajra** [comment]
Just remove `->get()`.
