### ISSUE TITLE
Render datatable when using `return view('...')->with([]);`

### ISSUE THREAD

**Issue by kaizokupuffball** [yajra/laravel-datatables#2434]
This is probably a pretty dumb question, but I have tried to find the solution in the documentation, but I can't find it..
I am using Laravel and I have different controllers displaying different pages. I want to use datatables to render a table of the data that the controller will handle.

Example:
I have `RolesController` with a `getIndex()` method wich would display all the roles in a datatable.
My `getIndex()` method looks like this:

`return view('dashboard.roles.index')->with(['roles' => DataTables::of(Role::all())->make(1)]);`

How do I render the table in the view? I tried `$roles->render()` and `$roles->table()` but both just gives an error.
The error I get is this:

`Method Illuminate\Http\JsonResponse::render`

Thanks in advance for any help and or pointers to where I should look in the docs.

**Comment by yajra** [comment]
I think your doing it wrong. See docs but it's a bit outdated ^_^. https://yajrabox.com/docs/laravel-datatables/master/buttons-starter

1. Create a `RolesDataTable` class.

```
php artisan datatables:make Roles
```

2. Update `RolesDataTable` and set the model, columns, etc.

3. Update your `RolesController`

```php
public function index(RolesDataTable $dataTable)
{
  return $dataTable->render('dashboard.roles.index');
}
```

4. Update your view `dashboard.roles.index`

```php
@section('content')
  {{ $dataTable->table() }}
@endsection

@push('scripts')
  {{ $dataTable->scripts() }}
@endpush
```

**Comment by kaizokupuffball** [comment]
Oh.. okay. I think i get it then, just thought there was a way to use the default `return view()->with()` method. But this helps, thanks!
