### ISSUE TITLE
put details-control button in  Master and Details Table in the last column of table 

### ISSUE THREAD

**Issue by MehranLabour** [yajra/laravel-datatables#2436]
As you see in this documai [datatables.yajrabox.com](https://datatables.yajrabox.com/eloquent/master)  the  details-control button is located in the first column, i want to place it in last column

is there anyway?

### System details

- Operating System:
- PHP Version: 7.1.3
- Laravel Version:5.8.*
- Laravel-Datatables Version 8.0

**Comment by yajra** [comment]
I think you just need to arrange the columns and make it as last?

```js
columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'},
            {
                "className":      'details-control',
                "orderable":      false,
                "searchable":      false,
                "data":           null,
                "defaultContent": ''
            },
        ],
```

**Comment by MehranLabour** [comment]
Thanks in advance
