### ISSUE TITLE
Removing default class from button and adding a new one

### ISSUE THREAD

**Issue by kaizokupuffball** [yajra/laravel-datatables#2437]
How would one remove the default button class `btn-secondary`? 
I found out i could use `..->addClass('my-button-class')` to add a new class to the specific button, but how can i remove the default class? Or remove every class? I found one example where someone said to take advantage of the `initComplete` method on the JS side of things, but how do i access the datatable on JS side when i just include the scripts with this: 
`@push('js', $dataTable->scripts())`

Thanks in advance!

**Comment by yajra** [comment]
You need to override the default buttons classes that comes with the bs4 plugin to something like:

```js
$.extend(true, $.fn.dataTable.Buttons.defaults, {
    dom: {
        container: {
            className: 'dt-buttons'
        },
        button: {
            className: 'btn btn-sm'
        },
        collection: {
            tag: 'div',
            className: 'dt-button-collection dropdown-menu',
            button: {
                tag: 'a',
                className: 'dt-button dropdown-item',
                active: 'active',
                disabled: 'disabled'
            }
        }
    }
});
```

**Comment by kaizokupuffball** [comment]
Thank you again. 😄
