### ISSUE TITLE
convertToArray endlessly recursing through a child entity with a reference back to its parent

### ISSUE THREAD

**Issue by rossbearman** [yajra/laravel-datatables#2438]
We're using the [Laravel Paperclip](https://github.com/czim/laravel-paperclip/) package which provides support for attaching files to entities. The attached entity contains a reference back to the original entity and Datatables currently gets stuck trying to convert this into an array as it will recursively try and nest the entities inside each other. Because we're passing the query builder to Datatables, there's no way for us to remove these references when they're instantiated. 

I have opened [an issue](https://github.com/czim/laravel-paperclip/issues/61) against that package as there's no way to stop it instantiating these objects at the query level, but as this problem will affect any entities that contain a reference to the parent, it seems like a more general solution in Datatables to ensure that the [`convertToArray`](https://github.com/yajra/laravel-datatables/blob/9.0/src/Utilities/Helper.php#L158) function doesn't endlessly recurse through references might be a better fix?

**Comment by yajra** [comment]
Not familiar with the package but feel free to submit a PR to fix this issue. Thanks!
