### ISSUE TITLE
Having trouble in Global search

### ISSUE THREAD

**Issue by umairchauhan1** [yajra/laravel-datatables#2440]
$nestedData['some_culumn'] = $values;
	                $nestedData['some_culumn'] = $values;
	                $nestedData['some_culumn'] = $values;
	                $nestedData['some_culumn'] = $values;
	                $nestedData['some_culumn'] = $values;
	                $data[] = $nestedData;
	            }
	        }
	        $json_data = array(
                    "draw"            => intval($request->input('draw')),  
                    "recordsTotal"    => intval($totalData),  
                    "recordsFiltered" => intval($totalFiltered), 
                    "data"            => $data   
                    );
      	 	 return json_encode($json_data);

**Comment by yajra** [comment]
Please provide snippets how to reproduce your issue. Thanks!
