### ISSUE TITLE
transformer not escaping

### ISSUE THREAD

**Issue by yilmazyusuf** [yajra/laravel-datatables#2441]
It is not escaped when  transformer based collection used.

`$rs = datatables()->eloquent($galleries)
                ->setTransformer(new VideoGalleryTransformer())
                ->escapeColumns('*')
->toJson()`

**Comment by yajra** [comment]
As stated in the [doc](https://yajrabox.com/docs/laravel-datatables/master/response-fractal), all column manipulations should be done via transformer which includes escaping of columns.
