### ISSUE TITLE
filterColumn bindings messy code

### ISSUE THREAD

**Issue by gebaiwan** [yajra/laravel-datatables#2442]
### Summary of problem or feature request

filterColumn bindings messy code

no chineses language can be correctly identified, even though "dd(request()->search)"  echo right words.

 the queries and inputs like: bindings: ["%ç­é¨%", "ç­é¨", "1", "ç­é¨", "%ç­é¨%", "%ç­é¨%", "%ç­é¨%", "%ç­é¨%"]

### Code snippet of problem

```php
use Yajra\DataTables\DataTables;

$datatables = $this->data_tables
            ->eloquent($query);

//search[value]:激活
if ($keyword = \request()->get('search')['value']) {
		    $datatables->filterColumn('active', function($query, $keyword){
			    if(Str::contains($keyword, ['激活', '启用'])){
				    $keyword = 1;
			    }elseif (Str::contains($keyword, '禁用')){
				    $keyword = 0;
			    }
			    $query->where('active', $keyword);
		    });
		    $datatables->filterColumn('is_hot', function($query, $keyword){
			    if(Str::contains($keyword,'热门')){
				    $keyword = 1;
			    }
			    $query->where('is_hot', $keyword);
		    });
		    $datatables->filterColumn('is_recommend', function($query, $keyword){
			    if(Str::contains($keyword,'推荐')){
				    $keyword = 1;
			    }
			    $query->where('is_hot', $keyword);
		    });
	    }
```
### System details

- Operating System: windows 10
- PHP Version:7.3
- Laravel Version:7.*
- Laravel-Datatables Version:9.10.2

thanks for help

**Comment by yajra** [comment]
Maybe you should use the request instead of the keyword?

```php
		    $datatables->filterColumn('is_recommend', function($query, $keyword){
                             $keyword = request('search.value');
			    if(Str::contains($keyword,'推荐')){
				    $keyword = 1;
			    }
			    $query->where('is_hot', $keyword);
		    });
```

**Comment by gebaiwan** [comment]
> Maybe you should use the request instead of the keyword?
> 
> ```
> 		    $datatables->filterColumn('is_recommend', function($query, $keyword){
>                              $keyword = request('search.value');
> 			    if(Str::contains($keyword,'推荐')){
> 				    $keyword = 1;
> 			    }
> 			    $query->where('is_hot', $keyword);
> 		    });
> ```

thanks for your reply,
i tried,shie still doesnot work fine

![1](https://user-images.githubusercontent.com/34265145/90466164-a4132d00-e143-11ea-96ca-1cb1b44fe133.png)
maybe chrome browser problem?
or init [order] parameters?
i just can't get correct result from her search api

**Comment by gebaiwan** [comment]
i print the sql,
![2](https://user-images.githubusercontent.com/34265145/90468595-729d6000-e149-11ea-8be0-87b508cb7e4c.png)
when i comment out this line, she 's fine!
`
active, is_hot, is_recommend tinyint unsigned not null default 0
`
filterColumn string concatenation broken?

**Comment by gebaiwan** [comment]
`
if ($keyword = request()->get('search')['value']) {
//	    	dd($keyword);
		    $datatables->filterColumn('tags.active', function($query) use ($keyword){
			    if(Str::contains($keyword, ['激活', '启用'])){
				    $keyword = 1;
			    }elseif (Str::contains($keyword, '禁用')){
				    $keyword = 0;
			    }
			    $query->where('tags.active', $keyword);
		    });
		    $datatables->filterColumn('tags.is_hot', function($query) use ($keyword){
			    if(Str::contains($keyword,'热门')){
				    $keyword = 1;
			    }
			    $query->where('tags.is_hot', $keyword);
		    });
		    $datatables->filterColumn('tags.is_recommend', function($query) use ($keyword){
			    if(Str::contains($keyword,'推荐')){
				    $keyword = 1;
			    }
			    $query->where('tags.is_recommend', $keyword);
		    });
	    }
`
i add the tags. before field, it's worked!
em, bindings messy code… forget it,
thanks!
