### ISSUE TITLE
Asking for paid support

### ISSUE THREAD

**Issue by devgiu** [yajra/laravel-datatables#2445]
Hi all,

Documentation is outdated and I can't get this plugin working. I appreciate if somebody with experience using it can connect with me and tell me rates to help just geting the plugin working. I tried to contact main dev but I didn't get any anwer. I'm sure will not take more than 1 hour. You can add me to skype giuseppe.komenco

Regards.

**Comment by yajra** [comment]
I currently don't do paid support and no idea for the rates too. Post some snippets and errors logs for us to be able to help.
