### ISSUE TITLE
Editor features disabled

### ISSUE THREAD

**Issue by jfwenger** [yajra/laravel-datatables#2446]
### Summary of problem or feature request

I have a licensed copy of editor. After following your installation instructions step by step, I was able to get a users datatable to display, but the editor functions do not work. The edit / delete buttons are grayed out, and in the "action" column, there is only a text that displays "users.action" for each row. Is this a license key problem with datatables editor, or is something else going on? 

It looks like this: 

![image](https://user-images.githubusercontent.com/24359792/90062822-48b1ec80-dcb6-11ea-8620-6b11fc0f1f76.png)

### System details

I am using Laragon on Windows to run:
Apache 2.4.35
PHP 7.4.6
Laravel 7.x
laravel-datatables: 9.x

**Comment by yajra** [comment]
Make sure you have enabled select plugin. Just chain `->select()` on the html builder or use other similar options.

**Comment by jfwenger** [comment]
Thanks for getting back to me! I've chained ->select() onto the builder,
and that has enabled the edit button, but when pressed, the edit button
produces this error:

"Uncaught Unable to find row identifier For more information, please refer
to https://datatables.net/tn/14." The reference at datatables.net says it's
because the row lacks a unique identifier. Do you know why this would be
happening?

**Comment by yajra** [comment]
You need to set the row id as the error suggested.

```php
datatables()->eloquent($query)->setRowId('id')
```
