### ISSUE TITLE
How do i add the generated pdf title and footer

### ISSUE THREAD

**Issue by lawyso** [yajra/laravel-datatables#2447]
Am using Yajra datatables for my huge data.I am able to generate the exports but my problem is i cant set the title and footer of the document please help

### System details

- Operating System window 8.1
- PHP Version 7.2
- Laravel Version 5.8.
- Laravel-Datatables Version

**Comment by yajra** [comment]
You can override the template used to generate the print preview / pdf file. On your DT class, override that property.

```
class UsersDataTable extends DataTable
{
    protected $printPreview = 'custom-view-path';
```

The default template being used is https://github.com/yajra/laravel-datatables-buttons/blob/4.0/src/resources/views/print.blade.php.
