### ISSUE TITLE
Pagination Error with server Side 

### ISSUE THREAD

**Issue by bmtmadushanka** [yajra/laravel-datatables#2451]
### Pagination Error with server Side 

 Datatable server side pagination work on localhost.but if access that local host network through pagination not work.i have more then 10000 records in my table.

### 
    var employee_table = $('#employee_table').removeAttr('width').DataTable({
    processing: true,
    serverSide: true,
    pageLength: 15,
    deferRender: true,
    ajax: '/employee',
    columnDefs: [
        {
            
            orderable: false,
            searchable: false,
        },
        {width: 40,targets: 0},
        {width: 40,targets: 1},
        {width: 150,targets: 2,render: $.fn.dataTable.render.ellipsis( 25 )},
        {width: 60,targets: 3},
        {width: 100,targets: 4,render: $.fn.dataTable.render.ellipsis( 18 )},
        {width: 120,targets: 5,render: $.fn.dataTable.render.ellipsis( 18 )},
        {width: 50,targets: 6},
        {width: 120,targets: 7,render: $.fn.dataTable.render.ellipsis( 18 )},
        {width: 100,targets: 8},
        {width: 50,targets: 9},
        {width: 60,targets: 10,render: $.fn.dataTable.render.number( ',', '.', 2 ),className: 'dt-body-right'},
        {width: 50,targets: 11},
        {width: 60,targets: 12},
        {width: 60,targets: 13},
        {width: 50,targets: 14},
        {width: 50,targets: 15},
        {width: 60,targets: 16},
        {width: 50,targets: 17},
        {width: 100,targets: 18},
       

    ],
    columns: [
        { data: 'empNo'},
        { data: 'empEPFNo'},
        { data: 'empName'},
        { data: 'empIDCardNo'},
        { data: 'subName'},
        { data: 'deptName'},
         { data: 'actName'  },
         { data: 'desigName'},
        { data: 'etName'  },
         { data: 'egraName'  },
         { data: 'empBasicSalary' },
         { data: 'empSex'  },
         { data: 'empDOJ'},
         { data: 'empDOB'},
         { data: 'empPaymentMode' },
         { data: 'checkbox1'  },
         { data: 'checkbox2'},
         { data: 'checkbox3'  },
        { data: 'action'},             
    ],
    scrollX:"200px",   
    scrollCollapse: true,
    paging:     true,
    fixedColumns:   {
        leftColumns: 1,
        rightColumns: 1
    },
    scrollX: true,
    // "dom": '<"top"i>rt<"bottom"flp><"clear">'
    
});

- Operating System = windows 10
- PHP Version = 7.3.12
- Laravel Version = 5.5
- Laravel-Datatables Version = 8.x

**Comment by yajra** [comment]
Might be server config issue. See https://github.com/yajra/laravel-datatables/issues/1210 for refs.

**Comment by bmtmadushanka** [comment]
solved the reason is server firewall blocking table draw request.
thank you
