### ISSUE TITLE
How to extract the JSON data in js side if passed as an additional parameter using with api

### ISSUE THREAD

**Issue by UmeshKrRana** [yajra/laravel-datatables#2452]
Hello yajra,
I have passed the additional parameters using the **with** function from controller like below snippet-
` ->with([
       "cities"            =>      app(\App\Http\Controllers\HelperController::class)->cityListing(),
       "leadCounters"      =>      $this->leadCounters
     ])
  ->make(true);`

Now, how can we extract these keys values in the view side?
Here, in the attachment. I am getting the response.
![2020-08-24_19h38_19](https://user-images.githubusercontent.com/30307542/91054758-7b0e0300-e641-11ea-8b0e-06001c974483.png)

Please help me.

If I am trying to get the response using the AJAX **success:function(result)** then it makes slow down the entire process.

**Comment by yajra** [comment]
Use `oTable.ajax.json()` where oTable is your DT instance.

**Comment by UmeshKrRana** [comment]
Thank you very much for your reply. This is my snippet of yajra datatable using the filter option.

`var table = $('#mytable').DataTable({
                "lengthMenu": [[10, 20, 50, 100, 150, 200, -1], [10, 20, 50, 100, 150, 200, "All"]],
                orderCellsTop: true,
                fixedHeader: true,
                responsive: true,
                "pageLength": 20,
                responsive: true,
                processing: true,
                serverSide: true,

                ajax: {
                    url: "{{ url('dashboard-data') }}",
                    data: function (d) {
                        d.location = $("#location_hidden").val();
                        d.date = $("#date_range").val();
                        d.status = $("#status_hidden").val();
                        d.attempt = $("#attempt_hidden").val();
                    },
                },

                columns: [
                    {data: 'lead_id', name: 'lead_id', searchable: true, sortable: true},
                    {data: 'requirement', name: 'requirement', searchable: true, sortable: false},
                    {data: 'location', name: 'location', searchable: true, sortable: true},
                    {data: 'budget', name: 'budget', searchable: true, sortable: false},
                    {data: 'ad_name', name: 'ad_name', searchable: true, sortable: false},
                    {data: 'short_link', name: 'short_link', searchable: true, sortable: false},
                    {data: 'status', name: 'status', searchable: true, sortable: true},
                    {data: 'action', name: 'action', searchable: false, sortable: false},
                    {data: 'purchased_by', name: 'purchased_by', searchable: true, sortable: false},
                    {data: 'price', name: 'price', searchable: true, sortable: false},
                    {data: 'created_at', name: 'created_at', searchable: true, sortable: true},
                ],
                language: {
                    processing: "<img src='{{asset('images/loader.gif')}}'> Processing....",
                },
     });

    $('#searchButton').click(function(){
          $('#mytable').DataTable().draw(true);
    });`

So, where can I put the `oTable.ajax.json()` help me to achieve this. Thank you.

**Comment by yajra** [comment]
You can add it on draw callback. Something like:

```js
let oTable = $('#mytable').DataTable();
oTable.on('draw', function () {
   console.log(oTable.ajax.json());
})
```

**Comment by UmeshKrRana** [comment]
Thank you very much Yajra. It worked.
