### ISSUE TITLE
Question re: nested Master-Detail tables

### ISSUE THREAD

**Issue by scottmc0525** [yajra/laravel-datatables#2453]
Are nested Master-Details tables allowed and supported? I need to create a table with expandable rows like this structure, but I wouldn't want to spend a lot of effort if it wouldn't work! Thanks much!

Manufacturer Name     Quantity     Total
...Category Name     Quantity     Total
......Size     Quantity     Total
.........Product     Quantity     Total
............ State     Quantity     Total
...............Dealer/Location     Quantity     Total

**Comment by yajra** [comment]
See demo https://datatables.yajrabox.com/eloquent/master for ref. It's a bit outdated but should work.
