### ISSUE TITLE
How to do lazy loading of records? +300000 records

### ISSUE THREAD

**Issue by devgiu** [yajra/laravel-datatables#2454]
TL;TR
What's the approach to use this plugin for tables with +300000 records.

I'm trying to implement a report using this plugin, but the problem I'm facing, is that seems like try to retrieve all records in once.
My "idea" is to only load records of each page and avoid to request all records because scripts crashed because out of memory.

This is what I use on my controller. I'm using Query builder and skipPaging as suggested on an older issue). Just for try, I tested doing some filtering too, and then works, but without filtering don't.

`return datatables(DB::table('mytable'))->skipPaging()->toJson();`

This is my JS side:
```
var table = $('#powersearch-table').DataTable({
           processing: true,
           serverSide: true,
           pageLength: 50,
           deferRender: true,	
           destroy: true,
           ajax: {
               url: "/powersearchajx",
               dataSrc: "data",
               type: "GET"
           },
           buttons: [
              'pageLength', 'csv', 'excel', 'pdf', 'print'
          ],
           columns: [
                mycolumns
           ],
       });

     $('#powersearch-table thead tr').clone(true).appendTo( '#powersearch-table thead' );
     $('#powersearch-table thead tr:eq(1) th').each( function (i) {
         var title = $(this).text();
         $(this).html( '<input type="text" placeholder="Search '+title+'" />' );

         $( 'input', this ).on( 'keyup change', function () {
             if ( table.column(i).search() !== this.value ) {
                 table
                     .column(i)
                     .search( this.value )
                     .draw();
             }
         } );
     } );
```

**Comment by UmeshKrRana** [comment]
Hello devgiu,
![2020-08-24_19h38_19](https://user-images.githubusercontent.com/30307542/91386105-ec230580-e84f-11ea-9845-b25bc61e20c0.png)
I have passed the additional parameters using the with function from controller like below snippet-
->with([ "cities" => app(\App\Http\Controllers\HelperController::class)->cityListing(), "leadCounters" => $this->leadCounters ]) ->make(true);

Now, how can we extract these keys values in the view side?
Here, in the attachment. I am getting the response.

**Comment by yajra** [comment]
@devgiu don't skip the paging unless you want to implement your own paging. Just remove `->skipPaging()`.
