### ISSUE TITLE
Reload button, change loading text/animation

### ISSUE THREAD

**Issue by kaizokupuffball** [yajra/laravel-datatables#2455]
Is there any way to change how the "reload" button works? I want to change the "processing" stuff when I click the reload button. I want to add an CSS animation when it is "processing", end the animation when it's done, and remove the "processing" text. Is this something i could fix with the $.extend method?

**Comment by yajra** [comment]
Reload button via js or php? For my projects, I use a class for each buttons. Here is a ReloadButton with custom classes and text for ref.

```php
namespace App\Editor\Buttons;

use Yajra\DataTables\Html\Button;

class ReloadButton extends Button
{
    /**
     * Create a new fluent instance.
     *
     * @param array|object $attributes
     * @return void
     */
    public function __construct($attributes = [])
    {
        $this->extend('reload')
             ->className('btn btn-sm btn-secondary btn-icon')
             ->text('<i class="flaticon2-refresh-button dt-icons text-dark" data-toggle="tooltip" title="Refresh"></i>');

        parent::__construct($attributes);
    }
}
```

**Comment by kaizokupuffball** [comment]
I was thinking JS, as I would need to check for when the ajax request was done so I could stop the animation.
Great example though!

**Comment by yajra** [comment]
I see, for js, this is what I currently use https://github.com/yajra/laravel-datatables-assets/blob/master/js/buttons/reload.js for spinning animation.

**Comment by kaizokupuffball** [comment]
That's exactly what I was looking for, if I could use the jQuery extend for this. Thanks! 👍 😄

**Comment by kaizokupuffball** [comment]
My stupid ass thought I got it when you gave me the code example.. 😂 

I am creating the button with PHP using the following code:
``` 
return $this->builder()->....->buttons(
    Button::make('reload')->addClass('btn-primary')->text('<i class="fas fa-fw fa-sync"></i>')
)
```

When I try the code from the JS example it just does nothing at all, no errors in console either. I probably am missing something or doing something wrong. 

I also tried to add the `action()` method with the action in the JS example, but that didn't work either. Do you have any clue what I am doing wrong? 😂
