### ISSUE TITLE
Server side search - extra fields

### ISSUE THREAD

**Issue by tcagkansokmen** [yajra/laravel-datatables#2456]
### How to change 'searchable fields'

Hi there,
Trying to use search function. But doesnt work as I expected.
I got two fields on database that; title and shortcode.

On datatable, I use only 'title' column.
But I want to use searching on 'shortcode' field too.

Actually, when user use 'quick search' I want it to search between title and shortcode fields.

But It doesnt search because there's no 'shortcode' field on datatable but also it is in database.

**Comment by yajra** [comment]
On you columns, add a hidden one for shortcode for it to be included in search

```js
columns: [
  {data: 'title'},
  {data: 'shortcode', visible: false},
]
