### ISSUE TITLE
How to display user defined column name in yajra datatables

### ISSUE THREAD

**Issue by Nahiyan47** [yajra/laravel-datatables#2458]
i am trying to view datatables where i have user defined columns.  It is showing the name of table column automatically. 

i have a class IncomesourceDatatable and from that class i am rendering to my view
below i have a function getColumns.

protected function getColumns()
    {
        return [
            'title',
            'description',
            'special_rule',
            'amount',
            'created_at',
        ];
    }

as i can see it shows the table column name as the column name in view, how can i put a user defined column name for example title as My Ttile

**Comment by gebaiwan** [comment]
addColumn?

**Comment by Nahiyan47** [comment]
can you please elaborate .?

**Comment by gebaiwan** [comment]
`
->addColumn('rename_title', function($datum){
  return $datum->title
})
->filterColumn('rename_title',  function($query, $keyword) {
                    $sql = "select title  like ?";
                    $query->whereRaw($sql, ["%{$keyword}%"]);
                })
`

js script: {data:'rename_title', name:'rename_title'}

will this solve your problem?

**Comment by shabeebrizvi** [comment]
> `->addColumn('rename_title', function($datum){ return $datum->title }) ->filterColumn('rename_title', function($query, $keyword) { $sql = "select title like ?"; $query->whereRaw($sql, ["%{$keyword}%"]); })`
> 
> js script: {data:'rename_title', name:'rename_title'}
> 
> will this solve your problem?

`->title('UserDefined')`

**Comment by demetreeus** [comment]
I assume the attributes here are compatible https://yajrabox.com/docs/laravel-datatables/master/html-builder-column .
So,
```
return [
 ['name' => 'column_1', 'title' => 'Da Column', 'data' => 'column_1'],
 ['name' => 'column_2', 'title' => 'Another Column', 'data' => 'column_2'],
]
```
works for me.
