### ISSUE TITLE
Column Search and Add/Edit/Remove Columns when using Datatables as a service

### ISSUE THREAD

**Issue by haakym** [yajra/laravel-datatables#246]
Awesome package! Thank you so much for developing this.

In brief I have the following issues:

1. Implement Datatables as a service with column filter and edit button column
2. Create a dropdown box for one column filter while the rest are text

I've got the basics working while using Datatables as a service, but I'm having trouble implementing Datatables as a service with [Filter Column Search](http://datatables.yajrabox.com/eloquent/add-edit-remove-column) and [Add/Edit/Remove Columns](http://datatables.yajrabox.com/eloquent/post-column-search) as the docs don't have an example of this (using both together) and I'm unsure where my code should go. My Datatable class for which I've tried to add the edit button currently looks like this but doesn't work:

```php
<?php

namespace App\DataTables;

use App\Models\Institution;
use yajra\Datatables\Services\DataTable;

class InstitutionDataTable extends DataTable
{
    // protected $printPreview = 'path-to-print-preview-view';
    // protected $exportColumns = ['id', 'name'];

    /**
     * Display ajax response.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
    {
        $query = $this->query();
        
        return $this->datatables
            ->of($query)
            ->addColumn('action', function ($query) {
                return '<a href="#edit-' . $query->id . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
            })
            ->setTransformer('App\Transformers\InstitutionTransformer')
            ->make(true);
    }

    /**
     * Get the query object to be processed by datatables.
     *
     * @return \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder
     */
    public function query()
    {
        $institutions = Institution::select();

        return $this->applyScopes($institutions);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns([
                'id',
                'name',
                'requires_id',
                'action'
            ])
            ->parameters([
                'dom' => 'Bfrtip',
                'buttons' => ['csv', 'excel', 'pdf', 'print', 'reset', 'reload'],
        ]);
    }
}
```

Also I'm unsure once I the column filtering working, how I can specify one column filter to be a dropdown box. The reason I want to do this is because one of my columns in the DB is a boolean and I transform is using fractal to output Yes if 1 and No if 0. So if I use just a text filter it will only accept 1 or 0 and not Yes or No whereas if I use a dropdown box I can set this up with the correct values. Hope that makes sense!

Any help would be appreciated.

**Comment by haakym** [comment]
Have added this to my JS:

```javascript
$('#dataTableBuilder').dataTable().fnFilterOnReturn();
```
and
```javascript
$('#dataTableBuilder').DataTable().fnFilterOnReturn();
```
as mentioned here: https://github.com/yajra/laravel-datatables/issues/51#issuecomment-145571498

But I get the following error:

```
Uncaught TypeError: $(...).DataTable(...).fnFilterOnReturn is not a function
```

I've also tried adding a callback in the fnFilterOnReturn to build the input boxes, but same issue.

**Comment by haakym** [comment]
For now I've reverted back to the original way of creating the datatable, so I'm no longer using it as a service.

I Couldn't get the additional column for an edit button working as mentioned on the [docs website](http://datatables.yajrabox.com/eloquent/add-edit-remove-column). After going through the issues I found this [helpful comment](https://github.com/yajra/laravel-datatables/issues/26#issuecomment-92690658) appear to have it working now, my implementation:

```js
columns: [
    /* other columns */
    {
        data: function(data) {
            return '<a href="#edit-' + data.id + '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
        }, "orderable": false, "searchable": false, name: 'action'
    }
]
```

I am still struggling to get the [column search](http://datatables.yajrabox.com/eloquent/multi-filter-select) working though. I have tried the code below in my javascript, but nothing at all shows up and no errors either?!

```js
$('#institutions-table').DataTable({
    /* other set up*/
    initComplete: function () {
        this.api().columns().every(function () {
            console.log(column);
            var input = document.createElement("input");
            $(input).appendTo($(column.footer()).empty())
            .on('change', function () {
                column.search($(this).val(), false, false, true).draw();
            });
        });
    }
});
```

Also, ideally once I have that working the third column should search by dropdown box, as I mentioned in the original post, rather than an text input box.

**Comment by yajra** [comment]
@haakym, dataTable as a service idea is to extract away most of the codes from our controller. We just wrap the functionality into it's own class but previous codes/way should be backward compatible to the new/develop version. 

For the dropdown, I think you can use it along with `filterColumn` implementation. Just take note on the regex flag on column search as it has an effect on the server side response. https://datatables.net/reference/api/columns().search()

**Comment by yajra** [comment]
For the add column, I think the problem was you were using `Transformer`, hence you should add the action column inside the transformer response.

**Comment by haakym** [comment]
@yajra Thanks for your reply and your support.

Some things are now working, but I still can't get everything working for the service approach annoyingly. Adding the additional column to the transformer worked, thank you!

However, I still can't get the search columns working when using the service approach and I'm really unsure where I'm going wrong. Can you please provide details on how I can get the search column working for the datatables as service approach.

Using the normal approach (not the service approach) I have thankfully got the column search working. It started working when I added the markup for `<tfoot>`:

```html
<table>
<!-- table contents -->
  <tfoot>
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
  </tfoot>
</table>
```

In the demo it appears to work without it?!

I also added the following js from the demo code modified slightly. (It should probably be refactored! Any comment for a better way to do this would be appreciated.):

```js
initComplete: function () {
    var j = 0;
    this.api().columns().every(function () {
        console.log(j);
        var column = this;
        if (j === 2) {
            var select = '<select>\
                <option value="">Select</option>\
                <option value="1">Yes</option>\
                <option value="0">No</option>\
            </select>';

            $(select).appendTo($(column.footer()).empty())
                .on('change', function () {
                    var val = $.fn.dataTable.util.escapeRegex($(this).val());
                    column.search(val ? val : '', true, false).draw();
                });
        } else {
            var input = document.createElement('input');
            $(input).appendTo($(column.footer()).empty())
                .on('change', function () {
                    var val = $.fn.dataTable.util.escapeRegex($(this).val());
                    column.search(val ? val : '', true, false).draw();
                });
        }
        j++;
    });
}
```

I would love to someday help with documentation for this awesome package.

**Comment by yajra** [comment]
Approach should be the same as how it was done on older version. Thanks!
