### ISSUE TITLE
How can sort from a custom columns that refers directly to a two or more differents field on DB?

### ISSUE THREAD

**Issue by Manu-sh** [yajra/laravel-datatables#2461]
### How can sort from a custom columns that refers directly to a two or more differents field on DB?

I have a custom column that came from 2 fields on model
```php
->addColumn('z_custom', static function ($m) {
   return $m->x * $m->y;
})
```

I would like sort for these two field example: `$query->orderBy('x', 'asc')->orderBy('y', $order_direction)` where `$order_direction` came from `datatable.html` and is reffered to `z_custom`.

in pseudo
```
->whenOrderRequestFor('z_custom', () => $query->orderBy('x', 'asc')->orderBy('y', getOrderDirection('z_custom'))
```

```js
table.DataTable({
   ...
   columns: [
      { data: 'z_custom', orderable: true, searchable: false }
   ]
  ...
})
```

- Linux
- PHP 7.x
- Laravel 6.x
- Laravel-Datatables v9.9.0

**Comment by yajra** [comment]
I think what you need is orderColumn. See https://yajrabox.com/docs/laravel-datatables/master/order-column.

**Comment by Manu-sh** [comment]
thankyou @yajra that seem exactly what im looking for
