### ISSUE TITLE
Column sorting of the Eloquent relations atributes is not working properly

### ISSUE THREAD

**Issue by JsMontesR** [yajra/laravel-datatables#2462]
# Column sorting of the Eloquent relations atributes is not working properly

Hi everyone!, I'll go straight to the point, when i try to sort a column by clicking head on the datatable, it replace all the "coincidencially same name atributes" of the nested model into the parent model columns

More specifically I have two eloquent models, ProductoTipo and Producto (which means ProductType and Product in english) the Producto model has the "with" property with his ProductoTipo relation as follows:

### Model Producto
```php
class Producto extends Model
{
    protected $with = ["tipo"];
    protected $guarded = ["id"];

    public function tipo(){
        return $this->belongsTo('App\ProductoTipo');
    }

```
This means every time that I retrive the model it will came up with the "tipo" relation already loaded, that's ok.

I have a ProductoController in which i list all the Productos (products)  as follows:

```php
public function list(){
        return datatables()->eloquent(Producto::query())->toJson();
    }

```

And i render that list response using this JS snippet:
```javascript

$('#recurso').DataTable($.extend({
            serverSide: true,
            ajax: 'api/productos/listar',
            columns: [
                {data: 'id', name: 'id', title: 'Id', className: "text-center"},
                {data: 'nombre', name: 'nombre', title: 'Nombre', className: "text-center"},
                {data: 'categoria', title: 'Categoría', className: "text-center"},
                {
                    data: 'costo',
                    name: 'costo',
                    title: 'Costo Unitario/Kg',
                    render: $.fn.dataTable.render.number(',', '.', 0, '$ '),
                    className: "text-center"
                },
                {
                    data: 'utilidad',
                    name: 'utilidad',
                    title: 'Utilidad Unitaria/Kg',
                    className: "text-center",
                    render: function (data, type, full, meta) {
                        return +data + '%';
                    }
                },
                {
                    data: 'precio',
                    name: 'precio',
                    title: 'Precio Unitario/Kg',
                    render: $.fn.dataTable.render.number(',', '.', 0, '$ '),
                    className: "text-center"
                },
                {
                    data: 'stock', name: 'stock', title: 'Unidades/g en stock', render: function (data, type, row) {
                        if (row["categoria"] == "Granel") {
                            return +data + ' gramos';
                        } else if (row["categoria"] == "Unitario") {
                            return +data + ' unidades';
                        }

                    }, className: "text-center"
                },
                {
                    data: 'tipo.id',
                    name: 'tipo.id',
                    title: 'Id de tipo',
                    visible: false,
                    searchable: false,
                    className: "text-center"
                },
                {data: 'tipo.nombre', name: 'tipo.nombre', title: 'Tipo de producto', className: "text-center"},
                {data: 'created_at', name: 'created_at', title: 'Fecha de creación', className: "text-center"},
                {data: 'updated_at', name: 'updated_at', title: 'Fecha de actualización', className: "text-center"},
            ]
        }, options));

```
"options" is a js file that contain some lang configuration, nothing problematic i think...

```javascript

let options = {
    "aLengthMenu": [[5, 10, 25, 50, 100 - 1], [5, 10, 25, 50, 100, "Todos"]],
    "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Registros del _START_ al _END_, total _TOTAL_ registros",
        "sInfoEmpty": "Registros del 0 al 0, total 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "Primero",
            "sLast": "Último",
            "sNext": "Siguiente",
            "sPrevious": "Anterior"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        },
        "buttons": {
            "copy": "Copiar",
            "colvis": "Visibilidad"
        }
    }

}
```

The result, this one...

![image](https://user-images.githubusercontent.com/30935905/93253305-539be900-f75c-11ea-9da7-d51d3b2abbf8.png)

For sorting i proceed to click over one of the theader of a column, and it works fine with columns that belongs to the Product model but when i try to sort the "Tipo de producto" column that references the ProductoType name it change all table values as follows:

![image](https://user-images.githubusercontent.com/30935905/93253737-ec326900-f75c-11ea-8d7e-dd873d016a1b.png)

It seems that the name of the product (in "Nombre" column) is now the name of the ProductType and the Ids and timestamps are now duplicated, and i dont know why... I really need your help, thanks!.

### System details

- Windows 10 1909
- PHP 7.4.9
- Laravel 7
- Laravel-Datatables 9.10.2

**Comment by albertoelias123** [comment]
Hello, I am having the same problem.

I've found that it's not just about replacing properties when filtering out something from a nested relationship. It inserts ALL the properties of the nested object in the "main" object, so the attributes with the same name (id, created_at, updated_at, deleted_at and others) end up being overwritten.

For example, I have a class "Person" and another "Representative", a "Person" hasOne "Representative", so in the "Representative" Model I put with = ['person'] to have the data for "Person" associated.
When using datatables, everything happens normally when I order with a "Representative" column, as shown below:
![image](https://user-images.githubusercontent.com/41304037/94497914-0ba2aa80-01cf-11eb-9bc6-d50c482b3300.png)

However, when i order the table with an attribute of "Person" in the ID case, it places the "Person" information in the "Representative", as shown below:
![image](https://user-images.githubusercontent.com/41304037/94497955-33920e00-01cf-11eb-925c-63d8cd979c2e.png)

In the image, we can see that the "Person" id, name, document and other fields went to "Representative".

For now, the solution I found was in the Representative model to remove the with = ['person'] from the Representative, so as not to load the person's information when taking a Representative.

In Datatables, I manually added the columns I want, added the sorting and added filtering, so it worked. However, for each field I need I have to write 14 lines of repetitive cod, I believe that this is not the ideal thinking about DRY (Don't Repeat Yourself)
![image](https://user-images.githubusercontent.com/41304037/94501510-5d9bfe00-01d8-11eb-98e0-29bc3e55fbce.png)
![image](https://user-images.githubusercontent.com/41304037/94501553-7c01f980-01d8-11eb-8275-295a16dda312.png)
Above the server response WITHOUT the problem of this issue

            ->addColumn('pessoa.name', function(Representante $rep){
                return $rep->pessoa->name;
            })
            ->orderColumn('pessoa.name', function ($query, $order) {
                $query
                    ->leftJoin('pessoas', 'representantes.pessoa_id', '=', 'pessoas.id')
                    ->orderBy('pessoas.name', $order)
                    ->select('representantes.*');
            })
            ->filterColumn('pessoa.name', function($query, $keyword) {
                $query->whereHas('pessoa', function($query) use ($keyword){
                    $query->where('name', 'like', '%'.$keyword.'%');
                });
            })

DETAIL: without the SELECT after the leftJoin the same problem occurs with the nested relationship, it loads all the information from the two tables.
When placing the select I leave specified to get ONLY the information from the "main" table in my case, representative.
I believe that in the datatables code, there is some leftJoin to perform the ordering in nested relationships but there is no select

Note, I am Brazilian so "Person" = "Pessoa" and "Representative" = "Representante"

**Comment by yajra** [comment]
When using eager loading / relationships, it is suggested to include a select in your main query. For instance:

```php
Producto::query()
```

Should be converted to something like:

```php
Producto::query()->select('productos.*')->with('tipo')
```

Adding a select explicitly prevents this odd behavior as documented [here](https://datatables.yajrabox.com/eloquent/relationships).

**Comment by JsMontesR** [comment]
Thank you so much!
