### ISSUE TITLE
column sorting and searching not working when serverside mode

### ISSUE THREAD

**Issue by deded89** [yajra/laravel-datatables#2464]
### Summary of problem or feature request

try to use laravel datatables for serverside,, data loaded perfectly but one of my column (the status column/ columns[2]) not sortable and not searchable, it's contain boolen data.

### Code snippet of problem

below is my code to load the table

```php
 let table = $('#simpleTable').DataTable({
            processing: true,
            serverSide: true,
            responsive: false,
            dom: '<"d-flex justify-content-between"pf>t', //default is 'lftipr'
            pagingType: 'simple',
            ajax: "{{ route('cabangs.index') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'nama_cabang',
                    name: 'nama_cabang',
                },
                {
                    data: 'is_open',
                    name: 'status',
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false
                },
            ]
        });
```
info from console  :

draw | 1
-- | --
columns[0][data] | DT_RowIndex
columns[0][name] | DT_RowIndex
columns[0][searchable] | true
columns[0][orderable] | true
columns[0][search][value] |  
columns[0][search][regex] | false
columns[1][data] | nama_cabang
columns[1][name] | nama_cabang
columns[1][searchable] | true
columns[1][orderable] | true
columns[1][search][value] |  
columns[1][search][regex] | false
columns[2][data] | is_open
columns[2][name] | status
columns[2][searchable] | true
columns[2][orderable] | true
columns[2][search][value] |  
columns[2][search][regex] | false
columns[3][data] | action
columns[3][name] | action
columns[3][searchable] | false
columns[3][orderable] | false
columns[3][search][value] |  
columns[3][search][regex] | false
order[0][column] | 0
order[0][dir] | asc
start | 0
length | 10
search[value] |  
search[regex] | false
_ | 1600522801134

but when I set the 
```php
processing: false,
serverside: false

```
the status column sortable and searchable

### System details

- OS = Windows 10
-  PHP =7.4.8
- Laravel 7
- Laravel-Datatables Version = "yajra/laravel-datatables-oracle": "~9.0"

**Comment by yajra** [comment]
DT_RowIndex is not searchable / orderable too

```
{
  data: 'DT_RowIndex',
  name: 'DT_RowIndex',
  orderable: false,
  searchable: false
}
```
