### ISSUE TITLE
Pointing to wrong model path when generating DataTable - Laravel 8

### ISSUE THREAD

**Issue by AjithLalps** [yajra/laravel-datatables#2468]
### Summary of problem or feature request

Laravel 8 introduced a new folder `Models` for the model class. When generating DataTable by `php artian datatables:make` command, the model namespace is wrong.

Model is pointing to `App` namespace instead of `App\Models` namespace.

### System details

- Operating System windows 10
- PHP Version 7.4
- Laravel Version 8.x
- Laravel-Datatables Version 1.5

**Comment by yajra** [comment]
Should be fixed on latest version. Thanks for reporting.
