### ISSUE TITLE
how i,m run function on query

### ISSUE THREAD

**Issue by mohsenmehribusiness** [yajra/laravel-datatables#2469]
### how run function on query
`
> public $words=null;
> public function AjaxQueryData(Request $request){
>         $this->words=Datatables::of(Word::query())
>             ->setRowId(function ($user) {
>             return $user->id;
>         })
>         ->addColumn('persian', function(Word $word){return view('study.yajra.persianColumn',compact('word'));})
>         ->addColumn('setting', function(Word $word){return view('study.yajra.settingColumn',compact('word'));})
>             //??  i,m want here just right here
**>         ->filter(function(Word $word){ return $word->details()->state == 1;}) //*********i,m want like here**
>             //??  i,m want here just right here
>         ->make(true);
>         return $this->words;
>     }
`

**Comment by yajra** [comment]
Please see https://yajrabox.com/docs/laravel-datatables/master/manual-search for details on how to use the `filter` api. Thanks!
