### ISSUE TITLE
editColumn using HTML Builder

### ISSUE THREAD

**Issue by Skintillion** [yajra/laravel-datatables#247]
Is there a way to editColumn using DataTables as a Service?

For example using the Eloquent method I can:

```
return Datatables::of($list)
    //Show Type Icon
    ->editColumn('typeicon', '<i class="{{ $typeicon }} fa-2x glyphicon-2x">{{ $typeicontext }}</i>')
```

but there is no way I can see of doing this using the HTML Builder.

**Comment by yajra** [comment]
Yes, you can basically do everything from old version to the new one. Just add your `editColumn` on the `ajax` method. The develop branch is backward compatible.

**Comment by yajra** [comment]
On `html` method, you just need to specify the column as instructed on this tutorial. http://datatables.yajrabox.com/service

**Comment by Skintillion** [comment]
Thank you Yajra I should have noticed that thank you!
