### ISSUE TITLE
Exception Message: array_intersect_key(): Expected parameter 1 to be an array, null given

### ISSUE THREAD

**Issue by madnankhan00** [yajra/laravel-datatables#2470]
Hi there, 
can you please help me. 
I'm facing error "array_intersect_key(): Expected parameter 1 to be an array, null given"

using datatables 9.0, laravel 8.6.0, PHP 7.4.8

code:
use Yajra\DataTables\DataTables;

    public function getAllPatientTests()
    {
        return $this->dataTables->eloquent($this->patientTests())->toJson();
    }

    public function patientTests()
    {
        return PatientTest::select(
            'patient_tests.display_id',
            'patient_tests.result',
            'patient_tests.created_at',
            'tests.name as test_name',
            'units.name as test_unit',
            'patients.name as patient_name',
            'sub_categories.name as sub_categories_name',
            'categories.name as categories_name'
            )
        ->join('tests','tests.id','patient_tests.test_id')
        ->join('units','tests.normal_range_unit_id','units.id')
        ->join('patients','patients.id','patient_tests.patient_id')
        ->leftjoin('sub_categories','sub_categories.id','tests.sub_category_id')
        ->leftJoin('categories','categories.id','tests.category_id');
    }

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by ikechukwukalu** [comment]
How did you resolve this?

**Comment by ikechukwukalu** [comment]
> How did you resolve this?

`php artisan config:cache`

Worked for me
