### ISSUE TITLE
Can this be used with DataTables Search Panes

### ISSUE THREAD

**Issue by einkinder** [yajra/laravel-datatables#2471]
### Summary of problem or feature request

I would like to incorporate DataTables Search Panes but I am not seeing how to add.
https://datatables.net/extensions/searchpanes/examples/

- Operating System
- PHP Version 7.4
- Laravel Version 8 
- Laravel-Datatables Version latest

**Comment by yajra** [comment]
Duplicate of https://github.com/yajra/laravel-datatables/issues/2463.
