### ISSUE TITLE
Page numbers in exported PDFs

### ISSUE THREAD

**Issue by mayanxoni** [yajra/laravel-datatables#2476]
### Summary of problem or feature request

I'm trying to add page numbers to the PDF generated by exporting the Yajra/DataTable.

### Code snippet of problem

I tried using the code from

[http://live.datatables.net/relopimi](http://live.datatables.net/relopimi)

But couldn't make it work out.

### System details

- Operating System: Windows 10 Pro
- PHP Version: 7.4.8
- Laravel Version: 7.5.2
- Laravel-Datatables Version: v9.10.0

**Comment by yajra** [comment]
You should do it via server side too. You can override `print.blade.php` and adjust as needed. 

You can also use a different template if you prefer. Just set `protected $printPreview = 'custom.view.path';` on your DT class.
