### ISSUE TITLE
Serverside Render - So Slow Performance

### ISSUE THREAD

**Issue by tcagkansokmen** [yajra/laravel-datatables#2482]
`I am using serverside render. And my code is below.

There's only 2500 products on list.
And it takes 30 seconds to render. If I remove "Datatables::of($products)->make(true);" line, it returns on 20ms.

What's wrong with it?
What should I do?

        $parameters = $this->request->query();
        $firm_id = $this->request->user()->firm_id;

        $products = Product::where('firm_id', $firm_id)
        ->with(['category', 'inventory' => function($q){
            $q->where('cost', '>', 0);
        }])
        ->orderBy('id', 'desc');
        if(isset($parameters['category_id'])){
            $products = $products->where('product_category_id', $parameters['category_id']);
        }

        $products = $products->get();

        $products = ProductResource::collection($products);

        return Datatables::of($products)->make(true);`

**Comment by yajra** [comment]
Try removing this line and try again.

```php
$products = $products->get();
```

**Comment by pirex360** [comment]
With a table with only 50 users the eloquent query is 0.04s, but the function of Datatables take too long 8 seconds, this is my function :

```
function dataTables()
    {
        // query
 
        return DataTables::of(User::query()
                            ->with('roles')
                            ->where('id', '!=', Auth::user()->id)
        )

        ->setRowId(function ($data) {
            return $data->id;
        })

        ->setRowData( ['data-name' => '{{$name}}'] )

        ->setRowAttr([
            'data-name' => '{{$name}}',
        ])


        ->addColumn('_enabled', function($data){
            $vis = $data->enabled ? "<span class='badge badge-pill badge-soft-success rounded-0'>ATIVO</span>" : "<span class='badge badge-pill badge-soft-dark rounded-0'>INATIVO</span>";
            return $vis;
        })

        ->addColumn('options', function ($data) {
            $editUrl = route('user.edit', ['id' => $data->id]);
            $viewUrl = route('user.show', ['id' => $data->id]);

            $btn_view = "<a href='{$viewUrl}'>
            <button
                type='button'
                id='view-{$data->id}'
                class='btn btn-sm btn-primary rounded-0'>
                <i class='fas fa-eye'></i> ". __('Ver') .
            "</button>
            </a>";
            $btn_edit = "<a href='{$editUrl}'>
            <button
                type='button'
                id='edit-{$data->id}'
                class='btn btn-sm btn-info rounded-0'>
                <i class='fas fa-edit'></i> ". __('Editar') .
            "</button>
            </a>";
            $btn_delete = "<button
                type='button'
                id='del-{$data->id}'
                class='btn btn-sm btn-danger btn-del rounded-0'>
                <i class='fas fa-trash'></i> ". __('Apagar') .
            "</button>";
            // Button Auth Logic
            $buttons =  ((Auth::user()->can('user-view')) ? $btn_view : NULL) .
                        ((Auth::user()->can('user-edit')) ? $btn_edit : NULL) .
                        ((Auth::user()->can('user-delete')) ? $btn_delete : NULL);
            return $buttons;
        })

        ->editColumn('_last_login_at', function($data){
            $formatedDate = __('Nunca');
            if ($data->last_login_at) {
                $formatedDate = Carbon::createFromFormat('Y-m-d H:i:s', $data->last_login_at)->diffForHumans();
            }

            return $formatedDate;
        })

        ->rawColumns(['_enabled','options'])

        //->toJson();
        ->make(true);
    }
```

**Comment by slossetti** [comment]
> With a table with only 50 users the eloquent query is 0.04s, but the function of Datatables take too long 8 seconds, this is my function :
> 
> ```
> function dataTables()
>     {
>         // query
>  
>         return DataTables::of(User::query()
>                             ->with('roles')
>                             ->where('id', '!=', Auth::user()->id)
>         )
> 
>         ->setRowId(function ($data) {
>             return $data->id;
>         })
> 
>         ->setRowData( ['data-name' => '{{$name}}'] )
> 
>         ->setRowAttr([
>             'data-name' => '{{$name}}',
>         ])
> 
> 
>         ->addColumn('_enabled', function($data){
>             $vis = $data->enabled ? "<span class='badge badge-pill badge-soft-success rounded-0'>ATIVO</span>" : "<span class='badge badge-pill badge-soft-dark rounded-0'>INATIVO</span>";
>             return $vis;
>         })
> 
>         ->addColumn('options', function ($data) {
>             $editUrl = route('user.edit', ['id' => $data->id]);
>             $viewUrl = route('user.show', ['id' => $data->id]);
> 
>             $btn_view = "<a href='{$viewUrl}'>
>             <button
>                 type='button'
>                 id='view-{$data->id}'
>                 class='btn btn-sm btn-primary rounded-0'>
>                 <i class='fas fa-eye'></i> ". __('Ver') .
>             "</button>
>             </a>";
>             $btn_edit = "<a href='{$editUrl}'>
>             <button
>                 type='button'
>                 id='edit-{$data->id}'
>                 class='btn btn-sm btn-info rounded-0'>
>                 <i class='fas fa-edit'></i> ". __('Editar') .
>             "</button>
>             </a>";
>             $btn_delete = "<button
>                 type='button'
>                 id='del-{$data->id}'
>                 class='btn btn-sm btn-danger btn-del rounded-0'>
>                 <i class='fas fa-trash'></i> ". __('Apagar') .
>             "</button>";
>             // Button Auth Logic
>             $buttons =  ((Auth::user()->can('user-view')) ? $btn_view : NULL) .
>                         ((Auth::user()->can('user-edit')) ? $btn_edit : NULL) .
>                         ((Auth::user()->can('user-delete')) ? $btn_delete : NULL);
>             return $buttons;
>         })
> 
>         ->editColumn('_last_login_at', function($data){
>             $formatedDate = __('Nunca');
>             if ($data->last_login_at) {
>                 $formatedDate = Carbon::createFromFormat('Y-m-d H:i:s', $data->last_login_at)->diffForHumans();
>             }
> 
>             return $formatedDate;
>         })
> 
>         ->rawColumns(['_enabled','options'])
> 
>         //->toJson();
>         ->make(true);
>     }
> ```

I have the same issue, when I add a addColumn the performance is too slow.

**Comment by yajra** [comment]
See https://github.com/yajra/laravel-datatables/discussions/2496
