### ISSUE TITLE
Ordering on addColumn 

### ISSUE THREAD

**Issue by lakshmiiyngaran** [yajra/laravel-datatables#2484]
### Summary of problem or feature request

I have this query:

 $userlist = [DB::table('vv_users')->select('vv_users.user_id','vv_users.first_name','vv_users.mobile_number','vv_users.user_code','vv_users.user_type',](url) 'vv_users.child_cnt','vv_users.unique_device_id')->where('vv_users.user_status', '=', 'Active') ->whereNotNull('vv_users.uuid');
        return Datatables::of($userlist)
        ->addColumn('myteamcnt', function ($userlist) {
            $child_cnt = DB::table('vv_users')->where('user_status', '=', 'Active')->where('parent_id',$userlist->user_id)->count();
            return $child_cnt;
        })
        ->addColumn('whatsappid', function ($userlist) {
            return '<a href="https://api.whatsapp.com/send?phone=91'.$userlist->mobile_number.'&text=Hi" target="_blank" style="border-style: none"><img src="https://img.icons8.com/color/24/000000/whatsapp.png" style="" /></a>';
        })
        ->rawColumns(['whatsappid'])
        ->make(true);
        return Datatables::of($users)->make(true);
	
	and in blade/js:

		$('#appmyteamusers').DataTable({
            "processing": true,
            "serverSide": true,
            dom: 'Blfrtip',
            "order": [[3, "desc" ]],
            lengthMenu: [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
        "iDisplayLength": 50,
        
            "ajax":{
				"url": "{{ url('admin/report/postappuserreport') }}",
				"dataType": "json",
				"type": "POST",
				"data":{ _token: "{{csrf_token()}}"}
            },
            "columns": [
				{data: 'user_id', name: 'vv_users.user_id'},
				{data: 'first_name', name: 'vv_users.first_name'},
				{data: 'mobile_number', name: 'vv_users.mobile_number'},
				{data: 'myteamcnt',name: 'myteamcnt', orderable: true,sortable : true },
				{data: 'unique_device_id', name: 'vv_users.unique_device_id'},
				{data: 'whatsappid', name: 'whatsappid'},
            ]
        });

**this code working fine. i need only myteamcnt sort order...that is not working... please any one help me**

### System details

- Operating System : Windows 7 Professional
- PHP Version : 7.1.3
- Laravel Version : 5.8
- Laravel-Datatables Version : 9.11

**Comment by yajra** [comment]
Since you are using query builder, you need to do include the count query inside and not add it using addColumn.

```php
DB::table('vv_users')
  ->select('vv_users.user_id','vv_users.first_name','vv_users.mobile_number','vv_users.user_code','vv_users.user_type',](url) 'vv_users.child_cnt','vv_users.unique_device_id')
  ->addSelect('(count_sql_here) as myteamcnt')
  ->where('vv_users.user_status', '=', 'Active') 
  ->whereNotNull('vv_users.uuid')
```

Another ways is to use Eloquent and `withCount()`.
