### ISSUE TITLE
usage with only eloquent not laravel

### ISSUE THREAD

**Issue by Goddard** [yajra/laravel-datatables#2486]
I am working on converting an old code base of CI 3 which is currently partially using Eloquent through something called Capsule.
https://github.com/illuminate/database

I am curious if using this package would be possible.  I eventually would like to migrate the entire code base to use Laravel, but for now I am doing things piece by piece.

Adding this package would help alot.  Is it possible to use this with that package only and not the entire laravel stack?

**Comment by yajra** [comment]
Unfortunately, I don't have idea if this package will work without laravel. Functions and features and mostly dependent on the framework >.<
