### ISSUE TITLE
DataTable changing the output of a bigint value

### ISSUE THREAD

**Issue by NichoTheMan** [yajra/laravel-datatables#2490]
### Summary of problem or feature request

I use steam authentication for a project and that stores SteamIDs in a column (bigint) in the users table. The SteamID remains the same until the point where I use DataTable. DataTable changes the example SteamID from ``76561198083670208`` to ``76561198083670200`` (the last number). In all cases I have tested it will only change the last number, usually increasing it or decreasing by 6-9.

### Code snippet of problem

```php
public function users(){
        $users = User::select('*');
        return Datatables::eloquent($users)
                ->make(true);
    }
```

**SteamID output**: 76561198083670200

### System details

- Operating System: Ubuntu 18.04
- PHP Version: 7.3.22-1
- Laravel Version: 8(.1 i think)
- Laravel-Datatables Version: ~9.0

**Comment by NichoTheMan** [comment]
It seems the issue is BIGINT.

Changing the type to ``VARCHAR`` restored expected results.

**Comment by harugon** [comment]
Use ``editColumn``.

convert bigint to string

```php
public function users(){
        $users = User::select('*');
        return Datatables::eloquent($users)
        ->editColumn('SteamID', function($users ){
                return strval($users->SteamID);
            })->make(true);
    }
    ```
