### ISSUE TITLE
Uncaught Cannot extend unknown button type: create

### ISSUE THREAD

**Issue by kossa** [yajra/laravel-datatables#2492]
### Datatable not loading

I followed this tutorial : https://yajrabox.com/docs/laravel-datatables/master/quick-starter on fresh Laravel 8 installation. I got an error : `Uncaught Cannot extend unknown button type: create`

### System details

- Operating System: MacOs Catalina
- PHP Version: 7.4
- Laravel Version: 8
- Laravel-Datatables Version : ^1.5

![image](https://user-images.githubusercontent.com/1175584/97070508-c8bad380-15d0-11eb-8399-b2909fbcd1be.png)

![image](https://user-images.githubusercontent.com/1175584/97070514-d3756880-15d0-11eb-91ea-38e1e4d9af36.png)

**Comment by schonhoff** [comment]
Hi,

did you import the button js into the bootstrap.js?

```
require('datatables.net-buttons-bs4');
```

Personally I import all js/css files into the view directly by pushing it into a stack (Blade) because some sites on my own site doesn't use datatables.

**Comment by kossa** [comment]
![image](https://user-images.githubusercontent.com/1175584/97152256-ec1c8480-1770-11eb-8ac9-d3585ce7850b.png)

**Comment by schonhoff** [comment]
Can you try changing:
```
@push('scripts')
    {{$dataTable->scripts()}}
@endpush
```
to:
```
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.bootstrap4.min.js"></script>
```

in your resources/views/users/index.blade.php?

Can you post your resources/views/layouts/app.blade.php changes?

**Comment by kossa** [comment]
![image](https://user-images.githubusercontent.com/1175584/97153263-7dd8c180-1772-11eb-8c71-bff4ef532449.png)

![image](https://user-images.githubusercontent.com/1175584/97153274-829d7580-1772-11eb-9751-d291990d847a.png)

**Comment by schonhoff** [comment]
Last try:
Maybe try to insert the script tags and the ```@stack('scripts')``` into the header of your app.blade.php file.

Maybe @yajra have another idea? Maybe a screenshot from your Network tab from the dev-tool can be helpful.

**Comment by kossa** [comment]
No error in the console

**Comment by kossa** [comment]
The table is empty(in DB I have 100rows)

**Comment by yajra** [comment]
The server-side buttons script should be loaded after the main scripts. 

```php
-- app.js
@stack('scripts')

...
@push('scripts')
-- dt.js
-- bs4.js
-- buttons.server-side.js

{{ $dataTable->scripts() }}
@endpush
```

**Comment by abhitheawesomecoder** [comment]
I am facing same issue. How to fix?

**Comment by azamuddin** [comment]
I faced same Issue, I did solve it by removing  the original script call to `js/app.js` in the layout app

Remove this code, it is in the head of `layouts/app.blade.php`
```html
    <script src="{{ asset('js/app.js') }}" defer></script>
```

Then insert the datatables script required, after body or wherever you like

```html
    <script src="{{ mix('js/app.js') }}"></script>
    <script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
    @stack('scripts')
```

**Comment by dwain-lab** [comment]
> 
> 
> I faced same Issue, I did solve it by removing the original script call to `js/app.js` in the layout app
> 
> Remove this code, it is in the head of `layouts/app.blade.php`
> 
> ```
>     <script src="{{ asset('js/app.js') }}" defer></script>
> ```
> 
> Then insert the datatables script required, after body or wherever you like
> 
> ```
>     <script src="{{ mix('js/app.js') }}"></script>
>     <script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
>     @stack('scripts')
> ```

Thanks this helped.  This change allowed me to view the table.

**Comment by maganius** [comment]
I have the same issue, I dont know why.

`dataTables.buttons.min.js:19 Uncaught Cannot extend unknown button type: create`

I tried with webpack

![image](https://user-images.githubusercontent.com/8250243/126414690-bd240a08-0c51-4fde-b714-1b28004bff78.png)

I tried with cdn without luck

![image](https://user-images.githubusercontent.com/8250243/126414746-2c7f2dc5-84d1-44b9-b276-aec591da1ece.png)

```
php artisan -V
Laravel Framework 8.50.0
```

**Comment by yajra** [comment]
@maganius you need to publish and load the package custom scripts

```
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
```

**Comment by sfinktah** [comment]
@yajra I think there is substantial confusion because of what is actually in `app.blade.php` in Laravel 8.  It might be helpful to describe a compete replacement to that file in your Quickstart guide.

Though my `app.blade.php` was far from virginal, I had to add things like `@yield content`.  

Also:  `UsersDataTable.php`
    
    use App\User;

Should be App\**Model**\User;

In the web.php routing file, those non-namespaced string specified classes are no longer valid in Laravel 8.  Either:

    Route::get('/animals', 'App\Http\Controllers\AnimalsController@index')->name('animals.index');
    # or 
    Route::get('/animals', [AnimalsController::class, 'index'])->name('animals.index');
