### ISSUE TITLE
Exclude columns when exporting

### ISSUE THREAD

**Issue by dhcmega** [yajra/laravel-datatables#2499]
### Summary of problem or feature request

Problem: Export is too slow
Reason?: I think the problem is that the action column is processed for each line
If I skip the action column (in my case with 20k records) export speed is many times faster.

### Code snippet of problem

```php
        return $dataTable->addColumn('action', 'admin.users.datatables_actions');
```

Actual work around
```php
        if($this->request()->filled('action')) {
            return $dataTable;
        }
        return $dataTable->addColumn('action', 'admin.users.datatables_actions');
```

I found this using `strace`
There was one of this chunks per row (user in this case).
This a simplified part of the strace output:

```
access("storage/framework/views/c08be0011b8c2177fd317340650742011c1b1208.php", F_OK) = 0
stat("resources/views/admin/users/datatables_actions.blade.php", {}) = 0
stat("storage/framework/views/c08be0011b8c2177fd317340650742011c1b1208.php", {}) = 0
lstat("resources/views/admin/users/datatables_actions.blade.php", {}) = 0
lstat("resources/views/admin/users", {}) = 0
lstat("resources/views/admin", {}) = 0
lstat("resources/views", {}) = 0
lstat("resources", {}) = 0
```

Even though the column is not exported, it's being processed.
I hope I got right and I am not confused about this.

Thanks!

### System details

- Operating System: Linux Ubuntu
- PHP Version: 7.3.11
- Laravel Version: 7.28.4
- Laravel-Datatables Version: 9.11.1

**Comment by dhcmega** [comment]
I have just realised that this is not a datatables problem. I'm adding a column (action) that has no parameter with exportable = false.

**Comment by yajra** [comment]
Are you using the DataTable service class? If yes, you can override `$exportColumns` property and exclude the action column.

```php
protected $exportColumns = [];
```

**Comment by dhcmega** [comment]
Hi, thanks for responding, I will check it.

**Comment by yajra** [comment]
Btw, you can also use `->exportable(false)` on you column definitions:

```php
Column::computed('action')->exportable(false)->printable(false);
```
