### ISSUE TITLE
add pagination parameters

### ISSUE THREAD

**Issue by whoami15** [yajra/laravel-datatables#2508]
### Feature request

Is it possible to add pagination parameters?

something like this
`/records?page=1`

**Comment by yajra** [comment]
Yes it's possible. However, you need a custom js for it to work. There is a legacy extension but can't recall what it was called. I think it has something todo with stateSave.

Better check with datatables.net forum since this is more of a js implementation.

**Comment by whoami15** [comment]
> Yes it's possible. However, you need a custom js for it to work. There is a legacy extension but can't recall what it was called. I think it has something todo with stateSave.
> 
> Better check with datatables.net forum since this is more of a js implementation.

Thank you
