### ISSUE TITLE
Browser throws ajax error when addColumn is used in controller

### ISSUE THREAD

**Issue by aleary06** [yajra/laravel-datatables#251]
So far I'm really liking this package. Thanks for developing this! I am having one small issue. When trying to add some CRUD functions to a table via the addColumn method in my controller I get a 404 error. Removing that column allows the rest of the table data to load as expected. Here's my code:

In the controller:

```php
public function show()
{
    $employees = Employee::select('id', 'last_name', 'first_name', 'position', 'department', 'email', 'ext', 'start_date');

    return Datatables::of($employees)
        ->addColumn('action', '<a href="{{ route(\'employees.edit\')}}" data-target="#myModal" role="button" class="btn btn-success" data-toggle="modal">Edit</a>')
        ->make(true);
}
```

In my views:

master.blade.php:
```javascript
...
<script>
    $(document).ready(function() {
        $('#employees-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route("employees.show") }}',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'first_name', name: 'first_name' },
                { data: 'last_name', name: 'last_name' },
                { data: 'position', name: 'position' },
                { data: 'department', name: 'department' },
                { data: 'email', name: 'email' },
                { data: 'ext', name: 'ext'},
                { data: 'start_date', name: 'start_date'},
                { data: 'actions', name: 'actions'}
            ]
        });
    });
```

admin.blade.php
```html
@extends('layouts.master')

...

<table class="table table-striped row-bordered" id="employees-table">
    <thead>
      <tr>
          <th>ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Position</th>
          <th>Department</th>
          <th>Email</th>
          <th>Ext.</th>
          <th>Start Date</th>
          <th></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
          <th>ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Position</th>
          <th>Department</th>
          <th>Email</th>
          <th>Ext.</th>
          <th>Start Date</th>
          <th></th>
      </tr>
    </tfoot>
</table>
```

As I mentioned above, removing the addColumn from my controller (and the corresponding code in my views), the rest of the table loads as expected, and I don't understand why adding the column causes a 404 error. Additionally, if I navigate to the json data directly (mysite.com/public/employees/show) I can see the data:

![raw_json_2](https://cloud.githubusercontent.com/assets/11541037/11122314/adffa442-8928-11e5-83e7-0f01c9d78fbf.PNG)

And in Firebug, here's the error I'm getting:

![firebug_output_2](https://cloud.githubusercontent.com/assets/11541037/11122539/a706ab44-8929-11e5-96de-a3cd851387f3.PNG)

Do you see what I'm doing wrong here? Thanks in advance for your help!

**Comment by Skintillion** [comment]
I think your error is here.

```a href="{{ route(\'employees.edit\')}}

Remove the blade code here temporarily and see if it loads.

**Comment by aleary06** [comment]
Hi Skintillion, thanks for the response. I just replaced the blade code with '#' and then replaced the entire anchor tag with just `<a href="#">edit</a>`, but I still get the same error.

**Comment by Skintillion** [comment]
In firebug what do the response and html tabs display?

**Comment by Skintillion** [comment]
Wait in your noun for action is plural in one spot and singular in another.
In your columns you have "actions" but in the addcolumn you put "action".
Try fixing that.

**Comment by aleary06** [comment]
Here's what the HTML tab outputs:

![html](https://cloud.githubusercontent.com/assets/11541037/11128301/f68cd59a-8946-11e5-8c1c-a226512fa504.PNG)

and the response tab just shows the HTML code for what is displayed in the HTML tab.

To your other point about having action in one place and actions in another, I originally had them the same (and just changed them back) and I still received the error. They were different at the time of my original post, because that's how it was written in the example shown here: https://github.com/yajra/laravel-datatables/wiki/Examples

**Comment by Skintillion** [comment]
This is my addColumn modified for your purpose. Maybe try this?


```
->addColumn('action', function ($employees) {
	                return '<a href="'.route("employees/edit/".$employees->id).'" class="btn btn-xs btn-success"><i class="fa fa-eye"></i> View</a>';
	            })

```

**Comment by aleary06** [comment]
I just tried that and I'm still getting that 404 error. When I first set datatables up on my site, I briefly had a similar issue and it had to do with url rerouting in my web.config file. I rewrote it as

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<system.webServer>
<rewrite>
  <rules>
    <rule name="Imported Rule 1" stopProcessing="true">
      <match url="^(.*)/$" ignoreCase="false" />
      <conditions>
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
      </conditions>
      <action type="Redirect" redirectType="Permanent" url="public/{R:1}" />
    </rule>
    <rule name="Imported Rule 2" stopProcessing="true">
      <match url="^" ignoreCase="false" />
      <conditions>
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
      </conditions>
      <action type="Rewrite" url="index.php" />
    </rule>
  </rules>
</rewrite> 
</system.webServer>
</configuration>
```

For Apache webservers, I believe that would be similar to having this in the htaccess file:

```xml
<IfModule mod_rewrite.c>
RewriteEngine On

#REWRITE RULES
#---------------------

#RULE IMPORTED RULE 1 
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)/$ public/$1 [r=301,L]

#RULE IMPORTED RULE 2 
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]

</IfModule>
```

I don't know how familiar you are with these configurations, but is it possible that I need to edit or add a rule here?

**Comment by Skintillion** [comment]
I avoided all of that by using Homestead, sorry I cannot be of more help. I could teamviewer if you want and take a better look?

**Comment by yajra** [comment]
@aleary06, I think there is some error on your route and on your convention? `show` method are used to display a specific single resource like `route('employees.show', $id)`. 

Anyways, please check `routes.php` and make sure that you have registered your routes properly. I suggest you also try this approach.

```php
public function index(Request $request)
{
	if ($request->ajax()) {
	    $employees = Employee::select('id', 'last_name', 'first_name', 'position', 'department', 'email', 'ext', 'start_date');

	    return Datatables::of($employees)
	        ->addColumn('action', '<a href="{{ route(\'employees.edit\')}}" data-target="#myModal" role="button" class="btn btn-success" data-toggle="modal">Edit</a>')
	        ->make(true);	
	}

	return view('master')
}
``` 
```js
<script>
    $(document).ready(function() {
        $('#employees-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '',
            columns: [
                { data: 'id', name: 'id' },
                { data: 'first_name', name: 'first_name' },
                { data: 'last_name', name: 'last_name' },
                { data: 'position', name: 'position' },
                { data: 'department', name: 'department' },
                { data: 'email', name: 'email' },
                { data: 'ext', name: 'ext'},
                { data: 'start_date', name: 'start_date'},
                { data: 'actions', name: 'actions'}
            ]
        });
    });
```

**Comment by aleary06** [comment]
Hi yajra, thanks for your response. In my routes I have `Route::resource('employees', 'EmployeesController');` which generates the following routes:

Method | URI | Name | Action
--------- | ----- | ------- | ---------
POST | employees | employees.store | App\Http\Controllers\EmployeesController@store
GET/HEAD | employees | employees.index | App\Http\Controllers\EmployeesControler@index
GET/HEAD |employees/create | employees.create |App\Http\Controllers\EmployeesController@create
DELETE | employees/{employees} | employees.destroy | App\Http\Controllers\EmployeesController@delete
PATCH | employees/{employees} | | App\Http\Controllers\EmployeesController@update
GET/HEAD | employees/{employees} | employees.show | App\Http\Controllers\EmployeesController@show
PUT | employees/{employees} | employees.update | App\Http\Controllers\EmployeesController@update
GET/HEAD | employees/{employees}/edit | employees.edit | App\Http\Controllers\EmployeesController@edit

To your other suggestions, I like your implementation better. I moved the Datatables controller code to the index function and wrapped it in the `if ($request->ajax())` statement. I then removed the route from the ajax listing in the script (`ajax: '',`). Unfortunately, I'm still getting the 404 error. Is there in issue in my routes that you can see? As I mentioned above these were autogenerated by Laravel using `Route::Resource`.

Thanks for your help!

**Comment by Skintillion** [comment]
I wish I could take a closer look at this, it's difficult for me without seeing everything in front of me =(

**Comment by aleary06** [comment]
Hey @Skintillion thanks for all of your help. I appreciate you to take as much time as you did. If you'd like I could upload a zip of the files I'm working with for this.

**Comment by yajra** [comment]
@aleary06, were you able to update your ajax route?
From:
```js
ajax: '{{ route("employees.show") }}',
``` 

To:
```js
ajax: '{{ route("employees.index") }}',
// or simply use
ajax: '',
```

**Comment by aleary06** [comment]
Hi @yajra, I did try both, (```ajax: '{{route("employees.index") }}',``` and ```ajax: '',```), unfortunately, neither of those implementations resolved the issue.

**Comment by aleary06** [comment]
So, I have something of an update. On another Laravel site I'm working on, I added a datatable and then used ```->addColumn('actions', '<a href=\'#\'>Edit</a>')``` to my controller and it worked perfectly. So oddly enough, I have two sites that appear to have the same implementation, and it works on one, but not for the other. One odd thing that I've noticed though, is that on the site where I'm having the issue, if I try navigating to ```http://mysite.com/Laravel_Site/public/employees``` (where the datatable that's causing me trouble is located), the url is rewritten as ```http://mysite.com/Laravel_Site/public/public/employees``` -- an extra '/public' gets added in there. Then I have to delete out the second '/public' (because the page obviously won't render with it in there...that's not a real url), and the page loads at which point I get the 404 error on the ajax call. My thinking now is that this is definitely a routing issue. I had previously been using ```Route::resource('employees', 'EmployeesController');``` to auto-generate my routes, but now I'm going to rewrite them individually myself and see if I can get better results. I'll post an update if that ends up working for me.

**Comment by aleary06** [comment]
Ok, so I've got my datatable working with the added column, but my solution is more of a temporary one so I'd love to get your feedback. Since my last post, I've rewritten all of my routes and that did not fix the issue. I then tried implementing the additional column on another datatable (on a different page within the same site) and it did work. These two tables are nearly identical. The only difference between them is the table that throws the error has columns for 'id' and 'start_date' while the table where the addColumn worked does not. So to recap so far:

On the table that worked:

Controller (FrontEnd.php):

```php
public function Index(Request $request)
{
    if ($request->ajax())
    {
           $employees = Employee::select('id', 'first_name', 'last_name', 'position', 'department', 'email', 'ext', 'start_date');
            return Datatables::of($employees)
                ->addColumn('actions', 'Edit')
                ->make(true);
    }
    return view('home', array('title' => 'Intranet', 'description' => '', 'page' => 'home'));
}
```
In the views:

master.blade.php:

```javascript

....

$(document).ready(function() {
    var table = $('#employees-table').DataTable( {
            processing: true,
            serverSide: true,
            ajax: '',
            columns: [
            {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": ''
            },
            { data: 'first_name', name: 'first_name' },
            { data: 'last_name', name: 'last_name' },
            { data: 'position', name: 'position' },
            { data: 'department', name: 'department' },
            { data: 'email', name: 'email' },
            { data: 'ext', name: 'ext'}
        ],
        order: [[1, 'asc']]
    } );
});

...
```

and in home.blade.php

```html
...
<table class="table table-striped row-bordered" id="employees-table">
	<thead>
		<tr>
			<th>ID</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Position</th>
		        <th>Department</th>
			<th>Email</th>
			<th>Ext.</th>
			<th></th>
		</tr>
	</thead>
								
	<tfoot>
		<tr>
		       <th>ID</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Position</th>
			<th>Department</th>
			<th>Email</th>
			<th>Ext.</th>
			<th></th>
		</tr>
	</tfoot>
</table>
...
```

Then in the table that didn't work, my controller code was identical and the only differences were in my blades:

master_admin.blade.php:
```javascript
$(document).ready(function() {
    var table = $('#employees-table').DataTable( {
        processing: true,
        serverSide: true,
        ajax: '{{ route("employees.index") }}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'first_name', name: 'first_name' },
            { data: 'last_name', name: 'last_name' },
            { data: 'position', name: 'position' },
            { data: 'department', name: 'department' },
            { data: 'email', name: 'email' },
            { data: 'ext', name: 'ext'},
            { data: 'start_date', name: 'start_date' },            
            { data: 'actions', name: 'actions'}
        ],
        order: [[1, 'asc']]
    } );
});
```
Then my admin.blade.php file had the corresponding table headers.

Given that the only difference between the two tables was the inclusion of the 'id' and 'start_date' columns in the table that wasn't working, I removed those two columns and everything started to work. I then added the 'id' column back in and it still worked.

However, when I add the 'start_date' column back in, I get the 404 message again. In my MySQL database, start_date is of type DATE. @yajra, are you aware of any bugs caused by dates in your package or perhaps in the original Datatables package? I'm not sure that that's what caused this because my datatable has no issue with the start_date when the additional column isn't present. At any rate, this is a weird issue that's sort of fixed, but not really since I'd eventually like to include the start_date column back into my table. Do you have any thoughts on what could be causing this?

For this sake of keeping the discussion open, I'm not closing this ticket just yet. However since the issue is technically resolved for right now, if I don't hear back soon I'll go ahead and close it out anyway. 

Thank you very much @yajra and @Skintillion for continuously replying back and staying active in this thread for the last few days. I really appreciate it.

**Comment by Skintillion** [comment]
No problem I wish I could have been more helpful =)

On Mon, Nov 16, 2015 at 11:08 AM, aleary06 <notifications@github.com> wrote:

> Ok, so I've got my datatable working with the added column, but my
> solution is more of a temporary one so I'd love to get your feedback. Since
> my last post, I've rewritten all of my routes and that did not fix the
> issue. I then tried implementing the additional column on another datatable
> (on a different page within the same site) and it did work. These two
> tables are nearly identical. The only difference between them is the table
> that throws the error has columns for 'id' and 'start_date' while the table
> where the addColumn worked does not. So to recap so far:
>
> On the table that worked:
>
> Controller (FrontEnd.php):
>
> public function Index(Request $request){    if ($request->ajax())    {           $employees = Employee::select('id', 'first_name', 'last_name', 'position', 'department', 'email', 'ext', 'start_date');            return Datatables::of($employees)                ->addColumn('actions', 'Edit')                ->make(true);    }    return view('home', array('title' => 'Intranet', 'description' => '', 'page' => 'home'));}
>
> In the views:
>
> master.blade.php:
>
> ....
>
> $(document).ready(function() {
>     var table = $('#employees-table').DataTable( {
>             processing: true,
>             serverSide: true,
>             ajax: '',
>             columns: [
>             {
>                 "className":      'details-control',
>                 "orderable":      false,
>                 "data":           null,
>                 "defaultContent": ''
>             },
>             { data: 'first_name', name: 'first_name' },
>             { data: 'last_name', name: 'last_name' },
>             { data: 'position', name: 'position' },
>             { data: 'department', name: 'department' },
>             { data: 'email', name: 'email' },
>             { data: 'ext', name: 'ext'}
>         ],
>         order: [[1, 'asc']]
>     } );
> });
>
> ...
>
> and in home.blade.php
>
> ...
> <table class="table table-striped row-bordered" id="employees-table">
>     <thead>
>         <tr>
>             <th>ID</th>
>             <th>First Name</th>
>             <th>Last Name</th>
>             <th>Position</th>
>                 <th>Department</th>
>             <th>Email</th>
>             <th>Ext.</th>
>             <th></th>
>         </tr>
>     </thead>
>
>     <tfoot>
>         <tr>
>                <th>ID</th>
>             <th>First Name</th>
>             <th>Last Name</th>
>             <th>Position</th>
>             <th>Department</th>
>             <th>Email</th>
>             <th>Ext.</th>
>             <th></th>
>         </tr>
>     </tfoot>
> </table>
> ...
>
> Then in the table that didn't work, my controller code was identical and
> the only differences were in my blades:
>
> master_admin.blade.php:
>
> $(document).ready(function() {
>     var table = $('#employees-table').DataTable( {
>         processing: true,
>         serverSide: true,
>         ajax: '{{ route("employees.index") }}',
>         columns: [
>             { data: 'id', name: 'id' },
>             { data: 'first_name', name: 'first_name' },
>             { data: 'last_name', name: 'last_name' },
>             { data: 'position', name: 'position' },
>             { data: 'department', name: 'department' },
>             { data: 'email', name: 'email' },
>             { data: 'ext', name: 'ext'},
>             { data: 'start_date', name: 'start_date' },
>             { data: 'actions', name: 'actions'}
>         ],
>         order: [[1, 'asc']]
>     } );
> });
>
> Then my admin.blade.php file had the corresponding table headers.
>
> Given that the only difference between the two tables was the inclusion of
> the 'id' and 'start_date' columns in the table that wasn't working, I
> removed those two columns and everything started to work. I then added the
> 'id' column back in and it still worked.
>
> However, when I add the 'start_date' column back in, I get the 404 message
> again. In my MySQL database, start_date is of type DATE. @yajra
> <https://github.com/yajra>, are you aware of any bugs caused by dates in
> your package or perhaps in the original Datatables package? I'm not sure
> that that's what caused this because my datatable has no issue with the
> start_date when the additional column isn't present. At any rate, this is a
> weird issue that's sort of fixed, but not really since I'd eventually like
> to include the start_date column back into my table. Do you have any
> thoughts on what could be causing this?
>
> For this sake of keeping the discussion open, I'm not closing this ticket
> just yet. However since the issue is technically resolved for right now, if
> I don't hear back soon I'll go ahead and close it out anyway.
>
> Thank you very much @yajra <https://github.com/yajra> and @Skintillion
> <https://github.com/Skintillion> for continuously replying back and
> staying active in this thread for the last few days. I really appreciate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yajra/laravel-datatables/issues/251#issuecomment-157138342>
> .
>



-- 
Jeremy Jackson

**Comment by yajra** [comment]
@aleary06, did you declare `start_date` on your model on `protected $dates`? If yes, then the package might have return a `Carbon` object instead of a `string`. Please inspect the json response on dev tools.

Also, make sure that the actions column is set to `orderable: false, searchable: false` to avoid SQL errors.

**Comment by yajra** [comment]
404 error is a Laravel routing issue and not on the package. Thanks!
