### ISSUE TITLE
Word-wrap issue in cell in excel file after export from laravel datatables.

### ISSUE THREAD

**Issue by brijesh1997** [yajra/laravel-datatables#2510]
Hello @yajra ,

I have query in my code, I want to export Laravel data-table same as table view. Means I can't export data-table with word-wrap text. Please visit below screenshot so you can sure about it.

Screenshot 1: This one is the view of my laravel data-table. That I need same as during export in excel file.
1. https://prnt.sc/vgji9s

Screenshot 2: This one is my current view of excel file.
1. https://prnt.sc/vgj83k
2. https://prnt.sc/vgj8nn

Please check it and give me a suggestion for it. Thanks in advance.

**Comment by yajra** [comment]
You can override the default excel export class to fine tune your export. Just set the export class to your custom one.

```php
// DataTable class
protected $exportClass = ExcelExport::class;

// export class
use Yajra\DataTables\Services\DataTablesExportHandler;

class ExcelExport extends DataTablesExportHandler
{
  // see laravel-excel docs
}
```

**Comment by brijesh1997** [comment]
Thank you for give me suggestion. Let me check it and I'll message you.

**Comment by brijesh1997** [comment]
Hello @yajra, 

I visit my whole code but I didn't find this code please help me what can I do in this situation?

**Comment by yajra** [comment]
What version are you using? The code I suggested is from the latest version.

**Comment by brijesh1997** [comment]
https://prnt.sc/vgol5g

**Comment by brijesh1997** [comment]
Hello @yajra , 

     Please check it. I'm using above version and please give me a solution.

**Comment by brijesh1997** [comment]
Hello @yajra, Please give me a soluion.
