### ISSUE TITLE
Multiple datatable in one page view given the same data

### ISSUE THREAD

**Issue by RayhanYulanda** [yajra/laravel-datatables#2511]
### Summary of problem or feature request

I have tried to put 2 datatable in one page as your suggested https://github.com/yajra/laravel-datatables/issues/2489#issuecomment-722136617. But when i see the table of $pangkat it gives the same result as $dataTable, just different in header of column. It should give different data cause i take it from different model

### Code snippet of problem

FrontendPensiunDataTable
```
public function query(Pensiun $model)
    {
        $myModel = Pensiun::query()->orderBy('id', 'DESC');
        return $this->applyScopes($myModel);
    }
```
FrontendPangkatDataTable
```
public function query(JenisKenaikanPangkat $model)
    {
        return $model->newQuery();
    }
```

FrontendPangkatDataTableHtml
```
public function handle()
    {
        return $this
                    ->setTableId('pangkatdatatable')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->dom('frtip')
                    ->orderBy(1);
    }
```

Controller
```
public function frontend(FrontendPensiunDatatable $datatable){
        $pangkat = FrontendPangkatDataTableHtml::make();

        return $datatable->render('frontend.welcome', compact('pangkat'));
}
```
View
```
{!! $dataTable->table(['width' => '100%', 'id'=>'pensiundatatable']) !!}
{!! $pangkat->table(['width' => '100%', 'id'=>'pangkatdatatable']) !!}

{!! $dataTable->scripts() !!}
{!! $pangkat->scripts() !!}
```

### System details

- Operating System : windows 10
- PHP Version : PHP 7.3.10
- Laravel Version : 6.2
- Laravel-Datatables Version :
- "yajra/laravel-datatables": "1.5",
- "yajra/laravel-datatables-buttons": "~4.6",
- "yajra/laravel-datatables-oracle": "~9.0"

**Comment by RayhanYulanda** [comment]
Please at least give the example for show 2 table one view with datatable service in documentation @yajra

**Comment by RayhanYulanda** [comment]
Have you tried insert 2 table in one view successfully? If yes can you help me or give me your example code? @andrecuellar

**Comment by lk77** [comment]
Hello,

it should work, what error do you have.

we have multiple datatables on same blade view and it works  fine.

**Comment by RayhanYulanda** [comment]
Thank you for helping me but i got another error 
`DataTables warning: table id=pensiundatatable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`

**Comment by lk77** [comment]
What do you have in the response body of the ajax request ?

**Comment by RayhanYulanda** [comment]
Thanks a lot!
I've solved it, the problem is i called `->minifiedAjax()` after call my ajax to send data table. After i removed it, it works!

Thank you for your support, i got insipired by you for solve my problem @lk77

**Comment by lk77** [comment]
no problem, good to know you solved your issue
