### ISSUE TITLE
Object attributes is casted to string

### ISSUE THREAD

**Issue by Zzombiee2361** [yajra/laravel-datatables#2515]
### Summary of problem

I have a `tinyint` column which I cast into [Enum](https://github.com/BenSampo/laravel-enum). But this column is then casted into string by `DataTables`. After some digging into the source code, this is what caused the issue (specifically line 198-199):

https://github.com/yajra/laravel-datatables/blob/7e45885588225b31a9e7bdf4b04733c44432531c/src/Utilities/Helper.php#L186-L207

Since this only affect objects, the workaround is converting/casting into associative array:  
```php
->editColumn('status', function(News $news) {
    return (array) $news->status;
})
```

IMO objects shouldn't just casted into string, since associative array which practically the same for the client is not casted into string as well

**Comment by yajra** [comment]
Thanks for reporting. Maybe we can add a check if the value is Arrayable? Would you be able to send a PR to fix this issue?

```php
if ($value instanceOf Arrayable) { 
  $row[$key] = $value->toArray();
}
```

**Comment by Zzombiee2361** [comment]
That could work, but what's wrong with sending a whole object?

**Comment by yajra** [comment]
Can't recall as that helper file is a bit old and rarely updated. But I think it has something todo with the serialization and returning an object causes an error. A stdClass maybe or something.

**Comment by Zzombiee2361** [comment]
Then what about just typecasting all object into array without checking for `Arrayable` since I might have standard object or `stdClass`. Much better than typecasting it into string of course

**Comment by yajra** [comment]
That might work too. But I think there are instances where object cannot be casted as array and raises an error.

**Comment by Zzombiee2361** [comment]
Really? Personally I've never experienced such thing, can you give me some example? Besides, why would anyone put such weird object as a model's attribute?

**Comment by yajra** [comment]
The package also works on collection and query builder and I think I encountered that error on either of the two. Can't recall how to replicate though.

**Comment by Zzombiee2361** [comment]
But this function doesn't convert directly from the query builder. This only converts each attribute of collection either directly given or the result of the query. So the problem shouldn't be from that.

Though I don't understand how could it could possibly throw an error. I looked at stackoverflow and php manual but I can't find anything about error caused by casting object to array. This could be a middle ground though:

```php
if (is_object($value)) {
	try {
		$row[$key] = (array) $value;
	} catch($err) {
		$row[$key] = (string) $value;
	}
} else { 
	$row[$key] = $value;
}
```

**Comment by Zzombiee2361** [comment]
Oh I found `Notice: Undefined index` but that happens if you try to cast an object with numeric properties and then try to access it using a string representation of the number. Mind you this only happens when accessing the array and not when casting to array itself. I can't find anything other than that.
