### ISSUE TITLE
escape url in Htmlbuilder with minifiedAjax

### ISSUE THREAD

**Issue by Momenoor** [yajra/laravel-datatables#2518]
### Summary of problem or feature request
when i use htmlbuilder with function minifiedAjax it shows url as escaped with \\/ slashs as showing below:

here is the result of $html->scripts();

$(function(){window.LaravelDataTables=window.LaravelDataTables||{};window.LaravelDataTables["dataTableBuilder"]=$("#dataTableBuilder").DataTable({"serverSide":true,"processing":true,"ajax":"**http:\\/\\/jpaemirates.mie\\/users**","columns":[{"name":"id","data":"id","title":"Id","orderable":true,"searchable":true},{"name":"first_name","data":"first_name","title":"First Name","orderable":true,"searchable":true},{"name":"email","data":"email","title":"Email","orderable":true,"searchable":true},{"name":"created_at","data":"created_at","title":"Created At","orderable":true,"searchable":true},{"name":"updated_at","data":"updated_at","title":"Updated At","orderable":true,"searchable":true}]});});

here is my controller code:

public function index(Builder $builder) {
        if (request()->ajax()) {
            return DataTables::of(User::all())->make(true);
        }
    
        $html = $builder->minifiedAjax()->columns([
                    ['data' => 'id', 'data'=>'id', 'title' => 'Id'],
                    ['data' => 'first_name', 'title' => 'First Name'],
                    ['data' => 'email', 'title' => 'Email'],
                    ['data' => 'created_at', 'title' => 'Created At'],
                    ['data' => 'updated_at', 'title' => 'Updated At'],
                ]);
    
        return view('tableList', compact('html'));
    }

here is blade template:

@extends('layouts.app')

@section('content')
    {!! $html->table() !!}
@endsection

@push('scripts')
    <script src="{{ asset('lib/datatables/jquery.dataTables.min.js')}}"></script>
    {!! $html->scripts() !!}
@endpush

**Comment by yajra** [comment]
Use raw columns, see https://yajrabox.com/docs/laravel-datatables/master/raw-columns.

**Comment by Momenoor** [comment]
The problem is when the service parsing Ajax url on builder script it's escaping the url its show like this http:\/\/ .....etc
Did you got my point?

**Comment by yajra** [comment]
Oic, didn't noticed you were referring to the actual URL :)

Maybe try specifying the url? 

```php
$builder->minifiedAjax(route('route-name'))
```
