### ISSUE TITLE
Any way to Cache database query?

### ISSUE THREAD

**Issue by IftekherSunny** [yajra/laravel-datatables#252]
@yajra brother can I cache database query?

**Comment by yajra** [comment]
@IftekherSunny, there is a recent PR that attempts to cache the query but it's not yet complete as there will be some errors that may raise when caching the query. See this PR #230 for ref. 

A workaround that you can do is to manually cache the whole query using collection. But be aware that this may cause some performance issues when your DB becomes large.

```php
$users = Cache::remember('users', $minutes, function() {
    return DB::table('users')->get();
});

return Datatables::of($users)->make(true);
```

**Comment by IftekherSunny** [comment]
@yajra thanks for your reply. I checked it. It's not work as I need. Brother any performance issue occur if I'll query large size of data (1000 thousands record) from database without Cache using your package? Give me some advice to improve performance of the database query.

**Comment by bishwajitcadhikary** [comment]
> @IftekherSunny, there is a recent PR that attempts to cache the query but it's not yet complete as there will be some errors that may raise when caching the query. See this PR #230 for ref.
> 
> A workaround that you can do is to manually cache the whole query using collection. But be aware that this may cause some performance issues when your DB becomes large.
> 
> ```
> $users = Cache::remember('users', $minutes, function() {
>     return DB::table('users')->get();
> });
> 
> return Datatables::of($users)->make(true);
> ```

Serialization of 'PDO' is not allowed
