### ISSUE TITLE
Sorting behaviour

### ISSUE THREAD

**Issue by i6media** [yajra/laravel-datatables#2523]
I have a Collection, which contains a name and a value:

<img width="319" alt="Schermafbeelding 2020-11-18 om 12 47 38" src="https://user-images.githubusercontent.com/14023039/99527212-bbf58980-299c-11eb-85ae-f16aab8131b3.png">

My method returns the following:

`return DataTables::of($collection)->toJson();`

On the frontend the DataTables object uses `"serverSide": true`

When I sort on name, the digits 3 and 4 are sorted before 1:

<img width="338" alt="Schermafbeelding 2020-11-18 om 12 46 16" src="https://user-images.githubusercontent.com/14023039/99527366-f9f2ad80-299c-11eb-8774-e0e11a928419.png">

What can cause this behaviour?

**Comment by Proudje** [comment]
Same problem here
