### ISSUE TITLE
On page load draw datatable rows without Ajax request (without deferLoading)

### ISSUE THREAD

**Issue by juliancc** [yajra/laravel-datatables#2528]
### Summary of problem or feature request

I can't seem to find a way to render the first page of record without an Ajax request.
If I turn off `->deferLoading(false)` it basically just gives me a blank table.

I want to be able to load the first records on page load so that the app seems faster than having the user wait on the first Ajax request to finish. 
Is there a way to do this?

**Comment by yajra** [comment]
Not sure but this may not be supported on serverSide? Is there any official demo on datatables.net that shows this feature? Will try to give it a shot if a demo is available. Thanks!

**Comment by juliancc** [comment]
https://datatables.net/examples/server_side/defer_loading.html

**Comment by yajra** [comment]
I see, based on the demo, the initial data is already loaded and I think you cannot use the html builder here. This is how I would handle this I guess (code below not tested).

```php
// controller
public function index(UsersDT $dt) {
  // get the first page of users manually
  $users = User::query()->take(10)->get();

  return $dt->render('users.index', compact('users'));
}

// view
<table id="users-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{ $user->id }}</td>
            <td>{{ $user->name }}</td>
        </tr>
        @endforeach
    </tbody>
</table>


@push('scripts')
{{ $dataTable->scripts() }}
@endpush
```

Note: just make sure to use `->setTableId('users-table')` on your HTML Builder so that the script would use the correct selector for table.

**Comment by juliancc** [comment]
Yeah that would work in a very simplify version. Assuming there is no custom filtering, ordering. 
Also defeats the purpose of setting of the DT with columns and stuff, because now you are hardcoding the initial table.

I guess I have to look into a way to get the columns and the first batch of records from the DT after the execution of filters and/or orders. Will see if I can come up with an elegant solution.
