### ISSUE TITLE
Multiple DataTable in one page Using Laravel Ajax Yajra

### ISSUE THREAD

**Issue by tanjiro-code** [yajra/laravel-datatables#2529]
Im new to DataTables and  trying to create 2 tables in one Page using DataTables Ajax unfortunately didnt work and have been looking over internet still cant find the answer. 

//Controller
public function index(Request $request)
    {
         if($request->ajax())
            {
                $data = allocate_budget::latest()->where('station',Auth::User()->station)->get();
                $datas = allocate_budget::latest() ->get();
                  return DataTables::of($data,$datas) ->make(true);
            }
            return view('user.create_ppmp');
 }
//route
Route::resource('/ppmp_156', 'station\PPMPController');

//HTML

###             <div class="table-responsive">
                            <table id="budget_table" class="table table-striped table-bordered style="width:100%">
                                <thead class="text-uppercase bg-primary">
                                    <tr class="text-white">
                                        <th>Budget Id</th>
                                        <th>Station</th>
                                        <th>Allocated Budget</th>
                                        <th>Total Used</th>
                                        <th>Balance</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                             </table>
                    
                            <table id="ppmp_table" class="table table-striped table-bordered style="width:100%">
                                <thead class="text-uppercase bg-primary">
                                    <tr class="text-white">
                                        <th>Particular Code</th>
                                        <th>Unified Code</th>
                                        <th>Particulars</th>
                                        <th>Item Description</th>
                                    </tr>
                                </thead>
                             </table>
                        </div>
                    </div>   
                       

//Javascript
$(document).ready(function(){
    // Budget table
    $('#budget_table').DataTable({
        dom: 'Bfrtip',
        pageLength: 7, 
        buttons: [
                'copy',
                    {
                        extend: 'excel'
                    }
                ],
        orderCellsTop: true, 
        processing: true,
        serverSide: false,
        ajax: {
        url: "{{ route('ppmp_156.index') }}",
        },
        columns: [
        {
            data: 'budget_id',
            name: 'budget_id'
        },
        {
            data: 'station',
            name: 'station'
        },
        {
            data: 'allocated_budget',
            name: 'allocated_budget'
        },
        {
            data: 'total_amount_used',
            name: 'total_amount_used'
        },
        {
            data: 'balance',
            name: 'balance'
        },
        {
            data: 'status',
            name: 'status'
        }
        ]
        });

    // PPMP Table
$('#ppmp_table').DataTable({
        dom: 'Bfrtip',
        pageLength: 3, 
        buttons: [
                'copy',
                    {
                        extend: 'excel'
                    }
                ],
        orderCellsTop: true, 
        processing: true,
        serverSide: false,
        ajax: {
        url: "{{ route('ppmp_156.index') }}",
        },
        columns: [
            {
            data: 'budget_id',
            name: 'budget_id'
        },
        {
            data: 'station',
            name: 'station'
        },
        {
            data: 'allocated_budget',
            name: 'allocated_budget'
        },
        {
            data: 'total_amount_used',
            name: 'total_amount_used'
        }
        ]
        });
 });

-->

**Comment by RayhanYulanda** [comment]
You can see this solution https://github.com/yajra/laravel-datatables/issues/2511#issuecomment-730459742
