### ISSUE TITLE
Invalid JSON response on AWS with a load balancer

### ISSUE THREAD

**Issue by cannycookie** [yajra/laravel-datatables#2532]
Hey Yajra,

Thank you so much for a really well written package.  It's awesome 👍  

I'm having this issue on on an ec2 instance, deployed from beanstalk. On local homestead it works fine.

Initially thought could be an issue with the web server running http and and load balancer having the certificate but it's not that -> just installed ssl on ngnix and same problem.

Maybe due to the route being guarded.  - have tried making the route public but still nothing

There's no other JS errors, DT initialises fine, but no data is loaded.
 
Have you any ideas?  There's nothing in any log file. I can't see anyway to capture the response.

The code is pretty much from your example.  If it was a guard issue it wouldn't work on my machine.

Is it worth trying to separate loading the view and the data?

```php
    public function index(AdminDatatables $datatables)
    {
        return $datatables->render('admin.users.manage_users');
    }

```

Many thanks for any advice.

- Laravel 8 / Nginx
- PHP 7.4
- Laravel-Datatables Latest

**Comment by cannycookie** [comment]
I've managed to solve this problem. Here's what I did in case anyone else has similar issue.

The HasData Trait includes jquery scripts prefixed with $,  our theme uses jQuery so that's a simple find and replace.  Then the bigger problem was caused by the minifiedAjax fn in that file creating an insecure URL.   After including `str_replace("http:",'https:',$url);` everyting  works beautifully.

Then had the issue that traits can't be extended like classes, so the easiest solution was to replace the vendor file using composer post-update-command. 

Like this in composer.json:-

```
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "cp vendor_overide/HasData.php vendor/yajra/laravel-datatables-html/src/Html/Options/HasData.php"
        ]
```
Other approach would be to extend the class that includes the trait.  Either way will still have to monitor future updates to ensure compatibility.

@yajra perhaps a solution to this would be to have a config option to force https and even better one for the jquery prefix.

Thanks anyway for a well written package. DT has always been fiddly but you've made it easy and super fast to build pages.  I created 10 datatables pages last night. That wasn't possible before.  Sending you a beer 🥇

**Comment by yajra** [comment]
@cannycookie can you provide your HasData solution? Maybe we can adapt it?

For the https, I think this is more of a Laravel configuration and can fixed by forcing SSL. Can't recall how but I definitely did something similar before.

For the jQuery part, are you referring to the part identifies if the value is a script? I think there is a config already for that under `datatables-html.php` config if you published it.

```php
'callback' => ['$', '$.', 'function'],
```

**Comment by cannycookie** [comment]
Hey Yajra, Thanks for the reply, no such config exists for me using:-

```
        "yajra/laravel-datatables": "^1.5",
        "yajra/laravel-datatables-oracle": "~9.0
```
All the scripts have $( hardcoded so perhaps those changes haven't been published yet?

I have force https as middleware:-
```
if (!$request->secure()) {
            return redirect()->secure($request->getRequestUri());
        }
```

in the app boot:-
```
\Illuminate\Support\Facades\URL::forceScheme('https');
```

But the generated form always comes out http on the aws stack.  

This is the updated minifiedAjax function.  Strangely this line: ` $url = url()->secure($url);` Still didn't generate an https url but. `$url  = str_replace("http:",'https:',$url);` forcibly does.



```
  public function minifiedAjax($url = '', $script = null, $data = [], $ajaxParameters = [])
    {
        $this->ajax = [];
        $appendData = $this->makeDataScript($data);
        $url = empty($url) ? url()->full() : $url;
        $this->ajax['url'] = str_replace("http:",'https:',$url);
        $this->ajax['type'] = 'GET';
        if (isset($this->attributes['serverSide']) ? $this->attributes['serverSide'] : true) {
            $this->ajax['data'] = 'function(data) {
            for (var i = 0, len = data.columns.length; i < len; i++) {
                if (!data.columns[i].search.value) delete data.columns[i].search;
                if (data.columns[i].searchable === true) delete data.columns[i].searchable;
                if (data.columns[i].orderable === true) delete data.columns[i].orderable;
                if (data.columns[i].data === data.columns[i].name) delete data.columns[i].name;
            }
            delete data.search.regex;';
        } else {
            $this->ajax['data'] = 'function(data){';
        }
        
        if ($appendData) {
            $this->ajax['data'] .= $appendData;
        }
        
        if ($script) {
            $this->ajax['data'] .= $script;
        }
        
        $this->ajax['data'] .= '}';
        
        $this->ajax = array_merge($this->ajax, $ajaxParameters);
        
        return $this;
    }
```

Also tried this which didn't work either
```
  /**
     * Get ajax url.
     *
     * @return array|mixed|string
     */
    public function getAjaxUrl()
    {
        if (is_array($this->ajax)) {
            return url()->secure(($this->ajax['url'] ?: url()->current()));
        }
        
        return url()->secure(($this->ajax ?: url()->secure(url()->current())));
    }
    ```

Finally replaced the $ with jQuery here:-
```
    public function ajaxWithForm($url, $formSelector)
    {
        $script = <<<CDATA
var formData = jQuery("{$formSelector}").find("input, select").serializeArray();
jQuery.each(formData, function(i, obj){
    data[obj.name] = obj.value;
});
CDATA;
        
        return $this->minifiedAjax($url, $script);
    }
```

and here
```
    public function pipeline($url, $pages)
    {
        $this->ajax = "jQuery.fn.dataTable.pipeline({ url: '{$url}', pages: {$pages} })";
        
        return $this;
    }
```

**Comment by jaiivarsson** [comment]
+1 for this issue too.

In my instance I have the app running on AWS Fargate behind a load balancer that terminates the https request and forwards to the ECS tasks as http. I have force HTTPS set in the `AppServiceProvider` which works for everything else. Unfortunately the generated javascript in the `{!! $dataTable->scripts() !!}` line in the blade template sets the url as http as noted above.

**Comment by yajra** [comment]
Haven't tried working with AWS + Load Balancer so I may not be able to fix this accurately. Accepting PR if anyone is interested in patching this.

@cannycookie I think we can consider the configuration for jQuery prefix and the force SSL. Will try to check this one when I got the chance. Thanks!

**Comment by snappermorgan** [comment]
I came here with the same problem about the http problem. I have since learned that this isn't a code issue but a Laravel configuration issue if you are running it on AWS Elasticbeanstalk with a load balancer. It specifically talks about the issue of the url() function not being able to return a correct scheme. This link will tell you what you need to do to fix this. 

https://laravel.com/docs/8.x/requests#configuring-trusted-proxies

**Comment by yajra** [comment]
@snappermorgan is correct and have personally experienced this yesterday. Trusting all proxies fixes the same issue for me.

https://laravel.com/docs/8.x/requests#trusting-all-proxies
