### ISSUE TITLE
PHP 8 error with eager loading

### ISSUE THREAD

**Issue by jwensley2** [yajra/laravel-datatables#2534]
### Summary of problem or feature request
When running on PHP 8 there is an error that occurs when using eager loading.

```
method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given {"userId":1,"exception":"[object] (TypeError(code: 0): method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given at /vendor/yajra/laravel-datatables-oracle/src/Utilities/Helper.php:160)
```

### Code snippet of problem

```php
$model = \App\Models\User::with([
    'role',
]);
return \DataTables::eloquent($model)
    ->addColumn('role', function (\App\Models\User $user) {
        return $user->role ? $user->role->name : 'N/A';
    })
    ->toJson();
```

```php
class User extends Authenticatable
{
    use SoftDeletes;
    use Notifiable;
    
    public function role()
    {
        return $this->belongsTo(Role::class);
    }
}
```

### System details

- Operating System: Ubuntu 18.04
- PHP Version: 8.0 RC3
- Laravel Version: 8.16.1
- Laravel-Datatables Version: 9.14.1

**Comment by yajra** [comment]
There seems seems to be changes on method_exists function on PHP 8 that causes this issue. Will try check this but can't upgrade to PHP 8 yet. If you can, please do not hesitate to submit a PR for PHP 8 support. Thanks!

**Comment by RayhanYulanda** [comment]
+1 I have the same issue
