### ISSUE TITLE
Search on eloquent with nullable relation.

### ISSUE THREAD

**Issue by tcagkansokmen** [yajra/laravel-datatables#2548]
I'm using server-side rendering, and trying to search between columns.

I got relation like below,

Post::with(['address']);
Post can have an address, but also It may not have any address too.

So that, my logic fails on there;

I'm using column like

{ data: 'address.name', name:'address.name'  }

so that, if there's no data inside "address relation" datatable return error, because it says "requested unknown parameter 'address.name'" because name field is undefined.

What could be the solve?

**Comment by RayhanYulanda** [comment]
+1 Have same issue

**Comment by yajra** [comment]
Since it's nullable, you should add a `withDefault()` on your relation.

```php
class Post extends Model
{
  public function address() {
    return $this->belongsTo(Address::class)->withDefault();
  }
}
```
