### ISSUE TITLE
Case Error

### ISSUE THREAD

**Issue by cfreak** [yajra/laravel-datatables#255]
There is a Problem on my mac in this Line:
$datatables          = app('datatables');

When i set it to
$datatables          = app('Datatables');

Everything is working correct.

**Comment by yajra** [comment]
Works fine for me. Were you able to register the package service provider? `yajra\Datatables\DatatablesServiceProvider::class`

```php
return app('datatables')->of(User::all())->make();
```

**Comment by yajra** [comment]
BTW, it works on `$datatables = app('Datatables');` because it will resolve againts facade class. You need to register the provider to bind `datatables` in IoC hence should make `$datatables = app('datatables');` works correctly.

**Comment by yajra** [comment]
Registering the provider should fix the issue.
