### ISSUE TITLE
How to Export XLSX with Cell Formatting as Text

### ISSUE THREAD

**Issue by aslanonline** [yajra/laravel-datatables#2551]
Hello,

i'm using Laravel 8 with the lastest version of Yajra Datatables and Buttons.
Currently I have a problem with Excel Export. All of my Numeric Columns are formatted as Numbers in Excel, so mobilenumbers starting with 4917417 replaced with 4,91787E+11. 

How can I format the whole export sheet as Text, without manually set in Office Excel.

Thank you.

**Comment by yajra** [comment]
Just to confirm, you are using excel and not csv button? I mostly encounter this behavior when you export using CSV and then opening it on MS Excel.
