### ISSUE TITLE
Is there any compability with MongoDB and Elasticsearch?

### ISSUE THREAD

**Issue by tcagkansokmen** [yajra/laravel-datatables#2555]
I'm planning to move my mysql to mognodb or elasticsearch.

But If I do this, does laravel-datatable support?
That's so important point for me

**Comment by yajra** [comment]
Unfortunately, Mongodb is not officially supported but I think there are some solved issues related to this. Elasticsearch is also not supported and the package only currently works on collection. I once tried to support [laravel-scout](https://github.com/yajra/laravel-datatables-scout) but don't have enough time and no actual projects yet to work with it.
