### ISSUE TITLE
How can I show second Attribute on next line in Yajra Laravel server side

### ISSUE THREAD

**Issue by Muhammad-uzair029** [yajra/laravel-datatables#2556]
In below I add the attribute but how can I show separated rows. 
 ->addColumn('Student_info', function(Student $student){
      return $student->phone_no .$student->name.$student->name;
})

 Thanks in advance

**Comment by yajra** [comment]
Next line means new line right?

```php
->addColumn('Student_info', function(Student $student){
  return $student->phone_no . '<br/>'. $student->name.$student->name;
})
->rawColumns(['Student_info])
```
