### ISSUE TITLE
Datatable not displaying data laravel 8/ BS 5

### ISSUE THREAD

**Issue by jcc5018** [yajra/laravel-datatables#2558]
### Summary of problem 

I have followed the various vague tutorials online, trying to implement it with my project, but I'm having difficulty getting this to work. 

I'm using laravel 8, bootstrap 5 beta

Part of the problem may be I dont completely understand what goes in the JS Code. 
Namely 
**var table = $('.hobbies').DataTable({**

I think the .hobbies is a class name that goes in 

`<table class="table table-bordered hobbies"> `
right?

 columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'hobbyName', name: 'hobbyName'},

I'm assuming **data:** is value from the database?
is **name** the column name or something else? 

I will also need to figure out how to include related table data, 

All I get is this... 
![image](https://user-images.githubusercontent.com/21000134/103157808-a3874480-477c-11eb-82ac-4d4363f49b68.png)

...but Im aiming for this I haven't tried adding the additional columns yet since i cant even get the basic data:

![image](https://user-images.githubusercontent.com/21000134/103157825-c6b1f400-477c-11eb-80e6-3cd81dd3b91e.png)

Thanks

### Code snippet of problem

Referencing hobbies table

hobby_manager.blade.php
```

<x-admin-master>
    @section('Title')
    Hobby Manager
    @endsection
    @section('header1')
    Hobby Manager
    @endsection
    @section('content')



    <div class="container mt-5">

        <table class="table table-bordered hobbies">
            <thead>
                <tr>
                     <th>ID</th>
                    <th>Hobby Name</th>
                    <th>Status</th>
                    {{-- <th>Categories</th>
                    <th>Types</th>
                    <th>Date Updated</th> --}}
                    <th>Likes</th>
                    {{-- <th>Equipment</th>
                    <th>View Demographics</th> --}}
                    <th>Action</th>

                
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    @endsection

    @section('script')

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
   


    <script type="text/javascript">
        $(function () {
    
    var table = $('.hobbies').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{!!route('admin.get.hobbies') !!}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'hobbyName', name: 'hobbyName'},
           
            {data: 'status', name: 'status'},
            //  {data: 'categories', name: 'categories'},
            //  {data: 'types', name: 'types'},
            //   
            //  {data: 'updated_at', name: 'updated_at'},
            // {data: 'equipment', name: 'equipment'},
            {data: 'like_count', name: 'like_count'},
            
            
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },
        ]
    });
    
  });
    </script>
    @endsection



</x-admin-master>

```
**HobbyController**
```

namespace App\Http\Controllers\Admin\Content;
use App\Models\Tag;
use App\Models\Hobby;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

use App\Http\Controllers\Controller;

class HobbyController extends Controller
{
public function index()
    {
 return view('admin.content.hobby_manager');
  
        // $hobbies = Hobby::all();
    //  $categories=Tag::whereTag_type('80')->get();

    //     return view('admin.content.hobby_manager', [
    //          'hobbies' => $hobbies,
    //          'categories' => $categories]);
    }


Public function get_hobbies(Request $request)
{
        if ($request->ajax()) {
            $data  = Hobby::latest()->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){
                    $actionBtn = '<a href="javascript:void(0)" class="edit btn btn-success btn-sm">Edit</a> <a href="javascript:void(0)" class="delete btn btn-danger btn-sm">Delete</a>';
                    return $actionBtn;
                })
               
                ->make(true);
                }}


```

Template Stylesheets and JS

```  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/fontawesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" />`
 <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="{{ asset('css/mystyles.css') }}" rel="stylesheet" type="text/css">

    <!-- Footer -->
 @include('layouts.footer')

    <!-- Bootstrap core JavaScript -->
    @yield('script')
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
     {{-- Bootstrap 4 --}}
    <script src="{{asset('vendor/jquery/jquery.min.js')}}">

    </script>

   
    <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
</body>
```
**Routes**

```
Route::middleware('auth')->group(function () {
    Route::group(['prefix' => '/admin', 'as' => 'admin.'], function () {
 Route::get('/content/hobbies', 'Admin\Content\HobbyController@index')->name('content.hobbies');
Route::get('/content/hobbies/list', 'Admin\Content\HobbyController@get_hobbies')->name('get.hobbies');
}}
```
### System details

- PHP Version: PHP version: 7.4.5
- Laravel Version :8
- "yajra/laravel-datatables-oracle": "^9.0"

**Comment by dyaskur** [comment]
try to check your javascript console error message ,

btw you should use {{route('admin.get.hobbies')}} instead of {!!route('admin.get.hobbies') !!}

**Comment by mattbylett** [comment]
I think I'm having a similar problem here ... I keep getting the general error http://datatables.com/tn/7

So I've Checked the console and the ajax error is 500 when I check the stack trace I get : 
`{message: "Invalid argument supplied for foreach()", exception: "ErrorException",…}
class: "Illuminate\Support\Facades\Facade"
file: "/Applications/MAMP/htdocs/Sites/padis2021/app/Http/Controllers/Admin/ProductController.php"
function: "__callStatic"
line: 51
type: "::"
`
This is my Product Controller:
`public function index(Request $request) {
    if ($request->ajax()) {
        $data = Product::all();
        return DataTables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function ($row) {
            return "<a href='/products/edit/{$row->id}' class='btn btn-primary btn-sm'> Edit </a>
            <a href='/products/delete/{$row->id}' class='btn btn-danger btn-sm' id=\"delete\" data-id='{$row->id}'>Delete</a>";
            })
            ->rawColumns(['action'])
            ->toJson()
            ->make(true);
    }
    return view('admin.products.index');
}`

Line 51 is :   return DataTables::of($data)

This is the  Index Blade:
`@extends('layouts.dashboard')

@section('dashboard_styles')
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection

@section('dashboard_content')
<div class="container-fluid">
    <div class="row row-30">
        <div class="col-md-12">
                <h2>Products Table</h2>
            </div>
                <div class="table col-11 align-content-center">
                    <table class="table display responsive nowrap" id="productTable"  style="align:middle;">
                        <thead>
                            <th scope="col"></th>
                            <th scope="col">Product Code</th>
                            <th scope="col">Product Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Stock</th>
                            <th scope="col">Price</th>
                            <th scope="col">Slider</th>
                            <th scope="col">Action</th>
                        </thead>
                    </table>
                </div>
@endsection

@section('dashboard_scripts')

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function() {
            var table = $('#productTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{route('admin.products.index')}}",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'product_code', name: 'product_code'},
                    {data: 'product_name', name: 'product_name'},
                    {data: 'product_details', name: 'product_details'},
                    {data: 'product_quantity', name: 'product_quantity'},
                    {data: 'selling_price', name: 'selling_price'},
                    {data: 'main_slider', name: 'main_slider'},
                    {data: 'action', name: 'action'}
                ]
            });
        });
    </script>
@endsection
`
All of the data field match the database - I just can't see whats going wrong...

Any Guidance / suggestions would be very much appreciated

Matt
