### ISSUE TITLE
QueryEngine + adding SELECT table.* + ajax dt search = errors

### ISSUE THREAD

**Issue by namik-mesic** [yajra/laravel-datatables#256]
Dear Yajra,

I love your package, you are awesome.
I used to have my repositories run full queries on the database and then have them crunched by your CollectionEngine. I am now transitioning to building the query for the QueryEngine instead.

The initial datatables request does work (with no search filtering), but as soon as I start typing anything into the search field I get ajax errors on my server.

The query is being built with errors. I presume that the error is caused by me adding a select "select articles.*" within the query (which can't be filtered this way). This causes your internal filtering to try and do something funny like: (articles.* LIKE ...).

However, I would not like having to remove this addition from my query building mechanisms. Would this be solved by having the engine class(es) not consider * as a column and instead ignore it for filtering?

A sample dump error dump:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*) LIKE ? or LOWER(`quantity`) LIKE ? or LOWER(`articles`.*) LIKE ? or LOWER(`ar' at line 1 (SQL: select count(*) as aggregate from (select '1' as `row_count` from `articles` where `articles`.`type` = 2 and (LOWER(`id`) LIKE %a% or LOWER(`code_1`) LIKE %a% or LOWER(`name`) LIKE %a% or LOWER(`articles`.*) LIKE %a% or LOWER(`quantity`) LIKE %a% or LOWER(`articles`.*) LIKE %a% or LOWER(`articles`.*) LIKE %a% or LOWER(`articles`.*) LIKE %a% or LOWER(`articles`.*) LIKE %a%)) count_row_table)

If you need a helping hand in building cool stuff, I'll be around :)
Keep being awesome,

Namik

**Comment by namik-mesic** [comment]
Update:

Interestingly, the error has stopped occurring once I did the following:
I kept the * select, but I disabled some other malicious searchable fields (action buttons that did not have searchable set to false) that were somehow not showing up in the search query. I am confused :(

**Comment by yajra** [comment]
@namik-mesic, you are correct that added columns via `addColumn` are not searchable and orderable. Hence, you should add on your script to disable this columns by setting the ff:

```js
columns: [
  {data: 'id', 'name': 'id'},
  {data: 'action', 'name': 'action', orderable: false, searchable: false}, // added columns
] 
```
This options are needed because added columns are not part of the SQL Query and will surely break your code when it was used for querying your database.

**Comment by namik-mesic** [comment]
@yajra Yes, I am aware of that, and that has been fixed (I just forgot to do it on the example where I had the error happen). However, isn't it still 'strange' that the query attempted to perform "articles.* LIKE ..." regardless?

**Comment by yajra** [comment]
Oh yeah, that is indeed strange. Can you please paste some snippets on how to replicate it?

**Comment by yajra** [comment]
Closing due to lack of interests. Please post a new issue if needed. Thanks!
