### ISSUE TITLE
Another alternative fix for Id column that existed in main model and relation model

### ISSUE THREAD

**Issue by Azshurith** [yajra/laravel-datatables#2562]
Is there another alternative fix for the issue where id in relation model merges in main model? I am currently using "hasOne" and it is not currently supporting select statement

**Comment by yajra** [comment]
Can you provide some snippets to reproduce your issue? Are you using eager loading? If yes, make sure to include a select statement on your query.

```php
Model::with('relation')->select('models.*');
```

See [has-one](https://datatables.yajrabox.com/relation/has-one) demo for ref.
