### ISSUE TITLE
Serverside filter by a many-to-many relationship

### ISSUE THREAD

**Issue by James4645** [yajra/laravel-datatables#2567]
### Summary of problem or feature request

I have a list of posts in a datatable using serverside filter/pagination and ajax loading. I have a column that displays a comma seperated list of the tags associated with a post.

The relationship between a post and tag is many to many,

I am looking at https://yajrabox.com/docs/laravel-datatables/master/filter-column as the probable solution but I am at a loss of how to actually do the query, I don't really know much SQL.

**Comment by yajra** [comment]
Maybe this [demo](https://datatables.yajrabox.com/relation/morph-to-many) can help you?

**Comment by James4645** [comment]
Interesting. I was using the code from the Belongs to Many demo. I got the tags to display just couldn't search by them. For some reason trying the Morph to Many demo you linked I get the same result. Not sure what the difference is supposed to be or why the search isn't working, because is certainly does in the demo for me.
