### ISSUE TITLE
Search gender not working

### ISSUE THREAD

**Issue by habibiazmi123** [yajra/laravel-datatables#2568]
### Summary of problem or feature request

I have table to store gender like this (1 => Male, 2 => Female)

<img width="252" alt="image" src="https://user-images.githubusercontent.com/8370125/106348791-84d81880-62fb-11eb-84bc-01c14f8b0ff0.png">

this is my datatable 

<img width="363" alt="image" src="https://user-images.githubusercontent.com/8370125/106348822-b8b33e00-62fb-11eb-8a0d-207445c8c680.png">

when search by gender name data not showing

<img width="410" alt="image" src="https://user-images.githubusercontent.com/8370125/106348831-d5e80c80-62fb-11eb-87f7-ec816adeacf4.png">

### Code snippet of problem

my model

`class Employee extends Model {
    public static $genderOptions = [1 => "Male", 2 => "Female"];

    public function getGenderAttribute($value)
    {
        if ($value)
            return self::$genderOptions[$value];
    }
}`

`var table = $("#kt_datatable").DataTable({`
        `processing: true,`
`        serverSide: true,`
    `    sort: false,`
     `   searchDelay: 1000,`
      `  "ajax": {`
     `       "url": '{!! route("employee.index") !!}'`
    `    },`
      `  columns: [`
        `    { data: 'gender', name: 'gender'}, `
      `      { data: 'marital_status', name: 'marital_status'},`
    `        { data: 'actions', name: 'actions'}`
  `      ]`
`    });`

why did it happen? sorry about my bad explanation thanks

**Comment by yajra** [comment]
Your displaying a computed value for gender column and thus it's not searchable on the database level since Male is not equal to 1 when doing a database query.

A workaround is to use the [filterColumn](https://yajrabox.com/docs/laravel-datatables/master/filter-column) api. 

```php
->filterColumn('gender', function($q, $keyword) {
  if ($keyword == 'Male') {
    $q->where('gender', 1);
  }
  // do stuffs to properly map the string search to equivalent gender value.
})
