### ISSUE TITLE
Does this package "used not as service" support DataTables Buttons

### ISSUE THREAD

**Issue by ettoinim** [yajra/laravel-datatables#2569]
### Summary of problem or feature request

Hi,
i would like to use this package in order to support for DataTables Buttons (server-side processing) without using it as service,
any one here knows how to deal with this?

Thank you.

**Comment by yajra** [comment]
This is doable, you just have to implement the server-side functionality on your own as needed (ex. print and export to xls functions). 

For the custom buttons, see https://github.com/yajra/laravel-datatables-buttons/blob/4.0/src/resources/assets/buttons.server-side.js for reference.

**Comment by ettoinim** [comment]
ok sir thank you!
