### ISSUE TITLE
Using Scopes with DataTables as a Service

### ISSUE THREAD

**Issue by Skintillion** [yajra/laravel-datatables#257]
I have tried searching but cannot find how you add scopes.

But I have figured it out. Works great with bicanroles to have records pulled based on Authentication.

First you have to run
`php artisan datatables:scope ActiveUserScope`

Then edit the scope in
`App/DataTables/Scopes`

```
if (Auth::user()->isManager()) {
    $query->where('user.active',1);
}
```
Then add the following to your UserDataTable.php
`use App\DataTables\Scopes\ActiveUserScope;`

and under query()

```
//Add Scopes
$this->addScope(new ActiveUserScope);

//Apply Scopes
return $this->applyScopes($users);
```

**Comment by yajra** [comment]
I think it's best to add the scopes inside the controller to make the DataTable class reusable via scoping. Like this example for instance. I wanted to reuse the `UsersDataTable` and display only those that are under a certain company (multi-tenant) app.

```php
public function index(Company $company, UsersDataTable $dataTable)
{
    return $dataTable->addScope(new CompanyOwnedScope($company))
        ->render('admin.companies.users.index', compact('company'));
}
```

**Comment by Skintillion** [comment]
Ah nice, should I go about adding this into one of the examples?

**Comment by yajra** [comment]
If you can then it would be great. That will help especially for those early adapters who may want to try these new features that we are introducing. Thanks!

**Comment by herzcthu** [comment]
I have very simple fix.
In service implementation html builder method
```php
public function html()
    {
        $table = $this->builder()
            ->columns($this->getColumns())
            ->ajax(['type' => 'POST', 'data' => '{"_method":"GET"}']);
        
            $table->addAction(['width' => '80px']);

        return $table->parameters($this->getBuilderParameters());
    }
`
