### ISSUE TITLE
Custom Input Filter 

### ISSUE THREAD

**Issue by AmaurySchmitt** [yajra/laravel-datatables#2571]
### Summary of problem or feature request

Hello,
I need of you, my custom filter doesn't work and I can't find the problem(s). In fact the request work but data aren't display,  thank for your help ! :)

### Code snippet of problem

	public function index(Request $request)
	{
		$countries = DB::table('tbl_countries')
		->select('*')
		->get();

		if ($request->ajax()) {
			$agents = DB::table('agents')
			->select('*')
			->join('tbl_countries', 'tbl_countries.idCountry', '=', 'agents.country')
			->orderBy('agents.id', 'desc')
			->get();		
			$datatables = Datatables::of($agents);

			if($id = $request->input('name')) {
				$agents->where('nameFirm', $id);
			}

			return $datatables
			->addIndexColumn()
			->addColumn('profil', function($row){
				return '<p>'.$row->lastName.'<span>'.$row->firstName.'</span></p><p>'.$row->mail.'</p>';
			})
			->rawColumns(['profil'])
			->make(true);
		}
		return view('pages/home', compact('countries'))->render();
	}

```javascript

	var table = $('#tableAgents').DataTable({
		processing: true,
		serverSide: true,
		ajax: {
			url: "/index",
			data: function (d) {
				d.name = $('input[name=name]').val();
			}
		},
		columns: [
		{data: 'DT_RowIndex', name: 'DT_RowIndex'},
		{
			data: 'profil', 
			name: 'profil', 
			orderable: true, 
			searchable: true
		},
		{data: 'phone', name: 'phone'},
		{data: 'nom_fr_fr', name: 'nom_fr_fr'},
		{data: 'city', name: 'city'},
		{data: 'nameFirm', name: 'nameFirm'},  
		]
	});

	$('#testTzabl').on('keyup', function(e) {
		table.draw();
		e.preventDefault();
	});



- Operating System : Windows
- PHP Version : 7.3|8.0
- Laravel Version : 8.12
- Laravel-Datatables Version : 9.15

**Comment by dream811** [comment]
I met a same problem.
how to fix this issue?
