### ISSUE TITLE
ErrorException (E_WARNING) count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by nrorah** [yajra/laravel-datatables#2572]
### Summary of problem or feature request

Hi, i meet some issue when development in this part using yajra datatables

![countables-errorexception](https://user-images.githubusercontent.com/13460810/107151207-ebaca000-6993-11eb-8076-28523485c803.png)

In my local in running well, but in production i meet that issue count(), 
- in print variable function $coulum in production is show ["null"] not showingall count in column data in JQuery
please is ther e any suggestion for this issue ?

thank u for advice.

### Code snippet of problem

`       var oTable = $('#data-table').DataTable({
                "processing"    : true,
                "serverSide"    : true,
                lengthMenu      : [[10, 50, 100, -1], [10, 50, 100, "All"]],
                scrollX         : "true",
                scrollCollapse  : true,
                searching       : false,
                fixedColumn    :   {
                    leftColumns : 1
                },

                dom: 'Bfrtip',
                buttons: {
                    buttons: [
                        {
                            extend: 'excel',
                            text: 'Export to Excell',
                            filename: 'Tabulasi Data',
                            action: newExportAction
                        },
                    ]
                },                

                ajax: {
                    "url": "{!! url($uri.'/data') !!}",
                    "type": "GET",
                    data: function (d) {
                        d.aksi = $(".filter_status option:selected").val();
                        d.balaiid = $(".filter_balai option:selected").val();
                    }
                },

                columns: [
                    {data: 'balaiid', name: 'balaiid'},
                    {data: 'embung', name: 'embung'},
                    {data: 'dataembung', name: 'dataembung'},
                    {data: 'bendungan', name: 'bendungan'},
                    {data: 'databendungan', name: 'databendungan'},
                    {data: 'bendung', name: 'bendung'},
                    {data: 'databendung', name: 'databendung'}
                 ], 
         });  `

### System details

My Local Development :
Laravel 5.8
PHP 7.2.5
MySQL
Yajra Datatables 6.24.1

Here's my production server environment :
PHP 7.2.38
Ubuntu 20.04
Yajra Datatables 6.24.1 already try to upgrade to versi 8.0 but search, pagination and lenght data is not working
Laravel 5.7  => i' already try with downgrade from 5.8 to 5.7

**Comment by yajra** [comment]
I think that is specific to PHP 7.2++ compatibility issue if I recall correctly and already fixed in the latest version. I suggest you upgrade to v9 since it still supports Laravel 5.8 per the matrix docs.

**Comment by gnm3000** [comment]
Put this in your PHP class controller 

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    // Ignores notices and reports all other kinds... and warnings
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
    // error_reporting(E_ALL ^ E_WARNING); // Maybe this is enough
    }
Example:
`<?php

namespace App\Http\Controllers;
if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    // Ignores notices and reports all other kinds... and warnings
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
    // error_reporting(E_ALL ^ E_WARNING); // Maybe this is enough
    }
use Illuminate\Http\Request;
use App\Http\Requests;
use DB;
use App\User;
use App\Role;
use Auth;
use Session;
use Yajra\Datatables\Facades\Datatables;
class UserController extends Controller {`
