### ISSUE TITLE
Search in an alias column with a count relationship

### ISSUE THREAD

**Issue by ramonMontanhes** [yajra/laravel-datatables#2582]
### Summary of problem or feature request

I have a table named `categories` and a table named `products`
Categories columns:
id, name, active, created_at, updated_at

Products columns:
id, name, barcode, sku, category_id, created_at, updated_at

I want to display the list of categories and a column in this table with the total of products that this relationship have.

On my table I want to display the columns:

category name, products (count of products on this category) and an action column with edit and delete buttons

I could display it and order it but the search isn't working, if I tried to search by 4 for example it does not return the categories that have 4 products in this relationship.

### Code snippet of problem

```php
if ($request->ajax()) {
            $category = Category::withCount('products')->where('active', 1);

            return DataTables::of($category)
                ->addColumn('action', function ($category) {
                    return $this->tableActions($category);
                })
                ->addColumn('products', function ($category) {
                    return $category->products_count;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
```

```js
$('.table-categories').DataTable({
        processing: true,
        responsive: true,
        serverSide: true,
        sDom: "ltipr", // exibe todos campos menos o campo de busca padrão da tabela
        ajax: "/categories",
        dataSrc: 'data',
        columns: [
            {data: 'name', name: 'name', orderable: true, searchable: true},
            {data: 'products', name: 'products_count', orderable: true, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],
```

### System details

- Operating System: Manjaro Linux
- PHP Version: 7.4.15
- Laravel Version: ^8.0
- Laravel-Datatables Version: ~9.0

**Comment by ramonMontanhes** [comment]
Something that I forget to say: I'm using https://tenancyforlaravel.com/ on my project, so far everything is working correctly.

**Comment by schonhoff** [comment]
Hi,

you need the following:
https://yajrabox.com/docs/laravel-datatables/master/filter-column

It should be something like this:

```php
        return DataTables::of($category)
            ->addColumn('action', function ($category) {
                return $this->tableActions($category);
            })
            ->addColumn('products', function ($category) {
                return $category->products_count;
            })
            ->filterColumn('products', function ($query, $keyword) {
                $query->having('products_count', '<', $keyword);
            })
            ->rawColumns(['action'])
            ->make(true);
```

The keyword is in that example the "4". Hope that will help you.

**Comment by ramonMontanhes** [comment]
> Hi,
> 
> you need the following:
> https://yajrabox.com/docs/laravel-datatables/master/filter-column
> 
> It should be something like this:
> 
> ```
>         return DataTables::of($category)
>             ->addColumn('action', function ($category) {
>                 return $this->tableActions($category);
>             })
>             ->addColumn('products', function ($category) {
>                 return $category->products_count;
>             })
>             ->filterColumn('products', function ($query, $keyword) {
>                 $query->having('products_count', '<', $keyword);
>             })
>             ->rawColumns(['action'])
>             ->make(true);
> ```
> 
> The keyword is in that example the "4". Hope that will help you.

Hi @schonhoff I tested it.

```
DataTables warning: table id=table-categories - Exception Message:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'categories.products_count' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `categories` where `active` = 1 and (LOWER(`categories`.`name`) LIKE %2% or LOWER(`categories`.`products_count`) LIKE %2%)) count_row_table)
```

```
public function index(Request $request)
    {
        if ($request->ajax()) {
            $category = Category::withCount('products')->where('active', 1);

            return DataTables::of($category)
                ->addColumn('action', function ($category) {
                    return $this->tableActions($category);
                })
                ->addColumn('products', function ($category) {
                    return $category->products_count;
                })
                ->filterColumn('products', function ($query, $keyword) {
                    $query->having('products_count', '=', $keyword);
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('categories.index');
    }
```

**Comment by yajra** [comment]
I think we cannot search on withCounts but sorting is working on it if I recall correctly. You need to set the products column as `searchable: false`. 

Also, afaik, `having` where clause is not supported on nested wheres. If you want to use is, it should on the query outside dataTables.

```php
public function index(Request $request)
    {
        if ($request->ajax()) {
            $category = Category::withCount('products')->where('active', 1);

           if ($add_condition) {
               $query->having('products_count', '=', $keyword); // not tested.
           }

            return DataTables::of($category)
                ->addColumn('action', function ($category) {
                    return $this->tableActions($category);
                })
                ->addColumn('products', function ($category) {
                    return $category->products_count;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('categories.index');
    }
```

**Comment by schonhoff** [comment]
I personally found this article on StackOverflow:
https://stackoverflow.com/questions/39930975/laravel-using-where-clause-on-a-withcount-method

There where some interesting things. Maybe something is working for you. My example wasn't on a nested where, so that was my bad!

**Comment by ramonMontanhes** [comment]
> I think we cannot search on withCounts but sorting is working on it if I recall correctly. You need to set the products column as `searchable: false`.
> 
> Also, afaik, `having` where clause is not supported on nested wheres. If needed, it should be on the query outside dataTables.
> 
> ```
> public function index(Request $request)
>     {
>         if ($request->ajax()) {
>             $category = Category::withCount('products')->where('active', 1);
> 
>            if ($add_condition) {
>                $query->having('products_count', '=', $keyword); // not tested.
>            }
> 
>             return DataTables::of($category)
>                 ->addColumn('action', function ($category) {
>                     return $this->tableActions($category);
>                 })
>                 ->addColumn('products', function ($category) {
>                     return $category->products_count;
>                 })
>                 ->rawColumns(['action'])
>                 ->make(true);
>         }
> 
>         return view('categories.index');
>     }
> ```

This did not worked for me.


> I personally found this article on StackOverflow:
> https://stackoverflow.com/questions/39930975/laravel-using-where-clause-on-a-withcount-method
> 
> There where some interesting things. Maybe something is working for you. My example wasn't on a nested where, so that was my bad!

I checked this link and I have some results:

If I do this query by default: 
![image](https://user-images.githubusercontent.com/983688/112358911-8399eb00-8caf-11eb-8eb7-a8b98031699c.png)
It returns me the rows filtered by the product count, but all the others products that have more or less than the integer value will not display.

Also of course I tried to do this:
![image](https://user-images.githubusercontent.com/983688/112358642-4afa1180-8caf-11eb-81bc-76e8b65d1502.png)
If I search for something it does not return nothing.

Checking the request on the browser I found this query:

select `categories`.*, (select count(*) from `products` where `categories`.`id` = `products`.`category_id`) as `products_count` from `categories` where (select count(*) from `products` where `categories`.`id` = `products`.`category_id`) = 2 and `active` = 1 **and** (LOWER(`categories`.`name`) LIKE 2) order by `name` asc limit 10 offset 0

I have run this query on the database and it does not return nothing as expected.

And after I changed the AND to an OR:

select `categories`.*, (select count(*) from `products` where `categories`.`id` = `products`.`category_id`) as `products_count` from `categories` where (select count(*) from `products` where `categories`.`id` = `products`.`category_id`) = 2 and `active` = 1 **or** (LOWER(`categories`.`name`) LIKE 2) order by `name` asc limit 10 offset 0

It worked.

Just to know:

I still have the searchable attribute as false on this test I did.

{data: 'products', name: 'products_count', orderable: true, searchable: false},
