### ISSUE TITLE
How to rename columns

### ISSUE THREAD

**Issue by MikadoInfo** [yajra/laravel-datatables#2584]
### Renaming Columns

I'm making a multilanguage website and I need to rename the  columns name based on the language selected by the user how do i rename the columns in my table?

- Windows 10
- PHP Version 7.4.9
- Laravel Version 7.24
- Laravel-Datatables Version 1.5

**Comment by schonhoff** [comment]
Hi,
do you use the html-Builder for that package? Than it should be something like this:
```php
 Column::make('id')->title(__('ID FIELD')),
```
Here the documentation:
https://yajrabox.com/docs/laravel-datatables/master/html-builder-column

If you use something like native datatable.js with the Backend from this package, just use blade syntax:

```js
{data: 'id', name: 'id', title: '{{ __('ID FIELD') }}' },
```

Or in the HTML table element:

```html
<table id="table-id" class="table dt-responsive table-bordered table-striped table-hover">
    <thead>
    <tr>
        <th>{{ __('ID FIELD') }}</th>
[...]
    </tr>
    </thead>
</table>
```

I hope that will help you :-)

**Comment by MikadoInfo** [comment]
It works thank you
