### ISSUE TITLE
Order en search can be applied to all columns in the database

### ISSUE THREAD

**Issue by rickatultraware** [yajra/laravel-datatables#260]
The jQuery datatables make a request to the server with the requested columns including order and search.
When i manipulate the request on the client it's possible to query, sort or filter by a column that isn't used in the datatable.

So as an example i can filter my rows by a field that isn't supposed to be accessible at the frontend.

It will be nice if i can prevent the use of unallowed columns within the datatables class.

**Comment by yajra** [comment]
@rickatultraware, Yes you are correct that it's possible to sort or filter by a column that isn't used in the dataTable.

Will try to figure out if we can prevent the use of not allowed columns. If you have a solution in mind, PR are always welcomed. ^_^ Thanks!

**Comment by rickatultraware** [comment]
Currently i use a quick fix with an object that filters the request manually.

```php
<?php

namespace \Datatables;


class DatatableRequestFilter
{
    private $allowedCols = [];

    public function setAllowedCols(array $allowedCols)
    {
        $this->allowedCols = $allowedCols;
    }

    public function apply($request)
    {

        $allowedCols = $this->allowedCols;

        $cols = $request->query->get('columns');

        foreach ($cols as $key => $column) {

            if (!in_array($column['data'], $allowedCols)) {
                unset($cols[$key]);

            }
        }
        $request->query->set('columns', $cols);

        return $request;
    }
}

**Comment by yajra** [comment]
@rickatultraware, I just [committed](https://github.com/yajra/laravel-datatables/commit/212ba252ee6b0e7eb1909ca4c1f641e5a3ed2db8) on `dev-develop` branch that add a `blacklist` function where we can set which columns are restricted from sort & search. Can you please try if the proposed solution is acceptable for you? See example usage below:

```php
$users = User::query();

return Datatables::of($users)
    ->blacklist(['password', 'email'])
    ->make(true);
``` 

Let me know what you think. Feedbacks appreciated. Thanks!

**Comment by rickatultraware** [comment]
I prefer to us a white list. because I use queries that contains more than 1 table. The blacklist would be big and not maintainable.

**Comment by yajra** [comment]
@rickatultraware, thanks for the feedback. I just [committed](https://github.com/yajra/laravel-datatables/commit/b0f81a8926446a86249f59179380e98c313fc84c) additional `whitelist` feature which works together with `blacklist`. This way, the user can choose which of the function to use based on their preference. 

```php
$users = User::query();

return Datatables::of($users)
    ->whitelist('*')
    ->blacklist(['password', 'email'])
    ->make(true);
```

In case we use both function at the same time, blacklist will be prioritized. Let me know if this works for you? Thanks!

**Comment by yajra** [comment]
@rickatultraware, I already released the blacklist & whitelist feature. Regards!
