### ISSUE TITLE
serverside  search help

### ISSUE THREAD

**Issue by NatBLida68** [yajra/laravel-datatables#2601]
can i set serverside false for  a single column  ?
in database I'm saving digits for states in my country (state_code) and in a common js file i have their corresponding names , as usual i use render functions to change digits to names in datatable callback  , others columns are displaying without render 
now i have to search  state names   so i  use filterColumn in controller to mange that   so if i can set serverside search false for a single column?

**Comment by yajra** [comment]
Afaik it's a NO. You can only use either serverSide true or false but not both. If you can change the states to a table and set a belongsTo relation, then you can easily search via eager loading. See https://datatables.yajrabox.com/relation/belongs-to for ref.

**Comment by NatBLida68** [comment]
@yajra  thanks for the info  👍
