### ISSUE TITLE
Broken Demo Link

### ISSUE THREAD

**Issue by jerryhall** [yajra/laravel-datatables#2603]
### Summary of problem or feature request

The URL for the Demo Application left menu [link ](https://datatables.yajrabox.com/)in the Getting Started section on your [main site](https://yajrabox.com/docs/laravel-datatables/master) is broken and returns this error message:

```
Secure Connection Failed

An error occurred during a connection to datatables.yajrabox.com. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by schonhoff** [comment]
Hi,

have no problem with the link. Maybe it was temporary down or can you say us your browser + version?

**Comment by jerryhall** [comment]
Apparently it's my bad as I can't replicate it myself. Feel free to delete this post to keep your board clean. Thank you for your work!

**Comment by schonhoff** [comment]
No problem. You can just close the ticket by yourself. Yajra is the package owner, not me :) But I try to help here if I have some freetime.

**Comment by jerryhall** [comment]
I believe this must've been an issue with my phone browser. Thanks you @Schonhoff and Yajra!
