### ISSUE TITLE
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by corriedtoppin** [yajra/laravel-datatables#2607]
Hello.  I have a problem, I am not sure if anyone here can help me, as I am new to coding etc. Please forgive for lack of knowledge...

I download a website on HTTrack which I placed my:

user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" and 

Cookie: PHPSESSID=2j0hb3liiv5km4grhvcmn6q933  as and my username and pass word.

The problem here is this: After downloading on my computer and opened the local website. I got and error which states:
"DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

I tried following the steps on the line provided, in Google Chrome http://datatables.net/tn/7 but no avail. Next

I followed the steps and source to the problem: Inspect>>Network>>XHR>>Name.

Under the "Name" tab, There are 8 on the list. Each name has the same initiator. Which is: "jquery-1.9.1.min.js:5"

Please view photo:
https://imgur.com/a/1oIUw1G
Even the "Response tab" "Failed to load response data" on all listings.

I am not sure how to move forward from here. I did some researched, which pointed to the 400 and 500 common errors.

I am sorry for the long texts... 
As I pasted the "jquery-1.9.1.min.js:5" code in https://jsonlint.com I came up with the following errors.

`Error: Parse error on line 1:
/*! jQuery v1.9.1 | 
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'`

I have no idea what that means and which part of the code to begin with. "pulling my hair out right now"...

What do you suggest I do to move forward? How can this problem fix?

I am afraid and terrify to pasted the whole code here. I am not sure if it was a ridiculous idea to view the code in the link below:

https://drive.google.com/file/d/1pw7ik_WtfeuvzwM9lBE76kW4w3xiR5K1/view?usp=sharing

Thanks in advance

I cannot drink no more caffeine

**Comment by corriedtoppin** [comment]
It seems like this is a difficult task to accomplish...

**Comment by schonhoff** [comment]
Hello,

if you have the Debug mode from laravel on true you can click on "OK" in the modal field.-After you did this the response in the Network tab says you where the error occured. It would help us here if you can provide us your controller code and your view code. In your google drive is only a jquery file which has nothing to do with this package. Also please consider to use the issue template next time :-)

**Comment by corriedtoppin** [comment]
Hello. schonhoff, I am really thankful for your feedback. I do...

I am sorry for my lack of knowledge with the jquery file.

Please, if you are willing. Below is the website information. This may have the controller code requested:
https://drive.google.com/file/d/14uvvldLcLIkLwstg9K8KenQZqYLbiqLz/view

It my seems like I may have knowledge about "Debug mode from laravel on true you can click "OK"". 
I am sorry. But how can I do that?
What is the steps to follow your tuition?

Thanks in advance

Corrie

**Comment by schonhoff** [comment]
Hi,

here is how you are handling the debug mode on Laravel:
https://laravel.com/docs/8.x/configuration#debug-mode

You can put your code in here. Just use the "insert code" control on top of the editor. I don't want to download a rar file nor am I willing to visit a google drive for security reasons.

Try to open another issue, copy the text from editor in here and fill out the form given there :-) It will help us to understand your problem. There is also a mask to handle code inline here.

In your screenshot from the first request there is a CORS error. I think your server isn't set up correctly and I would guess that you aren't even using Laravel. But you can provide the things asked for in the "new issue" -template.

**Comment by corriedtoppin** [comment]
Thanks schonhoff for your shift response.

I am sorry schonhoff, I was hesitant to write back to you, openly for others to read.
I was not sure what is "Laravel"? and How can Laravel can help me? As I have no understanding of coding.
I am not even clear, if Laravel is built installed on my windows 10 computer.

I apologies schonhoff. I may have to get sometime to really understand  and research some more on what you are saying. Concerning, The code you want me to paste, Laravel, and CORS error.

As a baby, the only thing I can feed on is milk. I may need someone to help with the diapers and the burping.

What video you recommend to watch base on your explanations?

Thanks in advance for your time and consideration.

Cheers

**Comment by Momenoor** [comment]
Hello,
(Forgive for weak English when I'm not English speaker)
It seem like that the website you downloaded is using DataTables library, which is a library built in jQuery.
One of its features that its calling some data from anywhere and format it like a table with a lot of advanced features this call done via AJAX call.
But actually this call failed because you haven't any data to return " it is just a downloaded template and not customized yet".

So you have to read more about JavaScript then jQuery then DataTables.

BTW This issue dose not belong to Laravel.

Thank you.

**Comment by corriedtoppin** [comment]
Thank you Momenoor. I was waiting for a response to move forward.
I am sorry, what do you suggest to do to move forward? How can I get the data download?

I am not sure if you have any suggestions or recommendations..

Thanks Momenoor

**Comment by Momenoor** [comment]
Hi,
Could you please clarify what kind of data you want to download (is it a data on a page? Or website template? Or what exactly data you need?).
The issue is not clear to me.

I will do my best to provide you with what you need.

Thanks

**Comment by corriedtoppin** [comment]
Thanks Momenoor for your swift responce. Yes I am trying to download a website template.

I am not sure whose recommendation I should follow. Yours or schonhoff.

Thanks again

**Comment by Momenoor** [comment]
Hi,

It is depend on your needs,( where GitHub is a Developers Community )

Are you a web developer? So you must follow schonhoff for advanced level "Backend", or my first comment for basic to solve your current issue "frontend".

If you just want to download the website so no need to dive into the code.

And you must share the files you downloaded to help on this.

**Comment by corriedtoppin** [comment]
Thank you Momenoor. I seems like you are really generous with your time and I really appriceate your effort to help me solved my problems.

Below is the download files. the problem with such files are this:
I can only view the first page. Every time I tried to click on any other links, I automatically is transferred to the login page.

I am sorry Momenoor. I am not sure how to bypass this? Then again, I am not even sure, if I did the right thing.

How can you point me to the right direction?

I appreciate your wisdom Momenoor

Cheers

Corrie
[Push Button.zip](https://github.com/yajra/laravel-datatables/files/6302017/Push.Button.zip)

**Comment by Momenoor** [comment]
I'm not sure if what you are trying to do is legal or not, but after reviewing the files you send, sadly I'm must tell you that it's need a hard work to bypass login screen.

I'm sorry to tell you I can't help.

Best wishes for you

**Comment by corriedtoppin** [comment]
Momenoor. I am sorry. I currently have my username and password. Is it a ridiculous idea that it can not work?

**Comment by Momenoor** [comment]
For offline version of files no way to make login, since there is no connection with database on live server.

**Comment by corriedtoppin** [comment]
Hello Momenoor & schonhoff Thanks for your feedback and contribution. 

I did not know there were so many issues to fix this. I decided not to move forward with the site again.

Thanks again 

Corrie
