### ISSUE TITLE
Incorrect "recordsTotal" returned

### ISSUE THREAD

**Issue by playstation9** [yajra/laravel-datatables#2613]
### Summary of problem or feature request

server-side returns incorrect "recordsTotal". 

### Code snippet of problem

In vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php in method count on row 211 this was added in 9.17.3:
        
        if (empty($builder->havings)) {
            return $builder->count();
        }

And it returns incorrect total records.

### System details

- Operating System
- PHP Version: 7.4
- Laravel Version: 6
- Laravel-Datatables 9.17.3

**Comment by yajra** [comment]
Count changes reverted on v9.17.4. Thanks for reporting!

**Comment by yajra** [comment]
@playstation9 may we request if possible, for you to test PR https://github.com/yajra/laravel-datatables/pull/2616. Just an additional check to make sure do don't break anything this time. Thanks!
