### ISSUE TITLE
Slow Search / Draw on Large Database (2M Rows)

### ISSUE THREAD

**Issue by saaiful** [yajra/laravel-datatables#2617]
### Summary of problem or feature request

I was testing a new system that has more than 2 million rows. When searching with `datatable` it took 10 seconds to find results and I was using Query Builder and only one column was searchable. To solve this issue I set `"searching" => false` and add a manual search filter, which cut the loading time to 0.006 - 1 second. 

Then I added a `JOIN` in my query and my new loading time hit a new record high of 30 seconds for 10 results. I specified every column name to reduce the query execution time. 

Finally, I fixed it by removing `JOIN` query and manipulating the JSON data.
1. I collected  the query result from the JSON data
2. Then I extracted user_id in an array and using that collected user names and insert them into the query result.

Now my hacked JOIN query (is not a join query) executes in 124ms for 10 results and 174ms for 100 results. 

My question is how can I make this process easy and fast without doing stupid hacks?

**Comment by saaiful** [comment]
```mysql
SELECT payments.*, `users`.`name` FROM `payments` JOIN `users` ON `payments`.`user_id` = `users`.`id` LIMIT 10
```
Query took 0.0008 seconds

```mysql
SELECT payments.*, `users`.`name` FROM `payments` JOIN `users` ON `payments`.`user_id` = `users`.`id` LIMIT 100
```
Query took 0.0018 seconds

```mysql
SELECT count(`payments`.`id`) as total FROM `payments` JOIN `users` ON `payments`.`user_id` = `users`.`id`
```
Query took 1.7467 seconds.
```mysql
SELECT count(`payments`.`id`) as total FROM `payments`
```
Query took 0.0002 seconds.

**Comment by yajra** [comment]
Performance depends on every project but it will greatly improved if you will be able to optimize your query. 

Anyways, I just released https://github.com/yajra/laravel-datatables/releases/tag/v9.18.0 which aims to improve the count performance. Try updating and hope it for works for your case. Thanks!
