### ISSUE TITLE
Custom columns names when export in CSV DataTables Laravel 8

### ISSUE THREAD

**Issue by AmaurySchmitt** [yajra/laravel-datatables#2622]
### Summary of problem or feature request

I am stuck on a big point, how can I customize the column names when exporting my table? And how can I pass accented characters without having a weird symbol when exporting? (I'm on Laravel 8)

Thanks for your help !

### Code snippet of problem

`public function html()
    {
        return $this->builder()
            ->setTableId('studentsdatatable-table')
            ->columns($this->getColumns())
            ->Ajax(['data' => '
                        function(d) {
                            d.dateTableStart= $("#dateTableStart").val();
                            d.dateTableEnd= $("#dateTableEnd").val();
                            d.dataTableSearch= $("#dataTableSearch").val();
                        }
                    '])
            ->language(url('json/fr_tables.json'))
            ->dom('Bfrtip')
            ->orderBy(1)
            ->buttons(
                Button::make('csv'),
                Button::make('print')
            );

    }

    protected function getColumns()
    {
        return [
            "Id" => ['data' => 'numbersId', 'name' => 'numbersId', 'className' => "idStudent"],
            "Numéro Etudiant" => ['data' => 'numStudent', 'name' => 'numStudent', 'className' => "numStudent"],
            "Nom" => ['data' => 'lastNameS', 'name' => 'lastNameS', 'className' => "lastName"],
            "Prénom" => ['data' => 'firstNameS', 'name' => 'firstNameS', 'className' => "firstName"],
            "Email" => ['data' => 'mail', 'name' => 'mail', 'className' => "email"],
            "Formation" => ['data' => 'nameFormation', 'name' => 'nameFormation', 'className' => "formation"],
            "Réglages" => ['data' => 'action', 'name' => 'action', 'className' => "text-right", 'orderable' => false, 'searchable' => false, 'exportable' => false, 'printable' => false]
        ];
    }`

### System details

- Operating Big Sur MacOS
- PHP 8.0
- Laravel 8.12

**Comment by yajra** [comment]
See https://yajrabox.com/docs/laravel-datatables/master/export-column#export-column-with-title

**Comment by AmaurySchmitt** [comment]
Thanks you so much !!! 
But how I can implent this ? In which function ? I just need some sample code to be able to implement it. For example I don't know whether to implement it in the "getColumns" or "html" function 

Thanks again!

**Comment by yajra** [comment]
See sample code:

```php
    public function html()
    {
        return $this->builder()
            ->setTableId('students-table')
            ->columns($this->getColumns())
            ->ajax(['data' => '
                        function(d) {
                            d.dateTableStart= $("#dateTableStart").val();
                            d.dateTableEnd= $("#dateTableEnd").val();
                            d.dataTableSearch= $("#dataTableSearch").val();
                        }
            '])
            ->language(url('json/fr_tables.json'))
            ->dom('Bfrtip')
            ->orderBy(1)
            ->buttons(
                Button::make('csv'),
                Button::make('print')
            );
    }

    protected function getColumns()
    {
        return [
            Column::make('numbersId')->title('Id'),
            Column::make('numStudent')->title('Numéro Etudiant')->className('numStudent'),
            ...
            Column::computed('action')->title('Réglages')->className('text-right')->exportable(false)->printable(false),
        ];
    }
```

**Comment by AmaurySchmitt** [comment]
Thank you for this concrete example,

I misspoke, my problem is when I export my data, my columns shouldn't be the column names displayed in HTML, for example the column that the user will see on the site will be "Student Name", but when export my data the column name should be "nameStudent" which is my column name in my database.

The goal of this action is to be able to import the exported data into a database, moreover how do you change the format of the CSV, I would like to have ";" instead of ",",
Thanks again for the help.

**Comment by yajra** [comment]
You can customize further using exportColumns property. https://yajrabox.com/docs/laravel-datatables/master/export-column#export-column-with-title.

```php
class UsersDataTable extends DataTable
{
  protected $exportColumns = [
    ['data' => 'numStudent', 'title' => 'Student Number'],
    ['data' => 'email', 'title' => 'Registered Email'],
  ];
}
```

If you want to go further, use export class instead: https://yajrabox.com/docs/laravel-datatables/master/buttons-laravel-excel
