### ISSUE TITLE
How to publish stubs?

### ISSUE THREAD

**Issue by tdrabikdev** [yajra/laravel-datatables#2629]
Hello guys,

I already publish laravel stubs however no datatables stubs there. I made this file manually however it don`t works like that. I just want to make easy to make bunch of classes.

```
php artisan datatables:make Admin\User --model=App\Models\User

```

but it still use stub from vendor

**Comment by yajra** [comment]
On `config/datatables-button.php`, update: `'stub' => '/stubs/dataTables',`

**Comment by tdrabikdev** [comment]
Thanks :)
