### ISSUE TITLE
Unexpected selection of rows

### ISSUE THREAD

**Issue by jmteixeira** [yajra/laravel-datatables#263]
Hi, I'm using this package in a project and it was working perfectly. I don't know if it was an update or something, but now when I click in a column to sort by, it selects all rows at the same time. I don't know if this is a problem of this package or datatables. Did it happened to someone else?

Thank you.

**Comment by yajra** [comment]
Not sure, but I think this is related to the [`select` extension](http://datatables.net/extensions/select/) of dataTables. And I think that this is a client-side (js) issue so I guess it's not related to the package.

**Comment by jmteixeira** [comment]
Thank you, I thought so too, but it's weird because it was working earlier. I will ask there.
