### ISSUE TITLE
editColumn with Blade view has no relations

### ISSUE THREAD

**Issue by victorelec14** [yajra/laravel-datatables#2632]
### Summary of problem or feature request

When I use the editColumn with the direct function it works but when I use the blade templates it does not take the relations "with" that were declared in Query().

### Code snippet of problem

```php
public function query() {
        return Ticket::with('latestEditor').....;
    }
```

This is ok
```php
// This is ok
->editColumn('editor', function(Ticket $ticket) {
                return $ticket->latestEditor ? $ticket->latestEditor->name : '';
            })
```

That give 'undefined variable: latestEditor'
```php

->editColumn('editor2', 'datatables.editor')

//editor.blade.php
@if($latestEditor)
  {{$latestEditor->name}}
@endif
```

### System details

- Operating System W10
- PHP Version 7.4
- Laravel Version 8.12
- Laravel-Datatables Version 
```
"yajra/laravel-datatables-buttons": "^4.13",
"yajra/laravel-datatables-oracle": "^9.18",
"yajra/laravel-datatables-html": "^4.36"
```

**Comment by sitenzo** [comment]
Hi, 

Have you tried the name of the column?
I think that is the only variable that will pass with the blade, just started yesterday with Datatables for Laravel so i could be wrong here.

->editColumn('editor2', 'datatables.editor')

//editor.blade.php
@if($editor2)
  {{$editor2->name}}
@endif

**Comment by yajra** [comment]
I think I see something here with regards `editor` variable. It is considered a raw / javascript by the compiler for it to work with DataTables Editor library. Atm, please use another variable name if possible like `latestEditor` or `editor2`.
