### ISSUE TITLE
how i can change the header title ?

### ISSUE THREAD

**Issue by 8lbiasian** [yajra/laravel-datatables#264]
how i can change the header title ? 

i use the Datatables as service and i try the edit column but its affect the result of that column not the title of it 

for example the id column i need to make it as #  also from my database i have some spelling mistake so i was think it will be easy if there is way to edit the column name from the table it self rather than playing with db again =(

**Comment by Skintillion** [comment]
on the html builder you want the 'title' attribute.

```
public function html()
    {
        return $this->builder()
            ->columns([
                [
                    "name" => "contractvalue",
                    "title" => "Contract Value",
                    "data" => "contractvalue"
                ],
```

**Comment by 8lbiasian** [comment]
@Skintillion i try this before but it give me this error 

![image](https://cloud.githubusercontent.com/assets/2717113/11415501/49b9d9ee-941d-11e5-86f1-f5fe1c019842.png)

**Comment by yajra** [comment]
Guys FYI: https://github.com/yajra/laravel-datatables/issues/265 Major breaking change is coming next week.

**Comment by sandipsapkota1** [comment]
It still Not working,Can somebody help me

I got this error,
Datatable Builder Exception Message:
strtolower() expects parameter 1 to be String, Array Given.

 How Header name changing works.?
I am worried, I always gets this error.   Can you post a example for me?
@Skintillion @8lbiasian @yajra  please guys.

**Comment by Fionajeremychik** [comment]
public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->addAction(['width' => '120px', 'printable' => false])
            ->parameters([
                'dom'       => 'Bfrtip',
                'stateSave' => true,
                'order'     => [[0, 'desc']],
                'buttons'   => [
                    ['extend' => 'export', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'print', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'reload', 'className' => 'btn btn-default btn-sm no-corner',],
                ],
            ]);
    }

protected function getColumns()
    {
        return [
            'id',
            'name',
            'section',
            'contact',
            'approved',
            'cardno',
            'issuedate',
            'status' => 'Approval Status'
        ];
    }

I got the above DataTables warning

**Comment by yajra** [comment]
@Fionajeremychik Use an array to set the attributes.

```php
['data' => 'status', 'title' => 'Approval Status']
````

**Comment by Fionajeremychik** [comment]
Thanks. I got it.
1. How to add placeholder inside the Search
2. How to use export .csv or excel, how to add header title inside excel and how to print
public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->addAction(['width' => '120px', 'printable' => false])
            ->parameters([
                'dom'       => 'Bfrtip',
                'stateSave' => true,
                'order'     => [[0, 'desc']],
                'buttons'   => [
                    ['extend' => 'export', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'print', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'reload', 'className' => 'btn btn-default btn-sm no-corner',],
                ],
            ]);
    }

**Comment by Fionajeremychik** [comment]
Hi Arjay,

Thank for your help.

[image: Screenshot 2020-07-07 at 9.08.52 PM.png]
1. How to add placeholder inside the Search field
2. How to add header title inside Excel
    How to disable to export pdf
    How to print

**Comment by Skintillion** [comment]
Try to read the documentation a bit. You can't rely on us to answer every
basic question without trying yourself.

**Comment by Fionajeremychik** [comment]
Hi Arjay,

Can you tell me where I can find the document? Thanks
