### ISSUE TITLE
Issue with timestamps & datetimes format (on the latest version of this package?)

### ISSUE THREAD

**Issue by PeraMika** [yajra/laravel-datatables#2640]
### Summary of problem or feature request

Timestamps are displayed with milliseconds. For example I have:

```php
$users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

        return Datatables::of($users)
            ->make(true);
```
and `created_at` is displayed like this: 

```
2018-06-19T23:04:50.000000Z
```

However, if I just add this:

```php
            ->editColumn('created_at', function ($user) {
                return $user->created_at; // no formatting, just returned $user->created_at; 
            })
```
Then it will be displayed like this:
```
2018-06-19 23:04:50
```
So I didn't format or do anything with `created_at`, I just returned `$user->created_at` and in that case it's shown as expected.

Also, in DB in `users` table `created_at` values are like this: `2018-06-19 23:04:50`.
Finally, I already have `created_at` in `protected $dates` in `User.php` model.

This is probably a bug because it didn't exist before I upgraded to the latest version of Laravel and yajra/laravel-datatables package.

- Operating System: Windows 10
- PHP Version: 7.3.11
- Laravel Version: 8.42.0
- Laravel-Datatables Version: **9.18.0**

**Comment by yajra** [comment]
This is the new behavior of Laravel Framework when using `toArray()` and not the package as far as I remember.

Also, if I recall correctly, using editColumn will trigger the internal formatter of the package for date which the reason for the output.

**Comment by yajra** [comment]
This is how I handle dates on Laravel 8 if it helps.


```php
namespace App\DataTables\Formatters;

use DateTime;
use Yajra\DataTables\Contracts\Formatter;

class DateFormatter implements Formatter
{
    /**
     * @var string
     */
    public $format;

    public function __construct($format = 'Y-m-d h:i a')
    {
        $this->format = $format;
    }

    public function format($value, $row)
    {
        if ($value instanceof DateTime) {
            return $value->format($this->format);
        }

        return $value ? carbon($value)->format($this->format) : '';
    }
}
```

```php
    public function dataTable($query)
    {
        return datatables()
            ->eloquent($query)
            ->formatColumn(['created_at', 'updated_at'], DateFormatter::class)
...
```
