### ISSUE TITLE
utf8_encode() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by artzavod** [yajra/laravel-datatables#2641]
Hello! I have some Laravel API method:

    public function getAllTurnovers(Position $position)
    {

        $dateTo         = new \DateTime();
        $dateTo->setTime(23,59, 59);

        $dateFrom       = clone $dateTo; $dateFrom->modify('-1 year');
        $dateFrom->setTime(0,0, 0);

        //start period subquery
        $start_period = Position::select([
                                            'positions.product_id',
                                            DB::raw("sum(if(`".DB::getTablePrefix().(new Movement())->getTable()."`.type IN (".$this->joinArrayToStringForQuery(Config::get('settings.movement_increase_types'))."),`".DB::getTablePrefix().(new Position())->getTable()."`.quantity,0)) as start_period_increase"),
                                            DB::raw("sum(if(`".DB::getTablePrefix().(new Movement())->getTable()."`.type IN (".$this->joinArrayToStringForQuery(Config::get('settings.movement_decrease_types'))."),`".DB::getTablePrefix().(new Position())->getTable()."`.quantity,0)) as start_period_decrease")
                                        ])
            ->leftJoin('movements', 'positions.movement_id', '=', 'movements.id')
            ->where('movements.moment_at', '<=', $dateFrom)
            ->where('movements.applicable', true)
            ->groupBy('positions.product_id');

        //end period subquery
        $end_period = Position::select([
                                             'positions.product_id',
                                             DB::raw("sum(if(`".DB::getTablePrefix().(new Movement())->getTable()."`.type IN (".$this->joinArrayToStringForQuery(Config::get('settings.movement_increase_types'))."),`".DB::getTablePrefix().(new Position())->getTable()."`.quantity,0)) as end_period_increase"),
                                             DB::raw("sum(if(`".DB::getTablePrefix().(new Movement())->getTable()."`.type IN (".$this->joinArrayToStringForQuery(Config::get('settings.movement_decrease_types'))."),`".DB::getTablePrefix().(new Position())->getTable()."`.quantity,0)) as end_period_decrease")
                                         ])
            ->leftJoin('movements', 'positions.movement_id', '=', 'movements.id')
            ->where('movements.moment_at', '<=', $dateTo)
            ->where('movements.applicable', true)
            ->groupBy('positions.product_id');

        //main query
        $query = Product::select([
                                    'products.id',
                                    'products.ms_id',
                                    'products.code',
                                    'products.external_code',
                                    'products.title',
                                    'start_period.start_period_increase',
                                    'start_period.start_period_decrease',
                                    'end_period.end_period_increase',
                                    'end_period.end_period_decrease'
        ->joinSub($start_period, 'start_period', function ($join) {
            $join->on('products.id', '=', 'start_period.product_id');
        })
        ->joinSub($end_period, 'end_period', function ($join) {
            $join->on('products.id', '=', 'end_period.product_id');
        });

        return datatables($query)->toJson();
    }

This is main query with too subqueries. And after execute this method, datatable exeption was thrown.

vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php

    protected function showDebugger(array $output)
    {
        $query_log = $this->connection->getQueryLog();
        array_walk_recursive($query_log, function (&$item) {
                $item = utf8_encode($item);
        });

After i make some fixes, all working good:

    protected function showDebugger(array $output)
    {
        $query_log = $this->connection->getQueryLog();
        array_walk_recursive($query_log, function (&$item) {
            if (is_string($item)) {
                $item = utf8_encode($item);
            }
        });

**Comment by yajra** [comment]
Thank you for reporting, would you like to send a PR for the fix you proposed?

**Comment by artzavod** [comment]
Ок, I will do )

**Comment by artzavod** [comment]
PR created
