### ISSUE TITLE
Multiple select - mjoin

### ISSUE THREAD

**Issue by tekvsakdan** [yajra/laravel-datatables#2643]
Is it possible to implement multiple selection with mjoin as example here?

[DataTables example - Multiple selection](https://editor.datatables.net/examples/datatables/mJoin.html)

**Comment by yajra** [comment]
Yes, possible but needs several things to work. Here is an example of multiple selection using jsTree.

![image](https://user-images.githubusercontent.com/2687997/120825611-231b0a00-c58c-11eb-8712-c0f8844c3136.png)

## Html Builder

```php
    public function html()
    {
        return $this->builder()
            ->setTableId('roles-table')
            ->columns($this->getColumns())
            ->selectStyleMulti()
            ->orderBy(2)
            ->ajaxWithFilters()
            ->buttons([
                CreateButton::makeIfCan('manage-roles'),
                EditButton::makeIfCan('manage-roles'),
                RemoveButton::makeIfCan('manage-roles'),
                CsvButton::make(),
                ReloadButton::make(),
            ])
            ->editors([
                Editor::make()
                    ->fields([
                        Fields\Field::make('name'),
                        Fields\Field::make('slug')
                            ->fieldInfo('System role slug cannot be altered.')
                            ->multiEditable(false),
                        YesNoField::make('system')
                            ->fieldInfo('System role cannot be deleted or slug to be modified.')
                            ->default(0),
                        JSTreeField::make('permissions[].id')
                            ->label('Permissions')
                            ->options(Permission::jsTree()),
                    ]),
            ]);
    }
```

**Comment by yajra** [comment]
@tekvsakdan  I just realized that `datatable` is a new field type for Editor 2. Will try to give this a shot when I got the chance. I currently implement a custom field type to achieve this case. 

Anyways, theoretically, the new field type should work out of the box.

**Comment by vanthao03596** [comment]
> @tekvsakdan  I just realized that `datatable` is a new field type for Editor 2. Will try to give this a shot when I got the chance. I currently implement a custom field type to achieve this case. 
> 
> 
> 
> Anyways, theoretically, the new field type should work out of the box.

Jstree look good, can you share in gist ?

**Comment by tekvsakdan** [comment]
If possible I also need an example how to create query for controller for data and how to build store function for one-to-many joins. I don't know how to do that in Laravel.

https://editor.datatables.net/manual/php/mjoin

**Comment by yajra** [comment]
@vanthao03596 here is the [gist](https://gist.github.com/yajra/a383bf41ec7eb7e673cf9b7794020d51), hope it helps.

**Comment by vanthao03596** [comment]
> @vanthao03596 here is the [gist](https://gist.github.com/yajra/a383bf41ec7eb7e673cf9b7794020d51), hope it helps.

Wow, it look amazing. Thanks for share!
