### ISSUE TITLE
yajra sorting issue

### ISSUE THREAD

**Issue by u-stack** [yajra/laravel-datatables#2645]
### Summary of problem or feature request

i  am removing a sorting from a specific column like this
 columnDefs: [{
            "targets": [0], 
            "orderable": false, 
            }, ],
its working but it also shows sorting arrows for first time and when i refresh the page they vanished how to resolve i am workin on laravel version 8

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by mattpramschufer** [comment]
@u-stack I may be incorrect here, but I believe that if you do not specifically set an initial column to be ordered by, DataTables will use the first column.  If you disabled sorting on that column, you will still see an initial `Down Arrow` until you sort by another column.  So I think the solution is to simply state what column you want to be order by default.

**Comment by yajra** [comment]
I think what you need is the orders option. Try setting `orders: []` to remove the default sorting.
