### ISSUE TITLE
Eloquent Datatable with Eager Loading propertyName problem

### ISSUE THREAD

**Issue by orhanerday** [yajra/laravel-datatables#2650]
### Summary of problem or feature request

I have a relationship get the null value I get this error
> DataTables warning: table id=table - Requested unknown parameter 'post.title' for row 0, column 5. For more information about this error, please see http://datatables.net/tn/4
**For example;**
`
User::find(1)->post->title; // null
`
I need to handle null property names in datatable.

### Code snippet of problem

```php
$data = User::with('post');

return Datatables::of($data)
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
```
```javascript
 $('#table').DataTable({
    processing: true,
    serverSide: true,
    ajax: '{!! route('asansor.index') !!}',
    columns: [
        {data: 'id', name: 'id'},
        {data: 'name', name: 'name'},
        {data: 'post.title', name: 'post.title'},
    ]
});

```

### System details

- Operating System; EditionWindows 10 Home Version 20H2
- PHP Version; 7.3.21
- Laravel Version; Laravel Framework 8.47.0
- Laravel-Datatables Version; 1.10.25

**Comment by yajra** [comment]
Try this:

```php
$data = User::with('post')->select('users.*');

.... 

class User extends Model 
{
  public function post()
  {
    return $this->belongsTo(Post::class)->withDefault();
  }
}
```
