### ISSUE TITLE
Search changed column names with conditions

### ISSUE THREAD

**Issue by udaraz** [yajra/laravel-datatables#2651]
### Summary of problem or feature request

I have a mysql query that contains few conditioned columns such as `FORMAT((vehi.mb - vehi.start_price),2) AS sp_minus_mb `when I try to search it shows` vehi.sp_minus_mb` column not found. In the datatable I also try like below in js and it's not working

### Code snippet of problem

`columns:[    
 {data: 'sp_minus_mb', name: 'sp_minus_mb'},
]`

`columns:[    
 {data: 'sp_minus_mb', name: 'vehicles.mb - vehicles.start_price'},
]`

### System details

- Operating System - ubuntu
- PHP Version - 7.4
- Laravel Version - 8.0
- Laravel-Datatables Version - 9.14

**Comment by yajra** [comment]
Try using filterColumn https://yajrabox.com/docs/laravel-datatables/master/filter-column
