### ISSUE TITLE
Laravel Session Randomly Drops

### ISSUE THREAD

**Issue by johnwswar** [yajra/laravel-datatables#2654]
Laravel Controller has  basic following code to check if the fiscal_year key exits before running a query based off a fiscal year and then creating the row to view.  However, when checking to see if it has session key value set_fiscal_year, it randomly display null either on load or when performing a server side search.  This seems to be occurring   when using DataTables.  Thank you!

//Previous Controller sets the session set_fiscal_year.  
\Session::put('set_fiscal_year ', $fiscal_year_max);
                      	\Session::save();
                      	\Session::keep();

//*  End of Controller Setting Session key value *//

//Controller displaying DataTables Data
//Here is where Session key randomly display null.  
if(Session::has('set_fiscal_year')) {
                	$fiscal_year =  Session::get('set_fiscal_year'); 
            	}

$fiscal_year_abbr = Str::substr($fiscal_year, 2);  

//Run a query
$data = DB::table('test_data')
        	->get();
 
 
        	$ifUpdateExists = DB::table( 'user_role)->where('granted_role','UPDATE_ROLE')->exists();
 
        	return Datatables::of($data)
                	->addIndexColumn()
 
                	->addColumn('fiscal_year', function($row) use ($fiscal_year)	{
 
                    	return $fiscal_year;
                        	})
                	->addColumn('fiscal_year_abbr', function($row) use ($fiscal_year_abbr)	{
 
                    	return $fiscal_year_abbr;
                        	})
               	 
                	->addColumn('action', function($row) use ($ifUpdateExists)  {
 
                      	if($ifUpdateExists){
                    	 
                       	$btn = ' <a href="#" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-sm btn-outline-info edit nowrap" title="Delete Record">  <img height="20px;" src="/image/edit.png">
                         	Delete </a>';
                       	}
 
                       	else {
                        	$btn = '';
                       	}
                      	 
                   	 
    
                        	return $btn;
                	})
                	->rawColumns(['action'])               	 
                	->make(true);
    	}
 	 
    	return view(‘mainview’);
	}

**Comment by yajra** [comment]
Are you using `artisan:serve`? If yes, there is a known weird issue with the package when using it. Can't dig further what causes this but is definitely a dev environment issue. Use valet, apache, homestead. Haven't tried sail yet.

**Comment by farsh1d** [comment]
i dont know but i suggest for you

`return $ifUpdateExists ? 
' <a href="#" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-sm btn-outline-info edit nowrap" title="Delete Record">  <img height="20px;" src="/image/edit.png">
Delete </a>' 
: '';`

vs

`if($ifUpdateExists){
            
        $btn = ' <a href="#" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-sm btn-outline-info edit nowrap" title="Delete Record">  <img height="20px;" src="/image/edit.png">
            Delete </a>';
        }

        else {
            $btn = '';
        }
            
        

            return $btn;`
