### ISSUE TITLE
Error when i try to search with datatables as service

### ISSUE THREAD

**Issue by 8lbiasian** [yajra/laravel-datatables#266]
strange error when i try to search 

DataTables warning: table id=dataTableBuilder - Ajax error. For more information about this error, please see http://datatables.net/tn/7

this is my DataTable class 

    public function ajax()
    {
        $students = $this->datatables
            ->eloquent($this->query())->addColumn('Edit', function ($student) {
                return '<a href="'.url('admin/students\/').$student->id.'/edit" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
            }) ->make(true);
        return $students;

    }

    public function html()
    {
        return $this->builder()
            ->columns([
                [
                    "name" => "id",
                    "title" => "id",
                    "data" => "id"
                ],
                [
                    "name" => "Name",
                    "title" => "Name",
                    "data" => "Name"
                ],
                [
                    "name" => "Register_Number",
                    "title" => "Register Number",
                    "data" => "Register_Number"
                ],
                [
                    "name" => "Trafic_Number",
                    "title" => "Traffic Number",
                    "data" => "Trafic_Number"
                ],
                [
                    "name" => "Edit",
                    "title" => "Edit",
                    "data" => "Edit"
                ],
            ])
            ->parameters([
            ]);
    }

**Comment by yajra** [comment]
Can you please dump the ajax error displayed on console? Anyways, set you `Edit` field as not oraderable and searchable.
```php
[
  "name" => "Edit",
  "title" => "Edit",
  "data" => "Edit",
  searchable: false,
  orderable: false
],
```

**Comment by 8lbiasian** [comment]
thanks now its work fine
