### ISSUE TITLE
How to make a raw column sortable?

### ISSUE THREAD

**Issue by Ryan-Minor** [yajra/laravel-datatables#2663]
I have a column for "status" of a record that needs to display a certain colored badge depending on that status value. Currently I am rendering that column by using the addColumn() api along with including it in the rawColumns() array. However, I cannot sort on this column. How can I accomplish this?

Here is my controller code:
```
public function index(Request $request)
{
    if ($request->ajax()) {
        $audios = $this->audio
            ->with('client')
            ->select('audios.*');

        return Datatables::of($audios)
	    ->addIndexColumn()
            ->addColumn('is_ftp', function($row) {
                return ($row->is_ftp) ? 'Yes' : 'No';
            })
            ->addColumn('status', function($row) {
                return view('admin.audios.partials.statuses', compact('row'))->render();
            })
            ->addColumn('action', function($row) {
                return view('admin.audios.partials.actions', compact('row'))->render();
            })
            ->rawColumns(['status', 'action'])
	    ->make(true);
    }
    return view('admin.audios.index');
}
```

Here is the code for my partial that is rendered by the raw column:
```
@if($row->status == 'uploaded')
    <span class="badge badge-danger">Uploaded</span>
@endif
@if($row->status == 'claimed')
    <span class="badge badge-warning">Claimed</span>
@endif
@if($row->status == 'complete')
    <span class="badge badge-success">Complete</span>
@endif
```

Here is my view code:
````
$(function () {
    let table = $('#audiosTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin.audios.index') }}",
        columns: [
            {data: 'number', name: 'number'},
            {data: 'doctor_name', name: 'doctor_name'},
            {data: 'filename', name: 'filename'},
            {data: 'is_ftp', name: 'is_ftp'},
            {data: 'created_at', name: 'created_at'},
            {data: 'status', name: 'status', orderable: true},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],
        order: [
            [0, 'desc']
        ]
    });
});
````

**Comment by yajra** [comment]
Use editColumn instead of addColumn.

```php
->editColumn('status', function($row) {
  return view('admin.audios.partials.statuses', compact('row'))->render();
})
```

**Comment by benjaminv** [comment]
> Use editColumn instead of addColumn.
> 
> ```
> ->editColumn('status', function($row) {
>   return view('admin.audios.partials.statuses', compact('row'))->render();
> })
> ```

Hi @yajra thanks for point this out. But if I had query side function closure, it resulted un-searchable column in sql. 
```ruby
if ($request->ajax()){
            return Datatables::of($sellers)
                ->addIndexColumn()
                ->editColumn('item_count_in_query', function (Seller $seller) use ($items){ return $items->where('seller_id', $seller->sellerID)->count(); })
                ->make(true);
            }
```
![image](https://user-images.githubusercontent.com/299269/126734840-aae1b187-967d-4d8e-9648-255d0924a270.png)

I really dont want to change from Query Builder to Collection as there are half a million rows of data. 

Any comment will be appreciated.

**Comment by yajra** [comment]
Some guidelines I guess to help you on what API to use.

1. Use [editColumn](https://yajrabox.com/docs/laravel-datatables/master/edit-column) if the column exists in the DB and you want to add some decoration and enable sort/search.
2. Use [addColumn](https://yajrabox.com/docs/laravel-datatables/master/add-column) for computed columns. This will disable sort/search since it's not part of the DB and query will most like fail like in your case.
3. If you want added column to be searchable, use [filterColumn](https://yajrabox.com/docs/laravel-datatables/master/filter-column) and write a custom query to achieve what you need in SQL level.
4. For sorting, use [orderColumn](https://yajrabox.com/docs/laravel-datatables/master/order-column).
5. When using `withCount(relation)`, ordering may work by default but not searching. You can toggle this feature via js or the Column builder.

```php
Column::make('relation_count')->searchable(false),

// js

columns: [
  {data: 'relation_count', searchable: false}
  ...
]
```

**Comment by benjaminv** [comment]
@yajra Thanks for clarification with suggestions. It does suggest to me this is a dead end. All of my added columns are calculated numbers (via closure function calling relations, like how many items sold by each seller in the searched category with certain "keywords") NOT something in the DB.
1. `editColumn` triggers the sort and leads to sql error,
2. `addColumn` sit in the case but disables sort (all numbers doesn't really matter the search)
3. Not in my case
4. `orderColumn` my understanding is this does the initial sorting not column sort triggered at client's end. Or am I misunderstanding the method?
5. unfortunately more complex than only `count`

**Comment by js-limitless-factor** [comment]
Hi @yajra , 

How can I sort new column data that are having manual calculations? 
I keep getting the Unknown column in the 'order clause'? 

// php
->addColumn('total_amount',  function($row){
	return $row->value1 / $row->value2
})
->orderColumn('total_amount', function ($query) {
     $query->orderBy('total_amount');
 });

// js
{data: 'total_amount', name: 'total_amount'}

Is there anything am doing wrong?

Please advice.

Thank you.

**Comment by 43213110446** [comment]
is there no solution so far?

**Comment by yajra** [comment]
@js-limitless-factor I think you just need to do the calculation at SQL level and sorting would work:

```php
->addSelectRaw('value1 / value2 as total_amount`)
````
