### ISSUE TITLE
How not to include records based on condition

### ISSUE THREAD

**Issue by VinceSanityyy** [yajra/laravel-datatables#2668]
### Summary of problem or feature request

How can i exclude data based on my condition on `addColumn` function?

### Code snippet of problem

What i tried is like this. But it will include records that > 0
```
                ->addColumn('total', function ($row) {
                    $arr = array(abs($row->fba_fee_count),abs($row->referral_fee_count));
                    if($arr > 0){
                        return array_sum($arr);
                    }
```
### System details

- Operating System = Windows
- PHP Version = 7.3
- Laravel Version = 6x
- Laravel-Datatables Version = 9.6^

**Comment by yajra** [comment]
Do you want to hide the data or whole column?

If you want to hide the value the addColumn can do the trick. 

If you want to hide the column, then add a condition on your column scripts. If you're using the html builder, you can do this:

```php
Column::computed('total')->hidden($condition);
```

**Comment by VinceSanityyy** [comment]
thanks
