### ISSUE TITLE
Question : Is there any planning for integration with Mongodb?

### ISSUE THREAD

**Issue by atapatel** [yajra/laravel-datatables#267]
Question : Is there any planning for integration with Mongodb?

**Comment by yajra** [comment]
I think the package already works on Mongodb but I don't/haven't personally used it so I am not really sure it works properly. See this issue for ref: https://github.com/yajra/laravel-datatables/issues/214

In general, if there is a proper DB Driver for Laravel, then the package should work most of the time. If not, then the package is open for PRs ^_^. I may not have much time though atm to further dig on this but will surely try it out sometime in the future.

**Comment by atapatel** [comment]
@yajra thanks for paying attention towards my question. but don't you thin so this operation will be too much heavy if there is too much data in mongodb Collection?

**Comment by yajra** [comment]
Yes, that is the downside of using a Collection. I'm wondering, does mongoDB queries differ much on other SQLs? The package depends on the Query Builder of Laravel DB package. As long as the DB package follows the same convention that Laravel has, querying should not be an issue? I have written an [Oracle DB driver](https://github.com/yajra/laravel-oci8) for Laravel and this package works on Oracle too. So I think the mongoDB driver should do the same too?

**Comment by yajra** [comment]
I guess the integration for MongoDB will depend on the db driver itself. If it works like how the standard laravel db driver works, then there should be no problem in implementing this. However, if it differs, then it's a limitation that will fall under `Collection` engine.

Maybe in the future, we can create a dedicated engine for MongoDB but not atm. Thanks!

**Comment by ahmadazimi** [comment]
I faced a problem in this case:

When using mongodb driver as a connection, when you pass your query builder to the datatables instead of a collection , then the following error occurred:

```
FatalErrorException in Yajra\Datatables\Engines\QueryBuilderEngine.php line 121:
Call to a member function wrap() on null
```

**Comment by c0h1b4** [comment]
I've got the exact same error.

FatalThrowableError (E_ERROR)
Call to a member function wrap() on null

/vendor/yajra/laravel-datatables-oracle/src/Engines/QueryBuilderEngine.php

    protected function wrap($column)
    {
        return $this->connection->getQueryGrammar()->wrap($column);
    }
