### ISSUE TITLE
i have an issue while installing the package using composer require yajra/laravel-datatables

### ISSUE THREAD

**Issue by Karimttarek** [yajra/laravel-datatables#2677]
### Summary of problem or feature request

iam facing problem while installing Yajra Datatable by using this Command " composer require yajra/laravel-datatables"on git i tried composer install and composer update

### Code snippet of problem

Running composer update yajra/laravel-datatables
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - maatwebsite/excel[3.1.28, ..., 3.1.30] require phpoffice/phpspreadsheet 1.16.* -> satisfiable by phpoffice/phpspreadsheet[1.16.0].
    - maatwebsite/excel[3.1.31, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0].
    - maatwebsite/excel 3.1.27 requires phpoffice/phpspreadsheet ^1.16 -> satisfiable by phpoffice/phpspreadsheet[1.16.0, 1.17.0, 1.17.1, 1.18.0].
    - maatwebsite/excel 3.1.26 requires phpoffice/phpspreadsheet ^1.15 -> satisfiable by phpoffice/phpspreadsheet[1.15.0, ..., 1.18.0].
    - yajra/laravel-datatables[v1.2.0, ..., v1.4.0] require yajra/laravel-datatables-oracle 8.* -> satisfiable by yajra/laravel-datatables-oracle[v8.0.0, ..., v8.13.7].
    - phpoffice/phpspreadsheet[1.15.0, ..., 1.18.0] require ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - maatwebsite/excel[3.0.1, ..., 3.1.25] require php ^7.0 -> your php version (8.0.8) does not satisfy that requirement.
    - maatwebsite/excel[3.0.0-alpha, ..., 3.0.0] require php ^7.1 -> your php version (8.0.8) does not satisfy that requirement.
    - yajra/laravel-datatables-buttons v4.0.0 requires illuminate/console 5.5.*|5.6.* -> found illuminate/console[v5.5.0, ..., 5.6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - yajra/laravel-datatables-buttons[v4.1.0, ..., v4.6.0] require illuminate/console ^5.5 -> found illuminate/console[v5.5.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - yajra/laravel-datatables-buttons[v4.7.0, ..., v4.8.0] require illuminate/console ^5.5|^6.0 -> found illuminate/console[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - yajra/laravel-datatables-buttons[v4.9.0, ..., v4.9.3] require illuminate/console ^5.5|^6|^7 -> found illuminate/console[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - yajra/laravel-datatables-oracle[8.0.x-dev, ..., v8.13.7] require illuminate/database 5.4.*|5.5.*|5.6.*|5.7.* -> found illuminate/database[v5.4.0, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - yajra/laravel-datatables-oracle[v8.0.0, ..., v8.3.3] require illuminate/database 5.4.*|5.5.* -> found illuminate/database[v5.4.0, ..., 5.5.x-dev] but these were not loaded, likely because it conflicts with another require.
    - yajra/laravel-datatables-oracle[v8.4.0, ..., v8.7.1] require illuminate/database 5.4.*|5.5.*|5.6.* -> found illuminate/database[v5.4.0, ..., 5.6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - yajra/laravel-datatables v1.5.0 requires yajra/laravel-datatables-buttons 4.* -> satisfiable by yajra/laravel-datatables-buttons[v4.0.0, ..., v4.13.1].
    - yajra/laravel-datatables-buttons 4.0.x-dev is an alias of yajra/laravel-datatables-buttons dev-master and thus requires it to be installed too.
    - yajra/laravel-datatables-buttons[dev-master, 4.0.x-dev, ..., v4.13.1] require maatwebsite/excel ^3.0 -> satisfiable by maatwebsite/excel[3.0.0-alpha, ..., 3.1.x-dev].
    - Root composer.json requires yajra/laravel-datatables ^1.2 -> satisfiable by yajra/laravel-datatables[v1.2.0, v1.3.0, v1.4.0, v1.5.0].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### System details

- windows 10 , ubuntu
- PHP 8
- Laravel 8
- Laravel-Datatables 1.5

**Comment by Karimttarek** [comment]
I used php 7.4 and it worked

**Comment by victorelec14** [comment]
Please close the issue. :)
