### ISSUE TITLE
Manual using Scopes with DataTables as a Service

### ISSUE THREAD

**Issue by ZAZmaster** [yajra/laravel-datatables#268]
Could you write a few examples of Scope for a full understanding of this problem?
I need to make the ability to select only certain values, for example:
```php
return $query->where('organization_id', $id);
```
But from the above example:
```php
public function index(Company $company, UsersDataTable $dataTable)
{
    return $dataTable->addScope(new CompanyOwnedScope($company))
        ->render('admin.companies.users.index', compact('company'));
}
```
I can not understand how to do it.

**Comment by yajra** [comment]
See this example scope for ref. I can't make a documentation atm but this example should give you an insight on how to use it.
```php
<?php

namespace App\DataTables\Scopes;

use App\Models\Company;
use Yajra\Datatables\Contracts\DataTableScopeContract;

class CompanyOwnedScope implements DataTableScopeContract
{
    /**
     * @var \App\Models\Company
     */
    protected $company;

    /**
     * @var string
     */
    protected $relation;

    /**
     * @param \App\Models\Company $company
     * @param string $relation
     */
    public function __construct(Company $company, $relation = 'companies.id')
    {
        $this->company  = $company;
        $this->relation = $relation;
    }

    /**
     * Apply a query scope.
     *
     * @param \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder $query
     * @return mixed
     */
    public function apply($query)
    {
        return $query->where($this->relation, $this->company->id);
    }
}
```

**Comment by ZAZmaster** [comment]
Thank you!

**Comment by yajra** [comment]
Welcome!

**Comment by bremg** [comment]
Scopes are never applied after initial initialization of the table. 

Bug?


	public function index()
    {
        return view('modules.user.index')->with([
	        'dataTable' => $this->usersDataTable->addScope( new UserFilterScope( $this->request->all() ) )->render('layouts.elements.datatable')->getData(),
	        'whitelabelGroups' => $this->whitelabelGroupRepository->getAll(),
	        'selectedWhitelabelGroup' => null,
			'tagGroups' => $this->tagGroupRepository->getAll(),
	        'selectedTagGroups' => []
        ]);
    }

	public function tableIndex(UsersDataTable $userDataTable)
	{
		return $userDataTable->addScope( new UserFilterScope($this->request->all()) )->render('layouts.elements.datatable');
	}






<?php

namespace App\DataTables\Scopes;

use Illuminate\Support\Facades\Log;
use Yajra\DataTables\Contracts\DataTableScope;

class UserFilterScope implements DataTableScope
{
	protected $whitelabelGroupId = null;
	protected $tagGroups = null;

	public function __construct(array $filters)
	{
		Log::debug('1 this is called');

		if(isset($filters['whitelabel_group_id'])) {
			Log::debug('2 this is sometimes called');
			$this->whitelabelGroupId = $filters['whitelabel_group_id'];
		}
	}

	public function apply($query)
	{
		Log::debug('this is only run when first loading not on ajax');
		Log::debug('group', [$this->whitelabelGroupId]);

		if(!is_null($this->whitelabelGroupId)){
			$query = $query->where('whitelabel_group_id', $this->whitelabelGroupId);
		}

		return $query;
	}
}

**Comment by bremg** [comment]
Could this be because i'm using minified ajax? Could you please write some documentation, this is all very unclear..
