### ISSUE TITLE
Laravel Yajra is not accepting post/get request on query

### ISSUE THREAD

**Issue by rbhsh** [yajra/laravel-datatables#2683]
I am using Yajra data table. It's working fine until I decide to filter the result. For example: This is how my query looks like for Yajra (in controller)

```if ($request->ajax()) {

        $data = product::get(); //SQL QUERY

        return Datatables::of($data)
                ->addIndexColumn()                    
                ->addColumn('action', function($row){
 
                    $btn = '<a href="'.url('product/{'.base64_encode($row->id).'}').'" class="edit" target="_blank"><i class="fa fa-eye" aria-hidden="true"></i></a> <a href="'.url('/').'/export?product_id='.$row->id.'&productname='.$row->product_name.'"><i class="fa fa-download" aria-hidden="true"></i></a>';

                        return $btn;
                })
                ->rawColumns(['image','discount','dt','action'])
                ->make(true);
    }
```
As you can see, this is how I defined sql query and it is working fine.

```
$data = product::get();
```
But later I decide to filter the result. I don't want to show all result but instead some result depending on the where condition with help of POST function.

So I replaced the previous query line with this one

```
$data = product::select('*');
        $data = $data->where('vendor', $request->vendor_list);
       $data = $data->get();
```

To check if $request->vendor_list really has some value or not, I tried to print $request->vendor_list and value is getting printed. SO $request->vendor_list has value inside.

And when I try to manually add value instead of POST function in where condition then it started to work. Like this

```$data = product::select('*');
$data = $data->where('vendor', 'vendor_name'); //MANUALLY typed value
$data = $data->get();
```

So not getting idea why yajra is not accepting value in where condition if I get value from GET or POST (both tried)?

**Comment by rbhsh** [comment]
Anyone here.............. who can help.....!!?? Pretty please :(

**Comment by yajra** [comment]
Get / Post? DataTables response would depend on your routes. Use `Route::any()` if you want to support both.

```php
        $data = product::query(); // Use query, get() is collection.

        return Datatables::of($data)
                ->addIndexColumn()                    
                ->addColumn('action', function($row){
 
                    $btn = '<a href="'.url('product/{'.base64_encode($row->id).'}').'" class="edit" target="_blank"><i class="fa fa-eye" aria-hidden="true"></i></a> <a href="'.url('/').'/export?product_id='.$row->id.'&productname='.$row->product_name.'"><i class="fa fa-download" aria-hidden="true"></i></a>';

                        return $btn;
                })
                ->rawColumns(['image','discount','dt','action'])
                ->make(true);

```

**Comment by rbhsh** [comment]
No, what I mean is different. I am on Laravel. And I have one form with some fields. When form submit, page refreshes and give data (from form fields). I am fetching that data using "$_GET['field_name']" (in laravel $request->field_name). And m using that GET method in where clause like this "where('category', $_GET['field_name'])". But yajra is not showing any result like this. HOWEVER if I manually type value in where clause like this "where('category', 'watches')" then it gives fine result. THIS IS THE ISSUE THAT Why it is taking manual value in where clause but not from $_GET[] Or $_POST[] method?

**Comment by rbhsh** [comment]
No, I think you didn't ask properly my quesion. What I want is, when I submit a form (GET method used in form) then all fields value of form started to appear on url in form of query string. Now I am fetching that value using "$_GET['form_field_name']" method and using it in where clause like this

`
 $data = product::select('*');
  $data = $data->where('vendor', $request->vendor);
  $data = $data->get();
`
BUt it don't show any result like this. 

HOWEVER if I manually type value instead of using query method (as shown bellow) then all result started to show up without any issue. As by following code

`
 $data = product::select('*');
  $data = $data->where('vendor','Elmo'); //Here I am manually typed value instead of query method
  $data = $data->query();
`

This way it is working fine. Question is how I can use query method ($request->field_name) in where clause?

And yes, I tried to replace query() with get() but it give me ajax error.

**Comment by rbhsh** [comment]
Hi greets, 
By following your suggestion, I tried this

```
 if ($request->ajax()) {

       $data  = product::query(); //Used query() here instead of get()
        if ($request->vendor_list) {
            $data ->where('vendor', $request->vendor_list);
        }
```

But it didn't work
Then I remove `if` condition and  did this

```
 if ($request->ajax()) {

       $data  = product::query(); //Used query() here instead of get()
       $data ->where('vendor', $request->vendor_list);
```

It still didn't work. 
AT LAST I tried `where` calause manually typed value instead of query method like this

```
 if ($request->ajax()) {

       $data  = product::query(); //Used query() here instead of get()
       $data ->where('vendor', 'Elmo');
```
Then it started to show correct data. So Yajra is working fine with where condition only if we manually typed value. If we use `$request->feild_name` then it don't show any data.

Can you please show any solution for it :)

**Comment by yajra** [comment]
Then I suspect that you are not sending the data properly to server. Inspect your ajax request and double check. See official docs https://datatables.net/examples/server_side/custom_vars.html for more info.

**Comment by rbhsh** [comment]
Thanks for points. I don't know where I missed. My script seems fine as shown in docs. Here is the script

```
<script type="text/javascript">
    $(document).ready(function() {
    $('.data-table').DataTable( {
          processing: true,
          serverSide: true,
          ajax: "{{ route('products.productList') }}",
          columns: [            
{data: 'image', name: 'image'},
{data: 'vendor', name: 'vendor'},
{data: 'product_name', name: 'product_name'},
{data: 'vendor_model', name: 'vendor_model'},
{data: 'product_code', name: 'product_code'},
{data: 'category', name: 'category'},
{data: 'product_price', name: 'product_price'},
{data: 'product_unit', name: 'product_unit', orderable: false, searchable: false},
{data: 'discount', name: 'discount'},
{data: 'dt', name: 'dt'},
{data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });
      
    });
  </script>
```
Here is the URLs
```
<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" defer></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
```

And controller function

```
function productList(Request $request){
        if ($request->ajax()) {

       $data  = product::query();
        //if ($request->vendor_list) {
            $data ->where('vendor', request($request->vendor_list));
        //}

            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
     
                        $btn = '<a href="'.url('product/{'.base64_encode($row->id).'}').'" class="edit" target="_blank"><i class="fa fa-eye" aria-hidden="true"></i></a> <a href="'.url('/').'/export?product_id='.$row->id.'&productname='.$row->product_name.'"><i class="fa fa-download" aria-hidden="true"></i></a>';
    
                            return $btn;
                    })
                    ->rawColumns(['image','discount','dt','action'])
                    ->make(true);
        }

        return view('products');
    }
```

And route

```
Route::match(['get', 'post'], 'products', [dashboardController::class, 'productList'])->name('products.productList');
```
I am using query string form url, same which we get in url after submitting form using `GET` method. example: `domain.com/page?vendor_list=anyname`

Can you please point out if there is any error, Sorry to bug you so much :(
