### ISSUE TITLE
dataTable - addColumn with sorting.

### ISSUE THREAD

**Issue by VeecotechBrandon** [yajra/laravel-datatables#2684]
### Summary of problem or feature request

dataTable - addColumn with sorting.

### Code snippet of problem

```
 public function dataTable($query)
    {
        $dataTable = new EloquentDataTable($query);
        $columns = array_column($this->getColumns(), 'data');
        $dataTable = $dataTable
            ->editColumn('name', function ($earning) {
                return getLinksColumnByRouteName([$earning], "restaurants.edit", 'id', 'name');
            })
            ->addColumn('total_orders', function ($earning) {

                $foodIds = $earning->foods->pluck('id')->all();
                $total_orders = FoodOrder::join("orders", "orders.id", "=", "order_id")
                    ->join("payments", "payments.id", "=", "orders.payment_id")
                    ->whereIn('food_id', $foodIds)
                    ->where('payments.status', "Paid")
                    ->whereBetween('payments.created_at', [$this->from_date, $this->to_date])
                    ->count();

                // $earning->total_orders = $total_orders;

                return $total_orders;
            })....

return $dataTable;
}

 protected function getColumns()
    {
        $columns = [
            [
                'data' => 'name',
                'title' => trans('lang.earning_restaurant_id'),

            ],
            [
                'data' => 'total_orders',
                'title' => trans('lang.earning_total_orders'),
                'searchable' => false,
            ],...

        return $columns;
}

 public function query(Restaurant $model)
    {
            return $model->newQuery()
                ->with("foods")
                ->select('restaurants.*');
     }
```

### System details

- Operating System = Windows 10
- PHP Version = 7.3.30
- Laravel Version = 5.8.38
- Laravel-Datatables Version = "yajra/laravel-datatables-oracle": "8.*|9.*"

**Comment by yajra** [comment]
FYI: addColumn disables search & sort by default since the package treat this as a computed column. It breaks the SQL most of the time if left enabled.

Try using this instead:

1. Use editColumn 
2. Set the column as searchable false

**Comment by yajra** [comment]
You can use [orderColumn](https://yajrabox.com/docs/laravel-datatables/master/order-column) and handle sorting via SQL level.

**Comment by VeecotechBrandon** [comment]
Which mean I have 5 new column, I need to add 5 editColumn (display data) and 5 orderColumn (specific the the column for sorting) ?

**Comment by yajra** [comment]
It depends on your requirements and setup. For example, you can use `withCount('relation')` and sorting will work out of the box but searching will not work. I suggest you do the total/count on the query level if possible.

**Comment by VeecotechBrandon** [comment]
What if I have multiple new columns not in the datatable like sum of something. I can do all in query level, can you give me a sample code? Or you have any suggestion?

**Comment by js-limitless-factor** [comment]
Hi @yajra , I facing this issue as well. 

I have opened, clicked columns in SQL, but I need to use addColumn for opened_rate and clicked_rate for percentage calculation. After I have added the 2 columns, I was unable to sort and search. 

As you mentioned above: addColumn disables search & sort by default. 

But, how can we use orderColumn as you suggested to display as a new column? 

Please advice. 

Thank you.

**Comment by yajra** [comment]
@js-limitless-factor  You can display the new column by setting the name key:

```
// php
->addColumn('opened_rate',  fn($x)...)
->orderColumn('opened_rate', fn($q, $dir) ...)

// js
{data: 'opened_rate', name: 'opened_rate'}
```

This snippet will allow ordering but searching is still disabled.

------

If computation was done on SQL level, sorting works w/o the need for addColumn:

```
// js
{data: 'opened_rate', name: 'opened_rate', searchable: false}
```

**Comment by js-limitless-factor** [comment]
thanks @yajra ! I got the idea now : )
