### ISSUE TITLE
Howto Coreui and yajra

### ISSUE THREAD

**Issue by Marthianfred** [yajra/laravel-datatables#2686]
can anybody showme on example server side CDataTable and Yajra server side..

i use Yajra on laravel service and vue coreui admin template.....

anybody can share one example.. ??? thx in advance

**Comment by Marthianfred** [comment]
anybody can help

**Comment by yajra** [comment]
CoreUI has a admin template that I used before as reference https://coreui.io/docs/integrations/laravel/. Were you able to give it a try? Not sure about the CDataTable that you were referring but you can just directly use http://datatables.net/ libraries,
