### ISSUE TITLE
invalid JSON response

### ISSUE THREAD

**Issue by afsharmahmoodian** [yajra/laravel-datatables#2694]
hi

I am using [InfyOmLabs-laravel-generator](https://github.com/InfyOmLabs/laravel-generator) for my project.

that helps me to generate my datatables and it using **yajra** !

but i have a problem : 

my code working on my local machine but when i put my project in the server, all my datatables encounter an error,  Invalid JSON response!

i checked my response, it is an html response -_- , but every thing working on local . help me.

You may use the markdown php code tags to format your paste:

thank you for your great package !

here is an example of my code : router + controller + dataTable

**in web.php**
`Route::resource('admins', 'AdminController');`

**here is example of my index action**

`class AdminController extends AppBaseController
{
    private $adminRepository;`

    public function __construct(AdminRepository $adminRepo)
    {
        $this->adminRepository = $adminRepo;
    }

    public function index(AdminDataTable $adminDataTable)
    {
        return $adminDataTable->render('admins.index');
    }
`}`

**and here is my dataTable**
(sorry for bad view i put my code in code Identifier but its not working...)

`<?php

namespace App\DataTables;

use App\Helpers\Helper;
use App\Models\Admin;
use App\Models\AdminRole;
use Yajra\DataTables\Services\DataTable;
use Yajra\DataTables\EloquentDataTable;

class AdminDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable($query)
    {
        $dataTable = new EloquentDataTable($query);
        $dataTable->editColumn('super_admin', function($data) {
            return $data->super_admin == 1 ? 'بلی' : 'خیر';
        });
        $dataTable->editColumn('role_id', function($data) {
            $role = AdminRole::find($data->role_id);
            if($role)
                return $role->title;
            return null;
        });
        $dataTable->editColumn('created_at', function($data) {
            return Helper::DbFormatToDateString($data->created_at);
        });
        $dataTable->editColumn('updated_at', function($data) {
            return Helper::DbFormatToDateString($data->updated_at);
        });
        return $dataTable->addColumn('action', 'admins.datatables_actions');
    }

    /**
     * Get query source of dataTable.
     *
     * @param \App\Models\Admin $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(Admin $model)
    {
        return $model->newQuery();
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->addAction(['width' => '120px', 'printable' => false , 'title' => 'عملیات'] , true)
            ->parameters([
                'dom'       => 'Bfrtip',
                'stateSave' => true,
                'order'     => [[0, 'desc']],
                "language" => [
                    "info" => "نمایش _START_ از _END_ آیتم (از مجموع _TOTAL_ آیتم)",
                    "infoFiltered"=> "",
                    "paginate" => [
                        "next" => "بعدی",
                        "previous" => "قبلی"
                    ],
                    "sSearch" => 'جستجو : ',
                ],
                'buttons'   => [
                    ['extend' => 'create', 'text'=> '<span><i class="fa fa-plus"></i> افزودن</span>','className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'reset', 'text'=> '<span><i class="fa fa-sync-alt"></i> تنظیم مجدد</span>','className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'reload', 'text'=> '<span><i class="fa fa-undo"></i> تازه سازی</span>','className' => 'btn btn-default btn-sm no-corner',],
                ],
            ]);
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            ['data' => 'id', 'name' => 'id', 'title' => 'شناسه'],
            ['data' => 'name', 'name' => 'name', 'title' => 'نام و نام خانوادگی'],
            ['data' => 'email', 'name' => 'email', 'title' => 'ایمیل'],
            ['data' => 'super_admin', 'name' => 'super_admin', 'title' => 'ادمین اصلی'],
            ['data' => 'role_id', 'name' => 'role_id', 'title' => 'نقش'],
            ['data' => 'created_at', 'name' => 'created_at', 'title' => 'تاریخ ایجاد'],
            ['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'تاریخ ویرایش'],
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'admins_datatable_' . time();
    }
}
`

**Comment by afsharmahmoodian** [comment]
I realized that request pass these two condition in DataTable.php ( only in server - in local is ok ).
why?!

    public function render($view, $data = [], $mergeData = [])
    {
        if ($this->request()->ajax() && $this->request()->wantsJson()) {
            return app()->call([$this, 'ajax']);
        }

        if ($action = $this->request()->get('action') and in_array($action, $this->actions)) {
            if ($action == 'print') {
                return app()->call([$this, 'printPreview']);
            }

            return app()->call([$this, $action]);
        }

        return view($view, $data, $mergeData)->with($this->dataTableVariable, $this->getHtmlBuilder());
    }

**Comment by TomEasterbrook** [comment]
> you can use ajax or postAjax in your dataTable and it gonna work!

I'm having the same issue in one of my projects, I wondered if it wouldn't be too much trouble for you to post your implementation off the ajax method to give me something to go on? Any help would be greatly appreciated!

**Comment by yajra** [comment]
I think this what he meant on postAjax: https://yajrabox.com/docs/laravel-datatables/master/html-builder-post-ajax

Also, don't forget to set your route to accept a post request.
