### ISSUE TITLE
Server side add select dropdown filter by custom column

### ISSUE THREAD

**Issue by bartw2k9** [yajra/laravel-datatables#2707]
### Summary of problem or feature request

I it possible to add select dropdown filter custom for custom query search by date for example I have to make select with last 1,2,3,6 months based on created_at date of db table row. Its all now working server-side. 

Should I add just parameter pass to DT in my ModelDataTables class and create my own in frontend select filter by: Date months OR
it is possible to create it just using Laravel DT package? So I will not have to create own html selects in JS. Will Laravel DT can generate dropdown select by field.. config serverside.

- Operating System: ubuntu
- PHP Version: 7.4
- Laravel Version: 8
- Laravel-Datatables Version: 9 (yajra/laravel-datatables-oracle)

**Comment by yajra** [comment]
Yes, here's a quick example:

```php
// ModelDataTables
html() 
{
   return $this->builder()
                    ->setTableId('model-table')
                    ->columns($this->getColumns())
                    ->ajaxWithForm(route('users.index'), '#users-table-form') // use this to automatically append the form data in request
}

query()
{
        return $model->select('users.*')
            ->when(request('custom-date'), function ($q, $date) {
                $q->whereDate('created_at', $date);
            })...
}

// view
<div id="users-table-form">
   <input name="custom-date" class="custom-date-picker" />
</div>

**Comment by yajra** [comment]
Here's an older [docs](https://datatables.yajrabox.com/fluent/custom-filter) but the concept should be the same.
