### ISSUE TITLE
hei，are you see the email ? 

### ISSUE THREAD

**Issue by openvast** [yajra/laravel-datatables#271]
![image](https://cloud.githubusercontent.com/assets/9793122/11495904/ac396c62-9849-11e5-84fb-77765e162cf4.png)

**Comment by openvast** [comment]
vendor\yajra\laravel-datatables-oracle\src\yajra\Datatables\Engines



    /**
     * Get column name from string.
     *
     * @param string $str
     * @return string
     */
    public function extractColumnName($str)
    {
        $matches = explode(' as ', Str::lower($str));

        if ( ! empty($matches)) {
            return array_shift($matches);
//            return array_pop($matches);
        } elseif (strpos($str, '.')) {
            $array = explode('.', $str);

            return array_pop($array);
        }

        return $str;
    }

**Comment by openvast** [comment]
vendor\yajra\laravel-datatables-oracle\src\yajra\Datatables\Engines|

 /**
     * @inheritdoc
     */
    public function filtering()
    {
        $this->query->where(
            function ($query) {
                $keyword = $this->setupKeyword($this->request->keyword());
                foreach ($this->request->searchableColumnIndex() as $index) {
                    $columnName = $this->setupColumnName($index);

                    if (isset($this->columnDef['filter'][$columnName])) {
                        $method     = Helper::getOrMethod($this->columnDef['filter'][$columnName]['method']);
                        $parameters = $this->columnDef['filter'][$columnName]['parameters'];
                        $this->compileColumnQuery(
                            $this->getQueryBuilder($query), $method, $parameters, $columnName, $keyword
                        );
                    } else {
//                        $columnName = $this->prefixColumn($columnName);
                        $this->compileGlobalSearch($this->getQueryBuilder($query), $columnName, $keyword);
                    }

                    $this->isFilterApplied = true;
                }
            }
        );
    }

**Comment by yajra** [comment]
@openvast, No haven't received an email. Anyways, when using join queries, you should note to use/define your columns using fully qualified column name which includes the table name like `table.column` on your js. See this demo for ref: http://datatables.yajrabox.com/eloquent/joins

**Comment by openvast** [comment]
give me an email.that you can see my send email.here cannot upload images easy
