### ISSUE TITLE
Replace NULL fields with empty string

### ISSUE THREAD

**Issue by Echecivuole** [yajra/laravel-datatables#2713]
### Summary of problem or feature request

It is absurd: there are no ways to replace automatically any NULL field with empty string and avoid to see that terrible "null" in each field!

Any solution for this without applying if condition in any column?!

### System details

- OSX
- PHP 7.4
- Laravel 7
- Laravel-Datatables version: latest

**Comment by madbasanta** [comment]
use `editColumn`
```
->editColumn('mid_name', function ($user) {
    return $user->mid_name ?: '';
})
```

**Comment by yajra** [comment]
`null` on display? Aside from what @madbasanta suggested, you can try using columnDefs. Check the official js docs for more info.

```js
    columnDefs: [
        {
            targets: '_all',
            defaultContent: '-'
        }
    ]
```
