### ISSUE TITLE
Don't trash the exception stack trace

### ISSUE THREAD

**Issue by Delph** [yajra/laravel-datatables#2714]
### Summary of problem or feature request

When a crash occurs within DataTables, the built in error handler can deal with it in a few ways. When set to `throw` a new exception is thrown instead of rethrowing the original exception. This trashes the stack trace and makes it appear as though the crash came from within DataTables (specifically, from the `make` call) rather than the user's code (e.g., `addColumn`).

I would submit a PR, but I'm not familiar enough to know what documentation materials etc need updating.

### Code snippet of problem

```php
    protected function errorResponse(\Exception $exception)
    {
        $error = $this->config->get('datatables.error');
        $debug = $this->config->get('app.debug');

        if ($error === 'throw' || (! $error && ! $debug)) {
            throw $exception; //new Exception($exception->getMessage(), $code = 0, $exception);
        }

        $this->getLogger()->error($exception);

        return new JsonResponse([
            'draw'            => (int) $this->request->input('draw'),
            'recordsTotal'    => $this->totalRecords,
            'recordsFiltered' => 0,
            'data'            => [],
            'error'           => $error ? __($error) : "Exception Message:\n\n".$exception->getMessage(),
        ]);
    }
```

### System details

- OS:
`Linux 49c30c358d5b 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 GNU/Linux`
- PHP:
PHP 7.4.16 (cli) (built: Mar  4 2021 21:24:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
- Laravel: 8.75.0
- Laravel DataTables: v9.18.2

**Comment by yajra** [comment]
Thank you for the inputs and interest on submitting a PR. Please fork the package and send the PR on 9.x branch.
