### ISSUE TITLE
Problem with pagination

### ISSUE THREAD

**Issue by silvioimp78** [yajra/laravel-datatables#2715]
Hi, I have a strange issue with your package.

When using server side paginantion I can only view first page.

On the others pages I get the following error;

 [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'offset' 

The final part of the query is: **[nome] desc offset 5 rows fetch next 5 rows only**

The syntax is wrong  for this SQL version.

Any help?

### System details

- Operating System
- PHP Version 7.3
- Laravel Version 8.0
- Laravel-Datatables Version 9.0
- Database SqlServer Version 2008R2

**Comment by yajra** [comment]
Please provide some snippets to replicate the issue.

**Comment by crisleiria** [comment]
This is because SQL SERVER 2008 R2 dont have OFFSET an NEXT function. 

This function only appear on SQL SERVER 2012.

I am having the same problem on laravel eloquent.

This package problably depends on eloquent pagination.
