### ISSUE TITLE
Calling or use variables outside addColumn function issue

### ISSUE THREAD

**Issue by iandecastro13** [yajra/laravel-datatables#2719]
### Summary of problem or feature request

I am trying to use a variable outside addColumn function but i'm unable to call it outside.

Please check my code below.

### Code snippet of problem

$pricevar = 'This return list'
$pricelist = 'This return list'

$dt = Datatables::of($pricelist);

$dt->addColumn($prcvar->code, function ($pricelist) use ($prcvar) {

                                                                        
        $calc =  ($pricelist->rate * $prcvar->value);             

        $calloutside = $calc * 100;

        return $calc; 
}); 

$dt->addColumn($prcvar->attr_code, $calloutside); //// error - undefined calloutside variable

return $dt->make(true);

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by madbasanta** [comment]
You should define your `$calloutside` variable outside of the function and pass it by reference(use `&` before variable inside use statement) just like `$prcvar`.
```
$pricevar = 'This return list';
$pricelist = 'This return list';
$calloutside = 0;

$dt = Datatables::of($pricelist);
$dt->addColumn($prcvar->code, function ($pricelist) use ($prcvar, &$calloutside) {
    $calc =  ($pricelist->rate * $prcvar->value);             
    $calloutside = $calc * 100;
    return $calc;
});
$dt->addColumn($prcvar->attr_code, $calloutside);
return $dt->make(true);

```
