### ISSUE TITLE
Double prefix

### ISSUE THREAD

**Issue by ohor** [yajra/laravel-datatables#272]
Hi!
Thanks for the package first.

But there is a little problem with it. 
While trying to use a search using a query builder with join I found an error with double prefix for related table.

To fix it I modified  Grammar\wrapTable:   
/**
     * Wrap a table in keyword identifiers.
     *
     * @param  string|\Illuminate\Database\Query\Expression  $table
     * @return string
     */
    public function wrapTable($table)
    {
        if ($this->isExpression($table)) {
            return $this->getValue($table);
        }
        $wrapped = (strpos($table, $this->tablePrefix) === false) ? $this->tablePrefix.$table : $table;

        return $this->wrap($wrapped, true);
    }

Could you please fix it in your package.

**Comment by yajra** [comment]
Hi @ohor,

`wrapTable` is part of [`illuminate/database`](https://github.com/illuminate/database) and I do not have control over it. Maybe try making a PR on Laravel framework instead? 

Thanks!

**Comment by yajra** [comment]
@ohor, @openvast  I think the issue was raised on [v5.11.12](https://github.com/yajra/laravel-datatables/releases/tag/v5.11.12)++. Would you please try [v5.11.11](https://github.com/yajra/laravel-datatables/releases/tag/v5.11.11) to see it it fixes the issue? Will revert the changes if this was fixed on v5.11.11. Thanks!

**Comment by openvast** [comment]
sorry,in my program ,i use v5.0, 
the bug file is        src/yajra/Datatables/Engines/EloquentEngine.php
the line 107

**Comment by openvast** [comment]
when i use select" table.column as myColumn" the bug file is :
src/yajra/Datatables/Engines/BaseEngine.php
line 261 
            return array_shift($matches);
//            return array_pop($matches);
