### ISSUE TITLE
Upgrade guide from 8.x to 9.x

### ISSUE THREAD

**Issue by inquisitive-stha** [yajra/laravel-datatables#2722]
Is there any breaking changes on 8.x to 9.x. Should updating from `~8.x` to `~9.x` be fine? Or there are some cautions that need to be followed?

**Comment by yajra** [comment]
Should be fine to upgrade from 8.x to 9.x directly. I think the major bump was only due to php version constraint. 

https://github.com/yajra/laravel-datatables/blob/9.0/CHANGELOG.md#v900---2019-02-27
