### ISSUE TITLE
Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::download()

### ISSUE THREAD

**Issue by enaeim** [yajra/laravel-datatables#2725]
### System details

- Operating System : `Windows Server 2022`
- PHP Version : `8.0.12`
- Laravel Version : `8.74.0`
- yajra/laravel-datatables-oracle : `"~9.0"`
- yajra/laravel-datatables-buttons : `"^4.13"`
- maatwebsite/excel: `"^3.1"`

Hi dear Yajra and other friends.

Using the datatables export button, I added a button to export from the table as a server side. So far everything is going well and there are no problems. But I got into trouble when I used maatwebsite/laravel-excel.

`app/DataTables/UsersDataTable.php` content:
```php
namespace App\DataTables;

use App\Exports\UsersExport;
use App\Models\User;
use Maatwebsite\Excel\Facades\Excel;
// ...

class UsersDataTable extends DataTable
{

    // ...

    protected function buildExcelFile()
    {
        $export = new UsersExport($this->getDataForExport());
        return Excel::download($export, 'users.xlsx');
    }
}
```

`app/Exports/UsersExport.php` content:
```php
namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;

class UsersExport implements FromArray
{
    protected array $users;

    public function __construct(array $users)
    {
        $this->users = $users;
    }

    public function array(): array
    {
        return $this->users;
    }
}
```

When I press the datatbles export excel button, I get the following error:
![image](https://user-images.githubusercontent.com/33656061/149144948-e1c3b71b-dc25-4903-a555-d3cfa864605e.png)

**Comment by yajra** [comment]
By the error itself, you should return an excel file on build method. Or you can just override excel method instead.

```php
protected function excel()
    {
        $export = new UsersExport($this->getDataForExport());
        return Excel::download($export, 'users.xlsx');
    }
```

**Comment by enaeim** [comment]
> By the error itself, you should return an excel file on build method. Or you can just override excel method instead.
> 
> ```
>     protected function excel()
>     {
>         $export = new UsersExport($this->getDataForExport());
> 
>         return Excel::download($export, 'users.xlsx');
>     }
> ```

Thanks a lot.
