### ISSUE TITLE
Filter relationship  by Yajra laravel-datatable serverside searchbuilder

### ISSUE THREAD

**Issue by enaeim** [yajra/laravel-datatables#2726]
Hi friends.
I Use Yajra/laravel-datatable to datatable server side and datatables searchbuilder extension for serverside filter. And this work correctly.
But how to add a relationship field to searchbuilder. For example, in my project, in the admin panel, there is a table containing all the admins of the site and there is no column as the their roles. But I want to search and find users who are operators in searchbuilder. How do I implement this using searchbuilder and yajra?
I am new to datatables, yajra and jquery.
I would be very grateful if you could guide me or introduce me to the tutorial link or in-depth tutorial on this.
Thanks a lot.

_Originally posted by @enaeim in https://github.com/yajra/laravel-datatables/issues/2648#issuecomment-1005632780_

**Comment by yajra** [comment]
You can use [filterColumn](https://yajrabox.com/docs/laravel-datatables/master/filter-column)

```php
    return DataTables::eloquent($model)
                ->filterColumn('relation_name', function($query, $keyword) {
                    $query->whereHas('relation', fn($q) => $q->where('relation_name', $keyword));
                })
                ->toJson();
```

**Comment by enaeim** [comment]
> @enaeim Could you teach me how to use SearchBuilder together with the ServerSide option? I've analyzed Issue #2648 but I still can't get it to work

Hello. Yes I can. But not now. I will get back to you within the next few days.

**Comment by humbertleonardo** [comment]
> > @enaeim Could you teach me how to use SearchBuilder together with the ServerSide option? I've analyzed Issue #2648 but I still can't get it to work
> 
> Hello. Yes I can. But not now. I will get back to you within the next few days.

Okay, thank you very much for your attention. If you can make the code you implemented available in some repository, I can try to do it myself
