### ISSUE TITLE
returns empty data but says it has filtered records

### ISSUE THREAD

**Issue by 0line** [yajra/laravel-datatables#2729]
Hello I would like to ask for help, I am using datatables as shown in the documentation but when filtering by a record when I put it as it is it does not return that record. Example: I have the following response with all my data without filters:

```
{
    "draw": 2,
    "recordsTotal": 4,
    "recordsFiltered": 4,
    "data": [
        {
            "id": 2,
            "name": "data1"
        },
        {
            { "id": 3,
            "name": "data 2"
        },
        {
            "id": 10002,
            "name": "data 3"
        },
        {
            "id": 10003,
            "name": "data 4",
        }
    ]
}
```

 but if I want to get the information with id = 10003 the result is as follows:
```
{
    "draw": 3,
    "recordsTotal": 4,
    "recordsFiltered": 1,
    "data": []
}
```

I leave my query and DT configuration:
```

$collection = Model::select(['id','name'])->get();
return DataTables::of($collection)->make(true);
```
_Postman request_
`http://127.0.0.1/datatables?draw=2&columns[0][data]=id&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=name&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=1&length=10&search[value]=10003&search[regex]=false&_=1641681564168&dt=1`

**I hope someone can help me... Greetings from Mexico.**

**Comment by yajra** [comment]
Maybe try using query instead of collection?

```php
$query = Model::select(['id','name']);

return DataTables::of($query)->make(true);
```

Also, it seems like there is a missing name parameter? 

`columns[0][name]=&columns[0][searchable]=true`

**Comment by 0line** [comment]
@yajra  In your search you also have undefined values.

`https://datatables.yajrabox.com/eloquent/basic-data?draw=2&columns[0][data]=0&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=1&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=2&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=true&columns[2][search][value]=&columns[2][search][regex]=false&columns[3][data]=3&columns[3][name]=&columns[3][searchable]=true&columns[3][orderable]=true&columns[3][search][value]=&columns[3][search][regex]=false&columns[4][data]=4&columns[4][name]=&columns[4][searchable]=true&columns[4][orderable]=true&columns[4][search][value]=&columns[4][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=0&length=10&search[value]=2&search[regex]=false&_=1642713765809`

I set up my DT, as you mention but the result is the same

$query = Model::select(['id','name']);
return DataTables::of($query)->make(true);

http://127.0.0.1/datatables?draw=2&columns[0][data]=id&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=name&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=1&length=10&search[value]=10003&search[regex]=false&_=1641681564168&dt=1

![imagen](https://user-images.githubusercontent.com/16262267/150425612-dd5f7e6c-d734-4776-8e1e-cfad2a1eaee2.png)

**Comment by 0line** [comment]
When the query is created in datatables it adds the offset setting, when it is at 1 it omits the result when there is only one match at 0 it places that match or more.
I forgot to mention from the beginning that I use SQL SERVER, sorry, could you help me to correct it please @yajra .

```
select [id], [name], from model| 
where (LOWER([cat_type_event_event_log_book].[id]) LIKE '%record3%' 
or LOWER([cat_type_event_event_log_book].[name]) LIKE '%record3%')
order by [id] asc offset 1 rows fetch next 10 rows only


select [id], [name], from model| 
where (LOWER([cat_type_event_event_log_book].[id]) LIKE '%registration3%') 
or LOWER([cat_type_event_event_log_book].[name]) LIKE '%record3%')
order by [id] asc offset 0 rows fetch next 10 rows only
```

**Comment by 0line** [comment]
@yajra Sorry, I saw my mistake. I had the configuration of the request wrong, the value of start should always be set to 0 since it defines the offset and I set it to 1 so I ignored the only match that existed.

**Comment by alexchirolde** [comment]
I'm facing this same issue. I'm using eloquent builder like this:

`$datatable = Datatables::of($models)->make(true);`

$models have been previously filtered, and if I check the content of $models before that line:
`dd($models);`
`$datatable = Datatables::of($models)->make(true);`

 I get all the filtered results, but then after the datatables package runs it returns this: 

{
   "draw": 1,
   "recordsTotal": 113,
   "recordsFiltered": 0,
   "data": [],
   "callsCounter": 0,
   "programsCounter": 113,
   "queries": [
      {
         "query": "select count(*) as aggregate from `programs_calls` where (lower(json_unquote(name->'$.*')) like ? or lower(acronym) like ?) and `prog_or_call` = ? and `programs_calls`.`deleted_at` is null",
         "bindings": [
            "%hor%",
            "%hor%",
            1
         ],
         "time": 7.32
      },
      {
         "query": "select count(*) as aggregate from `programs_calls` where (lower(json_unquote(name->'$.*')) like ? or lower(acronym) like ?) and `prog_or_call` = ? and (LOWER(`programs_calls`.`acronym`) LIKE ?) and `programs_calls`.`deleted_at` is null",
         "bindings": [
            "%hor%",
            "%hor%",
            1,
            "%hor%"
         ],
         "time": 7.89
      },
      {
         "query": "select * from `programs_calls` where (lower(json_unquote(name->'$.*')) like ? or lower(acronym) like ?) and `prog_or_call` = ? and (LOWER(`programs_calls`.`acronym`) LIKE ?) and `programs_calls`.`deleted_at` is null order by `acronym` asc limit 10 offset 0",
         "bindings": [
            "%hor%",
            "%hor%",
            1,
            "%hor%"
         ],
         "time": 7.41
      }
   ],
   "input": {
      "draw": "1",
      "columns": [
         {
            "data": null,
            "name": null,
            "searchable": "false",
            "orderable": "false",
            "search": {
               "value": null,
               "regex": "false"
            }
         },
         {
            "data": "logo_list_view",
            "name": "logo_list_view",
            "searchable": "true",
            "orderable": "true",
            "search": {
               "value": null,
               "regex": "false"
            }
         },
         {
            "data": "call_published_list_view",
            "name": "call_published_list_view",
            "searchable": "true",
            "orderable": "true",
            "search": {
               "value": null,
               "regex": "false"
            }
         },
         {
            "data": "acronym",
            "name": "acronym",
            "searchable": "true",
            "orderable": "true",
            "search": {
               "value": null,
               "regex": "false"
            }
         },
         {
            "data": "en_name",
            "name": "en_name",
            "searchable": "true",
            "orderable": "true",
            "search": {
               "value": null,
               "regex": "false"
            }
         },
         {
            "data": "updated_at",
            "name": "updated_at",
            "searchable": "false",
            "orderable": "true",
            "search": {
               "value": null,
               "regex": "false"
            }
         },
         {
            "data": "action",
            "name": "action",
            "searchable": "false",
            "orderable": "false",
            "search": {
               "value": null,
               "regex": "false"
            }
         }
      ],
      "order": [
         {
            "column": "3",
            "dir": "asc"
         }
      ],
      "start": "0",
      "length": "10",
      "search": {
         "value": "hor",
         "regex": "false"
      },
      "period": "0",
      "programCallStatus": "all",
      "alphabet": null,
      "onlyPrograms": "true",
      "_": "1661198968109"
   }
}

I can use some help here @yajra 

If there's anything else you need please let me know.
Best Alejandro
