### ISSUE TITLE
How to search when using withCount()?

### ISSUE THREAD

**Issue by jackzdev** [yajra/laravel-datatables#2730]
### Summary of problem or feature request

Hi, how can I search those column which generated by withCount() function? im trying to use having() to achieve this but failed

### Code snippet of problem

```php
   public function dataTable($query)
    {
        $request = $this->request();

        return datatables()
            ->eloquent($query)
            ->filter(function ($query) use ($request) {
                if ($request->filled('status')) {
                    $query->where('status', '=', $request->status);
                }
            }, true)
            ->editColumn('posts_count', function (User $user) {    
                return view('post', compact('user'));
            })
            ->filterColumn('posts_count', function ($query, $keyword) {
                $query->withCount('posts')->having('posts_count', $keyword);
            });
    }

  public function query(User $model)
    {
        return $model
        ->withCount('posts')
        ->newQuery();
    }

  protected function getColumns()
    {
        return [
            Column::make('posts_count'),
        ];
    }
```

### System details

- Operating System = Windows 10
- PHP Version = 8.0.12
- Laravel Version = 8
- Laravel-Datatables Version = 1.5

**Comment by yajra** [comment]
Not tested but I think it should be on the query side:

```php
    public function query(User $model)
    {
        return $model->select('users.*')
            ->withCount('posts')
            ->when($this->request()->keyword(), function ($q, $keyword) {
                $q->having('posts_count', $keyword);
            })
    }

// also disable search here
Column::make('posts_count')->searchable(false),
```

**Comment by jackzdev** [comment]
@yajra thanks for the respond, the code snippet I posted above is just a sample, my datatable is actually got more columns, I use this datatable for my index page which I need to retrieve all the records and allow user to search for specific word for every single column, the problem is I can get exactly what I need when I use User::withCount('posts')->having('posts_count', 1)->get(); , but when I use having() in filterColumn() it always return nothing

**Comment by yajra** [comment]
> but when I use having() in filterColumn() it always return nothing

Yes because filter column is being run inside a nested where clause and afaik, Laravel does not support having SQL inside a nested where clause that's why it should be appended on the main query.

```php
// filterColumn is equivalent to:
->where(function($q) {
   // append all filterColumns
  $q->having('posts_count', $count); // this does not work
})
```

**Comment by jackzdev** [comment]
> Laravel does not support having SQL inside a nested where clause

@yajra Oh I got it, is it possible to make it search for all column? The code you suggested above will work when the user only want to filter on the posts_count column, but my search input is for global one, the user can use the search input to search for others column as well.
E.g. when user search for '1', we should return those users have 1 post OR email that contain '1'.

**Comment by yajra** [comment]
Maybe try using `orHaving` so that it's not too strict?

**Comment by yajra** [comment]
From the docs, something similar I guess: https://laravel.com/docs/8.x/queries#havingraw-orhavingraw

**Comment by jackzdev** [comment]
@yajra Thanks a lot, orHaving() this work perfectly for my case.
