### ISSUE TITLE
checkbox misfunction

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [yajra/laravel-datatables#2731]
### Summary of problem or feature request

Hi
tnx for package
I'm returning a html code as a form in datatable action column and each row has a separate form and in the form there is a checkbox with same name of bank_update[] and different value each row and the problem is after the table is rendered on the front no matter which checkbox I select only the checkbox in first row get selected and no other checkbox

### Code snippet of problem
html code in return of action column

```
  <div class='btn-group-toggle'>
                        <a  href='" . $download_url . "'>
                        <button class='btn btn-secondary mb-1'>
                        دانلود
                        </button>
                        </a>
                   <form style='font-size:80%' action='" . $upload_url . "' method='post' enctype='multipart/form-data'>
                    <input type='hidden' name='type' value='" . $type . "'>
                    <input type='hidden' name='_token' value='" . $token . "'>
                    <div class='btn-group-toggle'>
                        <label  class='btn btn-info'>
                            <i class='fa fa-check-square'></i> انتخاب فایل قرارداد  $translate
                            <input type='file'
                            style='display: none'
                            name='contract'>
                        </label>
                        <input type='checkbox' id='flexCheckDefault' name='registrations[]'         value='" . $type . "'/>
 <label for='flexCheckDefault' class='form-check-label'>به روز رسانی بانک
                     </label>
                       <input type='submit' class='btn btn-success' value='آپلود'>
                     </div>
                  </form>
                  </div>

       
```

### System details

- Operating System windows,linux
- PHP Version  7.4
- Laravel Version 8.* latest
- Laravel-Datatables Version latest verstion 9.*

**Comment by yajra** [comment]
Sorry but I think this is an html issue and out of scope of the package. Anyways, might be because of the ID, I think it should be unique.

**Comment by darvishiyan-mahdi** [comment]
Hi I checked html part of multiple of checkbox form  in a sperate form with same ID an name used in these codes and its work properly but as soon as I add these part to datatable like the code I share the misfunction happen. If you can make a replica and test this issue I would be in your debt

**Comment by yajra** [comment]
When you add the action, try appending the row id.

```php
->addColumn('action', function($row) {
  return view('action', compact('row'));
});

// action.blade.php

<input type='checkbox' id='flexCheckDefault{{ $row->id }}' name='registrations[]'         value='" . $type . "'/>
<label for='flexCheckDefault{{ $row->id }}' class='form-check-label'>به روز رسانی بانک</label>
```

Hope you get the idea.

**Comment by darvishiyan-mahdi** [comment]
tnx man it worked like a charm 
I should have used blade files
it is so much easier to work than the way I code before
