### ISSUE TITLE
How to change language for datatables globally for the entire project? 

### ISSUE THREAD

**Issue by EgyptianM** [yajra/laravel-datatables#2732]
I'm setting language for a single table like this:

           `->parameters([
                'language' => [
                    'url' => url('/vendor/datatables/lang/'.app()->getLocale().'.json'),
                ]]
            );`

I don't want to set for every table in the project, is there a way to set it globally?
And where can I find localization files for yajrabox?

**Comment by yajra** [comment]
If you want it global, compile it or add the defaults in javascript. See js official docs for more refs.

**Comment by EgyptianM** [comment]
> If you want it global, compile it or add the defaults in javascript. See js official docs for more refs.

Thank you for your reply, can you please give a link to this docs?

**Comment by yajra** [comment]
See [datatables.net](datatables.net) I think on options section
