### ISSUE TITLE
selectable rows

### ISSUE THREAD

**Issue by EgyptianM** [yajra/laravel-datatables#2734]
Can anyone explain how to make selectable rows with example code?
Thanks in advance

**Comment by yajra** [comment]
Use [select extension](https://datatables.net/extensions/select/) of DT? 
See https://yajrabox.com/docs/laravel-datatables/master/html-builder-parameters, there is also a fluent version for each params but not documented.

```php
    public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->setTableId('users-table')
                    ->columns($this->getColumns())
                    ->selectStyleMulti() // enable multi selection
                    ->ajaxWithFilters()
                    ->orderBy(1)
                    ->buttons($this->getButtons())
                    ->editors($this->getEditors());
    }
```

**Comment by EgyptianM** [comment]
`selectStyleMulti()`
Do I need to use `Select extension` with this option? 
because I tried it but it didn't work

**Comment by yajra** [comment]
Yes, you need the extensions scripts and css for it to work properly.
