### ISSUE TITLE
Error with eager loading with multiple databases

### ISSUE THREAD

**Issue by ThiagoPrange** [yajra/laravel-datatables#2739]
![06355b2f-449a-4af0-a471-dbc1676f657d](https://user-images.githubusercontent.com/62709706/152985515-9bc7d11e-ce2b-4651-87f9-d1607bc05f00.jpg)
### Summary of problem or feature request

Hi! I am trying to retrieve data from a relationship, with tables in different databases. The relationship works if I work individually, but if I javascript the column directly to get the benefits of sorting and searching it gives an error. Not all records have a relationship, or none at all, using tinker returns null as expected...
If you create the column using an addColumn for example, it works fine, the problem is that it doesn't sort properly and doesn't filter

The screenshot with the error shows that it is apparently forcing the same connection to all tables.

What would be the best way to fix this?

### Code snippet of problem

```php
Controller: 

 public function getOp(Request $request)
    {
        if ($request->ajax()) {
            $sales = BudgetsSale::select(['bus_id', 'bus_idpeo', 'bus_closing_date', 'bus_idrep', 'bus_delivery_date_com', 'bus_type_doc'])->where([
                ['bus_closing_date', '!=', 'null'],
                ['bus_closing_date', '>=', '2021-07-01'],
            ])->with('client', 'typeDocument', 'seller', 'op');
        }

        return DataTables::of($sales)
            ->editColumn('bus_closing_date', function (BudgetsSale $sale) {
                return date('d/m/Y', strtotime($sale->bus_closing_date));
            })
            ->filterColumn('bus_closing_date', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(bus_closing_date,'%d/%m/%Y %h:%i:%s') like ?", ["%$keyword%"]);
            })
            ->editColumn('bus_delivery_date_com', function (BudgetsSale $sale) {
                return date('d/m/Y', strtotime($sale->bus_delivery_date_com));
            })
            ->filterColumn('bus_delivery_date_com', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(bus_delivery_date_com,'%d/%m/%Y %h:%i:%s') like ?", ["%$keyword%"]);
            })
            ->addColumn('options', function (BudgetsSale $sale) {
                return $sale->bus_id;
            })
            ->make(true);
    }

Modelos:

class ProductionOrder extends Model
{
    protected $connection = 'mysql';
    protected $fillable = [
        'id_budgets_sales',
        'id_status_sales',
        'version',
        'id_user_last_change',
    ];
}

class BudgetsSale extends Model
{
    protected $connection = 'dvalorne_cermob';
    protected $table = 'budgets_sale';
    protected $primaryKey = 'bus_id';
    public $timestamps = false;
}
```

```javascript
 columns: [{ data: 'op.id_budgets_sales', name: 'op.id_budgets_sales' }]
```

### System details

- Windows 10
- PHP 7.4
- Laravel 7
- Laravel-Datatables 9

**Comment by ThiagoPrange** [comment]
I managed to make the relationship part work, but now the search part doesn't work...

` public function getOp(Request $request)
    {
        if ($request->ajax()) {
            $sales = BudgetsSale::select(['bus_id', 'bus_idpeo', 'bus_closing_date', 'bus_idrep', 'bus_delivery_date_com', 'bus_type_doc'])->where([
                ['bus_closing_date', '!=', 'null'],
                ['bus_closing_date', '>=', '2021-07-01'],
            ])->with(['client', 'typeDocument', 'seller', 'op']);
        }

        return DataTables::of($sales)
            ->editColumn('bus_closing_date', function (BudgetsSale $sale) {
                return date('d/m/Y', strtotime($sale->bus_closing_date));
            })
            ->filterColumn('bus_closing_date', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(bus_closing_date,'%d/%m/%Y %h:%i:%s') like ?", ["%$keyword%"]);
            })
            ->editColumn('bus_delivery_date_com', function (BudgetsSale $sale) {
                return date('d/m/Y', strtotime($sale->bus_delivery_date_com));
            })
            ->filterColumn('bus_delivery_date_com', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(bus_delivery_date_com,'%d/%m/%Y %h:%i:%s') like ?", ["%$keyword%"]);
            })
            ->addColumn('status_op', function (BudgetsSale $sale) {
                return $sale->op->status->status ?? 'Pendente';
            })
            ->orderColumn('status_op', function ($query, $order) {
                $query->leftJoin('tasselo.production_orders as op', 'bus_id', '=', 'op.id_budgets_sales')->orderBy('op.id_status_sales', $order);
            })
            ->addColumn('options', function (BudgetsSale $sale) {
                return $sale->bus_id;
            })
            ->make(true);
    }`

I needed to make a leftjoin, which solved the sorting problem... How to make a query reference this other table from another database?

**Comment by adlytodak** [comment]
Have you solve the problem? i'm facing same problem. @ThiagoPrange

**Comment by ThiagoPrange** [comment]
> Have you solve the problem? i'm facing same problem. @ThiagoPrange

Not yet @adlytodak... I paused this project for a while, but if you find out anything i will be happy very grateful :)

**Comment by yajra** [comment]
Unfortunately this is not yet supported unless your database supports it. 

For instance, when using Oracle we can have multiple connection but then has the ability to join different schemas and database via database links and other DB stuffs like synonyms, views to make it work.

To keep it simple, it if works on SQL level, then it should work on the package too.
