### ISSUE TITLE
Datatables with big data (20,000) slow even with server side and pagination

### ISSUE THREAD

**Issue by Echecivuole** [yajra/laravel-datatables#2740]
### Summary of problem or feature request
Hello, I hope you can help me. I applied your package and server side + pagination. I have 20,000 contacts, but even if I made pagination by 25, it takes at least 4 seconds to show each 25-rows page. Even if I type in search bar, it takes 4 seconds for any action! Here below my code using datatables in controller + raw SQL query

### Code snippet of problem

```php
// CONTROLLER QUERY
    $contacts_array = DB::select("SELECT c.*,cp.company_id,cp.title as company, cp.logo as logo,co.connections
      FROM app_contact as c
      LEFT JOIN app_company as cp ON c.company_id=cp.company_id
      LEFT JOIN (SELECT count(connection_id) as connections, contact_id FROM app_connection WHERE organization_id=? AND contact_id !='' GROUP BY contact_id) as co ON co.contact_id=c.contact_id
      WHERE c.organization_id=? AND NULLIF(c.archived, ' ') IS NULL AND ( (c.privacy = 0 OR c.privacy IS NULL) OR (c.privacy = 1 AND (c.created_by='".$my_user."' OR FIND_IN_SET('".$my_user."',c.stakeholders))) )
      ORDER BY c.surname ASC",[$session_org_id,$session_org_id]);

      return Datatables::of($contacts_array)
      ->addColumn('updated_at', function($value) {
          return strtotime($value->updated_at) > strtotime('-7 day');
      })
      ->addColumn('stakeholders', function($value) {
          $stakeholders = \AppHelper::instance()->html_avatar($value->stakeholders, 'avatar_sm');
          return $stakeholders;
      })
      ->escapeColumns('all')
      ->make(true);

// BLADE DATATABLES
  init_datatables();

  function init_datatables(){

    var base_url = '{{ url("/") }}';
    var place_holder_image = base_url+'/image/icon/organization_icon.png';
    var my_placeholder_logo = "this.src='"+place_holder_image+"';this.className='avatar_square_sm position-absolute avatar_bg'";

    $.ajaxSetup({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    });
    table = $('#contacts_table').DataTable( {
      serverSide: true,
      processing: true,
      responsive: true,
      render: true,
      ajax: {
        url: "{{ route('contacts.get_json',[app()->getLocale()]) }}",
        dataType: "json",
        type: "POST",
        data:{
          _token: "{{csrf_token()}}",
          // params: 25,
        }
      },
      columns: [
        { data: "updated_at", class: "center px-0", render: function(data, type, full, meta) {
          return (data == true)? '<span data-toggle="tooltip" data-placement="bottom" title="{{ __('messages.recent_updated') }}"><i class="fas fa-circle text_brand" style="font-size:8px;vertical-align:middle"></i></span>':''
        }},
        { data: 'contact_id', class:"pl-3" },
        { data: "privacy", class: "center px-2", render: function(data, type, full, meta) {
          return (data == true)? '<i class="min_w35 fas fa-lock-alt text-dark mt-1" style="font-size:14px" data-toggle="tooltip" data-placement="bottom" title="{{ __('messages.private_contact') }}"></i>' :''
        }},
        { data: "name", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a id="my_contact_'+full.contact_id+'" class="d-flex align-items-center text-dark position-relative" href="javascript:void(0)" onclick="modal_show_entity(event,&quot;contact&quot;,'+full.contact_id+')">'+((full.photo) ? '<img class="avatar_sm position-absolute top-5" src="'+full.photo+'" width="100%">' :'<span class="avatar_sm position-absolute bg_blue text_white"><i class="far fa-user"></i></span>')+' <span class="ml-5">'+data+'</span></a>'
        }},
        { data: "surname", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a class="text-dark" href="javascript:void(0)" onclick="modal_show_entity(event,&quot;contact&quot;,'+full.contact_id+')" >'+data+'</a>'
        }},
        { data: "company", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a class="d-flex align-items-center text-dark" href="javascript:void(0)" onclick="modal_show_entity(event,&quot;company&quot;,'+full.company_id+')"> '+((full.logo) ? '<img class="avatar_square_sm position-absolute" src="'+full.logo+'" width="100%" onerror="'+my_placeholder_logo+'">' :'<span class="avatar_square_sm position-absolute bg_blue text_white"><i class="far fa-building"></i></span>')+' <span class="ml-5">'+data+'</span></a>'
        }},
        { data: "job_role", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a class="text-dark" href="javascript:void(0)" onclick="modal_show_entity(event,&quot;contact&quot;,'+full.contact_id+')" >'+data+'</a>'
        }},
        { data: "type", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a class="text-dark" href="javascript:void(0)" onclick="modal_show_entity(event,&quot;contact&quot;,'+full.contact_id+')" >'+data+'</a>'
        }},
        { data: "email1", class: "center min_w100", render: function(data, type, full, meta) {
          return '<a class="d-block" href="mailto:'+full.email1+'">'+((!full.email1) ? '' :  full.email1)+'</a><a class="d-block" href="mailto:'+full.email2+'">'+((!full.email2) ? '' :  full.email2)+'</a><a class="d-block" href="mailto:'+full.email3+'">'+((!full.email3) ? '' :  full.email3)+'</a><a class="d-flex" href="mailto:'+full.cert_email+'">'+((!full.cert_email) ? '' :  full.cert_email)+''+((full.cert_email) ? "<span class='text_blue' data-toggle='tooltip' data-placement='bottom' title='{{ __("titles.cert_email2") }}'><i class='far fa-badge-check ml-2'></i></span>" :'')+'</a>'
        }},
        { data: "phone1", class: "center min_w100", render: function(data, type, full, meta) {
          return '<a class="d-block" href="tel:'+full.phone1+'">'+((!full.phone1) ? '' :  full.phone1)+'</a><a class="d-block" href="tel:'+full.phone2+'">'+((!full.phone2) ? '' :  full.phone2)+'</a><a class="d-block" href="tel:'+full.phone3+'">'+((!full.phone3) ? '' :  full.phone3)+'</a>'
        }},
        { data: "address1", class: "center min_w100", render: function(data, type, full, meta) {
          return '<a href="http://maps.google.com/?q={{ addslashes('+full.address1+') }}" target="_blank" class="d-block">'+((!full.address1) ? '' :  full.address1)+'</a><a href="http://maps.google.com/?q={{ addslashes('+full.address2+') }}" target="_blank" class="d-block">'+((!full.address2) ? '' :  full.address2)+'</a><a href="http://maps.google.com/?q={{ addslashes('+full.address3+') }}" target="_blank" class="d-block">'+((!full.address3) ? '' :  full.address3)+'</a>'
        }},
        { data: "website1", class: "center min_w100", render: function(data, type, full, meta) {
          return '<a class="d-block" href="http://'+full.website1+'" target="_blank">'+((!full.website1) ? '' :  full.website1)+'</a><a class="d-block" href="http://'+full.website2+'" target="_blank">'+((!full.website2) ? '' :  full.website2)+'</a><a class="d-block" href="http://'+full.website3+'" target="_blank">'+((!full.website3) ? '' :  full.website3)+'</a>'
        }},
        { data: "facebook", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a class="text_darkgrey" href="https://'+full.facebook+'" target="_blank">'+((full.facebook) ? "<span class='d-none'>"+full.facebook+"</span><i class='fab fa-facebook hover_brand mx-1 mt-1' data-toggle='tooltip' data-placement='bottom' title=''></i>" : "")+'</a> <a class="text_darkgrey" href="https://'+full.instagram+'" target="_blank">'+((full.instagram) ? "<span class='d-none'>"+full.instagram+"</span><i class='fab fa-instagram hover_brand mx-1 mt-1' data-toggle='tooltip' data-placement='bottom' title=''></i>" : "")+'</a> <a class="text_darkgrey" href="https://'+full.linkedin+'" target="_blank">'+((full.linkedin) ? "<span class='d-none'>"+full.linkedin+"</span><i class='fab fa-linkedin hover_brand mx-1 mt-1' data-toggle='tooltip' data-placement='bottom' title=''></i>" : "")+'</a> <a class="text_darkgrey" href="https://'+full.twitter+'" target="_blank">'+((full.twitter) ? "<span class='d-none'>"+full.twitter+"</span><i class='fab fa-twitter hover_brand mx-1 mt-1' data-toggle='tooltip' data-placement='bottom' title=''></i>" : "")+'</a>'
        }},
        { data: "stakeholders", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a class="text-dark" href="javascript:void(0)" onclick="modal_show_entity(event,&quot;contact&quot;,'+full.contact_id+')" >'+data+'</a>'
        }},
        { data: "connections", class: "center min_w100", render: function(data, type, full, meta) {
          return (data==null) ? '' : '<a class="badge badge-pill bg_grey" href="javascript:void(0)" onclick="modal_show_entity(event,&quot;contact&quot;,'+full.contact_id+')" >'+data+'</a>'
        }},
      ],
      language: {
        emptyTable: "{{__('messages.no_data')}}",
        loadingRecords: "{{__('messages.data_loading')}}",
        url: "vendor/datatables/plugins/lang/{{app()->getLocale()}}.json",
      },
      lengthMenu: [ [25, 100, 200, -1], [25, 100, 200, "All"] ],
      pageLength: 25,
      order: [[ 3, "asc" ]],
      scrollX: true,
      scrollCollapse: true,
      columnDefs: [
        {
          targets: 0,
          searchable: false,
        },
        {
          targets: 1,
          defaultContent: '',
          render: function(data, type, row, meta){
            if(type === 'display'){
              data = '<div class="el-checkbox el-checkbox-sm mt-1"><input type="checkbox" class="dt-checkboxes"><span class="el-checkbox-style"></span><label class="pointer"></label></div>';
            }
            return data;
          },
          checkboxes: {
            selectRow: true,
            selectAllPages: false,
            selectAllRender: '<div class="el-checkbox el-checkbox-sm mt-1"><input type="checkbox" class="dt-checkboxes"><span class="el-checkbox-style"></span><label class="pointer"></label></div>'
          },
          data: "select",
          searchable: false,
          orderable: false,
          bSortable: false,
          className: 'select-checkbox'
        }
      ],
      select: 'multi',
    }).on( 'draw', function () {
      $('[data-toggle="tooltip"]').tooltip();
    } );
}
```

### System details

- OSX
- PHP7
- Laravel 7
- MYSQL 

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by Echecivuole** [comment]
I need to use raw SQL, not query builder

**Comment by yajra** [comment]
`DB::select` returns a collection thus the performance issue for bulk records. You can still use raw sql but make sure to use a query instance and not collection. I think something like below might do the trick.

```php
DB::table("($rawSql)", 'alias')
```

**Comment by Echecivuole** [comment]
> `DB::select` returns a collection thus the performance issue for bulk records. You can still use raw sql but make sure to use a query instance and not collection. I think something like below might do the trick.
> 
> ```
> DB::table("($rawSql)", 'alias')
> ```

Hello, thanks for reply. Yes it seems that any collection instance is affected by performances. Nevertheless, I replaced

`$contacts_array = DB::select("SELECT...`

with this: 

`$contacts_array = DB::table("SELECT....`

but now getting this error: 

`DataTables warning: table id=contacts_table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`

Please help me as this issue gave me 1 week of issues
thanks!

**Comment by Echecivuole** [comment]
> > `DB::select` returns a collection thus the performance issue for bulk records. You can still use raw sql but make sure to use a query instance and not collection. I think something like below might do the trick.
> > ```
> > DB::table("($rawSql)", 'alias')
> > ```
> 
> Hello, thanks for reply. Yes it seems that any collection instance is affected by performances. Nevertheless, I replaced
> 
> `$contacts_array = DB::select("SELECT...`
> 
> with this:
> 
> `$contacts_array = DB::table("SELECT....`
> 
> but now getting this error:
> 
> `DataTables warning: table id=contacts_table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`
> 
> Please help me as this issue gave me 1 week of issues thanks!

Let me add more comments: The main issue found with your package is that it does not work fast with Laravel raw SQL. As many apps prefer to user raw SQL, please give us solution to let server-side working also with raw SQL.

thanks

**Comment by yajra** [comment]
I already gave you a snippet for an idea but it seems like you didn't get it. Also, I suggest you review the difference between collection and a query. That might help you understand why you're getting errors and performance issues.

Here's a working example of raw sql.

```php
Route::get('/users', function () {
    $q = DB::table(DB::raw('(select * from users)'));

    return datatables($q)->toJson();
});
```

**Comment by Echecivuole** [comment]
> ```
> return datatables($q)->toJson();
> ```

Hello, thanks for your support and sorry, but I am not expert of Eloquent while I am using raw SQL. I tried your solution and also this (I remove route code as the query below is already called into controller function via routes/web.php):

`

    $contacts_array = DB::table(DB::raw("SELECT c.*,cp.company_id,cp.title as company, cp.logo as logo,co.connections
      FROM app_contact as c
      LEFT JOIN app_company as cp ON c.company_id=cp.company_id
      LEFT JOIN (SELECT count(connection_id) as connections, contact_id FROM app_connection WHERE organization_id=? AND contact_id !='' GROUP BY contact_id) as co ON co.contact_id=c.contact_id
      WHERE c.organization_id=? AND NULLIF(c.archived, ' ') IS NULL AND ( (c.privacy = 0 OR c.privacy IS NULL) OR (c.privacy = 1 AND (c.created_by='".$my_user."' OR FIND_IN_SET('".$my_user."',c.stakeholders))) )
      ORDER BY c.surname ASC",[$session_org_id,$session_org_id]));

      // option 1 when commenting the option 2
      return datatables($contacts_array)->toJson();

      // option 2 when commenting the option 1
      return Datatables::of($contacts_array)->toJson();
  
`

but getting this error: 
<img width="474" alt="Schermata 2022-02-09 alle 17 08 46" src="https://user-images.githubusercontent.com/73704491/153241155-84281814-c7b6-454e-9a4e-279f0f912b65.png">


I hope you can help me in applying the correct Datatables($contacts_array) using my raw query :)

**Comment by yajra** [comment]
You need to enclose your SQL with parenthesis `(sql)` to make it a sub-query table.

```sql
select * from (select * from users)
```

**Comment by Echecivuole** [comment]
> You need to enclose your SQL with parenthesis `(sql)` to make it a sub-query table.
> 
> ```sql
> select * from (select * from users)
> ```

Hello, thanks for the help. Also using this query I get error: 

```
$contacts_array = DB::table(DB::raw('(SELECT * FROM app_contact)'));
return datatables($contacts_array)->toJson();
``
<img width="520" alt="Schermata 2022-02-10 alle 07 20 41" src="https://user-images.githubusercontent.com/73704491/153349531-40df938e-8c39-4399-b831-0f07f0b97f5a.png">
`

Not getting why at my end I still see errors...

**Comment by Echecivuole** [comment]
> > You need to enclose your SQL with parenthesis `(sql)` to make it a sub-query table.
> > ```sql
> > select * from (select * from users)
> > ```
> 
> Hello, thanks for the help. Also using this query I get error:
> 
> ```
> $contacts_array = DB::table(DB::raw('(SELECT * FROM app_contact)'));
> return datatables($contacts_array)->toJson();
> ```
> 
> <img alt="Schermata 2022-02-10 alle 07 20 41" width="520" src="https://user-images.githubusercontent.com/73704491/153349531-40df938e-8c39-4399-b831-0f07f0b97f5a.png">
> 
> Not getting why at my end I still see errors...

Sorry, I have MariaDB. It could be the source of the issue?

**Comment by yajra** [comment]
You might need to add a table alias, it depends on your RDBMS, I'm using Oracle and works fine. 

TIP: try executing the generated SQL directly on your sql engine and fix it there. Once confirmed working, move it to Laravel via raw sql or query builder.

```php
DB::table(DB::raw('(SELECT * FROM app_contact) as contacts'));
```

**Comment by Echecivuole** [comment]
> You might need to add a table alias, it depends on your RDBMS, I'm using Oracle and works fine.
> 
> TIP: try executing the generated SQL directly on your sql engine and fix it there. Once confirmed working, move it to Laravel via raw sql or query builder.
> 
> ```
> DB::table(DB::raw('(SELECT * FROM app_contact) as contacts'));
> ```

ok thanks it seems that using alias it works. But in the below query I have last issue: how to pass variables as parameters as per Laravel best practice:

`DB::table(DB::raw('(SELECT * FROM app_contact WHERE contact_id=?) as contacts',[$contact_id]));`

is not the correct format.
thanks!

**Comment by Echecivuole** [comment]
> > You might need to add a table alias, it depends on your RDBMS, I'm using Oracle and works fine.
> > TIP: try executing the generated SQL directly on your sql engine and fix it there. Once confirmed working, move it to Laravel via raw sql or query builder.
> > ```
> > DB::table(DB::raw('(SELECT * FROM app_contact) as contacts'));
> > ```
> 
> ok thanks it seems that using alias it works. But in the below query I have last issue: how to pass variables as parameters as per Laravel best practice:
> 
> `DB::table(DB::raw('(SELECT * FROM app_contact WHERE contact_id=?) as contacts',[$contact_id]));`
> 
> is not the correct format. thanks!

Solved using ->setBindings()


THANKS!
