### ISSUE TITLE
Error while search $or/$and/$nor entries need to be full objects Laravel Datatable Mongo

### ISSUE THREAD

**Issue by naveenmanikya** [yajra/laravel-datatables#2741]
### Summary of problem or feature request

Searching for any matching string in the Datatable listing is throwing back this error for Mongodb data. 
"Exception Message:\n\n$or\/$and\/$nor entries need to be full objects"
The query on Object using "like" is returning some results in "recordsTotal" but giving zero results in "recordsFiltered" on console network response.

### Code snippet of problem

```
if( $search_term ){
     $data = Model : : where( 'category', 'like', '%'.$search_term.'%' );
  }
```
#### Network Response
```
draw: 1, recordsTotal: 360, recordsFiltered: 0, data: [],…}
data: []
draw: 1
error: "Exception Message:\n\n$or/$and/$nor entries need to be full objects"
recordsFiltered: 0
recordsTotal: 360
```

### System details

- Operating System : Windows 10
- PHP Version : 8.0.14
- Laravel Version: 8.83.0
- Laravel-Datatables Version: ~9.0

**Comment by yajra** [comment]
MongoDB is not fully supported as I think it has its own query builder implementation. Maybe try using a manual search?

https://yajrabox.com/docs/laravel-datatables/master/manual-search#without-global-search
