### ISSUE TITLE
[Datatable 9.19] Does not render HTML

### ISSUE THREAD

**Issue by duonghoaikhanh** [yajra/laravel-datatables#2745]
I'm using Laravel 8 + yajra datatables version 9.19, but my table is not rendering HTML code. 
Just have column action is render HTML but other column is not rendering.

![image](https://user-images.githubusercontent.com/14960858/156319160-a3ab9bce-5337-485d-a306-556e76c574cf.png)

This is my code

```php
return DataTables::of($totalDataUser)
		->addIndexColumn()
		->addColumn('action_suspended', function ($row) {
			$textButton = '送信中';
			if (intval($row['suspended']) === 1) {
				$textButton = '停止中';
			}
			return '<button type="button" class="btn btn-success btn-sm user-suspended">'. $textButton .'</button>';
		})
		->addColumn('action', function($row){
			$editUrl = url('users/' . $row['id'] . '/edit');
			$actionBtn = '<a href="'.$editUrl.'" class="edit btn btn-success btn-sm mb-2">編集</a>';
			return $actionBtn;
		})
		->editColumn('sex', function ($row) {
			return intval($row['sex']) === 1 ? '女性' : '男性';
		})
		->rawColumns(['action_suspended', 'action'])
		->make(true);
```

- Operating System
- PHP Version 7.3
- Laravel Version 8
- Laravel-Datatables Version 9.19

**Comment by duonghoaikhanh** [comment]
Also I try to use escapeColumns it not working too.
```
->escapeColumns([])
->make(true);
```

**Comment by dennsliu** [comment]
you can add 
->rawColumns(['default_banner','action','status'])
        ->make(true);
it work for me
