### ISSUE TITLE
yajra all in one packge error in larave 9

### ISSUE THREAD

**Issue by arbabi2010** [yajra/laravel-datatables#2746]
Hi , when I want to install  yajra/laravel-datatables:^1.5 , i get error like below text
`    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a part
ial update and that version does not match. Make sure you list it as an argument for the update command.
`

I install datatable version 9 but when i run php artisan datatables:make , i get `  There are no commands defined in the "datatables" namespace.  
` error

and when i use from service Implementation i get error `Class "Yajra\DataTables\Services\DataTable" not found`  in laravel debug
### Code snippet of problem

- Operating System
- PHP Version 8.0.2
- Laravel Version 9
- Laravel-Datatables 9

**Comment by schonhoff** [comment]
Hi,
if you got an error on your composer command, you need to look up your dependencies. Somewhere in your dependencies the package "psr/simple-cache" is set to 3.0. I think it is set by a fresh laravel installation. But Laravel 9 is working with psr/simple-cache ^1.0 also so you might include this to your composer.json .
