### ISSUE TITLE
Laravel Session Is not working Properly After Using Laravel Datatables

### ISSUE THREAD

**Issue by balamurugan1991** [yajra/laravel-datatables#2760]
After Installing Laravel datatables session is not working properly in local environment.
We are using Ajax Method to get the Data tables. But Before Using Yajra, All Session Flash messages are working properly in local. But After yajra, some session Management is handled for filter records and pagination all of the details stored and retrieved when i press back button.

My issue is after installing yajra. Flash success and Flash Error message's Not able get from "VIEW". Randomly works in local. Sometimes working, Lots of times not working. That's why Model popup success and error message's not shown. I cant able to figure that issue. Currently am using session file based.

Anybody have a idea of that issue. Thanks

- Operating System                  - Windows 8.1
  Xampp - V.3.3.0 PHP Version  - 7.4.24
- Laravel Version                       - 8
- Laravel-Datatables Version    - 9.19.0

**Comment by balamurugan1991** [comment]
Anybody There to Resolve My Issue?.   Admin Please take a look immediately.

**Comment by yajra** [comment]
Can you provide some snippets to reproduce the issue? But I suspect this is an environment issue like the known issue on [php artisan serve](https://github.com/yajra/laravel-datatables#php-artisan-serve-bug).

**Comment by balamurugan1991** [comment]
> Can you provide some snippets to reproduce the issue? But I suspect this is an environment issue like the known issue on [php artisan serve](https://github.com/yajra/laravel-datatables#php-artisan-serve-bug).

What snippet you want, i ill share. 
In production i cant able to check this issue.
In local and dev server only i can able to produce this issue. Local serve run from php artisan serve, But in dev its a Ubuntu Os not use artisan serve.
I try to print the Local Storage. After removing Local storage, Local storage is not cleared. Can you guide me on that ?
