### ISSUE TITLE
Additional variables

### ISSUE THREAD

**Issue by sirago** [yajra/laravel-datatables#277]
Is there any way to pass along additonal variables with the standards?:

draw:
recordsTotal:
recordsFiltered:
data:

**Comment by yajra** [comment]
Good question.. Currently there is no way to add variables on the standard response. I guess this is a good enhancement that should be implemented. Thanks!

But if you urgently need this. I think a workaround would be catching the response and then manipulate and add the necessary data. A workaround something like below:

```php
$users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

$response = Datatables::of($users)->make(true);	
$data     = $response->getData(true);
$data['key'] = 'value';

return new JsonResponse($data);
```

**Comment by yajra** [comment]
I think it would be nice if we could have something like:
```php
$users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

return Datatables::of($users)
	->with([
		'key1' => 'value1',
		'key2' => 'value2',
	])
	->make(true);	
```

Tagging as for enhancement.. Will try to implement this. Thanks!

**Comment by sirago** [comment]
Great, response. Thank you!

**Comment by yajra** [comment]
Added on upcoming v6.0 release. Thanks!

**Comment by yizhihou2** [comment]
Is this tagging feature already supported in 6.0? Thanks.

**Comment by yajra** [comment]
Yes, snippet below is already supported on v6.0.

```php
$users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

return Datatables::of($users)
    ->with([
        'key1' => 'value1',
        'key2' => 'value2',
    ])
    ->make(true);   
```

**Comment by dcrownak** [comment]
return Datatables::of($users)
    ->with([
        'key1' => 'value1',
        'key2' => 'value2',
    ])
    ->make(true); 


how i get the value1

**Comment by raulidavid** [comment]
How to print in blade ???

**Comment by dekos** [comment]
Y
