### ISSUE TITLE
Setting Up responseCallback.

### ISSUE THREAD

**Issue by Nuhel** [yajra/laravel-datatables#2777]
How to set responseCallback in datatable class . I saw there is a function named 'response' to set this, but i am confused from where to call this. So I override render function and called inside it. My code is attached below

```php
public function render($view, $data = [], $mergeData = [])
    {
        $this->response(function($data){
            return ($this->makeResponse($data->toArray()));
        });
        return parent::render($view,$data,$mergeData);
    }
```

### System details

- Operating System: MacOs
- PHP Version: 8.0..12
- Laravel Version 8.75
- "yajra/laravel-datatables": "^1.5",
   "yajra/laravel-datatables-buttons": "^4.0",
   "yajra/laravel-datatables-editor": "^1.0",
   "yajra/laravel-datatables-oracle": "^9.19"

**Comment by yajra** [comment]
Added a test for this feature via https://github.com/yajra/laravel-datatables-buttons/commit/59e71d12f383dd7b0e7d83e4caee47fce2dcbd0b.

```php
        $router->get('/users/response', function (UsersDataTable $dataTable) {
            return $dataTable->response(function (Collection $data) {
                $data['recordsTotal'] = 2;
                $data['recordsFiltered'] = 1;

                return $data;
            })->render('tests::users');
        });
```
