### ISSUE TITLE
There are no commands defined in the "datatables" namespace

### ISSUE THREAD

**Issue by fanjavaid** [yajra/laravel-datatables#278]
Hello i have this error when run : 
```
There are no commands defined in the "datatables" namespace
```

I already publish vendor using this  command : 
```
php artisan vendor:publish --provider="yajra\Datatables\DatatablesServiceProvider"
```

I'm using **Laravel 5.1**

**Comment by yajra** [comment]
@fanjavaid what version of datatables are using? Please use dev-develop branch if you want to use DataTable as Service. See this tuts for ref: http://datatables.yajrabox.com/service.

Also please note that I have changed the namespace earlier https://github.com/yajra/laravel-datatables/issues/265 from `yajra\Datatables` to `Yajra\Datatables` (capital Y). Thanks!

**Comment by fanjavaid** [comment]
Ooh :D okay it works now. Thank you.
