### ISSUE TITLE
search for single quotes does not show any results

### ISSUE THREAD

**Issue by mfahey79** [yajra/laravel-datatables#2782]
### Discussed in https://github.com/yajra/laravel-datatables/discussions/2781

<div type='discussions-op-text'>

<sup>Originally posted by **mfahey79** May  9, 2022</sup>
When data has a single quote I.E. O'Brien if you search for a single quote it does not find it.

In the normal datatables package it does work.
</div>

**Comment by yajra** [comment]
Answered in discussion, closing.
