### ISSUE TITLE
Datatable Search with filter options

### ISSUE THREAD

**Issue by mpapado3** [yajra/laravel-datatables#2785]
### Summary of problem or feature request

We had a working datatable with the default search function and we implemented an extra filter option to limit the results based on the filters.
Once we implemented the filters the default search stopped working. If we disable the ->filter() option the search works again.

How we can have both filter and search working together?

### System details

- Operating System: centos Linux 8.5
- PHP Version: 8.0.18
- Laravel Version: 8
- Laravel-Datatables Version
    "yajra/laravel-datatables": "^1.5",
     "yajra/laravel-datatables-oracle": "~9.0"

**Comment by mpapado3** [comment]
In order the search to work I have added a named property on the default search field and then on the filter options on the controller together with the rest filters I have added the search.

**Comment by mpapado3** [comment]
In order the search to work I have added a named property on the default search field and then on the filter options on the controller together with the rest filters I have added the search.

**Comment by yajra** [comment]
You can use https://yajrabox.com/docs/laravel-datatables/master/manual-search#with-global-search or https://yajrabox.com/docs/laravel-datatables/master/filter-column for this. Thanks!
