### ISSUE TITLE
Loads all the data from database on server but works well on local environment.

### ISSUE THREAD

**Issue by anuzbvbmaniac** [yajra/laravel-datatables#2788]
### Summary of problem or feature request
I have used this package for a quite a long time but I am getting a weird issue on a live server. On local environment the response from the controller is correct and response data count is correct for whatever I put in pageLength value. But in Live Server, it is fetching all 20,000+ records.

If I use 10 as a page length then the first query is fast i.e normal, but when i paginate to page 2, again all the records are fetched. and the response size is again huge.

`Local - Response Size is 7kb`
<img width="879" alt="Screen Shot 2022-05-20 at 3 14 26 PM" src="https://user-images.githubusercontent.com/25082225/169499456-84fcf371-ef87-4415-9cf4-861b5bf3fb6a.png">

`Live - Response Size is 80mb`
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/25082225/169499919-401089e0-0744-4e2d-b148-709474712d0f.png">

`-- BlogController.php`
```php
$articles = Article::query()
            ->with(['media', 'editor', 'categories', 'author', 'views'])
            ->select('articles.*')
            ->$scope();

return DataTables::of($articles)
            ->editColumn('title', function ($data) {
                    return '<div>' . $data->title . '</div>';
                })
            ->addIndexColumn()
            ->rawColumns(['title'])
            ->make(TRUE);
```

`-- Blade File`

```js
$(document).ready(() => {
    let articleTable = $("#article-tables").DataTable({
        processing: true,
        serverSide: true,
        "scrollX": true,
        "scrollY": false,
        responsive: false,
	paging: true,
        pageLength: 50,
        ajax: {
            url: "{{ route('api.cms.article.datatables') }}",
            type: "GET",
	},
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'title', name: 'title', orderable: false},
        ],
        "fnDrawCallback": function () {
            initSwitchToggler()
            initTooltip()
            initPopOver()
        }
    });
});
```

- Operating System : Oracle Linux (Live) | MacOs (Local)
- PHP Version : 8.0.19
- Laravel Version : 8.83
- Laravel-Datatables Version: 1.5

**Comment by yajra** [comment]
Looks like double encoding is happening in your url and it is server configuration issue. See https://github.com/yajra/laravel-datatables/issues/1210

**Comment by anuzbvbmaniac** [comment]
I tried changing .htaccess file and issue still persist.
`RewriteRule ^(.*)/$ /$1 [L,R=301,NE]`

Tried and compared nginx configuration with all commented codes, still no success 😥
