### ISSUE TITLE
Query run twice

### ISSUE THREAD

**Issue by adeiming** [yajra/laravel-datatables#2793]
Please help, my query runs twice before I used mysql 8 and laravel 8 databases it was not a problem, but not with this version

My code:
```
$data = Sekolah::query();

return DataTables::of($data)->make();
```

- Operating System : Windows 11 x64
- PHP Version : 8.1.2
- Laravel Version : 9
- Laravel-Datatables Version : 10
- Database : Postgre v14

<img width="875" alt="image" src="https://user-images.githubusercontent.com/13284072/171978535-614889f1-4ed9-4316-a9a0-6f0331e249d5.png">

**Comment by adeiming** [comment]
today in production, xhr runs twice

<img width="960" alt="image" src="https://user-images.githubusercontent.com/13284072/172113534-bf1b79d5-a062-4def-8b77-8c85afecb074.png">

if I use empty data from array it gets messy

<img width="943" alt="image" src="https://user-images.githubusercontent.com/13284072/172113876-36e4ccc9-7aac-450a-a507-b30525d181f0.png">

finally I decided to downgrade to v9, and it went really well

**Comment by yajra** [comment]
Thanks for reporting, I haven't encountered the same issue since I upgraded to v10 but will check/fix this as soon as I can.

**Comment by theonly27** [comment]
> Thanks for reporting, I haven't encountered the same issue since I upgraded to v10 but will check/fix this as soon as I can.

Thanks sir Aryjay, try to use laravel debugbar, it shows multiple query.

**Comment by yajra** [comment]
@adeiming I think the 2 queries are expected since we need count 2x. First is for total count and 2nd is for filtered records count. On initial load, it is expected to have the same query.

XHR runs twice is another thing and I think is a javascript issue. Can't replicate this.

**Comment by adeiming** [comment]
in laravel debugbar, the same query will be marked with a yellow background, like the image above, also in the previous version when using an empty array there was no error on the page number, unlike this version

**Comment by yajra** [comment]
Were you able to update to latest version available? Several patches added. Also, the change in behavior might be related to this PR https://github.com/yajra/laravel-datatables/pull/2778.

Can't replicate the null recordsFiltered, can you provide script on how to replicate it?

**Comment by adeiming** [comment]
> Were you able to update to latest version available? Several patches added. Also, the change in behavior might be related to this PR #2778.
> 
> Can't replicate the null recordsFiltered, can you provide script on how to replicate it?

like this:
```
return DataTables::of([])->make()
```

become:
```
{
  "draw": 1,
  "recordsTotal": 0,
  "recordsFiltered": null,
  "data": [],
  "input": {
    "draw": "1",
    "columns": [
      {
        "data": "uuid",
        "name": null,
        "searchable": "false",
        "orderable": "false",
        "search": {
          "value": null,
          "regex": "false"
        }
      },
      {
        "data": "tanggal",
        "name": "pendaftaran.updated_at",
        "searchable": "true",
        "orderable": "true",
        "search": {
          "value": null,
          "regex": "false"
        }
      },
      {
        "data": "nisn",
        "name": "p.nisn",
        "searchable": "true",
        "orderable": "true",
        "search": {
          "value": null,
          "regex": "false"
        }
      },
      {
        "data": "nama_lengkap",
        "name": "p.nama_lengkap",
        "searchable": "true",
        "orderable": "true",
        "search": {
          "value": null,
          "regex": "false"
        }
      },
      {
        "data": "jk",
        "name": "p.jk",
        "searchable": "true",
        "orderable": "true",
        "search": {
          "value": null,
          "regex": "false"
        }
      },
      {
        "data": "asal_sekolah",
        "name": "rs.name",
        "searchable": "true",
        "orderable": "true",
        "search": {
          "value": null,
          "regex": "false"
        }
      },
      {
        "data": "aksi",
        "name": null,
        "searchable": "false",
        "orderable": "false",
        "search": {
          "value": null,
          "regex": "false"
        }
      }
    ],
    "order": [
      {
        "column": "1",
        "dir": "asc"
      }
    ],
    "start": "0",
    "length": "10",
    "search": {
      "value": null,
      "regex": "false"
    },
    "_": "1656035512995"
  }
}
```

if I compare with version 9, ```recordsFiltered``` is not NULL, it's 0

**Comment by adeiming** [comment]
> <img alt="image" width="507" src="https://user-images.githubusercontent.com/13284072/175445938-37111e09-e2e9-4df0-a569-38900bb5f9ed.png">
> 
> as you can see, this is now 3 queries, the same 2 with a yellow background.
> 
> I hope this helps

I already updated the version when running this

**Comment by yajra** [comment]
Yes 2 queries for count then another one for the actual dataset, expected behavior.

I think the issue here is on null recordsFiltered only. Will review this, thanks!
