### ISSUE TITLE
get the columnName ,see url

### ISSUE THREAD

**Issue by openvast** [yajra/laravel-datatables#280]
see the post/GET param

columns[0][data]

type_name
columns[0][name]

columns[0][orderable]

true
columns[0][search][regex]

false
columns[0][search][value]

columns[0][searchable]

true
columns[1][data]

realname
columns[1][name]

columns[1][orderable]

true
columns[1][search][regex]

false
columns[1][search][value]

ad
columns[1][searchable]

true
columns[2][data]

add_time
columns[2][name]

columns[2][orderable]

true
columns[2][search][regex]

false
columns[2][search][value]

columns[2][searchable]

false

https://github.com/yajra/laravel-datatables/pull/279

**Comment by yajra** [comment]
The recommended approach is to declare column name on your js file. Relying on select order of the query is not flexible enough to handle most of the requirements when using dataTables.js and it's advance features. This is also the reason why most of my demo declares the `columns` in javascript. Like this demo for instance: http://datatables.yajrabox.com/eloquent/basic-object
