### ISSUE TITLE
Get Row Index Inside addColumn Method

### ISSUE THREAD

**Issue by core45** [yajra/laravel-datatables#2804]
### Summary of problem or feature request

I need the first and last row in the table in addColumn for the logic inside it like using the blade template $loop->first or $loop->iteration.
I can find the iteration indes anywhere. Please halp

### Code snippet of problem

```
$query = ProductCategory::query()->select(sprintf('%s.*', (new ProductCategory())->table));

$table = Datatables::of($query)->addIndexColumn();

$table->addColumn('sort', function($row) {
        if ($row->first) {
            'first'
        } elseif ($row->last) {
            'last'
        } else {
            'middle'
        }
    })
```

### System details

- Operating System
- PHP Version 8.1
- Laravel Version 9.17
- Laravel-Datatables Version 9.20.0

**Comment by yajra** [comment]
I think this is not yet supported. But maybe a workaround would be to manipulate the array response before returning.

Something like below but note that this is not tested and just an idea:

```php
    $response = Datatables::of($query)->addIndexColumn()->toArray();

    foreach ($response['data'] as &$row) {
        $row['sort'] = 'todo';
    }

    return $response;
```
