### ISSUE TITLE
Export to excel using post method not working

### ISSUE THREAD

**Issue by devlabs11** [yajra/laravel-datatables#2805]
### Summary of problem or feature request

I am using `dom: 'Blfrtip'` for inserting "Export to excel" button. It's working fine with GET method. But when method is changed to POST `type:"post"` as shown in the script below it's not working.

### Code snippet of problem

```
<script type="text/javascript">
$(function () {
    
    var token="{{ csrf_token() }}"; 

    var table = $('.yajra-datatable').DataTable({
        processing: true,
        serverSide: true,
        ajax:{
            url: "{{ route('ulist') }}",
		  type:"post",
                  data:function(data) {
		          data._token=token;
                  },
        },
        error: function(data){
            console.log(data);
        }, 
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'rate', name: 'rate'},
        ],
        dom: 'Blfrtip',
        buttons: [
            {
                extend: 'excel',
                text: 'Export',
            },
        ]
    });
	});
</script>
```

### System details

- Server :  IIS
- PHP version :  7.1.29
- Laravel Version : Laravel Framework 8.6.0
- Laravel-Datatables Version :   
                                                  yajra/laravel-datatables-buttons   v4.13.3
                                                  yajra/laravel-datatables-html        v4.41.1
                                                  yajra/laravel-datatables-oracle      v9.11.0

**Comment by yajra** [comment]
Try using `postExcel` instead.

```
buttons: [
            {
                extend: 'postExcel',
                text: 'Export',
            },
        ]
```
