### ISSUE TITLE
Display Row Number with DataTables as a Service

### ISSUE THREAD

**Issue by ZAZmaster** [yajra/laravel-datatables#281]
Something like this https://github.com/yajra/laravel-datatables/issues/53 but with DataTables as a Service possibly?

**Comment by yajra** [comment]
@ZAZmaster, YES! latest version are (should be) backward compatible. Just declare it inside the `ajax` method.

**Comment by ZAZmaster** [comment]
@yajra Can you show an example?

**Comment by yajra** [comment]
Something like below should work.

```php
public function query()
{
	DB::statement(DB::raw('set @rownum=0'));
	$users = User::select([
		DB::raw('@rownum  := @rownum  + 1 AS rownum'),
		'id',
		'name',
		'email',
		'created_at',
		'updated_at']);

	return $this->applyScopes($users);
}
```

**Comment by ambrooo** [comment]
Hi, any ideea how to do this on union tables?

**Comment by inghggw** [comment]
This does not work when using an orderBy in the query, any ideas?

**Comment by NicoAfandi11** [comment]
why this method doesn;t work on sql server?
on mysql this method work perfectly fine.

**Comment by deanlaw** [comment]
MS SQL Server has a build-in row number function, the example above is a workaround for MySQL which does not have a built-in function. Take a look at https://docs.microsoft.com/en-us/sql/t-sql/functions/row-number-transact-sql for the proper usage. You would need to replace the raw DB call in yajra's example with one using MS SQL's row_number() function. You would also remove the DB:statement line as well, as it would not be needed.
