### ISSUE TITLE
Want To Add Check Box but note working?

### ISSUE THREAD

**Issue by hasibul442** [yajra/laravel-datatables#2813]
### Summary of problem or feature request

I need To add A check box which will showed that is user request accept or pending. If Accept It will show checked id pending will show uncheck. 

but every time it showed unchecked if Status active or pending in database

### Code snippet of problem

->addColumn('status', function ($item) {
                    $togolebutton = '<input  ' .$item->status.' == "Active" ? "checked" : ""}}   type="checkbox" class="status" id="status"  data-id="'.$item->id.'" />';
                    return $togolebutton;
                })
### System details

- Operating System : Windows 10
- PHP Version :  7.3
- Laravel Version : 8
- Laravel-Datatables Version: 9.3

**Comment by Jagdish-J-P** [comment]
I guess it should be 
`$togolebutton = '<input ' . ($item->status == "Active" ? "checked" : "") .' type="checkbox" class="status" id="status" data-id="'.$item->id.'" />';`

**Comment by hasibul442** [comment]
I also try this way and it also work              
        ```
if($item->status == 'Active'){
                        $togolebutton = '<input type="checkbox" name="status" id="status" data-id="' . $item->id . '" data-status="' . $item->status . '" class="toggle-class status" checked>';
                     }
                     else{
                         $togolebutton = '<input type="checkbox" name="status" id="status" data-id="' . $item->id . '" data-status="' . $item->status . '" class="toggle-class status" >';
                    }
```
