### ISSUE TITLE
Filter Polymorphic Relation with different column name

### ISSUE THREAD

**Issue by Jagdish-J-P** [yajra/laravel-datatables#2817]
### Summary of problem or feature request

I am having 3 tables.

**Users Table**

* id
* first_name
* last_name
* other columns

**Parties Table**

* id
* party_name
* other columns

**Letters Table**

* id
* receiveable_type
* receiveable_id
* subject
* other columns

I want to show and filter result like below

#ID | Received From | Subject | Created At
-- | -- | -- | --
1 | User First Name Last Name | Subject 1 | 11-07-2022
2 | Party Party Name| Subject 2 | 10-07-2022
3 | Guest 2 | 04-06-14 14:01:00 (Order ID) | 09-07-2022

I am able to get name using getNameAttribute in Model. But while searching it throws error like invalid column "name" in users table or parties table.

### System details

- Operating System: Windows 11
- PHP Version: 8.1
- Laravel Version: 9.1
- Laravel-Datatables Version: ~9.0

**Comment by yajra** [comment]
You can use [filter column](https://yajrabox.com/docs/laravel-datatables/master/filter-column) and apply the necessary filter on SQL level.
