### ISSUE TITLE
Add sub headers 

### ISSUE THREAD

**Issue by PhHitachi** [yajra/laravel-datatables#2823]
Hi, how can i add sub headers like this if possible

![image](https://user-images.githubusercontent.com/44565442/180638047-6774e65d-938d-45fa-b59f-27fc12cca928.png)

**Comment by yajra** [comment]
Using the html builder? Currently not possible but you can always use the manual html to set the headers. Just be sure to use the correct table id

```php
// html builder
public function html() {
  return $this->builder()->setTableId('users-table')...
}

// view.blade.php

<table id="users-table">
<thead>
-- your th here
</thead>
</table>
