### ISSUE TITLE
Export PDF with child row

### ISSUE THREAD

**Issue by hardikiqlance** [yajra/laravel-datatables#2824]
### Summary of problem or feature request

I am using yajaradata table with expanded child row detail.

I am not getting child row detail in exported pdf, can you please help me?
or reference URL

### System details

- Operating System
- PHP Version 7.4
- Laravel Version 8

Here is my attached table screenshot.
![Screenshot_5](https://user-images.githubusercontent.com/52062664/181437665-cde1db9f-c355-4b81-a84a-13eb45eb1b05.png)

**Comment by samadra** [comment]
@hardikiqlance  http://live.datatables.net/hepopote/1/edit
