### ISSUE TITLE
How to change row group date format and row color?

### ISSUE THREAD

**Issue by DevMushref** [yajra/laravel-datatables#2826]
I grouped a table by date using `rowGroup` parameter:

```
public function html()
    {
        return $this->builder()
            ->setTableId('kpi-table')
            // ->addCheckbox([
            //     'data' => 'Checkbox',
            //     'width' => '10px',
            // ])
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->dom('Bfrtip') //lfrtipB, lfrtip, lrtip, rtip, Bfrtip
            ->stateSave(true)
            ->responsive()
            ->autoWidth(false)
            ->parameters([
                'scrollX' => true,
                'lengthMenu' => [
                    [10, 25, 50, 100, -1],
                    ['10 rows', '25 rows', '50 rows', '100 rows', 'Show all'],
                ],
                'buttons' => [
                    'pageLength',
                    'pdf',
                    'print',
                    'excel',
                    'copy',
                    'colvis',
                ],
                'rowGroup' => [
                    'dataSrc' => 'publishDate'
                ],
                //'select' => ['style' => 'os'],
            ])
            ->addTableClass('align-middle table-row-dashed fs-6 gy-5');
    }
```

![image](https://user-images.githubusercontent.com/25293489/181871459-970e5932-f347-4b45-86ea-ea0a72e52a2b.png)

I want to keep the date column as is, but format the group row as **month** (e.g. Jan, Feb).

### **The logic behind this/ trying to do:**
Group daily entries by months.

I tried to use `Carbon` withing the `rowGroup `but returned errors

How to format the row group date and color it?

**Comment by yajra** [comment]
You can use [setRowClass](https://yajrabox.com/docs/laravel-datatables/master/row-options#row-class) for styling and [addColumn](https://yajrabox.com/docs/laravel-datatables/master/add-column) for the rowGroup src.

**Comment by DevMushref** [comment]
Nice, thank you! But how can I style the row group title itself?

I created a column named rowGroupByDate and made it the group source in the datatable, but for the setRowClass it's coloring the rows instead of the row title (e.g. "Aug 2003")

```
->addColumn('rowGroupByDate', function($KPI) {
                        return Carbon::parse($KPI->publishDate)->format('M, Y');
                    })
                    ->setRowClass(function ($KPI) {
                        return $KPI->rowGroupByDate = 'alert-warning';
                    })
```
![image](https://user-images.githubusercontent.com/25293489/182017040-47724cae-1003-464e-b7ab-925aff853563.png)

**Comment by DevMushref** [comment]
I got it to work.

First off I created a column called `rowGroupByDate` then made it as a `rawColumns`. Raw columns accepts html code into it!

The `rowGroupByDate` is where I made a div with background color and a padding of 5px (Bootstrap classes):

```
->rawColumns(['action', 'level', 'rowGroupByDate'])
->addColumn('rowGroupByDate', function($KPI) {
  return "<div class='bg-secondary p-5'>" . Carbon::parse($KPI->publishDate)->format('M, Y') . "</div>";
   })
```
