### ISSUE TITLE
How to test quick-starter implementation

### ISSUE THREAD

**Issue by wikigods** [yajra/laravel-datatables#2828]
### Summary of problem or feature request

how to test quick-starter implementation

### Code snippet of problem

Good morning, could you please guide me on how to test this index method.
![Screenshot_32](https://user-images.githubusercontent.com/71094046/183776239-084956a0-1e6c-4d3f-9d84-da7f916bdc04.png)
![Screenshot_33](https://user-images.githubusercontent.com/71094046/183776242-f239a077-c5c6-4695-ad1e-0fbdeba25a07.png)

I have something like this but I would like to test methods that are inside "ProjectDataTable" and "{{$dataTable->table()}}", "{{$dataTable->scripts()}}", sorry I am new using test. 
![Screenshot_35](https://user-images.githubusercontent.com/71094046/183776298-9252ec10-10e1-4bf4-af89-c92eabfab309.png)
![Screenshot_34](https://user-images.githubusercontent.com/71094046/183776318-e5c08cef-e1ca-40c4-a52e-be8dd4f30e5a.png)

### System details

- Operating System: Windows 10
- PHP Version: 8.1 
- Laravel Version: 9.23.0
- Laravel-Datatables Version: 10.1.2
- Laravel-Datatables-Buttons Version: 9.0.10

**Comment by yajra** [comment]
See the package test that I created via https://github.com/yajra/laravel-datatables-buttons/blob/master/tests/DataTableServiceTest.php. Not full coverage test but should give you some hint. All other packages have unit tests too, just browse the repos.
