### ISSUE TITLE
Possible conflicts with "Automatically register 3rd party facades dependency.."

### ISSUE THREAD

**Issue by geraldb-nicat** [yajra/laravel-datatables#283]
hi there!

first of all many thanks for your work on this great package! :)

i've just tried out the current development-version of v6, and saw, that since a recent commit, you are registering various 3rd party facades in your service provider. i'm not so sure, if this is a good idea, because conflicting facades with the same name might already be in use in the same application.e.g. in my case i'm using the alias "Form" for my own form-builder. there might be many other use-cases, where this could be problematic.

i must admit, i'm fairly new to laravel and do not know, what the "best practice" is regarding definition of aliases within packages, but to avoid conflicts, it is maybe better to not use aliases in the packages itself at all, but the actual classes of 3rd party packages imported via use-statements. this would leave the "app" itself to be the sole responsibility of defining aliases and avoiding conflicts.

sorry in advance, if i overlooked the concrete reasons for why you are doing this.

best wishes
gerald

**Comment by yajra** [comment]
@geraldb-nicat,

Thanks for the feedback. I just registered the aliases for convenience without realizing that it may conflict on some installations. I saw some packages doing this approach and so I tried and give it a shot. 

Anyways, will remove the facade registrations to avoid possible conflicts like you said. Appreciate the feedbacks.. Let me know if you find something else. ^_^

Thanks,

@yajra

**Comment by geraldb-nicat** [comment]
many thanks, yajra!
