### ISSUE TITLE
Do I have to use jQuery as it says on the GitHub page?

### ISSUE THREAD

**Issue by mariusberget92** [yajra/laravel-datatables#2830]
Probably a bit stupid question. 😂 But is it possible to use only the PHP side of this? I am creating a reactive table component in Vue and would only need the JSON data from a DataTable. I saw it says **jQuery DataTables API for Laravel** on the GitHub page and was wondering if I would have to use jQuery or could just simply build my own Vue table? Asking before I implement it in my project. I would use Axios instead of the AJAX stuff (think they're the same but I like Axios better).

**Comment by yajra** [comment]
I think you can use the package without jquery and datatables library. The challenge is you need to emulate the payload being sent by dataTables for it to be processed by the package.

Used to have plans to make a request adapter that will convert other grid library payload to dataTables request but haven't had the time to do it yet.

**Comment by mariusberget92** [comment]
Alright. I see. Thanks! :)
