### ISSUE TITLE
Searching not working when value is decrypt

### ISSUE THREAD

**Issue by rzlmtrt** [yajra/laravel-datatables#2831]
### Summary of problem or feature request

 
I have dashboard page, and i'm using yajra datatables serverside to show the data. But i have problem with quick searching. I can search name, phone number, or other data, but i have problem with Encrypt Data. I have one column (basics.identification_number) that Encrypt. I use Traits\Encryptable. to show the value, i use decrypt function. If i didn't decrypt, i can search the identification_number with encrpt value. anyone know how to solve this? thank you in advance

$value=Crypt::decrypt($data->identification_number);

here is my Controller

### 
$data = DB::table('processings')
   ->join('basics', 'basics.id_customer', '=', 'processings.id_customer') 
   ->select(['basics.identification_number','basics.name','basics.phone', 
             'processings.id_customer','processings.status'])
   ->where('processings.status', '>=', '2');

    return DataTables::of($data)
        ->addIndexColumn()
        ->addColumn('identification_number', function($data) {
            $value=Crypt::decrypt($data->identification_number);
            return $value;
        })

        ->addColumn('name', function($data) {
            $value=$data->name;
            return $value;
        })
     
        ->addColumn('phone', function($data) {
            $value=$data->phone;
            return $value;
        })

        ->addColumn('status', function($data) {
            if($data->status==2){
                $value= 'Approved';
            }
            else if($data->status==3){
                $value= 'Rejected';
            }
                
            return $value;
        })

        ->rawColumns(['identification_number','phone','status','name'])
        ->make(true);

and here is my blade

### <script>
    $(document).ready(function(){
        $('#user_table').DataTable({
        processing: true,
        serverSide: true,
        scrollY:        true,
        scrollX:        true,
        scrollCollapse: true,
        paging:         true,
        ajax: {
            url: "{{url('/')}}/admin/data",
            type: "GET",
            'data': function ( d ) {
                d._token = "{{ csrf_token() }}";
            }
        },
        columns: [
            {
                data: 'DT_RowIndex',
                name: 'DT_RowIndex',
                orderable: false, 
                searchable: false
            },
            {
                data: 'identification_number',
                name: 'identification_number',
            },
            {
                data: 'id_customer',
                name: 'id_customer'
            },
            {
                data: 'name',
                name: 'name',
            },
            {
                data: 'phone',
                name: 'phone'
            },
        ]
    });
});

previously, my code like this. but the loading was so slow if i use get();. but the quick searching is working fine. if i removed ->get();. quick searching not working with identification_number and name, because have relation to table basics.

### $data = Processing::where('status', '>=', '2')->get();
return DataTables::of($data)
        ->addIndexColumn()
        ->addColumn('identification_number', function($data) {
            $value=$data->Basic->identification_number;
            return $value;
        })

**Comment by yajra** [comment]
Not supported, you need to decrypt at SQL level for the search to work. Thanks!
