### ISSUE TITLE
Error in Laravel 9.10 queryBuilder does not exist

### ISSUE THREAD

**Issue by KatiaSishost** [yajra/laravel-datatables#2836]
Using in Laravel 9.10 

Method Yajra\DataTables\DataTables::queryBuilder does not exist

With 

```
$query = DB::table('categories as c')
            ->leftJoin('categories as k','c.parent','=','k.id')
            ->select('c.id','c.thumbnail','c.name','k.name as parent')
            ->orderBy('id');


return DataTables::queryBuilder($query)->toJson();
```

Work with return DataTables::of($query)->toJson();

but only return 

`{"draw":1,"recordsTotal":5252,"recordsFiltered":5252,"data":[{"id":1,"thumbnail":"","name":"ABALORIOS","parent":null},{"id":2,"thumbnail":"","name":"ABALORIOS: ESTABLECIMIENTOS","parent":"ABALORIOS"},{"id":3,"thumbnail":"","name":"ABALORIOS: FABRICACION","parent":"ABALORIOS"},{"id":4,"thumbnail":"","name":"ABANICOS","parent":null},{"id":5,"thumbnail":"","name":"ABANICOS: FABRICACION","parent":"ABANICOS"},{"id":6,"thumbnail":"","name":"ABANICOS: FABRICANTES Y MINORISTAS","parent":"ABANICOS"},{"id":7,"thumbnail":"","name":"ABANICOS: MAYORISTAS","parent":"ABANICOS"},{"id":8,"thumbnail":"","name":"ABOGADOS","parent":null},{"id":9,"thumbnail":"","name":"ABOGACIA DEL ESTADO","parent":"ABOGADOS"},{"id":10,"thumbnail":"","name":"ABOGADOS ESPECIALISTAS EN DERECHO ADMINISTRATIVO","parent":"ABOGADOS"}],"queries":[{"query":"select count(*) as aggregate from (select `c`.`id`, `c`.`thumbnail`, `c`.`name`, `k`.`name` as `parent` from `categories` as `c` left join `categories` as `k` on `c`.`parent` = `k`.`id` order by `id` asc) count_row_table","bindings":[],"time":1.2},{"query":"select count(*) as aggregate from (select `c`.`id`, `c`.`thumbnail`, `c`.`name`, `k`.`name` as `parent` from `categories` as `c` left join `categories` as `k` on `c`.`parent` = `k`.`id` order by `id` asc) count_row_table","bindings":[],"time":1.01},{"query":"select `c`.`id`, `c`.`thumbnail`, `c`.`name`, `k`.`name` as `parent` from `categories` as `c` left join `categories` as `k` on `c`.`parent` = `k`.`id` order by `id` asc, `thumbnail` desc limit 10 offset 0","bindings":[],"time":8.55}],"input":{"draw":"1","columns":[{"data":"id","name":null,"searchable":"true","orderable":"false","search":{"value":null,"regex":"false"}},{"data":"thumbnail","name":null,"searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"name","name":null,"searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"parent","name":null,"searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"slug","name":null,"searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"icon_class","name":null,"searchable":"true","orderable":"true","search":{"value":null,"regex":"false"}},{"data":"6","name":null,"searchable":"true","orderable":"false","search":{"value":null,"regex":"false"}}],"order":[{"column":"1","dir":"desc"}],"start":"0","length":"10","search":{"value":null,"regex":"false"},"params":{"sac":"helo"},"_":"1660820667995"}}`

But i have 5252 fields... and only show 10.

**Comment by simsar78** [comment]
It's normal.
The total record is 5252?

**Comment by patricktorres27** [comment]
Hi @KatiaSishost,

like @simsar78  said this is normal because your datatables config was setup with length 10, if you want to show all the data you need to configure the length of result of your datatable or you can use pagination to control the list of data.

`"start":"0","length":"10"`
notice this part of the returned json. this define the start and end of the record to show.
