### ISSUE TITLE
v6.0 How to edit settings for PDF export and print

### ISSUE THREAD

**Issue by rogierborst** [yajra/laravel-datatables#284]
Is there any way to influence how the PDF is built up? Or the print export?
I'd like to be able to add our company logo for example, and add a title. Maybe repeat headers on each page (both in PDF and in print).

If this is possible, where should I look for documentation?

**Comment by yajra** [comment]
For PDF, Excel & CSV, we use [Laravel Excel](https://github.com/Maatwebsite/Laravel-Excel) package. You can also override the following methods to accomplish what you want to do.

```php
protected function buildExcelFile() // build main excel file.
public function excel()
public function csv()
public function pdf()
```

For printing, you can create your own print preview file by setting the property:
```php
protected $printPreview = 'path.to.view';
```

Lastly, there is no documentation yet for these developments.

**Comment by RahamSher** [comment]
Dear @rogierborst  are you done pdf . If(true) then please guide me.
Thank you.

**Comment by yajra** [comment]
Better exporting of PDF via laravel-snappy was released on v6.15.0. See PR https://github.com/yajra/laravel-datatables/pull/626 for more info. Thanks!

**Comment by setiawans** [comment]
Dear @yajra how to config if using another pdf library? such as dompdf. thanks

**Comment by yajra** [comment]
@setiawans see https://yajrabox.com/docs/laravel-datatables/master/buttons-config#pdf-generator for ref. However, it's been a long time since I used dompdf and not sure if it's still working. Thanks!

**Comment by RayhanYulanda** [comment]
file in vendor/datatables/print.blade.pdf is a template for generate pdf. Is it general or i just for one file?
