### ISSUE TITLE
Building tables is slow on complex queries because of un-needed call of function FilteredCount() when no filter is entered. Er

### ISSUE THREAD

**Issue by marcelhoogantink** [yajra/laravel-datatables#2841]
### Summary of problem or feature request

After updating to DataTables version 10.1.2, quering of a table is slow.

Because I have some complex queries, I made a simpler (base)-query to exclude complexity not needed for the row-count.
I send this fast calculated $count to setTotalRecords().

See code below.

This worked OK in previous releases. (v9)

Now the queries are slow again. 
Looking into it, shows that this is slowed down, by calling function filteredCount(), but I don't have a filter.

### Code snippet of problem

```php
    public function dataTable($query)
    {

        // simpler count() for speeding-up build of the view (orginal count() is slow because of taking the full complexity of the query with multiple joins
        $count= self::defQueryBase()->count();

        $dataTable = datatables($query)
            ->setTotalRecords($count)
            ->addColumn(Def::VIEW__EAN_RECORDS__ACTION,
                function ($row)
                {
                    return $this->fillActionColumn($row);
                });


        return $dataTable;
    }
```
### System details

- Operating System: Windows 10
- PHP Version: 8.0.18
- Laravel Version: 9.25.1
- Laravel-Datatables Version 10.1.2

**Comment by yajra** [comment]
Thanks for reporting, the filter count was added back at https://github.com/yajra/laravel-datatables/pull/2778 to fix several issues. Will try to review the implementation again, but if you can, please do not hesitate to submit a PR.

**Comment by marcelhoogantink** [comment]
Tried to make a PR

**Comment by marcelhoogantink** [comment]
Closing this issues due to no interest by the owner, showed by ignoring comments in the PR.
