### ISSUE TITLE
returns incomplete or empty data but property recordsTotal is fine

### ISSUE THREAD

**Issue by alexchirolde** [yajra/laravel-datatables#2843]
### Summary of problem or feature request

Hi, I'm facing a similar issue than [this one](https://github.com/yajra/laravel-datatables/issues/2729) and [this](https://github.com/yajra/laravel-datatables/issues/2729#issuecomment-1018278027) comment did not help.

I'm using eloquent builder like this:

`$datatable = Datatables::of($models)->make(true);`

$models have been previously filtered, and if I check the content of $models before that line all the records are properly displayed:

`dd($models);`
`$datatable = Datatables::of($models)->make(true);`

Sometimes data is empty or sometimes some records are missing but always the recordsTotal property  is fine.

this is sample of the response with empty data:

```json
{
	"draw": 1,
	"recordsTotal": 113,
	"recordsFiltered": 0,
	"data": [],
	"callsCounter": 0,
	"programsCounter": 113,
	"queries": [{
			"query": "select count() as aggregate from programs_calls where (lower(json_unquote(name->'$.')) like ? or lower(acronym) like ?) and prog_or_call = ? and programs_calls.deleted_at is null",
			"bindings": [
				"%hor%",
				"%hor%",
				1
			],
			"time": 7.32
		},
		{
			"query": "select count() as aggregate from programs_calls where (lower(json_unquote(name->'$.')) like ? or lower(acronym) like ?) and prog_or_call = ? and (LOWER(programs_calls.acronym) LIKE ?) and programs_calls.deleted_at is null",
			"bindings": [
				"%hor%",
				"%hor%",
				1,
				"%hor%"
			],
			"time": 7.89
		},
		{
			"query": "select * from programs_calls where (lower(json_unquote(name->'$.*')) like ? or lower(acronym) like ?) and prog_or_call = ? and (LOWER(programs_calls.acronym) LIKE ?) and programs_calls.deleted_at is null order by acronym asc limit 10 offset 0",
			"bindings": [
				"%hor%",
				"%hor%",
				1,
				"%hor%"
			],
			"time": 7.41
		}
	],
	"input": {
		"draw": "1",
		"columns": [{
				"data": null,
				"name": null,
				"searchable": "false",
				"orderable": "false",
				"search": {
					"value": null,
					"regex": "false"
				}
			},
			{
				"data": "logo_list_view",
				"name": "logo_list_view",
				"searchable": "true",
				"orderable": "true",
				"search": {
					"value": null,
					"regex": "false"
				}
			},
			{
				"data": "call_published_list_view",
				"name": "call_published_list_view",
				"searchable": "true",
				"orderable": "true",
				"search": {
					"value": null,
					"regex": "false"
				}
			},
			{
				"data": "acronym",
				"name": "acronym",
				"searchable": "true",
				"orderable": "true",
				"search": {
					"value": null,
					"regex": "false"
				}
			},
			{
				"data": "en_name",
				"name": "en_name",
				"searchable": "true",
				"orderable": "true",
				"search": {
					"value": null,
					"regex": "false"
				}
			},
			{
				"data": "updated_at",
				"name": "updated_at",
				"searchable": "false",
				"orderable": "true",
				"search": {
					"value": null,
					"regex": "false"
				}
			},
			{
				"data": "action",
				"name": "action",
				"searchable": "false",
				"orderable": "false",
				"search": {
					"value": null,
					"regex": "false"
				}
			}
		],
		"order": [{
			"column": "3",
			"dir": "asc"
		}],
		"start": "0",
		"length": "10",
		"search": {
			"value": "hor",
			"regex": "false"
		},
		"period": "0",
		"programCallStatus": "all",
		"alphabet": null,
		"onlyPrograms": "true",
		"_": "1661198968109"
	}
}
```

I can use some help here @yajra

If there's anything else you need please let me know.
Best Alejandro

### System details

- Operating System: MacOS Big Sur
- PHP Version: PHP 7.3.30 (cli) (built: Aug 26 2021 14:41:11) ( NTS )
- Laravel Version: Laravel Framework 8.63.0
- Laravel-Datatables Version: v9.18.2

**Comment by yajra** [comment]
How did you fetch your `$model` query?

**Comment by alexchirolde** [comment]
Hello, these are the queries I'm running:

In this case the search input has a value in the frontend datatable, so this query is executed, this code is inside a method which returns `$modelsQuery`.

`$modelsQuery = $this->getSearchQuery($search);`

The `getSearchQuery` method returns $modelsQuery

`public function getSearchQuery($caseSensitiveModel, $modelsQuery, $search){`
    `...`

    `$modelsQuery->where(function ($q) use ($search) {
                            $q->where(DB::raw("lower(json_unquote(name->'$.*'))"), "like", "%" . strtolower($search) . "%")
                                ->orWhere(DB::raw("lower(acronym)"), "like", "%" . strtolower($search) . "%");
                        });`

    `...`

`return $modelsQuery`
`}`

After that I sent to your package either `$modelsQuery` which is an Illuminate\Database\Eloquent\Builder object or `$models = $modelsQuery->get()` which is an Illuminate\Database\Eloquent\Collection object. I've tested both:

`Datatables::of($modelsQuery)`

and 

`Datatables::of($models)`



In each case I get the same incomplete result.

This is how I'm using your package to render the table, 

`$datatable = Datatables::of($models)->addColumn('logo_list_view', function ($row) {
                    return $row->logo_list_view;
                })
                ->editColumn('acronym', function ($row) use ($extraParams, $route_name) {
                    return $row->getAcronym();
                })
                ->addColumn('call_published_list_view', function ($row) {
                    return $row->call_published_list_view;
                })
                ->addColumn('all_children', function ($row) use ($route_name) {
                    return $row->hasChildren() ? $row->allChildrenSortedByAcronym()->get()->toArray() : [];
                })
                ->addColumn('en_name', function ($row) {
                    return $row->en_name;
                });
            if (app()->getLocale() != 'en') {
                $datatable->addColumn('lang_name', function ($row) {
                    return $row->lang_name;
                });
            }

return $datatable
                ->rawColumns(['action', 'lang_name', 'en_name', 'all_children', 'logo_list_view', 'call_published_list_view', 'acronym'])
                ->only(['acronym', 'en_name', 'id', 'updated_at', 'lang_name', 'all_children', 'action', 'logo_list_view', 'call_published_list_view'])
                ->with([
                    'callsCounter' => $extraParams['callsCounter'],
                    'programsCounter' => $extraParams['programCounter'],
                ])
                ->make(true);`


The table with no search input works fine, this bug occurs when I search for something.

Best.

**Comment by alexchirolde** [comment]
Hi @yajra after some testing I took a different approach and turns out the bug was on the search query, just changed this:

```
public function getSearchQuery($search){
    ...

    $modelsQuery->where(function ($q) use ($search) {
                            $q->where(DB::raw("lower(json_unquote(name->'$.*'))"), "like", "%" . strtolower($search) . "%")
                                ->orWhere(DB::raw("lower(acronym)"), "like", "%" . strtolower($search) . "%");
                        });

    ...

return $modelsQuery
}
```

for this:

```
public function getSearchQuery($search){
    ...

    $modelsQuery->where(function ($q) use ($search) {
                        $q->where(DB::raw("lower(json_unquote(name->'$.*'))"), "like", "%" . strtolower($search) . "%");
                    })->orWhere(function ($q) use ($search) {
                        $q->where(DB::raw("lower(acronym)"), "like", "%" . strtolower($search) . "%");
                    });

    ...

return $modelsQuery
}
```

And everything works just fine,

Thanks for your time.
