### ISSUE TITLE
after set  'bStateSave' => true i can't reset sorted columns 

### ISSUE THREAD

**Issue by moathOSA** [yajra/laravel-datatables#2854]
how can i reset sorted columns after set 'bStateSave' to true ? 
----------------------
PHP Version "^8.0.2
Laravel Version "^9.19"
Laravel-Datatables Version "^9.0"

**Comment by yajra** [comment]
I think you can trigger ordering manually via js https://datatables.net/reference/api/order()

```js
var table = $('#example').DataTable(); 
// Sort by columns 1 and 2 and redraw
table.order( [[ 1, 'asc' ], [ 2, 'asc' ]] ) .draw();
```

**Comment by moathOSA** [comment]
@yajra  can i reset state from back-end ? 
clear all state for a spacific table ?
