### ISSUE TITLE
Class "Yajra\DataTables\Services\DataTable" not found

### ISSUE THREAD

**Issue by AMoktar** [yajra/laravel-datatables#2863]
Hello

### Summary of problem or feature request

After upgrading to php 8.1 and laravel 9 
I 've installed new yajra/laravel-datatables-oracle
```
 composer require yajra/laravel-datatables-oracle:"^10.0"
```
### Code snippet of problem

```php
Class "Yajra\DataTables\Services\DataTable" not found
```
in app\DataTables\UsersDataTable.php
```php
namespace App\DataTables;

use App\Models\User;
use Yajra\DataTables\Html\Button;
use Yajra\DataTables\Html\Column;
use Yajra\DataTables\Html\Editor\Editor;
use Yajra\DataTables\Html\Editor\Fields;
use Yajra\DataTables\Services\DataTable;

class UsersDataTable extends DataTable
{
```

### System details

- Operating System: windows/linux
- PHP Version: 8.1
- Laravel Version: 9
- Laravel-Datatables Version: 10.0

**Comment by yajra** [comment]
@AMoktar have you also updated the `laravel-datatables-buttons:^9.0` package?

**Comment by AMoktar** [comment]
Thanks
