### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#2864]
Hi @yajra,

Can I ask do you support Vue3 ?. 

Thank you in advance

**Comment by yajra** [comment]
@ezekel Sorry but I was not able to work with Vue2/3 for quite a while. It was a pain when I last tried as dataTables js library doesn't seem to play well with it. Will not support for now but maybe in the future. Thanks!

**Comment by ezekel** [comment]
Thank you for the quick reply @yajra more power to you always.

Hope see this in the future vue3 with serverside :)
