### ISSUE TITLE
Similar package without jquery

### ISSUE THREAD

**Issue by sirosfakhri** [yajra/laravel-datatables#2878]
Hi there. I have a project that was developed with tailwind CSS and AlpineJS.
Now I need to use Datatable for my website,
So the question is there any similar package with tailwind CSS & JS Vanilla or AlpineJs?
Or is there any way I Use this package with my dependencies?

- Operating System
- PHP Version ^8.0.0
- Laravel Version ^9.0.0

**Comment by yajra** [comment]
Without jQuery, I don't think so. 

DataTables will still work with Tailwind and AlpineJS, have tried it before but a lot of custom configurations are needed to style with Tailwind. No longer working on that project though.

**Comment by sirosfakhri** [comment]
thanks, bro. so there's no way.
I hope to see the tailwind & Vanilla JS Version one day.
