### ISSUE TITLE
How to get data from 2nd table using $query->where ?

### ISSUE THREAD

**Issue by arjitc** [yajra/laravel-datatables#2879]
### Summary of problem or feature request

Hi,
Was just getting started with using this library in the past few days, 

I wanted to know how to use filterColumn for data which is stored in another table.

I have loaded in the 2nd model `rackspace` this way

```
public function query(Server $model): QueryBuilder
    {
        return $model->newQuery()->with(['rackspace']);
    }
```

and when I do 

```
return $query
```

It displays all the information stored in both tables `server` as well as the `rackspace` table == which is correct.

but when I do 

```
->filterColumn('rackspace_id', function($query, $keyword) {
                $query->where('rack_name', $keyword);
        })
```

I get an error saying unknown column `rack_name` not found in `servers` while $query has information about the `rackspace` table as well..

Any help would be appreciated!

**Comment by yajra** [comment]
Maybe try using `whereHas` to filter the relation. Something like:

```php
->filterColumn('rackspace_id', function($query, $keyword) {
    $query->whereHas('rackspace', fn($q) => $q->where('rack_name', $keyword));
})

**Comment by arjitc** [comment]
Thank you @yajra -- works perfect! :)
