### ISSUE TITLE
Count post and list post in row details

### ISSUE THREAD

**Issue by wiyfn** [yajra/laravel-datatables#288]
Part of the solution there is documentation http://datatables.yajrabox.com/eloquent/count and http://datatables.yajrabox.com/eloquent/row-details
I want display a list of posts in row details each post. Example images http://i.imgur.com/oaueChl.png
Help me please.

**Comment by yajra** [comment]
It's a little complicated to explain it here. But basically, just use handlebars or some javascript templating engine. This demo http://datatables.yajrabox.com/eloquent/row-details should give you a better insight on what to do. Just follow how it works. And this demo might also help: http://datatables.yajrabox.com/eloquent/master.

**Comment by wiyfn** [comment]
Thanks for the answer.
