### ISSUE TITLE
Over write the parent table primark key by relation table whe use has on relation 

### ISSUE THREAD

**Issue by hasib2008** [yajra/laravel-datatables#2885]
Overwrite the parent table primary key (id) by relation table when use has on the relation 
I have 2 table 

**1) company_user** 
 id -> primary key 
company_id  ->foreign key of company table
users_id    -> foreign key of the user table
status 

**users** (Laravel Default )
so when I  tun 

$models = CompanyUsers::myCompany()->has('users')->with('users');
return Datatables::eloquent($models)
    ->addIndexColumn()
     ->addColumn('check_box', function ($model) {
         return view('common.checkbox', ['model' => $model, 'class' => 'i-checks people-checkbox']);
     })
    ->addColumn('name', function ($model) {
        return $model->users->name;
   })
    ->addColumn('status', 'common.status')
    ->addColumn('action', templatePath('users.action'))
    ->rawColumns(['action', 'status','name' ,'check_box'])
    ->make(true);
 
 if I try to access $mode->id it gives me the user table id not the company user table 
 
 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/8968706/197262386-5a884b2e-56d2-4828-9540-d221e8ac2b45.png">

**Comment by hasib2008** [comment]
@yajra Can you please suggest

**Comment by Arne1303** [comment]
Can you send the user relation definition in user company?

**Comment by hasib2008** [comment]
@Arne1303 
here is the relation details.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/8968706/197590499-a1e8de38-7e03-4cbf-9a02-f7f6dbb869b2.png">

**Comment by Arne1303** [comment]
I can't find anything wrong with it, it should give you the ID of the company user. You could try specifying the table in a select statement and check if you are really viewing the right database in your DBMS

**Comment by yajra** [comment]
I think you just need to specify a select SQL:

```php
CompanyUsers::myCompany()->select('company_users.*')->has('users')->with('users');
```

**Comment by hasib2008** [comment]
> I think you just need to specify a select SQL:

Yes after doing that it works
