### ISSUE TITLE
How can i set pagination and improve speed load

### ISSUE THREAD

**Issue by aliinjectorr** [yajra/laravel-datatables#2886]
### Summary of problem or feature request
i have 200K records in my products table, when i called Product::all() in my controller, it takes 70 seconds to load page.
how can i improve loading speed ?
**how can i paginate and set offset server side? (load just one page of data instead of load 200k records)**

### Code snippet of problem

`
 $products = Product::all();

        if (request()->ajax()) {
            return DataTables::of($products)
                 ->editColumn('image', function ($product) {
                     return '<a href="" target="_blank"></a>';
                 })
`

### System details

- Operating System: Mac
- PHP Version: 8.0.2
- Laravel Version: 8
- Laravel-Datatables Version

**Comment by Arne1303** [comment]
The `::all()` helper is basically a select * which loads all records into a collection bevor the datatable has a chance to modify the request for pagination.

You want to use `Products::query()` this will create a new query to the database but it gives it to the datatable to handle and modify bevor executing it.

**Comment by aliinjectorr** [comment]
thanks, how can i paginate and set offset server side? (load just one page of data instead of load 200k records)

**Comment by aliinjectorr** [comment]
> The `::all()` helper is basically a select * which loads all records into a collection bevor the datatable has a chance to modify the request for pagination.
> 
> You want to use `Product::query()` this will create a new query to the database but it gives it to the datatable to handle and modify bevor executing it.


thanks, how can i paginate and set offset server side? (load just one page of data instead of load 200k records)

**Comment by yajra** [comment]
I just updated the documentation for Laravel 9 and Vite. You might want to have a refresher to get the gist of how to work with the package. https://yajrabox.com/docs/laravel-datatables/10.0/quick-starter#setup-users-datatable

Also, maybe this [doc](https://yajrabox.com/docs/laravel-datatables/10.0/response-object) might help?

**Comment by yajra** [comment]
Based on your gist, should be something like this:

```php
Route::get('products', function () {
    if (request()->ajax()) {
        $model = App\Product::query();

        return DataTables::eloquent($model)
                         ->addColumn('intro', 'Hi {{$name}}!')
                         ->toJson();
    }

    return view('products');
});
```
