### ISSUE TITLE
ReadOnly is a reserved word in PHP 8.1

### ISSUE THREAD

**Issue by nettsite** [yajra/laravel-datatables#2889]
### Summary of problem or feature request
readonly is a reserved keyword in PHP 8.1. Any existing classes or other symbols that use the name readonly (case insensitive) will result in a syntax error in PHP 8.1.

It is not possible to port the readonly functionality to older PHP versions.

### Code snippet of problem
```
<?php

namespace Yajra\DataTables\Html\Editor\Fields;

class ReadOnly extends Field
{
    protected $type = 'readonly';
}
```

### System details

- Operating System  Ubuntu 22.04
- PHP Version  8.1.2
- Laravel Version  9 latest
- Laravel-Datatables Version Latest

I have fixed this by changing "ReadOnly" to "ReadOnlyProp", which works for me, but I haven't done any testing.

**Comment by Arne1303** [comment]
You need to update the DataTable Html package, the `ReadOnly` class has already been renamed into [ReadOnlyField](https://github.com/yajra/laravel-datatables-html/blob/master/src/Html/Editor/Fields/ReadOnlyField.php).

**Comment by nettsite** [comment]
Thanks! 
I thought I was up to date, as I ran composer update, but it seems that doesn't do it.

```
 composer update yajra/laravel-datatables-html
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```

**Comment by nettsite** [comment]
I have now removed yajra-datatables altogether, and required it, and there is still the ReadOnly class.

**Comment by Arne1303** [comment]
Sounds like you got a package installed which requires a specific version of the html package. You can use composers `depends` command to find out which package is blocking the upgrade, you then need to upgrade the blocking package:

https://getcomposer.org/doc/03-cli.md#depends-why

**Comment by nettsite** [comment]
I am giving up for now, my workaround work for me. I am sure after a few weeks or months other packages which may be causing the issue will catch up.

Thanks for your help!

**Comment by yajra** [comment]
@nettsite Have you tried using the [all-in-one installer](https://yajrabox.com/docs/laravel-datatables/10.0/installation)? 

```
composer require yajra/laravel-datatables:^9.0
```

**Comment by nettsite** [comment]
I have tried that, I have even deleted the composer.lock file and the vendor directory and did a full install. The only way I can get yajra/laravel-datatables to install is 
```
composer require yajra/laravel-datatables:*
```
