### ISSUE TITLE
sAjaxSource vs ajax

### ISSUE THREAD

**Issue by ajayfroiden** [yajra/laravel-datatables#289]
When i use sAjaxSource ,All the data is showing on all pages..
But when i replace it with ajax..Everything is working fine..

 >"bProcessing": true,
  >  "bServerSide": true,
  > "sAjaxSource": "{{ route("admin.ajax_employees") }}",
  >"aaSorting": [[ 1, "asc" ]],
<pre>Showing 1 to 5 of 22 entries  but it is actually showing all 22 records</pre>
<hr>
  >"bProcessing": true,
  >  "bServerSide": true,
  > "ajax": "{{ route("admin.ajax_employees") }}",
  >"aaSorting": [[ 1, "asc" ]],
<pre>Showing 1 to 5 of 22 entries  but it is actually showing all 5 records</pre>

Please provide some fix for this too..

**Comment by yajra** [comment]
@ajayfroiden, `sAjaxSource` is the old way of using dataTables and I already drop support for the legacy / DT1.9.x version. Note: `sAjaxSource` works/behaves differently against `ajax` in terms of the data being sent to the server.
