### ISSUE TITLE
Problem when adding the actions column, the render parameter is passed as null

### ISSUE THREAD

**Issue by mikesocorecc** [yajra/laravel-datatables#2890]
### Summary of problem or feature request

Added addAction() method but in vendor/yajra/laravel-datatables-oracle/src/Utilities/Helper.php file in toJsonScript method in isJavascript($value, $$key) does not accept null in var $value, and defaults to pass null value to methos addAcrions().
the actions column in a blade view

Yajra\DataTables\Utilities\Helper::isJavascript(): Argument #1 ($value) must be of type object|array|string, null given, called in /opt/lampp/htdocs/mtg-us.us/vendor/yajra/laravel-datatables-oracle/src/Utilities/Helper.php on line 329

### Code snippet of problem
     /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable($query)
    {
        $dataTable = new EloquentDataTable($query);
        $dataTable->addColumn('action', 'countries.datatables_actions'); //Here I tell it to show a view in that column
        $dataTable->editColumn('status', function(Countrie $Countrie) {
         return ($Countrie->status == 1) ? '<span class="badge bg-success">'.__('locale.active').'</span>' : '<span class="badge bg-danger">'.__('locale.inactive').'</span>';
        });
        $dataTable->rawColumns(['status','action']);
        return  $dataTable;
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax() 
             ->addAction(['width' => '120px', 'printable' => true, 'title' => 'Acctions']) //Here I pass the attributes to the actions column and this is what causes the problem
            ->parameters([
               'dom'  => '<"d-flex justify-content-between align-items-center header-actions mx-2 row mt-75" '.
                    '<"col-sm-12 col-lg-4 d-flex justify-content-center justify-content-lg-start" l>'.
                    '<"col-sm-12 col-lg-8 ps-xl-75 ps-0"<"dt-action-buttons d-flex align-items-center justify-content-center justify-content-lg-end flex-lg-nowrap flex-wrap"<"me-1"f>B>>'.
                    '>t'.
                    '<"d-flex justify-content-between mx-2 row mb-1"'.
                    '<"col-sm-12 col-md-6"i>'.
                    '<"col-sm-12 col-md-6"p>'.
                    '>'
                ,
                'stateSave' => false,
                'order'     => [[0, 'desc']], 
                'language' => [
                    'url' => url('//cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json'),
                ],
            ]);
    }

### System details

- Operating System
- PHP Version 8.1
- Laravel Version 9.0
- yajra/laravel-datatables-oracle Version 10.0

**Comment by yajra** [comment]
Maybe try doing a composer update? The current method accepts null.

```php
public static function isJavascript(string|array|object|null $value, string $key): bool
```

**Comment by mikesocorecc** [comment]
Thank you very much, I was using yajra/laravel-datatables-oracle version 10.0 upgrade to version 10.1.6 and now it works great.
