### ISSUE TITLE
Column Search on editColumn 

### ISSUE THREAD

**Issue by aliinjectorr** [yajra/laravel-datatables#2892]
### Summary of problem or feature request

Im using column search on each datatables column and it works on my database columns but on columns that added with editColumn not working. how can i use column search on columns that added with editColumn ? 

### System details

- Operating System: Centos
- PHP Version: 8.1
- Laravel Version: 9

**Comment by yajra** [comment]
You can use filterColumn and add a custom sql to match the value of your edited column. 

Ref: https://yajrabox.com/docs/laravel-datatables/10.0/filter-column
