### ISSUE TITLE
How to change Datatable styling?

### ISSUE THREAD

**Issue by DevMushref** [yajra/laravel-datatables#2893]
### Summary of problem or feature request

My datatable looks like this:

![image](https://user-images.githubusercontent.com/25293489/199201785-b9b919d9-4df3-4049-83c1-19bfd93f4ef4.png)

How can I change the styling of this sub-table plus icon and change its position? Something exactly like this:

![image](https://user-images.githubusercontent.com/25293489/199202066-d024783d-5d59-4c05-943c-4783beb6f3e9.png)

I am including my table into the blade like this:

```
<!--begin::Table-->
{{ $dataTable->table() }}
<!--end::Table-->

{{-- Inject Scripts --}}
@section('scripts')
    {{ $dataTable->scripts() }}
@endsection
```

When I look for solutions, all the answers are using pure JS and `<table>` which is not what I'm looking for.

### Here is the html method of the datatable

```
public function html()
    {
        return $this->builder()
            ->setTableId('reports-table')
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->dom('t') // <"d-flex" Br> <ft> <"d-flex justify-content-between" lip>
            ->stateSave(true)
            ->responsive(true)
            ->autoWidth(false)
            ->orderBy(1)
            ->parameters([
                'scrollX' => false,
                'lengthMenu' => [
                    [10, 25, 50, 100, -1],
                    ['10 rows', '25 rows', '50 rows', '100 rows', 'Show all']
                ],
                'language' => [
                    // Search
                    'className' => 'form-control form-control-solid w-250px ps-14',
                    'searchPlaceholder' => 'Search Report',
                    'search' => theme()->getSvgIcon("demo8/media/icons/duotune/general/gen021.svg", "svg-icon-1"),
                ],
            ])
            ->addTableClass('table table-row-dashed fw-bold fs-5 text-gray-600');
    }
```

Note: I am using Metronic 8 Theme with this package.

### System details

- Operating System: Windows 11
- PHP Version: 8.1
- Laravel Version: 9
- Laravel-Datatables Version: 10

**Comment by yajra** [comment]
Not a pro when it comes to styling but you can target the table style but using the table id: `reports-table`.

```css
#reports-table {
  ...
}
```
