### ISSUE TITLE
Removing unnecessary keys from JSON response

### ISSUE THREAD

**Issue by slash-aka-eric** [yajra/laravel-datatables#2907]
Noticed that the JSON response will return additional information like "queries" and "input".
Is there any option to remove these from the response JSON? The queries information is actually a security concern as it exposes the database tables and columns on client side.

$response = datatables()->of(Country::query())->toJson();

JSON Response:
{
    "draw": 1,
    "recordsTotal": 246,
    "recordsFiltered": 246,
    "data": [...],
    "queries": [{
            "query": "select count(*) as aggregate from `country`",
            "bindings": [],
            "time": 0.57
        }, {
            "query": "select * from `country` order by `COUNTRY_CODE` asc limit 10 offset 0",
            "bindings": [],
            "time": 0.36
        }
    ],
    "input": {xxx}
}

**Comment by yajra** [comment]
Just set `APP_DEBUG=false`

**Comment by slash-aka-eric** [comment]
Hi Yajra,

Thanks for responded so promptly. Have tested and it works as like what you have mentioned :)
