### ISSUE TITLE
Which is the difference between yajra/laravel-datatables-oracle and yajra/laravel-datatables ?

### ISSUE THREAD

**Issue by realtebo** [yajra/laravel-datatables#2909]
Which is the difference between yajra/laravel-datatables-oracle and yajra/laravel-datatables ?

**Comment by yajra** [comment]
> yajra/laravel-datatables

Is the all-in-one installer I created which will install other packages like buttons, HTML, editor, etc.

> yajra/laravel-datatables-oracle

This is the core library of datatables for Laravel.

Ref: https://yajrabox.com/docs/laravel-datatables/10.0#installing-laravel-datatables
