### ISSUE TITLE
How can we use datatable without jquery?

### ISSUE THREAD

**Issue by realtebo** [yajra/laravel-datatables#2911]
### Summary of problem or feature request

We are stasrting a new project from scratch and our theme is NOT using at all jQuery.

We can see here: https://datatables.net/examples/non_jquery/init.html 
There is a possibility to use datatables without jquery.

Is your excellent package already compatible? 
If yes, how?

**Comment by yajra** [comment]
I may not be able to help with this as I haven't tried this non-jquery approach yet.

But based on the example, you might need to do the scripts manually as the HTML builder package currently relies on jQuery.

**Comment by yajra** [comment]
Also, I noticed that the example still relies on jQuery 3.5.1. The initialization is just a vanilla js script.

![image](https://user-images.githubusercontent.com/2687997/205011776-bf7cb405-8df9-4b92-8800-41d1a97f1d8b.png)
