### ISSUE TITLE
security issue at global search function

### ISSUE THREAD

**Issue by mohamed-hendawy** [yajra/laravel-datatables#2912]
Is it secure when we get searchable columns from the request at `globalSearch` via `$this->request->searchableColumnIndex()` , My end users edit the columns array at the client side to add columns that aren't exist in the original datatable columns so they could do search query on them

**Comment by yajra** [comment]
You can use the following if that is a concern for your use case:

https://yajrabox.com/docs/laravel-datatables/10.0/whitelist
https://yajrabox.com/docs/laravel-datatables/10.0/blacklist

**Comment by mohamed-hendawy** [comment]
I know these two functions but I think it won't help because we can add x column as whitelist and this x column have two options searchable is false and orderable is true then the user at the client side edit the searchable to true he will be able to search against this column.

**Comment by yajra** [comment]
A workaround to disable search on the specific columns is via [filterColumn](https://yajrabox.com/docs/laravel-datatables/10.0/filter-column#main-content) and add an empty closure.

```php
    return DataTables::eloquent($model)
                ->filterColumn('fullname', function($query, $keyword) {})
```

The same goes with [orderColumn](https://yajrabox.com/docs/laravel-datatables/10.0/order-column#main-content).

Lastly, you can do your own [manual search](https://yajrabox.com/docs/laravel-datatables/10.0/manual-search#main-content) and disable global search.

**Comment by mohamed-hendawy** [comment]
I think we need to check from something at server side instead of doing workaround because we have many causes to handle and  we won't force the  package users to write extra code at every datatable
