### ISSUE TITLE
How can i export all records using yajra datatables?

### ISSUE THREAD

**Issue by henockbarakael** [yajra/laravel-datatables#2914]
### Summary of problem or feature request

I need to export all records on click in csv button but now yajra only export record of current page. Someone can help me? @yajra 

### Code snippet of problem

```
return $this->builder()
                    ->setTableId('drcsendmoneytransac-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->stateSave(true)
                    // ->responsive()
                    ->autoWidth(false)
                    ->parameters(['scrollX' => true])
                    ->addTableClass('align-middle table-row-dashed fs-6 gy-5')
                    ->parameters([  
                        'dom'          => 'Bfrtip',  
                        'buttons'      => ['excel', 'csv', 'pdf'],  
                    ])
                    ->orderBy(0)
                    ->selectStyleSingle();
```

### System details

- Windows
- PHP 8
- Laravel 9
- Laravel-Datatables 9

**Comment by yajra** [comment]
You need to use the server-side export buttons https://yajrabox.com/docs/laravel-datatables/10.0/buttons-starter.

You need to load the custom scripts `<script src="/vendor/datatables/buttons.server-side.js"></script>`

**Comment by henockbarakael** [comment]
Thank you so much! 👋 👋
