### ISSUE TITLE
Raw select error: Call to a member function getQuery() on array

### ISSUE THREAD

**Issue by rogercbe** [yajra/laravel-datatables#292]
Hello, I'm trying to create a table fetching the results of a complex query, to do so I'm using DB:raw. It breaks with this error:

FatalErrorException in EloquentEngine.php line 26:
Call to a member function getQuery() on array

This is my code

```PHP
$projectes = DB::select(DB::raw('SELECT d.*, do.domini, c.nom_fiscal, TIMESTAMPDIFF(DAY, NOW(), d.previsio) as diff, p.id as projecte_id,
            (SELECT SUM(i.hores) 
                FROM imputacions i
                WHERE i.projecte_id = p.id) as total_hores,
            (SELECT SUM(f.import) 
                FROM factures_emeses fe
                LEFT JOIN  factures f ON f.facturable_id = fe.id
                WHERE f.facturable_type = \'App\\\FacturaEmesa\'
                AND f.pagada = 1
                AND fe.projecte_id = p.id) as total_factures_cobrat,
            (SELECT SUM(f.import) 
                FROM factures_emeses fe
                LEFT JOIN  factures f ON f.facturable_id = fe.id
                WHERE f.facturable_type = \'App\\\FacturaEmesa\'
                AND fe.projecte_id = p.id) as total_factures
        FROM desenvolupaments d
        LEFT JOIN projectes p ON p.projectable_id = d.id
        LEFT JOIN dominis do ON do.id = p.domini_id
        LEFT JOIN clients c ON c.id = do.client_id
        WHERE p.projectable_type = \'App\\\Desenvolupament\''));

        return Datatables::of($projectes)
            ->addColumn('opts', function ($projecte) {
                return view('datatables.desenvolupaments', compact('projecte'))->render();
            })
            ->make(true);
```

This indeed returns an array, my guess is that the package only accepts collections? I don't really know how to translate this query to Eloquent, specially because there are several sums. 

If that was already answered I did not find it. 

Thanks yajra for your package, it is awesome!

**Comment by yajra** [comment]
Does this query works without using `Datatables`? also try using `DB::table` instead of select?

**Comment by yajra** [comment]
See this for ref: https://github.com/yajra/laravel-datatables/issues/239

**Comment by rogercbe** [comment]
Thanks for the hint yajra, after reading the ref you posted I realized that you have to pass a QueryBuilder instance to Datatables, using select you return an array (same as you do with get() method) so thats why it wasn't working. Everything working like a charm now. 

Thanks for your help!

**Comment by pedroskakum** [comment]
Can you help me?
It is to add a clause "order by" automatically without specifying the table, and I have two columns "id" in my query because the join:

snippet of the generated code:
"**order by [id] asc**"
