### ISSUE TITLE
filterColumn not fired (server-side)

### ISSUE THREAD

**Issue by Frykky** [yajra/laravel-datatables#2922]
I have the same problem written in this thread of Discussions

### Discussed in https://github.com/yajra/laravel-datatables/discussions/2921

<div type='discussions-op-text'>

<sup>Originally posted by **alessandromannini** December  7, 2022</sup>
Hi,

i'm trying to implement a custom filter on some column using ->filterColumn but it never is fired.
If you refere to the code below for "stato" the message "Something happened!" is logged but "QUERY" or "QUERY2" doesn't.

What could be the problem?
Thx
Alessandro

```
    $candidati =  Candidatura::join('candidature_mansioni', 'candidature.id', '=', 'candidature_mansioni.candidatura_id')
    ->leftjoin('candidature_lingue', 'candidature.id', '=', 'candidature_lingue.candidato_id')
    ->leftJoin('candidature_patenti', 'candidature.id', '=', 'candidature_patenti.candidatura_id')
    ->leftJoin('candidature_esperienze', 'candidature.id', '=', 'candidature_esperienze.candidatura_id')
    ->leftJoin('candidature_attestazioni', 'candidature.id', '=', 'candidature_attestazioni.candidatura_id')
	->leftJoin('note', 'candidature.id', '=', 'note.candidato_id')
    ->join('mansioni', 'candidature_mansioni.mansione_id', '=', 'mansioni.id')
    ->join('comuni', DB::raw('COALESCE(domicilio_comune_id,residenza_comune_id)'), '=', 'comuni.id')
    ->select(['candidature.id','candidature.nome','candidature.cognome','candidature.sesso','candidature.created_at','comuni.descrizione',DB::raw('YEAR(CURDATE()) - YEAR(nascita_data) AS eta, count(DISTINCT note.id) as noteCount'),'candidature.stato']);
    ->groupBy('candidature.id', 'candidature.nome', 'candidature.cognome', 'candidature.sesso', 'candidature.created_at', 'comuni.descrizione', 'candidature.nascita_data', 'candidature.stato');

	Log::info('Something happened!');

    $result=DataTables::of($candidati)
		->filterColumn('candidature.stato', 	function($query, $keyword) use ($request) {
													Log::info('QUERY=' . $query);
													$query->whereIn('candidature.stato',$request->get('stato'));
												})
		->filterColumn('stato', 				function($query, $keyword) use ($request) {
													Log::info('QUERY2=' . $query);
													$query->whereIn('candidature.stato',$request->get('stato'));
												})
		->addColumn('mansioni', function ($candidato) {
		  return $this->getCandidatureMansioni($candidato);
		})->addColumn('action', function ($candidato) {
		  return $this->getCandidatureListButtons($candidato->id);
		})->editColumn('created_at', function($candidato){
		  return $candidato->created_at?$candidato->created_at->format('d/m/Y'):'';
		})->rawColumns(['mansioni', 'action'])
		->make(true);
```
</div>

**Comment by yajra** [comment]
@alessandromannini @Frykky 

Looks like there is a conflict with eager loading and when using join SQL similar to orderColumn PR https://github.com/yajra/laravel-datatables/pull/2906.

For a workaround, please use this something like:

```
// js
{data: 'candidature.stato', name: 'candidature_stato'}

// PHP
->filterColumn('candidature_stato', function($query, $keyword) {})

**Comment by alessandromannini** [comment]
Hi @yajra , thanks for your reply!

I've tried your workaround and I discovered a new problem.

Using this javascript:
`	    ajax: {
	        url: '/getCandidature',
			data: function (d) {
				d.candidature_stato = $('#filter-stato').val();
				d.domicilio = $('#filter-domicilio').val();
				d.domicilioc = $('#filter-domicilioc').val();
				d.sesso = $('#filter-sesso').val();
				d.lingua = $('#filter-lingua').val();
				d.mansione = $('#filter-mansione').val();
				d.patente= $('#filter-patente').val();
				d.attestazione = $('#filter-attestazione').val();
				d.eta = $('#filter-eta').val();
				d.esperienza = $('#filter-esp').val();
				d.elementari = $('#filter-ele').is(':checked');
				d.medie = $('#filter-medie').is(':checked');
				d.scuolasecondaria = $('#filter-secondaria').val();
				if ($('#enablematuritaSlider').is(':checked')){
					d.annomaturita =maturitaSlider.slider('getValue');
				}
				d.laurea = $('#filter-laurea').val();
				if ($('#enablelaureaSlider').is(':checked')){
					d.annolaurea =laureaSlider.slider('getValue');
				}
			}
	    },
	    columns: [
			{data: 'cognome', name: 'candidature.cognome'},
			{data: 'nome', name: 'candidature.nome'},
			{data: 'sesso', name: 'candidature.sesso'},
			{data: 'created_at', name: 'candidature.created_at'},
			{data: 'descrizione', name: 'comuni.descrizione'},
			{data: 'mansioni', name: 'mansioni'},
			{data: 'eta', name: 'eta', searchable: false},
			{data: 'candidature_stato', name: 'candidature_stato'},
			//{data: 'noteCount', name: 'noteCount'},
			{data: 'action', namse: 'action', orderable: false, searchable: false}
	    ],
`

the **filterColumn in not fired** on the server-side and the data sent by the client is (for ex. filtering stato):

![immagine](https://user-images.githubusercontent.com/85100584/207868942-dcefbcc7-657f-4edb-80d6-9479b573355f.png)

BUT, if I manually alter the request **setting a value to `columns[7][search][value]='S'` then filterColumn is fired on the server-side**.

The question is why a `candidature_stato` is generated and valued instead of putting the values in  `columns[7][search][value]`?

Thanks
Alessandro

**Comment by yajra** [comment]
That is the expected behavior based on your script. If you want a column search instead, your script should be something like:

```js
oTable.columns(candidature_stato_index).search('S')
```
