### ISSUE TITLE
How to localize ?

### ISSUE THREAD

**Issue by realtebo** [yajra/laravel-datatables#2924]
I am unable to find any suggestion of how to create and pass locale to this package.

Could you help me?

**Comment by yajra** [comment]
From official js docs https://datatables.net/reference/option/language

**Comment by Mirko-Tebaldi** [comment]
Yes, thanks. But  I using your package to generate the HTML.
I initially didn't find the  ->language() method.
I needed to open the code, because, I think, it's not documented.

**Comment by yajra** [comment]
I think you can chain on the builder class.

```php
$this->builder()
  ->language('url')
```

https://github.com/yajra/laravel-datatables-html/blob/master/src/Html/Options/HasInternationalisation.php#L38

> I needed to open the code, because, I think, it's not documented.

Yes, I currently rely on PHPStorm / IDE for auto-completion. Can't find time to document, sorry about that.
