### ISSUE TITLE
jQuery is not defined when loading via ES module

### ISSUE THREAD

**Issue by cannycookie** [yajra/laravel-datatables#2928]
### Summary of problem or feature request

Datatable won't initialise with deferred Jquery loading as a module.  Have found a fix if anyone needs it.

### Code snippet of problem

import Datatables instead of require:-

```javascript
import $ from 'jquery'
import JSZip from "jszip";
import DataTable from 'datatables.net-bs5'
import 'datatables.net-buttons-bs5'
import 'datatables.net-buttons/js/buttons.html5'
import 'datatables.net-buttons/js/buttons.print'

window.$ = window.jQuery = $;
DataTable.Buttons.jszip(JSZip);

```
Results in:-  jQuery is not defined on the injected script.

### System details

- Operating System - Ubuntu
- PHP Version 8.1
- Laravel Version 9.x
- Laravel-Datatables Version 10.2.1

###Solution

In the blade file when injecting the script set the attribute type as module:-

```php
@push('scripts')
    {!! $dataTable->scripts(null, ['type'=>'module']) !!}
@endpush
```

Hope this helps someone.  

@yajra Still totally in love with this package, it's frigging awesome.  Thank you :-)

If I set the script attribute on the builder:-
```php
$builder->scripts(null, ['type' => 'module']);
```
The html is created with <script type="module"> but then somewhere lost and only the $dataTable->scripts() function is used.

**Comment by yajra** [comment]
Your script looks fine. Are you using vitejs? 

I recently updated the [quick starter](https://yajrabox.com/docs/laravel-datatables/10.0/quick-starter) using vitejs and made a little npm [script](https://github.com/yajra/laravel-datatables-vite/blob/main/js/index.js) for it. Might give you a clue about what's missing.

Thanks for the love ❤️ !

**Comment by cannycookie** [comment]
Ah Ha. yes, that's the last piece of the puzzle.  Thank you :-)

So I was almost right but 
```

**Comment by benyaminl** [comment]
@cannycookie if it's solved, please close the issue. thank you
