### ISSUE TITLE
csv, excel, pdf, print not working

### ISSUE THREAD

**Issue by shanka12** [yajra/laravel-datatables#293]
Hi
those, button functions not working for me. Can anyone help me? Its just print json value.

{"draw":1,"recordsTotal":11,"recordsFiltered":11,"data":[{"full_name":"Mr. Nithan Raj","id":2,"gender":"Mane","email":"","telephone_no":"","mobile_no":"","date_of_birth":"0000-00-00","city":"","action":"<a href=\"..\/member\/2\/stream\/pdf\" target=\"_blank\" class=\"btn btn-xs btn-primary\">

**Comment by Skintillion** [comment]
Did you include the datatables.buttons.js?

**Comment by Skintillion** [comment]
Also are you running datatables as service?

**Comment by shanka12** [comment]
yes I included js file. here is my script

@section('script-table')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.print.min.js"></script>
<script src="{{asset('/vendor/datatables/buttons.server-side.js')}}"></script>

        <script>
            var oTable = $('#users-table').DataTable({
                 processing: true,
                 serverSide: true,
                 ajax: {
                     url: '{{URL::to('admin/reports/members/json')}}',
                     data: function (d) {
                         d.gender = $('#gender').val();
                         d.email = $('input[name=email]').val();
                     }
                         },
                 dom: 'Bfrtip',
                 buttons: ['csv', 'excel', 'pdf', 'print', 'reset', 'reload'],
                 columns: [
                     {data: 'id', name: 'id'},
                     {data: 'full_name', name: 'full_name'},
                     {data: 'gender', name: 'gender'},
                     {data: 'date_of_birth', name: 'date_of_birth'},
                     {data: 'email', name: 'email'},
                     {data: 'telephone_no', name: 'telephone_no'},
                     {data: 'mobile_no', name: 'mobile_no'},
                     {data: 'city', name: 'city'},
                     {data: 'action', name: 'action', orderable: false, searchable: false}
                 ]
             });

         $('#search-form').on('submit', function(e) {
                 oTable.draw();
                 e.preventDefault();
             });
        </script>
@endsection

**Comment by shanka12** [comment]
controller file

<?php namespace App\Http\Controllers\Admin;

use App\Member;
use Symfony\Component\HttpFoundation\Request;
use App\Http\Requests;
use App\Http\Controllers\AdministrationController;
use PDF;
use yajra\Datatables\Facades\Datatables;
use Illuminate\Support\Facades\Input;


class ReportsController extends AdministrationController {

    public function getMembersReport()
    {
        return view('admin.reports.member_index');
    }

    public function getMembersData(Request $request)
    {
        $members = Member::selectRaw('CONCAT(title, ". ",CONCAT(UCASE(LEFT(first_name, 1)), SUBSTRING(first_name, 2)), " ", CONCAT(UCASE(LEFT(last_name, 1)), SUBSTRING(last_name, 2))) as full_name, id, gender, email, telephone_no, mobile_no, date_of_birth, city');
        if (Input::get('gender')) {
            $gender = Input::get('gender');
            $members = $members->where('gender', $gender);
        }

        if (Input::get('email')) {
            $email = Input::get('email');
            $members = $members->where('email', 'like', "%$email%");
        }

        return Datatables::of($members)
            ->addColumn('action', function ($members) {
                return '<a href="../member/'.$members->id.'/stream/pdf" target="_blank" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-list-alt"></i> View</a>';
            })
        ->make(true);
    }
}

**Comment by yajra** [comment]
`use yajra\Datatables\Facades\Datatables;`? Are you sure you're using dev-develop/6.0 branch? New namespace will be `Yajra\Datatables` (capital Y). Also please use, `Yajra\Datatables\Datatables;`. Facade seems not working properly.

**Comment by shanka12** [comment]
@yajra  im using yajra/laravel-datatables-oracle": "~5.0

**Comment by shanka12** [comment]
yes. I use 'use yajra\Datatables\Facades\Datatables;'

**Comment by yajra** [comment]
@shanka12, csv, excel, pdf, print will only work on `6.0` version and it's not yet released. You need to use  `yajra/laravel-datatables-oracle": "6.*"` or dev-develop branch. Please see [6.0 branch](https://github.com/yajra/laravel-datatables/tree/6.0) for details.

**Comment by shanka12** [comment]
@yajra It will work with laravel 5.0 ?

**Comment by shanka12** [comment]
when I upgrade to yajra/laravel-datatables-oracle:6.*   , I receive following error  

FatalErrorException in DatatablesServiceProvider.php line 57: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

**Comment by yajra** [comment]
@shanka12, package will work on Laravel 5.0 but would need at least PHP 5.5.9 for it to work. https://github.com/yajra/laravel-datatables/commit/e7687fc102b397435aca38071f352570503ce90a

The error you received means that you are using PHP 5.4 or below.

**Comment by shanka12** [comment]
@yajra Its working now with latest PHP version. but, still exce,pdf,print buttons not working. received like this
{"draw":1,"recordsTotal":6,"recordsFiltered":6,"data":[{"first_name":"Nithan","id":2,"gender":"Male","email":"user@user.com","telephone_no

**Comment by yajra** [comment]
Please follow this tuts http://datatables.yajrabox.com/service to make it work.

**Comment by yajra** [comment]
Using 6.0 branch and following the tuts should fix this. Thanks!
