### ISSUE TITLE
Display custom message when table is empty?

### ISSUE THREAD

**Issue by arjitc** [yajra/laravel-datatables#2938]
### Summary of problem or feature request

Currently, the output shows 

> No data available in table

when there is no data in the table being rendered via the HTML Builder Table.

Would it be possible to change this to a custom message?  for eg,

> There are no items in the fridge

### Code snippet of problem

Don't have any code error for this as such, the table itself renders fine when there's items in it, 

![image](https://user-images.githubusercontent.com/363587/213878657-5aff9adf-6aaa-4d0d-a6a9-d1206454dc01.png)

### System details

- Operating System: Ubuntu 22.04
- PHP Version: 8.1
- Laravel Version 9.41.0
- Laravel-Datatables Version 9.0

**Comment by yajra** [comment]
See official [docs](https://datatables.net/reference/option/) for ref:

![image](https://user-images.githubusercontent.com/2687997/215021883-f6a55088-2cec-4677-9049-9c8215541b53.png)

On the builder side, you can use something like:

```php
        return $this->builder()
                    ->setTableId('users-table')
                    ->columns($this->getColumns())
                    ->languageEmptyTable('Empty Table')
```
