### ISSUE TITLE
Class 'Yajra\Datatables\Facades\Datatables' not found

### ISSUE THREAD

**Issue by fanjavaid** [yajra/laravel-datatables#294]
Hello, Why i get this error : 
```
Class 'Yajra\Datatables\Facades\Datatables' not found
```
Cause i never update anything.

My app.php is : 

```
Yajra\Datatables\DatatablesServiceProvider::class,
'Datatables' => Yajra\Datatables\Datatables::class,
```

How to fix that?

**Comment by shafrazlk** [comment]
Change follwoing
```
Yajra\Datatables\DatatablesServiceProvider::class,
'Datatables' => Yajra\Datatables\Datatables::class,
```
to this
```
yajra\Datatables\DatatablesServiceProvider::class,
'Datatables' => yajra\Datatables\Datatables::class,
```
and try.

**Comment by fanjavaid** [comment]
Still get Error, 
```
Server Error
500
```

At the first time i install this version : 
```
"yajra/laravel-datatables-oracle": "dev-develop"
```

May be any way to reset configuration??

**Comment by shanka12** [comment]
try this

'yajra\Datatables\DatatablesServiceProvider',

remove ::class

**Comment by fanjavaid** [comment]
Still got error :( 
Here is my laravel logs : 
```
[2015-12-08 14:15:36] local.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'yajra\Datatables\DatatablesServiceProvider' not found' in /Applications/MAMP/htdocs/ulp3/bootstrap/cache/compiled.php:6916
Stack trace:
#0 {main} {"identification":{"id":"8593e01b-5cd9-4b85-9707-1fbaf2d10138"}} 
```

**Comment by shanka12** [comment]
I installed "yajra/laravel-datatables-oracle": "~5.0" 
its works fine. 
dev-develop version not work for me

**Comment by yajra** [comment]
`dev-develop` uses `Yajra\Datatables` namespace which will be tagged as v6.0.0. For the facade, please use `'Datatables' => Yajra\Datatables\Datatables::class,` atm.

**Comment by fanjavaid** [comment]
hmm, I already change to 
```
'Datatables' => Yajra\Datatables\Datatables::class
```
But it still not work.
And, finally i downgrade to 
```
"yajra/laravel-datatables-oracle": "~5.0" 
```
It works now.
But I don't know why i get that error suddenly.

Thanks for your support :) :+1:

**Comment by shairozan** [comment]
I'm actually still having this issue. Had to revert to 5 to get it to work, but I wouldn't say its fixed in 6.

**Comment by yajra** [comment]
@shairozan, the Facade file are removed on v6.0 and an alias was automatically registered in the service provider. You need to replace this `use Yajra\Datatables\Facades\Datatables` to just `use Datatables` or use `Yajra\Datatables\Datatables` instead for better IDE support.

**Comment by 2kodes** [comment]
This problem still seems to exist . On a Laravel 5.1.29 install i had to change Yajra\Datatables\DatatablesServiceProvider::class to yajra\Datatables\DatatablesServiceProvider::class in the providers array before it worked.
                                                                
  [Symfony\Component\Debug\Exception\FatalErrorException]       
  Class 'Yajra\Datatables\DatatablesServiceProvider' not found

**Comment by shanmca** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laraveldaily/quickadmin 2.0.0 requires yajra/laravel-datatables-oracle ^6.18 -> satisfiable by yajra/laravel-datatables-oracle[v6.18.0, v6.18.1, v6.18.2, v6.19.0].
    - laraveldaily/quickadmin 2.0.1 requires yajra/laravel-datatables-oracle ^6.18 -> satisfiable by yajra/laravel-datatables-oracle[v6.18.0, v6.18.1, v6.18.2, v6.19.0].
    - laraveldaily/quickadmin 2.0.2 requires yajra/laravel-datatables-oracle ^6.18 -> satisfiable by yajra/laravel-datatables-oracle[v6.18.0, v6.18.1, v6.18.2, v6.19.0].
    - yajra/laravel-datatables-oracle v6.18.0 requires dompdf/dompdf ^0.7 -> satisfiable by dompdf/dompdf[v0.7.0].
    - yajra/laravel-datatables-oracle v6.18.1 requires dompdf/dompdf ^0.7 -> satisfiable by dompdf/dompdf[v0.7.0].
    - yajra/laravel-datatables-oracle v6.18.2 requires dompdf/dompdf ^0.7 -> satisfiable by dompdf/dompdf[v0.7.0].
    - yajra/laravel-datatables-oracle v6.19.0 requires dompdf/dompdf ^0.7 -> satisfiable by dompdf/dompdf[v0.7.0].
    - dompdf/dompdf v0.7.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for laraveldaily/quickadmin ^2.0 -> satisfiable by laraveldaily/quickadmin[2.0.0, 2.0.1, 2.0.2].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/15-xml.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-dom.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mbstring.ini
    - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-simplexml.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-wddx.ini
    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.0/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by Britic** [comment]
I occasionally get this message even when it has been working fine up to that point.

For me, just running `composer update` fixes the issue.

**Comment by RBBarani** [comment]
just delete all files inside a bootstrap->cache folder. And run your project. Bug fixed.

**Comment by idmeneo** [comment]
Neither "yajra" nor "Yajra" works. I still have the error with Alaval 5.4 & Datatables v7.
It's been 3 hours I've been struggling with this library, it's exshausting.

**Comment by yajra** [comment]
@idmeneo sorry for the inconvenience. What are steps have you done so far? Are using a fresh installation or upgrading a project?

Some tips:
1. Use `composer show` to double check which version of packages you are using.
2. Delete all files under `bootstrap/cache` folder as suggested by @RBBarani.
3. Delete `vendor` folder and reinstall all packages using `composer install`.

**Comment by idmeneo** [comment]
Thx for the answer. I finally got it working by downgrading your module to v6.2 and updating all the other libraries.

**Comment by rashhmijain** [comment]
Try removing syntactic sugar operators like tilde and caret sign in composer.json. Because sometimes they do not allow the exact version to install. The same problem happened to me also. Then run,

`comoposer update`

Solved the issue for me.

**Comment by wisnuvb** [comment]
I am getting a problem in version 8.1.0 using laravel 5.5. What do I do about it? I've done the existing suggestions.

![screenshot from 2017-10-14 11-04-08](https://user-images.githubusercontent.com/3140168/31572442-2623f786-b0d0-11e7-87d0-e110239168ec.png)

**Comment by yajra** [comment]
@wisnuvb  Namespace and class name were updated on v8. Use `DataTables` instead of `Datatables`. See [upgrade guide](https://yajrabox.com/docs/laravel-datatables/master/upgrade) for ref.

**Comment by wisnuvb** [comment]
right, I have not read the upgrade guide. once it's done. thank you

**Comment by alihesari** [comment]
On v8, Run `composer update` and use this namespace `use Yajra\DataTables\Facades\DataTables;`

**Comment by lexxyungcarter** [comment]
Changing from v6.0 to v8.0 forced me to change **config/app.php** 
form 
```php
         'Datatables' => Yajra\Datatables\Facades\Datatables::class,
```
to
```php
        'Datatables' => Yajra\Datatables\Datatables::class,
```
and it worked fine afterwards.

Also, if used to automatically un-escape html elements, you'd have to publish the vendor package and change **config/datatables.php** 
```php
       /*
         * List of columns to be escaped. If set to *, all columns are escape.
         * Note: You can set the value to empty array to disable XSS protection.
         */
         'escape' => '*',
```
to
```
        'escape' => [],
```

**Comment by yajra** [comment]
@lexxyungcarter please see [upgrade guide](https://yajrabox.com/docs/laravel-datatables/master/upgrade) for ref.

**Comment by victorsteven** [comment]
Namespace and class name were updated on v8. Use DataTables instead of Datatables. 

That worked

**Comment by vajiraHOA** [comment]
@victorsteven's  solution worked on a fresh Laravel 5.6 + Datatables 8.7.0

**Comment by AQShah** [comment]
This is use Yajra\DataTables\Facades\DataTables; working fine from my side thanks

**Comment by nyamjantsan** [comment]
I use **composer require yajra/laravel-datatables-oracle** command and  change below line
yajra\Datatables\DatatablesServiceProvider::class,
'Datatables' => yajra\Datatables\Datatables::class,
It,s work.
Something like this https://appdividend.com/2018/04/16/laravel-datatables-tutorial-with-example/

**Comment by nadiyapara-axon** [comment]
Use this: 

'Datatables' => Yajra\DataTables\Facades\DataTables::class,  // Datatable

**D and T should be capital.**

**Comment by nadiyaparaamit** [comment]
Use this:

'Datatables' => Yajra\DataTables\Facades\DataTables::class, // Datatable

D and T should be capital.

**Comment by washington-kibichii** [comment]
I got this error when I was trying to remove the package. To clear the error, go to boostrap > cache and clear everything

**Comment by laurence702** [comment]
Im facing same issue here. code works perfectly on local, but I take it to server and my entire app fails to bootstrap. 
steps taken.
1. I copied yajra from my vendor to server
2. Copied also published vendor config/datatables.php to server
3. copied the composer and composer.lock
4. cleared all in server bootstrap cache 

im really frustrated after 2hrs of trying things im seeing here :(

**Comment by laurence702** [comment]
After hrs of trying. I decided to re-upload local code which was working into my shared host server. and it works fine now. Thanks Yajra

**Comment by stipsuarez** [comment]
I have the same problem with laravel 7 . I execute: php artisan config:cache
And my problem was result.
