### ISSUE TITLE
serverSide searching not working

### ISSUE THREAD

**Issue by abdosaeedelhassan** [yajra/laravel-datatables#2940]
The laravel controller code

```php
  $model = Faqquestions::with(['section', 'user'])->orderBy('id', 'asc');
        return DataTables::of($model)
            ->addColumn('id', function ($instance) {
                return $instance->id;
            })
            ->addColumn('section_name', function ($instance) {
                if ($instance->section) {
                    return $instance->section->name;
                }
            })
            ->addColumn('question', function ($instance) {
                return $instance->question;
            })
            ->addColumn('asked_by', function ($instance) {
                return $instance->user->name;
            })
            ->make(true);
```

in datatables.net implementation in js file when i put (serverSide:true) the search box not filtering the table data, but when i changed it to  (serverSide:false) it worked correctly, i need to work in service side because i have big data records

**Comment by yajra** [comment]
Using [addColumn](https://yajrabox.com/docs/laravel-datatables/10.0/add-column) will disable search/sort for that column. 

Use [editColumn](https://yajrabox.com/docs/laravel-datatables/10.0/edit-column) if the column is from the database and can be searched/sorted on the SQL level.

**Comment by abdosaeedelhassan** [comment]
@yajra thank you for your reply, it worked in database columns only but sometime i used additions columns likes actions or result column or yes or no column when i used something like that it show column not found (sql error) like as shown in next attached image, and this also work correctly if not using serverside option.
 
![Screenshot from 2023-01-28 18-50-31](https://user-images.githubusercontent.com/15355610/215278815-39a4f600-b83c-42aa-aa39-de9559510324.png)

**Comment by yajra** [comment]
If you want an added column to be searchable, you need to use [filterColumn](https://yajrabox.com/docs/laravel-datatables/10.0/filter-column) and convert it to SQL search.

**Comment by abdosaeedelhassan** [comment]
Now it worked for me as you explained, thank you

**Comment by abdosaeedelhassan** [comment]
i have other question please, sometime we need to add computed column using (addColumn), is there away to use filter function in manual search this filter work after computed columns done, my question with an other way, is there away to use/access added columns in filter function.

**Comment by abdosaeedelhassan** [comment]
@yajra i dev inside package work flow, i suggest that if (make) function that prepare the data before call render function, if it contain callback function to add additional filter that will do filtering also in computed columns that not come from the database, next attachment show what function i meant
![Screenshot from 2023-02-01 10-09-10](https://user-images.githubusercontent.com/15355610/215987960-f7cb38bc-50cb-4cb1-9b54-c6ba2c000e58.png)

Thank you
