### ISSUE TITLE
Custom data source (e.g. for REST/SOAP-backend API)

### ISSUE THREAD

**Issue by geraldb-nicat** [yajra/laravel-datatables#295]
hi yajra!

i have a question regarding this package:

is it possible to use this package to realize server-side processing (paging/filtering/sorting) of data, that comes from a server-side REST- or SOAP-backend?

i can see, that the package supports laravel collections as a data source. but afaik that would mean, i have to get all the rows from the backend first, and then filter/sort this on the webserver. but if the REST/SOAP-backend supports paging/sorting by itself, it would be great, if there was a way for yajra/laravel-datatables to forward/map it's requests to this API.

if there is currently no way of achieving this, i guess this would be a great enhancement. maybe it could be realized as some kind of Custom Data Source, that implements functions to map the data-processing variables and calls to the custom backend API.

i think cartalyst has a similar feature called "Custom Data Handlers" (see here: https://cartalyst.com/manual/data-grid/3.0#custom-data-handlers) - although i must admit, i have never worked with cartalyst.

many thanks in advance for your help!

best wishes
gerald

**Comment by yajra** [comment]
I think this is possible but you may have to write your own class wrapper to convert the paging/sorting to your API calls. I have a demo that fetch data from github http://datatables.yajrabox.com/collection/github. This demo might help you achieve what you want to do.

**Comment by geraldb-nicat** [comment]
@yajra
many thanks for your feedback, it is greatly appreciated!

afaics the linked demo loads the full data via REST, puts it inside a laravel-collection, which is then handed over to your Datatables-class. but i don't yet understand, how i would implement a REST-based paging/sorting/filtering?

here would be an example of how i get data from the REST-API, with a starting index of 1 and a rowcount of 5:
```php
        $backendCall = App::make('Registry')->load(
            Constants::$ctxContact,
            new ContactSearchDataObj(),
            new ContactSearchOptionsObj([
                .....search parameters.....
                "startIndex" => 1,
                "count" => 5
            ])
        );
        $data = $backendCall->toArray();
```
i can also retreive the number of total rows in the backend with ``$backendCall->overallCount``.

i guess mapping the search-parameters, startIndex and count from datatables' ajax-call to the backend-call should not be a problem. but i guess datatables also needs to know the overallCount to be able to display the paging-controls correctly. could you please elaborate, how i would provide the datatables-class with this info?

**Comment by judgej** [comment]
We have created a PR #2083 that supports what OP was asking for. It is very simple and avoids the "hack" of creating a bunch of dummy records in the collection with your real API records at the end.
