### ISSUE TITLE
How to use bootstrap 4 version in 10.x?

### ISSUE THREAD

**Issue by AndriiTereshchuk** [yajra/laravel-datatables#2952]
Or are you only using version 5?

**Comment by yajra** [comment]
Haven't tried Laravel 10 with BS4, but it should be the same. Just change the packages to bs4 versions. See https://github.com/yajra/laravel-datatables-vite for ref.

**Comment by yajra** [comment]
Duplicate of https://github.com/yajra/laravel-datatables-vite/issues/4#event-8504507837
