### ISSUE TITLE
Not possible to add additional data to print action

### ISSUE THREAD

**Issue by denosaurusz** [yajra/laravel-datatables#2956]
On print button it's not possible to add some additional data, also print button doesn't print footer from datatable. It's possible to change print view with override $printPreview and $printColumns with data and title, but no way to pass any other data...

"laravel/framework": "^9.2",
"yajra/laravel-datatables-buttons": "^4.13",
"yajra/laravel-datatables-oracle": "^9.19"

**Comment by yajra** [comment]
As a workaround, maybe try using view composer which is targeted to the overridden `$printPreview`?
