### ISSUE TITLE
How can I use relationship in the new version [question]

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#2960]
Hi @yajra 

I'm using this version https://yajrabox.com/docs/laravel-datatables/10.0 , How can I load the relationship using this version

`php artisan datatables:make BookAuthor`

how to do this `Book::with('author')`

I don't know where I can put that isn't it in `function dataTable`  or in `function query()`?

Thank you in advance

**Comment by yajra** [comment]
Use it in the query method:

```php
return $model->newQuery()->with('author')->select('books.*');
```

**Comment by ezekel** [comment]
Thank you so much.
