### ISSUE TITLE
How to ignore special chars on filtering/searching

### ISSUE THREAD

**Issue by fabicurti** [yajra/laravel-datatables#2961]
Hi there!

So.. I have the following model:
<pre>public static function getRegistros($tipo)
    {
        if ($tipo === 'modulo') {
            return  DB::table('pct_modulos')
                ->select(
                    'pct_modulos.id as id',
                    'pct_modulos.nome as nome',
                    'pct_modulos.deleted_at as deleted_at',
                    'pct_pacotes.nome as pacote'
                )
                ->join('pct_pacotes', 'pct_pacotes.id', '=', 'pct_modulos.pct_pacotes')
                ->orderBy('pct_modulos.nome')
                ->get();
        }
        elseif ($tipo === 'funcionalidade') {
            return DB::table('pct_funcionalidades')
                ->select(
                    'pct_funcionalidades.id as id',
                    'pct_funcionalidades.nome as nome',
                    'pct_funcionalidades.deleted_at as deleted_at',
                    'pct_modulos.nome as modulo'
                )
                ->join('pct_modulos', 'pct_modulos.id', '=', 'pct_funcionalidades.pct_modulos')
                ->orderBy('pct_funcionalidades.nome')
                ->get();
        }
        else {
            return  DB::table('pct_pacotes')->orderBy('nome')->get();
        }
    }
</pre>
My controller:
<pre>
public function lstRegistros($tipo)
{
      return DataTables::of(AppPMFModel::getRegistros($tipo))->toJson();
}
</pre>

My Datatables returns correctly like this:
![image](https://user-images.githubusercontent.com/5249996/222859755-11dfe38d-2154-4898-8b27-727665340256.png)

But, when I try to search or filter for "age" it considers "ê" as being different from "e":
![image](https://user-images.githubusercontent.com/5249996/222859931-502db569-a64f-4d3c-b53c-845ea9e2f47a.png)
![image](https://user-images.githubusercontent.com/5249996/222859956-f7dd1aea-b689-40cd-a92a-54715ada7380.png)

I need the result to be as following:
![image](https://user-images.githubusercontent.com/5249996/222860242-b0935aca-c1ac-4eb7-93ae-9d0c49f69771.png)

How can I achieve this result?
OBS: I can't use eloquent (On that page it would be ok, however, I have other cases where eloquent is not a viable choice)

Thank you in advance!!

- Operating System: Debian 5.10
- PHP Version: 8.1.11
- Laravel Version:  10.1.5
- Laravel-Datatables Version: Oracle v10.0

**Comment by yajra** [comment]
Try removing `->get();` on your queries.

**Comment by fabicurti** [comment]
I tried that countless times and didn't worke..
Then I tried again now
And worked
I was strugling with it for days now! 
THANK YOU!!
