### ISSUE TITLE
Script type module

### ISSUE THREAD

**Issue by nik04r** [yajra/laravel-datatables#2968]
### Summary of problem or feature request

In my project, it is necessary for the script to be a module because Laravel loads JavaScript with Vite. According to the tutorial "Quick Starter

[01. Installing Laravel & DataTables](https://yajrabox.com/docs/laravel-datatables/10.0/quick-starter#installation)" I use the following code:

### Code snippet of problem

```php
@push('scripts')
    {{ $dataTable->scripts(attributes: ['type' => 'module']) }}
@endpush
```
But this has no effect. When I do inspect element I always see:
```html
<script type="text/javascript">$(function(){window.LaravelDataTables
…
</script>
```
How can i get <script type="module">?

### System details

- Operating System Windows 11 Pro
- PHP Version 8.1.2
- Laravel Version v10.3.3 
- Laravel-Datatables Version: "yajra/laravel-datatables": "^10.0"

**Comment by yajra** [comment]
That snippet should work. Anyways, you can also use this new helper to lessen your code:


```php
namespace App\Providers;
 
use Illuminate\Support\ServiceProvider;
use Yajra\DataTables\Html\Builder;
 
class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Builder::useVite();
    }
}
```

And your scripts:

```php
@push('scripts')
    {{ $dataTable->scripts() }}
@endpush
```

I already updated the tutorial last week I think to show this tip.
