### ISSUE TITLE
Laravel 10 support for yajra/laravel-datatables-oracle

### ISSUE THREAD

**Issue by MGeurts** [yajra/laravel-datatables#2969]
### Summary of problem or feature request:

In a fresh LARAVEL 10.4.1 project, after only adding **composer require laravel/ui** and **php artisan ui bootstrap --auth**, installing the latest **yajra/laravel-datatables-oracle** according [the documentation](https://yajrabox.com/docs/laravel-datatables/10.0) by issuing the command **composer require yajra/laravel-datatables-oracle:"^10.0"** throws an error concerning conflicting libraries.

### Code snippet of problem:
```
PS > composer require yajra/laravel-datatables-oracle:"^10.0"
The "10.0" constraint for "yajra/laravel-datatables-oracle" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update yajra/laravel-datatables-oracle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yajra/laravel-datatables-oracle 10.0 -> satisfiable by yajra/laravel-datatables-oracle[v10.0.0].
    - yajra/laravel-datatables-oracle v10.0.0 requires illuminate/database ^9 -> found illuminate/database[v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### System details:
Windows 11 Version 22H2
PHP Version 8.2.4
Laravel Version 10.4.1
Yajra Laravel-Datatables Version 10

### Questions:

1. What is the correct composer command to install the **yajra/laravel-datatables-oracle** package in **Laravel 10**?
2. Can [the documentation](https://yajrabox.com/docs/laravel-datatables/10.0) be adapted to reflect the correct composer require command?

Thanks.

**Comment by yajra** [comment]
Updated the version constraint to ^10.3.1, thanks!
