### ISSUE TITLE
PHP 5.4 Support

### ISSUE THREAD

**Issue by leonardohcb** [yajra/laravel-datatables#297]
DatatablesServiceProvider is using: 
- DataTablesMakeCommand::class (Line 57)
- DataTablesScopeCommand::class (Line 58)
- Request::class (Line 74)
- HtmlServiceProvider::class (Line 86)
- ExcelServiceProvider::class (Line 87)
- \Yajra\Datatables\Facades\Datatables::class (Line 96)

which not working on 5.4 PHP version.

**Comment by leonardohcb** [comment]
Solved issue changing them with full path:

- 'Yajra\Datatables\Generators\DataTablesMakeCommand' (Line 57)
- 'Yajra\Datatables\Generators\DataTablesScopeCommand' (Line 58)
- 'Request' (Line 74)
- 'Collective\Html\HtmlServiceProvider' (Line 86)
- 'Maatwebsite\Excel\ExcelServiceProvider' (Line 87)
- '\Yajra\Datatables\Facades\Datatables' (Line 96)

Don't know if this is the best solution.

**Comment by BenaddiRar** [comment]
Hy :
::class require Laravel 5.1 ( PHP 5.5.9 )

**Comment by yajra** [comment]
@leonardohcb, Yes, I intentionally [dropped the support for PHP 5.4](https://github.com/yajra/laravel-datatables/commit/a3bb11a8a1c6c8006e2177e768ad912c45dd76c8) and set the minimum php version to 5.5.9. Although this package is working with Laravel 5.0, I would be requiring at least PHP 5.5.9. This is to adapt to latest changes/standard of Laravel 5.1 & upcoming 5.2.

**Comment by leonardohcb** [comment]
Ok! I'll change for myself.

Thank you so much for your feedback and thanks for your work with the package, helped me a lot!
