### ISSUE TITLE
convertToArray endlessly recursing through a child entity with a reference back to its parent (pt. 2)

### ISSUE THREAD

**Issue by wlkns** [yajra/laravel-datatables#2970]
This is a continuation of #2438 . I am not using the original issue authors mentioned plugin but have observed the same thing happening - this helper function enters into an infinite loop that never ends, causing the request to timeout. This original issue has been closed and I could not comment on it.

The issue primarily seems to be caused by an enum or spatie state relation being passed to this `foreach` — https://github.com/yajra/laravel-datatables/blob/master/src/Utilities/Helper.php#L175 Commenting out this loop allows my code to proceed and the result/JSON output is what I'd expect.

I have a lot of datatables in this application, and the primary work around is running the query outside of datatables and then passing only the raw result/flat array in.

I'm happy to submit a PR fix but wanted to fully understand what this code achieves first. It looks as though it converts all sub-arrays or objects to arrays on the parent `$data` array? the confusing part is that it then `unset($value)` ...

**Comment by yajra** [comment]
I can't recall why there is an `unset` there, but that function's purpose is to convert all values recursively to key-value pairs. 

Also, I think one problem with that method is when a stdClass is being converted to an array. There are times that it doesn't work but may be invalid now.

Please submit a PR, if it passes the current tests I can merge it. Thanks!
