### ISSUE TITLE
how to create a custom Button?

### ISSUE THREAD

**Issue by Not-Net** [yajra/laravel-datatables#2973]
### Summary of problem or feature request

I want to create a custom Button that redirect the user to the `create user` page:
I flowed the instructions in the docs: https://yajrabox.com/docs/laravel-datatables/10.0/buttons-custom 

But i get this error:
`Type of App\DataTables\UsersDataTable::$actions must be array (as in class Yajra\DataTables\Services\DataTable)`

### Code snippet of problem

```php
    protected $actions = ['print', 'excel', 'myCustomAction'];

    public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->setTableId('users-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->orderBy(1)
                    ->selectStyleSingle()
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['excel', 'print', 'myCustomAction'],
                    ]);
    }

    public function myCustomAction(){

    }
```

### System details

- Operating System: win 10
- PHP Version: v8.1.12
- Laravel Version: v10
- Laravel-Datatables Version: v10

**Comment by yajra** [comment]
Docs updated, please add the array type:

```php
protected array $actions = ['print', 'excel', 'myCustomAction'];
```

**Comment by Not-Net** [comment]
Now the datatable get loaded properly but only with the `print` and `excel` buttons.
the `myCustomAction` button is missing for some reason.

**Comment by yajra** [comment]
Any console error? Do you have the counter part script for `myCustomAction` button loaded?

**Comment by Not-Net** [comment]
No, I get no console error!
```php
protected array $actions = ['print', 'excel', 'myCustomAction'];

    public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->dom('Bfrtip')
                    ->buttons([
                        'print',
                        'excel',
                        'myCustomAction',
                    ]);
    }
    public function myCustomAction()
    {
        //...your code here.
    }

**Comment by yajra** [comment]
I think you need to create a counterpart js like https://github.com/yajra/laravel-datatables-assets/blob/master/js/buttons/add.js.

```js
$.fn.dataTable.ext.buttons.myCustomAction = {
    name: 'add',
    className: 'buttons-add btn-success',
    text: '<i class="fa fa-plus"></i> New',
    action: function (e, dt, button, config) {
        alert('myCustomAction');
    }
};
```

Will update the documentation with an actual working code when I got the chance.
