### ISSUE TITLE
Weird issue with buttons classes.

### ISSUE THREAD

**Issue by saimow** [yajra/laravel-datatables#2974]
### Summary of problem

I noticed this `btn-primary` class in the buttons as you see on the image below:

![01](https://user-images.githubusercontent.com/20516412/227624838-0a142831-7820-4dda-8856-0c0d91a5b511.PNG)

The problem is that when I change button classes, this `btn-primary` class doesn't get removed, which ruin the buttons styling, as you see on the image below:
```php
'dom' => [
    'button' => [
        'className' => 'btn btn-outline-dark',
    ]
]
```
![02](https://user-images.githubusercontent.com/20516412/227627766-1835e372-58ba-46eb-94f5-b9c6148a12b7.PNG)

### System details

- Operating System: win10
- PHP Version: v8.1.12
- Laravel Version: v10
- Laravel-Datatables Version: v10

**Comment by yajra** [comment]
Most of the time, it was automatically added via js config.

You can configure it by overriding `$.fn.DataTable.Buttons.defaults`
