### ISSUE TITLE
Filter with more than one column in the same table

### ISSUE THREAD

**Issue by radcloudcorp** [yajra/laravel-datatables#2980]
Hello good afternoon, thanks in advance for the great package.

I would like to ask a question.

I have a "study" table that has two fields "study_datetime" and "study_sla".

I need to perform a filter that retrieves the study by comparing study_datetime" and "study_sla" when one is greater than the other.

How can I perform this filter comparing two fields in the same table???

**Comment by yajra** [comment]
You can still use the query builder for this. In this case, I usually write the SQL manually and then convert it to Laravel's query builder.

You can use `whereHas`, `whereExists`, `when`, etc queries as needed.

**Comment by radcloudcorp** [comment]
Thanks for the reply friend.

I solved it in a very simple way. I created a raw query with whereRaw and passed the current date comparing with the other.

```php
....

if ($request->get('filters') == 'ea') {
    $query->whereRaw("NOW() > sla_date");
}

....
