### ISSUE TITLE
How to remove duplicates after leftJoin?

### ISSUE THREAD

**Issue by tudorached** [yajra/laravel-datatables#2984]
### Summary of problem or feature request
Hello guys!

The query below returns duplicates because the relationship leads->events is oneToMany. I would like to display only the leads with the oldest event date. How do I remove the other results/duplicates from the query?

Thank you for any help!

### Code snippet of problem

```php

public function query(Lead $model) {

$query = $model->newQuery()
              ->select(
                'leads.*',
                'events.start_date as event_start_date'
            )
            ->leftJoin('events', 'leads.id', '=', 'events.lead_id');

 return $query;

}

```

### System details

- Operating System: linux
- PHP Version: v7.1.3
- Laravel Version: v5.7
- Laravel-Datatables Version: v8.13.7

**Comment by yajra** [comment]
I think this is an SQL issue and not related to the package. Anyways, try using distinct or groupBy SQL instead.
