### ISSUE TITLE
Issue for phone number formatting while exporting to Excel & CSV

### ISSUE THREAD

**Issue by KevinMakwanaBacancy** [yajra/laravel-datatables#2985]
I am facing an issue for phone number formatting while exporting to Excel & CSV

Scenario:
During export phone number's leading zero (0) are getting removed. 
And if adding country code (+353) it will remove plus (+) sign from the field.

e.g.
Case: 1 number is 0########## and during export it's removed leading zero and converts to ##########
Case: 2 number is +353########## and during export it's removed plus sign and converts to 353##########

How to fix this ? Does anyone have idea about it ?

**Comment by keyur-bacancytechnology** [comment]
@yajra 
Tried the same, but it's not working. Having the same issue.

I am using Laravel 8.X
