### ISSUE TITLE
Multi connections relations and text filter

### ISSUE THREAD

**Issue by Zawardo1000** [yajra/laravel-datatables#2986]
### Summary of problem or feature request

I used datatables api and it's working like a charm (using collections: return DataTables::of($collection)).
i have relations using different connections and the text filtering is perfect.

Now i want to use the export to xls and as far as i understand i need to use a different approach, extending Datatable class and making the html server side.
The issue is that now the filtering doesn't work anymore since it tries a single query and i don't have all the db tables in a single database connection (some are on postgre, others on sqlserver).

There is any workaround or great idea to accomplish what i need to do? 

### System details

- Operating System windows/linux
- PHP Version 8.1.13
- Laravel Version 9.52.5
- Laravel-Datatables Version 10.4.0
![dt_error](https://user-images.githubusercontent.com/101346511/231387324-e6a6fdd8-fe5d-4a1b-82c2-c9d9f2d8b41b.png)

**Comment by yajra** [comment]
I think it may only work with the collection. Just load all the needed relations before passing it to dataTable for processing.

For eloquent/query, if it works via SQL, it should also work with the package.
