### ISSUE TITLE
Search is not working when "serverSide: true".

### ISSUE THREAD

**Issue by bondhupabel120** [yajra/laravel-datatables#2991]
When serverSide: true then the search option works not perfectly (works for only current paginate data, if paginate has 10 data then works only these 10 data, but I need to search for the whole 5000+ data).

My table has 5000+ records, I'm using serverSide: true for fast data load, but the search not working. Again when using serverSide: false then the search works perfectly but the data loading slowly.

Please help me with this issue. Thanks

![image](https://user-images.githubusercontent.com/39088855/233994158-33755e1a-9153-49e2-bd7d-b798c260dd32.png)
### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
Can you provide your server-side code to reproduce the issue?

**Comment by bondhupabel120** [comment]
`public function getRecords($request)
    {
        $q_length = $request->length;
        $q_start = $request->start;
        $title = $request->title;
        $code = $request->code;
        $account_category_id = $request->account_category_id;
        $user = auth()->user();

        $records_q = Account::where('type', 'customer')
            ->where('company_id', $user->company_id)
            ->when($account_category_id, function ($q) use ($account_category_id) {
                $q->where('account_category_id', $account_category_id);
            })
            ->when($title, function ($q) use ($title) {
                $q->where('title', 'LIKE', '%' . $title . '%');
            });

        $total_records = $records_q->count();
        if ($q_length > 0) {
            $records_q = $records_q->limit($q_start + $q_length);
        }
        $records = $records_q->with(['category','metas'])->get();
        return DataTables::of($records)
            ->addColumn('actions', function ($record) {
                return view(self::VIEW . '.includes.actions', [
                    'record' => $record
                ])->render();
            })
            ->rawColumns(['actions'])
            ->setTotalRecords($total_records)
            ->make(true);
    }`

This is my controller code.

**Comment by yajra** [comment]
Maybe use a query instead of a collection?

```php
$records = $records_q->with(['category','metas']);
```

**Comment by bondhupabel120** [comment]
@yajra Thank you, it works for me.
