### ISSUE TITLE
Datatable slows down for large dataset

### ISSUE THREAD

**Issue by manadinho** [yajra/laravel-datatables#2993]
I have a very complex query that involves 13 tables. when i provide query to yajra datatables in takes about 20 seconds to several minutes on load, on pagination and on search.
do you have any suggestion.

### System details

- PHP 7.4
- Laravel 7
"yajra/laravel-datatables": "^1.5",
"yajra/laravel-datatables-oracle": "~9.0"

**Comment by Arne1303** [comment]
Can you send the query?

**Comment by manadinho** [comment]
> Can you send the query?

here is the query
DB::table('units as u')
    ->select(DB::raw("DISTINCT
        u.id,
        cm. `name` as 'customer',
        cm. `number` as 'customer_number',
        u.actual_id as 'actual_id',
        lub.actual_id as 'loading_unit_bundle_actual_id',
        rmas.rma_number,
        u.serial_number,
        u.model_number,
        -- u.manifest_number,
        lub.cd_number,
        lub.rma_number,
        u.state,
        u.note,
        p.actual_id as 'pallet',
        lp.code as 'pallet_location',
        l.code as 'location',
        uc.`name` as 'created_by',
        uu.`name` as 'updated_by',
        g.name as 'grade',
        (SELECT DISTINCT GROUP_CONCAT(sdl.description SEPARATOR ', ')
        FROM scanning_discrepancy_logs sdl
        WHERE sdl.unit_id = u.id
        ) as 'unit_discrepancy_logs',
        u.is_packed,
        (SELECT GROUP_CONCAT(fbf.name SEPARATOR ', ')
        FROM unit_criteria_field_values ucfv
        INNER JOIN field_builder_fields fbf on fbf.id = ucfv.field_builder_field_id
        WHERE ucfv.unit_id = u.id
        ) as 'failed_criteria',
        u.created_at as 'created_at',
        u.in_transfer as 'in_transfer',
        u.was_inspection_started as 'was_inspection_started',
        u.was_repair_started as 'was_repair_started'
    "))
    ->leftJoin('pallets as p', 'p.id', '=', 'u.pallet_id')
    ->leftJoin('locations as lp', 'lp.id', '=', 'p.location_id')
    ->leftJoin('grades as g', 'g.id', '=', 'u.grade_id')
    ->leftJoin('users as uc', 'uc.id', '=', 'u.created_by_user_id')
    ->leftJoin('users as uu', 'uu.id', '=', 'u.updated_by_user_id')
    ->leftJoin('model_masters as mm', 'mm.model', '=', 'u.model_number')
    ->leftJoin('loading_unit_bundles as lub', 'lub.id', '=', 'u.loading_unit_bundle_id')
    ->leftJoin('rmas', 'lub.rma_number', '=', 'rmas.rma_number')
    ->leftJoin('return_contracts as rc', 'rc.id', '=', 'rmas.return_contract_id')
    ->leftJoin('customer_masters as cm', 'cm.id', '=', 'rc.customer_master_id')
    ->join('locations as l', function ($join) {
        $join->on('l.id', '=', 'u.location_id');
    })
    ->whereNull('u.deleted_at')
    ->where('u.type', '=', 'unit')
    ->orderBy('u.created_at', 'desc')

**Comment by manadinho** [comment]
> Can you send the query?

But if i remove the joins it works fine.
