### ISSUE TITLE
How do i filter datatable queries from my controller, and how do i return a collection or array to my view from datatable controller

### ISSUE THREAD

**Issue by toyintheisaac** [yajra/laravel-datatables#2994]
### How do i filter datatable queries from my controller, and how do i return a collection or array to my view from datatable controller

I have 2 issues.
No 1: I am trying to filter my datatable queries 
eg. 
When a class group is selected only record to that class show be displayed, if no class group  is selected, all the class list should be displayed.

No 2: I want to show all teachers in the database to the view in yajra table.

Here is my sample code 

-  My controller
![my controller](https://user-images.githubusercontent.com/58235609/237017359-3af5b088-8d58-49ef-af96-f6be3067be4c.png)
```php
    public function getSubject(SubjectDataTable $dataTable){
        $allTeachers = (new TeacherService())->getSubjectTeacher();
        $classID = 10;
        return $dataTable->render('staffAuth.classes.subjects', compact(['allTeachers','classID']));
    }
```

- My Datatable Controller 
![subject datatable](https://user-images.githubusercontent.com/58235609/237017389-2dee5b15-0d5a-4060-8df9-d01627f366ac.png)
```php

    public function dataTable(QueryBuilder $query): EloquentDataTable
    {
        return (new EloquentDataTable($query))
            ->addColumn('class', 'components.subject-class')
            ->addColumn('subject_teacher', 'components.subject-teachers')  i want to be able to access  $allTeachers here in the view
            ->addColumn('action', 'components.subject-edit')
            ->escapeColumns([])
            ->setRowId('id');
    }
    public function query(Subject $model): QueryBuilder
    {
        if(!empty($this->classID)){  
            return $model->newQuery()->where('status', 'active')->where('class_id', $this->classID);
        }
        return $model->newQuery()->where('status', 'active'); 
    }
```
 
 
![subject datatable](https://user-images.githubusercontent.com/58235609/237017513-57449cfb-cbb3-483a-9edf-93e522ce2f5c.png)

**Comment by toyintheisaac** [comment]
Please I need Help @yajra

**Comment by yajra** [comment]
I think you need to pass the classID using `with`:

```php
    public function getSubject(SubjectDataTable $dataTable){
        $allTeachers = (new TeacherService())->getSubjectTeacher();
        $classID = 10;
        return $dataTable->with('classID', $classID)
            ->render('staffAuth.classes.subjects', compact(['allTeachers','classID']));
    }
```

**Comment by toyintheisaac** [comment]
> I think you need to pass the classID using `with`:
> 
> ```
> // Controller
>     public function getSubject(SubjectDataTable $dataTable){
>         $allTeachers = (new TeacherService())->getSubjectTeacher();
>         $classID = 10;
> 
>         return $dataTable->with('classID', $classID)
>             ->render('staffAuth.classes.subjects', compact(['allTeachers','classID']));
>     }
> 
> // DataTable
>     public function query(Subject $model): QueryBuilder
>     {
>         return $model->newQuery()
>                 ->where('status', 'active')
>                 ->when($this->classID, function ($query, $classID) {
>                     return $query->where('class_id', $classID);
>                 });
>     }
> ```

This works really fine,
Thanks alot,

**Comment by toyintheisaac** [comment]
Please how do i solve this.

I want to be able to get $allTeachers in the components.subject-teachers component here.
Please how can i do this.


 
    ` public function dataTable(QueryBuilder $query): EloquentDataTable
    {
        return (new EloquentDataTable($query))
            ->addColumn('class', 'components.subject-class')
            ->addColumn('subject_teacher', 'components.subject-teachers')  i want to be able to access  $allTeachers here in the view
            ->addColumn('action', 'components.subject-edit')
            ->escapeColumns([])
            ->setRowId('id');
    }
    public function query(Subject $model): QueryBuilder
    {
        if(!empty($this->classID)){  
            return $model->newQuery()->where('status', 'active')->where('class_id', $this->classID);
        }
        return $model->newQuery()->where('status', 'active'); 
    }`
@yajra

**Comment by yajra** [comment]
Something like below:


Controller:

```php
->with('allTeachers', $allTeachers)
```

DataTable:

```php
->addColumn('subject_teacher', function($model) {
  return view('components.subject-teacher', ['allTeachers' => $this->allTeachers, 'model' => $model]);
}) 

```

**Comment by toyintheisaac** [comment]
> Something like below:
> 
> Controller:
> 
> ```
> ->with('allTeachers', $allTeachers)
> ```
> 
> DataTable:
> 
> ```
> ->addColumn('subject_teacher', function($model) {
>   return view('components.subject-teacher', ['allTeachers' => $this->allTeachers, 'model' => $model]);
> }) 
> ```

Thanks you very much, this works well,
I really appreciate your swift response.

**Comment by toyintheisaac** [comment]
Should i create a new issue for this?
Also this is my last question, And thanks for always replying.

I want to be able to number the ID column or SN by loop, not by the table column id value.

![numbering](https://github.com/yajra/laravel-datatables/assets/58235609/f18a0f9a-28c6-4409-89f3-f512b0d467c9)

I want the ID to be numbered 1, 2 3 4 5 6 7 8 9 etc. instead of getting the values from the database which omits some numbers whenever an ID value is deleted
