### ISSUE TITLE
I want to be able number my rows in the dataTable, not using my table id column as the numbering row.

### ISSUE THREAD

**Issue by toyintheisaac** [yajra/laravel-datatables#2997]
![sample 1](https://github.com/yajra/laravel-datatables/assets/58235609/e7a19647-33ae-4646-98cb-8a4f69e122fb)
![sample 2](https://github.com/yajra/laravel-datatables/assets/58235609/6de6b2b8-5a88-4284-b944-5ac715584696)

as Seen here My numbering is coming from the database which some deleted Id is not showing, I want to make the rows numbering from my datatable class or a better approach
![ordering](https://github.com/yajra/laravel-datatables/assets/58235609/e9a18b6c-b2f9-4837-80cf-aae0e7510d93)

@wuwx @ligne13 @donnykurnia @yajra

**Comment by donnykurnia** [comment]
@toyintheisaac like this? https://datatables.net/examples/api/counter_columns.html

**Comment by yajra** [comment]
You can also use [addIndexColumn](https://yajrabox.com/docs/laravel-datatables/10.0/index-column#main-content) API for the server-side counter.
