### ISSUE TITLE
Yajra Error resolveRelationColumn()

### ISSUE THREAD

**Issue by Hardz27** [yajra/laravel-datatables#2999]
I have a large data from a table only, i have read some docs and dive in some question in stackoverflow but still don't get the answer.
I've done some suggestion from github issue and stackoverflow, but the error still occurs.

this is what error i get,
Yajra\DataTables\EloquentDataTable::resolveRelationColumn(): Argument #1 ($column) must be of type string, null given, called in C:\laragon\www\pmb\vendor\yajra\laravel-datatables-oracle\src\QueryDataTable.php on line 643.

This is My Controller
    $student = Student::query();
    return DataTables::of($student)->make();

i'v tried using this
    $student = Student::query();
    return DataTables::eloquest($student);

and this too
    $student = Student::orderBy('name', 'ASC');
    return DataTables::of($student)->make();

but all of them get same error message.

=========================================================

This is my Model
    use HasFactory, Uuid;

    public $incrementing = false;
 
    // In Laravel 6.0+ make sure to also set $keyType
    protected $keyType = 'string'; 

    protected $guarded = [];

=========================================================

This is my JS :
    var table = $("#datatable").DataTable({
            processing: true,
            serverSide: true,
            autoWidth: true,
            ajax: "{{ route('students.datatable') }}",
            columnDefs: [
            {
                targets: 0,
                render: function(data, type, full, meta) {
                    return (meta.row + 1);
                }
            }, 
            ],
            columns: [
                { data: null }, 
                { data: 'nisn'},
                { data: 'name'},
                { data: 'last_school' },
                { data: 'phone'},
                { data: 'address'},
                { data: 'id'},
            ]
        });

**Comment by yajra** [comment]
Maybe try using:

```php
$student = Student::query();

return DataTables::eloquent($student)->toJson();
```

**Comment by Hardz27** [comment]
> Maybe try using:
> 
> ```
> $student = Student::query();
> 
> return DataTables::eloquent($student)->toJson();
> ```
I've try using 
$student = Student::query();
return DataTables::eloquent($student)->toJson();

But the result is same as previous:
Yajra\DataTables\EloquentDataTable::resolveRelationColumn(): Argument #1 ($column) must be of type string, null given, called in C:\laragon\www\web-acq\vendor\yajra\laravel-datatables-oracle\src\QueryDataTable.php on line 643

why my query function are not detected, do i need to install anything?
