### ISSUE TITLE
Multiple Datatables in Same View Laravel

### ISSUE THREAD

**Issue by isaactds** [yajra/laravel-datatables#3004]
I don't remember the version that worked without problems according to this stackoverflow answer

https://stackoverflow.com/questions/69346943/how-can-i-have-multiple-yajra-datatables-on-one-page-in-laravel

in the current version, it is working in parts, it is correctly showing the two datatables, but it is searching for the first datatable in the second, that is, it is only working and accepting the existing fields and the addColumn() of the first datatable

on controller
```php
        $dataTable = new DatatableDataTable();
        $dataTable2 = (new Datatable2DataTable())->html();  
        return $dataTable->render('view', compact('dataTable2'));
```
on view
```php
         <div class="card-body">
              {{ $dataTable->table() }}
              {{ $dataTable->scripts() }}
          </div>
         <div class="card-body">
              {{ $dataTable2->table() }}
              {{ $dataTable2->scripts() }}
          </div>
```
### System details

- Operating System Windows 11 22H2
- PHP Version 8.26
- Laravel Version v10.13.0
- Laravel-Datatables Version v10.1.0

**Comment by yajra** [comment]
Just make sure you set the `ajax` prop accordingly in each dataTable. By default, it uses the current URL.

```php
->setTableId('xx')
->ajax(route('path'))
...
```

**Comment by yajra** [comment]
There is also a `DataTableHtml` class that you can implement if you want it extracted and reusable but sad to say that I haven't had the time to document it well.

To generate, use something like: `php artisan datatables:make User --builder`.

**Comment by isaactds** [comment]
Added the route it worked.

I don't remember which version worked without this need, I only needed the table id and the $dataTableVariable for each one in the case of multiple tables in the same view

It would be interesting if it worked without this need because for multiple tables it can generate an excess of too many routes.

Thanks for the explanation and help.
