### ISSUE TITLE
datatables exclude id row in search

### ISSUE THREAD

**Issue by adrianriyadi** [yajra/laravel-datatables#3006]
I have ```ProductController``` that handles server-side processing data with Yajra datatables. All works fine, but whenever I try to search data, datatables always exclude ```id``` row (which I add as a column and set as row id). So, if I search ```id``` it always said no data found. Here's my code in ```ProductController```:

    public function getData()
    {
        $products = Product::select('id', 'name', 'price', 'stock')->get();

        return datatables($products)
            ->addColumn('id', function ($products) {
                return $products->id;
            })->addColumn('name', function ($products) {
                return $products->name;
            })->addColumn('price', function ($products) {
                return $products->price;
            })->addColumn('stock', function ($products) {
                return $products->stock;
            })
            ->setRowId('id')->toJson();
    }

then in my view, I have this datatables script

    let productTable = $('#products').DataTable({
			'ajax': "{{ route('products.get.data') }}",
			'processing': true,
			'serverSide': true,
			'deferRender': true,
			'responsive': true,
			'aaSorting': [[1, "asc"]], // Sort by name
			'language': {
				"emptyTable": "@lang('text.product') @lang('text.not_exist')",
				"info": "_START_ - _END_ @lang('text.from') _TOTAL_ @lang('text.product')",
				"infoEmpty": "0 @lang('text.product')",
				"lengthMenu": "_MENU_ @lang('text.product') @lang('text.per_page')",
				"infoFiltered": "(@lang('text.total') _MAX_)",
				"zeroRecords": "@lang('text.product') @lang('text.not_found')",
				"search": "@lang('text.search')",
				"paginate": {
					"previous": "@lang('text.prev')",
					"next": "@lang('text.next')"
				},
                "processing": "Loading..."
			},
			'columns': [
				{data: 'id', className: 'dt-center'},
				{data: 'name', className: 'dt-center'},
				{data: 'price', className: 'dt-center dt-body-right',
                render: DataTable.render.intlNumber('id-iD', {
                    style: 'currency',
                    currency: 'IDR',
                    minimumFractionDigits: 0
                })},
				{data: 'stock', className: 'dt-center'},
			]
		});

**Comment by yajra** [comment]
Maybe try using query instead of collection by removing get().

```php
$products = Product::select('id', 'name', 'price', 'stock');
```

**Comment by adrianriyadi** [comment]
the weird thing is it only affect id (index/primary key). Even when I setRowId('name'), the id still be excluded, and I still can search name

**Comment by adrianriyadi** [comment]
thanks. solved.
can you explain why this happen?

**Comment by yajra** [comment]
You've used [addColumn](https://yajrabox.com/docs/laravel-datatables/10.0/add-column#main-content) which disable the search & sort function of the given key.

You also used collection which is prone to performance issue and is limited to basic search available in php.

**Comment by adrianriyadi** [comment]
I also have this controller, which include relation. How can I add that relation field without using addColumn?

```public function getData()
    {
        $invoices = Invoice::select('id', 'invoice_number', 'customer_id', 'total', 'created_at')->orderBy('created_at', 'desc')->get();

        return datatables($invoices)
            ->addColumn('invoice_number', function ($invoices) {
                return $invoices->invoice_number;
            })->addColumn('customer_name', function ($invoices) {
                return $invoices->customer->name;
            })->addColumn('total', function ($invoices) {
                return $invoices->total;
            })->addColumn('date', function ($invoices) {
                return $invoices->created_at;
            })
            ->setRowId('id')->toJson();
    }```

**Comment by yajra** [comment]
[docs](https://yajrabox.com/docs/laravel-datatables/10.0/relationships#main-content)

PHP

```php
$invoices = Invoice::with('customer')->select('id', 'invoice_number', 'customer_id', 'total', 'created_at');

return datatables($invoices)->setRowId('id')->toJson();
```

JS

```php
columns: [
  {data: 'customer.name'}
]

**Comment by yajra** [comment]
Try to use this:

```php
$invoices = Invoice::with('customer')->select('invoices.*');
```

**Comment by adrianriyadi** [comment]
wont it cause performance issue by selecting all?

**Comment by adrianriyadi** [comment]
thanks.. you really help a lot
