### ISSUE TITLE
Column Visibility in Datatable as Service

### ISSUE THREAD

**Issue by fanjavaid** [yajra/laravel-datatables#301]
Hello, i want to hide some column in Ver. 6.0 Library.
Here is my html() code : 
```php
return $this->builder()
            ->columns([
                'id_paket',
                'nama_paket',
                'pagu',
                'satker_name',
                'tanggal_awal_pengadaan',
                'tipe',
                'tanggal_pengumuman',
                'status',
                'action'
            ])
            ->ajax('')
            ->parameters([
                // 'dom' => 'lBfrtip',
                'dom' => '<"dt-panelmenu clearfix"lBfr>t<"dt-panelfooter clearfix"ip>',
                'buttons' => ['csv', 'pdf', 'print'],
                'aoColumnDefs' => [
                    'aTargets' => [ 5 ],
                    'mRender' => function ( data, type, full ) {
                        return '<strong>'+ (data == 0) ? 'Penyedia' : 'Swakelola' +'</strong>';
                    }
                ],
            ]);
```

I know in section aoColumnDefs will get error.
How to implement that?

**Comment by yajra** [comment]
@fanjavaid, it's not yet possible to pass a function from builder class. However, you can just directly set `visible: false` from your columns scripts like: 

```php
return $this->builder()
            ->columns([
                'id_paket' => ['visible' => false],
                'nama_paket',
                'pagu',
                'satker_name',
                'tanggal_awal_pengadaan',
                'tipe',
                'tanggal_pengumuman',
                'status',
                'action'
            ])
```

**Comment by yajra** [comment]
@fanjavaid, as of this PR #300, you can now add a function callback js on column render property. Check it out! Thanks!

For visibility, just set `visible => false`.

**Comment by mraghayev** [comment]
No, it is not working. On this example orderable function works, but visible not works.  I still see the phone number. I tried to use removeColumn, wasn't any result. 

    private function getColumns()
    {
        return [
            ['data' => 'id', 'title' => '№'],
            ['data' => 'firstname', 'title' => 'Tələbə', 'orderable' => false],
            ['data' => 'cell', 'title' => 'Phone', 'visible' => false],

        ];
    }

**Comment by mraghayev** [comment]
I couldn't figure out, how to hide column using render property. Tried from PR #300 , but wasn't any result. Can you share an example code please?

**Comment by salihklc** [comment]
Why don't u write it in to getColumns method like:
```
 /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            ["title" => "title 1", "data" => "created_at", "name" => "created_at"]
            ["title" => "title 2", "data" => "updated_at", "name" => "updated_at","visible"=>false],
            ["title" => "title 3", "data" => "updated_by.full_name", "name" => "full_name","orderable"=>false],
        ];
    }

```
This is more readable then parameter method :simple_smile:

**Comment by salihklc** [comment]
This code tested and works like charm maybe you miss something else in your service class. Would you paste of your YourCustomServiceDataTable.php code here maybe I could help :)

**Comment by mraghayev** [comment]
Abi, amina koydugum bilmirem neden chalishmiyor :)

[    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('')
                    ->addAction(['width' => '80px', 'orderable' => false, 'searchable' => false])
                    ->parameters($this->getBuilderParameters());
    }



    protected function getColumns()
    {
        return [
            ['data' => 'published_at', 'title' => 'Date', 'searchable' => false],
            ['data' => 'title', 'title' => 'Title','orderable' => false],
            ['data' => 'name', 'title' => 'Category', 'searchable' => false],
            ['data' => 'status', 'title' => 'Status', 'searchable' => false],
            ['data' => 'featured', 'title' => 'Featured', 'searchable' => false],
            ['data' => 'published_by', 'title' => 'Published by','orderable' => false, 'searchable' => false],
        ];
    }



    protected function getBuilderParameters()
    {
        return [
            'responsive' => true,
            'filter' => true,
            'order' => [ [0,'desc'] ],
            'lengthMenu' => [10,25,50]
        ];
    }](url)

**Comment by salihklc** [comment]
Looks like u miss ajax url. What is controller index url you have to add the url to ```
->ajax('HERE') ``` :)

**Comment by Skintillion** [comment]
I'm having trouble with this too.

Updated to v7
The columns are hidden until the ajax loads, at which point they are made visible again.
