### ISSUE TITLE
Used "scrollY: 300" and showed an extra unnecessary column in datatable.

### ISSUE THREAD

**Issue by bondhupabel120** [yajra/laravel-datatables#3011]
### Summary of problem or feature request

I used "scrollY: 300" for scrolling my datatable, scrollbar works perfectly but unfortunately, I saw I extra 1 row, I don't know from where this row is coming. 

### Code snippet of problem

![image](https://github.com/yajra/laravel-datatables/assets/39088855/d3661437-0438-4e51-89e0-fb9bc825988a)

After this result is 

![datatable issue](https://github.com/yajra/laravel-datatables/assets/39088855/73f0dfa5-0edb-41fa-bb45-6834ee80ddd6)

Now, I want to remove this red color mark extra row from my datatable, please help me, thanks in advance.

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
I think it's not an extra row but a table instead. ScrollY creates a new table for the body. I think this can be fixed via CSS but it's out of scope of the project. Thanks!
