### ISSUE TITLE
Support for LazyCollection

### ISSUE THREAD

**Issue by NAUMAN-ISRAR** [yajra/laravel-datatables#3014]
Hi!
@yajra I was wondering if there is support available for LazyCollection in YajraDatatables?
as when we load large data in memory it throws memory limit exceeded error. If we can use LazyCollection instead of Collection that might help memory limit error.

**Comment by yajra** [comment]
Do you need it for export? If you are using livewire, maybe try using this https://github.com/yajra/laravel-datatables-export.

**Comment by NAUMAN-ISRAR** [comment]
@yajra thanks for the reply.
No actually we showing data in datatable from 14 tables which involves joins etc. when there are records in thousands, the yajra datatable throws memory limit exceeded error and the data does not loads. may be due to yajra datatable loads all records in memory at once.

But I think if we can use LazyCollection than we can avoid the memory limit exceeded issue while displaying fetching and preparing the data for frontend. So that all the data is not loaded in memory at once.
