### ISSUE TITLE
Problem of float precision in the data

### ISSUE THREAD

**Issue by FabienArr** [yajra/laravel-datatables#3016]
Hi,

When i retrieve the data to the server in the mysql database : i go this : 

![image](https://github.com/yajra/laravel-datatables/assets/87081538/5795d4e9-8a1e-4148-9557-ac660d26cab7)

In the mysql database i have 1.8701 in a double(11,4) and when the ajax return me the value i have 1.8700999999999999.
But i does like that for some rows and not all why ?

### Code snippet of problem

To render on 4 decimal i do like this :
```php
{data: 'superficie', name: 'sous_parcelles.superficie', render: DataTable.render.number(' ', ',', 4), className: "text-right"},
```
How i can limit to 4 decimal in the result of the ajax dataTable ?

For the moment i add this in javscript to have good precision but it's a temporary solution : 
```php
Math.round(table.row('#' + row_id).data().superficie * 10000) / 10000;
```

### System details

- Unix
- PHP Version 8.1
- Laravel Version 10.13.5
- Laravel-Datatables Version 10.4.3

Regards

**Comment by FabienArr** [comment]
Hi,

Thanks for your answer but i don't understand why using EditColumn when it's the data which are retreive from the server which are not good.

Here the code to retrieve the data, the problem is here perhaps ?

```
  return Datatables::of($userData)->filter(function ($query) {
            })->make(true);

```

**Comment by yajra** [comment]
Something like: 

```php
return Datatables::of($userData)
  ->editColumn('amount', fn($model) => number_format($model->amount, 4))
  ->filter(function ($query) {})
  ->make(true);
```

**Comment by FabienArr** [comment]
Thanks it works.
But, why i need to do that because in the database i got a field with 4 decimals, and it does it only on some rows not all.

**Comment by yajra** [comment]
It depends, do you have casting, mutators or maybe a computation occurs? Or the value is fetch directly from DB?

**Comment by yajra** [comment]
Also, if you have to format several columns, you can use [formatColumn](https://github.com/yajra/laravel-datatables/pull/2193).

**Comment by FabienArr** [comment]
I think it's directly from the DB because i do like that :
```
   $userData = DB::table('sous_parcelles')->select(.....)->where(....)
return Datatables::of($userData)
                ->editColumn('superficie', fn($model) => number_format($model->superficie, 4))
                ->filter(function ($query) {})->make(true);
```
I have no cast or  others in the model of SousParcelles.

And yes i have to format several columns.
