### ISSUE TITLE
laravelcollective/html is abandoned

### ISSUE THREAD

**Issue by JF-626164** [yajra/laravel-datatables#3023]
### Summary of problem or feature request

Lately, when I run 'composer update', I receive a message letting me know that the laravelcollective/html package is abandoned. And to use spatie/laravel-html instead. See below image.
![image](https://github.com/yajra/laravel-datatables/assets/74377418/cb5249ad-93cc-46ad-9c32-5249530e7301)

Yajra/datatables uses the laravelcollective/html package
![image](https://github.com/yajra/laravel-datatables/assets/74377418/5ce90f94-f394-4d77-a033-cc1492ae3a18)

### Code snippet of problem

Not a code issue, composer issue.
### System details

- Operating System: Ubuntu
- PHP Version: v8.1.12
- Laravel Version: v9.52.10
- Laravel-Datatables Version: v9.4

**Comment by yajra** [comment]
Yes, I already removed that dependency on v10.
