### ISSUE TITLE
Problem with creating custom search box

### ISSUE THREAD

**Issue by MIMAXUZ** [yajra/laravel-datatables#3027]
### Summary of problem or feature request

We know that in Datatables.js we can use custom search box inputs. I need the same opportunity.I wrote the following code, but it returns an error saying that it is being re-initialized. Doc did not mention such a possibility. I have also made changes to generated-scripts but this is also giving error and not working.
```
$(document).ready(function () {
    dTable = $("#datatable").DataTable({
        // "dom": 'rtip'
        // paging: true,
        // info: false
    }), $("#datatable-buttons").DataTable({
        lengthChange: !1,
        buttons: ["copy", "excel", "pdf", "colvis"]
    }).buttons().container().appendTo("#datatable-buttons_wrapper .col-md-6:eq(0)"), $(".dataTables_length select").addClass("form-select form-select-sm")
    
    $('#cSearch').keyup(function () {
        dTable.search($(this).val()).draw();   // this  is for customized searchbox with datatable search feature.
    })
});
```
I also added same code to `views/vendor/datatables.script.blade.php`:
```
$('#d-search').keyup(function () { d=$("#%1$s").DataTable().destroy(); d=$("#%1$s").DataTable(%2$s)  d.dataTable().search($(this).val()).draw();})
```
My question is how can i create my custom input for search?

**Comment by yajra** [comment]
If you are using the html builder, just access the dataTable instance in the global variable.


```php
$('#cSearch').keyup(function () {
  LaravelDataTables['table-id'].search($(this).val()).draw();
})

**Comment by MIMAXUZ** [comment]
> If you are using the html builder, just access the dataTable instance in the global variable.
> 
> 
> ```php
> $('#cSearch').keyup(function () {
>   LaravelDataTables['table-id'].search($(this).val()).draw();
> })

Thans for response. Where can i use this script? In my own js file or inside script.php file? Thanks.
