### ISSUE TITLE
Row Number Automatic update after filter

### ISSUE THREAD

**Issue by aliinjectorr** [yajra/laravel-datatables#3030]
### Summary of problem or feature request

I want the first row of the table to be the row number so that after searching and filtering, the row number will be updated based on the number of new rows. (i have columns filter)

How can I implement this?

### System details

- Operating System: Mac/linux
- PHP Version: 8.1
- Laravel Version: 9
- Laravel-Datatables Version: last

**Comment by yajra** [comment]
I believed what you need is [addIndexColumn](https://yajrabox.com/docs/laravel-datatables/10.0/index-column).
