### ISSUE TITLE
Issue for phone number formatting while exporting to Excel & CSV

### ISSUE THREAD

**Issue by keyur-bacancytechnology** [yajra/laravel-datatables#3031]
I am facing an issue for phone number formatting while exporting to Excel & CSV

Scenario:
During export phone number's leading zero (0) are getting removed.
And if adding country code (+353) it will remove plus (+) sign from the field.

e.g.
Case: 1 number is 0########## and during export it's removed leading zero and converts to ##########
Case: 2 number is +353########## and during export it's removed plus sign and converts to 353##########

How to fix this ? Does anyone have idea about it ?

**Comment by Jayushi-Bacancy** [comment]
Also facing following issue while while using exportFormat(NumberFormat::FORMAT_TEXT) while formatting mobile number:

![Screenshot from 2023-07-21 14-28-22](https://github.com/yajra/laravel-datatables/assets/97512476/79f1b362-aae1-4728-bea8-093d729704ea)

**Comment by Jayushi-Bacancy** [comment]
Along with that we used ecportFormat() in our datatable yet while exporting the excel sheet shows monile number column format as 'integer':

![Screenshot from 2023-07-21 14-43-19](https://github.com/yajra/laravel-datatables/assets/97512476/42706610-5699-4ce1-8a13-b00705ee5a4e)
Could you please help us with this issue?

**Comment by Jayushi-Bacancy** [comment]
Along with that we used ecportFormat() in our datatable yet while exporting the excel sheet shows monile number column format as 'integer':

![Screenshot from 2023-07-21 14-44-40](https://github.com/yajra/laravel-datatables/assets/97512476/60129f04-3e75-494b-956c-55208b29a5d9)


Could you please help us with this issue?

**Comment by yajra** [comment]
I think NumberFormat is a php issue, make sure the class is imported. For exportFormat, are you using Laravel Excel or the [laravel-datatables-export](https://github.com/yajra/laravel-datatables-export) package?

**Comment by keyur-bacancytechnology** [comment]
> I think NumberFormat is a php issue, make sure the class is imported. For exportFormat, are you using Laravel Excel or the [laravel-datatables-export](https://github.com/yajra/laravel-datatables-export) package?

Using [laravel-datatables-export](https://github.com/yajra/laravel-datatables-export) in Laravel 8.x version 

what is the solution on it?

**Comment by yajra** [comment]
See the readme docs for possible options: https://github.com/yajra/laravel-datatables-export#formatting-columns

Note: formatting doesn't work on CSV as it is an OpenSpout limitation.
