### ISSUE TITLE
Responsive table white space issue.

### ISSUE THREAD

**Issue by developer-macrew** [yajra/laravel-datatables#3040]
### Summary of problem or feature request

The issue at hand pertains to the implementation of DataTables in a Laravel application with a focus on responsiveness. Upon making the table responsive by adding the appropriate classes (such as table and table-responsive), an unwanted white space emerges on the right side of the table. Additionally, the inclusion of (responsive: true) in the server-side configuration aids in achieving the desired horizontal scrolling functionality on smaller screens. However, the cells in the table exhibit fixed widths, thereby hindering their ability to expand and adapt to the full width on larger screens.
![image](https://github.com/yajra/laravel-datatables/assets/29918022/a8610d77-786f-4d71-b97e-473f49e9f9b3)

### System details

- Operating System
- PHP Version:  8.2
- Laravel Version  10.10
- Laravel-Datatables Version 1.13.6

**Comment by jamalul-insan** [comment]
I thing this bug on datatables , i'm found bug like this

**Comment by yajra** [comment]
I agree with @jamalul-insan, the issue is in JS & CSS and out of the scope of the package. I think we did some tricks for this at the CSS level and disabled the responsive plugin.

**Comment by jamalul-insan** [comment]
@developer-macrew i thing this just add attribute width="100%" on table , it's work with me
