### ISSUE TITLE
The yajra datatables can't be imported in laravel 7

### ISSUE THREAD

**Issue by daviddprtma** [yajra/laravel-datatables#3051]
### Summary of problem or feature request

Undefined type 'DataTables' in laravel 7

### Code snippet of problem
<img width="678" alt="image" src="https://github.com/yajra/laravel-datatables/assets/76859181/695cafe9-30b7-4ebb-93e5-d9842ca879a0">

public function dataSoal()
    {
    if (Auth::user()->roles == 'Guru' || Auth::user()->roles == 'Admin') {
      $soals = Soal::where('id_user', Auth::user()->id)->get();
    } else {
      $soals = Soal::get();
    }
    return DataTables::of($soals)
      ->editColumn('waktu', function ($soals) {
        return $soals->waktu . ' menit';
      })
      ->editColumn('jenis', function ($soals) {
        if ($soals->jenis == 1) {
          return '<center><span class="label label-success">Ujian</label></center>';
        } else {
          return '<center><span class="label label-info">Latihan</label></center>';
        }
      })
      ->editColumn('kkm', function ($soals) {
        return "<center>" . $soals->kkm . "</center>";
      })
      ->addColumn('action', function ($soals) {
        return '<div style="text-align:center"><a href="soal/ubah/' . $soals->id . '" class="btn btn-success btn-xs">Ubah</a> <a href="soal/detail/' . $soals->id . '" class="btn btn-primary btn-xs">Detail</a></div>';
      })
      ->rawColumns(['jenis', 'action', 'kkm'])->make(true);
  }

### System details
I don't know what's wrong with the version of yajra in laravel 7 because I did everything same as what the docs guide to me but it seem like the yajra couldn't be added in my controller. What I've been did like publish the vendor of yajra, clear the cache, do the config cache, edit the file in config/app.php especially in providers and aliases all I've been follow through the guide but I failed it. I can't do anything right now. Please help me because this datatable I needed for my thesis. Thank you.

- Operating System: Windows 11
- PHP Version: 7.3.31
- Laravel Version: 7
- Laravel-Datatables Version: ^9.21

**Comment by yajra** [comment]
Did you import the DataTable class accordingly?

**Comment by daviddprtma** [comment]
I've been solved my problem just because I forgot to add jQuery Datatables in my blade file and now it's work. Anyway thank you for your reply @yajra
