### ISSUE TITLE
It's possible to change connection ?

### ISSUE THREAD

**Issue by franciscoarnaldog** [yajra/laravel-datatables#3057]
### Summary of problem or feature request

It's possible to change connection ?

### Code snippet of problem

```php
// $query = Model::from('model as m')
$builder = Model::query();
$builder->from('model as m')
    ...
$query 				= $builder->getQuery();
$conn 				= DB::connection('other_db');
$query->connection 	= $conn;
$query->grammar 	        = $conn->query()->getGrammar();
$query->processor 	       = $conn->query()->getProcessor();
$builder 			       = $builder->setQuery($query);

return Datatables::of($builder)
   ...
   ->toJson();
```

### System details

Laravel on Linux

- Linux Mint 21
- PHP 8.0
- Laravel 9
- Laravel-Datatables 10

**Comment by yajra** [comment]
I think this is out of scope. Anyways, are you trying some multitenant stuff? You can change the model via middleware
