### ISSUE TITLE
How to upgrade from version 5.12 to 6

### ISSUE THREAD

**Issue by iscjiha** [yajra/laravel-datatables#306]
i run composer update yajra/laravel-datatables-oracle and get following message: Nothing to install or update

**Comment by yajra** [comment]
This is because v6.0 is not yet tagged as stable. In this regard, you need to add the ff on your composer.json:

```json
  "minimum-stability": "dev",
  "prefer-stable": true
```

**Comment by yajra** [comment]
Documentation added on read me. Thanks!

**Comment by AEK-BKF** [comment]
Hi @yajra , is the v6 still not stable ? I'm using ^5.12 and I really need eager loading ...
Thanks
