### ISSUE TITLE
DataTable As A Service PDF Not working

### ISSUE THREAD

**Issue by yhagus** [yajra/laravel-datatables#3060]
### Summary of problem or feature request

![image](https://github.com/yajra/laravel-datatables/assets/61816313/03d92d36-4833-4731-9ecc-9699774e2da0)
![image](https://github.com/yajra/laravel-datatables/assets/61816313/4c10cf37-2115-48e3-9cf2-d33fefbfd376)

I'm currently using Yajra DataTables 10 on Laravel 10 and I'm facing this problem when I tried Export As PDF (Laravel Snappy, I've installed wkhtmltopdf via composer also.

### Code snippet of problem

PHP Controller File
```php
public function index(DeviceDataTable $dataTable)
{
    return $dataTable->render('pages.device.index');
}
```

PHP Service file:
```php
public function html(): HtmlBuilder
    {
        return $this->builder()
            ->setTableId('device-table')
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->autoWidth(false)
            ->orderBy(0)
            ->buttons([
                Button::make('excel'),
                Button::make('csv'),
                Button::make('pdf'),
                Button::make('print'),
//                Button::make('reset'),
                Button::make('reload')
            ]);
    }
```

main.js
```javascript
$(document).ready(function(){
    $.extend(true, DataTable.defaults, {
        dom:
            "<'row'<'col-sm-12 mb-4'B>>" +
            "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
    });

    $.extend(true, DataTable.Buttons.defaults, {
        dom: {
            buttonLiner: {
                tag: ''
            },
        },
    });

    $.extend(DataTable.ext.classes, {
        sTable: "table table-bordered table-hover dataTable",
    });
})
```

### System details

I modified the laravel-datatables-vite package into my needs, which is removing the jquery and bootstrap and changed it to match my app theme accordingly (Bootstrap 4.6 and jQuery 3.6)

- Windows
- PHP 8.1
- Laravel 10
- Laravel-Datatables 10

**Comment by yajra** [comment]
Seems like an issue with snappy package, see https://github.com/barryvdh/laravel-snappy/issues/512.

**Comment by yhagus** [comment]
Thanks, it's fixed. 
Solution was to keep "knplabs/knp-snappy": "1.4.1" (install that specific version if you don't have one) in composer.json. ^1.43 still has problems with it.
