### ISSUE TITLE
datatables.net-bs5 is not in this registry

### ISSUE THREAD

**Issue by NyasterDZ** [yajra/laravel-datatables#3063]
### Summary of problem or feature request

i can't install the package **laravel-datatables-vite**, i get this error

```
datatables.net-bs5@https://repo.huaweicloud.com/repository/npm/datatables.net-bs5/-/datatables.net-bs5-1.13.6.tgz' is not in this registry.
```

**Comment by yajra** [comment]
https://repo.huaweicloud.com? Not familiar with that, try using the default npm registry.
