### ISSUE TITLE
How to order by a custom (computed) colum?

### ISSUE THREAD

**Issue by realtebo** [yajra/laravel-datatables#3071]
### Summary of problem or feature request

How to order by a custom (computed) colum?

### Code snippet of problem

I have 

```php
Column::computed('date_time_insertion', 'Data e Ora'),
```

Where date_time_insertion is an appended virtual attribute of my model. 
this is needed to localized date format

But I need to keep the column sortabke

### System details

- Operating System: indipendent
- PHP Version: php 7.4
- Laravel Version: 8
- Laravel-Datatables Version 9

**Comment by yajra** [comment]
Is this a date field that is part of the table? If yes, you can do something like:

```php
Column::make('date_time_insertion')->title('Data e Ora')->name('date_time_field_name'),
```

**Comment by realtebo** [comment]
I always make confusion between the goal of 'name' and of 'data'. 

Resolved using your syntax
I create a custom query, due to need to sort by joined table field
I also added an alias to each fields but it's not related to this, I suppose

```
        return $model
            ->select('derogations.id as derogations_id', 'derogations.seller_user_id as seller_id', 'debtors.name as debtor_name', 'derogations.request_date', 'derogations.close_date', 'derogations.status')
            ->join('debtors','derogations.debtor_user_id', '=', 'debtors.id')
            ->newQuery();
```

I added a 'request_date_formatted' as  `data`, and then used `derogations.request_date` (sql table and field name) to allow sorting

```
Column::computed('request_date_formatted', 'Data inserimento')->name('derogations.request_date')->orderable(true),
```

**Comment by realtebo** [comment]
I kindly suggest to add this example in the documentation [i am using the 9, but it's ok to add into the last version only]

**Comment by yajra** [comment]
Feel free to submit a PR in [docs](https://github.com/yajra/laravel-datatables-docs), Thanks!
