### ISSUE TITLE
Searching aggregated columns such as GROUP_CONCAT

### ISSUE THREAD

**Issue by mihaiscurtucb** [yajra/laravel-datatables#308]
Hi! 

Firstly I am using version 3.6.12 of the package on laravel 4.2.

I have a rather complicated query that joins a bunch of table, and I got around that with aliases. I still have a column that represents a group concat 

`DB::raw('GROUP_CONCAT(DISTINCT coupon_packs.name SEPARATOR ", ") AS coupon_packs'),`

I tried aliasing the column but then the search query looks like 

```where `GROUP_CONCAT(DISTINCT coupon_packs.name SEPARATOR ", ") AS coupon_packs` LIKE "%search%"```

Which obviously is bad. Is there an easy way to specify that that alias needs to be in a HAVING statement? I would use `filter` but I don't want to have to rewrite global search for all the other columns.

Thanks!

**Comment by yajra** [comment]
@mihaiscurtucb, your issue should be fixed by using `filterColumn` method. However, this feature is not available on L4.2 version. Sadly, you have to use `filter` atm or just disable the searching on that column by setting `searchable: false` on your js.

**Comment by mihaiscurtucb** [comment]
Thanks :)

**Comment by mihaiscurtucb** [comment]
@yajra, I created a quick and dirty solution for this by building my own raw HAVING statement and bypassing WHERE completely

```php
$info = $this->datatableInfo;
        $input = Input::all();

        $datatable = Datatables::of($this->datatableQuery)
            ->filter(function(Builder $query) use ($info, $input) {
                if ($search = $input['search']['value']) {
                    $search = preg_replace('/\s+/', '%', $search);

                    $rawHaving = '';

                    foreach ($info['columns'] as $column => $name) {
//                        $alias = Arr::get($info['aliases'], $column, $column);

                        $rawHaving .= ($rawHaving ? ' OR ' : '') . "$column LIKE '%$search%'";
                    }

                    $rawHaving = "($rawHaving)";

                    $query->havingRaw($rawHaving);
                }
            });

        return $datatable->make(true);
```

**Comment by mihaiscurtucb** [comment]
If you agree with the approach I'd be happy to submit a PR

**Comment by yajra** [comment]
@mihaiscurtucb, sorry for overlooking this issue. I guess the Laravel 4 version is good as is since using `filter` is what I usually do during those times. Thanks!
