### ISSUE TITLE
Lazy loading on a large db - Laravel 10 raw query

### ISSUE THREAD

**Issue by jim1506** [yajra/laravel-datatables#3080]
### Summary of problem or feature request

I have a 105K table and no matter what I do it is returning all records rather than, say, 50 which is chosen in the drop down. This is making matters rather slow on initially showing the data.

### Code snippet of problem

```
$gp = DB::table('GoogleProspects')
            ->orderBy('id')
            ->whereNull('deleted_at')
            ->select([
                'GoogleProspects.id as id',
                'searchRequest as searchRequest',
                'websiteEmail as websiteEmail',
                'websiteHomePageURL as websiteHomePageURL',
                'websitePhoneNr as websitePhoneNr',
                'active as activeFlag'
            ])->get();
return Datatables::of($gp)
                ->editColumn("websiteHomePageURL", function ($gp) {
                    if (strlen($gp->websiteHomePageURL) > 35) {
                        $nw = substr($gp->websiteHomePageURL, 0, 35) . "...";
                        return $nw;
                    } else {
                        return $gp->websiteHomePageURL;
                    }
                })
                ->editColumn("websitePhoneNr", function ($gp) {
                    if (strlen($gp->websitePhoneNr) > 35) {
                        $nw = substr($gp->websitePhoneNr, 0, 35) . "...";
                        return $nw;
                    } else {
                        return $gp->websitePhoneNr;
                    }
                })
                ->editColumn("websiteEmail", function ($gp) {
                    if (strlen($gp->websiteEmail) > 35) {
                        $nw = substr($gp->websiteEmail, 0, 35) . "...";
                        return $nw;
                    } else {
                        return $gp->websiteEmail;
                    }
                })
                ->make(true);
```
I have tried omitting the get() but it makes no difference.

### System details
I am running on a Linux server using Laravel 10 (10.26.2) and your package (10.9.1)

**Comment by yajra** [comment]
First, you need to indeed remove `get`. Second, make sure the `start` and `length` are properly sent in the Ajax request.

**Comment by jim1506** [comment]
I tried removing the get and it made no difference. How do I make sure the start and length are passed (I am using datatables.js). Thanks.

**Comment by yajra** [comment]
Are you using the JS library? it should automatically be sent in the request. Inspect the Ajax request and it should give you some clues. You can also enable APP_DEBUG=true to see the SQL generated by the package.

**Comment by yajra** [comment]
Just recalled, might also be related to this server config issue https://github.com/yajra/laravel-datatables/issues/1210
