### ISSUE TITLE
Laravel Datatables v10 Unable to Handle Orthogonal Data

### ISSUE THREAD

**Issue by hazimimdnazri** [yajra/laravel-datatables#3083]
### Summary of problem or feature request

I have 2 laravel applications, one is using Laravel Datatables v9 and another one is using v10. Both are using the same jquery datatable plugin and both are reading orthogonal data from an API.

![image](https://github.com/yajra/laravel-datatables/assets/48105325/248ab884-1223-4bc5-a6f2-0d6ff9b222e5)
This the data from the API serving the application using Laravel Datatables v9

![image](https://github.com/yajra/laravel-datatables/assets/48105325/65c87c94-2e57-468a-b2f5-8b4192f0eb90)
This is data from the API serving the application using Laravel Datatables v10

They both have the same data structure.

### Code snippet of problem

This is the jquery datatables code for the column displaying the data for Laravel Datatables v9
```
           {
                class: 'text-center align-middle px-2',
                data: {
                    "filter": "application_date",
                    "sort": "application_date.timestamp",
                    "display": "application_date"
                },
                orderable: true,
                render: function (data, type, row) {
                    return `
                    ${data.display}<br>
                    ${data.time}
                    `
                },
            },
```

While this is the code for Laravel Datatable v10
```
            {
                class: 'text-center align-middle px-2',
                data: {
                    "_": "event_date.display",
                    "sort": "event_date.timestamp",
                    "display": "event_date.display"
                },
                orderable: true,
                render: function (data, type, row) {
                    return `
                    ${data.display}<br>
                    ${data.timestamp}
                    `
                },
            },
```

Again both have the same structure, yet the v10 will report this error.
`
Yajra\DataTables\Utilities\Request::columnName(): Return value must be of type ?string, array returned
`

Why is this error appear in version 10?

- Operating System: Linux
- PHP Version: 8.1.20
- Laravel Version: 9.52.16
- Laravel-Datatables Version: 10.10.0

**Comment by yajra** [comment]
I think this was raised before but can't recall if was supported previously. 

Anyways, upon quick review, it seems like orthogonal data is not supported. We can do some patches in `columnName()` to handle array value but I think orthogonal data also allows sort and filter keys to be with different values.

Maybe try code below if it will work:

```php
    public function columnName(int $i): ?string
    {
        /** @var string[] $column */
        $column = $this->request->input("columns.$i");

        if (is_array($column)) {
            return $column['_'] ?? $column['sort'] ?? null;
        }

        return (isset($column['name']) && $column['name'] != '') ? $column['name'] : $column['data'];
    }
```

Feel free to submit a PR if you have a solution in mind. Thanks!

**Comment by hazimimdnazri** [comment]
After searching through the issues, I found a solution. Apparently this works:

```
           {
                class: 'align-middle text-center',
                data: { 
                    _: "booking_date", 
                    sort: "booking_date.timestamp", 
                    filter: 'booking_date' 
                }, 
                name: 'booking_date.timestamp',
                render: function (data, type, row) {
                    return `
                    ${data.display}<br>
                    ${data.time}
                    `
                },
            },
```
Just add the **name** with the data which the datatables will use to sort the column.
