### ISSUE TITLE
I can't do search operations on a joined table

### ISSUE THREAD

**Issue by Aladdin4u** [yajra/laravel-datatables#3094]
I can't search each row field when joining two tables together but sorting the table works.
Below is the screenshot of the SQL query

![testsearc](https://github.com/yajra/laravel-datatables/assets/101972392/d9ceda1d-8194-4e88-88c9-40f8dca5fa4a)

- Operating System = windows
- PHP Version = 8.1
- Laravel Version = 10.10
- Laravel-Datatables Version = 10.3.1

**Comment by yajra** [comment]
Try including the table name on your column definition:

```js
{data: 'firstName', name: 'students.firstName'}
...
```

**Comment by Aladdin4u** [comment]
It worked

**Comment by Aladdin4u** [comment]
Please is there any way to add range to filter date row using DataTable class

**Comment by yajra** [comment]
Use `->ajaxWithForm('', '#form-selector')` then handle the filter via query.

### html

```php
->setTableId('mytable')
->ajaxWithForm(route('your-dt-route'), '#form-selector')
...
```

### query 

```php
->when(request('dateRange'), fn($q) => $q->whereBetween('date', explode(' - ', request('dateRange'))
```

### form / view

```blade
<form id="form-selector">
  <input class="date-range" name="dateRange" />
</form>
```

PS: this is just a quick snippet just to give you an idea.
