### ISSUE TITLE
Minimum php version for 10.11.1

### ISSUE THREAD

**Issue by xhevatziberi** [yajra/laravel-datatables#3099]
### Summary of problem or feature request

The readme on the reqirements of latest version (v10.11.1), php is tagged as 8.0.2. My php version is 8.0.23
When I try to install it as a composer package I get the following error.

yajra/laravel-datatables[v10.0.0, ..., v10.1.0] require php ^8.1 -> your php version (8.0.23) does not satisfy that requirement.

### System details

- PHP Version: 8.0.2
- Laravel Version: 9.19
- Laravel-Datatables Version : 10

**Comment by yajra** [comment]
Some dependencies might have bumped their minimum PHP version since the current version also supports Laravel 10. Will review further when I got the chance.
