### ISSUE TITLE
Option for caching results when using as service

### ISSUE THREAD

**Issue by sarfraznawaz2005** [yajra/laravel-datatables#311]
Hey, thanks for nice package !

Is it possible to cache results instead of triggering an ajax request each time ? Here is nice thread about caching ajax requests:

http://stackoverflow.com/questions/4869609/how-can-jquery-deferred-be-used

Thanks!

**Comment by yajra** [comment]
It's not possible atm. There was an attempt #230 to implement caching but it's not yet complete. For js caching, it's a client-side implementation and is not covered by the package. You may try asking on https://datatables.net/forums/index.

**Comment by sarfraznawaz2005** [comment]
makes sense thanks
