### ISSUE TITLE
toJson causes encoding of utf-8 characters

### ISSUE THREAD

**Issue by avatarofhope2** [yajra/laravel-datatables#3119]
### Summary of problem or feature request

When selecting data with valid utf-8 characters, the JsonResponse html encodes the data. I can disable this by using the rawColumns method, but I do want it to escape html specific things, just not normal characters that would not have an impact on xss. I think that maybe characters like `'` (`&#039;` or `U+0027`) should maybe be unmangled by default. My apologies if I've overlooked something or this has been addresses since version 8. I searched around in the issues, and while I did find some issues related to this, I didn't spot anything specific to this issue.

### Code snippet of problem

```php
return DataTables::eloquent(MyModel::select())->toJson();
```
data that shows the issue: `"COEUR-D'ALENE"` is returned as `"COEUR-D&#039;ALENE-ID"`

### System details

- Centos 7
- PHP 7.2
- 5.6
- 8

**Comment by yajra** [comment]
I think you need to use [rawColumns](https://yajrabox.com/docs/laravel-datatables/10.0/raw-columns#main-content)?

**Comment by avatarofhope2** [comment]
I am using rawColumns, but it could be a security issue, if the column data could contain html/javascript, right? I'm trying to establish a difference between utf-8 and html when it comes to encoding data from the database.

**Comment by yajra** [comment]
Yes, rawColumns will also allow the js script. Maybe try using the [column.render](https://datatables.net/reference/api/column().render()) api.

**Comment by avatarofhope2** [comment]
I appreciate the thought, but I tend to re-use these APIs for more than just datatables front-ends, so I'd prefer to get just the exact utf-8 data as-is, except if there is html/js which could pose a security risk.
