### ISSUE TITLE
Passing two dataTables as render

### ISSUE THREAD

**Issue by jigapate** [yajra/laravel-datatables#3124]
Hello,

I am passing two dataTables in one render, but I could not get second table,
So question is how we can pass two dataTable instances with one render?

```
    public function future($property, EodFuturesDataTable $dataTable1, EodBhavDataTable $dataTable)
    {         
        $dataTable->property = $property;
        $dataTable1->property = $property;
        return $dataTable->render('pages/apps.symbol.overview_future', compact('property', 'dataTable1'));
    }

```

With the above code, I can get a table for ```data table``

```
$dataTable->table()
```
But when I call for ```$dataTable1->table()``` it ends with errors ```Call to undefined method App\DataTables\EodFuturesDataTable::table()```

So what is way to pass two dataTables in one view?

Laravel 10.

**Comment by yajra** [comment]
You need to have 2 routes to process the DataTable response. For the html, you can use `--builder` option that extracts the html builder to its own class which you can reuse on any page.

```bash
php artisan datatables:make Users --builder
// or
php artisan datatables:html Users
```

On your controller:

```php
    public function future($property, EodFuturesDataTable $dataTable1, EodBhavDataTable $dataTable)
    {         
        $dataTable->property = $property;
        $users = UserDataTableHtml::make();

        return $dataTable->render('pages/apps.symbol.overview_future', compact('property', 'dataTable1', 'users'));
    }
```

On your view:

```blade
{{ $users->table() }}
{{ $users->scripts() }}
```
