### ISSUE TITLE
The table disappears Editor with DateTime, Date, Select2

### ISSUE THREAD

**Issue by markplus** [yajra/laravel-datatables#3127]
I can't find the solution for this problem, if I use Fields\Text::make, Fields\Select::make, everything works perfectly but if I try to use DateTime, Date, Select2 the table disappears completely from the page I'm using laravel 10 with the latest version of yajra datatables and also latest version of the editor, if I add the option in the editor

[[](url)](https://datatables.net/forums/uploads/editor/g8/aut7i6i8ciyb.png)

- Operating System Linux
- PHP Version 8.2
- Laravel Version 10
- Laravel-Datatables Version 10.1
-- Laravel-Datatables Editor Version 1.25

**Comment by yajra** [comment]
How many select2 field you have? There is a similar issue I encountered before and the problem was I have 2 forms with the same field name.

Solution: set the `->id('id2')` to next field with the same name

Also, check your console error for possible js issue.
