### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by aslanonline** [yajra/laravel-datatables#3130]
Hello,

please Add Support for Laravel 11.

**Comment by Seb33300** [comment]
The `master` branch is already compatible with Laravel 11.

In case this help until a new laravel-datatables release is published, you can force using `master` branch by modifying your `composer.json`:
```json
"yajra/laravel-datatables-oracle": "dev-master"
```

**Comment by THPAdmin** [comment]
yajra just released Laravel 11 version, yay.

**Comment by Seb33300** [comment]
No upgrade guide?
https://github.com/yajra/laravel-datatables/blob/master/UPGRADE.md

**Comment by Mo7sin** [comment]
Great, what about all-in-one installer package? it supports only up until Laravel 10.

`composer require yajra/laravel-datatables:^10.0`

**Comment by reflymandau** [comment]
11.0

**Comment by yajra** [comment]
All packages bumped to v11, please verify and submit a new issue for any concerns. Thanks!
