### ISSUE TITLE
Laravel 11 support 

### ISSUE THREAD

**Issue by lucasmazevedo** [yajra/laravel-datatables#3136]
I try install yajra/laravel-datatables:^11.0 on laravel 11.3.1 not working.

### Code snippet of problem

```
Problem 1
    - pestphp/pest[v2.33.6, ..., v2.34.0] require phpunit/phpunit ^10.5.10 -> found phpunit/phpunit[10.5.10, ..., 10.5.18] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.1 requires phpunit/phpunit ^10.5.11 -> found phpunit/phpunit[10.5.11, ..., 10.5.18] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.2 requires phpunit/phpunit ^10.5.12 -> found phpunit/phpunit[10.5.12, ..., 10.5.18] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest[v2.34.3, ..., v2.34.4] require phpunit/phpunit ^10.5.13 -> found phpunit/phpunit[10.5.13, ..., 10.5.18] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.5 requires phpunit/phpunit ^10.5.15 -> found phpunit/phpunit[10.5.15, 10.5.16, 10.5.17, 10.5.18] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.6 requires phpunit/phpunit ^10.5.16 -> found phpunit/phpunit[10.5.16, 10.5.17, 10.5.18] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.7 requires phpunit/phpunit ^10.5.17 -> found phpunit/phpunit[10.5.17, 10.5.18] but it conflicts with your root composer.json require (^11.0.1).
    - yajra/laravel-datatables v11.0.0 requires yajra/laravel-datatables-export ^11 -> satisfiable by yajra/laravel-datatables-export[v11.0.0].
    - yajra/laravel-datatables-export v11.0.0 requires pestphp/pest ^2.34 -> satisfiable by pestphp/pest[v2.34.0, ..., v2.34.7].
    - Root composer.json requires yajra/laravel-datatables ^11.0 -> satisfiable by yajra/laravel-datatables[v11.0.0].
```

**Comment by yajra** [comment]
I think the issue in your `pestphp` installation and not on the package?

  - pestphp/pest[v2.33.6, ..., v2.34.0] require phpunit/phpunit ^10.5.10 -> found phpunit/phpunit[10.5.10, ..., 10.5.18] but it conflicts with your root composer.json require (^11.0.1).

**Comment by abhaybhalala** [comment]
@lucasmazevedo 

below steps works for me after creating a new laravel 11 project.

Remove phpunit and pestphp

composer remove phpunit/phpunit
composer remove pestphp/pestphp

then run below command
composer require yajra/laravel-datatables -W

this will install all required dependencies.

**Comment by vipertecpro** [comment]
> @lucasmazevedo
> 
> below steps works for me after creating a new laravel 11 project.
> 
> Remove phpunit and pestphp
> 
> composer remove phpunit/phpunit composer remove pestphp/pestphp
> 
> then run below command composer require yajra/laravel-datatables -W
> 
> this will install all required dependencies.

Yeap that works, thx alot

**Comment by cryptothree** [comment]
Seems that the `[laravel-datatables-export](https://github.com/yajra/laravel-datatables-export)` this package requires `pestphp/pest` which conflicts  with the `phpunit/phpunit` which requires by the laravel project

**Comment by yajra** [comment]
It seems like `pestphp` was accidentally added in `require` and it should be in `require-dev`. Released https://github.com/yajra/laravel-datatables-export/releases/tag/v11.1.1, Thanks!
