### ISSUE TITLE
Custom Html Template

### ISSUE THREAD

**Issue by SyntaxKavindu** [yajra/laravel-datatables#3138]
How can i change yajra datatable default html template
Default page
![image](https://github.com/yajra/laravel-datatables/assets/115771259/b4f5d180-15a6-4c3d-b256-d41d793c9c27)

i want ui like this
![image](https://github.com/yajra/laravel-datatables/assets/115771259/4f89b0ae-0c62-4ec5-84fd-bd896d456215)

i want to add yajra datatable to my custom template

**Comment by yajra** [comment]
Use [dom](https://datatables.net/reference/option/dom) with some css

**Comment by SyntaxKavindu** [comment]
> Use [dom](https://datatables.net/reference/option/dom) with some css

thank you
