### ISSUE TITLE
Laravel 5.2 , plz update LaravelCollective to v 5.1

### ISSUE THREAD

**Issue by aborigines** [yajra/laravel-datatables#314]
plz update LaravelCollective to v 5.1

changelog 
replace bindShared to singelton 
https://github.com/LaravelCollective/html/commit/a28c3dc94cdebdc25e2edfcf336dd84d07df8bf7

thank you.

**Comment by yajra** [comment]
Thanks for reporting. The problem here is that `html` package does not support 5.2 yet. It's on master branch but no stable/tagged version was released. Forcing v5.1 will not solved the issue too. https://github.com/LaravelCollective/html/issues/133

**Comment by yajra** [comment]
Duplicate #313. Please see my suggestions there for temporary workaround. Thanks!
