### ISSUE TITLE
SQL injection using length input

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [yajra/laravel-datatables#3141]
### Summary of problem or feature request
So my friends are using this package and seems like someone have been using sql injection on them
after tons of investigations and using telescope to see what's going on, seems like the length input isn't validated as numeric at all.

### Code snippet of problem

![image](https://github.com/yajra/laravel-datatables/assets/30704271/3d703256-fb91-41fb-876c-61ea0c2d6ad4)

### System details

- Operating System: Windows Server 2022
- PHP Version: 8:0:30
- Laravel Version: 8.0
- Laravel-Datatables Version: 1.5
- Laravel Datatables Oracle Version: 9.8

**Comment by yajra** [comment]
If you can't upgrade for some reason, feel free to submit a PR to the `9.0` branch. Thanks!

**Comment by jonjieviduya** [comment]
@yajra Is there any breaking changes when we upgrade to 10.x version? I'm currently using laravel8. And I also noticed that the website documentation is down.

**Comment by yajra** [comment]
The docs site is fixed. I think there is not much-breaking change from 9.x to 10.x and 11.x
