### ISSUE TITLE
Argument '1' passed to render() is expected to be of type Yajra\DataTables\Services\view-string|null, string given

### ISSUE THREAD

**Issue by gokhankapucuoglu** [yajra/laravel-datatables#3158]
Argument '1' passed to render() is expected to be of type Yajra\DataTables\Services\view-string|null, string given

class StudentController extends Controller
{
    public function index(StudentsDataTable $dataTable)
    {
        return $dataTable->render('admin.students.index');
      }
}

![image](https://github.com/yajra/laravel-datatables/assets/87229790/055832fe-d661-4db2-a4c6-252343bc1173)
![image](https://github.com/yajra/laravel-datatables/assets/87229790/ef7a0a06-1c32-4426-a875-5338f7ff963a)

Project works but warning the ide always. How can i fix it

- Operating System w11
- PHP Version 8.2
- Laravel Version 11
- Laravel-Datatables Version  11

**Comment by yajra** [comment]
I think this would be fixed if you install ide-helper or larastan.

**Comment by gokhankapucuoglu** [comment]
yeap. composer remove barryvdh/laravel-ide-helper  after fix. Thanks.
