### ISSUE TITLE
Search not working after modyfying source

### ISSUE THREAD

**Issue by Dambar93** [yajra/laravel-datatables#3161]
When modifying source of dataTable, table search in frontend is not working and returning empty table. Until I'm not writing in search it shows records by filtering. If there is solution to this or I need to use other search tools? Or I'm doing it all wrong?

    /**
     * Build the DataTable class.
     *
     * @param QueryBuilder $query Results from query() method.
     */
    public function dataTable(QueryBuilder $query): EloquentDataTable
    {
        $user = Auth::user();

        $dataTable = new EloquentDataTable($query);

        $dataTable->addColumn('action', 'order.dt.actions')
            ->addColumn('date', function (Order $order) {
                return $order->created_at->format('Y-m-d');
            })
            ->addColumn('car_plate', function (Order $order) {
                return $order->car->number_plate ?? '';
            })
            ->addColumn('id', function (Order $order) {
                return $order->internal_id;
            })
            ->rawColumns(['action']);
            
        return $dataTable;
    }

    /**
     * Get the query source of dataTable.
     */
    public function query(Order $model): QueryBuilder
    {
        $user = Auth::user();
        return $model->where('driver_id', $user->driver_id)
                     ->orWhere('customer_id', $user->customer_id);
    }

### System details

- Operating System macOS
- PHP Version 8.2.0
- Laravel Version 11
- Laravel-Datatables Version 11

**Comment by yajra** [comment]
`addColumn` disables search/sort by default since it is considered computed and not part of the DB. You can use [filterColumn](https://yajrabox.com/docs/laravel-datatables/10.0/filter-column#main-content) to handle the search instead.
