### ISSUE TITLE
Does it support lumen?

### ISSUE THREAD

**Issue by jasonz1987** [yajra/laravel-datatables#317]
great plugin,but how can i use it in my lumen project?

**Comment by MightySCollins** [comment]
I managed to get the project working in Lumen for 5.x but it seems I cannot get 6.0 to work. I cant remember everything I did but all the information is out there...

Here is just a few things to get you started

I had to add a few lines to my `bootstrap/app.php` file:
```
$app->withFacades();
class_alias('yajra\Datatables\Datatables', 'Datatables');
$app->configure('datatables');
$app->register('yajra\Datatables\DatatablesServiceProvider');
```

I also had to create a config folder and did a `php artisan vendor:publish` and after some shouting it all seemed to work.

The steps are almost the same for any plugin you want to convert to using Lumen from Laravel so if I was you just Google.

**Comment by jasonz1987** [comment]
@MightySCollins tks for your answer,it's also support lumen for 6.0, i make some little changes.

uncomment these lines in registerCommands method of DatatablesServiceProvider

<pre>

 // $loader = \Illuminate\Foundation\AliasLoader::getInstance();
  // $loader->alias('Datatables', \Yajra\Datatables\Datatables::class);
</pre>

and add base_path(), config_path() in your autoload helper

<pre>

if ( ! function_exists('config_path'))
{
    /**
     * Get the configuration path.
     *
     * @param  string $path
     * @return string
     */
    function config_path($path = '')
    {
        return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
    }
}

if(!function_exists('public_path'))
{
        /**
        * Return the path to public dir
        * @param null $path
        * @return string
        */
        function public_path($path=null)
        {
                return rtrim(app()->basePath('public/'.$path), '/');
        }
}

</pre>

**Comment by yajra** [comment]
Thanks for the snippets. The package does not officially support Lumen but will try to maybe add a separate service provider for Lumen or maybe some try catch to handle this.

**Comment by naneri** [comment]
any progress?

**Comment by poornimasudha** [comment]
I just followed the above mentioned procedure.when I am trying to publish vendor in lumen,I am getting this error
Class 'yajra\Datatables\Datatables' not found .How can I fix this?

**Comment by VuongTran21** [comment]
`class_alias('Yajra\DataTables\DataTables', 'Datatables');
$app->configure('datatables');
$app->register('Yajra\DataTables\DataTablesServiceProvider');`

Insert these snippet codes into boostrap/app.php, it actually works for me.
Thanks @MightySCollins , but seem `yajra` namespace with lower case "y" is not working for me.

**Comment by proraesa** [comment]
> `class_alias('Yajra\DataTables\DataTables', 'Datatables');`
> `$app->configure('datatables');`
> `$app->register('Yajra\DataTables\DataTablesServiceProvider');`
> 
> Insert these snippet codes into boostrap/app.php, it actually works for me.
> Thanks @MightySCollins , but seem `yajra` namespace with lower case "y" is not working for me.

this one is work for me thanks. with lumen 8.x
