### ISSUE TITLE
how i can pass data into new page transactions.print

### ISSUE THREAD

**Issue by Mohamed-Elaraby** [yajra/laravel-datatables#3172]
The print options should be modified via print preview by overriding the default view used in printing.

``` php
class TransactionsDataTable extends DataTable
{
    protected $printPreview = 'transactions.print';
...
```

Copy `resources/views/vendor/datatables/print.blade.php` content to `resources/views/transactions/print.blade.php` and append any necessary info you wanted to print.

_Originally posted by @yajra in https://github.com/yajra/laravel-datatables/issues/759#issuecomment-248494798_

**Comment by yajra** [comment]
At the moment, you can override the method `getDataForPrint` or the `printPreview`.

```php
    public function printPreview(): Renderable
    {
        $data = $this->getDataForPrint();

        return view($this->printPreview, compact('data'));
    }

    /**
     * Get mapped columns versus final decorated output.
     */
    protected function getDataForPrint(): array
    {
        $columns = $this->printColumns();

        return $this->mapResponseToColumns($columns, 'printable');
    }
```
