### ISSUE TITLE
Tailwind support

### ISSUE THREAD

**Issue by Arkhas** [yajra/laravel-datatables#3174]
I saw this issue, but it is locked : 

https://github.com/yajra/laravel-datatables/issues/3044

any update on the subject ? :)

**Comment by yajra** [comment]
There are several movements on the subject. See this forum https://datatables.net/forums/discussion/65775/integration-of-tailwind-css/p3

I might try the following when I get the chance:

https://preline.co/docs/datatables.html
https://flowbite.com/docs/plugins/datatables/

**Comment by Arkhas** [comment]
do you think your library works with any of this package ?

**Comment by yajra** [comment]
Yes, the `laravel-datatables` package works as expected. I am already using TailwindCSS on my latest projects. It works fine, **BUT** lots of js and css customizations were needed to make it work well along with the Editor library.
