### ISSUE TITLE
Currency shows strange characters when viewed using MS excel

### ISSUE THREAD

**Issue by jonjieviduya** [yajra/laravel-datatables#3177]
### Summary of problem or feature request

When viewing the exported file, the Philippine Peso (₱) currency shows strange characters: `â,±`. I tried both `&#8369;` and the `₱` but both of these are not working and still show the same strange characters.

### Code snippet of problem
```
->addColumn('Order Amount', function ($payment) {
	return '&#8369;' . number_format((float) $payment->amount, 2);
})
```

### System details

- Operating System: win10
- PHP Version: 8.1
- Laravel Version: 8
- Laravel-Datatables Version: 9.11

**Comment by yajra** [comment]
You might need to add `Order Amount` to the [raw columns](https://yajrabox.com/docs/laravel-datatables/11.0/raw-columns#main-content).

Or you can use the `render` option via js to handle the money formatting.

**Comment by yajra** [comment]
Oh, the context was on export ~~ I will have to review this one. I think the formatting should handle on the excel cell format level for this to work.

**Comment by yajra** [comment]
There is a new feature released via https://github.com/yajra/laravel-datatables-buttons/pull/186 and https://github.com/yajra/laravel-datatables-buttons/pull/187. That might help in your case.

**Comment by jonjieviduya** [comment]
@yajra yes it is for export. Using these links, how can I format the currency? BTW it is working when you open it using google sheet. The issue only occurs when opening in ms excel.

> There are new features released via [yajra/laravel-datatables-buttons#186](https://github.com/yajra/laravel-datatables-buttons/pull/186) and [yajra/laravel-datatables-buttons#187](https://github.com/yajra/laravel-datatables-buttons/pull/187). That might help in your case.

**Comment by yajra** [comment]
Try using `exportFormat('₱#,##0.00')`. This is how I usually check Excel.

![image](https://github.com/user-attachments/assets/32e564b2-68df-4d30-88a6-565173987981)

**Comment by jonjieviduya** [comment]
@yajra I still got the same output.

**Comment by yajra** [comment]
I just tested this and it works fine for me:

Id | Account UUID | Account Id | Member UUID | Balance | Date Created
-- | -- | -- | -- | -- | --
12 | 871d932d-09b8-404c-917d-cc1cfde8873d | 79133479 | a09eecb3-4603-411c-91d8-dfa534e9725b | ₱ 0.00 | 2024-09-22
11 | cb0db73c-acf0-4021-9edc-1d8e57f9c5d0 | 38123042 | 938d9a51-d380-42c6-9505-fa3c2f224fe1 | ₱ 0.00 | 2024-09-22


```php
DecimalMoneyColumn::make('balance')
    ->exportRender(fn($row, $amount) => '₱ '.number_format($amount / 100, 2)),
```

Here is my Decimal money class, need this since I used int to store the amount:

```php
class DecimalMoneyColumn extends Column
{
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->addClass('text-right')
            ->render('(data/100).toFixed(2).replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")');
    }
}
```

**Comment by jonjieviduya** [comment]
@yajra what is this code for? Sorry I'm a bit confused since I am using float instead of int

```
$this->addClass('text-right')
            ->render('(data/100).toFixed(2).replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")');
```

**Comment by jonjieviduya** [comment]
Are you using Laravel Excel for this project @yajra?

**Comment by jonjieviduya** [comment]
Also, it terms of upgrading the package from `v9` to `v10` to `v11`, I think the documentation is no longer updated.

https://yajrabox.com/docs/laravel-datatables/10.0/upgrade

@yajra

**Comment by yajra** [comment]
> Are you using Laravel Excel for this project @yajra?

Yes but for small export only. However, for newer projects, I skipped Laravel Excel and moved to OpenSpout / fastexcel. For thousands to millions of exports, you can use https://github.com/yajra/laravel-datatables-export.

**Comment by yajra** [comment]
> Also, it terms of upgrading the package from `v9` to `v10` to `v11`, I think the documentation is no longer updated.
> 
> https://yajrabox.com/docs/laravel-datatables/10.0/upgrade
> 
> @yajra

Thanks for noticing, upgrading from 10 to 11 is just a matter of changing the version in composer. No major breaking change.

**Comment by jonjieviduya** [comment]
@yajra Any breaking changes from yajra-datatables v9 to v11? I'm planning to upgrade its version from 9 to 11.

My system setup details in case you need it:
PHP Version: **8.1**
Laravel Version: **8**
Laravel-Datatables Version: **9.11**

**Comment by yajra** [comment]
None that I know of. The version change is mostly due to aligning to the Laravel Framework version.
