### ISSUE TITLE
How to trigger reload

### ISSUE THREAD

**Issue by donny26utama** [yajra/laravel-datatables#3179]
`
@push('scripts')
    {{ $dataTable->scripts(attributes: ['type' => 'module']) }}
@endpush
`

I have an ajax action, after complete I want to reload the datatable.  how to call datatable ajax reload?

**Comment by yajra** [comment]
Just call the draw event:

```js
LaravelDataTables['table-id'].draw()
```

**Comment by donny26utama** [comment]
I have tried, but `LaravelDataTables` is undefined

**Comment by donny26utama** [comment]
here is my code
`@push('page-script')
    {{ $dataTable->scripts(attributes: ['type' => 'module']) }}
    <script>
        console.log(LaravelDataTables['productcategories-table'].draw());
    </script>
@endpush
`

**Comment by yajra** [comment]
It seems you're using vite, inline scripts should be mostly a module type. You can also add the document ready if needed.

```js
    <script type="module">
        LaravelDataTables['productcategories-table'].draw();
    </script>
```

**Comment by donny26utama** [comment]
![image](https://github.com/user-attachments/assets/3f36852c-915c-426c-842e-904522743097)
I have try your suggestion, but still not work.
![image](https://github.com/user-attachments/assets/cd025df1-8b27-40ed-bc11-da19d3e673d0)

**Comment by donny26utama** [comment]
@yajra please help me

**Comment by yajra** [comment]
I think you need to call the script when dom is ready. The complete script should be something like:

```js
$(function() {
  $('.btn-reload').on('click', function() {
    LaravelDataTables['productcategories-table'].draw();
  });
})
