### ISSUE TITLE
Lumen AliasLoader not found

### ISSUE THREAD

**Issue by MightySCollins** [yajra/laravel-datatables#318]
Although you don't officially support lumen I just though I would point out that Lumen does not support `Illuminate\Foundation\AliasLoader` so it might be worth doing a check and only making it call `registerAliases()` if it is a detected Laravel install and making Lumen users setup the alias themselves.

**Comment by jasonz1987** [comment]
see https://github.com/yajra/laravel-datatables/issues/317 , i give the answer:

if you set class_alias in your bootstrap/app.php, you don't need `registerAliases()` in the DatatablesServiceProvider,so you can comment this line 

<pre> 
 $this->registerAliases();
</pre>

**Comment by MightySCollins** [comment]
@jasonz1987 Thats great but I am not a fan of changing files in my `vendor` folder I would be really nice if there was some sort of check. I ended up just putting the code in a try catch block then I could use the same fork for laravel and lumen

**Comment by yajra** [comment]
Fixed on v6.1.0. Kindly check and verify. Thanks!
