### ISSUE TITLE
Support for Mongodb database

### ISSUE THREAD

**Issue by khaleelrasakh** [yajra/laravel-datatables#3189]
### Summary of problem or feature request
Type mismatch when extending  QueryDataTable

Type  Illuminate\Contracts\Database\Query\Builder to MongoDB\Laravel\Query\Builder 

### Code snippet of problem
   public function __construct(protected QueryBuilder $query)
    {

### System details

- Operating System
- PHP 8.3
- Laravel 11
- Laravel-Datatables Version

**Comment by yajra** [comment]
Unfortunately, this is still not yet supported. I don't have a use case for MongoDB and can't find time to work on this. Feel free to submit a PR. Thanks!
