### ISSUE TITLE
Fix Resource example in code or documentation

### ISSUE THREAD

**Issue by funder7** [yajra/laravel-datatables#3191]
### Summary of problem or feature request

The problem reported in #2995 has not been fixed.
OP said that Yajra Datatables 9.x works with the example provided in the documentation, but users using the latest version are not able to use resources without the workaround provided in the github issue.

It would be nice to do one of the following:
- restore the expected behaviour in the library (best)
- update the example in the doc

### Code snippet of problem

Working
```php
$data     = User::paginate(10);
$resource = User::collection($data);

return Datatables::of($resource->toArray($request))->make();
```

[Documentation example](https://yajrabox.com/docs/laravel-datatables/master/response-resource) (not working)
```php
$data     = User::paginate(10);
$resource = User::collection($data);

return Datatables::of($resource)->toJson();
```

### System details

- Operating System Win11
- PHP Version 8.3
- Laravel Version 11
- Laravel-Datatables Version 11

**Comment by yajra** [comment]
Thank you for reporting, will review it as soon as I can. Please do not hesitate to submit a PR if possible.
