### ISSUE TITLE
Where to put columns.render options ?

### ISSUE THREAD

**Issue by stepgr** [yajra/laravel-datatables#3195]
### Summary of problem or feature request

In plain JS something like below is used to make Blade display an icon when a boolean value is set.
Following your example  from Quick Starter where am I supposed to add this code below ? Blade file ? ControllerDataTable.php ?
Controller.php ? I'm lost !! 
 
### Code snippet of problem

```
"columnDefs": [{
  "targets": [5, 6],
  "render": function ( data, type, row ) {
    if ( data == "1" )
    {return '<i class="fas fa-check-circle"></i>';}
    else if ( data == "0" )
    { return ' ';}
  },
}],
```

### System details

- Linux Debian
- PHP 8.3.13
- Laravel 11.9
- Laravel-Datatables Version 11.0

**Comment by stepgr** [comment]
Ok continuing on my own  can someone confirm I'm going on the right track ? 
this is expanding the Quick starter code but there is formatting issues when I put the render function 
after the targets : 

```
public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->setTableId('vessels-table')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    //->dom('Bfrtip')
                    ->orderBy(2, 'asc')
                    ->selectStyleSingle()
                    ->columnDefs(
                        ['targets', [4]],
                    )
```

**Comment by yajra** [comment]
You can do it via Column builder:

```php
Column::make('amount')->renderRaw('function() {alert("test")}'),
Column::make('amount')->render('(data).toFixed(2).replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")');
```

You can also use a renderer. Assuming you have this render function `$.fn.dataTable.render.rendererFunction`:

```php
Column::make('amount')->renderJs('rendererFunction')
```

**Comment by stepgr** [comment]
Sorry for late reply , confirmed works as you described  thank you , only issue not resolved yet is how to escape the html tag inside the first return code block , I will look into into it later on , thanks again .
