### ISSUE TITLE
Fluent on Button class stopped working

### ISSUE THREAD

**Issue by OzanKurt** [yajra/laravel-datatables#3197]
It works for `Column`
![image](https://github.com/user-attachments/assets/78da6c80-2702-49e1-96a8-fe570f7d05df)
![image](https://github.com/user-attachments/assets/565aa141-9a73-49c8-890b-dd14172a490d)

It doesn't work for `Button`
![image](https://github.com/user-attachments/assets/d8ac2d44-12aa-4f4e-862f-82eb15730a15)
![image](https://github.com/user-attachments/assets/1a44d5ea-1fdb-4894-b197-2497719cb48e)

**Comment by OzanKurt** [comment]
I am sorry but this was actually a breaking change. 😢 

https://github.com/yajra/laravel-datatables-html/commit/dd652c96b0e1fdf67f8e0bc7e62fd8fd34fe9473#diff-d8dd76a4cd27a40c9d8812ddc0ebe070d8be6f213e74509f5e86fd429103211dR12

The `__call` method from `Macroable` overwritten the `__call` from `Fluent`

Macroable:
```php
    /**
     * Dynamically handle calls to the class.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     *
     * @throws \BadMethodCallException
     */
    public function __call($method, $parameters)
    {
        if (! static::hasMacro($method)) {
            throw new BadMethodCallException(sprintf(
                'Method %s::%s does not exist.', static::class, $method
            ));
        }

        $macro = static::$macros[$method];

        if ($macro instanceof Closure) {
            $macro = $macro->bindTo($this, static::class);
        }

        return $macro(...$parameters);
    }
```

Fluent:
```php
    /**
     * Handle dynamic calls to the fluent instance to set attributes.
     *
     * @param  TKey  $method
     * @param  array{0: ?TValue}  $parameters
     * @return $this
     */
    public function __call($method, $parameters)
    {
        $this->attributes[$method] = count($parameters) > 0 ? reset($parameters) : true;

        return $this;
    }
```

**Comment by OzanKurt** [comment]
@yajra

I've fixed the issue by merging the `__call` methods of both.

https://github.com/yajra/laravel-datatables-html/pull/227

Can we please merge this asap?

**Comment by yajra** [comment]
I agree and apologize for the BC. I already identified the issue via https://github.com/yajra/laravel-datatables/issues/3190#issuecomment-2458887426 but I haven't had the chance to fix it. Thanks for the PR.

**Comment by OzanKurt** [comment]
Thank you!

**Comment by OzanKurt** [comment]
I hate it when PHP cannot understand imports by itself sometimes!

Great spot! 👍🏻
