### ISSUE TITLE
Would like latest versions of dependent packages

### ISSUE THREAD

**Issue by cheshirec7** [yajra/laravel-datatables#3198]
### Summary of problem or feature request

When I add laravel-datatables to my project:

"yajra/laravel-datatables": "^11.0"

I get v2.3.0 of phpoffice/phpspreadsheet and v11.3.0 of yajra/laravel-datatables-export

If I then add:

"roave/security-advisories": "dev-latest"

Then I run "composer update":

Downgrading phpoffice/phpspreadsheet (2.3.0 => 1.29.4)
Downgrading yajra/laravel-datatables-export (v11.3.0 => v11.1.1)

Found 2 security vulnerability advisories affecting 1 package.

"composer outdated" says:

phpoffice/phpspreadsheet        1.29.4 3.4.0  
yajra/laravel-datatables-export 11.1.1 11.3.0

I think it would be nice to get the latest versions of these packages, if possible.

Thanks!

### System details

- Windows 10
- PHP 8.3
- Laravel 11

**Comment by yajra** [comment]
Sorry for the late response, this should be fixed on the latest version of yajra/laravel-datatables-export. Thanks!
