### ISSUE TITLE
Empty result on first request when APP_DEBUG=true

### ISSUE THREAD

**Issue by llioor** [yajra/laravel-datatables#320]
Hi, I'm using datatables and it is amazing.
The only problem I have is that I'm loading the datatable with ajax on load function and the first request returns empty result when the second (right click on ajax request in console and choosing the Replay XHR option) returns results.

Some facts:
1. Both ajax are exactly the same because I'm using "replay XHR".
2. Both ajax return status code 200 OK.
3. I have 8 columns and each of them includes HTML. When I remove the first 4 columns it suddenly works. Then, when I bring them back it stops to work and then when I remove the last 4 columns it back to work so it means all the columns are OK and the problem is with the amount of data????! =\?

I played with it foe a while and when I'm changing APP_DEBUG in .env file to false it works!!! I'm on development env so I want to keep it APP_DEBUG=true but it is not working.

Any help?
Thanks!

**Comment by yajra** [comment]
Can you please paste some snippets or gists so we can review what might went wrong? Thanks!

**Comment by yajra** [comment]
Please submit new issue if needed. Thanks!

**Comment by slamgundam** [comment]
I also have same issue, weird thing is that i have applied 3 datatables in different pages, one of the page is not return the data, other 2 do return the data.

i already checked these 3 datatables do have data

Set `my APP_DEBUG=true`, one of datatables failed return data, other 2 working fine
Set `my APP_DEBUG=false`, all datatables are working fine


is there anything I need to be aware of it?  I'm using version 9.0, I upgraded from 8.0 to 9.0, and I also upgraded the datatables JS to latest.

**Comment by yajra** [comment]
You might be including a binary / blob object on response and the debugger was not able to parse it to json format?

**Comment by slamgundam** [comment]
only pure text.

I think package have conflict with 
https://github.com/mlanin/laravel-api-debugger

if i uninstall the laravel-api-debugger and `APP_DEBUG=true`, it works fine.

Anything different from laravel-datatables 8.0 and laravel-datatables 9.0, should I be aware of?

both stay together fine when  it in laravel-datatables 8.0
(I'm still wishing to use laravel-api-debugger though, hence have other APIs that I need to use)


how to detect json have binary / blob object? b/c it failed on API side, before it start the parsing

**Comment by yajra** [comment]
The only changes as far as I remember that relates on this is PR: https://github.com/yajra/laravel-datatables/pull/2088

I may not be able to support that package, so please submit a PR if needed. Thanks!

**Comment by ceswebmaster** [comment]
Looking at 2008 PR mentioned above and this thread, is there any solution proposed for this? I just noticed I was having this issue when I turned off the debug bar. I can see the results are being returned in the Network tab but are not being included in the table. 

APP_DEBUG in .env = false // this breaks
setting debug to false in config/app.php also breaks
