### ISSUE TITLE
Declaration of Column::data does not compatible with Fluent::data

### ISSUE THREAD

**Issue by fdteam-deanie** [yajra/laravel-datatables#3201]
### Error

Declaration of Yajra\DataTables\Html\Column::data(array|string $value): static must be compatible with Illuminate\Support\Fluent::data($key = null, $default = null)

### Code snippet of problem

File vendor/yajra/laravel-datatables-html/src/Html/Column.php, function data (line 305 - 310) was the reason:

```php
    public function data(array|string $value): static
    {
        $this->attributes['data'] = $value;

        return $this;
    }
```

### System details

- Operating System: Mac OS 15
- PHP Version: 8.3
- Laravel Version: laravel/framework ^11.34
- Laravel-Datatables Version: yajra/laravel-datatables ^11.0

### Solution

File vendor/yajra/laravel-datatables-html/src/Html/Column.php, change function data (line 305 - 310) to:

```php
    public function data($key = null, $default = null): static
    {
        $this->attributes['data'] = $key;

        return $this;
    }
```

**Comment by alberto-morais-oliveira-f** [comment]
I have the same problem, this was caused by the update in Laravel

**Comment by madmouse17** [comment]
I have the same problem now,

**Comment by madmouse17** [comment]
While I commented on the function, and my website is running normally again, please improve the function

![image](https://github.com/user-attachments/assets/a56fdedb-6a2c-434b-8740-6a41b945d4f7)

**Comment by asheekofficial** [comment]
any updates? having this issue from today

**Comment by asoltec** [comment]
same error with me

**Comment by OzanKurt** [comment]
The solution is avoiding the error but having a second parameter here doesn't make sense, we need to find a proper way to implement this method.

> ### Solution
> File vendor/yajra/laravel-datatables-html/src/Html/Column.php, change function data (line 305 - 310) to:
> 
> ```
>     public function data($key = null, $default = null): static
>     {
>         $this->attributes['data'] = $key;
> 
>         return $this;
>     }
> ```

**Comment by yajra** [comment]
Should we petition to revert the latest PR (https://github.com/laravel/framework/pull/53665), remove the data method added to the framework, or move on with the quick solution suggested by @OzanKurt?

**Comment by OzanKurt** [comment]
I would personally like a revert.

The new pull request doesn't seem to be adding much to the codebase other than "forcefully combining" two completely different classes' (`Request` and `Fluent`) functionalities.

***BUT***, while we wait for an action we should implement a temporary solution for the `data` method.

**Comment by vipertecpro** [comment]
How about giving us a way to override entire fluent method, i mean leave that door open so that we won't 100% rely on package manager to make that update, it is possible ?

**Comment by donny26utama** [comment]
or just down to previous laravel version until any they fix it

**Comment by nuernbergerA** [comment]
@yajra why dont you copy laravels fluent class into your codebase and you are good?

**Comment by OzanKurt** [comment]
> @yajra why dont you copy laravels fluent class into your codebase and you are good?

That is actually a great idea, having fluent as a standalone package. Simply something like `xxx/fluent` which would not nuke anybodies codebase. 😄

**Comment by yajra** [comment]
> @yajra why dont you copy laravels fluent class into your codebase and you are good?

I agree, this is my initial plan if the revert never happens in the framework. It seems like you went ahead with it :)

**Comment by HydroMoon** [comment]
For now you can downgrade using `composer update --with "laravel/framework:11.33.1"`.

**Comment by crynobone** [comment]
A good solution for this is to use a decorator class instead of extending Fluent directly:

```
<?php

use ArrayAccess;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Contracts\Support\Jsonable;
use Illuminate\Support\Traits\ForwardsCalls;
use JsonSerializable;

/**
 * @template TKey of array-key
 * @template TValue
 *
 * @implements \Illuminate\Contracts\Support\Arrayable<TKey, TValue>
 * @implements \ArrayAccess<TKey, TValue>
 */
abstract class FluentDecorator implements Arrayable, ArrayAccess, Jsonable, JsonSerializable
{
    use ForwardsCalls;

    /**
     * The Fluent instance.
     *
     * @var \Illuminate\Support\Fluent<TKey, TValue>
     */
    protected $fluent;

    /**
     * Create a new fluent instance.
     *
     * @param  iterable<TKey, TValue>  $attributes
     * @return void
     */
    public function __construct($attributes = [])
    {
        $this->fluent = new \Illuminate\Support\Fluent($attributes);
    }

    /**
     * Convert the fluent instance to an array.
     *
     * @return array<TKey, TValue>
     */
    public function toArray()
    {
        return $this->fluent->getAttributes();
    }

    /**
     * Convert the object into something JSON serializable.
     *
     * @return array<TKey, TValue>
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }

    /**
     * Convert the fluent instance to JSON.
     *
     * @param  int  $options
     * @return string
     */
    public function toJson($options = 0)
    {
        return json_encode($this->jsonSerialize(), $options);
    }

    /**
     * Determine if the given offset exists.
     *
     * @param  TKey  $offset
     * @return bool
     */
    public function offsetExists($offset): bool
    {
        return $this->fluent->offsetExists($offset);
    }

    /**
     * Get the value for a given offset.
     *
     * @param  TKey  $offset
     * @return TValue|null
     */
    public function offsetGet($offset): mixed
    {
        return $this->fluent->offsetGet($offset);
    }

    /**
     * Set the value at the given offset.
     *
     * @param  TKey  $offset
     * @param  TValue  $value
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        $this->fluent->offsetSet($offset, $value);
    }

    /**
     * Unset the value at the given offset.
     *
     * @param  TKey  $offset
     * @return void
     */
    public function offsetUnset($offset): void
    {
        $this->fluent->offsetUnset($offset);
    }

    /**
     * Handle dynamic calls to the fluent instance to set attributes.
     *
     * @param  TKey  $method
     * @param  array{0: ?TValue}  $parameters
     * @return $this
     */
    public function __call($method, $parameters)
    {
        return $this->forwardDecoratedCallTo($this->fluent, $method, $parameters);
    }

    /**
     * Dynamically retrieve the value of an attribute.
     *
     * @param  TKey  $key
     * @return TValue|null
     */
    public function __get($key)
    {
        if (method_exists($this->fluent, 'value')) {
            return $this->fluent->value($key);
        }

        return $this->fluent->get($key);
    }

    /**
     * Dynamically set the value of an attribute.
     *
     * @param  TKey  $key
     * @param  TValue  $value
     * @return void
     */
    public function __set($key, $value)
    {
        $this->fluent->offsetSet($key, $value);
    }

    /**
     * Dynamically check if an attribute is set.
     *
     * @param  TKey  $key
     * @return bool
     */
    public function __isset($key)
    {
        return $this->fluent->offsetExists($key);
    }

    /**
     * Dynamically unset an attribute.
     *
     * @param  TKey  $key
     * @return void
     */
    public function __unset($key)
    {
        $this->fluent->offsetUnset($key);
    }
}
```

**Comment by eduah33b** [comment]
> For now you can downgrade using `composer update --with "laravel/framework:11.33.1"`.

I have is working in 11.33.2 as well

**Comment by amiranbari** [comment]
Same problem here!
