### ISSUE TITLE
throw a exception:"order by '0'" by demo

### ISSUE THREAD

**Issue by chrisho** [yajra/laravel-datatables#322]
SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'order clause' (SQL: select `id`, `name`, `email`, `created_at`, `updated_at` from `users` order by `0` asc limit 10 offset 0)

i think "order by 1" is right

**Comment by MightySCollins** [comment]
Which page do you see this on?
I have been getting this error for a while and it is really bugging me I cannot find out the problem. Is anyone else having this or have I done something wrong?

**Comment by chrisho** [comment]
i see the demo, it has problem for all

**Comment by MightySCollins** [comment]
I just checked out the demo and get the same error on a clean C9 environment and my application has this problem too

**Comment by yajra** [comment]
Thanks for reporting. Will try to check this as soon as I can. Happy New Year!

**Comment by yajra** [comment]
I just update the demo packages and used v6.1.0 of the package and seems to work well for me? Can you give some details on how to replicate the issue? Thanks!

**Comment by chrisho** [comment]
the new version has same problem, because mysql cant support "order by 0" , but can run "order by 1"
I open the \src\Engines\QueryBuilderEngine.php line 258

**Comment by MightySCollins** [comment]
If you have a Cloud 9 account you can see it at https://ide.c9.io/scollins/datatables or the demo at http://datatables-scollins.c9users.io/eloquent/basic. Its a new install from git running 6.1.0.

**Comment by yajra** [comment]
Issue was raised when using `make()` response. Fixed on v6.1.1. Thanks for reporting!
