### ISSUE TITLE
Update API Doc on site!

### ISSUE THREAD

**Issue by intech** [yajra/laravel-datatables#324]
https://github.com/yajra/laravel-datatables/blob/6.0/src/Engines/BaseEngine.php#L819
Spend an hour of time, thought has to copy the entire library of vendor and remake.
But there was method in the source code ready! Spent time. Update API Doc on the site.

**Comment by yajra** [comment]
Thanks for reporting. Forgot to regenerate the API docs to v6. Anyways, it's up to date now. Thanks!
