### ISSUE TITLE
Cannot Modify HtmlBuilder on Services\DataTable

### ISSUE THREAD

**Issue by mcordingley** [yajra/laravel-datatables#326]
I'm in much the same situation as described in #208. My tables are each in a separate tab on the page and load via AJAX if the tab is selected. The individual tables are each set in their own routes, so only one really exists per route. If loaded via the tab, I alter the `X-Requested-With` AJAX request header to make the initial load of the route return an HTML fragment. The value could be practically anything, so long as it is not "XMLHttpRequest". The HTML version loads up and the table tries to initialize itself. It then fails miserably when trying to load the data.

The trouble is that when the data table is set up, it tries to load its data via AJAX, but the "ajax" property is set to an empty string. I tried to set that on my instance of `Yajra\Datatables\Services\DataTable`, but it looks like the returned `HtmlBuilder` from the `html` method is a fresh instance with each invocation of the method. So, I can modify state on the builder, but it doesn't mean anything as the builder used when rendering the view is a new one with default state.

I'm overriding that function in my own subclass to cache the builder object and return the same instance on subsequent calls, but this seems like it ought to be handled in the base class.

**Comment by yajra** [comment]
Your case seems a bit complicated and can't clearly visualize it. ATM, DataTable Service implementation is a bit limited to a single DataTable per page. Will try to create a multiple tables in a single page on my free time to check this. If you have a solution in mind, the package is open to accept a PR. Thanks!

**Comment by yajra** [comment]
2 DataTables [demo](http://datatables.yajrabox.com/services/two-datatables) was contributed in docs. Please check it out on how to implement this. Thanks!
