### ISSUE TITLE
How I can do a query count() in a column, with option to search and sort

### ISSUE THREAD

**Issue by aminebk** [yajra/laravel-datatables#328]
Hi all,

First I want to thank everyone who have made this amazing plugin, and for the very helpfull support here.

I have 2 tables : subject, messages 

In my datatable (I have laravel4), I want to show subjects list, and a column total responses (only response that have statut=approved).

my tables looks like : 
subject(idsubject, title)
responses(idresponse, idsubject, message, statut)

I have found that addcolumn is not possible as it's not searchable, so it's possible to make a custom query before doing return Datatables::of($subjects) ?

Thanks

**Comment by Skintillion** [comment]
You have to say that the column is not searchable in your column
definitions.

[
                    "title" => "Custom Column",
                    "orderable" => false,
                    "searchable" => false,
                    "data" => "customcolumn"
                ],

**Comment by yajra** [comment]
See this [demo](http://datatables.yajrabox.com/eloquent/count) for ref.

**Comment by aminebk** [comment]
Thanks all
