### ISSUE TITLE
Column searchable via collections

### ISSUE THREAD

**Issue by xLink** [yajra/laravel-datatables#335]
Using ```$table->filter(function($instance) {})``` i can filter out what rows for my search, but passing it back to ```$instance->collection``` seems to be getting ignored??

```php
            /*
            TODO: this filters out the correct rows, but doesnt pass it back to the datatable???
            $table->filter(function ($instance) use ($request, $columns) {

                foreach ($request->get('columns') as $idx => $info) {
                    if (empty(array_get($info, 'search.value', null))) {
                        continue;
                    }

                    if (array_get($info, 'searchable', false) === false) {
                        continue;
                    }
                    $key = array_get($info, 'data', null);

                    $instance->collection = $instance->collection->filter(function ($row) use ($info, $key) {
                        return str_contains(strtolower($row->$key), strtolower(array_get($info, 'search.value'))) ? true : false;
                    });

                }

            });*/
```

**Comment by yajra** [comment]
I think this has something to do with Laravel version. What versions are you using please? Will try to replicate the issue on my free time. Thanks!

**Comment by xLink** [comment]
Laravel 5.1

**Comment by yajra** [comment]
Seems to work well on [demo](http://datatables.yajrabox.com/collection/custom-filter) but it uses Laravel 5.0 though. 

BTW, are you sure that filtering is getting reached on your code? This code might be blocking?

```php
if (array_get($info, 'searchable', false) === false) {
  continue;
}
```

**Comment by xLink** [comment]
@yajra nah ive had some debug happening below that, that ive seen, the filter is working properly its just not being used :S

**Comment by yajra** [comment]
@xLink sorry for overlooking this. I just realized that I already upgraded my demo to Laravel 5.1 and seems to work well for me. Are you still having this issue?

**Comment by xLink** [comment]
yup, just tried using the latest version, still on L5.1, and the filter is working, but setting `$instance->collection` is having no effect & the datatable is showing zero results too

**Comment by xLink** [comment]
@yajra any ideas on this?

**Comment by yajra** [comment]
@xLink, sorry but I can't replicate this issue. Looking at this [Laravel 5.1 Demo](http://datatables.yajrabox.com/collection/custom-filter), everything seems to work as expected.

**Comment by xLink** [comment]
okay looking at your demo some more, mebe i screwed up somewhere

**Comment by xLink** [comment]
hey @yajra, okay so i rebuilt the JS some, and managed to fix it :D thanks for the eg and your awesome work on this package

You can close this now
