### ISSUE TITLE
Is it possible to add a column at an arbitrary position?

### ISSUE THREAD

**Issue by Petah** [yajra/laravel-datatables#336]
Is it possible to add a column at an arbitrary position? Like for example the first column, or somewhere in the middle?

**Comment by yajra** [comment]
Yes, just set the 3rd parameter of add column method to some index like:
```
->addColumn('col', 'content', 1)
```

Or a much better approach is to just add the column then define the arrangements of display of columns via `columns` property of dataTables.

**Comment by Petah** [comment]
Thanks, this works great, although I didn't see it in the docs so it might be worth mentioning (unless I suck at searching).

Good job BTW.
