### ISSUE TITLE
is there a way to lazyload the data in eloquent?

### ISSUE THREAD

**Issue by prolonginc** [yajra/laravel-datatables#338]
Hello, i am dealing witha  pretty large database 1.0 Million + records. 
i was wondering if there is a way to limit the query not to load everything from the controller i am aware of the ajax piping however that limits the view part not the server side. 

please let me know.

btw thank you for an amazing package I sure do appreciate your time, and effort.

**Comment by yajra** [comment]
By using, query builder or eloquent engine, all records will automatically be paginated and will not be loaded at once. Maybe you are using `->get()` method on your queries which in turns uses collection engine that causes all record to loaded at once?

**Comment by prolonginc** [comment]
Thanks for the reply however if i do a select statement it will return all unless i do something 
User::paginate(200); 

what i do have now is the same as your example. and i am getting an out of memory since its a pretty big table.

     $users = Parts::select(*);

        return Datatables::of($users)->make();

**Comment by yajra** [comment]
I suggest you specifically select only the columns that are needed by dataTable to optimize the query. Most of the time, php hangs out when loading some `text` or `binary` data from SQL with large volumes. And the snippet below should not return all the records but will return only number of rows set on your display length.

```php
$users = User::select(['id', 'name', 'etc...']);

return Datatables::of($users)->make();
```

**Comment by prolonginc** [comment]
I will give it a try, and let you know thank you.

**Comment by prolonginc** [comment]
it seems to be working with selecting a couple of fields, when it was failing i thought of viewing the actual route in the browsers and that loads everything. after reading the http request i saw that it passed it a few params. thank you very much for your help enjoy the beer :D

**Comment by yajra** [comment]
Glad it worked for you and thanks for beer! ^_^
