### ISSUE TITLE
Use unedited data in export (csv, excel, etc)

### ISSUE THREAD

**Issue by rogierborst** [yajra/laravel-datatables#341]
I'm using the DataTables as a Service functionality.
In my DataTable class I use the `ajax()` method to 'decorate' the data as follows:
```php
return $this->datatables->of($this->query())
    ->editColumn('provider', '<a href="{{route(\'providers.show\', $providerId)}}">{{$providerName}}</a>')
    ->editColumn( // etc
    ->make(true);
```

When I export the resulting table as csv or excel using the buttons, I don't want to include the anchor tags, just the raw data.
Is there any way to bypass all editColumn declarations when exporting?

**Comment by yajra** [comment]
@rogierborst, I just released earlier v6.2.x and it will automatically strip tags on decorated data when doing export. Have you checked out the latest version?

**Comment by yajra** [comment]
And note, please use `eloquent()`, `collection()`, or `queryBuilder()` instead of `of()` method. Of is buggy when using service approach.

**Comment by rogierborst** [comment]
Aah, I see. Yes, it works like a charm and I see you've made some more changes to the behavior.
Couple of things:
- In one of my `editColumn` calls, I returned `'&infin;'` to show the infinity symbol. Somehow the semicolon broke the exports, putting many columns into one field. 
- In the `html()` method of my DataTable class I do:
```php
return $this->builder()
    ->columns([ /* my column definitions */])
    ->ajax(['type' => 'POST']) // <----
```
But I see that the export functionality still uses the `GET` method. How can I change that?

**Comment by yajra** [comment]
> In one of my editColumn calls, I returned '&infin;' to show the infinity symbol. Somehow the semicolon broke the exports, putting many columns into one field.

- I think we need to add htmlentities when exporting along with strip tags? Will check this when I had the chance.

>In the html() method of my DataTable class I do:

- I think I have not considered using `POST` when developing this feature. Not yet sure how to do it via post method. Any suggestions?

**Comment by yajra** [comment]
I just added `html_entity_decode` when exporting to excel file. However, `&infin;` doesn't seem to be parsed properly. Can't find a solution for it yet. If you have some solutions in mind, please do not hesitate to submit a PR. Thanks!

**Comment by rogierborst** [comment]
How do you check the output? In any blade template I can do
```php
{{html_entity_decode('&infin;')}}
```
and get the proper result.
Might be because I have `<meta charset="UTF-8">` in the head of my html.

I have solved this issue for my personal project by just not html encoding in the first place. Just pasting in the infinity symbol in my html gave me no problems. (using latest browsers and setting `<meta charset="UTF-8">`)

**Comment by yajra** [comment]
This is just the basic decoder I write when exporting a file. Please see https://github.com/yajra/laravel-datatables/blob/6.0/src/Transformers/DataTransformer.php#L66.

**Comment by yajra** [comment]
BTW, I checked the results directly on the output/exported file. I think displaying of HTML is a bit different when writing the data to an actual excel file.

**Comment by rogierborst** [comment]
The latest update works like a charm for me. Both csv and excel exports show the &infin; symbol even though I encoded them as `&infin;`. Have you tried opening a csv export in a text-editor like SublimeText for example?

A more pressing matter for me is the `POST` method. I haven't checked your code yet, so I'm not sure how the buttons are generated. Will have a look at it now.

**Comment by yajra** [comment]
I was able to test using `POST` method and exporting function does not work properly due to how the URL was build. Opened a new ticket for enhancement.

**Comment by mansouralex** [comment]
it doesn't seem to work for me: 

return $this->datatables
            ->eloquent($this->query())
            ->editColumn('post', function ($post) {

                if($post->lat)
                {
                    return '<a target="_blank" href="'.$post->post_link.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-link"></i>View</a>
                     <a target="_blank" href="http://maps.google.com/maps?z=15&t=m&q=loc:'.$post->lat.'+'.$post->long.'"" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-link"></i>Map</a>';
                }else{
                    return '<a target="_blank" href="'.$post->post_link.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-link"></i>View</a>';
                }
            })->editColumn('photo', function ($post) {
                return '<img src="'.$post->media_url.'" class="img-responsive center-block" style="height: 82px; width: 82px;">';
            })
            ->make(true);

Please notice the column photo, when exporting to excel or csv instead of this column value I'm getting empty.

Any suggestions?

Thanks.

**Comment by jorgecolonconsulting** [comment]
> I'm using the DataTables as a Service functionality. In my DataTable class I use the `ajax()` method to 'decorate' the data as follows:
> 
> ```
> return $this->datatables->of($this->query())
>     ->editColumn('provider', '<a href="{{route(\'providers.show\', $providerId)}}">{{$providerName}}</a>')
>     ->editColumn( // etc
>     ->make(true);
> ```
> 
> When I export the resulting table as csv or excel using the buttons, I don't want to include the anchor tags, just the raw data. Is there any way to bypass all editColumn declarations when exporting?

The way we solved it was using `request()` and seeing if the action wasn't `'excel'` and only apply the partials if it _wasn't_ as export. If you don't apply any form of transformations with the blade partials, the data will remain unedited.

**Comment by yajra** [comment]
Another way I often use is to addColumn instead of editing the original field:

```php
->addColumn('provider_html', '<a href="{{route(\'providers.show\', $providerId)}}">{{$providerName}}</a>')

// columns
{data: 'provider_html', name: 'provider'}
```

Or you can also use the [render](https://datatables.net/reference/option/columns.render) column option.

**Comment by jorgecolonconsulting** [comment]
@yajra oh wow, that's another great workaround. I didn't think about that.
