### ISSUE TITLE
Eloquent model - all rows return same string

### ISSUE THREAD

**Issue by MegaCookie** [yajra/laravel-datatables#342]
I'm currently using this nice package, however I have an issue with a 'function return' by adding an extra column. If the first row returns one string, ALL rows return the same string. 

```php
$orders = Order::select(['id', 'created_at', 'company_name']);

return Datatables::of($orders)
	->addColumn('status', function ($order) {
		if( $order->paid == 1 ){
			return 'paid';
		} else {
			return 'not paid';
		}
	})
	->addColumn('this_works', function ($order){
		return $order->paid;
	})
	->make(true);
```

For example if the output of the 'status' column in the first row is paid then ALL rows return 'paid'. 
  
  Maybe this is by design and isn't really a bug, but a simple return without conditions seem to be working fine as for example in the 'this_works' column.

**Comment by yajra** [comment]
That's odd. The if condition should work. Maybe try removing `== 1`?

```php
->addColumn('status', function ($order) {
        if( $order->paid ){
            return 'paid';
        } else {
            return 'not paid';
        }
    })
```

**Comment by Orayi** [comment]
You need to add paid to your select.

```php
$orders = Order::select(['id', 'created_at', 'company_name', 'paid']);
```

**Comment by yajra** [comment]
@Orayi nice catch. He is correct! the `paid` field should be added on select statement. Thanks!
