### ISSUE TITLE
DataTables warning on documentation page at, datatables.yajrabox.com/fluent/joins

### ISSUE THREAD

**Issue by WesThorburn** [yajra/laravel-datatables#343]
I was browsing through the documentation and I came across a tn/7 error on the fluent/joins page. URL: http://datatables.yajrabox.com/fluent/joins

"DataTables warning: table id=posts-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7."

It's not really a serious issue, I just thought I should let you know.

**Comment by yajra** [comment]
Thanks for reporting! Will check it as soon as I can.

**Comment by yajra** [comment]
Found the issue and it was due to `HTML` facade registration. Fixed and upgraded the demo to Laravel 5.1. Thanks again!
