### ISSUE TITLE
Multi column search

### ISSUE THREAD

**Issue by brunjick** [yajra/laravel-datatables#345]
When I search with datatables' builtin search box, it doesn't search for all columns. Let's say, I have two columns: **_name, surname_**, and one row: **_[John, Doe]_**, when I search for **_john doe_** it doesn't give result. This works by default with non server side processing. On server side I'm just using `Datatables::of(SomeModel::all())->make()`. Is there any method to achieve what I want? If not, I will try to fix this and make pull request.

**Comment by yajra** [comment]
This is the expected behavior when searching on server-side. ATM, we build are global search by default using wildcard string. Your search will look something like this on the query.

```php
->orWhere('name', 'like', '%John%Doe%')
->orWhere('surname', 'like', '%John%Doe%')
```

If you want to search on the full name, you may need to use concatenation on your query.

**Comment by yajra** [comment]
Please see this [demo](http://datatables.yajrabox.com/eloquent/post-column-search) for some ref on using concat to search on multiple columns. Thanks
