### ISSUE TITLE
install fail on 5.1

### ISSUE THREAD

**Issue by hardikdangar** [yajra/laravel-datatables#347]
installing on Laravel 5.1 via command,
composer require yajra/laravel-datatables-oracle:~6.0

fails with,

>php artisan optimize
PHP Fatal error:  Class 'yajra\Datatables\DatatablesServiceProvider' not found in /home/sphere76/sphere76/code/l5/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

To fix the issue,

config/app.php

yajra\Datatables\DatatablesServiceProvider::class, replacing with,
Yajra\Datatables\DatatablesServiceProvider::class,

works.

Should i send a pull request for this? is this intentional ?

**Comment by yajra** [comment]
Are you upgrading from v5.x to v6.x? 

v6.x now uses `Yajra` instead of `yajra` namespace so `Yajra\Datatables\DatatablesServiceProvider::class` is correct class to use. See this [doc](https://github.com/yajra/laravel-datatables#upgrading-from-v5x-to-v6x) for some basic upgrade notes.

**Comment by hardikdangar** [comment]
No i didn't upgraded i just used composer require yajra/laravel-datatables-oracle:~6.0 on fresh laravel 5.1 setup.

**Comment by yajra** [comment]
I see. Then you need to use `Yajra\Datatables\DatatablesServiceProvider::class` and it is intended. Thanks!

**Comment by shafrazlk** [comment]
Hi Yajra,

I tried to upgrade the version to 6.0, but am getting following error
```
PHP Fatal error: Class 'yajra\Datatables\DatatablesServiceProvider' not found in E:/PHP_PROJECTS/laravel-sn/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
```
i followed the docs to upgrade but still the same. Now i can't revert it to earlier version to work with. Unfortunately composer updated doesn't allow me to do that either. Same error!

**Comment by yajra** [comment]
@shafrazlk, were you able to follow this upgrade guide? https://github.com/yajra/laravel-datatables#upgrading-from-v5x-to-v6x

**Comment by shafrazlk** [comment]
Yes, I followed each step one by one. Out of the blue all crashed. Can't get the app running back.

**Comment by yajra** [comment]
Might be related to this issue https://github.com/yajra/laravel-datatables/issues/405. 

Can you please try

> From SO. http://stackoverflow.com/questions/33122553/class-datatables-does-not-exist-error-when-using-yajra-laravel-datatables

1.first rename your project to a new name.
2.use composer update
3.run php artisan config:cache
4.and run php artisan cache:clear

**Comment by hardikdangar** [comment]
if your folder is git repository then stash your changes. that way your application will start working again.

and then try the above changes in separate folder as mentioned by yajra

**Comment by shafrazlk** [comment]
@yajra: first of all it doesn't allow me to rename the project, command **php artisan app:name SN** throws same error. I tried to rename the project folder that doesn't work either.

@hardikdangar Unfortunately folder is not a git repository. :(

**Comment by yajra** [comment]
Can you try removing the vendor folder and composer.lock file then reinstall all the packages? Backup your app first before doing it to be sure since your not on git.

**Comment by shafrazlk** [comment]
Managed to get it work by reversing the steps [here](https://github.com/yajra/laravel-datatables#upgrading-from-v5x-to-v6x) and with the command ***composer update --no-scripts***

Thanks for the replies guys, will try to upgrade it at a later time.

@yajra All begun with Datatable column sorting not working with v5.0.
