### ISSUE TITLE
Dynamically add row to datatable 

### ISSUE THREAD

**Issue by stumped101** [yajra/laravel-datatables#350]
Hi,

Can you tell me how to dynamically add a row to a datatable populated from server side with this plugin. I have tried rows.add & row .add followed by draw() which has not worked. What partially worked was table.rows.add(data).destroy().draw() - but this showed "cannot get property nTr of undefined or null" error. I am using datatables 1.10.8, yarja for Laravel4.2.

Many Thanks in advance for your help.

**Comment by yajra** [comment]
@stumped101, I haven't tried using to add row dynamically on dataTables so I am not really sure about this. But I think that plugin is only applicable on the client-side. Server-side approach will always redraw the content and thus will remove any custom row you have added.

**Comment by andreiculda** [comment]
I think the row must be added only to the database (with ajax or something). Upon draw it should come as any other row. So don't add it to the client table at all.

**Comment by stumped101** [comment]
Thanks for the feedback and advice. I'll try that.

Much appreciated - thanks again

**Comment by Nasirkhan-259** [comment]
How can we achieve this to add a dynamic row to the data table from ajax call in laravel .
I have multiple columns like atm, cash and I want at the end of the table there should be a row of the total to show the total of each column
