### ISSUE TITLE
Return columns

### ISSUE THREAD

**Issue by hugofabricio** [yajra/laravel-datatables#353]
How to return only the columns in the script?

    "columns": [
        {
            "name": "id",
            "data": "id",
            "title": "Id",
            "orderable": true,
            "searchable": true
        },
        {
            "name": "first_name",
            "data": "first_name",
            "title": "First Name",
            "orderable": true,
            "searchable": true
        },
        {
            "name": "email",
            "data": "email",
            "title": "Email",
            "orderable": true,
            "searchable": true
        },
        {
            "name": "created_at",
            "data": "created_at",
            "title": "Created At",
            "orderable": true,
            "searchable": true
        }
    ]

**Comment by yajra** [comment]
Not sure but you may find the answer by browsing the JS api docs at http://datatables.net/reference/index.

**Comment by hugofabricio** [comment]
Yajra thanks,

My question is:
In script.blade.php  %1$s returns id and %2$s returns 

{"serverSide":true,"processing":true,"ajax":"","columns":[{"name":"id","data":"id","title":"Id","orderable":true,"searchable":true},{"name":"first_name","data":"first_name","title":"First Name","orderable":true,"searchable":true},{"name":"email","data":"email","title":"Email","orderable":true,"searchable":true},{"name":"created_at","data":"created_at","title":"Created At","orderable":true,"searchable":true}],"dom":"Bfrtip","buttons":["csv","excel","pdf","print","reset","reload"]}

How to returns only data columns?

,"columns":[{"name":"id","data":"id","title":"Id","orderable":true,"searchable":true},{"name":"first_name","data":"first_name","title":"First Name","orderable":true,"searchable":true},{"name":"email","data":"email","title":"Email","orderable":true,"searchable":true},{"name":"created_at","data":"created_at","title":"Created At","orderable":true,"searchable":true}]

**Comment by hugofabricio** [comment]
Solved, thanks :)

**Comment by hugofabricio** [comment]
getColumns() dont work in script.blade.php =/
