### ISSUE TITLE
Regexp issue

### ISSUE THREAD

**Issue by ansient** [yajra/laravel-datatables#354]
Hi,
I'm working on a Oracle DB (11g) using Laravel 5, Laravel-OCI8, and this package for DataTables( jquery).
Whenever I search records in the table using the regexp flag, i always get  "ORA-00920: invalid relational operator", related to the "REGEXP" command.
After a short read of the Oracle docs (<a href="https://docs.oracle.com/cd/B28359_01/appdev.111/b28424/adfns_regexp.htm">external link</a>), I've replaced two lines of code in QueryBuilderEngine.php (line 219 and 226), fixing the thing up.

<code>
line 219: $this->query->whereRaw(' REGEXP_LIKE( '.$column.' , ?, \'i\' )', [Str::lower($keyword)]);
line 226: $this->query->whereRaw(' REGEXP_LIKE('.$col.' , ? , \'i\' )', [$keyword] );
</code>

I hope this could be of help.

**Comment by yajra** [comment]
Hi,

So we just need to remove the `Str::lower()` method to make the REGEX work? And it does seem not needed since `i` flag means case insensitive searching. Thanks for the info.

If you can submit a PR, please do so.

Regards!

**Comment by yajra** [comment]
Your PR was merged and released on v6.4.2. Thanks!
