### ISSUE TITLE
Enable lengthChange option?

### ISSUE THREAD

**Issue by mansouralex** [yajra/laravel-datatables#356]
I have added the lengthChange to the script but still not showing up, following is my script:

(function(window,$){window.LaravelDataTables=window.LaravelDataTables||{};
			window.LaravelDataTables["dataTableBuilder"]=$("#dataTableBuilder").DataTable({"serverSide":true,"processing":true,"ajax":"","lengthChange": true,"columns":[{"name":"id","data":"id","title":"Id","orderable":true,"searchable":true},
				{"name":"media_text","data":"media_text","title":"Media Text","orderable":true,"searchable":true},
				{"name":"photo","data":"photo","title":"Photo","orderable":false,"searchable":false},
				{"name":"flag","data":"flag","title":"Flag","orderable":true,"searchable":true},
				{"name":"source","data":"source","title":"Source","orderable":true,"searchable":true},
				{"name":"posted_time","data":"posted_time","title":"Posted Time","orderable":true,"searchable":true},
				{"name":"lat","data":"lat","title":"Lat","orderable":true,"searchable":true},
				{"name":"long","data":"long","title":"Long","orderable":true,"searchable":true},
				{"name":"post","data":"post","title":"Post","orderable":false,"searchable":false}],
				"dom":"Bfrtip","buttons":["csv","excel","reset","reload"]});})(window,jQuery);
	
Any Idea? thanks.

**Comment by yajra** [comment]
Make sure you added `l` on your dom settings like:
```js
$(..).DataTable({
  'dom': 'bfrtlip',
  'buttons': [...]
});
```

**Comment by mansouralex** [comment]
Thanks for your quick response. 

it's there now (at the bottom of the table). But this is removes the buttons.

**Comment by mansouralex** [comment]
Ok got it. I just make it starts with capital as 

$(..).DataTable({
  'dom': 'Bfrtlip',
  'buttons': [...]
});

Anyway to get it beside the buttons ?

**Comment by yajra** [comment]
Just arrange the dom accordingly. See this api doc for ref on [dom values](https://datatables.net/reference/option/dom).
```php
l - length changing input control
f - filtering input
t - The table!
i - Table information summary
p - pagination control
r - processing display element
B - buttons
```

**Comment by mansouralex** [comment]
Thanks.
