### ISSUE TITLE
enable/disable column order-able or searchable?

### ISSUE THREAD

**Issue by mansouralex** [yajra/laravel-datatables#357]
How to enable/disable column order-able or searchable features in Service Implementation?

Thanks.

**Comment by yajra** [comment]
Just set searchable and/or orderable to false like:

```php
->columns([
  'id',
  'action' => ['orderable' => false, 'searchable' => false]
])
```

**Comment by mansouralex** [comment]
great, working as expected. Thanks.

Could you have a look on my comment #341 Thanks.

**Comment by nostrebla** [comment]
no found call to a member function getquery() on null

**Comment by PrafullaKumarSahu** [comment]
@yajra and @mansouralex Could you please let me know, if this in the documentation, my need is simillar

lets say if my code is 

```
 ->editColumn('created_at', function(Video $video){
            return $video->createdAt();
        })
```


or in js it is

` { data: 'created_at', name: 'created_at' },`
 and I want it to disable sorting on it, how I can do it?

**Comment by PrafullaKumarSahu** [comment]
` { data: 'created_at', name: 'created_at', orderable: false },`

is the solution.
