### ISSUE TITLE
[v5.0] Add support for Collection as data source

### ISSUE THREAD

**Issue by yajra** [yajra/laravel-datatables#36]
WIP: Add support for Laravel's Collection object as data source for Datatables. 

Inviting beta testers and contributors to join the fun. ^_^. Please checkout [develop branch](https://github.com/yajra/laravel-datatables-oracle/tree/develop).

Note: 
v5.0 Initial plan:
- ~~Drop support for Laravel 4 [will depend on demand].~~ 
- Support for Laravel 4 will continue on v3.x branch but Collection and new features will not be added.
- Drop support for Datatables v1.9 and below.

**Comment by illuminate3** [comment]
I'll try to get to this.

# thoughts
Support for L4 should be paired with DT 1.9
Support for L5 should be paired with DT 1.10 and newer

DataTables has really started to progress with 1.10.x so I expect that it'll even get better with future versions.

Maybe you should consider renaming this package with the L5 version. Leave the old name for L4.

**Comment by javenosa** [comment]
Sorry for my ignorance.

With this functionality we can return a mixed (union for example) query to datatables, right??

**Comment by yajra** [comment]
Thanks @illuminate3!
**Support for L4 should be paired with DT 1.9**
- For L4 we would stick with version 3.x and it supports both DT1.9 and 1.10. However, it will not have a Collection feature

**Support for L5 should be paired with DT 1.10 and newer**
- Will consider renaming the package and will definitely drop support for DT1.9

**Comment by yajra** [comment]
@javenosa Yes, you are correct. By having a Collection feature, you can return a mixed query to datatables. Other possible sources that I can think of are as follows:

1. Data from an API
2. Plain array
3. Data from a file (CSV, Excel, etc.)
4. Union of 2 or more different queries.

**Comment by yajra** [comment]
@illuminate3 I have renamed the package on Github to `laravel-datatables` to lessen the confusions. However, the installation would be the same as packagist does not allow renaming of packages as it is a bad practice.

**Comment by yajra** [comment]
I just released v5.0.0 and test for collection are supported by [demo app](https://github.com/yajra/laravel-datatables-demo). Thanks for everyone!

**Comment by illuminate3** [comment]
What kind of performance changes have you seen?

**Comment by yajra** [comment]
Not really sure how measure the performance but one thing is I am sure of. Dropping support for DT1.9 increases the processing speed because a lot of loops and conditions were removed in favor of it.
