### ISSUE TITLE
Can't change language with htmlbuilder

### ISSUE THREAD

**Issue by EricKwan2014** [yajra/laravel-datatables#361]
Hi,

I have trouble with language translate with datatable htmlbuilder.

```js
<script>
$(document).ready(function() {
    $.extend(true, $.fn.dataTable.defaults, {
        "stateSave": true,
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Chinese-traditional.json"
        }
    });
});
{{ $dataTable->scripts() }}
</script>
```

I am using this code in my blade file and the table still representing in English.

Did anyone have any idea.

Also, is there possible to add custom script in htmlbuilder?

**Comment by Jastkast** [comment]
Try this
`<script type="text/javascript">
    $.extend(true, $.fn.dataTable.defaults, {
        language: {
            url : '//cdn.datatables.net/plug-ins/1.10.10/i18n/Polish.json'
        }
    });
</script>
{!! $dataTable->scripts() !!}`

**Comment by yajra** [comment]
@EricKwan2014, there is an issue on arrangements of how you call the scripts. Using @Jastkast suggestion should fix your issue. `{!! $dataTable->scripts() !!}` should not be inside the `<script>` tag.
