### ISSUE TITLE
Link to Route

### ISSUE THREAD

**Issue by Bottelet** [yajra/laravel-datatables#364]
Is it possible to link directly to a route, for example...
`->addColumn('namelink', function ($users) {
                return '<a href="redirect()->route('users.show').$users->id.'" ">'.$users->name.'</a>';
            })`

Just an example or something like that. Also what is the easiest way to link in the table so all the name result link to the show page as example.

**Comment by Bottelet** [comment]
And also only show actions buttons, if a user has a specfic role?

**Comment by yajra** [comment]
I think the problem here is you use `redirect()` and your route is not properly called. Just remove it and link should work fine.
```php
->addColumn('namelink', function ($users) {
  return '<a href="' . route('users.show', $users->id) .'">'.$users->name.'</a>'; 
})
```

**Comment by jpuck** [comment]
Thanks for this snippet! Also, don't forget to call `rawColumns` for unescaped HTML

```php
return Datatables::of(User::query())
    ->addColumn('namelink', function ($user) {
        return '<a href="' . route('users.show', $user->id) .'">'.$user->name.'</a>'; 
    })
    ->rawColumns(['namelink'])
    ->make(true);
```

**Comment by parthkharecha** [comment]
```
->editColumn('user_id, function ($data) {
      return '<a href="/uesr/'.$data->user_id.'">'.$data->user_id.'</a>';
    })
->rawColumns(['user_id'])
```

**Comment by parthkharecha** [comment]
```
->editColumn('user_id', function ($data)  {
      return '<a href="/user/'.$data->user_id.'">'.$data->user_id.'</a>';
    })
    ->rawColumns(['action','user_id'])
```
working fine thank @jpuck  and @yajra

**Comment by ErwinIbrani** [comment]
Thanks Brothers for this love
