### ISSUE TITLE
Unused Dependency: dompdf?

### ISSUE THREAD

**Issue by gpmcadam** [yajra/laravel-datatables#365]
There's a requirement for the `dompdf/dompdf` package defined in **composer.json** but I can't see it being used anywhere else in the code.

This is causing a dependency collision issue in a project I'm working on, and I'm wondering if that dependency is not longer being used you could remove it from your **composer.json**?

**Comment by yajra** [comment]
@gpmcadam, `dompdf` is used for generating PDF file when exporting the table using Laravel Excel package. Removing it may caused some breaking change on some users?

**Comment by yajra** [comment]
`dompdf` is being used on service approach. Please send a PR if possible to fix your issue? Thanks!
