### ISSUE TITLE
Searching/sorting on eager loaded models

### ISSUE THREAD

**Issue by ikerasLT** [yajra/laravel-datatables#366]
Is this going to be supported in near future?

**Comment by yajra** [comment]
YES, but the problem is I don't have any idea yet how to implement it. ^_^

If you some solutions in mind, please do not hesitate to submit a PR. Thanks!

**Comment by ikerasLT** [comment]
Ok, found the solution for global search. No ordering though

**Comment by yajra** [comment]
Your PR #381 merged and [demo](http://datatables.yajrabox.com/eloquent/relationships) were updated to reflect the changes. Thanks!

**Comment by ikerasLT** [comment]
No problem, will try to implement sorting when I have time
