### ISSUE TITLE
Sortable table

### ISSUE THREAD

**Issue by butoibogdan** [yajra/laravel-datatables#367]
Hello,
Please can you help with an information :)
How can i make something like this
http://www.mccran.co.uk/index.cfm/2011/5/15/Combining-JQuery-Datatable-with-drag-and-drop-functions
It about jquery sortable with drag and drop.
Thank's a lot

**Comment by butoibogdan** [comment]
I resolve this isue with sortable by jquery ui.
Thank a lot

**Comment by yajra** [comment]
@butoibogdan, glad you sorted this out. Don't have time yet to test this so I can't give much help. :beers:
