### ISSUE TITLE
customize iTotalRecords and iTotalDisplayRecords

### ISSUE THREAD

**Issue by yizhihou2** [yajra/laravel-datatables#368]
Hi,

Is it possible to customize the iTotalRecords and iTotalDisplayRecords in the server's response, so that  a information string like 

> Showing 1-10 of 1,000 out of 5,000 total

 can be shown on the webpage?

Thanks

**Comment by yajra** [comment]
I think you can by hijacking the json response.  See the [workaround here](https://github.com/yajra/laravel-datatables/issues/277) for an idea how to change the json response.
