### ISSUE TITLE
how set default order 

### ISSUE THREAD

**Issue by it9xpro** [yajra/laravel-datatables#371]
how set default order ?
ex default order data column id

**Comment by yajra** [comment]
Follow this https://datatables.net/reference/option/order and just use the proper column index.

**Comment by it9xpro** [comment]
thanks

**Comment by rafaelqm** [comment]
If you are using as a service, in the method html(), on parameters array use

```
/**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->parameters([
                'order' => [
                    0, // here is the column number
                    'desc'
                ]
           ]);
```

**Comment by groovenectar** [comment]
> Follow this https://datatables.net/reference/option/order and just use the proper column index.

This doesn't really solve a default order for the query though, for example the default sort that comes from an Eloquent model... if it is necessary to loop the first page to prevent a page jump, then the order will rearrange after the first AJAX call to sort

**Comment by groovenectar** [comment]
> > Follow this https://datatables.net/reference/option/order and just use the proper column index.
> 
> This doesn't really solve a default order for the query though, for example the default sort that comes from an Eloquent model... if it is necessary to loop the first page to prevent a page jump, then the order will rearrange after the first AJAX call to sort

Does this make sense? Is there a workaround or standard method? I'm still having a hard time finding this info

**Comment by groovenectar** [comment]
This idea is to have the `$query` end up with the same defaults as the AJAX, for example to render the first page.

Here is a way to sort of hack in the functionality, but it does not seem ideal at all:

```php
if (!request()->ajax() && !request()->get('order')) {
    $query = $query->orderByRaw('column_name desc');
}

$dataTable = DataTables::eloquent($query);

if (request()->ajax() && !request()->get('order')) {
    $dataTable = $dataTable->order(function($query) {
        $query->orderBy('column_name', 'desc');
    });
}
```

There must be a more official way to do this?

**Comment by gabrieljenik** [comment]
Have you checked this?
