### ISSUE TITLE
How to Handle Custom Pagination, with Aggregate count function

### ISSUE THREAD

**Issue by maheshtc** [yajra/laravel-datatables#378]
I am facing issue with the large number of data for loading in datatable. I have table having records with 30000 records. It breaks datatable listing. 

So Is It possible to pass count result(using aggregate count function) for pagination and for listing we will pass query with offset and limit?
If It is already implemented  then, Please guide me to use that. 
It not then how can change it to achieve that.

Thank you

**Comment by yajra** [comment]
Sorry, but it's not possible to pass the count for pagination.

On the other hand, what engine are you using? Can you please paste some snippets on how you declare your dataTable?

**Comment by maheshtc** [comment]
Thank you for your response. Please check below code that I am using.  It is working on my local server. But When I am trying it same on server. It breaks lisiting.
//$zipcode = Zipcode::select(['id','zip_code','zip_city','zip_state', 'zip_latitude', 'zip_longitude', 'zip_areacode'])->offset($request->get('start'))->limit($request->get('length'));
        $zipcode = Zipcode::select(DB::raw('count(1) as totolRecords'))->first();
        
        return Datatables::of($zipcode)
            ->add_column('actions', '<a href="{{{ URL::to(\'admin/zipcode/\' . $id . \'/edit\' ) }}}" class="btn btn-success btn-sm" ><span class="glyphicon glyphicon-pencil"></span>  {{ trans("admin/modal.edit") }}</a>
                    <a href="{{{ URL::to(\'admin/zipcode/\' . $id . \'/delete\' ) }}}" class="btn btn-sm btn-danger iframe"><span class="glyphicon glyphicon-trash"></span> {{ trans("admin/modal.delete") }}</a>
                    <input type="hidden" name="row" value="{{$id}}" id="row">')
            ->remove_column('id')
            ->make();
So I want to change code such that I can get fast response

**Comment by yajra** [comment]
What is your builder script for `$zipcode`? It should be something like:

```php
$zipcode = Zipcode::select(['id','zip_code','zip_city','zip_state', 'zip_latitude', 'zip_longitude', 'zip_areacode']);
```

No need to set the offset and limit.

**Comment by maheshtc** [comment]
Yes You are right. But It breaks listing on server. So I tried to pass offset and limit. 
Is it possible to remove normal pagination and add ajax pagination. so that I can set query with limit.

**Comment by yajra** [comment]
I have a table with 100k records and its not breaking my app. Can you please dump the server error response?

**Comment by maheshtc** [comment]
I have been trying to regenerate same error. But It is not showing  any error just showing blank result in browser console. It is just showing alert message for datatable 
![screenshot from 2016-02-06 16 38 20](https://cloud.githubusercontent.com/assets/9860829/12866332/7e0cc18c-ccf0-11e5-9ded-f1e6b84e3980.png)

**Comment by yajra** [comment]
You should open firebug/dev tools before loading the page and then look on the network logs. You should be able to get a hint on on how to fix the issue.

**Comment by kennyfans** [comment]
> $zipcode = Zipcode::select(['id','zip_code','zip_city','zip_state', 'zip_latitude', 'zip_longitude', 'zip_areacode']);

if we have 1.000.000 or 10.000.000 or more it will get all ?

**Comment by yajra** [comment]
Using browser developer tools should help you fix this issue. Thanks!
