### ISSUE TITLE
Eloquent relationship not working in search

### ISSUE THREAD

**Issue by mprandot** [yajra/laravel-datatables#379]
Hello! (again :smile: )

The filters not work whe data are from eloquent relationships, see:

```
public function datatableRecebimentoPagamento() {
        $registros = $this->repositoryRecebimentoPagamento->all();

        return Datatables::of($registros)
            ->addColumn('action', function ($registro) {
                $estornar = botaoEstornar($registro, 'estornos.executa');
                return $estornar;
            })->editColumn('valor', function ($registro) {
                return $registro->present()->valueForUser($registro->valor, true);
            })->editColumn('tipo_operacao', function ($registro) {
                return $registro->parcela->conta->present()->tipoOperacaoAtt;
            })->editColumn('pessoa_nome', function ($registro) {
                return $registro->parcela->conta->pessoa->present()->nomeAtt;
            })->editColumn('titulo', function ($registro) {
                return $registro->parcela->conta->titulo;
            })->make(true);
    }
```

and my view:

```
<script>
        $(function () {
            var pathname = window.location.pathname;

            $('#table-historico').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{route('estornos.datatable')}}',
                    data: {url: pathname}
                },
                columns: [
                    {data: 'titulo', name: 'titulo', searchable: true},
                    {data: 'valor', name: 'valor', searchable: true},
                    {data: 'tipo_operacao', name: 'tipo_operacao', searchable: true},
                    {data: 'pessoa_nome', name: 'pessoa_nome', searchable: true},
                    {data: 'data', name: 'data', searchable: true},
                    {data: 'action', name: 'Ação', orderable: false, searchable: false}
                ], "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.9/i18n/Portuguese-Brasil.json"
                }
            });
        });
    </script>
```

If the field not come from eloquent the search work, else, not.

**Comment by mprandot** [comment]
The `searchable: true},` is default, i know, but i tested with.

**Comment by yajra** [comment]
@mprandot, search on related/eager loaded models is not yet supported. But I think we will soon have this feature. Thanks to #381 for the initiative.

**Comment by yajra** [comment]
@mprandot, searching on eager loaded models implemented but no sorting yet. See the [demo](http://datatables.yajrabox.com/eloquent/relationships) for ref. :beers:

**Comment by mprandot** [comment]
@yajra, Thanks for you reply!

I looked in the demo, but i not use the relationship like in demo...

see:

```
$registros = $this->repositoryRecebimentoPagamento->all();

        return Datatables::of($registros)
            ->addColumn('action', function ($registro) {
                $estornar = botaoEstornar($registro, 'estornos.executa');
                return $estornar;
            })->editColumn('valor', function ($registro) {
                return $registro->present()->valueForUser($registro->valor, true);
            })->editColumn('tipo_operacao', function ($registro) {
                return $registro->parcela->conta->present()->tipoOperacaoAtt;
            })->editColumn('pessoa_nome', function ($registro) {
                return $registro->parcela->conta->pessoa->present()->nomeAtt;
            })->editColumn('titulo', function ($registro) {
                return $registro->parcela->conta->titulo;
            })->make(true);
    }
```
For each  $registro i get the relationship , and in some cases more than one relationship .
So , in my case ,  functionality is not working yet...

**Comment by ZAZmaster** [comment]
@yajra @mprandot need this feature too!

**Comment by AEK-BKF** [comment]
I need it too :+1:

**Comment by yajra** [comment]
Guys, are you using Eloquent or a Collection? On example code above, it seems like this issue uses a collection instead of Eloquent? `all()` by default returns a collection of Models, unless it's overridden on your repo?

```php
$registros = $this->repositoryRecebimentoPagamento->all();
```

**Comment by AEK-BKF** [comment]
No, I'm using Eloquent,
Here an example of my code :
`$users = User::All();`
      `return Datatables::of($users)            
            ->editColumn('position_id', function($user) {
                return $user->position->name;
              }) ->make(true);`

So I can't search on Position name.

**Comment by yajra** [comment]
@AEK-BKF, using `User::all()` will return a collection instead of eloquent builder. Try using `User::with('position');`  instead and follow the eager loading [demo](http://datatables.yajrabox.com/eloquent/relationships) for ref.

**Comment by ZAZmaster** [comment]
@yajra if i have User::with('roles') and want show all hasMany roles with ordering and filtering by roles?

**Comment by AEK-BKF** [comment]
I tried with an other code which is my real case :

`$installations =  Customer::find(Session::get('$customerID'))->installations->where('user_id', Auth::user()->id);`        
        `return Datatables::of($installations)      
            ->addColumn('action', function ($installation) {
                return View::make('install.actions')->withInstall($installation)->render();
            })
            ->editColumn('code', function ($installation) {
                return $installation->vehicle->code;
            })
            ->editColumn('registernumber', function ($installation) {
                return $installation->vehicle->registernumber;
            })
            ->editColumn('site_id', function ($installation) {
                return $installation->vehicle->site->name;
            })
            ->editColumn('tracer_id', function ($installation) {
                return Tracer::find($installation->tracer_id)->name;
            })            
            ->make(true);`

So I added " with('relation') " method but it doesn't work..
Please could you help me? thanks

**Comment by yajra** [comment]
@ZAZmaster, `User::with('roles')` will search on roles table depending on the field you specified using `whereHas` query.

@AEK-BKF, I think your query should be something like:
```php
 $installations =  Customer::find(Session::get('$customerID'))
    ->installations()
    ->with('vehicle')
    ->where('user_id', Auth::user()->id);`        
```

**Comment by mprandot** [comment]
@yajra yes, i override the method all(), i will test the others solutions and pass a feedback!

**Comment by AEK-BKF** [comment]
@yajra  Unfortunately it doesn't work :/ 
` Unknown column 'vehicle.code' in 'order clause' `

**Comment by erknafcn** [comment]
For global search I made everything similar to demo but when I search I got this error : http://datatables.net/tn/7, I use eloquent as shown `$websites = Website::with('officers');`, relationship between websites and officers is many-to-many. I want to get list of the related websites when I type name of the responsible officer and planning to show responsible officers of each website in a cell as dropdown list. Please help

**Comment by yajra** [comment]
Guys, are you still having this issue? I think this should be fixed on the PR above. Let me know if it works so we can close this. Thanks!

**Comment by mprandot** [comment]
@yajra In my case(using repository to get object and $obj->attribute in editColumn) still not working...
Have possibility to create some to work in my way?

**Comment by yajra** [comment]
@mprandot I think this issue should be fixed on the latest version. I think your problem above is different, please open a new one and provide the details if needed. Thanks!
