### ISSUE TITLE
How to create child row / Child detail

### ISSUE THREAD

**Issue by edlie** [yajra/laravel-datatables#38]
As the title said, how to create a row child for extra information like this example using this plugins :D
https://www.datatables.net/examples/api/row_details.html

Best regards

**Comment by yajra** [comment]
Hi, 

Just follow as what that link shows on javascript side and it should work as expected. The only difference on that example is that you will have to use the server side script of DT.

On the other hand, I think I will add this on the [Demo App](https://github.com/yajra/laravel-datatables-demo) that I've been working on lately. Will keep you posted here when the demo for **Row Details** is ready. Also check it out for you to see how use the package on certain scenarios.

Cheers!

**Comment by yajra** [comment]
Below is an example script you can use to implement this.

```js
var table = $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url("users-data") }}',
        columns: [
            {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": ''
            },
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'}
        ],
        order: [[1, 'asc']]
    });

    // Add event listener for opening and closing details
    $('#users-table tbody').on('click', 'td.details-control', function () {
        var tr = $(this).closest('tr');
        var row = table.row( tr );

        if ( row.child.isShown() ) {
            // This row is already open - close it
            row.child.hide();
            tr.removeClass('shown');
        }
        else {
            // Open this row
            row.child( format(row.data()) ).show();
            tr.addClass('shown');
        }
    });

    /* Formatting function for row details - modify as you need */
    function format ( d ) {
        // `d` is the original data object for the row
        return '<table class="table">'+
            '<tr>'+
                '<td>Full name:</td>'+
                '<td>'+d.name+'</td>'+
                '</tr>'+
            '<tr>'+
                '<td>Email:</td>'+
                '<td>'+d.email+'</td>'+
                '</tr>'+
            '<tr>'+
                '<td>Extra info:</td>'+
                '<td>And any further details here (images etc)...</td>'+
                '</tr>'+
            '</table>';
    }
```

On your controller
```php
public function getUsersData()
{
        $users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

        return Datatables::of($users)->make(true);
}
```

**Comment by yajra** [comment]
Done adding Row Details example on [Demo App](https://github.com/yajra/laravel-datatables-demo) just check it out to see how it works. Thanks!

**Comment by edlie** [comment]
Sorry When i Try to apply the Details I got this error: 
Uncaught TypeError: Cannot read property 'style' of undefined


Where's to add the data of the details row?
I add it like this

Main Table:
<pre><code>          <table id="do-list" class="table table-bordered table-striped table-hover dt-responsive display nowrap" cellspacing="0" >
                    <thead>
                    <tr>
                        <th></th>
                        <th>DO ID</th>
                        <th>Title</th>
                        <th>Date Time Issued</th>
                        <th>Delivery Type</th>
                        <th>Weight</th>
                        <th>Pickup Time Request</th>
                        <th>Delivery Time Request</th>
                        <th>Operator Pickup Time Request</th>
                        <th>Operator Delivery Time Request</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
</code></pre>
The Datatables Data: 
<pre>
{data: 'do_id', name: 'tb_do.do_id'},
                {data: 'title', name: 'tb_do.title'},
                {data: 'date_time_issued', name: 'tb_do.date_time_issued'},
                {data: 'delivery_type', name: 'tb_delivery_type.name'},
                {data: 'weight', name: 'tb_do.weight'},
                {data: 'pickup_time_request', name: 'tb_do.pickup_time_request'},
                {data: 'delivery_time_request', name: 'tb_do.delivery_time_request'},
                {data: 'operator_pickup_time_request', name: 'tb_do.operator_pickup_time_request'},
                {data: 'operator_delivery_time_request', name: 'tb_do.operator_delivery_time_request'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
                {data: 'pickup_address_name', name: 'pickup_address_name', orderable: false, searchable: false},
                {data: 'pickup_street', name: 'pickup_street', orderable: false, searchable: false},
                {data: 'pickup_area_name', name: 'pickup_area_name', orderable: false, searchable: false},
                {data: 'pickup_postcode', name: 'pickup_postcode', orderable: false, searchable: false},
                {data: 'pickup_country_name', name: 'pickup_country_name', orderable: false, searchable: false},
                {data: 'pickup_pic_name', name: 'pickup_pic_name', orderable: false, searchable: false},
                {data: 'pickup_pic_telephone', name: 'pickup_pic_telephone', orderable: false, searchable: false},
                {data: 'pickup_pic_mobile_phone', name: 'pickup_pic_mobile_phone', orderable: false, searchable: false},
                {data: 'delivery_address_name', name: 'delivery_address_name', orderable: false, searchable: false},
                {data: 'delivery_street', name: 'delivery_street', orderable: false, searchable: false},
                {data: 'delivery_area_name', name: 'delivery_area_name', orderable: false, searchable: false},
                {data: 'delivery_postcode', name: 'delivery_postcode', orderable: false, searchable: false},
                {data: 'delivery_country_name', name: 'delivery_country_name', orderable: false, searchable: false},
                {data: 'delivery_pic_name', name: 'delivery_pic_name', orderable: false, searchable: false},
                {data: 'delivery_pic_telephone', name: 'delivery_pic_telephone', orderable: false, searchable: false},
                {data: 'delivery_pic_mobile_phone', name: 'delivery_pic_mobile_phone', orderable: false, searchable: false}
</pre>
For the normal datatables i only use it after action, if i delete the data after the 'action' data it works but without detail
------
This is my handle bar script:

    <script id="details-template" type="text/x-handlebars-template">
        <table class="table">
            <tr>
                <td>Pickup Address:</td>
                <td>@{{pickup_address_name}}</td>
            </tr>
            <tr>
                <td>Pickup Street:</td>
                <td>@{{pickup_street}}</td>
            </tr>
            <tr>
                <td>Pickup Area:</td>
                <td>@{{pickup_area_name}}</td>
            </tr>
            <tr>
                <td>Pickup Postcode:</td>
                <td>@{{pickup_postcode}}</td>
            </tr>
            <tr>
                <td>Pickup Country:</td>
                <td>@{{pickup_country_name}}</td>
            </tr>
            <tr>
                <td>Pickup PIC:</td>
                <td>@{{pickup_pic_name}}</td>
            </tr>
            <tr>
                <td>Pickup PIC Telephone:</td>
                <td>@{{pickup_pic_telephone}}</td>
            </tr>
            <tr>
                <td>Pickup PIC Mobile Phone:</td>
                <td>@{{pickup_pic_mobile_phone}}</td>
            </tr>
            <tr>
                <td>Delivery Address:</td>
                <td>@{{delivery_address_name}}</td>
            </tr>
            <tr>
                <td>Delivery Street:</td>
                <td>@{{delivery_street}}</td>
            </tr>
            <tr>
                <td>Delivery Area:</td>
                <td>@{{delivery_area_name}}</td>
            </tr>
            <tr>
                <td>Delivery Postcode:</td>
                <td>@{{delivery_postcode}}</td>
            </tr>
            <tr>
                <td>Delivery Country:</td>
                <td>@{{delivery_country_name}}</td>
            </tr>
            <tr>
                <td>Delivery PIC:</td>
                <td>@{{delivery_pic_name}}</td>
            </tr>
            <tr>
                <td>Delivery PIC Telephone:</td>
                <td>@{{delivery_pic_telephone}}</td>
            </tr>
            <tr>
                <td>Delivery PIC Mobile Phone:</td>
                <td>@{{delivery_pic_mobile_phone}}</td>
            </tr>
        </table>

**Comment by yajra** [comment]
not sure on the js error but you should have something like this on your script. Using handle bar template and then pass the data `template(row.data())`.

```js
var template = Handlebars.compile($("#details-template").html());

// Add event listener for opening and closing details
    $('#users-table tbody').on('click', 'td.details-control', function () {
        var tr = $(this).closest('tr');
        var row = table.row( tr );

        if ( row.child.isShown() ) {
            // This row is already open - close it
            row.child.hide();
            tr.removeClass('shown');
        }
        else {
            // Open this row
            row.child( template(row.data()) ).show();
            tr.addClass('shown');
        }
    });
```

**Comment by edlie** [comment]
Yup sorry, the code working i just need delete the other data after 'action',
The detail can be clicked on the left side of the table, the problem is the icon is not showing..Already download the button from your demo though :?

**Comment by edlie** [comment]
I think the css hasnt inserted yet..
My bad, thank you for the fast respond :+1:

**Comment by vipertecpro** [comment]
Here is how i did it all from my controller, i hope this helps someone who doesn't want implementation from js, actually we're calling js but from our laravel controller,

```
$model = User::all();
if (request()->ajax()) {
   return DataTables::make($model)
	->addIndexColumn()
	->addColumn('handleBarColumn',function(User $userData){
	        return view('admin.pages.forms.handleBarInfo',compact('userData'));
	})
	->rawColumns(['handleBarColumn'])
        ->toJson();
}
$html = $builder->columns([
       ['title' => '','className' => 'details-control','orderable'  => false, 'data' => null,'searchable' => false,'defaultContent' => '','width' => '20px'],
    // ['data' => 'DT_RowIndex', 'name' => 'DT_RowIndex', 'title' => '#','orderable' => 'false','searchable' => 'false'],
       ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
       ['data' => 'handleBarColumn', 'name' => 'handleBarColumn', 'title' => '','visible' => false,'orderable'  => false]
  ])->parameters([
            'dom'           => 'Bfrtip',
            'paging'        => true,
            'searching'     => true,
            'info'          => true,
            'buttons'       => [ 'csv' , 'excel' , 'pdf'],
            'order'         => [1,'asc'],
            'drawCallback' => 'function () {
                function format ( d ) {
                    return d.handleBarColumn;
                }
                let table = $("#formDataTables").DataTable();
                $("#formDataTables tbody").on("click", "td.details-control", function () {
                    let tr = $(this).closest("tr");
                    let row = table.row( tr );
                    if ( row.child.isShown() ) {
                        row.child.hide();
                        tr.removeClass("shown");
                    }
                    else {
                        row.child(format(row.data())).show();
                        tr.addClass("shown");
                    }
                });
            }',
        ]);
```


Now finally inside blade file (which is in my case "admin > pages > forms > handleBarInfo.blade.php") you can write any condition you want 

`{{ $userData->email }}`

**Comment by angellee177** [comment]
> Here is how i did it all from my controller, i hope this helps someone who doesn't want implementation from js, actually we're calling js but from our laravel controller,
> 
> ```
> $model = User::all();
> if (request()->ajax()) {
>    return DataTables::make($model)
> 	->addIndexColumn()
> 	->addColumn('handleBarColumn',function(User $userData){
> 	        return view('admin.pages.forms.handleBarInfo',compact('userData'));
> 	})
> 	->rawColumns(['handleBarColumn'])
>         ->toJson();
> }
> $html = $builder->columns([
>        ['title' => '','className' => 'details-control','orderable'  => false, 'data' => null,'searchable' => false,'defaultContent' => '','width' => '20px'],
>     // ['data' => 'DT_RowIndex', 'name' => 'DT_RowIndex', 'title' => '#','orderable' => 'false','searchable' => 'false'],
>        ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
>        ['data' => 'handleBarColumn', 'name' => 'handleBarColumn', 'title' => '','visible' => false,'orderable'  => false]
>   ])->parameters([
>             'dom'           => 'Bfrtip',
>             'paging'        => true,
>             'searching'     => true,
>             'info'          => true,
>             'buttons'       => [ 'csv' , 'excel' , 'pdf'],
>             'order'         => [1,'asc'],
>             'drawCallback' => 'function () {
>                 function format ( d ) {
>                     return d.handleBarColumn;
>                 }
>                 let table = $("#formDataTables").DataTable();
>                 $("#formDataTables tbody").on("click", "td.details-control", function () {
>                     let tr = $(this).closest("tr");
>                     let row = table.row( tr );
>                     if ( row.child.isShown() ) {
>                         row.child.hide();
>                         tr.removeClass("shown");
>                     }
>                     else {
>                         row.child(format(row.data())).show();
>                         tr.addClass("shown");
>                     }
>                 });
>             }',
>         ]);
> ```
> 
> Now finally inside blade file (which is in my case "admin > pages > forms > handleBarInfo.blade.php") you can write any condition you want
> 
> `{{ $userData->email }}`
> 
> And here is my index file where all datatables is rendered
> 
> ```
> 
> @extends('admin.layout.app')
> 
> @section('content')
>     <div class="ibox">
>         <div class="ibox-content">
>             <div class="row">
>                 <div class="col-md-12">
>                     <div class="table-responsive">
>                     {!! $html->table(['class' => 'table table-striped table-bordered', 'id' => 'formDataTables']) !!}
>                     </div>
>                 </div>
>             </div>
>         </div>
>     </div>
> @endsection
> @section('styles')
>     <style>
>         #formDataTables tbody td.details-control {
>             background-image: url('{{ asset('assets/admin/images/details_open.png') }}');
>             cursor: pointer;
>             background-repeat:  no-repeat;
>             background-position: center;
>             background-origin: content-box;
>             background-size: cover;
>             padding: 7px;
>         }
>         #formDataTables tbody tr.shown td.details-control {
>             background-image: url('{{ asset('assets/admin/images/details_close.png') }}');
>             cursor: pointer;
>             background-repeat:  no-repeat;
>             background-position: center;
>             background-origin: content-box;
>             background-size: cover;
>             padding: 7px;
>         }
> 
>         #formDataTables tbody tr .rowDetails p {
>             font-size: 14px;
>             font-weight: 800;
>             float: left;
>             margin-right: 10px;
>             padding: 1px;
>             margin-bottom: 0;
>         }
>         #formDataTables tbody tr .rowDetails a{
> 
>         }
>         #formDataTables tbody tr .rowDetails td{
>             padding: 5px;
>         }
>         .m-r-10{
>             margin-right: 10px !important;
>         }
>     </style>
> @endsection
> @section('scripts')
>     {!! $html->scripts() !!}
> @endsection
> ```

can we put ajax inside our php controller? like you do, you are call js inside controller. is it possible if we put ajax inside the js on controller?

**Comment by underdpt** [comment]
I know this is old, but just to mention, @vipertecpro , your implementation has one bug because drawCallback is executed on every table reload, so when you load your page, it works as expected. If you reload you datatable (not the whole page) it runs again, so it runs twice (show-hide) when clicking (and the info doesn't show). If you reload again, it runs three times and the info is shown (show-hide-show) and so on....

I think you should use 'initComplete' for this.

**Comment by RayhanYulanda** [comment]
> Here is how i did it all from my controller, i hope this helps someone who doesn't want implementation from js, actually we're calling js but from our laravel controller,
> 
> ```
> $model = User::all();
> if (request()->ajax()) {
>    return DataTables::make($model)
> 	->addIndexColumn()
> 	->addColumn('handleBarColumn',function(User $userData){
> 	        return view('admin.pages.forms.handleBarInfo',compact('userData'));
> 	})
> 	->rawColumns(['handleBarColumn'])
>         ->toJson();
> }
> $html = $builder->columns([
>        ['title' => '','className' => 'details-control','orderable'  => false, 'data' => null,'searchable' => false,'defaultContent' => '','width' => '20px'],
>     // ['data' => 'DT_RowIndex', 'name' => 'DT_RowIndex', 'title' => '#','orderable' => 'false','searchable' => 'false'],
>        ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
>        ['data' => 'handleBarColumn', 'name' => 'handleBarColumn', 'title' => '','visible' => false,'orderable'  => false]
>   ])->parameters([
>             'dom'           => 'Bfrtip',
>             'paging'        => true,
>             'searching'     => true,
>             'info'          => true,
>             'buttons'       => [ 'csv' , 'excel' , 'pdf'],
>             'order'         => [1,'asc'],
>             'drawCallback' => 'function () {
>                 function format ( d ) {
>                     return d.handleBarColumn;
>                 }
>                 let table = $("#formDataTables").DataTable();
>                 $("#formDataTables tbody").on("click", "td.details-control", function () {
>                     let tr = $(this).closest("tr");
>                     let row = table.row( tr );
>                     if ( row.child.isShown() ) {
>                         row.child.hide();
>                         tr.removeClass("shown");
>                     }
>                     else {
>                         row.child(format(row.data())).show();
>                         tr.addClass("shown");
>                     }
>                 });
>             }',
>         ]);
> ```
> 
> Now finally inside blade file (which is in my case "admin > pages > forms > handleBarInfo.blade.php") you can write any condition you want
> 
> `{{ $userData->email }}`
> 
> And here is my index file where all datatables is rendered
> 
> ```
> 
> @extends('admin.layout.app')
> 
> @section('content')
>     <div class="ibox">
>         <div class="ibox-content">
>             <div class="row">
>                 <div class="col-md-12">
>                     <div class="table-responsive">
>                     {!! $html->table(['class' => 'table table-striped table-bordered', 'id' => 'formDataTables']) !!}
>                     </div>
>                 </div>
>             </div>
>         </div>
>     </div>
> @endsection
> @section('styles')
>     <style>
>         #formDataTables tbody td.details-control {
>             background-image: url('{{ asset('assets/admin/images/details_open.png') }}');
>             cursor: pointer;
>             background-repeat:  no-repeat;
>             background-position: center;
>             background-origin: content-box;
>             background-size: cover;
>             padding: 7px;
>         }
>         #formDataTables tbody tr.shown td.details-control {
>             background-image: url('{{ asset('assets/admin/images/details_close.png') }}');
>             cursor: pointer;
>             background-repeat:  no-repeat;
>             background-position: center;
>             background-origin: content-box;
>             background-size: cover;
>             padding: 7px;
>         }
> 
>         #formDataTables tbody tr .rowDetails p {
>             font-size: 14px;
>             font-weight: 800;
>             float: left;
>             margin-right: 10px;
>             padding: 1px;
>             margin-bottom: 0;
>         }
>         #formDataTables tbody tr .rowDetails a{
> 
>         }
>         #formDataTables tbody tr .rowDetails td{
>             padding: 5px;
>         }
>         .m-r-10{
>             margin-right: 10px !important;
>         }
>     </style>
> @endsection
> @section('scripts')
>     {!! $html->scripts() !!}
> @endsection
> ```

I've tried your solution, it works fine just for the first page. If i redraw the datatable, i can't click the detail (not shown the detail anymore)
