### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by SerdarSanri** [yajra/laravel-datatables#382]
If Laravel5 is required how we can use it in Laravel4 as in readme file?

**Comment by yajra** [comment]
Please use [L4 branch](https://github.com/yajra/laravel-datatables/tree/L4) for Laravel 4 installations.

**Comment by yajra** [comment]
Please use  `"yajra/laravel-datatables-oracle": "~3.0"` on your composer. v3 is the stable release for L4. Thanks!

**Comment by SerdarSanri** [comment]
No actually it is not a bug. It is confusing for someone who just started laravel. You need laravel 5 to use it in laravel 4


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by yajra** [comment]
Oh sorry if it's confusing, can you please submit a PR on how to probably make it not confusing? I maybe seeing it differently than the others so it's best if it would come from other perspective. Thanks!

**Comment by yajra** [comment]
Just please send a PR if possible. Thanks!
