### ISSUE TITLE
serverside searching is not working

### ISSUE THREAD

**Issue by sandeep-daffodilsw** [yajra/laravel-datatables#383]
i am having 

        $feedbacks = Feedback::select(array('feedbacks.name as name','feedbacks.email as email', 'feedbacks.phone as phone', 'feedbacks.created_at as created_at', DB::raw('CASE WHEN id >= 1 THEN "feedbacks" END as coltype'),'feedbacks.id as id'))->whereNull('deleted_at');
        
        $lead_data = LeadData::select(array(DB::raw('CONCAT(firstname, " ", lastname) as name'),'lead_data.email as email', 'lead_data.phn_number as phone', 'lead_data.created_at as created_at', DB::raw('CASE WHEN id >= 1 THEN "leaddata" END as coltype'),'lead_data.id as id'))->whereNull('deleted_at');
        
        $reffered = DB::table('refered_users')
                ->join('refer_user_relation', 'refered_users.id', '=', 'refer_user_relation.refered_user_id')
                ->select( 'refered_users.name as name', 'refered_users.refer_mail as email', 'refered_users.refer_phone_number as phone', 'refered_users.created_at as created_at', DB::raw('CASE WHEN refered_users.id >= 1 THEN "refer" END as coltype'), 'refered_users.id as id')
                ->union($lead_data->getQuery())->union($feedbacks->getQuery());
        
        $reffered = $reffered->where('refer_user_relation.is_deleted', '=', 0);
     
            return Datatables::of($reffered)
            
            ->edit_column('id', '
                <div class="btn-group">
                    <a href="{{{ URL::to(\'admin/\' .$coltype. \'/\'.$id ) }}}" id="view-button" class="iframe btn btn-xs btn-primary view"><i class="fa fa-eye"></i>View</a>               
                    <a href="{{{ URL::to(\'admin/\' .$coltype. \'/\'. $id  . \'/delete\' ) }}}"  id="delete-button" class="iframe btn btn-xs btn-danger delete"><i class="fa fa-trash-o"></i>Delete</a>
                </div>
            ')
            ->make();

for serverside

and 

    var oTable;
    $(document).ready(function() {

            oTable = $('#leaddata').dataTable({
		"sDom": "<'row'<'col-md-6'l><'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
                "aaSorting": [[3,'desc']],
                "aoColumnDefs": [
                    { "bSearchable": false, "bSortable": false, "aTargets": [5] }                             
                    ],
                "sPaginationType": "bootstrap",
		"oLanguage": {
			"sLengthMenu": "_MENU_ records per page"
		},
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "{{ URL::to('admin/leaddata/data') }}",
		"fnDrawCallback": function ( oSettings ) {
			$(".delete").on('click',function(e) {
                            $(".iframe").colorbox({iframe:true, width:"80%", height:"40%"}); 
                        });
                        $(".view").on('click',function(e) { // alert('view');
                            $(".iframe").colorbox({iframe:true, width:"90%", height:"80%"});
                        });                              
		}
	});
    });

Searching is not working in this code while sorting working properly. Thankx in advance.

**Comment by sandeep-daffodilsw** [comment]
Please leave your reply as soon as possible

**Comment by yajra** [comment]
It seems like you are still using datatables v1.9 convention. You need to update your js to how it is done on v1.10. See the demo site for ref. 

Sent from Outlook using iPhone




On Wed, Feb 10, 2016 at 4:23 AM -0800, "sandeep-daffodilsw" <notifications@github.com> wrote:












Please leave your reply as soon as possible

**Comment by sandeep-daffodilsw** [comment]
Thanks for reply. But now i have used this version in whole project. So it is neccesery to update the version. kindly Suggest me any possible solution with the same.

**Comment by yajra** [comment]
What version of laravel are you using? I already dropped the support on older version of datatables on latests releases. Sorry!

Sent from Outlook using iPhone




On Wed, Feb 10, 2016 at 5:23 AM -0800, "sandeep-daffodilsw" <notifications@github.com> wrote:












Thanks for reply. But now i have used this version in whole project. So it is neccesery to update the version. kindly Suggest me any possible solution with the same.

**Comment by sandeep-daffodilsw** [comment]
i am using 4.2

**Comment by sandeep-daffodilsw** [comment]
if already have support then kindly share reference with me.

**Comment by yajra** [comment]
Please see [L4](https://github.com/yajra/laravel-datatables/tree/L4) branch for Laravel 4.2. It does support lower version of DT but most of the latest features are not available on v3.x.
