### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by jongkon** [yajra/laravel-datatables#39]
production.ERROR: exception 'ErrorException' with message 'Undefined index: columns' in vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Engine/BaseEngine.php:919

**Comment by yajra** [comment]
can you please provide your `js` and `controller` code or any details to reproduce the error?

**Comment by stojankukrika** [comment]
I have a same error. Controller code:
 $news = News::select(array('id', 'title', 'created_at'));
  return Datatables::of($news)
            ->add_column('actions', '<a href="{{{ URL::to(\'admin/news/\' . $id . \'/edit\' ) }}}" class="btn btn-success btn-sm" >
                                            <i class="fa fa-pencil-square-o "></i>  {{ trans("table.edit") }}</a>
                                    <a href="{{{ URL::to(\'admin/news/\' . $id . \'/show\' ) }}}" class="btn btn-primary btn-sm" >
                                            <i class="fa fa-eye"></i>  {{ trans("table.details") }}</a>
                                     <a href="{{{ URL::to(\'admin/news/\' . $id . \'/delete\' ) }}}" class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i> {{ trans("table.delete") }}</a>')
            ->remove_column('id')
            ->make();

and js file:

<script type="text/javascript">
    var oTable;
    $(document).ready(function() {
        oTable = $('#data').dataTable( {
            "sDom": "<'row'<'col-md-6'l><'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
            "sPaginationType": "bootstrap",
            "oLanguage" : {
                "sProcessing":   "{{{ trans('table.processing') }}}",
                "sLengthMenu":   "{{{ trans('table.showmenu') }}}",
                "sZeroRecords":  "{{{ trans('table.noresult') }}}",
                "sInfo":         "{{{ trans('table.show') }}}",
                "sEmptyTable":   "{{{ trans('table.emptytable') }}}",
                "sInfoEmpty":    "{{{ trans('table.view') }}}",
                "sInfoFiltered": "{{{ trans('table.filter') }}}",
                "sInfoPostFix":  "",
                "sSearch":       "{{{ trans('table.search') }}}:",
                "sUrl":          "",
                "oPaginate": {
                    "sFirst":    "{{{ trans('table.start') }}}",
                    "sPrevious": "{{{ trans('table.prev') }}}",
                    "sNext":     "{{{ trans('table.next') }}}",
                    "sLast":     "{{{ trans('table.last') }}}"
                }
            },
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "{{ URL::to('admin/'.$type.'/data') }}"
        });
    });
</script>

**Comment by stojankukrika** [comment]
<script type="text/javascript">
    var oTable;
    $(document).ready(function() {
        oTable = $('#data').dataTable( {
            "sDom": "<'row'<'col-md-6'l><'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
            "sPaginationType": "bootstrap",
            "oLanguage" : {
                "sProcessing":   "{{{ trans('table.processing') }}}",
                "sLengthMenu":   "{{{ trans('table.showmenu') }}}",
                "sZeroRecords":  "{{{ trans('table.noresult') }}}",
                "sInfo":         "{{{ trans('table.show') }}}",
                "sEmptyTable":   "{{{ trans('table.emptytable') }}}",
                "sInfoEmpty":    "{{{ trans('table.view') }}}",
                "sInfoFiltered": "{{{ trans('table.filter') }}}",
                "sInfoPostFix":  "",
                "sSearch":       "{{{ trans('table.search') }}}:",
                "sUrl":          "",
                "oPaginate": {
                    "sFirst":    "{{{ trans('table.start') }}}",
                    "sPrevious": "{{{ trans('table.prev') }}}",
                    "sNext":     "{{{ trans('table.next') }}}",
                    "sLast":     "{{{ trans('table.last') }}}"
                }
            },
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "{{ URL::to('admin/'.$type.'/data') }}"
        });
    });
</script>

**Comment by yajra** [comment]
I see. You are still using the legacy code for DT. Please use the new convention since your using v5.x.

On the other hand, if you don't like to change your js then use v4.x instead for Laravel 5 and v3.x for Laravel 4.

Below is an example of new convention for DT1.10.

```js
$(function() {
        $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: 'users-data'
        });
    });
```

**Comment by yajra** [comment]
If you need some working codes, you can also check the [demo app](https://github.com/yajra/laravel-datatables-demo) I created for this package.

**Comment by stojankukrika** [comment]
TNX. Now it's works. I just change bProcessing=>processing, bServerSide=>serverSide, sAjaxSource=>ajax, dataTable=>DataTable. Thank you very much.

**Comment by jongkon** [comment]
Thank you very much

**Comment by vijaysebastian** [comment]
Here is my controller  
               public function getAddEditRemoveColumnData(Article $article) {
		 $users = Article::select(['id', 'name', 'created_at', 'updated_at'])->get();
                 return Datatables::of($users)
			->addColumn('action', function ($users) {
				return '&lta href="#edit-' . $users->id . '" class="btn btn-xs btn-primary"&gt&lti class="glyphicon glyphicon-edit"&gt&lt/i&gt Edit&lt/a&gt';
			})
			->editColumn('id', 'ID: @{{$id}}')
			->removeColumn('password')
			->make(true);
	}

**Comment by vijaysebastian** [comment]
here is my js

<script type="text/javascript">
$('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url("get-articles") }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'},
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
</script>

**Comment by vijaysebastian** [comment]
$('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url("get-articles") }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'},
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });

**Comment by yajra** [comment]
@vijaysebastian having same issue? 

There are some errors on your controller. `Password` is not on selected fields so why remove it? Also use proper html markup on you `action` column and not `&lt` or `&gt`.

```php
public function getAddEditRemoveColumnData(Article $article) {
	$users = Article::select(['id', 'name', 'created_at', 'updated_at'])->get();

	return Datatables::of($users)
	->addColumn('action', function ($users) {
		return '<href="#edit-' . $users->id . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i>Edit</a>';
	})
	->editColumn('id', 'ID: @{{$id}}')
	->make(true);
}
```

**Comment by vijaysebastian** [comment]
thanks for your quick response....

**Comment by yajra** [comment]
Also you can remove the `get()` method on you Article model to use `Eloquent` instead of `Collection`:
```php
$users = Article::select(['id', 'name', 'created_at', 'updated_at'])->get();
// should be
$users = Article::select(['id', 'name', 'created_at', 'updated_at']);
```

**Comment by vijaysebastian** [comment]
still shows same error

**Comment by yajra** [comment]
what version are you using for this package and Laravel?

**Comment by vijaysebastian** [comment]
laravel 5.0.28

**Comment by vijaysebastian** [comment]
![image](https://cloud.githubusercontent.com/assets/10737619/7631688/1e293e7c-fa63-11e4-8397-dee2a9e3d651.png)

**Comment by yajra** [comment]
You need to remove the `get()` method and use Eloquent instead. And also, you do not access the url directly. Some parameters must be set for the package to work. You need a view where you will define your table markup and js that will call the package via ajax request.

**Comment by yajra** [comment]
The package must work side by side with the datatables.js plugin. See this example code from their site for reference. http://datatables.net/examples/ajax/objects.html

**Comment by vijaysebastian** [comment]
sorry.......... so far i couldn't figure-out the problem. When i execute - dd($datatable->of($users)); shows expected output, but i got the exception while calling - 
return $datatable->of($users)->make();
please help me... :-(

**Comment by yajra** [comment]
I suggest you check/review the [Demo App](https://github.com/yajra/laravel-datatables-demo) I created on how to make this work. Anyways, below is another example with view and controller.
Example View:
```php
<table id="users" class="table table-hover table-condensed">
    <thead>
        <tr>
            <th class="col-md-3">{{{ Lang::get('users/table.username') }}}</th>
            <th class="col-md-3">{{{ Lang::get('users/table.email') }}}</th>
            <th class="col-md-3">{{{ Lang::get('users/table.created_at') }}}</th>
            <th class="col-md-3">{{{ Lang::get('table.actions') }}}</th>
        </tr>
    </thead>
</table>

<script type="text/javascript">
$(document).ready(function() {
    oTable = $('#users').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "/users/data",
        "columns": [
            {data: 'username', name: 'username'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
});
</script>
```

Controller:
```php
public function getData()
{
    $users = User::select(['id','name','email','created_at','updated_at']);

    return Datatables::of($users)
        ->addColumn('action', 'action here')
        ->make(true);
}
```

**Comment by vijaysebastian** [comment]
This time i just copied your code... both view and controller

**Comment by yajra** [comment]
And still having the same error? maybe your vendor folder is somewhat changed/corrupted? try deleting the vendor folder and run `composer update` to reinstall the packages?

**Comment by shijupoothotta** [comment]
Getting the same error reported by Vijaybastin:
ErrorException in BaseEngine.php line 969: 
Undefined index: columns

Controller Code:
public function getData() {
        $providers = Provider::select(['email','type','status']);
        return Datatables::of($providers)
        ->make(true);        
    }

**Comment by shijupoothotta** [comment]
After debugging with firebug, I was able to get data but this warning is shown:
DataTables warning: table id=users-table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Comment by yajra** [comment]
You might have initialized datatables more than once. Verify if you have no duplicates in your js

**Comment by intrepidtr** [comment]
yajra OH no I all function replace :(

**Comment by yajra** [comment]
@intrepidtr is this related to update your JS code to DT1.10? If yes, you can still use v4.x so that it will work on legacy code of DT. However, new features is not available on that version.

**Comment by Orthophilos** [comment]
Thanks so much . You save me from a headache!!

**Comment by asasmoyo** [comment]
hi, i have similar error. 

```
ErrorException in BaseEngine.php line 966:
Undefined index: columns
```

all i did just follow the wiki https://github.com/yajra/laravel-datatables/wiki/Installation and  https://github.com/yajra/laravel-datatables/wiki/Quick-Start. my laravel version is 5.0.* and my datatables version is ~5.0. how can i fix this? thanks :D

**Comment by yajra** [comment]
`undefined index: columns` error is related to your js columns definition. Make sure that the columns defined in your js has a corresponding selected fields on your database.

```js
columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'}
        ]
```

**Comment by asasmoyo** [comment]
my bad, it is working now, thanks a lot :D
but now i have another problem, sometimes when datatables makes a request to get data, it returns 401 unauthorized, it somehow log myself out. maybe there are bugs on my middleware but i've tested it on my other controllers it is working fine

**Comment by yajra** [comment]
For the logout part, there is a pending issue at #60. I can't replicate that issue and still trying to figure out what may have been causing the random logout.

**Comment by omar-faruk-sust** [comment]
Hello, i am getting this error.
![error](https://cloud.githubusercontent.com/assets/7138045/8234397/b15a98ce-15a9-11e5-9436-cedd4546934c.png)

when i am using make() function this error is happening. i am using laravel 5.1 and i have a confusion about one thing. in your documentation you said to add Facade like this.

Laravel 5 'Datatables' => 'yajra\Datatables\Facades\Datatables',

Laravel 5.1 'Datatables' => yajra\Datatables\Facades\Datatables::class,

but my question is about Laravel 5.1 'Datatables' => yajra\Datatables\Facades\Datatables::class, this one. is it valid? currently i am adding 'Datatables' => 'yajra\Datatables\Facades\Datatables', this one to the Facade.

**Comment by bernier** [comment]
same error as omar-faruk-sust
I have yajra/laravel-datatables-oracle (v5.4.1) installed

**Comment by yajra** [comment]
@omar-faruk-sust ,@bernier, undefined index column error means you are using the legacy code of datatables. You should use the new convention like below and DT version must be v1.10++

```php
$('table').DataTable({
  serverSide: true,
  processing: true,
  ajax: 'data',
  columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'}
        ]
})
```

**Comment by omar-faruk-sust** [comment]
i have an another question? Is it responsive? how can i make it responsive?

**Comment by yajra** [comment]
What do you mean by responsive? You need to use bootstrap 3 or css frameworks to make the design responsive and is not part of the package.

For "but getting an error of FatalErrorException in EloquentEngine.php line 24: Call to a member function getQuery() on array". There must be a bug in the package. Can you please elaborate how to reproduce the error?

**Comment by omar-faruk-sust** [comment]
i have solve this problem. but i am getting another problem in search option. Search option is not working when for the join query. help me!
