### ISSUE TITLE
[website] PDF Button on TableTools not working

### ISSUE THREAD

**Issue by mosid** [yajra/laravel-datatables#393]
When clicking the PDF button on this page [http://datatables.yajrabox.com/buttons](url), i get the following  

![pdf-yarjax](https://cloud.githubusercontent.com/assets/5040354/13026932/dba73ee8-d24b-11e5-9f00-2b36f1931b7a.png)

**Comment by yajra** [comment]
Thanks for reporting. I think this was due to server resource limitation. Try doing a filter first to trim down the data before generating the pdf file.

**Comment by mosid** [comment]
Yes ,it did work.
I am closing this issue.
Keep up the excellent work.
