### ISSUE TITLE
Problem connection ODBC and DATATABLE

### ISSUE THREAD

**Issue by miguelcano9** [yajra/laravel-datatables#394]
Hi, i have this problem

SQLSTATE[42000]: Syntax error or access violation: 0 [Informix][Informix ODBC Driver][Inr (SQLPrepare[0] at ext\pdo_odbc\odbc_driver.c:206) (SQL: select "arb_nivel", "arb_orden", "arb_codigo", "arb_des_nodo" from "gearbol" limit 10 offset 0)

and the controller

$users = DB::table('gearbol')->select('arb_nivel','arb_orden','arb_codigo','arb_des_nodo');
return Datatables::of($users)->make();

thanks for your help

**Comment by yajra** [comment]
I haven't tried using odbc but will try to give it a shot on my free time.

On the other hand, i think the odbc driver you are using seems having an issue on pagination? What package are you using?

**Comment by miguelcano9** [comment]
Thanks for your response, i dont speak much english, but i using this
package

https://github.com/michaelbonds/laravel-db2

my database is informix, the code in my controller


 $data =
DB::table(DB::raw('gearbol'))->select(DB::raw('arb_nivel,arb_orden,arb_codigo,arb_des_nodo'))->get();
  var_dump($data);

and this return the data well

but when i try with datatable

$data =
DB::table(DB::raw('gearbol'))->select(DB::raw('arb_nivel,arb_orden,arb_codigo,arb_des_nodo'));

return Datatables::of($data)->make(true);


return this

SQLSTATE[42000]: Syntax error or access violation: 0 [Informix][Informix
ODBC Driver][Ing (SQLPrepare[0] at ext\pdo_odbc\odbc_driver.c:206) (SQL:
select arb_nivel,arb_orden,arb_codigo,arb_des_nodo from gearbol limit 10
offset 0)

i copy the query in my database admin and return problem for the offset 0

thanks very much for your help and sorry for my english.

2016-02-17 20:37 GMT-05:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
Can you try limiting the query results manually? I think the problem is on the package you are using.
```php
dd(
DB::table(DB::raw('gearbol'))
->select(DB::raw('arb_nivel,arb_orden,arb_codigo,arb_des_nodo'))
->limit(10)
->get()
);
```

**Comment by miguelcano9** [comment]
Thanks, this run perfect, this return the data but when change the code for

$data = DB::table(DB::raw('gearbol'))
            ->select(DB::raw('arb_nivel,arb_orden,arb_codigo,arb_des_nodo'))
            ->limit(10)
            ->get();
return Datatables::of($data)->make(true);

Call to a member function getQuery() on array

I try also this

$data = DB::table(DB::raw('gearbol'))

->select(DB::raw('arb_nivel,arb_orden,arb_codigo,arb_des_nodo'));
        return Datatables::of($data)->make(true);

and return

SQLSTATE[42000]: Syntax error or access violation: 0 [Informix][Informix
ODBC Driver][Ing (SQLPrepare[0] at ext\pdo_odbc\odbc_driver.c:206) (SQL:
select arb_nivel,arb_orden,arb_codigo,arb_des_nodo from gearbol limit 10
offset 0)





2016-02-17 22:27 GMT-05:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
@miguelcano9, not sure about this but my guess is that your DB Driver package is not yet fully compatible on all Laravel's DB functions which makes it incompatible with this package.
