### ISSUE TITLE
Throws exception on invalid input

### ISSUE THREAD

**Issue by Petah** [yajra/laravel-datatables#395]
When I request this url `http://localhost:8440/some/table?search=da` I get 

```
ErrorException in Request.php line 34:
Illegal string offset 'value'
```

I would have expected it to show a 400, invalid input.

**Comment by yajra** [comment]
This is correct since invalid inputs were sent on the request. Maybe try catching the exception and then throw your 400 error response?

**Comment by Petah** [comment]
There is no way to tell that this was invalid input from that exception though, as it is an `ErrorException` (or just a literal error in < php 7).

**Comment by yajra** [comment]
I think I will label this for enhancement and will add custom error handler for invalid inputs. Thanks!
