### ISSUE TITLE
[question] How do I make it use HAVING for searching rather than WHERE?

### ISSUE THREAD

**Issue by Petah** [yajra/laravel-datatables#396]
How do I make it use `HAVING` for searching rather than `WHERE`?

**Comment by yajra** [comment]
You can use `filterColumn` to use a custom query for a column.

**Comment by Petah** [comment]
It didn't seem to work, as if you do a global filter it does some columns using `where` and others with `having`. This causes a query which is like:

```
SELECT foo
FROM bar
WHERE 
    col1 LIKE ?
    OR col2 LIKE ?
HAVING
    agg1 LIKE ?
    OR agg2 LIKE ?
```

This is effectively the same as:
```
SELECT foo
FROM bar
HAVING
    (
        col1 LIKE ?
        OR col2 LIKE ?
   ) AND (
        agg1 LIKE ?
        OR agg2 LIKE ?
    )
```

**Comment by yajra** [comment]
I see, if that is the case then you would have to manually write your search query using `filter` method. See this [demo](http://datatables.yajrabox.com/eloquent/custom-filter) for ref:

**Comment by yajra** [comment]
Using filter should be able to accommodate your complex queries.
