### ISSUE TITLE
retains the page number

### ISSUE THREAD

**Issue by butoibogdan** [yajra/laravel-datatables#397]
Hello,
It is possible to retain the page number of datatables after a request.
I have an edit button and i want after save the element i want to redirect me on the page where is the element not on the first page.
Thank a lot

**Comment by yajra** [comment]
I think using [saveState](https://datatables.net/reference/option/stateSave) option will the trick for that.

**Comment by butoibogdan** [comment]
Thank you very much.
It's so simple and works perfect.
Thks again
