### ISSUE TITLE
[question] A question concerning DataTables as a service

### ISSUE THREAD

**Issue by salehliam** [yajra/laravel-datatables#398]
Please forgive me if it is not the right place for such topics, I couldn't find any better though.
Is there any way to pass a parameter to the query method of the generated class?

Best regards and thank you for your response!

**Comment by yajra** [comment]
Does the parameter you need belongs to the request? If yes, then you can just use `$this->request()` to get the request instance in the query method.

**Comment by salehliam** [comment]
Thank you Arjay for the hint.

**Comment by yajra** [comment]
Welcome! :+1:
