### ISSUE TITLE
Sort problem with count

### ISSUE THREAD

**Issue by GHFernando** [yajra/laravel-datatables#40]
Hello, there is a problem with the datatable sorting a field when you use count(*) with Alias. any help plz.

**Comment by yajra** [comment]
Hi, can you please post an example code on how to reproduce the error if possible? Please also provide the Laravel and Datatables version you are using. Thanks!

**Comment by yajra** [comment]
I was able to reproduce the error and this should be fixed on v5.05. Thanks for reporting.
