### ISSUE TITLE
Eager loading Search

### ISSUE THREAD

**Issue by pyaesone17** [yajra/laravel-datatables#402]
The first issues is When i search eargerloaded data it shows like this. But there is user_name column in meter_users table.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meter_users.user_name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `meters` where (LOWER(`id`) LIKE %ev% or LOWER(`meter_users`.`user_name`) LIKE %ev% or LOWER(`computer_code`) LIKE %ev% or LOWER(`meter_number`) LIKE %ev% or LOWER(`total_charge`) LIKE %ev% or LOWER(`updated_at`) LIKE %ev% or LOWER(`id`) LIKE %ev%)) count_row_table)

This also happens when i try to select using '*' function on single table with no relationshiop

**Comment by yajra** [comment]
Were you able to see this [demo](http://datatables.yajrabox.com/eloquent/relationships)? Please see it for ref:

**Comment by pyaesone17** [comment]
Yes i do reference this demo but cant able to manage searching function. When ever i try to search 
it throws error.

Here is my js

<pre>
		    var table=$('#meter').DataTable({
		        processing: true,
		        serverSide: true,
		        ajax: '{!! route('backend.meter-management.meters.index') !!}',
		        columns: [
		            { data: 'id', name: 'id' },
		            { data: 'computer_code', name: 'computer_code' },
		            { data: 'meter_user.user_name', name: 'meter_user.user_name',orderable: false},
		            { data: 'meter_number', name: 'meter_number' },
		            { data: 'total_charge', name: 'total_charge' },		            
		            { data: 'updated_at', name: 'updated_at' },
		            { data: 'action', name : 'action'}
		        ]
		    });
</pre>

Here is my controller 

<pre>

        $columns=   ['id','meter_user_id','total_charge','computer_code','meter_number','meter_charge',
                        'created_at','updated_at'];
        return \Datatables::of(Meter::with('meterUser')->select($columns)->latest())
                ->make(true);
</pre>

Here is my model set up

<pre>


class Meter extends Model
{

    public function meterUser()
    {
    	return $this->belongsTo(\App\MeterUser::class,'meter_user_id');
    }
}
</pre>

Thansk for your time.

**Comment by yajra** [comment]
```php
{ data: 'action', name : 'action'}
``` 
should be 
```php
{ data: 'action', name : 'action', 'searchable': false, 'orderable': false}
```
since action is not part of the query.

FYI: If you are using v6.x, you can now optionally remove the name value if it's the same with data:
`{ data: 'id', name: 'id' },` to `{ data: 'id' },` for convenience.

**Comment by pyaesone17** [comment]
I finally found this issues.

Meter::with('meterUser')->select($columns) // this doesn't work

Meter::with('user')->select($columns) // After changing relationship name this  work.

I think your datatables is only compatiable with small letter relationship.

Thanks Advance.

**Comment by yajra** [comment]
OIC... eager load searching is a bit new and haven't gone some major test from the community. Will try to  look at it on my free time. Thanks!

**Comment by pyaesone17** [comment]
I know you were busy a lot for new version. :+1: 
Btw thanks for your datatables . I really love it. Keep it up

**Comment by yajra** [comment]
@pyaesone17, are you sure that camelCase relationship is causing your issue? It seems like it's working on #403? Can you please verify? Thanks!

**Comment by ikerasLT** [comment]
@pyaesone17 you should reference the relationship in view in the same fashion as it's defined in your model. In this case:
`{ data: 'meter_user.user_name', name: 'meter_user.user_name',orderable: false},`

should be

`{ data: 'meter_user.user_name', name: 'meterUser.user_name',orderable: false},`
