### ISSUE TITLE
Errors in eagle loading search

### ISSUE THREAD

**Issue by warrence** [yajra/laravel-datatables#403]
Hi, i got this error on eager loading search
`SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 6 column(s) (SQL: select count(*) as aggregate from (select '1' as `row_count` from `order_headers` where ((select * from `hospitals` where `order_headers`.`ordered_from` = `hospitals`.`id` and `hospital_name` like %a%) >= 1)) count_row_table)
`
this is my query:
`$users = OrderHeader::with('orderedFrom')->select('*');
return $this->applyScopes($users);`

and this is my column setting
`['data'=>'ordered_from.hospital_name', 'name'=>'orderedFrom.hospital_name', 'title'=>'Ordered From','searchable'=>true,'orderable'=>false],`

Please help.

**Comment by pyaesone17** [comment]
OrderHeader::with('orderedFrom')->select('*'); 

OrderHeader::with('orderedfrom')->select('*'); 

Change the Relationship name also in your model Setup.

Try to change your relationship name to lowercase. Then it will work like a charm. Your issues and mine was the same.

**Comment by warrence** [comment]
@pyaesone17 hi thanks for help.

I have follow your instruction but still getting the same message :(

**Comment by yajra** [comment]
@warrence, can you please test the snippet below if it fixes your issue? Please update QueryBuilderEngine compileRelationSearch method to this one:
```php
    protected function compileRelationSearch($query, $relation, $column, $keyword)
    {
        $myQuery = clone $this->query;
        $myQuery->orWhereHas($relation, function ($q) use ($column, $keyword, $query) {
            $sql = $q->select($this->connection->raw('count(1)'))
                     ->where($column, 'like', $keyword)
                     ->toSql();
            $sql = "($sql) >= 1";
            $query->orWhereRaw($sql, [$keyword]);
        });
    }
``` 

Let me know if it works. Thanks!

**Comment by yajra** [comment]
BTW, guys you may remove `->select('*')` on your code. It is the default of Laravel and is not needed. Already updated the demo too. Thanks!

**Comment by warrence** [comment]
@yajra thanks for reply.

May i know where to place the function compileRelationSearch?

**Comment by yajra** [comment]
`/vendor/yajra/laravel-datatables-oracle/src/Engines/QueryBuilderEngine.php`

Please update to v6.6.0 too. Thanks!

**Comment by warrence** [comment]
@yajra yes its working now :)

**Comment by yajra** [comment]
@warrence Thanks for confirming. Will release a bugfix in few minutes.

**Comment by warrence** [comment]
@yajra Thank you so much. 

Hope can see the support of the sorting soon :) :+1:

**Comment by yajra** [comment]
BTW, does `orderedFrom.hospital_name'` relation search works? @pyaesone17 is having some issues on camelCase relation.

**Comment by yajra** [comment]
Released on v6.6.1. Thanks for reporting! :+1:

**Comment by warrence** [comment]
@yajra yes its working i tried to change back the relation name in model to orderedFrom, however I'm kind of confuse when i change to lowercase, my column config as below using the relation.column for both data and name:

`['data'=>'orderedfrom.hospital_name', 'name'=>'orderedfrom.hospital_name', 'title'=>'Ordered From','searchable'=>true,'orderable'=>false],`

after i change back to orderedFrom, the data cannot use relation.column, to make it works i need to use tablecolumnname.column, as below:

`['data'=>'ordered_from.hospital_name', 'name'=>'orderedFrom.hospital_name', 'title'=>'Ordered From','searchable'=>true,'orderable'=>false],`

I don really know why but if i set data to orderedFrom, it gives error when table load, and nothing come out.

**Comment by yajra** [comment]
It's the way Laravel handles camelCase. When toJson() is called, it converts camelCase to snake_case as json response which results to `orderedFrom.hospital_name` to become `ordered_from.hospital_name`. Thus, your latter code is correct.

```php
['data'=>'ordered_from.hospital_name', 'name'=>'orderedFrom.hospital_name', 'title'=>'Ordered From','searchable'=>true,'orderable'=>false],
```

**Comment by warrence** [comment]
@yajra Thanks. Case Solved!
