### ISSUE TITLE
Row detail from eloquent query

### ISSUE THREAD

**Issue by butoibogdan** [yajra/laravel-datatables#404]
Hello,
Please can you help me with an ideea.
I have a relation ship one to may in Model and i want to use row datails.
In json response i see all  fileds but i don't know how can i use in handlebars.
In handlebars i want to use element from the second table.
I suppose that would be something like @{{tablename.columname}} but not working
Thank you verry much.

**Comment by yajra** [comment]
See this [demo](https://datatables.net/examples/server_side/row_details.html) from datatables.net that I also use as ref for my demo.

**Comment by butoibogdan** [comment]
Thank for all,
I resolve with handlebars with something like this:
@{{#table_name}}
@{{columns_name}}
@{{/table_name}}
Where table_name is the ajax response from eager loading hasmany.
Thats work on my project.
Best regards
