### ISSUE TITLE
Laravel Datatables.net get Class datatables does not exist error

### ISSUE THREAD

**Issue by tux-world** [yajra/laravel-datatables#405]
after install this package on laravel i get this error:
```
ReflectionException in Container.php line 738: 
Class datatables does not exist
```
Install:
```
composer require yajra/laravel-datatables-oracle
```
configuration on app.php:
```
'providers' => [
    ...
    yajra\Datatables\DatatablesServiceProvider::class,
],

'aliases' => [
    ...
    'Datatables' => yajra\Datatables\Datatables::class,
],
```
run publish command:
```
php artisan vendor:publish
```
route:
```
Route::get('profitsData', 'ReportProfitsController@data');
```
controller:
```
namespace App\Http\Controllers;
use Yajra\Datatables\Datatables;

class ReportProfitsController extends Controller
{
    public function data()
    {
        return Datatables::of(User::select('*'))->make(true);
    }
}
```

‍‍‍```
composer dump-autoload
```

**Comment by yajra** [comment]
Please use `Yajra\Datatables\DatatablesServiceProvider::class` as service provider and no need to add a facade/alias.

```php
'providers' => [
    ...
    Yajra\Datatables\DatatablesServiceProvider::class,
],
```

**Comment by tux-world** [comment]
after change to that, problem not solved :(

**Comment by yajra** [comment]
What version of the package and Laravel are you using? Were you able to remove the alias?

**Comment by tux-world** [comment]
​Laravel:

```
"laravel/framework": "5.2.*",
```

datatables:

```
"yajra/laravel-datatables-oracle": "^6.6.0"
```

**Comment by tux-world** [comment]
no any body can help me? :(

**Comment by yajra** [comment]
Are you upgrading from lower version? Try deleting the vendor folder then do `composer update`.

**Comment by tux-world** [comment]
Ohhhh my God!!!! DONT resolved :| :| :|

**Comment by tux-world** [comment]
do you have other solution about this problem? :(

**Comment by yajra** [comment]
Hmmm. Maybe it's the cache causing the issue? Try deleting `bootstrap/cache/services.php` then reinstall all the packages?

**Comment by tux-world** [comment]
​i use newest version of this package and i don't have that already,remove
service.php file and reinstall that dont resolve my problem :(

**Comment by yajra** [comment]
From SO. http://stackoverflow.com/questions/33122553/class-datatables-does-not-exist-error-when-using-yajra-laravel-datatables

1.first rename your project to a new name.
2.use composer update
3.run php artisan config:cache
4.and run php artisan cache:clear

**Comment by wahyusigit** [comment]
i have same problem.... and can't solve this problem :(

**Comment by yajra** [comment]
@tux-world  @wahyusigit, were you able to resolve this issue? Have you tried the suggestions from SO? Thanks!

**Comment by eComEvo** [comment]
I found this was fixed by changing "minimum-stability" to "stable" from "dev" because composer was trying to pull in "6.0.0-alpha" instead of the latest stable "6.20.0". Maybe this will help.

**Comment by hsali** [comment]
same error has also happened if you don't have conf/datatables.php. try installing latest or above 7.x

    composer require yajra/laravel-datatables-oracle
    
add these lines in config/app.php

     Yajra\Datatables\DatatablesServiceProvider::class,

     Datatables' => Yajra\Datatables\Facades\Datatables::class,

     php artisian config:cache

if you don't have file config/datables.conf. Try to paste these file there. 
https://gist.github.com/hsali/1cab0d6c81020bf7bce043b65f94373a

**Comment by price2b** [comment]
If someone come to this post using datatables 8 take into consideration that the namespace was updated

**Comment by VincentWon** [comment]
@price2b thank you. You're right.
