### ISSUE TITLE
Default number of rows to show on page load - Scroller plugin

### ISSUE THREAD

**Issue by gerald27** [yajra/laravel-datatables#406]
Hi,

Thanks for this wonderful laravel-datatables but I only have one question. Is there a way to show x number of rows upon page load? I have tried setting the pageLength but I think it's not working on scroller. I'm also using server-side processing.

Regards,
Gerald

**Comment by yajra** [comment]
Is this the [scroller extension](https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html) you were referring? I just tested it and seems to work fine but for pageLength, i think the extension computes it depending on `scrollY` value. I tested setting it to 500, and it shows 153 records. Setting it to 200 loads 63 records.

**Comment by delia-curiel** [comment]
@yajra hi, I know this issue is already closed, but I need to know if there is a way to limit the pageLength using the scroller plugin, other than the scrollY value .... I need to return just 20 rows per page, but it always return many more, and the performance is poor.
