### ISSUE TITLE
Error: Undefined index: columns

### ISSUE THREAD

**Issue by markvdputten** [yajra/laravel-datatables#41]
Hi,

Thanks for creating this package, it's exactly what I would need... only issue is that I cannot seem to get it working. I keep on receiving this error:

ErrorException in BaseEngine.php line 918: Undefined index: columns

Any thought on how to get around this?

![screen shot 2015-05-12 at 14 35 38](https://cloud.githubusercontent.com/assets/1622123/7586293/2caa4834-f8b4-11e4-9060-ddcac52bbf93.png)

Thanks in advance!

**Comment by yajra** [comment]
Can you please paste your `js`? This must be related to #39. Kindly checkout the solution there. Thanks!

**Comment by markvdputten** [comment]
Thanks for your quick response Yajra! I was trying to debug on the route directly... Ill checkout issue number #39 it looks indeed like I made the same mistake... sorry about that!
