### ISSUE TITLE
Show ... entries in Service example

### ISSUE THREAD

**Issue by jopi2016** [yajra/laravel-datatables#411]
Hi,
I implemented the Service example (http://datatables.yajrabox.com/service) and it's working great.
I've been wondering if it might be possible to show also the "Show ... entries"-dropdown as in http://datatables.yajrabox.com/images/tuts.png

If not - can I adapt how many entries are shown in the list (default is 10)

Thanks

**Comment by yajra** [comment]
Yes, you can still have it by setting the proper dom value like `'dom' => 'Blfrtip',`. `l` represents the length filter in dom. See https://datatables.net/reference/option/dom for more details.

**Comment by jopi2016** [comment]
Thank you, that worked.
