### ISSUE TITLE
Set custom limit

### ISSUE THREAD

**Issue by fabianscholz** [yajra/laravel-datatables#412]
Hi,

I tried to override the limit . Unfortunately this does not work . Even the override of the request does not work . Since the request is regenerated in Datatables.php -> Request :: Capture ( )

Is there a hint how it works?

Thanks!

```
 $datatable = Datatables::of($workingtimes)
        ->editColumn('workingtime_sum', '{{ str_replace(".",",",$workingtime_sum) }}')
		->editColumn('targettime_sum', '{{ str_replace(".",",",$targettime_sum) }}')
		->addColumn('deviation',function($element){
		                return $element->targettime_sum - $element->workingtime_sum;
		 })
		  ->setRowClass(function ($element) {
		   return $element->targettime_sum - $element->workingtime_sum >= 0 ? 'plus' : 'minus';
		 })->filter(function ($query) use ($request) {
		 if ($request->has('action') && $request->action == 'excel') {
			$query->limit('0','-1');
		}
		})
       ->make(true);
```

**Comment by yajra** [comment]
Are you trying to display all records? If yes, then you need to override the length on datatables request instance. See example snippet:

```php
public function getData(Datatables $datatables) {
	$request = $datatables->getRequest();

	$datatables->eloquent($workingtimes)
		->editColumn('workingtime_sum', '{{ str_replace(".",",",$workingtime_sum) }}')
		->editColumn('targettime_sum', '{{ str_replace(".",",",$targettime_sum) }}')
		->addColumn('deviation',function($element){
            return $element->targettime_sum - $element->workingtime_sum;
		})
		->setRowClass(function ($element) {
		   return $element->targettime_sum - $element->workingtime_sum >= 0 ? 'plus' : 'minus';
		})
		->filter(function ($query) use ($request) {
			if ($request->has('action') && $request->action == 'excel') {
			   $request->merge(['length' => -1]);
			}
		})
		->make(true);
}
```

**Comment by fabianscholz** [comment]
Hi yajra,
thanks for your support. My mistake was to create a new instance of Datatables ` Datatables::of($workingtimes)` and that grap the request again. You can close this issue. Thanks!

**Comment by hairmenu** [comment]
Hi,
sorry, i know the topic is closed but i have the same issue as fabian (expect this is the start value i want to overwrite). However, i do not get the answer.

Where do you call the `getData `function from and where are defined the `$datables`?

On my side i have a function called by ajax
```
public function dataList(Request $request) {
      ...wihtin it i do a 
     $dataTable = Datatables::of($allInvoices);
}
```

So again it is not clear to me where i stick the '`$datatables->eloquent($workingtimes)`' logic
Regards
