### ISSUE TITLE
Using show row details in Service Implementation

### ISSUE THREAD

**Issue by readergirltracey** [yajra/laravel-datatables#417]
Is it possible to add row details to service implementation. If yes can you explain how?

**Comment by yajra** [comment]
Yes, just add the column like below with the appropriate js script and css. Below is a snippet from my project that uses row details like on this [demo](http://datatables.yajrabox.com/eloquent/row-details)

```php
private function getColumns()
{
    return [
        [
            "className"      => 'details-control',
            "orderable"      => false,
            "searchable"     => false,
            "data"           => null,
            "defaultContent" => '<i class="icon-plus font-blue" style="cursor: pointer; font-size: 16px;"></i>',
            "title"          => '',
            "width"          => '20px',
        ],
        'id',
        'name',
    ];
}
```

**Comment by readergirltracey** [comment]
Okay thank you and would implementing the master details table be similar to that

**Comment by yajra** [comment]
:+1:

**Comment by developerabdan** [comment]
it cannot be clicked (the plus buttons) why ?

`protected function getColumns()
    {
        return [
            [
                "className"      => 'details-control',
                "orderable"      => false,
                "searchable"     => false,
                "data"           => null,
                "defaultContent" => '<i class="icon-plus font-blue" style="cursor: pointer; font-size: 16px;"></i>',
                "title"          => '',
                "width"          => '20px',
            ],
            'invoice',
            'nama_pemesan',
            'total_bayar',
            'konfirmasi_bayar',
            'konfirmasi_pengiriman'
        ];
    }`

`public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax('')
                    ->addAction(['width' => '100%'])
                    ->parameters([
                        'buttons' => ['csv', 'excel', 'pdf', 'print'],
                        'dom' => 'Bfrtip',
                    ]);
    }`
