### ISSUE TITLE
Global searching after Sorting on Eager Loaded tables

### ISSUE THREAD

**Issue by mauroartizzu** [yajra/laravel-datatables#418]
I am experiencing a strange fault when **global searching** eager loaded tables after I **sorted** eager loaded fields.

I am still investigating into this, but it seems it triggers only if I sort columns before i global search.

That's an example error I get

> SQLSTATE[HY000]: General error: 1 no such column: faulttype.name (SQL: select count(*) as aggregate from (select '1' as "row_count" from "faults" where LOWER("faulttype"."name") LIKE %s%) count_row_table)

Where "faulttype.name" is the column name in the datatables column definitions.

```
columns: [
      {data: 'name',           name: 'name'},
      {data: 'faulttype.name', name: 'faulttype.name'}
    ],
```

I have two models structured like this:
```
class Fault extends Model
{
    public function faulttype()
    {
        return $this->belongsTo('App\Faulttype');
    }
}

class Faulttype extends Model
{
    public function faults()
    {
        return $this->hasMany('App\Fault');
    }
}
```

And in the Controller:
```
public function datatables()
    {
        $faults = Fault::with('faulttype')
            ->select('*');

        return \Datatables::of($faults)
            ->make(true);
    }
```

The problem goes away if I cancel the column sorting by, for example, ordering by another column.

Version: yajra/laravel-datatables-oracle (v6.7.2)

EDIT: I see that in the demo pages (http://datatables.yajrabox.com/eloquent/relationships) this does not happen. It might be related to the fact I am using Sqlite on local dev. I'll try tomorrow on staging with MySQL.

**Comment by mauroartizzu** [comment]
It seems it's a duplicate column name problem. I'll watch the code asap to see it it could be fixed

**Comment by yajra** [comment]
You might be having an issue on ambiguous column name? As stated in the demo, you should use the convention we use when using a join statement. Like you said, I was not able to reproduce the error on demo site. 

Let me know what you may find. Thanks!

**Comment by mauroartizzu** [comment]
Yep, I used the convention. The thing is that I have same name fields on both tables.

```
Faults:
id
name
faulttype_id

Faulttypes:
id
name
```

I'm working on a solution, if something comes to mind I'll PR

**Comment by ikerasLT** [comment]
@mauroartizzu try to add the following into your select query:
`->addSelect('faults.name as fault_name')->addSelect('fault_types.name as fault_type_name')`
then you should avoid the ambiguous column name issue

**Comment by yajra** [comment]
Using the latest version and following @ikerasLT suggestion should fix the issue. Thanks!
