### ISSUE TITLE
Individual column searching (select inputs)

### ISSUE THREAD

**Issue by EricKwan2014** [yajra/laravel-datatables#419]
Dear Sir,

I am using laravel-datatables with HTML-BUILDER,

is there any way to make the datatable like as below.

https://datatables.net/examples/api/multi_filter_select.html

Many Thanks and have a nice day!

**Comment by yajra** [comment]
Yes, it's not yet fully documented but support for DT events callback were already added on this [commit](https://github.com/yajra/laravel-datatables/commit/38b3066e8e9fab5f13ccd604b436899568675186). 

See issue for #401 for example usage.
