### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by lloy0076** [yajra/laravel-datatables#420]
On CentOS 7 in 'bash' doing this:

```
composer require yajra/Laravel-datatables-oracle
```

...would mysteriously fail.

It turns out that one needs to quote the name of the package (my guess is that something's falling over the dashes in the name):

```
composer require 'yajra/Laravel-datatables-oracle'
```

It may be worth noting this in the installation section of the wiki (which I might have noted myself but I can't figure out how to make suggestions directly on the relative page).

**Comment by yajra** [comment]
Maybe it's because of the capital `L` that you used? `composer require yajra/Laravel-datatables-oracle` instead of `composer require yajra/laravel-datatables-oracle`?

Anyways, thanks for the info. This might help some future users.
