### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by claytonferraz** [yajra/laravel-datatables#421]
Dear @yajra 

The documentation is in http://datatables.yajrabox.com/service site is different or out of date the latest version , when I run the command: `php artisan datatables : make UsersDataTable` The file is generated with the methods and different functions and could not make it work , has update forecast? Thank you and congratulations on the excellent package.

**Comment by mithleshjs** [comment]
There is some difference but the code from the tutorial still works.

**Comment by yajra** [comment]
As @mithleshjs, the tutorial is a bit different due to some refactoring but it should still work. 

Anyways, I am planning to add more demo on service implementation soon. Thanks for the heads up!

**Comment by claytonferraz** [comment]
@yajra Thank.

**Comment by Konafets** [comment]
Was the `datatables` command removed? 

```
$ php artisan datatables                                                                                                                                                          


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "datatables" is not defined.
```
