### ISSUE TITLE
dataTable custom filter as select box

### ISSUE THREAD

**Issue by EricKwan2014** [yajra/laravel-datatables#422]
Dear Sir,

I had just follow the syntax here
https://github.com/yajra/laravel-datatables/commit/38b3066e8e9fab5f13ccd604b436899568675186

I had add the select filter code from https://datatables.net/examples/api/multi_filter_select.html

i.e.
protected function getBuilderParameters()
    {
        return [
            'order'   => [[1, 'desc']],
            'initComplete' => 'function() //...',
        ];
    }

But after that, I go back to my CMS and nothing appear, would you mind share some sample code and make it work like https://datatables.net/examples/api/multi_filter_select.html

Thank you very much

**Comment by EricKwan2014** [comment]
btw, you are the one passionate programmer :+1:  Thanks for your effort!

**Comment by yajra** [comment]
Here's a sample snippet. The trick is you have to manually write your table html and only use the generated scripts since footer is not yet available on the builder. Just set the table id to `dataTableBuilder` and apply the appropriate class.

```html
    <table id="dataTableBuilder" class="table">
    	<thead>
    		<tr>
    			<th>ID</th>
    			<th>NAME</th>
    			<th>EMAIL</th>
    			<th>CREATED AT</th>
    			<th>UPDATED AT</th>
    		</tr>
    	</thead>
    	<tfoot>
    		<tr>
    			<td></td>
    			<td></td>
    			<td></td>
    			<td></td>
    			<td></td>
    		</tr>
    	</tfoot>
    </table>
```

On your html builder, set the initComplete parameter.
```php
            ->parameters([
                 'initComplete' => 'path.to.init-complete'
            ]);
```

On `init-complete.blade.php`
```js
function() {
    this.api().columns().every( function () {
        var column = this;
        var select = $('<select><option value=""></option></select>')
            .appendTo( $(column.footer()).empty() )
            .on( 'change', function () {
                var val = $.fn.dataTable.util.escapeRegex(
                    $(this).val()
                );

                column
                    .search( val ? '^'+val+'$' : '', true, false )
                    .draw();
            } );

        column.data().unique().sort().each( function ( d, j ) {
            select.append( '<option value="'+d+'">'+d+'</option>' )
        });
    });
}
```

**Comment by EricKwan2014** [comment]
Dear Sir, 

Firstly, many thanks!

BTW, I figure out the problem.
since I am follow the document in official site as below
http://datatables.yajrabox.com/service
The syntax for represent the table is {!! $dataTable->table() !!} (without tfoot)

So is there possible to add the 
<tfoot>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tfoot>
in the library, then may fix the missing footer part

**Comment by yajra** [comment]
@EricKwan2014, yes will definitely add footer builder on a future releases of the package when given the time. Thanks!

**Comment by manelsanz** [comment]
Hello everyone, specially @yajra for this awesome work you have done with DataTables on Laravel.

I'm trying to put the code of function 'initComplete' to a separate blade file, but with no luck. The error I'm getting is from JS console: 

`b.fn.apply is not a function`

But I supose that is happening here is basically that new blade file is not found by DataTable plugin.

What I'm doing:

Partial of file EmployeesDataTable.php:

```php
    public function html()
    {
        return $this->builder()
        ->columns($this->getColumns())
        ->minifiedAjax()
        ->parameters([
            'order'   => [[0, 'asc']],
            'initComplete' => 'employees.filters',
        ]);
    }
```

File /resources/views/employees/filters.blade.php:

```php
function () {
    $(".dataTables_filter label input").attr("placeholder", "Search all employees").removeClass("form-control-sm");

    var filters =
    `<form class="form-row align-items-center ml-4">

    <span class="mr-1" title="Filters"><i class="fas fa-filter"></i></span>

    <div class="col-auto d-inline">

    <select class="form-control" id="exampleFormControlSelect1">
        <option>Type</option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
    </select>

    </div>

    <button type="submit" class="btn btn-secondary ml-1"><i class="fas fa-filter"></i> Filter</button>

    </form>`; $("#filters").append(filters);  }
```

**Comment by Skintillion** [comment]
Are you calling your blade files in the proper order?

**Comment by manelsanz** [comment]
@Skintillion Sorry, I don't understand what are you asking me. The ".append(filters)" is appending that filters to a div '#filters' added with 'dom' paramater of datatables in my principal layout 'app.blade.php' with the defaults function:

```php
$.extend(true, jQuery.fn.dataTable.defaults, {
    'dom': "<'row justify-content-between mb-2'<'#filters.col-sm-6 form-inline text-left'f><'col-sm-6 text-right'B>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'i><'col-sm-7'p>>",
    'language': {
        'search': '<i class="fas fa-search"></i>',
        'processing': '<div class="fa-3x"><i class="fas fa-circle-notch fa-spin"></i></i></div>',
        //'url': "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
    },
    'responsive': true,
    'pageLength': 20,
    // "iDisplayLength": 10,
    'buttons': [
        {
            'extend': 'print',
            'className': 'btn btn-light',
            //'message': 'This print was produced using the Print button for DataTables',
            'text': '<i class="fas fa-print"></i>',
            'exportOptions': {
                'columns': ':visible'
            },
        },
        {
            'extend': 'copy',
            'text': '<i class="fas fa-copy"></i>',
            'className': 'btn btn-light'
        },
        {
            'extend': 'reload',
            'text': '<i class="fas fa-sync-alt"></i>',
            'title': 'Reload',
            'className': 'btn btn-light'
        },
        {
            'extend': 'export',
            'alt': 'Exportar ya',
            'className': 'btn btn-light'
        },
    ],
});
```

**Comment by Skintillion** [comment]
I dont think you can just do employee.filters

Try @include('employee.filters')
