### ISSUE TITLE
Column search for many to many relation

### ISSUE THREAD

**Issue by webpixels** [yajra/laravel-datatables#424]
Hi,

I have an issue trying to make a custom column searchable.
I am using Laravel and datatable pack's version is 6.6.

I have a users model. Each user can have multiple categories attached. 

**Table structure is**:

users (id, first_name, last_name)
user_categories (id, name)
user_has_categories (user_id, user_category_id)

The models are created and everything works fine. But I am trying to make the category column searchable and sortable also:

**Datatable query**:

```
$users = User::with(array(
                'categories' => function($query){
                    $query->select('name');
                }));

return Datatables::of($users)
            ->editColumn('categories', function ($categories) {
                foreach ($categories->categories as $category) {
                     return $category->name;
                }
            })
```

**HTML**:

`<table id="datatable_fixed_column" class="table table-striped table-bordered td-v-align-middle" width="100%">          
        <thead>
            <tr>
                ..
                <th class="dt-categories">Categories</th>
                ...
            </tr>
        </thead>
    </table>`

**JS**:

`var otable = $('#datatable_fixed_column').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! action('DatatablesController@users') !!}',
            columns: [
                ...
                { data: 'categories', name: 'categories.name', width: '100px' },
                ... 
            ]
})`

Thanks!

**Comment by yajra** [comment]
First, you have to update the package to `^6.7` to support ordering on eager loaded columns. Then follow this [demo](http://datatables.yajrabox.com/eloquent/relationships) on how to make it work.

**Comment by yajra** [comment]
BTW, haven't tested it on many to many relationship. Let me know if it works. Thanks!

**Comment by yajra** [comment]
Eager loading demo should work on your case. Thanks!

**Comment by hugofabricio** [comment]
@webpixels  

You did it make searchable and sortable?

**Comment by chamra** [comment]
> @yajra 
  you have to update the package to ^6.7


I'm new to DataTables. please, can anyone tell me how to update to 6.7. I did an update via composer but it only updated to 6.22.5

**Comment by yajra** [comment]
@chamra the latest version is v6.22.5.
