### ISSUE TITLE
How I can change column property from the Laravel side?

### ISSUE THREAD

**Issue by mansouralex** [yajra/laravel-datatables#425]
For example I want to make column visible true from the backend, without using the html builder?

Thank you.

**Comment by yajra** [comment]
Not sure on this one since column property is on js/client side. I think what you can as a workaround is to add additional data on ajax response that defines the column definition. From there, listen on `draw.dt` event and do the necessary changes on your column.

**Comment by mansouralex** [comment]
Thanks for your reply. That's should do it. Actually I have done some js workaround to check when to put the column property as false or true based on some condition.
