### ISSUE TITLE
Sorting not working properly when column contains string with mixed cases

### ISSUE THREAD

**Issue by matsura** [yajra/laravel-datatables#426]
If I use a collection of eloquent models as my data source, and if the collection consists of models having the following properties(for example): name, age, organization - if name for example contains mixed cases(e.g. some names written in lower case only, some in uppercase first, or all uppercase etc.), sorting does not work properly.

Example:(desc)

test3
test2
test1
Uncharted

The one with the capital U always comes in between for some reason. This only seems to happen with collections.

I can provide any code you wish.

Using Laravel 5.

**Comment by yajra** [comment]
I just tested this and seems to work for me. Like on example output below, I use the demo app and change the `email` field to `EmAil` and it works.

```js
0: {id: 43, name: "Prof. Nick Mitchell", EmAil: "America.Pouros@Breitenberg.com",…}
EmAil: "America.Pouros@Breitenberg.com"
created_at: "03-02-2016"
id: 43
name: "Prof. Nick Mitchell"
updated_at: "03-02-2016"
```

Please provide some code to replicate the issue? Thanks!

**Comment by matsura** [comment]
This is my DataTable class, I'm providing it here in its entirety.

[http://pastebin.com/8N7xvKBh](url)

In the meantime we added a workaround. V_anketa is a database view, so we added a column with all uppercase letters(which sorts right), and left the standard one. Then we sort by the uppercase one and display the standard one.

But this leads to duplicating columns in a view and selecting more than we need which could be a performance issue in the future.

**Comment by matsura** [comment]
Any ideas?

**Comment by yajra** [comment]
You code seems fine. Just make sure the column `name` value is the same with the table/source column name or index and I think it should work fine.

```php
->columns([
  [data: 'data_to_display', name: 'ColumnName']
])
```

**Comment by ChaosPower** [comment]
@matsura Please reopen if you're still this issue.
