### ISSUE TITLE
Creating from Array or Object

### ISSUE THREAD

**Issue by mifas** [yajra/laravel-datatables#427]
Hi I'm trying to create Datatable from array or object, following article

http://datatables.yajrabox.com/collection/object

But, I'm using Laravel 4.1. I'm getting `"Call to undefined method Illuminate\Support\Collection::getQuery()"` error.

**Comment by yajra** [comment]
@mifas, sorry but the collection engine is only available on Laravel 5 & up. Laravel 4 version has lesser functionality since Bllim's version is more appropriate to use during that time.
