### ISSUE TITLE
[BUG] Sorting, Filtering problem when eager loading relationships

### ISSUE THREAD

**Issue by shadoWalker89** [yajra/laravel-datatables#428]
Hi,

First of all i want to thank you for your hard work for this amazing package :+1: .

The bug is the following : i have a relationship called "researchStructure" on a Student model

```php
public function researchStructure()
{
        return $this->belongsTo(ResearchStructure::class);
}
```

Loading the table for the first time and paginating works fine, and when i check the "queries" column in the json response, i see the correct query with an **s** in the table name

```sql
select * from `research_structures` where `research_structures`.`id` in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```

But when Using the global dataTable filter or sorting the research structure column i get the following error (sorting the other columns doesn't cause the error).

As you can see in this query the letter **s** is missing from the table name we should have "research_structure**s**" instead of "research_structure"

```sql
SQLSTATE[42S22]: Column not found: 1054 Champ 'research_structure.name' inconnu dans order clause (SQL: select * from `students` order by `research_structure`.`name` asc limit 25 offset 0)
```

By the way i have two other relations that i'm eager loading on this query called "discipline" and "establishment", both of these relationships work fine.
What i think is that the problem comes from relationships composed with more then one word.

**Comment by yajra** [comment]
@shadoWalker89 can you paste how you declare your js name and data value? Please see #403 for possible solution. Convention to follow when eager loading with 2 or more words is something like below.

```php
columns: [
  {data: 'research_structure.name', name: 'researchStructure.name'},
]
```

Let me if it works and will also update the demo and add a note for this cases. Thanks!

**Comment by shadoWalker89** [comment]
My js declaration is

```js
columns: [
    { data: 'research_structure.name', name: 'research_structure.name' }
]
```

Your declaration solved my problem.
Thanks.

It would be nice if you can add this convention into the documentation.

**Comment by yajra** [comment]
Convention added on [demo](http://datatables.yajrabox.com/eloquent/relationships) notes. Thanks for confirming!
