### ISSUE TITLE
Encrypted Data

### ISSUE THREAD

**Issue by arnoldjp57** [yajra/laravel-datatables#429]
I am using delatbabel/elocryptfive and eloquent to encrypt data. The Searching mechanism of datatables server-side does not work on these fields ... As I type Fr the records are displayed then as I type the e, they both disappear. If I switch off the encryption then the search works.

The controller uses Eloquent ... 

public function anyData()
    {
      return Datatables::of(Patn::query())->make(true);
    }

![image](https://cloud.githubusercontent.com/assets/12873055/13486596/05af3ffa-e11b-11e5-9d78-b0c4fa926a1d.png)

![image](https://cloud.githubusercontent.com/assets/12873055/13486621/37e00bf8-e11b-11e5-95ce-b12c15a3ce2a.png)

**Comment by yajra** [comment]
The package you are using is not supported by DataTables. In this case, you may to write your own `filter` manually or use `filterColumn` and do the necessary encrypt/decrypt function and apply it on your query.
