### ISSUE TITLE
Laravel5.2 Eloquent "join"

### ISSUE THREAD

**Issue by arnoldjp57** [yajra/laravel-datatables#430]
Hi .. Quick Question please ... :-)
eloquent model
![image](https://cloud.githubusercontent.com/assets/12873055/13497141/8c2b7bf2-e15c-11e5-977b-70fd694a6495.png)
Patn references Base where  base->id = patn->titl  ... I want to return base->desc
How do I define this in Datatables ... I've tried various ways and cannot get it to work
Controller ...
![image](https://cloud.githubusercontent.com/assets/12873055/13497210/dfdd5496-e15c-11e5-957a-1b4906699f25.png)
Part of Blade view
![image](https://cloud.githubusercontent.com/assets/12873055/13497253/091d26e2-e15d-11e5-9c3f-ee9d08e9a722.png)

**Comment by yajra** [comment]
See this [eager loading demo](http://datatables.yajrabox.com/eloquent/relationships) for ref.

**Comment by arnoldjp57** [comment]
Hi ... Datatables/Eloquent searching ignores case on  search on fields on primary table. On Fields referenced thru the eloquent model, the case must match. Please point me in the right direction ... Thank you

**Comment by yajra** [comment]
On config, you can configure it to do exact search.

```php
'case_insensitive' => false,
'use_wildcards'    => false,
```

**Comment by arnoldjp57** [comment]
Hi

Searching now working 100% ... the issue was the naming of the function in the model for the hasOne relationship ... I have an  issue when I try and order a column that is an eloquent relationship .... 

![image](https://cloud.githubusercontent.com/assets/12873055/14809893/6a26a294-0b90-11e6-915f-730066a41225.png)

![image](https://cloud.githubusercontent.com/assets/12873055/14809926/8f95279e-0b90-11e6-8e77-7573eea642e3.png)


![image](https://cloud.githubusercontent.com/assets/12873055/14809866/39465af2-0b90-11e6-9c9d-8b663086cf5e.png)
