### ISSUE TITLE
Button Column visibility and Column Search for v6.0

### ISSUE THREAD

**Issue by kingofkilled** [yajra/laravel-datatables#431]
Hi, i didn't find myself any example of how to implement these functions as the documents i found is out of date and can not use for the new script. Please help me. 
For Button Column visibility:
I tried add 'colvis' to buttons array and implement assets from datatables.net but it seem not working.
For Column Search:
I don't know how to implement the search script to script.blade.php.

**Comment by yajra** [comment]
Just set `visible: false` or if using the builder, `'visible' => fase` on your column definition.

**Comment by kingofkilled** [comment]
Hi, this is one of the buttons function, here is the link : https://datatables.net/reference/button/colvis#Examples

For the Column search, i was able to achieve it follow your tutorial here https://github.com/yajra/laravel-datatables/issues/422. thanks so much.

**Comment by yajra** [comment]
I see. Sorry but I haven't used `colvis` yet. Will try to have a look at it on my free time.

**Comment by kingofkilled** [comment]
Hi, i was able to resolve the issue in an easy way, just include the newest css and js of datatables.net have colvis and place buttons.server-side.js below it so it can override the functions.

**Comment by mortenlandmark** [comment]
Hi kingofkilled. Can you post the code?
