### ISSUE TITLE
datatables v5.12.5 bug : order by 

### ISSUE THREAD

**Issue by openvast** [yajra/laravel-datatables#433]
first see change log
###v5.12.5
    - Get order column name from the request. Fix #307.

###v5.12.4
    - Fix searching when aliasing a column. Fix #274.

if use "datatable->make()" the bug ：Unknown column '0' in 'order clause' (SQL: select * from ...order by `id` desc, `0` asc limit 10 offset 0)

this bug not exist  in  v5.12.4

so ,what happened...thanks

**Comment by yajra** [comment]
I see. I think this was already resolved on the latests version 6.x. Can you try upgrading to v6 and confirm if issue still occurs?

https://github.com/yajra/laravel-datatables#upgrading-from-v5x-to-v6x

**Comment by yajra** [comment]
On your email you said you had this bug on v6.x. Are you using the latest version? I tried to improved the column name detection on v6.6.0. https://github.com/yajra/laravel-datatables/blob/6.0/CHANGELOG.md#v660---2016-02-20

**Comment by openvast** [comment]
tried on 2016-03-05 10:00:00 (PRC time)

v6~  change log :
###v6.7.3 - 2016-03-02

i think i useing  v6.73in my program，have some bug like "as" /"order by" , i don't have time to change source code and fix the bug.

so, i change "datatable->make()" to "datatables->make(true)" on v5~ .

on my free time,  i will try to update v6~
