### ISSUE TITLE
Undefined index: columns: line 376 of /vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Datatables.php

### ISSUE THREAD

**Issue by jmichaelterenin** [yajra/laravel-datatables#434]
Here's my data before the call to addColumn:
`[{"id":2,"reservation_no":0,"channel":1,"status":"Active","created_at":"2015-11-14 15:06:58","date_in":"2015-11-19 00:00:00","date_out":"2015-11-20 00:00:00","guest":"First Name Last Name","total_price":"475"},{"id":5,"reservation_no":605246661,"channel":2,"status":"Cancelled","created_at":"2015-12-22 10:48:16","date_in":"2016-02-16 00:00:00","date_out":"2016-02-20 00:00:00","guest":"First Name Last Name","total_price":"0"},{"id":11,"reservation_no":285558376,"channel":2,"status":"Active","created_at":"2016-02-15 21:40:48","date_in":"2016-02-18 00:00:00","date_out":"2016-02-24 00:00:00","guest":"First Name Last Name","total_price":"2850"}]`

Here's my code:

```php
$result = \Datatables::of($reservations)
 ->addColumn('commission', function($r) {
	$resRec = $this->reservation->recordExists(array('id' => $r->id));						
	return $resRec->commission;
  })
  ->make(true);					
```

Here's my js:

```js
	var dt = $('#reservations').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": window.location.protocol + "//" + window.location.host + "/reservations/" + jdata.facility.id + "/ajax/",        
        "sDom": 'l<"title"><"create">frtip',        
        "bSortable": true,
        "bSearchable": true,
        "order": [[ 3, "desc" ]],        
        "columns": [
          { "data": "reservation_no", "name": "reservation_no"},            
		  {	"data": "channel", 
        	"name": "channel",
        	"bSearchable": false,
			"render": function(data, type, row) {
				return (data != null) ? 'TikiTour.com' : 'TikiWidget';
			}  
		  }, 		                                   
          { "data": "status", "name": "reservations.status" },
          { "data": "created_at", "name": "reservations.created_at",
			"render": function(data, type, row) {
				return moment(data).format('DD MMM, YYYY hh:mma');
			}          	          	
          },
          { "data": "date_in", "name": "date_in",
  			"render": function(data, type, row) {
				return moment(data).format('ddd, DD MMM, YYYY');
			}          	  
          },
          { "data": "date_out", "name": "date_out",
        	  "render": function(data, type, row) {
  				return moment(data).format('ddd, DD MMM, YYYY');
  			}   
          },
		  {	"data": "guest", "name": "guest", "bSearchable": false },	    			   
          { "data": "total_price", "name": "total_price", "bSortable": false, "bSearchable": false, },
		  {	"data": "commission", "name": "commission", "bSortable": false, "bSearchable": false,  }	    			   
        ]        
    });
```

Weirdly enough, it works locally. I'm on Laravel 4.2, even removed the yajra vendor directory and did a composer update. I've been at this for several hours, I'm stumped.

Using: https://cdn.datatables.net/r/bs/dt-1.10.9/datatables.min.js

And I'm sorry, I don't normally create issues, not sure how to properly display the code.

I also use datatables in another location, with success, but don't have a need to create a column.

**Comment by yajra** [comment]
I think it's on ` "bSortable": false, "bSearchable": false,`. Try using `sortable` and `orderable` instead? Since you use DT 1.10, I think the proper one to use is without `b` like `bSortable`.

**Comment by jmichaelterenin** [comment]
This is what my incoming data looks like on the production server (url-encoded). So this is the issue, will setting those options fix it? I'll try ... thanks

 'columns%5B0%5D%5Bdata%5D' => 'reservation_no',
  'columns%5B0%5D%5Bname%5D' => 'reservation_no',
  'columns%5B0%5D%5Bsearchable%5D' => 'true',
  'columns%5B0%5D%5Borderable%5D' => 'true',
  'columns%5B0%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B0%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B1%5D%5Bdata%5D' => 'channel',
  'columns%5B1%5D%5Bname%5D' => 'channel',
  'columns%5B1%5D%5Bsearchable%5D' => 'false',
  'columns%5B1%5D%5Borderable%5D' => 'true',
  'columns%5B1%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B1%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B2%5D%5Bdata%5D' => 'status',
  'columns%5B2%5D%5Bname%5D' => 'reservations.status',
  'columns%5B2%5D%5Bsearchable%5D' => 'true',
  'columns%5B2%5D%5Borderable%5D' => 'true',
  'columns%5B2%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B2%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B3%5D%5Bdata%5D' => 'created_at',
  'columns%5B3%5D%5Bname%5D' => 'reservations.created_at',
  'columns%5B3%5D%5Bsearchable%5D' => 'true',
  'columns%5B3%5D%5Borderable%5D' => 'true',
  'columns%5B3%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B3%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B4%5D%5Bdata%5D' => 'date_in',
  'columns%5B4%5D%5Bname%5D' => 'date_in',
  'columns%5B4%5D%5Bsearchable%5D' => 'true',
  'columns%5B4%5D%5Borderable%5D' => 'true',
  'columns%5B4%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B4%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B5%5D%5Bdata%5D' => 'date_out',
  'columns%5B5%5D%5Bname%5D' => 'date_out',
  'columns%5B5%5D%5Bsearchable%5D' => 'true',
  'columns%5B5%5D%5Borderable%5D' => 'true',
  'columns%5B5%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B5%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B6%5D%5Bdata%5D' => 'guest',
  'columns%5B6%5D%5Bname%5D' => 'guest',
  'columns%5B6%5D%5Bsearchable%5D' => 'false',
  'columns%5B6%5D%5Borderable%5D' => 'true',
  'columns%5B6%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B6%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B7%5D%5Bdata%5D' => 'total_price',
  'columns%5B7%5D%5Bname%5D' => 'total_price',
  'columns%5B7%5D%5Bsearchable%5D' => 'false',
  'columns%5B7%5D%5Borderable%5D' => 'false',
  'columns%5B7%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B7%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'columns%5B8%5D%5Bdata%5D' => 'commission',
  'columns%5B8%5D%5Bname%5D' => 'commission',
  'columns%5B8%5D%5Bsearchable%5D' => 'false',
  'columns%5B8%5D%5Borderable%5D' => 'false',
  'columns%5B8%5D%5Bsearch%5D%5Bvalue%5D' => '',
  'columns%5B8%5D%5Bsearch%5D%5Bregex%5D' => 'false',
  'order%5B0%5D%5Bcolumn%5D' => '3',
  'order%5B0%5D%5Bdir%5D' => 'desc',
  'start' => '0',
  'length' => '10',
  'search%5Bvalue%5D' => '',
  'search%5Bregex%5D' => 'false',
  '_' => '1457089285600',

**Comment by yajra** [comment]
I see, i think `bSortable` is ok since it's being passed as `sortable` in the server. Hmmm....

**Comment by jmichaelterenin** [comment]
Obviously, url decoding it will fix the problem. Would it be too much to ask to check for something like this in the constructor? 

urlencode(urldecode($data)) === $data

seems like i'll have to do this if I want it to work, unless there's a config option in jQUery DataTables??

**Comment by yajra** [comment]
I think the value is decoded by the Request object automatically? 

Anyways, can you please submit a PR if possible? I don't have Laravel 4.2 projects now and so I will be able to test this atm.

On the other hand, you said that it's working locally right? I think there is a similar issue like this before where the values are being encoded twice. Will try to look for it. I think some apache config fixes that issue.

**Comment by yajra** [comment]
Maybe something like this? https://www.sencha.com/forum/showthread.php?25594-Json-string-gets-encoded-twice

>[SOLVED]
I've solved my problem with the json string getting escaped. I found out that PHP's magic_quotes was still on (defaults to on with XAMPP) and was happily escaping my json strings.

**Comment by yajra** [comment]
Found the issue https://github.com/yajra/laravel-datatables/issues/142. Can you try the solution there? It was on htaccess.

```
 # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301,NE]
```

**Comment by jmichaelterenin** [comment]
Thank you very much, that was the issue, closing ...
