### ISSUE TITLE
Adding data to json response?

### ISSUE THREAD

**Issue by rombat** [yajra/laravel-datatables#438]
Hi,
Is there a way to add some data to the json response?
I'm using Laravel 4.2
Thanks in advance.

**Comment by yajra** [comment]
Yes, see issue #277 for the workaround since you're using Laravel 4.2. 

```php
$users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

$response = Datatables::of($users)->make(true); 
$data     = $response->getData(true);
$data['key'] = 'value';

return new JsonResponse($data);
```

In case of Laravel 5, you can use `->with(['key' => 'value'])`.

**Comment by dcrownak** [comment]
How to get the value . that i added in extra parameter.

**Comment by mariani10** [comment]
How to get the value . that i added in extra parameter. +1

**Comment by yajra** [comment]
You can fetch it using ajax.json api:

```js
var data = oTable.ajax.json();
console.log(data.custom_key);
```
