### ISSUE TITLE
Adding Checkboxes with Pagination

### ISSUE THREAD

**Issue by yudijohn** [yajra/laravel-datatables#439]
@yajra, i have added checkbox on my server-side datatables, when i check a data at page 1, and i move to page 2, and return to page 1, the check is gone, how to make my check still there?

**Comment by yajra** [comment]
Just follow the demo on datatables.net. 
http://datatables.net/extensions/select/examples/
http://datatables.net/extensions/select/examples/initialisation/reload.html

**Comment by genjerdotcom** [comment]
@yajra hi yajra. it dosent work on my server side. checkbox work perfectly but when i changed page checkbox gone.. 

please help me

my code 

$(document).ready(function() {
	//var rows_selected = [];
	var oTable =  $('#table-roles').DataTable({
		processing: true,
		sPaginationType: "full_numbers",
		serverSide: true,
		stateSave: true,
		ajax: "{{ url('roles-datatable') }}",
		type: 'get',
		deferRender: true,
		headers: {
			'X-CSRF-TOKEN': '{{ csrf_token() }}'
		},
		columns: [
			{ data: 'checkRow',name: 'checkRow',orderable: false, searchable: false},
			{ data: 'rownum',name: 'rownum',orderable: false,searchable: false},
			{ data: 'name',name: 'name'},
			{ data: 'aksi',name: 'aksi',orderable: false,searchable: false}
		]
	});
	var allPages = oTable.cells().nodes();
	// single checkbox
	$('#table-roles').on('change', 'td:first-child input', function(){
		$(this).closest('tr').toggleClass("highlight", this.checked);
		check_true();
	});
	// multi checkbox all
	$('#table-roles').on('click', '#mail-checkall', function(){
		if ($(this).hasClass('check-row')) {
			$('.check-row').prop('checked', false);
		} else {
			$('.check-row').prop('checked', true);
		}
		$(this).toggleClass('check-row');
		$('.check-row').closest('tr').toggleClass("highlight", this.checked);
		check_true();

	});
	// delete check
	$('#delete-value').on('click', function(){
		var val = [];
		$('.check-row:checked').each(function(i){
			val[i] = $(this).val();
			alert(val[i]);
		});
		return false;
	});
	// check if checked
	function check_true(allPages){
		if($('.check-row').is(':checked')){
			$('#delete-value').removeClass("disabled");
		}else{
			$('#delete-value').addClass("disabled");
		}
	}
	// End checkbox
});

**Comment by tantanito** [comment]
This works for me.

https://datatables.net/examples/server_side/select_rows.html

**Comment by webexpert4rv** [comment]
yykul
