### ISSUE TITLE
caseInsensitive search not working: what i'm missing??

### ISSUE THREAD

**Issue by peyobr** [yajra/laravel-datatables#44]
Hi Arjay,

i cannot figure how to make caseInsensitive search work. What i'm doing wrong?

```php
//In my controller
public function index(Request $request)
{
	$ulogs = Ulog::select(['id','id_utente','ip','url', 'method', 'action', 'tipo', 'messaggio']);
	return Datatables::of($ulogs)->make();
}

//In my view
	$(document).ready(function() {
		$('#ulogs-table').DataTable({
			processing: true,
			serverSide: true,
			ajax: '{{ url("ws/ulogs") }}',
			order: [ [0, "desc"] ],
			lengthMenu: [ [10, 25, 50, -1], [10, 25, 50, "+"] ],
			language: {
				url: "https://cdn.datatables.net/plug-ins/1.10.7/i18n/Italian.json"
			},
			search: {
				caseInsensitive: true
			},
			searchHighlight: true,
			responsive: true,
			columnDefs: [{
				render: function(data, type, row){
					return '<abbr title="' + data + '"><span class="fa fa-expand"></span></abbr>';
				},
				targets: 3
			}, {
				render: function(data, type, row){
					return data;
				},
				targets: 7
			}]
		});
	});
```
Thank you!!

**Comment by yajra** [comment]
Hi @peyobr,

Atm, case insensitive search is only available on server side config. You need to publish the config first `php artisan vendor:publish` then update `datatables.php` to your preference.

```php
return array(

	'search' => array(
		'case_insensitive' => true,
		'use_wildcards' => false,
	)

);
```

On the other hand, I think I will implement this option to override caseInsensitive config whenever it is set on the js. Will include this on v5.1 released. Thanks!

**Comment by yajra** [comment]
@peyobr sad to say but it seems that Datatables does not pass the search caseInsensitive parameter to  server side which means that we cannot override this setting via js. Atm, just use the server side config provided by the package. Cheers!

**Comment by peyobr** [comment]
OK. As explained in doc, i actually ran:

php artisan vendor:publish --provider="yajra\Datatables\DatatablesServiceProvider" --tag="config"

but now i simoly ran:

php artisan vendor:publish

:D 

Thank you.

PS. Your job is a great value!!

**Comment by yajra** [comment]
Yes, `php artisan vendor:publish` will do, but it will publish all the vendor's config. The long command publishes the config specific to the package. ^_^

**Comment by peyobr** [comment]
Sure?? O.O

Long command did'nt work for me... tried several times

Anyway now the result is perfect!

**Comment by yajra** [comment]
YES, sure but now that I've tried it doesn't work anymore... Thats odd cause it works the last time I execute it. I need to remove `--tags` part and it works now. Maybe an update in Laravel or something cause it to fail... Updating docs command to `php artisan vendor:publish --provider="yajra\Datatables\DatatablesServiceProvider"`. Thanks for the hint!

**Comment by umrtariq** [comment]
Just create php file name "datatables.php" on config folder of laravel and paste below code. its working. Thanks
<?php

return [

    'search'          => [
        
        'smart'            => true,

        'case_insensitive' => true,

        'use_wildcards'    => false,
    ],

    'fractal'         => [
        'includes'   => 'include',

        'serializer' => 'League\Fractal\Serializer\DataArraySerializer',
    ],

    'script_template' => 'datatables::script',

    'index_column'    => 'DT_Row_Index',

    'namespace'       => [

        'base'  => 'DataTables',

        'model' => '',
    ],

    'pdf_generator'   => 'excel',

    'snappy'          => [
        
        'options'     => [
            'no-outline'    => true,
            'margin-left'   => '0',
            'margin-right'  => '0',
            'margin-top'    => '10mm',
            'margin-bottom' => '10mm',
        ],
        'orientation' => 'landscape',
    ],
];
