### ISSUE TITLE
searching on 3 more eager Loaded models 

### ISSUE THREAD

**Issue by sainbayarus** [yajra/laravel-datatables#441]
Thanks for this great package. 
When i using nested relationships  (3 more tables) such as 'claim.customer.car' it shows records, but filtering has error.
It says Column not found: # Unknown column 'claim.customer.car'  
How can i searching without errors.

**Comment by yajra** [comment]
Thanks for reporting. Haven't tested eager loading with 3 or more related tables. ATM, please set the column as `searchable: false`. Will have a look at it as soon as I can.

Ping @ikerasLT. ^_^. Thanks!

**Comment by ikerasLT** [comment]
@sainbayarus could you post your select statement and the column definition?

**Comment by sainbayarus** [comment]
Sorry, 
I done it another way, using query builder  with joins. Thanks!

**Comment by yajra** [comment]
@sainbayarus, yes, using join would definitely make this work. Thanks!

**Comment by yajra** [comment]
@sainbayarus this should be fixed/supported on v6.22.0. Thanks!

**Comment by sainbayarus** [comment]
@yajra appreciated for that, good work.
