### ISSUE TITLE
Frontend side searchable attribute is ignored on server side

### ISSUE THREAD

**Issue by ady-ghe** [yajra/laravel-datatables#442]
I want to disable the search by one attribute in view:
` { data: 'distance', searchable: false, orderable: false },`

However, I see in the SQL logs that is still adding the search after this attribute:
`or LOWER(CAST("distance' ))......`

Or maybe there is any way to prevent the server side to ignore a search attribute? The problem is that if you have a SQL expression as an column, it  will throw a SQL error  because Yajra is adding that  code "LOWER(CAST("SQL expression...."))

Cheers!

**Comment by yajra** [comment]
Hmmm... ` searchable: false` should make that column ignored on search. Can you please paste your js if possible?

**Comment by ady-ghe** [comment]
The view is ok,  I get the _searchable: false_ in the Controller but I have to prevent the library to modify the SQL and search after the "_distance_"  attribute since this is not a real column in the database:

`$tracks = DB::table('tracks')
            ->select([
                    'tracks.id',
                    'tracks.title',
                    'tracks.created_at',
                    DB::raw('round((ST_Length(tracks.track, true) / 1000)::numeric, 2) as distance ')
            ->get();

return Datatables::of($tracks)
->editColumn('distance', '{{ $distance }} km')
->make(true);`

So my issue title is not correct, should  have been:  "Howto remove certain columns from search"

Regards,
Adrian

**Comment by yajra** [comment]
One way to remove a column from search is by using `searchable: false` like:
```js
{data: 'distance', name: 'distance', searchable: false, orderable: false }
```

Or another trick is to use [filterColumn](http://datatables.yajrabox.com/eloquent/post-column-search) like:
```php
->filterColumn('distance', function($query, $keyword) {
  $query->whereRaw('1 = 1');
})
```

**Comment by ady-ghe** [comment]
That did the job, thanks for your quick support!
