### ISSUE TITLE
Select <a> element inside a column using jQuery [DataTable as Service]

### ISSUE THREAD

**Issue by mithleshjs** [yajra/laravel-datatables#449]
Using DataTable as Service Implementation, I added a column with html <a> element. Now using jQuery, I can't select it using class selector method as it is nested very deep. I tried jQuery find method but still couldn't select it. Please help.

**Comment by yajra** [comment]
Use something like below:

```js
$('#tableId').on('click', 'a.className', function() {
  // do stuffs
});
```

Or you can use `LaravelDataTables` js namespace. NOTE: `dataTableBuilder` is the default ID use by the service.

```js
LaravelDataTables['dataTableBuilder'].on('click', 'a', function(){ alert('test') })
```

**Comment by mithleshjs** [comment]
Thanks man, it worked.
