### ISSUE TITLE
Call to undefined method getQualifiedForeignKey

### ISSUE THREAD

**Issue by ZAZmaster** [yajra/laravel-datatables#450]
What could be the problem?
> BadMethodCallException in Builder.php line 2161:
> Call to undefined method Illuminate\Database\Query\Builder::getQualifiedForeignKey()

**Comment by yajra** [comment]
Seems like related to eager loading. Can you please paste some snippets how to replicate the issue?

**Comment by ZAZmaster** [comment]
@yajra error was in the fact that it is not selected the correct type of relationships, my bad =)
