### ISSUE TITLE
Broken page

### ISSUE THREAD

**Issue by vipindasks** [yajra/laravel-datatables#453]
### Summary of problem or feature request

when I tried to access this page
http://datatables.yajrabox.com/html/columns
I get this

FatalErrorException in HtmlBuilderController.php line 53: Call to undefined method Yajra\Datatables\Facades\Datatables::getRequest()

**Comment by yajra** [comment]
@vipindasks, thanks for reporting. Demo fixed.

**Comment by vipindasks** [comment]
@yajra Thank you so much. :-)
