### ISSUE TITLE
alias filter fields compounds

### ISSUE THREAD

**Issue by georey** [yajra/laravel-datatables#455]
### Summary of problem or feature request

How can I filter a column that is a composite from multiple fields for example the name of person 

firstname concat lastname as person

### Code snippet of problem

->addSelect(DB::raw("coalesce(assign_users.firstname || ' ' || assign_users.lastname, 'Pending') as assign_user"))

ERROR:  column "assign_user" does not exist
LINE 14: LOWER(CAST("assign_user" as TEXT)) LIKE '%something%'

### System details

- Operating System windows 10
- PHP Version 5.6.18
- Laravel Version 5.2
- Laravel-Datatables Version:  "yajra/laravel-datatables-oracle": "^6.6" from my composer.json

**Comment by yajra** [comment]
You can use `filterColumn` for this case. See this [demo](http://datatables.yajrabox.com/eloquent/post-column-search) for reference.

**Comment by yajra** [comment]
Using filter should work for this issue. Thanks!

**Comment by georey** [comment]
thanks man Ill try this solution
