### ISSUE TITLE
New Update v5.1.1 Error My Codes !

### ISSUE THREAD

**Issue by intrepidtr** [yajra/laravel-datatables#46]
ErrorException in BaseEngine.php line 968:
Undefined index: columns

$data = Equipment::join('equipment_lang', 'equipment_lang.parentid', '=', 'equipment.id')
            ->select(array('equipment.id','equipment_lang.title','equipment_lang.product_type'))
            ->orderBy('equipment.position', 'ASC')->where('equipment_lang.lang', 'tr');

              return Datatables::of($data)->make();

**Comment by yajra** [comment]
duplicate. see #41 please.
