### ISSUE TITLE
Security issue allowing users executing public methods

### ISSUE THREAD

**Issue by vladkucherov** [yajra/laravel-datatables#460]
Hello guys,

I encountered a strange code that I don't think is well planned.
File: Services\DataTable.php
Line: 98

The function render, as to my understanding, should return the view for the data table.
If an AJAX call was made, it should return the JSON for the request.

BUT! if an `action` attribute was passed along (for none AJAX requests) it will try to execute it using:

```php
if ($action = $this->request()->get('action')) {
    if ($action == 'print') {
        return $this->printPreview();
    }

    return call_user_func_array([$this, $action], []);
}
```

I don't have any issues with `print` action, but take a look on all the public methods this class has:

- **__construct**
- render
- request
- html
- builder
- getFilename
- setFilename
- addScope

This is a serious security issue that should be fixed.
I don't think it's a good idea to let users execute those functions.

I think that if we limit the user for specific functions, that would be enough.

```php
if ($action = $this->request()->get('action') AND in_array($action, ['print','csv','excel', 'pdf']) {
    ...
}
```

Vlad.

**Comment by yajra** [comment]
@vladkucherov, thanks for the contributions. Your PR and this security issue fix were merged and released on v6.9.3 . Thanks a lot!

BTW, in case you find another security issue. Please email me directly at aqangeles@gmail.com. :beers:

**Comment by vladkucherov** [comment]
@yajra Thanks for the quick response! is this release should be available already? Also, note that the list of allowed methods maybe incomplete as I didn't really give it much a look. try to see if I missed some needed methods.

**Comment by yajra** [comment]
Your list is complete for that scope of actions. New version should be available now. I think propagation of composer takes around 5min.
