### ISSUE TITLE
Is it possible to specify which columns not to include in export to pdf/csv/excel/print

### ISSUE THREAD

**Issue by vesper8** [yajra/laravel-datatables#462]
I know you can set flags to have columns be orderable and sortable but what about exportable?

**Comment by yajra** [comment]
Yes, just set the following property on your DataTable class. 

```php
    protected $exportColumns = '*';
    protected $printColumns = '*';
```

Another way is to set it explicitly on your columns data like:
```php
['orderable' => false, 'sortable' => false, 'printable' => false, 'exportable' => false]
```

**Comment by vesper8** [comment]
beautiful! thanks!
