### ISSUE TITLE
Do this vendor works with columnFilter?

### ISSUE THREAD

**Issue by Dewilas** [yajra/laravel-datatables#463]
Hello,

your vendor for laravel server side works with datatable front end plugin http://yadcf-showcase.appspot.com/server_side_source.html?

Maybe on your plans are plugin like this? Or may recommend plugin with filter type for datatable?

**Comment by yajra** [comment]
@Dewilas, the package supports column filter but not sure if the plugin linked above will work with the package. But at a glance, it seems like it might work with some tweaks. The plugin seems to insert `yadcf_delim` on search value for dates like `03/01/2011-yadcf_delim-03/17/2016`.

See this column filter [demo](http://datatables.yajrabox.com/eloquent/multi-filter-select) for instance.

**Comment by yajra** [comment]
I think the plugin will work with some tweak on request values.

**Comment by phuthoma** [comment]
Well, as to YADCF it works fine for **text** filters, but it does not work for **data_range** filters and I don't know how to make it work. 

I'm using Datatables in server-side mode with custom paging, ordering and searching - I'm just passing the results based on data sent by DataTables to server at each draw - so I'm not loading the entire table.

Here's my controller code (I'm using Laravel 5.5.48):

    public function getDataTablesJsonActivities(Request $request) {
        $query = Activity::query(); 
        if ($request['search']['value']) {
            $request_query = addslashes($request['search']['value']);
            foreach($request['columns'] as $key => $column) {
                if (!$key) {
                    $query->where($column['data'], 'LIKE', '%'.$request_query.'%');
                } else {
                    $query->orWhere($column['data'], 'LIKE', '%'.$request_query.'%');
                }
            } 
        }   

        if ($request['columns'][2]['search']['value'] != null) {
            $query->where($request['columns'][2]['name'], '=', $request['columns'][2]['search']['value']);            
        }

        if ($request['columns'][3]['search']['value'] != null) {
            $query->where($request['columns'][3]['name'], 'LIKE', '%'.addslashes($request['columns'][3]['search']['value']).'%');            
        }

        if ($request['columns'][7]['search']['value'] != null) {
            $date = $request['columns'][7]['search']['value'];
            $date = explode('-yadcf_delim-', $date);
            $min_date = $date[0];

            if ($date && sizeof($date) > 1) {
                $max_date = $date[1];
            }

            if ($min_date)
                $query->whereDate($request['columns'][7]['name'], '>=', $min_date); 

            if ($max_date)
                $query->whereDate($request['columns'][7]['name'], '<=', $max_date); 
        }

        $count = $query->count();
        $query->orderBy($request['columns'][$request['order'][0]['column']]['data'], $request['order'][0]['dir']);
        $query->skip($request->start);
        $query->take($request->length);
        $activities = $query->get();

        $records_total = sizeof(Activity::all());

        if (!$count) {
            $records_total = 0;
        }

        return DataTables::of($activities)
            ->setTotalRecords($records_total)
            ->setFilteredRecords($count)      
            ->with([
                'query_result' => $activities,
            ])
            ->skipPaging()
            ->filter(function ($query) {})
            ->toJson();
    }

Laravel query result seems to be OK, but no data is populated to Datatables. Here are some videos for more details:
https://streamable.com/pjz41s
https://streamable.com/ibyljl

Perhaps there is way to disable YADCF filtering for this column?
