### ISSUE TITLE
How to add "table-striped" class to all my table?

### ISSUE THREAD

**Issue by rahmatawaludin** [yajra/laravel-datatables#467]
### Summary of problem
Is there an easy way to add `table-striped` class to the generated table?
My aim was to make this in config file. Is this possible?

### System details
- Operating System: OSX
- PHP Version: 7.0
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.0

**Comment by yajra** [comment]
Just pass the attributes in the `table` method.

```php
$dataTable->table(['id' => 'tableId', 'class' =>'table table-striped']);
```

**Comment by rahmatawaludin** [comment]
Ok, I'll use this approach. 
But, I'm open if there's is another way to do this (probably in `config/datatables.php`) as all datatable in my app would use `table-striped` class.

Thanks.

**Comment by yajra** [comment]
Yeah good point. Maybe we can do include it on the config file. If you can, please submit a PR if possible. Thanks for feedback.
