### ISSUE TITLE
How to add drawCallback when generating script via Html Builder?

### ISSUE THREAD

**Issue by rahmatawaludin** [yajra/laravel-datatables#468]
### Summary of problem
I'm using `$html->scripts()` to generate the js. How to add drawCallback like this one: 

````
    "drawCallback": function ( settings ) {
            var api = this.api();
            var rows = api.rows( {page:'current'} ).nodes();
            var last=null;

            api.column(4, {page:'current'} ).data().each( function ( group, i ) {
                if ( last !== group ) {
                    $(rows).eq( i ).before(
                        '<tr class="group"><td colspan="5">'+group+'</td></tr>'
                    );

                    last = group;
                }
````

### System details

- Operating System: OSX El Capitan
- PHP Version: 7.0
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.9.1 (`89c4c41ca02aeed18dac98fb1128f2f03ff17e46`)

**Comment by yajra** [comment]
You can pass it on the builder parameters like:

```php
->parameters([
   'drawCallback' => 'function(settings) { ... }'
])
```
See this issue for ref: https://github.com/yajra/laravel-datatables/issues/401
