### ISSUE TITLE
Firebug Warning

### ISSUE THREAD

**Issue by shijupoothotta** [yajra/laravel-datatables#47]
While debugging with firebug, I was able to get data with warning:
DataTables warning: table id=users-table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Comment by yajra** [comment]
Double check your JS and make sure that there are no duplicates or you have not initialize Datatables more than once. This is a JS/client side error and not really related to the package.

**Comment by shijupoothotta** [comment]
I don't know how it was cleared, but changing to eloquent and clearing all other issues, just stopped the warning. Has to be related to errors in my code. Thanks.
