### ISSUE TITLE
Can Services\DataTable access row data for custom actions?

### ISSUE THREAD

**Issue by nkvorn** [yajra/laravel-datatables#472]
I am using a `Yajra\Datatables\Services\DataTable` service to render a table and I need to add edit functionalty to each row. Is that supported?

The code I use is

```php
public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', '<a href="admin/client/'. $id . '/edit">edit</a>')
            ->make(true);
    }
```

So I need at the `$id` to access somehow the current row `$id`. Is this possible?

**Comment by yajra** [comment]
You need to use blade syntax like:
```php
->addColumn('action', '<a href="admin/client/{{$id}}/edit">edit</a>')
```

Other ways are via closure and view.
```php
->addColumn('action', 'path.to.your.view')
->addColumn('action', function($model){
    return '<a href="admin/client/'. $model->id . '/edit">edit</a>';
})

```

**Comment by yajra** [comment]
See this demo for ref: http://datatables.yajrabox.com/eloquent/add-edit-remove-column

**Comment by MPK1** [comment]
Hi there,
this solution seems not to work anymore, since "addColumn" only accepts one single array as argument.
Is there a new way to add row-specific buttons in an action column with Datatables-As-A-Service?
Thank you.
