### ISSUE TITLE
Open Page With Some Parameter

### ISSUE THREAD

**Issue by endytc** [yajra/laravel-datatables#474]
when I want to edit data in page 2 and this page have keyword for searching, after data updated I want go to page 2 and with keyword parameter for searching, when I use method redirect()->back(), page will go to index without parameter (page and search).

thank's. :smile:

**Comment by yajra** [comment]
You can use `stateSave` option to retain the paging/filter state. https://datatables.net/examples/basic_init/state_save.html
https://datatables.net/reference/option/stateSave
