### ISSUE TITLE
Applying Natural Sort to Eloquent Query

### ISSUE THREAD

**Issue by rossbearman** [yajra/laravel-datatables#475]
I'm using the service based implementation of laravel-datatables, pulling data in from an Eloquent query on an eager loaded relationship. The datatable shows the `name` column of both the `Display` and it's related `System`.

The names of records from both models is a string that can include numbers with no predetermined format within the rest of the text and the list should be sorted naturally so that it makes sense to a human user (i.e. "Test 1, Test 2, Test 10", not "Test 1, Test 10, Test 2").

Ordinarily I would use Collection's `sortBy('name', SORT_NATURAL)` method after retrieving a collection, but I can't find any way to do this with just an Eloquent query and allow the user to sort the columns as they see fit.

I also looked into using the [natural sorting plugin](https://datatables.net/plug-ins/sorting/natural) for Datatables, but this won't work with serverside processing.

How would I be able to implement natural sorting with this set up?

(As an aside, the "addSelect" and odd column naming was the only way I was able to get searching and sorting to work properly with a eager loaded relation with the same column naming, is there a better way of doing this?)

### DisplaysDataTable
```php
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query()->select('*')->addSelect('displays.name as display_name'))
            ->make(true);
    }

    public function query()
    {
        $displays = Display::query()->with('system');

        $this->addScope(new LimitBySystemSiteDataTableScope);
        return $this->applyScopes($displays);
    }

    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->addAction(['width' => '80px'])
                    ->parameters($this->getBuilderParameters());
    }

    private function getColumns()
    {
        return [
            'display_name',
            'system.name',
        ];
    }

```

**Comment by yajra** [comment]
You may need to use `orderColumn` method to override default ordering on that column and apply your natural sort query.

```php
    /**
     * Override default column ordering.
     *
     * @param string $column
     * @param string $sql
     * @param array $bindings
     * @return $this
     * @internal string $1 Special variable that returns the requested order direction of the column.
     */
    public function orderColumn($column, $sql, $bindings = [])
```

Example:
```php
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query()->select('*')->addSelect('displays.name as display_name'))
            ->orderColumn('display_name', 'display_name $1')
            ->make(true);
    }
```

**Comment by rossbearman** [comment]
Hi yajra, 

Thanks for the response. Does that mean there is no way to sort the data in PHP after the query has been run? 

As far as I can tell there is no single natural sort SQL query that works across different databases and they tend to be excessively complex (30-40 lines of code). 

As Laravel implements it at the Collection level using PHPs built in SORT_NATURAL,  is there any point where I would be able to use this (or even just PHPs natsort()) to reorder the results before they're passed to the client? 

The only other solution I can think of would be to use the Collection engine, but I think I read on another issue here about natsort that the Collection engine isn't very advanced and I imagine it's a lot less efficient than using Eloquent or the query engine. 

Thanks for your help.

**Comment by yajra** [comment]
@rossbearman, unfortunately, there is no way to mix DB and PHP sorting as far as I know. We can only choose DB sort using Eloquent Engine or via PHP sort using Collection Engine. But as you said, there are certain limitations. Like when using collection, PHP may took more resources to process the request especially if you have a large data.

**Comment by herzcthu** [comment]
```php
         ->orderColumn('display_name', 'LENGTH(display_name) $1')
`
Should work.

**Comment by rossbearman** [comment]
Unfortunately that's not actually natural sort. It sorts strings of the same length that end in a number correctly (`Thing 1,  Thing 2, Thing 10`), but not arbitrary strings containing numbers (for instance, a list of directory names). 

On 4 December 2016 07:33:19 GMT+00:00, Sithu Thwin <notifications@github.com> wrote:
>   ```php
>         ->orderColumn('display_name', 'LENGTH(display_name) $1')
>`
>Should work.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/yajra/laravel-datatables/issues/475#issuecomment-264689216

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alr2413** [comment]
> ```
>       ->orderColumn('display_name', DB::raw('LENGTH(display_name)') . $1')
> `
> Should work.
> ```

I think it's better to use the `->orderColumn('display_name', DB::raw('LENGTH(display_name), display_name') . '$1')
`
