### ISSUE TITLE
Datatables as Service add columns to Show,Edit and Delete

### ISSUE THREAD

**Issue by nasirkhan** [yajra/laravel-datatables#476]
### Summary of problem or feature request
I am planning to use Datatables as Service and i need to add Show,Edit and Delete columns. I found an example in the documentation (http://datatables.yajrabox.com/eloquent/add-edit-remove-column) but could not find any for 'Datatables as Service'

### System details
- Laravel Version : 5.1
- Laravel-Datatables Version : "yajra/laravel-datatables-oracle": "~6.0"

**Comment by nasirkhan** [comment]
got the solution form another issue.

```php

public function ajax() {
        $query = $this->query();

        return $this->datatables
                        ->eloquent($this->query())
                        ->addColumn('action', function ($query) {
                            return '<a href="' . route("admin.districts.edit", $query->id) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
                        })
                        ->make(true);
    }
```

**Comment by praveenpatel95** [comment]
Hello Yajra, I need to add delete and edit button with different column but i am using action it only use one column. show what i do?? can you help me

**Comment by backstageel** [comment]
@praveenpatel95 just change the column name:
`->addColumn('action', function ($query) {
                            return '<a href="' . route("admin.districts.edit", $query->id) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
                        })

->addColumn('another_action', function ($query) {
                            return '<a href="' . route("admin.districts.edit", $query->id) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
                        })`

**Comment by djonpereira** [comment]
Hello,Do you know how to add the action column on latest Yajra version ^8.0 ?
ajax function got replaced with:
 public function dataTable($query)
    {
        return new EloquentDataTable($query);       
    }
but in here i'm not sure how to add the:
->addColumn('action', function ($query) {
                            return '<a href="' . route("admin.districts.edit", $query->id) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
                        })

Thanks in advance,
Joao

**Comment by LewisW** [comment]
> got the solution form another issue.
> 
> ```
> public function ajax() {
>         $query = $this->query();
> 
>         return $this->datatables
>                         ->eloquent($this->query())
>                         ->addColumn('action', function ($query) {
>                             return '<a href="' . route("admin.districts.edit", $query->id) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
>                         })
>                         ->make(true);
>     }
> ```

For anyone who gets the raw HTML printed out when doing this, I also had to add rawColumns('action') to prevent the HTML getting escaped, i.e:
```
public function ajax() {
        $query = $this->query();

        return $this->datatables
                        ->eloquent($this->query())
                        ->addColumn('action', function ($query) {
                            return '<a href="' . route("admin.districts.edit", $query->id) . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
                        })
                        ->rawColumns(['action'])
                        ->make(true);
    }
```
