### ISSUE TITLE
Problem with Table tbody font-weight

### ISSUE THREAD

**Issue by minedun6** [yajra/laravel-datatables#479]
When I use this package, it displays everything correcly and the style of the tbody is ok, but when i try to use the plugin by itself, i have all the td styled with bold for an unknown reason, is there anything i can do ??

**Comment by yajra** [comment]
font-weight goes thru css. Better consult your web designer or download the standard assets to apply the default styling of dataTables. See the plugins documentation for more ref. http://datatables.net/examples/index
