### ISSUE TITLE
Add support for Builder AJAX data callback

### ISSUE THREAD

**Issue by rawaludin** [yajra/laravel-datatables#480]
### Summary of problem
I want to send custom field to datatable. Following this guide https://datatables.net/examples/server_side/custom_vars.html, I have to modify the ajax options.

Currently I'm using html builder like this:

```php
    {!! $html->parameters([
        'ajax' => ['data' => 'function(d) {d.myKey = 123}']
    ])->scripts() !!}
```

But the ajax still not changed on the html. What should I do?

### System details
- Operating System: OSX 10.11.1
- PHP Version: 7.0
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.9.4 (`22bc8c0f0ecb221ff4af3b51e812ddf369a3f1a8`)

**Comment by yajra** [comment]
@rahmatawaludin, custom data on ajax is not yet supported. ATM, you can achieve the same result by using `prexhr` event of DT. See this docs for ref: https://datatables.net/reference/event/preXhr

**Comment by rahmatawaludin** [comment]
I'm using `preXhr` like this, but still can't get it working..

````
    {!! $html->parameters([
        'preXhr.dt' => 'function (e, settings, data) { data.myData = 'foo';}' 
    ])->scripts() !!}
````

Here is what I get when I search for `a`:

<img width="264" alt="screen shot 2016-03-22 at 2 06 53 pm" src="https://cloud.githubusercontent.com/assets/1274849/13944373/62657522-f037-11e5-970d-fcff9185b3d0.png">

<img width="196" alt="screen shot 2016-03-22 at 2 07 00 pm" src="https://cloud.githubusercontent.com/assets/1274849/13944376/68b69d34-f037-11e5-9480-32ff2ec651c4.png">

What should I do to make this working?

**Comment by rahmatawaludin** [comment]
Nevermind. Get it working by making it like this:

````
    {!! $html->scripts() !!}
    <script>
    $("#dataTableBuilder").on('preXhr.dt', function(e, settings, data) { data.myData = 'foo'});
    </script>
````

**Comment by yajra** [comment]
@rawaludin This enhancement was already implemented on latest version of the package. Check it out! Thanks!
