### ISSUE TITLE
how can i customize the html and css ?

### ISSUE THREAD

**Issue by soly2014** [yajra/laravel-datatables#483]
### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
You can use the CDN if you want. See http://cdn.datatables.net/ for list of possible assets.

**Comment by AiFxApp** [comment]
Thanks - but i had to import that file to edit the views .. I am trying to find where i can add the padding, button colors etc?
