### ISSUE TITLE
RouteNotFoundException When going from page to page

### ISSUE THREAD

**Issue by minedun6** [yajra/laravel-datatables#484]
Sometimes, when i paginate from page to another page, i found an odd "RouteNotFoundException", but the problem is when i reload the page, it works just fine, is this a bug or something, i dunno.
Is there a fix for it ?

Ps: I did check the system requirements for it to work.

**Comment by yajra** [comment]
Is this happening only on your local or also in production? 

You might be using `artisan serve` which is known to be buggy when used with the package? If yes, I suggest you use homestead if possible.

**Comment by minedun6** [comment]
yes, indeed, I am on my local machine and not using homestead because I'm not really used to it yet but i will.
Isn't there a way to get this to work correctly cuz i'm still comfortable with the old way ?

Btw keep up the good work ^^

**Comment by yajra** [comment]
Are you using artisan serve? Try using apache/nginx or zend server/xampp instead. Thanks!

**Comment by minedun6** [comment]
Yes I am using artisan serve ?? Is there something wring with it or what ?

**Comment by yajra** [comment]
Yes, there are several issues that weirdly occur when using artisan serve. Here are some related issues and are fixed by using apache. https://github.com/yajra/laravel-datatables/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+artisan+serve

**Comment by yajra** [comment]
Using apache and avoiding artisan serve should fix this issue.
