### ISSUE TITLE
Oracle Reserved Words Case Sensitive Problem in Soft Delete Model

### ISSUE THREAD

**Issue by fathur** [yajra/laravel-datatables#485]
Hi, I installed laravel-datatables on laravel project, I am using Oracle 11g. Somehow in query with [reserved words](https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm), it must be in case sensitive.

For example I have table `imagesizes` and column `LABEL`, in uppercase. And I run following code in my Controller:

```php
$imageSizes = ImageSize::onlyTrashed()->select([
            \DB::raw(strtoupper('LABEL')),
            'type','width','height'
        ]);

return Datatables::of($imageSizes);
```

My view:

```php
$('#imagesize-datatables').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{route('imagesize.trash.data')}}",
                },
                columns: [
                    {data:'label',name:'label'},
                    {data:'type',name:'type'},
                    {data:'width',name:'width'},
                    {data:'height',name:'height'}
                ]
            });
```

It gives me error like this:

```
Error Code : 904
Error Message : ORA-00904: "label": invalid identifier
Position : 152
Statement : select t2.* from ( select rownum AS "rn", t1.* from (select LABEL, type, width, height from image_size where image_size.deleted_at is not null order by "label" asc) t1 ) t2 where t2."rn" between 1 and 10
Bindings : []
(SQL: select t2.* from ( select rownum AS "rn", t1.* from (select LABEL, type, width, height from image_size where image_size.deleted_at is not null order by "label" asc) t1 ) t2 where t2."rn" between 1 and 10)
```

Column "label" in order by query above still in lowercase, which is should be in uppercase. Please help me with this.

System details:

- OS: Ubuntu, Yajra Homestead Oracle
- PHP version: 5.6.15
- Laravel version: 5.1.*
- Yajra datables version: 6.10.*

**Comment by yajra** [comment]
I think we can do a work around here using `filterColumn` and `orderColumn`. Basically, you need to override the default sort/filter function and write your own case sensitive column query. See this filterColumn demo for ref: http://datatables.yajrabox.com/eloquent/post-column-search

For orderColumn, you can use `->orderColumn('label', '"LABEL" $1')`. 

BTW, I just added a quick demo for orderColumn. http://datatables.yajrabox.com/eloquent/order-column

**Comment by fathur** [comment]
great this work
