### ISSUE TITLE
Custom filters for Eloquent relationships

### ISSUE THREAD

**Issue by duxet** [yajra/laravel-datatables#486]
Right now, you can only add custom filter for fields of target object. What about related objects?

**Comment by ryanrca** [comment]
Yes, I encountered this today.   My query looks like this:
``
$users = User::whereHas('roles', function ($query) use ($filter) {
                    $query->where('name', $filter);
                })->with('roles');
``

When I try to enter search string, I get a stack trace from Datatables (backend) that says "unknown column 'roles'"

**Comment by yajra** [comment]
Were you able to see this [relationship demo](http://datatables.yajrabox.com/eloquent/relationships)? It might address this issue. However, please note that not all relationships are fully supported. For a more stable solution, you can use join statements like this [demo](http://datatables.yajrabox.com/eloquent/joins).

**Comment by ryanrca** [comment]
Thanks, but no love.  Here is a log dump of the json I pass to 'return Datatables::of($credits)->make(true);', and here are my column defs.

`[{"id":"1","created_at":null,"updated_at":null,"credits":"1","title":"Single Credit","description":"Purchase as many credits at $1 each.","product":{"id":"4730","upc":"CRE-001","name":"Single Credit","long_description":"Purchase a single credit","short_description":"Purchase a single credit","productable_id":"1","productable_type":"fuel\\CreditPackage","state":"new","processing_error":null,"contributor_id":null,"curator_id":null,"credit_price":null,"cash_price":"1.00","curators_choice":"0","enabled":"1","sha256":null,"curators_notes":null,"url_slug":null,"purchase_count":"0","download_count":"0","exclusive":"0","last_downloaded":null,"created_at":"2016-03-25 03:45:29","updated_at":"2016-03-25 03:45:29","max_edge":"1"}},{"id":"2",....`

`       columns: [
            { data: 'id',                        name: 'credit_packages.id', searchable: false },
            { data: 'credits',                   name: 'credit_packages.credits'},
            { data: 'title',                     name: 'credit_packages.title'},
            { data: 'product.long_description',  name: 'product.long_description' },
            { data: 'product.short_description', name: 'product.short_description' },
            { data: 'product.state',             name: 'product.state' },
            { data: 'product.enabled',           name: 'product.enabled' },
            { data: 'product.cash_price',        name: 'product.cash_price' },
            { data: 'product.purchase_count',    name: 'product.purchase_count' }
          ],
`
The error I'm getting:
"Requested unknown parameter 'product.long_description' for row 1 column 3"

I have no idea what I'm doing wrong.

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
