### ISSUE TITLE
Searching doesn't work with POST routes

### ISSUE THREAD

**Issue by joanebrown** [yajra/laravel-datatables#49]
Hi,

My Javascript code:

<pre>$('#list').dataTable({
    "sAjaxSource":"/complete_list",
     "sPaginationType": "bootstrap_full_number",
    "bAutoWidth": false,
    "iDisplayLength": 25,
    "deferRender": true,
    "bProcessing": true,
    "bServerSide": true,
    "sServerMethod": "POST",
    "order": [[0, "desc"]],
});</pre>

My route:

`Route::get('/complete_list', array('uses' => 'testController@load_Datatable'));`

When I change the GET method in my route and in my JS, the searching works well. But when I use POST; the search doesn't work. Return all the rows.

Is my code wrong... or is a fail of the package?

Regards and thanks for your amazing job:)

**Comment by yajra** [comment]
Hi, what version of the package are you using? Will try to replicate the error.

**Comment by joanebrown** [comment]
Sorry for my ignorance... How I can check my version?

**Comment by yajra** [comment]
Oh good question. If your using phpstorm, you just open composer.json file and hovering/selecting the package will show you the version you are using. Or you can also view it on composer.lock file and search yajra/laravel-datatables-oracle.

**Comment by joanebrown** [comment]
In my composer.json I have the next:
`"yajra/laravel-datatables-oracle": "~3.0"`

**Comment by yajra** [comment]
I see. Your using Laravel 4 version. Atm, can you please use `get` method? Will not be able to check it today but will try to check this as soon as I can. Thanks for reporting.

BTW, have you tried doing a composer update? The latest stable release for Laravel 4 is v3.6.3.

**Comment by joanebrown** [comment]
Of course I can use GET now. Thanks to you :) But do not forget! jaja

Yes, I tried with composer update command; but nothing changes...

See you! :D

**Comment by yajra** [comment]
hi @joanebrown,

I just tried the `POST` method and it works. Maybe you haven't setup your [CSRF protection](http://laravel.com/docs/master/routing#csrf-protection)?

Try using firebug/chrome dev tools and inspect your ajax request? You might be getting a TokenMismatchError.

**Comment by joanebrown** [comment]
Hi @yajra, thanks for your response.

Nope, I not get any error; only the stream generated by datatable package:

<pre>{"sEcho":0,"iTotalRecords":7,"iTotalDisplayRecords":7,"aaData": .... }</pre>

I do not get to make it work with POST; the search box returns all rows.

Maybe I have an error... but I can't find where.  May you take a look to my code, please...?

ROUTES.PHP:

<pre>Route::post('/complete_list', array('uses' => 'TestController@load_Datatable'));</pre>

JAVASCRIPT:
<pre>
$('#list').dataTable({
    "sAjaxSource":"/complete_list",
    "sPaginationType": "bootstrap_full_number",
    "bAutoWidth": false,
    "iDisplayLength": 25,
    "deferRender": true,
    "bProcessing": true,
    "bServerSide": true,
    "sServerMethod": "POST",
});
</pre>

CONTROLLER:
<pre>
  public function load_Datatable() {
        return Datatables::of(Clients::select(array('id', 'name', 'phone', 'email', 'state', 'active')))
                        ->setRowId(function($client) {
                            return $client->id;
                        })
                        ->editColumn('active', '
                           @if($active)
                                <span class="label label-sm label-success">Yes</span>
                           @else
                               <span class="label label-sm label-danger">No</span>
                           @endif'
        )->make();
    }

</pre>

**Comment by yajra** [comment]
hi @joanebrown ,

Sorry I was using v5.x when I test the package. Was able to reproduce the error on v3.x and this should be fixed on v3.6.4. Thanks for reporting!

**Comment by joanebrown** [comment]
Ok, thanks!!

How can I update the package using composer?

**Comment by yajra** [comment]
just run `composer update yajra/laravel-datatables-oracle`
