### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by necenzurat** [yajra/laravel-datatables#492]
Any plans for implementing [Simple Inline Editing](https://editor.datatables.net/examples/inline-editing/simple)?

**Comment by yajra** [comment]
@necenzurat, DT Editor is a paid plugin and I do not have a license to use it. But you can check this site http://datatables.codetoweb.com/ that add supports for the editor.

**Comment by yajra** [comment]
Maybe not atm. Thanks!
