### ISSUE TITLE
Optimizing pagination

### ISSUE THREAD

**Issue by hairmenu** [yajra/laravel-datatables#495]
Hi,

As many of us, i can not really afford the full search on all the record before the pagination. Too much time spent in join and so on.

So basically i created a first query to get the total of record (skipping all order and some joins).
Then i make a limited search for the current chunck (draw).

All the query part works well, but  when i send the collection to Database::of, i can not find any way to overwrite the start parameter of the request. So far, it results in database returning empty data for every draw bigger than one.

It is similar to issue412, but i m still missing some part.
My code looks like this

 ```
$allInvoicesQuery = Invoice::
            join('contacts', 'contacts.id', '=', 'invoices.contact_id')
            ->join('customers', 'customers.id', '=', 'invoices.customer_id')
            ->more joins

        /** Filters */
        if (isset($searches['customer_id']) && $searches['customer_id'] > 0) {
            $allInvoicesQuery->where('invoices.customer_id', $searches['customer_id']);
        }

        /** @var optimized count before full query $allInvoicesQueryCount */
        $allInvoicesQueryCount = $allInvoicesQuery;
        $allInvoicesQueryCount = $allInvoicesQueryCount->count();


        if ($allInvoicesQueryCount > 0) {
            $allInvoicesQuery->select([
                '..my fields',
            ])
            ->skip($request->start)->take($request->length) // my chunk
            ->orderBy('invoices.created_at', 'DESC');
            $allInvoices = $allInvoicesQuery->get();

            $originalStart = $request->start;
            $request->merge( [ 'start' => 0 ] );

            $dataTable = Datatables::of($allInvoices)
                ->filter(function ($query) use ($request) {
                   $request->merge(['start' => 0]);
                })
                ->with([
                    'recordsTotal' => $allInvoicesQueryCount,
                    'recordsFiltered' => $allInvoicesQueryCount,
                ])
                ->make(true);
```
I do get that the DataBase is working with the original Request object but still, somehow, i should be able to overwrite this. As if i force the start value  to be 0 in the CollectionEngine::paging() function, Everythinf works as expected.

Thx for any tips

**Comment by yajra** [comment]
@hairmenu, I think you are using a wrong request instance. Datatables has it's own request instance that you should use. You may try using IoC or method injection to get the DT instance first then get the Request instance like on this [demo](http://datatables.yajrabox.com/collection/ioc).

```php
    $datatables = app('datatables');
    $request = $datatables->getRequest();
    // do your request override and other stuffs.
    return $datatables->collection($invoices)->make(true);

**Comment by hairmenu** [comment]
Yup this totally made my day thx.
