### ISSUE TITLE
can project be updated to work with latest dompdf v7 ?

### ISSUE THREAD

**Issue by vesper8** [yajra/laravel-datatables#496]
Currently I can't install dompdf 0.7.x because this has a dependency on dompdf/dompdf ^0.6.1

Is there any chance you can check if your pdf export still works correctly under 0.7 and if it does update the dependency?

thank you

**Comment by yajra** [comment]
Will try to check this later. Thanks for the info.

**Comment by vesper8** [comment]
thanks, that would be really helpful

**Comment by yajra** [comment]
@vesper8, 0.7 is still in beta? I think we should wait for the stable version first before upgrading?

Anyways, can you please give me some idea on the changes on v0.7 why you decided to use it? Thanks!

**Comment by vesper8** [comment]
Yea it's still in beta but I figure since your project barely uses it and uses it for something quite simple (export datatable to pdf) it should be fine to use this. The thing is I have been using dompdf a lot lately to build a pretty complex pdf report and have been running into a few annoying issues that I hoped might be addressed in version 7 so I wanted to give it a try, but I couldn't because I'm also using your package and it's holding me back from upgrading.

**Comment by yajra** [comment]
I see. You can temporarily test it by forking the project and then update the dependencies. Afterwards, use composer repositories to force composer to use your version of the package. Update your composer and add something like below:
```php
"repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/vesper8/laravel-datatables-oracle.git"
      },
    
```

**Comment by yajra** [comment]
I think we should wait for the stable version first before upgrading. Thanks!

**Comment by mgrulich** [comment]
Hi @yajra,

0.7.0 is now stable for a while (since May 2016), can you please update?

Best regards,
Martin
