### ISSUE TITLE
Route not found sometimes for the ajax call

### ISSUE THREAD

**Issue by sebastianvirlan** [yajra/laravel-datatables#498]
### Summary of problem or feature request

I have set up a blank app with the library. Sometimes the table is populated, sometimes route is not found.

https://www.dropbox.com/s/tx61jqa56z12ghb/datatable.rar?dl=0

### System details

- Operating System windows 10
- PHP Version 5.6
- Laravel Version 5.
- Laravel-Datatables Version

**Comment by yajra** [comment]
Same with #497.
