### ISSUE TITLE
not working! help please

### ISSUE THREAD

**Issue by donny26utama** [yajra/laravel-datatables#499]
i'm using laravel 4.2 and i was looking for datatable server-side processing. and i found yajra/laravel-datatables. in readme you say "jQuery DataTables API for Laravel 4|5". but when try to using. showing error because not compatible to my laravel. how i can use this in laravel 4.2?

**Comment by yajra** [comment]
Please see [L4 Branch](https://github.com/yajra/laravel-datatables/tree/L4) for Laravel 4.2 usage.

Alternatively, you can also use https://github.com/bllim/laravel4-datatables-package. This is the most used package during Laravel 4.2 days.

**Comment by donny26utama** [comment]
now i use yajradatatables v3..  but something wrong in there.
when i open my page (myweb.com/merchant/customer-list/)
it will show my customer list...
and i use yajra datatables

on "ajax: "myweb.com/merchant/customer-list/data",

but the datatables request not "myweb.com/merchant/customer-list/data" but
on "myweb.com/merchant/customer-list/"...
and i cant control what column i want to show.. how to fix it?

2016-04-07 8:02 GMT+07:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
Can you please paste your code so we can review further? Thanks!

**Comment by donny26utama** [comment]
sorry i just uninstall your package, but i still waiting solution from you.
how about you give me instruction step by step for using it. i think i miss
some step. can you give me instruction my condition?

my condition:
i have model 'MerchantStore'
so my query is

$store = \MerchantStore::where('merchant_id',$merchant)->get();
$this->data['store'] = $store;
return \View::make('merchant.store.inde',$this->data);

i using this to create table of store list. and i using datatables plugin.

from above can you show me how to use your package? thanks.

2016-04-29 8:50 GMT+07:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
You can check this [demo](http://datatables.yajrabox.com/eloquent/basic) for reference.

**Comment by donny26utama** [comment]
in your case you use
$('#user-table).DataTable({
// some code
});

but on me
$('#user-table).dataTable({
// some code
});

is any different from .DataTable with .dataTable ? because to write
serverSide i must write bServerSide

2016-04-29 9:33 GMT+07:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
.DataTable is on v1.10, .dataTable is on v1.9 and below. It depends on your js version. But 1.10 still have backward compatibility.

**Comment by yajra** [comment]
Please see [L4 Branch](https://github.com/yajra/laravel-datatables/tree/L4) for Laravel 4.2 usage.

**Comment by donny26utama** [comment]
ok, so must i to update my js version? or still this version?

2016-04-29 9:41 GMT+07:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
I suggest you use v1.10 and it's new js convention if possible.

**Comment by donny26utama** [comment]
ok. i will install your package again. if i have question, can i ask you
again?

2016-04-29 9:45 GMT+07:00 Arjay Angeles <notifications@github.com>:

**Comment by yajra** [comment]
Sure NP. But please note that L4.2 version is not actively maintained so any enhancements may not be accommodated. 👍

**Comment by donny26utama** [comment]
got it. thanks

2016-04-29 9:54 GMT+07:00 Arjay Angeles <notifications@github.com>:

**Comment by ChaosPower** [comment]
Closing inactive issue
