### ISSUE TITLE
Row Numbering on Page Click

### ISSUE THREAD

**Issue by shijupoothotta** [yajra/laravel-datatables#50]
I need to add a serial number column to all rows. How can I access the start page from data-table.
    public function getData() {
        $providers = Provider::select(['fname','lname','email', 'type', 'status', 'created_at']);
        return Datatables::of($providers)
                       <strong> ->addColumn('slno','start page + 1',1)</strong>
                        ->addColumn('fullname', function($model) {
                            return $model->fullname;
                        },2)
                        ->editColumn('status', '{!! ucfirst($status) !!}')
                        ->removeColumn('fname')
                        ->removeColumn('lname')
                        ->make();
    }

**Comment by yajra** [comment]
What database are you using? For oracle and mysql, you can access `rn` and `row_num` variable for that. For the other database, not sure if they have something like that.

Another way is to compute it manually. Just check input value for `start` and `length` then just do the math. 

```php
$start = Request::get('start'); // start of page
$length = Request::get('length'); //pagination limit
```

**Comment by shijupoothotta** [comment]
I was able to access the start variable but how can I pass it on to Datatables::of()

public function postData() {
        $providers = Provider::select(['fname','lname','email', 'type', 'status', 'created_at']);
        $start = Request::get('start'); // start of page
        return Datatables::of($providers)
                        ->addColumn('Slno','$start + 1')
                        ->addColumn('fullname', function($model) {
                            return $model->fullname;
                        },2)
                        ->addColumn('Actions','Action Here')
                        ->editColumn('status', '{!! ucfirst($status) !!}')
                        ->removeColumn('fname')
                        ->removeColumn('lname')
                        ->make();
    }

**Comment by yajra** [comment]
use closure on your addColumn:

```php
->addColumn('Slno', function($model) use ($start) {
   return $start + 1;
})

```

**Comment by shijupoothotta** [comment]
Yes, that did it. Thanks.

**Comment by yajra** [comment]
Your welcome, glad to help!

**Comment by shijupoothotta** [comment]
Please, One Issue. The value of Slno is always 1.

public function getData(AjaxRequest $request) {
        $providers = Provider::select(['fname','lname','email', 'type', 'status', 'created_at']);
        $start = $request->get('start'); // start of page
        return Datatables::of($providers)
                        ->addColumn('slno', function($model) use ($start) {
                            return $start + 1;
                        },1)                
                        ->addColumn('fullname', function($model) {
                            return $model->fullname;
                        },2)
                        ->addColumn('Actions','Action Here')
                        ->editColumn('status', '{!! ucfirst($status) !!}')
                        ->removeColumn('fname')
                        ->removeColumn('lname')
                        ->make();
    }

**Comment by yajra** [comment]
Yes, because `$start` is a fixed value. As I've said above, you need to do your math using `start` and `length` but again it would still be fixed so you would also need to include the record id or something for it to be unique.

**Comment by shijupoothotta** [comment]
I tried this. But sql error. I am using my_sql.
public function getData() {
        DB::statement(DB::raw('set @rownum=0'));
        $providers = Provider::select(['@rownum:=@rownum+1 row_num','fname','lname','email', 'type', 'status', 'created_at']);
        return Datatables::of($providers)
                        ->addColumn('slno','row_num',1)                
                        ->addColumn('fullname', function($model) {
                            return $model->fullname;
                        },2)
                        ->addColumn('Actions','Action Here')
                        ->editColumn('status', '{!! ucfirst($status) !!}')
                        ->removeColumn('fname')
                        ->removeColumn('lname')
                        ->make();
    }

**Comment by elbakly** [comment]
@shijupoothotta  passing variable by reference will solve the problem
```
$start=1;
            $employees->addColumn('slno', function ($employee) use (&$start) {
                return $start++;
            });
```

**Comment by genjerdotcom** [comment]
Just Try My code

Working perfectly for number rows.. great plugin Yajra by the way

`
$model = Model::select([DB::raw('@rownum  := @rownum  + 1 AS number')]);
$start  = $request->start;
$length = $request->length;
return DataTables::of($model)
->addColumn('number', function ($model) use ($start) {
	return $items->number+$start;
})
->make(true);
`

my code working perfec with row number paginate click.

**Comment by sujaypatel53** [comment]
> Just Try My code
> 
> Working perfectly for number rows.. great plugin Yajra by the way
> Set Model
> 
> `DB::statement(DB::raw('set @rownum=0'));`
> `$model = Model::select([DB::raw('@rownum := @rownum + 1 AS number')]);`
> 
> get request start and length
> 
> `$start = $request->start;`
> `$length = $request->length;`
> 
> `return DataTables::of($model)`
> `->addColumn('slno', function ($model) use ($start) { return $items->number+$start; })`
> `->make(true);`
> 
> my code working perfect with row number paginate click.


 $items->number ??
