### ISSUE TITLE
Datatables as a Service Implementation

### ISSUE THREAD

**Issue by Mylo-92** [yajra/laravel-datatables#500]
### Summary of problem or feature request

Good Day,

I find the "Datatables as a Service" option more useful in most of my cases. However, I am not too sure how to proceed when extending it to include, in this case, management options: e.g view/edit/delete columns. 

I tried implementing/modifying this [Example](http://datatables.yajrabox.com/collection/add-edit-remove-column). By adding:
**UsersDatable**
```
public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addColumn('action', function ($user) {
                return '<a href="#edit-user/'.$user->id.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
            })
            ->make(true);
    }
```
**UsersController**
```
public function index(UsersDataTable $dataTable)
    {
        return $dataTable->render('users');
    }

    public function getAddEditRemoveColumn()
    {
        return view('user_management.edit-user');
    }
```
**Users View**
```
$('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: 'http://localhost/project/public/edit-user/',
        columns: [
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
```

However to no avail, no column appears. How would I go about getting this right? 

### System details

- Operating System: OS X El Capitan 10.11.2
- PHP Version: 5.6.10
- Laravel Version: 5.1.33 (LTS)
- Laravel-Datatables Version: 6.10.1

Regards,

**Comment by yajra** [comment]
Were you able to see this [tutorial](http://datatables.yajrabox.com/service)? Please try to follow it and see how it works. Thanks!

**Comment by Mylo-92** [comment]
@yajra Yes, already implemented that in my project, for multiple entities. My issue is how to extend this implementation in include a new column containing e.g an edit/delete or view action/button

**Comment by Mylo-92** [comment]
Lastly, how does one go about excluding certain columns from the printing option without using javascript?

**Comment by Mylo-92** [comment]
Lastly how does one go about excluding certain columns from the print option and file output?

**Comment by vesper8** [comment]
@Mylo-92 just like you are using orderable and searchable, you can also use exportable and printable with true/false flags

**Comment by yajra** [comment]
@vesper8 suggestion should fix your issue. Thanks!
