### ISSUE TITLE
orderBy colunm id desc

### ISSUE THREAD

**Issue by phainv** [yajra/laravel-datatables#503]
Hi,
I want sort colum id desc ?
Plz help me
Thanks :)

**Comment by yajra** [comment]
Just use the `order` method on your javascript like below. Use the column index of id.

```js
$('table').DataTable({
    ...
    order: [ [0, 'desc'] ]
})

**Comment by phainv** [comment]
i want via sql eloquent. Cant u help me? :)

**Comment by ArtbyArjan** [comment]
Can you give us an example of your code?

Sorting in Eloquent is done with `->orderBy('id','desc')` or '->latest('id')`

**Comment by phainv** [comment]
But when out outside table then i sorting column is not working

**Comment by ArtbyArjan** [comment]
I believe using sorting in your eloquent overrides the sorting functionality in datatables.
At least, when I used it, sorting didn't work anymore.

But again, show us your code. We can help you better with an example of what you're trying to achieve.

**Comment by phainv** [comment]
thanks for the helper :)

**Comment by yajra** [comment]
@ArtbyArjan is correct that setting the order on your query manually will make the sorting not to work anymore. If you want to sort by ID by default, use the `order` that I suggested above. Else just click on ID header to trigger the sort functionality.

**Comment by devaescasio** [comment]
Yes @yajra and @ArtbyArjan you can use ->orderBy in Eloquent. However, by doing this will disable the ajax feature `<th>` class sorting. As tested by doing `$policies = Policy::query()->latest()` at PostDataTable.php. I think @phainv wanted to order by desc and likewise the `<th>` sorting feature.

**Comment by rafaelqm** [comment]
If you are using as a service, in the method html(), on parameters array use 
```
/**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->parameters([
                'order' => [
                    0, // here is the column number
                    'desc'
                ]
           ]);
```

**Comment by digitlimit** [comment]
How do you sort with a column that you don't wish to display on the table ?

**Comment by vp33722** [comment]
> If you are using as a service, in the method html(), on parameters array use
> 
> ```
> /**
>      * Optional method if you want to use html builder.
>      *
>      * @return \Yajra\Datatables\Html\Builder
>      */
>     public function html()
>     {
>         return $this->builder()
>             ->columns($this->getColumns())
>             ->parameters([
>                 'order' => [
>                     0, // here is the column number
>                     'desc'
>                 ]
>            ]);
> ```

thanks bro its working

**Comment by vp33722** [comment]
if you want to get code then plz reply me

**Comment by RayhanYulanda** [comment]
@rafaelqm How about ordering raw column?

**Comment by rafaelqm** [comment]
> @rafaelqm How about ordering raw column?

@RayhanYulanda do you mean that you have a raw query? Because works the same way, just put the name you give to the alias of the column.

**Comment by RayhanYulanda** [comment]
> > @rafaelqm How about ordering raw column?
> 
> @RayhanYulanda do you mean that you have a raw query? Because works the same way, just put the name you give to the alias of the column.

No, i mean raw column that generate button text. I need to search and order that column too
