### ISSUE TITLE
master-details-table search is broken since 6.x

### ISSUE THREAD

**Issue by ndum** [yajra/laravel-datatables#506]
### Summary of problem or feature request

Hi,
The search in the master-detail-table has stopped working since I upgraded from version 5.x to 6.x.
It throws an AJAX-Error.
The same error also exists in the official demo (http://datatables.yajrabox.com/eloquent/master)

If I use the version 5.x, it works flawlessly .

Can you fix that in the demo? many thanks  ;)

**Comment by yajra** [comment]
@ndum, thanks for reporting. Demo fixed by adding `searchable: false` on expansion column.
