### ISSUE TITLE
i get Cannot reinitialise DataTable error for all package samples

### ISSUE THREAD

**Issue by tux-world** [yajra/laravel-datatables#507]
hi all. i get error for all samples such as:

> DataTables warning: table id=users - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

sample code:

# php:
    public function data()
    {
        $users = User::select(['id','name','email','created_at','updated_at']);

        return Datatables::of($users)->make();
    }

# Route:
    Route::get('showAllTickets'  , 'ManageUserTicketsController@data');

# Javascript

    $(function() {
        $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '<?php echo url('showAllTickets'); ?>'
        });
    });

Html:
```
<table id="users" class="table table-hover table-condensed">
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Action</th>
    </tr>
    </thead>
</table>
```

**Comment by yajra** [comment]
Your table id is `users` but you select `users-table` on your js? Try using this:

```php
$(function() {
    $('#users').DataTable({
        processing: true,
        serverSide: true,
        ajax: '<?php echo url('showAllTickets'); ?>'
    });
});
```
