### ISSUE TITLE
how to use POST method with datatables as a service implementation?

### ISSUE THREAD

**Issue by vesper8** [yajra/laravel-datatables#508]
I am running into a "414 Request-URI Too Large" issue with a very large dataset.

And a suggestion made here https://datatables.net/forums/discussion/9454/414-request-uri-too-long-error-when-using-large-numbers-of-columns-and-performance-issue-s is to use the POST method by setting it using the sServerMethod parameter.

But I don't know how to set that with the "datatables as a service" implementation.

I have tried this way but that doesn't work

```
            ->parameters([
                'dom' => 'Blfrtip',
				'sServerMethod' => 'POST',
                'scrollX' => true,
                'buttons' => [
                    'create', 'csv', 'excel', 'pdf', 'print', 'reset', 'reload'],
            ]);
```

If you have any other tips on how to deal with this "URI too large" issue please let me know.

Many thanks

**Comment by yajra** [comment]
@vesper8, post method is not yet supported on service implementation. I already created an enhancement issue for this on https://github.com/yajra/laravel-datatables/issues/348.
