### ISSUE TITLE
About searching and ajax calling method

### ISSUE THREAD

**Issue by edlie** [yajra/laravel-datatables#51]
Sometimes when i abuse using search to much, the datatables response with 302, and the alert datatable error 1 popout..
Sometimes it's get unauthorized, alert datatable error 7 popout 
How to prevent these?

When i search in the forum, it stated that laravel doing it on purpose for security when there are to many same GET request happen
What happen if i change the AJAX method to POST? Will the datatable run smoothly..
thank you :)

**Comment by yajra** [comment]
I suggest you use the [fnFilterOnReturn](http://datatables.net/plug-ins/api/fnFilterOnReturn) plugin to lessen too much search request. Haven't used much the POST method so I am not so sure if it will run smoothly.

**Comment by edlie** [comment]
Already Tried the Post Method, the pagination bugging when changing page :(

---------------
Try to Use the plugins

var table = $('#element').DataTable({some data}).fnFilterOnReturn();

TypeError: $(...).DataTable(...).fnFilterOnReturn is not a function

Already Insert the script

**Comment by yajra** [comment]
For the plugin to work, you need to use `dataTable` and not `DataTable`. 

-----
For post method, will have to check it first cause I haven't personally used it much. Need to do more testing for it and already have a pending issue on it @ #49.

**Comment by yajra** [comment]
I just tried the POST method and it works. Maybe you haven't setup your CSRF protection?

Try using firebug/chrome dev tools and inspect your ajax request? You might be getting a TokenMismatchError.

**Comment by edlie** [comment]
I already try to use the plugins, it's solve the searching problem but when i'm using dataTable, there's so many function become error so i couldn't use it :(..i wonder if there's a plugin that have the same functionality that can be used with DataTable..

**Comment by yajra** [comment]
I think you can declare your js this way so that you can utilize the DT1.10 API approach.

```js
// use DT1.10 apprach
var table = $('#element').DataTable({some data});

// attach plugin
$('#element').dataTable().fnFilterOnReturn();
```

**Comment by yajra** [comment]
@edlie the JS above should work for you. Have tried and tested it. Closing this issue. Thanks!

**Comment by rogierborst** [comment]
Any clue on how to do this when using the new DataTables as a Service approach, including the HTML Builder?

**Comment by yajra** [comment]
default table id is `#dataTableBuilder`. Adding the same script should do the trick.

```js
// attach plugin
$('#dataTableBuilder').dataTable().fnFilterOnReturn();
```

**Comment by rogierborst** [comment]
I see.
Which brings me to the next point: what if I have multiple datatables on a single page?

**Comment by yajra** [comment]
In cases where we have multiple datatables, I suggest you write an external js and to not use the html builder. `html()` method on service approach is optional and is currently designed for single instance. You will still achieve the same results using the service though you have to write the table and scripts manually. This is what I also do on cases where I have master-details relationship table and/or complex datatables.

**Comment by gadius** [comment]
@mastrip2 Just nailed it; changed my initialization as follow.

var tableIndex=$('#tableIndex').DataTable({
"order": [[ 0, "asc" ]],
"aLengthMenu": [[5, 10, 25], [5, 10, 25]],
"iDisplayLength": 10,
"dateFormat": 'yyyy-mm-dd',
"processing": true,
"serverSide": true,
"ajax": {
'url': '{{route("clinics.api.laboratoryIndex")}}',
'type': 'POST',
'headers': {
'X-CSRF-TOKEN': '{{ csrf_token() }}'
}
},
"columns":[
{data: 'products', name: 'products'},

],
"columnDefs": [
{ "searchable": false, "bSortable": false, "targets": 0 }
],
language: {
"sProcessing": "Procesando...",
"sLengthMenu": "Mostrar MENU registros",
"sZeroRecords": "No se encontraron resultados",
"sEmptyTable": "Ningún dato disponible en esta tabla",
"sInfo": "Mostrando registros del START al END de un total de TOTAL registros",
"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
"sInfoFiltered": "(filtrado de un total de MAX registros)",
"sInfoPostFix": "",
"sSearch": "Buscar: ",
"sUrl": "",
"sInfoThousands": ",",
"sLoadingRecords": "Cargando...",
"oPaginate": {
"sFirst": "Primero",
"sLast": "Último",
"sNext": "Siguiente",
"sPrevious": "Anterior"
},
"oAria": {
"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
"sSortDescending": ": Activar para ordenar la columna de manera descendente"
}
}
});

Thank you fam
