### ISSUE TITLE
Error When Upgrading from v5.11 to v6.0

### ISSUE THREAD

**Issue by lawrence615** [yajra/laravel-datatables#510]
### Summary of problem or feature request

When I run 'composer require yajra/laravel-datatables-oracle:~6.0', I get the error;

 ' laravel/framework v5.0.33 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.'

I have mcrypt installed and composer is working well with other Laravel projects

### Code snippet of problem

>   Problem 1
>     - laravel/framework v5.0.33 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
>     - laravel/framework v5.0.33 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
>     - laravel/framework v5.0.33 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
>     - Installation request for laravel/framework == 5.0.33.0 -> satisfiable by laravel/framework[v5.0.33].

### System details

- OSX Yosemite Version 10.10.5
- PHP 5.6.19
- Laravel Framework version 5.0.33
- Laravel-Datatables Version 5.11

**Comment by yajra** [comment]
Hmm not sure about this one but I think this is not related to the package. Issue raised was on the framework itself.

Anyways, can you check if mcrypt is enabled on your php cli config file? Are you using homestead?

**Comment by lawrence615** [comment]
@yajra No am not using homestead. mcrypt is enabled in my php.ini and other mcrypt operations are fine

**Comment by yajra** [comment]
@lawrence615, the error above is not related to the package. Better ask on Laravel forums and related sites. Thanks!
