### ISSUE TITLE
Service injection difference

### ISSUE THREAD

**Issue by vkosachev** [yajra/laravel-datatables#511]
I have doubts about how to implement the simple inline example as a service:
1. What is a proper way to add custom columns?
2. How to customize column names when using the `html()` method in service? I mean the name that is displayed to the user

### Code snippet
I am adding a custom column like this:
```php
 public function getUsers(Request $request)
    {
        $users = User::all();
        return Datatables::of($users)
            ->addColumn('action', function ($user)
            {
                $data = [
                    'editRoute' => route("dashboard.users.index"),
                    'deleteRoute' => route("dashboard.users.index"),
                    'entity'    => $user
                ];
                return view('dashboard.partials.actions')
                    ->with($data);
            })
            ->make(true);
    }
```

### System details

- Ubuntu 14.04
- PHP 7.0.5
- Laravel 5.2
- Laravel-Datatables latest

**Comment by yajra** [comment]
> 1. What is a proper way to add custom columns?

You can use `addColumn` to add a custom column but you should also set that column as not orderable and searchable since it's not part of the query.

> 2. How to customize column names when using the html() method in service? I mean the name that is displayed to the user

Just set the title attribute like `'col' => ['title' => 'Custom Title']`.

**Comment by vkosachev** [comment]
Thx man.
