### ISSUE TITLE
Pass a field from the form to the controller for use in the eloquent query

### ISSUE THREAD

**Issue by arnoldjp57** [yajra/laravel-datatables#512]
### Summary of problem or feature request

How to pass a parameter to the controller with the ajax call

### Code snippet of problem

Modal ...

<div class="modal fade" id="modal-icd10-select">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Select ICD10 Code</h4>
      </div>
      <div class="modal-body">
        <table id="icdcs-table" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>Code</th>
              <th>Description</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
</div>

javascript ...
$(function() {
    $('#icdcs-table').DataTable({
      processing: true,
      serverSide: true,
      destroy: true,
      "pagingType": "simple",
      ajax: '{!! route('datatables_icdcs.data') !!}',
      columns: [{"visible": false,data: 'id',name: 'id'}, 
      {data: 'code',name: 'code',
        "fnCreatedCell": function(nTd, sData, oData, iRow, iCol) {
          $(nTd).html('<a data-dismiss="modal" href="#"' +
            ' onclick="fill_code(\'icdc\',\'' + oData.id + '\',\'' + oData.code + '\',\'' + oData.desc + '\')">' + oData.code + '</a>');
        }
      }, 
      {data: 'desc',name: 'desc'}, ]
    });
  });

Routes ...

Route::controller('datatables_icdcs', 'Odie\IcdcsController', [
    'anyData'  => 'datatables_icdcs.data',

Controller

public function index()
	{
		$folder = "icdc";
		return view('odie.icdc.index',compact('folder'));
	}
  
  /**
    * Process datatables ajax request.
    *
    * @return \Illuminate\Http\JsonResponse
    */
    public function anyData()
    {
      return Datatables::of(icdc::query())->make(true);
    }

### System details

The modal calls datatables and works perfectly (table with 80,000 rows is quick and searchable/sortable  ... I am able to select a specific record and return the details to my form and all is good :-) ... Just need to pass a parameter into the controller anyData() method to limit the query based on a field value selected by the user. As a new web developer, datatables is great ... Thank you for a very useful/powerful product

- Operating System
Ubuntu
- PHP Version
7.0
- Laravel Version
5.2.26
- Laravel-Datatables Version
latest ..... :-)

**Comment by yajra** [comment]
Follow this demo for ref: https://datatables.net/examples/server_side/custom_vars.html

**Comment by yajra** [comment]
And on your controller, just inject the `Request` class to access the custom vars value.

**Comment by arnoldjp57** [comment]
Hi 
When I add the $request in to the controller method 

public function anyData(TfrtFormRequest $request)

I get an error ... 
![image](https://cloud.githubusercontent.com/assets/12873055/14487331/4185a278-0162-11e6-90f5-c6b0407ba19f.png)

Here is my javascript
![image](https://cloud.githubusercontent.com/assets/12873055/14487465/e9abadb2-0162-11e6-9e60-5e2e7db9d1aa.png)

If I remove the $request, then the session works ... I just cant get my thtp variable in the controller

Here is the ajax call with the 2 fields I added _token and thtp

![image](https://cloud.githubusercontent.com/assets/12873055/14487429/bd31f2dc-0162-11e6-8ce3-0bd078806b78.png)

I added the "type":"POST" .... have been fiddling with the routes as well, but no sucess ...

I'm missing something basic in injecting the Request ....

**Comment by arnoldjp57** [comment]
Hi ... OK, I found my error ... The Request Object that I injected had rules defined ..... :) Working 100%
