### ISSUE TITLE
Hidden columns still appear in export

### ISSUE THREAD

**Issue by alex-LE** [yajra/laravel-datatables#513]
### Summary of problem or feature request

If some columns are hidden through column definition (to show/hide them on runtime), they are still exported to the excel file.
Isn't it better to hide them in the export too?

### Code snippet to FIX the problem

```php
protected function getColumnsFromBuilder()
    {
        $columns = new Collection();

        foreach ($this->html()->getColumns() as $column) {
            if (is_null($column->visible) || $column->visible == true) {
                $columns->push($column);
            }
        }

        return $columns;
    }
```

Should i create a PR for that?

**Comment by alex-LE** [comment]
Ok, i've found another issue with that, i show a column on runtime, which has the visible = false flag, it will not be visible in the excel file. So the excel export should also get a list of currently visible columns.

**Comment by yajra** [comment]
@alex-LE good point. Does the client side table tools works the same where hidden fields are not exported? If yes, then please do submit a PR. Will try to check it as soon as I can. Thanks!

**Comment by alex-LE** [comment]
@yajra I'm not sure, as i saw on some comments it seems that table tools and colvis are exporting all columns even if they are hidden in the frontend.

I got it working now, so my export shows the same columns as the frontend. Hidden columns are not getting exported.

**Comment by yajra** [comment]
@alex-LE if that is the case where hidden columns are exported too then I think we should not change the current behavior. Instead, I suggest you use `exportable => false` and `printable => false` to explicitly set it at runtime.
