### ISSUE TITLE
Searching Related Models

### ISSUE THREAD

**Issue by prolonginc** [yajra/laravel-datatables#515]
### Filter and export relationship is not working 

Hello Yajra, in an application that i have i am using the service provider implementation and i have two issues, 1 - the export does not export the related models using the hasOne relationship 
2- the searching mechanism is not filtering through the related models either. 

### Code snippet of problem

```php
  $parts = Part::select(['id','key'])->with(['people'=> function($query) {
            $query->select('key', 'people');

        }
        ]);```
-->

### System details

<!--
the query above executes and displays as desired however does not export or search properly. 

-->

- Operating System Mac OsX 10.11 
- PHP Version  5.6
- Laravel Version 5.1 
- Laravel-Datatables Version 6.4.1

**Comment by yajra** [comment]
@prolonginc, were you able to see this [relationship demo](http://datatables.yajrabox.com/eloquent/relationships)? If not, please check it for reference. 

BTW, i just recently updated that demo and noted to use `select('table.*')` by default since the records becomes intermittent if not specified.

```php
$posts = Post::with('user')->select('posts.*');
```

And lastly, be sure to include the related column on your select query for the relation to be loaded properly. Thanks!

**Comment by prolonginc** [comment]
thank you for the response i tried the demo you updated getting datatables error. is there a way to debug the json return / query in the service provider implementation for example  without the service provide and going by the eloquent way i used to access the route, and would be able to see whats going on now it just returns a  datatable view?

**Comment by prolonginc** [comment]
disregard my question about debugging i was missing the response from the dev tools in chrome i will debug and let you know thanks.

**Comment by ChaosPower** [comment]
@prolonginc are you still having issues? Will close after 5 days if this is already resolved.

**Comment by ChaosPower** [comment]
Please reopen if this is still an issue.
