### ISSUE TITLE
Set columns order at Controller

### ISSUE THREAD

**Issue by aleixfabra** [yajra/laravel-datatables#516]
We would like to refactor this:

```php
$roles = Role::join('role_translations', 'roles.id', '=', 'role_translations.role_id')
            ->select(['roles.id', 'role_translations.name', 'roles.created_at', 'roles.updated_at'])
            ->groupBy('roles.id');

/* $roles 
[  
   {  
      "id":1,
      "name":"Admin",
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49"
   },
   {  
      "id":2,
      "name":"User",
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49"
   }
]
*/

$datatables = Datatables::of($roles);
return $datatables->make();
``` 

Into this:

```php
$roles = Role::all();

/* $roles
[  
   {  
      "id":1,
      "deleted_at":null,
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49",
      "name":"Admin"
   },
   {  
      "id":2,
      "deleted_at":null,
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49",
      "name":"User"
   }
]
*/

$datatables = Datatables::of($roles);
return $datatables->make();
``` 

In order to avoid having to write those joins.

We also want to avoid to specify the column order in the view neither with Js nor HTML5 attributes.

So, we would like to set the column order in the Controller as you can do other operations like `addColumn()`, `removeColumn()` , etc.

Something like:

```php
$datatables = Datatables::of($roles)->orderColumns(...);
``` 

Is there any way to achieve this?

Many thanks!

P.S. thanks to @HarleyFuagras

### System details

- OSX
- PHP 5.5.23
- Laravel 5.2.x
- Laravel-Datatables ~6.0

**Comment by yajra** [comment]
@aleixfabra, you can use `order` method and manually write your desired ordering.

```php
    /**
     * Override default ordering method with a closure callback.
     *
     * @param \Closure $closure
     * @return $this
     */
    public function order(\Closure $closure)
```

**Comment by aleixfabra** [comment]
Thanks @yajra!

Could you give us an example?

**Comment by intrepidws** [comment]
Ooh, an example would be most helpful. I'm having the same issue.

**Comment by yajra** [comment]
A quick example would be:

```php
->order(function($query) use ($request) {
    if ($request->get('...column')) {
        $query->orderBy('col', $request->get('...direction'));
    }
})
```

**Comment by aleixfabra** [comment]
Hi @yajra!

I think I've not explained myself properly. What I want is to order the columns, not the records of this columns.

This:

```php
$roles = Role::all();

/* $roles
[  
   {  
      "id":1,
      "deleted_at":null,
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49",
      "name":"Admin"
   },
   {  
      "id":2,
      "deleted_at":null,
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49",
      "name":"User"
   }
]
*/

$datatables = Datatables::of($roles);
return $datatables->make();
```

Into this:

```php
$roles = Role::all();

/* $roles
[  
   {  
      "id":1,
      "name":"Admin",
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49",
      "deleted_at":null
   },
   {  
      "id":2,
      "name":"User",
      "created_at":"2016-04-11 17:07:49",
      "updated_at":"2016-04-11 17:07:49",
      "deleted_at":null
   }
]
*/

$datatables = Datatables::of($roles);
return $datatables->make();
```

Thanks!

**Comment by yajra** [comment]
@aleixfabra, sorry, I misunderstood the question. Anyways, since your using `make(false)`, the column order would rely on you selected field. Hence, I advise you select the columns and get all the records like:

```php
$roles = Role::select(['id', 'name', ...]);
```

**Comment by aleixfabra** [comment]
What I was asking is that:

If I don't use the `select` method, there's any way to select it using your Datatables methods?

Thanks!

**Comment by intrepidws** [comment]
What is the use case where you wouldn't be using the select method but what be OK using another method further down the chain?

**Comment by aleixfabra** [comment]
When I want to avoid making a join and select the fields by hand for example. I put an example at my first comment.

**Comment by ChaosPower** [comment]
@aleixfabra you may refactor you're output alternatively using transformers.
http://datatables.yajrabox.com/eloquent/transformer

**Comment by ChaosPower** [comment]
Closing discussion. You guys may chat with us at gitter https://gitter.im/yajra/laravel-datatables. Reopen issue if needed to have further discussions.
