### ISSUE TITLE
\Yajra\Datatables\Request ajax request check always returns false

### ISSUE THREAD

**Issue by moharrum** [yajra/laravel-datatables#517]
### ajax() always returns false, but when using \Illuminate\Http\Request returns true

I needed to check if the request was a result of an AJAX call before sending data back, when using \Yajra\Datatables\Request ajax() method always returns false.

### Code snippet of problem

`controller`:
```php
    public function getDatatable(\Moharrum\Posts\Services\ViewService $view, \Yajra\Datatables\Request $request)
    {
        return $view->getDatatable($request);
    }
```

`getDatatable()`:
```php
        if (!$request->ajax()) { // ---> this always returns false ?
            // If the request is not a result of an AJAX call
            // Terminate the app.
            return response('Unauthorized.', 401);
        }
        // code ...
```

### System details

- Fedora 23 Workstation
- PHP 5.6.20
- Laravel 5.2.29
- Laravel-Datatables v6.10.1

**Comment by yajra** [comment]
Maybe try getting the request instance via dataTable class and not via method injection?

```php
$dt = app('datatables');
$request = $dt->getRequest();
```

**Comment by moharrum** [comment]
Nice, it returns true now.

May I ask what is the difference?

Thanks
