### ISSUE TITLE
Moving column order, actions column

### ISSUE THREAD

**Issue by nWidart** [yajra/laravel-datatables#518]
Hello,

### Summary of problem or feature request

Currently, I have added an `actions` column at the end of the table with the service implementation, using the following code:

``` php
public function ajax()
{
    return $this->datatables
        ->eloquent($this->query())
        ->addColumn('action', 'user::admin.partials.installers_datatables_actions')
        ->make(true);
}

public function html()
{
    return $this->builder()
                ->columns($this->getColumns())
                ->addAction(['width' => '130px'])
                ->parameters([
                    'dom' => 'Bfrtip',
                    'buttons' => ['csv', 'excel', 'print', 'reset', 'reload'],
                ]);
}
```

However I would like to have the actions table as first column. Is there a way to choose the order ?

I tried using the third argument :

``` php
->addColumn('action', 'user::admin.partials.installers_datatables_actions', 0)
``` 
But this doesn't move the column first.

### System details

- Operating System: Ubuntu 14.04
- PHP Version: 7.0.5
- Laravel Version 5.1.34
- Laravel-Datatables Version: 6.10.1

Thank you!

**Comment by yajra** [comment]
When using `make(true)`, the order (3rd) parameter would be useless. You would need to arrange the columns on `getColumns()` method and remove `addAction()` like:

```php
public function html()
{
    return $this->builder()
                ->columns($this->getColumns())
                ->parameters([
                    'dom' => 'Bfrtip',
                    'buttons' => ['csv', 'excel', 'print', 'reset', 'reload'],
                ]);
}

function getColumns() {
  return [
    'action' => ['orderable' => false, 'searchable' => false],
    'id',
    ....
  ];
}
```

**Comment by nWidart** [comment]
I see, thank you for the reply.

in `getColumns` I've thus added:

```
'action' => ['orderable' => false, 'searchable' => false, 'width' => '130px'],
```

However on initial page load the first column, action, is still orderable: table header can be clicked.
But, when ordering another column, the order icon disappears from the actions column, and it can't be clicked anymore.

I'm guessing there is some option somewhere to choose which column is ordered on initial page load ?

**Comment by yajra** [comment]
Since by default, table will be sorted on 1st column. To override, just set the param like: 
```php
'order' => [[1, 'asc']]
```

**Comment by nWidart** [comment]
Ah yes of course 😄 .

Thank you for your support!
