### ISSUE TITLE
Bootstrap style is not working

### ISSUE THREAD

**Issue by nasirkhan** [yajra/laravel-datatables#519]
### Summary of problem or feature request

I want to use the Bootstrap3 style of Datatables. But i does not work with this package. added the `dataTables.bootstrap.min.css` but css does not change anything. 

With the same setting i tried datatables with table (without the package) and it worked perfectly.

is there any setting i missed to enable? can you please refer a doc? 

### System details

- Operating System: Windows 10
- PHP Version: 7
- Laravel Version: 5.1
- Laravel-Datatables Version

**Comment by yajra** [comment]
Are you setting the correct DT [dom](https://datatables.net/reference/option/dom) values that matches the bs3 styles? Are the appropriate table classes declared?

**Comment by nasirkhan** [comment]
I am using the Datatables as service. that is what i am asking where can i declare the table classes?

**Comment by yajra** [comment]
You can declare it via `dom` parameter or create a `js` file that extends that default DT options. BTW, i just remember that BS3 for DT comes with a js file and should be included before the table scripts.

Lastly, you can pass a class on the table using `$dataTable->table(['class' => 'table ....'])`.

**Comment by nasirkhan** [comment]
thank. it is working. :)

**Comment by capricorn05** [comment]
I am struggling to figure out how to get bootstrap 3.3.7 styles applied.  Any help would be appreciated.

**Comment by yajra** [comment]
@capricorn05 just make sure that DT bootstrap related assets are added after the main library.
