### ISSUE TITLE
Service scope getting current controller ID of child table

### ISSUE THREAD

**Issue by neverender24** [yajra/laravel-datatables#520]
### Summary of problem or feature request

I have a URI '/tests/1/relations'. I want to query all relations with test ID=1. Idk where to put it. So that i can do like this  **return $query->where('id', $id);** I created a scope like in the tutorial, but its pretty static, I want to make it something dynamic on my end.

**RelationsDatatables:**
```
    public function query()
    {

        $relations = Relation::query();

        return $this->applyScopes($relations);
    }
```

**RelationsDataTableScope:**
```
    /**
     * Apply a query scope.
     *
     * @param \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder $query
     * @return mixed
     */
    public function apply($query)
    {
        return $query->where('id', 1);
    }
```

**RelationsController:**
_I usually put my $id here like below. _
```
public function index(RelationsDataTable $dataTable, $id)
    {
        return $dataTable->addScope(new RelationsDataTableScope)->render('admin.relations.relations');
    }
```

Thanks :-D

**Comment by yajra** [comment]
@neverender24, since `id` is mostly common on most tables on laravel, hence you would need to specify the table name on your scope like `return $query->where('relations.id', 1);`. If you want the table name to be dynamic you can add a constructor then optionally pass the table name to be used.

```php
    public function __construct($table = null)
    {
        $this->table = $table;
    }

    public function apply($query)
    {
        $column = $this->getQualifiedColumnName();

        return $query->where($column, 1);
    }

    private function getQualifiedColumnName()
    {
        return $this->table ? $this->table . '.id' : 'id';
    }
```

You can use the snippet above by passing the table name in the scope constructor.

```php
return $dataTable->addScope(new RelationsDataTableScope('table_name'))->render('admin.relations.relations');
```

**Comment by neverender24** [comment]
Hi thank you for the reply, I want the actual value of the ID to be dynamic. return $query->where('test.id', $id);  Where $id = the ID from the URL /tests/1/relations

**Comment by yajra** [comment]
You can also pass the id value on the constructor or maybe get the request instance on the ioc. I think it's `app('request')`.

**Comment by neverender24** [comment]
hi I'm not sure what you mean, can you elaborate more on how to do this? thank you

**Comment by yajra** [comment]
On apply, you can use:
```php
 public function apply($query)
    {
        $column = $this->getQualifiedColumnName();
        $request = app('request');

        return $query->where($column, $request->get('id'));
    }
```

**Comment by yajra** [comment]
Or in the construct, 
```php
 public function __construct($id, $table = null)
    {
        $this->id = $id;
        $this->table = $table;
    }

 public function apply($query)
    {
        $column = $this->getQualifiedColumnName();

        return $query->where($column, $this->id);
    }
``

**Comment by neverender24** [comment]
Hi I have tested both methods, it does not carry out the construct id or the request id. but it seems both returns null upon testing.

**Comment by yajra** [comment]
It depends on your routes. Based on your example, the construct approach should fit your need.
```php
public function index(RelationsDataTable $dataTable, $id);
```

Double check your routes and make sure your get the proper id value.

**Comment by neverender24** [comment]
I have my route
`Route::resource('relations.test', 'RelationsController');`

In my controller 
```
class RelationsController extends Controller
{
    public function index(RelationsDataTable $dataTable, $id)
    {
        return $dataTable->addScope(new RelationsDataTableScope)->render('admin.relations.relations');
    }
}

```
In my scope table

```
    public function __construct($id)
    {
        $this->id = $id;
    }

    public function apply($query)
    {
        $request = app('request');

        return $query->where('id', $request->get('id'));
    }

```
This will give me error 

> Missing argument 1 for App\DataTables\Scopes\RelationsDataTableScope::__construct(), called in E:\xampp\htdocs\msap\app\Http\Controllers\RelationsController.php on line 13 and defined

**Comment by yajra** [comment]
You need to update your controller and pass the necessary parameters... 

```php
class RelationsController extends Controller
{
    public function index(RelationsDataTable $dataTable, $id)
    {
        return $dataTable->addScope(new RelationsDataTableScope($id))->render('admin.relations.relations');
    }
}

```

**Comment by neverender24** [comment]
That's it

> `  return $dataTable->addScope(new RelationsDataTableScope($id))`

Thanks kabayan :-D

**Comment by yajra** [comment]
Peenoise too? LOL good to hear that kabayan! 👍
