### ISSUE TITLE
Invalid parameter number on related models search ( possibly global scope issue)

### ISSUE THREAD

**Issue by hardikdangar** [yajra/laravel-datatables#523]
Hi,

I have issue with Datatable as service i am using service just described in,
http://datatables.yajrabox.com/eloquent/relationships.

What happens is i am able to get list view and sorting also works but during the search there is an issue with error,

SQLSTATE[HY093]: Invalid parameter number (SQL: select count(*) as aggregate from (select '1' as `row_count` from `onzup_cities` where (LOWER(`name`) LIKE %tt% or (select count(1) from `onzup_states` where `onzup_cities`.`states_id` = `onzup_states`.`id` and `name` like %tt% and `onzup_states`.`deleted` = 0) >= 1) and `onzup_cities`.`deleted` = ?) count_row_table)

I have two models, City and State with Globalscopes attached. and Datatable Service class. Datatable listing and sorting works but when i try to search it gives error described above. I believe issue is during the count query method globalscopes parameter is not attached correctly.

### Datatable service class

Datatable service class
```php
   public function query()
    {

        $models = City::with('state')->select('city.*');
        return $this->applyScopes($models);
    }

    private function getColumns()
    {
        return [
            'name',
            'state.name'
        ];
    }
```

### City Model

```php
class City extends Model
{
    protected $table = 'city';
    
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('city.deleted', function (Builder $builder) {
            $builder->where('city.deleted', '=', 0);
        });
    }
    public function state()
    {
        return $this->belongsTo(State::class,'states_id');
    }
}
```

### State Model

```php
class State extends Model
{
    protected $table = 'states';
    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('states.deleted', function(Builder $builder) {
            $builder->where('states.deleted', '=', 0);
        });
    }
    public  function  city()
    {
        return $this->hasMany(City::class,'states_id');
    }
    public function country()
    {
        return $this->belongsTo(Country::class,'countries_id');
    }
}
```

- Operating System : linux
- PHP Version : 7.0
- Laravel Version : 5.2.29
- Laravel-Datatables : v6.10.1

**Comment by yajra** [comment]
Thanks for reporting, the issue might be indeed connected on count and global scope binding. Will try to replicate this and let you know what I may find. If you can fix the issue, please do not hesitate to submit a PR. Thanks!

**Comment by hardikdangar** [comment]
Yajra,

I found even without scopes,
search doesn't work when we are using nested eager loading.

i.e.

```php

    public function query()
    {
        $users = City::with('states.countries')->select('cities.*');

        return $this->applyScopes($users);
    }

    private function getColumns()
    {
        return [
            'id',
            'name',
            'states.name',
            'states.countries.name',
        ];
    }

```
The above will produce datatable with sorting and listing working but search will fail with,


SQLSTATE[42S22]: Column not found: 1054 Unknown column 'states.countries_id' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `cities` where (LOWER(`id`) LIKE %c% or LOWER(`name`) LIKE %c% or (select count(1) from `states` where `cities`.`states_id` = `states`.`id` and `name` like %c%) >= 1 or (select count(1) from `countries` where `states`.`countries_id` = `countries`.`id` and `name` like %c%) >= 1)) count_row_table)

If you want i could share an example code here. I am trying to find solution of this. i believe only issue is with when we build count query in search.

**Comment by yajra** [comment]
Thanks for the feedback. Nested eager loading is not yet fully supported by the package along with belongsToMany relationship. 

Anyways, thanks for the hint. This info would really help when I had the chance to broaden the support for eager loading (nested and many-many relationships).

ATM, I suggest you use join statements while we work on the solutions for this. Thanks!

**Comment by yajra** [comment]
See #509 for updates on this same issue. Thanks!
