### ISSUE TITLE
icheck js plugin not work

### ISSUE THREAD

**Issue by cuneydtural** [yajra/laravel-datatables#524]
Icheck checkbox plugin not work after page click.

$('.datatable-wrap').dataTable( {
            "initComplete": function(settings, json) {
                $('input[type=checkbox]').iCheck({
                    checkboxClass: 'icheckbox_flat-red',
                    radioClass: 'iradio_polaris'
                });
            }
        } );

**Comment by yajra** [comment]
@cuneydtural, I think you should should draw callback and not the initComplete event.

**Comment by cuneydtural** [comment]
Thanks @yajra Problem is solved.

  $('#dataTableBuilder').on('draw.dt', function() {
            $('input[type=checkbox]').iCheck({
                checkboxClass: 'icheckbox_flat-red',
                radioClass: 'iradio_polaris'
            });
