### ISSUE TITLE
[strongly] add use responsive 

### ISSUE THREAD

**Issue by imagine10255** [yajra/laravel-datatables#526]
### Summary of problem or feature request

[strongly] add use responsive 

https://www.datatables.net/blog/2014-07-16

or How to Extend -> function table() 

### Code snippet of problem

`vendor/yajra/laravel-datatables-oracle/src/Html/Builder.php`
```php
public function table(array $attributes = [])
    {
        $this->tableAttributes = array_merge($this->tableAttributes, $attributes);

        //append start---------------------------------------
        $thead = [];
        foreach($this->collection->toArray() as $row){
            $thead[] = '<th '.$this->html->attributes($row).'">'.$row['title'].'</th>';
        }

        return '<table ' . $this->html->attributes($this->tableAttributes) . '><thead><tr>'.implode('',$thead).'</tr></thead></table>';
       //append end---------------------------------------
    }
```

### System details

- Operating System CentOS 6.7
- PHP Version 5.6
- Laravel Version 5.2.30
- Laravel-Datatables Version 6.10.1

**Comment by yajra** [comment]
@imagine10255, thank you for the suggestions! Will review and try to implement this. There is a change in behavior and this might be a breaking change so we need to be careful. Thanks!

**Comment by imagine10255** [comment]
Thanks for your response

**Comment by yajra** [comment]
@imagine10255, what are the attributes needed for the responsive extension? I think we need to limit it to only this attr: `['class', 'id', 'width', 'style']`? Let me know if I miss something. I just tested the snippet and I think we can implement this request.

```php
    public function table(array $attributes = [])
    {
        $this->tableAttributes = array_merge($this->tableAttributes, $attributes);

        $th = [];
        foreach ($this->collection->only(['class', 'id', 'width', 'style']) as $row) {
            $th[] = '<th ' . $this->html->attributes($row) . '">' . $row['title'] . '</th>';
        }

        $htmlAttr = $this->html->attributes($this->tableAttributes);

        return '<table ' . $htmlAttr . '><thead><tr>' . implode('', $th) . '</tr></thead></table>';
    }
```

**Comment by imagine10255** [comment]
### Code snippet of problem

`app/DataTables/Backend/System/UserDataTable.php`
```php
/**
     * Optional method if you want to use html builder.
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
            ->ajax(asset('smart/backend/system/user'))
            ->addHideId()
            ->addCheckbox()
            ->addColumn(['data' => 'name','data-class'=>'expand','title' => '使用者名稱'])
            ->addColumn(['data' => 'account', 'data-hide'=>'xs', 'title' => '使用者帳號'])
            ->addColumn(['data' => 'email', 'data-hide'=>'xs', 'title' => '電子郵件'])
            ->addEnable()
            ->addCreateAt()
            ->addUpdateAt()
            ->addAction()
            ->parameters();
    }
    }
```

```javascript
/**
<script>
var breakpointDefinition = {
            xs: 480,
            sm: 750,
            md: 970,
            lg: 1170
        };
</script>
```
reference http://192.241.236.31/themes/preview/smartadmin/1.8.x/ajax/index.html#ajax/datatables.html

So, I think need attr [data-class,data-hide]

data-class : [expand] open and close btn event column
data-hide : hide column on max @px

Thanks for your response,

**Comment by yajra** [comment]
Thanks for the feedback. I just updated the PR and added `data-class` and `data-hide` attributes. Will merge and release this PR later this week. If you can, please do test and verify that the PR works. 👍

**Comment by imagine10255** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by n6ither** [comment]
Is this working? I can't get it..
