### ISSUE TITLE
Display Row Number

### ISSUE THREAD

**Issue by shijupoothotta** [yajra/laravel-datatables#53]
I tried this. But sql error. I am using my_sql.
Displaying a serial number as the first column is required in most table. But not successfull, till now.

public function getData() {
DB::statement(DB::raw('set @rownum=0'));
$providers = Provider::select(['@rownum:=@rownum+1 row_num','fname','lname','email', 'type', 'status', 'created_at']);
return Datatables::of($providers)
->addColumn('slno','row_num',1)

->addColumn('fullname', function($model) {
return $model->fullname;
},2)
->addColumn('Actions','Action Here')
->editColumn('status', '{!! ucfirst($status) !!}')
->removeColumn('fname')
->removeColumn('lname')
->make();
}

**Comment by yajra** [comment]
I am not familiar with mysql row num so not sure about this. But try it first if it works on Laravel Eloquent without passing to Datatables. If your code works on Eloquent/Query Builder, I guess it should also work with the package.

**Comment by yajra** [comment]
Try something like this: However, this approach will use the Collection Engine and it's execution time will be slower than usual specially if you are using a large database.
 
```php
$providers = DB::table(DB::raw('providers, (SELECT @rownum := 0) r'))
    ->select('providers.*', DB::raw('@rownum := @rownum + 1 AS rank'))->get();

```

**Comment by yajra** [comment]
Or another better approach is to create a database view for your table where it includes the `rownum` function so that you can fully utilize the Eloquent's feature.

**Comment by shijupoothotta** [comment]
How can we sort Collections? The data returned perfect but in the data table data is displayed in the reverse order of 'Rank'.
->orderBy('rank','asc'); is not working since it is a collection.
Firebug show order => columns="0", dir='asc'.
But still data is displayed in the reverse order of RANK.

Repo:
public function getDTProviders() {
        DB::statement(DB::raw('set @rownum=0'));
        return Provider::select(DB::raw('@rownum := 0 r'))
                ->select(DB::raw('@rownum := @rownum + 1 AS rank'),'fname','lname','email', 'type', 'status', 'created_at')
                ->get();
    }

Controller:
    public function getData() {
        $providers = $this->provider_repo->getDTProviders();
        return Datatables::of($providers)
                        ->addColumn('fullname', function($model) {
                            return $model->fullname;
                        },2)
                        ->addColumn('Actions','Action Here')
                        ->editColumn('status', '{!! ucfirst($status) !!}')
                        ->removeColumn('fname')
                        ->removeColumn('lname')
                        ->make();
    }

**Comment by shijupoothotta** [comment]
Search is also not working. Is is due to the usage of collections.

**Comment by yajra** [comment]
I just tried your code and it does work on both Eloquent and Collection so I suggest you use Eloquent (without `get()`). Sorting also works as expected. However, search will not work because `rownum` is computed which means you have to override the default global filter for `rownum` and change to something that works using `filterColumn('rank','whereRaw','rank > 1')` **(adjust the sql to a working one)**. Or just make make the field not searchable by setting in you js `searchable: false`.

```php
        DB::statement(DB::raw('set @rownum=0'));
        $users = User::select(DB::raw('@rownum := 0 r'))
        ->select(DB::raw('@rownum := @rownum + 1 AS rank'),'users.*');

        return Datatables::of($users)->make(true);
```

**Comment by shijupoothotta** [comment]
Issues:
The sort column and search columns has to be turned off to avoid js errors.
Search on full name is working.
DB::raw('@rownum := @rownum + 1 AS rank') cannot be placed first in the query. Cannot figure out what is happening.
Anyhow things are better. 
Data Function:
public function getDTProviders() {
        DB::statement(DB::raw('set @rownum=0'));
        $providers = Provider::select(DB::raw('@rownum := 0 r'))
                        ->select('id',<b>DB::raw('@rownum := @rownum + 1 AS rank')</b>,'fname','lname','email', 'type', 'status', 'created_at');
        return Datatables::of($providers)
                        ->addColumn('fullname', function($model) {
                            return $model->fullname;
                        }, 2)
                        ->removeColumn('id')
                        ->removeColumn('fname')
                        ->removeColumn('lname')
                        ->editColumn('status', '{!! ucfirst($status) !!}')
                        ->addColumn('actions', function ($model) {
                            return '<a href="serviceprovider/' . $model->id . '/delete" class="edit-ad" title="delete " data-toggle="modal" 
                                            data-target="#myModal"><i class="fa fa-remove"></i></a>';
                        })
                        ->make();
    }
Javascript:
<script type="text/javascript">
        $(document).ready(function () {
        oTable = $('#table_id').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": "/serviceprovider/data",
        "columnDefs": [
            { orderable: false, targets: [1] },
            { "searchable": false, "targets": [0,1,6] }
        ]
});
        });
</script>

**Comment by yajra** [comment]
I just added a rownum demo on [datatables demo app](https://github.com/yajra/laravel-datatables-demo).  Kindly check it out to see how it was done. Below are some snippets used:

Controller:
```php
    public function getRowNumData(Request $request)
    {
        DB::statement(DB::raw('set @rownum=0'));
        $users = User::select([
            DB::raw('@rownum  := @rownum  + 1 AS rownum'),
            'id',
            'name',
            'email',
            'created_at',
            'updated_at']);
        $datatables = Datatables::of($users);

        if ($keyword = $request->get('search')['value']) {
            $datatables->filterColumn('rownum', 'whereRaw', '@rownum  + 1 like ?', ["%{$keyword}%"]);
        }

        return $datatables->make(true);
    }
```

```js
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ url("eloquent/row-num-data") }}',
        columns: [
            // or just disable search since it's not really searchable. just add searchable:false
            {data: 'rownum', name: 'rownum'},
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'}
        ]
    });
```

**Comment by yajra** [comment]
Does this works now? Please close issue if fixed! Thanks.

**Comment by shijupoothotta** [comment]
Yes, ii was working. There is another issue I want to bring into your notice. I am travelling. So please close it.

-----Original Message-----

**Comment by praveenpatel95** [comment]
When i am using groupby Rownnum not working correct

DB::statement(DB::raw('set @rownum=0'));
         $data = DB::table('patients')
         ->leftjoin('patient_logs','patients.id','=','patient_logs.patient_id')
            ->select([
                DB::raw('@rownum  := @rownum  + 1 AS rownum'),
                DB::raw("CONCAT(patients.name,' ',patients.sir_name) as fname"),
                'patient_logs.created_at','patients.patient_no','patients.mobile_no'])->groupBy('patient_logs.patient_id');

**Comment by pratik007kumar** [comment]
thanks you save my time

**Comment by nizamudeen003** [comment]
in yajra datatable how get last inserted data in first row...its comes from asc order.

**Comment by kingzamzon** [comment]
You should check the documentation on their website
[Index Column Yajra Datatable Documentation](https://yajrabox.com/docs/laravel-datatables/master/index-column)
