### ISSUE TITLE
Many-to-Many relationship is not searchable.

### ISSUE THREAD

**Issue by tepafril** [yajra/laravel-datatables#530]
Basically, I would like to say thank you for your effort to write this package which is really useful.

I have 3 tables which are many-to-many relationship.
-users
-user_role
-roles

I have tried addColumn('roles',function(){});. It totally worked, but unfortunately it's not searchable on the roles column.

Did I miss something? Or there is another to do so? Please instruct me.

**Comment by yajra** [comment]
@tepafril, can you try this PR and use [eager loading demo](http://datatables.yajrabox.com/eloquent/relationships) for ref?

On the other hand, you can also use the [join demo](http://datatables.yajrabox.com/eloquent/joins) for more stable solution. 

Thanks!

**Comment by tepafril** [comment]
The demo of eager loading is not many-to-many relationship. I think it's one-to-many relationship.

**Comment by yajra** [comment]
Yes, the demo is one-to-many but the concept is the same and you need to use PR #490. Forgot to add the link to the PR above.

**Comment by tepafril** [comment]
Work like a charm! Thank you so much 👍

**Comment by yajra** [comment]
@tepafril, what approach did you use? Join statements or using the PR? Will merge the PR if that fixes your issue. Thanks!

**Comment by tepafril** [comment]
@yajra here is my code snippet:
`
<?php
//controller
public function ApiGetAll(){
$transactions = Transaction::with(array('stocks','user'));
return Datatables::of($transactions)->make(true);
}
?>
`
`
// hidden the column and enable searching
// doing so to enable searching
columns: [
          { data: 'stocks.en_name', name: 'stocks.en_name',searchable:true },
]
`

**Comment by yajra** [comment]
I just merged and released PR #490 on v6.11.0. Thanks!
