### ISSUE TITLE
Setting columns content with a function causes a warning

### ISSUE THREAD

**Issue by murrant** [yajra/laravel-datatables#531]
### Summary of problem or feature request

Setting columns content with a function causes a warning.

```
function ($data) { ... } is of type object<Closure>, but the function expects a string.
```

Updating the phpdoc should fix the issue.
From:
`@param string $content`
to
`@param string|callable $content`

### Code snippet of problem

```php
$datatable->editColumn( 'column.name', function($data) { return 'prefix' . $data; } );
```

### System details

- Operating System: Gentoo
- PHP Version: 7.0.5
- Laravel Version: 5.2.30
- Laravel-Datatables Version: 6.10.1

**Comment by yajra** [comment]
@murrant thanks for reporting. I just submitted a PR to update the doc blocks. Will merge the changes later this week. 👍
