### ISSUE TITLE
Possible to access route parameters query() when running as service?

### ISSUE THREAD

**Issue by laf** [yajra/laravel-datatables#532]
### Summary of problem or feature request

I'd like to access the parameter of a route /search/{type} within my SearchDataTables classes query and html functions so that I can decide which data to use based on the url selected.

### Code snippet of problem

```php
Route::resource('search/{type}', 'General\SearchController');
```

Then something like:

```php
public function query()
{
    dd($type);
}
```

### System details

- CentOS 7
- 5.6.18
- 5.2
- v6.10.1

**Comment by yajra** [comment]
@laf, this is the approach I use when I want to pass a route variable in my dataTable class.

## Controller
```php
public function search($type, TypeDataTable $dataTable)
{
    return $dataTable->forType($type)->render('view.index');
}
```

## DataTable
```php
protected $type;

public function query()
{
    dd($this->type);
}

public function forType($type)
{
	$this->type = $type;

	return $this;
}
```

**Comment by laf** [comment]
Thanks so much for the quick response. This worked perfectly :)

Thank you also for such an amazing addition to Laravel and DataTables.
