### ISSUE TITLE
Column HTML Data Attributes

### ISSUE THREAD

**Issue by intrepidws** [yajra/laravel-datatables#536]
### Summary of problem or feature request

Is there a way to set HTML data attributes for a column? HTML data attributes can be used with DT as such: https://datatables.net/examples/advanced_init/html5-data-attributes.html

### System details

- Operating System: Ubuntu 14.04
- PHP Version: PHP 5.6.10
- Laravel Version: 5.0.35
- Laravel-Datatables Version: 6.10.1

**Comment by yajra** [comment]
I think you can use DT Row Options for this. See this [demo](http://datatables.yajrabox.com/eloquent/dt-row) for reference specifically this part:

```php
->setRowAttr([
  'color' => 'red',
])
```

**Comment by intrepidws** [comment]
Oh, very nice - for some reason I was thinking that this was used for CSS styles, not attributes. Thanks, this worked perfectly.

In hindsight though, I suppose that the HTML 5 data attributes in the URL that I referenced aren't actually very useful when you're using server side processing and AJAX. Oh well, at least I know how to do it.
