### ISSUE TITLE
Advance Where Clause

### ISSUE THREAD

**Issue by pyaesone17** [yajra/laravel-datatables#538]
### Summary of problem or feature request

Searching result show all the datas without respect the input when I use Laravel Advance Where Clauses. After applying advance where clause , Search box doesn't work and it shows all the data.

### Code snippet of problem
<pre>
<code>
->where(function($query) {
                            $query->where('voucher_details.status', '!=', 'pending');
                        })->orWhere(function($query) {
                            $query->where('voucher_details.shipping_option', 'standard')
                           ->where('voucher_details.shipping_option', 'free');
                        })
</code>
</pre>

**Comment by yajra** [comment]
Can you please paste your whole DT code? But afaics, these where clause looks fine.

**Comment by ChaosPower** [comment]
Closing inactive issue.
