### ISSUE TITLE
question , export to excel

### ISSUE THREAD

**Issue by rebornishard** [yajra/laravel-datatables#539]
### Summary of problem or feature request
Thanks for amazing package, i found excel config there

Is that possible to convert to excel with that setting ?
any explaination code sir ?

thank you

### System details

- Operating System Centos 7
- PHP Version 5.6
- Laravel Version 5.1
- Laravel-Datatables Version 6.11

**Comment by yajra** [comment]
The packages uses [Laravel-Excel](https://github.com/Maatwebsite/Laravel-Excel) and is loaded via IoC using `$excel = app('excel');`. In this regard, any configuration used by that package should be used by default. You just need to publish the excel config as stated in their docs like:
```php
php artisan vendor:publish --provider="Maatwebsite\Excel\ExcelServiceProvider"
```

**Comment by rebornishard** [comment]
@yajra thank you,
i'll make some test flight, do you have doc to integrate this one with datatables ?
thankyou

**Comment by yajra** [comment]
I am just using the basic function of laravel excel. You may use this [API Docs](http://yajra.github.io/laravel-datatables/api/class-Yajra.Datatables.Services.DataTable.html) as reference. Specifically the buildExcelFile method where the excel package was used.
http://yajra.github.io/laravel-datatables/api/source-class-Yajra.Datatables.Services.DataTable.html#222-237

And of course, use the [laravel excel](https://github.com/Maatwebsite/Laravel-Excel) package own documentation.
