### ISSUE TITLE
Datatable conflicts with bootstrap modal datatable

### ISSUE THREAD

**Issue by mraghayev** [yajra/laravel-datatables#541]
### Firstly, I appreciate you for nice tutorial, especially service implementation method is useful. While using service implementation method I found that there is a little conflict If I will use it together bootstrap modal DT.

Basically, I have two controllers: students and students lessons. Using basic service implementation method I can render all students as you suggest on your tutorial and it works pretty good. Using addColumn function I add html button for each student. Clicking to this button bootstrap modal dialog is opened with ajax call  and it calls again a new DT which fetches student's lessons. But second DT gives a conflict with first (students) DT. I see from debugbar that second DT uses first DT query() and ajax() method. I do both of them with service implementation method. If I will try to do this with basic query builder it will work perfect. I don't think that the problem is with my ajax. I assume that methods ```$this->query() ``` conflicts with each other after ajax request and that is why second DT uses first DT query.
Is there any way to fix this issue?

**Comment by yajra** [comment]
I think this [demo](http://datatables.yajrabox.com/services/two-datatables) contributed by user is somewhat close to what you are trying to achieve. It basically display two DT that uses service approach. Can you give it a shot to get a hint on how it works? The idea is to create a controller and DT class for each table you need.
