### ISSUE TITLE
Edit column: access row being looped on

### ISSUE THREAD

**Issue by nWidart** [yajra/laravel-datatables#542]
Hello,

### Summary of problem or feature request

I have a table, using the service setup. On this table I would like to add a column, which will call the presenter to display some data on the column.

For this I added the following line on the `getColumns()` method:

```
'type' => 'type',
```
Which doesn't exist on the model, thus fails however, I then edit the column to do my custom logic:

``` php
public function ajax()
{
    return $this->datatables
        ->eloquent($this->query())
        ->addColumn('action', 'user::admin.partials.installers_datatables_actions')
        ->editColumn('type', '{{ $? }}')
        ->make(true);
}
```

So my question here is: How can I access the row, so I can call `$row->present()->someMethod` :

``` php
public function ajax()
{
    return $this->datatables
        ->eloquent($this->query())
        ->addColumn('action', 'user::admin.partials.installers_datatables_actions')
        ->editColumn('type', '{{ $row->present()->someMethod }}')
        ->make(true);
}
```

`$row` is not defined sadly, and I see all properties are getting exploded into their own variable. I'm thus wondering how I can still access the row being looped over.

### System details

- Operating System: Ubuntu 14.04
- PHP Version: 7.0.5
- Laravel Version 5.1.34
- Laravel-Datatables Version: 6.10.1

**Comment by mraghayev** [comment]
As I understand you want to access to the details of rows while in loop. You can do this easily, using edit column  like below:

```
public function ajax()
{
    return $this->datatables
        ->eloquent($this->query())
        ->addColumn('action', 'user::admin.partials.installers_datatables_actions')
            ->editColumn('type', function ($row) {
                return $row->present()->someMethod;
            })
        ->make(true);
}
```

**Comment by yajra** [comment]
You need to use a closure if you want to access the row:

```php
->editColumn('type', function($row){
  return $row->present()->someMethod;
})
```

**Comment by nWidart** [comment]
Awesome thank again! 😄 

I tried the `addColumn`, and removing the definition in getColumns, however that does not add the type column.
