### ISSUE TITLE
[7.0] Make Engines Pluggable

### ISSUE THREAD

**Issue by cirdog** [yajra/laravel-datatables#544]
### Summary of feature request

I tried extending the engines because I was building the "server-side index column" myself, but it was too tedious sorting through all those layers of instantiations. Even though it's already pretty organized, I just cannot find a straighforward way to override the BaseEngine from which the 3 engines descend.

I suppose I can extend the ServiceProvider as a start, but then I still need to mod a bunch of classes just to get to BaseEngine's getProcessedData(). And by overriding it then I can put the $this->request['start'] into the DataProcessor and count the index from there.

If I'm mistaken and there is a better way to do it (Transformer?), please kindly share. I'm pretty new to Laravel, thanks!
### Code snippet of feature request

``` php
$this->app->singleton('datatables', function () {
    $engines = [
        'eloquent' => App\Datatables\Engines\MyEloquentEngine::class,
    ];
    // But then how to override BaseEngine??

    return new Datatables($this->app->make(Request::class), $engines);
});
```

And if my server-side index-column is successful, I will make a PR. And I bet it's also trivial for the Author to add this. The client-side index-column just doesn't cut it, not to mention that it doesn't work for SSP.

**P.S.**
Please also make these 3 methods (isLumen(), registerRequiredProviders(), registerAliases())  "protected" instead of "private", otherwise we cannot subclass the ServiceProvider easily. Thanks.
### System details

- Operating System
- PHP Version: 5.6.20
- Laravel Version: 5.2.30
- Laravel-Datatables Version: 6.11.0

**Comment by cirdog** [comment]
I guess before the day when every key component of this package becomes "pluggable", I'll try to modify the code and make a PR, it's more direct than subclassing the seemingly impossible.

**Comment by cirdog** [comment]
Actually, to achieve full pluggability, I suggest that we move all the "service registrations" to here, where the main singleton registers.

```php
 $this->app->singleton('datatables', function () {

	// Processors
	$this->app['datatables.processor.data'] = ....
	$this->app['datatables.processor.row'] = ....
	// Engines
	$this->app['datatables.engine.eloquent'] = ....
	$this->app['datatables.engine.query'] = ....
	$this->app['datatables.engine.collection'] = ....
	// HTML
	$this->app['datatables.html'] = ....
	// Excel
	$this->app['datatables.excel'] = ....
	// Builder
	$this->app['datatables.builder'] = ....

	return new Datatables($this->app->make(Request::class));
});
```
Make them all singletons shared under the Application, then it's reusable besides it's pluggable, refactor away redundant instantiations like:

```php
public static function of($builder)
{
	$datatables = app('Yajra\Datatables\Datatables');  // becomes $this->app['datatables']
	$datatables->builder = $builder;

	if ($builder instanceof QueryBuilder) {
	    $ins = $datatables->usingQueryBuilder($builder);
	} else {
	    $ins = $builder instanceof Collection ? $datatables->usingCollection($builder) : $datatables->usingEloquent($builder);
	}

	return $ins;
}

public function __construct(/*Datatables $datatables,*/ Application $app, Factory $viewFactory)
{
	// $this->app = $app;
	//$this->datatables  = $datatables; // $this->app['datatables']
	$this->viewFactory = $viewFactory;
}
```
Surely if having them as singletons has side-effect, maybe there are other ways to do it. But I suppose that it's one way of doing it based on what I saw in other packages' service provider.

Just wild suggestions, if it's wrong please kindly bear with me.

**Comment by yajra** [comment]
@cirdog, thanks for bringing this up. I was actually thinking of this way back but can't figure out yet how to start the structure properly. If you can, please do submit a PR. This feature will be a good candidate maybe for a major bump v7.

**Comment by yajra** [comment]
I just released v6.11.1 where private methods are converted to protected as requested. Thanks!

**Comment by yajra** [comment]
@cirdog I just made an attempt to make the package pluggable. If you can, any assistance/testing would be appreciated. Upcoming version 7 is available at [master](https://github.com/yajra/laravel-datatables/tree/master) branch. 

BTW, I tried to implement some of snippets you provided here. Thanks a lot!

**Comment by yajra** [comment]
Implemented on master/v7 branch. See [docs](https://yajrabox.com/docs/laravel-datatables/master/general-settings#engines) for the proposed implementation. Basically, plugging of engines would be done via the config file. 

Let me know if you have something better in mind. Thanks!
