### ISSUE TITLE
issue with internet explorer export 

### ISSUE THREAD

**Issue by prolonginc** [yajra/laravel-datatables#545]
i have the datatables setup and working on all of the browsers the only issue i have is that the export button for csv and excel tajes you to a page not found on IE  it works okay on chrome and firefox. tried from 5 different machines and they are all failing. this page cannot be displayed error.

i am using the service provider implementation. 
- Operating System
- PHP Version 5.6
- Laravel Version 5.1 
- Laravel-Datatables Version 6.4.1

**Comment by yajra** [comment]
Oh the friendly IE. I am using mac and may not be able to try and replicate this atm. Can you double check or paste the url generated when doing an export? My guess is the js builds wrong export url when using IE.

**Comment by prolonginc** [comment]
Yu gotta Love IE, im on a mac too but some of the users are forced to use IE, so heres the url that it tries to access : 
websiteurl/dataview?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=part.id&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true  and it repeats that for the rest of the columns 

Thank you in advance

**Comment by yajra** [comment]
It's been a while but this should be fixed now using this work around:

https://github.com/yajra/laravel-datatables-buttons/pull/24
https://github.com/yajra/laravel-datatables-html/pull/13

Thanks!
