### ISSUE TITLE
Undefined index: columns

### ISSUE THREAD

**Issue by Wit3** [yajra/laravel-datatables#55]
Hi, when i try to implement controller / view example i had this error in my controller.
<addr>
ErrorException in BaseEngine.php line 968: Undefined index: columns

    in BaseEngine.php line 968
    at HandleExceptions->handleError('8', 'Undefined index: columns', '/Users/XXX/Sites/YYY/vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Engine/BaseEngine.php', '968', array('input' => array())) in BaseEngine.php line 968

This is my function in Controller

<addr>

    public function data()
    {

        $users = User::select([
            'users.id',
            'users.name',
            'users.email',
            \DB::raw('count(posts.user_id) as count'),
            'users.created_at',
            'users.updated_at'
        ]);

        return Datatables::of($users)->make(TRUE);
}

if only i try to call route i get the previous error! why?

PS: i had the <addr>"yajra/laravel-datatables-oracle": "dev-master", version in my composer.json
thanks for help

**Comment by yajra** [comment]
duplicate. please see #39

**Comment by yajra** [comment]
@Wit3 FYI: I suggest you use the tagged version because I used dev-master for testing and it's unstable. Use `~5.0` instead. Thanks!
