### ISSUE TITLE
Pass variable to view from controller

### ISSUE THREAD

**Issue by smccoy78** [yajra/laravel-datatables#550]
### Summary of problem or feature request

Is it possible to pass a variable to the view before datatables details call is made and pass that variable in the datatables ajax call?  When I try to pass a variable to the initial details view I now get MethodNotAllowedHttpException. If I do not pass the variable the page loads but I do not have the id I need. Here is an example of what I want to do:

### Code snippet of problem

```php
public function details( $id )
{
     return view( 'details', compact('id');
}

public function getDetailsData()
{
     $details = Details::where('id', '=', Input::get('id'))->get();

     return Datatables::of( $details )->make( TRUE );
}
```
In View:
```javascript
$('table').DataTable(
{
     serverSide: true,
     ajax: {
          url: '{!! route('details::getdetailsdata') !!}',
          data: function(d) {
               d.id = {!! $id !!};
          }
     },
     columns: [ column info here ],
}
```

### System details

- Ubuntu Server 14.04
- PHP Version 5.5.9
- Laravel Version 5.2
- Laravel-Datatables Version 6.10.1

**Comment by smccoy78** [comment]
Apparently, it works just the way I posted.

**Comment by punitakathiriya** [comment]
Its Not Working occur this type of  Errors.
"DataTables warning: table id=authorozation - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3"
