### ISSUE TITLE
FatalErrorException in EloquentEngine.php line 22: Call to a member function getQuery() on a non-object

### ISSUE THREAD

**Issue by thom7kick** [yajra/laravel-datatables#551]
### i cant export my data table 

how can i export the my data tables.

```php
public function query()   {
	$users = User::select();
	if ($this->request()->ajax() && $this->request()->wantsJson()) {
	    $mother = new User();
	    $mother = $mother->generalReport();
        return $this->applyScopes($mother);
 	}
 }
```

**Comment by yajra** [comment]
If you want export to work, then you need to use the code like on this [demo](http://datatables.yajrabox.com/services/basic).

**Comment by thom7kick** [comment]
@yajra thank you i had something like this in my query :   
`public function query()
    {

        if ($this->request()->ajax() && $this->request()->wantsJson()) {
            $mother = new User();
            $mother = $mother->generalReport();

            return $this->applyScopes($mother);

        }

    }`

My code is like this now: 
`public function query()
    {

            $mother = new User();
            $mother = $mother->generalReport();

            return $this->applyScopes($mother);


    }`

after removing the validation of `$this->request()->ajax() && $this->request()->wantsJson()` now i am not getting the error: `Call to a member function getQuery()`
