### ISSUE TITLE
Is this the correct way to enable autoPrint

### ISSUE THREAD

**Issue by Mylo-92** [yajra/laravel-datatables#555]
### Summary of problem or feature request
Trying to implement autoPrint, as such I am not too sure that my syntax and location of parameter is correct.

### Code snippet of problem
->parameters([
                 'dom' => 'Bfrtip',
                 'buttons' => ['csv', 'excel', 'extend' => 'print','autoPrint' => true,'reload'],
             ]);

### System details

- Operating System: OS X El Capitan 10.11.2
- PHP Version: 7.0.0
- Laravel Version: 5.1.33 (LTS)
- Laravel-Datatables Version: 6.10.1

Kind Regards,

**Comment by yajra** [comment]
I haven't use autoPrint yet but based on this [link](https://datatables.net/extensions/buttons/examples/print/autoPrint.html), I think the code should be something like:
```php
->parameters([
  'dom' => 'Bfrtip',
  'buttons' => [
    'csv', 
    'excel', 
    ['extend' => 'print','autoPrint' => true], // should be in array
    'reload'],
]);
```

**Comment by Mylo-92** [comment]
Apologies for the delayed response, waited to see if anyone else had info on the query. Unfortunately that syntax still did not work, even wrapping "print" and "autoPrint" in separate arrays does not work. Will leave open for a few more days and close if nothing new pops up and cause it is not deal breaker.

Regards,

**Comment by yajra** [comment]
@Mylo-92 were you able to resolve this issue? Please re-open if needed. Thanks!

**Comment by setiawans** [comment]
I have the same problem. 
I used your example code in above but still did not work.

please se this example from datatables [link](https://datatables.net/extensions/buttons/examples/initialisation/export.html)
if i click print button will showing page and popup both.
please help me. Thank you.
