### ISSUE TITLE
Datatables Service. Is Posible remplace to DB Collection?

### ISSUE THREAD

**Issue by alejandri** [yajra/laravel-datatables#558]
I want use Db table collection clauses in Datatables Service implementation

```
    public function query()
    {
        $posts = Post::query();
        return $this->applyScopes($posts);
    }
```

remplce like this before added this lines 

 ```
   use DB;
   public function query()
    {
        $posts = DB::table('posts')->where('id', '>', '1')->get();
        return $this->applyScopes($posts);
    }

```

- Operating System Win7 Xampp 3.2.1
- PHP Version 5.6
- Laravel Version 5.2
- Laravel-Datatables Version 6

**Comment by yajra** [comment]
Yes, it's possible just like the way you posted on your code. However on `ajax` method, you need to use `collection` instead of eloquent like:
```php
    public function ajax()
    {
        return $this->datatables
            ->collection($this->query())
            ->make(true);
    }
```

**Comment by alejandri** [comment]
Thanks yajra. It is great repo. I use it for many projects
