### ISSUE TITLE
export to PDF does not work

### ISSUE THREAD

**Issue by rongxingsun** [yajra/laravel-datatables#561]
export to PDF does not work

**Comment by yajra** [comment]
What error did you received? 

Anyways, double check your server resources and make sure you have enough memory limit to process the export request. Exporting may do fail on large datasets.

**Comment by rongxingsun** [comment]
like this http://datatables.yajrabox.com/services/basic

**Comment by jpkontreras** [comment]
Hello. I have the same problem . I checked the memory and scriptTimeout configuration on my server. Im having a `ERR_CONNECTION_RESET ` . maybe i have to change something in laravel ? Thanks!

**Comment by yajra** [comment]
Yes, it seems like the demo to export pdf is not working. But as far as I know, this is due to my server resources limitation.

On the other hand, I just created a [PR](https://github.com/yajra/laravel-datatables/pull/582) to enhance the export to pdf function using `laravel-snappy`. Can you please check it out if it works for you guys? Thanks!

**Comment by jpkontreras** [comment]
Hello again. I did all the above and im getting this error. 

```
The exit status code '1' says something went wrong:
stderr: "System cannot find specified route  
"
stdout: ""
command: /usr/local/bin/wkhtmltopdf --lowquality --margin-bottom "10mm" --margin-left "0" --margin-right "0" --margin-top "10mm" --orientation "landscape" --no-outline "C:\Users\patri\AppData\Local\Temp\knp_snappy574d1482a7a026.57878404.html" "C:\Users\patri\AppData\Local\Temp\knp_snappy574d1482a83bd8.42876022.pdf".
```

Seems like is searching through my OS . 

Those lines are getting errors with my ide ( PHPSTORM 2016.1) 

$data   = $this->getDataForPrint();

return $snappy->loadView($this->printPreview, compact('data'))

The error is `Member has protected access`

That's IT

**Comment by yajra** [comment]
Oh yes, you also need to install [wkhtmltopdf](http://wkhtmltopdf.org/downloads.html) for it to work. It is part on `laravel-snappy` installation process. I just tried this with thousand of records and seems to work better than using `laravel-excel` export to pdf function.

**Comment by rongxingsun** [comment]
export to pdf is Chinese garbled

**Comment by yajra** [comment]
Better exporting of PDF via laravel-snappy was released on v6.15.0. See PR https://github.com/yajra/laravel-datatables/pull/626 for more info. Thanks!

**Comment by Sarmed-armis** [comment]
Dear's i have same issue when try to export PDF, it's just reload page !

**Comment by Makaveli255** [comment]
> Oh yes, you also need to install [wkhtmltopdf](http://wkhtmltopdf.org/downloads.html) for it to work. It is part on `laravel-snappy` installation process. I just tried this with thousand of records and seems to work better than using `laravel-excel` export to pdf function.

hello @yajra  i had the same problem in pdf, and excel i was able to solve in pdf using wkhtmltopdf but in excel still get this error "RuntimeException
Directory "C:\Users\MMATHA~1\AppData\Local\Temp" was not created"
