### ISSUE TITLE
addRowAttr not working when using datatable as a service

### ISSUE THREAD

**Issue by kife-design** [yajra/laravel-datatables#563]
Hello,

I'm using the datatable as a service feature and i would like to add an onclick to the TR but i cant get it to attach. This is what i'm doing in my Datatable Class:

```php
public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->addRowAttr('onclick', function($customer) {
                return 'customers.editCustomer(' . $customer->id . ')';
            })
            ->make(true);
    }
```

Am i doing something wrong here?

**Comment by yajra** [comment]
Hmm, AFAIK `addRowAttr` does not support closure and only accepts a string value like:
```php
->addRowAttr('attr', 'value')
```

**Comment by kife-design** [comment]
Hey, 

take a look at example 6 on the following page: https://github.com/yajra/laravel-datatables/wiki/Examples

```
 ->setRowAttr([
        'color' => 'data',
        'closure' => function($user) {
            return $user->name;
        },
        'blade' => '{{ $name }}'
        ])
```

and keep up the good work btw!

**Comment by yajra** [comment]
Oh good spot.. memory gap there.. But still it will return a string value so your onclick function will still not work. You to manually bind it on draw event I guess.

**Comment by yajra** [comment]
Issue should be implemented on js file. Thanks!
