### ISSUE TITLE
mistakes in examples

### ISSUE THREAD

**Issue by salarAsadi** [yajra/laravel-datatables#564]
I was reading the Examples page  at 
https://github.com/yajra/laravel-datatables/wiki/Examples
I tried the code in "Example 4" and I found syntax errors in it.

this line of code
        ->editColumn('created_at', function($data){ $data->created_at->toDateTimeString() })
must be changed to this
        ->editColumn('created_at', function($data){ return $data->created_at->toDateTimeString(); })

**Comment by yajra** [comment]
Thanks for reporting. Wiki updated/fixed. 👍

**Comment by salarAsadi** [comment]
you forgot the ";"
update it again.
