### ISSUE TITLE
->add_column('delete').. breaks with Laravel 5.2.32

### ISSUE THREAD

**Issue by dennisbruinen** [yajra/laravel-datatables#565]
### Summary of problem
On May the 17th Laravel released 5.2.32. After updating I noticed a new problem in combination with this package. If you use the method add_column() with the name 'delete' Datatables will return an error and the first record in the collection will be deleted (!). 

A screenshot of the given error:
![datatables-bug-screenshot](https://cloud.githubusercontent.com/assets/6872354/15390020/d39830b8-1db9-11e6-905c-006cb85c736d.PNG)

### Code snippet of problem
```php
public function getIndex()
{
    if( Request::ajax() )
    {
        $entities = Entity::select( ['entity.id','entity.varchar','entity.date_picker','entity.is_active'] );
        return Datatables::of( $entities )
        ->add_column('delete', '{!! Form::delete( URL::route( "admin.entity.destroy", $id, false ), $id, $varchar ) !!}')
        ->make();
    }
        
    return view('admin.entity.index');
}
```

If we use 
```php
        ->add_column('x', '{!! Form::delete( URL::route( "admin.demo-single.destroy", $id, false ), $id, $varchar ) !!}')
```
instead, everything works fine.

### System details
- Laravel Version 5.2.32
- Laravel-Datatables Version v6.11.2

**Comment by rianne-o** [comment]
+1

**Comment by ArtbyArjan** [comment]
We are experiencing the same problem!

**Comment by yajra** [comment]
Thanks for reporting. Will try to review this as soon as I can. But if you guys can, please do submit a PR to fix this? Thanks!

**Comment by yajra** [comment]
Guys, what `laravel-form` package are using? It seems like `Form::delete` does not exists on Collective Forms package?

**Comment by yajra** [comment]
Anyways, I tried adding a delete column and seems to work fine for me. BTW, sorry for the late response:

```php
            ->addColumn('delete', function($user) {
                return '<button class="btn btn-xs btn-danger btn-delete">Delete</button>';
            })
```

**Comment by dennisbruinen** [comment]
Hi @yajra thanks for your reply! The `Form::delete` we use is a self-built macro for adding a simple form with button to make deleting easy. However, if I try `->addColumn()` or `->add_column()` with as parameter just a simple string or your example function + returning HTML, I still get the same issue.

I get the same error and the first records gets deleted.

Also this issue doesn't occur when using Laravel 5.2.31.

**Comment by yajra** [comment]
Guys, I just tested this again on `Laravel Framework version 5.2.39` and `Laravel Framework version 5.1.40 (LTS)` and seems to work fine with me. Maybe upgrading to latest version of the framework will fix the issue?

Example response from my test:
```json
"draw": 1,
	"recordsTotal": 1,
	"recordsFiltered": 1,
	"data": [{
		"id": 1,
		"category_id": "2",
		"title": "<a href=\"http:\/\/platform.dev\/administrator\/articles\/1\/edit\">ASd<\/a>\n<small>(Alias: asd)<\/small>\n<br>\n<small>Category: Uncategorized<\/small>",
		"alias": "asd",
		"author_alias": null,
		"blade_template": null,
		"body": "<p>asd<\/p>\r\n",
		"publish_up": null,
		"publish_down": null,
		"parameters": "{\"meta_description\":\"\",\"meta_keywords\":\"\",\"key_reference\":\"\",\"content_rights\":\"\",\"external_reference\":\"\"}",
		"order": "1",
		"hits": "<span class=\"label bg-purple\">13<\/span>",
		"published": "<span class=\"badge bg-green\">Yes<\/span>\n",
		"authenticated": "<span class=\"badge bg-red\">No<\/span>\n",
		"featured": "0",
		"authorization": "can",
		"created_by": "1",
		"updated_by": "1",
		"created_at": "2016-07-05 17:32:12",
		"updated_at": "2016-07-08 01:43:15",
		"category_title": "Uncategorized",
		"action": "<div class=\"btn-group\">\n    <a href=\"http:\/\/platform.dev\/administrator\/articles\/1\/edit\"\n       class=\"btn btn-xs btn-default\"\n       data-toggle=\"tooltip\"\n       data-title=\"Edit\"\n       data-container=\"body\"\n    >\n        &nbsp;&nbsp;<i class=\"fa fa-pencil\"><\/i>&nbsp;&nbsp;\n    <\/a>\n    <\/a>\n    <button data-remote=\"http:\/\/platform.dev\/administrator\/articles\/1\"\n            class=\"btn btn-xs btn-delete btn-danger\"\n            data-toggle=\"tooltip\"\n            data-title=\"Delete\"\n            data-container=\"body\"\n    >\n        &nbsp;&nbsp;<i class=\"fa fa-trash-o\"><\/i>&nbsp;&nbsp;\n    <\/button>\n            <button data-ajax=\"http:\/\/platform.dev\/administrator\/articles\/1\/publish\"\n                class=\"btn btn-warning btn-xs\"\n                data-toggle=\"tooltip\"\n                data-title=\"Unpublish\"\n                data-container=\"body\"\n        >\n            &nbsp;&nbsp;<i class=\"fa fa-close\"><\/i>&nbsp;&nbsp;\n        <\/button>\n    <\/div>\n",
		"delete": "test",
		"plain_title": "ASd"
	}],
```

Anyways, I just can't reproduce the issue on my side. Can please someone send a PR for possible fix? Thanks!

**Comment by yajra** [comment]
Ok, I was able to replicate the issue. It seems like when you combine `editColumn` with blade contents and `addColumn('delete', ...)` triggers this issue. Working on it!

**Comment by ArtbyArjan** [comment]
Awesome job @yajra 
My programming knowledge isn't sufficient enough yet to make a PR and fix issues, so I'm glad you've managed to reproduce the problem and fix it!
