### ISSUE TITLE
Search not working in HasOne relationship.

### ISSUE THREAD

**Issue by mortenlandmark** [yajra/laravel-datatables#567]
Ok I have tried for a while, searched extensively, please help me out.

The table displays correct, but search and sort is only working for rones.RNo, not ords.OrdNo.

So search and sorting is only working for one table. why? Whyyy?

Ord Model:
public function rones()
    {
        return $this->hasOne('App\Rone', 'RNo', 'OrdNo');
    }

Rone Model:
    public function ords()
    {
        return $this->belongsTo('App\Ord', 'OrdNo', 'RNo');
    }

Controller: 
$ords = Ord::with('rones')->get();

Blade:
@extends('layouts.master')
@section('content')
<div class="table-responsive">
    <table width ="100%" class="table table-bordered table-hover table-striped" id="ords-table">
        <thead>
            <tr>
                <th>OrdNo</th>
                <th>RNo</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>OrdNo</th>
                <th>RNo</th>
            </tr>
        </tfoot>
    </table>
</div>
@stop
@push('scripts')
<script>
$(function() {
    $('#ords-table').DataTable({
        "processing": true,
        "serverSide": true,
        "aoColumnDefs": [
          {
            "mData": null,
            "sDefaultContent": "-",
            "aTargets": [ -1 ]
          }
        ],
        "dom": 'Blfrtip',
        "buttons": [
            'colvis',
        ],
        "ajax": { url: '{!! route('datatablesordsrones.data') !!}' },
        "columns": [
            { data: 'OrdNo', name: 'ords.OrdNo' },
            { data: 'rones.RNo', name: 'rones.RNo', 'defaultContent': " " },
        ],
    });
});
</script>
@endpush

**Comment by yajra** [comment]
Please see this [demo](http://datatables.yajrabox.com/eloquent/joins) and this [one](http://datatables.yajrabox.com/eloquent/relationships) for ref.

**Comment by mortenlandmark** [comment]
Hi.

I have used this demo to set it up:
http://datatables.yajrabox.com/eloquent/relationships

It is set up from two tables, exactly like the example.



But for some reason it's returning the error:
"DataTables warning: table id=ords-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

I have a one to one relationship with two models and tables: Ord with the ords table (orders) and Rone  with the rones table (projects).

A project belongs to an order, and an order may or may not have a project attached. This means that some fields in the rones table are left empty. 

Both tables are displayed correctly in the grid, and search and sorting works fine for the orders table, but not for the projects table.

Is there a way to fix it so that the second table will search and sort correctly?

EDIT: I just checked what happens if I made sure that all the orders have projects attached, and the sorting and searching still won't work.

I have attached sample data for the tables.

 
Here's my controller and blade:



Controller:
---------------------------------------------------------------------------------------------------------------------------
    public function anyOrdsRones()
    {
        
        $ords = Ord::with('rones')->select('ords.*');

        return Datatables::of($ords)->make(true);
    }
---------------------------------------------------------------------------------------------------------------------------


Blade:
---------------------------------------------------------------------------------------------------------------------------
@extends('layouts.master')

@section('content')
<div class="table-responsive">
    <table width ="100%" class="table table-bordered table-hover table-striped" id="ords-table">
        <thead>
            <tr>
                <th>Ordrenummer</th>
                <th>Ordredato</th>
                <th>Kundenummer</th>
                <th>Kundenavn</th>
                <th>Leveringsnavn</th>
                <th>Leveringsadresse1</th>
                <th>Leveringsadresse2</th>
                <th>Leveringsadresse3</th>
                <th>Leveringsadresse4</th>
                <th>Postnummer</th>
                <th>Område</th>
                <th>Etikett</th>
                <th>Vår referanse</th>
                <th>Kundens referanse</th>
                <th>Rekvisisjonsnummer</th>
                <th>Fakturanummer</th>
                <th>Fakturabeløp</th>
                <th>Siste fakturadato</th>
                <th>Pakkenummer</th>
                <th>Prosjektnummer</th>
                <th>Prosjektnavn</th>
                <th>Ad1</th>
                <th>Notis</th>
                <th>LokalisasjonVisma</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
            </tr>
        </tfoot>
    </table>
</div>
@stop

@push('scripts')
<script>
$(function() {
    $('#ords-table').DataTable({
        "processing": true,
        "serverSide": true,

        "dom": 'Blfrtip',
        "buttons": [
            'colvis',
        ],

        "ajax": { url: '{!! route('datatablesordsrones.data') !!}' },

        "columns": [
            
            { data: 'OrdNo', name: 'ords.OrdNo' },
            { data: 'OrdDt', name: 'ords.OrdDt', 'visible': false },
            { data: 'CustNo', name: 'ords.CustNo', 'visible': false },
            { data: 'Nm', name: 'ords.Nm' },
            { data: 'DelNm', name: 'ords.DelNm', 'visible': false },
            { data: 'DelAd1', name: 'ords.DelAd1', 'visible': false },
            { data: 'DelAd2', name: 'ords.DelAd2', 'visible': false },
            { data: 'DelAd3', name: 'ords.DelAd3', 'visible': false },
            { data: 'DelAd4', name: 'ords.DelAd4', 'visible': false },
            { data: 'DelPNo', name: 'ords.DelPNo', 'visible': false },
            { data: 'DelPArea', name: 'ords.DelPArea', 'visible': false },
            { data: 'Label', name: 'ords.Label', 'visible': false },
            { data: 'OurRef', name: 'ords.OurRef', 'visible': false },
            { data: 'YrRef', name: 'ords.YrRef', 'visible': false },
            { data: 'ReqNo', name: 'ords.ReqNo', 'visible': false },
            { data: 'InvoNo', name: 'ords.InvoNo', 'visible': false },
            { data: 'InvoAm', name: 'ords.InvoAm', 'visible': false },
            { data: 'LstInvDt', name: 'ords.LstInvDt', 'visible': false },
            { data: 'PacNo', name: 'ords.PacNo', 'visible': false },
            { data: 'rones.RNo', name: 'rones.RNo', 'defaultContent': " " },
            { data: 'rones.Nm', name: 'rones.Nm', 'defaultContent': " " },
            { data: 'rones.Ad1', name: 'rones.Ad1', 'visible': false, 'defaultContent': " " },
            { data: 'rones.Inf', name: 'rones.Inf', 'visible': false, 'defaultContent': " " },
            { data: 'rones.Inf2', name: 'rones.Inf2', 'defaultContent': " " },
        ],

        initComplete: function () {
            this.api().columns().every(function () {
                var column = this;
                var input = document.createElement("input");
                $(input).appendTo($(column.footer()).empty())
                .on('change', function () {
                    var val = $.fn.dataTable.util.escapeRegex($(this).val());

                    column.search(val ? val : '', true, false).draw();
                });
            });
        },
    });
});
</script>
@endpush
---------------------------------------------------------------------------------------------------------------------------

(I can remove the search function, and it has no effect, the sorting still won't work for the second table)






Morten Landmark
+47 9074 4883

Date: Fri, 20 May 2016 08:27:37 -0700

**Comment by necenzurat** [comment]
Same issue but using as a Service Provider

```
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
             ->addColumn('action', function ($offer) {
                return '<a href="offers/'.$offer->id.'/edit" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
            })
            ->make(true);
    }

 public function query()
    {
        $offers = Offer::with('mail', 'agent')->orderBy('created_at', 'desc');

        return $this->applyScopes($offers);
    }

```

It works like a charm, except when i try to search.

it throws this beautiful error
![Error](http://puu.sh/p4yE1/924a2ac37f.png)

**Comment by yajra** [comment]
Guys, can you please check v6.11.5 to verify that hasOne relationship was fixed? Just tested and released the PR above and works well for me. Thanks!

**Comment by necenzurat** [comment]
using v6.11.5, same error.

**Comment by amirolzolkifli** [comment]
Hi,

I'm also having the same error. The join is not working.

I'm using Laravel 5.0.35, Datatable 6.13.1

**Comment by yajra** [comment]
Sorry for late response. I suggest you try inspecting the network / ajax request for better debugging. From there you will see which column is failing on search/order. Just note that for joins, you must use `table.column` and for eager loading, use `relationMethod.column` as the name in your js. Thanks!

**Comment by yajra** [comment]
Guys can you please test this again on v6.18.0? Just found/fixed a bug that is related to searching on eager loaded models. Thanks!

**Comment by necenzurat** [comment]
it fixed a regular datatable, but nothing on the relations one.

**Comment by yajra** [comment]
Just added [hasOne demo](https://datatables.yajrabox.com/relation/has-one) and works fine. See it for ref.
