### ISSUE TITLE
how to use a helper in DataTable

### ISSUE THREAD

**Issue by agungIDku** [yajra/laravel-datatables#571]
I have my own data and displayed in the basic display. but I want to ask, I have a date field with sample results 12/12/2014, and I wanted to change into 12 December 2014, of course, if the helper without datatables certainly can. because this datatables javascipt and display data in JSON, where the helper should I put? is there any other way ? Thank you very much.

**Comment by yajra** [comment]
I think you can use Carbon for this. See this [demo](http://datatables.yajrabox.com/eloquent/carbon) for ref.

**Comment by agungIDku** [comment]
makasih banyak , solved!
