### ISSUE TITLE
Laravel Datatables as a Service without using Render

### ISSUE THREAD

**Issue by intrepidws** [yajra/laravel-datatables#574]
### Summary of problem or feature request

I have followed the tutorial on how to use Laravel Datatables as a Service, but I have so far been unable to figure out how to do this without using the generated HTML. I want to use my own HTML/JS, is that possible? Could you point me in the right direction of how I might do this?

P.S. We started this conversation on Twitter and you asked me to create a Github issue to continue the conversation here.

**Comment by yajra** [comment]
@intrepidws, using the the service implementation requires us to use `render()` method. This method handles the response when exporting/printing the table. But for the html/js, you can use your own for this. You just need to set the `ajax` parameter to the route that handles `$dataTable->render('view')`.

```
<table id="my-table">
<thead>...</thead>
</table>
```

```js
$('#my-table').DataTable({
  processing: true,
  serverSide: true,
  ajax: '/controller/render'
  buttons: true,
  columns: [...],
  etc...
});
