### ISSUE TITLE
databales waits more than 20 seconds to load all data first !!

### ISSUE THREAD

**Issue by macnux** [yajra/laravel-datatables#575]
i use this code to use datatables to load 4000 records

    $('#provincedataTable').DataTable({
        paging:true,
        bprocessing: true,
        bserverSide: true,
        sAjaxSource: 'province/provinces-json',
        columns: [
            {data: 'select', name: 'select'},
            {data: 'code', name: 'code'},
            {data: 'name', name: 'name'},
            {data: 'options', name: 'options'}
        ],
        "fnDrawCallback": function() {
            Checkboxs();
        }
    });

the page waits more than 20 seconds to load all records first !!!
although it should load only the first page and when i click the page it should load the records on that page

- Operating System windows 8.1
- PHP Version 5.6.15
- Laravel Version 5.2
- Laravel-Datatables Version 1.10.7

**Comment by yajra** [comment]
Can you please provide your server side code? You might be using collection?

**Comment by ChaosPower** [comment]
@macnux I believe you're using an old version of datatables JS?

**Comment by macnux** [comment]
ok sorry was my problme but solved and now another problem

i use this new code 

 $('#provincedataTable').DataTable({
        processing: true,
        serverSide: true,
        stateSave: true,
        ajax: 'province/provinces-json',
columns: [
{'data': 'options'}
{'data': 'icheck'}
],
        "fnDrawCallback": function() {
            Checkboxs();
        }
    });

and on server side code i use this 

        $provinces = Province::orderBy('name','ASC');
        return \Datatables::of($provinces)
            ->add_column('options',' html code here')
            ->add_column('icheck','html code here')
            ->make(true);


give me error says those columns are not on the database
NOW how i can output those added columns on the page?
thanks in advance.

**Comment by yajra** [comment]
@macnux since your columns are added and not part of the database, it should not be searchable and orderable. To fix this add:

```js
{'data': 'options', searchable : false, orderable: false},
{'data': 'icheck', searchable : false, orderable: false}
```
