### ISSUE TITLE
[question] Dynamically generated columns with addColumn method.

### ISSUE THREAD

**Issue by salehliam** [yajra/laravel-datatables#576]
Hello Guys!

I would like to add a column with a given name that is passed by variable and use the same variable to access the object property to render the content of the column. Is it possible?

**Comment by yajra** [comment]
I think you can do something like below:

```php
$dt = Datatables::of($model);
if ($request->has('field') {
  $dt->addColumn($request->field, 'content here');
}

return $dt->make(true);

**Comment by salehliam** [comment]
Thanks Arjay for the response.

I have a collection of objects. Every object is built from JSON that is retrieved from the 'objects' table and has given type. Another table holds information about fields specific to given type of objects. I want to display objects of given type in a table. It's quite easy to generate columns based on the information stored in a table as to what fields belongs to what type of object but I have no idea how to refer to object property itself based on the same information.

**Comment by ChaosPower** [comment]
@salehliam for adding columns dynamically, I use transformers.

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!

**Comment by xyrintech** [comment]
@yajra Is it possible to please share the code for this dynamic column thing?

**Comment by ambrooo** [comment]
@xyrintech you could do something like @yajra said on ajax:
`$dt = Datatables::of($model);
if ($request->has('field') {
  $dt->addColumn($request->field, 'content here');
}

return $dt->make(true);`

and on columns:
`$columns = [
            [ 'data' => 'name', 'name' => 'name', 'title' => 'Name' ]
        ];

        if($request->has('field'){
            $columns[] = [ 'data' => $request->field, 'name' => $request->field, 'title' => 'Field Title'];
        }

        return $columns;`
