### ISSUE TITLE
Laravel 4 - Sortable by 2 columns in one

### ISSUE THREAD

**Issue by aminebk** [yajra/laravel-datatables#587]
Hi,

I have a table job(), with fields "feedback_client", "feedback_user"

I have make a column in datatable, to show if feedback is done or not, so I did:

`->editColumn('feedback', '{{ ($feedback_client==1 || $feedback_user==1) ? \'<h5 class="badge bg-green">Yes</h5>\' : \'<h5 class="badge bg-red">No</h5>\' }}')`

it works good, the issue is this new column is not sortable, and I don't know how to do it. In init datatable I did:
`
{data: 'feedback', name: 'feedback_client', searchable:false},`

but of course, it will work only in first field, not second one.

any ideas? 

Thanks

**Comment by yajra** [comment]
Unfortunately for Laravel 4 version, I think this not doable. But using the latest version, you can try using [orderColumn](http://datatables.yajrabox.com/eloquent/order-column) API to do the custom sorting.

**Comment by aminebk** [comment]
Hi Yajra,

We can do something like count or sum sql, of the 2 columns, as name of the field in the JS init of datatable?

Thank you for helping

**Comment by yajra** [comment]
In Laravel 4 days, what I usually do is I create all the data I need in the sql level so that the package responsibility is to just display it since it does not most of the feature we have now. I suggest you do the same too and do it on the sql level or making a view for instance. Thanks!
