### ISSUE TITLE
Data Export Creating Empty File

### ISSUE THREAD

**Issue by smccoy78** [yajra/laravel-datatables#589]
### Summary of problem or feature request
I am using the Datatables Service implementation. When I try to perform an export of the data using either csv, excel, or pdf, the file is created with no data, headers, etc... I is just an empty file. I was originally using the non-service implemenation but ran into issues with data export displaying json to screen so I just switched to this method. I apologize for the lengthy post, I just want to make sure you have everything you might need to be able to assist me in this issue.

The way I am intending this to work is:
User clicks the reports link which loads the index view. From here they have a custom date filter and report selection drop down. Based on their input, the appropriate report is ran and results displayed in the datatable located on the same page. So far, everything except the data export works.

### ReportsDataTable.php
```php
public function ajax()
{
    return $this->datatables
                      ->collection($this->query())
                      ->make(true);
}

public function query()
{
    $response = "";

    switch( $this->type )
    {
        case 1:
            $response = $this->sales($this->start, $this->end);
            break;
        case 2:
            $response = $this->commission($this->start, $this->end);
            break;
        case 3:
            $response = $this->cog($this->start, $this->end);
            break;
        case 4:
            $response = $this->shipping($this->start, $this->end);
            break;
    }

    return $response;
}

public function html()
{
     return $this->builder()
                       ->columns($this->getColumnNames())
                       ->ajax('')
                       ->parameters($this->getBuilderParameters());
}

protected function getBuilderParameters()
{
    return [
        'order'   => [[0, 'asc']],
        'buttons' => [
            'csv',
            'excel',
            'pdf',
        ],
    ];
}

protected function getColumnNames()
{
    return $this->columns;
}

private function commission($start, $end)
{
    $dataArray = new Collection;

    $data = 'QUERY';

    $dataArray->push([
        'public_name' => $data->public_name,
        'comm_total' => money_format('%.2n', $data->comm_total)
    ]);

    $this->columns = [ 'public_name', 'comm_total' ];

    return $dataArray;
}
```
### Javascript
```js
$('#reports-table').DataTable({
    dom:            'frtBp',
    paging:         true,
    pagingType:     'simple_numbers',
    lengthMenu: [ [ 15, 30, 50, -1 ], [ 15, 30, 50, "All" ] ],
    processing:     true,
    serverSide:     true,
    destroy:        true,
    buttons:
    [
        'excel',
        'csv',
        'pdf',
    ],
    ajax: {
        url: '{!! route( 'reports::getreport' ) !!}',
        data: function(d) {
            d.fromDate = start;
            d.toDate = end;
            d.report_type = 2;
        }
    },
    columns: [
        { data: 'public_name', name: 'public_name', title: 'Name', sortable: true },
        { data: 'comm_total', name: 'comm_total', title: 'Commission', sortable: true },
     ],
});
```
### ReportsController.php
```php
public function index()
{
    return view('reports.index');
}

public function getReport(ReportsDataTable $dataTable)
{
    $report_type = Input::get('report_type');
    $start = Carbon::now()->subMonth();
    $end = Carbon::today();

    return $dataTable->setSelection($report_type, $start, $end)->render('reports.index');
}
```
### Routes
```php
Route::group( [ 'as' => 'reports::', 'prefix' => 'reports', 'namespace' => 'Reports' ], function() {
    Route::get( 'index', [ 'as' => 'index', 'uses' => 'ReportsController@index' ] );
    Route::get( 'getreport', [ 'as' => 'getreport', 'uses' => 'ReportsController@getReport' ] );
});
```
### System details
- Operating System: Windows 10 Professional (Workstation) / Ubuntu Server 14.04 (Server)
- PHP Version: 5.5.9-1
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.10.1

**Comment by yajra** [comment]
Does your table renders correctly? Exporting process is almost the same with rendering the default ajax response. So basically, ff the table in service renders properly, exporting should work as expected.

**Comment by smccoy78** [comment]
My table renders as expected. All the data is present, but for some reason when I attempt to export I get nothing. I'm not getting table headers or data, just an empty excel or csv.

**Comment by smccoy78** [comment]
I was able to get it working with the csv option. I will test the other options now. What I had to do to get it to work was to add columns array to my setSelection() and pass the columns for the desired query. Then set $this->columns in setSelection instead of my query function.
