### ISSUE TITLE
How add column delete?

### ISSUE THREAD

**Issue by luizpatrocinio** [yajra/laravel-datatables#590]
My controller

public function api()
    {
        //Datatables::eloquent(Cliente::query())->make(true);
        $dadosAPI = Cliente::select(['id', 'nomeCliente', 'cpf', 'rg', 'email'])->get();
        
        return Datatables::of($dadosAPI)->addColumn('action', function ($user)
        {
            return '<a href="/cliente/'.$user->id.'/edit" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Editar</a>';
        })
        ->editColumn('id', 'ID: {{$id}}')
        ->make(true);
    }

My index

script>
$(function() {
    $('#tabela').DataTable({
        "processing": true,
        "serverSide": true,
        "language": { "url": "/datatables/pt.br" },
        "ajax": "/cliente/api",
        "columns": 
        [ 
        { data: "id" },
        { data: "nomeCliente" },
        { data: "cpf" },
        { data: "rg" },
        { data: "email" },
        { data: "action"}
       
        ]
    });
});
</script>

**Comment by ChaosPower** [comment]
What's this for?

**Comment by luizpatrocinio** [comment]
sorry am beginner does not work, I have to use classes?

use CommPay\Models\Advance;
use League\Fractal\TransformerAbstract;

**Comment by ChaosPower** [comment]
you need to use use League\Fractal\TransformerAbstract;
```php
public function getTransformerData()
    {
        $users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

        return Datatables::of($users)
            ->setTransformer('App\Transformers\DatatablesTransformer')
            ->make(true);
    }
```

**Comment by luizpatrocinio** [comment]
Get. Thank you for your time

**Comment by luizpatrocinio** [comment]
$dadosAPI = User::select(['id', 'name', 'email'])->get();
        
        return Datatables::of($dadosAPI)->addColumn('action', function ($user)
        {
            return '<a href="/cliente/'.$user->id.'/edit" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i> Editar</a>'
            ." ".
            '<a href="/cliente/'.$user->id.'" class="btn btn-xs btn-danger"><i class="fa fa-eraser"></i>Excluir</a>';
        })->editColumn('id', '{{$id}}')->make(true);
