### ISSUE TITLE
How to use DB indexes

### ISSUE THREAD

**Issue by josemujicap** [yajra/laravel-datatables#592]
Hello,

So far when I try column filtering I'm able to use LIKE or REGEXP but nether of them are using table indexes, which is a great concern given the amount of data I need to filter.

Is there a way to get an exact match using indexes?

**Comment by ChaosPower** [comment]
Can you give example on what you are trying to do?

Please check: http://datatables.yajrabox.com/fluent/advance-filter

**Comment by josemujicap** [comment]
Thank you, seems like filterColumn will do the job.

**Comment by ChaosPower** [comment]
Thanks for the reply. Closing this issue. Please reopen if there's more.
