### ISSUE TITLE
concatenate column search issue

### ISSUE THREAD

**Issue by shireen22** [yajra/laravel-datatables#593]
### Code snippet of problem

========== $query=============
$query = ApplicationForm::with('agent');
 return $query;

```
     ==============================

     $isExportRequest = Request::query('action');
        return $this->datatables
         ->of($this->query())
         ->editColumn('full_name', function ($row) use ($isExportRequest) {
           return $row->agent->first_name . $row->agent->last_name . ' (' . $row->agent->number .')';                                            
        })->filterColumn('full_name', 'whereRaw', "(agent.first_name LIKE ? OR agent.first_name       LIKE ?)", ["$1", "$1"])->make(true);
```
# 

using laravel 5.1

please help me to solve this issue

**Comment by yajra** [comment]
@shireen22 Your snippet looks fine. I suggest you inspect the ajax response using firebug or chrome dev tools to get a better hint on what may been going wrong.

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
