### ISSUE TITLE
how to search two concatenate column

### ISSUE THREAD

**Issue by shireen22** [yajra/laravel-datatables#595]
### Summary of problem or feature request

i want first name and last name which concatenate column search should work 

### Code snippet of problem

 public function getPendingPolicies(array $options = [])
    {
        $agentId = isset($options['agent_id']) ? $options['agent_id'] : activeAgentId();
        //search with relationship
        $query = ApplicationForm::with('agent');

        $this->setCommonAgentsIdsInAppFormsQuery($options, $query, $agentId);

        $query->where('policy_status', ApplicationForm::PENDING);
        //query
        
        return $query;
    }

i made method then i call this in query for example like this

 public function query()
    {
        if ($this->type === 'approved') {
            $query = $this->getApprovedPolicies($this->options);

        } elseif ($this->type === 'pending') {
            $query = $this->getPendingPolicies($this->options);

        } elseif ($this->type === 'pastdue') {
            $query = $this->getOverduePolicies($this->options);

        }

        return $this->applyScopes($query);
    }

in ajax request i m using follow code

====================ajax part i did following code=============================

    public function ajax()
    {
        // checks whether request is for exporting (CSV, Excel, PDF)
        $isExportRequest = Request::query('action');

   
        return $this->datatables
            ->of($this->query())
            ->editColumn('full_name', function ($row) use ($isExportRequest) {
                return $row->agent->first_name . $row->agent->last_name . ' (' . $row->agent->number . ')'
           })->make(true);
    }
 here i m concatenate two column first_name and last_name
i want to search base on first_name ,last_name

  $columns =
                [

                    ['data' => 'full_name', 'name' => 'agent.first_name', 'title' => 'Agent', 'searchable' => true],
                    [
                        'data' => 'payor',
                        'name' => 'payor',
                        'title' => 'Payor',
                        'orderable' => false,
                        'searchable' => true
                    ],
                    ['data' => 'contract_number', 'name' => 'contract_number', 'title' => 'Policy'],
                    ['data' => 'premium', 'name' => 'premium', 'title' => 'Amount'],
                    ['data' => 'released_on', 'name' => 'released_on', 'title' => 'Issued on'],
                    'paid_to',
                    ['data' => 'days_late', 'name' => 'days_late', 'title' => 'Days Late', 'searchable' => false],
                    'policy_status',
                    ['data' => 'payor_phone', 'name' => 'payor_phone', 'title' => 'Payor Phone'],
                ];

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
@shireen22 you can use filterColumn method to write your concat query. But note that concat usage may differ depending on the DB driver you are using. See this [demo](http://datatables.yajrabox.com/eloquent/post-column-search) for ref.
