### ISSUE TITLE
Custom export when printing, pdf, excel ....and more exports

### ISSUE THREAD

**Issue by thom7kick** [yajra/laravel-datatables#596]
How can i have custom **TITLES**, **HEADERS**, AND **FOOTERS**. When I export a data table

**Comment by yajra** [comment]
You can override `protected function buildExcelFile()` method and do the customizations you need. Just check the [Laravel-Excel](https://github.com/Maatwebsite/Laravel-Excel) api for more details.

**Comment by thom7kick** [comment]
ok i will raise this issue with Maatwebsite/Laravel-Excel. Thank you.

**Comment by RayhanYulanda** [comment]
how about pdf ? @yajra
