### ISSUE TITLE
Implement custom filter as service implementation

### ISSUE THREAD

**Issue by josedejesusjaime** [yajra/laravel-datatables#599]
Hi I already read 2 issues treating this topic, but i dont get how to send the additional data yet.
I understand i need to use the Request Object to get the data, but i put it at htmlbuilder?, i need to have a js file or what? I really appreciate an advice. My code is like below:
` public function query() {
        

        $tipoCambioRfcAlumnos = TipoCambioRfcAlumno::query()
                ->select('id_tipo_cambio', 'fecha', DB::raw('CONCAT(moneda," ",descripcion) as moneda'), DB::raw('FORMAT(tipocambio,2) as tipocambio'))
                ->join('rfc_alumno', 'tipo_cambio_rfc_alumno.id_rfc_alumno', '=', 'rfc_alumno.id_rfc_alumno')
                ->join('moneda', 'tipo_cambio_rfc_alumno.id_moneda', '=', 'moneda.id_moneda')
                ->whereIn('rfc_alumno.id_rfc_alumno', function($query) {
            $query->select('id_rfc_alumno')
            ->from('rfc_alumno')
            ->where('matricula', '=', session('matricula'));
        });

        return $this->applyScopes($tipoCambioRfcAlumnos);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html() {
        return $this->builder()
                        ->columns(array_merge(
                                        $this->getColumns(), [
                            'actions' => [
                                'orderable' => false,
                                'searchable' => false,
                                'printable' => false,
                                'exportable' => false
                            ]
                                        ]
                        ))
                        ->parameters([
                            'language' => [
                                'url' => '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'
                            ],
                            'dom' => 'Bfrtip',
                            'scrollX' => true,
                            'buttons' => [
                                'reload'
                            ],
        ])
                ;
    }`

**Comment by yajra** [comment]
You can add a js file after the dataTable scripts and use this https://datatables.net/reference/event/preXhr to attach a data to server request.

**Comment by josedejesusjaime** [comment]
I have to initialize the table again, Or I have to delete  {!! $dataTable->scripts() !!}  and put my own code

**Comment by josedejesusjaime** [comment]
Look i put this in my table.blade, but I Cannot reinitialise the table .DataTables warning: table id=dataTableBuilder - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

`{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>
<script src="vendor/datatables/buttons.server-side.js"></script>
{!! $dataTable->scripts() !!}
<script type="text/javascript">
    $(function () {
        $('#dataTableBuilder')
                .on('preXhr.dt', function (e, settings, data) {
                    data.sessionId = $('input[name="fecha"]').val();
                })
                .dataTable({
                    ajax: "data.json"
                });
    });
</script>

@endsection`

**Comment by josedejesusjaime** [comment]
I did it !! thx

**Comment by emoragaf** [comment]
@josedejesusjaime can you ost yout solution pls
