### ISSUE TITLE
Searching related models returns related model instead of desired model

### ISSUE THREAD

**Issue by oceanapplications** [yajra/laravel-datatables#600]
I have a datatable based on my orders table with some data from a related customers table.  If the search query contains a column from the customers table, this library returns the customer model instead of the order model which causes the IDs in the table to be switched.

My serverside function is this 

```php
function ordersTableData(Request $request)
{
    $orders = Order::with('customer');
    return Datatables::of($transactions)->make(true);
}
```

### System details

- Laravel Homestead Ubuntu 14.04
- PHP 7
- Laravel 5.2
- Laravel-Datatables v6.11.5

Thanks

**Comment by yajra** [comment]
As noted in this [demo](http://datatables.yajrabox.com/eloquent/relationships), you need to add `->select('order.*');` on your query to avoid switching of ID. Thanks!

**Comment by oceanapplications** [comment]
Thanks very much, works perfectly now.
