### ISSUE TITLE
Dates are not sorting after being formatted.

### ISSUE THREAD

**Issue by Gouvi** [yajra/laravel-datatables#601]
### Summary of problem or feature request
Dates are not sorting after being formatted. The first piece of code works, the second doesn't sort them properly.

### Code snippet of problem
Column is set to:
```javascript
{ data: 'created_at', name: 'created_at', class: 'date' },
```

This works:
```php
->editColumn('created_at', function($orders){
    $createdAt = new Carbon($orders->created_at);
    return $createdAt->format('d/m/y');
})
```
This doesn't:
```php
->editColumn('created_at', function($orders){
    $createdAt = '';

     if (is_null($orders->netsuite_created_at)) {
        $createdAt = new Carbon($orders->created_at);
    } else {
        $createdAt = new Carbon($orders->netsuite_created_at);
    }

    return $createdAt->format('d/m/y');
})
```

### System details
- PHP Version v7.0.6
- Laravel Version v5.2.29
- Laravel-Datatables v6.10.1

**Comment by jadavpalak** [comment]
i also face the same issue. 
`$orders = Order::with('user')->orderBy('created_at', 'desc')->get();
        return Datatables::of($orders)
        ->addIndexColumn()
        ->addColumn(
          'user_name',
          function ($orders) {
            return $orders['user_name'] = $orders['user']['first_name'].' '.$orders['user']['last_name'];
          })
          ->addColumn(
            'status',
            function ($orders) {
              if($orders['paid'] == 0){
                return $orders['paid'] = 'Unpaid';
              }else{
                return $orders['paid'] = 'Paid';
              }
            })
            ->addColumn(
              'date',
              function ($orders) {
                return Carbon::parse($orders['created_at'])->format("d, F Y");
              })
              ->addColumn('action', function ($order) {
                return '<a href="/orders/'.$order->id.'" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> View</a>';
              })
              ->make(true);`
`{data: 'date', name: 'date'},`

**Comment by theM1st** [comment]
> i also face the same issue.
> This is blade template code:
> 
> ```
>     {data: 'date', name: 'date'},
> ```
> This is controllers code:
> 
> ```
>     $orders = Order::with('user')->orderBy('created_at', 'desc')->get();
>     return Datatables::of($orders)
>     ->addIndexColumn()
>     ->addColumn(
>       'user_name',
>       function ($orders) {
>         return $orders['user_name'] = $orders['user']['first_name'].' '.$orders['user']['last_name'];
>       })
>         ->addColumn(
>           'date',
>           function ($orders) {
>             return Carbon::parse($orders['created_at'])->format("d, F Y");
>           })
>           ->addColumn('action', function ($order) {
>             return '<a href="/orders/'.$order->id.'" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> View</a>';
>           })
>           ->make(true);
> ```

{data: 'date', name: 'created_at'},

**Comment by dhavalbera9898** [comment]
you need to change  "addColumn"  to "editColumn" i think it's solve problem

**Comment by francesco-taioli** [comment]
Another solution is `[here](https://stackoverflow.com/a/62873055/5723524)`
