### ISSUE TITLE
How to AJAX search tables created by variable relational columns

### ISSUE THREAD

**Issue by eComEvo** [yajra/laravel-datatables#602]
### Summary of problem or feature request
This is a two part problem...

I have columns on a datatable that are from a `products` table and other columns from an `attribute_values` table. There is an `attributes` table which is related to the `attribute_values` table via the foreign key `attribute_id`. The `attributes` table holds the name of each unique attribute, thus becoming the column heading.

The `attributes` table is flexible, allowing a variable number of attributes to be stored from a variety of different other models using `attributable_id` and `attributable_type` fields.

For instance, I might have `attribute_id=1 AND attribute_id=5 AND attributable_type='Product'`.

The columns can be added to the datatable using a loop on the first product result using the `customAttributes` relation.

Basic example of how the attribute columns will be added:
```php
$products = Product::all();
$dt = Datatables::of($products);
        
foreach ($products->first()->customAttributes() as $a) {
    $dt->addColumn($a->name);
}
```

**Problem 1:** _How do I make these fields searchable over AJAX?_

The actual values I'm planning to have flattened into each product row by looping through them for each paginated slice.

**Problem 2:** _How can I intercept DataTable's pagination on each AJAX data request so that I can add the required values to the main collection and do so in a resource efficient manner?_

### System details
- Operating System: Ubuntu
- PHP Version: 7
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.x
- Database solution: PostgreSQL 9.4

**Comment by yajra** [comment]
Unfortunately, for query builder and eloquent engine, this is not possible because added columns are not part of the query. But if you can convert this added column using a database view then I think it should work.

Currently, there is no way to intercept pagination and even count queries.

**Comment by eComEvo** [comment]
Do you think this could conceivably work if I modified the original query to chain a variable number of subqueries into the SELECT statement?

**Comment by yajra** [comment]
Yes, i think it would work and I think I already did something like that before but not in a loop.

Something like below:
```php
$query->addSelect(DB::raw("'hard coded value' as custom_field"));
```

**Comment by eComEvo** [comment]
Thanks! I'll give it a try!
