### ISSUE TITLE
Hide Queries Attribute

### ISSUE THREAD

**Issue by johnwheal** [yajra/laravel-datatables#603]
I may be missing something but the AJAX json being returned contains a `queries` attribute. This lists all the database queries run and their associated execution time. This may be useful for debugging but there is no way that I will allow this in a production environment. Is there any way to hide or disable this behaviour? I'm guessing that I'm missing something because I cannot believe that so many people are happy with this from a security prospective.

**Comment by yajra** [comment]
@johnwheal you need to disable `app.debug` to hide the queries. Thanks!

**Comment by johnwheal** [comment]
@yajra I think this should be in the documentation

**Comment by yajra** [comment]
Yes, it used to be in the read me but I think I have deleted it. Will bring it back later. Thanks!

Sent from Outlook using iPhone




On Thu, Jun 16, 2016 at 6:48 PM +0800, "John Wheal" <notifications@github.com> wrote:












@yajra I think this should be in the documentation

**Comment by alehosaini** [comment]
Hi Mr. Arjay,
where could i find the `app.debug` attribute
because i'm using Angularjs Datatable and Laravel is this attribute related with your plugin
or in the javascript.

Thanks.

**Comment by lombervid** [comment]
@alehosaini It's a Laravel configuration. 
config/app.php in index 'debug' 
or 
in your .env file the APP_DEBUG

**Comment by alehosaini** [comment]
@lombervid Thanks

**Comment by MubinSayed** [comment]
@yajra it is not working for me.

**Comment by gzai** [comment]
@yajra it's not working to hide queries when I set .env APP_DEBUG=false
yajra/laravel-datatables : v1.5.0
yajra/laravel-datatables-oracle : v9.14.1
any help?

**Comment by yajra** [comment]
@gzai might be a cache issue. Try clearing the config: `php artisan config:clear`

**Comment by gzai** [comment]
@yajra ah yes cache issue. Thanks a ton.
