### ISSUE TITLE
Search not working in many-to-many relationship 

### ISSUE THREAD

**Issue by fido888** [yajra/laravel-datatables#608]
### Summary of problem or feature request

many to many relationship  not searchable and sort not working and i tried in the [demo](http://datatables.yajrabox.com/eloquent/joins) its not working
i have 3 tables 

users
roles
user_role ( pivot )
### Code snippet of problem

in model

```
 return $this->belongsToMany('App\User','user_role');
return $this->belongsToMany('App\Role','user_role');
```

in controller

```
public function getData()
    {
        $users = User::with('Roles')->select('*')->withTrashed()->get();

        return Datatables::of($users)
           ->addColumn('roles', function ($users){
                $role_name = [];
                foreach ($users->roles as $role){
                    $role_name =  $role->role_title;
                }
               return  $role_name;
           })
  }
```

in view

```
 var table = $('#data').DataTable(
            {
                processing: true,
                serverSide: true,
                ajax: '{{ url('users/data') }}',

                columns: [
                    {data: '#', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'roles', name: 'roles.role_title', Searchable: true}
            ]
    });
```
### System details

- Operating System
- PHP Version 5.6
- Laravel Version 5.2
- Laravel-Datatables Version 5.7.9

**Comment by yajra** [comment]
@fido888 not all eager loaded models are currently supported by the package. And I think many-to-many relationship is one of them. You have to use join statements for this case. Thanks!

**Comment by martimarkov** [comment]
@yajra Any example on using JOIN statements?

**Comment by yajra** [comment]
@fido888 can you please try this again on v6.18.0? A recent bug was found/fixed that is relation to eager loaded model searching. Thanks!

**Comment by yajra** [comment]
This issue should be fixed on the latest version. Thanks!
