### ISSUE TITLE
Can't manage to get column search work

### ISSUE THREAD

**Issue by ozza** [yajra/laravel-datatables#610]
Hello,

I am trying to accomplish a column search using the same codes from the demo pages related to the column search like;
-http://datatables.yajrabox.com/eloquent/multi-filter-select
-http://datatables.yajrabox.com/eloquent/post-column-search
etc..

But I am currently unable to see the search inputs at the footer of the datatable. I think 
`$(input).appendTo($(column.footer()).empty())` is not working. Can anyone suggest me anything to make it work?

Thanks

### System details

- Operating System: Fedora 23
- PHP Version: 5.6
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.11

**Comment by yajra** [comment]
@ozza sorry for late response. Do you have a footer mark up on table? If not, then you need to add it for this to work. `tfoot>tr>th`

**Comment by ozza** [comment]
thank you. i'm going to try.
