### ISSUE TITLE
Array instead object inside transformer

### ISSUE THREAD

**Issue by Hicask** [yajra/laravel-datatables#615]
Why transformers receive array as parameter instead of objects??

Main code:
```
$datatables =  Datatables::of($resources)
    ->setTransformer(new Transformer)
    ->make(true);
```
Transformer:
```
public function transform($resource)
{
    // gettype($resource) => array instead of object
    $transformer = [
        'id' => $resource['id']
    ]
    return $transformer;
}
```
Thanks.

**Comment by yajra** [comment]
I think it depends on your resource. If your using query builder then it's an array. If your using eloquent then it will return object.

**Comment by Hicask** [comment]
I am using eloquent.

`$resources = Model::where('condition', true)->get();`

$resources is an array of eloquent object, but when using transformers I get an array instead of object. So I can't call relationships methods.

**Comment by yajra** [comment]
Try adding a type hint if it's a model.

```php
public function transform(ModelName $resource);
```

**Comment by Hicask** [comment]
I got an exception.

`Argument 1 passed to Transformer::includeExtra() must be an instance of App\Models\Model, array given`

I am doing something wrong???

**Comment by yajra** [comment]
Oh I think it's because you are using collection. Try removing `->get();` on your query.

**Comment by Hicask** [comment]
Still getting array. I use the same example of [http://datatables.yajrabox.com/eloquent/transformer](url) with same result, array instead object. Anyone having this same problem????

**Comment by yajra** [comment]
@Hicask I just updated that demo and used `User` model and still works. Maybe there is something wrong on your includes? `Transformer::includeExtra()`...

**Comment by Hicask** [comment]
Umm, maybe something related to this package, I am using [https://github.com/Cyvelnet/laravel5-fractal](url)
I will take a look and see what happend with this. Thanks for the time.
