### ISSUE TITLE
No data when using  DataTables as a service

### ISSUE THREAD

**Issue by HarleyFuagras** [yajra/laravel-datatables#618]
### Summary of problem or feature request

I am not being able to show any data on my datatable when trying to follow this tutorial http://datatables.yajrabox.com/service

I am using a model different than User, named Trial. And as I found that no query was being executed I added **->ajax($this->ajax())** to the builder. Now the correct query is being called but no data gets populated on the table, the view just shows the columns specified in the getColumns() method. Thank you for your time, awesome work.

### Code snippet of problem
# 
**TrialDatatable.php**

```php
<?php

namespace App\DataTables;

use App\Trial;
use Yajra\Datatables\Services\DataTable;

class TrialDataTable extends DataTable
{
    // protected $printPreview  = 'path.to.print.preview.view';

    /**
     * Display ajax response.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->make(true);
    }

    /**
     * Get the query object to be processed by datatables.
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
        $trials = Trial::select();
        return $this->applyScopes($trials);
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax($this->ajax())
                    ->addAction(['width' => '80px'])
                    ->parameters($this->getBuilderParameters());
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            'id',
            'name',
            'email',
            'created_at',
            'updated_at',
        ];
    }

    /**
     * Get builder parameters.
     *
     * @return array
     */
    protected function getBuilderParameters()
    {
        return [
            'dom' => 'Bfrtip',
            'buttons' => ['csv', 'excel', 'pdf', 'print', 'reset', 'reload'],
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return 'trials';
    }
}

```
# 
**TrialDatatable.php**

```php
<?php

namespace App\Http\Controllers\Admin;

use App;
use App\Http\Controllers\Controller;
use App\DataTables\TrialDataTable;
use App\Trial;
use Yajra\Datatables\Datatables;

class TrialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(TrialDataTable $dataTable)
    {
        return $dataTable->render('index');
    }
}

````
# 
**index.blade.php**

```php
@extends('app')

@section('content')
{!! $dataTable->table() !!}
@endsection

````

- Windows 7
- Laravel 5.2
- Laravel-Datatables ~6.0

**Comment by yajra** [comment]
First, `ajax()` accepts a route where the json data will be fetch and is default to empty string to fetch data on same route.
```php
->ajax('')
```

Second, I think you are missing the scripts. 
```php
@section('content')
{!! $dataTable->table() !!}
@endsection

@push('scripts')
{!! $dataTable->scripts() !!}
@endpush
```

**Comment by HarleyFuagras** [comment]
Hi, thanks for your reply.

I put that inside `ajax()` because I didn't see any query being made on my debugbar If I didn't.

If I try to make `dd()` test calls inside `query()` or `ajax()` nothing is happening, is this normal?

The scripts are not on the view, I am using gulp to include them -but I tried to include them like you said with no results-. I think I am missing something really basic but I can't find my way on the docs. 

Thank you!

**Comment by yajra** [comment]
Can you inspect your network tab and double check if the ajax request is being triggered upon loading of page? I suspect that your js is failing.

**Comment by HarleyFuagras** [comment]
Yes! the problem was there. Somehow I am not including properly in my gulp the scripts needed here. But if I include them as you suggested in your first reply (and I do it properly, not as I was doing it before) the ajax call is correct.

I don't know if I am missing some script in my gulp file. Now I am including these datatables related script files.

```
nodeModulesPath + 'datatables/media/js/jquery.dataTables.min.js',

nodeModulesPath + 'datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.min.js',

nodeModulesPath + 'datatables.net-responsive/js/dataTables.responsive.js',

nodeModulesPath + 'datatables.net-buttons/js/dataTables.buttons.js',

publicPath + 'vendor/datatables/buttons.server-side.js',

```
Do I need more than those?
Thank you very much.

**Comment by HarleyFuagras** [comment]
Ah, I looked deeper at the Builder class and understood what was going on and why the scripts were neeeded the way you were saying. Thanks for taking the time!
