### ISSUE TITLE
Error in Documentation - Searchable in joined table returns Ajax error

### ISSUE THREAD

**Issue by mastermind23** [yajra/laravel-datatables#622]
### Summary of problem or feature request

https://datatables.yajrabox.com/services/two-datatables

The searchable POSTS tab in this link of documentation isn't working and gives ajax error ( DataTables warning: table id=postsTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7 ). I'm having a similar issue to search in joined tables when I'm using Yajra as a Service through a packge Infyom Laravel Generator https://github.com/InfyOmLabs/laravel-generator

### System details

- Operating System: windows 7
- PHP Version: latest
- Laravel Version latest
- Laravel-Datatables Version: latest

**Comment by gusilveiramp** [comment]
+1

**Comment by yajra** [comment]
Thanks for reporting. Demo fixed!
