### ISSUE TITLE
Failure to Vendor Publish

### ISSUE THREAD

**Issue by jim1506** [yajra/laravel-datatables#623]
I am using Laravel 5.2. When I type

php artisan vendor:publish --tag=datatables

I get 
[RefelectionException]
Class Illuminate\Contracts\Auth\Access\Gate does not exist

- Operating System - Windows 10
- PHP Version 5.6
- Laravel Version 5.2
- Laravel-Datatables Latest

**Comment by yajra** [comment]
I think there is something wrong on your Gate implementation which causes the issue and is not related with the package. Try using `php artisan vendor:publish` without tags. If it fails then there is a problem in your Gate.

**Comment by jim1506** [comment]
Thanks after using publish without tags I could then publish it with tags OK.
