### ISSUE TITLE
Big data problem!

### ISSUE THREAD

**Issue by saeedvaziry** [yajra/laravel-datatables#624]
hi.
i have a table that has many records. in every request datatable loads all data in array even on pagination...! and this is wrong! i just need to load only 25 record in each requests!

        $products = Product::orderBy('id', 'desc')->get();
        return Datatables::of($products)->make(true);

**Comment by yajra** [comment]
It's because you are fetching all the records. Remove `->get()` and it should be fixed.

**Comment by oriceon** [comment]
There is a change on package? I have same trouble and not using ->get() or so .. All records are stored in first request :(
