### ISSUE TITLE
Join Queries and edit columns take more time to load

### ISSUE THREAD

**Issue by maheshtc** [yajra/laravel-datatables#627]
I have been trying to figure out loading issue with join queries and edit columns. I have table law_firms having 17000+ records and other related tables. Below is code snippets which takes around 1 mins time to load. Sometimes it gives time out error. As per other previous tickets, they say datatable can load 1lac records in mean time. But here it takes around 1 min to load 

```
$lawfirm = LawFirm::leftJoin('user_profile', function($join) {
                $join->on('law_firms.user_id', '=', 'user_profile.user_id');
            })
            ->leftJoin("users",function($join){
                $join->on('law_firms.user_id', '=', 'users.id');    
            })
            ->leftJoin('lawyer_clients', function($join){
                $join->on('lawyer_clients.lawyer_id','=','users.id');
            })
            ->groupBy('users.id')
            ->select(DB::raw('`law_firms`.`id`,`user_profile`.`firm_name`,concat(`user_profile`.`first_name`," ",`user_profile`.`last_name`) as attorney_name,`users`.`email`,`user_profile`.`address_1`,`user_profile`.`address_2`,`user_profile`.`city`,`user_profile`.`state`,`user_profile`.`zip`,`user_profile`.`county`,`user_profile`.`phone`,`law_firms`.`premium_firm`,count(`lawyer_clients`.`id`) as clients_count,`law_firms`.`user_id`,`users`.`created_at`'))
            ->orderBy('users.id','DESC');



        return Datatables::of($lawfirm)
            ->edit_column('id','<input type="checkbox"  class="deleteRow" value="{{$id}}"/>',0)
            ->edit_column('address_1',function($model){
                return (($model->address_1?$model->address_1.",<br>":"").
                        ($model->address_2?$model->address_2.",<br>":"").
                        ($model->city?$model->city.", ":"").
                        ($model->state?$model->state." ":"").
                        ($model->zip?$model->zip:"")
                       );
            })
            ->edit_column('phone', function($model){
                return $model->phone;
            })
           ->edit_column('clients_count','@if($clients_count>0)<a href="{{{ URL::to(\'admin/client/\' . $user_id . \'/clientlist\' ) }}}">{{$clients_count}}</a>@else {{$clients_count}} @endif')
            ->edit_column('premium_firm', '@if ($premium_firm=="1") <span class="glyphicon glyphicon-ok"></span> @else <span class=\'glyphicon glyphicon-remove\'></span> @endif')
            ->add_column('actions', '<a href="{{{ URL::to(\'admin/lawfirm/\' . $id . \'/view\' ) }}}" class="btn btn-info btn-sm" title="View"><span class="glyphicon glyphicon-eye-open"></span></a>
                    <a href="{{{ URL::to(\'admin/lawfirm/\' . $id . \'/edit\' ) }}}" class="btn btn-info btn-sm"  title="{{ trans("admin/modal.edit") }}"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a href="{{{ URL::to(\'admin/lawfirm/\' . $id ) }}}" class="btn btn-sm btn-primary deleteRowBtn" title="{{ trans("admin/modal.delete") }}"><span class="glyphicon glyphicon-trash"></span></a>
                    <input type="hidden" name="row" value="{{$id}}" id="row">')
            ->edit_column('created_at', function($model){
                if(strtotime($model->created_at)){
                    return date("d-m-Y", strtotime($model->created_at));
                }else{
                    return '';
                }
            })
            ->remove_column('address_2')
            ->remove_column('zip')
            ->remove_column('city')
            ->remove_column('state')
            ->make(true);
```
### System details
- Operating System : Ubuntu linux
- PHP Version : 5.6
- Laravel Version : 5.1
- Laravel-Datatables Version : ~6.0

**Comment by yajra** [comment]
I suggest you try executing the queries generated on your SQL app manually and see which queries are taking so much time to execute. On my personal experience, there are queries where count took 3min to execute so you would need to count your records in an optimize way. To do this, see this [manual count demo](https://datatables.yajrabox.com/eloquent/manual-count).

**Comment by maheshtc** [comment]
Thanks for your reply,
There is two queries executed.
1)
`select count(*) as aggregate from (select `law_firms`.`id`,`user_profile`.`firm_name`,concat(`user_profile`.`first_name`," ",`user_profile`.`last_name`) as attorney_name,`users`.`email`,`user_profile`.`address_1`,`user_profile`.`address_2`,`user_profile`.`city`,`user_profile`.`state`,`user_profile`.`zip`,`user_profile`.`county`,`user_profile`.`phone`,`law_firms`.`premium_firm`,count(`lawyer_clients`.`id`) as clients_count,`law_firms`.`user_id` from `law_firms` left join `user_profile` on `law_firms`.`user_id` = `user_profile`.`user_id` left join `users` on `law_firms`.`user_id` = `users`.`id` left join `lawyer_clients` on `lawyer_clients`.`lawyer_id` = `users`.`id` where `law_firms`.`deleted_at` is null group by `users`.`id`) count_row_table`
It takes time 0.1870 seconds on **LOCAL SERVER PHPMYADMIN** and 0.2602 on Server Phpmyadmin.

2)
`select `law_firms`.`id`,`user_profile`.`firm_name`,concat(`user_profile`.`first_name`," ",`user_profile`.`last_name`) as attorney_name,`users`.`email`,`user_profile`.`address_1`,`user_profile`.`address_2`,`user_profile`.`city`,`user_profile`.`state`,`user_profile`.`zip`,`user_profile`.`county`,`user_profile`.`phone`,`law_firms`.`premium_firm`,count(`lawyer_clients`.`id`) as clients_count,`law_firms`.`user_id` from `law_firms` left join `user_profile` on `law_firms`.`user_id` = `user_profile`.`user_id` left join `users` on `law_firms`.`user_id` = `users`.`id` left join `lawyer_clients` on `lawyer_clients`.`lawyer_id` = `users`.`id` where `law_firms`.`deleted_at` is null group by `users`.`id``

It takes 0.1482  Seconds on local phpmyadmin and 0.3262 Seconds on Server Phpmyadmin  

These queries hardly take 1 sec by combining both. But in datatable it takes around 1 min. Please tell me where I am doing wrong.

**Comment by yajra** [comment]
Hmm, then I guess there is something else going on that's taking the execution time. Maybe try using [laravel debugbar](https://github.com/barryvdh/laravel-debugbar)? I personally use this to trace this kind of issues.

**Comment by yajra** [comment]
Closing old issues. Please open a new one if needed. Thanks!
