### ISSUE TITLE
Error using all() in query() method implementing DataTables as a service

### ISSUE THREAD

**Issue by HarleyFuagras** [yajra/laravel-datatables#628]
### Summary of problem or feature request

Hi,
I have a model Role with a related table that contains the role translations. I am using [dimsav translatable](https://github.com/dimsav/laravel-translatable) and the only translated field is 'name'.

Before refactoring my site to implement DataTables as a service I was able to show a table with name, created_at and updated_at columns having the following method called as the table ajax url.

```php
/**
     * Get resource datatable.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexData()
    {
        $roles = Role::all();
        $datatables = Datatables::of($roles);
        return $datatables->make(true);
    }
```
Now, in my RolesDataTable class, in the query method I have...

```php
/**
     * Get the query object to be processed by datatables.
     *
     * @return \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder
     */
    public function query()
    {        
        $roles = Role::join('role_translations', 'roles.id', '=', 'role_translations.role_id')
        ->select([
            'roles.id as id',
            'role_translations.name',
            'roles.created_at',
            'roles.updated_at',
        ])
        ->where('locale', config('app.fallback_locale'))
        ->groupBy('roles.id');

        return $this->applyScopes($roles);
    }
```
And it works smoothly, but I would like to be able to not have to specify the join in the query as I could before. But if I try to use all() there, as all() returns a collection and not a query I get an error. Is there a way I can achieve this? Thank you very much.

### System details
- Windows 7
- Laravel 5.2
- Laravel-Datatables ~6.0

**Comment by aleixfabra** [comment]
👍

**Comment by standaniels** [comment]
I'm not able to test this right now, but can't you select all columns by using ``Role::select(['*'])``, or something simular?

**Comment by HarleyFuagras** [comment]
I tried that. Actually you can do it by not calling the select method at all, but when I do I get a MySQL error saying 

> Column already exists: 1060 Duplicate column name id

caused -I think- because we are joining two tables with its own id's and there is an ambiguity problem then.

**Comment by yajra** [comment]
@HarleyFuagras, there are some conditions when setting the column if you are using join statements. See this [demo](https://datatables.yajrabox.com/eloquent/joins) for ref:
