### ISSUE TITLE
Service Implementation - Create Summary Row in Excel Export

### ISSUE THREAD

**Issue by smccoy78** [yajra/laravel-datatables#631]
### Summary of problem or feature request

Is it possible to include the summary row when exporting records to excel? I am using the service implementation.

### System details

- Operating System: Windows 10 Professional (Workstation) / Ubuntu Server 14.04 (Server)
- PHP Version: 5.5.9-1
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.10.1

**Comment by yajra** [comment]
@smccoy78, Yes it's possible but you need to manually write your excel by overriding:
```php
    /**
     * Build excel file and prepare for export.
     *
     * @return \Maatwebsite\Excel\Writers\LaravelExcelWriter
     */
    protected function buildExcelFile()
    {
        /** @var \Maatwebsite\Excel\Excel $excel */
        $excel = app('excel');

        return $excel->create($this->getFilename(), function (LaravelExcelWriter $excel) {
            $excel->sheet('exported-data', function (LaravelExcelWorksheet $sheet) {
                $sheet->fromArray($this->getDataForExport());
            });
        });
    }
```
