### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getQualifiedForeignKey()

### ISSUE THREAD

**Issue by mtx-z** [yajra/laravel-datatables#634]
### Summary of problem

I'm trying to get the column ordering (and filtering) working on a relations columns.
I'm using [this laravel package](https://github.com/dimsav/laravel-translatable) to manage translation.
This give me a `translations `relations on my translated models. 

To get the data, i'm doing a `->all() with('translations')`, and i can see my translations object in the ajax result. 

The package seems to anyway append the '`name`' attribute on the base object. So if my column declaration is like` {data: 'name', name: 'translations.name'}`, it works, but if i do `{data: 'translations.name', name: 'translations.name'}` it dont work anymore even if i can see the translations object in the ajax result. 

So using `{data: 'name', name: 'translations.name'}`, i got the right datas. The global search is working, and i was able to filter the column using a `whereas` on the query. 

But : 
- column ordering throw an error `getQualifiedForeignKey()`, only on this one
- column search from [here](https://datatables.yajrabox.com/eloquent/multi-filter-select) is not working also, throwing the same error (even if global search work on this column values!), works great on other column (except count column but not important and not related)

### Code snippet of problem
JS
```
 var columns = [
                {data: 'id', name: 'account_category.id'},
                {data: 'name', name: 'translations.name'}, //the one partially working
                {data: 'account_type_id', name: 'account_category.account_type_id'},
                {data: 'sort_order', name: 'account_category.sort_order'},
                {data: 'user_count', name: 'user_count', searchable: false},
                {data: 'created_at', name: 'account_category.created_at'},
                {data: 'updated_at', name: 'account_category.updated_at'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ];
```

PHP
   ```
$data = $this->mainRepo->all('', '', ['*'], ['translations'], true);
 public function returnDataTable($data) {
        $dt = app('datatables')->of($data)
            ->editColumn(
                'account_type_id', function ($account_cat) {
                return $account_cat->accountType->name;
            })
            ->addColumn(
                'user_count', function ($account_cat) {
                return $account_cat->user->count();
            })
            ->addColumn(
                'action', function ($account_cat) {
                return $account_cat->action_buttons;
            });

        //we cannot filter on relation (like translation) here as no whereHas available, only filter on object attributes
        if ($p = Input::get('params')) {
            foreach ($p as $attr => $value) {
                if (strstr($attr, 'translated'))
                    continue;
                $dt->where('account_category.' . $attr, 'like', "%$value%");
            }
        }

        return $dt->make(true);
    }
```

Code i use to make external filtering on translated attributes (filtering the query directly): 
```
        if ($p = Input::get('params')) {
            foreach ($p as $attr => $value) {
                if (strstr($attr, 'translated')) {
                    $attr = str_replace("translated_", "", $attr);
                    $users->whereHas('translations', function ($query) use ($attr, $value) {
                        $query->where('locale', App::getLocale())
                            ->where($attr, 'like', "%$value%");
                    });
                }
            }
        }
```

### System details

- Win 8.1
- 7.x
- 5.1
- Latest from composer

Thanks a lot again for the help.

**Comment by ChaosPower** [comment]
@mtx-z you're invoking collection instead of builder / eloquent class.

```php
$data = $this->mainRepo->all('', '', ['*'], ['translations'], true);
```

You do not need to ->all. Laravel Datatables does that automatically. When you use all() method you are calling Laravel's collection which you cannot issue SQL queries.

**Comment by mtx-z** [comment]
Hey, thanks for answsering. 

Actually, the 'mainRepo' is an instance of my repository, wich will make the ->all() call. 

So, if I understand, i should always give to datatable a instance of builder OR eloquent, and no collection/result, right ?

**Comment by standaniels** [comment]
> So, if I understand, i should always give to datatable a instance of builder OR eloquent, and no collection/result, right ?

That's correct.
