### ISSUE TITLE
Getting the error "DataTables warning: table id=pages-table - Invalid JSON response"

### ISSUE THREAD

**Issue by ChubbyBalboa** [yajra/laravel-datatables#635]
### Summary of problem
I'm trying to get the basic implementation working but I am getting this error message: 

> Uncaught Error: DataTables warning: table id=pages-table - Invalid JSON response.

This is the response in the Network tab in devtools
> <?php{"draw":1,"recordsTotal":2,"recordsFiltered":2,"data":[{"title":"fgdhdfgh"},{"title":"Home"}],"queries":[{"query":"select count(*) as aggregate from (select '1' as `row_count` from `pages`) count_row_table","bindings":[],"time":0.17},{"query":"select `title` from `pages` order by `title` asc limit 10 offset 0","bindings":[],"time":0.17}],"input":{"draw":"1","columns":[{"data":"title","name":"title","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}}],"order":[{"column":"0","dir":"asc"}],"start":"0","length":"10","search":{"value":"","regex":"false"},"_":"1468188553838"}}

### Code snippet of problem

Controller:
```
public function data()
{
    $pages = Page::select(['title']);
    return Datatables::of($pages)->make(true);
}
```

Route:
`Route::get('pages/data', [ 'as' => 'admin.pages.data', 'uses' => 'PageController@data']);`

JS:
```
$(function() {
    $('#pages-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{!! route('admin.pages.data') !!}",
        columns: [
            { data: 'title', name: 'title' }
        ]
    });
});
```

### System details

- PHP Version - 7.0.1
- Laravel Version - 5.2
- Laravel-Datatables Version - 6.0

**Comment by yajra** [comment]
It seems like the response have some <?php tag on it and that's weird. Did you made some changes on the vendor codes by any chance? I suggest try tracing where did that php tag came from or it's just a typo here?

**Comment by ChubbyBalboa** [comment]
@yajra Nope, no changes to vendor codes or any typos. I'll delete everything and try again.

**Comment by ChubbyBalboa** [comment]
So I found the issue.. My application is modular and each module has its own routes.php, the main routes.php file that comes with laravel just had <?php in it which was added to the response somehow.

**Comment by kcifuentes** [comment]
Hi @ChubbyBalboa 
I have the same problem, how you fixed?

**Comment by ChubbyBalboa** [comment]
@kcifuentes I had a routes.php file that only contained "<?php". I just cleared the routes.php file.

**Comment by kcifuentes** [comment]
@ChubbyBalboa Thanks for your help, I had the same error but in a different file.

**Comment by designer999** [comment]
kcifuentes hi i have sam issue can u help me please
