### ISSUE TITLE
Ajax error 500: Converting raw SQL to Query Builder

### ISSUE THREAD

**Issue by hoanguel** [yajra/laravel-datatables#638]
### Summary of problem

Hi, from previous closed issues I know that I will need to convert to Query Builder since I have a raw SQL query. I did it similar like what was instructed but it is not working.

Here is the one that work:
```php
$results = DB::table('test')->select(['name', 'age', 'gender']);
 return Datatables::of($results)->make(true);
```
and here is the one that doesn't:
```php
$sql="SELECT name, age, gender FROM test WHERE 1=1 AND age='50' AND gender='M' ORDER BY name ASC";
$results=DB::table(DB::raw("$sql as results"))->get();
return Datatables::of($results)->make(true);
```
I would be very grateful for any given help / advice. Thank you!

### System details

- Operating System: Windows 7 
- PHP Version: 5.5.12
- Laravel Version: 5.1
- Laravel-Datatables Version: 6.0

**Comment by yajra** [comment]
I think you should use something like below and remove the get() method.

```php
$sql="SELECT name, age, gender FROM test WHERE 1=1 AND age='50' AND gender='M' ORDER BY name ASC";
$results=DB::table(DB::raw("($sql)"));
return Datatables::of($results)->make(true);
```

**Comment by hoanguel** [comment]
Thank you very much :)

**Comment by BaelishLord** [comment]
@yajra Need your help

```
$sql="SELECT brands_id,brand_name,brand_code FROM brands where brands_id = 2";
$results=\DB::table(\DB::raw("($sql)"));
return Datatables::of($results)->make(true);
```

using the same but getting error as below

`error: "Exception Message:↵↵SQLSTATE[42000]: Syntax error or access violation: 1248 Every derived table must have its own alias (SQL: select count(*) as aggregate from (select '1' as `row_count` from (SELECT brands_id,brand_name,brand_code FROM brands where brands_id = 2)) count_row_table)"`

"yajra/laravel-datatables-oracle": "~9.0"
"laravel" : "6"

**Comment by yajra** [comment]
@BaelishLord why not use the query builder instead of the raw query?

```php
$query = DB::table('brands')->select('brands_id' ,'brand_name', 'brand_code')->where('brands_id', 2);

return datatables()->query($query)->toJson();
```

**Comment by BaelishLord** [comment]
@yajra This helps!! Thank you.

But I do have complex long queries which are difficult to convert in this format, is there a way to deal better with just raw select queries and pass in the complete query to the datatables?
