### ISSUE TITLE
FilterColumn on relations

### ISSUE THREAD

**Issue by kife-design** [yajra/laravel-datatables#639]
Hello,

I am using the plugins with much success.
I am struggling with one aspect thou.

I would like to filter a column on a relation.

I have the following code:

`$trainingParticipants = TrainingParticipant::select('training_participants.*')->with(
            'training',
            'training.costCenter',
            'participant',
            'participant.sbeFunction',
            'participant.department'
        );

        return $datatables
            ->of($trainingParticipants)
            ->addRowAttr(
                'onclick',
                function ($trainingParticipant) {
                    return 'trainings.editTraining("' . id($trainingParticipant->training->id) . '")';
                }
            )
            ->editColumn(
                'participant.name',
                function ($training) {
                    return $training->participant->name . ' ' . $training->participant->surname;
                }
            )
            ->editColumn(
                'training.evaluated',
                function ($training) {
                    return $training->evaluated ? 'Yes' : 'No';
                }
            )
            ->filterColumn('training.evaluated', function($query, $keyword) {
                $yesValues = ['y', 'e', 's', 'yes'];
                $noValues = ['n', 'o', 'no'];

                if(in_array(strtolower($keyword), $yesValues)) {
                    $query->where('training_participants.training.evaluated', '=', 1);
                } elseif(in_array(strtolower($keyword), $noValues)) {
                    $query->where('training_participants.training.evaluated', '=', 0);
                } else {
                    $query->where('training_participants.training.evaluated', '>', 1);
                }
            })
            ->make(true);`

So i have a column 'evaluated', which is saved to the database as 0 or 1, and this column is edited to show in the datatables as 'yes' or 'no', now the problem is when they are searching (using the column search) and they type 'yes', then i need to transform that value to 0 or 1. the item i need to check this against is a relation, so the problem here is that i get an error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'training_participants.training.evaluated' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `training_participants` where (`training_participants`.`training`.`evaluated` = 1)) count_row_table)`

Any chance you can push me in the right direction?

**Comment by yajra** [comment]
I think there is a mistake on your query, I think it should be like below:
```php
if(in_array(strtolower($keyword), $yesValues)) {
    $query->where('training.evaluated', '=', 1);
} elseif(in_array(strtolower($keyword), $noValues)) {
    $query->where('training.evaluated', '=', 0);
} else {
    $query->where('training.evaluated', '>', 1);
}
```

**Comment by kife-design** [comment]
That is giving me the same exception:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'training.evaluated' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as 'row_count' from 'training_participants' where ('training'.'evaluated' = 1)) count_row_table)`

**Comment by yajra** [comment]
Hmm, It seems like the related table is not being joined on query because you override the default filter. Maybe try modifying the request instead of using `filterColumn`?

**Comment by yajra** [comment]
Or maybe you should manually join the training table inside the filterColumn like:

```php
$query->join('training', 'training.id', '=', 'training_participants.training_id');

if(in_array(strtolower($keyword), $yesValues)) {
    $query->where('training.evaluated', '=', 1);
} elseif(in_array(strtolower($keyword), $noValues)) {
    $query->where('training.evaluated', '=', 0);
} else {
    $query->where('training.evaluated', '>', 1);
}
```
