### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by karthikastra** [yajra/laravel-datatables#64]
Hello,

I am using version 4.3.2 in a laravel 5 project using datatable 1.9. On clicking the column heading the request sends the correct column order and column direction but the query does not contain the order by clause.

When i debugged, i found the following line in method doOrdering

$columns = $this->cleanColumns($this->last_columns);

I could not find any other reference where the last_columns is getting populated. When i changed that to $this->columns the ordering started working.

Can you please check and let me know if this a correct fix

thanks,
Karthik

**Comment by yajra** [comment]
Hi @karthikastra,

Yes, that cleanColumns is somewhat deprecated and was already fixed on v5.x. Will review v4.x and try to fix this. Will let you know when it's done thru this issue.

Thanks for reporting!

**Comment by yajra** [comment]
@karthikastra can you please provide some snippets of your controller and your js?

Btw, if you can upgrade to DT1.10.x / v5.x, then I suggest you do because 4.x branch will not be updated unless a major bug fix is required. Thanks!

**Comment by karthikastra** [comment]
Hi @yajra ,

Please find below the code

Controller
```
class PlanController extends Controller {

	public function search() {

		$plans = Plan::select(array('plans.id', 'plans.plan_name', 'plans.projects_allowed', 'plans.trial_allowed', 'plans.deleted_at'));

		return Datatables::of($plans)
			->edit_column('trial_allowed', '@if($trial_allowed) <span class="label label-primary">Yes</span> @else <span class="label label-default">No</span> @endif')
			->edit_column('deleted_at','@if($deleted_at)  <span class="label label-danger">Deleted</span> @else <span class="label label-primary">Active</span> @endif')
            ->make(true);
	}

}
```

View code

```
 <table id="plans-table" class="display table table-bordered">
	<thead>
    	<tr>
	        <th>Id</th>
	        <th>Plan Name</th>
	        <th>Projects Allowed</th>
	        <th>Trial Allowed</th>
	        <th>Status</th>
	        <th>Actions</th>
	    </tr>
    </thead>
</table>

<script type="text/javascript">
    $(function() {
        $('#plans-table').dataTable({
            bProcessing: true,
            bServerSide: true,
            sAjaxSource: "{{ route('plans.search') }}",
            aoColumnDefs: [
                {mData: 'id', bVisible: false, bSearchable: false, bSortable: false, aTargets: [0]},
                {mData: 'plan_name', aTargets: [1]},
                {mData: 'projects_allowed', bSearchable: false, aTargets: [2]},
                {mData: 'trial_allowed', aTargets: [3]},
                {mData: 'deleted_at', aTargets: [4]}
            ],
            aaSorting: [[1, 'asc']],
            sPaginationType: "bootstrap"
        });
    });
```

**Comment by yajra** [comment]
@karthikastra sorry for the delay in fixing this. can you please try pulling v4.3.3 and verify if the issue was fixed? thanks!

**Comment by karthikastra** [comment]
Hi @yajra thanks its working now :)

**Comment by mifas** [comment]
Hey @yajra I'm using L4 for laravel 4.2, Still sorting is not working. Can you please check

**Comment by yajra** [comment]
@mifas the patched I've done was for v4.x. If you're using L4 then we also need to create a patch on v3.x. Please create a new issue for that. Closing this one. Thanks!
