### ISSUE TITLE
[Announcement] v6.15.2 Breaking Change

### ISSUE THREAD

**Issue by yajra** [yajra/laravel-datatables#643]
Since the release of v6.15.2, an unintended breaking change occurs specifically on Carbon object with blade syntax. Before the update, we can access the carbon instance on model's date on blade string syntax like `->editColumn('created_at', '{{ $created_at->format('Y') }}')`. But allowing this feature causes a **critical issue** like #565 where record is being deleted.

Moving forward, please use closure if you want to access the Carbon instance of the model like:

``` php
->editColumn('updated_at', function (User $user) {
    return $user->updated_at->format('Y/m/d');
})
```

Carbon demos were also updated to reflect the changes:
https://datatables.yajrabox.com/eloquent/carbon
https://datatables.yajrabox.com/fluent/carbon
https://datatables.yajrabox.com/collection/carbon

Sorry for those who will get affected on this breaking change. 

Thanks,

@yajra

**Comment by ctoma** [comment]
I can confirm this latest commit solved the issue, thanks @yajra !
