### ISSUE TITLE
Data is not show in a view blade but it has loaded.

### ISSUE THREAD

**Issue by yong0011** [yajra/laravel-datatables#645]
### Data is not show in a view blade but it has loaded.

I'm new for Laravel 5.2 and trying to use laravel-datatables from Quick Starter Tutorial
and I follow almost every step of that tutorial .

but when I try this URL
[http://localhost/blog/public/datatables](url)

  it show the empty table with header of table.

and when I try this URL
[http://localhost/blog/public/datatables/data](url)

it show all of the Users record correctly looks like it is string array.

Now I can't find how to fix this problem or my mistake.
please help me or advice me how to fix that
Thank you so much and apologize for my bad English.

There is my code :
### Code snippet of problem

layouts.main
```php
    {!! Html::style('assets/css/bootstrap.min.css')!!}
    {!! Html::style('assets/css/datatables.min.css')!!}
     .
     .
    {!! Html::script('assets/js/jquery.min.js')!!}
    {!! Html::script('assets/js/bootstrap.min.js')!!}
    {!! Html::script('assets/js/datatables.min.js')!!}
```

DatatablesController.php
```php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\User;
use Yajra\Datatables\Datatables;

class DatatablesController extends Controller
{
    public function getIndex()
    {
        return view('datatables.index');
    }

    public function anyData()
    {
        return Datatables::of(User::query())->make(true);
    }
}
```

index.blade.php
```php
@extends('layouts.main')

@section('content')
    <table class="table table-bordered" id="users-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>Updated At</th>
            </tr>
        </thead>
    </table>
@stop

@push('scripts')
<script>
$(function() {
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.data') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'created_at', name: 'created_at' },
            { data: 'updated_at', name: 'updated_at' }
        ]
    });
});
</script>
@endpush
```
and this is my route
```php
Route::controller('datatables', 'DatatablesController', [
    'anyData'  => 'datatables.data',
    'getIndex' => 'datatables',
]);
```

### System details

- Operating System Windows 8.1 use XAMPP 5.6.21
- PHP Version 5.6.21
- Laravel Version 5.2.39
- Laravel-Datatables Version 6.15.2
-jQuery Version 2.1.4

**Comment by yajra** [comment]
Maybe you don't have a `@stack('scripts')` on your layout?

**Comment by yong0011** [comment]
@yajra I try to put it on <head> of main.layout but it still not work.

Sorry for my slow response, that was weekend.

**Comment by yong0011** [comment]
Oh , It work if I change `ajax: '{!! route('datatables.data') !!}',` to ` ajax: '{{ url("datatables/data") }}',` and insert `@stack('script')`

Thanks for your advice ^^

**Comment by iLongRanger** [comment]
Hi ! i am exactly having the same issue , and im a little confused as to where should i put @stack('script'). may I now where exactly should i put this  ?

**Comment by swati-clarion** [comment]
Hi,
I had excatly same issue and after lot of searching, I was able to sort it this ways. 
In your layout blade file , before closing html , include following scripts :

    <script src="{{ asset('js/app.js') }}"></script>	
	<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
	@yield('script')

And in your datatable.blade.php file,  instead of ending section content , use @stop and add @section('script').

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Data Table Demo</div>

                <div class="panel-body">
                    <table class="table table-hover table-bordered table-striped datatable" style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('script')
<script type="text/javascript">
$(document).ready(function() {
    $('.datatable').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ route('datatable/getdata') }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
        ]
    });
});
</script>
@endsection

This includes ajax script properly at end of file. Hope this helps for anyone who is facing same issue.
