### ISSUE TITLE
How filtering in DataTables as a service Implementation

### ISSUE THREAD

**Issue by NikDevPHP** [yajra/laravel-datatables#654]
### Filtering in DataTables as a service Implementation

How can I use filtering in DataTables as a service Implementation with out js code?

### System details
- Windows 8.1
- PHP 5.6
- Laravel 5.2
- Latest from composer

**Comment by yajra** [comment]
See this tuts for ref: https://datatables.yajrabox.com/service

**Comment by NikDevPHP** [comment]
Did you read my question ? I asked about filtering for service case. There's nothing here..
 https://datatables.yajrabox.com/service
