### ISSUE TITLE
sort by count column using eloquent model

### ISSUE THREAD

**Issue by nichworks** [yajra/laravel-datatables#656]
How do I sort by a count column of related items. It keeps telling me column name doesnt exist in the sql response from ajax

All the data and columns load perfectly fine in the table.
I can sort all columns except the count records column when clicked

the following is an example code, as I cannot share the real code due to NDA. If there are any typos, please assume the typo is actually correct on my end as im not experiencing a typo error.

the following is the same code im using with names switched to books and authors for examples

i have the following tables

1. authors
2. authors_address
3. authors_phonenumbers
4. authors_company
5. authors_books

```
$request = Authors::select(['authors.record_id','authors.Name' ])
  
  ->where('authors.created_at', '>=', Carbon::now()->yesterday())

  ->with(['address' => function($query){
	$query->select('address', 'Name');
  }])
  
  ->with(['phone' => function($query){
	$query->select('cellphone', 'Name');
  }])
  
  ->with(['company' => function($query){
	$query->select('companyname', 'Name');
  }])
    
 ->with(['countbooks' => function($query){
	$query->select( DB::raw('COUNT(book) AS bookcount'), 'Name'  )->groupBy('Name');
	}]);
```

```
JS

var oTable = $('#authorstable').DataTable({
    processing: true,
    serverSide: true,
    ajax: {
      url: '/authorstable'
    },
    columns: [{
      data: 'authorname'
    },{
      data: 'authors_address.address'
    },{
      data: 'authors_phonenumbers.cellphone'
    },{
      data: 'authors_company.companyname'
    }, {
      data: 'authors_books.0.numberofbooks'
    },]
});
```

final output

Name | Address  | Phone | Company | # of books
------------ | ------------- | ------------- | ------------- | -------------
John | 123 main st | 123-123-1234 | abc corp | 10
Adam | 321 main st | 123-123-1234 | xyz corp | 2
Jane | 111 main st | 123-123-1234 | acme corp | 12

When I click on # of books column to sort asc or desc, thats when i get an issue. All other columns sort just fine

**Comment by yajra** [comment]
Unfortunately, counting of books like on your example is not yet supported by the package. You would have to use join and group sql statements if you want it to be orderable.

**Comment by nichworks** [comment]
ok, that is what I have done for now...

any idea when you might integrate this?

**Comment by yajra** [comment]
@nichworks cannot commit on when I can integrate this. But we are open to PR if you can implement this. Thanks!

**Comment by GoldenSwaroop** [comment]
->with(['countbooks' => function($query){
    $query->select( DB::raw('COUNT(book) AS bookcount'), 'Name'  )->groupBy('Name');
    }]);
Replace By
->withCount('countbooks')

uses
countbooks_count
