### ISSUE TITLE
Erro 404  NotFoundHttpException in RouteCollection.php line 161:

### ISSUE THREAD

**Issue by luizpatrocinio** [yajra/laravel-datatables#658]
![erro2](https://cloud.githubusercontent.com/assets/16004201/17033925/6b249168-4f4e-11e6-9016-cce5a8f7b768.jpg)

My Controller

  public function api()
    {
        $dados = $this->audiencia->select('id', 'processo', 'cliente' ,'tel', 'cparte', 'dtaudiencia', 'hraudiencia', 'local', 'tipo')->where('ativo', 1);
        return Datatables::of($dados)
        ->addColumn('action', function($id)
        {
            return '<a href="/audiencia/avisado/'.$id->id.'/get?ativo=0" class="btn btn-xs btn-primary"> Avisado</a>';
        })->make(true);
    }

My js:

$(function() {
    //$.fn.dataTable.ext.errMode = 'throw';
    $('#tabela').DataTable({
        "processing": true,
        "serverSide": true,
        "language": { "url": "/datatables/pt.br" },
        "ajax": "/audiencia/api/",
       
        "columns":
        [
        { data: "processo" },
        { data: "cliente" },
        { data: "tel" },
        { data: "cparte" },
        { data: "dtaudiencia" },
        { data: "hraudiencia" },
        { data: "local" },
        { data: "tipo" },
        { data: "action", name: "action", orderable: false, searchable: false }
        ]
       
    });

});

![erro1](https://cloud.githubusercontent.com/assets/16004201/17033960/96a3f0ea-4f4e-11e6-980c-9b0f0053f04d.jpg)

**Comment by luizpatrocinio** [comment]
My js
![erro1](https://cloud.githubusercontent.com/assets/16004201/17034008/c2c8b43a-4f4e-11e6-89f5-2a7138ff0b48.jpg)

$(function() {
    //$.fn.dataTable.ext.errMode = 'throw';
    $('#tabela').DataTable({
        "processing": true,
        "serverSide": true,
        "language": { "url": "/datatables/pt.br" },
        "ajax": "/audiencia/api/",
       
        "columns":
        [
        { data: "processo" },
        { data: "cliente" },
        { data: "tel" },
        { data: "cparte" },
        { data: "dtaudiencia" },
        { data: "hraudiencia" },
        { data: "local" },
        { data: "tipo" },
        { data: "action", name: "action", orderable: false, searchable: false }
        ]
       
    });

});

**Comment by nichworks** [comment]
did you add /audiencia/api/ to your routes.php file?

Route::get('audiencia.api', array('uses' => 'MyController@api'));

**Comment by luizpatrocinio** [comment]
Tks Nic,

See

Route::get('/audiencia/api', 'Painel\AudienciaController@api');

And sometimes it works. Very strange.

**Comment by nichworks** [comment]
so the table does load? sometimes? Is there something that breaks it?

**Comment by luizpatrocinio** [comment]
Tks Nic,

Yes sometimes carries no errors. When bears come all right.

**Comment by luizpatrocinio** [comment]
When work is so.

![ok](https://cloud.githubusercontent.com/assets/16004201/17040508/17ed69f0-4f6e-11e6-874d-6504092e5477.jpg)

**Comment by yajra** [comment]
@luizpatrocinio what is your dev environment? My guess is that you are using artisan serve. There are several related issues like this which is mainly cause by it. Try using homestead or valet for more stable environment.

**Comment by luizpatrocinio** [comment]
Yajra grateful, I have many views working very well this only has problem. And it works sometimes.
My environment:

        "Laravel / framework": "5.2. *"
        "Yajra / laravel-datatables-oracle", "~ 6.0"

**Comment by luizpatrocinio** [comment]
Oops, using Apache see what happened.

![erro3](https://cloud.githubusercontent.com/assets/16004201/17066658/06c8f51a-5016-11e6-98a5-05850871b8b1.jpg)

**Comment by luizpatrocinio** [comment]
I follow this recommendation is correct that? It seems that solved.

In App / bootstrap / autoload.php
add
ini_set ('xdebug.max_nesting_level', 200);

**Comment by luizpatrocinio** [comment]
Tks nichworks, Yajra 

It Wokrs:

In App / bootstrap / autoload.php
add
ini_set ('xdebug.max_nesting_level', 200);
