### ISSUE TITLE
Column Search Not Working

### ISSUE THREAD

**Issue by hohuuhau** [yajra/laravel-datatables#659]
### Summary of problem or feature request

Hi, i'm using Column Search, but it not working, it only display data (not show column search)
[Images Demo](http://imgur.com/a/HF0z8)

Thanks you!
Hau Ho

### System details

- Operating System
- PHP Version 5.5.9
- Laravel Version 5.2
- Laravel-Datatables Version 6.0

**Comment by yajra** [comment]
Did you add `tfoot>tr>th` on your table markup?

**Comment by hohuuhau** [comment]
I'm forgot it, sorry :+1: 
Thanks yajra,

**Comment by prajapatim** [comment]
Thanks Yajra
