### ISSUE TITLE
SQL Aliases problem,

### ISSUE THREAD

**Issue by haytamkh** [yajra/laravel-datatables#66]
when building a table with select aliases like select client.id as clientid there is a bug on sorting and searching, 
doOrdering function was fixed by adding :
if (strpos($this->columns[$order_col],' as ') !== false) {
   $this->columns[$order_col]=explode(' as ',$this->columns[$order_col]);
 $this->columns[$order_col]=trim($this->columns[$order_col][0]);							
}

**Comment by yajra** [comment]
when using alias, you need to define in your js the actual column name that will be used for sorting and searching. The column name are being fetch on `columns.name` definition on your js.

```js
columns: [
            {data: 'id', name: 'id'},
            {data: 'alias', name: 'name'}
        ]
```

On some cases, alias are sortable but it's not searchable. In that case, you need to override the default global search on that column by using `filterColumn` function.

**Comment by yajra** [comment]
@haytamkh any updates on this? btw, what version of the package are you using? thanks!

**Comment by haytamkh** [comment]
i'm using datatables v1.10.7 and laravel-datatables v5.x , this issue was fixed by using your suggested solution , i was looking for more generic way to define columns in js to match all cases on my project 
Thanks you

**Comment by yajra** [comment]
great! closing the issue. If you need more example codes, you can check the [demo site](http://datatables.yajrabox.com/) for reference.
