### ISSUE TITLE
sort and search with 2 "belongs to" relation

### ISSUE THREAD

**Issue by gabva** [yajra/laravel-datatables#660]
Hi,

Thank you for this great package.
I have a problem when i'm trying to make searchable a field with 2 belongs to : 

example : 

 my controller :

``` php
 $matches = Match::with('matchday.competition', 'team1', 'team2') //match belongs to matchday belongs to competition
```

my view : 

 `
{ data: 'matchday.competition.name', name: 'matchday.competition.name },
`

Searching and sorting cause an error in that case.
I've tried a lot of change but the only solution i've found is to disable searching and sorting

Am i making something wrong or that's just this feature is not available ?

Thanks in advance :)

**Comment by yajra** [comment]
@gabva, I think 2 or more levels of eager loading is not yet fully supported. I haven't tried it personally so I am not so sure.

**Comment by yajra** [comment]
@gabva can you please test this again on the latest version 6.18.0? There was a bug on relation search that was just fixed. Thanks!

**Comment by tad3j** [comment]
Hey,
Thanks from me as well. Everything has been working great except ordering 2 levels deep, which I think is related to OP problem.

I'm using MorhOne/To relation and my query builder code looks like this:

` ->with(['promoListing.onlineListing' => ....])`

...which loads the data perfectly fine, but ordering fails for some reason, with exception saying that relation "promoListing.onlineListing" doesn't exist. I've played around with tinker and that relationship is available there, so I think the problem may be deeper.

Here is the stack trace:
http://screencast.com/t/oUy8E9Ufs0

I'm using v6.21.1.

**Comment by yajra** [comment]
This should be fixed on the latest version. See this demo for ref: https://datatables.yajrabox.com/relation/belongs-to
Thanks!
