### ISSUE TITLE
Error on relationship one-to-one

### ISSUE THREAD

**Issue by jgcl** [yajra/laravel-datatables#661]
I have problems in my datatables search.

My view works correctly, but when performing a search the laravel generates an error:

``
QueryException in Connection.php line 725:
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select count(*) as aggregate from (select '1' as `row_count` from `projetos` inner join `parceiros` on `projetos`.`parceiro_id` = `parceiros`.`id` where (LOWER(`id`) LIKE %%sea%% or LOWER(`nome`) LIKE %%sea%% or LOWER(`parceiro`) LIKE %%sea%% or LOWER(`created_at`) LIKE %%sea%% or LOWER(`id`) LIKE %%sea%%)) count_row_table)
`

My controller

public function listAjax()	{

	return Datatables::queryBuilder(
		DB::table('projetos')
			->join('parceiros', 'projetos.parceiro_id', '=', 'parceiros.id')
			->select('projetos.id', 'projetos.nome', 'projetos.created_at', 'parceiros.nome as parceiro')
	)->make(true);

}

Tips?

**Comment by yajra** [comment]
Since you are using join statement, please follow this demo to avoid ambiguous column name issues. https://datatables.yajrabox.com/eloquent/joins
