### ISSUE TITLE
When sorting relation primary id changes to relation id.

### ISSUE THREAD

**Issue by koenvdheuvel** [yajra/laravel-datatables#662]
When sorting on a hasMany relation the ID of the item changes to the ID of the relation in the datatables. 

This happens when adding a column with the following data:

```
[
    'data' => 'id',
    'title' => 'Id'.
    'name' => 'relations.id',
]
```

**Comment by yajra** [comment]
You need to use a select statement to avoid this issue. See https://datatables.yajrabox.com/eloquent/relationships for ref.
