### ISSUE TITLE
no search format d / m / Y

### ISSUE THREAD

**Issue by luizpatrocinio** [yajra/laravel-datatables#663]
### Summary of problem or feature request

I have a form with date tables with many fields and the date is changed on the model for the standard d / m / Y. It works to search for 2016-01-19
### Code snippet of problem

  public function api()
    {
        $dados = $this->audiencia->select('id', 'processo', 'cliente' ,'tel', 'cparte', 'dtaudiencia', 'hraudiencia', 'local', 'tipo')->where('ativo', 1);
        return Datatables::of($dados)
        ->addColumn('action', function($id)
        { 
return '<a href="/audiencia/avisado/'.$id->id.'/get?ativo=0" class="btn btn-xs btn-primary"> Avisado</a>';
        })->make(true);
    }
- Operating System Windows 10
- PHP Version 5.5.2
- Laravel Version 5.1
  Como fazer datatables pesquisar d/m/Y  ?
  Tks

**Comment by yajra** [comment]
You would have to write your own query to match the date format. Try using [filterColumn](https://datatables.yajrabox.com/eloquent/post-column-search)

**Comment by luizpatrocinio** [comment]
Hi Yajra,

Model:
public function getDtvencimentoAttribute($a)
    {
    	return Carbon::parse($a)->format('d/m/Y');
    }

Controller:
public function api()
	{
		//$dados = $this->pagamento->all();
		
		$dados = $this->pagamento->select( 'id', 'numContrato', 'parcela', 'valor', 'dtVencimento')
		->where('ativo', 1);

		    return Datatables::of($dados)->addColumn('action', function ($user)
        {
            return '<a href="/pagamento/mostrar/'.$user->id.'" class="btn btn-xs btn-primary"><i class="fa fa-pencil"></i> Detalhar</a>';
        })
        ->editColumn('id', '{{$id}}')
        ->editColumn('dtVencimento', function ($dt)
         {
         	return $dt = $dt->dtVencimento;
          	 
        })
        ->make(true);
    }
Tks.

**Comment by yajra** [comment]
See this [carbon demo](https://datatables.yajrabox.com/fluent/carbon) for ref. Thanks!
