### ISSUE TITLE
Search 2 DB columns from just 1 front-end Field

### ISSUE THREAD

**Issue by seivad** [yajra/laravel-datatables#664]
### Summary of problem or feature request

I'm trying to figure out a nice way to search a "Full Name" column on the front-end which will search both the first_name and last_name columns in the database on the back-end. Haven't had too much luck at this stage. Any advice on achieving this would be greatly appreciated.

**Comment by yajra** [comment]
You can add a hidden column for last_name and first_name and it will be included in the search like:
```js
columns: [
{data: 'first_name', visible: false},
{data: 'last_name', visible: false},
]
```

Or use filterColumn api.
