### ISSUE TITLE
display the result of editing function ajax

### ISSUE THREAD

**Issue by jakaprima** [yajra/laravel-datatables#666]
### How to display the result of editing function 

i have a problem. i can updated data without refresh. but i can't view the result without refresh in datatable

### my jquery

    $(function(){
        $("#datakeluhan").on('click', 'a.edit', function(event) {
            event.preventDefault();

        datakeluhan = event.target.parentNode.parentNode.parentNode.childNodes[2].textContent;
        postId = event.target.parentNode.parentNode.parentNode.childNodes[0].textContent;
        console.log(postId);
            $('#post-body').val(datakeluhan);
            $("#edit-modal").modal();
        });

        $("#datakeluhan").DataTable({
             processing: false,
                serverSide: true,
                ajax: '{{ url("/keluhankerusakan/getdata") }}',
                columns: [
                    { data: 'idkeluhan', name: 'idkeluhan', "orderable": true, "searchable":true},
                    { data: 'staffusername', name: 'staffusername', "orderable": true, "searchable":true},
                    { data: 'keluhan', name: 'keluhan', "orderable": true, "searchable":true },
                    { data: 'idlokasi', name: 'idlokasi', "orderable": true, "searchable":true },
                    { data: 'tanggalkeluhan', name: 'tanggalkeluhan', "orderable": true, "searchable":true },
                    { data: 'action', name: 'action', "orderable": false, "searchable":false },
                    
                ]   
        });

        $('#modal-save').on('click', function(){ 
               $.ajax({
             method: 'POST',
           url: urlEdit, 
           data: {boxkeluhan: $('#post-body').val(), postId: postId, _token: token} 
            })
                .done(function (msg){
                $(datakeluhan).text(msg['post_new']);
                $('#edit-modal').modal('hide');
                });
            });
    }); 

### in my controller
public function edit(request $request){
         $this->validate($request, [
            'boxkeluhan' => 'required'
            ]);
        $post = keluhankerusakan::find($request['postId']);
        $post->keluhan = $request['boxkeluhan']; //keluhan itu field database
        $post->update();

        return response()->json(['post_new' => $post->keluhan], 200);
    } 

I stuck here, what I should do refresh a DataTable? how to do this automaticaly?

- Operating System Windows 7
- Laravel Version 5.2
- Laravel-Datatables Version

**Comment by yajra** [comment]
You can trigger DT to draw after saving like:

```js
var oTable = $("#datakeluhan").DataTable({....});

$('#modal-save').on('click', function(){ 
    $.ajax({
         method: 'POST',
         url: urlEdit, 
         data: {boxkeluhan: $('#post-body').val(), postId: postId, _token: token} 
    })
    .done(function (msg){
         $(datakeluhan).text(msg['post_new']);
         $('#edit-modal').modal('hide');
         oTable.draw();
    });
});
```

**Comment by jakaprima** [comment]
thanks yajra it's work :)

**Comment by vilmer** [comment]
<button class="btn btn-info btn-sm" onclick="reloadTable(this);"><i class="fa fa-plus"></i> <b>Actualizar</b> </button>
{!! $dataTable->scripts() !!}
<script>
	function reloadTable() {
		var oTable = $("#dataTableBuilder").DataTable();
		oTable.draw(false);
	}
</script>
