### ISSUE TITLE
Taking input values from form and return a datatable below the form with proper query

### ISSUE THREAD

**Issue by karakanb** [yajra/laravel-datatables#668]
Hey there. 
I want to trigger datatables plugin via the submit button of my form.

My form looks like : 
![qss](https://cloud.githubusercontent.com/assets/16530606/17184894/45698918-5437-11e6-91b1-0724caf56f12.PNG)

I want to pass input values of the form to my controller due to write a query to database according to these values. And  then show the result below the form as a datatable. 

My routes : 

```
   Route::get('qualityscore', ['as'=>'qualityscorereport', 'uses'=> 'KeywordsController@GetQualityScore']);
      Route::get('qualityscore-ajax', ['as'=>'postqualityscorereport', 'uses'=> 'KeywordsController@PostQualityScore']);
```

My js code in blade.php : 

```
`$(document).ready(function() {
          $('#formqs').submit(function() {
              $('#qualityScoreDatatable').DataTable({
                  processing: true,
                  serverSide: true,
                  ajax: '{!! route('postqualityscorereport') !!}',
                  columns: [

                    { data: 'adGroupID', name: 'adGroupID' },
                    { data: 'keywordID', name: 'keywordID' },
                    { data: 'previousQualityScore', name: 'previousQualityScore' },
                    { data: 'qualityScore', name: 'qualityScore' },
                    { data: 'day', name: 'day' }
                ],
                order: [[1, 'des']]
            });
    });
});
```

My aim is : 

1 - Arranging routes according to ajax request 
2 - Being able to retrieve input data from form and write a query to database with them
3 - Displaying output of this query below the form with ajax.

I've really read about both datatables-jquery and yajra plugin but couldn't get this thing done. 
ANY HELPS WOULD BE REALLY APPRECIATED.

**Comment by yajra** [comment]
You can pass some form vars to your controller like below. See this [demo](https://datatables.yajrabox.com/eloquent/advance-filter) for ref.
```js
ajax: {
            url: '/data',
            data: function (d) {
                d.name = $('input[name=name]').val();
                d.operator = $('select[name=operator]').val();
                d.post = $('input[name=post]').val();
            }
        },
```

**Comment by karakanb** [comment]
@yajra thanks for the help
