### ISSUE TITLE
Need search datatable with colom alias of sum/count

### ISSUE THREAD

**Issue by raunak-cispl** [yajra/laravel-datatables#670]
### Summary of problem or feature request

How can I make the datatable to search field which has come from aggregate function like, SUM, COUNT, etc..

I also check this issue https://github.com/yajra/laravel-datatables/issues/219 but it did't help me and can not able to the get desired output
### Code snippet of problem

Data Source (Modal file)
`$data = DB::table('buyers')
            ->select('buyers.id', 'buyers.username', DB::raw('COUNT(DISTINCT(' . DB::getTablePrefix() . 'accounts.id)) as total_accounts'), DB::raw('SUM(' . DB::getTablePrefix() . 'account_spend_history.amount_spend) as account_spend_total'))
            ->leftJoin('accounts', 'buyers.id', '=', 'accounts.buyer_id')
            ->leftJoin('account_spend_history', 'accounts.id', '=', 'account_spend_history.account_id')
            ->groupBy('accounts.buyer_id');
$datatables = Datatables::of($data);
        return $datatables->make(true);`

My JS file

```
table = $('#inbox-table').DataTable({
    iDisplayLength: 100,
    aLengthMenu: [[100, 200, 300, 500], [100, 200, 300, 500]],
    processing: true,
    serverSide: true,
    scrollX: true,
    ajax: SITEURL + 'buyer/list',
    columns: [
        {
            data: 'id',
            name: 'buyers.id'
        },
        {data: 'username', name: 'buyers.username'},
        {
            data: 'total_accounts',
            name: 'total_accounts'
        },
        {
            data: 'account_spend_total',
            name: 'account_spend_total'
        },
        {
            data: 'action',
            name: 'action',
            orderable: false,
            searchable: false
            className: 'text-center'        }
    ],
    order: [[1, "desc"]],
});
```

Showing SQL Error
**SQLSTATE[42S22]: Column not found: 1054 Unknown column 'total_accounts' in 'where clause'** 

when I replace **name: 'total_accounts'** to **name: 'accounts.id'**
it is showing wrong output
### System details
- PHP Version : 5.6.3
- Laravel Version : 5.1.40 

Thanks.

**Comment by yajra** [comment]
See this demo for ref: 
https://datatables.yajrabox.com/eloquent/advance-filter
https://datatables.yajrabox.com/eloquent/post-column-search

Try using `filterColumn` api and use having query.

**Comment by raunak-cispl** [comment]
Thanks.
I was looking for advance filter.

**Comment by lherreranetlink** [comment]
@yajra the server where you have the documentation is not working, please check it out.
