### ISSUE TITLE
show and search for the translated value of the field

### ISSUE THREAD

**Issue by macnux** [yajra/laravel-datatables#673]
im viewing the country name from the database and i can show its translated value by using 

```
->edit_Column('name','function($row){
return trans($row->name);
})
```

now when i search for the translated country it does not find it .. and this is normal because this translated value does not exist already
so how i can search for the translated value
ex.
when i type België it knows that im searching in the db for belguim and shows that record

"yajra/laravel-datatables-oracle": "v6.11.3"
DataTables 1.10.12
PHP 5.6.15
windows 8.1

**Comment by yajra** [comment]
Unfortunately, since translated value is not part of the database, searching on it is not supported.
