### ISSUE TITLE
show translatable fields based on App::locale

### ISSUE THREAD

**Issue by macnux** [yajra/laravel-datatables#674]
how i can show the translated fields on server side datatables using laravel-datatables

note:: if i use edit_Column
that will not help me in case of searching ..because if the client for in the translated version it will return nothing because there is nothing match in the database

"yajra/laravel-datatables-oracle": "v6.11.3"
DataTables 1.10.12
PHP 5.6.15
windows 8.1

**Comment by yajra** [comment]
@macnux, it will not work because it's not part of the database and the package uses the database engine for querying the results. This might work if you can store the translations on a table and by doing some join statements.
