### ISSUE TITLE
search 3 related models gives me sql error

### ISSUE THREAD

**Issue by macnux** [yajra/laravel-datatables#675]
i have 3 related models

Country->Province->Area

now i want to show areas on datatable with its related data
i use this code to get json

```
   $areas=Area::with('province','province.country');
    return Datatables::of($areas)->make(true);
```

then i use the return json in the view like this

```
    $('#areadataTable').DataTable({
        processing: true,
        serverSide: true,
        stateSave: true,
        ajax: 'area/areas-json',
          columns: [
            {data: 'id', name: 'id'},
            {data: 'province.country.name', name: 'province.country.name'},
            {data: 'province.name', name: 'province.name'},
            {data: 'code', name: 'code'},
            {data: 'name', name: 'name'},
        ]
    });
```

all columns appeared correctly BUT when i search it give me sql error says

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'countries.name' in 'where clause' `

although there is a column called names in countries table as seen above !!

when i remove country the problem disappear .. but i need to show it because it is the parent of the parent

i think maybe i should write something else in the name of columnDefs or what?

"yajra/laravel-datatables-oracle": "v6.11.5"
DataTables 1.10.12
PHP 5.6.15
windows 8.1

**Comment by yajra** [comment]
Not sure if `province.country` is supported. I only tested the package on a single level relationship. To make your DT work, I suggest you temporarily set that column to not searchable and orderable.

```js
{data: 'province.country.name', name: 'province.country.name', orderable: false, searchable: false},
```

**Comment by macnux** [comment]
i use query builder and edit the column to solve my problem 

any way  thanks for help

hope you add support for multi level relation ship
