### ISSUE TITLE
Fatal error: Uncaught exception 'RuntimeException' with message 'A facade root has not been set.' 

### ISSUE THREAD

**Issue by sjwdavies** [yajra/laravel-datatables#680]
Hi,

When trying to add this to a project that's using Eloquent as a stand alone tool, I get this error:

> Fatal error: Uncaught exception 'RuntimeException' with message 'A facade root has not been set.' 

Have you come across this or do you have any idea how to resolve it?

Thanks in advance,
Steve

**Comment by yajra** [comment]
@sjwdavies sorry but I haven't tested the package on a stand alone Eloquent. But I think creating/extending the Service Provider without the facade registration may do the trick.

**Comment by yajra** [comment]
Maybe try this solution based on this issue: https://github.com/nicolaslopezj/searchable/issues/86

```php
use \Illuminate\Container\Container as Container;
use \Illuminate\Support\Facades\Facade as Facade;

/**
* Setup a new app instance container
* 
* @var Illuminate\Container\Container
*/
$app = new Container();
$app->singleton('app', 'Illuminate\Container\Container');

/**
* Set $app as FacadeApplication handler
*/
Facade::setFacadeApplication($app);
```

**Comment by sjwdavies** [comment]
Thanks for the reply...

I tried that and now get a different error:

> Fatal error: Uncaught exception 'ReflectionException' with message 'Class datatables does not exist' in D:\project\vendor\illuminate\container\Container.php:734 

I don't suppose that gives you any ideas does it?

Thanks again,
Steve

**Comment by yajra** [comment]
@sjwdavies sorry but I haven't had any chance to test the package on a standalone app. Closing the issue but please do share if ever you figure this out. Thanks!

**Comment by danillo10** [comment]
Try remove: use Yajra\Datatables\Facades\Datatables; of yout controller and add use Datatables;
