### ISSUE TITLE
How can I change the languaje?

### ISSUE THREAD

**Issue by cahucadi** [yajra/laravel-datatables#682]
### Summary of problem or feature request

I trying to change the lang of the pluggin with no success

Must we develop a routine or there is a way to change the lang of the plugin?

**Comment by yajra** [comment]
See the official docs of the jQ DT. Quick search for lang:
https://datatables.net/search/?cx=004673356914326163298%3Abcgejkcchl4&cof=FORID%3A9&ie=UTF-8&q=language&sa=Search

**Comment by luizpatrocinio** [comment]
Hi cahucadi,
look

 $('#tabela').DataTable({

        "processing": true,
        "serverSide": true,
        "language": { "url": "/datatables/pt.br" },
        "ajax": "/cliente/api",
        "columns": 
        [ 
        { data: "xx" },
        { data: "xxx" },
        { data: "xxx" },
        { data: "xxx" },
        { data: "xxx" },
        { data: "xxx"},
        ]
    });
});
and make your pt.js

{
    "sEmptyTable": "Nenhum registro encontrado",
    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
    "sInfoPostFix": "",
    "sInfoThousands": ".",
    "sLengthMenu": "_MENU_ resultados por página",
    "sLoadingRecords": "Carregando...",
    "sProcessing": "Processando...",
    "sZeroRecords": "Nenhum registro encontrado",
    "sSearch": "Pesquisar",
    "oPaginate": {
        "sNext": "Próximo",
        "sPrevious": "Anterior",
        "sFirst": "Primeiro",
        "sLast": "Último"
    },
    "oAria": {
        "sSortAscending": ": Ordenar colunas de forma ascendente",
        "sSortDescending": ": Ordenar colunas de forma descendente"
    }
}
