### ISSUE TITLE
How do I add auto incrementing row to the table.

### ISSUE THREAD

**Issue by icodebuster** [yajra/laravel-datatables#683]
I want to display index as number in increasing order.

**Comment by yajra** [comment]
Do you mean the internal index id? Maybe try using this PR as ref: https://github.com/yajra/laravel-datatables/pull/597

```php
return $this->datatables
            ->collection($this->query())
            ->addIndexColumn()
            ->make(true);
```

**Comment by icodebuster** [comment]
I was indeed looking for `addIndexColumn`

Thank you for the quick reply,

**Comment by mansouralex** [comment]
@yajra At the JS side how we should add the new column ?

**Comment by yajra** [comment]
By default, the data key used is `DT_Row_Index`:

```js
{data: 'DT_Row_Index', orderable: false, searchable: false}
```

**Comment by mansouralex** [comment]
@yajra thanks for your reply. This is what I tried but it's not working and giving `jquery.dataTables.min.js:62 Uncaught TypeError: Cannot read property 'style' of undefined`

**Comment by llplaxll** [comment]
@yajra sir how can i order the indexcolumn to descending order, (3,2,1)

**Comment by prajapatim** [comment]
Thanks

**Comment by javidjan** [comment]
I have still this error:
DataTables warning: table id=daily_schedule - Requested unknown parameter 'DT_Row_Index' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

**Comment by javidjan** [comment]
@yajra

**Comment by yajra** [comment]
@javidjan sorry for the inconvenience. `DT_Row_Index` was renamed to `DT_RowIndex`.

See https://github.com/yajra/laravel-datatables/pull/1882 for ref.

**Comment by d33pak-singh** [comment]
> @yajra sir how can i order the indexcolumn to descending order, (3,2,1)

You got any solution for this mate?

**Comment by nickforbizz** [comment]
how do you use yajra addIndexColumn on view, so as it appears like 1, 2, 3....
