### ISSUE TITLE
Laravel 5.3 support

### ISSUE THREAD

**Issue by jiriko** [yajra/laravel-datatables#685]
### Summary of problem or feature request

getting bindShared() error on collective Html 

### System details

- Operating System
- Php 7.1
- Laravel Version (Dev)
- Laravel-Datatables Version (Latest)

**Comment by yajra** [comment]
You need to use collective html, not illuminate.

**Comment by jiriko** [comment]
we are not using the html package I think it's a dependency pulled by datatables package?

**Comment by ChaosPower** [comment]
@jiriko  Illumitate Html it's not part of datatables. If something like that is showing please grep your project folder for Illumitate/html. Probably came from other packages.

https://github.com/yajra/laravel-datatables/blob/6.0/composer.json#L20

**Comment by jiriko** [comment]
@ChaosPower @yajra  Sorry guys. I don't know what happened yesterday. I ran composer update and it just worked fine now. Thanks for the fast response.
