### ISSUE TITLE
Column name and uppercase problem

### ISSUE THREAD

**Issue by aymenpeak** [yajra/laravel-datatables#689]
How to avoid the space after each character written in uppercase?

There is my getColumns function 

![capture1](https://cloud.githubusercontent.com/assets/19589742/17555441/7eea9f76-5f07-11e6-814e-e9c42d50e68f.PNG)

and there is the result

![capture2](https://cloud.githubusercontent.com/assets/19589742/17555454/8b1e3b72-5f07-11e6-8da4-da17b24a6226.PNG)

**Comment by yajra** [comment]
You can set the title manually:

```php
return [
    'Montant_TTC' => ['data'=>'Montant TTC' , 'title' => ' Montant TTC']
];
```

**Comment by aymenpeak** [comment]
it works .. thnks @yajra :)
