### ISSUE TITLE
L5: Not able to access column name, only column index

### ISSUE THREAD

**Issue by kingsloi** [yajra/laravel-datatables#69]
Hi, 

Firstly, awesome plugin! Thank you so much for porting it over to Laravel!

I've followed your examples for the past few days, and I keep running into the same problem. 

This is my controller:
```php

    $users = App\Profile::with('user')->with('occupation')->with('location')->with('company')->select('*');

    return Datatables::of($users)
        ->addColumn('action', function ($user) {
        return '<div class="btn-group">
                <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        Actions <span class="caret"></span>
                    </button>
                    
                    <ul class="dropdown-menu" role="menu">
                        <li>'.HTML::decode(link_to_route('admin-user-view','<i class="fa fa-eye"></i> View', array('id'=>$user->id))).'</li>
                        <li>'.HTML::decode(link_to_route('admin-user-edit','<i class="fa fa-pencil-square-o"></i> Edit', array('id'=>$user->id))).'</li>
                    </ul>
                    
                </div>';
        })
        ->editColumn('id', 'ID: {{$id}}')
        ->make();
```

This is my JS

```javascript

        $('#admin-users-index').DataTable({
            processing: true,
            serverSide: true,
            ajax: '/api/v1/users',
            columns: [
                {data: 4, name: 'first_name'},
                {data: 2, name: 'last_name'},
                {data: 19, name: 'email', orderable: false, searchable: false},
                {data: 37, name: 'company.name', orderable: false, searchable: false},
                {data: 25, name: 'occupation.name', orderable: false, searchable: false},
                {data: 30, name: 'location.name', orderable: false, searchable: false},
                {data: 41, name: 'action', orderable: false, searchable: false}
            ]         
        });

```

Here's what the JSON returns:

    https://gist.github.com/kingsloi/1cfa1dae6f38cb753096

As you can see, I have to use `data: ID OF THE RETURNED JSON ARRAY`, whereas in your examples, and everywhere else, people use the name of the column? Is this a bug? I've tried every possible combination of table.column, model.column, etc, etc. 

My version of Laravel is `5.0.32`... any help is much appreciated! I'm okay using the ID, but obviously, would much prefer to use the column name

Cheers,
Kingsley

**Comment by yajra** [comment]
Hi, you should use 'make(true)' to return object data source. Afterwards, you can now assign the data value via column name. Also inspect the ajax response to see the data output using firebug or chrome dev tools

**Comment by kingsloi** [comment]
Yajra, wow, talk about something so simple!

I've been searching for a fix for like 3 days... turns out all I needed to do was add a boolean. Thank you so much!
