### ISSUE TITLE
(Bug?) Eager Loading - Order by table.* syntax error

### ISSUE THREAD

**Issue by xxRockOnxx** [yajra/laravel-datatables#690]
Copied original example here: https://datatables.yajrabox.com/eloquent/relationships

`$prescriptions = Prescription::with('patient')->select('prescriptions.*');`

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '* asc limit 10 offset 0' at line 1 (SQL: select `prescriptions`.* from `prescriptions` order by `prescriptions`.* asc limit 10 offset 0)

Relationship is Many to One. (Pres -> Patient) on this view
Prescription Model has method patient that returns belongsTo Patient Model

**Comment by yajra** [comment]
Can you please paste your js code? Did you declare your js columns properly?

**Comment by xxRockOnxx** [comment]
Found out it doesn't support Eloquent relationship. I am now using Query Builder joins instead.

**Comment by yajra** [comment]
Yes, using join is a more stable solution. Not all relationships and fully tested with the package.
