### ISSUE TITLE
Problems to sort on MongoDB

### ISSUE THREAD

**Issue by elfeffe** [yajra/laravel-datatables#691]
I use MongoDB https://github.com/jenssegers/laravel-mongodb
The problem is that sorting doesn't work, it sort "almost good", empty fields first, but then it mixes the result. K before C, etc.
If I do the search on Mongo, I get correct results. the problem is with datatables.
Any idea about why?

**Comment by yajra** [comment]
@elfeffe I haven't used MongoDB so I'm not really sure about this. But maybe try debugging by inspecting the generated queries in ajax response. Just set APP_DEBUG=true to include the debug queries on ajax response.

**Comment by yajra** [comment]
Closing old issues. Please open a new one if needed. Thanks!
