### ISSUE TITLE
How search in Added column?

### ISSUE THREAD

**Issue by alejandri** [yajra/laravel-datatables#694]
When adding a new column. Visualize and render fine. But when search in these rows. Row retrieve failed with error "Column (new column name doesnt exist)"

```
            $rows = DB::table('orders')
                        ->leftJoin('orders', 'orders.id', '=', 'users.prospecto_id')
                        ->select([
                                    'orders.id',
                                    'users.id as uid',
                                     'users.name',
                                    'orders.created_at',                          
                                    ]);
            return Datatables::of($rows)
                    ->addColumn('cliusers', function ($rows) {
                            return $rows->name;
                    })
                ->make(true); 
```
Any help to read? Thanks !

### System details
- Operating System
- PHP Version 5.6
- Laravel Version 5.2
- Laravel-Datatables Version "yajra/laravel-datatables-oracle": "~6.0"

**Comment by yajra** [comment]
Basically, searching on added column is not possible since it's not part of the query. However, you can do this trick: on your `cliusers` column, set the name value to `users.name`

```js
{data: 'cliusers', name: 'users.name'}
```

This will perform search on users.name column on cliusers.

**Comment by carlituxman** [comment]
It will be great can search in collections like in the abandoned package Chumper/Datatable
