### ISSUE TITLE
Route with two parmeters

### ISSUE THREAD

**Issue by julianscreawn** [yajra/laravel-datatables#695]
`Route::get('home/customers/{custid}/contacts/{custcontactid?}', ['as' => 'customer.contacts', 'uses' => 'CustomerContactsController@index']);`

The direct link works fine in the script	
`ajax: 'http://localhost/untdchem/public/home/customers/1812/contacts/21',`

However, this does not seem to work:
`ajax: '{!! route('customer.contacts', $CustID, $CustContactID) !!}',`

I tested both variables in the view and they have values.  Is it possible to use two parameters as above ?

Thanks, Julian

**Comment by yajra** [comment]
I think you have incorrect syntax on your route:
```php
ajax: '{!! route('customer.contacts', $CustID, $CustContactID) !!}',
// should be
ajax: '{!! route('customer.contacts', [$CustID, $CustContactID]) !!}',
```

**Comment by julianscreawn** [comment]
Thank you, that was the problem.
