### ISSUE TITLE
Service implementation: sending variable via route to function query() 

### ISSUE THREAD

**Issue by mraghayev** [yajra/laravel-datatables#697]
### Sending variable via route to function query() using service implementation

Can't get a variable inside function query() and use it.
### Route:

```
Route::get('posts/{category_id}', ['as' => 'post', 'uses' => 'PostController@index']);
```
### PostController:

```
public function index(PostsDataTable $dataTable, $category_id)
{
    return $dataTable->render('dashboard.posts.index', ["category_id" => $category->id]);
}
```
### Builder Parametres:

```
protected function getBuilderParameters()
{
    return [
        'order' => [0,'desc'],
        'lengthMenu' => [10,25,50],
        'ajax' => ['category_id' => $category_id],   //doesn't work
    ];
}
```
### Query:

```
protected function query()
{
    $query = Post::query()
        ->join('categories', 'categories.id', '=', 'posts.category_id')
        ->where('posts.category_id', $this->request()->get('category_id')) //doesn't work
        ->select([
            'posts.id', 'categories.name', 'title', 'published', 'published_at', 'published_by'
        ]);

    return $this->applyScopes($query);
}
```
### Problems
- Can't pass variable to the postsDataTable.php
- Even if it is passed, can't use this variable at the function query()
### I have done it already by writing simple javascript at the view using method ajax:

```
        ajax: {
            url: 'myRoute',
            data: {"category_id": '{{$category_id}}'},
            type: "POST"
        },
```

I am looking for the way to pass variable: category_id to postsDataTable without using javascript and use this variable at the function query().

**Comment by yajra** [comment]
This is how I do it on my project. Just add a method on your dataTable class like `->forCategory($cat)` setter.

```php
return $dataTable->forCategory($cat)
    ->render('dashboard.posts.index', ["category_id" => $category->id]);
```

DataTable class:
```php
protected $category;

public function forCategory($cat) {
    $this->category = $cat;
    return $this;
}
```

**Comment by mraghayev** [comment]
Thank you, it worked!

**Comment by joxper** [comment]
@mraghayev  I cannot get this to work, could you show me how did you implemented @yajra example please.

I need to pass a variable to the query() so I can filter the users of a specific client.

thanks in advance

**Comment by gsc89** [comment]
Just what I was looking for!

**Comment by ssheduardo** [comment]
For access to value?
```php
public function query()
{
    $categ = $this->category      
}
```

**Comment by mraghayev** [comment]
There is one little issue. If the variable `$cat` comes from ajax,  it is sent to class as null. I saw this issue on my project, where I try to load dataTable in bootstrap Modal Dialog.

```
$cat = $request->input('catalog_id'); // comes via Ajax, and works

return $dataTable->forCategory($cat) //but it is sent as null
    ->render('dashboard.posts.index', ["category_id" => $category->id]);

```
