### ISSUE TITLE
Get and set the index in Datatables::of()

### ISSUE THREAD

**Issue by maengkom** [yajra/laravel-datatables#699]
I want to set row index in a column and I do that using editColumn, but not know how get and set the index value. 

```
$result = Model::select('*');
return $result->get();
```
Below are output of query. The keys (0,1,2,3) are the indexes what I'm talking about.

<img width="133" alt="screen shot 2016-08-21 at 7 54 35 am" src="https://cloud.githubusercontent.com/assets/960467/17834645/d2b519ea-6774-11e6-9143-09257d803979.png">

Below are code to process data to datatables that I think could use to get the row index by getting key of each data, passing $key to the editColumn closure.

    $result = MsItemDimension::select('*');
        
    return Datatables::of($result)
        ->setRowId('id')
        ->editColumn('name', function($item, $key) {
            return '<a href="#" data-index="'.$key.'">'.$item->name.'</a>';
        })
        ->make(true);

That's not works of course. My objective is getting data from each record when user clicked the link of the column 'name'. I am using row selected by click checkbox in the other column. What I know I can get table.row( index ).data() in frontend's code, that's why I need  to set index value in the link. Or are there some alternatives ?

**Comment by yajra** [comment]
You can use `->addIndexColumn()` method.

**Comment by maengkom** [comment]
Nice. Just confirm that method not zero based index. I saw DT_Row_Index start from 1. 

Thank you.

**Comment by nilesh-a09** [comment]
I want index/key of result in editcolumn option. want to perform some operations depending on the key. how can it be done?
 
 ->editColumn('name', function($results) {
        //here
    })

**Comment by salman9607** [comment]
In order to get index you can use

use DB;


DB::statement(DB::raw('set @rownum=0'));
ModelName::select(DB::raw('@rownum := @rownum + 1 as rownum'),'column_names');

that's it you can get the index by using => $results->rownum

**Comment by salman9607** [comment]
> I want index/key of result in editcolumn option. want to perform some operations depending on the key. how can it be done?
> 
> ->editColumn('name', function($results) {
> //here
> })



In order to get index you can use

use DB;

DB::statement(DB::raw('set @rownum=0'));
ModelName::select(DB::raw('@rownum := @rownum + 1 as rownum'),'column_names');

that's it you can get the index by using => $results->rownum

**Comment by nilesh-a09** [comment]
> 
> 
> > I want index/key of result in editcolumn option. want to perform some operations depending on the key. how can it be done?
> > ->editColumn('name', function($results) {
> > //here
> > })
> 
> In order to get index you can use
> 
> use DB;
> 
> DB::statement(DB::raw('set @rownum=0'));
> ModelName::select(DB::raw('@rownum := @rownum + 1 as rownum'),'column_names');
> 
> that's it you can get the index by using => $results->rownum

Hey, thanks for the reply.
Your solution is giving row number. I need index of returned results.
eg: my resultset have 20 items.  so index will start from 0 , 1,....19.
