### ISSUE TITLE
Getting data of other dynamic columns

### ISSUE THREAD

**Issue by joanebrown** [yajra/laravel-datatables#700]
Hi Yajra!

It's possible to get access a variable created within a `addColumn` from another `addColumn`?

**Example:**

```
->addColumn('A', function($object) {
    $data= $object->getSomeData();
    return $data->dataA;
})

->addColumn('B', function($object) {
    // I want to access to $data variable, to avoid repeating operations
    // I tried with "use" but doesn't work.

   // I want:
   $data->dataB;
})
```

Thank you for your amazing work!

**Comment by yajra** [comment]
@joanebrown maybe try using eager loading to avoid re-fetching of data? 

But to answer your question, I think it's not possible to to pass the `$data` var like you wanted on addColumn.

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
