### ISSUE TITLE
Order by added column

### ISSUE THREAD

**Issue by amitaymolko** [yajra/laravel-datatables#71]
Using laravel 4.2

when creating the table i use:

->addColumn('joined_date', function($customer) {
                return $customer->user->created_at->toFormattedDateString();
            }, true)

when trying to order by 'joined_date' i get this response:

{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'joined_date' in 'order clause' (SQL: select `id`, `user_id`, `is_active` from `customers` order by `joined_date` desc limit 10 offset 0)","file":"vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}

Thats because joined_date isn't a column in my db.

how do i order by a column i added, and make it not use the sql query?

**Comment by yajra** [comment]
@amitaymolko , sorry but sorting by added column is not possible because it's not part of the query. However, you may achieve this on Laravel 5 via v5.x of the package by using `Collection`.
