### ISSUE TITLE
Can't install on Laravel 5.3 (stable)

### ISSUE THREAD

**Issue by neoteknic** [yajra/laravel-datatables#711]
### Summary of problem or feature request

Can't install datatable on Laravel 5.3.0
Composer installation is OK, but when I add the Yajra\Datatables\DatatablesServiceProvider::class in app.php there is an error

### Code snippet of problem
This is the error : 
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::bindShared()

### System details

- Operating System : Linux Gentoo x64
- PHP Version : 7.0.10
- Laravel Version : 5.3.0
- Laravel-Datatables Version : 6.17.1

**Comment by yajra** [comment]
@neoteknic it's because laravel collective does not have stable version of `html` for 5.3. You need to wait for them to release a stable version and the package should work fine by then. 

Or you can force install their 5.3 dev version for it to work now. ^_^
