### ISSUE TITLE
Order Issue on date field for Upcoming birthdays only on day and month basis

### ISSUE THREAD

**Issue by abdullahmallik** [yajra/laravel-datatables#712]
Order Issue on date field for Upcoming birthdays only on day and month basis

I am unable to find workaround for sort date column on month and day basis for upcoming birthdays.

Code Snippet  :
public function html()
    {
        return $this->builder()
            ->columns([
                ['data' => 'full_name', 'name' => 'full_name', 'title' => 'Lead', 'searchable'=> true],
                ['data' => 'insured_name', 'name' => 'insured_name', 'title' => 'Insured'],
                ['data' => 'next_contact_date', 'name' => 'next_contact_date', 'title' => 'Next Contact Date'],
                ['data' => 'phone', 'name' => 'phone', 'title' => 'Phone'],
                ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
                **['data' => 'date_of_birth', 'name' => 'date_of_birth', 'title' => 'Birth Date','orderable' => true],**
                ['data' => 'notes', 'name' => 'notes', 'title' => 'Notes'],  
                [
                    'data' => 'action',
                    'name' => 'action',
                    'title' => 'Action',
                    'orderable' => false,
                    'searchable' => false
                ],
            ])
            ->ajax('')
            ->parameters([
                'bSortable' => false,
                'responsive' => true,
                //'pageLength' => config('agents.rows_per_page'),
                'pageLength' => 20,
                'dom' => 'Bfrtip',
                'buttons' => [],
                'ordering' => config('agents.ordering'),
            ]);
    }
- Laravel Version : 5.1
- Laravel-Datatables Version : 6.17.0

**Comment by yajra** [comment]
Try using `orderColumn('date_of_birth', 'upcoming_sql $1')`

**Comment by yajra** [comment]
Using orderColumn should fixed this issue. Thanks!
