### ISSUE TITLE
Cannot use object of type Illuminate\Http\JsonResponse as array

### ISSUE THREAD

**Issue by joxper** [yajra/laravel-datatables#715]
### Summary of problem or feature request

I am trying to use Datatables as Service following https://datatables.yajrabox.com/service

I have the same steps as there and I always ended in the following error.

I tried already with:

-queryBuilder
-eloquent
-collection

###Logs

```
Cannot use object of type Illuminate\Http\JsonResponse as array (View: ~/resources/views/modules/test/datatables.blade.php)
~/vendor/yajra/laravel-datatables-oracle/src/Html/Builder.php#185

protected function encodeAjaxDataFunction($parameters)
    {
        $ajaxData = '';
        if (isset($parameters['ajax']['data'])) {
            $ajaxData                   = $parameters['ajax']['data'];
            $parameters['ajax']['data'] = "#ajax_data#";
        }
```

### System details

- Laravel 5.2
- Laravel-Datatables 6.18

**Comment by joxper** [comment]
Seems like if I take away 

` ->ajax($this->ajax())

from the html() method

```
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->ajax($this->ajax())
                    ->addAction(['width' => '80px'])
                    ->parameters($this->getBuilderParameters());
    }
```
like this:

```
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->addAction(['width' => '80px'])
                    ->parameters($this->getBuilderParameters());
    }
```

then it works

also if i putted like:

` ->ajax('')


it is on purpose? 

thanks

**Comment by yajra** [comment]
`ajax()` method on html builder is different from `ajax()` method on the service class.

`->ajax('')` on html builder requires the **url** where DT will fetch the results.
`->ajax()` on service class is the one that handles the json response.
