### ISSUE TITLE
PDF Export is not working.

### ISSUE THREAD

**Issue by mcsaygili** [yajra/laravel-datatables#718]
Hello, 

I just setup my datables as a service and pdf export is not working. When i click to the PDF button error shows.

PHPExcel_Writer_Exception in DomPDF.php line 34:
Unable to load PDF Rendering library

When i searched on google, https://github.com/dompdf/dompdf/releases dompdf was changed configuration file. "dompdf_config.inc.php file has been removed"

DomPDF.php uses this config file and there is no config file.
```php
$pdfRendererClassFile = PHPExcel_Settings::getPdfRendererPath() . '/dompdf_config.inc.php';
if (file_exists($pdfRendererClassFile)) {
    require_once $pdfRendererClassFile;
} else {
    throw new PHPExcel_Writer_Exception('Unable to load PDF Rendering library');
}
```
What i have to do ? Is there any workaround ?

- Operating System : Windows 9.1 Pro, XAMP
- PHP Version : 5.6
- Laravel Version : 5.2
- Laravel-Datatables Version : Lastest

**Comment by yajra** [comment]
I suggest you use [`laravel-snappy`](https://github.com/barryvdh/laravel-snappy) as the pdf generator. Laravel-Excel usually hangs when being used with PDF.

**Comment by mcsaygili** [comment]
Which version of laravel-snappy i have to use? I added ""barryvdh/laravel-snappy": "^0.3.1"," and change datatables.php "pdf_generator" to "snappy". after these changes i got this error.

"Unknown long argument --lowquality"

**Comment by yajra** [comment]
@mcsaygili were you able to install [wkhmtltopdf](wkhtmltopdf.org)?

**Comment by mcsaygili** [comment]
ah sorry, yes i'm using perfectly. but if you are using windows i'm not recommend. I was change my development platform to Ubuntu. :)

**Comment by RayhanYulanda** [comment]
I have install laravel-snappy but still i get json format not the pdf. why? @yajra
