### ISSUE TITLE
Datatables v3 are not working with Laraval 4.1

### ISSUE THREAD

**Issue by Lexazan** [yajra/laravel-datatables#72]
If Datatables version 3 is used with Laravel 4.1 the following exception will arise: 

*exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Support\Arr' not found' in ...../vendor/yajra/laravel-datatables-oracle/src/yajra/Datatables/Datatables.php:209 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main}*

The reason is because Arr.php is absent in Laravel 4.1 (It was added in Laravel 4.2)
This probably should be mentioned in readme

**Comment by yajra** [comment]
@Lexazan , you need to use `~2.0` for Laravel 4.1

**Comment by Lexazan** [comment]
@yajra I upgraded Laravel to version 4.2, had to do it anyway, just needed a kick :) Thank for the great job by the way.
