### ISSUE TITLE
Sotring issue

### ISSUE THREAD

**Issue by testwts** [yajra/laravel-datatables#723]
sorting is not working for me and I can't event get log of queries in response of server side implementation. Here is my code [link](http://kopy.io/cE91f).   

normal table
![normal_table](https://cloud.githubusercontent.com/assets/6149419/18053612/f984f464-6e1d-11e6-8e66-62b882a83db1.png)

order by date 
![order_by_date](https://cloud.githubusercontent.com/assets/6149419/18053611/f9848d26-6e1d-11e6-815c-af5df929d934.png)

order by price
![order_by_price](https://cloud.githubusercontent.com/assets/6149419/18053613/f9d84ba0-6e1d-11e6-8e9e-d6b75161760b.png)

How can I make order proper and how can I get log of queries in server side response? My APP_DEBUG variable is having value true.

**Comment by yajra** [comment]
Try clearing your config cache and set APP_DEBUG=true to get the query logs. Also, I suggest you use query builder instead of collection by removing the get() method.

```php
 $orders = DB::table('orders as o')
        ->leftJoin('users as u', 'u.id', '=', 'o.user_id')
        ->leftJoin('store_details as s', 's.id', '=', 'o.store_id')
        ->leftJoin('payments as p', 'p.order_id', '=', 'o.id')
        ->select(
        'o.order_number', DB::raw('(select count(id) from `orders_details` where order_id=o.id) as total_items'), 'o.user_id', 'u.username as customer', 's.id as store_id', 's.storename', 'o.created_at', 'o.grand_total','p.comm', 'o.status'
    );

return Datatables::of($orders)
...
```

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
