### ISSUE TITLE
Prefixing setRowId()

### ISSUE THREAD

**Issue by mojosef** [yajra/laravel-datatables#725]
Is it possible to prefix when setting the row ID? As far as I can see I can only add in values or a string.

Thanks for any help
Joe

**Comment by yajra** [comment]
Yes, I think you can do something like this:
```php
->setRowId('prefix_{{$id}}')
```

**Comment by mojosef** [comment]
Ah thank you! Had spaces in the braces and it didn't like it!

This works a treat!
