### ISSUE TITLE
saveState of footer column search

### ISSUE THREAD

**Issue by aymenpeak** [yajra/laravel-datatables#727]
Is it possible to include the filter in the saveState of the table? i'm talking service implementation

**Comment by yajra** [comment]
Yes, just set `'stateSave' => true,` on `protected function getBuilderParameters()`.

**Comment by yajra** [comment]
But I'm not sure if footer column search is included on the default saveState. You may need to hook on the save state event if it's not included.

**Comment by aymenpeak** [comment]
Yes it's included but when i return to the first page i found a filtred table but the inputs are empty .. i'm gonna try to override the callback function in order to populate the inputs with the old values

**Comment by aymenpeak** [comment]
hey Yajra,

i managed to override the callback function to save the state of the footer column search.. BUT in one column i had that date range filter that i can't save its values in data object that get used by the callback function.
the data object look has that structure
![datacallback](https://cloud.githubusercontent.com/assets/19589742/18959231/44618ef0-865d-11e6-9f43-ea623d53e1aa.PNG)

and there is my code;

![datacapture](https://cloud.githubusercontent.com/assets/19589742/18959304/955ec426-865d-11e6-888c-2d6c508bf2e0.PNG)

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
