### ISSUE TITLE
Prevent Xss 

### ISSUE THREAD

**Issue by josedejesusjaime** [yajra/laravel-datatables#728]
Hi! I auto attacked my web, with a xss attack . i put <script>alert('totoro was here')</script> on a field and save it, i would beef up my validation i know it, but i wanna know if datatables has any way to prevent or treat it.

**Comment by yajra** [comment]
You can use `escapeColumns([])` to prevent xss on selected fields. See https://github.com/yajra/laravel-datatables/issues/128.
