### ISSUE TITLE
Anyway to keep current page when sorting?

### ISSUE THREAD

**Issue by pixelone** [yajra/laravel-datatables#73]
Not sure if this is a bug, but if you sort a column on any page other than 1, it resets back to the first page.  Is there anyway to sort the current page without having to go back to page 1? 

By the way thank you for this contribution your hard work is much appreciated!

**Comment by yajra** [comment]
@pixelone , it's the default behavior of datatables. I guess you would have to override the plugin's default to achieve this. Below are some links I found that might help you with this.

- https://www.datatables.net/forums/discussion/21001/how-to-keep-current-page-after-sorting
- http://stackoverflow.com/questions/23607943/how-to-keep-the-current-page-after-sorting-with-jquery-datatables
- https://datatables.net/examples/basic_init/state_save.html
- https://www.google.com.ph/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=datatables%20sort%20on%20same%20page&es_th=1
