### ISSUE TITLE
Metronic datatables buttons

### ISSUE THREAD

**Issue by josedejesusjaime** [yajra/laravel-datatables#731]
Hi ! Im using metronic templates everything is ok, but when the view is rendering it doesn't recognize the reload and reset buttons, how can i put them?

**Comment by josedejesusjaime** [comment]
The problem was solved, but i have a question how can i change the class of the server button ? like print or reload

**Comment by yajra** [comment]
Just publish the asset and modify `dataTables.buttons.server-side.js` accordingly.

**Comment by mcsaygili** [comment]
@josedejesusjaime if you have time can u try u implement as picture. 
![image](https://cloud.githubusercontent.com/assets/21283796/18229860/0ff5db42-7291-11e6-9b5c-fff4f8443693.png)
I'm trying to modify dataTables.buttons.server-side.js.

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
