### ISSUE TITLE
filterColumn and Related Models

### ISSUE THREAD

**Issue by rcevs** [yajra/laravel-datatables#734]
Hi Arjay. Congratulations for the great work. 

I'm struggling to create a custom filter in which the user can search for a client either by first name or last name. Here's my code:

```
$polizas = Auth::user()->polizas()
            ->with([
                'cliente' => function ($query) { $query->select('id','nombre', 'apellido_paterno', 'apellido_materno'); },
            ]);

return Datatables::of( $polizas )
                ->filterColumn('cliente.nombre', function($query, $keyword) {
                    $query->whereRaw("CONCAT( cliente.nombre, ' ', cliente.apellido_paterno ) like ?", ["%{$keyword}%"]);
                })
                ->make( true );
```

And here's the error I'm getting:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cliente.nombre' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `polizas` where `polizas`.`user_id` = 1 and `polizas`.`user_id` is not null and (CONCAT( cliente.nombre, ' ', cliente.apellido_paterno ) like %a%)) count_row_table)

How can I make it search in the 'clientes' table? I hope you can point me in the right direction. Thanks!

**Comment by yajra** [comment]
@rcevs how did you declare `cliente.nombre` column name on your js? Filter column uses the name on your js when filtering records. I think it should be something like this.

```js
columns: [
    {data: 'cliente.nombre', name: 'cliente.nombre'}
]

**Comment by rcevs** [comment]
I'm using <a href="https://github.com/l-lin/angular-datatables">Angular Datatables</a> so the column definition is a bit different:
```
	    vm.dtColumns = [
	        DTColumnBuilder.newColumn('cliente.nombre').withTitle('Cliente').renderWith(cliente),
	    ];

    	function cliente (data, type, full, meta) {
    		return nombre (full.cliente.nombre, full.cliente.apellido_paterno);
    	}

		function nombre (nombre, apellido_paterno) {

			var nombre = nombre;

			if ( apellido_paterno ) {
				nombre += ' ' + apellido_paterno;
			}

			return nombre ? nombre : '';

		}
```

Which should translate to the typical Datatable object as:

```
'aoColumns': [{
        'mData': 'cliente.nombre',
        'sTitle': 'cliente',
        'render': cliente
 }]
```

The original filter column works fine for first name searches, but I can't figure out how to define my custom filterColumn for the users to be able to search also by last name.

**Comment by yajra** [comment]
Hmm, maybe try using this trick. Add another column last name and just hide it by setting visible to false. This way, it will still search on last name column. This way, you can now remove `filterColumn`.

```js
'aoColumns': [{
        'mData': 'cliente.apellido_paterno',
        'visible': false
 }]
```

**Comment by rcevs** [comment]
Wouldn't this be a solution for the global search input? I have 7 other columns in the table that I omitted for simplicity, which they need their own individual column filter. All of the them work as intended, I'm just struggling with this one. I guess adding an invisible column would only work for the global search. Am I right?

**Comment by yajra** [comment]
@rcevs right, invisible column will work only for global search.

**Comment by rcevs** [comment]
Thanks for the support @yajra. So there's no way to make it work for the individual column filters?

**Comment by rcevs** [comment]
Hey @yajra. Good news! I managed to get it to work by using _join_ for the related table inside the main query. 

It seems that Eloquent's _with_ function won't work because it creates separates queries for each relationship, but filterColumn searches for the keyword inside the main query.

**Comment by yajra** [comment]
@rcevs good to know that it works for you. That is what I also usually do (join statements) for a more stable solution. Would need a bit of more code but works well on most cases.
