### ISSUE TITLE
Question: Button in action column only seen if user ist admin for that row

### ISSUE THREAD

**Issue by jgatringer** [yajra/laravel-datatables#736]
First of all, thanks for this excellent piece of code! I love Datatables in Laravel.

I have on Question who i cant find an answer anywhere.

I show a table with teams. This table has a view columns and an action column at the end. But only an defined usergroup (in the datarow) should see the editbutton in the action column to got to edit the team.

The part of the routes.php:

```
Route::get('myteams/teammemberlist/{team_id}','TeamsController@teammemberlist');
Route::any('myteams/teammember.data', 'TeamsController@anyTeammemberData')->name('teammember.data');
```

The part of the Controller:

```
public function anyMyTeamsData()
{
    $userid = Auth()->user()->id;
    $listquery = DB::table('teammembers')
        ->join('users', 'users.id', '=', 'teammembers.user_id')
        ->join('teams','teams.id', '=', 'teammembers.team_id')
        ->join('teamroles','teamroles.id','=', 'teammembers.teamroles_id')
        ->select('teams.id as teamid', 'teams.teamname', 'users.id as userid', 'users.name as username', 'teamroles.id as roleid', 'teamroles.name as rolename')
        ->where('users.id', '=', $userid)
        ->get();
    $listquery= collect($listquery);

    return Datatables::of($listquery)
        ->addColumn('action', '<a href="/myteams/teammemberlist/{!! $teamid !!}" class="btn btn-xs btn-primary"><i class="fa fa-pencil-square"></i></a>&nbsp;')
        ->make(true);
}

public function myteams()
{
    return view('pages.users.myteams', array('user' => Auth::user()));
}
```

The link in the addColumn('action'.... should only be seen by user who ist admin of this team. (field roleid in datarow of the table has value '1')

The Output-File:
    <div class="panel-heading">Meine Teams</div>

```
<div class="panel-body">
    <div>
        <a href="/myteams/accession" class="btn btn-primary form-control">einem Team beitreten</a><br /><br />
        <a href="/teams/create" class="btn btn-primary form-control">neues Team anlegen</a>

    </div>
    <div class="table-responsive">
        </br>
        <table class="display compact" id="myteams-table">
            <thead>
            <tr>
                <th>Teamname</th>
                <th>Rolename</th>
                <th>Action</th>
            </tr>
            </thead>
        </table>
    </div>


</div>
```

The Script in the output-file:

```
$(function() {
    $('#myteams-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('myteams.data') !!}',
        columns: [
            { data: 'teamname', name: 'teamname' },
            { data: 'rolename', name: 'rolename' },
            { data: 'action', name:'action', orderable: false, searchable: false }
        ]
    });
});
```

Please help to solve my problem. Thanks a lot!
### System details

i use homestead on windows for development
- OS: Windows 10
- PHP: 7.0
- Laravel Version: 5.2
- DB: mysql on (actual) homestad machine

**Comment by yajra** [comment]
You can use a view and any necessary authorizations like:

```php
->addColumn('action', 'path.to.partial')
```

```blade
// partial view
@can('team.admin')
<a href="/myteams/teammemberlist/{!! $teamid !!}" class="btn btn-xs btn-primary">
    <i class="fa fa-pencil-square"></i>
</a>
@endcan
        
```

**Comment by jgatringer** [comment]
Im sorry, i need a bit more assistance. 
Where in the code i have to that two blocks?

**Comment by yajra** [comment]
On your controller:

```php
    return Datatables::of($listquery)
        ->addColumn('action', 'teams.action')
        ->make(true);
```

Create your view `resources/views/teams/action.blade.php`
```php
@can('team.admin')
<a href="/myteams/teammemberlist/{!! $teamid !!}" class="btn btn-xs btn-primary">
    <i class="fa fa-pencil-square"></i>
</a>
@endcan
```

**Comment by jgatringer** [comment]
Still not understanding everything.

@can describes a new page, thats ok so far.

Problem is the condition

@can('team.admin') ?

i do habe in the select fields the condition: ->select('teams.id as teamid', 'teams.teamname', 'users.id as userid', 'users.name as username', 'teamroles.id as roleid', 'teamroles.name as rolename')
        
The teamroles.id = roleid, means the roleid has to be 1 => admin, who can edit (show the action buttons)

How can i pass that condition to the @can?


Thanks a lot for your assistance!

**Comment by jgatringer** [comment]
Ok, i found the missing parts. It works! Thanks.

Here my team.action:

<a href="/myteams/teammemberlist/{!! $teamid !!}" class="btn btn-xs btn-primary"><i class="fa fa-users"></i></a>&nbsp;
@if($roleid == 1)
    <a href="/teams/{!! $teamid !!}/edit" class="btn btn-xs btn-primary"><i class="fa fa-pencil-square"></i></a>&nbsp;
@endif

I solved it with a if statement to validate the id!

Thanks!

**Comment by poseso** [comment]
Hello Yajra,

I tried with the example mentioned above but I don't seem to get it working right,

This is my controller:

    public function get()
    {
        $positions = Positions::with('employees', 'department', 'reportTo')->get();

        return Datatables::of($positions)
            ->addColumn('action', 'backend.payroll.positions.partials.actions')
            ->editColumn('status',
                '@if($status == 1)
                                    <span class="label label-success">Activo</span>
                                @else
                                    <span class="label label-danger">Inactivo</span>
                                @endif')
            ->make(true);
    }


This is my actions.blade.php:

@if($position->employees->count() > 0)
    <button type="button" class="btn btn-sm btn-warning deny" data-toggle="tooltip" data-placement="top" title="Tiene {{ $position->employees->count() }}  empleados">
        <span class="fa fa-lock"></span>
    </button>
    <button data-toggle="tooltip" title="{{ trans('payroll.backend.general.positions.buttons.save') }}" class="btn btn-sm btn-primary" type="submit" name="btn-submit">
        <span class="fa fa-save"></span>
    </button>
@else
    <a href="javascript:;" data-toggle="tooltip" title="{{ trans('payroll.backend.general.positions.buttons.delete') }}"  data-id="{{ $position->id }}" class="btn btn-sm btn-danger btn-delete"><i class="fa fa-trash"></i></a>
    <button data-toggle="tooltip" title="{{ trans('payroll.backend.general.positions.buttons.save') }}" class="btn btn-sm btn-primary" type="submit" name="btn-submit">
        <span class="fa fa-save"></span>
    </button>
@endif


The error I see on console is:

line: 1
message: "Undefined variable: positions (View: \wamp64\www\contable\resources\views\backend\payroll\positions\partials\actions.blade.php)"
type:"ErrorException"


Can you please help me? Thanks in advanced!
