### ISSUE TITLE
dataTable pdf page size

### ISSUE THREAD

**Issue by nimeshc64** [yajra/laravel-datatables#737]
![image](https://cloud.githubusercontent.com/assets/8343294/18299679/5057ec2e-74e0-11e6-8ae7-df3f2878cdc7.png)

how to set pdf fit the page

**Comment by yajra** [comment]
The package uses [Laravel Excel](https://github.com/Maatwebsite/Laravel-Excel) to generate the csv, xls & pdf. Better check their documentation how to configure it.

On the other hand, I suggest you use [Laravel Snappy] as the pdf generator. The pdf output would be the same as the print view.

See this issue for ref: https://github.com/yajra/laravel-datatables/issues/718
