### ISSUE TITLE
\Request parameters for the datatable

### ISSUE THREAD

**Issue by krugerdavid** [yajra/laravel-datatables#739]
Hi Yajra

Is there a way to send parameters for the Builder? I'm using infyom and it comes with this great library. Was able to create a great collection with multiple joins. But I'm working on a report table, which I must send parameters for the filters. But right now I'm unable to set those parameters using the PHP classes itself and not the javascript code. Please let me know if there is an alternative or solution for this.

Regards

**Comment by yajra** [comment]
The DataTable class have `request()` method that you can use to access the request data.

```php
$this->request()->input('key');
```

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
