### ISSUE TITLE
overriding orderColumn method

### ISSUE THREAD

**Issue by thanasis-oob** [yajra/laravel-datatables#740]
### Summary of problem or feature request

Hi, 

I use your package and it looks pretty good!
I face up difficulties when I have complex order clauses. Instead of filterColumn() that defines a callback function for specific column, the orderColumn() method has completely different functionality. I think that is very useful to have the ability to define a specific method for some column. Does it possible to be added this feature?

**Comment by yajra** [comment]
Not sure if I get this correctly, but you want to apply a custom ordering to a lists of columns right? We have `orderColumns` api that I think you can use:

```php
public function orderColumns(array $columns, $sql, $bindings = [])
    {
        foreach ($columns as $column) {
            $this->orderColumn($column, str_replace(':column', $column, $sql), $bindings);
        }

        return $this;
    }
```

See this PR https://github.com/yajra/laravel-datatables/pull/679 for use case.

**Comment by yajra** [comment]
If not, please elaborate by using codes ^_^. Thanks!

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
