### ISSUE TITLE
How to use Excel and PDF methods from standard usage.

### ISSUE THREAD

**Issue by mathieutu** [yajra/laravel-datatables#745]
Hi, I'm trying to use the Excel and PDF export function, but I'm not in the service part of Datatable.
Is it possible to do that from the datatable package or should I make custom function directly from Dompdf and ExcelLaravel ?

Thanks !

**Comment by yajra** [comment]
@mathieutu  you need to make a custom function directly from dompdf/laravel-excel if you are not using the Service class.

**Comment by mathieutu** [comment]
Ok too bad...
Thank's
