### ISSUE TITLE
Searching Date Columns

### ISSUE THREAD

**Issue by seivad** [yajra/laravel-datatables#747]
This is slightly different to the d/m/Y issue posted recently, I too want to be able to search via d/m/Y although the database is Y-m-d. 

This is not working correctly:

```
            ->filterColumn('projects.due_date', function ($query, $date) {
                // $query->whereRaw("CONCAT(users.id,'-',users.id) like ?", ["%{$date}%"]);
                if (strlen($date) == 10) {
                    $date = Carbon::parse($date)->format('Y-m-d');
                    $query->where('due_date', $date);
                }
            })
```

I went with strlen == 10 as 01/01/2016 is 10 characters, anything less and I'm assuming Carbon will fail to create a parsable date. 

Any help would be appreciated.

**Comment by yajra** [comment]
I recently updated this [carbon demo](https://datatables.yajrabox.com/fluent/carbon) and implemented a custom date search. Have a look at it for ref.

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!

**Comment by raghbendra2015** [comment]
Hi Arjay Angeles

I have tried these three solution but not working search on date column.
Actually I am displaying date in grid like "DD-MM-YYYY" but search is not working.
->filterColumn('hull_survey_due_date', function ($query, $keyword) {
                    $query->whereRaw("DATE_FORMAT(hull_survey_due_date,'%d-%m-%Y') like ?", ["%$keyword%"]);
                })
==================================================
->filterColumn('hull_survey_due_date', function ($query , $keyword) {
                    if (strpos($keyword, '-')  !== false) {
                        $val = collect(explode('-', $keyword))
                            ->reverse()
                            ->implode('-');
                        $query->where("hull_survey_due_date","like","%$val%");
                    }
                })
==================================================
->filterColumn('hull_survey_due_date', function ($query, $date) {
                     $query->whereRaw("CONCAT(users.id,'-',users.id) like ?", ["%{$date}%"]);
                    if (strlen($date) == 10) {
                        $date = Carbon::parse($date)->format('Y-m-d');
                        $query->where('hull_survey_due_date', $date);
                    }
                })*
==================================================

Could you please help me out if anything is wrong
