### ISSUE TITLE
How to modify the search query

### ISSUE THREAD

**Issue by vkosachev** [yajra/laravel-datatables#748]
### Summary of problem or feature request

When serverSide processing is on, the global search is also sending a request to server for searching. The problem happens when I have in table virtual columns that do not exist on table.

So the question can be one of the following:
1) How to modify the search query in this case?
2) How to set search to be looking on client side, while pagination and etc - to remain server side.

http://screencloud.net/v/y5zX - this shows the error.
### Code snippet of problem

**THE MODEL**

``` php
class Coupon extends BaseModel
{

    const TYPE_REWARD  = 1;
    const TYPE_ONBOARD = 2;


    public $appends = ['display_type'];

    public function getDisplayTypeAttribute()
    {
        return (int)$this->type === self::TYPE_REWARD ? 'Rewards' : 'Onboarding';
    }
```

**DATATABLE FILE**

``` php
class CouponDataTable extends BaseDataTable
{
    protected function getColumns()
    {
        return [
            'id',
            'code' => [
                'title' => 'Code'
            ],
            'price',
            'display_type' => [
                'title' => 'Type'
            ],
            'used'=> [
                'title' => 'Used/Unused'
            ],
            'status',
            'created_at',
            'expiry_date',
            'actions' => [
                'sortable' => false,
                'orderable' => false,
                'className' => 'col-xs-1'
            ]
        ];
    }

    public function ajax()
    {
      return $this->datatables->eloquent($this->query())->make(true);
    }

    public function query()
    {
        $query = $this->repository->getQB();  //get the query builder 
        return $this->applyScopes($query);
    }
}
```

-->
### System details
- Operating System - Ubuntu 14.04
- PHP Version - PHP 7.0
- Laravel Version - 5.2.45
- Laravel-Datatables Version 6.18.1

**Comment by yajra** [comment]
Since `display_type` column is not part of the query, then technically it's not possible to search/sort with it. However, a trick you can do is implement a custom query using like `CASE` statement to fetch the display_type value on the SQL side.

**Comment by vkosachev** [comment]
Hey, thanks for the hint. Well, technically it will solve it only in this specific case, not on every virtual column. Can you point out if it is possible to ovveride the searching sql in a datatable file?
So for ex.. if I need complex conditions on search I can just override the default one
