### ISSUE TITLE
how do you add a function in the attributes

### ISSUE THREAD

**Issue by prolonginc** [yajra/laravel-datatables#749]
i am trying to add the initComplete  function using the Datatables Service Provider Implementation, i tried adding it using the parameter but it putting "" on the function itself.

```
$('#example').dataTable( {
  "initComplete": function( settings, json ) {
    $('div.loading').remove();
  }
} );


```

above is what i am trying to accomplish this should go for any kind of other functions i am just having a problem understanding how to add the callable into the parameters. 

Thank you

**Comment by yajra** [comment]
@prolonginc just pass the initComplete function as plain text on the parameters like: 
```php
->parameters([
'initComplete' => "function( settings, json ) {
    $('div.loading').remove();
  }"
])
```

**Comment by prolonginc** [comment]
first thank you for the quick reply, 
I apologize i should have mentioned that i tried that exact approach, however i get an error `jquery.dataTables.min.js:75 Uncaught TypeError: b.fn.apply is not a function`

**Comment by prolonginc** [comment]
for anyone that needs to add this event (very helpful ) this method worked with the datatables service provider 
`    $(function() {
        var table = $('#dataTableBuilder').DataTable();
        $('#dataTableBuilder').on( 'init.dt', function () {
             console.log('whatever');
        } );
    });
`

**Comment by yajra** [comment]
@prolonginc yes, that script should also do the trick. However, I find it weird why `initComplete` did not work. It seems to work well on this [demo](https://datatables.yajrabox.com/services/users-with-footer)

**Comment by prolonginc** [comment]
yeah it was very strange honestly could not go further with debugging so i started exploring other options.

**Comment by yajra** [comment]
Closing old questions. Please open a new one if still having issues. Thanks!
