### ISSUE TITLE
Searching for name from `belongsToMany` relationship

### ISSUE THREAD

**Issue by OzanKurt** [yajra/laravel-datatables#750]
### Summary of problem or feature request

Let me start by explaining my case. I have a large database of users to display, so I am using server-side filtering. In my table, i have a column called `Membership Types` this is a concatenation  of `membership_type.name`s.

``` php
// I can reach the value I want to put to the table like this.
$value = $user->currentMembership->membershipTypes->implode('name', ' / ');
```

I was able to display the table as I wanted, but it would be great to let the client filter through the names.

For example:

``` php
// User1 has the types `Boxer`, `Official` and `Coach`
// User2 has the types `Boxer` and `Coach`
// User3 has the types `Boxer`
```

If the client were to type `Coach` he should be able to get `User1` and `User2`.
- Laravel Version `5.2`
- Laravel-Datatables Version `6.18`

Regards,
Ozzy

**Comment by yajra** [comment]
Thanks for reporting, I haven't really tried doing a `belongsToMany` with the package. But I will try to make a demo for this to test if it's supported. If not, then will try to add a support for it. Will try to do it as soon as I can. Thanks!

**Comment by OzanKurt** [comment]
@yajra Is there chance for me to add some stuff to your documentation website? I read your whole repository and have some real-life use cases. I could help. :)

**Comment by yajra** [comment]
@OzanKurt , yes. Would really appreciate it if you can contribute to the docs. Just send a PR on the [demo repo](https://github.com/yajra/laravel-datatables-demo). Thanks!

**Comment by barryvdh** [comment]
Did either one of you figure out belongsToMany searching?

**Comment by ChaosPower** [comment]
@barryvdh I did a work around.

```php

if ($this->request->get('producer') != '') {
            if (is_numeric($this->request->get('producer'))) {
                $producer = $producer->where('producer.producerid', '=', (int)$this->request->get('producer'));
            } else {
                $producer = $producer->where('upper(producername)', 'LIKE',
                    '%' . strtoupper($this->request->get('producer')) . '%');
                $producer = $producer->orWhere('upper(produceralias)', 'LIKE',
                    '%' . strtoupper($this->request->get('producer')) . '%');
            }
        }
```

**Comment by yajra** [comment]
@barryvdh I just added a demo for [belongs-to-many](https://datatables.yajrabox.com/relation/belongs-to-many) and the approach is just like the has-many demo but please take note of the `distinct` query added to avoid duplicate data since it's many to many relationships.
