### ISSUE TITLE
Value in 'Search' Parameter of Request

### ISSUE THREAD

**Issue by yugidestiny** [yajra/laravel-datatables#752]
Hi, May I know where is search value of below function originated from?

`public function isSearchable()
    {
        return $this->get('search')['value'] != '';
    }`

**Comment by yugidestiny** [comment]
I see. Thank you very much. Actually I wan to find the "value" in Search parameter because due to unknown reason somehow it only return `search: {regex: "false"}` instead of `search: {value: "", regex: "false"}`. Can you please teach me in which function this Search parameter was created?

**Comment by yajra** [comment]
@yugidestiny not sure about that as It is bundled within the `dataTable.js` file. Try inspecting the ajax request to see the query string sent to the server. You might be overriding the search value on your form?

**Comment by yugidestiny** [comment]
Thanks for your advices. It appeared that something to do with server error which omitted the search value if it was empty. I will close this issues.
