### ISSUE TITLE
Display wrong information for first column

### ISSUE THREAD

**Issue by Samadhini** [yajra/laravel-datatables#753]
Hi Yajra,
yajra, really like the package. but when i display the data using server side processing, initially it always shows 1-10 for first column in first page. 

but if i select value in show entries dropdown, it shows correct details in first column
And i cannot get the search , sort to work.

My code:
$message = DB::table('messages')
			->leftJoin('message_recipients', 'messages.id', '=', 'message_recipients.message_id')
			->leftJoin('users', 'message_recipients.user_id', '=', 'users.id')
			->select(array('messages.*', 'message_recipients.user_id', 'users.first_name',    'users.last_name', 'messages.id as mid'))
			->orderBy('mid', 'DESC');

return Datatables::of($message)
				->editColumn('recipients_id', function($message){
					return $message->user_id;
				})
				->editColumn('recipients_name', function($message){
					return ($message->first_name);
				})
				->editColumn('message_type', function($message){
					return ucwords(strtolower(str_replace("_"," ",$message->message_type)));
				})
				->editColumn('message_method', function($message){
					return ucwords(strtolower(str_replace("_"," ",$message->message_method)));
				})
				->make(true);

Js:
oTable = $('#notificationListTable').DataTable({
      	processing : true,
      	serverSide:true,
      	ajax:'{!! route('notification-datatables-data') !!}',
      	pagelength :10,
      	columns:[
           { data: 'message_id', name: 'message_id'},
            { data: 'recipients_id', name: 'recipients_id' },
            { data: 'recipients_name', name: 'recipients_name' },
            { data: 'subject', name: 'subject' },
            { data: 'body', name: 'body' },
            { data: 'header', name: 'header' },
            { data: 'sent', name: 'sent' },
            { data: 'message_type', name: 'message_type' },
            { data: 'message_method', name: 'message_method' },
            { data: 'created_at', name: 'created_at' }
      	],
		"order":[[9, 'desc']],
        "dom": '<"top"f>rt<"bottom"ilp><"clear">',
        "scrollX":true
      });

**Comment by yajra** [comment]
Most probably this is due to ambiguous column name issue since you are using join statement. See this [demo](https://datatables.yajrabox.com/eloquent/joins) for ref on how to fix it.

**Comment by Samadhini** [comment]
thank you yajra. yaa it is because of ambiguous column name.
