### ISSUE TITLE
How to add search functionality for edit column 

### ISSUE THREAD

**Issue by Samadhini** [yajra/laravel-datatables#754]
Hi yajra,
there is some problems when i edit column.
in this case,  i cannot search on 'email field as well as 'Guest' in full_name column'

``` php
return $datatables = Datatables::of($abdReservations)
            ->editColumn('abandonedemail', function($abdReservations){
                if(!($abdReservations->user_id == 0))
                                     return $abdReservations->uemail;
                               else{
                                     return $abdReservations->email;  }  })
            ->editColumn('full_name', function($abdReservations){
                if($abdReservations->user_id == 0)
                                     return 'Guest';
                               else{  return $abdReservations->full_name; }  })     
            ->filterColumn('full_name', function($query, $keyword) {
                if($abdReservations->user_id == 0) {
                    //in this i want to find all the rows which as 'Guest' has full_name
                 }
                else{
                              //in this i want to execute following query.(but if i  used if else in filter column it shows ajax error, but if didn't use if-else it didn't search for 'Guest' )
                $query->whereRaw("CONCAT(users.id,'/',users.first_name,' ', users.last_name) like ?", ["%{$keyword}%"]);
         }  })
        ->make(true);
```

i'll appreciate your help yajra !

**Comment by yajra** [comment]
I think you can just use your if condition in the query since `user_id==0` represents `Guess`. 

```php
if ($abdReservations->user_id == 0) {
    $query->where('user_id', 0);
}
```

**Comment by yajra** [comment]
Or something like raw sql:

```php
if ($abdReservations->user_id == 0) {
    $query->whereRaw("'Guest' like ?", [$keyword]);
}

**Comment by Samadhini** [comment]
the thing is when i used if else in filter column function it gives ajax error,
->filterColumn('full_name', function($query, $keyword) {
	 if($abdReservations->user_id == 0) {
	                $query->where('user_id', 0);
	  }
	  else{
	         	 $query->whereRaw("CONCAT(users.id,'/',users.first_name,' ', users.last_name) like ?", ["%{$keyword}%"]);
	   }

**Comment by yajra** [comment]
Better inspect the ajax request to get a better hint of what was causing the issue. Might be an SQL exception was thrown.

**Comment by Samadhini** [comment]
yajra, there are some issues

- when i used if else inside filterColumn function it gives AJAX ERROR like 'Undefined variable: abdReservations'


- when i pass $abdReservations as parameter to the filterColumn, it gives AJAX ERROR ' Missing argument 3 for App\Src\Modules\Admin\Controllers\{closure}()  '

**Comment by yajra** [comment]
@Samadhini, based on the error dump, this is the correct behavior and what you need to do is to convert the if condition to SQL level since `filterColumn` is a process where we modify the queries. Hence, there is no values available on this method like `$abdReservations`. Try using SQL IF or CASE WHEN statements. Try following the solution on this SO post. Just convert it to laravel way.

http://stackoverflow.com/questions/15683185/if-else-in-where-clause-mysql

**Comment by Samadhini** [comment]
thank you very much yajra. Your point is a big help for me.
i need to change select statement. we should used 'if else' within select statement instead of filter column.

we should use this,
select(array(  DB::raw('(CASE WHEN abandoned_reservations.user_id = 0 THEN "Guest" ELSE CONCAT(users.id, "/", users.first_name , " " , users.last_name) END) AS full_name')  ));

instead of this,
 select(array( DB::raw("CONCAT(users.id,'/',users.first_name,' ', users.last_name) as full_name") ));

and finally we should modify filter column as well as like below.

->filterColumn('full_name', function($query, $keyword) {
	         	$query->whereRaw("(CASE WHEN abandoned_reservations.user_id = 0 THEN '%Guest%' ELSE CONCAT(users.id, users.first_name , users.last_name) END) like ?", ["%{$keyword}%"]);
	       })
