### ISSUE TITLE
Is it's support unicode UTF-8

### ISSUE THREAD

**Issue by monkhsaikhan** [yajra/laravel-datatables#755]
How to fix this?

i wrote on the search input 

![capture](https://cloud.githubusercontent.com/assets/6801431/18552017/c201a2e6-7b95-11e6-8ef1-e148abf611b2.PNG)

error:

![capture1](https://cloud.githubusercontent.com/assets/6801431/18551813/0ae40072-7b95-11e6-9015-25313927850d.PNG)

this is my controller function:

![capture2](https://cloud.githubusercontent.com/assets/6801431/18551828/1ba3b7cc-7b95-11e6-9416-e3a7f3e1c362.PNG)

this is my js:

![capture3](https://cloud.githubusercontent.com/assets/6801431/18551842/2626b870-7b95-11e6-8a1c-8ce3e199a1b4.PNG)

**Comment by yajra** [comment]
I think this is on database level configuration. See this SO post for possible fix.

http://stackoverflow.com/questions/3029321/troubleshooting-illegal-mix-of-collations-error-in-mysql
