### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#756]
Hi @yajra ,

can I ask is it possible to use `@can`  to hide the delete button if the user is not enough permission?

Here is my code but I am having problem in applying `@can`
```
       return Datatables::of($d)
            
            ->addColumn('action', function ($c) {
                return '<a href="cu/' . $c->id . '/edit" > Edit</a>
              
                    <a href="#">Delete</a>
              
                ';

            })
            ->make(true);

```

Thank you in advance.

**Comment by yajra** [comment]
You can use view for easier mark up.

```php
 return Datatables::of($d)
            ->addColumn('action', function ($c) {
                return view('partial.action', compact('c'))->render();
            })
            ->make(true);

// partials.action
@can('action')
<a>Delete</a>
@endcan
```

**Comment by ezekel** [comment]
@yajra ,

you mean like this in my view ?

```
<table width="100%" class="table table-bordered table-striped" id="my-table">
                                <thead>
                                <tr>
                                    <th>A</th>
                                    <th>B</th>
                                    <th>C</th>
                                    <th>D</th>
                                    <th>E</th>
                                    @can('action')
                                       <a>Delete</a>
                                    @endcan

                                </tr>
                                </thead>


                            </table>




```

**Comment by ezekel** [comment]
@yajra ,

Do I Need also to transfer the edit button in the view ? but I am confuse where I will put the edit button after </thead > ?

**Comment by ezekel** [comment]
@yajra ,

It's not working, it will loop and keep datatables infinit draw.

**Comment by BAKTETE** [comment]
when using partials the response become too slow 20 seconds +

**Comment by Palazzino** [comment]
Hello @yajra i need your help please, with add a helpers @can @endcan in my datatable...

have this code, but can't make the exactly code for work... thanks for ur time...

`Route::get('clientes', function (){
	$user = Auth::user();
	return datatables()
	->eloquent(GastosComunes\Clientes::query())
	->addColumn('action', function ($cliente) {
		return '<a href="' . route("clientes.show", $cliente->ID) . '" class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a> ' .
		'<a href="' . route('clientes.edit', $cliente->ID) . '" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a> ' .
		'<a href="#" value="' . $cliente->ID . '" class="btn btn-danger btn-sm" id="btnEliminar"><i class="fa fa-trash"></i></a>';
	})
	->make(true);
});`

**Comment by Palazzino** [comment]
Hello @yajra  i need your help please, with add a helpers @can @endcan in my datatable...

have this code, but can't make the exactly code for work... thanks for ur time...

Route::get('clientes', function (){
$user = Auth::user();
return datatables()
->eloquent(Space\Clientes::query())
->addColumn('action', function ($cliente) {
return '<a href="' . route("clientes.show", $cliente->ID) . '" class="btn btn-info btn-sm"> ' .
' ' .
'';
})
->make(true);
});

**Comment by Palazzino** [comment]
Hello @yajra i need your help please, with add a helpers @can @endcan in my datatable...

have this code, but can't make the exactly code for work... thanks for ur time...

Route::get('clientes', function (){
$user = Auth::user();
return datatables()
->eloquent(Space\Clientes::query())
->addColumn('action', function ($cliente) {
		return '<a href="' . route("clientes.show", $cliente->ID) . '" class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a> ' .
		'<a href="' . route('clientes.edit', $cliente->ID) . '" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a> ' .
		'<a href="#" value="' . $cliente->ID . '" class="btn btn-danger btn-sm" id="btnEliminar"><i class="fa fa-trash"></i></a>';
	})
	->make(true);
});

**Comment by Palazzino** [comment]
Hello @yajra  i need your help please, with add a helpers @can @endcan in my datatable...

have this code, but can't make the exactly code for work... thanks for ur time...

`Route::get('clientes', function (){
$user = Auth::user();
return datatables()
->eloquent(Space\Clientes::query())
->addColumn('action', function ($cliente) {
		return '<a href="' . route("clientes.show", $cliente->ID) . '" class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a> ' .
		'<a href="' . route('clientes.edit', $cliente->ID) . '" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a> ' .
		'<a href="#" value="' . $cliente->ID . '" class="btn btn-danger btn-sm" id="btnEliminar"><i class="fa fa-trash"></i></a>';
	})
	->make(true);
});`

**Comment by yajra** [comment]
Just use a regular if?

```php
Route::get('clientes', function (){

return datatables()
->eloquent(Space\Clientes::query())
->addColumn('action', function ($cliente) {
  $actions = '';
  $user = Auth::user();
  if ($user->can('view')) {
    $actions .=  '<a href="' . route("clientes.show", $cliente->ID) . '" class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a> ';
  }
  return $actions;
})
->make(true);

});
```

**Comment by Palazzino** [comment]
Thank bro, i add this code but have a detail

this line making reference to if ($user->can('view')) ...

I don't understand what mean 'view' if is a method in my controller or a route of view... please if is you can help mem thank @yajra 

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function can() on null
  
Thank you
