### ISSUE TITLE
Is there any way to use this package with "PostgreSQL function" AKA stored procedure? 

### ISSUE THREAD

**Issue by xparthx** [yajra/laravel-datatables#757]
Hello,

I want to use this with "PostgreSQL stored procedure", but I have no idea how to do that. 

Any help would be appreciated.

Thanks,
Parth vora

**Comment by yajra** [comment]
I think It depends on the procedure. Does your procedure return a cursor? If yes, try wrapping it into a collection. But I suggest using a temp table that will be populated by the store proc when called? Then use that table to display on dataTables?

**Comment by ChaosPower** [comment]
@xparthx can try doing something like DB::select('execute procedurename`); ?

**Comment by yajra** [comment]
Closing old issue. Please open a new one if needed. Thanks!
