### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by joaowall** [yajra/laravel-datatables#758]
Hi, 

How can I show the date and search in dd/mm/YYYY format?

Thanks

**Comment by yajra** [comment]
See this demo for ref: https://datatables.yajrabox.com/fluent/carbon

**Comment by joaowall** [comment]
Thanks yajra.

**Comment by marcelogarbin** [comment]
I have the date format in pt_br (21/11/2017 13:55:00), I tried to use the filterColumn(), but I didn't succeed.

```
->filterColumn('data_hora', function ($query, $keyword) {
                    $query->whereRaw("DATE_FORMAT(data_hora,'%d/%m/%Y %H:%i:%s') like ?", ["%$keyword%"]);
                })
```

My version is: v7.10.1

Did you get this to work?

Thank's

**Comment by albertoelias123** [comment]
Hello, I recently had a similar problem formatting dates and then filtering with date formatata. The following code worked very well with me:

    return Datatables::of(
        Contact::query()
    )->filterColumn('created_at', function ($query, $keyword) {
        $query->whereRaw("DATE_FORMAT(created_at,'%d/%m/%y %H:%i') like ?", ["%$keyword%"]);
    })
    ->filterColumn('updated_at', function ($query, $keyword) {
        $query->whereRaw("DATE_FORMAT(updated_at,'%d/%m/%y %H:%i') like ?", ["%$keyword%"]);
    })
    ->make(true);


In addition, you must format the column, for this I used a mutation, but it is also possible to use the editColumn method. Below is the mutation in Model:

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/y H:i');
    }

    public function getUpdatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/y H:i');
    }

Example using editColumn and filterColumn:

    return Datatables::of(
        Contact::query()
    )->editColumn('created_at', function ($contact){
        return date('d/m/y H:i', strtotime($contact->created_at) );
    })
    ->filterColumn('created_at', function ($query, $keyword) {
        $query->whereRaw("DATE_FORMAT(created_at,'%d/%m/%y %H:%i') like ?", ["%$keyword%"]);
    })
    ->editColumn('updated_at', function ($contact){
        return date('d/m/y H:i', strtotime($contact->updated_at) );
    })
    ->filterColumn('updated_at', function ($query, $keyword) {
        $query->whereRaw("DATE_FORMAT(updated_at,'%d/%m/%y %H:%i') like ?", ["%$keyword%"]);
    })
    ->make(true);
