### ISSUE TITLE
Custom print message view and templating

### ISSUE THREAD

**Issue by jakaprima** [yajra/laravel-datatables#759]
### custom print preview message

sir, i want to make customize print like want to make a title text before table, visible border of table, or make image in print preview how i can to do that?

       'message' => 'This print was produced using the Print button for DataTables', 
not work in my yajra datatable but work on datatable.net

### Code snippet of problem

  ->parameters([

            'dom' => 'Bfrtip',
            'buttons' => [
                [
                'extend' => 'print',
                'message' => 'This print was produced using the Print button for DataTables',
                'text' => 'Print all',
                'exportOptions' => [
                     'columns' => ':visible'
                ],
                ],
            'csv',
            'pdf',

            ],
        ]);

- Operating System
- PHP Version
- Laravel Version 5.2
- Laravel-Datatables Version

**Comment by yajra** [comment]
The print options should be modified via print preview by overriding the default view used in printing.

```php
class TransactionsDataTable extends DataTable
{
    protected $printPreview = 'transactions.print';
...
```

Copy `resources/views/vendor/datatables/print.blade.php` content to `resources/views/transactions/print.blade.php` and append any necessary info you wanted to print.

**Comment by jakaprima** [comment]
thanks yajra i skip to seen this helper :D
// protected $printPreview  = 'path.to.print.preview.view';
now it work successfully

**Comment by alejandri** [comment]
Thanks. Works fine on Laravel 5.6.
How I can pass these search parameters to view transactions.print? 
Is very useful print 

> List of Users. (created between 2018-05-05 to 2018-06-05 ) 

for example...
