### ISSUE TITLE
Colspan troubles

### ISSUE THREAD

**Issue by ricardoisec** [yajra/laravel-datatables#761]
Hi!

I have a bunch of datatables with serverside processing on very big page that features tabbed navigation. For simplicity lets assume there is a datatable on tab1 and a datatable on tab2. Lets also assume there isn't data for those datatables yet so I'm getting the "No results found" message, as expected.

The problem is this: if tab1 has focus during page load the message will be correctly shown with an appropriate colspan BUT on the tab2 the message will be shown with incorrect colspan. The situation reverses if tab2 has focus during page load.

This image shows the message with the correct colspan that is shown if this tab has focus during page load (sorry for foreign language messages).
![image](https://cloud.githubusercontent.com/assets/8938688/18720526/12ffdd6a-8024-11e6-85d5-0c4ea6bed101.png)

This images shows the message with the incorrect colspan that is shown on the tab that has not received focus during page load.
![image](https://cloud.githubusercontent.com/assets/8938688/18720560/3f7b4d02-8024-11e6-9eaa-fb772c2169b3.png)

My controller is as follows:

```
$multimedia = TourMultimedia::where('tour', $tour->id)->get();

$datatables = Datatables::of($multimedia)
            ->addColumn('#', function ($i) {
                static $i = 1;
                return $i++;
})
// etc, I just add a few more columns
});

return $datatables->make(true);
```

My datatable JS is as follows:

```
$('#imageTable').DataTable({
                processing: true,
                serverSide: true,
                filter: true,
                paging: true,
                language: {
                    url: "{{ asset('backoffice/global/plugins/datatables/plugins/i18n/portuguese.json') }}"
                },
                ajax: {
                    type: 'POST',
                    url: "{{  url('admin/ajax/tour/datatablemultimedia') }}",
                    data: {
                        'token': "{{ $tour->token }}"
                    }
                },
                columns: [
                    {data: 'id', name: 'id', visible: false},
                    {data: '#', name: '#'},
                    {data: 'image', name: 'image', orderable: false, searchable: false},
                    {data: 'description', name: 'description', orderable: false, searchable: false},
                    {data: 'actions', name: 'actions', orderable: false, searchable: false}
                ]
            });
```
### System details
- I'm using XAMPP on Windows
- PHP 7.1.0
- Laravel 5.2.45
- Laravel-Datatables latest as I did a composer update

Any ideas of what I might be doing wrong or otherwise solve the problem?

**Comment by yajra** [comment]
Are you using a single script to load multiple dataTables? This might be solve via js tricks but not yet sure how. Based on this contributed [demo](https://datatables.yajrabox.com/services/two-datatables), it loads well on tabbed dataTables.

**Comment by ricardoisec** [comment]
I'm using the same script for all datatables and I've seen the demo but the colspan problem only happens when there is no data and you get that "No results found" string that should colspan the whole table.

**Comment by yajra** [comment]
Sorry for late response. I think the issue here on the client side and is not in the scope of the project. Maybe try asking on datatables.net forums if still having the issue. Thanks!
