### ISSUE TITLE
Search column's with presenter 

### ISSUE THREAD

**Issue by mprandot** [yajra/laravel-datatables#763]
Hello!

I have problem to search in custom columns, the search works in this case? See my example.
Search return no data.
It's a presenter problem?
### Snippet

``` php
 return Datatables::of($registros)
            ->addColumn('action', function ($registro) {
                 return "buttons";
            }) 
            ->editColumn('nome-razao_social', function ($registro) {
                if (!empty($registro->nome)) {
                    return $registro->nome;
                } 
                    return $registro->razao_social . ' <BR> ' . $registro->fantasia;
            })
            ->editColumn('cpf-cnpj', function ($registro) {
                if (!empty($registro->cpf)) {
                    return $registro->cpf;
                }
                    return $registro->cnpj;
            })
            ->editColumn('fones', function ($registro) {
                return $registro->fone . ' <BR> ' . $registro->fone2;
            })
            ->editColumn('tipo-pessoa', function ($registro) {
                return $registro->present()->cadastradoComoAtt;
            })
            ->make(true);
```

``` javascript
 $(function () {
            var pathname = window.location.pathname;
            $('#table-pessoa').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{route('pessoa.datatable')}}',
                    data: {url: pathname}
                },
                columns: [
                    {data: 'nome-razao_social', name: 'nome-razao_social'},
                    {data: 'cpf-cnpj', name: 'cpf-cnpj'},
                    {data: 'fones', name: 'fones'},
                    {data: 'tipo-pessoa', name: 'tipo-pessoa'},
                    {data: 'action', name: 'Ações', orderable: false, searchable: false}
                ], "language": {
                    "url": '{{asset('vendor/datatables/DataTable-pt-BR.json')}}'
                }
            });
        });
```
- Ubuntu 16.04
- 7.0.8
- 5.1
- "yajra/laravel-datatables-oracle": "^6.0",

**Comment by yajra** [comment]
Since your editing the columns, you also need to change how to filter the columns to match how it was displayed. Try using [`filterColumn`](https://datatables.yajrabox.com/eloquent/post-column-search) api and convert your edited columns to an equivalent SQL command.

**Comment by mprandot** [comment]
Cool!
In my case i don't have the cpf-cnpj column in database (on the fly).
i have add the filterColumn method, but still not work

I use two columns in this search (cpf, cnpj), the code bellow it is correct? 

```php
            ->editColumn('cpf-cnpj', function ($registro) {
                if (empty($registro->cpf)) {
                    return $registro->cnpj;
                } else {
                    return $registro->cpf;
                }
            })
            ->filterColumn('cpf-cnpj', function($query, $keyword) {
                $query->whereRaw("cpf like ?", ["%{$keyword}%"])
                      ->whereRaw("cnpj like ?", ["%{$keyword}%"]);
            })
```

**Comment by mprandot** [comment]
@yajra, can you help me?

**Comment by yajra** [comment]
@mprandot your code looks fine but I think you need to use orWhere clause like:
```php
->filterColumn('cpf-cnpj', function($query, $keyword) {
     $query->whereRaw("cpf like ?", ["%{$keyword}%"])
         ->orWhereRaw("cnpj like ?", ["%{$keyword}%"]);
})
```

You may also want to add case insensitive search by adding `upper(cnpj) like upper(?)` on your sql.

**Comment by mprandot** [comment]
Not work,
i've debugged the datatables and the debugger not passed on filterColumn method.
i'm using datatables with collection, can be the problem?

**Comment by yajra** [comment]
@mprandot yes, collection must be the problem. filterColumn is for Eloquent and Query Builder.

**Comment by mprandot** [comment]
@yajra

Amazing ! 
So now, i have another problem, i have a "on the fly" column named : `nome-razao_social`  in datatables, when i pass the QueryBuilder to method `make`  (with filterColumn ) the package try to order by `nome-razao_social` column, but she no exists on database and is throwed me a SQL error.

I need create this field on my QueryBuilder or this is a behavior of datatables and a i need do something?
I looked in documentation and can't find nothing about `orderColumn`.
Thank's!

**Comment by yajra** [comment]
See [orderColumn](https://yajrabox.com/docs/laravel-datatables/6.0/order-column) docs. Thanks!
