### ISSUE TITLE
Range Search For Dates Print

### ISSUE THREAD

**Issue by jakaprima** [yajra/laravel-datatables#764]
### Range Search For Dates Print

sir can you help me, i search to make datatable for search between date like this 
https://www.datatables.net/examples/plug-ins/range_filtering.html
or
http://www.thoughtdelimited.org/thoughts/demos/dataTablesDateRange/

how can i draw() datatable with yajra implementation? or trick for solution for this problem
- Operating System Windows 7
- PHP Version
- Laravel Version 5.2
- Laravel-Datatables Version

**Comment by yajra** [comment]
You can use `filterColumn` and apply the between query. See this [demo](https://datatables.yajrabox.com/eloquent/post-column-search) for ref.

For sending additional parameters to server, see this [demo](https://datatables.yajrabox.com/eloquent/advance-filter).

**Comment by jakaprima** [comment]
ok i do step by step
the datatable as a service filter coloum search why not work? by id or by date?

    /**
     * Display ajax response.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax()
{
    $query = $this->query();
    return $this->datatables
    ->eloquent($this->query())
            ->editColumn('tanggalkeluhan', function ($query) {
                return $query->tanggalkeluhan ? with(new Carbon($query->tanggalkeluhan))->format('d-m-Y / h:i:s') : 'h:i:s';
            })
             ->filterColumn('id', function($query, $keyword) {
                $query->whereRaw("CONCAT(id,'-',id) like ?", ["%{$keyword}%"]);
            })
    ->make(true);
}

**Comment by yajra** [comment]
For date searching, see https://datatables.yajrabox.com/fluent/carbon.

Closing old questions. Please open a new one if still having issues. Thanks!
