### ISSUE TITLE
paging not working using sql server 2005

### ISSUE THREAD

**Issue by ajiehatajie** [yajra/laravel-datatables#767]
why when I display a lot of data but its not working paging pages ?

I am using sql server 2005 database

**Comment by yajra** [comment]
Can you please paste your code? Thanks!

**Comment by ajiehatajie** [comment]
Blacklist.php
`
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blacklist extends Model
{
    //
	 protected $connection = 'cms';

   
     protected $fillable = ['id'];

     
     protected $table = 'tb_jadwal_push';
}

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Blacklist;#model
Use Datatables;

class BlacklistController extends Controller
{
    //


    public function getall()
    {
    	$data =Blacklist::all();
    	return Datatables::of($data)->make(true);
    }

    public function index()
    {
    	return view('blacklist.list');
    }
}


Routes



Route::get('/blacklist', 'BlacklistController@index');

Route::get('/blacklist/all', 'BlacklistController@getall');
`

**Comment by yajra** [comment]
Don't use all. That is the reason why paging is not working.

```php
$data =Blacklist::query();
return Datatables::of($data)->make(true);
```

**Comment by ajiehatajie** [comment]
I've tried but still not succeed. paging pages do not work

**Comment by yajra** [comment]
Can you paste your view/javascript?

**Comment by yajra** [comment]
Closing old issues. Please open a new one if needed. Thanks!
