### ISSUE TITLE
Applying filter functionality for custom date format

### ISSUE THREAD

**Issue by Samadhini** [yajra/laravel-datatables#768]
Hi, 
I have some problems related dates in datatables.

I am displaying timestamps in my table related to  user's time-zone. Although in the database, the dates are stored  UTC format How can I allow the global search term, to search these dates (the dates in user's time zone)
 
--helper function to convert date into user timezone,--
```php
public function getDateTimeToUserTimeZone($datetime, $format){
$dt = new DateTime($datetime, new DateTimeZone('UTC'));
$dt->setTimezone(new DateTimeZone($timezone));
return $dt->format($format);
}

--In Controller--
$datatables = Datatables::of($payments);
		    return $datatables
                     ->editColumn('payment_date', function($payments){
			   return DateTimeHelper::getDateTimeToUserTimeZone($payments->payment_date,   'm/d/Y h:i a');
			 })
                	  ->filterColumn('payment_date', function($query, $keyword) {
                        // in this i want to filer my dates
	         	$query->whereRaw("................................");
	        })
                ->make(true);
```

**Comment by yajra** [comment]
See this [demo](https://datatables.yajrabox.com/fluent/carbon) for possible fix/ref.

**Comment by Muhammadinaam** [comment]
How to do this in Laravel 4.2, Yajra Datatables version 3

**Comment by yajra** [comment]
@Muhammadinaam just replied on #774. Continue the thread there. Thanks!

**Comment by bjmercado** [comment]
hi @yajra filipino dev here, i want to filter the date of the logs by setting the range date. help? 

![image](https://cloud.githubusercontent.com/assets/25813633/23011581/9d06e7c6-f3d6-11e6-84e4-40a0472be7cd.png)

![image](https://cloud.githubusercontent.com/assets/25813633/23011603/c22a08ee-f3d6-11e6-8506-407c68b9db68.png)

filtering of auditable type and type is already working

**Comment by yajra** [comment]
@bjmercado wow kabayan 👍 . This is what I usually do on date range. Try using carbon to parse the date and maybe format to `Y-m-d` if needed.

```php
if ($request->has('from')) {
    $from = Carbon::parse($request->get('from'));

    if ($request->has('to')) {
        $to = Carbon::parse($request->get('to'));
        $query->whereBetween('created_at', [$from, $to]);
    } else {
        $query->whereDate('created_at', $from);
    }
}
```

**Comment by bjmercado** [comment]
@yajra kabayan ano problem kapag ganito?, na upload na kasi
![i199 pimgpsh_mobile_save_distr](https://cloud.githubusercontent.com/assets/25813633/25214147/8b49cc1a-254a-11e7-9239-186ec4a763f6.jpg)


sa local gumagana sya ganito 
![i200 pimgpsh_mobile_save_distr](https://cloud.githubusercontent.com/assets/25813633/25214213/e0dba112-254a-11e7-91c7-2cfc4d7805e7.jpg)


ito yung code
    public function lpfview(Request $request){
      $data =  $request->session()->get(config('app.projcode').'_user');
      $result = LpfForm::select(['id', 'control_no', 'account_no', 'jhsez_enter', 'inspected_by',  'status', 'message'])
      ->where('jhsez_enter', $data->locator_id)
      ->get();

      return DataTables::of($result)
      ->addColumn('pdf', function($result){
        if ($result->status == 0) {
          return '<a href="lpf-report/'.$result->id.'"  class="btn btn-info btn-sm" target="_blank">PDF</a>';
        }
        elseif ($result->status == 2) {
          return '<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#rejectGroup_modal'.$result->id.'" title="REJECT">Rejected</button>
          <div class="modal fade" id="rejectGroup_modal'.$result->id.'" role="dialog">
            <div class="modal-dialog">
              
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">
                    <strong>READ ME</strong>
                  </h4>
                </div>
                <div class="modal-body">
                  '.$result->message.'
                </div>
            </div>
          </div>
        </div>
          ';
        }
        else {
          return '<label>Pending</label>';
        }
      })
      ->addColumn('edit', function($result){
        if ($result->status != 0 ) {
            return '<a href="lpf-edit/'.$result->id.'" class="btn btn-info btn-sm" title="UPDATE">Update</a>';
        }
      })
      ->addColumn('delete', function($result){
        return '<button type="button" class="btn btn btn-warning btn-sm" data-toggle="modal" data-target="#deleteGroup_modal'.$result->id.'">Delete</button> <div class="modal fade" id="deleteGroup_modal'.$result->id.'" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title"><strong>READ ME</strong></h4></div><div class="modal-body"><h4><p>Are you sure you want to delete this user?</p></h4></div><div class="modal-footer"><a href="lpf-delete/'.$result->id.'" class="btn btn-danger">Delete</a></div></div></div></div>';
      })
      ->editColumn('jhsez_enter', function($result){
        return $result->locator->name;
      })
      ->make(true);
    }

**Comment by yajra** [comment]
Bro baka magkaiba version ng dataTables mo sa local and production? Anyways, malamang v7 ang nasa prod so dapat gamitan mo ng `->rawColumns(['edit' , 'delete'])`.

Para macheck mo version: `composer show`

**Comment by bjmercado** [comment]
@yajra ou nga so lahat ng steps dun sa documentation follow ko na lang?, or kahit yung html builder lang install ko

**Comment by yajra** [comment]
Mukhang di ka naman gumagamit ng html (laravel collective) at buttons so kahit main package lang. Optional lang yung 2 plugins.

**Comment by bjmercado** [comment]
@yajra it works 👍 thanks master!
