### ISSUE TITLE
General column search with filter() enabled

### ISSUE THREAD

**Issue by eness** [yajra/laravel-datatables#769]
### Summary of problem or feature request

I want to use default global column search of Datatables but also I want to use some custom eloquent clauses in `filter(function($query) { ........ }` method. But this method overrides the auto generated query and disables the column search that is located in the header.
### Code snippet of problem

``` php

          $users = Users::query()
          return \Datatables::of($users)
                ->filter(function ($query) { // this method disables original column search feature
                       $query->where('status', 1);
                })
          // ....
```
### System details
- Ubuntu/Nginx/MySQL
- PHP 7
- Laravel 5.2
- Laravel-Datatables 6.0

**Comment by yajra** [comment]
Just pass true as 2nd param on filter api to enable global search.

```php
->filter(function ($query) { // this method disables original column search feature
    $query->where('status', 1);
}, true)
```
