### ISSUE TITLE
[4.2] Showing only 10 results when serverside=false

### ISSUE THREAD

**Issue by Muhammadinaam** [yajra/laravel-datatables#773]
### Summary of problem or feature request

In JavaScript, when serverSide is set equal to false (serverSide:false) then datatable only shows 10 results even when there are more records in mysql table. But when serverSide is True, then it works correctly.

### Code snippet of problem

$('#datatable').DataTable({
        "processing": true, 
        "serverSide": true, //false doesnt work
        "ajax": "{{url('admin/brands-datatable')}}",
        "columns": [
            {data: 0,...

### System details

- Operating System
- PHP Version
- Laravel Version: 4.2
- Laravel-Datatables Version: 3.6.13

**Comment by yajra** [comment]
@Muhammadinaam server-side false is out scope of the package. Anyways, see this [branch](https://github.com/yajra/laravel-datatables/tree/L4) for Laravel 4.2 docs. Thanks!
