### ISSUE TITLE
Search Custom Date Format in Laravel 4.2

### ISSUE THREAD

**Issue by Muhammadinaam** [yajra/laravel-datatables#774]
### Summary of problem or feature request

Search does not work on date columns with custom format. It can be done in Latest version with filterColumn() function which is not available in yajrabox version 3 for Laravel 4.2. Please tell me how can we do this Laravel 4.2, Yajra Datatables version 3.

I have a project in L4.2 which cannot be changed to L5.2. Please help.

**Comment by yajra** [comment]
`filterColumn` is not available on L4.2 version but you can manually implement it via `filter` api. The downside is, you have to manually create all the search function for each fields that you need since `filter` method will disable global search.

**Comment by yajra** [comment]
See this docs/branch for ref: (https://github.com/yajra/laravel-datatables/tree/L4)
