### ISSUE TITLE
Display categories and category's childs with relationship

### ISSUE THREAD

**Issue by tuyenlaptrinh** [yajra/laravel-datatables#775]
Hello Everybody.
My name is Tuyen.
I have problem with yajra datatables
This is my app's construct

MySQL table

``` php
categories
- id
- name
- parent_id (this is root category id)
.....
```

Category Controller

``` php
.....
public function datatableCategories(){
    $categories = Category::with('childrens')->get();
    return Datatables::of($categories)->make(true);
}
.....
```

Relationship function in Category Model

``` php
....
public function childrens(){
    return $this->hasMany('Category','parent_id');
}
.....
```

I want to display data like this image.
![image](https://cloud.githubusercontent.com/assets/7567800/19011341/c5124098-87bc-11e6-8760-7c9afb01a0d7.png)

Please help me.
Thank you so much

**Comment by yajra** [comment]
Hi Tuyen, you can follow this [demo](https://datatables.yajrabox.com/relation/has-many) for ref. Also, I suggest you remove `get()` on `$categories = Category::with('childrens')->get();` for better response.

**Comment by tuyenlaptrinh** [comment]
Hi Yajra
I want to display like that on table
Category Name
- Child Category 1
- Child Category 2
.....

**Comment by tuyenlaptrinh** [comment]
Hello!
I think we need more function for your package for show children rows of parent row.
Like
```php
$categories = Category::with('childrens')->where('parent_id',0)->get();
return Datatables::of($categories)->addChild('child_row',function($category){
//something for show child category as a row after parent row
})->make(true);
```
Thank you

**Comment by yajra** [comment]
@tuyenlaptrinh thanks for the suggestion but I think it's not workable to add something like addChild since we still have to manage the UI using javascripts. 

Anyways, if you have some implementation in mind, please do not hesitate to submit a PR. Thanks!

**Comment by cod3rshotout** [comment]
@tuyenlaptrinh did you managed to achieve this?

**Comment by yajra** [comment]
Maybe try rowGrouping plugin https://datatables.net/examples/advanced_init/row_grouping but haven't tried if it will also work on nested relations.

**Comment by cod3rshotout** [comment]
@yajra unfortunately row grouping plugin is not the solution in this case
