### ISSUE TITLE
Print button does not fully work yet

### ISSUE THREAD

**Issue by bte2** [yajra/laravel-datatables#778]
### Summary of problem or feature request

I don't believe the print button is fully functional yet, perhaps this is stated and I missed it.

While the print button will bring up a print view, it doesnt seem to function as intended and there is no way to pass parameters to the print view for adding messages, visible columns, etc. (Can be viewed at https://datatables.yajrabox.com/services/two-datatables)

Within the datatables.net examples, print opens a new window and does an autoprint unless disabled. With the yajra laravel implementation, the print passes a bunch of get variables and displays a printable table, there doesn't seem to be any way of controlling the visible columns with extend, exportOptions or adding a message or changing the print view page title.

Also, the print button on https://datatables.yajrabox.com/services/two-datatables for the posts tables only displays data for the column "Created By" I am assuming this has to do with a similar issue of how the print options are being processed by the laravel framework.

Example of what I as using attempting to print all columns except for the last column

``` php
return $this->builder()
                        ->columns($this->getColumns())
                        ->addAction(['width' => '10%'])
                        ->ajax('')
                        ->parameters([
                            'dom' => 'lBfrtip',
                            'scrollX' => false,
                            'responsive' => true,
                            'buttons' => [
                                'create',
                                'reload',
                                [
                                    'extend' => 'colvis',
                                    'text' => 'Columns',
                                ],
                                [
                                    'extend' => 'collection',
                                    'text' => '<i class="fa fa-download"></i> Export',
                                    'buttons' => [
                                        'csv',
                                        'excel',
                                        'pdf',
                                    ],
                                ],
                                [
                                    'extend' => 'print',
                                    'title' => "Title",
                                    'exportOptions' => ['columns' => ':visible']
                                ]
                            ],
                            'columnDefs' => [
                                [
                                'targets' => -1,
                                'visible' => false
                                ]
                            ]
        ]);
```

**Comment by yajra** [comment]
@bte2 print button of the package does not work exactly like on the client side print button. If you want to customize the print output, you need to override the printPreview property of the class. See similar issue for some ref: https://github.com/yajra/laravel-datatables/issues/759

**Comment by Fionajeremychik** [comment]
I used laravel 6 but where is printPreview. The print button cannot print

 public function html()
    {
        return $this->builder()
            ->columns($this->getColumns())
            ->minifiedAjax()
            ->addAction(['width' => '120px', 'printable' => false])
            ->parameters([
                'dom'       => 'Bfrtip',
                'stateSave' => true,
                'order'     => [[0, 'desc']],
                'buttons'   => [
                    ['extend' => 'export', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'print', 'className' => 'btn btn-default btn-sm no-corner',],
                    ['extend' => 'reload', 'className' => 'btn btn-default btn-sm no-corner',],
                ],
            ]);
    }
