### ISSUE TITLE
Disabling the aggregate count query

### ISSUE THREAD

**Issue by wjgilmore** [yajra/laravel-datatables#779]
### Summary of problem or feature request

When laravel-datatables retrieves data for reason of populating a table, it executes two queries. The first is the `select count(*) as aggregate from...` query, and the second is the query used to actually retrieve the data.

The `select count(*) as aggregate from...` query is used to presumably populate the data found in the DataTables.js "Showing 1 to 4 of 4 entries (filtered from 98,799 total entries)" string. It is taking a significant amount of time, far more so than the query used to actually retrieve the data. For example in the particular example I'm dealing with right now the `select count(*) as aggregate from...` query takes 28.62 seconds to complete, whereas the data retrieval query is taking 0.5 seconds to complete.

All of the appropriate columns are indexed; it is just this counter query that is inexplicably consuming so much time. Is there any way to disable this query? We really don't need to show the result count on the page.

### Code snippet of problem

N/A

### System details

- Operating System OS X 10.11.6
- PHP Version 7.0.6
- Laravel Version 5.1
- Laravel-Datatables Version 6.17.0

Thank you!
Jason

**Comment by yajra** [comment]
You can use setTotalRecords api to achieve this. See this [demo](https://datatables.yajrabox.com/eloquent/manual-count) for ref.

**Comment by wjgilmore** [comment]
Works like a charm thank you so much!
