### ISSUE TITLE
How to Video 

### ISSUE THREAD

**Issue by techguydev** [yajra/laravel-datatables#78]
Hello Yajra,

Thanks a lot  for sharing this  great package.

It would be  great  if you could  make a video  showing  how  to run de basic  examples it  laravel 5.

Thanks

**Comment by yajra** [comment]
@lmatab , I am not good at doing videos and teaching but I will try to give it a shot on my free time.

**Comment by lmatab** [comment]
Hello, It is  finally working for me. I will  create a  video and share it here so  people can use  this  wonderful  package faster!, thanks.

**Comment by yajra** [comment]
Hi, that would be great if you could create and share the video. Thanks!

**Comment by basementjack** [comment]
I'm not bad at doing videos - Imatab - are you still going to do yours? If not, what were you looking for? just a recording of someone using the demo site?

**Comment by ssnukala** [comment]
Thanks for the package.

Do you guys have the video or an example script. I am going thru the code, before I spend the time figuring out what and how, would be great if you guys can share your example / video.

**Comment by lmatab** [comment]
Hello,

Jack if you have Time just make  the video. I have  been kind of busy.

**Comment by ssnukala** [comment]
While you guys create / upload the video. 
I installed the demo app, but not able to access the  demo page 
once installed on http://laravel-datatables.localhost 
and created a user to login.
what would be the URL to go to to see the POSTS and USERS table data in datatable ?

**Comment by yajra** [comment]
@ssnukala, routes for demo site are /eloquent/xxx, /fluent/xxx, /collection/xxx. See this link for a quick [starter tutorial](http://datatables.yajrabox.com/starter). Also, please post your concerns on the demo site [repo](https://github.com/yajra/laravel-datatables-demo). Thanks!

**Comment by RahamSher** [comment]
First of all I would like to pay my special Thanks to @yajra for such great work.
Dear @lmatab video tutorial will be the best option as well.Please if you can.It would be more better for beginners like me.
