### ISSUE TITLE
General language configuration for all the project datatables.

### ISSUE THREAD

**Issue by nicolaeturcan** [yajra/laravel-datatables#781]
Hi @yajra, thanks for this awesome package. 

I managed to change the language of the tables doing this:

`
            $htmlBuilder->parameters([ "language" =>  [
                "url" => "//cdn.datatables.net/plug-ins/1.10.12/i18n/Catalan.json"]
            ])
`

But I have a lot of tables more. Wouldn't it be a good idea to have a variable in order to set a general language for the application in the config/datatables.php file? Something like this:

`    'language' => [
        "url" => "//cdn.datatables.net/plug-ins/1.10.12/i18n/Catalan.json"
    ]
`

**Comment by gotrecillo** [comment]
I think it is fine, you can configure the script template to adjust to your needs.

You can just call an IIFE to override the datatables default configuration and calling them in your layout field or whenever you import the datatable.js script.



``` Javascript
(function ($, DataTable) {
  
    // Datatable global configuration
    $.extend(true, DataTable.defaults, {
        language: {
            "sProcessing": "Procesando...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "No se encontraron resultados",
            "sEmptyTable": "Ningún dato disponible en esta tabla",
            "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix": "",
            "sSearch": "Buscar:",
            "sUrl": "",
            "sInfoThousands": ",",
            "sLoadingRecords": "Cargando...",
            "oPaginate": {
                "sFirst": "Primero",
                "sLast": "Último",
                "sNext": "Siguiente",
                "sPrevious": "Anterior"
            },
            "oAria": {
                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
        }
    });

})(jQuery, jQuery.fn.dataTable);
```

**Comment by nicolaeturcan** [comment]
Thanks @gotrecillo for your helpful answer.

**Comment by Noor600** [comment]
thanks 
that's helpful
