### ISSUE TITLE
Datatables Search Totals

### ISSUE THREAD

**Issue by knox2** [yajra/laravel-datatables#782]
### Summary of problem or feature request

How go I get Search totals from the datatables search query assuming each user has a number of cars for example. I know how to get the total cars, but how to I get the total of a filtered result
### Code snippet of problem

```
$users = User::where('created_date',Carbon::now()->subYears(1));

        return Datatables::of($users)
            ->addColumn('total_cars', $user->sum('num_cars'))
           // ->addColumn('search_total_cars', ??)
            ->make(true);
```

**Comment by yajra** [comment]
@knox2 added column is not searchable since it's not part of the query. I suggest you try adding a sub-query to fetch the total and use `filterColumn` and do the necessary search sql. Another work around is by creating a view with the total and use it via query builder.

**Comment by knox2** [comment]
@yajra can i get access to the filtered query builder from the code ie something like this:
```
$users = User::where('created_date',Carbon::now()->subYears(1));

return Datatables::of($users)
            ->addColumn('total_cars', $user->sum('num_cars'))
            ->with('search_total_cars', $this->query()->sum('num_cars'))
            ->make(true);
```

**Comment by knox2** [comment]
Hi @yajra the column search_total_cars is just a number at the footer that sums the total of the column total_cars during search, how can i get the value

**Comment by yajra** [comment]
Sorry for late reply, you can get it using javascript. Regards!

**Comment by sandipsapkota1** [comment]
I am using Non service datatables(Am just using single function to get ajax), How can i  sum,
this function didnt worked for me,
 Also i dont have query() function in my class.
->with('totalqty',$this->query()->sum('total_quantity'))

Any idea?
