### ISSUE TITLE
Change column header AND use render function

### ISSUE THREAD

**Issue by TomAudre** [yajra/laravel-datatables#783]
### Summary of problem or feature request

I've been able to use the render function to combine the values of two columns into a single column, but I'm unable to change the column header title without breaking the render function. (I'm using the HTML builder)

Is there a way use render AND change the column header title?

Render works fine here:

``` php
 protected function getColumns()
 {
      return [
        'direction' => ['render' => function() { 
                return 'function(data, type, row) {return data + " (" + row.MWD +")";}';}]

    ];
}
```

I've tried defining the "title" attribute, which changes the column header, but breaks the render function

``` php
    protected function getColumns()
    {
        return [
            [
                'title' => 'Direction (MWD)',          
                'direction' => ['render' => function() { 
                return 'function(data, type, row) {return data + " (" + row.MWD +")";}';}]

            ],  

    ];
}
```

-->
### System details
- OS X 10.11
- PHP Version 5.6
- Laravel Version 5.3
- Laravel-Datatables Version 6.0

**Comment by yajra** [comment]
@TomAudre I think you should use render directly like:

```php
protected function getColumns()
    {
        return [
            [
                'title' => 'Direction (MWD)',          
                'render' => 'function(data, type, row) {return data + " (" + row.MWD +")";}'
            ],  
    ];
```

**Comment by TomAudre** [comment]
Hi @yajra - thanks for the suggestion.  I tested it and the datatable rendering stalls at "processing" and I get an error:
(index):104 Uncaught TypeError: Cannot read property 'MWD' of undefined

**Comment by yajra** [comment]
Sorry for late response, the issue is on client side and is not in the scope of the project. However, maybe try console logging your row first and make sure the MWD property does indeed exists in the row object. Thanks!
