### ISSUE TITLE
custom fields in json response

### ISSUE THREAD

**Issue by dabonzo** [yajra/laravel-datatables#785]
Hi Yajra,

How can I send additional data with the json-response. I have a small blood-pressure app (bp.aria-network.com) and I need the average for the columns with sys,dys and puls. I figured it out with javascript but I don't get all the data in one ajax request. If i use pagination i get the average only for the page, if I use scroller I get 78 out of 100, but not the average of all records. So I decided to get the average and some other calculations serverside. I tried to hack your classes but I figured out I won't be able to recreate this should there be an update. Any possibilities to add custom fields, like your draw, recordsfiltered and recordsTotal, to the response. If not,where is it best to start hack your classes

**Comment by yajra** [comment]
Hi @dabonzo,

We have a `->with('key', 'value')` api that you can use to attach additional data in the response. I think I don't have a demo of it yet but the are similar issues here the you can use as ref.

A quick ref: https://github.com/yajra/laravel-datatables/issues/277

**Comment by dabonzo** [comment]
Thank you @yajra, this is exactly what I asked for. Great package btw. and every day I find something very usefull

**Comment by mariani10** [comment]
How i use the variables that i send to the view? i want a tfoot with all sums and counts

**Comment by kylesean** [comment]
@mariani10 Did you solve it? the problem same to me.

**Comment by baskinvolkan** [comment]
`var api = this.api() ;`
`var customKeyName = api.ajax.json().customKeyName;`
