### ISSUE TITLE
Column name conflict

### ISSUE THREAD

**Issue by Juzepe** [yajra/laravel-datatables#791]
I have 2 tables companies and addresses. Both of them have column "name". I use alias "address" for "addresses.name". When I try search, It returns empty result.

My select:

```sql
select(['companies.id', 'companies.name', 'addresses.name as address', 'companies.created_at', 'companies.updated_at'])
```

My javascript:

```js
processing: true,
        serverSide: true,
        ajax: '{!! url('allcompanies') !!}',
        columns: [
            { data: 'name', name: 'companies.name' },
            { data: 'address', name: 'addresses.name' },
            { data: 'created_at', name: 'companies.created_at' },
            { data: 'updated_at', name: 'companies.updated_at' },
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ]
```

- Operating System Ubuntu 14.04.5 LTS
- PHP Version 7.0.11
- Laravel Version 5.3
- Laravel-Datatables Version 6.18

**Comment by yajra** [comment]
Your code looks fine. I suggest you inspect the ajax request and check the generated queries to get a better hint on what's causing the issue. Note: you should enable APP_DEBUG to be able to see the queries.

**Comment by Juzepe** [comment]
I already found mistake. I was using query builder and `->get()` same time. I deleted `->get()` and it works now.

Thank for answer.

**Comment by afoysal** [comment]
Thanks @yajra . How to inspect the ajax request and check the generated queries ?
