### ISSUE TITLE
Live Update

### ISSUE THREAD

**Issue by nimeshc64** [yajra/laravel-datatables#792]
How to live update data Table without refreshing

**Comment by yajra** [comment]
I think you need to dig deeper on dataTables.js to be able to do this. Check the [api docs](http://datatables.net/). Try asking on their forum since I think this is more on js issue and not php. Thanks!

**Comment by ChaosPower** [comment]
@nimeshc64 Live updates is doable via angular-datatables. https://l-lin.github.io/angular-datatables/

Set `processing: false` or just don't include in the options
