### ISSUE TITLE
Looking for a responsive footer

### ISSUE THREAD

**Issue by reficul** [yajra/laravel-datatables#793]
### Summary of problem

Hello, I use the footercallback to add a row with some operations on the columns, it's not a simply sum.

![schermata 2016-10-17 alle 12 08 29](https://cloud.githubusercontent.com/assets/1073883/19433821/991d37b0-9462-11e6-9b9f-90f523bc4c11.png)

It's works but when it display with a low resolution all rows show the "+" icon and I can expand them. But for the footer row no "+" show and then some column are hidden.
### Code snippet

``` php
  'footerCallback': function ( row, data, start, end, display ) {
                                var api = this.api(), data;

```

And here I update the footer:

``` php
// Update footer
                                $( api.column( 0 ).footer() ).html('TOTALI');
                                $( api.column( 1 ).footer() ).html(total);
                                $( api.column( 2 ).footer() ).html('€ ' + totalval.toFixed(2));
                                $( api.column( 3 ).footer() ).html('€ ' + totalvar.toFixed(2));
                                $( api.column( 4 ).footer() ).html(totalore + 'h' + ' ' + totalmin + 'm');
                                $( api.column( 5 ).footer() ).html('€ ' + totalfissi.toFixed(2));
                                $( api.column( 6 ).footer() ).html('€ ' + totalris.toFixed(2));
                                $( api.column( 7 ).footer() ).html('€ ' + (totalris / (totalore + (totalmin/100))).toFixed(2));
                                $( api.column( 8 ).footer() ).html((totalris / totalval * 100).toFixed(2) + " %");
                            }
                        });
                        table.column('0:visible').order('desc').draw();
                    });

```

How can I add the responsive feature also on the footer? or how I can resolve this problem?

Thanks in advance.
- PHP Version: 5.6
- Laravel Version: 5.2

**Comment by yajra** [comment]
Have you tried the responsive extension of DataTables? Maybe try asking on the the DataTables.js forum since this is a bit out of scope of the package. Thanks!

**Comment by yajra** [comment]
Try asking on the main js package forum for responsive extensions. Thanks!
