### ISSUE TITLE
morphToMany Eloquent Relations

### ISSUE THREAD

**Issue by Juzepe** [yajra/laravel-datatables#795]
Hi Yajra!

I have searched but I could not found anything about this topic. I done like this [](https://datatables.yajrabox.com/relation/has-many). It works and returns result, but when I try search it returns error:

`SQLSTATE[HY093]: Invalid parameter number`

Can you help me or give me some advice?
- Operating System Ubuntu 14.04.5 LTS
- PHP Version 7.0.11
- Laravel Version 5.3
- Laravel-Datatables Version 6.18

**Comment by yajra** [comment]
@Juzepe I think searching/ordering on morph** relations is not yet supported by the package. ATM, below are the list of supported relations (verified by creating a demo):
* BelongsTo
* BelongsToMany
* HasMany
* HasOne

**Comment by yajra** [comment]
Issue should be fixed on latest version. See this [demo](https://datatables.yajrabox.com/relation/morph-to-many) for ref. Thanks!
