### ISSUE TITLE
Set Total Records method is not working

### ISSUE THREAD

**Issue by mikhi** [yajra/laravel-datatables#801]
hi Yajra, i integrate with success your wonderfull package in my project. I have a little issue, regarding the setTotalRecords() method. In my case, the mthod is not working.
### Code snippet of problem

 $users = User::select(['id', 'name', 'email', 'created_at', 'updated_at'])->get();        

```
    return Datatables::of($users)
        ->setTotalRecords(3)
        ->make(true);
```

The setTotalRecords is not setting the totalRecords value.

### System details

- Operating System: Ubuntu 14.
- PHP Version: 5.5.9
- Laravel Version: 5.2
- Laravel-Datatables Version: ~6.0

Can u please help me to solve this issue?

Thanks,
Mihai

**Comment by yajra** [comment]
@mikhi I suggest you try removing `->get()` on your query and thus you will not need the setTotalRecords.
```php
$users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);

return Datatables::of($users)
        ->make(true);
```

**Comment by yajra** [comment]
Closing old issue. Please open a new one if needed. Thanks!
