### ISSUE TITLE
Datatable is not working on search case

### ISSUE THREAD

**Issue by webassic15** [yajra/laravel-datatables#802]
Whenever i reload page then it's working fine but when i search then i am getting a result & pass to collection class, that result is passing to Datatable::of method.. but it's responding as null

$response = $this->apiResource->getQueryStringData('users-list', $request->get('params'));
        $data = new Collection($response['records']);
        return Datatables::of($data)
                        ->setTotalRecords($response['total_count'])
                        ->skipPaging()
                        ->removeColumn('password')
                        ->make(true);

On ajax response as below : 

{draw: 7, **recordsTotal: 2**, **recordsFiltered: 0**, data: [], input: {draw: "7",…}}
data:[]
draw:7
input:{draw: "7",…}
recordsFiltered:0
recordsTotal:2

**Comment by yajra** [comment]
@webassic15 can you try returning `$response` to see if it does have a data? The code looks fine to me. Thanks!

**Comment by ChaosPower** [comment]
@webassic15 can you paste `dd($response);` and `dd($data);` here? I would like to replicate your issue.

**Comment by webassic15** [comment]
$data variable getting a data but it's not showing a row on table.
On page loading getting a record & displaying correctly but after search it's not showing a values.

**Comment by yajra** [comment]
Have you tried inspecting the ajax request? Any error appears on the console?
