### ISSUE TITLE
Null hasOne relationships

### ISSUE THREAD

**Issue by gsc89** [yajra/laravel-datatables#803]
I have a job table which has the following columns which are nullable:
- customer_id
- rig_id
- well_id

I have done the columns like this for them to display without the popup error about null values:

```
        'customer' => ['name' => 'customer.name', 'data' => 'customer.name', 'defaultContent' => ' ', 'searchable' => false],
```

I have set them not to be searchable because as some columns are nullable it means if a null value is used in the column it will throw an error on searching to say that the value doesn't exist, is there any way to account for this?

**Comment by yajra** [comment]
Since you know that this column will be null, you add a column like below:

```php
->addColumn('customer_name', function($m){
    return $m->customer? $m->customer->name : '';
})
```

Then use customer_name as your data to display.

**Comment by petarvasilev91** [comment]
Is it possible to make that searchable?

**Comment by Juzepe** [comment]
@yajra help us :)

**Comment by yajra** [comment]
For latest version of Laravel, you can use `withDefault()` on your relationship to handle nulls. To make it searchable, use `editColumn`. addColumn disables sort & search for that field.

**Comment by RayhanYulanda** [comment]
> For latest version of Laravel, you can use `withDefault()` on your relationship to handle nulls. To make it searchable, use `editColumn`. addColumn disables sort & search for that field.

I've triend using withDefault but got an error `"Call to undefined method Illuminate\\Database\\Eloquent\\Builder::withDefault()",`
Is it available for laravel 7?
