### ISSUE TITLE
Subquery needed. How to do COMPLEX query?

### ISSUE THREAD

**Issue by xxRockOnxx** [yajra/laravel-datatables#805]
my query is something like

```
select 
    table.Acol1, 
    tableB.col2 as tableC.foo, 
    col3 as bar, sum(tableD.quantity) as total 
from tableA

left join tableB.....
left join tableC....
left join tableD...

where clause produced by datatables
```

I need the `total` which is an alias from `sum` to be searchable also.

 I can do ordering/sorting and column search but on the global search I'm having an error about the where clause which is obviously because of the query... We can't do `where` on an alias.

I'm planning to do `subquery` but things just get more complex that I think I need to make my own `datatables` package which I'm avoiding just for this one part.

How can fix this?

**Comment by yajra** [comment]
First, I advise you to inspect the ajax response to get a hint on what was causing the error. Most probably it was due to the sum sql. You can then override the default searching using `filterColumn` api.

**Comment by yajra** [comment]
BTW, you can see the queries generated by the package by setting APP_DEBU=true. I also suggest you run the SQL generated manually on your SQL tools. As long a the query is valid, it should work with the package too.

**Comment by ChaosPower** [comment]
@xxRockOnxx it would be faster to do complex queries via compiled procedures or views. It will be really slow if doing it via PHP.

**Comment by xxRockOnxx** [comment]
I have never tried those but I think it'll be worth it to know such stuffs considering "It is slow" like what you said, and people who I trust on freenode said it is actually invalid.

I tend to avoid more complexity and just use what's already there so... ¯\_(ツ)_/¯
