### ISSUE TITLE
Export Buttons not working on a non-service implementation

### ISSUE THREAD

**Issue by sabival89** [yajra/laravel-datatables#808]
Hello,

I have tried the [Service Implementation](https://datatables.yajrabox.com/services/basic), and it works pretty well on exporting table contents. But whenever i try using non service implementations, the export buttons don't work. It keeps redirecting to a JSON result page. please see output below..

![print-pdf-csv-excel-output](https://cloud.githubusercontent.com/assets/2057169/19625901/0c7291f6-991d-11e6-8dd0-a6ac248a94e0.PNG)

Kindly assist me please cuz i'm pretty stuck.

## My Controller**
![controller](https://cloud.githubusercontent.com/assets/2057169/19625120/563a09b0-9907-11e6-9f06-d875f3c46718.PNG)

## My Script Declaration**
![script](https://cloud.githubusercontent.com/assets/2057169/19625124/77f22b64-9907-11e6-8a80-46c03d75d1e5.PNG)

## My View

![table](https://cloud.githubusercontent.com/assets/2057169/19625142/67bad466-9908-11e6-915d-1fb92978d87e.PNG)

## The Output when ever i click on any of the export buttons: Print, CSV, PDF, EXCEL
![print-pdf-csv-excel-output](https://cloud.githubusercontent.com/assets/2057169/19625901/0c7291f6-991d-11e6-8dd0-a6ac248a94e0.PNG)

**Comment by yajra** [comment]
@sabival89 sorry, but server side buttons are only supported via service class implementation. You have to manually create your own handler when using the standard way.

**Comment by turgutsaricam** [comment]
You can create a base service class. Here is my implementation.

```php
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Query\Builder;
use Yajra\Datatables\Datatables;
use Yajra\Datatables\Engines\BaseEngine;
use Yajra\Datatables\Services\DataTable;

class DataTableBase extends DataTable {

    /*
     * The reason why this class exists is that Yajra/Datatables requires this service class for export methods to work
     * properly.
     */

    /** @var Builder The query that will be used to get the data from the db. */
    private $mQuery;

    /** @var array An array of columns */
    private $mColumns;

    /** @var BaseEngine The DataTable */
    private $mDataTable;

    /**
     * @param            $query
     * @param BaseEngine $dataTable
     * @param array      $columns
     */
    public function __construct($query, BaseEngine $dataTable, $columns) {
        parent::__construct(app(Datatables::class), app(Factory::class));

        $this->mQuery = $query;
        $this->mColumns = $columns;
        $this->mDataTable = $dataTable;
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax() {
        return $this->mDataTable->make(true);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query() {
        $this->mQuery;
    }

    public function html() {
        return $this->builder()->columns($this->mColumns);
    }
    
}
```

Then, you can use the datatable you created without a service like this:

```php
$base = new DataTableBase($query, $dataTable, $columns);
return $base->render(null);
```

Just do not call `make` method for your datatable instance and let the `$base` handle it. So, your `userdata` method may look like this:

```php
public function userdata() {
    $query = User::latest('created_at');
    $dataTable = Datatables::of($query); // Do not call make here
    $columns = ['firstname', 'lastname', 'email', 'action'];

    $base = new DataTableBase($query, $dataTable, $columns);
    return $base->render(null);
}
```

**Comment by sabival89** [comment]
@yajra Thanks. I appreciate your response.

**Comment by sabival89** [comment]
@turgutsaricam I'm gonna give this a try and get back to you. Thanks bro.

**Comment by sabival89** [comment]
@turgutsaricam Nice work bro. ): It worked seamlessly... Like magic. I am really glad you helped. Thanks to you all. Cheers!!

**Comment by vipin733** [comment]
i followed this tutorial but I;m getting errors "GET http://gramyanchal.dev/print/unpaid/test1?draw=1&columns%5B0%5D%5Bdata%5D=i…ngth=10&search%5Bvalue%5D=&search%5Bregex%5D=false&course=&_=1486189545120 500 (Internal Server Error)"

`
 public function ajaxindexing(Request $request)
   {

     $courses = $request->course;
     if ($courses) {
        $students = Student::with('courses')->where('course_id',$courses)->get();
     }else {
      $students = Student::with('courses')->get();
     }
    
        $dataTable = Datatables::of($students);
        ->addColumn('action', function ($student) {
                   return '<a href="/student/'.$student->reg_no.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> View Profile</a>';
                 });
         $columns = ['student_name', 'reg_no', 'courses.name', 'father_name','mother_name','action'];
        $base = new DataTableBase($students, $dataTable, $columns);
        return $base->render(null);
   }

`

**Comment by sabival89** [comment]
Hello @vipin733 !

The chaining portion below needs to be added in your DataTableBase Class
``` php
->addColumn('action', function ($student) {
        return '<a href="/student/'.$student->reg_no.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> View Profile</a>';
      });
```
**DataTableBase class** you should have something like this
``` php
public function ajax() {
   return $this->mDataTable
    ->addColumn('action', function ($student) {
        return '<a href="/student/'.$student->reg_no.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> View Profile</a>';
      }); 
...
```

**Comment by turgutsaricam** [comment]
@sabival89 Adding the column from inside the base class or not does not matter, since it is the same instance you are using.

@vipin733 You probably have something else going wrong. You can check your debug file to find the cause of the problem. The base class is just a wrapper.

**Comment by vipin733** [comment]
@turgutsaricam thanks for this tutorial  and reply. but i solved that (its internal server problem)

**Comment by hardiktailored** [comment]
@turgutsaricam I'm using your solution and everything working fine except Print button behaviour. When I click on Print button, it opens datatable as HTML on same page instead of on new page where also Print pop-up should open. But in my case it doesn't. Do you have any idea? How can I fix this so it work like normal Print functionality of datatables where a new page opens and closes automatically after finish printing or on click of cancel button?

**Comment by hardiktailored** [comment]
@yajra As a temporary solution I am using below script to print and redirect back to previous URL with searched text in `print.blade.php` and using the search text in `"oSearch": {"sSearch": "{{ $search_text }}"}` to filter records again on the main page.
```
<script type="text/javascript">
    function getParameterByName(name) {
        var match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
        return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
    }

    window.print();
    var url = new URL(window.location.href);
    var c = getParameterByName("search%5Bvalue%5D");
    window.location.href = document.referrer + '?search=' + c;
</script>
```

**Comment by linaspasv** [comment]
I have created a wrapper for an easy data exporting, when used in a non-service implementation.

## **Here is how it looks on the back-end:**
**Implementation:**
```php
use Illuminate\Contracts\View\Factory;

use Yajra\Datatables\Datatables;
use Yajra\Datatables\Services\DataTable;

use Exception;

class DataTableExport extends DataTable
{
    /**
     * @var \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    private $source = null;

    /**
     *
     * @var array
     */
    private $exports = ['excel', 'pdf', 'csv'];

    /**
     * constructor
     *
     * @param \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection $source
     */
    public function __construct($source)
    {
        parent::__construct(
            app(Datatables::class),
            app(Factory::class)
        );

        $this->source = $source;
    }

    /**
     * @return Datatables
     */
    protected function dataTable()
    {
        return $this->datatables->of($this->query());
    }

    /**
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query()
    {
        return $this->source;
    }

    /**
     * @param \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection $source
     * @return \static
     */
    public static function of($source)
    {
        return new static($source);
    }

    /**
     * set columns to export
     *
     * @param type $columns
     * @return $this
     */
    public function columns($columns)
    {
        $this->builder()->columns($columns);

        return $this;
    }

    /**
     * export action
     *
     * @param string $action
     * @param string|null $filename
     * @return void
     * @throws Exception
     */
    public function export($action = 'excel', $filename = null)
    {
        if (! in_array($action, $this->exports)) {
            throw new Exception(sprintf('Export action of "%s" is not supported.', $action));
        }

        $this->setFilename($filename);

        return call_user_func([$this, $action]);
    }
}
```

**Usage example:**
```php
$model = App\User::with('group');
$columnsToExport = [
    'group.title',
    'email',
    'first_name',
    'last_name',
    'company_name'
];

return DataTableExport::of($model)
    ->columns($columnsToExport)
    ->export('excel');
```

## **Here is an example on how it looks on the front-end:**


**JavaScript snippet:**
```js
// dtCustomers is a datatables object
$('button[name="export"]').on('click', (evt) => {
    let url = $(evt.target).data('action');
    let params = dtCustomers.ajax.params();

    window.location = url + '?' + $.param(params);
});
```

**HTML snippet:**
```html
<button name="export" type="button" data-action="{{ route('admin.customers.excel.export') }}"  class="btn btn-md btn-danger"><i class="fa fa-fw fa-download"></i> Export</button>
```

**Also make sure to register a route, where export call is going to happen:**
```php
Route::get('export')->uses('CustomerController@exportToExcel')->name('admin.customers.excel.export');
```


@yajra I was wondering would it be possible to have an export funcionality in a separate (lightweight) package. This would allow an easy solution for people like me that have a more complex use cases, where custom non-service implementation is a must. While current implementation works but it feels really heavy, even so only third of a package is being used in my case. My suggestion would be to have a ``laravel-datatables-export`` package, and it could be re-used in your newest ``laravel-datatables-buttons`` package.

I do hope this will be helpful for people.

**Comment by yajra** [comment]
@linaspasv `laravel-datatables-export` is a good suggestion. Will create the plugin when I got the chance to test all codes suggested. Thanks a lot!

**Comment by hardiktailored** [comment]
How can I use custom title for columns to use as header in exports and printing using @turgutsaricam 's method? Currently it uses same name from column array. But I want different header name than table column. See below controller method:

    public function companiesAjax()
    {
        $query = Company::where("status","1");
        $dataTable = Datatables::of($query); // Do not call make here
        $columns = ['company_title', 'company_abbreviation', 'city', 'phone_number', 'email'];

        $base = new DataTableBase($query, $dataTable, $columns);
        return $base->render(null);
    }

In the above example, "company_title" column prints as "Company Title" but I want to print that column with "Company/Organization" and same for other columns.

**Comment by ebardier** [comment]
Hi, I have used the solution of @linaspasv, but I have an error in the constructor of class "DataTableExport" .. anyone who has happened to it? Any suggestions? thank you very much

The error: "Cannot call constructor"

Datatables: 8.0
Laravel: 5.5

**Comment by linaspasv** [comment]
@ebardier I guess it's related to [the following change](https://github.com/yajra/laravel-datatables-buttons/commit/07a6c4fbb4ce5acf2360ed9c4715f9943e93f01a#diff-d3d45086719f15dd1bef60db9ee40ef7)

because of this, the following part is no valid anymore:

```php
        parent::__construct(
            app(Datatables::class),
            app(Factory::class)
        );
```

**Comment by indowebdeveloper** [comment]
Hello.. I'm trying to use @linaspasv solution, 
but it throws me Call to a member function getRequest() on null on DataTable.php line 272
i'm using laravel 5.4

**Comment by deanlaw** [comment]
@linaspasv where should we be placing the DataTableExport class file in our app structure? Also, should it have a namespace as well?

**Comment by linaspasv** [comment]
@deanlaw you could have app/Services directory to keep all these re-usable classes. Personally, I do have app/Foundation where I store all of my universal classes and re-use these across different projects.

Something like so:
![image](https://user-images.githubusercontent.com/1407067/34407701-8604be96-ebc8-11e7-8060-5172b831a8f7.png)

There are no rules for this. It's what and how best works for you! I hope it helps. :-)

**Comment by deanlaw** [comment]
@linaspasv Thank, Linas, I appreciate the clarification.

**Comment by yupangestu** [comment]
hi, I am currently on @turgutsaricam method and i find one thing that if you add integer in the data it returns as string and i cannot sum it using excel, any solution to this?

**Comment by oranges13** [comment]
@turgutsaricam 's solution worked a treat, however I had to remove the typechecking of `BaseEngine` in the `__construct` function for it to work without error.

**Comment by yupangestu** [comment]
> @turgutsaricam 's solution worked a treat, however I had to remove the typechecking of `BaseEngine` in the `__construct` function for it to work without error.

Can you tell me how to do it? I think i have this issue currently

**Comment by oranges13** [comment]
> > @turgutsaricam 's solution worked a treat, however I had to remove the typechecking of `BaseEngine` in the `__construct` function for it to work without error.
> 
> Can you tell me how to do it? I think i have this issue currently

In the `__construct` function, remove the type `BaseEngine`

Change `public function __construct($query, BaseEngine $dataTable, $columns) {` to `public function __construct($query, $dataTable, $columns) {`

**Comment by yupangestu** [comment]
> > > @turgutsaricam 's solution worked a treat, however I had to remove the typechecking of `BaseEngine` in the `__construct` function for it to work without error.
> > 
> > 
> > Can you tell me how to do it? I think i have this issue currently
> 
> In the `__construct` function, remove the type `BaseEngine`
> 
> Change `public function __construct($query, BaseEngine $dataTable, $columns) {` to `public function __construct($query, $dataTable, $columns) {`

![Untitled](https://user-images.githubusercontent.com/13581978/54748283-c548b480-4c03-11e9-8acf-8d5efd1f1a78.png)

I got this error though, can you help me?

```php
<?php
namespace Thanatos\Providers;

use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Query\Builder;
use Yajra\DataTables\DataTables as Datatables;
use Yajra\DataTables\Engines\BaseEngine;
use Yajra\DataTables\Services\DataTable;

class DataTableExport extends DataTable {

    /*
     * The reason why this class exists is that Yajra/Datatables requires this service class for export methods to work
     * properly.
     */

    /** @var Builder The query that will be used to get the data from the db. */
    private $mQuery;

    /** @var array An array of columns */
    private $mColumns;

    /** @var BaseEngine The DataTable */
    private $mDataTable;

    protected $datatables;

    /**
     * @param            $query
     * @param BaseEngine $dataTable
     * @param array      $columns
     */
    public function __construct($query, $dataTable, $columns) {
        parent::__construct(app(Datatables::class), app(Factory::class));

        $this->mQuery = $query;
        $this->mColumns = $columns;
        $this->mDataTable = $dataTable;
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajax() {
        return $this->mDataTable->make(true);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
     */
    public function query() {
        return $this->mQuery;
    }

    public function html() {
        return $this->builder()->columns($this->mColumns);
    }

}
```

**Comment by dani821** [comment]
@yupangestu it been one year maybe you solved this problem already but today I came across the same problem because yajra new version creating this error previous version not giving this error.

So you can easily remove this error by also removing the following line in the constructor
```  
parent::__construct(app(Datatables::class), app(Factory::class)) 

```
