### ISSUE TITLE
SUM column value from all data

### ISSUE THREAD

**Issue by donny26utama** [yajra/laravel-datatables#809]
how to sum column value from all data when using serverside?
because im was trying with footercallback datatables to sum all data still wrong,,
it just count current page.

here is the code:
// Total over all pages
            total = api
                .column( 4 )
                .data()
                .reduce( function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0 );

```
        // Total over this page
        pageTotal = api
            .column( 4, { page: 'current'} )
            .data()
            .reduce( function (a, b) {
                return intVal(a) + intVal(b);
            }, 0 );
```

im using total over all pages,, but the result same as im using total over this page.
can you help me?

**Comment by yajra** [comment]
You can use `->with('key', 'value')` api to append the computed total on the json response. You can then parse it by hooking on the draw callback of dataTables.

**Comment by ChaosPower** [comment]
@donny26utama can also be done via javascript

https://datatables.net/plug-ins/api/sum()

**Comment by medivh13** [comment]
I did this :
const Table = $('#foo').DataTable({
    . . . . . .,
    . . . . . .,
   drawCallback: function(){
            Table.columns(5, {
                page: 'current'
            }).every(function() {
                var sum = this
                .data()
                .reduce(function(a, b) {
                    var x = parseFloat(a) || 0;
                    var y = parseFloat(b) || 0;
                    return x + y;
                }, 0);
                // console.log(sum); alert(sum);
                $(this.footer()).html(sum);
            });
     }
});

in this case the column was column number 5
