### ISSUE TITLE
Fractal Transformer issue

### ISSUE THREAD

**Issue by cond0r** [yajra/laravel-datatables#81]
I'm trying to implement datatable into my app, and i want to use Fractal Transformer. But the issue is that is ignored.  Or how we have to deal with that ?

I looked on your demo app and i see same result / issue. 
For example here - http://datatables.yajrabox.com/eloquent/transformer you used fractal to transform the results, and you set the date to be be in this format return 'Y-m-d'; But that doesn't change. It's still in raw format 2015-05-06 13:48:25.

Also i have to change the columns names, but it doesn't work because it returns raw format, ignoring transformer class setTransformer.

**Comment by yajra** [comment]
thanks for reporting. should be fixed on v5.3.2
