### ISSUE TITLE
return vertically

### ISSUE THREAD

**Issue by donny26utama** [yajra/laravel-datatables#811]
i have query will result only 1 row which have 3 fields. when im using yajra-datatables it will show horizantal. and i want to show on table vertically, like this:

from: field1 field2 field 3 (using yajra)

to:
field1
field2
field3

can you help me?

**Comment by yajra** [comment]
Not sure if this is possible but I think you can open up this issue on main dataTables.js site/forum since this will require you a custom extension js script. Thanks!

**Comment by donny26utama** [comment]
ok. thanks for your answer.

**Comment by ChaosPower** [comment]
@donny26utama is this for matrix tables? you can just add your header as column data for 1st index. Can be done using php, but would recommend javascript solution.

You may want to use
https://datatables.net/extensions/fixedcolumns/
and
https://datatables.net/examples/basic_init/complex_header.html
