### ISSUE TITLE
Display Row Number After Sorting?

### ISSUE THREAD

**Issue by aldo235** [yajra/laravel-datatables#814]
Hello , can i get rank after sorting data ?

my code
`       DB::statement(DB::raw('set @rownum=0'));
        $datas = Scoreboard::where('competition_id','=',null)->where('level','=',$level)
         ->orderBy(DB::raw('scoreboards.score'))
        ->select(DB::raw('@rownum := 0 r'))
        ->select(DB::raw('@rownum := @rownum + 1 AS rank '),'scoreboards.*')
        ->groupBy('user_id')
        ->get();
       return Datatables::collection($datas)
            ->make(true);`
if im dd($datas ) its sorting but the rank its wrong

**Comment by yajra** [comment]
Maybe using index column? See this PR https://github.com/yajra/laravel-datatables/pull/597 for details.

```php
return $this->datatables
            ->collection($this->query())
            ->addIndexColumn()
            ->make(true);
```
