### ISSUE TITLE
Hi i want to add reordering with drag and drop in Data table Service 

### ISSUE THREAD

**Issue by adnanmayo** [yajra/laravel-datatables#816]
Hi @yajra i am trying to add draggable row reordering  with [this](https://editor.datatables.net/examples/extensions/rowReorder.html) is there a clue where should i start?

**Comment by yajra** [comment]
I haven't personally tried implementing rowReorder but this [PR](https://github.com/yajra/laravel-datatables/pull/693) should be a good start. Read the thread for details.

**Comment by yajra** [comment]
Closing old issue. Please open a new one if needed. Thanks!
