### ISSUE TITLE
Not able to show footer using html builder

### ISSUE THREAD

**Issue by Krittam** [yajra/laravel-datatables#817]
i am using html builder to populate a datatable
here is a part of the code in my controller

 $html = $htmlBuilder
            ->addColumn(['data' => 'name', 'title' => 'Name'])
            ->addColumn(['data' => 'phone', 'name' => 'phone', 'title' => 'Phone'])
            ->addColumn(['data' => 'dob', 'name' => 'dob', 'title' => 'Age'])
            ->addColumn(['data' => 'highest_education', 'name' => 'highest_education', 'title' => 'Education'])
            ->addColumn(['data' => 'languages', 'name' => 'languages.language', 'title' => 'Languages'])
            ->addColumn(['data' => 'min_salary_expectation', 'name' => 'min_salary_expectation', 'title' => 'Expected Salary'])
            ->addColumn(['data' => 'previous_experience', 'name' => 'previous_experience', 'title' => 'Past Experience'])
            ->addColumn(['data' => 'candidateprofile.has_aadhaar', 'name' => 'candidateprofile.has_aadhaar', 'title' => 'Has Aadhar'])
            ->addColumn(['data' => 'candidateprofile.stickability', 'name' => 'candidateprofile.stickability', 'title' => 'Stickability'])
            ->addColumn(['data' => 'tags', 'name' => 'tags.tag', 'title' => 'Status'])
            ->addColumn(['data' => 'last_active', 'name' => 'last_active', 'title' => 'Last Active'])
            ->parameters([
//                'bDestroy'=> true,
                'dom'          => 'Bfrtip',
//                'retrieve'      =>true,
                'select'       => 'select: {
                                    style: \'multi\'
                                   }',
                'buttons'      =>['copy'],
                'initComplete' => "function () {               
                             var table = this;
                             
                             $('#dummy').click(function(){
                            $('#sendPush').modal('show');
                             });
                             $('.dt-button').click(function(){
                            $('#sendSMS').modal('show');
                             });
                             
                            
                            this.api().columns().every(function () {                                                             
                                var column = this;
                                var input = document.createElement(\"input\");
                                $(input).appendTo($(column.footer()).empty())
                                .on('keyup change', function () {
                                    column.search($(this).val(), false, false, true).draw();
                                });
                            });
                        }",
            ]);

I am not able to show footer, instead i have to change the default boolean for this purpose in builder.php.

**Comment by yajra** [comment]
Make sure you set the 2nd param of table to true. See this [demo](https://datatables.yajrabox.com/services/users-with-footer) for ref.

```php
$dataTable->table([], true);
```

**Comment by Krittam** [comment]
i am not able to use the table function on the html builder  because of the following type errors.
1. table function returns string but i have to use many other functions such as addColumn which can be applied only on builder.
2. Also i cant use table function in the end because i have to use parameter functions which again returns string

**Comment by yajra** [comment]
Additional doc for ref: https://yajrabox.com/docs/laravel-datatables/6.0/html-builder-table
