### ISSUE TITLE
How to export excel with big data

### ISSUE THREAD

**Issue by canhkieu** [yajra/laravel-datatables#819]
I have a table with > 100.000 record. Display 100 records per page. I was added Excel button. But it just export current page with 100 records. Any way to export all data?

Because this is very big table, so I think we need a ajax function to request data step by step and then merge to download, right?

Please, help.

**Comment by yajra** [comment]
The package uses [laravel-excel](https://github.com/Maatwebsite/Laravel-Excel). You can override the excel() method and maybe try chunking the results.

**Comment by muhamed-didovic** [comment]
Hi @yajra, 
I managed with chunking to reduce time to build Excel or CSV, but PDF creation is really slow, do you have any advice how to speed it up?

**Comment by yajra** [comment]
@muhamed-didovic have you tried using `snappy` as the pdf generator? See this [doc](https://yajrabox.com/docs/laravel-datatables/6.0/general-settings) for ref. 

Maybe you can also try chunking the results on print template that snappy will use when generating the PDF?
