### ISSUE TITLE
Global search issue with Postgres and Ajax

### ISSUE THREAD

**Issue by axgmsk** [yajra/laravel-datatables#82]
Hi,

Just got the issue after recent update:
PostgreSQL, AJAX feed mode, large table, global search stop working with error 500.

SQLSTATE[42703]: Undefined column: 7 ERROR:  column &quot;shortname&quot; does not exist<br />
LINE 1: ... (LOWER(CAST(name as TEXT)) LIKE $1 or LOWER(CAST(shortName ...<br />

Table contains shortName field as well as other columns with capital letter inside.
Investigation led to
    private function compileGlobalSearch($query, $column, $keyword)
function.

Is this correct and expected behavior?

Thanks.

**Comment by yajra** [comment]
hi, 

try inspecting the ajax response in debug mode and check if the queries generated are correct? Are you using a join statements?

**Comment by yajra** [comment]
ooops, I missed the word issue after update... compileGlobalSearch is the correct behavior.

I am not using PostgreSQL, can you please assists in tracking the issue?

**Comment by axgmsk** [comment]
Hi Yajra,

I have investigated the issue more. Syntax is correct in general, but with one exception.
Postgres requires columns with uppercase to be specified in quotes. 
So this one doesn't work
select LOWER(CAST(shortName as TEXT)) from "organizational_units";
and that one works perfectly as it should
select LOWER(CAST("shortName" as TEXT)) from "organizational_units";

This it is required to check field name for capital letter containment and add quotes around.
Other option is to add quotes always as strict Postgres syntax states field name should be in doubled quotes " and value is in singe quotes '

Thanks!

**Comment by axgmsk** [comment]
Proposed fix made search works perfectly:
	if($this->databaseDriver() === 'pgsql') { $column = '"'.$column.'"'; }
BaseEngine.php, add after line 602.

**Comment by axgmsk** [comment]
Sorry, just noticed wrapColumn function. So upper one better to replace with

                case 'pgsql':
                    $column .= '"' . str_replace('"', '""', $key) . '"' . '.';
                    break;

inserted after line 639 in BaseEngine.php

**Comment by yajra** [comment]
@axgmsk , thanks for the assistance. Can you please create a pull request? I will not be able to test this as I don't have PostgeSQL. Thanks a lot!

**Comment by yajra** [comment]
PostgreSQL is built-in on homestead. I guess I would be able to check this. But it would be better if you could PR and test the proposed fixed on your machine as you know PostgreSQL better than me. :)

**Comment by yajra** [comment]
@axgmsk , I applied your proposed solution on wrap column. Thanks a lot for reporting and assistance. Should be fixed on v5.4.3

**Comment by axgmsk** [comment]
Great, thank you!

**Comment by hugofabricio** [comment]
Not works in related columns.
