### ISSUE TITLE
Customize action to excel button

### ISSUE THREAD

**Issue by erotundo** [yajra/laravel-datatables#822]
Hi.

I have a problem because i want to put customize property to excel button but after download the document the changes not appear. I don't know if the problem it's about my modification it's in client side

This is my code to add filters or style to cell into excel
```js
{
                    extend: 'excelHtml5',
                    customize: function(xlsx){
                        var sheet = xlsx.xl.worksheets['sheet1.xml'];
                        var lastCol = sheet.getElementsByTagName('col').length - 1;
                        var colRange = createCellPos( lastCol ) + '1';
                        //Has to be done this way to avoid creation of unwanted namespace atributes.
                        var afSerializer = new XMLSerializer();
                        var xmlString = afSerializer.serializeToString(sheet);
                        var parser = new DOMParser();
                        var xmlDoc = parser.parseFromString(xmlString,'text/xml');
                        var xlsxFilter = xmlDoc.createElementNS('http://schemas.openxmlformats.org/spreadsheetml/2006/main','autoFilter');
                        var filterAttr = xmlDoc.createAttribute('ref');
                        filterAttr.value = 'A1:' + colRange;
                        xlsxFilter.setAttributeNode(filterAttr);
                        sheet.getElementsByTagName('worksheet')[0].appendChild(xlsxFilter);

                    }
                }
```
- Windows 10
- PHP Version 7
- Laravel Version 5.2
- Laravel-Datatables Version 6.0

**Comment by yajra** [comment]
@erotundo are using the service class to export to excel? If yes, the package uses [Laravel-Excel](https://github.com/Maatwebsite/Laravel-Excel). You can extend the DataTable class and do the necessary stuffs using laravel-excel.

If you are exporting via js, then I suggest try asking the datatables.net forum. Thanks!

**Comment by erotundo** [comment]
Dear @yajra i'm using JS, i see the problem and it's i don't have the lastest version of JS in my system, this is the problem 

Thanks and sorry for the inconvenience 

ER
