### ISSUE TITLE
Problem display data when using soft delete.

### ISSUE THREAD

**Issue by maengkom** [yajra/laravel-datatables#824]
@yajra I am using softdeletes and all data display in a list using datatables, but I think there is something weird in result.

### Code snippet of problem

```
$result = User::withTrashed()->select('*');
return Datatables::of($result)->make(true);
```

### Result

Below is table user, check `id`, `code` and `deleted_at` columns for checking to the next screen capture.
![image](https://cloud.githubusercontent.com/assets/960467/20162165/bad9c2c6-a725-11e6-9665-fe76963dfd04.png)

Below snippet to display datatables on the page, nothing special here.
```
var table = $('#data-table').DataTable({
        order: [1, 'desc'],
        ajax: {
            url : '/employe/data',
           type: 'POST'
        },
        columns: [
            { data: 'id', name: 'id', class: "select-checkbox", width: '50px', orderable: false, searchable: false,
                render: function() { return '' }
            },
            { data: 'id', name: 'id', width: '30px', searchable: false, class: "text-center" },
            { data: 'code', name: 'ms_users.code' },
            { data: 'first_name', name: 'first_name', visible: false },
            { data: 'last_name', name: 'last_name', visible: false },
            { data: 'first_name', name: 'first_name', searchable: false },
            { data: 'jobtitle.name', name: 'jobtitle.name', defaultContent: '' },
            { data: 'role.name', name: 'role.name', defaultContent: '' },
            { data: 'deleted_at', name: 'deleted_at', width: '30px', class: 'text-center', searchable: false },
        ]
    });
```

This screen below when page load. `Active` field using softdelete, when deleted, it is displayed by cross red icon. Look at the pagination  and information. Only show 1 page, and 9 entries (9 records those are not deleted). It must be 35 entries and should have 4 pages.
![image](https://cloud.githubusercontent.com/assets/960467/20162086/36a9da2c-a725-11e6-9b9e-0e041572d4d1.png)

Below is inspection result. recordsFiltered must 35, not 9 (not deleted records only).
![image](https://cloud.githubusercontent.com/assets/960467/20162237/3aed59f0-a726-11e6-9d25-dea52763f306.png)

### System details

- Operating System : Mac
- PHP Version : 7.x
- Laravel Version : 5.1
- Laravel-Datatables Version : 6.17.1

**Comment by maengkom** [comment]
@yajra I saw code in QueryBuilderEngine class, probably because this code ? 

```
// check for select soft deleted records
if (! $this->withTrashed && $this->modelUseSoftDeletes()) {
    $myQuery->whereNull($myQuery->getModel()->getTable() . '.deleted_at');
}
```

should be add exclamation mark in `! $this->modelUseSoftDeletes()` ? or wrap `! ($this->withTrashed && $this->modelUseSoftDeletes())` ?

```
// check for select soft deleted records
if (! $this->withTrashed && ! $this->modelUseSoftDeletes()) {
    $myQuery->whereNull($myQuery->getModel()->getTable() . '.deleted_at');
}
```

**Comment by yajra** [comment]
You need to tell dataTables to use withTrashed too. See this [demo](https://datatables.yajrabox.com/eloquent/with-trashed) for ref.

```php
return Datatables::of(User::withTrashed())
                ->withTrashed()
                ->make(true);
```

**Comment by maengkom** [comment]
Oh ok, I miss that... Thank you.
