### ISSUE TITLE
Change page and search problem

### ISSUE THREAD

**Issue by aghict** [yajra/laravel-datatables#825]
Hello
I install laravel-datatables and now I works on page load but when I want to change page number or search I get this error:
http://i65.tinypic.com/15pkbgw.jpg

This is my controller code:

```php
    public function getJSONTransactionDataTables()
    {
        return Datatables::of(Transaction::where('user_id', Auth::user()->id))->make(true);
    }
````
And for route:
```php
Route::any('payment/datatables','PaymentController@getJSONTransactionDataTables');
```

I think I my problem is route.
How can I solve this problem.
- Windows 7
- PHP 7
- Laravel 5.3
- Laravel-Datatables 6.21

**Comment by yajra** [comment]
Try inspecting the ajax request using chrome dev tools / firebug to get a better hint of what was causing the issue.

**Comment by yajra** [comment]
Closing old issue. Please open a new one if needed. Thanks!
