### ISSUE TITLE
how to get all data in all pages

### ISSUE THREAD

**Issue by fakhryan** [yajra/laravel-datatables#828]
### Summary of problem or feature request
sir how to get all data in all pages

i know this code  'table.data();' just get in current pages
how to all pages?

### Code snippet of problem
var table = ("#table").Datatable();
console.log(table.data())

### System details

- Windows 10
- PHP Version 7
- Laravel  5.1
- Laravel-Datatables new, using services

**Comment by yajra** [comment]
@fakhryan that is the expected behavior since we are paginating the records to have a smaller footprint response. If you want to get all the data, you can alter the xhr request and set the `length=-1`. Setting length to `-1` will disable pagination, thus will fetch all records.
