### ISSUE TITLE
Using Filters with Where

### ISSUE THREAD

**Issue by pixelone** [yajra/laravel-datatables#83]
I think I found a weird issue. It might just be my code, but if I run the query directly it outputs correctly.  

I am using filters like shown in your demo app.  

My output looks something like this:

        $q = $this->model->select($data)->where('users.is_admin','!=',1);
        $datatables = \Datatables::of($q)->leftJoin('user_to_user_groups',
            'users.id', '=', 'user_to_user_groups.user_id')
            ->leftJoin(
                'user_groups', 'user_to_user_groups.group_id', '=', 'user_groups.id');

        $datatables->filter(function ($q) {
            if ($term = \Input::get('filter_by_search')) {
                $q->where('users.firstname', 'like', "%{$term}%");
                $q->Orwhere('users.lastname', 'like', "%{$term}%");
                $q->Orwhere('users.email', 'like', "%{$term}%");
            }
        });

The initial page load pulls correctly however when I go to search using the custom filter it brings up the admin user and it ignores the where " is_admin !=1"  .  I am lost because if I run the query in mysql that you have outputted in the json it works fine.

select `users`.`email`, `users`.`firstname`, `users`.`lastname`, `users`.`created_at`, `user_groups`.`name`, `users`.`id` as `action`, `users`.`status`, `users`.`id` from `users` left join `user_to_user_groups` on `users`.`id` = `user_to_user_groups`.`user_id` left join `user_groups` on `user_to_user_groups`.`group_id` = `user_groups`.`id` where `users`.`is_admin` != 1 and `users`.`firstname` like 'test' or `users`.`lastname` like 'test' or `users`.`email` like 'test' order by `firstname` asc limit 10 offset 0

^ This works and this is whats being shown in the Json output.  

Json Output looks like this

  "query": "select `users`.`email`, `users`.`firstname`, `users`.`lastname`, `users`.`created_at`,   `user_groups`.`name`, `users`.`id` as `action`, `users`.`status`, `users`.`id` from `users` left join `user_to_user_groups` on `users`.`id` = `user_to_user_groups`.`user_id` left join `user_groups` on `user_to_user_groups`.`group_id` = `user_groups`.`id` where `users`.`is_admin` != ? and `users`.`firstname` like ? or `users`.`lastname` like ? or `users`.`email` like ? order by `firstname` asc limit 10 offset 0",
"bindings": [
"1",
"%test%",
"%test%",
"%test%"
],
"time": 0.3

Any ideas on what I am doing wrong?

**Comment by yajra** [comment]
@pixelone, I just tested adding a where clause and all is working fine. On your example, the bindings shows 1 as first param which indicates that is process `'users.is_admin','!=',1`

**Comment by mifas** [comment]
Hey @pixelone  please check this page, I think you need to change the javascript columns options
