### ISSUE TITLE
Should the html builder be cached?

### ISSUE THREAD

**Issue by ElfSundae** [yajra/laravel-datatables#830]
For DataTables Service usage, each call to `Services\DataTable::builder` or `Services\DataTable::html` will return a new Html Builder instance. Should we cache this instance for further use?

---

The current source code in `Yajra\Datatables\Services\DataTable`:

```php
/**
 * Optional method if you want to use html builder.
 *
 * @return \Yajra\Datatables\Html\Builder
 */
public function html()
{
    return $this->builder();
}

/**
 * Get Datatables Html Builder instance.
 *
 * @return \Yajra\Datatables\Html\Builder
 */
public function builder()
{
    return $this->datatables->getHtmlBuilder();
}
```

And the `Datatables::getHtmlBuilder`:

```php
public function getHtmlBuilder()
{
    return app('Yajra\Datatables\Html\Builder');
}
```

---

Maybe the html builder could be cached using a variable, then each call to `html` will return the same instance.

```php
/**
 * Get Datatables Html Builder instance.
 *
 * @return \Yajra\Datatables\Html\Builder
 */
public function builder()
{
    if (is_null($this->builder)) {
        $this->builder = $this->datatables->getHtmlBuilder();
    }

    return $this->builder;
}
```

**Comment by yajra** [comment]
@ElfSundae this makes sense. Can you please submit a PR? Thanks!
