### ISSUE TITLE
[7.0] Split features across packages

### ISSUE THREAD

**Issue by spescina** [yajra/laravel-datatables#832]
This package does too much. I think that the export features should be kept outside (plugin?) in order to remove the maatwebsite/excel and the dompdf/dompdf dependency.

**Comment by yajra** [comment]
I think it's a great idea to split the export as another plugin and good candidate for v7 I guess. Will consider this for enhancements. Thanks for the suggestions!

**Comment by yajra** [comment]
@spescina I really find your suggestion interesting so I tried to implement it asap. Would you mind testing the [master](https://github.com/yajra/laravel-datatables/tree/master) branch if it works for you?

I split the export function into it's own [repo](https://github.com/yajra/laravel-datatables-buttons) too as suggested. Thanks a lot!

**Comment by spescina** [comment]
@yajra I'm speechless... Nice job man. I can't test it right now but your test suite should do the job. Hope to try it asap.
Tnx a lot.

**Comment by yajra** [comment]
Implemented on master/v7 branch. See example [buttons plugin](https://yajrabox.com/docs/laravel-datatables/master/buttons-installation) docs. 

Also planning to extract html builder on a separate package.  Thanks!

**Comment by rizqyhi** [comment]
Hi, is there any plan to implement this on `v6.*` ?
