### ISSUE TITLE
How to aplied searchDelay

### ISSUE THREAD

**Issue by ssheduardo** [yajra/laravel-datatables#839]
I use services with datatables, I need what the input search have a delay, how implement the delay in search via ajax?

Example in datatable
```
$('#example').DataTable( {
  searchDelay: 350
} );
```
How to applied in services?

**Comment by yajra** [comment]
What I used is [`fnFilterOnReturn`](https://datatables.net/plug-ins/api/fnFilterOnReturn) extension of DataTables. There is also a [`fnSetFilteringDelay`](https://datatables.net/forums/discussion/comment/68217/#Comment_68217) extension. Maybe try giving it a shot.

**Comment by yajra** [comment]
I think I misunderstood the question, just pass searchDelay in the parameters.

```php
$builder->parameters([
    "searchDelay" => 350,
]);
```

**Comment by ssheduardo** [comment]
Great, but i how to applied when use a services?

**Comment by adantart** [comment]
How can I do it **without** the builder ?

**Comment by yajra** [comment]
@adantart on js

```js
$('#dt').DataTable({
  ...
  searchDelay: 500
})
```
