### ISSUE TITLE
Edit on demo not working

### ISSUE THREAD

**Issue by scottpd** [yajra/laravel-datatables#84]
Hi 
On your demo site (http://datatables.yajrabox.com/) selecting for example "EloquentController.php - Add|Edit|Remove Column" and clicking the "Edit" icon under "Action" has no effect.

**Comment by yajra** [comment]
@scottpd , yes I did not put an effect on the edit button. I just displayed it to show that adding a button is possible. But maybe I would add some interactions there when I have time. Thanks for reporting.
