### ISSUE TITLE
Service implementation: repeating query for each request

### ISSUE THREAD

**Issue by aghayeff** [yajra/laravel-datatables#840]
I use service implementation method and load user's payment. It works perfect. Except this one, I want to get user's full name and display it before dataTable as a title. My controller code:

```php
    public function getPayments(UserPaymentsDataTable $dataTable, $id)
    {
            $user = Student::findOrFail($id);
            $title = $user->first_name.' '.$user->last_name;

        return $dataTable->studentId($id)->render('payments', ['title' => $title]);
    }
```

My view:

Payments of {{$title}}

    {!! $dataTable->table() !!}

This code works fine. So, if I check the debugbar, I see the query for Student is run each time: before rendering, after rendering. I don't need to run this query when datatable is rendered. I guess, we can write 2 different controllers, like basic method on your example.

```php
    public function index($id)
    {
            $user = Student::findOrFail($id);
            $title = $user->first_name.' '.$user->last_name;

        return view('payments', ['title' => $title]);
    }
```

```php
    public function getPayments(UserPaymentsDataTable $dataTable, $id)
    {
        return $dataTable->studentId($id)->render('payments');
    }
```

But, with service implementation, using 2 controllers for each request doesn't work. I would appreciate if you find any solution.

**Comment by yajra** [comment]
Whoops overlooked this one. If I get this right, queries are also executed when displaying the view, no?

Will validate and seems like a possible optimization is needed in the package. Thanks!

**Comment by yajra** [comment]
Sorry for late response. I think you can optimize this by checking if the request is ajax:

```php
public function getPayments(UserPaymentsDataTable $dataTable, $id)
    {
        if (! request()->ajax()) {
            $user = Student::findOrFail($id);
            $title = $user->first_name.' '.$user->last_name;
        }

        return $dataTable->studentId($id)->render('payments', ['title' => $title]);
    }
```
