### ISSUE TITLE
How to filter query using services?

### ISSUE THREAD

**Issue by ssheduardo** [yajra/laravel-datatables#842]
### How to filter query using services?

I using services and work fine but i need filter query for show in the datatable
Ex of url.
```
http://demo.com/provider/[name]
```
So need set [name] for create a filter in the query
```php
public function query()
{
    $query = Provider::select('id', 'name')->where('slug', [name]);
    return $this->applyScopes($query);
}
```
how to inject the parameter **[name]** ?

### System details

- Ubuntu 14.04
- PHP 5.6
- Laravel 5.3
- Laravel-Datatables 6.0

**Comment by ssheduardo** [comment]
Great,
The solution here: https://github.com/yajra/laravel-datatables/issues/697

One question, why not add as example in service please?.

**Comment by yajra** [comment]
Thanks, will try to add this on documentation.
