### ISSUE TITLE
How can i count all Sums and add it as footer?

### ISSUE THREAD

**Issue by rocket-enterprise** [yajra/laravel-datatables#843]
I still know that i am able with ->with('key' => 'value') to add a parameter to my grid, but how can i add a global sum? 

```php

  $invoices = Invoice::join('countries', 'countries.id', '=', 'invoices.country_id')
        ->select('invoices.id',
            'invoices.invoice_number',
            'invoices.invoice_date',
            'invoices.invoice_date as invoice_month',
            'invoices.user_id',
            'invoices.name',
            'invoices.shipping_type_id',
            'invoices.paytype_id',
            'countries.title as country_id',
            'countries.eu',
            'countries.shortcut as short',
            'invoices.shipping',
            'invoices.bonus',
            'invoices.group_bonus',
            'invoices.tax',
            'invoices.bonus_deduction',
            'invoices.sum'
        );

        $datatables = app('datatables')->of($invoices);

        if ($name = $datatables->request->get('title')) {
            $datatables->where('invoices.name','LIKE',$name."%");
        }
        .....

        return $datatables->make(true);
```

But how can i know add the sum of all invoices (SUM(invoices.sum) including all my filters? )like filter for a name or a date?)

### System details

WIndows Server 2012 R2 / SQL Server 2014
PhP 7.x
Laravel 5.1 LTS
Laravel Datatables 6.0

**Comment by yajra** [comment]
You can use the `with` api. See this [docs](https://yajrabox.com/docs/laravel-datatables/6.0/response-with) for details.

**Comment by yajra** [comment]
To add a global sum, just execute a basic sum sql on your query along with `with` api.

```php
return $datatables->with('invoice_sum', $invoices->sum('amount'))->make(true);
```

**Comment by mraghayev** [comment]
How we can use ->with to send variable to grid on service implementation?

**Comment by yajra** [comment]
@aghayeff same using `with` api. Just append it inside the `ajax()` method. Thanks!
