### ISSUE TITLE
Call to undefined method yajra\Datatables\Facades\Datatables::of()

### ISSUE THREAD

**Issue by EwanValentine** [yajra/laravel-datatables#85]
I'm getting the following error

```
FatalErrorException in Facade.php line 207:
Call to undefined method yajra\Datatables\Facades\Datatables::of()
```

From the following code:

```
 public function dataTables($site)
    {
        $submissions = Auth::user()->sites()->find($site)->submissions();        

        return Datatables::of($submissions)->make(true);
    }

```

**Comment by omar-faruk-sust** [comment]
is your $submissions is getting the result? 
you have to follow his convention. 
(
$users = User::select(['id','name','email','created_at','updated_at']);
 return Datatables::of($users)->make();
)

http://datatables.yajrabox.com/eloquent/basic this is his deep app for this package. you can look over it.

**Comment by yajra** [comment]
@EwanValentine , my mistakes of the Facade. Please use `yajra\Datatables\Datables` instead. Thanks!

**Comment by EwanValentine** [comment]
Okay great thanks!

**Comment by arunmadathil** [comment]
of is only working with get()
