### ISSUE TITLE
Order by foreign column that is null returns id=null for base table

### ISSUE THREAD

**Issue by tad3j** [yajra/laravel-datatables#855]
### Summary of problem or feature request

When ordering table via a foreign column that is null (ManyToOne relation), the id returned for base table is null (but only for columns that don't that relation/are null). I've tested that on multiple foreign keys and the same happens, but works OK if column is not null.

In bellow example, when I want to order by business.name the ordering works OK, but the listing id returned for rows that has business_id set to null is also null, although id exists in listings DB table. If I get that same row in tinker I'see the id is there, so it seems like the model works as expected.

Is this a known problem?

### Code snippet of problem
Migration code for Listing:
```php
    $table->increments('id');
    $table->integer('business_id')->unique()->unsigned()->nullable()->default(NULL);
    $table->foreign('business_id')->references('id')->on('businesses')->onDelete('set null');
```

Relation code for Listing:
```php
public function business()
{
    return $this->belongsTo(Business::class);
}
```

Query code:
```php
public function query()
{
        $listings = Listing::query();
        $listings
            ->with(['business' => function ($query) {
                /* @var \Illuminate\Database\Query\Builder $query */
                $query->select(['id', 'name']);
            }]);
        return $this->applyScopes($listings);
}
```

Table code:
```php
public function ajax()
{
        return $this->datatables
            ->eloquent($this->query())
            ->setRowId('id')
            ->make(true);
}
```

JavaScript column definition:
```javascript
{'title': 'Business', 'name': 'business.name', 'data': 'business', 'render': function() {...}}
```

I tried to keep my code at minimal, if I should post more let me know.

### System details
- Operating System: Windows 10
- PHP Version : 5.6.24
- Laravel Version: 5.3.24
- Laravel-Datatables Version 6.22.0

**Comment by tad3j** [comment]
I figured it out and am posting it here in case anyone else will have similar problems.

It turned out that the problem was in my models. I used generator to generate them and it didn't create inverse relations.

**Comment by yajra** [comment]
Can you please paste the error dump of ajax request? Your code looks fine so I guess there must be something wrong with fetching the column name when ordering the table. 

If you can, please do not hesitate to submit a PR for possible fix. Thanks!

**Comment by tad3j** [comment]
Hey @yajra . Thanks for replying. Even after the recent update I still experience the problem, but had to put it on side since I couldn't figure out why this happens.

There is no error when request is made, data is returned, but listings without businesses (where business_id = null) just don't return the id: http://screencast.com/t/D5BmcJIo73Zs (id is returned as null but obviously each entry has it's own id).

I'm suspecting it could be because of duplicate column names in queries, though not sure where to start looking. Any ideas from your side?

If you need anything else let me know.

**Comment by xelab** [comment]
Hello, same problem for me (even with last laravel-datatables update, and with Laravel 5.2 for me).
Standard fields seems to be replaced by the value of the ordered object (created_at, updated_at and id are null) when the relation is null.

When I execute the query here

```
$this->datatables
           ->eloquent($this->query())
```

outside the eloquent method from Datatable class (with standard Eloquent's Laravel class), data is ok.

**Comment by xelab** [comment]
I found a workaround.
Here was my old code to get the query for my datatable:

`public function query()
    {
        $books = Book::with('publisher', 'distributor', 'authors');
        return $this->applyScopes($books);
    }`

I added "->select('books.*')" to force my columns (for the main object) to have an alias:

`public function query()
    {
        $books = Book::with('publisher', 'distributor', 'authors')->select('books.*');
        return $this->applyScopes($books);
    }`

**Comment by yajra** [comment]
@xelab glad you sorted this out. The `select('books.*')` is indeed needed when using eager loading as documented [here](https://datatables.yajrabox.com/eloquent/relationships).

**Comment by xelab** [comment]
Oh sorry, did'nt see that! Thank you.

**Comment by tad3j** [comment]
Sorry for late reply. You were right, adding select statement for base table solved the problem. Somehow I missed that on documentation page. Thanks for pointing to it.
