### ISSUE TITLE
Is it optimized ?

### ISSUE THREAD

**Issue by vijaysebastian** [yajra/laravel-datatables#856]
Hi Yajra,

It is a great package. But I have a doubt, it is fetching whole record at one shot ! if i have 100k records. It will use huge memory. I hope you understood my problem. Please provide your perception about this.

Thank You & Good luck

**Comment by yajra** [comment]
@vijaysebastian it depends on how you use the package. If you use eloquent or query builder, then I could say it is optimized. However, if you are using collection, having 100k records would definitely raise a memory issue.

```php
User::query(); // Eloquent
DB::table('users'); // Query Builder
User::all(); // Collection
```
