### ISSUE TITLE
soft delete

### ISSUE THREAD

**Issue by omar-faruk-sust** [yajra/laravel-datatables#86]
when i am deleting a record from a table and redirect to the list i am getting an error. To show the list i have used this package. it was working fine before the soft delete.

ErrorException in AliasLoader.php line 63: Class 'yajra\Datatables\Facades\Datatables' not found

but in my aliases array in app.php there is 'Datatables' => yajra\Datatables\Facades\Datatables::class 
added. :( help me.

**Comment by omar-faruk-sust** [comment]
i do not know what happen when i am adding Facade like this way
'Datatables' => yajra\Datatables\Facades\Datatables::class

but now i am adding the facade like this way it is working. 
'Datatables' => yajra\Datatables\Datatables::class
but my question is why this behaviour.

**Comment by yajra** [comment]
@omar-faruk-sust , thanks for reporting. `'Datatables' => yajra\Datatables\Datatables::class` should be the correct alias. updated the read me. Thanks!
