### ISSUE TITLE
Eager loading, "Requested unknown parameters" on relationship

### ISSUE THREAD

**Issue by truongle7793** [yajra/laravel-datatables#860]
### Summary of problem or feature request
I want to display all the roles of user in one column via many-to-many relationship "roles" of entrust.
But getting the Requested unknown parameters "roles.name".
The first 2 columns is displaying fine.

### Code snippet of problem

```php
        $users = User::with('roles')->select('users.*');
        return Datatables::of($users)->make(true);
```
my javascript
```php
            $('#table-db').DataTable({
                searchable: true,
                processing: true,
                serverSide: true,
                stateSave: true,
                ajax: {
                    "url": '{{env('APP_URL')}}/admin/users/getdata'
                },
                columns: [
                    { data: 'id', name: 'users.id' },
                    { data: 'name', name: 'users.name' },
                    { data: 'roles.name', name: 'roles.name' }
                ],
            });
        });
```

- Laravel-Datatables Version install as instruction a couple of days ago

**Comment by yajra** [comment]
I think your `User` model have many `Roles` right? In this case, you should not access the `roles` array directly and instead should loop onto it. See this [demo](https://datatables.yajrabox.com/relation/has-many) on how I loop into user's posts.

**Comment by truongle7793** [comment]
Thanks so much! Can i ask another question.
I have something like this
`with('user', 'job')->select(user_job.*)`
And then i want to edit the user.name column. Is this code correct
`->editColumn('user.name', 'blade template')`
how can i access the user's parameters inside of the template.
Usually when using select as and join then it would be {{$username}} or the like right.
But when using eager load this don't work {{$user->name}}.

**Comment by yajra** [comment]
See this [edit column](https://yajrabox.com/docs/laravel-datatables/6.0/edit-column) docs for ref.

**Comment by truongle7793** [comment]
Thanks!
