### ISSUE TITLE
table id=table - Invalid JSON response

### ISSUE THREAD

**Issue by xeebeast** [yajra/laravel-datatables#862]
I'm using Server side processing of DATATABLES using larvel5.3

It is working fine on my local machine Ubuntu 16.04 but on server same Ubuntu 16.04 its is giving my Invalid JSON error.

Please help me

this us my JS code
```php
var users = $('.users-datatable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{{ url('admin/adminPanleUserDataTable') }}}",
        columnDefs: [{
            targets: [0, 1, 2],
            className: 'mdl-data-table__cell--non-numeric'
        }]
    });
```
and this my response
```
 {"draw":2,"recordsTotal":1,"recordsFiltered":1,"data":[["taimoor","hassan","dastisupportadmin@gmail.com"]],"input":{"draw":"2","columns":[{"data":"0","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}},{"data":"1","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}},{"data":"2","name":"","searchable":"true","orderable":"true","search":{"value":"","regex":"false"}}],"order":[{"column":"0","dir":"asc"}],"start":"0","length":"10","search":{"value":"","regex":"false"},"_":"1480405136776"}}
```

 Operating System Ubuntu 16.04 both local and Server
 PHP Version 5.6 both
 Laravel Version 5.3 both
 Laravel-Datatables Version 5.7.16

**Comment by yajra** [comment]
Your code looks fine. Is there any error dump when you inspected the ajax request?

**Comment by xeebeast** [comment]
this is what I get ...
SyntaxError: Unexpected token ﻿ in JSON at position 0 when returning html 
Its working fine on my local machine

**Comment by xeebeast** [comment]
Solved... The problem was that the object buffer was not cleared, dun know why, but it is working fine when I used ob_clean().
