### ISSUE TITLE
Support LengthAwarePaginator

### ISSUE THREAD

**Issue by mits87** [yajra/laravel-datatables#863]
Hello,

Are you thinking about support of LengthAwarePaginator format in larave-datatables plugin?

Example:
```
$admins = Admin::where('email', 'like', "%{$search_param}%")->paginate(10);
return \Yajra\Datatables\Facades\Datatables::of($admins)->make(true);
```

in my opinion this is great feature. What are you thinking about it?

Best Regards
Peter

**Comment by yajra** [comment]
Not sure since dataTable has it's own way of paging via client side. But if you can give me some hints on how should we go about this, then I guess I could consider this on the next major release. Thanks!
