### ISSUE TITLE
Invalid JSON response

### ISSUE THREAD

**Issue by safiboss** [yajra/laravel-datatables#864]
Hello!

I am getting the invalid json response and I really don't know why. When I use the developer tools the answer from the server is the html of the webpage. Below you can find my code:

controller:

```
<?php

namespace App\Http\Controllers;
use Carbon\Carbon;
use Cartalyst\Sentinel\Laravel\Facades\Activation;
use File;
use Hash;
use Illuminate\Http\Request;
use Lang;
use Mail;
use Redirect;
use Sentinel;
use URL;
use View;
use Datatables;
use Validator;
use DB;

class XController extends Controller
{

public function thirdparty(Request $request)
    {
		
		$id = $datatables->request->get('id');
	
			
			$l = DB::table('l')
            ->leftJoin('lethirdparties', 'l.id', '=', 'lethirdparties.le_id' )
			->select('l.id', 'lethirdparties.de', 'lethirdparties.dni', 'lethirdparties.address',
			'lethirdparties.contact_number', 'lethirdparties.state', 'lethirdparties.de_l', 'lethirdparties.de_p')
			->where('l.id',$id)
            ->get();

         return Datatables::of($l)->make(true);
    }
	
	
}
```
Route
`Route::get('le/thirdparty', array('as' => 'le.thirdparty', 'uses' => 'XController@thirdparty'));`

	<script>
        $(function() {
            var table = $('#thirpartytable').DataTable({
                processing: true,
                serverSide: true,
				responsive: true,
				"sScrollX": "100%",
				"sScrollXInner": "100%",
                ajax: {
            "url": "{!! route('le.thirdparty') !!}",
            "data": function (d) {
                d.id = {!! $result->id !!};
              
            }
        },
				createdRow: function( row, data, dataIndex ) {
        $( row ).find('td').attr('style', 'text-align:center;');
    },
                columns: [
                    { data: 'id', name: 'id' },
					{ data: 'de', name: 'de' },
					{ data: 'dni', name: 'dni' },
					{ data: 'address', name: 'address' },
					{ data: 'contact_number', name: 'contact_number' },
					{ data: 'state', name: 'state' },
					{ data: 'de_l', name: 'de_l' },
                                        { data: 'de_p', name: 'de_p' },
                ],
				
			
            });
           
        });
    </script>

**Comment by yajra** [comment]
Your code looks fine. Maybe try checking if this route `"url": "{!! route('le.thirdparty') !!}",` does exists? Since you say that it returns the html, then I guess you might be pointing on the wrong url?

**Comment by safiboss** [comment]
You were right. There was a conflict with others url. 

Thank you, close the question.
