### ISSUE TITLE
Please consider setting up a patreon page

### ISSUE THREAD

**Issue by jackfruh** [yajra/laravel-datatables#866]
Hi there, I think i've donated a few times in the past and I see you're still going strong here!

I'd like to suggest that you put up a patreon page for donations instead of your current system.

Patreon donations are like "subscriptions" people pledge a little bit each month.

My thought is that it's easier to get someone to pledge $1.50 a month than it is to get them to give an $18 donation and then come back a year later and do that again, etc..

**Comment by yajra** [comment]
Hi @jackfruh, 

Thanks for the suggestion. I am not familiar with "patreon" so I searched and found out that taylor otwell do also use this system. In this regard, I did signup to test it and here is my [patreon page](https://www.patreon.com/yajra).

Will do the necessary changes! Thanks!

**Comment by jackfruh** [comment]
I just checked out the page, but it has a $100 a mont minimum. I think most people either have no minimum or they set the minimum to $1.

**Comment by yajra** [comment]
I see, i think it's because of the reward. Anyways, I made a $1 reward for a cup of coffee. I was thinking that the **No Reward** was the option for $1+ tip. Thanks for looking at it.

**Comment by yajra** [comment]
Thanks a lot @jackfruh for being a patreon! 🚀
