### ISSUE TITLE
 FatalErrorException in Helper.php(99) : eval()

### ISSUE THREAD

**Issue by kyawzinwin** [yajra/laravel-datatables#867]
### Summary of problem or feature request
After upgraded to version **6.17.0**, got error says "FatalErrorException in Helper.php(99) : eval()'d". Everything was ok in previous version **6.11.0**.

- Laravel Version (5.1)
- Laravel-Datatables Version (6.17.0)

**Comment by yajra** [comment]
Can you try updating to latest version 6.22.0 and verify if still having this issue?

**Comment by kyawzinwin** [comment]
Hi @yajra,

I updated to version 6.22.0 and error is still happening.

**Comment by yajra** [comment]
@kyawzinwin thanks for the feedback. Can you please provide some snippets on how to reproduce the issue?

**Comment by kyawzinwin** [comment]
@yajra 

Please check the snippet. I noticed that this error is only happening on this one. I also use datatable server side processing in other module which are working correctly. So may be some codes in this method are conflict with latest version. Thanks.

```
public function datatables(Request $request)
    {
        DB::statement(DB::raw('set @rownum=0'));
        $type = $request->get('type');
        $products = Product::select([DB::raw("@rownum  := @rownum  + 1 as no"), 'code', 'name', 
                            'price', 'status', 'created_at'])
                            ->where('partner_id', Auth::user()->Partner->id);
     
        if ($type=='draft'){
            $products->where('draft',1);
        }
        else{
            $products->where('draft',0);
        }                                    

        return \Datatables::of($products)     
                ->addColumn('action', function ($product) use ($type) {
                    return view('product.partial.datatable.action', compact('product', 'type'))->render();
                })
                ->editColumn('created_at','{{ $created_at->format("d-m-Y") }}')
                ->editColumn('price','${{ $up_price }}')
                ->make(true);
    }
```

**Comment by yajra** [comment]
I see, I think this code is what breaks your app. Methods are now disabled when using blade string. See https://github.com/yajra/laravel-datatables/issues/643 for details.

```php
->editColumn('created_at','{{ $created_at->format("d-m-Y") }}')
```

**Comment by kyawzinwin** [comment]
Thanks @yajra, now it's working properly after updated as below

```
->editColumn('created_at', function($products) {
    return $products->created_at->format("d-m-Y");
})
```
