### ISSUE TITLE
Can't search with HasManyThorugh

### ISSUE THREAD

**Issue by stsepelin** [yajra/laravel-datatables#869]
Hello,

Trying to make search working. I have HasManyThorugh relationship and I need to sum some values. Datatables render data perfectly, but I cant search this values.
Controller:
`
->addColumn('views', function (Campaign $campaign) {
    return $page->reports->sum('views');
})
`
Blade:
`{ data: 'views', name: 'reports.views' },`
Error:
`
Call to undefined method Illuminate\Database\Query\Builder::getQualifiedForeignKey()
`
Version: v6.22.2

**Comment by yajra** [comment]
@stsepelin I think HasManyThrough is not yet supported and I haven't personally tested the package with it. Tagging for enhancement. Thanks!

**Comment by yajra** [comment]
@stsepelin I think this was already supported on the latest version. Can you please confirm if it's working? Thanks!
