### ISSUE TITLE
Getting related models fields

### ISSUE THREAD

**Issue by arieltoledo** [yajra/laravel-datatables#870]
Hi, im quite new at datatables and I cant figure out how to get the related model field instead of the foreign key in my related models. Its a "hasone" relationship. Thanks in advance.

**Comment by stsepelin** [comment]
There is example in docs: https://yajrabox.com/docs/laravel-datatables/6.0/relationships
Also demo: https://datatables.yajrabox.com/relation/has-one

**Comment by arieltoledo** [comment]
Thanks a lot @stsepelin, made it work with the docs !!!
