### ISSUE TITLE
Error SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "as"

### ISSUE THREAD

**Issue by Abdulhmid** [yajra/laravel-datatables#871]
### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by efriandika** [comment]
I got same error

**Comment by yajra** [comment]
Thanks for reporting. I think this might be connected to PR #849. I haven't used PostgreSQL so if someone can please submit a PR for a possible fix? Will try to setup a postrgeSQL app when I had the chance. Sorry for the inconvenience.

**Comment by yajra** [comment]
Guys, can you please check if the PR above fixes this issue? Thanks!
