### ISSUE TITLE
Smart search does not work, even when putting it in verbose

### ISSUE THREAD

**Issue by thomasmoors** [yajra/laravel-datatables#881]
`Datatables::eloquent(Model::query())->smart(true)->make(true);` Does not work either.
smart search reference: https://datatables.net/examples/api/regex.html

**Comment by yajra** [comment]
I haven't really personally used this feature but the package handles regex differently. See this [doc](https://yajrabox.com/docs/laravel-datatables/6.0/regex) for ref. [`smart(true)`](https://yajrabox.com/docs/laravel-datatables/6.0/smart-search) is case insensitive search runtime settings.

**Comment by thomasmoors** [comment]
@yajra I don't use the regex function, but this page also demos the smart feature. This issue has nothing to do with regex.

**Comment by yajra** [comment]
OIC, are you using the latest version? Seems to work fine on my side.

**Comment by thomasmoors** [comment]
@yajra so does it search multiple columns space separated on your side?

**Comment by yajra** [comment]
Fixed on v7.4.0. Thanks!
