### ISSUE TITLE
How to add ajax parameters in service implementation

### ISSUE THREAD

**Issue by ozza** [yajra/laravel-datatables#883]
hello,

i'm working with a massive table (50 million+ rows). and there's a continuous data flow (insert, get etc) on the table. displaying the datatable takes forever..

we're using datatables as a service implementation. we managed to get it work by following DataTables as Service tutorial. and it works fine with smaller tables.

for the problem with the massive table, we thought we had to make it serverside and paginated. but couldn't manage to get it work.

i tried to add ajax parameters in DataDataTable.php's html method like this;

> return $this->builder()
            ->columns($this->getColumns())
            ->ajax([
                'processing'   => 'true',
                'serverSide'   => 'true',
                'ajax'         => 'http://localhost:8000/data'
            ])

(code styling not worked)

but it's not the correct way i think since it's not working. can you give me an example how to make this work?

thank you

**Comment by yajra** [comment]
Try this snippet:

```php
return $this->builder()
	->columns($this->getColumns())
	->ajax('http://localhost:8000/data')
```

**Comment by ozza** [comment]
hello yajra,

thank you for your answer. how should i return the results in my controller or route? when i fetch the results by model::all() or model::query() i'm getting a memory exception. do i have to paginate the results in the controller or something?

**Comment by yajra** [comment]
Make sure you are using `model::query()` to avoid memory exceptions and check this [demo](https://datatables.yajrabox.com/html/method) for some ref. Pagination is automatically handled by the package along with the jQuery DataTables plugin.

```php
use Yajra\Datatables\Html\Builder; // import class on controller

public function getBasic(Request $request, Builder $htmlBuilder)
{
    if ($request->ajax()) {
        return Datatables::of(User::select(['id', 'name', 'email', 'created_at', 'updated_at']))->make(true);
    }

    $html = $htmlBuilder
        ->addColumn(['data' => 'id', 'name' => 'id', 'title' => 'Id'])
        ->addColumn(['data' => 'name', 'name' => 'name', 'title' => 'Name'])
        ->addColumn(['data' => 'email', 'name' => 'email', 'title' => 'Email'])
        ->addColumn(['data' => 'created_at', 'name' => 'created_at', 'title' => 'Created At'])
        ->addColumn(['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Updated At']);

    return view('datatables.html.method', compact('html'));
}
```

**Comment by ozza** [comment]
thank you yajra, i will try it on monday.
