### ISSUE TITLE
Adding permissions on the button show, edit and delete

### ISSUE THREAD

**Issue by agungid** [yajra/laravel-datatables#884]
@permission('menu-show')
                        <a class="btn btn-info btn-sm" href="{{ route('menu.show',$menu->id) }}">Lihat</a>
                    @endpermission

                    @permission('menu-edit')
                        <a class="btn btn-primary btn-sm" href="{{ route('menu.edit',$menu->id) }}">Edit</a>
                    @endpermission

                    @permission('menu-delete')
                        {!! Form::open(['method' => 'DELETE','route' => ['menu.delete', $menu->id],'style'=>'display:inline','class'=>'delete']) !!}
                            {!! Form::submit('Hapus', ['class' => 'btn btn-danger btn-sm']) !!}
                        {!! Form::close() !!}
                    @endpermission

**View**

$('#users-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('coba.data') !!}',
            columns: [
                { data: 'name', name: 'name' },
                { data: 'display_name', name: 'display_name' },
                { data: 'roles[].display_name', name: 'roles.display_name' },
                { data: 'description', name: 'description' },
                { data: 'created_at', name: 'created_at' },
                { data: 'updated_at', name: 'updated_at' },
                { data: 'action', name: 'action', orderable: false, searchable: false }
            ]
        });

**Controller**

public function anyData()
    {
        $query = Permission::with('roles')->select('permissions.*')->orderBy('id','desc');

        return Datatables::of($query)
                ->addColumn('action', function($query){
                     return "<a href='#edit-" . $query->id . "' class='btn btn-xs btn-primary'><i class='glyphicon glyphicon-edit'></i> Edit</a>";
                })
                ->editColumn('id', 'ID: {{$id}}')
                ->make(true);
    }

**Comment by yajra** [comment]
You can use a view on addColumn. See this doc for ref: https://yajrabox.com/docs/laravel-datatables/6.0/add-column#view

**Comment by agungid** [comment]
Thanks @yajra It's a good solution

**Comment by ibnudirsan** [comment]
> ```
>                 @permission('menu-show')
>                     <a class="btn btn-info btn-sm" href="{{ route('menu.show',$menu->id) }}">Lihat</a>
>                 @endpermission
> 
>                 @permission('menu-edit')
>                     <a class="btn btn-primary btn-sm" href="{{ route('menu.edit',$menu->id) }}">Edit</a>
>                 @endpermission
> 
>                 @permission('menu-delete')
>                     {!! Form::open(['method' => 'DELETE','route' => ['menu.delete', $menu->id],'style'=>'display:inline','class'=>'delete']) !!}
>                         {!! Form::submit('Hapus', ['class' => 'btn btn-danger btn-sm']) !!}
>                     {!! Form::close() !!}
>                 @endpermission
> ```
> 
> **View**
> 
> $('#users-table').DataTable({ processing: true, serverSide: true, ajax: '{!! route('coba.data') !!}', columns: [ { data: 'name', name: 'name' }, { data: 'display_name', name: 'display_name' }, { data: 'roles[].display_name', name: 'roles.display_name' }, { data: 'description', name: 'description' }, { data: 'created_at', name: 'created_at' }, { data: 'updated_at', name: 'updated_at' }, { data: 'action', name: 'action', orderable: false, searchable: false } ] });
> 
> **Controller**
> 
> public function anyData() { $query = Permission::with('roles')->select('permissions.*')->orderBy('id','desc');
> 
> ```
>     return Datatables::of($query)
>             ->addColumn('action', function($query){
>                  return "<a href='#edit-" . $query->id . "' class='btn btn-xs btn-primary'><i class='glyphicon glyphicon-edit'></i> Edit</a>";
>             })
>             ->editColumn('id', 'ID: {{$id}}')
>             ->make(true);
> }
> ```

ini ada di blade apa return json dari controller ?.
ketemu issu yang sama untuk penggunaan permission spatie pakai @can
 masih bingung untuk implementasi ke laravel nya (6.x).
