### ISSUE TITLE
Applying filterColumn to a relationship

### ISSUE THREAD

**Issue by andcl85** [yajra/laravel-datatables#886]
### Summary of problem or feature request

Is it possible to apply filterColumn() to change the default search behaviour to columns that belong to a relationship? It does not seem to work in my case, and I do not know if it is implemented...

#### Laravel controller

```
return Datatables::of(Alarma::with('tipoAlarma')->select('alarmas.*'))

                // FechaAlarma column definition
                ->editColumn('fechaAlarma', function ($alarma) {
                    return $alarma->fechaAlarma->format('d/m/Y - H:i:s');
                })

                // FechaAlarma filterColumn
                ->filterColumn('fechaAlarma', function ($query, $keyword) {
                    $query -> whereRaw("DATE_FORMAT(fechaAlarma, '%d/%m/%Y - %H:%i:%s') like ?", ["%$keyword%"]);
                })

                // TipoAlarma column definition
                ->addColumn('tipoAlarma', function (Alarma $alarma) {
                    return $alarma->tipoAlarma->nombre . ' (' . $alarma->duracion . ' s)';
                })

                // TipoAlarma filterColumn
                ->filterColumn('tipoAlarma', function ($query, $keyword) {
                    $query -> whereRaw("CONCAT(tipoAlarma.nombre, ' ', tipoAlarma.tipo) like ?", ["%$keyword%"]);
                })
```
With 'fechaAlarma', filterColumn works fine, as 'fechaAlarma' is a field of 'alarmas' table...
But with 'tipoAlarma', filterColumn definition does not work. Search query looks for the id in the 'tiposAlarma' table (respecting the relationship), but it is not overriden by filterColumn behaviour...

#### JS call

```
...
columns: [
    { data: 'fechaAlarma', name: 'fechaAlarma' },
    { data: 'tipoAlarma', name: 'tipoAlarma.id' },   <----- filterColumn query searchs for the ID in 'tiposAlarma' table, but is not overriden by filterColumn...
],
...

```

Thanks in advance.

**Comment by yajra** [comment]
I think filter column uses the name on your js. Try using something like below:

```php
// TipoAlarma filterColumn
->filterColumn('tipoAlarma.id', function ($query, $keyword) {
    $query -> whereRaw("CONCAT(tipoAlarma.nombre, ' ', tipoAlarma.tipo) like ?", ["%$keyword%"]);
})
```

**Comment by andcl85** [comment]
First of all, thanks for your reply.
And yes, with your proposal, the filterColumn overrides the default search for that column, but then I get an error because it behaves as if the 'tipoAlarma.id' field was in the same table of 'alarmas', and not in another one. The error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tipoAlarma.nivel' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `alarmas` where ((DATE_FORMAT(fechaAlarma, '%d/%m/%Y - %H:%i:%s') like %example%) or (CONCAT(tipoAlarma.nivel, ' ', tipoAlarma.nombre) like %example%) >= 1)) count_row_table)

Any idea?

**Comment by yajra** [comment]
@andcl85 it appears that `filterColumn` does not join the related tables atm. You may have to join the tables manually to make it work. Thanks and sorry for late response!

**Comment by andcl85** [comment]
Ok, thanks anyway.
I managed to do it manually some time ago ;)

**Comment by nickbr5** [comment]
Hi @andcl85 ,

Can you show me how you resolved this problem?
I have the same issue.

thx

**Comment by andcl85** [comment]
Hi @nickbr5 ,
Do it manually means that you will have to query your **main table** using some JOIN to get the **related / relationship fields** BEFORE passing them to the `filterColumn` method. Then, those related fields will be just fields contained in the query result and, therefore, correctly accesible by `filterColumn`. E.g.:
```
// Query over your main table
MainModel::join('relatedTable', 'mainTable.relatedTable_id', '=', 'relatedTable.id')
            -> select(DB::raw("
                        mainTable.id as id,
                        mainTable.anyField, 
                        relatedTable.anyField as relatedField")
);                       
```
Use ALIAS (relatedField) when necessary.
Finally doing so, the list of available fields to pass to `filterColumn` now will be `id`, `anyField` and `relatedField`.

Regards!

**Comment by kjjdion** [comment]
You don't have to use a join, you can use `whereHas` in the `filterColumn` query.

**Comment by amataslovers** [comment]
> You don't have to use a join, you can use `whereHas` in the `filterColumn` query.

thank you very much
