### ISSUE TITLE
Invalid parameter number when using global scope

### ISSUE THREAD

**Issue by shadoWalker89** [yajra/laravel-datatables#887]
### Summary of problem or feature request

I get the `Invalid parameter number` error when i try using the dataTables search field

even after following instructions in

https://datatables.yajrabox.com/eloquent/relationships

https://datatables.yajrabox.com/relation/belongs-to

```
SQLSTATE[HY093]: Invalid parameter number (SQL: select count(*) as aggregate from (select '1' as `row_count` from `edoc_students` where (LOWER(`edoc_students`.`id`) LIKE %f% or (select count(1) from `edoc_users` where `edoc_students`.`user_id` = `edoc_users`.`id` and LOWER(`edoc_users`.`first_name`) LIKE %f% and `edoc_users`.`school_id` = %f%) >= 1 or LOWER(`edoc_students`.`first_name_secondary`) LIKE %f% or (select count(1) from `edoc_users` where `edoc_students`.`user_id` = `edoc_users`.`id` and LOWER(`edoc_users`.`last_name`) LIKE %f% and `edoc_users`.`school_id` = %f%) >= 1 or LOWER(`edoc_students`.`last_name_secondary`) LIKE ? or LOWER(`edoc_students`.`id_document`) LIKE ?)) count_row_table)
```

I'm using "hipsterjazzbo/landlord" package to manage multi tenancy in my application.
On the `users` table i have `school_id` field that i used in a global scope by the package that i mentioned.
The packages responsibility is to add where clause to all the queries `WHERE school_id = ID_OF_THE_SCHOOL`

When i remove the multi tenancy behavior (and thus the global scope) from the `User` Model the problem disappears.

### Code snippet of problem

```javascript
{
    processing: true,
    serverSide: true,
    ajax: '{!! route('student.index.data') !!}',
    columns: [
        { data: 'id', name: 'students.id' },
        { data: 'user.first_name', name: 'user.first_name' },
        { data: 'first_name_secondary', name: 'students.first_name_secondary' },
        { data: 'user.last_name', name: 'user.last_name' },
        { data: 'last_name_secondary', name: 'students.last_name_secondary' },
        { data: 'id_document', name: 'students.id_document' }
    ]
}
```

```php
$students = Student::with('user')->select('students.*');

return Datatables::eloquent($students)->make(true);
```

### System details

- Operating System Windows 8.1
- PHP Version 5.6
- Laravel Version 5.3.26
- Laravel-Datatables Version 6.22.5

**Comment by yajra** [comment]
Thanks for reporting, will try to check that package / simulate global scope when I had the chance. ATM, maybe try manually setting the school_id if possible for a work around. Thanks!

**Comment by ndiiorio** [comment]
@shadoWalker89 could you solve this issue?

**Comment by shadoWalker89** [comment]
@ndiiorio no i didn't.
I'm just not using the package for now.

**Comment by dhcmega** [comment]
Hi @ndiiorio, what's the problem? I use multi tenancy with a global scope and I have no errors, it just filters the query. Do you need the package for something else or a scope filter will do?
