### ISSUE TITLE
Change response data

### ISSUE THREAD

**Issue by neeonline** [yajra/laravel-datatables#888]
Hi,

First, thanks for save my weekend. This is exactly what I was looking for.

Now,

There is any way to extend/change the responde data? In other words, can I use something similar:

```
$result = Datatables::collection($collection)->make();

$result->data->each(...
```

Thank you!

**Comment by yajra** [comment]
@neeonline you can access the json response using the snippet below:

```php
$dataTable = $this->datatables->eloquent($this->query())->make(true);
$response = $dataTable->getData(true);
$response['data'] = collect($response['data'])->each(...)
```

**Comment by neeonline** [comment]
Thanks Yajra, that works like a charm.

Congratulations on this amazing plugin.

Kudos.

**Comment by p0nt** [comment]
This does not seem to work in combination with laravel and/or the version ^1.0

"Call to undefined method"

**Comment by p0nt** [comment]
<img width="536" alt="Screenshot 2019-11-29 at 22 57 38" src="https://user-images.githubusercontent.com/25501135/69891276-a73b6400-12fb-11ea-9db6-125b620e3f72.png">
