### ISSUE TITLE
No SQL request executed

### ISSUE THREAD

**Issue by alur86** [yajra/laravel-datatables#889]
Hello,

I try to launch this code, what are bellow and all time get the empty view. The sql data request doesn't executed.Can you help me?

```php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


use App\User;
use Yajra\Datatables\Datatables;


class DatatablesController extends Controller
{
   
    public function getIndex()
    {
        return view('datatables.index');
    }

    public function getData()
    {
    
          
        $users = User::select(['id','name','email','created_at','updated_at'])->get();

        return Datatables::of($users)->make();

    }
}


@extends ('layouts.app')
@section ('content')
@section('title', 'Users')

@section('content')
    <table class="table table-bordered" id="users-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>Updated At</th>
            </tr>
        </thead>
    </table>
@endsection

@push('js')
<script>
$(function() {
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('getdata') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'created_at', name: 'created_at' },
            { data: 'updated_at', name: 'updated_at' }
        ]
    });
});
</script>
@endpush

Route::get('/datatables', 'DatatablesController@getIndex');
Route::get('/getdata', ['as' => 'getdata', 'uses' => 'DatatablesController@getData']);

```

- Operating System
- PHP Version 5.6
- Laravel Version 5.3
- Laravel-Datatables Version 6.22

**Comment by yajra** [comment]
Your code looks fine except for the double section for content? Try removing the first content section.

```php
@extends ('layouts.app')
@section ('content')
@section('title', 'Users')

@section('content')
```

**Comment by alur86** [comment]
Ok, I did. It didn't help.I used the code like that, without blame tags and after that it started work well.Any ideas why that happened?

   <table class="table table-bordered" id="users-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>Updated At</th>
            </tr>
        </thead>
    </table>



<script>
$(function() {
    $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('getdata') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'created_at', name: 'created_at' },
            { data: 'updated_at', name: 'updated_at' }
        ]
    });
});
</script>

**Comment by yajra** [comment]
@alur86 not sure what happened but must be related on how Laravel compiles the section. Thanks!
