### ISSUE TITLE
how to change default class

### ISSUE THREAD

**Issue by rakshitbharat** [yajra/laravel-datatables#890]
in short i am using dependency injection to draw table but cant change design HTML 

- Operating System
- 7PHP
- Laravel 5.3

**Comment by yajra** [comment]
You can pass an array of parameters when drawing the table. See this [doc](https://yajrabox.com/docs/laravel-datatables/6.0/html-builder-table) for ref. 

But for default class, I think it's not yet configurable. Tagging this for enhancement. Thanks!

**Comment by rakshitbharat** [comment]
thanks for fast reply .

please add this in to do.

this package contains good effort thanks for making this .

**Comment by yajra** [comment]
Moved the issue to HTML plugin repo. https://github.com/yajra/laravel-datatables-html/issues/3 Thanks!
