### ISSUE TITLE
Call to undefined method Yajra\Datatables\Datatables::eloquent()

### ISSUE THREAD

**Issue by itzikbenh** [yajra/laravel-datatables#891]
### Summary of problem or feature request

I need to render a table with belongsTo relations and allow search. I followed the docs, but I get this error.
How can I allow search to all those relations?

If I use "of" instead of eloquent I get "Call to undefined method Illuminate\Database\Query\Builder::map()"

### Code snippet of problem

```php
        use Yajra\Datatables\Datatables;

        $model = Ticket::with('client', 'location', 'status', 'priority');
     
            return Datatables::eloquent($model)
            ->addColumn('client', function (Ticket $ticket) {
                return $ticket->client->map(function($client) {
                    return $client;
                })->implode('<br>');
            })
            ->make(true);
```

### System details

- MAC Sierra
- 7.0
- 5.3
- 1.5.6

**Comment by yajra** [comment]
You need to use the Facade to be able to call `Datatables::eloquent()`.

```php
use Yajra\Datatables\Facades\Datatables;
// OR
use Datatables;
```

**Comment by yajra** [comment]
See this [doc](https://yajrabox.com/docs/laravel-datatables/6.0/engine-eloquent) for some ref on how to call the package. Thanks!

**Comment by itzikbenh** [comment]
Thank you very much! All works now. Sorry for the false alarm.
