### ISSUE TITLE
Query Relationship Additional Column

### ISSUE THREAD

**Issue by seivad** [yajra/laravel-datatables#893]
### How do you query a relationships additional columns using ->filterColumn()

I've got a column called "customer" and inside it's <td> is the customers Name, Email and Phone Number. I'd like to search those fields but currently in the Javascript it's just set to name="customer.name". 

I've setup a ->filterColumn() but I can't tell if it's already inside the relationship, I did try $query->where('email', 'LIKE', '%'.$keyword.'%'); but this did not work.

Any ideas? It would be great if you could just stipulate that you are querying a relationship and it'll then search all of the columns specified within that relationship too. 

Otherwise everything is working include another filterColumn on AUS dates for US date filtering.

- PHP Version 7.0.x
- Laravel Version 5.2.x
- Laravel-Datatables 6.x

**Comment by yajra** [comment]
Try using something like below. The package will automatically joins the required table for you. 

```php
->filterColumn('customer.name', function($query, $keyword) {
    $query->where('customer.name', 'like', $keyword)->orWhere(...);
})
```

For dates, see this [demo](https://datatables.yajrabox.com/fluent/carbon) for ref.

**Comment by seivad** [comment]
That did not work for me.

```
QueryException in Connection.php line 729: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'customer.name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `bookings` where (LOWER(`bookings`.`booking_number`) LIKE %davies% or (select count(1) from `suppliers` where `suppliers`.`id` = `bookings`.`supplier_id` and LOWER(`suppliers`.`name`) LIKE 
```

Even when using something basic like:

```
$query->where('customer.name', 'LIKE', '%'.$keyword.'%');
```

Instead I ended up using:

```
->filterColumn('customer', function ($query, $keyword) {
                $query->where('customer_phone_number', 'LIKE', '%'.$keyword.'%')
                    ->orWhere('customer_email', 'LIKE', '%'.$keyword.'%')
                    ->orWhere('customer_name', 'LIKE', '%'.$keyword.'%');
            })
```

and

revised the initial query to be:

```
$bookings = Booking::join('users', 'bookings.customer_id', '=', 'users.id')
            ->join('suppliers', 'bookings.supplier_id', '=', 'suppliers.id')
            ->select(['bookings.*', 'suppliers.name', 'users.name as customer_name', 'users.email as customer_email', 'users.phone_number as customer_phone_number', 'users.address as customer_address', 'users.id as customer_id']);
        $data = Datatables::eloquent($bookings);
```

In future releases it would be cool just do something like:

```
"columns": [
            {data: 'booking_number', name: 'booking_number', "orderable": true},
            {data: 'date', name: 'date', "orderable": true},
            {data: 'address', name: 'address',  "orderable": true},
            {data: 'customer', name: ['customer.name', 'customer.id', 'customer.phone_number', 'customer.email'],  "orderable": true },
        ]
```

**Comment by yajra** [comment]
Glad you sorted this out. I reviewed and found that filterColumn does not join the related tables. Which in turns, you need to join the tables manually. Thanks!
