### ISSUE TITLE
Search Russian characters

### ISSUE THREAD

**Issue by hsander** [yajra/laravel-datatables#894]
### Summary of problem or feature request

If you use Russian characters in the search, an error occurs. When using the Latin alphabet, everything works fine. Encoding base utf8_unicode_ci. The title of the page <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
Error following:
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `blogs` inner join `blog_descriptions` on `blogs`.`id` = `blog_descriptions`.`blog_id` and `blog_descriptions`.`language_id` = 1 inner join `blog_categories` on `blogs`.`category_id` = `blog_categories`.`id` inner join `blog_category_descriptions` on `blog_categories`.`id` = `blog_category_descriptions`.`blog_category_id` and `blog_category_descriptions`.`language_id` = 1 where (`blogs`.`created_at` LIKE %Проверка% or `blogs`.`title_list` LIKE %Проверка% or `blogs`.`id` LIKE %Проверка% or `blogs`.`published` LIKE %Проверка% or `blogs`.`id` LIKE %Проверка% or `blogs`.`updated_at` LIKE %Проверка% or `blogs`.`id` LIKE %Проверка% or `blogs`.`view_count` LIKE %Проверка% or `blogs`.`id` LIKE %Проверка%) and `blogs`.`showcase_id` = 1) count_row_table)'

### Code snippet of problem

```php
$blogs = Blog::join( 'blog_categories', 'blogs.category_id', '=', 'blog_categories.id' )
		             ->join( 'blog_category_descriptions', function ( $join ) {
			             $join->on( 'blog_categories.id', '=', 'blog_category_descriptions.blog_category_id' )
			                  ->where( 'blog_category_descriptions.language_id', '=', $this->getLanguage()->id );
		             } )
		             ->select( [
			             'blogs.id',
			             'blogs.created_at',
			             'blogs.title_list',
			             'blogs.updated_at',
			             'blogs.view_count',
			             'blogs.published',
			             'blog_category_descriptions.meta_h1',
			             'blog_categories.slug',
			             'blog_categories.id',
		             ] );

		return Datatables::of( $blogs )
		                 ->editColumn( 'created_at', function ( Blog $blog ) {
			                 return $blog->created_at->formatLocalized( '%d/%m/%Y' );
		                 } )
		                 ->editColumn( 'updated_at', function ( Blog $blog ) {
			                 return $blog->updated_at->formatLocalized( '%d/%m/%Y' );
		                 } )
		                 ->make( true );
//////////////////////
js
///////////////
$('#form-search').on('keyup', '.form-search', function () {
    CreateTable.search(this.value).draw();
});
I tried so:
encodeURIComponent(this.value);

Error not, but finds nothing.
```

### System details

- Operating System - windows 10
- PHP Version 5.6
- Laravel Version 5.3
- Laravel-Datatables Version mySQL 5.7 64

**Comment by yajra** [comment]
@hsander I think this is on a database level configuration. I suggest you consult with your DBA for assistance. I made some quick search and seems to be related on the collation of table. Maybe try the solution suggested [here](http://forums.mysql.com/read.php?103,27204,27214#msg-27214).

```sql
SET collation_connection = utf8_general_ci; 

or 

SET character_set_connection = utf8;
```

**Comment by wvllvw** [comment]
same problem here

**Comment by hsander** [comment]
This problem has been the development of locally using OpenServer. After transferring to the hosting, not a problem. But what exactly is incorrectly configured locally do not know, all checked.

**Comment by SuperlativeEntity** [comment]
This is still an issue
