### ISSUE TITLE
Dispaly Sql Query in sql

### ISSUE THREAD

**Issue by Narayan-codelee** [yajra/laravel-datatables#895]
![screenshot_1](https://cloud.githubusercontent.com/assets/14311811/21284631/82d748dc-c447-11e6-8f2e-d08816f102ae.png)

### Summary of problem or feature request

Hi iam using datatables with backend laravel and frontend angular.js. when i fetch data using querybuilder it shows whole sql query in my console like this. 

### Code snippet of problem
  return Datatables::queryBuilder((new IssuedBook())->getLibraryFeePayer(organizatoinId(), $inputs))
                    ->editColumn('fine_amount', function($result) {
                        return twoDecimal($result->fine_amount);
                    })->make(true)

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
You need disable `APP_DEBUG=false` to remove the queries on response. See [docs](https://yajrabox.com/docs/laravel-datatables/6.0/debugger) for ref.

**Comment by Narayan-codelee** [comment]
Awo! its worked. Thanks
