### ISSUE TITLE
Is it possible to pass a repository instance to the datatables service class a param ?

### ISSUE THREAD

**Issue by minedun6** [yajra/laravel-datatables#896]
Is it possible to pass a repository instance to the datatables service class as a param ?

    `
     protected $locations;

    /**
     * LocationDataTable constructor.
     * @param $locations
     */
    public function __construct(LocationRepository $locations)
    {
        // parent::__construct(?,?);
        $this->locations = $locations;
    }`

**Comment by yajra** [comment]
Sorry but i think this is not possible since the parent class have it's own dependencies that should be passed in the constructor. You may have to load the repository class using the app helper:

```php
$this->locations = app(LocationRepository::class);
```
