### ISSUE TITLE
Error BaseEngine.php 407

### ISSUE THREAD

**Issue by pc-mon** [yajra/laravel-datatables#898]
Hello 
Thank you for good job
Acutely , I have Error : 
exception 'ErrorException' with message 'Call to undefined method Yajra\Datatables\Engines\BaseEngine::withtrashed()' in /vendor/yajra/laravel-datatables-oracle/src/Engines/BaseEngine.php:407
I'm working in this framework : https://github.com/rappasoft/laravel-5-boilerplate
and I did all what you said such as php artisan vendor:publish --tag=datatables and result was : 
Copied Directory [/vendor/yajra/laravel-datatables-oracle/src/resources/views] To [/resources/views/vendor/datatables]
Publishing complete for tag [datatables]!

I hope this problem will fixed soon , Thank you so much in advance

**Comment by yajra** [comment]
You might be using a lower version of the package. Try doing a composer update first then try publishing again?

**Comment by pc-mon** [comment]
I did update the composer and composer update the script even 
written in composer.json "yajra/laravel-datatables-oracle": "~6.0"
Is it last version or i have to change it ?

**Comment by yajra** [comment]
`withTrashed` was added on PR #786 and was released on v6.20.0. I guess updating the version to `"yajra/laravel-datatables-oracle": "^6.20"` and doing a composer update to make sure you're using the min version required.

Or try using `composer show` to verify the installed packages with their corresponding version.

**Comment by pc-mon** [comment]
fixed : "yajra/laravel-datatables-oracle": "^6.20"

**Comment by pc-mon** [comment]
Thank you so much
