### ISSUE TITLE
Testing datatables running as service

### ISSUE THREAD

**Issue by pjona** [yajra/laravel-datatables#901]
Hi,

at the beginning, thanks for this package, it's help me a lot!

I have problem only with testing datatables running as service. I found your example in demo app: https://github.com/yajra/laravel-datatables-demo/blob/master/tests/ExampleTest.php
but you used there "laracasts/integrated" which is not support anymore, and when I try install it on Laravel 5.3 I get conflicts.

I try use method that is build in Laravel - https://laravel.com/docs/5.3/application-testing#testing-json-apis and I get something like this:

```php
$url = '/settlement?draw=1&[HERE LONG URL]&_=1482194312785';
$this->json('GET', $url);
```

but it return always HTML instant of JSON data. I started debugging why it's happen, and when I add here: https://github.com/yajra/laravel-datatables/blob/6.0/src/Services/DataTable.php#L97

```php
dd($this->request()->all(), $this->request()->ajax(), Input::all());
if ($this->request()->ajax() && $this->request()->wantsJson()) {
    return $this->ajax();
}
```

`$this->request()->all()` is empty array (`[]`),  `$this->request()->ajax()` is `false`, and in `Input::all()` I have correct data:

```
array:7 [
  "draw" => "1"
  "columns" => array:6 [
    ...
    ]
  "order" => array:1 [
    0 => array:2 [
      "column" => "0"
      "dir" => "asc"
    ]
  ]
  "start" => "0"
  "length" => "10"
  "search" => array:2 [
    "value" => ""
    "regex" => "false"
  ]
  "_" => "1482194312785"
]
```

You have some idea how I can test datatables as a service with build in methods in Laravel 5.3?
All my code is here: https://github.com/pjona/krowa

### System details

- PHP Version: 7.0.14
- Laravel Version: 5.3.26
- Laravel-Datatables Version: 6.22.5

**Comment by yajra** [comment]
@pjona not really sure on testing but does `$this->json()` is sent as `ajax` request? It may not be passing the condition which is the reason why html is being returned. Can you try the code below if it passes?

```php
if ($this->request()->ajax() && $this->request()->wantsJson()) {
    dd('ajax');
    return $this->ajax();
}
```

**Comment by yajra** [comment]
@pjona, see this [post](http://stackoverflow.com/questions/20093897/how-to-simulate-xmlhttprequests-in-a-laravel-testcase). Basically, it suggests that you set the requested with header for `ajax()` to be detected. Maybe try something like below:

```php
$this->json('GET', $url, [],  ['HTTP_X-Requested-With' => 'XMLHttpRequest'])
```

**Comment by yajra** [comment]
Just tested this and seems like the dataTables Request class instance is null when running in the terminal. However, Laravel's `request()` helper have all the headers and inputs.

BTW, I think the syntax below is the proper way to test this:

```php
$this->json('GET', $url, [],  ['HTTP_X-Requested-With' => 'XMLHttpRequest'])->seeJson();
```

**Comment by yajra** [comment]
@pjona I made some changes on the Request class but is available only on v7.1++. Latest version is more testable and I also migrated the package unit tests using orchestra/testbench package. Upgrading to Laravel 5.4 version should address your issue. Thanks!

**Comment by yajra** [comment]
This is [commit](https://github.com/yajra/laravel-datatables/commit/f4e9b7b915b4a2b1ed3d8b914bcccaced0778972) for ref incase you need it.

**Comment by pjona** [comment]
@yajra Thanks! I plan make Laravel upgrade in February and then I will check, thanks once again!
