### ISSUE TITLE
Get SearchBar input val on Server Side !

### ISSUE THREAD

**Issue by Enemy22** [yajra/laravel-datatables#906]
### Get SearchBar input val on Server Side !

Good Morning; I have a problem, is it possible to access the "Value" of serachBar input on the server side? Basically the problem is that I need to filter the query before "return Datatables"; 

### I have SomeThing Like this 

      $casa = Casa::where('client_id', Auth::user()->id)->first();

        $guifftCards = guiftcarwin::where('casa', $casa->id)->orderBy('created_at','DESC')->select(['created_at','client_id' ,'id']);

        return Datatables::of($guifftCards)
            ->editColumn('client_id',function ($guifftCard){
                return  HellperFunction::getUserName($guifftCard->client_id);
            }  )
            ->editColumn('id',function ($guifftCard){
                return  HellperFunction::makeValue($guifftCard->id);
            }  )
            ->make();

### And i need ... 

      $casa = Casa::where('client_id', Auth::user()->id)->first();

      $usersID = Users::where('name', 'LIKE', "%{$SEARCHBAR}%")->pluck('client_id');

        $guifftCards = guiftcarwin::where('casa', $casa->id)->wherein('client_id',$usersID)->orderBy('created_at','DESC')->select(['created_at','client_id' ,'id']);

        return Datatables::of($guifftCards)
            ->editColumn('client_id',function ($guifftCard){
                return  HellperFunction::getUserName($guifftCard->client_id);
            }  )
            ->editColumn('id',function ($guifftCard){
                return  HellperFunction::makeValue($guifftCard->id);
            }  )
            ->make();

Thanks !

- Operating System: Osx 10.11.1
- PHP Version : 5.6
- Laravel Version 5.3
- Laravel-Datatables Xamp/mysql

**Comment by AdrienPoupa** [comment]
Hi,

Maybe this can answer your question? https://datatables.yajrabox.com/fluent/custom-filter

**Comment by yajra** [comment]
You can access it using `request('search.value')`. A more advance search can also be done using the link provided by @AdrienPoupa. Thanks!

**Comment by Enemy22** [comment]
Thanks AdrienPoupa, it do the job !!
