### ISSUE TITLE
Documentation needed For Service Approach

### ISSUE THREAD

**Issue by minedun6** [yajra/laravel-datatables#907]
I'm honestly not a big fan of the usual aproach as the service approach is a lot more helpful. The documentation is really really needed for this approach as it saves so much time writing stuff in the view files since I only update my DataTable class file.
The problem I stumbled on is that I need a custom filter on a column that has a many to many relationship, so far when I die and dump the query, it works and returns one result but when return it to make the datatable search for it, returns null so how can I go about this ? here's the code so far:

           ->filterColumn('statuses.label', function ($q, $keyword) {
                return Box::join('box_status', 'box_status.box_id', '=', 'boxes.id')
                        ->join('statuses', 'statuses.id', '=', 'box_status.status_id')
                        ->where('statuses.label', 'LIKE', '%'.$keyword.'%')->get();
            })

so far I think it needs to use the $q to work, but please advise.

And last but not least, how do you go about making a custom search using the Service approach.
Inspiration from this sample:
[Laravel Datatables | Overriding global search](https://datatables.yajrabox.com/fluent/custom-filter)

**Comment by yajra** [comment]
Yes, I think you need to use `$q` as it is the query builder instance. Maybe try something like below:

```php
->filterColumn('statuses.label', function ($q, $keyword) {
    return $q->join('box_status', 'box_status.box_id', '=', 'boxes.id')
            ->join('statuses', 'statuses.id', '=', 'box_status.status_id')
            ->where('statuses.label', 'LIKE', '%'.$keyword.'%');
})
```

I think join is also required when using `filterColumn` as the package does not automatically joins the eager loaded tables when using this api.

Lastly, will do more documentations next year for the service approach. Thanks for the suggestions!

**Comment by yajra** [comment]
Please open a new issue if needed. Thanks!
