### ISSUE TITLE
Reusing dataTables (service approach)

### ISSUE THREAD

**Issue by rzb** [yajra/laravel-datatables#908]
The scopes feature is handy when used in controllers to reuse existing datatables, but it only covers query filtering. 

What about adding/removing a certain column, modifying actions and so on? I think it's a common use case that we have to list, for instance, users in (usually slightly) different ways across the app, which leads to creating multiple UsersDatatable and repeating most of the code.

**Comment by yajra** [comment]
@rzb good point. I also bump on the same issue before but what I did was just a quick and dirty work around. If you have some idea on how to implement this, please don't hesitate to submit a PR. Thanks!

**Comment by yajra** [comment]
Moved issue to buttons plugin. https://github.com/yajra/laravel-datatables-buttons/issues/3
