### ISSUE TITLE
[7.0] Escape columns by default

### ISSUE THREAD

**Issue by nCrazed** [yajra/laravel-datatables#909]
### Summary of problem or feature request

XSS protection should be the default behavior to be in line with how Laravel5+ handles similar concepts. Of course this then becomes revers of how Laravel 4 handles this, but considering the two options the default behavior should be the secure one.

I understand that this would be a major BC break so the change would have to be delayed until the next major release. If you decide that this is a necessary change I am happy to work on a PR for it.

### Code snippet of problem

So instead of having to explicitly enable it for every column like so:

```php
return Datatables::eloquent(Role::select())
            ->escapeColumns()
            ->make(true);
```
we should be able to simply have this as the "safe" way:

```php
return Datatables::eloquent(Role::select())
            ->make(true);
```

and something like this for cases where we do need to avoid escaping:

```php
return Datatables::eloquent(Role::select())
            ->unescapedColumns(['name'])
            ->make(true);
```

**Comment by yajra** [comment]
Thanks for the suggestions. I agree with your proposal to escape all columns by default. Can you please submit a PR on master branch if possible? Thanks!

**Comment by yajra** [comment]
BTW, maybe we can use raw to match Laravel's raw statements?

```php
return Datatables::eloquent(Role::select())
            ->rawColumns(['name'])
            ->make(true);
```

**Comment by nCrazed** [comment]
Yeah, that's definitely a better name.

**Comment by nCrazed** [comment]
@yajra as far as I can tell there is no test coverage for the current column escaping functionality and I am not sure where to put them and and how to best design them.

I am thinking of create a trait that is applied to all three engine test classes (although EloquentEngineTest would have to be created as there isn't one yet) that defines the necessary tests and an abstract mocking/configuration that each engine test would have to implement. Do you think that it's a good way to go about it or is there a better way that I am missing?

**Comment by yajra** [comment]
@nCrazed I think you can just add a `rawColumns` method on the `BaseEngine` class and then handle the logic inside `DataProcessor` class.

With regard to testing, I must admit that the package lacks testing and would really appreciate if you could help and add more test if possible. Thanks!

**Comment by yajra** [comment]
In addition, a quick way to enable escaping of columns by default is just by setting the default escape list to `*`.

```php
protected $columnDef = [
        'index'     => false,
        'append'    => [],
        'edit'      => [],
        'excess'    => ['rn', 'row_num'],
        'filter'    => [],
        'order'     => [],
        'escape'    => '*',
        'blacklist' => ['password', 'remember_token'],
        'whitelist' => '*',
    ];
```
You can then add a `raw` key on the `columnDef` property that will set as a tracker on which columns should be allowed with html codes.

**Comment by yajra** [comment]
Added on master branch and will be released on v7. Thanks!

**Comment by quelo83** [comment]
Excuse me @yajra, but how can I do the inverse?
I mean, I need not to escape anything because when I access a related model with stats and numbers I get all related model fields in string format.
Is there a way to "skip" the escape functionality at all?

**Comment by quelo83** [comment]
Sorry, I've found the solution:

$dt->escapeColumns([])

Thanks and sorry again.
