### ISSUE TITLE
Filtering SQL modification?

### ISSUE THREAD

**Issue by martimarkov** [yajra/laravel-datatables#912]
### Summary of problem or feature request

I have a column that I need to search in a very specific way, how can I do this? I'm passing the data that needs to be searched but then I need to modify the SQL query before it's executed on the server. How can I do this?

**Comment by yajra** [comment]
Maybe try following this [demo](https://datatables.yajrabox.com/eloquent/advance-filter) for ref. You can do your own custom search using `filter` api. Thanks!
