### ISSUE TITLE
How to display dynamic column names

### ISSUE THREAD

**Issue by AshishGupta001** [yajra/laravel-datatables#914]
I am looking for ways to display list of columns which are dynamic based on user inputs. For example - My data is list of employees and their salary past several fiscal years. Now I want to provide a multi select dropdown for end user to select list of years for which this data is being displayed. 

I am not able to figure out how to form list of column which is dynamic.

**Rendering the table. How to pass list of columns?**
```php
        <thead>
            <tr text-align="center">
                <th text-align="center">Staff Name</th>
                <th text-align="center">FY #1</th>
                <th text-align="center">FY #2</th>
                <th text-align="center">FY #3</th>
                <th text-align="center">FY #4</th>
                <th text-align="center">FY #5</th>
                <th text-align="center">FY #6</th>
                <th text-align="center">FY #7</th>
            </tr>
        </thead>
```
**JS function**
```php
            columns: [
                { data: 'staff_name', name: 'staff_name' },
                { data: 'FY_1', name: 'FY', searchable: false, orderable: false },
                { data: 'FY_2', name: 'FY', searchable: false, orderable: false },
                { data: 'FY_3', name: 'FY', searchable: false, orderable: false },
                { data: 'FY_4', name: 'FY', searchable: false, orderable: false },
                { data: 'FY_5', name: 'FY', searchable: false, orderable: false },
                { data: 'FY_6', name: 'FY', searchable: false, orderable: false },
                { data: 'FY_7', name: 'FY', searchable: false, orderable: false },
            ]
```

**Comment by yajra** [comment]
Sorry but I think this is on javascript side and is out of scope of the project. Maybe try asking on datatables.net forum?

**Comment by marcelogarbin** [comment]
@AshishGupta001 Do you do this?

**Comment by deanlaw** [comment]
@AshishGupta001 I just had to do the exact same thing. What I found to work best was to remove the column definitions from your HTML (including the entire thead tags) and then define the column headings from within the columns section of your JS.

    columns: [
                { data: 'staff_name', name: 'staff_name' title:'Staff Name' },
                { data: 'FY_1', name: 'FY', searchable: false, orderable: false, title: 'FY 1' },
                { data: 'FY_2', name: 'FY', searchable: false, orderable: false, title: 'FY 2' },
                { data: 'FY_3', name: 'FY', searchable: false, orderable: false, title: 'FY 3' },
                { data: 'FY_4', name: 'FY', searchable: false, orderable: false, title: 'FY 4' },
                { data: 'FY_5', name: 'FY', searchable: false, orderable: false, title: 'FY 5' },
                { data: 'FY_6', name: 'FY', searchable: false, orderable: false, title: 'FY 6' },
                { data: 'FY_7', name: 'FY', searchable: false, orderable: false, title: 'FY 7' },
                { data: 'dynamic_field_1', name: 'FY', searchable: false, orderable: false, title: 'dynamic_title_1' },
                { data: 'dynamic_field_2', name: 'FY', searchable: false, orderable: false, title: 'dynamic_title_2' },
            ]
