### ISSUE TITLE
Ajax error occurs randomly

### ISSUE THREAD

**Issue by ezekel** [yajra/laravel-datatables#915]
Hi @yajra i just want to ask why is it i will get ajax error randomly when i navigate back and forth to my page...is this due to network?

Thank you in advance

**Comment by yajra** [comment]
I think this is an environment issue. This mostly occurs when using `php artisan serve`.

**Comment by ezekel** [comment]
@yajra ,
 
by the way I am working in localhost

Is this okay in my database.php

```
 'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

    ],

```


and my .env

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=mydb
DB_USERNAME=root
DB_PASSWORD=

```

**Comment by yajra** [comment]
Oops sorry, it's not the `.env` I am referring to. I was referring to your dev environment. I suggest you use valet, homestead, wamp, xamp, etc. ^_^

**Comment by ezekel** [comment]
@yajra .,

I am using wamp

**Comment by yajra** [comment]
@ezekel, I'm not really sure on how to fix this one but based on [previous duplicate issues](https://github.com/yajra/laravel-datatables/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20artisan%20serve), the intermittent error was due to `artisan serve` or the dev environment you are using. Maybe try updating your settings as a production configurations?
