### ISSUE TITLE
Possible to sort by dynamic column? 

### ISSUE THREAD

**Issue by mattpramschufer** [yajra/laravel-datatables#917]
I have the following code 
```php
            $dt = Datatables::of($users);
            $dt->addColumn('completed_runs', function ($row) {
                $totalRescues = $row->closedRuns()->get()->count();
                return $totalRescues;
            });
            
            return $dt->make(true);
```

On my front end I want to be able to sort by `completed_runs`  however it keeps throwing the database error that the column completed_runs does not exist.  That is correct it is not a database table it comes from the addColumn function.

I tried looking at the API documentation but that goes to a 404 page.  I tried looking at the addFilter documentation but that just goes to the homepage of the wiki.  So I am stumped here on if this is possible.

**Comment by yajra** [comment]
I think it's possible as long as you can it do it on the SQL level. You need to use [orderColumn](https://datatables.yajrabox.com/eloquent/order-column) for this to work.
