### ISSUE TITLE
Filter input how to set old data value.

### ISSUE THREAD

**Issue by mariani10** [yajra/laravel-datatables#923]
### Summary of problem or feature request

Hi, i have a form with some inputs that acts as filters (query scopes) but need to repopulate the search(filters) inputs with the old value when a page reload or go to details and back... i set stateSave to true, but dont work.. need help. Thanks in advance @yajra 

### System details

I think that this information is not relevant to solve my problem.

**Comment by yajra** [comment]
@mariani10 I think you need to manually store and populate your form by hooking on the `state` events. See snippet below on how I used to do that way back on my old project. Try searching on datatables.net for more ref on state api.

On DT init:
```js
    "stateSaveParams": function (settings, d) {
            var data = $('select, input', form).serializeArray();
            $.each(data, function(i, o) {
                d[o.name] = o.value;
            });
        },
```

After DT init:

```js
    var state = oTable.state.loaded();
    if ( state ) {
        form.find('[name=first_name]').val(state.first_name);
        form.find('[name=last_name]').val(state.last_name);
        form.find('[name=address]').val(state.address);
        form.find('[name=city]').val(state.city);
        form.find('[name=email]').val(state.email);
        oTable.draw(false);
    }
```
