### ISSUE TITLE
order yajra datatables by added column

### ISSUE THREAD

**Issue by ahmadbadpey** [yajra/laravel-datatables#924]
I want to Order a table by added column that checks whether current user readed a row (based on their roles) or no and I want to show unread rows on top always. 

This is a part of laravel snippet codes:

    $conversations =
    	Conversation::
    	with('latestQuestion');
    
    $datatable = 
    app('datatables')->of($conversations)
    		->addColumn('checkbox', '<input type="checkbox" name="item_id[]">')
    		->addColumn('ordering',function ($conversation){
    			if ($this->user->hasRole('expert') and
    			(is_null($conversation->read_at) or $conversation->hasUnAnsweredQuestion())) {
    				return 1;
    			}
    			return 0;
    })
    ->make(true);

And javascript codes :

     $('#allQuestionsTable').DataTable({
    					    processing: true,
    					    serverSide: true,
    					    "bSort": false,
    					    "responsive": true,
                            "order": [[1, "desc" ]],
                            columns: [
                                {data: 'checkbox', "width": "20px", 'searchable': false, 'orderable': false},
                                {data: 'ordering', 'visible': false}
    
                            ]
    				    });

As you can see I used `"order": [[1, "desc" ]],` to set ordering based on second column by it does not work properly and rows shown in order that inserted in database table.

What I do to solve that?

**Comment by yajra** [comment]
By default, ordering and searching is not working on added columns. You need to use [`orderColumn` api](https://yajrabox.com/docs/laravel-datatables/6.0/order-column) or set the name of the column to be used when doing this actions via js.

Something like below, which will trigger ordering based on read_at column. 
```js
{data: 'ordering', 'visible': false, name: 'read_at'}
```
