### ISSUE TITLE
can I use dropdown menu in each row 

### ISSUE THREAD

**Issue by Mahdi-Sahib** [yajra/laravel-datatables#925]
public function CustomersTableOneAjax()
    {
        $users = Customer::select('customers.*');
        return Datatables::of($users)
            ->addColumn('action', function ($customer) {
                return '           
           
                                     <div class="btn-group">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Action <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="{{ route(\'admin.customer.show\' , $customer->id) }}">View</a></li>
                                            <li><a href="{{ route(\'admin.customer.edit\' , $customer->id) }}">Edit</a></li>
                                            <li><a href="">Config</a></li>
                                            <li><a href="{{ route(\'admin.customer.destroy\' , $customer->id) }}">Delete</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="#">Invoice</a></li>
                                            <li><a href="#">Refill</a></li>
                                        </ul>
                                    </div>
                                     
                                     
                                     ';
            })
            ->make(true);

**Comment by Mahdi-Sahib** [comment]
try that but dropdown menu it doesn't work

**Comment by yajra** [comment]
@Mahdi-Sahib I tried something like this before and it works. You may have to listen on `dt.draw` event and initialize the dropdown script when table is drawn.

**Comment by 05K4R1N** [comment]
i didn't understand... i used your example and it worked for me :o

**Comment by Mahdi-Sahib** [comment]
@05K4R1N yes its work now but with old v I didn't work.

**Comment by 05K4R1N** [comment]
OH! i was worried for a second jejeje... well.. May I know what Laravel version you were working on ?

**Comment by mck776775** [comment]
it's not working on me only showing the Action button and caret but no dropdown... im using laravel 5.6

**Comment by abidra** [comment]
not work on laravel 5.6 😔

**Comment by HassanElshazlyEida** [comment]
Try this

       ```
      public function html()
                {
                    return $this->builder()
                                ->setTableId('adminpostsdatatable-table')
                                ->columns($this->getColumns())
                                ->minifiedAjax()
                                ->dom('Bfrtip')
                                ->orderBy(1, 'desc')   
                                ->parameters([
                                'buttons'      => 
                                 [
                                    [
                                        'text' =>'<i class="fa fa-eye"></i> ' . 'My custom button',
                                        'className' => 'My custom class'
                                    ],
                                     'csv',
                                     'excel'
                                 ],
                                  ]);
                }
```
  and if you want dropdown collection button 
```

                            'buttons'      => 
                               [
                                 "extend"=> 'collection',
                                 "text"=> 'My Collection button',
                                 "buttons" => 
                                     [ 
                                       'csv',
                                       'excel',
                                        [                
                                            [
                                               'text' =>'<i class="fa fa-eye"></i> ' . 'My custom button',
                                               'className' => 'My custom class'
                                            ],
                                         ] 
                                     ]
                               ],
```
