### ISSUE TITLE
All of the data retrieve without using length in Soft delete Model

### ISSUE THREAD

**Issue by pyaesone17** [yajra/laravel-datatables#928]
### Summary of problem or feature request

All of the data retrieve in onlyTrashed() method . It does not limit the items.
It works well when using withTrashed(). 

### Code snippet of problem

```php
        
        $shops = Shop::select('shops.*')->onlyTrashed();        

        return Datatables::of($shops)->make(true);
```

### System details

- PHP 7.1
- PHP Version
- Laravel 5.2
- Datatable version 6.22.5

**Comment by yajra** [comment]
We have support for [withTrashed](https://yajrabox.com/docs/laravel-datatables/6.0/with-trashed) but I think we don't handle yet `onlyTrashed`. Tagging for enhancements. Thanks for reporting.
