### ISSUE TITLE
Silent conversion from camelCase into snake_case using Eloquent's belongsTo

### ISSUE THREAD

**Issue by AdrienPoupa** [yajra/laravel-datatables#929]
Hello,

I was trying to do a one-to-one relationship using Eloquent.

It seems that there is a silent transition from camelCase:

`$query = MyModel::with('otherModel')->select([myModel.*]);`

to snake_case when trying to access the data with JS:

```
    protected function getColumns()
    {
        return [
            'other_model.title' => ['data' => 'other_model.titre', 'name' => 'title'],
```

I was trying to do a otherModel.title which obviously didn't work.

Maybe this should be mentionned in the docs somewhere?

**Comment by yajra** [comment]
@AdrienPoupa, yes. Laravel automatically converts model attributes from camelCase to snake_case when returning the response. I think it's a standard behavior of Eloquent which dataTables inherits.
