### ISSUE TITLE
Html builder with custom class column content

### ISSUE THREAD

**Issue by mattevolve** [yajra/laravel-datatables#93]
I'm trying to minimise a standard set of controls e.g. edit button within an action column and call the method from a custom class I have created to work with the datatables html builder. However, I'm not having much luck... I'm essentially trying to reference this:

```php
->addColumn('action', function($user) {
    return '<a href="'.route('admin.user.edit', ['id' => $user->id]).'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
})
```

as:

```php
            return Datatables::of($this->userRepository->all(['id', 'username', 'email', 'created_at', 'updated_at']))
                ->addActionEditButton('admin.user.edit', $id)
                ->make(true);
```

I tend to receive a fatal error exception referencing 'Call to a member function getQuery() on null' or 'Undefined variable $id'.

Any ideas on how to do this?

**Comment by omar-faruk-sust** [comment]
try like this 

$users = $users = User::select(['id','name','email','created_at','updated_at']);

return Datatables::of($users)
	
	->addColumn('action', function ($user) {
		$actions = '';
		$actions .= '  <a href="admin/user/edit' . $user->id . '/edit" class="btn btn-xs btn-primary"><i class="fa fa-pencil-square-o"></i> Edit</a>';
		return $actions;
	})
	->make(true);

**Comment by mattevolve** [comment]
Thanks @omar-faruk-sust for your reply but perhaps I didn't explain it well enough. The first code above works but I want to do the bottom code by using a class like this:

```php
abstract class BaseDatatable extends Builder {
    
    public function addActionEditButton($route, $id)
    {
        return '<a href="'.route($route, ['id' => $id]).'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> Edit</a>';
    }

}
```

**Comment by yajra** [comment]
@mattevolve, Builder and Datatables are different class. Extending the builder wont add a `addActionEditButton` on Datatables instance. You should use what @omar-faruk-sust have suggested. 

On the other hand, you may extend the EloquentEngine and other engines to add your desired functionality. Datatables class is just a factory for those engines.
