### ISSUE TITLE
How to implement complex headers (service approach)?

### ISSUE THREAD

**Issue by alfa6661** [yajra/laravel-datatables#930]
### Implement complex headers (rowspan and colspan)

I'm using datatables as a service and it works as expected.
however, i need to implement complex headers on the table, something like https://datatables.net/examples/basic_init/complex_header.html.

is it possible to implement the complex headers when using datatables as a service?

**Comment by yajra** [comment]
Yes, but you need to overwrite the print template to match your needs. You can do this by setting `$printPreview = 'path.to.view'` property and then copying the contents of `print.blade.php` to your new print preview template.

**Comment by yajra** [comment]
For the table, you may need to write the html manually and just set the table id to `dataTableBuilder`.

**Comment by alfa6661** [comment]
i don't think so.
i'm not talking about the print preview, the print view only used when someone clicked on the print button. no?

i just tried to trace all the code and i found the html builder.
i think we use the html builder to generate the table.

https://github.com/yajra/laravel-datatables/blob/6.0/src/Html/Builder.php#L538-L542

so my first thought i need to create my own builder.

am i wrong?

**Comment by yajra** [comment]
@alfa6661 Oh yes, I think you can extend the builder class to handle the complex headers. But you would still need to update the print view if you want the printable version identical. 

BTW, If ever you manage to create a complex header using PHP, then a PR is gladly welcomed. Thanks!

**Comment by alfa6661** [comment]
still trying to find the best way to handle this.
will submit a PR when it does.

btw, thanks for your response.
i will close this issue.
