### ISSUE TITLE
Action column header language

### ISSUE THREAD

**Issue by n6ither** [yajra/laravel-datatables#936]
Hi, is it possible to change "Action" by the same word in another language? I'm using [this file](http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json).
Thanks for your time!

- Operating System: Ubuntu 16.04
- PHP Version: 7
- Laravel Version: 5.3
- Laravel-Datatables Version:   "yajra/laravel-datatables-oracle": "~6.0"

**Comment by yajra** [comment]
Are you using the service approach? If yes, you can pass the title attribute:

```php
->addAction(['title' => 'acción'])
```

**Comment by n6ither** [comment]
@yajra Thank you very much, it works!
