### ISSUE TITLE
How to Filter Raw Query with DataTables as a Service

### ISSUE THREAD

**Issue by benlwong** [yajra/laravel-datatables#939]
I am using the DataTables as a Service and in the query() method, I am trying to use a RAW query because of its complexity. I followed the suggestions in Issue #239:  

```php
public function query() {

   $registrations = DB::table(DB::raw("(select distinct(ev.id) as event_vendor_id, ...

   return $this->applyScopes($registrations);
}
```

However, in the ajax() method when I try to implement a custom filter as below, I get back the same error - "SQLSTATE[42000]: Syntax error or access violation: 1583 Incorrect parameters in the call to native function 'lower' (SQL: select count(*) as aggregate from (select * from (select distinct(ev.id) as event_vendor_id, ...

```php
public function ajax() {

   $registrations = $this->query();

   return $this->datatables
      ::of($registrations)
      ->filterColumn('event_vendor_status_datetime', function ($query, $keyword) {
         $query->whereRaw("DATE_FORMAT(ev.event_vendor_status_datetime,'%m/%d/%Y') like ?", ["%$keyword%"]);
      })
      ->make(true);
}
```

I also tried changing the query to the following: 

```php
public function query() {
   
   $registrations = DB::select("select distinct(ev.id) as event_vendor_id, ...

   $registrations = collect($registrations);
   
   return $this->applyScopes($registrations);   
}
``` 

In this case, the filter does not return an error but also doesn't do any filtering at all.

**Comment by yajra** [comment]
Maybe try creating a view instead that encapsulates your complex query? Then use it like a normal table? And btw, please avoid using `::of` on service approach as it's a bit buggy.

```php
public function query() {

   $registrations = DB::table('your_view_name')

   return $this->applyScopes($registrations);
}

...

return $this->datatables->queryBuilder($registrations)->make(true);
```

**Comment by benlwong** [comment]
Is using a view the only solution? Also, just trying to understand why it doesn't work the way it is. Is it because DB::select returns the result set right away in the query() method whereas DB::table returns a Builder? Thanks for all your help!

**Comment by yajra** [comment]
You can still use a raw query if you prefer like the demo on [unions](https://datatables.yajrabox.com/fluent/union).

I think `DB::select` returns a collection if using 5.3 so the correct engine would be `->collection($data)`

For `DB::table` it returns, a `Query\Builder` instance.
