### ISSUE TITLE
Error in display row number

### ISSUE THREAD

**Issue by iambillywilly** [yajra/laravel-datatables#940]
`return Datatables::of(User::query())->make(true);` work fine for me, but when I add `->addIndexColumn()`  so `return Datatables::of(User::query())->addIndexColumn()->make(true);` get an exception `Call to undefined method Yajra\Datatables\Engines\BaseEngine::addindexcolumn()`.

**Comment by yajra** [comment]
@iambillywilly please make sure that you are using the latest version. `addIndexColumn` was added maybe around `v6.10++`.

**Comment by iambillywilly** [comment]
Now I updated to latest version, it works! Thanks, @yajra!
