### ISSUE TITLE
Datatables and document.ready()

### ISSUE THREAD

**Issue by n6ither** [yajra/laravel-datatables#941]
Hello.
I have a view using a datatable, it works perfect but when I add the following script at the bottom of the page, the datatable only load its header. How I can proceed here?
What do I want to do? After I add or update a "foo", I want to go back to the index view and show a success or error alert.

```
<script>
   $(document).ready(function() {
      console.log('Document is ready but there's no data on the datatable :(  ');
   });
</script>
```

Thank you for your time!

**Comment by yajra** [comment]
Have you tried inspecting the console for any errors? Use firebug of chrome dev tools. This is mostly due to a javascript error.

**Comment by n6ither** [comment]
I don't know, I wasn't able to find anything yet. I also was playing with jquery.bootgrid and found the same behaviour..

**Comment by yajra** [comment]
Still having this issue? Try adding the script directly on your master layout. You might be pushing on sections that is not being rendered properly. Thanks!
