### ISSUE TITLE
Collection Order (Case sensitive) problem

### ISSUE THREAD

**Issue by ruverd** [yajra/laravel-datatables#945]
I've tried order a column (string) but a have some values in upper case and some others in lower case. For example:

COLUMN
ABC
BCD
ZXY
aaa
bbb
zzz

There are any way to do this not be case sensitive like this:
COLUMN
aaa
ABC
bbb
BCD
zzz
ZXY

**Comment by ruverd** [comment]
Ok but if I have many columns and I don't know the name of the current column!
Do you have idea how can I resolve this?

**Comment by yajra** [comment]
Use [orderColumns](https://yajrabox.com/docs/laravel-datatables/6.0/order-columns) for multiple columns. But dynamic column name is not supported. You may have to find a way to extract those column names and pass it on the api.

**Comment by ruverd** [comment]
I'm sorry to insiste but are you know if it works with collections?
Because I'm trying and the result doesn't change.

**Comment by ruverd** [comment]
Do you know if have any way to overwrite in class Collection the method sortBy or pass a different value in $options? I need change the $options to SORT_NATURAL | SORT_FLAG_CASE!

`$descending ? arsort($results, SORT_NATURAL | SORT_FLAG_CASE)
                    : asort($results, SORT_NATURAL | SORT_FLAG_CASE);`

This could follow the config:  
`'case_insensitive' => true`

**Comment by yajra** [comment]
@ruverd I think orderColumn/s is not applicable on collection.

For collection, I think what you can use is the `order` callback:

```php
->order(function(CollectionEngine $engine) {
    // override the code default below
    foreach ($this->request->orderableColumns() as $orderable) {
            $column           = $this->getColumnName($orderable['column']);
            $this->collection = $this->collection->sortBy(
                function ($row) use ($column) {
                    $data = $this->serialize($row);

                    return Arr::get($data, $column);
                }
            );

            if ($orderable['direction'] == 'desc') {
                $this->collection = $this->collection->reverse();
            }
        }
})

**Comment by yajra** [comment]
> This could follow the config: 'case_insensitive' => true

Hmm, looking at Collection, I think we should add `SORT_FLAG_CASE` given the config?

```php
public function sortBy($callback, $options = SORT_REGULAR, $descending = false)
```

**Comment by yajra** [comment]
@ruverd can you please test #989 if fixes this? Thanks!

**Comment by yajra** [comment]
I added another PR for v6.0? Anyways, what version are you using? Thanks!

**Comment by yajra** [comment]
FYI: Have tested my own PR and it's not working. Working on some feature test to back this up.

**Comment by yajra** [comment]
Patch release on v7.1.4 and v6.24.4 🚀
