### ISSUE TITLE
Does not render HTML

### ISSUE THREAD

**Issue by FaZeRs** [yajra/laravel-datatables#949]
I'm using Laravel Datatables 7, but my table is not rendering HTML code. It was rendering HTML before, but when I updated to new Laravel DataTables to 7 from 6, it stopped rendering HTML in column. http://prntscr.com/e11n84

This is with Laravel DataTables 6 - http://prntscr.com/e11ph0

**Comment by yajra** [comment]
Results are escaped by default on v7. Haven't documented all the breaking change yet but change log should provide some clues. Thanks!

- Issue #909
- https://github.com/yajra/laravel-datatables/blob/7.0/CHANGELOG.md#v700---01-27-2017

**Comment by brian2694** [comment]
How can I fix the same issue but in Service?

**Comment by yajra** [comment]
@brian2694 use the new method `->rawColumns(['column_with_html'])`.

**Comment by newbie2005** [comment]
I have similar problem, any example to use the rawColumns ?

**Comment by FaZeRs** [comment]
return Datatables::of($this->users->getForDataTable($request->get('status'), $request->get('trashed')))
            ->editColumn('confirmed', function ($user) {
                return $user->confirmed_label;
            })
            ->addColumn('roles', function ($user) {
                return $user->roles->count() ?
                    implode('<br/>', $user->roles->pluck('name')->toArray()) :
                    trans('labels.general.none');
            })
            ->addColumn('actions', function ($user) {
               return $user->action_buttons;
            })
            ->rawColumns(['actions', 'confirmed'])
            ->withTrashed()
            ->make(true);

**Comment by newbie2005** [comment]
Good!

**Comment by divdax** [comment]
Maybe allow
```
->rawColumns(['*'])
```
?

**Comment by yajra** [comment]
@divdax maybe try using `->escapeColumns([])` to achieve the same result.

**Comment by YounesseSoft** [comment]
thank u very much this is very helpful

**Comment by nara-l** [comment]
->escapeColumns([]) worked for me. rawColumns('column_with_html') did not.
Using laravel 5.5 with  "yajra/laravel-datatables-oracle": "~8.0"

**Comment by deanlaw** [comment]
Nara, rawColumns takes an array argument, so it should be rawColumns(['column_with_html'])

**Comment by digitlimit** [comment]
If wish to render a view in a column you could do this:

      ->editColumn('action', function(User $u){
                    return view('users.action-btns', ['id'=>$u->id])->render();
      })

**Comment by tonihidayt** [comment]
i have same problem, and my friend tell me to add ->escapeColumns([]), and its works.

`if ($request->ajax()) {
            $ajax = Datatables::of(Admin::query())->escapeColumns([])->make(true);
            return $ajax;
        }

        $dataTable = $htmlBuilder
            ->addColumn(['data' => 'admin_id', 'name' => 'admin_id', 'class' => 'id-column', 'title' => 'Id', 'searchable' => false, 'render' => function () {
                $editUrl = route('backend.staff.edit', '');
                return "function(data,type,full,meta){ return '<a href=" . $editUrl . "/'+data+'>'+data+'</a>'; }";
            }])
            ->addColumn(['data' => 'username', 'name' => 'username', 'title' => trans('default.name'), 'class' => 'name-column', 'render' => function () {
                $editUrl = route('backend.staff.edit', '');
                return "function(data,type,full,meta){ return '<a href=" . $editUrl . "/'+full.admin_id+'>'+data+'</a>'; }";
            }])
            ->addColumn(['data' => 'ip_address', 'name' => 'ip_address', 'title' => trans('default.ip_address')])
            ->addColumn(['data' => 'last_login', 'name' => 'last_login', 'title' => trans('default.last_login'), 'class' => 'date-column', 'searchable' => false])
            ->addColumn(['data' => 'html_status', 'name' => 'html_status', 'title' => trans('default.status'), 'class' => 'status-column', 'searchable' => false])
            ->addAction(['data' => 'action_button', 'name' => 'action', 'title' => trans('default.action'), 'class' => 'actions-column'])`

**Comment by judgej** [comment]
@tonihidayt Do you understand what `escapeColumns([])` does? It looks to me like it disabled ALL HTML escaping by setting NO columns to apply HTML escaping. This may be an easy way to fix one problem, that then leads you into a dangerous situation in other circumstances.

**Comment by Artistan** [comment]
I agree with @judgej . I do not want to risk escaping ALL columns, but the one that I want to make raw is an accessor and does not produce a raw result with `$datatables->rawColumns(['full_link']);`

**Comment by sarizu99** [comment]
@yajra Please update this documentation

https://datatables.yajrabox.com/eloquent/add-edit-remove-column
