### ISSUE TITLE
[7.0] No available engine for Illuminate\Database\Eloquent\Relations\BelongsToMany

### ISSUE THREAD

**Issue by Raikia** [yajra/laravel-datatables#950]
### Summary of problem or feature request

When using a BelongsToMany relation, I get a "No available engine for Illuminate\Database\Eloquent\Relations\BelongsToMany" error.

![img](https://vgy.me/wcH4D7.png)

### Code snippet of problem

Datatables code that works:

```php
 return Datatables::of(TargetList::findOrFail($id)->users())->make(true);
```

I get this error with:

```php
public function users()
    {
        return $this->belongsToMany('App\TargetUser');
    }
```

I don't get an error if I change that to:

```php
public function users()
    {
        $ids = \DB::table('target_list_target_user')->where('target_list_id', '=', $this->id)->pluck('target_user_id');
        return TargetUser::where('hidden', false)->whereIn('id', $ids);
    }
```

### System details

Ubuntu 16.04, PHP 7.0, Laravel 5.4, Laravel-Datatables 7.0

**Comment by yajra** [comment]
Can you try adding this line on `datatables.php` config and check if it works?

```php
'builders' => [
    Illuminate\Database\Eloquent\Relations\BelongsToMany::class => 'eloquent',
    ...
]
```

**Comment by yajra** [comment]
Or maybe lets use the `Relation` class so that it will handle any relations?

Can you please also try removing:
```php
Illuminate\Database\Eloquent\Relations\BelongsToMany::class => 'eloquent',
``` 
and replace it with 
```php
Illuminate\Database\Eloquent\Relations\Relation::class => 'eloquent',
```

**Comment by yajra** [comment]
Please update to v7.0.2 and force publish the config. Thanks!
