### ISSUE TITLE
Add a column to global search

### ISSUE THREAD

**Issue by AdrienPoupa** [yajra/laravel-datatables#951]
Hello,

I want to add a column that is not displayed to the search query.

I am using DataTables as a service. The following does not work as it should:

```
    public function query()
    {
        $query = SiteContenu::with('menu')->select('siteContenu.*');

        if ($this->request()->has(('search.value'))) {
            $query->where('siteContenu.contenu', 'like', "%{$this->request()->input('search.value')}%");
        }

        return $this->applyScopes($query);
    }
```

As you may have guessed, I want the "contenu" field, not displayed in the datatable, to be searched like this: LIKE %keyword%.

However, if I search a string that is in a "contenu" field, DataTables fails to retrieve it. What am I doing wrong?

Thank you.

**Comment by yajra** [comment]
Maybe try adding it on your javascript but set it as `visible: false`:

```php
protected function getColumn() {
    return [
        'id', 
        '...', 
        'contenu' => ['visible' => false]
    ];
}
```

**Comment by AdrienPoupa** [comment]
Thanks. It works this way but I would have preferred to do it the proper way.
