### ISSUE TITLE
[7.0] Error "No available engine for Illuminate\Database\Eloquent\Collection"

### ISSUE THREAD

**Issue by newbie2005** [yajra/laravel-datatables#954]
When use yajra / laravel-datatables in Laravel 5.4, it shown

Exception in Datatables.php line 61:
No available engine for Illuminate\Database\Eloquent\Collection

**Comment by yajra** [comment]
I think you need to republish the config. Please see [upgrade docs](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade) on to migrate to L5.4. Thanks!

**Comment by yajra** [comment]
Fixed on v7.1.0. Thanks for reporting!

**Comment by newbie2005** [comment]
Good

**Comment by raphox** [comment]
Remember to execute the command `php artisan config:cache`.
The same in https://github.com/yajra/laravel-datatables/issues/950
