### ISSUE TITLE
[7.0] Class not found

### ISSUE THREAD

**Issue by n6ither** [yajra/laravel-datatables#955]
### Summary of problem or feature request

Class 'Yajra\Datatables\Services\DataTable' not found

### Code snippet of problem

I just followed the instructions

1. composer require yajra/laravel-datatables-oracle:7.*
2. Yajra\Datatables\DatatablesServiceProvider::class
3. artisan vendor:publish --tag=datatables

### System details
- Operating System Kubuntu 16.04
- PHP Version 7
- Laravel Version 5.4
- Laravel-Datatables Version 7

**Comment by n6ither** [comment]
6.0 works, 7.0 nope

**Comment by sakibulalam** [comment]
Same here. Was there a breaking change?

**Comment by yajra** [comment]
Yes, there was a breaking change. Please see [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade). Thanks!

**Comment by n6ither** [comment]
You were right, thank you!

**Comment by anik587** [comment]
Don't use DataTablesServiceProvider. Instead of that use dataTablesServiceProvider 
In your Service providers Yajra\Datatables\datatablesServiceProvider::class
then publish 'php artisan vendor:publish --tag=datatables'
