### ISSUE TITLE
Search across multiple databases...

### ISSUE THREAD

**Issue by n1smo** [yajra/laravel-datatables#956]
### Summary of problem or feature request

Hi,

i have to work with two databases in my application. One general sqlite database (A) that holds all the app information, an orders table and more. In addition i have one access database (B) with a list of customers. This is no problem in laravel and i can even join tables from two databases with eloquent as long as as i tell laravel in the model declaration that it needs to look for my customers in the another database.

Im building my datables with ajax like this:

``` 
     $elo= Order::all->with('customer');
     $dt= Datatables::eloquent($model)
            ->editColumn('customer_id', function(Order $order) {
                      return strtoupper($order->customer->name);
             })
      ->make(true);
      return $dt;
```

customer_id is the foreign key of the customer id in my orders table.
So far everything works fine.

But the problem is when i try to use the global search field.

The app is looking for the customers table in my default app database (A).

This is the important part of the query:

`(select count(1) from "customer" where "orders"."customer_id" = "customer"."ID" and LOWER("customer"."name") LIKE %s%) >= 1 
`

I have no idea how to fix this with  a filter...

Can anyone help?

- Operating System Windows Server / IIS
- PHP Version 7.0
- Laravel Version 5.3
- Laravel-Datatables Version 6.0

**Comment by yajra** [comment]
Sorry but this is not supported. The query generated by the package assumes that all tables have direct link/access to each other. You can only display eager loaded relations but you cannot search on it. Thanks!
