### ISSUE TITLE
Website SSL-Cert

### ISSUE THREAD

**Issue by divdax** [yajra/laravel-datatables#959]
### Please Check SSL-Cert
![bildschirmfoto 2017-02-01 um 08 34 16](https://cloud.githubusercontent.com/assets/1456739/22498561/760496f6-e859-11e6-9fdd-0e312d467a8c.png)

**Comment by yajra** [comment]
@divdax yeah, my friend who sponsored hosting my site still not responding on my request to renew the SSL (letsencrypt). Don't have permission to do so. Have disabled force SSL atm. Thanks!

**Comment by yajra** [comment]
SSL is fixed. Thanks!
