### ISSUE TITLE
[7.0] Laravel 5.4: Call to undefined method Illuminate\Database\Query\Builder::getQualifiedOtherKeyName()

### ISSUE THREAD

**Issue by AdrienPoupa** [yajra/laravel-datatables#963]
### Summary of problem or feature request

On v6, using Laravel 5.4, I get this error on some datatables. I'm using DataTables as a service.
![2017-02-02_210319](https://cloud.githubusercontent.com/assets/15086425/22566183/3b27d812-e98b-11e6-912d-ca503fbe74c2.png)

This works fine using Laravel 5.3.

Code:

```
    public function query()
    {
        $query = SiteTheme::with('menu')->has('menu')->select('siteTheme.*');

        return $this->applyScopes($query);
    }
```

Edit: it seems to work on v7. Maybe you should specify somewhere that v6 is incompatible with Laravel 5.4?

**Comment by yajra** [comment]
@AdrienPoupa what is the relation type of your menu? Laravel made some breaking changes by renaming the methods on relationships. Might have miss this one. Thanks!

**Comment by AdrienPoupa** [comment]
It is a belongs to.

**Comment by yajra** [comment]
>Edit: it seems to work on v7. Maybe you should specify somewhere that v6 is incompatible with Laravel 5.4?

Didn't see the edit part. Yes, I have locked the latest version of v6 to support Laravel 5.0 - 5.3 only. But lower version of v6 is still installable on 5.4. Will update the docs. Thanks!

**Comment by rumes** [comment]
@yajra I get the same error as Adrien Poupa getting anyway to work around this?.

**Comment by yajra** [comment]
@rumes you need to use v7 to fix this issue. See [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade) for details.
