### ISSUE TITLE
[7.0] Single quote converted to &#39;

### ISSUE THREAD

**Issue by snagytx** [yajra/laravel-datatables#966]
### Summary of problem or feature request

The single quotes in the result are converted to &#39;

The first print_r() shows the single quote OK while the 2nd one shows it as convested to &#39;
### Code snippet of problem

```php
        $data =  FieldOption::where('id', '>', 0 )->get();
        print_r($data);
        $data = Datatables::of($data)->make();
        print_r($data);
        return $data;
```

### System details

- Operating System W10
- PHP Version 7.0.13
- Laravel Version 5.4
- Laravel-Datatables Version 7.1(latest)

**Comment by yajra** [comment]
Please see #949. Thanks!
