### ISSUE TITLE
[7.0] Error render laravel 5.4 with datatable editColumn :(

### ISSUE THREAD

**Issue by sintaxsysdev** [yajra/laravel-datatables#967]
Error render laravel 5.4 with datatable editColumn :(

```
->addColumn('action', function ($location) {
                return '<button type="button" value="' . $location->id . '" onclick="confirmDelete(this);" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small modal</button>';
            })
```

`->editColumn('location_name', function ($location) {
                return '<b>a</b>';
            })
`

`"data":[{"id":"1","location_name":"&lt;b&gt;a&lt;\/b&gt;","location_description":"","location_status":"1","created_at":"&lt;b&gt;Feb 3, 2017&lt;\/b&gt;","action":"<button type=\"button\" value=\"1\" onclick=\"confirmDelete(this);\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\".bs-example-modal-sm\">Small modal<\/button>"},`

addColumn is OK

editColumn fail :(

**Comment by yajra** [comment]
Please see #949. Thanks!

**Comment by sintaxsysdev** [comment]
Thank you ;)
