### ISSUE TITLE
[6.0] Error in Html Builder Table documention

### ISSUE THREAD

**Issue by RuiGau** [yajra/laravel-datatables#971]
### Summary of problem or feature request

I think there is an error in documention at this page : https://yajrabox.com/docs/laravel-datatables/master/html-builder-table

The footer parameter (true) is in the attributes array parameter and should be outside, after the closing square bracket.

### Code snippet of problem

Indeed, the line 

{!! $html->table(['class' => 'table table-bordered', true]) !!}

should be 

{!! $html->table(['class' => 'table table-bordered'], true) !!}

### System details

- Operating System
- PHP Version 7.1.1
- Laravel Version 5.4
- Laravel-Datatables Version 6.0

**Comment by yajra** [comment]
Thanks for reporting. The docs repo is located [here](https://github.com/yajra/laravel-datatables-docs) in case you want to contribute. Will update it later today. Thanks!

**Comment by yajra** [comment]
PR Merged. Thanks!
