### ISSUE TITLE
how to print ?

### ISSUE THREAD

**Issue by vipin733** [yajra/laravel-datatables#973]
I'm following this https://datatables.yajrabox.com/service tutorial but I dont  where i get print button like for view table I have `  public function indexing()
   {

        $courses = DB::table("courses")->pluck("name","id");

         return view('search.printing_databable',compact('courses'));
   }

   public function ajaxindexing(Request $request)
   {

     $courses = $request->course;
     if ($courses) {
        $students = Student::with('courses')->where('course_id',$courses)->select('students.*');
     }else {
      $students = Student::with('courses')->select('students.*');
     }

     return Datatables::of($students)
            ->addColumn('action', function ($student) {
                return '<a href="/student/'.$student->reg_no.'" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> View Profile</a>';

        })->make(true);
   }`
but where I should use print button 
help thanks

**Comment by vipin733** [comment]
its solved

**Comment by yajra** [comment]
Glad you sorted this out! Thanks!
