### ISSUE TITLE
Pass Variable

### ISSUE THREAD

**Issue by alederzz** [yajra/laravel-datatables#976]
Hello, how can I pass a ROUTE variable to the DATATABLES query method?

#### Route FIle
```php
Route::get('demo/{id}', 'PersonsController@demo');
```

#### Datatables Class
```php
public function query()
    {
        $query = Person::with('user')
->where('person_type_id',$this->request()->get('id') )//not work
->select('persons.*');

        return $this->applyScopes($query);
    }
```
What would be the possible solution ?, I have been following the tutorials but still I am new in Laravel

### System details

- Laravel Version 5.1

**Comment by minedun6** [comment]
I think it's already asked.
U can add a public method on your "Custom"DataTable class like this

`
class CustomDataTable extends DataTable {
protected $model;
public function forModel($model){
     $this->model = $model;
}

}
`
and you need to use it like this
`return $dataTable->forClient($client)->render('backend.clients.users.index', compact('client'));`

**Comment by alederzz** [comment]
@minedun6 Thanks.
I suspected that the solution was here [#697](https://github.com/yajra/laravel-datatables/issues/697) , but I did not understand much, with your solution I was cleared everything.  
#### Datatable Class
```php
/*
     * Custom method
     */
    protected $person_type;
    public function personType($id){
        $this->person_type = $id;
        return $this;
    }

/*
* Query Method
*/

public function query()
    {
        $query = Person::with('user')->where('person_type_id',$this->person_type )->select('persons.*');
        return $this->applyScopes($query);
    }
```

#### Controller
```php
 public function demo(PersonsDataTable $dataTable, $id){
        return $dataTable->personType($id)
            ->render('demo', compact('id'));
    }
```
