### ISSUE TITLE
No available engine for Jenssegers\Mongodb\Eloquent\Builder

### ISSUE THREAD

**Issue by c0h1b4** [yajra/laravel-datatables#977]
### Summary of problem or feature request

I use Laravel 5.4 with the Jenssegers Mongodb Eloquent Model.

### Code snippet of problem

vendor/yajra/laravel-datatables-oracle/src/Datatables.php

Exception
No available engine for Jenssegers\Mongodb\Eloquent\Builder

        $builders   = $config->get('datatables.builders');
        $builder    = get_class($object);
 
        if (array_key_exists($builder, $builders)) {
            $engine = $builders[$builder];
            $class  = $engines[$engine];
 
            return new $class($object, $datatables->getRequest());
        }
 
        throw new \Exception('No available engine for ' . $builder);
    }

### System details

- Ubuntu server
- PHP 7.1
- Laravel Version 5.4
- Laravel-Datatables Version 7.0.2

**Comment by yajra** [comment]
Please update to the latest version.

**Comment by johanvanhelden** [comment]
I am having the same issue, but 7.1 is not a valid option for me. Because some dependencies are not stable. Could you fix this @yajra ?

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yajra/laravel-datatables-oracle v7.1.0 requires orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - yajra/laravel-datatables-oracle v7.1.1 requires orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - yajra/laravel-datatables-oracle v7.1.2 requires orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - orchestra/testbench v3.4.4 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.3 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.2 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.1 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.0 requires orchestra/database ~3.4.0 -> satisfiable by orchestra/database[3.4.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for yajra/laravel-datatables-oracle ^7.1 -> satisfiable by yajra/laravel-datatables-oracle[v7.1.0, v7.1.1, v7.1.2].
`

**Comment by yajra** [comment]
Hmm that's weird. Can you try deleting your `vendor` folder and `composer.lock` file and try to reinstall the packages? Works well on my side.

What is your minimum stability?

**Comment by yajra** [comment]
See this issue https://github.com/orchestral/testbench/issues/147. It seems like you need to use `--prefer-stable`

On my project, I use:

```
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
```

**Comment by johanvanhelden** [comment]
@yajra 
Thank you for your response.

Our minimum stability policy is `stable`. The "fix" would indeed be to lower it to allow `dev` packages and prefer stable, but this is not really an option for us.

**Comment by yajra** [comment]
I see, I migrated my tests suites using orchestral and was not aware that it somewhat uses `dev` stability. It is possible to use `--no-dev` flag? I think we should open an issue on testbench package?

**Comment by johanvanhelden** [comment]
Maybe you could set the "minimum-stability" for laravel-datatables to "stable", in order to prevent these things in the future? I think it would always be better to rely on stable packages.

And then, in the composer.json set "orchestra/testbench" to use a stable version?

(and make sure everything still works ofcourse - if that is the case, release it is the next version, 7.1.4?)

**Comment by yajra** [comment]
Oh you're right. The package composer still uses "dev"... Will update and release a patch. That might be causing the issue. Thanks!

**Comment by johanvanhelden** [comment]
Yep, and if you set it to stable, and replace the 3.4 version of the testbench package with a stable version, I am pretty sure everything is solved.

And the stable change should prevent you from using any dev version in the future.

**Comment by yajra** [comment]
Released on v7.1.3. 🚀

**Comment by johanvanhelden** [comment]
@yajra 

I did a fresh composer install with ^7.1, but it is still complaining about ` orchestra/testbench` 3.4. I made sure to clear the cache.

**Comment by yajra** [comment]
packagist might still be propagating.. Try again now. I just updated my installs.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing yajra/laravel-datatables-oracle (v7.1.2)
  - Installing yajra/laravel-datatables-oracle (v7.1.3)
    Downloading: 100%

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
```

**Comment by johanvanhelden** [comment]
It does find v7.1.3:

```
Problem 1
    - yajra/laravel-datatables-oracle v7.1.0 requires orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - yajra/laravel-datatables-oracle v7.1.1 requires orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - yajra/laravel-datatables-oracle v7.1.2 requires orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - yajra/laravel-datatables-oracle v7.1.3 requires orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - orchestra/testbench v3.4.4 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.3 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.2 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.1 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.0 requires orchestra/database ~3.4.0 -> satisfiable by orchestra/database[3.4.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for yajra/laravel-datatables-oracle ^7.1 -> satisfiable by yajra/laravel-datatables-oracle[v7.1.0, v7.1.1, v7.1.2, v7.1.3].

````

I did notice the composer.json still uses 3.4, should this not be lowered?
https://github.com/yajra/laravel-datatables/blob/7.0/composer.json#L23

**Comment by yajra** [comment]
`^3.4` is the stable version of testbench for Laravel 5.4.

This is my composer:
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-snappy": "^0.3.2",
        "dompdf/dompdf": "^0.6.2",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "league/fractal": "^0.15.0",
        "yajra/laravel-datatables-buttons": "1.*",
        "yajra/laravel-datatables-html": "1.*",
        "yajra/laravel-datatables-oracle": "7.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "stable"
}
```

**Comment by johanvanhelden** [comment]
@yajra 

Yep, got it fixed now. Must have been cache than. Anyhow, thank you very much! :+1:

**Comment by c0h1b4** [comment]
I know that this is closed, but I am having a hard time on installing the composer package. It is soooo frustrating. I just can't install the orchestra/testbench with the Laravel 5.4 that is required by the yajra/laravel-datatables 😢

#composer require orchestra/testbench --prefer-lowest --prefer-stable

Using version ^3.4 for orchestra/testbench
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - orchestra/testbench v3.4.4 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2, v3.2.3] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.3 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2, v3.2.3] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.2 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2, v3.2.3] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.1 requires symfony/css-selector ~3.2.0 -> satisfiable by symfony/css-selector[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2, v3.2.3] but these conflict with your requirements or minimum-stability.
    - orchestra/testbench v3.4.0 requires orchestra/database ~3.4.0 -> satisfiable by orchestra/database[3.4.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for orchestra/testbench ^3.4 -> satisfiable by orchestra/testbench[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].


Installation failed, reverting ./composer.json to its original content.

**Comment by yajra** [comment]
@c0h1b4 I made some changes, can you please try v7.2.1 if it's working now? thanks!
