### ISSUE TITLE
Will DataTables as a Service make it back to 7.0?

### ISSUE THREAD

**Issue by Konafets** [yajra/laravel-datatables#980]
### Summary of problem or feature request

I want to use DataTables as a Service with Laraval 5.4 and laravel-datatables 7.0, but the Service is not available anymore. 

### System details

- Operating System: OSX
- PHP Version: 7.0
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.0

**Comment by alfa6661** [comment]
There was a breaking change on 7.0
See [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade).

**Comment by Konafets** [comment]
Thank you @alfa6661 for pointing me to the right direction.
