### ISSUE TITLE
The composer require is different from the documentation

### ISSUE THREAD

**Issue by yuzrieSiddiq** [yajra/laravel-datatables#983]
### Summary of problem or feature request
The composer command is wrong/not working. But really the fix is just to follow the one on the documentation so its nothing big. But still it may confuse new people.

The one on the readme is:
```
composer require yajra/laravel-datatables-oracle:7.*
```
The one on the documentation is:
```
composer require yajra/laravel-datatables-oracle:^7.0
```

### Code snippet of problem
```
$ composer require yajra/laravel-datatables-oracle:7.*                                                         1 ↵
zsh: no matches found: yajra/laravel-datatables-oracle:7.*
```
### System details

- Operating System: Manjaro Linux
- PHP Version: PHP 7.1.1
- Laravel Version: 5.4
- Laravel-Datatables Version

Regards,
Yuz

**Comment by yajra** [comment]
@yuzrieSiddiq it's basically the same and use it depending on your preference as far as I know.

^7.0 - at least 7.0++
7.* - any version from 7.0++.

>zsh: no matches found: yajra/laravel-datatables-oracle:7.*

Add a double quote on the version.
```
composer require yajra/laravel-datatables-oracle:"7.*"
```

**Comment by yajra** [comment]
Read me updated. Thanks!
