### ISSUE TITLE
Problem sorting numerical columns

### ISSUE THREAD

**Issue by cydrobolt** [yajra/laravel-datatables#984]
### Summary of problem or feature request

When I try to sort numerical columns, Laravel DataTables seems to sort them alphabetically rather than numerically. For instance, "2" is considered larger than "12" because the first digit in "2" is larger than the first digit in "12". 

Instead, 12 should be treated as larger than 2 because it is a larger number.

I've attempted to add the "html-num" type to DataTables on the client-side, but there seems to be no effect on the server-side sorting.

### Code snippet of problem

https://github.com/cydrobolt/polr/blob/master/app/Http/Controllers/AdminPaginationController.php#L116

### System details

- Operating System: Fedora 25
- PHP Version: 5.6
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.0

cydrobolt/polr#294

**Comment by yajra** [comment]
Sorting is done via SQL side. Are you using integer type on clicks column?

**Comment by yajra** [comment]
You are using string on your clicks column which in turns sql treat it as string.

https://github.com/cydrobolt/polr/blob/master/database/migrations/2015_11_04_015813_create_link_table.php#L26

**Comment by cydrobolt** [comment]
Oh, shoot. You're right. Thank you for pointing that out.
