### ISSUE TITLE
v7 - Class 'Yajra\Datatables\Services\DataTable' not found

### ISSUE THREAD

**Issue by aborigines** [yajra/laravel-datatables#986]
v7 - Class 'Yajra\Datatables\Services\DataTable' not found

How to solve it ?

Thank you.

**Comment by yajra** [comment]
See [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade) please. Thanks!

**Comment by aborigines** [comment]
im implement class as a service as like v.6 , on source code v.7 i don't see a service .

ref. https://datatables.yajrabox.com/service

**Comment by yajra** [comment]
Have you seen the upgrade guide? You need to install `laravel-datatables-buttons` plugin to use it on v7. Duplicate of #980. Thanks!

**Comment by MATOVURONALD** [comment]
FatalThrowableError in ProviderRepository.php line 208:
Class 'Yajra\Datatables\DatatablesServiceProvider' not found
i have checked the upgrade guide and installed the yajra package but it cannot find the datatable service provider

**Comment by yajra** [comment]
@MATOVURONALD namespace were updated from`Datatables` to `DataTables`. You are still using the older version.

**Comment by andrefrd** [comment]
I only got it working without the service provider class.

Removing the line "Yajra\DataTables\DataTablesServiceProvider::class" from config/app.php

**Comment by vahidalvandi** [comment]
show in v8.4

`Class 'Yajra\Datatables\Services\DataTable' not found
`
