### ISSUE TITLE
[7.0] Laravel 5.4 READ ME FIRST 

### ISSUE THREAD

**Issue by yajra** [yajra/laravel-datatables#988]
Version 7.0 have breaking changes. Please see [upgrade guide](https://yajrabox.com/docs/laravel-datatables/7.0/upgrade) first before posting an issue. Thanks!

**Comment by duongtdvn** [comment]
@yajra Is it possible to use version 7.0 for laravel 5.3?

**Comment by yajra** [comment]
@duongtdvn unfortunately no. There are breaking changes from Laravel 5.3 to 5.4 that affects the package.

**Comment by yajra** [comment]
Note added on read me.
