### ISSUE TITLE
Column is searchable, still when I am searching it doesn't show result from that column

### ISSUE THREAD

**Issue by tarunhere** [yajra/laravel-datatables#99]
![screenshot from 2015-07-03 15 14 15](https://cloud.githubusercontent.com/assets/4122496/8496919/810b9792-2196-11e5-99f3-d84f45474643.png)

In the screen-shot above, the column 3 (Brand_name) shows as searchable=true, but when I search from the box, it doesn't shows result from that column. 
In brand_name, i have comma separated values eg, brand 1, brand 2, brand 3
Other all columns are filtered from search box, except this? 
can anyone help me with this issue? have anyone faced this??

**Comment by yajra** [comment]
I think you need to use `filterColumn` function here since global search will make your query looks something like `brand like '%brand1,brand2%'`. You need to explode the value and then use something like:
```php
->filterColumn('brand', 'whereIn', explode(',', $brands));
```

**Comment by tarunhere** [comment]
I am trying to set filter column but I didn't got success. I also want to setup a drop-down filter column for isMember where I have three conditions (Member type 1, member type 2, member type 3), this will be at the bottom of the datatables. I tried many option, but I failed to get select filter at the bottom/top!

One more thing, when I loaded this DataTables directly with foreach loop, that branding filter is working but when I am using it with AJAX, it filter every column except brands!!
I'll try your solution.

**Comment by yajra** [comment]
Yes, it will filter all columns by default as it is the default behavior. I also suggest you use the `filter()` function and just write your custom query. See this for ref: http://datatables.yajrabox.com/eloquent/custom-filter

**Comment by tarunhere** [comment]
I am getting error of variable not found!!
Lets first discuss, point 1) In the DataTables listing, I am unable to search for Brand Names, which are comma separated valued. Other fields are searchable but not brands!?
As per your guide, I added the `->filterColumn('brand_name', 'whereIn', explode(',', $brand_name))` 
where 'brand_name' is my DB column name. I am getting error of $brand_name not found!!!

point 2) In the User DB table, I want to add the drop down select box, to search for i)registered Users ii)anonymous users and iii) silver_member user. Where I select from dropdown and whole table got filtered based on selected value. I have to use filter there??

**Comment by tarunhere** [comment]
ok. Point 1) resolved. I donno what error was, in the js I had written `serverSide` and I noticed that when searching the count in bottom was not updating. So I changed that into `serverside`, small case and it worked. All columns are searchable now.
Now I am working on Point 2. To keep a select box on search bar.

**Comment by tarunhere** [comment]
When I changed the `serverSide` into `serverside`, I realized that my datasets are loading at a time and it is taking 46 seconds to load. 
This means actual keyword is `serverSide`. When this is set true, only 10 records are loaded as expected.
![datatables](https://cloud.githubusercontent.com/assets/4122496/8588434/231a7a86-2628-11e5-9066-6ee708ed836b.png)

But when I use serverSide and use the search feature, the records are filtered but, the filter count shows total count, not the filtered count?!! Due to this, blank paginations are created !!
In pic attached you can see, I had searched for keyword "konn" but 

`recordsTotal  379`
`recordsFiltered  379`
both are same!!

**Comment by yajra** [comment]
@tarunhere , `serverSide: true` is the correct syntax. Just to be clear, what version of the package are you using? Maybe try updating to the latest release (v5.5.5 atm). And test again. As per the demo link I provided, all is working fine.

<img width="1004" alt="screen shot 2015-07-09 at 2 25 28 pm" src="https://cloud.githubusercontent.com/assets/2687997/8589227/710310d2-2646-11e5-968f-1fe0b70cd88e.png">

**Comment by tarunhere** [comment]
Datatable "version": "v5.5.1" is the one, I am using. I had checked this, I don't know, why for search its not working!!

**Comment by yajra** [comment]
Please update to version `v5.5.5`, there were several fixes done and may have fixed this issue. You can see [change log](https://github.com/yajra/laravel-datatables/blob/master/change-log.md) for details.

**Comment by yajra** [comment]
I think your issue was fixed on v5.5.3

```php
v5.5.3

- Fix total filtered records count when overriding global search.
- Fix implementation of PR #95 on Collection Engine.
```

**Comment by tarunhere** [comment]
sorry to ask you this lame question?? but, how to upgrade package from composer??
I tried to change the version ~5.0 in composer.json to 5.5.5 but its not taking it.

**Comment by tarunhere** [comment]
i changed it ~5.5, but it says,nothing to update. Any ideas here!!

**Comment by yajra** [comment]
on your terminal, change dir to you project folder then run `composer update`.

```
cd /path/to/laravel
composer update
```

**Comment by tarunhere** [comment]
with composer update, all my dependencies will be upgraded. I just want to update this datatables.

**Comment by yajra** [comment]
if you want to update just the package. run `composer update yajra/laravel-datatables-oracle`

**Comment by tarunhere** [comment]
ok.
I was trying this 
`composer update "yajra/laravel-datatables-oracle":"~5.0"`
my bad.

OH YES!! Its working now. 
Thanks Yajra for all your help and this awesome plugin too.
