### ISSUE TITLE
[6.x] Custom sorting query with the Eloquent engine

### ISSUE THREAD

**Issue by johanvanhelden** [yajra/laravel-datatables#991]
We have a datatable with a column that consists of 2 columns merged together, a first name and last name into a full name column.

We tried using the Collection engine, that works like a charm, but the table is very large and has many relations, so the performance is terrible. So we switched to the Eloquent engine. This one is much faster, but broke the "$appends" column.

I've added the proper filter method and searching works perfectly:
```
->filterColumn('contact_fullname', function ($query, $keyword) {
    $query->whereRaw(
        "CONCAT(contact_first_name,' ',contact_last_name)  like ?",
        [
            "%{$keyword}%",
        ]
    );
})
```

Sorting however is not working. It is still looking for a column that does not exist:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'orders.contact_fullname' in 'where clause'
```

How can I fix the sorting without either splitting the column in 2 columns or switching back to a Collection table?

### System details
- OS: Ubuntu 16.04 LTS
- PHP: 5.6-fpm
- Laravel: 5.2.45
- Laravel-Datatables: 6.24.2

**Comment by yajra** [comment]
For sorting, you can use [orderColumn](https://yajrabox.com/docs/laravel-datatables/6.0/order-column) api.

**Comment by blueminded** [comment]
Hi, There.

Related to this I'm having a problem trying to sort a table that has a relationship with itself. I explain:

I have model called User and has this relationship (a simple child - parent relation)

```
public function asesor()
{
         return $this->hasOne('App\User', 'id', 'created_by');
 }
```

So in the Datatable search I have:

```
$users = User::with('role')->with('asesor')->where('role_id',3);

        return Datatables::eloquent($users)
        ->editColumn('asesor.name', function(User $user) {
                    return $user->asesor ? $user->asesor->fullName : 'Ninguno';
                })
        ->editColumn('city', function(User $user) {
                    return $user->city.', '.$user->department;
                })
        ->editColumn('created_at', function(User $user) {
                    return Date::parse($user->created_at)->toFormattedDateString();
                })
         ->addColumn('action', 'participants.datatables.actions')
         
         ->make(true);
```

and the js:
```
var $table = $('#participants-datatable').DataTable({
	        processing: true,
	        serverSide: true,
	        ajax: $('#participants-datatable').data('url'),
	        bStateSave: false, // save datatable state(pagination, sort, etc) in cookie.
	        columns: [
	            { data: 'name', name: 'name' },
	            { data: 'last_name', name: 'last_name' },
	            { data: 'document', name: 'document' },
	            { data: 'city', name: 'city' },
	            {data: 'asesor.name', name: 'asesor.name',searchable: false},
	            { data: 'created_at', name: 'created_at',searchable: false },
	            {data: 'action', name: 'action', orderable: false, searchable: false}
	        ],
	        "initComplete": function() {
	            var $searchInput = $('div.dataTables_filter input');

	            $searchInput.unbind();

	            var searchWait = 0;
    			var searchWaitInterval;

	            $searchInput.bind('keyup', function(e) {
	            	var item = $(this);
			        searchWait = 0;
			        if(!searchWaitInterval){
				        searchWaitInterval = setInterval(function(){
				            if(searchWait >= 4){
				                clearInterval(searchWaitInterval);
				                searchWaitInterval = '';
				                searchTerm = $(item).val();
				                $table.search(searchTerm).draw(); // change to new api
				                searchWait = 0;
				            }
				            searchWait++;
				        },300);
			        } 
	            });
	        }
    	});
```

Everthing works great except when I try to order by the 'asesor', so when I click the sort button an error come out:
`SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'users' (SQL: select * from `users` left join `users` on `users`.`id` = `users`.`created_by` where `role_id` = 3 order by `users`.`name` asc limit 50 offset 0)`

I'm trying to set an alias to the join table but I can't find any solution neither via Laravel Model or Datatable component to modify in some way the query, for now the only thing I can do to disable ordering for that column.

Anyone who can shine me a little there.

Thanks in advance.
