### ISSUE TITLE
Ordering by nested relationships with Eloquent as a Service

### ISSUE THREAD

**Issue by rossbearman** [yajra/laravel-datatables#993]
I'm using the service based DataTables, and pulling the data directly from Eloquent. The only problem I'm having is with an orders table that displays the name of a customer, via the relationship Order > Customer > User.

Everything displays correctly, but if you try to search, or sort by the customer's name, it doesn't work correctly. Sort seems to be fairly random, and searching doesn't return any results regardless of what's entered.

I'm pretty sure I should be using orderColumn() to configure how this column should be ordered, but everything I've tried so far results in errors because it doesn't recognise the `customer.user.name` notation.

## Simplified Schema

```
order
-----
id
customer_id

customer
--------
id
user_id

user
----
name
```

## OrderDataTable.php (skeleton code)
```php
    public function ajax()
    {
        return $this->datatables
            ->eloquent($this->query())
            ->editColumn('subtotal', '{{ $subtotal->asCurrency() }}')
            ->editColumn('tax', '{{ $tax->asCurrency() }}')
            ->editColumn('total', '{{ $total->asCurrency() }}')
            ->editColumn('created_at', function($row) { return $row->created_at->diffForHumans(); })
            ->addColumn('action', function($order) {
                return $this->renderActions($order->id, 'admin.orders.show');
            })
            ->make(true);
    }

    public function query()
    {
        $orders = Order::query()->with(['payment', 'customer.user'])->select(['orders.id', 'orders.subtotal', 'orders.tax', 'orders.total', 'orders.customer_id', 'orders.created_at']);

        return $this->applyScopes($orders);
    }

    protected function getColumns()
    {
        return [
            'id',
            [
                "data" => "customer.user.name",
                "title" => "Customer",
            ],
            'subtotal',
            'tax',
            'total',
            [
                "data" => "payment.type",
                "title" => "Payment",
            ],
            [
                "data" => "created_at",
                "title" => "Ordered",
            ],
        ];
    }
```

### System details

- Operating System Ubuntu 14.04.4 LTS 
- PHP Version 7.0.5-3
- Laravel Version 5.3.29
- Laravel-Datatables: 6.24.2

**Comment by yajra** [comment]
I think the problem here is on your column declaration. Try adding the name:

```php
'id',
            [
                "data" => "customer.user.name",
                "name" => "customer.user.name",
                "title" => "Customer",
            ],
```

**Comment by yajra** [comment]
BTW, please note that sorting on nested relationship is not yet stable and have a pending PR that I need to review further. #850 #965

**Comment by rossbearman** [comment]
If I set the name to `customer.user.name` I get the following error when sorting (it still displays the names correctly):

`Call to undefined relationship [customer.user] on model [App\Models\Orders\Order].`

Is this likely a problem with sorting nested relationships?

**Comment by yajra** [comment]
@rossbearman yes, that's the problem with nested relationship. Sorting is currently supported only on the first level of relationship.

**Comment by rossbearman** [comment]
Okay, thanks for the clarification and all your work on the module. I'll subscribe to those PRs for updates.
