### ISSUE TITLE
Artisan datatables:make model used

### ISSUE THREAD

**Issue by carlos-mora** [yajra/laravel-datatables#994]
When using 

```
php artisan datatables:make Article
```
the class is built using User as a model. It makes an

```php
// at line 5...
use App\User;

// at line 30
 public function query()
    {
        $query = User::query();
...
```
It should be 
```php
// at line 5...
use App\Article;

// at line 30
 public function query()
    {
        $query = Article::query();
...
```
Am I wrong?

Regards and thanks for a great job.

**Comment by yajra** [comment]
You need to add `--model` option.

```php
php artisan datatables:make Article --model
```

**Comment by carlos-mora** [comment]
Great! Thanks! Anyway, may be using the name also as the model would be better than using an arbitrary model name like 'User'. Or using an invalid name that raises an exception like <YourModelHere> that would draw the programmers attention. 
Best regards and thanks for your great work and support.
