### ISSUE TITLE
Version 7 - Error in documentation

### ISSUE THREAD

**Issue by jim1506** [yajra/laravel-datatables#999]
### Summary of problem or feature request

In the documentation for version 7 you have:

Register Yajra\Datatables\ButtonsServiceProder on 'config/app.php' and publish config.

This should of course be 

Yajra\Datatables\ButtonsServiceProvider::class,

### System details

- Operating System
- PHP Version
- Laravel Version
- Laravel-Datatables Version

**Comment by yajra** [comment]
Fixed, thanks for reporting! BTW, this is the [docs repo](https://github.com/yajra/laravel-datatables-docs) in case you want to contribute. 👍
